### ISSUE TITLE
Migrate to k18s jenkins

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#10]
Code for cluster is in [infra/jenkins-cluster](../tree/master/infra/jenkins-cluster)

Jenkins can build our images using the cluster definition.

We _can not_ run those images with mounted directories. It is not possible to know exact physical location to send to docker daemon from within the container. Further investigation is needed

**Comment by inferno-chromium** [comment]
Oliver, is this even applicable after GKE ?

**Comment by oliverchang** [comment]
Nothing left to do here.
