### ISSUE TITLE
Trouble with RSS growth only visible under ASan - but not a leak?

### ISSUE THREAD

**Issue by randombit** [google/oss-fuzz#1001]
I recently made a change to one of the Botan fuzzers (asn1) to improve coverage. Unfortunately it seems to have some kind of leak that causes crashes after a while

https://oss-fuzz.com/v2/testcase-detail/6622180981866496

If I build the fuzzer locally with ASan, I can reproduce the leak; RSS seems to grow without bounds. However I can't find the problem. Setting `ASAN_OPTIONS=detect_leaks=1` and running with a limit (`-max_runs=10000`) the RSS grows, but Asan reports nothing at exit. If I disable ASan (just using `-fcoverage-sanitizer`) the leak disappears. I also ran the same fuzzer (with a test main that reads stdin) against the generated corpus under valgrind, no leaks are reported.

At this point I have no way forward besides reverting the fuzzer code, so I'm posting this in the hopes @kcc or anyone else has ideas for debugging this.

I don't think this is related to #977.

**Comment by randombit** [comment]
Closing, seems to be fixed now. On Dec 9th, max RSS was 1755 MB. On Dec 11th, max RSS was 502 MB, and it's been under 500 MB since then. Also, on Dec 9th the corpus was 8337 (8 MB), following day 2338 (778 KB). Coverage %s have remained steady.

I just double checked git history and there were *no* changes to the fuzz target or the code it calls between Nov 15th and Dec 23rd. So I assume something changed on OSS-Fuzz side that made it better.

**Comment by kcc** [comment]
Yes, there were changes in both asan and libFuzzer to reduce memory consumption. 
(and there was a problem in libFuzzer that caused the corpus to grow too much; the problem was fixed around that time). 
Thanks for checking!
