### ISSUE TITLE
Duplicate "the the" in various messages and comments

### ISSUE THREAD

**Issue by stweil** [google/oss-fuzz#10018]
OSS-Fuzz creates issues and e-mails with text like this: "Friendly reminder that the the build is still failing."

In addition, the sources contain similar duplications:
```
infra/base-images/base-builder/detect_repo.py:"""Module to get the the name of a git repo containing a specific commit
infra/cifuzz/filestore/github_actions/__init__.py:    # Not applicable as the the entire corpus is uploaded under a single
projects/binutils/fuzz_disas_ext.c:  // depending on the the target.
```

**Comment by oliverchang** [comment]
Thanks, these are not very high priority because they're code comments and not user facing. Feel free to send a PR to fix them if you would like.
