### ISSUE TITLE
Wget2 Build is broken

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#1002]
https://oss-fuzz-build-logs.storage.googleapis.com/log-f771f8fe-f1a3-40f6-be34-df690386a65a.txt

These look like the relevant lines:
Step #3: /tmp/wget_options_fuzzer-4386d4.o: In function `LLVMFuzzerTestOneInput':
Step #3: /src/wget2/fuzz/wget_options_fuzzer.c:106: undefined reference to `enable_testing()'
Step #3: ../src/options.o: In function `prompt_for_password':
Step #3: /src/wget2/src/options.c:2318: undefined reference to `is_testing'
Step #3: ../src/options.o: In function `run_use_askpass':
Step #3: /src/wget2/src/options.c:2358: undefined reference to `is_testing'
Step #3: /src/wget2/src/options.c:2369: undefined reference to `is_testing'
Step #3: clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
Step #3: Makefile:2736: recipe for target 'oss-fuzz' failed
Step #3: make: *** [oss-fuzz] Error 1

**Comment by jonathanmetzman** [comment]
@rockdaboot can you please take a look?

**Comment by rockdaboot** [comment]
Thanks, just pushed a fix.

**Comment by inferno-chromium** [comment]
@rockdaboot - build is still broken.

Step #3: /tmp/wget_options_fuzzer-4e64c6.o: In function `LLVMFuzzerTestOneInput':
Step #3: /src/wget2/fuzz/wget_options_fuzzer.c:106: undefined reference to `enable_testing()'
Step #3: clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
Step #3: Makefile:2736: recipe for target 'oss-fuzz' failed
Step #3: make: *** [oss-fuzz] Error 1
Finished Step #3

https://oss-fuzz-build-logs.storage.googleapis.com/log-726fa9e8-cf56-4cdb-8778-7fabe02e38eb.txt

**Comment by rockdaboot** [comment]
Now finally fixed. Thanks for reporting.
