### ISSUE TITLE
Wireshark Build is Broken

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#1003]
Logs here:
https://oss-fuzz-build-logs.storage.googleapis.com/log-15db43c4-ed7e-40d8-8b78-7858257573bc.txt

These look like the relevant lines:

Step #3: + clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ /work/fuzzshark_ip.o -o /workspace/out/address/fuzzshark_ip -lFuzzingEngine -L/work/install/lib -lwireshark -lwiretap -lwsutil -Wl,-Bstatic -lglib-2.0 -pthread -lpcre -lgcrypt -lgpg-error -lz -Wl,-Bdynamic
Step #3: /work/fuzzshark_ip.o: In function `fuzz_init':
Step #3: /src/wireshark/tools/oss-fuzzshark/fuzzshark.c:213: undefined reference to `register_all_protocols'
Step #3: /src/wireshark/tools/oss-fuzzshark/fuzzshark.c:213: undefined reference to `register_all_protocol_handoffs'
Step #3: clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
Finished Step #3
ERROR
ERROR: build step "gcr.io/oss-fuzz/wireshark" failed: exit status 1

**Comment by jonathanmetzman** [comment]
@jwzawadzki  can you please take a look?

**Comment by jwzawadzki** [comment]
Should be fixed by https://code.wireshark.org/review/24523/
