### ISSUE TITLE
 fixed crash not updated as such in bugs.chromium.org

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#1007]
Like #973 https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4149 links to https://oss-fuzz.com/v2/testcase-detail/4565444439572480 and oss-fuzz reports it as Fixed but https://oss-fuzz.com/v2/testcase-detail/4565444439572480 doesn't link back to https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4149 which remains open

I wonder if this happens if an issue is fixed while oss-fuzz is still processing the test case with the previous build.

**Comment by Dor1s** [comment]
Weird. I checked the logs in case anyone manually unattached bug from the testcase, but haven't found any records.

@inferno-chromium @oliverchang  I wonder if it's possible that in `def file_issue` function `issue.save()` works successfully, but testcase update fails after that. Maybe race condition with another job?

**Comment by Pro** [comment]
I have the same problem here:

It shows still open here: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4183

While https://oss-fuzz.com/v2/testcase-detail/4952054897311744?noredirect=1 shows it is fixed

**Comment by dtardon** [comment]
Same here: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3631 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3670

**Comment by inferno-chromium** [comment]
This happened to a bunch of testcases, i think this time i have a clue to the race condition update. For these testcase i would have to manually fix the mappings.

5611874281324544 2017-11-25 12:54:37.956540 asan_chakra
5407414712008704 2017-11-24 09:36:29.812530 libfuzzer_msan_unrar
4952054897311744 2017-11-12 03:31:21.129930 libfuzzer_asan_open62541
4565444439572480 2017-11-09 15:37:07.192440 libfuzzer_ubsan_libreoffice
6686971150729216 2017-10-18 08:54:00.431440 libfuzzer_asan_dlplibs
4526360841158656 2017-10-16 01:28:37.357250 libfuzzer_asan_llvm
4594987875434496 2017-10-13 21:13:01.596550 libfuzzer_asan_llvm
6715693878738944 2017-10-13 08:27:52.753200 libfuzzer_asan_dlplibs
4838858534420480 2017-10-11 05:35:52.887810 afl_asan_libpng
6200421431377920 2017-08-17 02:29:42.818378 libfuzzer_asan_fuchsia_fidl

**Comment by inferno-chromium** [comment]
I did another speculative fix, also added more logging for future debugging. Also, ran a script to update all current testcase mappings, so i see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4149 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3670 getting marked verified now.

**Comment by inferno-chromium** [comment]
Not seeing this anymore.

**Comment by inferno-chromium** [comment]
Just saw this on internal chromium - https://clusterfuzz.com/v2/testcase-detail/5275556227842048

**Comment by inferno-chromium** [comment]
Landed another fix, but last comment was clusterfuzz internal (chromium) only, and does not impact oss-fuzz, also confirmed no new oss-fuzz testcases impacted. Closing.
