### ISSUE TITLE
Bug "fixed" by renaming some variables

### ISSUE THREAD

**Issue by bboreham** [google/oss-fuzz#10097]
Hi, I am a maintainer on Prometheus, and we received this report:

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57502#c3

I can't see the details of the original problem (permissions?), but the fix is said to be this commit:
https://github.com/prometheus/prometheus/commit/7309ac272195cb856b879306d6a27af7641d3346

which is just renaming a few things.

If you can point me at some mechanism to resolve my permissions issue, I would be happy to look at the underlying issue.

**Comment by jonathanmetzman** [comment]
What's your email address, I can give you permission

**Comment by Alan32Liu** [comment]
I hope that works and we can close this now?

**Comment by jonathanmetzman** [comment]
Reopen this if it still doesn't work
