### ISSUE TITLE
About oss-fuzz-base/base-builder version

### ISSUE THREAD

**Issue by featherL** [google/oss-fuzz#10094]
I'm trying to add a fuzzbench whose llvm pass implementation is based on llvm-11, but the llvm version of base-builder:latest can't compile the pass.
So I would like to know which version of oss-fuzz-base/base-builder uses llvm-11. please let me know, thanks!

**Comment by jonathanmetzman** [comment]
We don't version the images so you will need to do some searching
You may be able to figure this out by looking back at https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-clang/checkout_build_install_llvm.sh check it's history and see if there's a point in time when llvm 11 is being used. Or search the repo for hints.
then go to https://console.cloud.google.com/gcr/images/oss-fuzz-base/GLOBAL/base-builder and look for an image for around the date you have in mind and try it out. Good luck!

**Comment by jonathanmetzman** [comment]
Although I'm guessing an image that old will have a lot of trouble building benchmarks

**Comment by featherL** [comment]
> We don't version the images so you will need to do some searching
> You may be able to figure this out by looking back at https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-clang/checkout_build_install_llvm.sh check it's history and see if there's a point in time when llvm 11 is being used. Or search the repo for hints.
> then go to https://console.cloud.google.com/gcr/images/oss-fuzz-base/GLOBAL/base-builder and look for an image for around the date you have in mind and try it out. Good luck!

I am trying so. Thanks a lot😀
