### ISSUE TITLE
-fsanitize=memory mbrtowc is broken:

### ISSUE THREAD

**Issue by zoulasc** [google/oss-fuzz#1009]
The sanitizer version of mbrtowc is broken:

[11:53am] 24>cat t.c
#include <wchar.h>
#include <stdio.h>
#include <string.h>

int
main(void)
{
        mbstate_t state;
        char c = '\377';
        wchar_t wc;
        size_t rv;

        memset(&state, 0, sizeof(state));

        rv = mbrtowc(&wc, &c, 1, &state);
        printf("%#zx\n", rv);
        return 0;
}
[11:53am] 25>clang -fPIE -pie -fsanitize=memory t.c
[11:53am] 26>./a.out 
0xffffffff
[11:53am] 27>clang -fPIE -pie  t.c
[11:53am] 28>./a.out
0xffffffffffffffff

**Comment by eugenis** [comment]
Ouch. The bug has been there for >4 years.
