### ISSUE TITLE
increase time limit for lcms fuzzer

### ISSUE THREAD

**Issue by kcwu** [google/oss-fuzz#101]
How do chrome fuzzer determine the time limit? Could you help adjust the time limit of oss-fuzz's  lcms_cms_transform_fuzzer similar to chrome's pdf_codec_icc_fuzzer ? I guess lcms_cms_transform_fuzzer exercise less paths than pdf_codec_icc_fuzzer because its time limit is much shorter.

**Comment by kcc** [comment]
libFuzzer's default timeout is 1200 seconds per input. 
Are we setting a different timeout for oss-fuzz?

**Comment by inferno-chromium** [comment]
Yes, we have lower 25 sec per test timeout for both Chromium and OSSFuzz

**Comment by kcwu** [comment]
Ah, i found `-timeout=25` from chromium's log. 

The problem is, chromium's cluster-fuzz only listed crashes and no hangs. But https://clusterfuzz-external.appspot.com/crashstats?fuzzer_name=libFuzzer_lcms_cms_transform_fuzzer&job_type=All&date_start=2016-11-28&date_end=2016-11-28&security_flag=Both listed many hangs. So I was confused.

**Comment by inferno-chromium** [comment]
We detect hangs on both cluster-fuzz and clusterfuzz-external. Which fuzzer on cluster-fuzz were you comparing against, since i don't see lcms_cms_transform_fuzzer on cluster-fuzz and these hangs are all dependent on type of fuzz target.

**Comment by kcwu** [comment]
I'm referring to pdf_codec_icc_fuzzer. It is very similar to lcms_cms_transform_fuzzer.
