### ISSUE TITLE
u-root: compile_native_go_fuzzer fails in ipxe pkg

### ISSUE THREAD

**Issue by RiSKeD** [google/oss-fuzz#10112]
```
+ compile_native_go_fuzzer /src/u-root/pkg/boot/netboot/ipxe FuzzParseIpxeConfig fuzz_ipxe_parse_config
# ipxe
./ipxe.go:99:23: c.schemes.LazyFetchWithoutCache undefined (type curl.Schemes has no field or method LazyFetchWithoutCache)
./ipxe.go:124:19: c.schemes.LazyFetchWithoutCache undefined (type curl.Schemes has no field or method LazyFetchWithoutCache)
./ipxe.go:154:29: undefined: boot.CatInitrdsWithFileCache
```
see: https://github.com/u-root/u-root/pull/2655

After changes in the package's dependencies, the native_go-fuzzer script fails when trying to build the fuzzer, but local fuzzing works just fine on this branch. I'm not sure how to fix the script .@AdamKorcz do you have any idea how I would be able to fix the build script?

**Comment by AdamKorcz** [comment]
I can't see the problem. u-root builds fine on OSS-Fuzz and also for me locally including the `FuzzParseIpxeConfig` fuzzer. 

Where do you see the errors?

**Comment by jonathanmetzman** [comment]
I think this is a cifuzz issue. Let me investigate.

**Comment by AdamKorcz** [comment]
> I think this is a cifuzz issue. Let me investigate.

It could be an issue in the build file as well. I will also investigate on my side.

**Comment by jonathanmetzman** [comment]
They can't land this with CI being red?

**Comment by jonathanmetzman** [comment]
Yeah I'm not really sure how to fix this, it seems kind of go specific

**Comment by RiSKeD** [comment]
> I think this is a cifuzz issue. Let me investigate.

The issue should be related to the build file, as building the oss-fuzz fuzzingtarget locally on this branch fails, but go test did not.

**Comment by AdamKorcz** [comment]
https://github.com/google/oss-fuzz/pull/10121 should have fixed this. Could you try running the CI job again, @RiSKeD ?

**Comment by RiSKeD** [comment]
The build is fixed now, appreciate the help.
