### ISSUE TITLE
Please document applicability of asan user poisoning of the input data

### ISSUE THREAD

**Issue by LebedevRI** [google/oss-fuzz#1012]
Hi. I did search for this, but i did not find it.

There is one more kind of issues that i would like to be able to find, but don't yet.
*Abstract* example, does not check buffer sizes:
```c++
// these read [Data + offset, Data + offset + size).
void DecodeBuf1(const uint8_t *Data, uint32_t offset, uint32_t size);
void DecodeBuf2(const uint8_t *Data, uint32_t offset, uint32_t size);

extern "C" int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size) {
  const uint32_t* buff = (const uint32_t*)Data;

  uint32_t Buf1Offset = Data[0];
  uint32_t Buf1Size = Data[1];

  uint32_t Buf2Offset = Data[2];
  uint32_t Buf2Size = Data[3];

  DecodeBuf1(Data, Buf1Offset, Buf1Size);
  DecodeBuf2(Data, Buf2Offset, Buf2Size);

  return 0;  // Non-zero return values are reserved for future use.
}
```
As long as it does not read out-of-bounds, all is good from ASAN's side.

BUT, these two buffers may end up pointing to the same memory, or to overlapping regions of memory. And that isn't actually always meaningful for underlying code.

So in *some* cases, it is possible to poison the memory region after reading, so if the code reads it again, an error is detected. Obviously, we can unpoison the `[Data, Data + size)` region when entering `LLVMFuzzerTestOneInput()`, but can not reliably unpoison it after (if the normal return is not reached), there is no "post_TestOneInput" hook.

What i'm not clear on is, is there a guarantee (or lack of such a guarantee) that the fuzzing engines, during their internal operations, will *not* be affected by this user poisoning?

The workaround is obvious though - copy `Data` into tmp buffer, and operate on it.

**Comment by kcc** [comment]
I would suggest to malloc and free temporary buffers (or, in C++, create `std::vector<>`) and copy data there, then use these temp objects. User poisoning is much easier to get wrong.

**Comment by LebedevRI** [comment]
> I would suggest to malloc and free temporary buffers (or, in C++, create std::vector<>) and copy data there, then use these temp objects

temporary buffer*s*? That would completely defy the point.
(The question is, can i safely poison the input, or do i *have to* duplicate it first)

> User poisoning is much easier to get wrong.

While not on the input data, but on internal memory, it has found and is finding quite a few issues, not all of which would end up being write past the end of the buffer without said poisoning.

**Comment by kcc** [comment]
> can i safely poison the input

Probably you can, as long as you unpoison it before returning from `LLVMFuzzerTestOneInput`. 
But again, it's easy to get wrong. 

> but can not reliably unpoison it after (if the normal return is not reached), there is no "post_TestOneInput" hook.

I don't understand the problem, please explain. 
If `LLVMFuzzerTestOneInput` didn't return nicely, libFuzzer will report an error and exit. 
So, why would you need "post_TestOneInput"?

**Comment by LebedevRI** [comment]
> > can i safely poison the input

> Probably you can, as long as you unpoison it before returning from LLVMFuzzerTestOneInput.

> If LLVMFuzzerTestOneInput didn't return nicely, libFuzzer will report an error and exit.

Hmm, actually, i did not entertain that possibility.
I *thought* that it would/might still access the input buffer for whatever housekeeping needs (storing the crashed state to disk). So if it is really that simple, it would be awesome.

But now the question is, is that libFuzzer-specific, or others (afl, ...) also won't read the buffer after bad return?

**Comment by kcc** [comment]
>  still access the input buffer for whatever housekeeping needs

libFuzzer does read the buffer after `LLVMFuzzerTestOneInput`, but only if `LLVMFuzzerTestOneInput` has returned. If a crash happens, `LLVMFuzzerTestOneInput` does not return. 

> or others (afl, ...) also won't read the buffer after bad 

Can't promise you this.

**Comment by inferno-chromium** [comment]
@kcc - any work here or can we close ?

**Comment by LebedevRI** [comment]
Actually documenting the findings of this disscussion ("can do that for libfuzzer, not guaranteed to work with other fuzzers, best to make local copy and do whatever you like with it") into writing somewhere wouldn't hurt, otherwise i think this can be closed.
Thanks!

**Comment by morehouse** [comment]
Not sure where the best place to document this would be (besides here).  We could add some section to [libFuzzer's documentation](https://llvm.org/docs/LibFuzzer.html), but that seems like a rather specific (and uncommon) use case to put there.  We also don't have direct edit access to AFL's documentation, so we couldn't put something there.

Googling "libfuzzer poison data" currently brings this thread up for me, so this is probably fine staying here.
