### ISSUE TITLE
zlib: example_large_fuzzer.c improvement

### ISSUE THREAD

**Issue by acr0niks** [google/oss-fuzz#10137]
In the zlib project, there is a harness example_large_fuzzer.c.
It does not use any data obtained from the fuzzer, only the length of the generated data. Was this intentional, or does it make sense to rework this wrapper?
I conducted some small experiments by adding data from the fuzzer to *test_large_deflate* function (44,45 lines)  in the following way:
```C
  c_stream.next_in = (Bytef *)data;
  c_stream.avail_in = (unsigned int)dataLen;
```
and obtained a larger number of found paths.

**Comment by Alan32Liu** [comment]
That target was created by @sebpop, who might have more insights into this : )
