### ISSUE TITLE
Automatically ignoring certain crash conditions?

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#1014]
Hi folks,

For spidermonkey, we'd like to automatically ignore crashes that have the message "[unhandlable oom]", since these are the VM intentionally crashing due to being unrecoverably out of memory.

Is this possible?

**Comment by inferno-chromium** [comment]
Can you give a testcase example link currently showing up on ClusterFuzz ?

**Comment by alex** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4418

**Comment by inferno-chromium** [comment]
Added regex  "SEARCH_EXCLUDES = \[unhandlable oom\]" to spidermonkey job type.

**Comment by alex** [comment]
Slick, thanks!
