### ISSUE TITLE
Eligibility of line coverage reward for corpus improvement

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#10146]
I've taken the corpus of a prominent OSS-Fuzz project and enhanced it so that this corpus now yields ~10% more code coverage. I want to feed this into the OSS-Fuzz project by putting my upgraded corpus in a repository, and using it as the project's seed corpus. The project maintainers have agreed to this. According to https://bughunters.google.com/about/rules/5097259337383936/oss-fuzz-reward-program-rules#fuzzing-coverage there is a reward up to $1,000 for a 10% increase. Is a corpus enhancement eligible for the line coverage reward, or does this require improvements to the fuzzing harness?

**Comment by jonathanmetzman** [comment]
I think so, and I support this. @oliverchang WDYT?

**Comment by guidovranken** [comment]
Cool thank you. I did this for wasmtime, found a bug in the process (https://groups.google.com/a/bytecodealliance.org/g/sec-announce/c/ecK-6G2yi90), will submit my upgraded corpus to https://github.com/bytecodealliance/wasmtime-libfuzzer-corpus once the bug is public. There is currently 1 other important project I want to do this for.

**Comment by guidovranken** [comment]
Awesome thank you.
