### ISSUE TITLE
Issues with issues.

### ISSUE THREAD

**Issue by LebedevRI** [google/oss-fuzz#1018]
The issue https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3320 is
1. marked as unreproducible, which is wrong, i was quite reproducible with the git commits before it was fixed.
2. now that it is actually fixed, it is not being marked as such because of false "unreproducible" status
3. `Closure: | Will be auto-closed on 12/14/2017 if flaky crash no longer seen`
and 
   ```
   Nov 29 (2 days ago)
   This bug is approaching its deadline for being fixed, and will be automatically
   derestricted within 7 days. If a fix is planned within 2 weeks after the deadline
   has passed, a grace extension can be granted.
   ```
   => so it will be published on Dec 6 and then closed as unreproducible on Dec 14.

**Comment by LebedevRI** [comment]
Ping, complaint/observation is still valid. Also, no occurrences for 8 days now.

**Comment by inferno-chromium** [comment]
Sometimes a test can be flaky based on execution environment. I don't think we have cycles to debug this one explicitly. This stack has not come back again, so closing the bug.

**Comment by LebedevRI** [comment]
@inferno-chromium thank you!
