### ISSUE TITLE
Are libs used by woodpecker-ci in the fuzz target?

### ISSUE THREAD

**Issue by 6543** [google/oss-fuzz#10231]
I just ask if these libs do have any success to be added ...

- golang lib: [codeberg.org/6543/xyaml](https://codeberg.org/6543/xyaml/pulls/8)
- glang lib: [codeberg.org/6543/go-yaml2json](https://codeberg.org/6543/go-yaml2json/pulls/11)

----
PS: [woodpecker ci](https://woodpecker-ci.org/) is a forge independent CI

**Comment by 6543** [comment]
ok local fuzzing did show flaws in underlying `gopkg.in/yaml.v3@v3.0.1` ... witch is used by a lot of projects ... also one that are already included in oss-fuzz

not sure if that qualifies it ...

**Comment by jonathanmetzman** [comment]
Sorry, I think this question is lacking context or directed at the wrong people. We just maintain a service that fuzzes projects. If youre interested in knowing which dependencies of certain software, find all the dependencies of that software and compare them to https://github.com/google/oss-fuzz/tree/master/projects

**Comment by jonathanmetzman** [comment]
Reopen this if you need more help.
