### ISSUE TITLE
New projects not being run on OSS-Fuzz

### ISSUE THREAD

**Issue by anonrig** [google/oss-fuzz#10266]
oss-fuzz returns 404 for all ada-url builds and even for coverage results page. Is this a bug on the infrastructure level, or something else?

**Comment by jonathanmetzman** [comment]
Can you give me a link please?

**Comment by jonathanmetzman** [comment]
I don't see this https://oss-fuzz-build-logs.storage.googleapis.com/index.html#ada-url

**Comment by jonathanmetzman** [comment]
Do you mean this https://oss-fuzz.com/fuzzer-stats?project=ada-url&fuzzer=libFuzzer&job=libfuzzer_asan_ada-url&group_by=by-fuzzer

**Comment by anonrig** [comment]
Well that was fast! I'll monitor the issue.

**Comment by jonathanmetzman** [comment]
I think there were two issues actually. I think i solved a second one.

**Comment by jonathanmetzman** [comment]
Okay I'm pretty sure this is fixed now: gs://ada-url-logs.clusterfuzz-external.appspot.com/libFuzzer_ada-url_parse/libfuzzer_asan_ada-url/2023-05-10/19:39:54:622366.log
Can you reopen this in a day if you don't see any stats for your project?

**Comment by jonathanmetzman** [comment]
Thank you for reporting this!

**Comment by anonrig** [comment]
Thanks for the fast response and your help! I'll look into this in the next couple of days.
