### ISSUE TITLE
[open5gs] Issue 58803 build fail

### ISSUE THREAD

**Issue by 0x34d** [google/oss-fuzz#10300]
### oss-fuzz
![image](https://github.com/google/oss-fuzz/assets/36335769/29604483-ce22-4c79-8ae5-6de7341d301f)

### My local build
![image](https://github.com/google/oss-fuzz/assets/36335769/9e66c355-4b3f-4180-88d0-46279955c5e1)

[Issue 58803](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58803)

Mine one everything is working fine.

**Comment by 0x34d** [comment]
And the file also there https://github.com/open5gs/open5gs/blob/main/tests/fuzzing/meson.build

**Comment by 0x34d** [comment]
If [build.sh](https://github.com/google/oss-fuzz/blob/master/projects/open5gs/build.sh#L21)  is unable to find the correct path to `tests/fuzzing/meson.build` it can be changed to `$SRC/open5gs/tests/fuzzing/meson.build`

**Comment by jonathanmetzman** [comment]
Ha I just noticed this same issue too.
Yes, please don't rely on $PWD, change to $SRC please.

**Comment by 0x34d** [comment]
Fingers crossed. It should do the work https://github.com/google/oss-fuzz/pull/10313

**Comment by 0x34d** [comment]
![image](https://github.com/google/oss-fuzz/assets/36335769/39418764-8157-4072-9e1b-cbfe6dab2f13)

It didn't work new fix : https://github.com/google/oss-fuzz/pull/10321

**Comment by 0x34d** [comment]
If https://github.com/google/oss-fuzz/pull/10313 didn't work, 
then there are two more options:

1. Use `pushd $SRC/open5gs`.
2. Use the prefix `$SRC/open5gs` everywhere.

I would like to hear your thoughts.
