### ISSUE TITLE
nccl build fail

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#10307]
@DavidKorczynski @AdamKorcz 
Hi David, you added NCCL in https://github.com/google/oss-fuzz/pull/10250 but the build has sadly never succeed: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#nccl
This causes exceptions in ClusterFuzz, could you please fix this, or I will have to delete it to get these exceptions under control.

Thank you!

**Comment by DavidKorczynski** [comment]
I'll just keep this open until the build shows ups successfully on the tracker

**Comment by DavidKorczynski** [comment]
build succeeds now
