### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by garydgregory** [google/oss-fuzz#10339]
Hi All:

I am getting a permission denied for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59038

**Comment by Alan32Liu** [comment]
@jonathanmetzman, what's the best way to give people access to the page?
(e.g., adding emails to the project.yaml?)

**Comment by garydgregory** [comment]
I am ggregory at apache dot org, garydgregory at gmail .com dot com, and garydgregory here on GitHub. The Apache email account is with apache.org, not Google. I hope that help but I'm not sure ;-)

**Comment by jonathanmetzman** [comment]
Alright, try again in an hour or two and reopen this if that doesn't work.

**Comment by garydgregory** [comment]
> Alright, try again in an hour or two and reopen this if that doesn't work.

I can see it now @jonathanmetzman, ty!
