### ISSUE TITLE
Build Status failing

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#10366]
It's basically timing out all the time now. We can either make things faster or give it more time.
https://pantheon.corp.google.com/cloud-build/builds;region=global?project=oss-fuzz
@hogo6002 do you have time to work on this? I'm happy to give you the necessary background/context.

It also fails sometimes because of a failure in processing one project, this could probably be fixed by adding a retry.

**Comment by hogo6002** [comment]
Sure! I will have a look and let you know if I need more information.

**Comment by hogo6002** [comment]
I will increase the time from 3 hours to 4 hours first to see if it works.

**Comment by oliverchang** [comment]
Looks like the timeout increase worked and the recent runs are all succeeding now: https://pantheon.corp.google.com/cloud-build/builds;region=global?project=oss-fuzz&pageState=(%22builds%22:(%22f%22:%22%255B%257B_22k_22_3A_22Trigger%2520Name_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22Build-Status_5C_22_22_2C_22s_22_3Atrue_2C_22i_22_3A_22triggerName_22%257D%255D%22))

**Comment by jonathanmetzman** [comment]
Thanks Holly!
