### ISSUE TITLE
UBSAN Unsigned-integer-overflow report deduplication is broken.

### ISSUE THREAD

**Issue by LebedevRI** [google/oss-fuzz#1036]
https://oss-fuzz.com/v2/testcase-detail/6655889663590400
https://oss-fuzz.com/v2/testcase-detail/5355717868388352
https://oss-fuzz.com/v2/testcase-detail/6208906813505536
https://oss-fuzz.com/v2/testcase-detail/5095098715996160
... and many more from https://oss-fuzz.com/v2/crash-stats?block=day&days=7&end=420323&group=platform&number=count&q=unsigned-integer-overflow&sort=total_count

all point to https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4550
But they all have *completely* different backtraces, and even happen in different functions/files...

I suppose kinda related to #863

**Comment by inferno-chromium** [comment]
Basically our deduplication works as a best guess, it tries to group similar looking stacktraces into one group (https://oss-fuzz.com/v2/testcases?q=group%3A5575276596559872). If we don't this, we spam and create many bugs for most scenarios (>90%). So, this case which happens ~ <10% time, we rely on you fixing individual bugs. If you fix one bug, then ClusterFuzz will close that, then later automatically realise that this other grouped testcase should get a new bug, and it files another new one. So, this is a reasonable workaround for this scenario.

**Comment by inferno-chromium** [comment]
And no, this is not related to #863, #863 is an issue of not using the right part of stacktrace to put in crash state for deduplication.
