### ISSUE TITLE
openssl build is broken

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1037]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

Step #3: ../../usr/lib/libFuzzingEngine.a(FuzzerUtilLinux.o):(.eh_frame+0x13): undefined reference to `__gxx_personality_v0'
Step #3: ../../usr/lib/libFuzzingEngine.a(FuzzerUtilPosix.o): In function `fuzzer::DisassembleCmd(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)':
Step #3: /src/libfuzzer/FuzzerUtilPosix.cpp:142: undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
Step #3: ../../usr/lib/libFuzzingEngine.a(FuzzerUtilPosix.o): In function `fuzzer::SearchRegexCmd(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)':
Step #3: /src/libfuzzer/FuzzerUtilPosix.cpp:146: undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
Step #3: ../../usr/lib/libFuzzingEngine.a(FuzzerUtilPosix.o): In function `operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >':
Step #3: /usr/local/bin/../include/c++/v1/string:3870: undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*)'
Step #3: ../../usr/lib/libFuzzingEngine.a(FuzzerUtilPosix.o): In function `__libcpp_deallocate':
Step #3: /usr/local/bin/../include/c++/v1/new:236: undefined reference to `operator delete(void*)'
Step #3: /usr/local/bin/../include/c++/v1/new:236: undefined reference to `operator delete(void*)'
Step #3: ../../usr/lib/libFuzzingEngine.a(FuzzerUtilPosix.o):(.eh_frame+0x193): undefined reference to `__gxx_personality_v0'
Step #3: clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
Step #3: make[1]: *** [fuzz/x509] Error 1
Step #3: Makefile:6990: recipe for target 'fuzz/x509' failed
Step #3: clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
Step #3: Makefile:6974: recipe for target 'fuzz/server' failed
Step #3: make[1]: *** [fuzz/server] Error 1
Step #3: clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
Step #3: make[1]: *** [fuzz/crl] Error 1
Step #3: Makefile:6942: recipe for target 'fuzz/crl' failed
Step #3: clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
Step #3: make[1]: *** [fuzz/conf] Error 1
Step #3: Makefile:6926: recipe for target 'fuzz/conf' failed
Step #3: make[1]: Leaving directory '/src/openssl'
Step #3: Makefile:140: recipe for target 'all' failed
Step #3: make: *** [all] Error 2
Finished Step #3
ERROR
ERROR: build step "gcr.io/oss-fuzz/openssl" failed: exit status 2

@kroeckx - can you please take a look.

**Comment by kroeckx** [comment]
For some reason the LDCMD=clang++ doesn't seem to have an effect anymore, this is probably related to some recent changes. @levitte: Can you look at this?

**Comment by levitte** [comment]
Ahhhhh, yes, I may have missed that one.  Distracted by a meeting right now, but @kroeckx, please nudge me this evening and I'll have another look.

**Comment by levitte** [comment]
I would like to make something cleaner, but need to have more brains than I have for the moment...  in the mean time, can you check if this patch gives a better result?

``` diff
diff --git a/Configurations/unix-Makefile.tmpl b/Configurations/unix-Makefile.tmpl
index 7f8a322cc4..8c0bb66a72 100644
--- a/Configurations/unix-Makefile.tmpl
+++ b/Configurations/unix-Makefile.tmpl
@@ -1053,7 +1053,7 @@ EOF
       return <<"EOF";
 $bin$exeext: $objs $deps
        rm -f $bin$exeext
-       $cmd $cmdflags \$(LDFLAGS) \$(BIN_LDFLAGS) -o $bin$exeext $objs \\
+       \$\${LDCMD:-$cmd} $cmdflags \$(LDFLAGS) \$(BIN_LDFLAGS) -o $bin$exeext $objs \\
                \$(PLIB_LDFLAGS) $linklibs \$(EX_LIBS)
 EOF
   }
```

**Comment by inferno-chromium** [comment]
Build is green now!.
