### ISSUE TITLE
two issues "fixed" but not "verified" and closed

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#1038]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4583 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4592 were detected as "fixed", but didn't get the usual follow up "verified" and closed status for some unknown reason

**Comment by inferno-chromium** [comment]
It is a monorail glitch. We pushed an issue comment update, and thought it went through, but it didn't. So, we closed testcase and didn't followup on verified again. Closed these manually now and pushing a fix on our side to recheck issue status after update to ensure we have the right result.
