### ISSUE TITLE
web interface doesn't have log-out option

### ISSUE THREAD

**Issue by mrphs** [google/oss-fuzz#1039]
I just realized that the https://oss-fuzz.com web interface doesn't have a way for user to log out. Even if users log out of their google account in the same browser, oss-fuzz will remain logged in. This is very risky since you can have access to the list of crashes using this interface and people might not notice they haven't been successfully signed out.

**Comment by inferno-chromium** [comment]
We now have a Logout and Switch Account menu item on the menu drawer on top left. Thanks for reporting this.
