### ISSUE TITLE
Some of the LLVM fuzzers fail with "size of coverage PC tables does not match"

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#1042]
* build llvm fuzzers
* run e.g. /out/llvm-isel-fuzzer--aarch64-O2
```
/out/llvm-isel-fuzzer--aarch64-O2 -runs=0 
/out/llvm-isel-fuzzer: Injected args: -mtriple=aarch64 -O2
INFO: Seed: 2376904356
INFO: Loaded 1 modules   (959068 inline 8-bit counters): 959068 [0xb2e64b8, 0xb3d0714), 
INFO: Loaded 1 PC tables (958819 PCs): 958819 [0xb3d0718,0xc271d48), 
ERROR: The size of coverage PC tables does not match the
number of instrumented PCs. This might be a compiler bug,
please contact the libFuzzer developers.
Also check https://bugs.llvm.org/show_bug.cgi?id=34636
for possible workarounds (tl;dr: don't use the old GNU ld)
```

**Comment by morehouse** [comment]
llvm.org/pr34636

**Comment by kcc** [comment]
sure, but I thought we've disabled dead stripping in the llvm build for fuzzers.

**Comment by igor-laevsky** [comment]
From the ClusterFuzz logs I see that problem started to appear somewhere around 13-14 of November, the day when the llvm-opt-fuzzer was added, but that may be just a coincidence.

Also worth noting that I can run these fuzzers locally on MacOS with no problem.

**Comment by morehouse** [comment]
November 14 makes sense.  That's when we switched coverage flags to `-fsanitize=fuzzer-no-link`.  My guess is the LLVM build is using dead stripping.  Looking into it.

**Comment by igor-laevsky** [comment]
Hm. I still see this error in the recent logs. I checked recent build logs which have "-DLLVM_NO_DEAD_STRIP" defined.

**Comment by igor-laevsky** [comment]
Actually I can see that new issues just started to come in from the isel and opt fuzzers. So I think everything works, I just needed to wait a bit longer.
