### ISSUE TITLE
Build status is timing out

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#10436]
https://pantheon.corp.google.com/cloud-build/builds?project=oss-fuzz it succeeds on about 1/4 runs.

**Comment by Alan32Liu** [comment]
I did not notice any timeout in the linked page, did I miss anything?

**Comment by jonathanmetzman** [comment]
The page may have redirected you to https://pantheon.corp.google.com/cloud-build/builds;region=us-central1?project=oss-fuzz instead of https://pantheon.corp.google.com/cloud-build/builds;region=global?project=oss-fuzz which is where the build status jobs are run. Holly fixed this.
