### ISSUE TITLE
gstreamer build is broken

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#1045]
@bilboed could you please take a look at this?

[Here](https://oss-fuzz-build-logs.storage.googleapis.com/log-bd33f783-17bb-487c-ab28-156a41036fb8.txt) are the build logs.

These seem to be the relevant lines:
```
Step #3: configure: error: conditional "HAVE_GRAPHENE" was never defined.
Step #3: Usually this means the macro was only invoked conditionally.
Step #3:   configure failed
Finished Step #3
ERROR
ERROR: build step "gcr.io/oss-fuzz/gstreamer" failed: exit status 1
```

**Comment by inferno-chromium** [comment]
@bilboed - Happy new year and friendly ping!

**Comment by bilboed** [comment]
whoops, right. Having a look at it. Happy new year :)

**Comment by bilboed** [comment]
Should be fixed now.

**Comment by Dor1s** [comment]
Confirmed, thanks!
