### ISSUE TITLE
[Q] Would it be acceptable to move `build.sh` into project's repo?

### ISSUE THREAD

**Issue by LebedevRI** [google/oss-fuzz#10458]
Currently, `build.sh` is located in this repo.

This is a bit of a pain point for me, because for the most part,
it encodes internal implementation detail of the _project_,
and it needs to be modified (in another repo!),
when those details change.
Moreover, this does not play well with (recommended) CIFuzz integration.

Would it be acceptable if i do $subj for my project?
(https://github.com/google/oss-fuzz/tree/master/projects/librawspeed)

**Comment by jonathanmetzman** [comment]
Yes. We prefer this!

**Comment by LebedevRI** [comment]
Yay!
