### ISSUE TITLE
Print out trial build links of all projects

### ISSUE THREAD

**Issue by Alan32Liu** [google/oss-fuzz#10463]
[Context](https://github.com/google/oss-fuzz/pull/10433#issuecomment-1574212955).

**Comment by oliverchang** [comment]
FYI @hogo6002 is workign on https://github.com/google/oss-fuzz/issues/8774 which may overlap with some of this.

**Comment by Alan32Liu** [comment]
Yep, you are right.
I will close this, as that task includes this and more.
