### ISSUE TITLE
Max len for runs with corpus

### ISSUE THREAD

**Issue by igor-laevsky** [google/oss-fuzz#1047]
This is more of a question than an issue.

Is there a way to force OSSFuzz to calculate max_len argument from the testing corpus? This is motivated by the large amount of failures of the llvm-opt-fuzzer  (~70% of runs). Problem is that fuzzer gets rather small max_len argument and libFuzzer seems to blindly clamp cases from the input corpus. However those inputs are structured files representing llvm ir and they don't survive such truncation. This leads to us not being able to load large part of the corpus input and additionally exposes obscure issues in the llvm ir reader.

**Comment by Dor1s** [comment]
You can specify an arbitrary `max_len` value via .options file. In that case, OSS-Fuzz will not use some random length, but will always use the one you specified. Example:

https://github.com/google/oss-fuzz/blob/a143b9b39a51412d133f846688194d68fe4197ba/projects/woff2/convert_woff2ttf_fuzzer.options#L2

and don't forget to copy that to `$OUT/` dir: https://github.com/google/oss-fuzz/blob/a143b9b39a51412d133f846688194d68fe4197ba/projects/woff2/build.sh#L40

**Comment by igor-laevsky** [comment]
Thanks! Didn't know that it's possible to specify separate options for each of the fuzzing targets. However llvm fuzzer case is a bit more complicated because we generate corpus out of the current set of unit tests. Which means that it's maximum size may change over time. It there a more elegant solution rather than simply putting very high max length limit?

**Comment by Dor1s** [comment]
In chat case we'll probably have to make a change on our side. By default, libFuzzer uses length of the largest corpus input as `max_len`, so we simply don't need to add our own value.

Abhishek (@inferno-chromium) what do you think about using 
```
# use length of the largest corpus unit
max_len = -1
```

in .options file and not adding `max_len` option in the launcher in that case?

**Comment by inferno-chromium** [comment]
@Dor1s - sounds good!

@jonathanmetzman - What does afl do in this case ? Or does it ignore it always.

**Comment by jonathanmetzman** [comment]
AFL doesn't have a way to set maximum length. So we always ignore it.

**Comment by inferno-chromium** [comment]
We fixed it by picking a random -max_len only 33% of the time. Rest of the time, we just leave it for libFuzzer to read corpus and determine it from max file size. Note that sometimes we try with a subset of corpus to see it we can get more coverage, so in those case, it will pick maximum file size of the corpus subset.

**Comment by kcc** [comment]
>>  .. and additionally exposes obscure issues in the llvm ir reader.

But those are bugs, right? 
(I do understand that those are not the bugs we want to find the most)
The fuzz target should generally not assume that the input is valid.

**Comment by igor-laevsky** [comment]
@kcc, yes those are valid bugs. However they cover obscure parts of the bitcode reader and don't present any immediate interest especially for the llvm-opt-fuzzer. I think right way to deal with them would be to add separate llvm-bitcode fuzzer.

**Comment by igor-laevsky** [comment]
Hi!

Unfortunately I'm still observing the same problematic behaviour. Though it now has slightly less impact (~60% of runs). After conversation with @kcc I believe that problem lurks in the fact that fuzzer observes new coverage in the truncated tests. It then adds these new incorrect test cases to the corpus and then they produce non-deterministic failures in parts unrelated to the fuzzing target.

So essentially it means that even low percentage of a max_len runs will cumulatively poison the corpus. I believe that by disabling such runs completely we may greatly increase llvm-opt-fuzzer effectiveness. Is this something which is possible to do? Will I achieve this goal by providing ".options" file with "max_len=0"?

**Comment by kcc** [comment]
>> may greatly increase llvm-opt-fuzzer effectiveness.

Not sure about greatly. 
What we *may* be able to get is the reduction of uninteresting bugs in the IR parser, but hardly a significant bump in interesting bugs. 

If we stop using ClusterFuzz-provided max_len, (Oliver, can we do it?) we will still need to remove all truncated inputs from the existing corpus and make sure they don't appear again. Given that the IR mutator itself is a bit buggy I am not confident we can do this.

**Comment by oliverchang** [comment]
> If we stop using ClusterFuzz-provided max_len, (Oliver, can we do it?)

If you a max_len in the .options file, then ClusterFuzz will always use that.  i.e. using `max_len = 0` in the options file should achieve this.

**Comment by igor-laevsky** [comment]
@kcc, I might have been overly optimistic with the "greatly" quality :) However not having truncated inputs will at least help to clearly understand what's happening when there is a bug in the mutator itself. I'm a bit curious on how corpus is updated on the ClusterFuzz. Is it accumulated across different builds? If there is a new hand-written test, when it get's merged to the ClusterFuzz corpus?

@oliverchang , thanks! I will prepare a patch in a few moments.
