### ISSUE TITLE
Can't build Halide/LLVM (No space left on device)

### ISSUE THREAD

**Issue by silvergasp** [google/oss-fuzz#10491]
I've been trying to [integrate the halide project](https://github.com/google/oss-fuzz/pull/10107), and I'm running into issues with github's action runners.

One of Halides dependencies is libllvm which I can't build and install with the base github action runners as I am getting the error [no space left on device](https://github.com/google/oss-fuzz/actions/runs/5204782077/jobs/9389446765#step:8:8540). I'm able to build this project locally on my machine just fine.

According the [github action documentation](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) there is "14 GB of SSD space" which is just shy of what I would need to build llvm on a linux machine. In fact some of the builds are successful (they don't run out of space). 

I've run into similar limitations with the base github actions previously in #10174. Would it make sense to either;
1. Upgrade the github actions runners to the "large runners" with more space/ram OR
2. Configure the CI to use the same machines the OSS-fuzz actually builds with on a regular basis.

**Comment by silvergasp** [comment]
Ah yeah that pr looks great. It seems to help a little but it's still running out of space.

**Comment by jonathanmetzman** [comment]
I don't know if we're going to do either of those solutions though they would make sense. It's a lot easier just to use github actions even if they don't work on some anomalous projects. You don't need to pass CI to integrate with oss-fuzz, especially if it's because our CI is broken.
