### ISSUE TITLE
oss-fuzz seems to leak file descriptors after running a while

### ISSUE THREAD

**Issue by darconeous** [google/oss-fuzz#1054]
While investigating [oss-fuzz-3565](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3565), I added some code to count the number of open file descriptors both before and after a run of the fuzz target. Expecting to finally be able to identify what in `wpantund` was leaking file descriptors, I was surprised to notice that the number of open file descriptors at the start of the fuzz target was always equal to the number of open file descriptors at the end of the target. However, the number of open file descriptors was still increasing!

I noticed that extra file descriptors seem to show up *between* the individual executions of the fuzz target, and this only starts to happen after running a few hours on my machine. Once it starts though, it steadily keeps adding file descriptors until (due to [oss-fuzz-3565](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3565)) the fuzz target crashes.

It is somewhat unclear to me what might be causing this. My initial impression is that there is some sort of strange file descriptor leak in oss-fuzz, as unlikely at that might seem.

**Comment by Dor1s** [comment]
Did you notice that behavior while running fuzz target locally, or you were looking at logs from OSS-Fuzz?

**Comment by darconeous** [comment]
It was from a local run, but I've merged the change into wpantund so that I can reproduce this on oss-fuzz.

**Comment by darconeous** [comment]
You can see the trap I added being triggered here: https://oss-fuzz.com/v2/testcase-detail/5138387548766208

That the code does is compare the number of file descriptors at the start of the test to the number of descriptors at the end of the previous test. If they differ, it prints out a log message. If the total number of file descriptors open is more than 10, then it aborts.

**Comment by darconeous** [comment]
It also compares the number of file descriptors which are opened between the start of the test and the end of the test and aborts if the counts are different. I haven't seen any aborts from that, so I'm somewhat confident that wpantund isn't leaking file descriptors.

**Comment by Dor1s** [comment]
If it can be reproduced locally, then it's not caused by OSS-Fuzz infra, but still can be caused by fuzzing engine, i.e. libFuzzer in this particular case. It's expected that libFuzzer does file operations, as it reads and writes corpus files. Though everything should happen in single process, thus I wouldn't expect libFuzzer to have too many files open at the same time. What's the max value you've observed so far?

**Comment by darconeous** [comment]
1024, the point where my app can no longer function.

**Comment by Dor1s** [comment]
Thanks for the info. I did a quick look through libFuzzer's file operations, didn't noticed any possible leaks. //cc @morehouse regarding this behavior from libFuzzer side and @oliverchang in case our restricted environment may affect this.

**Comment by darconeous** [comment]
Yeah, I poked around in libfuzzer as well and nothing obvious stood out to me. Maybe I should try forcing the execution of lsof when it hits this issue to see what those open file descriptors are.

**Comment by Dor1s** [comment]
Correction to my previous command: @oliverchang, restricted environment shouldn't matter here, sorry, but anyway maybe you have some clues about the issue

**Comment by Dor1s** [comment]
@darconeous did you try `strace` to see which FDs are open and leaked? It those are files, we should see filenames as well.

**Comment by darconeous** [comment]
Oh, good idea, I'll give that a try after this `lsof` attempt finished running on my machine.

**Comment by darconeous** [comment]
Hmm... `strace` makes things run *really* slowly. Still trying to get `lsof` to run properly.

**Comment by darconeous** [comment]
Well, I got `lsof` to work...

```
wpantund-  15 root    0r   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root    1u   CHR  136,0      0t0        3 /dev/pts/0
wpantund-  15 root    2u   CHR  136,0      0t0        3 /dev/pts/0
wpantund-  15 root    3r  FIFO   0,10      0t0 10930333 pipe
wpantund-  15 root    5u   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root    6w  FIFO   0,10      0t0 10930334 pipe
wpantund-  15 root    7u   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root    8u   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root    9u   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root   10u   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root   11u   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root   12u   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root   13u   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root   14u   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root   15u   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root   16u   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root   17u   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root   18u   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root   19u   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root   20u   CHR    1,3      0t0 10970171 /dev/null
wpantund-  15 root   21u   CHR    1,3      0t0 10970171 /dev/null
```

Seems kinda weird. I'm also (so far) having some trouble reproducing this issue when I run the fuzzer directly from the shell, which may just be due to my impatience, but may be indicative of... something...

**Comment by darconeous** [comment]
Normally it looks something like this:

```
COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF     NODE NAME
wpantund-  15 root  cwd    DIR               0,45     1224 25690771 /out
wpantund-  15 root  rtd    DIR               0,62     4096        2 /
wpantund-  15 root  txt    REG               0,45  8799304 25699521 /out/wpantund-fuzz
wpantund-  15 root  mem    REG               0,62    47600       51 /lib/x86_64-linux-gnu/libnss_files-2.23.so
wpantund-  15 root  mem    REG               0,62    47648       49 /lib/x86_64-linux-gnu/libnss_nis-2.23.so
wpantund-  15 root  mem    REG               0,62    93128       47 /lib/x86_64-linux-gnu/libnsl-2.23.so
wpantund-  15 root  mem    REG               0,62    35688       45 /lib/x86_64-linux-gnu/libnss_compat-2.23.so
wpantund-  15 root  mem    REG               0,62  1868984       39 /lib/x86_64-linux-gnu/libc-2.23.so
wpantund-  15 root  mem    REG               0,62    89696       86 /lib/x86_64-linux-gnu/libgcc_s.so.1
wpantund-  15 root  mem    REG               0,62    14608       37 /lib/x86_64-linux-gnu/libdl-2.23.so
wpantund-  15 root  mem    REG               0,62    31712       85 /lib/x86_64-linux-gnu/librt-2.23.so
wpantund-  15 root  mem    REG               0,62  1088952       83 /lib/x86_64-linux-gnu/libm-2.23.so
wpantund-  15 root  mem    REG               0,62    10656       81 /lib/x86_64-linux-gnu/libutil-2.23.so
wpantund-  15 root  mem    REG               0,62   138696       62 /lib/x86_64-linux-gnu/libpthread-2.23.so
wpantund-  15 root  mem    REG               0,62   162632       32 /lib/x86_64-linux-gnu/ld-2.23.so
wpantund-  15 root    0r   CHR                1,3      0t0 10970171 /dev/null
wpantund-  15 root    1u   CHR              136,0      0t0        3 /dev/pts/0
wpantund-  15 root    2u   CHR              136,0      0t0        3 /dev/pts/0
wpantund-  15 root    3r  FIFO               0,10      0t0 10930333 pipe
wpantund-  15 root    4u  unix 0x0000000000000000      0t0 11163011 type=STREAM
wpantund-  15 root    6w  FIFO               0,10      0t0 10930334 pipe
wpantund-  15 root    7u  unix 0x0000000000000000      0t0 11163012 type=STREAM
wpantund-  15 root    8u   CHR                1,3      0t0 10970171 /dev/null
```

**Comment by oliverchang** [comment]
What did you do different to get these 2 different results?

**Comment by darconeous** [comment]
The first instance came from a `system()` call to `lsof` directly from the fuzzer once a threshold number of FDs had leaked. 

The second instance came from me running `lsof` on the PID of the fuzzer in a 1-second loop from a `docker exec` shell while the `run-fuzzer` was running.

Here is the output from `lsof` from before too many FDs have leaked but after FDs have started leaking:

```
COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF     NODE NAME
### omitting non-fd files ###
wpantund-  15 root    0r   CHR                1,3      0t0 10970171 /dev/null
wpantund-  15 root    1u   CHR              136,0      0t0        3 /dev/pts/0
wpantund-  15 root    2u   CHR              136,0      0t0        3 /dev/pts/0
wpantund-  15 root    3r  FIFO               0,10      0t0 10930333 pipe
wpantund-  15 root    4u  unix 0x0000000000000000      0t0 11193562 type=STREAM
wpantund-  15 root    5u   CHR                1,3      0t0 10970171 /dev/null
wpantund-  15 root    6w  FIFO               0,10      0t0 10930334 pipe
wpantund-  15 root    7u   CHR                1,3      0t0 10970171 /dev/null
wpantund-  15 root    8u   CHR                1,3      0t0 10970171 /dev/null
wpantund-  15 root    9u   CHR                1,3      0t0 10970171 /dev/null
wpantund-  15 root   10u   CHR                1,3      0t0 10970171 /dev/null
wpantund-  15 root   11u   CHR                1,3      0t0 10970171 /dev/null
wpantund-  15 root   12u   CHR                1,3      0t0 10970171 /dev/null
wpantund-  15 root   13u   CHR                1,3      0t0 10970171 /dev/null
wpantund-  15 root   14u   CHR                1,3      0t0 10970171 /dev/null
wpantund-  15 root   15u   CHR                1,3      0t0 10970171 /dev/null
wpantund-  15 root   17u  unix 0x0000000000000000      0t0 11193563 type=STREAM
wpantund-  15 root   18u   CHR                1,3      0t0 10970171 /dev/null
```

**Comment by darconeous** [comment]
There are a few instances where wpantund opens `/dev/null`, so I'm going to explicitly rule those out real quick... But I'm not sure why my code wouldn't have detected that as an obvious FD leak internal to wpantund.

**Comment by darconeous** [comment]
I cannot fathom why my code wouldn't have detected a leak. Here is the code that is supposed to calculate and store the number of file descriptors open before the real target gets executed:

https://github.com/openthread/wpantund/blob/2772d9a64dd3d8695f866b429dc1a3f6e35b11af/src/wpantund/wpantund-fuzz.cpp#L255-L267

And here is the code that is supposed to detect FD leaks in the target:

https://github.com/openthread/wpantund/blob/2772d9a64dd3d8695f866b429dc1a3f6e35b11af/src/wpantund/wpantund-fuzz.cpp#L290-L295

**Comment by darconeous** [comment]
oh gawd I'm an idiot. I'm returning early.

My bug.

**Comment by darconeous** [comment]
False alarm. Will fix. Sorry for the noise.
