### ISSUE TITLE
Build status page doesn't render in Firefox nightly

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#1065]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

It fails with: `Loading failed for the <script> with source “https://oss-fuzz-build-logs.storage.googleapis.com/bower_components/webcomponentsjs/webcomponents-hi-sd.js”.`

Skimming the source, it looks like that WebComponents URL is built based on which set of polyfills are needed, so that one needs `hi` and `sd`.

I guess for whatever reason the build process doesn't build a JS file with that combination.

This started breaking today, so I assume we added/removed some feature to trigger this polyfill issue.

If you think this is a Firefox bug, I can file it with us, but it seemed like a normal browser shouldn't cause the WebComponents JS to try to load a non-existent file.

**Comment by oliverchang** [comment]
Looks similar to https://github.com/webcomponents/webcomponentsjs/issues/817

**Comment by alex** [comment]
Strange, I wonder why I didn't notice this before today, I've certainly looked at the build status before.

**Comment by oliverchang** [comment]
Did a flag just get enabled by default? The issue in https://github.com/google/oss-fuzz/issues/1065#issuecomment-357128636 seems to suggest that it was caused by a flag.

**Comment by alex** [comment]
It's entirely possible we turned something on/off on nightly yesterday. I'll poke around when I'm at the office tomorrow.

**Comment by bennypowers** [comment]
I'd like to suggest this is because Nightly enabled `dom.webcomponents.customelements.enabled` a few days ago. see https://github.com/webcomponents/webcomponentsjs/issues/817#issuecomment-357496820

**Comment by inferno-chromium** [comment]
Fix is in - https://github.com/webcomponents/webcomponentsjs/pull/889, but need to wait on a new webcomponentsjs release from @azakus

**Comment by alex** [comment]
🎉

**Comment by inferno-chromium** [comment]
Verified that it works.

In dir infra/gcb/templates:
bower install
./deploy.sh
after making the change to deploy.
