### ISSUE TITLE
geos: fuzzing build failure due to patch error

### ISSUE THREAD

**Issue by hedsnz** [google/oss-fuzz#10661]
It looks like the fuzzing builds for *geos* have been failing since January 2023: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54891. I have reproduced this build failure on PopOS 22.04 LTS. The error seems to be due to a failed patch; the relevant part of the logs is the following:

```
+ git apply ../patch.diff
error: patch failed: tests/CMakeLists.txt:11
error: tests/CMakeLists.txt: patch does not apply
../patch.diff:106: new blank line at EOF.
+
ERROR:__main__:Building fuzzers failed.
```

The full build logs are available at the URL above.

**Comment by jonathanmetzman** [comment]
Do you want to take a crack at fixing it?
CC @catenacyber

**Comment by catenacyber** [comment]
Should be fixed by https://github.com/google/oss-fuzz/pull/10669

@hedsnz are you interesting in merging the patch upstream ?

**Comment by hedsnz** [comment]
@catenacyber thanks very much for the quick fix -- can confirm that it works for me.

Unfortunately I'm not a member of the upstream project, and having seen https://github.com/libgeos/geos/pull/436, it looks like they aren't too interested in integrating.
