### ISSUE TITLE
How can I get access to bug-reports

### ISSUE THREAD

**Issue by centic9** [google/oss-fuzz#10775]
Hi, in #10769 I added myself to CCS of project apache-poi via @apache and @gmx email addresses.

It seems I now get bug-reports via Email, but cannot access bug-reports via my Google account (which is based on a @gmail address), e.g. if I try to open https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54494 I get "Permission denied."

I also have another @gmail account which is linked with my @gmx address, but also when I log in with this one I cannot access bug-details.

What else do I need to do to get access to reports for apache-poi? Add the @gmail address as well?

**Comment by DavidKorczynski** [comment]
The emails in the `project.yaml` should be affiliated with a Google account as the primary email. See here for reasons: https://google.github.io/oss-fuzz/getting-started/new-project-guide/#primary

If you use your `gmail` email then that should work.

**Comment by centic9** [comment]
Thanks, added this change to PR #10776
