### ISSUE TITLE
Fuzzer stats are not available on any projects

### ISSUE THREAD

**Issue by AdamKorcz** [google/oss-fuzz#10798]
Have checked the "Fuzzer stats/coverage" link on oss-fuzz.com for around 30 projects, and all of them return a 404 when searching the stats for the last week.

It looks like the stats became unavailable around 16th July.

**Comment by oliverchang** [comment]
This is caused by https://github.com/google/clusterfuzz/issues/3269

**Comment by jonathanmetzman** [comment]
This should be fixed now.
