### ISSUE TITLE
CPython fuzzing

### ISSUE THREAD

**Issue by androm3da** [google/oss-fuzz#108]
I have a project I started that uses `libFuzzer` with CPython -- https://bitbucket.org/ebadf/fuzzpy

I'd love to integrate it with oss-fuzz, I think it would make a good contribution.  But it generates the fuzz tests dynamically given test cases defined in Python source.  What would be a good way to hook it into oss-fuzz's build system?

Note that as it exists currently it is a monorepo and I'd be willing to decompose it into constituent parts in order to work well with oss-fuzz.

**Comment by inferno-chromium** [comment]
Sorry, but your project does not meet the requirements for OSS-Fuzz - "an open-source project must have a significant user base and/or be critical to the global IT infrastructure". Also, it should be first upstreamed in the python repo.

**Comment by androm3da** [comment]
Ok, but are you saying that CPython doesn't meet that criteria?  Such that even if it were upstreamed it wouldn't be included in OSS-Fuzz?

**Comment by oliverchang** [comment]
Sorry, to clarify: CPython definitely meets the bar, but we'd like to only depend on the upstream cpython repo for fuzzing.
