### ISSUE TITLE
libsodium build broken

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1081]
python infra/helper.py build_fuzzers libsodium

++ basename /src/secret_key_auth_fuzzer.cc _fuzzer.cc
+ fuzzer=secret_key_auth
+ clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -std=c++11 -I/work/include /src/secret_key_auth_fuzzer.cc -o /out/secret_key_auth_fuzzer /work/lib/libsodium.a -lFuzzingEngine
clang-6.0: error: no such file or directory: '/work/lib/libsodium.a'
fuzzers build failed.

@derwolfe - can you please take a look. It is important to ensure that build_fuzzers completes without error locally.

**Comment by derwolfe** [comment]
Sorry about this, this must have happened due to me having a dirty `$WORK` directory when building locally. I've submitted https://github.com/google/oss-fuzz/pull/1082#event-1428899964 to fix the issue.

**Comment by inferno-chromium** [comment]
Fixed, thanks, build is green.
