### ISSUE TITLE
Unable to Access ClusterFuzz UI

### ISSUE THREAD

**Issue by capuanob** [google/oss-fuzz#10866]
I recently implemented the pyvex project for OSSFuzz and am listed as an auto_CC. However, when I attempt to login to OSSFuzz with the email listed in the project.yaml, I get

You (email=myemail@gmail.com) are not authorized to access this page!

Please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.

I've been attempting sporadically to log in for a few weeks now, to no luck.

Thank you for your help!

**Comment by DavidKorczynski** [comment]
I think things will come up in the next 24-36 hours following the addition of code for the project a few hours ago. I could imagine some things may not be working as expected when there's only a `project.yaml`.

**Comment by jonathanmetzman** [comment]
That is correct, it's expected that you can't access the UI yet Let's wait a bit. If it doesn't work in a day or two please reopen this.
