### ISSUE TITLE
Fuzz Introspector attempts introspection of non-test executable files

### ISSUE THREAD

**Issue by ligurio** [google/oss-fuzz#10882]
**Goal**: I want to support Fuzz Introspector for project/lua.

Building fuzzers with introspector is failed:

```
[206/207] Linking CXX executable protoc-3.20.1.0                                                                                             
[Log level 1] : 16:20:07 : Fuzz introspector is running                                                                                      
[Log level 1] : 16:20:07 : Running introspector on ld-temp.o                                                                                 
[Log level 1] : 16:20:07 : Main function filename: /src/testdir/build/tests/external.protobuf_mutator/src/external.protobuf_mutator-build/ext
ernal.protobuf/src/external.protobuf/src/google/protobuf/compiler/main.cc                                                                    
[Log level 1] : 16:20:07 : Main function is non-empty                                                                                        
[Log level 1] : 16:20:07 : This means a main function is in the source code rather in the libfuzzer library, and thus we do not care about it
. We only want to study the actual fuzzers. Exiting this run.                                                                                
[207/207] Creating executable symlink protoc                                                                                                 
[7/16] Performing install step for 'external.protobuf'                                                                                       
[0/1] Install the project...   
```

`protoc` is an executable built by Protobuf library. It is not a test executable.

According to OSS Fuzz documentation, "Resulting binaries should be placed in $OUT." [^1]
But for unknown reasons, Fuzz Introspector looking for all executables in a build/ directory and complains if executable is not satisfied by requirements as in example above.

Is there a way to pass a whitelist with files to Fuzz Introspector?

[^1]: https://google.github.io/oss-fuzz/getting-started/new-project-guide/#buildsh

**Comment by DavidKorczynski** [comment]
It doesn't run analysis on `protoc`, the issue happened earlier in the process. Please see https://github.com/google/oss-fuzz/pull/10891 for more details on this issue.

I came up with a fix, but it has some limitations in that ASAN is enabled, which consequently makes the calltree a bit weird. Am working on seeing if I can get this solved.

You should be able to view the report on oss-fuzz.com or here https://introspector.oss-fuzz.com/project-profile?project=lua

Closing this -- feel free to reopen if I missed something.

**Comment by ligurio** [comment]
Huge, thanks for help, David!

> I came up with a fix, but it has some limitations in that ASAN is enabled, which consequently makes the calltree a bit weird. Am working on seeing if I can get this solved.

It is really bad, because `luaL_loadbuffer_proto` is a grammar-based fuzzing test and it makes a big contribution to coverage.

> You should be able to view the report on oss-fuzz.com or here https://introspector.oss-fuzz.com/project-profile?project=lua

It is strange that not all tests [^1] are present in the report.

-  `luaL_buffaddr_test`                                                               
-  `luaL_bufflen_test`                                                                   
-  `luaL_buffsub_test`                                                                   
-  `luaL_gsub_test`                                                                      
-  `luaL_loadbuffer_proto`  (known problem)                                                             
-  `luaL_loadbufferx_test`                                                               
-  `luaL_traceback_test`                                                                 
-  `lua_stringtonumber_test`

[^1]: https://github.com/ligurio/lua-c-api-tests/tree/master/tests

**Comment by DavidKorczynski** [comment]
> It is strange that not all tests [1](#user-content-fn-1-fffc6f824543cbe011f1cdf769a97505) are present in the report.
> 
>     * ``

Oohh, interesting. I'll take a look at this, it should be solvable.

**Comment by ligurio** [comment]
> Am not sure what changed, but the latest has all fuzzers?

No changes on my side. But this report contains all tests. Many thanks!

**Comment by ligurio** [comment]
> It doesn't run analysis on protoc, the issue happened earlier in the process. Please see https://github.com/google/oss-fuzz/pull/10891 for more details on this issue.

Interesting detail: the same fuzzing test successfully processed by Fuzz Introspector in Tarantool project:
- Fuzz Introspector report https://storage.googleapis.com/oss-fuzz-introspector/tarantool/inspector-report/20230831/fuzz_report.html#Fuzzer:-luaL_loadbuffer_fuzzer
- source code: https://github.com/tarantool/tarantool/tree/master/test/fuzz/luaL_loadbuffer

Perhaps the problem with compiler flags?

**Comment by ligurio** [comment]
Unbelievable, `luaL_loadbuffer_proto_test` is in a FuzzIntrospector report [^1]. Many thanks, David @DavidKorczynski!

[^1]: https://storage.googleapis.com/oss-fuzz-introspector/lua/inspector-report/20230904/fuzz_report.html#Fuzzer:-luaL_loadbuffer_proto_test

**Comment by DavidKorczynski** [comment]
Great @ligurio !

I'm still not 100% sure why the ASAN linking worked tbh.

For reference, in general, when running into issues with Fuzz Introspector a rule of thumb if trying to get it to work is ensuring the build process only creates static libraries. Fuzz Introspector depends on LTO which sometimes struggles with dynamically linked libraries, including e.g. if the build creates some unit tests or other binaries that link to dynamically linked libraries. In this case, I was also looking into the lines: https://github.com/ligurio/lua-c-api-tests/blob/9a8e27ac625dce2ce6a14c41756301cbb49f3b66/cmake/BuildLua.cmake#L62-L64 because the `make` command builds more stuff than what is actually needed. For example, converting it to `make liblua.a` (i.e. only build the static library used for fuzzing) helped build a set of the additional fuzzers that didn't build before.
