### ISSUE TITLE
Questions about ClusterFuzz Features

### ISSUE THREAD

**Issue by ennamarie19** [google/oss-fuzz#10900]
Hello, 
When I try to generate fuzzer statistics on ClusterFuzz, I get a "404 no stats" error message. Additionally, when I try to look at my total coverage on ClusterFuzz, I get a "failed to get coverage report" error message. 

Could you tell me how to resolve these issues?

Thank you!

**Comment by jonathanmetzman** [comment]
What is your project? We had a breakage in stats recently but it should be fixed by now

**Comment by ennamarie19** [comment]
Oh yes, looks like both are working now! Thank you!
