### ISSUE TITLE
kyverno not showing fuzzing stats

### ISSUE THREAD

**Issue by AdamKorcz** [google/oss-fuzz#10913]
Kyverno is returning a 404 on the stats page (https://oss-fuzz.com/fuzzer-stats?project=kyverno&fuzzer=libFuzzer&job=libfuzzer_asan_kyverno&group_by=by-fuzzer) but the build succeeds.

**Comment by AdamKorcz** [comment]
A few more details:

As far as I can see Kyverno has never had fuzz stats available. It integrated into OSS-Fuzz in early July.

I cannot find any of its fuzzers when searching - for example in the "Fuzzers" field in https://oss-fuzz.com/crash-stats?project=kyverno

**Comment by jonathanmetzman** [comment]
I think that was due to our stats breakage. I think there are stats now? https://oss-fuzz.com/fuzzer-stats?project=kyverno&fuzzer=libFuzzer&job=libfuzzer_asan_kyverno&group_by=by-fuzzer

**Comment by AdamKorcz** [comment]
Yes, it looks fixed now. Thanks!
