### ISSUE TITLE
Set up a discussion forum

### ISSUE THREAD

**Issue by szhorvat** [google/oss-fuzz#10925]
I would like to suggest setting up a discussion forum where people can help each other set up new integrations, create fuzz targets, and discuss the best approach to fuzzing various features of their library. I feel that this is not a good fit for the existing issue tracker. GitHub already has a Discussions feature that you could just enable with minimal effort, and leave the discussion to users, if the OSS-fuzz developers don't want to take on the extra workload of participating.

Personal motivation:

I am taking care of igraph's fuzz targets. Currently, the only useful fuzzing I was able to do was for igraph's graph format readers, i.e. the functions parsing various representations of graphs. I was considering whether it would be feasible to also fuzz some of the graph algorithms, but not being experienced with fuzzing, it isn't even clear to me if OSS-fuzz is suitable for this. It would involve translating the byte-array input that the fuzzer generates to a valid graph with certain properties.  I was not able to do this in a way so that the fuzzer could explore the space of graphs in a useful manner.  I would have loved to discuss this topic with people more experienced with fuzzing, but did not find a suitable space to do so.

**Comment by oliverchang** [comment]
Hi!

Thank you for the suggestion, and sorry for the late response.

I've enabled discussions here: https://github.com/google/oss-fuzz/discussions. Our team is not familiar with this, so we'll likely need some time to understand how discussions work and how we can help foster discussions and build communities on this.

Closing this request as done!
