### ISSUE TITLE
install_javascript.bash is not working

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#10936]
Failing with
```
+ npm install --global npm
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: npm@10.1.0
npm ERR! notsup Not compatible with your version of node/npm: npm@10.1.0
npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}
npm ERR! notsup Actual:   {"npm":"9.6.3","node":"v19.9.0"}

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-09-11T14_51_58_244Z-debug-0.log

```

Also the node install is using a deprecated method.

**Comment by jonathanmetzman** [comment]
@kyakdan @fmeum @0roman could someone take a look at this please? It's breaking our testing for a lot of things sadly.

**Comment by mumernaeem1123** [comment]
I am facing the same issue, can someone please help me with this?? is this is a issue on AWS code build or there is issue in the application?

**Comment by mumernaeem1123** [comment]
I have found the cause of it, actually it is getting the latest npm

you may use npm i npm@9.8.1 -g

it will resolve the issue, because the latest is 10.1.0 , and the code build container is not using it, it is using 9.8.1 for now
