### ISSUE TITLE
Fuzz-introspector config files per fuzzer

### ISSUE THREAD

**Issue by kroeckx** [google/oss-fuzz#10930]
I see that Fuzz-introspector supports config files to exclude things. But it's unclear how I can make oss-fuzz use a config file for each of the fuzzers.

**Comment by DavidKorczynski** [comment]
Set `FUZZ_INTROSPECTOR_CONFIG` environment variable to point to your config file.

See example here: https://github.com/google/oss-fuzz/blob/31cb5ddba2ed1b4d1f588864bab37cb8b362f126/projects/fluent-bit/build.sh#L21-L26

**Comment by DavidKorczynski** [comment]
Oh sorry, I just saw the "`use a config file for each of the fuzzers`" -- the above solution will apply the configuration to all of the fuzzers. When you saw "for each of the fuzzers" are you referring to having different behaviour per fuzzer? If so, could you perhaps clarify what specifically you're looking to achieve?

**Comment by kroeckx** [comment]
I

**Comment by kroeckx** [comment]
There are probably large overlaps of what I want to ignore over the different fuzzers, I'm not sure yet. I just started looking at it. But there are large portions of the libraries that aren't really relevant to what the fuzzer is trying to do that might be relevant in some other fuzzer.

I'll start with a single file and see where I'll end up at.

**Comment by DavidKorczynski** [comment]
Closing this as answered.
