### ISSUE TITLE
What is a correct way to exclude unneeded functions from a Fuzz Introspector report?

### ISSUE THREAD

**Issue by ligurio** [google/oss-fuzz#10931]
Each report made by Fuzz Introspector for a fuzzing test that uses LibProtobufMutator, contains Protobuf functions.
This is really annoying! In Lua project [^1], 6,661 out of 8,937 entries are Protobuf functions (section "All functions overview").

[^1]: Lua https://storage.googleapis.com/oss-fuzz-introspector/lua/inspector-report/20230904/fuzz_report.html#Fuzzer:-luaL_loadbuffer_proto_test

**Comment by DavidKorczynski** [comment]
Set `FUZZ_INTROSPECTOR_CONFIG` environment variable to point to your config file.

See example here: https://github.com/google/oss-fuzz/blob/31cb5ddba2ed1b4d1f588864bab37cb8b362f126/projects/fluent-bit/build.sh#L21-L26

**Comment by DavidKorczynski** [comment]
Closing this as answered.
