### ISSUE TITLE
someone can please help me with this, i am using aws codebuild 

### ISSUE THREAD

**Issue by mumernaeem1123** [google/oss-fuzz#10940]
npm ERR! code EBADENGINE
23 | npm ERR! engine Unsupported engine
24 | npm ERR! engine Not compatible with your version of node/npm: npm@10.1.0
25 | npm ERR! notsup Not compatible with your version of node/npm: npm@10.1.0
26 | npm ERR! notsup Required: {"node":"^18.17.0 \|\| >=20.5.0"}
27 | npm ERR! notsup Actual:   {"npm":"9.5.1","node":"v18.16.1"}
28 |  
29 | npm ERR! A complete log of this run can be found in:
30 | npm ERR!     /root/.npm/_logs/2023-09-12T12_04_16_924Z-debug-0.log
31 |  
32 | [Container] 2023/09/12 12:04:18 Command did not exit successfully npm i npm@latest -g exit status 1
33 | [Container] 2023/09/12 12:04:18 Phase complete: INSTALL State: FAILED
34 | [Container] 2023/09/12 12:04:18 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm i npm@latest -g. Reason: exit status 1
35

<br class="Apple-interchange-newline">

**Comment by DavidKorczynski** [comment]
Duplicate of https://github.com/google/oss-fuzz/issues/10940

Closing accordingly.
