### ISSUE TITLE
Disable specific sanitizer just for one fuzz target

### ISSUE THREAD

**Issue by szhorvat** [google/oss-fuzz#10949]
Is it possible to disable UBSan for just a single fuzz target?

We have one fuzz target for igraph for which we don't have the capacity to fix all issues at this time. Fuzzing it with UBSan is pointless—I know it's broken. All I'm looking for is to make sure it won't crash (ASan).

If this is not possible at the moment, I'll just disable the fuzz target entirely.

Ref: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62289

**Comment by jonathanmetzman** [comment]
In your build.sh, you can simply delete the fuzzer during UBSAN builds.
Please reopen if this doesn't work.

**Comment by szhorvat** [comment]
For future reference, the way to do detect UBSan builds seems to be to check the `$SANITIZER` envvar.

https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/README.md#build-configuration
