### ISSUE TITLE
Integration Reward Form

### ISSUE THREAD

**Issue by ennamarie19** [google/oss-fuzz#10958]
Hello,
I submitted the Integration Reward Google form over 2 weeks ago for my project icalendar but have not heard anything from the OSS-Fuzz team. Could you confirm that you received my submission? 

Thank you!

**Comment by arezooalizadeh06** [comment]
Verygood

**Comment by arezooalizadeh06** [comment]
Verygood🙏

**Comment by arezooalizadeh06** [comment]
Hello and thank you, thank you very much for your efforts, it is a great honor for me to work with you, a cultured and knowledgeable lady, be successful and victorious, my good friend.🙏🙏🙏💐🥰

**Comment by jonathanmetzman** [comment]
It can take that long, that's not so unexpected.
Your submission did actually fall through some cracks, but now it is is in the queue.
Maybe reopen this or send us another email if you don't hear anything in another 2 weeks.

**Comment by ennamarie19** [comment]
Hi! Is there a status update on this? About at the 2 week mark so wanted to reach out. Thanks! On Sep 15, 2023, at 6:41 AM, jonathanmetzman ***@***.***> wrote:﻿
It can take that long, that's not so unexpected.
Your submission did actually fall through some cracks, but now it is is in the queue.
Maybe reopen this or send us another email if you don't hear anything in another 2 weeks.

**Comment by jonathanmetzman** [comment]
I've granted the award, sorry I was out a bit during the past two weeks and lost the thread.

**Comment by ennamarie19** [comment]
Oh no worries! Thank you! Will I get an email from you with the award details or someone else? Or does OSS-Fuzz process it another way? On Sep 27, 2023, at 8:28 AM, jonathanmetzman ***@***.***> wrote:﻿
I've granted the award, sorry I was out a bit during the past two weeks and lost the thread.

**Comment by jonathanmetzman** [comment]
> Oh no worries! Thank you! Will I get an email from you with the award details or someone else? Or does OSS-Fuzz process it another way? On Sep 27, 2023, at 8:28 AM, jonathanmetzman ***@***.***> wrote:﻿ I've granted the award, sorry I was out a bit during the past two weeks and lost the thread. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

You should get an email soon
