### ISSUE TITLE
Integration Reward _Process Inquiry

### ISSUE THREAD

**Issue by capuanob** [google/oss-fuzz#10960]
I submitted my initial integration for pyvex for reward about three weeks ago.

I am wondering what this process looks like. Should I expect a response regardless of acceptance or denial? If accepted, what are the next steps?

Thank you!

**Comment by jonathanmetzman** [comment]
Sorry about the delay. I think we overlooked it, I'll ask the team and get back to you.

**Comment by jonathanmetzman** [comment]
I think this has been awarded. Please reopen if there are more issues.

**Comment by capuanob** [comment]
@jonathanmetzman Thank you very much! Out of curiosity, is there a rubric or feedback that I could receive on my submission? I've looked at the rewards breakdown but would like to know specifically what I could improve for future submissions and ideal integrations. Thank you!
