### ISSUE TITLE
The `code coverage` for the `libzip` project is failing.

### ISSUE THREAD

**Issue by nmlsg** [google/oss-fuzz#11010]
Hello!

I'm working on expanding the fuzzing coverage of the libzip project. I have added new fuzzers as well as new corpora. The last two builds were successful except for generating a coverage report and the introspector.

I have observed the following problem:
https://oss-fuzz-build-logs.storage.googleapis.com/log-d3820902-fdef-4ba9-b718-a635b711d339.txt
https://oss-fuzz-build-logs.storage.googleapis.com/log-544ef7f0-d387-4f43-a38b-c2cca0921011.txt
```
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: [/corpus/zip_read_file_fuzzer.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/zip_read_file_fuzzer.zip or
Step #5:         /corpus/zip_read_file_fuzzer.zip.zip, and cannot find /corpus/zip_read_file_fuzzer.zip.ZIP, period.
Step #5: Failed to unpack the corpus for zip_read_file_fuzzer. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
```
I have waited for more than 24 hours, even more than 48 hours. I have also checked coverage locally as well as the introspector, and it worked well. I got 80% coverage (delta = 24%) for all the added fuzzers. Can you please specify what's going wrong with the corpus backup ? I would like to fix this issue.

Thank you!

**Comment by IvanNardi** [comment]
In ntopng project we had the same issue (https://github.com/google/oss-fuzz/issues/10323): there were too many memory leaks/timeouts so the corpus pruning timeout was hit.
Hope that it helps

**Comment by nmlsg** [comment]
Hi !
@IvanNardi thanks for your comment, but I don't think that we have too many memory leaks or something similar :)

**Comment by nmlsg** [comment]
Hi @DavidKorczynski 
Could you help us?

**Comment by DavidKorczynski** [comment]
@nmlsg @0-wiz-0 I think this is an infrastructure problem and same as what Oliver describes here: https://github.com/google/oss-fuzz/issues/10994#issuecomment-1737055492

This should be auto-resolved in a few days

**Comment by jonathanmetzman** [comment]
Looks like there's an issue with corpus backups actually

**Comment by nmlsg** [comment]
Hi @jonathanmetzman 
Do you require specific action points from our side?"

**Comment by jonathanmetzman** [comment]
Sorry, this is an issue with our internal infra. No acction is required on your part. I can confirm that there are now corpus backups available for  zip_write_encrypt_aes256_file_fuzzer and zip_write_encrypt_pkware_file_fuzzer, soI would guess this problem resolves itself. by tomorrow.

**Comment by DavidKorczynski** [comment]
`libzip` is now failing with:

```
Step #3 - "compile-afl-address-x86_64": ---------------------------------------------------------------
Step #3 - "compile-afl-address-x86_64": + /src/libzip/regress/ossfuzz.sh
Step #3 - "compile-afl-address-x86_64": /src/build.sh: line 18: /src/libzip/regress/ossfuzz.sh: Permission denied
Step #3 - "compile-afl-address-x86_64": ********************************************************************************
```
[log](https://oss-fuzz-build-logs.storage.googleapis.com/log-a5929e06-e559-4010-a13e-741eda32c859.txt)

**Comment by 0-wiz-0** [comment]
Thanks - we already fixed that and some other issues earlier today (https://github.com/nih-at/libzip/commit/158acd54453e2e13ba849f0c2e1b9ee9bd8e270e)

**Comment by DavidKorczynski** [comment]
Coverage report is up: https://storage.googleapis.com/oss-fuzz-coverage/libzip/reports/20230929/linux/report.html

**Comment by jreiser** [comment]
Although increasing the (disk) storage quota may be a workaround, if so then there is a software bug in the `zip` program: not detecting and handling a `write()` system call which returns the error `EDQUOT` (Error: Disk QUOTa; see /usr/include/asm-generic/errno.h) when the output file is being generated.  Upon detection then the proper response is a message on `stderr`, followed by a process `exit` with non-zero exit code, which indicates failure. Such detection and response enables the user to learn the actual reason, and to take corrective action sooner with much less consternation and head-scratching.

**Comment by jreiser** [comment]
It's conceivable that the EDQUOT error could occur on `close()`, and not on any prior `write()` to the same file.  This would not be as safe as an OS policy, but it might be very cost-effective.  And almost every programmer does not check the return value of `close()`: "What could possibly go wrong?"

**Comment by jreiser** [comment]
Even more details about `close()`: On a physical magnetic tape medium with Standard (magnetically recorded) tape labels, it is possible that the last `write()` succeeds, but that writing the trailer label (which contains the volume name, sequence number, etc., and which might be written automatically by the OS) can fail, and this failure would be reported by the `close()`.  When a process exits, then all open file descriptors are closed automatically by the OS, and any errors are ignored: there is nowhere to report them!.  If a careless programmer forgets to close the output file explicitly, then the EDQUOT error will get swallowed and not reported.  So the code for **zip** should be checked for an explicit `close()` of the output file, and that `close()` should handle all reported errors.

**Comment by jreiser** [comment]
The cause is a bug in the **zip** utility program for UNIX and Linux: no explicit `close()` of the output file, thus no checking for EDQUOT, thus no reporting of exceeding disk space quota when constructing any compressed zip output file.

Verified using the source for zip-3.0-37.fc38.src.rpm from Fedora 38 Linux, which is a current release.
Debugging session:
```
$ date >foo  # a test file
$ rm -f foo.gz  # no corresponding compressed file
$ gdb --args ./zip foo.gz foo  # invoke debugger
(gdb) b close  # set breakpoints on interesting functions
(gdb) b rename
(gdb) run
Starting program: /absolute_path/zip foo.gz foo
  adding: foo
Breakpoint 1, 0x00007ffff7ebb820 in close () from /lib64/libc.so.6
(gdb) p $rdi  # value of first argument on x86_64
$2 = 0x4  # close(4)
(gdb) bt  # get a backtrace of subroutine calls
#0  0x00007ffff7ebb820 in close () from /lib64/libc.so.6
#1  0x000000000041bff5 in zipup (z=<optimized out>) at /absolute_path/zipup.c:928

# The corresponding source in zipup.c is:
  if (ifile != fbad)
    zclose(ifile);
# and this is closing an input file.

#2  0x000000000040668c in main (argc=<optimized out>, argv=<optimized out>) at /absolute_path/zip.c:5557
(gdb) info proc
process 29509
(gdb) shell ls -l /proc/29509/fd
total 0
lrwx------. 1 jreiser jreiser 64 Jan  3 10:48 0 -> /dev/pts/0
lrwx------. 1 jreiser jreiser 64 Jan  3 10:48 1 -> /dev/pts/0
lrwx------. 1 jreiser jreiser 64 Jan  3 10:48 2 -> /dev/pts/0
lrwx------. 1 jreiser jreiser 64 Jan  3 10:48 3 -> /absolute_path/ zioc1Xgb  # fd3 is the temporary output file
lr-x------. 1 jreiser jreiser 64 Jan  3 10:48 4 -> /absolute_path/foo  # fd4 is the input file
(gdb) continue
 (stored 0%)
Breakpoint 2, 0x00007ffff7e156d0 in rename () from /lib64/libc.so.6
(gdb) x/s $rdi
0x4836d0:	"zioc1Xgb"  # arg1, the temporary name of the output file
(gdb) x/s $rsi
0x483690:	"foo.gz"  # arg2, the final name of the output file
(gdb) shell ls -l /proc/29509/fd  # no open files except for stdin, stdout, stderr
total 0
lrwx------. 1 jreiser jreiser 64 Jan  3 10:50 0 -> /dev/pts/0
lrwx------. 1 jreiser jreiser 64 Jan  3 10:50 1 -> /dev/pts/0
lrwx------. 1 jreiser jreiser 64 Jan  3 10:50 2 -> /dev/pts/0
(gdb)  continue
Continuing.
[Inferior 1 (process 29509) exited normally]  # there was only 1 call to close; it was on the fd for the input file
(gdb) q
$ 
```
So there was no call to `close()` on any file descriptor corresponding to the output *.gz file.  So any EDQUOT that would be reported on `close()` would be ignored.  This is likely in the case of NFS or cloud storage.
