### ISSUE TITLE
fmemopen() vs fopen() with temp file: which is recommended?

### ISSUE THREAD

**Issue by szhorvat** [google/oss-fuzz#11011]
There is a note in the docs to avoid `fmemopen()` if possible because "using `fmemopen` may inhibit important search algorithms in the fuzzing engine":

https://github.com/google/fuzzing/blob/master/docs/good-fuzz-target.md#fmemopen

When the functions being fuzzed can only take a `FILE *`, is it better to use `fmemopen()` or `fopen()`?  

@AdamKorcz, when you originally integrated igraph into OSS-fuzz, you used `fopen()` with a temporary file (https://github.com/igraph/igraph/pull/1588). Is there a reason you avoided `fmemopen()`, which should in principle be faster?

**Comment by AdamKorcz** [comment]
No particular reason! You can try and use fmemopen and see if it improves stats?
