### ISSUE TITLE
libzip access

### ISSUE THREAD

**Issue by 0-wiz-0** [google/oss-fuzz#11020]
Hi!

We're currently using a role account to access the libzip bug reports. Can you please allow us two libzip developers to access the reports via our github logins?

https://github.com/0-wiz-0
https://github.com/dillof
https://github.com/nih-at/libzip/graphs/contributors

https://github.com/google/oss-fuzz/blob/master/projects/libzip/project.yaml

Thanks, 
Thomas

**Comment by 0-wiz-0** [comment]
(admin access would be great, we can't currently access the configuration page)

**Comment by DavidKorczynski** [comment]
To get access you just need to add your email to the `auto_ccs` list here: https://github.com/google/oss-fuzz/blob/master/projects/libzip/project.yaml

**Comment by 0-wiz-0** [comment]
Thanks, @DavidKorczynski , I've sent a pull request doing that.
How can one get access to the 'Configuration' tab, or is that only useful to the oss-fuzz admins?

**Comment by DavidKorczynski** [comment]
That's not something for OSS-Fuzz users, it's for controlling the Clusterfuzz instance that is powering all of OSS-Fuzz projects (https://google.github.io/clusterfuzz/using-clusterfuzz/ui-overview/#configuration).
