### ISSUE TITLE
Requesting access for Lucene results

### ISSUE THREAD

**Issue by dsmiley** [google/oss-fuzz#11067]
I wish to investigate something the fuzzer found in Apache Lucene: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62034 However I'm confused at what is shown there.  I need to be able to click through links there for the details but I don't have access.  I'm advised to open an issue here to gain access.

FWIW I'm an Apache Lucene PMC member.

**Comment by DavidKorczynski** [comment]
It would be great to have you on the list of contacts, could you add your email as `primary_contact` here https://github.com/google/oss-fuzz/blob/3e29067ae8e22f5769060a039d628e39a7186952/projects/lucene/project.yaml#L8C17-L8C17 ?

The email has to be Google affiliated (gmail or primary email on a Google account) and once you've done this then you should be able to see all details.
