### ISSUE TITLE
The code coverage for the compress project is failed

### ISSUE THREAD

**Issue by viktoriia-lsg** [google/oss-fuzz#11081]
Hi!
I'm expanding the code coverage of the compress project. The last coverage build missed a corpus for FuzzDictBlocks fuzzer, but the previous build before did not have this error.
```
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/FuzzDictBlocks.zip or
Step #5:         /corpus/FuzzDictBlocks.zip.zip, and cannot find /corpus/FuzzDictBlocks.zip.ZIP, period.
Step #5: Failed to unpack the corpus for FuzzDictBlocks. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
```
06/10/2023 - https://oss-fuzz-build-logs.storage.googleapis.com/log-c7159d48-a59f-49b3-bb7e-9aa148881b0a.txt
05/10/2023 - https://oss-fuzz-build-logs.storage.googleapis.com/log-2c1c18a6-cb2a-42a1-bd8d-66e46c9ac549.txt

@DavidKorczynski could you please assist?

**Comment by DavidKorczynski** [comment]
Did the new fuzzers run into issues quickly? Sometimes this can cause some weird issues so best fixing those in case.

That said, this looks similar to another recent issue:
- https://github.com/google/oss-fuzz/issues/10994#issuecomment-1737055492
- https://github.com/google/oss-fuzz/issues/11010

Has this resurfaced @oliverchang ?

**Comment by viktoriia-lsg** [comment]
I also had a crash while running this fuzzer FuzzDictBlocks, but not sure that these issues are connected.

**Comment by bxa-stripe** [comment]
memcached is also experiencing this, despite running/building fine for a few days.

**Comment by fuzzy-boiii23a** [comment]
nokogiri is also facing this same issue, unsure how i can fix this as i cannot reproduce the error offline and i've kept a backup corpus in line with https://google.github.io/oss-fuzz/getting-started/new-project-guide/#seed-corpus however i'm unsure if it's being used.

**Comment by fuzzy-boiii23a** [comment]
> Sorry for the delays here.
> 
> 
> 
> `compress` appears to be working now: https://oss-fuzz-build-logs.storage.googleapis.com/log-2fc031cd-7072-4b09-ae20-3496664f9d09.txt
> 
> 
> 
> For nokogiri, there is another infra issue blocking nokogiri from being set up correctly. This should be unblocked now, and we should see the backup corpus getting created in the next few days, which will also unblock the coverage build. 
> 
> 
> 
> I'll check back on this in a few days. 

Thanks Oliver, much appreciated

**Comment by viktoriia-lsg** [comment]
@oliverchang Thanks! Should I close this issue or keep it open due to other projects?

**Comment by oliverchang** [comment]
I can see corpus backups getting created properly for nokogiri now, so the coverage job should also be getting fixed shortly. I'll close this issue, but if this still seems broken in 1-2 days please comment back.
