### ISSUE TITLE
The code coverage for FRR project is failed

### ISSUE THREAD

**Issue by Shbinging** [google/oss-fuzz#11084]
Hi! 
I use the following commands to fuzz the FRR project locally:

```bash
# Build the FRR image
python infra/helper.py build_image frr

# Build fuzzers with the address sanitizer
python infra/helper.py build_fuzzers --sanitizer address frr

# Run the fuzzer with a corpus directory
python infra/helper.py run_fuzzer --corpus-dir=./corpus frr ospfd

# Build fuzzers with coverage sanitizer
python infra/helper.py build_fuzzers --sanitizer coverage frr

# Generate coverage report for the corpus in ./corpus
python infra/helper.py coverage frr --fuzz-target=ospfd --corpus-dir=./corpus
```

The last two commands are used to generate a coverage report for the corpus in the "./corpus" directory, as indicated in the OSS-Fuzz documentation.

However, I encountered the following error message:

```bash
Running ospfd
Error occured while running ospfd:
/out/ospfd: symbol lookup error: /out/lib/libyang.so.2: undefined symbol: __asan_option_detect_stack_use_after_return
du: cannot access '/out/dumps/ospfd.*.profraw': No such file or directory
error: /out/dumps/*.profdata: No such file or directory
ERROR:__main__:Failed to generate clang code coverage report.
```
It seems that there is something wrong with libyang.so which is built in `build.sh`

**Comment by DavidKorczynski** [comment]
It's up to the respective maintainers to fix the build failure, not an OSS-Fuzz issue as such.

Please reach to the maintainers or make a PR with a fix to the relevant build script.

**Comment by DavidKorczynski** [comment]
fyi you can see the build status of all projects here: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#frr and here https://introspector.oss-fuzz.com/indexing-overview
