### ISSUE TITLE
FP crash in the compress fuzzer

### ISSUE THREAD

**Issue by viktoriia-lsg** [google/oss-fuzz#11082]
Hi!
I'm expanding the code coverage of the compress project. It started building on 05/10/2023 with new fuzzers and new corpora files.
Today I received a crash from the maintainer that likely occured due of a missing file, which is used by FuzzDictBlocks fuzzer.
```
==1366==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000280 (pc 0x00000069235f bp 0x10c000058c80 sp 0x10c000058b90 T0)
==1366==The signal is caused by a READ memory access.
==1366==Hint: address points to the zero page.
    #0 0x69235f in compress/gzip.(*Reader).Read compress/gzip/gunzip.go:247
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_compress_61346020cd6da186a08431a8ea08b78ff25812aa/revisions/FuzzDictBlocks+0x69235f)
==1366==ABORTING
```
See reports:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63006
https://oss-fuzz.com/testcase?key=5449952580730880

In detail, FuzzDictBlocks reads testdata/s2-dict.bin.gz file on the 416th row.
```
func FuzzDictBlocks(f *testing.F) {
	...
	file, err := os.Open("testdata/s2-dict.bin.gz")
```
Link to fuzzer's code: https://github.com/klauspost/compress/blob/master/s2/dict_test.go

According to fuzzing and coverage builds, this file was successfully copied from repository to the destination:
```
Step #6:   adding: testdata/s2-dict.bin.gz (stored 0%)
```
Logs of fuzzing and coverage builds:
https://oss-fuzz-build-logs.storage.googleapis.com/log-36a32235-6f7b-4f62-8eb3-0615db4fa00d.txt
https://oss-fuzz-build-logs.storage.googleapis.com/log-c7159d48-a59f-49b3-bb7e-9aa148881b0a.txt

It looks like the file cannot be found by fuzzer, but it was moved to the proper location.
@DavidKorczynski  could you please assist?

**Comment by DavidKorczynski** [comment]
Likely you are running into an issue with a file not being present at runtime which is by design. 

Please ensure the fuzzer works with the environment set out in https://google.github.io/oss-fuzz/further-reading/fuzzer-environment/

**Comment by viktoriia-lsg** [comment]
I've located it at $OUT directory, such as:
```
cp -r $SRC/compress/s2/testdata $OUT/
```
So this file will not be present at runtime environment where fuzzers, right?

**Comment by DavidKorczynski** [comment]
It will likely be there as far as I'm concerned but it's not guaranteed at what path it will be, and, specifically not guaranteed it will be in `./`. Can you embed it in your binary?

**Comment by viktoriia-lsg** [comment]
Thanks for help, will do this!
