### ISSUE TITLE
gdal builds are broken

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#1111]
@rouault can you please look into this?

[Here](https://oss-fuzz-build-logs.storage.googleapis.com/log-98aead30-f095-478a-ad7b-364fdf4c56f5.txt) are logs showing a broken build.

I think these are the important lines:
```
Step #4: ./fuzzers/build_seed_corpus.sh: line 185: cd: ./fuzzers/../../autotest/ogr/data/cad: No such file or directory
Finished Step #4
ERROR
ERROR: build step 4 "gcr.io/oss-fuzz/gdal" failed: exit status 1
```

**Comment by rouault** [comment]
Fixed per https://trac.osgeo.org/gdal/changeset/41332
