### ISSUE TITLE
CiFuzz: libc++ seems to be behind what the Clang version would suggest

### ISSUE THREAD

**Issue by randombit** [google/oss-fuzz#11116]
I'm not quite sure what's happening but it seems the Clang in CiFuzz jobs, which reports itself as Clang 15, is missing `std::ranges::fill`, which is already available in Clang 14's libc++.

This unfortunately prevents us from using certain C++ features because CiFuzz build fails :/

https://github.com/randombit/botan/actions/runs/6506193613/job/17671282348?pr=3753

Same PR with Clang 14 from 22.04 is fine:
https://github.com/randombit/botan/actions/runs/6506193607/job/17671297710?pr=3753

Any chance of updating libc++ - or maybe there is something else going on that I'm missing?

**Comment by LebedevRI** [comment]
Also just hitting this, it's weird.
https://github.com/google/oss-fuzz/blob/90d0c14a8c84c1ffcf62a5afb8fec8c0a6096fe8/infra/base-images/base-clang/checkout_build_install_llvm.sh#L53

@jonathanmetzman ?

**Comment by LebedevRI** [comment]
Actually, XCode 14.2 has the exact same failures for me, so it must have just been unimplemented in that libc++ version...

**Comment by randombit** [comment]
Is there any update here? This situation is really unfortunate since at this point OSS-Fuzz is literally the only thing holding us back from using functionality that could enable safer coding practices, namely most/all of the C++20 `std::ranges` library.

**Comment by LebedevRI** [comment]
I think https://github.com/google/oss-fuzz/pull/11714 is the latest attempt to bump the provided versions, sometimes in the future, maybe.
FWIW, i really don't understand why must the oss-provided versions be used, or why they are provided at all.

**Comment by jonathanmetzman** [comment]
>FWIW, i really don't understand why must the oss-provided versions be used, or why they are provided at all.

If everyone is on the same clang then we know we can use the same version of libFuzzer and its flags, and whatever flags centipede needs. The same is true for introspector and LLVM plugins needed by AFL++.
We also need to rebuild libc++ using MSAN for MSAN to work for most users.

**Comment by jonathanmetzman** [comment]
> Is there any update here? This situation is really unfortunate since at this point OSS-Fuzz is literally the only thing holding us back from using functionality that could enable safer coding practices, namely most/all of the C++20 `std::ranges` library.

Ah sorry, that's quite bad.
To stop blocking you, I think I have a hack you can use.
If you change the base-builder image you inherit from, from `gcr.io/oss-fuzz-base/base-builder` to `gcr.io/oss-fuzz-base/base-builder-testing-2403-roll-clang@sha256:1ddba772045a47e355df5e2b62bacc6ee3fa73ee47463d41fd818f7d8d5d6620` you should get to use LLVM 18

**Comment by jonathanmetzman** [comment]
And reopen this if it's still happening please.
