### ISSUE TITLE
OpenVPN: fuzz_route.c

### ISSUE THREAD

**Issue by headshog** [google/oss-fuzz#11128]
Hi! We were fuzzing OpenVPN with sydr-fuzz (https://github.com/ispras/oss-sydr-fuzz) and we found null-pointer dereference in `src/openvpn/route.c:2349`.
By looking at the stacktrace:

    
    #0 0xa054be in delete_route_ipv6 /openvpn/src/openvpn/route.c:2349:30
    #1 0xa0ce60 in delete_routes /openvpn/src/openvpn/route.c:1272:13
    #2 0x51d6ea in LLVMFuzzerTestOneInput /fuzz_route.c:162:9
    
I found out that in `fuzz_route.c` target there is a NULL pointer that was put in `delete_routes(&rl, &rl6, NULL, 0, c.es, &c)` at line 162. That subsequently leads to null-pointer dereference at src/openvpn/route.c:2349.

Is that a bug in fuzz target or it was intended there to be NULL?

**Comment by DavidKorczynski** [comment]
In this case it's an issue in the fuzzer -- I think the fuzzer may be a bit outdated at this point and the build has also been broken for a while.
