### ISSUE TITLE
afl fuzzer builds out of date compared to libFuzzer builds ?

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#1112]
There are two afl detected bugs in bugs.chromium.org for libreoffice, (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=5542 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4946) which link to https://oss-fuzz.com/v2/testcase-detail/5685654865313792 and https://oss-fuzz.com/v2/testcase-detail/5741892999315456

I know the bugs are fixed, but the latest afl fuzzer build seems stuck at revision 401a3d2336bf46b38235c498ff86ff675d0de759 (Nov 27, 2017) while the libFuzzer builds have definitely progressed to contemporary HEAD

Are they intentionally disabled or is there some afl specific buildfailure ?

**Comment by inferno-chromium** [comment]
Seems like a libreoffice only issue, i checked other projects they seem to have latest builds.

I see this suspicious message in logs
Step #21: <?xml version='1.0' encoding='UTF-8'?><Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message><Details>Request has expired: 1516792525</Details></Error>

@oliverchang - is libreoffice taking too long to build, so afl builds are ignored ? Should we increase the request timeout ?

**Comment by inferno-chromium** [comment]
we are not generating its coverage build as well.

Downloading https://commondatastorage.googleapis.com/clusterfuzz-builds/libreoffice/libreoffice-coverage-201801250611.zip failed.

**Comment by oliverchang** [comment]
> @oliverchang - is libreoffice taking too long to build, so afl builds are ignored ? Should we increase the request timeout ?

I've landed a possible fix. Let's see if tonight's build works.

**Comment by oliverchang** [comment]
Last night's build succeeded (`gs://clusterfuzz-builds-afl/libreoffice/libreoffice-address-201802010626.zip`).
