### ISSUE TITLE
libunistring trunk broke compile on dependent projects

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1113]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

Following projects are impacted
gnutls
knot-dns
libpsl
wget2

Same failure

```
Step #4: In file included from localcharset.c:59:
Step #4: ./langinfo.h:163:7: error: invalid token at start of a preprocessor expression
Step #4: # if !@HAVE_LANGINFO_ALTMON@
Step #4:       ^
Step #4: 1 error generated.
Step #4: Makefile:5886: recipe for target 'config.h' failed
Step #4: make[2]: *** [config.h] Error 1
Step #4: make[2]: Leaving directory '/src/libunistring/lib'
Step #4: make[1]: *** [all-recursive] Error 1
Step #4: Makefile:1558: recipe for target 'all-recursive' failed
Step #4: make[1]: Leaving directory '/src/libunistring'
Step #4: make: *** [all] Error 2
Step #4: Makefile:1486: recipe for target 'all' failed
Finished Step #4
```

+cc @jonathanmetzman current sheriff to furthur triage.

**Comment by jonathanmetzman** [comment]
Taking a look at this now.

**Comment by jonathanmetzman** [comment]
These projects all clone and build libunistring where there is a file lib/langinfo that begins with an "@" sign which is illegal for a macro.
Locally I can build libunistring if I delete the "@" signs.
Should I file a bug on whatever tracker they use?

**Comment by jonathanmetzman** [comment]
Offline we agreed to wait since this project probably wont be broken on trunk for much longer.
@alex @jfoote @rockdaboot do any of you think we should contact libunistring or want do so yourselves?

**Comment by alex** [comment]
I don't know anything about libunistring or how it interacts with the gnutls build, sorry!

cc: @nmav

**Comment by rockdaboot** [comment]
I just built libunistring successful locally. I look into it tomorrow with more time and eventually contact the gnulib maintainers. I am subscribed to the ML.

**Comment by jonathanmetzman** [comment]
Interesting. Thanks all for looking into this.

I did more digging and I think this issue isn't being directly caused by libunistring as it hasn't been changed since Dec 11th.

However it pulls in gnulib. I saw this interesting change in the gnulib ChangeLog

2018-01-24  Bruno Haible  <bruno@clisp.org>

	langinfo, nl_langinfo: Add support for alternative month names.
	* m4/langinfo_h.m4 (gl_LANGINFO_H): Define HAVE_LANGINFO_ALTMON.
	* lib/langinfo.in.h (ALTMON_1...ALTMON_12): New macros.
	* lib/nl_langinfo.c (rpl_nl_langinfo): Treat ALTMON_i like MON_i.
	* tests/test-nl_langinfo.c (main): Test ALTMON_*.
	* doc/posix-headers/langinfo.texi: Document support of ALTMON_*.
	* doc/posix-functions/nl_langinfo.texi: Likewise.

**Comment by jonathanmetzman** [comment]
After undoing the latest gnulib commit locally I was able to build libunistring, looks like that latest change is causing this breakage.

**Comment by rockdaboot** [comment]
Very quick fix made by Bruno Haible, one of the gnulib maintainers.

Libunistring builds locally again, so I assume the issue to be fixed.

**Comment by inferno-chromium** [comment]
Thanks a ton @rockdaboot 

All green!
