### ISSUE TITLE
libc++ clarification

### ISSUE THREAD

**Issue by htuch** [google/oss-fuzz#1114]
I'm working on adding Envoy support in oss-fuzz (https://github.com/envoyproxy/envoy/issues/508). Envoy uses Bazel, which does not have proper support for libc++ on Linux today. How critical is it to link against libc++ vs. libstdc++ for oss-fuzz?

**Comment by kcc** [comment]
I *think* it will be easier to make libc++ work with bazel than to make oss-fuzz work with libstdc++. 
Let me summon more folks for this discussion...

**Comment by htuch** [comment]
We could make it work in Bazel with a custom CROSSTOOLS (ignoring the autoconfigured C++ toolchain stuff). However, to do this would require some assumptions about the stability of the Docker environment. I.e. we have to balance what we hardcode in terms of paths, flags, compilers etc. We could also try and make the upstream Bazel cc_configure.bzl smart enough to know to use libc++ in some cases, but it will be a while before it merges into a release, and there is some design/implementation work there.

BTW, I'm also a Googler and happy to setup a meeting to discuss with Bazel team if necessary. Ideally we can have a short term workaround to get Envoy + oss-fuzz happening and a longer term plan to do this cleanly.

**Comment by kcc** [comment]
One ugly workaround that may work (completely untested). 
Let's start with just asan and just libFuzzer.

* build your fuzz target as `.a` file (w/o main) in a similar way to [what grpc does](https://github.com/google/oss-fuzz/blob/master/projects/grpc/build.sh)
* build your own copy of libFuzzer with libstdc++, link it against your `.a`. 

Building your own libFuzzer should be pretty trivial: 
   * In docker file, `svn co https://llvm.org/svn/llvm-project/compiler-rt/trunk/lib/fuzzer MyLibFuzzer`
   * In build file `cd MyLibFuzzer && ./build.sh` or some such

I really hope we'l have a better solution built into bazel *soon*-ish

**Comment by htuch** [comment]
In can try that. Which fuzzers and sanitizers have a hard dependency on
libc++?

**Comment by kcc** [comment]
msan won't work w/o libc++. 

the libFuzzer build provided by oss-fuzz docker requires libc++, but you can build libFuzzer yourself to drop this requirement. (as a workaround!! We don't want everyone to do this)
In LLVM trunk, libFuzzer already uses its own private copy of libc++, so we'll eventually lift this limitation. 

AFL probably doesn't care. 

libc++ is *good to have* with asan because this way we'll find more bugs (libc++ is instrumented, libstdc++ is not)

**Comment by inferno-chromium** [comment]
@htuch - any other questions, otherwise feel free to close this.

**Comment by htuch** [comment]
@inferno-chromium Will close, thanks all for the replies. The actionable followup is now tracked at https://github.com/bazelbuild/bazel/issues/4524.
