### ISSUE TITLE
False positive?

### ISSUE THREAD

**Issue by FrancescAlted** [google/oss-fuzz#11166]
Hi.  In https://github.com/Blosc/c-blosc2/pull/567 we have been trying to cope with a possible issue raised by oss-fuzz.  However, we cannot reproduce it in our Ubuntu boxes, and furthermore, we don't think we are doing anything controversial in the pointed function.

Is there a way to silence a potential false positive using oss-fuzz?

Thanks in advance.

**Comment by DavidKorczynski** [comment]
I tried reproducing and was also unable to.

Is there a way you can guard against the potential issue suggested here https://github.com/Blosc/c-blosc2/pull/567#issuecomment-1785790518 ?

When build in fuzzer mode a fuzzer-specific macro is defined: `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` [see here for more details](https://llvm.org/docs/LibFuzzer.html#fuzzer-friendly-build-mode) -- would it be possible to use this macro? around the area that complains with some alternative logic?

**Comment by FrancescAlted** [comment]
Recently I did [some commit](https://github.com/Blosc/c-blosc2/pull/567/commits/5cd384c9a65cafb983de116db86ea990a545bfee) that seems to fix the issues with OSS-Fuzz.  Not sure why they are passing now, because I did not touch anything special affecting the Linux/Clang platform that uses OSS-Fuzz.  Did you fixed something on the OSS-Fuzz side of the things?  Anyway, happy this seems fixed now.

**Comment by FrancescAlted** [comment]
Happy to see the issue gone (but still scratching my head :-)
