### ISSUE TITLE
Add fuzzer for UBJSON input in nlohmann/json

### ISSUE THREAD

**Issue by nlohmann** [google/oss-fuzz#1120]
I added a fuzzer for UBJSON input (see https://github.com/nlohmann/json/commit/f0b26c8f38e97bf0392cbefe64080f832849a73a). The project [nlohmann/json](https://github.com/nlohmann/json) is checked as "json" in OSS-Fuzz.

Could you please add the json_parse_ubjson_fuzzer to OSS-Fuzz, or tell me how I can do this myself?

**Comment by nlohmann** [comment]
In the meantime, I already got an issue (https://oss-fuzz.com/testcase?key=6526515224248320) for the UBJSON parser.

So:

- Either the fuzzer was automatically added, so this ticket can be closed.
- Or someone already addressed this issue, so the ticket can also be closed.

Thanks a lot!

**Comment by kcc** [comment]
Isn't this because https://github.com/google/oss-fuzz/blob/master/projects/json/build.sh has a `for` loop over all executables found in `./test` ?

**Comment by nlohmann** [comment]
Right, totally forgot about that. Thanks for pointing this out!
