### ISSUE TITLE
`pandas` coverage issue

### ISSUE THREAD

**Issue by nmlsg** [google/oss-fuzz#11210]
Hi,

I contributed to and expanded the pandas project two days ago. Recently, I noticed in the logs that the coverage build failed (link: [here](https://oss-fuzz-build-logs.storage.googleapis.com/log-fea2314d-4491-49c9-b6f7-23609fdbe6eb.txt)).

I suspect this is due to a quota issue similar to the one described here: https://github.com/google/oss-fuzz/issues/11010

Here's the error I observed:

```

Step #5: [/corpus/fuzz_to_datetime.zip]
Step #5:   End-of-central-directory signature not found. Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive. In the
Step #5:   latter case, the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
```
This same error appeared for all newly added fuzzers.

@DavidKorczynski and @oliverchang, could you please take a look?

**Comment by oliverchang** [comment]
@jonathanmetzman can you please take a look here? Something seems to be going wrong with corpus pruning for these new targets. Likely the same root cause as #11154

**Comment by oliverchang** [comment]
It looks like the latest build is succeeding now, so it may have just been a matter of time for the new targets to get picked up:

**Comment by nmlsg** [comment]
Hi, @oliverchang 
I could only see 2 new fuzz targets in the report
Could you somehow clarify what ?

[latest coverage](https://storage.googleapis.com/oss-fuzz-coverage/pandas/reports/20231113/linux/index.html)
