### ISSUE TITLE
Access to dashboard with different email

### ISSUE THREAD

**Issue by MatthiasVC** [google/oss-fuzz#11211]
Hello,

I am the maintainer of [Wt ](https://github.com/emweb/wt), we recently integrated with this project. On your [documentation](https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/) it states that the `primary_contact` should be an email with an attached Google email, not an alias (which is what we currently use, so that multiple people get send notifications).

However, we would like to set it up in such a way that multiple people in our organization have access to the https://oss-fuzz.com dashboard (and its reports). Is this currently possible? If so, how can I enable this access. If it isn't, could this be implemented? Maybe something along the lines of an additional variable `access-emails` that can take a list of email addresses allowed to access the page?

**Comment by DavidKorczynski** [comment]
Use `auto_ccs` -- each email on this list has access to the same data as `primary_contact`. See Envoy as an example:

https://github.com/google/oss-fuzz/blob/a37f61012d54764b724ed2d5610199adb3be6ea5/projects/envoy/project.yaml#L4-L23

**Comment by MatthiasVC** [comment]
Oh ok, thank you I was not aware of this.
I have created a PR:  #11222.
