### ISSUE TITLE
Can't access the reports to respond to either of these

### ISSUE THREAD

**Issue by t3lurid3** [google/oss-fuzz#11243]
https://github.com/facebook/time/issues/309

OSS-Fuzz issue 64279

OSS-Fuzz has found a bug in this project. Please see https://oss-fuzz.com/testcase?key=4666103720443904 for details and reproducers.

This issue is mirrored from https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64279 and will auto-close if the status changes there.

If you have trouble accessing this report, please file an issue at https://github.com/google/oss-fuzz/issues/new.

https://github.com/facebook/time/issues/310

OSS-Fuzz issue 64287

OSS-Fuzz has found a bug in this project. Please see https://oss-fuzz.com/testcase?key=5939434687954944 for details and reproducers.

This issue is mirrored from https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64287 and will auto-close if the status changes there.

If you have trouble accessing this report, please file an issue at https://github.com/google/oss-fuzz/issues/new.

**Comment by t3lurid3** [comment]
and you have just opened https://github.com/facebook/time/issues/311 - you may want to hold off on opening more issues with us for now if you don't mind. That's 3 in about 2 hours.

**Comment by oliverchang** [comment]
Hi! can you please add your email to https://github.com/google/oss-fuzz/blob/master/projects/time/project.yaml under "auto_ccs" ? This will grant you access, provided the account is associated with a Google account.

**Comment by t3lurid3** [comment]
Have access now, thanks
