### ISSUE TITLE
iCalendar Ideal Integration Status

### ISSUE THREAD

**Issue by ennamarie19** [google/oss-fuzz#11293]
Hello,
I submitted the Integration Reward Google form over 2 weeks ago for my project icalendar but have not heard anything from the OSS-Fuzz team. Could you confirm that you received my submission?

Thank you!

**Comment by oliverchang** [comment]
We've processed this reward at the end of last year. 

Note that we may take up to a month in some circumstances before we are able to respond on these submissions. Thank you for your patience.

**Comment by oliverchang** [comment]
Please do not use the OSS-Fuzz issue tracker to follow up on these requests. 

Thank you all for the submissions -- rewarding can take a bit of time for our team, particularly during the December/January months as people go OOO. Your patience is appreciated.
