### ISSUE TITLE
How to launch the container in privileged mode?

### ISSUE THREAD

**Issue by Sadiq1811** [google/oss-fuzz#11301]
My fuzzing harness fails as it isn't able to access some kernel filesystems (Ex: /dev).
So i was wondering if the container can be launched in privileged mode.

Adding the "--privileged" option to the "docker run" command can be used.
But how do i activate this in the OSS-FUZZ infrastructure?

**Command used:** `python infra/helper.py run_fuzzer <project> <fuzz_harness_binary>`

**Comment by Sadiq1811** [comment]
@DavidKorczynski can't we modify the infra/helper.py script to accept "--privileged" option for the "docker run" command?

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski can't we modify the infra/helper.py script to accept "--privileged" option for the "docker run" command?

This won't have an impact for the fuzzers when running in the cloud (by way of [clusterfuzz](https://github.com/google/clusterfuzz)).

Are there options for doing more compositional fuzzing such that the fuzzers do not rely on these folders? or mocking of sorts?

**Comment by Sadiq1811** [comment]
@DavidKorczynski not sure about this. I am fairly new to OSS-FUZZ.
Closing the issue for now.
Thanks for the support.
