### ISSUE TITLE
Crash stats not updated since Nov 24, 2023

### ISSUE THREAD

**Issue by mbroz** [google/oss-fuzz#11306]
Hi,

when I select crash stats in oss-fuzz (for cryptsetup project or util-linux), I see that
"The statistics have been aggregated until Nov 24, 2023, 12 PM" and there are no new data since then.
Seems automatic closing of bugs is not run too...

Is there any problem with updating statistics there?

**Comment by IvanNardi** [comment]
Same issue with nDPI project...

**Comment by oliverchang** [comment]
Sorry for the slow reply! One of our aggregation jobs was stuck. I've restarted this and we will be backfilling all the data up to today.

**Comment by IvanNardi** [comment]
Stats seem fine, now. Thank you!

**Comment by mbroz** [comment]
Yes, it looks ok now. Thanks!
