### ISSUE TITLE
/corpus/decompress_packed_file_fuzzer.zip error

### ISSUE THREAD

**Issue by jreiser** [google/oss-fuzz#11402]
The fuzzing process suffered an internal error that cannot be blamed on the project being fuzzed, which is **upx**.  In general, the error message is consistent with running out of disk space, but there can be other reasons instead, and ENOSPC does not appear explicitly in the log.

Top level:  https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65302
Build log: https://oss-fuzz-build-logs.storage.googleapis.com/log-6ec3ffcd-bdbc-488a-b166-7d9f5f5111c4.txt
Error context:
```
Finished Step #4
Starting Step #5
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: [/corpus/decompress_packed_file_fuzzer.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/decompress_packed_file_fuzzer.zip or
Step #5:         /corpus/decompress_packed_file_fuzzer.zip.zip, and cannot find /corpus/decompress_packed_file_fuzzer.zip.ZIP, period.
Step #5: Failed to unpack the corpus for decompress_packed_file_fuzzer. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.

```

**Comment by jreiser** [comment]
What is the PROJECT_NAME for this project?  Where is it supposed to be set?

After installing **gsutil**, then I run the test:
```
$ gsutil ls gs://${PROJECT_NAME}-corpus.clusterfuzz-external.appspot.com/
BucketNotFoundException: 404 gs://-corpus.clusterfuzz-external.appspot.com bucket does not exist.
```
which is consistent with PROJECT_NAME not set.  (Bug: the directions should have specified `${parameter:?word}`  which checks for the existence of shell variable `parameter`, and gives an error message if not set.)

**Comment by jreiser** [comment]
I also tried:
```
$ export PROJECT_NAME=oss-fuzz-upx
$ gsutil ls gs://${PROJECT_NAME}-corpus.clusterfuzz-external.appspot.com/
BucketNotFoundException: 404 gs://oss-fuzz-upx-corpus.clusterfuzz-external.appspot.com bucket does not exist.


$ export PROJECT_NAME=upx
$ gsutil ls gs://${PROJECT_NAME}-corpus.clusterfuzz-external.appspot.com/
AccessDeniedException: 403 reiser.john@gmail.com does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
```

**Comment by jreiser** [comment]
Proceeding with the suggestions in the initial report of failure of coverage, namely:
```
Step #5: ********************************************************************************
Step #5: Code coverage report generation failed.
Step #5: To reproduce, run:
Step #5: python infra/helper.py build_image upx
Step #5: python infra/helper.py build_fuzzers --sanitizer coverage upx
Step #5: python infra/helper.py coverage upx
Step #5: ********************************************************************************
```
1. python infra/helper.py build_image upx   # Succeeds
2. python infra/helper.py build_fuzzers --sanitizer coverage upx   # Succeeds
3. python infra/helper.py coverage upx   # Gives warnings, starts http server, waits forever

The first few lines on Terminal are:
```
$ python infra/helper.py coverage upx
INFO:__main__:Downloading corpora for upx project to /Sam2T/home/jreiser/oss-fuzz/build/corpus/upx.
AccessDeniedException: 403 reiser.john@gmail.com does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
AccessDeniedException: 403 reiser.john@gmail.com does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
AccessDeniedException: 403 reiser.john@gmail.com does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
WARNING:__main__:Corpus for upx_test_packed_file_fuzzer not found:

WARNING:__main__:Corpus for upx_list_packed_file_fuzzer not found:

WARNING:__main__:Corpus for upx_decompress_packed_file_fuzzer not found:

INFO:__main__:Running: docker run --rm --privileged --shm-size=2g --platform linux/amd64 -i -e FUZZING_ENGINE=libfuzzer -e HELPER=True -e FUZZING_LANGUAGE=c++ -e PROJECT=upx -e SANITIZER=coverage -e COVERAGE_EXTRA_ARGS= -e ARCHITECTURE=x86_64 -e HTTP_PORT=8008 -p 8008:8008 -v /Sam2T/home/jreiser/oss-fuzz/build/corpus/upx:/corpus -v /Sam2T/home/jreiser/oss-fuzz/build/out/upx:/out -t gcr.io/oss-fuzz-base/base-runner coverage.
Running list_packed_file_fuzzer
Running test_packed_file_fuzzer
Running decompress_packed_file_fuzzer
```

The last few lines on Terminal are:
```
[2023-12-30 17:33:12,282 DEBUG] Writing per-directory coverage html reports.
[2023-12-30 17:33:12,409 DEBUG] Finished writing per-directory coverage html reports.
[2023-12-30 17:33:12,409 DEBUG] Generating directory view html index file as: "/out/report_target/decompress_packed_file_fuzzer/linux/directory_view_index.html".
[2023-12-30 17:33:12,409 DEBUG] Finished generating directory view html index file.
[2023-12-30 17:33:12,409 INFO] Index file for html report is generated as: "file:///out/report_target/decompress_packed_file_fuzzer/linux/index.html".
Serving the report on http://127.0.0.1:8008/linux/index.html
Serving HTTP on 0.0.0.0 port 8008 (http://0.0.0.0:8008/) ...
```

Browsing to http://127.0.0.1:8008/linux/src/report.html does give a coverage report, but it is usable for "eyeballs only"; there is no option to "download" tables which can be processed by text editor, spreadsheet, 'dot' graphics program, etc.

**Comment by MykolaMykhno** [comment]
This issue looks similar to https://github.com/google/oss-fuzz/issues/11010
@DavidKorczynski Could you please check upx coverage report generation, because locally it builds but on oss fuzz infrastructure we have problem.

**Comment by DavidKorczynski** [comment]
Yes, this is a quota problem as far as I can tell. @oliverchang do you have any insights if this will be resolved automatically?

**Comment by jreiser** [comment]
As I diagnosed in https://github.com/google/oss-fuzz/issues/11010#issuecomment-1875852761 , there is a bug in the **zip** utility: no explicit `close()` of the output file, so no catch-and-report of EDQUOT exceeding disk space quota.  The system action is to truncate the file as much as necessary to not exceed the quota.  Therefore SILENT LOSS OF DATA, which has been observed several times in the last 4 months.  Increasing the quota merely postpones the next occurrence of the bug.  The source code of **zip** must be fixed.

**Comment by oliverchang** [comment]
Thanks for the investigation! The underlying build error you're seeing is due to a different problem we were encountering, which should be getting resolved now. I can see the upx is starting to be properly fuzzed now with some bugs being filed now. 

The coverage build error should be resolved in the next day or so.

**Comment by oliverchang** [comment]
Looks like the latest coverage build works now. Sorry again for the noise here!
