### ISSUE TITLE
Quantlib project not fuzzing

### ISSUE THREAD

**Issue by silvergasp** [google/oss-fuzz#11426]
I previously opened #11234, which was closed automatically via a PR. However the PR didn't fix the issue. I'm able to see quantlib on ossfuzz.com e.g.

![image](https://github.com/google/oss-fuzz/assets/7277663/6632b56c-b2b6-4c7b-b9aa-9ba7d48240ef)

However the fuzzing stats seem to be empty.

I'm also unable to see it in the [build status](https://oss-fuzz-build-logs.storage.googleapis.com/index.html). I'm kind of stumped as to what the issue is.

**Comment by DavidKorczynski** [comment]
I think this is likely a quota issue, which is currently happening for other newly integrated projects https://github.com/google/oss-fuzz/issues/11402

**Comment by oliverchang** [comment]
I believe this is due to https://github.com/google/oss-fuzz/commit/3fde24173b293cdc4896e8b0c4d1c4fdef5764db. I've now removed it -- let's see if builds start coming through now.

**Comment by oliverchang** [comment]
> I think this is likely a quota issue, which is currently happening for other newly integrated projects #11402

There is another infrastructure issue blocking https://github.com/google/oss-fuzz/issues/11402, https://github.com/google/oss-fuzz/issues/11306 and probably others. 

This should all be fixed shortly (and prevented from occurring again in the future) after https://github.com/google/clusterfuzz/pull/3614

**Comment by silvergasp** [comment]
Cool, it looks like its building again now. Although the build is now broken. I made some changes, which I'm hoping will fix the problem for the next round of builds.

**Comment by oliverchang** [comment]
I see stats now on https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2023-12-31&date_end=2024-01-06&fuzzer=libFuzzer&job=libfuzzer_asan_quantlib&project=quantlib. Closing!
