### ISSUE TITLE
ffmpeg build failing

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#1146]
From https://oss-fuzz-build-logs.storage.googleapis.com/log-cee893d3-914a-4849-b4b3-ed8624db0c55.txt:

```
Step #4: + for c in '$CONDITIONALS'
Step #4: + fuzzer_name=ffmpeg_AV_CODEC_ID_AASC_fuzzer
Step #4: ++ git grep 'REGISTER_[A-Z]*DEC[A-Z ]*(AASC *,' libavcodec/allcodecs.c
Step #4: ++ sed 's/.*, *\([^) ]*\)).*/\1/'
Step #4: + symbol=
Step #4: + echo -en '[libfuzzer]\nmax_len = 1000000\n'
Step #4: + make tools/target_dec__fuzzer
Step #4: make: *** No rule to make target 'tools/target_dec__fuzzer'.  Stop.
Finished Step #4
```

**Comment by oliverchang** [comment]
@michaelni could you please take a look?

**Comment by michaelni** [comment]
allcodecs.c was changed in https://github.com/FFmpeg/FFmpeg/commit/7e8eba2d8755962d9dca5eade57bf8f591a73c0c
so the grep/sed command will need an update unless this gets reverted (there was some disucssion about revert and one patch from this patchset was reverted). Its possible this will be changed again in the comming weeks as people seem not to agree on the API. So it may be needed to update the grep/sed more than once sadly
