### ISSUE TITLE
Please stop with the "this is a top crasher for... " emails

### ISSUE THREAD

**Issue by mtklein** [google/oss-fuzz#1148]
These notes from Clusterfuzz-External read like they know something we humans don't.  We can prioritize fuzzer bugs, and don't need the added prodding from a bot.  I don't want someone who's new to things to be tricked into thinking some fuzzer bugs are more important than others.  Attaching the label "Labels: ClusterFuzz-Top-Crash" is going stress people out.

If it simply said "This fuzzer bug represents a class of bugs that the fuzzer seems to fall more often than most.  Fixing this one issue will open the most doors for future fuzzing." I'd be totally on board.  It's just that's what written right now is overly scary and not really very descriptive.

**Comment by inferno-chromium** [comment]
Thanks a lot for reporting this. We agree with your sentiment and working on a fix.

**Comment by inferno-chromium** [comment]
The new message will look like

"This crash occurs very frequently on linux platform and is likely preventing the fuzzer fuzz_target1 from making much progress. Fixing this will allow more bugs to be found.

If this is incorrect, please file a bug on https://github.com/google/oss-fuzz/issues/new"

and we add Fuzz-Blocker label.

**Comment by inferno-chromium** [comment]
Note that all these fuzz blocker message are based on top crashes for a particular (project, platform) combination.

**Comment by mtklein** [comment]
Thank you.  The new messages are very clear!
