### ISSUE TITLE
md4c: Most (if not all) issues got stuck in a pending state

### ISSUE THREAD

**Issue by mity** [google/oss-fuzz#11490]
Some days ago, I've committed https://github.com/mity/md4c/commit/d775b5103ee130edbd808e21d1da6ca75f76a558 and https://github.com/mity/md4c/commit/c6942ef03ed46a67bd9b3af8ce1eefd781622777 which should fix most (if not all) reported issues, including these:

- https://oss-fuzz.com/testcase-detail/4508383846203392
- https://oss-fuzz.com/testcase-detail/5142007786635264
- https://oss-fuzz.com/testcase-detail/5609076764573696

Crash statistics at oss-fuzz.com seems to confirm that. 

Yet all those issue reports seem to be stuck in

```
Status: Pending, refreshes every 5 minutes.
Fixed: Pending
```

And metadata at the bottom of the page usually say something like this:
```
[2024-01-09 03:54:37 UTC] oss-fuzz-linux-zone8-host-k2vd-0: Progression task started.
```
as the most recent message.

Can you please have a look at it?

**Comment by oliverchang** [comment]
Thanks for the report! Looks like most of these machines were stuck with disk space issues. I've recreated them and they should be getting unblocked now.
