### ISSUE TITLE
Assigning an owner to bug on the issue tracker

### ISSUE THREAD

**Issue by matt-kwong** [google/oss-fuzz#1150]
When new issues are opened on the bug tracker, is there a way for anyone on the CC list to be able to assign the bug to someone else on the CC list? I also don't see a way to assign myself as the owner of an issue. Is this feature not available or am I missing where to do this on the bug page? Thanks

**Comment by inferno-chromium** [comment]
We currently only allow people to be cced. Since ClusterFuzz automatically verifies fixes and closes issues, we don't need to assign bugs to specific people, and ask them for closing bug.
