### ISSUE TITLE
node.js fuzzers seem to not be running

### ISSUE THREAD

**Issue by AdamKorcz** [google/oss-fuzz#11538]
It looks like the Node.js fuzzers do not run. Considerations:

1. The stats page returns a 404 error: https://oss-fuzz.com/fuzzer-stats?project=nodejs&fuzzer=libFuzzer&job=libfuzzer_asan_nodejs&group_by=by-fuzzer
2. The coverage build fails because of missing corpus for some fuzzers.

We recently added a lot (almost 50) fuzzers for Node.js. Prior to this, Node.js was already failing on and off from resource limitations.

**Comment by DavidKorczynski** [comment]
@jonathanmetzman did you have a chance to look at this?

**Comment by jonathanmetzman** [comment]
Everyone I've checked seems to work. Which in particular aren't running?
https://oss-fuzz.com/fuzzer-stats?project=d3&fuzzer=libFuzzer&job=libfuzzer_nosanitizer_d3&group_by=by-fuzzer - crashes on every run.
https://oss-fuzz.com/fuzzer-stats?project=jimp&fuzzer=libFuzzer&job=libfuzzer_nosanitizer_jimp&group_by=by-fuzzer
https://oss-fuzz.com/fuzzer-stats?project=js-yaml&fuzzer=libFuzzer&job=libfuzzer_nosanitizer_js-yaml&group_by=by-fuzzer
https://oss-fuzz.com/fuzzer-stats?project=ua-parser-js&fuzzer=libFuzzer&job=libfuzzer_nosanitizer_ua-parser-js&group_by=by-fuzzer
https://oss-fuzz.com/fuzzer-stats?project=d3&fuzzer=libFuzzer&job=libfuzzer_nosanitizer_d3&group_by=by-fuzzer

**Comment by mzlatko8219** [comment]
Am Do., 14. März 2024 um 22:52 Uhr schrieb jonathanmetzman <
***@***.***>:

**Comment by AdamKorcz** [comment]
> Everyone I've checked seems to work. Which in particular aren't running? https://oss-fuzz.com/fuzzer-stats?project=d3&fuzzer=libFuzzer&job=libfuzzer_nosanitizer_d3&group_by=by-fuzzer - crashes on every run. https://oss-fuzz.com/fuzzer-stats?project=jimp&fuzzer=libFuzzer&job=libfuzzer_nosanitizer_jimp&group_by=by-fuzzer https://oss-fuzz.com/fuzzer-stats?project=js-yaml&fuzzer=libFuzzer&job=libfuzzer_nosanitizer_js-yaml&group_by=by-fuzzer https://oss-fuzz.com/fuzzer-stats?project=ua-parser-js&fuzzer=libFuzzer&job=libfuzzer_nosanitizer_ua-parser-js&group_by=by-fuzzer https://oss-fuzz.com/fuzzer-stats?project=d3&fuzzer=libFuzzer&job=libfuzzer_nosanitizer_d3&group_by=by-fuzzer

I am getting "Got error with status: 403" on all of these links an no stats.

**Comment by jonathanmetzman** [comment]
403 is forbidden. Do you have access to every project in OSS-Fuzz already? If not do you want access?

**Comment by DavidKorczynski** [comment]
> 403 is forbidden. Do you have access to every project in OSS-Fuzz already? If not do you want access?

Hmm -- I get 403 as well, but we should have access? https://github.com/google/oss-fuzz/blob/94f13c36742f4002eb3f9f338526e7886e48862b/projects/nodejs/project.yaml#L8-L10

**Comment by AdamKorcz** [comment]
I am getting 404 here: https://oss-fuzz.com/fuzzer-stats?project=nodejs&fuzzer=libFuzzer&job=libfuzzer_asan_nodejs&group_by=by-fuzzer

**Comment by mzlatko8219** [comment]
Am Do., 14. März 2024 um 23:34 Uhr schrieb AdamKorcz <
***@***.***>:

**Comment by mzlatko8219** [comment]
bekome ich was geld


Am Do., 14. März 2024 um 23:55 Uhr schrieb Zlatko Ma ***@***.***

**Comment by jonathanmetzman** [comment]
> > 403 is forbidden. Do you have access to every project in OSS-Fuzz already? If not do you want access?
> 
> Hmm -- I get 403 as well, but we should have access (happy to do get access in general -- I could see it being useful -- but I think we should still be able to see the data)?
> 
> https://github.com/google/oss-fuzz/blob/94f13c36742f4002eb3f9f338526e7886e48862b/projects/nodejs/project.yaml#L8-L10
> 
> Ah, I just saw the query was a general query? Then, yes, general access would be nice to have in these cases.

OOOO I thought you meant javascript projecsts, my bad.

**Comment by jonathanmetzman** [comment]
Let me look into nodejs

**Comment by jonathanmetzman** [comment]
It looks like a disk space issue.

**Comment by jonathanmetzman** [comment]
The builds are pretty big. Let me find out how we bump the disk for certain projects.

**Comment by mzlatko8219** [comment]
@ Ich.

**Comment by jonathanmetzman** [comment]
I'm not sure why I thought it was a disk space issue. I think I know what the issue is now. Sorry for the too long delay in fixing this.

**Comment by jonathanmetzman** [comment]
Haha I got confused again by node vs javascript fuzzers (which do seem broken)

**Comment by DavidKorczynski** [comment]
@jonathanmetzman did you have a chance to look at this?

**Comment by jonathanmetzman** [comment]
Should be fixed in a day or so.

**Comment by DavidKorczynski** [comment]
Thanks a ton @jonathanmetzman Can confirm it's working now
