### ISSUE TITLE
enable -fsanitize=alignment for ubsan 

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#1156]
See https://github.com/google/oss-fuzz/issues/1154 for a motivating case. 
But this could cause huge amount of noise (real, but not very interesting bugs), so we should be careful. 
(probably not urgent)

**Comment by inferno-chromium** [comment]
We can target this in early Q2. Or i will see if i get cycles to add this.

**Comment by inferno-chromium** [comment]
tracked in https://github.com/google/oss-fuzz/issues/232
