### ISSUE TITLE
InChI project now on GitHub - update link / new version

### ISSUE THREAD

**Issue by kiddr** [google/oss-fuzz#11591]
Hi - the InChI project is now fully on github: https://github.com/IUPAC-InChI/InChI

I know you had to update the url before to load in the new release source code - I don't know if this should happen differently now we're on github, but let us know what we should do to routinely update for new versions. 

The current beta should have all the outstanding bugs fixed that you've notified us about - is it possible to plug this new beta in oss-fuzz to test? 
https://github.com/IUPAC-InChI/InChI/releases/tag/v1.07-beta.3

Many thanks

**Comment by DavidKorczynski** [comment]
Hi @kiddr - I have updated the project to use the GitHub repository here https://github.com/google/oss-fuzz/pull/11598

This should now work on the latest repo.
