### ISSUE TITLE
libass build failing

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1160]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

@astiob, @wm4, @astiob, @MrSmile - can you please take a look.

**Comment by astiob** [comment]
It’s failing when trying to build FriBiDi. It appears that just three days ago, in fribidi/fribidi@8576118c37c8fd0b03f18ba1e56cedbcd5bd658d, they replaced the `bootstrap` script with an `autogen.sh`.

It seems that replacing https://github.com/google/oss-fuzz/blob/106bb66541e9156fcfd0b1b3cf19e7db57ddbe37/projects/libass/build.sh#L19-L20 with a single call to `./autogen.sh --enable-static=yes --enable-shared=no --with-pic=yes --prefix=/work/` should do the trick.

**Comment by inferno-chromium** [comment]
@astiob - now we are running into

checking for c2man... no
configure: error: c2man is required to build documentation
fuzzers build failed.

can you please confirm the build works with python infra/helper.py build_fuzzers libass
and submit a pull request to fix this. Thanks!

**Comment by astiob** [comment]
Add `--disable-docs` to the same line (which was also added only a few days ago in fribidi/fribidi@21b18b07c0b57fbaff15b622df80408cf8936809).

I appreciate that it is in our own best interests that the fuzzer runs smoothly, but I don’t currently have oss-fuzz set up, and https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md unfortunately isn’t terribly clear on how I should go about setting one up in the least painful way, either (how do I even start? git checkout oss-fuzz? then just run `python infra/helper.py build_fuzzers libass` and it will do everything for me? what does “latest build” mean here? do I need Docker? I don’t know anything about Docker and therefore assume that I don’t want it, if I may be very blunt; I also don’t have free disk space, which sounds like a problem from what I’m reading on the oss-fuzz pages about Docker).

**Comment by inferno-chromium** [comment]
yes @astiob - just three things
1. Check OSS-Fuzz github repo.
2. Install docker using instructions from https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md#prerequisites
3. python infra/helper.py build_fuzzers libass
that will build libass from source.

let me add --disable-docs for now and see if build works.

**Comment by inferno-chromium** [comment]
Yes that fixes it.
