### ISSUE TITLE
unrar build failing

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1163]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

@aawc - can you please take a look.

**Comment by aawc** [comment]
Can you please assign it to me?

Also, any chance that the flags passed to the make command changed somehow?

**Comment by inferno-chromium** [comment]
@aawc - can't assign since you are not a oss-fuzz team member.

i dont think this is a make flag issue, probably some function changed.

```
Step #4: /src/unrar/unrar_fuzzer.cc:15:13: error: no member named 'SetArcInMem' in 'CommandData'
Step #4:   cmd_data->SetArcInMem(const_cast<unsigned char *>(data), size);
Step #4:   ~~~~~~~~  ^
Step #4: 1 error generated.
Finished Step #4
ERROR
```

**Comment by inferno-chromium** [comment]
now fixed
