### ISSUE TITLE
Total coverage does not work for large projects, move to Clang Coverage

### ISSUE THREAD

**Issue by reaperhulk** [google/oss-fuzz#1166]
For GraphicksMagick & ImageMagick when I click the "Total Coverage" button I get "Failed to get coverage report". Is this expected behavior or is there something we need to change to make oss-fuzz capable of generating these reports properly?

**Comment by inferno-chromium** [comment]
i can load both
https://oss-fuzz.com/coverage_report/fuzzer/libFuzzer_graphicsmagick_coder_3FR_fuzzer/2018-02-14
and
https://oss-fuzz.com/coverage_report/fuzzer/libFuzzer_imagemagick_crop_fuzzer/2018-02-14

can you give some examples where it is failing.

**Comment by inferno-chromium** [comment]
Did you mean error like

Couldn't load file content {"vcs_url":"http://hg.code.sf.net/p/graphicsmagick/code","path":"/magick/color_lookup.c","revision":"f96c32ca07a98984311fcaa31286bca4edd5229e"}: 404 ?
on https://oss-fuzz.com/coverage_report/fuzzer/libFuzzer_graphicsmagick_coder_3FR_fuzzer/2018-02-14/f/%2Fsrc%2Fgraphicsmagick%2Fmagick%2Fcolor_lookup.c

**Comment by alex** [comment]
I'm not on the right computer to verify, but I believe @reaperhulk is talking about the "global coverage" button that's on the home page, that's supposed to aggregate all coverage from all fuzzers.

**Comment by inferno-chromium** [comment]
@alex @reaperhulk - global coverage currently has issues with aggregation for too many fuzz targets, it breaks there. we are planning to move away from sanitizer coverage to clang source code based code coverage, that would fix this, but it is still few months away.

**Comment by alex** [comment]
Sounds like the correct thing to do is update the title to be accurate an wait for that :-)

**Comment by reaperhulk** [comment]
Excellent, thanks for the quick responses!

**Comment by inferno-chromium** [comment]
Duplicate of https://github.com/google/oss-fuzz/issues/799, and work tracked there.
