### ISSUE TITLE
Targeted languages execution environments?

### ISSUE THREAD

**Issue by pettermahlen** [google/oss-fuzz#117]
This looks interesting, but it's not clear to me from the documentation where you can use it. From the looks of the examples, it seems to be only for native libraries, written in C/C++? Is that correct? Would it be possible to add some information about where it is intended to be used to the README?

**Comment by kcc** [comment]
Thanks for the note. I've added this to the front page: 

Currently OSS-Fuzz supports C and C++ code (other languages supported by LLVM may work too).
