### ISSUE TITLE
OpenSSL Fuzz Introspector build timeout

### ISSUE THREAD

**Issue by kroeckx** [google/oss-fuzz#11706]
This log:
https://oss-fuzz-build-logs.storage.googleapis.com/log-6c267c4b-0002-41a8-9af0-65487323c6c8.txt

End with:
```
Step #6 - "compile-libfuzzer-introspector-x86_64": 2024-03-16 10:52:46.493 INFO debug_info - extract_all_functions_in_debug_info: Extracting functions
Step #6 - "compile-libfuzzer-introspector-x86_64": 2024-03-16 10:52:47.291 INFO debug_info - load_debug_all_yaml_files: Set base loader to use CSafeLoader
Step #6 - "compile-libfuzzer-introspector-x86_64": 2024-03-16 11:13:46.995 INFO debug_info - load_debug_all_yaml_files: Set base loader to use CSafeLoader
Step #6 - "compile-libfuzzer-introspector-x86_64": Correlating
TIMEOUT
ERROR: context deadline exceeded
```

**Comment by IvanNardi** [comment]
Same issue on nDPI project since 10 March: latest log https://oss-fuzz-build-logs.storage.googleapis.com/log-0e5ccc8b-1c53-4b7e-8e19-5b2b531ce9a2.txt

**Comment by IvanNardi** [comment]
Any updates about this issue?

**Comment by qkaiser** [comment]
Similar output observed with unblob. See https://oss-fuzz-build-logs.storage.googleapis.com/log-feef94eb-5c75-40db-b693-e94148b167be.txt

**Comment by DavidKorczynski** [comment]
Apologies for the delay, I will look at solutions today

**Comment by IvanNardi** [comment]
Very sorry to keep bothering you, guys... any updates?

**Comment by DavidKorczynski** [comment]
Sorry for the slowness here -- I've located the bottleneck, am working on a fix

**Comment by DavidKorczynski** [comment]
https://github.com/google/oss-fuzz/pull/11971 fixes this one -- will close it once the report is up again

**Comment by DavidKorczynski** [comment]
Can confirm openssl is build again

**Comment by DavidKorczynski** [comment]
Same with nDPI

**Comment by IvanNardi** [comment]
> Same with nDPI

Thank you very much!
