### ISSUE TITLE
Upgrade Clang Version in base-image

### ISSUE THREAD

**Issue by EricWF** [google/oss-fuzz#11731]
libc++ only supports clang versions within the last two LLVM releases. The current clang version in the base image 15, but libc++ requires v16 or newer.

Can we upgrade the clang version in the base image?
If not, what's the most efficient way for just the llvm_libcxx project to get a new compiler?

**Comment by fanquake** [comment]
#11714 is the current attempt at bumping this (to 18).

**Comment by EricWF** [comment]
Fantastic! Is there a way to target the newer image prior to the change landing as the default?

**Comment by jwakely** [comment]
This is a blocker for the libstdc++ fuzzing too, as clang 15 can't compile our C++23 code.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65666
