### ISSUE TITLE
Is macOS supported by ClusterFuzzLite?

### ISSUE THREAD

**Issue by ligurio** [google/oss-fuzz#11738]
ClusterFuzz declares macOS support in it's documentation [^1], but ClusterFuzzLite says nothing about supported OSes [^2].

Github announced support of M1 macOS runners [^3], so it would be nice to have running CFL on M1 runners.

[^1]: https://google.github.io/clusterfuzz/architecture/
[^2]: https://google.github.io/clusterfuzzlite/
[^3]: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by jonathanmetzman** [comment]
I don't think it's realistic to support because the build system is reliant on using oss-fuzz's docker images.
