### ISSUE TITLE
graphicsmagick build failing for couple of days

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1177]
```
Step #1: Step 4/6 : RUN hg clone -v http://hg.code.sf.net/p/graphicsmagick/code graphicsmagick
Step #1:  ---> Running in 522a44939424
Step #1: [91mtransaction abort!
Step #1: [0mrequesting all changes
Step #1: adding changesets
Step #1: adding manifests
Step #1: adding file changes
Step #1: [91mrollback completed
Step #1: [0m[91mabort: connection ended unexpectedly
Step #1: The command '/bin/sh -c hg clone -v http://hg.code.sf.net/p/graphicsmagick/code graphicsmagick' returned a non-zero code: 255
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/cloud-builders/docker" failed: exit status 255
Step #1: [0m
```
@alex - any thoughts on how to fix this ?

**Comment by alex** [comment]
The recent failures seem to be caused by SourceForge's hosting migration (https://mobile.twitter.com/sfnet_ops). The GM team is aware and is taking a wait-and-see approach as to whether to move hosting providers.

**Comment by alex** [comment]
SourceForge seems to have recovered somewhat, I've now managed several successful clones this evening! Hopefully we'll see a successful one in tomorrow's build. (If not, maybe we should replace `hg clone` with `hg clone || hg clone || hg clone` to make it more resillient to intermittent network errors)

**Comment by inferno-chromium** [comment]
yay green build!
