### ISSUE TITLE
Add a CITATION.ctf

### ISSUE THREAD

**Issue by coastalwhite** [google/oss-fuzz#11817]
It would be really nice to have a simple way to cite this work being done for academics. GitHub has accepted the [Citation File Format](https://citation-file-format.github.io/) for repositories. I would truly appreciate it if this repository could add such a file.

**Comment by oliverchang** [comment]
@DonggeLiu are you familiar with this?

**Comment by coastalwhite** [comment]
If you feel a bit lost or want a reference file, I did the same for verilator/verilator#5057.

**Comment by DonggeLiu** [comment]
Thanks @coastalwhite!
This is a great idea. I've added one to the link above.
