### ISSUE TITLE
libreoffice fuzz targets crashing a lot on startup

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1188]
https://oss-fuzz.com/v2/fuzzer-stats/by-fuzzer/2018-02-16/2018-02-22/fuzzer/libFuzzer/job/libfuzzer_asan_libreoffice

e.g.
https://oss-fuzz.com/v2/performance-report/libFuzzer_libreoffice_ww2fuzzer/libfuzzer_asan_libreoffice/latest

```
terminating with uncaught exception of type com::sun::star::uno::DeploymentException
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1==ERROR: AddressSanitizer: ABRT on unknown address 0x000000000001 (pc 0x7f1f83dc9428 bp 0x7ffeb0ef22b0 sp 0x7ffeb0ef2078 T0)
SCARINESS: 10 (signal)
    #0 0x7f1f83dc9427 in gsignal /build/glibc-bfm8X4/glibc-2.23/sysdeps/unix/sysv/linux/raise.c:54
    #1 0x7f1f83dcb029 in abort /build/glibc-bfm8X4/glibc-2.23/stdlib/abort.c:89
    #2 0x7428da6 in abort_message
    #3 0x742ca2b in demangling_terminate_handler()
    #4 0x742c675 in std::__terminate(void (*)())
    #5 0x7429b66 in __cxa_throw
    #6 0x582c123 in cppu::defaultBootstrap_InitialComponentContext(rtl::OUString const&) /src/libreoffice/cppuhelper/source/defaultbootstrap.cxx:53:9
    #7 0x582cb5e in cppu::defaultBootstrap_InitialComponentContext() /src/libreoffice/cppuhelper/source/defaultbootstrap.cxx:104:12
    #8 0x570d1d in CommonInitialize(int*, char***) /src/libreoffice/vcl/workben/commonfuzzer.hxx:107:47
    #9 0x57174e in TypicalFuzzerInitialize(int*, char***) /src/libreoffice/vcl/workben/commonfuzzer.hxx:128:5
    #10 0x5717c0 in LLVMFuzzerInitialize /src/libreoffice/vcl/workben/ww2fuzzer.cxx:83:5
    #11 0x6d6505f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:539:5
    #12 0x6d5c63c in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #13 0x7f1f83db482f in __libc_start_main /build/glibc-bfm8X4/glibc-2.23/csu/libc-start.c:291
    #14 0x46c0a8 in _start

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x35427)
==1==ABORTING
```

@caolanm - can you please take a look.

**Comment by inferno-chromium** [comment]
This is also https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6480

**Comment by caolanm** [comment]
This doesn't happen locally for me in the oss-fuzz docker image.

From the backtrace it suggests that the "unorc" file does not exist beside the ww2fuzzer binary, and so throws its "not found" exception. is there a log of what ends up copied to the target hardware ?

**Comment by inferno-chromium** [comment]
Because of the large archive size and uncompressed size, we now only copy a particular fuzz target binary and their needed dependencies (.options, .dict, etc). Is unorc dependency always needed, can it backed into the static fuzz target binary ?

**Comment by caolanm** [comment]
Its more than the unorc that's needed, its just the first thing missing that's fatal. There's a few other things in there that they need.

They don't need eachother of course, so if the oss-fuzz side looped 0..N_fuzzers and for each fuzzer copied everything except anything that matches the pattern of another fuzzer that would work.

Or if I could put each fuzzer and a copy of the runtime reqs into separate dirs or zips or something if the infra supported that.

**Comment by inferno-chromium** [comment]
We can't look into pattern of every other fuzzer every time, since it means we have to look through entire archive and we shouldn't need to do this for non-fuzz tasks like minimize, regression, etc where we know the fuzz target and should be able to unarchive it from archive. We have a set of whitelisted binaries, like afl-*, llvm-symbolizer that if they are found in archive, they are always unarchived. Can you put all dependencies in a resources directory and we can whitelist that so that it is unarchived always ?

**Comment by caolanm** [comment]
Maybe I can bodge things on my side to bootstrap from individual config files. If I output e.g.
demofuzzer and a directory demofuzzer.services would they currently get bundled together ?

**Comment by inferno-chromium** [comment]
Yes correct, they will get bundled then

**Comment by inferno-chromium** [comment]
@caolanm - thanks for doing this. sorry we had to add this optimization on our side to avoid unarchiving everything. we expect fuzz targets to be static binaries and we unarchive everything that has any extensions. in this case, unorc was a no extension binary, so it didn't get unarchived. I think best solution is what you suggest, having a <fuzz_target_name><.services/whatever directory).

**Comment by caolanm** [comment]
I have high hopes the next set of builds will work again

**Comment by inferno-chromium** [comment]
Seems to start working, see latest logs on libreoffice-logs.clusterfuzz-external.appspot.com/libFuzzer_libreoffice_slkfuzzer/libfuzzer_asan_libreoffice/2018-02-26. Lets give it 1-2 days to make sure all fuzz targets are fixed, then i will close this.

**Comment by inferno-chromium** [comment]
That crash is gone completely.
