### ISSUE TITLE
Need help to start contributing

### ISSUE THREAD

**Issue by fireballpoint1** [google/oss-fuzz#1190]
I wish to start contributing to the project with the aim : Convert FreeType's HTML documentation to markdown. I need help starting with the same. Any documentation for developers starting to contribute ?

**Comment by kcc** [comment]
I'm not sure what you mean and why your question is related to oss-fuzz. 
We do fuzz FreeType on oss-fuzz, but all of the FreeType code and documentation are in FreeType's revision control, not here.
