### ISSUE TITLE
Include total line information in summary.json for JVM 

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#11966]
Context: https://github.com/google/oss-fuzz-gen/pull/236

> the summary.json for the coverage report of JVM projects lacks that information. And after some search, it seems that sumamry.json is generated from the oss-fuzz side in https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/coverage#L218-L227 with the script jacoco_report_converter.py. Thus if we need to make the summary.json have the needed information for getting the total lines, we will need to change the infer of oss-fuzz to accommodate that.

**Comment by oliverchang** [comment]
Any chance one of you could help fix this? @arthurscchan @DavidKorczynski  ?

**Comment by arthurscchan** [comment]
@oliverchang Yes, I will take a look of how to fix it later on.

**Comment by arthurscchan** [comment]
This issue should be fixed.
