### ISSUE TITLE
Suricata fixed bug does not get closed

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#11993]
Follow up on https://github.com/google/oss-fuzz/pull/11714#issuecomment-2096878442 cc @jonathanmetzman 

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68317&q=label%3AProj-suricata is fixed 
https://oss-fuzz.com/testcase-detail/5167091775766528

But it does not appear so 
The last tested revision shown is stuck to the one before the 30 of April : [OISF/suricata@ad4185b](https://github.com/OISF/suricata/commit/ad4185b3c4fdcdfd0eac44a5ddf6bc7484c35bda)

**Comment by catenacyber** [comment]
Also https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67938&q=label%3AProj-suricata does not get closed

**Comment by jonathanmetzman** [comment]
I bumped the disk size up. Let's wait until tomorrow for this to go into effect and see if anything changes.

**Comment by catenacyber** [comment]
Build was successful yesterday and the days before, and the bug on 30th of April, and The last tested revision shown is the one before the 30 of April : [OISF/suricata@ad4185b](https://github.com/OISF/suricata/commit/ad4185b3c4fdcdfd0eac44a5ddf6bc7484c35bda)

**Comment by catenacyber** [comment]
Thanks @jonathanmetzman bugs now marked as fixed

**Comment by jonathanmetzman** [comment]
Oh nice, is everything working now?
