### ISSUE TITLE
Apparent off by one of issue number between Chromium oss-fuzz tracker and oss-fuzz testcase-detail page

### ISSUE THREAD

**Issue by bobfriesenhahn** [google/oss-fuzz#12038]
The issue [https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60199](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60199) leads to testcase-detail issue number 60200.  This apparent off by one between the two trackers results in the Chromium bug never being closed.

**Comment by oliverchang** [comment]
Thanks for the report (and sorry for the slow response)! I've marked https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60199  as a duplicate.
