### ISSUE TITLE
Loading coverage reports doesn't work for hg repos?

### ISSUE THREAD

**Issue by durin42** [google/oss-fuzz#1207]
If I try to visit a coverage page (for example [this one](https://oss-fuzz.com/coverage_report/job/libfuzzer_asan_mercurial/latest/f/%2Fsrc%2Fmercurial%2Fmercurial%2Fbdiff.c/l/227) ) I get an error like:

Couldn't load file content {"vcs_url":"https://www.mercurial-scm.org/repo/hg","path":"/mercurial/bdiff.c","revision":"638c012a87efc583225052c8e8cd5b31b9f141a1"}: 404

But the file [clearly exists](https://www.mercurial-scm.org/repo/hg/file/638c012a87ef/mercurial/bdiff.c) ([raw](https://www.mercurial-scm.org/repo/hg/raw-file/638c012a87ef/mercurial/bdiff.c)). Do we need to configure something, or is this a missing feature?

**Comment by inferno-chromium** [comment]
Jonathan is triage sheriff, should be an easy fix in appengine/v2/handlers/source_fetcher.py#52, please do it sometime this week.

**Comment by jonathanmetzman** [comment]
Will do. I'll probably take a look around Wednesday.

**Comment by jonathanmetzman** [comment]
Done. This should be fixed now.
