### ISSUE TITLE
Closure status on testcase-detail page.

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#1209]
The Closure status on the testcase-detail page use an American date notation:

>Closure: | Will be auto-closed on 13-2-2018 if flaky crash no longer seen
Closure: | Will be auto-closed on 4-2-2018 if flaky crash no longer seen

Would it be possible to use the same notation as in the metadata block?

>Closure: | Will be auto-closed on 2018-02-13 if flaky crash no longer seen
Closure: | Will be auto-closed on 2018-02-04 if flaky crash no longer seen

**Comment by inferno-chromium** [comment]
we actually use other date format on most pages (with local timezone). metadata is in utc which is confusing.
So, changed it now to match that. it will look like

Will be auto-deleted on Sun, Mar 11, 2018 if flaky crash no longer seen

**Comment by dlemstra** [comment]
Thanks for the quick change, this looks much better.
