### ISSUE TITLE
Confirm dialog submit button does not close dialog in Firefox.

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#1210]
In the test case "https://oss-fuzz.com/v2/testcase-detail/5947508753694720?noredirect=1" I tried to press the button after `CRASH STACKTRACE` and a modal with confirm/cancel buttons showed up. Pressing the confirm button shows a loader but the modal remains visible. It looks like nothing has happened but the metadata block shows `oss-fuzz-linux-zone1-host-2mbj-10: Stack task started.` after I close the modal myself and wait for a few minutes. Is it a bug that the modal won't close or is that by design?

**Comment by inferno-chromium** [comment]
We had a bug where we didn't show "Last Tested Stacktrace" section for unreproducible testcases (with Fixed=NA). Flow works like if press button "Update crash stacktrace using trunk build", then  "Last Tested Stacktrace" section starts showing "Pending", then Stack task runs. Once it finishes, it either shows latest stacktrace from trunk in that section or message "No crash found using XYZ job.".

In this case, now it shows section with "No crash found using libfuzzer_asan_imagemagick job."

**Comment by dlemstra** [comment]
Maybe I was not clear with what is happening. The modal that shows `Please confirm that you want to update last tested stacktrace using trunk build.` has two buttons. When I press the confirm button I see a loader and what that is done I am stuck in the modal.

**Comment by inferno-chromium** [comment]
I see the modal getting closed on Chrome, which browser are you on ?

**Comment by dlemstra** [comment]
I am using Firefox 58.0.2 (x64)

**Comment by inferno-chromium** [comment]
please use chrome as a workaround, there is some bug in our confirm dialog code that does not close dialog on firefox. i dont see any error in console, so would need more time with debugging. we have a lot on our plate atm, so a fix will come in some time in next few weeks.

**Comment by dlemstra** [comment]
No worries, just wanted to report it. No rush on fixing this.

**Comment by inferno-chromium** [comment]
I have failed here after a few hours of debugging last night. tanin, who wrote this code is no longer with team. we are not polymer experts and there is no error on console. some event might not be firing as expected.

**Comment by dlemstra** [comment]
@inferno-chromium Is the source of that website publicly available? I don't mind also taking a look at this.

**Comment by inferno-chromium** [comment]
@dlemstra - some in the next quarter or two, we want to open source all clusterfuzz code. currently only the backend infra code is open source (which is in this repo in infra/).

**Comment by dlemstra** [comment]
This issues seems to be resolved now.
