### ISSUE TITLE
Issue wont close eventhough it has been fixed.

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#1211]
The issue "https://oss-fuzz.com/v2/testcase-detail/5947508753694720?noredirect=1" won't close but it looks like it can no longer be reproduced. The metadata is showing the following error message:

>[2018-03-04 11:38:27 UTC] oss-fuzz-linux-zone1-host-328r-6: Regression task errored out: Known crash revision 201801081955 did not crash.
[2018-03-04 11:38:27 UTC] oss-fuzz-linux-zone1-host-328r-6: Regression task errored out: Test case appears to be flaky.

And the Closure status is stating the following:

>Will be auto-closed on 4-2-2018 if flaky crash no longer seen

This means the issue should be closed on the 4th of February but it I wonder if that did not happen because it still crashed on the 22th of February. Will this issue close itself on the 8th of March because it hasn't crashed for 14 days? If so it will be nice if the Closure status will be updated to the new date.

**Comment by inferno-chromium** [comment]
We have a bug, we are counting 7(without bug)/14(with bug) days from crash created date. instead it should be 7(without bug)/14(with bug) days from crash last seen date.

**Comment by dlemstra** [comment]
Are you counting days without a crash for the fuzzer or days without a crash for that input file? I hope the former but I suspect the latter due to issues that don't get closed but have an input file that no longer reproduces the crash.

**Comment by dlemstra** [comment]
Would it be possible to update the test case with the other file that caused the timeout with the same signature? In this issue the input file no longer causes the timeout but it seems that another file is still doing that because there have been crashes in the last 7 days.

**Comment by inferno-chromium** [comment]
https://oss-fuzz.com/v2/testcase-detail/5947508753694720?noredirect=1 now shows the date correctly, which is 14 days from date of last crash (=March 25, since it was seen once today).

We don't update the same testcase due to race issues, but if you click the group link in there (https://oss-fuzz.com/v2/testcases?q=group%3A6104290541174784), it should show other similar testcases or testcase that are reproducible. in this case, there was no other reproducible testcase yet, so no new testcase created.

**Comment by dlemstra** [comment]
Thanks for pointing me towards the group link @inferno-chromium . I had no clue that these where related test cases. I hope that will help us finally close some of the issues. Maybe the title could be changed to clarify that? I thought it was something internal. Just like the "eye" that sometimes shows up in the issues but says I have no access when I click on it.

**Comment by inferno-chromium** [comment]
Ok changing label s/Group/Related and title text s/Crashes with similar looking stacks are grouped into the same group (identified with the group ID)./Click to see crashes with same and similar looking stacks (grouped by a 'Group ID').

**Comment by inferno-chromium** [comment]
Ok that change is getting deployed.

@dlemstra - question: can you explain this in more detail - "Just like the "eye" that sometimes shows up in the issues but says I have no access when I click on it.". Please provide page link or screenshot to tell what you are seeing. if a new issue is needed please file one.

**Comment by dlemstra** [comment]
Thanks for the super fast change in the interface, it is more clear what it means now. 

I was talking about this eye:

![image](https://user-images.githubusercontent.com/10426229/37339933-9e5d4d4e-26bc-11e8-9c27-78a960fd6e79.png)

It does not show up every time (sometimes gone after page refresh) and it is unclear what this does. It says I have no access when I click on it.

And I wonder if related testcases that are also unreproducible should become part of the group. For example this issus "https://oss-fuzz.com/v2/testcase-detail/5328626414256128?noredirect=1" was a member of a group yesterday. But no longer is part of that group because I fixed a related issue that was reproducible. I am now just struggling to find another test case that is also unreproducible but would give me some more information on why it sometimes fails. Maybe it should become part of the group if a particular test case also has an unreproducable result X times?

Could you give me some specific pointers on how to find another testcase that also sometimes gives a timeout for this particular issue for now? There is just a big overload of information in the logs and a lot of files in the testcase folder. What should I be looking for in the logs to find another testcase in the testcase folder?

**Comment by inferno-chromium** [comment]
That eye thing appears on those testcase that are ascii like and hence can be viewable in web interface. it wont appear for binary files. For you not being able to access it is a bug, i have filed https://github.com/google/oss-fuzz/issues/1238 to track that. Please add the error there, i am guessing it is access denied.

For similar timeout cases, see example gs://imagemagick-logs.clusterfuzz-external.appspot.com/libFuzzer_imagemagick_encoder_tga_fuzzer/libfuzzer_asan_imagemagick/2018-03-13 (https://github.com/google/oss-fuzz/blob/master/docs/corpora.md)

https://storage.cloud.google.com/imagemagick-logs.clusterfuzz-external.appspot.com/libFuzzer_imagemagick_encoder_tga_fuzzer/libfuzzer_asan_imagemagick/2018-03-13/04%3A45%3A21%3A136403.testcase
https://storage.cloud.google.com/imagemagick-logs.clusterfuzz-external.appspot.com/libFuzzer_imagemagick_encoder_tga_fuzzer/libfuzzer_asan_imagemagick/2018-03-13/02%3A21%3A55%3A387425.testcase
https://storage.cloud.google.com/imagemagick-logs.clusterfuzz-external.appspot.com/libFuzzer_imagemagick_encoder_tga_fuzzer/libfuzzer_asan_imagemagick/2018-03-13/02%3A17%3A47%3A812557.testcase

are three timeout example cases. Replace ".testcase" with ".log" to see their stacktrace.
