### ISSUE TITLE
Issues created manually in duplication aren't closed

### ISSUE THREAD

**Issue by rouault** [google/oss-fuzz#1214]
I manually created from a testcase-report https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6704 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6705 got also created in duplication . The issue got fixed but only 6705 got closed

Same for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6670 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6671

So could you manually close https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6704 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6670 ?

Thanks

**Comment by inferno-chromium** [comment]
Done, but not advisable to manually file issues at this point. there can be a race in db update, plus the testcase might have not grouped with another similar testcase, so best to wait on auto-file and have less spam with duplicate.

**Comment by inferno-chromium** [comment]
we just believe in too much automation. right now only thing missing in automation is automated patching :)

probably automated cl detection as well. we have it in chromium land but there we have many more frequent builds which narrows down regression range and make it easy to find culprit cl.
