### ISSUE TITLE
Clarification on Missing Include Directory `apr-util` in Build Configuration for `apache-httpd`

### ISSUE THREAD

**Issue by MarkLee131** [google/oss-fuzz#12146]
Hello, I noticed that the directory `./srclib/apr-util/include/`, referenced in the [build script](https://github.com/google/oss-fuzz/blob/ef7aeec6961b49fd08efb6e5616d8d8d7318ba38/projects/apache-httpd/build.sh#L37) for `apache-httpd` (also shown below), is missing within the oss-fuzz docker container (as shown in the img below). 

https://github.com/google/oss-fuzz/blob/ef7aeec6961b49fd08efb6e5616d8d8d7318ba38/projects/apache-httpd/build.sh#L37

![image](https://github.com/google/oss-fuzz/assets/38575222/646588d8-bf97-466b-ae98-59d3a755ef47)

According to the [installation notes](https://github.com/apache/httpd/blob/cf3402e182f7a32eb9085a82347769cb2efe491e/INSTALL#L61), `httpd` has integrated `apr-util` into the `APR trunk`.

Should we remove the `-I./srclib/apr-util/include/` argument from our build script based on this integration? Your confirmation would be greatly appreciated.

**Comment by jonathanmetzman** [comment]
Apache-httpd seems to be building fine, so I don't see a need to do this, but please let me know if I'm missing something.
