### ISSUE TITLE
Which emails can be used for access via GitHub OAuth

### ISSUE THREAD

**Issue by TheOneric** [google/oss-fuzz#12156]
Currently docs state e.g. [here](https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/) email addresses need to  belong to an google account. In order to also gain access to the dashboard rather than "just" bugs on bugs.chromium.org it must be the _primary_ email of this Google account.   
Responses to recent'ish issues seem to reaffirm this.
 
However, at some point the dashboard gained another login method via GitHub OAuth rather than via Google. If I understand correctly the OAuth app is granted access to _all_ emails associated with the GitHub account. I was unable to find any more details about how this login method works and am hoping you could help me out with the below questions:
 
 - Which email(s) of the GitHub account will be considered here? Does any linked email work, only verified emails or only the primary email?
 - When using GitHub OAuth, does the chosen email address still need to be linked to a Google account to access the dashboard?

**Comment by oliverchang** [comment]
Hi,

Only the primary, verified email for the GitHub account works, and a Google account should no longer be required to access the https://oss-fuzz.com dashboard. 

Note though, to access our bug tracker (monorail), you will still need a Google account.

**Comment by TheOneric** [comment]
Thanks for the clarification!
