### ISSUE TITLE
How to add more people to a particular report and/or project?

### ISSUE THREAD

**Issue by kientzle** [google/oss-fuzz#12166]
A number of people have joined the libarchive project and are interested in helping with particular fuzzed issues.  How can I add those people to particular reports and/or to the entire project?

We also now have a mailing list for security bugs; it would be nice to add that email to the CC for all libarchive reports.

**Comment by DavidKorczynski** [comment]
Add emails to the `auto_ccs` list: https://github.com/google/oss-fuzz/blob/e4951edd3d3251626f859590c3c5802eb422d933/projects/libarchive/project.yaml#L4-L6
