### ISSUE TITLE
support tar.gz corpus

### ISSUE THREAD

**Issue by pdknsk** [google/oss-fuzz#1217]
You may or may not know this, but `zip` compresses each file in the archive separately. This is obviously particularly bad when compressing many small files, or many files which are very similar to each other, as is the case here.

A `zip` can easily be multiple times larger here compared to `tar.gz`. Even moreso if `tar.bz2` or `tar.xz` were supported.

You can download `tar.gz` (or any format) and then repack into `zip` during the build process for fuzzer consumption, but why not have it supported properly then.

**Comment by inferno-chromium** [comment]
Seed corpus is usually a minimized corpus of <10K files. This optimization can be done, we already support reading different kind of archives like tar.gz, tar.bz2, etc for other things. We can fix this bug sometime in future , unless this is blocking you in some way.

**Comment by pdknsk** [comment]
No it's not urgent to me. I just noticed when I merged locally.

**Comment by jonathanmetzman** [comment]
This should work now (tar.xz should work as well). 
Also worth noting that starting recently we will only unpack seed corpus when a target is brand new (ie: corpus is empty) and once a day during corpus pruning, so slower decompression is less of a concern.
