### ISSUE TITLE
Unable to download reproducers

### ISSUE THREAD

**Issue by nhorman** [google/oss-fuzz#12192]
Hello-
     I'm authorized to access bugs for the openssl project, and have signed the CLA.  However, for any given issue that I look at, when I click the download reproducer link at the bottom of the page, I get an unauthorized error.  I can download the minimal test case and full test case at the top of an issue, its just the reproducer link that seems to be non-functional

**Comment by ktmf01** [comment]
I think this is the same issue as #11744?

**Comment by nhorman** [comment]
ACK, certainly looks the same. I'll close this a a dup
