### ISSUE TITLE
jsc build is broken

### ISSUE THREAD

**Issue by mbarbella** [google/oss-fuzz#1225]
Step #4: FAILED: /usr/local/bin/clang++   -DBUILDING_JSCONLY__ -DBUILDING_WITH_CMAKE=1 -DBUILDING_WTF -DHAVE_CONFIG_H=1 -I../../Source/bmalloc -I. -IDerivedSources -I../../Source/ThirdParty -isystem /src/deps/include -I../../Source/WTF -I../../Source/WTF/wtf -I../../Source/WTF/wtf/dtoa -I../../Source/WTF/wtf/persistence -I../../Source/WTF/wtf/text -I../../Source/WTF/wtf/text/icu -I../../Source/WTF/wtf/threads -I../../Source/WTF/wtf/unicode -fdiagnostics-color=always -fcolor-diagnostics -Wno-parentheses-equality -Wno-noexcept-type -Qunused-arguments -Wwrite-strings -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -Wextra -Wall -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope  -stdlib=libc++ -DU_STATIC_IMPLEMENTATION  -fno-strict-aliasing -fno-exceptions -std=c++14 -fno-rtti -gsplit-dwarf -g -fPIC -MMD -MT Source/WTF/wtf/CMakeFiles/WTF.dir/CurrentTime.cpp.o -MF Source/WTF/wtf/CMakeFiles/WTF.dir/CurrentTime.cpp.o.d -o Source/WTF/wtf/CMakeFiles/WTF.dir/CurrentTime.cpp.o -c ../../Source/WTF/wtf/CurrentTime.cpp
Step #4: ../../Source/WTF/wtf/CurrentTime.cpp:266:19: error: use of undeclared identifier 'CLOCK_MONOTONIC'
Step #4:     clock_gettime(CLOCK_MONOTONIC, &ts);
Step #4:                   ^
Step #4: 1 error generated.
Step #4: ninja: build stopped: subcommand failed.
Finished Step #4
ERROR
ERROR: build step 4 "gcr.io/oss-fuzz/jsc" failed: exit status 1

@oliverchang Could you take a look or pass this along to someone at Apple?

**Comment by oliverchang** [comment]
@jfbastien could you please help pass this along to the right person?

**Comment by jfbastien** [comment]
I believe @Constellation made that change.

**Comment by Constellation** [comment]
I'll look into this part.

**Comment by Constellation** [comment]
Included `<time.h>`. https://trac.webkit.org/changeset/229571

**Comment by oliverchang** [comment]
Build looks green again. Thank you!
