### ISSUE TITLE
llvm build is broken

### ISSUE THREAD

**Issue by mbarbella** [google/oss-fuzz#1226]
Step #4: FAILED: /usr/local/bin/clang++   -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/clang/tools/extra/clangd/fuzzer -I/src/llvm/tools/clang/tools/extra/clangd/fuzzer -I/src/llvm/tools/clang/include -Itools/clang/include -Iinclude -I/src/llvm/include -I/src/llvm/tools/clang/tools/extra/clangd/fuzzer/.. -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fno-omit-frame-pointer -gline-tables-only -fsanitize=address -fsanitize-address-use-after-scope -fcolor-diagnostics -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -Wno-nested-anon-types -O3    -UNDEBUG  -fno-exceptions -fno-rtti -MMD -MT tools/clang/tools/extra/clangd/fuzzer/CMakeFiles/clangd-fuzzer.dir/ClangdFuzzer.cpp.o -MF tools/clang/tools/extra/clangd/fuzzer/CMakeFiles/clangd-fuzzer.dir/ClangdFuzzer.cpp.o.d -o tools/clang/tools/extra/clangd/fuzzer/CMakeFiles/clangd-fuzzer.dir/ClangdFuzzer.cpp.o -c /src/llvm/tools/clang/tools/extra/clangd/fuzzer/ClangdFuzzer.cpp
Step #4: /src/llvm/tools/clang/tools/extra/clangd/fuzzer/ClangdFuzzer.cpp:26:34: error: no matching constructor for initialization of 'clang::clangd::ClangdLSPServer'
Step #4:   clang::clangd::ClangdLSPServer LSPServer(
Step #4:                                  ^
Step #4: /src/llvm/tools/clang/tools/extra/clangd/fuzzer/../ClangdLSPServer.h:34:3: note: candidate constructor not viable: requires 4 arguments, but 7 were provided
Step #4:   ClangdLSPServer(JSONOutput &Out, const clangd::CodeCompleteOptions &CCOpts,
Step #4:   ^
Step #4: /src/llvm/tools/clang/tools/extra/clangd/fuzzer/../ClangdLSPServer.h:29:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 7 were provided
Step #4: class ClangdLSPServer : private DiagnosticsConsumer, private ProtocolCallbacks {
Step #4:       ^
Step #4: 1 error generated.
Step #4: ninja: build stopped: subcommand failed.
Finished Step #4
ERROR
ERROR: build step 4 "gcr.io/oss-fuzz/llvm" failed: exit status 1

@kcc Mind taking a look at this when you have time?

**Comment by morehouse** [comment]
Fixed in https://reviews.llvm.org/rCTE327184.  Should go green on next build.
