### ISSUE TITLE
spidermonkey build is broken

### ISSUE THREAD

**Issue by mbarbella** [google/oss-fuzz#1227]
Step #4: [179/277] Compiling C object 'src/basic/basic@sta/cgroup-util.c.o'.
Step #4: ../../src/systemd/src/basic/cgroup-util.c:2041:32: warning: unused variable 'f' [-Wunused-variable]
Step #4:         _cleanup_fclose_ FILE *f = NULL;
Step #4:                                ^
Step #4: 1 warning generated.
Step #4: [180/277] Compiling C object 'src/shared/systemd-shared-238@sta/install.c.o'.
Step #4: [181/277] Compiling C object 'src/libsystemd/systemd@sta/sd-bus_bus-message.c.o'.
Step #4: ninja: build stopped: subcommand failed.
Finished Step #4
ERROR
ERROR: build step 4 "gcr.io/oss-fuzz/systemd" failed: exit status 1

@alex Would you mind taking a look at this when you have time?

**Comment by alex** [comment]
The log you included seems to be for systemd, and I don't see a spidermonkey build error on https://oss-fuzz-build-logs.storage.googleapis.com/index.html

Please confirm.

**Comment by mbarbella** [comment]
My mistakes. This I was looking at stale data to begin with, and managed to copy the wrong error from it.
