### ISSUE TITLE
question about targets and coverage

### ISSUE THREAD

**Issue by pdknsk** [google/oss-fuzz#1228]
As each project can have multiple fuzz targets, I'm wondering if it's better to split multiple APIs that a project provides in separate targets, or run them sequentially in a single target (with fall-through for each API). Like a simple API, an advanced API (which more or less produces the same result, but has higher complexity and more options), or some other API. Combining would provide more useful coverage I think, as coverage is made separately for each target it seems. And there is no cross-merge across targets. On the negative side, the number of path combinations increases significantly, with redundancy.

**Comment by pdknsk** [comment]
I've got another question for which I don't want to file a separate bug. How much available RAM do the VMs have? I've noticed when testing locally that one target tends to use slightly more than the default _2048_ when running MSAN, and I'm not sure if I can increase `rss_limit_mb` to _3072_ or so.

**Comment by inferno-chromium** [comment]
1. Complex API is better to split into their own targets. That ensures they have their own unique minimized corpus.
2. We cap at 2048 MB. There should be a bug in target if it takes more than that ram, going beyond that would also mean that fuzzing with that target will be very inefficient/slow.
