### ISSUE TITLE
Issue 71044: openh264: Fuzzing build failure caused by pip install corpus-replicator failure

### ISSUE THREAD

**Issue by BenzhengZhang** [google/oss-fuzz#12343]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=71044
pls see build log, thanks

**Comment by DaveLak** [comment]
Other projects have had similar issues. Upgrading pip before using it to install packages might be all that's necessary, e.g:

https://github.com/DaveLak/oss-fuzz/commit/37437294f65bf37ab639c5900613147e9f2c05c5
