### ISSUE TITLE
No fuzzer stats on aptos-core

### ISSUE THREAD

**Issue by gedigi** [google/oss-fuzz#12358]
The infrastructure is not producing data for our fuzzers since August 6th. We had build issues but they have been solved and the build has now completed for the last 2 days ([ref](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#aptos-core)).

Can you help understand what's missing/broken?

**Comment by DavidKorczynski** [comment]
I think this is related to https://github.com/google/oss-fuzz/issues/12357 https://github.com/google/oss-fuzz/issues/12349

**Comment by gedigi** [comment]
> I think this is related to #12357 #12349

I see, thanks - so is it being addressed on the infrastructure side?

**Comment by DavidKorczynski** [comment]
yes, I think give this a few days and it should stabilize

**Comment by catenacyber** [comment]
I also have the same issue on ngolo-fuzzing since March : just a few stats (like 10 targets our of 100), and coverage build not working because it does not find corpus.
Locally, it seems to work fine so far.

Any clues ?

**Comment by catenacyber** [comment]
cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67724#c18

**Comment by DavidKorczynski** [comment]
> I also have the same issue on ngolo-fuzzing since March

Considering this has happened for several months then I don't think the underlying issue is the infra issues I have in mind.

@jonathanmetzman @oliverchang do you have ideas?

**Comment by catenacyber** [comment]
Running out of disk space is likely since this is a big project (many fuzz targets)

**Comment by jonathanmetzman** [comment]
I bumped up disk size to 80 GB.
Might be worth waiting to land that PR.

**Comment by catenacyber** [comment]
Thanks Johnathan, it looks better now :-)

**Comment by catenacyber** [comment]
> Thanks Johnathan, it looks better now :-)

And finding bugs again https://github.com/golang/go/issues/69066
