### ISSUE TITLE
boost-beast: Failed to unpack the corpus

### ISSUE THREAD

**Issue by tyler92** [google/oss-fuzz#12357]
I have the following error for boost-beast project:

```
Starting Step #5
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: [/corpus/http_request.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/http_request.zip or
Step #5:         /corpus/http_request.zip.zip, and cannot find /corpus/http_request.zip.ZIP, period.
Step #5: Failed to unpack the corpus for http_request. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
```

https://oss-fuzz-build-logs.storage.googleapis.com/log-fe1ab2b0-7762-41c5-9e65-0f1cc7085261.txt

The error is the same for 3 days. As far as I understood it's an infrastructure issue. Can you please help me to solve it?

**Comment by DavidKorczynski** [comment]
I think this is similar to https://github.com/google/oss-fuzz/issues/12358 and https://github.com/google/oss-fuzz/issues/12349

**Comment by jonathanmetzman** [comment]
@oliverchang We're seeing a lot of HostErrors for this one, https://pantheon.corp.google.com/logs/query;query=SEARCH%2528%22%60boost-beast%60%22%2529%0A-SEARCH%2528%22Permission%22%2529%0Aseverity%3DERROR;cursorTimestamp=2024-08-19T13:17:03.213553682Z;duration=P30D?e=-13802955&mods=logs_tg_prod&project=clusterfuzz-external Any idea how we stop this? Is it just restarting the bots?

**Comment by jonathanmetzman** [comment]
Did you guys delete a fuzzer recently?

**Comment by tyler92** [comment]
By the way, the error with unpacking corpus disappeared without any actions from my side. So now everything is OK, but I don't know if we should close the issue

**Comment by tyler92** [comment]
Yes, everything works properly, thank you

**Comment by tyler92** [comment]
I don't know if I have to open a new issue but this problem is still reproduced. Now with `boost-json`. A new fuzzer was added several days ago and every day there is the same error:

```
Step #5: [/corpus/fuzz_direct_parse.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/fuzz_direct_parse.zip or
Step #5:         /corpus/fuzz_direct_parse.zip.zip, and cannot find /corpus/fuzz_direct_parse.zip.ZIP, period.
Step #5: Failed to unpack the corpus for fuzz_direct_parse. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
```

https://oss-fuzz-build-logs.storage.googleapis.com/log-d51eada7-e55e-4cc6-918c-9c119c3c1300.txt
