### ISSUE TITLE
[infra] Unpin clang version

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#12385]
This is about removing the following lines

https://github.com/google/oss-fuzz/blob/173cae95c4d1810ee56484a8e63e0cf6f990afeb/infra/base-images/base-clang/checkout_build_install_llvm.sh#L63-L64

Now that the reason for the pinning has now been resolved (see https://github.com/google/oss-fuzz/issues/7273#issuecomment-1980529974)

CC @nikola-matic

**Comment by jonathanmetzman** [comment]
Indeed. It would be too chaotic I think to have it unpinned.
