### ISSUE TITLE
Centipede reports old bug that was fixed a long time ago

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#12383]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=71198

Centipede is digging up this old bug; I verified that current builds don't have this bug.

**Comment by jonathanmetzman** [comment]
I think that issue was caused by us making centipede a default engine. We reverted that PR so it shouldn't be a problem anymore (https://github.com/google/clusterfuzz/pull/4190)
But please let us know if it is. Sorry for the trouble.

**Comment by guidovranken** [comment]
Thanks.
