### ISSUE TITLE
Integration Reward Status

### ISSUE THREAD

**Issue by capuanob** [google/oss-fuzz#12406]
Good morning, all!

I submitted an initial integration for Crow and an ideal integration for pdfminer.six three weeks ago and have not received a status update on them. I understand that it takes time to review these, but I just want to check if anything is needed on my end / if they have made it into your queue successfully. 

Thank you for your time!

**Comment by capuanob** [comment]
@DonggeLiu Good afternoon! Would you be able to provide me an update on the status of payments?

**Comment by DonggeLiu** [comment]
Sorry about the delay, @capuanob, we plan to discuss this in this week's meeting.
@oliverchang

**Comment by capuanob** [comment]
@DonggeLiu Thank you! Looking forward to hearing more :)

**Comment by DonggeLiu** [comment]
Hi @capuanob, hope you have received the update!

**Comment by capuanob** [comment]
I have! Thank you very much for your time

Thank You, Bailey Capuano
