### ISSUE TITLE
Log4cxx tests are not running

### ISSUE THREAD

**Issue by vy** [google/oss-fuzz#12417]
I have recently contributed Log4cxx tests in #12352. Though I am not able to see the tests being picked up and run by ClusterFuzz.

### Fuzzing builds

I can see that [the Log4cxx fuzzer builds](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#apache-logging-log4cxx) are succeeding.

### Coverage builds

Coverage builds are failing with the following failure:

```
...
Starting Step #5
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: [/corpus/PatternLayoutFuzzer.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/PatternLayoutFuzzer.zip or
Step #5:         /corpus/PatternLayoutFuzzer.zip.zip, and cannot find /corpus/PatternLayoutFuzzer.zip.ZIP, period.
Step #5: Failed to unpack the corpus for PatternLayoutFuzzer. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
...
```

It has been more than 24 hours, hence I was expecting this message to disappear. Though I suspect the tests have not been run at all yet.

### Fuzzing

When I login to [oss-fuzz.com](https://oss-fuzz.com), I cannot see anything Log4cxx related. Neither [a bucket for the run logs](https://console.cloud.google.com/storage/browser/apache-logging-log4cxx-logs.clusterfuzz-external.appspot.com) exists.

**Comment by vy** [comment]
@DonggeLiu, since you were the one who reviewed #12352, could you help me with this ticket, please?

**Comment by DavidKorczynski** [comment]
I would give this another day -- the project started building two days ago and there's been one coverage build. I assume the harness just hasn't been picked up by the bots yet.

@jonathanmetzman do we guarantee that the bots for running fuzzers picks up each harness once a day?

**Comment by vy** [comment]
#12352 was merged in Aug 27, ~6 days ago. AFAICT, we should have received some results until now. I suspect an infrastructure issue. Could somebody help with troubleshooting it, please?

**Comment by vy** [comment]
@jonathanmetzman, would you mind helping with this issue, please?

**Comment by jonathanmetzman** [comment]
I can see where the issue is happening. There's too much contention on our libFuzzer entity (silly of us to have a single entity that needs to be updated like this). I think I know why. Let me try a fix.

**Comment by jonathanmetzman** [comment]
If you look at oss-fuzz.com you should see a job for log4cxx now. Stats take a day to populate and should be there by Wednesday.
From the internal logs, it looks like it's running.

**Comment by vy** [comment]
@jonathanmetzman, I can confirm that the tests are running. Thanks so much! :pray:
