### ISSUE TITLE
issues "open" in bugs.chromium.org but "fixed" in oss-fuzz.com

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#12434]
I've got two issues in https://bugs.chromium.org

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68994&q=libreoffice
and
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69874&q=libreoffice

which link to
https://oss-fuzz.com/testcase-detail/5939540316454912
and
https://oss-fuzz.com/testcase-detail/5598214137380864

where oss-fuzz has about a week ago detected fixes for the issues and in oss-fuzz the issues are now tagged as Fixed, but that state doesn't seem to have been picked up at https://bugs.chromium.org

**Comment by tbeu** [comment]
Same here: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70617&q=proj%3Amatio is marked "New", bu the linked detailed report https://oss-fuzz.com/testcase-detail/6239205672419328 is set "fixed".

**Comment by cujomalainey** [comment]
Also seeing this under sound-open-firmware

**Comment by catenacyber** [comment]
Also for suricata with https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=71056&q=label%3AProj-suricata&can=2

**Comment by catenacyber** [comment]
ping @DonggeLiu ? Any ideas ?

**Comment by DonggeLiu** [comment]
@oliverchang has much more expertise on this than I do.

**Comment by cujomalainey** [comment]
I got a bunch of bug closures last night. Did this get fixed?

**Comment by catenacyber** [comment]
Same here

**Comment by oliverchang** [comment]
Thanks for the report! We had an issue with our automated cron for closing bugs. This has been fixed now.
