### ISSUE TITLE
openssl (and tor) build is broken

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#1244]
https://oss-fuzz-build-logs.storage.googleapis.com/log-e526067d-c9b8-411a-85e6-12bd874ee34b.txt

```
Step #4: ***** Mixing env / make variables and additional compiler/linker flags as
Step #4: ***** configure command line option is not permitted.
Step #4: ***** Affected env / make variables: CFLAGS, CPPDEFINES, CXXFLAGS
```

@kroeckx can you please help with this one?

**Comment by oliverchang** [comment]
(tor build is broken for same reason: https://oss-fuzz-build-logs.storage.googleapis.com/log-f9b528a3-b6ea-44bb-86fc-4fa9f1e7129b.txt)

**Comment by kroeckx** [comment]
@levitte: Can you look at this?

**Comment by levitte** [comment]
Looking at it now.

**Comment by levitte** [comment]
Have a look at openssl/openssl#5641

**Comment by levitte** [comment]
So openssl/openssl#5641 got merged now.  I hope these errors will clear, but if not, feel free to ping me again

**Comment by inferno-chromium** [comment]
both openssl and tor builds are green now.
