### ISSUE TITLE
no way to close fixed unreproducible issues

### ISSUE THREAD

**Issue by dtardon** [google/oss-fuzz#1245]
If I push a fix for an issue that is marked as unreproducible, it won't be verified and closed automatically. And there is no other way to close it. (Unreproducible issues contain a note that ends with "If the fix resolved the issue, please close the bug by marking as Fixed." But I don't have sufficient rights to do this...)

Examples: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2938 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3246 were both fixed in October.

**Comment by inferno-chromium** [comment]
We close even unreproducible bugs, but the condition is that crash signature should stop showing on crash stats. If you go to https://oss-fuzz.com/v2/testcase-detail/5284500193935360?noredirect=1 and go down to crash stats, you will still see timeout happening today.

I need to fix that message, it should be that we will automatically close bug when crash is no longer seen. keeping the bug to fix that message.

**Comment by dtardon** [comment]
I don't see how it could... The run times I'm getting here are >25s before the fix and ~125ms after it.

**Comment by inferno-chromium** [comment]
Go to fuzzer logs from oss-fuzz.com/v2/fuzzer-stats, in that logs bucket you can download logs for a day and it has testcases for those logs as well.

For X.log with timeout string, you can try X.testcase locally to see if it reproduce. Also, stacktrace in X.log can give you insight. it can be a different timeout, so stack in there can be useful. We only create one timeout testcase per fuzz target (since deduplication is not possible with stack frames moving around)

**Comment by inferno-chromium** [comment]
These are old bugs, the text is already changed on new bugs as

    '<b>Note: This crash might not be reproducible with the provided testcase. '
    'That said, for the past X days we\'ve been seeing this crash frequently. '
    'If you are unable to reproduce this, please try a speculative fix based '
    'on the crash stacktrace in the report. The fix can be verified by looking '
    'at the crash statistics in the report, a day after the fix is deployed. '
    'We will auto-close the bug if the crash is not seen for X days.'

**Comment by inferno-chromium** [comment]
For https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2938, if you see testcase https://oss-fuzz.com/testcase?key=5284500193935360, there is a link "Related: Group 4903212470501376", click on that to see https://oss-fuzz.com/v2/testcase-detail/5735142984253440 which it says reproducible on trunk, can you try that.

Similarly for https://oss-fuzz.com/testcase?key=5695290696794112, click on Related: and you will see https://oss-fuzz.com/v2/testcase-detail/5735142984253440 is a reproducible testcase.

Hope that helps!
