### ISSUE TITLE
Host fuzz harness in synced fork?

### ISSUE THREAD

**Issue by ennamarie19** [google/oss-fuzz#12467]
As discussed [here](https://github.com/jsvine/pdfplumber/issues/1198), an upstream maintainer is asking if the fuzz harnesses can hosted in a synced fork as opposed to the upstream. Is that feasible for OSS-Fuzz or must it be in the upstream repository itself? 

Thank you!

**Comment by oliverchang** [comment]
Hi @ennamarie19 , our preference is for the fuzz harnesses to live upstream with the project, but we do have some cases where the fuzzers live in another repo.
