### ISSUE TITLE
A false positive seems to be preventing a fuzzer from making much progress

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#1247]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6884 is caused by https://github.com/google/sanitizers/issues/767, which I've already reported there. I almost forgot about it, when the following comment appeared in my inbox:
> This crash occurs very frequently on linux platform and is likely preventing the fuzzer fuzz-unit-file from making much progress. Fixing this will allow more bugs to be found.

I was wondering if there was a way to fix it without getting around the issue in our code.

**Comment by kcc** [comment]
I don't see a good workaround in oss-fuzz -- we need to fix this in msan. 
Or you may want to change the code, since IIRC %ms is a non-standard extension. 
Note that this is blocking only msan builds on oss-fuzz, not any other builds.

**Comment by evverx** [comment]
Thank you. It seems that the message sounds more frightening than it really is. I thought that all the queues everywhere were blocked.

I was hoping that `OSS-Fuzz` could ignore known failures somehow, but if there is no such mechanism, I agree that workarounds shouldn't be added.

I think the discussion whether to use `%ms` will be continued in https://github.com/systemd/systemd/pull/8461.

Should I close this issue or should I leave it open?

**Comment by evverx** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6897 seems to be a false positive caused by https://github.com/google/sanitizers/issues/926.

**Comment by keszybz** [comment]
Another one:
```
Uninitialized bytes in __interceptor_strcmp at offset 0 inside [0x707000000380, 1)
==11==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f43db03f5e5 in strcmp_ptr /work/build/../../src/systemd/src/basic/string-util.c:41:24
    #1 0x7f43db03542a in streq_ptr /work/build/../../src/systemd/src/basic/string-util.h:51:16
    #2 0x7f43db02f23c in netlink_family_from_string /work/build/../../src/systemd/src/basic/socket-util.c:798:1
    #3 0x7f43db02eea0 in socket_address_parse_netlink /work/build/../../src/systemd/src/basic/socket-util.c:254:18
    #4 0x4bd414 in config_parse_socket_listen /work/build/../../src/systemd/src/core/load-fragment.c:393:21
    #5 0x7f89aa in next_assignment /work/build/../../src/systemd/src/shared/conf-parser.c:155:32
    #6 0x7ecb90 in parse_line /work/build/../../src/systemd/src/shared/conf-parser.c:273:16
    #7 0x7eab4c in config_parse /work/build/../../src/systemd/src/shared/conf-parser.c:390:21
    #8 0x4b41eb in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-unit-file.c:48:16
    #9 0x8a7e33 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:517:13
    #10 0x8a5022 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoop.cpp:442:3
    #11 0x8acbf6 in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:650:19
    #12 0x8b07c5 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:773:5
    #13 0x875114 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:754:6
    #14 0x8603c1 in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #15 0x7f43d9b6382f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #16 0x433be8 in _start (/out/fuzz-unit-file+0x433be8)

  Uninitialized value was created by a heap allocation
    #0 0x4712b0 in __interceptor_malloc /src/llvm/projects/compiler-rt/lib/msan/msan_interceptors.cc:915
    #1 0x7f43d9ba0599 in _IO_vfscanf (/lib/x86_64-linux-gnu/libc.so.6+0x5d599)
    #2 0x7f43d9bb3276 in vsscanf (/lib/x86_64-linux-gnu/libc.so.6+0x70276)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /work/build/../../src/systemd/src/basic/string-util.c:41:24 in strcmp_ptr
```
Essentially every use of `sscanf` with `%ms` is causing false positives.

> Or you may want to change the code, since IIRC %ms is a non-standard extension.

`sscanf` and related functions are very annoying to use with plain %s, since one doesn't know how much space to allocate. So one would need to provide a buffer the length of the string for every %s use, and then do a `strdup`. Doing the allocation in `sscanf` is *way* more sensible.

I tried setting `__attribute__((no_sanitize("memory")))` as described in https://clang.llvm.org/docs/MemorySanitizer.html, but apparently that would have to be set on the function that is *using* the "undefined" value, not on the function where `sscanf`is called. So that's not really feasible, since that other function is called from many different contexts.

**Comment by evverx** [comment]
There was apparently another false positive reported in https://oss-fuzz.com/v2/issue/5546208027213824/7049, which seems to be just a variation on https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6884.

Given that MemorySanitizer is explicitly said to be in development mode and not recommended for use, I don't think there is anything to discuss here. I'm closing the issue. Sorry for the noise.

**Comment by kcc** [comment]
MemorySanitizer is pretty stable, but indeed your code exercises parts of glibc that our 250 MLOC codebase doesn't use. We'll fix this, just give us time (we are a bit overwhelmed now). 
Patches welcome too, let's discuss further in the other bugs you've filed.

**Comment by evverx** [comment]
I don't think `MemorySanitizer` is unstable. I was just quoting from https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md#testing-locally :-)

All the false positives have been got around, but It would be great to limit the scope of those stopgaps. I was wondering if the environment variable `SANITIZER` could be used at runtime to detect if the test is being run under `MemorySanitizer`. `infra/helper.py` seems to always set it, but I'm not sure about the real environment where the tests are run.

**Comment by evverx** [comment]
It seems that it is unnecessary to wait for a test to be run, so `__has_feature(memory_sanitizer)` should probably work.
