### ISSUE TITLE
Reproducible crash is not reported as an issue

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#1248]
To figure out why some of our issues are not getting closed I took a look at logs of one of our fuzzers:

https://oss-fuzz.com/v2/fuzzer-stats/by-day/2018-03-09/2018-03-14/fuzzer/libFuzzer_imagemagick_encoder_pcd_fuzzer/job/libfuzzer_msan_imagemagick

This has known crashes but they are not getting reported. I can reproduce the error from the following log file: 00:14:51:678683.log (Buckets / imagemagick-logs.clusterfuzz-external.appspot.com / libFuzzer_imagemagick_encoder_pcd_fuzzer / libfuzzer_msan_imagemagick / 2018-03-14). And this crash has been happening for a couple days now. But this is not reported as an issue. When I search the open issue I only see the issue that I am trying to fix: `fuzzer: libFuzzer_imagemagick_encoder_pcd_fuzzer`. And when I search all the issues for this fuzzer there is also not an old issue about this. Can you clarify why no issue is created?

p.s. I fixed the issue that caused so the latest head will no longer reproduce the issue.

**Comment by inferno-chromium** [comment]
We rotate logs after two weeks, so lost the crash stack. if you have that, then i can try searching to see why we didnt report it. we dont report new crash if it looks similar to an existing crash. and few times, it can be https://github.com/google/oss-fuzz/issues/1267. Closing for now.
