### ISSUE TITLE
Update docs to reflect header-check rule

### ISSUE THREAD

**Issue by PatriceJada** [google/oss-fuzz#12497]
The docs don't mention any rules for header-checker. Initially, checks would pass with 2021 copyright but currently fails for certain files but not others. It would be nice if it was documented somewhere

ref: https://github.com/google/oss-fuzz/runs/30155900880

**Comment by jonathanmetzman** [comment]
I don't think we need to include details about a license header in the docs. It's doubtful enough people would read it for it to be useful, and the check is pretty easy to satisfy once someone notices it is wrong.
