### ISSUE TITLE
Include SHA-1 of repository in log files

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#1250]
I am trying to find out why some of our issues are still reporting timeouts and going through the logs and test cases I found this folder: https://console.cloud.google.com/storage/browser/imagemagick-logs.clusterfuzz-external.appspot.com/libFuzzer_imagemagick_encoder_wpg_fuzzer/libfuzzer_ubsan_imagemagick/2018-03-15. In that folder there is a file called `03:04:24:063056.testcase` and its log file `03:04:24:063056.log`. I tried to run that testcase on my machine it finishes in 500ms so I cannot understand why it showing the message `ALARM: working on the last Unit for 26 seconds` in the log files. We did however fix some things in our project that would improve the failure detecting and would cause this early exit. Not sure if it would take 26 seconds with an other checkout. I would like to investigate this because this crash causes a change in the closure date of the issue I am investigating (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=5800). It is now at 14 days from today because of this testcase. I would like to know which checkout was used to run this testcase but I cannot find a SHA-1 of our project. The file does contain `4880a0c823f401d0ece299ed204ad3e106276b3a` at the start but I have no where that comes from or what it means. Would it be possible to include the SHA-1 of the repository in the logs?

**Comment by oliverchang** [comment]
Thanks for the suggestion. 

All logs should now start to have revisions prepended to them (05:50:20:589250.log in https://console.cloud.google.com/storage/browser/imagemagick-logs.clusterfuzz-external.appspot.com/libFuzzer_imagemagick_encoder_wpg_fuzzer/libfuzzer_ubsan_imagemagick/2018-04-12 for an example).

**Comment by dlemstra** [comment]
Thanks for adding this @oliverchang !
