### ISSUE TITLE
Permission issue to access a ticket

### ISSUE THREAD

**Issue by rouault** [google/oss-fuzz#1251]
https://oss-fuzz.com/v2/crash-stats?block=day&days=7&end=422579&group=platform&number=count&project=gdal&sort=total_count shows a ticket https://oss-fuzz.com/v2/issue/6193236899004416/2661 , but I can't access it. I get a " You do not have permission to view the requested page. Reason: User is not allowed to view this issue " whereas this is a GDAL ticket, so I should have access to it

**Comment by inferno-chromium** [comment]
Some glitch caused ccs to not happen at bug filing. manually added now, all other bugs look ok. closing.

**Comment by rouault** [comment]
Thanks
