### ISSUE TITLE
Give reproducer downloads a file extension!

### ISSUE THREAD

**Issue by garydgregory** [google/oss-fuzz#12525]
I download a reproducer and it does not have a file extension, so I don't know how to use it, it does not seem to be a zip file...

TY

**Comment by DavidKorczynski** [comment]
Reproduction documentation is here https://google.github.io/oss-fuzz/advanced-topics/reproducing/ which details how to use the reproducer files.

**Comment by jonathanmetzman** [comment]
Right. The reproducers are meant to be fed to fuzzers, so the extension for these could be anything. And an extension wouldn't really be helpful because e.g. even if the input is a corrupted zip, it's not mean to be opened with a zip too.
