### ISSUE TITLE
Testcase with zero bytes

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#1252]
While trying to find test cases that result in an out-of-memory for this issue "https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6691" I found the test case "11:41:38:123574.testcase" in this folder: https://console.cloud.google.com/storage/browser/imagemagick-logs.clusterfuzz-external.appspot.com/libFuzzer_imagemagick_encoder_gif_fuzzer/libfuzzer_ubsan_imagemagick/2018-03-16. But this test case is zero bytes. I don't understand how this could result in an out of memory. I also tried other testcases and none of them go past 8mb so I wonder if there is an issue with the out of memory detection. Or do we need to look for a memory leak that could cause this when the fuzzer is executed multiple times?

**EDIT:** I did find a memory leak, could this be the cause?

**Comment by oliverchang** [comment]
I think it's likely that there is an issue happening with the fuzzer being executed multiple times, rather than there being an issue in the OOM detection.

How did you find the memory leak (per your edit)?

**Comment by dlemstra** [comment]
I found the memory leak by going through the code and checking each exit of the method that is being executed. Turned out that some of the exits forgot to free something. I did not check if the test cases would exit at that point.

Maybe it would be interesting to do a memory leak check with the test case when the OOM is not reproducible?

**Comment by inferno-chromium** [comment]
Weird that LSan never caught this ?

**Comment by inferno-chromium** [comment]
We are no longer filing unreproducible oom and timeouts which could be the cause of the reason Oliver cited - "I think it's likely that there is an issue happening with the fuzz target being executed multiple times, rather than there being an issue in the OOM detection."

I don't see any new OOM, so closing this.
