### ISSUE TITLE
Reported issues are hidden in the new issue tracker

### ISSUE THREAD

**Issue by maflcko** [google/oss-fuzz#12534]
Steps to reproduce:
* Go to testcase-detail without issue. For example https://oss-fuzz.com/testcase-detail/6582005385461760 didn't have an issue reported.
* Click on "Create an issue" and select "[x] CC me on the issue?"
* Open the issue and get "Access is denied to this issue", even after log-in. The URL would be https://issues.oss-fuzz.com/u/3/issues/369374541 (u3 for me)

**Comment by jonathanmetzman** [comment]
Since youre already looking into the issue tracker, can you take a look at this when you get a chance Vitor?

**Comment by vitorguidi** [comment]
There are two tickets from bitcoin-core that got automatically deleted, I am looking into it to know what triggered, probably some false positive in our automations. This does not seem like a widespread problem.

**Comment by vitorguidi** [comment]
I undeleted these two bugs, please let me know if you can now access them. If no further concern besides these two issues is raised, I will close the issue.
