### ISSUE TITLE
Cannot reproduce out-of-memory bug

### ISSUE THREAD

**Issue by rouault** [google/oss-fuzz#1255]
I'm trying to reproduce https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=7019

I've first tried using https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md instructions ("Reproduce using latest OSS-Fuzz build" section) but unsuccessfully. The 100 iterations run ends up fine

I then downloaded https://storage.cloud.google.com/clusterfuzz-builds/gdal/gdal-address-201803180610.zip from the "Build" link in the testcase , unzipped it and ran
```
$ ./shape_fuzzer -timeout=25 -rss_limit_mb=2048 -runs=100 ~/Téléchargements/clusterfuzz-testcase-shape_fuzzer-5755325421453312 
INFO: Seed: 1792886423
INFO: Loaded 1 modules   (320340 inline 8-bit counters): 320340 [0x55d0d10, 0x561f064), 
INFO: Loaded 1 PC tables (320340 PCs): 320340 [0x561f068,0x5b025a8), 
./shape_fuzzer: Running 1 inputs 100 time(s) each.
Running: /home/even/Téléchargements/clusterfuzz-testcase-shape_fuzzer-5755325421453312
Executed /home/even/Téléchargements/clusterfuzz-testcase-shape_fuzzer-5755325421453312 in 10547 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
```

**Comment by rouault** [comment]
Disregard the above GDAL commit messages. I just copied&pasted the wrong URL in them...

**Comment by inferno-chromium** [comment]
Can you try with setting ASAN_OPTIONS in environment, as highlighted in report. Maybe the higher redzone helps here.

ASAN_OPTIONS = redzone=1024:strict_string_check=1:strict_memcmp=1:allow_user_segv_handler=0:allocator_may_return_null=1:handle_sigfpe=1:handle_sigbus=1:detect_stack_use_after_return=1:alloc_dealloc_mismatch=0:print_scariness=1:strip_path_prefix=/workspace/:max_uar_stack_size_log=16:quarantine_size_mb=10:detect_odr_violation=0:handle_sigill=1:allocator_release_to_os_interval_ms=500:coverage=0:use_sigaltstack=1:fast_unwind_on_fatal=0:detect_leaks=1:print_summary=1:handle_abort=1:check_malloc_usable_size=0:detect_container_overflow=1:symbolize=0:handle_segv=1

**Comment by rouault** [comment]
> Can you try with setting ASAN_OPTIONS in environment, as highlighted in report.

Doesn't help when running ./shape_fuzzer directly. I'm not sure if it is propagated when using  `python infra/helper.py reproduce` ?

**Comment by rockdaboot** [comment]
Looks like I have a similar problem with two new issues:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=7580
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=7588

Not sure if someone reads my comment on #7480, so I copy&paste it here (the bugs are not security related, but I remove the project name):

I can build the fuzzers without instrumentation in a way they simply test the corpus/corpora once.

For the reproducer corpus, valgrind tells me:

$ valgrind ./fuzzer
==16604== Memcheck, a memory error detector
==16604== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==16604== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==16604== Command: ./fuzzer
==16604==
testing 450193 bytes from '/home/.../fuzz/fuzzer.repro/clusterfuzz-testcase-minimized-fuzzer-5752886257516544'
==16604==
==16604== HEAP SUMMARY:
==16604==     in use at exit: 0 bytes in 0 blocks
==16604==   total heap usage: 223,467 allocs, 223,467 frees, 14,946,816 bytes allocated
==16604==
==16604== All heap blocks were freed -- no leaks are possible
==16604==
==16604== For counts of detected and suppressed errors, rerun with: -v
==16604== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

That's ~15Mb counting all mallocs together, a bunch of it is malloc/free pairs in loops/functions. The max. memory usage is around 1-2 MB from my estimation and by far not 2GB.

**Comment by randombit** [comment]
I just (today) encountered a similar issue to @rockdaboot. OSS-Fuzz reported OOMs that I could not replicate. Valgrind reported no leaks and reasonable allocation counts (under 20 MB).

Then I tried AddressSanitizer (Clang 6.0) copying the `ASAN_OPTIONS` from the bug page. Again testcase worked fine.

Then I enabled libFuzzer (instead of the "read-stdin" test fuzzer). Again, it worked.

Then I added `-runs=100`, and OOM.

Then I unset `ASAN_OPTIONS`, and `-runs=100` also works.

Seems like an ASan problem to me.

**Comment by Dor1s** [comment]
For most of the recent OOMs the issue is the redzone size. We've recently started enabling larger redzones for a fraction of fuzzing sessions, as it may help to detect some bugs. However, there is a downside. If a fuzz target does many allocations, redzones drastically increase memory overhead and produce non-valid OOM bugs. We've landed a fix for that and also closed a bunch of OOMs that have been reported due to that (e.g. issues 7019, 7580, 7588 all got closed ~2 hours ago).

We apologize for the inconvenience a thank you for reporting the issue.

**Comment by Dor1s** [comment]
@rockdaboot re:
> Not sure if someone reads my comment on #7480, so I copy&paste it here (the bugs are not security related, but I remove the project name):

I guess you meant https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=7580. Unfortunately, it's nearly impossible to read all comments on all the issues, so yes, likely noone would read a comment on the bug, unless any of OSS-Fuzz team members is explicitly CC'd on the issue.

To contacts us, we have the following line in the bottom of every issue description:

> If you have questions for the OSS-Fuzz team, please file an issue at https://github.com/google/oss-fuzz/issues.

**Comment by rockdaboot** [comment]
@Dor1s Thanks for fixing the issue that fast.

> If you have questions for the OSS-Fuzz team, please ...

Not being a native speaker, I stumbled about this several times in the past. At least for me it would be helpful if it says "If you have questions or information for ...". Or similar because not everything is a question.

**Comment by Dor1s** [comment]
Thanks for the feedback, @rockdaboot ! We definitely can re-phrase that sentense, I'll give it a shot :)
