### ISSUE TITLE
Projects not building daily

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#12573]
Looks like missing corpus, e.g.:
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#muparser
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#icu
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#astroid
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#xerces

**Comment by DavidKorczynski** [comment]
@jonathanmetzman do you know about this?

**Comment by jonathanmetzman** [comment]
> Looks like missing corpus, e.g.: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#muparser https://oss-fuzz-build-logs.storage.googleapis.com/index.html#icu https://oss-fuzz-build-logs.storage.googleapis.com/index.html#astroid https://oss-fuzz-build-logs.storage.googleapis.com/index.html#xerces

Do you have a rough estimate for how many started failling?

**Comment by DavidKorczynski** [comment]
> Do you have a rough estimate for how many started failling?

Yeah, the following counts the number of projects building with coverage:

![Image](https://github.com/user-attachments/assets/f9600dfe-169d-45e9-8cd5-c0e1931f1800)


From https://introspector.oss-fuzz.com/

**Comment by DavidKorczynski** [comment]
Although, it looks like a fair amount of these are not due to projects **failing** but more due to projects not being build since 5/6/7 Oct, e.g. https://oss-fuzz-build-logs.storage.googleapis.com/index.html#ron

When I search for dates in the build page I get:

05/10/2024: 124 cases
06/10/2024: 129 cases
07/10/2024: 219 cases
08/10/2024: 489 cases
09/10/2024: 257 cases

So some have not been build daily for a few days, they will be part of the drop in the graph above.

**Comment by jonathanmetzman** [comment]
We have not switched the build cadence intentionally. I bet this is some rate limiting hurting us with builds and we aren't actually seeing a huge increase in actual coverage failures.

**Comment by jonathanmetzman** [comment]
I dont' see any evidence that it's rate limiting. I'm not sure why we aren't building all of these daily.

**Comment by jonathanmetzman** [comment]
Let me know if this doesn't improve. And definitely if emails get sent out because of failed builds (oof I think this feature is broken anyway).

**Comment by alexcrichton** [comment]
Redirecting from [here](https://github.com/google/oss-fuzz/issues/12536#issuecomment-2405953395) but at least for Wasmtime we [didn't get a build this morning](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#wasmtime) (typically happens ~10 hours ago for us)

**Comment by DavidKorczynski** [comment]
Further to @alexcrichton -- when I look at the most recent build dates on the build page I get:

05/10/2024: 40 projects
06/10/2024: 47 projects
07/10/2024: 77 projects
08/10/2024: 178 projects
09/10/2024: 223 projects
10/10/2024: 322 projects
11/10/2024: 331 projects

**Comment by amodra** [comment]
last oss-fuzz binutils build remains at Oct 8

**Comment by IvanNardi** [comment]
Same issue on nDPI since ~October 8.
Fuzzing builds seems fine, but coverage and introspector builds stopped (no logs, no mail)
![Image](https://github.com/user-attachments/assets/4b81c18e-7b57-4097-8a6c-0f25206702e8)

**Comment by oliverchang** [comment]
It looks like we have some recent quota issues. We're looking into this and will hopefully have a resolution soon.

**Comment by DavidKorczynski** [comment]
This has been resolved, it looks like all is working the 15th Oct
