### ISSUE TITLE
OSS Fuzz spamming ASF Commons security list

### ISSUE THREAD

**Issue by markt-asf** [google/oss-fuzz#12588]
OSS Fuzz has started spamming the ASF Commons security list again. This appears to have started after the migration of issues to a new issue tracker.

All Apache Commons projects at OSS Fuzz should have the following configuration:

- The primary contact for all oss-fuzz issues in Commons components should be oss-fuzz@commons.a.o
- The security team security@commons.a.o should have access to the issues but should not receive any notifications by default
- Only if security@commons.a.o stars the issue should security@commons.a.o start to receive notifications for an issue

Please restore this configuration ASAP before we have to resort to more drastic measures such as blocking all email from OSS Fuzz.

**Comment by oliverchang** [comment]
Hi @markt-asf, thanks for the report and sorry for the spam. 

I'm not entirely how this could have worked in the previous configuration at all, but my guess is that you had some filter or account-level setting set up on your end? We don't have any control over notifications being set at the level of individual emails.

With the old system, email notifications came with some annotation on the emails in the content footers that would enable users to build filters based on these contents. 

e.g. 
```
You received this message because:
  1. Reason 1.
  2. Reason 2.

You may adjust your notification preferences at:
https://bugs.chromium.org/hosting/settings
```

Is it possible you had an email filter set based on this? It's also possible that https://bugs.chromium.org/hosting/settings provides a user setting to achieve something similar, but unfortunately this page no longer works as it's been turned down so I can't confirm. 

The new Buganizer system provides something similar:

```
**Generated by Google IssueTracker notification system.

You're receiving this email because you are subscribed to updates on Google IssueTracker issue XXX where you have the roles: starred, cc**
```

Additionally, if you are able to log into the Google account associated with [oss-fuzz@commons.a.o](mailto:oss-fuzz@commons.a.o), you might be able to configure settings broadly at https://issuetracker.google.com/settings/notifications:

![Image](https://github.com/user-attachments/assets/a6663ff4-dbb3-41d3-a799-ed7489687e6a)

**Comment by markt-asf** [comment]
Oliver,

Thanks for the reply. There was/is no filtering at the ASF end. This was controlled by account settings at the oss-fuzz end. You are correct that the old system enabled notification configuration. It was this that was used but not replicated when the process was transferred to the new system. I have updated the settings for `security@commons.a.o` and restored the previous configuration so that it only receives notifications for issues when the issue is starred by that user.

The remaining issue is that the notifications are not reaching `fuzz-testing@commons.a.o`. I suspect that the sender has changed so the list will need to be reconfigured to accept messages from the new source. The amount of work required will depend on how the sender is formatted.

I intend to leave this issue open for now and update it when the required notification configuration is working.

**Comment by markt-asf** [comment]
Notifications are now reaching the fuzz-testing list. Nothing more to do here.
