### ISSUE TITLE
When clusterfuzz flips a crash to unreproducible, monorail isn't updated

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#1259]
For example:

https://oss-fuzz.com/v2/testcase-detail/4766460271394816?noredirect=1 vs. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6900

You can see the bug is out of sync with the testcase

**Comment by inferno-chromium** [comment]
Fix is in, should start happening for new bugs.
