### ISSUE TITLE
Issue 369956898 daily mail

### ISSUE THREAD

**Issue by abartlet** [google/oss-fuzz#12606]
I get daily useless updates claiming new disclosure or found dates on https://issues.oss-fuzz.com/issues/369956898

Can someone please look into it and get this back to one mail per new issue or significant event please?

**Comment by douglasbagnall** [comment]
More detail:

Every day at about 00:21 UTC, we get an email saying 

```
Changed
Reported:  Oct 10, 2024 → Oct 11, 2024
```

and most days at about 16:00 UTC (but variable), another message saying
```
Changed
Disclosure:  Jan 8, 2025 → Jan 9, 2025
```

The "reported" and "disclosure" times march steadily forward in time. The original report was "Sep 27, 2024" and the disclosure "Dec 26, 2024".

**Comment by oliverchang** [comment]
Apologies for the noise! We've identified the cause and have temporarily paused the job that was responsible for sending this erroneous notifications while we fix the underlying bug.

**Comment by oliverchang** [comment]
CC @alex also who reported this in https://github.com/google/oss-fuzz/issues/12508#issuecomment-2403861681

**Comment by oliverchang** [comment]
This should no longer occur.
