### ISSUE TITLE
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### ISSUE THREAD

**Issue by Lz892** [google/oss-fuzz#12683]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

#### References

_Originally posted by @Lz892 in https://github.com/trufflesecurity/trufflehog/issues/3549_

**Comment by DavidKorczynski** [comment]
spam
