### ISSUE TITLE
No CC to me for PHP issues

### ISSUE THREAD

**Issue by iluuu1994** [google/oss-fuzz#12717]
Hi! I'm a maintainer of the PHP project. I'm listed in the project.yaml file.

https://github.com/google/oss-fuzz/blob/0bc3d2f1ce0e8fa5c7d95029690f3644e5f4cca5/projects/php/project.yaml#L8

I've noticed that I stopped receiving e-mails for new issues. My e-mail isn't listed in the CC section either. For example:

https://issues.oss-fuzz.com/issues/376496310

![Image](https://github.com/user-attachments/assets/d26cf024-9610-4888-a97e-525be72fd16f)

Is there anything I can do to receive these e-mails again? Thank you for your help!

**Comment by jonathanmetzman** [comment]
Sorry, our new bug tracker doesn't support non-google accounts and our old tracker has been turned down.
Could you add another account that is a google account? We're working on a solution but I don't know when it will be ready.
