### ISSUE TITLE
Coverage failing for my project Grok

### ISSUE THREAD

**Issue by boxerab** [google/oss-fuzz#12797]
https://github.com/GrokImageCompression/grok

shows coverage failure. 

https://issues.oss-fuzz.com/issues?q=proj:grok

How do I find out what the issue is ?

Thanks!

**Comment by jonathanmetzman** [comment]
For other OSS-Fuzz mainainters:
Grok's issue isn't caused by the oss-fuzz infra, as there are successful backups each day.

**Comment by DavidKorczynski** [comment]
Similar issues are happening in fast_float: https://github.com/fastfloat/fast_float/issues/297
