### ISSUE TITLE
AFL support

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#128]
Let's try to support AFL in Q1'17, same way we already to it in Chrome.

**Comment by kcc** [comment]
FYI: the most recent afl now support trace-pc-guard, so we should start using trace-pc-guard for afl too.

**Comment by oliverchang** [comment]
We have experimental support on CF now for AFL. This is currently enabled for woff2, libarchive, and ffmpeg. I'll wait for @mikea to come back before turning it on everywhere. Another issue might be that it'll slow down our builder even more (#400)

To enable a fuzzer with AFL, add:

```
fuzzing_engines:
 - afl
 - libfuzzer
```

**Comment by oliverchang** [comment]
AFL is enabled everywhere now.

**Comment by kcc** [comment]
Sweeeeet! 
If AFL finds something before libFuzzer does, we will see 'afl' in the bug reports, right?

**Comment by oliverchang** [comment]
Yep! You can also take a look at what AFL is finding in general (even if libFuzzer already found them) here: https://oss-fuzz.com/v2/crash-stats?end=413783&fuzzer=afl&hours=24&order=total_count
