### ISSUE TITLE
Crash not auto-closing?

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#1282]
https://oss-fuzz.com/v2/testcase-detail/4766460271394816?noredirect=1 says it will autoclose on te 27th, which is two days ago. The bug is still open :-)

**Comment by dlemstra** [comment]
Looks like there is now a reproducible related issue: https://oss-fuzz.com/v2/testcase-detail/5076244040253440.

**Comment by dlemstra** [comment]
@alex This issue appears to be closed now.

**Comment by jonathanmetzman** [comment]
@alex could you add more context on what happened please? 

I assume there was an unreproducible crash that stayed open for longer than the date ClusterFuzz said it would stay open until?
Just guessing the unreproducible crash was found again but still could not be reproduced consistently. 

I suppose in that case the correct behavior is for clusterfuzz to update the autoclose-by-date (assuming my guess about what happened is correct).

**Comment by alex** [comment]
That all sounds correct, including the expected behavior.

**Comment by inferno-chromium** [comment]
This is a minor annoyance. Our auto-close date is based on exact crash state, while bug-closing behavior looks at similar looking crash state, SetPixelIndex vs SetPixelGreen. we can't calculate auto-close date on the fly with similar looking crash state since that query is expensive.
