### ISSUE TITLE
All builds stopped

### ISSUE THREAD

**Issue by yawkat** [google/oss-fuzz#12879]
Not sure if you noticed yet, but it seems all projects have stopped building: https://oss-fuzz-build-logs.storage.googleapis.com/index.html

I see most builds on dec 18th, a few on dec 19th, and none after that. So I assume it broke on the 19th. Maybe #12871? But the diff seems harmless.

**Comment by DavidKorczynski** [comment]
Thanks -- we're aware and I was hoping https://github.com/google/oss-fuzz/pull/12876 would resolve it. See https://github.com/google/oss-fuzz/pull/12831#issuecomment-2557474087 If it's not resolved today I'll look further into it.

**Comment by jonathanmetzman** [comment]
I think your fix didn't work because it was deployed (because I didn't deploy it, not even sure you can).
Deploying now. I'll kick off another build after

**Comment by jonathanmetzman** [comment]
I think I've fixed this now, first build (skcms) seems to pass the bug.

**Comment by jonathanmetzman** [comment]
The others seemed to pass. Of course https://oss-fuzz-build-logs.storage.googleapis.com/index.html isn't updating because of some other bug. i'll try to fix it tomorrow.
Thanks for the bug report.

**Comment by DavidKorczynski** [comment]
Thanks @jonathanmetzman -- the builds are working well now
