### ISSUE TITLE
Coverage Report Shows 0%

### ISSUE THREAD

**Issue by korovindenis** [google/oss-fuzz#12878]
When trying to generate a coverage report for the suricata target, the coverage report at http://localhost:8008/linux/src/report.html shows 0% in the Totals Coverage Report.

Steps to Reproduce:  
```
git clone https://github.com/google/oss-fuzz.git
cd oss-fuzz
python3 infra/helper.py build_image suricata
python3 infra/helper.py build_fuzzers --sanitizer=coverage suricata
python3 infra/helper.py coverage --public suricata
python3 infra/helper.py coverage --no-corpus-download suricata
```
Expected Behavior:  
I expected the suricata fuzz target to generate a proper coverage report with a nonzero percentage for the code coverage in report.html.

---

Observed Behavior: 
![Image](https://github.com/user-attachments/assets/4bdc2e13-5f98-4958-aa69-281162040caa)

Folder oss-fuzz/build/corpus/suricata:
![Image](https://github.com/user-attachments/assets/6b07b64b-f1ad-443a-aee7-11fd5ded3879)

**Comment by jonathanmetzman** [comment]
Sorry for that, I'm taking a look at what I think is the root cause here.

**Comment by jonathanmetzman** [comment]
Fee free to reopen if I close that issue and this is still not resolved.
