### ISSUE TITLE
500 in fuzer-stats

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#1302]
URL: https://oss-fuzz.com/v2/fuzzer-stats/by-fuzzer/2018-03-31/2018-04-06/fuzzer/libFuzzer_imagemagick_encoder_pict_fuzzer/job/libfuzzer_ubsan_imagemagick

![screen shot 2018-04-07 at 1 25 47 pm](https://user-images.githubusercontent.com/772/38458064-3742fd7a-3a67-11e8-83b9-e9a8130cfbaf.png)

**Comment by inferno-chromium** [comment]
We are aware of this, but dont have a fix idea yet. you can workaround this by refreshing page in ~30sec and it should load.

**Comment by jonathanmetzman** [comment]
It's still difficult to figure out what exactly is causing this issue, but I'll try out a fix I have in mind tomorrow.

**Comment by jonathanmetzman** [comment]
Should be fixed now. Please reopen if you see this again.
