### ISSUE TITLE
qcms

### ISSUE THREAD

**Issue by pdknsk** [google/oss-fuzz#1308]
I noticed that `qcms` is one of the suggested projects to be added. I've been fuzzing `qcms` for a while, and have a _heap-buffer-overflow_  pending currently. When that gets fixed, I'm interested in adding `qcms`.

I shall point out though that the [official source](https://hg.mozilla.org/mozilla-central/file/tip/gfx/qcms/) is in the Firefox code base. For that reason it won't quite be _ideal integration_. Unlike the [suggested copy](https://github.com/jrmuizel/qcms), it is occasionally updated. If you still want to have it added, I'll ask Mozilla.

**Comment by Dor1s** [comment]
There are Mozilla people who are active on OSS-Fuzz, I guess they may help to upstream necessary parts //cc @alex

**Comment by pdknsk** [comment]
With *ideal integration* I meant having the fuzz target in the source repository. Everything else works. I assume Mozilla does not want `oss-fuzz` fuzz targets in its Firefox repository, as a [search for 
 LLVMFuzzerTestOneInput](https://dxr.mozilla.org/mozilla-central/search?q=LLVMFuzzerTestOneInput) reveals no relevant hits.

**Comment by alex** [comment]
We wrap libFuzzer/AFL with our own API in several cases: https://searchfox.org/mozilla-central/search?q=MOZ_FUZZING_INTERFACE_RAW&redirect=false (this API loads libFuzzer up _after_ we've initialized XPCOM)

We also use libFuzzer and OSS-Fuzz for testing nss.

We'd have to figure out where it'd live and how it'd integrate into our build system, but I'd love to have more libFuzzer targets in Firefox.

**Comment by inferno-chromium** [comment]
Note that ideal integration is not a blocker. Initially, it is fine to have fuzz target in our repo and then eventually move it. Or as @alex said, support is already there, so i think it should be fine to add fuzz target in mozilla repo directly.
