### ISSUE TITLE
Crash Statistics project filter

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#1309]
It looks like the project filter of the Crash Statistics page has a tiny bug. With the url https://oss-fuzz.com/v2/crash-stats?block=day&days=7&end=423106&group=platform&number=count&project=imagemagick&sort=total_count we see issue for our project but for some reason there is also a link to this issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4390. And that is not an issue for the imagemagick project.

**Comment by inferno-chromium** [comment]
Thanks for reporting this. This actually made me fix it, also there was a bigger issue of testcase being duplicated across projects which we shouldn't do. Right on crash stats, you wont see a testcase link, but in time you will see a testcase created specifically from your own project.

**Comment by dlemstra** [comment]
Thanks for the quick fix 👍 Really happy with how my issues are handled.
