### ISSUE TITLE
wpantund: bad build, partial instrumentation

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1328]
Has been detected after lading #838

```
root@2d14f453ace2:/out# ./ncp-spinel-fuzz 
INFO: Seed: 4186706769
INFO: Loaded 1 modules   (3 inline 8-bit counters): 3 [0x8a16e8, 0x8a16eb), 
INFO: Loaded 1 PC tables (3 PCs): 3 [0x64e2b0,0x64e2e0), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2	INITED cov: 2 ft: 2 corp: 1/1b lim: 4 exec/s: 0 rss: 34Mb
^C==17== libFuzzer: run interrupted; exiting
```

> INFO: Loaded 1 PC tables (3 PCs): 3 [0x64e2b0,0x64e2e0), 

3 PCs doesn't look right. Compare it with another fuzz target from the same project:

```
root@2d14f453ace2:/out# ./wpantund-fuzz 
INFO: Seed: 4189433736
INFO: Loaded 1 modules   (18217 inline 8-bit counters): 18217 [0xb10348, 0xb14a71), 
INFO: Loaded 1 PC tables (18217 PCs): 18217 [0x819f90,0x861220), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2	INITED cov: 29 ft: 11 corp: 1/1b lim: 4 exec/s: 0 rss: 36Mb
	NEW_FUNC[0/1388]: 0x528970 in nlpt_hook_check_read_fd_source /src/wpantund/src/wpantund/./wpantund.cpp:441
	NEW_FUNC[1/1388]: 0x52c030 in NCPInputFuzzTarget(unsigned char const*, unsigned long) /src/wpantund/src/wpantund/wpantund-fuzz.cpp:99
#21	NEW    cov: 2357 ft: 2349 corp: 2/2b lim: 4 exec/s: 21 rss: 41Mb L: 1/1 MS: 3 InsertByte-ChangeByte-EraseBytes-
```

**Comment by Dor1s** [comment]
//cc @darconeous could you please take a look? I guess `$CFLAGS` / `$CXXFLAGS` are not used when `ncp-spinel-fuzz` is built

**Comment by Dor1s** [comment]
Ping.

**Comment by darconeous** [comment]
I'm on baby bonding leave. @abtink, can you have a look?

**Comment by abtink** [comment]
I will take a look to see if it's something quick I can help address. But to be clear, I won't be able to spend much time on this. There are already a lot of other stuff on my plate.

**Comment by Dor1s** [comment]
Thanks @abtink. Our infrastructure provide `$CFLAGS` / `$CXXFLAGS` that should be used for compilation of a target project. That way we ensure we have a proper instrumentation for every piece of it.

In case of `ncp-spinel-fuzz` mentioned above, it looks like everything is compiled without using the flags provided. Most likely only the last compilation step (e.g. `clang++ fuzz_target.cpp other_stuff_compiled_before.o -o fuzzer_target`) uses the right flags

**Comment by abtink** [comment]
The PR is merged.

**Comment by inferno-chromium** [comment]
fixed, thanks!
