### ISSUE TITLE
mercurial: bad build, partial instrumentation

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1333]
Has been detected after lading #838 

https://oss-fuzz-build-logs.storage.googleapis.com/index.html

```
Step #5: INFO: performing bad build checks for /workspace/out/address/bdiff_fuzzer.
Step #5: INFO: performing bad build checks for /workspace/out/address/xdiff_fuzzer.
Step #5: Broken fuzz targets (1):
Step #5: bdiff_fuzzer:
Step #5: BAD BUILD: the target seems to have only partial coverage instrumentation.
Step #5: ERROR: 50% of fuzz targets seem to be broken. See the list above for a detailed information.
```

**Comment by Dor1s** [comment]
//cc @durin32

It might be that the target is compiler properly, but is very small:

```
root@a80f833976b4:/out# ./bdiff_fuzzer 
INFO: Seed: 1920559767
INFO: Loaded 1 modules   (116 inline 8-bit counters): 116 [0x8a46a8, 0x8a471c), 
INFO: Loaded 1 PC tables (116 PCs): 116 [0x650970,0x6510b0), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2	INITED cov: 26 ft: 27 corp: 1/1b lim: 4 exec/s: 0 rss: 34Mb
#5	NEW    cov: 30 ft: 31 corp: 2/3b lim: 4 exec/s: 0 rss: 35Mb L: 2/2 MS: 3 ChangeByte-ShuffleBytes-InsertByte-
```

@durin42 do you know if that's the case? Would it be possible / would it make sense to extend the fuzz target functionality so it would have more code reachable?

**Comment by durin42** [comment]
I'm confused. The coverage of bdiff.c looks really good: https://oss-fuzz.com/coverage_report/job/libfuzzer_asan_mercurial/latest/f/%2Fsrc%2Fmercurial%2Fmercurial%2Fbdiff.c

It is a *tiny* piece of code, but an important one that's given us trouble in hg in the past. Does it being small explain the complaint? Or should I dig more?

**Comment by Dor1s** [comment]
Thanks for the quick response! Most of the fuzz targets we're running have at least a couple hundred of PCs, so tiny targets like `bdiff_fuzzer` are suspected to be not fully instrumented by the bad build checks.

However, I agree that some times those are valid fuzz targets just like the yours. I can add an exception for `bdiff_fuzzer` or lower down the threshold to ~100 of PCs. Let me think a bit.

**Comment by durin42** [comment]
Yeah, feel encouraged to hit me up on corp chat (though I'm America/New_York, so AFK for the day) or schedule a meeting if you want to bounce more ideas in real time. I'm augie@.

**Comment by Dor1s** [comment]
I've checked the fuzz target. Indeed, it doesn't look like we can add anything else as you're already calling all APIs from bdiff.h.

I believe that it would be fine to lower the threshold to ~100, as completely broken fuzz targets usually have even smaller number of instrumented PCs.
