### ISSUE TITLE
wget: broken build (tests are failing)

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1353]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

```
Step #10: FAIL: wget_ftpls_fuzzer
Step #10: PASS: wget_options_fuzzer
Step #10: PASS: wget_css_fuzzer
Step #10: PASS: wget_html_fuzzer
Step #10: ============================================================================
Step #10: Testsuite summary for wget 1.19.4.72-b0f80
Step #10: ============================================================================
Step #10: # TOTAL: 4
Step #10: # PASS:  3
Step #10: # SKIP:  0
Step #10: # XFAIL: 0
Step #10: # FAIL:  1
Step #10: # XPASS: 0
Step #10: # ERROR: 0
Step #10: ============================================================================
Step #10: See fuzz/test-suite.log
Step #10: Please report to bug-wget@gnu.org
Step #10: ============================================================================
Step #10: Makefile:1812: recipe for target 'test-suite.log' failed

```

//cc @rockdaboot

**Comment by rockdaboot** [comment]
Has been repaired 8 hours before. The test suite with UBSAN failed, fixed three different integer overflows. Just pushed another fuzzer + initial corpora, crossing fingers for the next build (but this time I also checked building with UBSAN flags).

**Comment by rockdaboot** [comment]
BTW, when comes the long promised (automatic) email notification on broken builds ? Is there an issue open for it ?

**Comment by Dor1s** [comment]
Thanks for the reply! As for the email notifications, yes there is a bug (https://github.com/google/oss-fuzz/issues/333), but no ETA at the moment :(

**Comment by inferno-chromium** [comment]
fixed!
