### ISSUE TITLE
Linkify source for sourceforge

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#1361]
If you look at a report for the graphics magick, neither commits nor source code paths are linkified.

I think it should be possible to handle this, since the sourceforge web UI is a standard hgweb: http://hg.code.sf.net/p/graphicsmagick/code/

**Comment by durin42** [comment]
log between revisions example:

https://www.mercurial-scm.org/repo/hg-committed/log?rev=009aa4af5093%3A%3A02f992ac26e9&revcount=200

(that is, rev is $NODE_1::$NODE_2, and set revcount to something that's likely big enough for the project but small enough as to not melt servers.)

**Comment by inferno-chromium** [comment]
@durin42 @alex 
any idea why

http://hg.code.sf.net/p/graphicsmagick/code/log?rev=ebd3eb090848%3A%3A535883a4cf4d&revcount=100 does not work ?

**Comment by alex** [comment]
I'll file a bug on hg this evening, when I'm back at a computer  that has those creds.

**Comment by inferno-chromium** [comment]
actually this works for mozilla.org

https://hg.mozilla.org/mozilla-central/log?rev=47e81ea1ef10189ef210867934bf36e14cf223dc%3A%3A1bdf8e7d1cfe6d8b9bfa891f43473345210ee281&revcount=10000

so, it is /log?rev=

**Comment by durin42** [comment]
The `hg-committed` is the name of a repo - I'm surprised that doesn't 404 on SourceForge.

It's not working on SF almost for sure because they're running an *ancient* hg. Do you have any contacts over there? All mine are long gone...

**Comment by inferno-chromium** [comment]
See links in https://oss-fuzz.com/v2/testcase-detail/4634864576888832 (qcms) work nicely with https://hg.mozilla.org/

for grahicsmagick, you need to get their mercurial version fixed. see https://oss-fuzz.com/v2/testcase-detail/6241781560639488, everything works except http://hg.code.sf.net/p/graphicsmagick/code/log?rev=356b0eba718c996d67c214b5844da92da7c5003e%3A%3Af98187e882129a8e108c937d32f15807fb8f5a86&revcount=10000
