### ISSUE TITLE
skia: UBSan build is crashing on seed corpus

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1364]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

5 fuzz targets are considered broken as they crash when running on a seed corpus without any mutations.

//cc @kjlubick

**Comment by kjlubick** [comment]
Is this new?  Can we opt out?

**Comment by inferno-chromium** [comment]
@kjlubick - yes that check is a little noisy without auto-bug creation (esp here vs monorail). we are disabling the check now.

**Comment by Dor1s** [comment]
Yes, the post-build check is new, but the idea is not, as it matches requirements of [Ideal Integration Guide](https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md#regression-testing). There is no way to opt out. Fuzz targets that crash on seed corpus are considered broken and not useful until those crashes get fixed. If we upload and run those targets, we simply waste CPUs crashing on corpus again and again.

However, we've temporarily disabled that check until we implement bug auto-filing for broken builds.

**Comment by kjlubick** [comment]
Thanks - will the autobug give a list of bad inputs to make it easy to remove from the corpus?  Or will there be a script I can run locally to double check the seed corpus is clean?

**Comment by Dor1s** [comment]
Removing inputs from the corpus is a wrong way to fix this :)

But yes there will be a way to reproduce that locally: 1356

**Comment by inferno-chromium** [comment]
No need to track here, you should see a bug filed with title "<Project>: Build failure" in monorail tracker.
