### ISSUE TITLE
assert failures not recognized as such

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#1380]
E.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8079 says "Abrt"
while it should show the failed assertion.

Other projects (e.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8016) get this just fine.

**Comment by inferno-chromium** [comment]
everyone likes using their own assertion failure message.

this one is like "assert failure:", we can add a signature for that. we have ones for things like "assertion failed", etc.

**Comment by inferno-chromium** [comment]
@oliverchang fixed this already.
