### ISSUE TITLE
fix new project guide for msan

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1396]
i think project.yaml section can be fixed, should we change the defaults to enable msan by default OR encourage people to try MSan for sure ?

also, this text "MemorySanitizer is in development mode and not recommended for use." should be changed.

**Comment by oliverchang** [comment]
We shouldn't change the project.yaml defaults. I'll change the documentation.

**Comment by inferno-chromium** [comment]
sgtm to encouraging/later debugging in docs
