### ISSUE TITLE
"Setting up fuzzers for a new library" doc is unclear

### ISSUE THREAD

**Issue by dvyukov** [google/oss-fuzz#14]
https://github.com/google/oss-fuzz/blob/master/docs/new_library.md#dictionaries-and-custom-libfuzzer-options

```
Any top-level files in the library directory ending with the extension ".dict" or ".options" will be picked up by ClusterFuzz. Files ending with ".dict" are assumed to be libFuzzer compatible dictionaries, and .options files have the format:

[libfuzzer]
dict = dictionary_name.dict
max_len = 9001
```

If .dict files are picked up by ClusterFuzz and are assumed to be libFuzzer compatible dictionaries, why do they need to be specified in the config file? Are they picked up iff they are specified in the config? Will they be picked up if I don't specify them in the config?...

**Comment by dvyukov** [comment]
What is `library directory`? Is it on host? Or in the image?...
If it's in the image, how do add additional files there?

**Comment by dvyukov** [comment]
```
$ python scripts/helper.py run_fuzzer $LIB_NAME name_of_a_fuzzer
```

What is name_of_a_fuzzer? Not mentioned anywhere else.

**Comment by oliverchang** [comment]
Thanks for the feedback! We'll be sure to address them in our documentation.

To answer your first question, we require the config to allow sharing of dicts between different fuzzers in a library. You're right though, in that we may be able to default to picking up dicts with the same name as the fuzzer binary.

Library directory refers to the directory where the config files are stored in the repo.

name_of_a_fuzzer is just the name of the fuzzer you're building.

**Comment by mikea** [comment]
I made another pass on Dictionary/Corpus parts. Please let us know if it still not clear.

**Comment by dvyukov** [comment]
Looks good to me now.
