### ISSUE TITLE
Allow change of status in Monorail.

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#1402]
Our @ImageMagick project is fuzzing itself and various dependencies. One of the fuzzers is checking the code of the libraw library. For some of the issue the maintainer does not want to patch the code (e.g. https://github.com/LibRaw/LibRaw/issues/153#issuecomment-387364818). I understand his point of view and it should be okay for a maintainer to mark some issues as won't fix. 

But this kind of messes up my page where I view the open issues: https://bugs.chromium.org/p/oss-fuzz/issues/list?can=2&q=ImageMagick&colspec=ID+Type+Component+Status+Proj+Reported+Owner+Summary&cells=ids. I have no way to change the status of an issue to "upstream" (reported upstream) or "wontfix" so I can filter those kind out issues out of the list. I now mark them as "favorite" so I know I don't need to look at them anymore but that feels a bit odd.

p.s. Where should I report that the monorail page no longer supports right click on the issues list (forced to use ctrl-click).

**Comment by inferno-chromium** [comment]
I have added an ExternalDependency status for this.

Also, gave you EditIssueStatus and EditIssueCC permissions.

**Comment by dlemstra** [comment]
@inferno-chromium: Can you change the email to my current email? I can no longer update issues after I changed my email to: `dirk@lemstra.org`.

**Comment by Dor1s** [comment]
@dlemstra what needs to be changed in https://github.com/google/oss-fuzz/blob/master/projects/imagemagick/project.yaml?

**Comment by dlemstra** [comment]
I used to be able to change the status of an issue @Dor1s. Is it possible to configure that in the project.yaml file now? Last year @inferno-chromium gave me permissions to change the status. But that was done with my old email. I changed my email earlier this year and I would like to get the `EditIssueStatus` and `EditIssueCC` back.

**Comment by inferno-chromium** [comment]
Ok done, added EditIssueStatus and EditIssueCC to dirk@lemstra.org and removed from dirk@git.imagemagick.org
