### ISSUE TITLE
Merging corpora questions

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#1406]
When updating the corpora from oss-fuzz, often thousands of files are downloaded (which is BTW extremely slow). After performing a merge step using clang-built fuzzers, the number of corpora reduces by a large number (e.g. 1.7k files downloaded, 550 after merge step). While doing the merge I often see detected UBSAN issues, that have not been reported by oss-fuzz.

From this arise three questions:
1. Can't you merge/minimize the corpora on your side to reduce download time ?
2. Why is downloading using 100% CPU on one core while using a pretty low bandwidth (1.1mbps down, 500kbps down) - I believe I have never seen a slower download client ever. An easy work-around could be zipp'ed archive with all the corpora.
3. Why haven't those UBSAN issues being reported by oss-fuzz ?

**Comment by kcc** [comment]
1. We have recently started using `-use_value_profile=1` during the merge, which blows up the corpus (but sometimes improves coverage, so it's worth it). If you merge with this flag you will most likely see that the corpus is close to minimal

2. Are you using `gsutil -m cp ... `?

3. Dunno. Need an example. (Or maybe others have a clue)

**Comment by kcc** [comment]
3: What flags for ubsan are you using?
-fsanitize=unsigned-integer-overflow and null are not enabled in our builds.

**Comment by oliverchang** [comment]
> An easy work-around could be zipp'ed archive with all the corpora.

This exists under `gs://PROJECTNAME-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/`, or through the "corpus_backup" links on the fuzzer statistic page for your targets.

I'll update the documentation to highlight this.

**Comment by rockdaboot** [comment]
> This exists under gs://PROJECTNAME-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/

Thx. To make download a little bit easier and stable, a `...-latest.zip`, pointing to the latest corpus zip file, would be perfect.

**Comment by rockdaboot** [comment]
> 3: What flags for ubsan are you using?
> -fsanitize=unsigned-integer-overflow and null are not enabled in our builds.

@kcc Thx, that explains it. I once took the flags from the docker build and they have changed since then. I keep them since the null flag just detected two real problems in Wget. And I fixed ~20 integer overflows - some of them were false positives (or intended behavior) but some were real bugs in parsers.

**Comment by rockdaboot** [comment]
@Dor1s Thx, that works and is 100x faster than a simple rsync or cp :-)

**Comment by kcc** [comment]
> null flag just detected two real problems in Wget. And I fixed ~20 integer overflows 

We can not enable these flags for all users because 
a) unsigned-integer-overflow is not a UB according to the C++ spec (it may still be a dangerous logical and security bug, it's great that you've fixed those) 
b) null will require huge cleanup for most projects. 

But you can enable extra ubsan checks yourself for your project. 
Check e.g. projects/llvm_libcxx/build.sh or projects/librawspeed/build.sh: the do exactly that:

```
if [[ $SANITIZER = *undefined* ]]; then
  CFLAGS="$CFLAGS -fsanitize=unsigned-integer-overflow -fno-sanitize-recover=unsigned-integer-overflow"
  CXXFLAGS="$CXXFLAGS -fsanitize=unsigned-integer-overflow -fno-sanitize-recover=unsigned-integer-overflow"
fi

```
