### ISSUE TITLE
Bug fixed before disclosure deadline, embargo lifted early anyway

### ISSUE THREAD

**Issue by kjlubick** [google/oss-fuzz#1408]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6146#c8

In this case, it's a minor UBSAN bug, but it could have been something dangerous that would have benefited from the normal "30 days after fixing"

**Comment by inferno-chromium** [comment]
@oliverchang - is this how disclosure system works ?

**Comment by kcc** [comment]
looks like normal 90 days. 
From the top page: 
  After notifying project authors, we will open reported issues to the public in 90 days, or 30 days after the fix is released (**whichever comes earlier**).
