### ISSUE TITLE
All OSS-Fuzz builds failing

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#141]
https://oss-fuzz-build-logs.storage.googleapis.com/build_logs/re2/latest.txt
---------------------------------------------------------------
Compiling libFuzzer into /usr/lib/libfuzzer.a .../src/libfuzzer/FuzzerCrossOver.cpp:12:10: fatal error: 'cstring' file not found
#include <cstring>
         ^~~~~~~~~
1 error generated.

**Comment by kcc** [comment]
the file did not change for a few months, I bet this is recent Mike's changes in the build scripts.

**Comment by mikea** [comment]
Unlucky LLVM revision. Triggered new build of base-images and builds are starting to succeed.
