### ISSUE TITLE
Possible incorrect issue report.

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#1414]
I would like to report a possible incorrect issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8112. This issue was first reported with this line: https://github.com/libraw/libraw/blob/0c7fe79af2bd4de73b8790e0d506d025798ab2d8/internal/dcraw_common.cpp#L19589 and now with with this line: https://github.com/libraw/libraw/blob/8260dcf3db045923a5ca5c05170f9bc7a4bd971a/internal/dcraw_common.cpp#L18121. It looks like there is a problem with the `filters` variable but that is initialized here: https://github.com/libraw/libraw/blob/8260dcf3db045923a5ca5c05170f9bc7a4bd971a/internal/dcraw_common.cpp#L17601. And the value is not changed by something that could mark it as uninitialized. I have no idea what could be causing this report. Maybe an issue in the tooling?

**Comment by eugenis** [comment]
For example, load from a bitfield looks like a bitwise operation with a partially undefined value.
Even worse, this
`struct S {
  int b : 31;
  int a : 1;
};
void g();
void f(S *s) {
  if (s->a) g();
}`
is transformed into
`void f(S *s) {
  if (*(int *)s < 0) g();
}
`
before MSan sees it, so it has to allow comparisons of partially undefined values (think S::a defined, S::b undefined).
