### ISSUE TITLE
Consider changing order of original/most recent stacktraces

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#1416]
Currently oss-fuzz.com shows the original stacktrace first, and the most recent stacktrace second. I think it'd be helpful to reverse this, so the most-recent stacktrace is first.

The current UI often results in people looking at lines of code from the original stacktrace, which are no longer correct on the most recent version of the repository.

**Comment by oliverchang** [comment]
This seems reasonable. @inferno-chromium @mbarbella any objections?

**Comment by inferno-chromium** [comment]
@oliverchang - sgtm

**Comment by oliverchang** [comment]
This is now done. Thanks for the suggestion!
