### ISSUE TITLE
Make helper.py match production msan build.

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#1419]
If I run `infra/helper.py shell --sanitizer=memory graphicsmagick` I'm able to get past building libpng (where https://oss-fuzz-build-logs.storage.googleapis.com/index.html shows the problem) without issue.

Is there something significant different between the OSS-Fuzz environment and the local docker env?

**Comment by oliverchang** [comment]
Could you try rebuilding the graphicsmagick image with:

`python infra/helper.py build_image graphicsmagick`

and answering 'y' to

`Pull latest base images (compiler/runtime)? (y/N):`

And then run 

`python infra/helper.py build_fuzzers --sanitizer=memory  graphicsmagick`

**Comment by alex** [comment]
That's working fine.

**Comment by alex** [comment]
By working fine I mean "compiles", not "reproduces the build failure" :-)

**Comment by alex** [comment]
@oliverchang I believe this has something to do with the zlib version in the production build env, can you say what version that is?

**Comment by alex** [comment]
FWIW, we pushed a change to GM's build script that I expected to fix this (and which worked in the docker env), but it seems to have made the problem worse in the prod env. With no ability to reproduce this locally, fixing is going to be a lot of guess and test.

**Comment by oliverchang** [comment]
Sorry for the delay; swapmed with a bunch of other things.

The latest build appears to have succeeded according to https://oss-fuzz-build-logs.storage.googleapis.com/index.html.

I'm working on some changes to the helper script to make the msan build more like the production build (the difference is we pull some pre-built msan instrumented libraries)  and expect to finish that next week.

**Comment by oliverchang** [comment]
This is now implemented.
