### ISSUE TITLE
Rename ossfuzz/base-libfuzzer image

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#142]
Now that we plan #128 we should rename `base-libfuzzer` image. Probably `base-fuzzer`.

Dockerfile would look like:

```Dockerfile
FROM ossfuzz/base-fuzzer
MAINTAINER
...
```

@oliverchang kcc WDYT about new name?

**Comment by kcc** [comment]
base-fuzzing-engine? 
but really up to you.

**Comment by mikea** [comment]
Other versions: `base-fuzzer-builder`, `base-builder`.

**Comment by inferno-chromium** [comment]
Why not just base-image, i like base-builder as well. this image can have src checkout, fuzzer files, other build-files, etc ?
and can instead of FROM, can we do USE

USE ossfuzz/base-image

**Comment by mikea** [comment]
base-image sounds to generic to me. I'd also like to find a name for 'ossfuzz/base' which basically says ubuntu:16.04. 'base-X' as well. Maybe that should be base-image?

> and can instead of FROM, can we do USE

no, this is Dockerfile syntax

**Comment by mikea** [comment]
I suggest we have following image names:

- `ossfuzz/base-image` - clean ubuntu.
- `ossfuzz/base-clang` - image with clang installed.
- `ossfuzz/base-builder` - base image for creating fuzzer builders from.
- `ossfuzz/base-runner` - runner image that replicates clusterfuzz restricted environment.
- `ossfuzz/base-runner-debug` - runner image with debug utilities installed (e.g. gdb)

Are these clear enough? 

Other base-builder names candidates: `ossfuzz/base-fuzzer-builder`, `ossfuzz/base-fuzzer`, `ossfuzz/base-fuzzing-engine`.

**Comment by inferno-chromium** [comment]
LGTM, 

do we really need base-runner-debug, ideally we can have all debug utilities installed in every runner image, no ?

**Comment by mikea** [comment]
Debug tools install a lot of dependencies. It will be hard to catch the fuzzer linking dynamically.

E.g. gdb:

```
apt install gdb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  file gdbserver libbabeltrace-ctf1 libbabeltrace1 libc6 libc6-dbg libcc1-0 libexpat1 libffi6 libglib2.0-0 libglib2.0-data libicu55 libmagic1 libmpdec2 libpython3.5 libpython3.5-minimal libpython3.5-stdlib
  libsqlite3-0 libssl1.0.0 libxml2 mime-support sgml-base shared-mime-info xdg-user-dirs xml-core
Suggested packages:
  gdb-doc glibc-doc sgml-base-doc debhelper
The following NEW packages will be installed:
  file gdb gdbserver libbabeltrace-ctf1 libbabeltrace1 libc6-dbg libcc1-0 libexpat1 libffi6 libglib2.0-0 libglib2.0-data libicu55 libmagic1 libmpdec2 libpython3.5 libpython3.5-minimal libpython3.5-stdlib
  libsqlite3-0 libssl1.0.0 libxml2 mime-support sgml-base shared-mime-info xdg-user-dirs xml-core
```

**Comment by inferno-chromium** [comment]
Ok.

**Comment by inferno-chromium** [comment]
ossfuzz/base-runner and ossfuzz/base-runner-debug are done. and base-clang already existed.

@mikea - can you do s/base/base-image and s/base-libfuzzer/base-builder and then close this :) ?

**Comment by inferno-chromium** [comment]
This seems done, closing.

**Comment by mikea** [comment]
There's still some cleanup to be done.
