### ISSUE TITLE
MSAN says Sanitizer CHECK failure in "((0)) != (0)" (0x0, 0x0), but is likely just an OOM

### ISSUE THREAD

**Issue by kjlubick** [google/oss-fuzz#1420]
See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8311

It is confusing and hard to tell if it is actionable.

**Comment by kcc** [comment]
`==1==WARNING: MemorySanitizer failed to allocate 0x000242826208 bytes`
It's just an OOM, please treat it as such. 
We'll need to fix it in msan (not a high priority: @eugenis )

**Comment by eugenis** [comment]
Please give me access to the oss-fuzz bug.
Isn't this fixed by @alekseyshl 's allocator changes?

**Comment by kjlubick** [comment]
Access granted to eugenis@

**Comment by inferno-chromium** [comment]
@kcc @eugenis - what is the fix here ? don't we need to set allocator_may_return_null on our side for other san (other than asan) ?

**Comment by kcc** [comment]
I think this is @alekseyshl's pipeline. Right?
