### ISSUE TITLE
No valid coverage files given 

### ISSUE THREAD

**Issue by 4B5F5F4B** [google/oss-fuzz#1426]
Hello,

I build fuzzer ossfuzz for sqlite3 project like this:

helper.py build_image sqlite3
helper.py build_fuzzers --engine=libfuzzer --sanitize=coverage sqlite3
helper.py coverage sqlite3 ossfuzz

after ossfuzz ran about 60 seconds, I did't get coverage information but:

This may take a while (running your fuzzer for 60 seconds)...
Running: docker run --rm -i --privileged -e FUZZING_ENGINE=libfuzzer -e ASAN_OPTIONS=coverage_dir=/cov -e MSAN_OPTIONS=coverage_dir=/cov -e UBSAN_OPTIONS=coverage_dir=/cov -v /home/fuzzer/rd/oss-fuzz/build/out/sqlite3:/out -v /tmp/tmp0YQD2o:/cov -w /cov -t gcr.io/oss-fuzz-base/base-runner run_fuzzer ossfuzz -dump_coverage=1 -max_total_time=60
Running: docker run --rm -i --privileged -v /home/fuzzer/rd/oss-fuzz/build/out/sqlite3:/out -v /tmp/tmp0YQD2o:/cov -w /cov -p 8001:8001 -t gcr.io/oss-fuzz/sqlite3 coverage_report /out/ossfuzz
WARNING: No coverage file for *.sancov
WARNING: No coverage file for /out/ossfuzz
ERROR: No valid coverage files given.

**Comment by kcc** [comment]
ouch. I think I broke it in http://llvm.org/viewvc/llvm-project?view=revision&revision=332036 .. 
I really want to get rid of this functionality in libFuzzer. 

@Dor1s , are you planing to migrate `helper.py coverage` to clang coverage any time soon?

**Comment by Dor1s** [comment]
Yes!

**Comment by kcc** [comment]
Timeline? 
If soon, I won't even try resurrecting the old libFuzzer's dump_coverage.

**Comment by Dor1s** [comment]
I think in one week or two.

**Comment by Dor1s** [comment]
@oliverchang Since dump_coverage appears to be broken and yet to be removed, should I just replace `coverage` configuration with clang stuff, rather then adding another configuration I've planned earlier for safe migration?

**Comment by oliverchang** [comment]
Does any form of sancov dumping still work with libFuzzer (e.g. with ASAN_OPTIONS=coverage=1)?

**Comment by oliverchang** [comment]
Looking at our coverage stats, it looks like they stopped working on May 11, after http://llvm.org/viewvc/llvm-project?view=revision&revision=332036 landed in May 10. 

I don't think it's worth it if it's non-trivial. We should probably just replace this with clang coverage since it will take about 1-2 weeks (our coverage stats will be broken for the time being).

**Comment by kcc** [comment]
r332876 reinstates -dump_coverage. 
Sorry for the breakage.
