### ISSUE TITLE
Add libaom project / establish fuzzing for AV1

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1427]
//cc @jzern

This should be pretty straightforward, just follow https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md and / or look at some projects that are already integrated: https://github.com/google/oss-fuzz/tree/master/projects

**Comment by pdknsk** [comment]
Unless someone is already working on this or has committed to, I'd like to do this. I've been fuzzing `libaom` locally briefly (few months ago), but stopped, as it yielded too many reports. I assumed that since the bitstream (and code) are not yet stable that was to be expected, so I haven't reported any bugs.

(I have two other projects in the queue, so it could take a week or so.)

**Comment by jzern** [comment]
Thanks for the offer. No one has started work yet, but there is an existing libfuzzer based implementation that we've been using elsewhere. My thought was to let that stabilize before enabling reporting here.

I had some people in mind to handle this one as I think it's beneficial to expose more people to the process. I know you're familiar with the setup and have looked at adding [libwebp](http://crbug.com/webp/376) -- thanks again for doing that! Let me check availability and I'll let you know if this one is still open.

**Comment by jzern** [comment]
@urvangjoshi is going to have a look at this one.

**Comment by urvangjoshi** [comment]
Hi @Dor1s @jzern @pdknsk 
Here's a pull request for libaom: https://github.com/google/oss-fuzz/pull/1502

I tested the patch locally as per instructions in: https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md

Could you please review the same?
Let me know if you need anything else.

**Comment by urvangjoshi** [comment]
Fuzzing seems to be working as expected with some reports already generated: https://oss-fuzz.com/v2/testcases?project=libaom&open=yes

Given that, here's a follow-up PR for threaded decoder: https://github.com/google/oss-fuzz/pull/1509

**Comment by urvangjoshi** [comment]
I believe this issue can be closed now.

**Comment by urvangjoshi** [comment]
Possibly the last PR for the project setup:
https://github.com/google/oss-fuzz/pull/1512

**Comment by Dor1s** [comment]
Thanks everyone!
