### ISSUE TITLE
Broken builds due to disabled networking

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#1445]
Hi, I see several projects not building due to disabled networking/dns.

Is it just temporary or should the build.sh scripts be amended ?

**Comment by Dor1s** [comment]
Thanks, @rockdaboot! That looks like a temporary issue that should get resolved by itself. I've just re-started the builds to give them a chance to recover.

**Comment by rockdaboot** [comment]
:+1:

**Comment by alex** [comment]
Is this still affecting some builds? I'm seeing this on GraphicsMagick, ImageMagick, and gnutls.
