### ISSUE TITLE
Range for this bug was fixed is reversed for poppler

### ISSUE THREAD

**Issue by tsdgeos** [google/oss-fuzz#1450]
https://oss-fuzz.com/revisions?job=libfuzzer_ubsan_poppler&range=201805240508:201805250506 says
 76820f5ab932a9ed18913bc7d1a452ddf060c133:f966b9096d046aaee4891de11f74207218cc929b 
which is correct 768 is the old revision and f96 is the new one, but then it links to 
https://cgit.freedesktop.org/poppler/poppler/diff/?id=76820f5ab932a9ed18913bc7d1a452ddf060c133&id2=f966b9096d046aaee4891de11f74207218cc929b that does the diff in reverse order, the id and id2 should be switched

**Comment by inferno-chromium** [comment]
Thanks for spotting this. This is fixed now.
