### ISSUE TITLE
Unable to retrieve corpus backup

### ISSUE THREAD

**Issue by cherusker** [google/oss-fuzz#1458]
I currently work on fuzzing support for FreeType and I am unable to download any of the corpus backups of any of the fuzzers:

![download](https://user-images.githubusercontent.com/5071440/40741707-6e3e9262-644c-11e8-97a9-981e83b1b4e3.png)

The linked bucket seems to be empty:

![empty](https://user-images.githubusercontent.com/5071440/40741767-92127488-644c-11e8-8ec7-8b6ffbe26cbb.png)

@kcc observed the same issue (at least with FreeType).

**Comment by oliverchang** [comment]
Looks like google cloud console changed their UI and now it's no longer possible to link to a particular file.

In the meantime, you can still access the backups if you go one directory up (i.e. by clicking the freetype2_ftfuzzer link below the in the "Buckets / freetype2-backup.clusterfuzz-external.appspot.com /" ... part)

**Comment by cherusker** [comment]
I see you've already changed the link - can't test what you said but I'm able to download the buckets from the directory view, thanks 😄
