### ISSUE TITLE
Upper bounds of edge coverage and function coverage

### ISSUE THREAD

**Issue by cherusker** [google/oss-fuzz#1459]
I currently work on fuzzing support for FreeType and I stumbled across the the statistics page of the different fuzzers. After running `libFuzzer` and `llvm-cov` locally, I am slightly confused as I am unable to reproduce the upper bounds `edge_cov` and `func_cov`. To the best of my knowledge, this statistic misses ~10% of the functions and somewhat more edges. Do you run some optimisations before calculating these numbers / is there a way to reproduce the upper bounds that OSS-Fuzz calculates locally?

Thanks in advance :)

**Comment by oliverchang** [comment]
We use a different instrumentation (SanitizerCoverage instead of clang coverage) currently to display this information. We'll change this to use clang coverage in a few weeks. @Dor1s

**Comment by Dor1s** [comment]
Yep, stay tuned, #799

**Comment by cherusker** [comment]
Thanks 😄
