### ISSUE TITLE
Can you share reproducer for Issue 6711?

### ISSUE THREAD

**Issue by DeafBDoor** [google/oss-fuzz#1515]
Hi, I work as a security analyst for Red Hat and would like to have access to reproducer for the aforementioned issue, in order to test Red Hat builds of wireshark.

Link for issue is: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6711

Thanks in advance and regards,
- Richard Maciel Costa (rcosta@redhat.com)

**Comment by jonathanmetzman** [comment]
I've CCed you on the issue, you should be able to access it with a google account using that email address. Please let me know (and close the issue) if it works

**Comment by oliverchang** [comment]
Note that it shouldn't be necessary to be CC'ed on a publicly viewable issue to download the reproducer.
