### ISSUE TITLE
Support code coverage report generation without a corpus using run_fuzzer->then running coverage command, also update docs

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1517]
The old code coverage script used to run fuzz targets without any corpus for 60 seconds and then generate code coverage report. With clang source-based code coverage it is not possible, as we don't use sancov in new coverage builds. Without sancov, libFuzzer can't work and just errors out:

```
...
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2	INITED lim: 4 exec/s: 0 rss: 25Mb
ERROR: no interesting inputs were found. Is the code instrumented for coverage? Exiting.
```

I'm personally not a big fan of this usecase, but it seems that there might be a demand for it, so we may have to find some convenient workaround.

One of the options we have is to generate some corpus by running fuzz target locally, and then use that corpus to the new script among with `--no-corpus-download` option, so that the fuzzers will be run against corpus provided by user.

**Comment by Dor1s** [comment]
I've removed `--dry-run` functionality from the new script for now: https://github.com/google/oss-fuzz/pull/1494/commits/f04f4c6b3d9e617de16fd7b56aba0b66d6de1282

**Comment by alex** [comment]
I would personally like this; it'd be a good way to get an initial sense of a new fuzzer.

Perhaps we could mount both an ASAN and a profiling build into the same container, and use both of them?

**Comment by Dor1s** [comment]
Not really... We need to use SanitizerCoverage (not ASan), and it doesn't always seem to work when used together with clang coverage (i.e. `profile` build config): https://github.com/google/oss-fuzz/issues/891

We might want to bring https://github.com/llvm-mirror/compiler-rt/commit/af6859eaab3f96b8d926da0f62169f49060192ae#diff-9754f4d5700fb6011cf3606c0fdd9f18 back in order to support this case, but the coverage still be pretty dumb as `profile` build is very slow.

**Comment by alex** [comment]
Sorry, I wasn't suggesting doing a profiling+ASAN build, I was suggesting mounting two sets of binaries into the container. One that's the `--sanitizer=profile` build, and one that's `--sanitizer=address` (as a random example of a build with sancov).

**Comment by Dor1s** [comment]
Ah, sorry for misunderstanding. Yeah, that could be an option, but it might be an unnecessary complication to maintain two builds.

Another idea I had was:
- build asan
- run for a minute or so
- save corpus
- build profile
- run against the corpus from previous run

but that also doesn't sound very convenient, even if it's all implemented inside the helper script.

**Comment by inferno-chromium** [comment]
How about we ask users to run these command in sequence

build_fuzzers --sanitizer=asan
run_fuzzer and tell them to run for >X secs
build_fuzzers --coverage or whatever
run_coverage --xyz option that picks up corpus from last run_fuzzer ? since in same docker image

**Comment by alex** [comment]
So one frustration that happens is that the  `/out` mount is shared between different sanitizers. Should we make the directory on the host be `build/out/$project/$sanitizer/`?

Right now if you attempt to do things in parallel you often end up with frustration and confusion. (e.g. I'd totally try to do both of those `build_fuzzers` concurrently to save time)

**Comment by inferno-chromium** [comment]
I have hit this too, this is actually frustating. @alex - you want to upload a patch :)

**Comment by inferno-chromium** [comment]
@oliverchang to confirm there is no issue with changing /out to /out/project/sanitizer ?

actually i dont think projects can share docker image.
so i think it should be /out/fuzzing_engine/sanitizer ?

**Comment by alex** [comment]
Sure. Patch incoming.

**Comment by inferno-chromium** [comment]
Please use https://github.com/google/oss-fuzz/pull/3217 as a starting point

**Comment by inferno-chromium** [comment]
This is an extremely common usecase that several OSS integrators ran into, when integrating a new project. high priority.

**Comment by inferno-chromium** [comment]
Fixed in https://github.com/google/oss-fuzz/pull/4191
