### ISSUE TITLE
Coverage changes on seed-corpus should be NOTIFIED somehow

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1531]
@kjlubick suggested this in a meeting.

e.g. reasons when format changes and dev needs to work on regenerating seed corpus.

**Comment by Dor1s** [comment]
I think this should be handled on a project's CI side, as a part of regression testing required by the ideal integration. That's kind of what CI is used for -- to catch regressions. Also,  that would be much faster compared to OSS-Fuzz pulling the changes in and reporting such a regression only the next day in the worst case.

**Comment by inferno-chromium** [comment]
Well, only a small set of projects get ideal integration and then asking them to monitor coverage is another big deal.

On our side, we have stats on coverage for seed corpus (if not very easy to add since libfuzzer gives that number at least), it might be simple to generate notification from it.
