### ISSUE TITLE
Seed corpus improvements

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1532]
@jonathanmetzman has this idea.

maybe rather than unarchiving seed corpus everytime, we just put it in the bucket everytime in corpus pruning task before minimization (that is done once a day). So, instead of big seed corpus, bots downloads minimized corpora everytime.

**Comment by inferno-chromium** [comment]
Only problem is sometimes other testcase might get prioritized over seed corpus item when doing minimization (if they have same coverage).

**Comment by alex** [comment]
Why would that be a problem?

**Comment by inferno-chromium** [comment]
Maybe seed corpus item has better valid / interesting values ? I always think seed corpus item is more important than randomly generated data based on mutation. maybe that is not true for most cases.

**Comment by alex** [comment]
If they provide equivalent coverage, I think it makes sense to prioritize which to include based on the fuzzer's usual rules.

Consider: If you start libFuzzer with a corpus of "initial (good)" data, and then it discovers some random mutation which provides equivalent coverage while being smaller, libFuzzer will replace the seed element. This suggests that simply choosing the smallest input which provides a given coverage is an effective heuristic.

**Comment by jonathanmetzman** [comment]
Done. 
Now we only unpack seed corpus when the main corpus is basically empty and during corpus pruning.
