### ISSUE TITLE
Past crash regressions need to be retried

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1533]
Right now, we retry traditional fuzzer testcase as regressions. But don't do this for afl, libfuzzer. we need to retry all old testcases on new builds.

@kjlubick pointed this out.

**Comment by Dor1s** [comment]
I think we've been discussing this in the past and came to a conclusion that older crash inputs (or their variants) should be already in the corpus, once the bugs get fixed.

However, if the goal is to re-open old bugs in case of regressions, then it probably makes sense to complicate things and collect all previous crashers + run against those.

**Comment by inferno-chromium** [comment]
So, it gets into corpus if developer explicitly added it. Which is usually not the case ?

Otherwise, when there is a crash, that input does not go into corpus right ? Maybe when bug is fixed, we put that item in corpus atleast for it to try.

**Comment by Dor1s** [comment]
Yes, we quarantine crashy inputs, but we have the corresponding baseunits in the corpus, which are one-mutation-off the crashy ones and likely to be re-generated again and again. The fact that we usually see every crash happening multiple times across different bots is an evidence of that.

**Comment by inferno-chromium** [comment]
Quarantine input are old corpus units that now started crashing and hence are moved to quarantine. These are not the latest crashing input.

Your point about one-mutation-off is sort of valid. this crashy input came from mutation of something that is already in corpus (or atleast in 45 min of fuzzing that corpus unit). So, unsure on value.
@jonathanmetzman @oliverchang @mbarbella - thoughts here ? any value that crash regressions can give based on above discussion.

**Comment by jonathanmetzman** [comment]
I filed an issue about this, I just didn't get around to doing it. I'd be
happy to take ownership.
https://bugs.chromium.org/p/chromium/issues/detail?id=844644

Earlier I didn't feel great that regressions can prevent new bugs from
being found, now I think it doesn't matter.
I think crashing on a regression is a pretty big deal, one that outweighs
finding new bugs. Especially if the testcase was made public.
I don't know where old timeouts and ooms fit into this though.

**Comment by inferno-chromium** [comment]
I think we will only put this in corpus when the testcase is fixed (and only for ones that have bug attached to it).

**Comment by alex** [comment]
There are definitely projects participating in OSS-Fuzz (and getting a lot of value out of it) which do not have significant test suites or continuous integration 🤷‍♂️

**Comment by inferno-chromium** [comment]
This is done in https://github.com/google/clusterfuzz/pull/1869
