### ISSUE TITLE
No corpus update

### ISSUE THREAD

**Issue by kroeckx** [google/oss-fuzz#1537]
It seems that for some reason the last corpus update for openssl was on 2018-06-11, as in over a week ago.

**Comment by kroeckx** [comment]
That is the files I get at gs://openssl-corpus.clusterfuzz-external.appspot.com/

**Comment by inferno-chromium** [comment]
Fixed now, i am suspecting this was a blobstore issue which we resolved. Now i see all fuzzer stats and their corpuses updated.
https://oss-fuzz.com/v2/fuzzer-stats/by-fuzzer/date-start/2018-06-16/date-end/2018-06-22/fuzzer/libFuzzer/job/libfuzzer_asan_openssl
