### ISSUE TITLE
EditIssueCc for ease of project triage

### ISSUE THREAD

**Issue by jzern** [google/oss-fuzz#1539]
I was wondering if I could get edit cc access for myself (jzern@), huisu@ and urvang@ to better triage bugs in libaom and libwebp on the monorail project. In dealing with ffmpeg it seemed michaelni@ had this ability.

**Comment by inferno-chromium** [comment]
Done!

**Comment by jaikrishnan** [comment]
One more request for edit cc access: for me on libaom and libwebp

**Comment by inferno-chromium** [comment]
@jzern - do you approve this ? Also i don't have the uid for jaikrishnan@

**Comment by jzern** [comment]
This is OK, jaikk@. Thanks for updating things.
