### ISSUE TITLE
Potential false-positive 'container-overflow' with -fsanitize=address

### ISSUE THREAD

**Issue by rouault** [google/oss-fuzz#1550]
I've investigated https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8963 and I strongly suspect a false positive  -fsanitize=address  'container-overflow' warning.

So this PCIDSK::ProjParmsFromText() function declares a std::vector<double> dparms; , push_back 17 times a value in it in the for() loop and does a dparms.resize(18) that triggers 'container-overflow'
By doing the following growing before the resize(18), the warning disappears.
```
while( dparms.size() < 18 )
{
        dparms.push_back(0.0);
}
```

I tried a simpler similar reproducer within a oss-fuzz docker
```
#include <cstdlib>
#include <vector>

int main(int argc, char* argv[])
{
    std::vector<double> ar;
    for( int i = 0; i < atoi(argv[1]); i++ )
        ar.push_back(0);
    ar.resize(18);
    return 0;
}
```

but
```
clang++ -fsanitize=address -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -stdlib=libc++ test.cpp -lstdc++ -o test && ./test 17
```
doesn't trigger the warning, so this is something more subtle

**Comment by inferno-chromium** [comment]
This should get closed today, we have reverted the change causing this, now new builds should get generated soon.

**Comment by inferno-chromium** [comment]
Should be fixed now, and no longer happen.
