### ISSUE TITLE
Build failures with detect_container_overflow in fuzzer::InputCorpus::UpdateCorpusDistribution()

### ISSUE THREAD

**Issue by LebedevRI** [google/oss-fuzz#1556]
It does not seem like #1542 handled all the failures.

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8989
Filed upstream just in case https://bugs.llvm.org/show_bug.cgi?id=37910 (as asked by @mclow)
But i can not reproduce.

Might be related to https://github.com/google/oss-fuzz/issues/1550

**Comment by inferno-chromium** [comment]
@morehouse - something broke in libFuzzer, can you please check.

**Comment by morehouse** [comment]
My guess at the culprit:  https://github.com/google/oss-fuzz/commit/63d9392e59bad3d19217997614c5fefd125b897c

There are known ASan container overflow false positives when mixing ASan-ified and non-ASan-ified libraries.  See https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow#false-positives.

**Comment by kcc** [comment]
very likely. Note that upstream LLVM has switched to building libFuzzer with it's own private copy of libc++ 
exactly to avoid these problems. 
However, there was one more protection (not using vanilla std::vector), and there is one place where I failed to do this: 
```
FuzzerTracePC.cpp:    std::vector<uintptr_t> UncoveredPCs;
```

If we replace `std::vector` with `Vector` in this one place the problem may be gone for a while. 
@morehouse please do the change. 

Longer term, oss-fuzz needs to switch to LLVM uilds of libFuzzer, but we first need to make sure it works with msan. @morehouse, this is yours as well. :)

**Comment by inferno-chromium** [comment]
Thanks @kcc for triaging this.

**Comment by morehouse** [comment]
The last `std::vector` has been replaced with `Vector` in https://reviews.llvm.org/rL335487.

**Comment by inferno-chromium** [comment]
@morehouse - we can't uptake r335487 since blocked on this install-cxx failure in https://github.com/google/oss-fuzz/issues/1560#issuecomment-399765227, any idea how to fix that ? If you have a workaround, then we can uptake both with rolling forward.

**Comment by inferno-chromium** [comment]
Rolled in https://github.com/google/oss-fuzz/commit/ffe166e75ceb716fe34e11471501946b953ec754#diff-2ac6f4fc7d326765c42e2f3f30d5f2d5, we can close this after clusterfuzz verifies the fix and closes the monorail issue.

**Comment by inferno-chromium** [comment]
@morehouse @kcc - this container overflow issue is still happening. Please see https://oss-fuzz-build-logs.storage.googleapis.com/log-c1c10688-2c41-4b42-ae65-819f7122d955.txt.

**Comment by LebedevRI** [comment]
Not too surprising, given that the `std::piecewise_constant_distribution<double>` internally consists of:
https://github.com/llvm-mirror/libcxx/blob/661dff0e60093266e7833cbbf5d3809a4f950378/include/random#L6089-L6091:
```
vector<result_type> __b_;
vector<result_type> __densities_;
vector<result_type> __areas_;
```
They don't respect (do not take it as a template parameter) the custom allocator which is what the `fuzzer::Vector` is really.
I somewhat suspect that it can only be fixed by e.g. not building libfuzzer with asan, or reverting whatever oss-fuzz commit that exposed this issue (63d9392e59bad3d19217997614c5fefd125b897c?)

**Comment by LebedevRI** [comment]
@inferno-chromium thanks!

**Comment by inferno-chromium** [comment]
I will trigger a rebuild of base-images now, which will be followed by rebuild of librawspeed. Really sorry for the inconvenience caused to you because of this.

**Comment by mclow** [comment]
Let me know if/when I can close https://bugs.llvm.org/show_bug.cgi?id=37910 as well.

**Comment by inferno-chromium** [comment]
I think you can that llvm bug since @kcc said that upstream uses it with its own version of libc++

**Comment by inferno-chromium** [comment]
librawspeed is green now.
