### ISSUE TITLE
Redo task doesn't use the latest git master?

### ISSUE THREAD

**Issue by tsdgeos** [google/oss-fuzz#1559]
Maybe it's just my wrong understanding, but i thought pressing "Redo task" would try the same issue with the current git master.

But if you go at 
https://oss-fuzz.com/v2/testcase-detail/5192706421686272
you can see i pressed "Redo task" at 2018-06-24 09:20:59 UTC but it still tested poppler 877dcec7e2357991d79508a2aefc39d1510bf235 when there's five or six commits after that one https://cgit.freedesktop.org/poppler/poppler/log/

Is this because i'm understanding the "Redo task" button wrong or is there actually something wrong somewhere?

**Comment by inferno-chromium** [comment]
Builds are done once a day (around 9-10 PM PST timezone). We don't have new builds for last 2 days, should get fixed soon, see https://github.com/google/oss-fuzz/issues/1560

**Comment by tsdgeos** [comment]
I see, then i guess misunderstanding on my side on what that button does, will mark this as closed.
