### ISSUE TITLE
EditIssueOwner for ease of project triage

### ISSUE THREAD

**Issue by jzern** [google/oss-fuzz#1565]
I probably should have thought about that in making the edit cc request. I don't know if EditIssue is possible if you want to keep the status update and summary automatic, but that might make things simpler.

jzern@, huisu@, urvang@, jaikk@

Original cc request:
https://github.com/google/oss-fuzz/issues/1539

/cc @urvangjoshi

**Comment by inferno-chromium** [comment]
Done!
