### ISSUE TITLE
Access denied to clusterfuzz page

### ISSUE THREAD

**Issue by randombit** [google/oss-fuzz#157]
Vising https://clusterfuzz-external.appspot.com/v2 as linked from clusterfuzz.md I get

```
You (email=jack.lloyd@gmail.com) are not authorized to access this page!

For access, please contact .
```

I double checked my original PR and I didn't typo my google account, jack.lloyd@gmail.com

Could this be because the botan build only just recently succeeded for the first time? Perhaps the results coming in from clusterfuzz are required to initiate something that allows access to the web interface...

**Comment by inferno-chromium** [comment]
https://github.com/google/oss-fuzz/blob/master/projects/botan/project.yaml does not have jack.lloyd@gmail.com, do you want to use that instead of jack@randombit.net.

**Comment by randombit** [comment]
I think I am confused about how this works. My google account is linked with jack@randombit.net email, which based on what readme says about email addresses under the Accepting New Projects section, seemed like it was ok.

But if it is easier, just using jack.lloyd@gmail.com for all clusterfuzz related contacts is fine.

**Comment by inferno-chromium** [comment]
Ok changed to use jack.lloyd@gmail.com so that you can access. I will discuss with team on what is going on with auth.

**Comment by inferno-chromium** [comment]
Can you try this in a incognito window with signing using jack@randombit.net as email to signin and same gmail password for jack.lloyd@gmail.com.

**Comment by randombit** [comment]
Tried logging in using other email from incognito, worked fine.

However, one other (related?) issue remains - I cannot see any fuzzer stats for the botan fuzzers. I either get error "No stats" or "Access denied" depending on options (eg selecting Group by day gets Access Denied error). I can however see the testcase associated with oss-fuzz bug 266.

**Comment by oliverchang** [comment]
Stats aren't available yet because they can be delayed by up to a day. Since you recently fixed the startup crash, stats only just started getting uploaded into our pipeline. 

"No stats" means you do have access to the stats, but none are available. As for the access denied messages, what were the exact options you selected?

**Comment by randombit** [comment]
Re no stats, makes sense thanks.

Re the access denied, these options:

```
Fuzzer Stats >

Fuzzer name: libFuzzer_botan_ber_decode
Job Type: All
Group By: Day
Start: 12/02/16
End: 12/08/16```

Causes error

```
Got error with status:

Access denied. (email=jack.lloyd@gmail.com)
```

**Comment by oliverchang** [comment]
Ah, "Job Type: All" won't work. Thanks for pointing this out, we'll need to improve the UI here.

**Comment by randombit** [comment]
Stats and everything else are working fine for me now, so closing this. Thanks!

**Comment by randombit** [comment]
Oh dear. Now, if I attempt to access a testcase (either of the two for botan created so far, both of which I had looked at previously), such as https://clusterfuzz-external.appspot.com/v2/testcase-detail/6081501837918208 I get

```
You (email=jack.lloyd@gmail.com) are not authorized to access this page!

For access, please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.
```

Both of the cases are still visible in the testcases search.

**Comment by inferno-chromium** [comment]
Should be fixed now, can you retry. And we are working on fixing our error messages so that the error message is clear.
