### ISSUE TITLE
[infra] Compile fuzzing engine without SANITIZER_FLAGS unless MSan is used.

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1575]
Just to track that https://github.com/google/oss-fuzz/pull/1522 was reverted and we can't do this yet because of https://github.com/google/oss-fuzz/issues/1556. We can compromise of speed/coverage, but can't compromise on false positives.

**Comment by jonathanmetzman** [comment]
I think this is taken care of by #2312
