### ISSUE TITLE
Decide how to handle cross pollinations intelligently.

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#1581]
When discussing cross pollination (ie: sharing corpora between fuzz targets) today we came up with two models for how this should work.

1. Fuzzers opt-in to pollination from other fuzzers with the same format.
Example: I specify in my project.yaml that png_fuzzer accepts PNG files. Then png_fuzzer will be pollinated with other fuzzers. 

2. There is no opt-in (automatic). Fuzzers are randomly pollinated with others and ClusterFuzz learns to favor corpora that produce effective pollination. 

We can also do some mix of the two.

OSS-Fuzz users: please give us your thoughts on this. Would you use an opt-in system?

I'll add some of the things we said about each option below.

**Comment by alex** [comment]
I'd try to participate in an opt-in system, but for example, ImageMagick and GraphicsMagick have _so many_ targets, which partially overlap with so many other projects, that it'd be a bit of a challenge; some sort of automated handling would be helpful.

**Comment by randombit** [comment]
I would certainly use a opt-in system for relevant fuzzers, for instance there are probably now half a dozen or more fuzzers for X.509 certificates within OSS-Fuzz currently, so great potential for cross-pollination there.

But random pollination would IMO be useful also.

**Comment by jonathanmetzman** [comment]
The main things we said were:
* Opt-in is simpler to implement.
* Opt-in is less wasteful:
  Our guess is that pollination will be useless for most targets. And for targets that pollination will benefit, it only makes sense to pollinate them with a fraction of formats. In the automatic system, we will have to waste a lot of time learning which formats are useless
* Automatic is more resistant to human error. Opt-in was previously decided against in #394 for this reason.
@kcc wasn't involved in our most recent discussion, so I'm not sure exactly how poorly this works in practice. But I see it as similar to dictionaries, it's extra work that most people won't do, but is still useful overall.

I think the point @alex makes about scalability is a good one. An opt-in system presumes it is practical for users to opt-in, but this is not always the case.

**Comment by jonathanmetzman** [comment]
Some of my own thoughts I didn't really discuss in the meeting:

* I think a hybrid system isn't a great idea. If the automation works well, won't it be a waste of time to opt-in? If the automation doesn't work well why should we do it/maintain it? Reality probably won't be this black and white, but I think this point is worth considering.

* I wonder how pollination is affected by use of the `data` buffer for multiple inputs. For example, one can imagine a PNG parser target that uses the first 3 bytes of input to do configuration and then actually parses the 4-N bytes as a PNG. 
This seems quite bad in an opt-in system. It also seems not great in automated system. 
Maybe instead of merging a corpus into another, we can fuzz using another corpus so the fuzzer can add/remove config bytes as needed.

**Comment by jonathanmetzman** [comment]
Abhishek also raised the point that some testcases can be bad to share (eg: timeouts or OOMS). 
It seems possible that one target can produce testcases that another considers valid but handles poorly (AFL has a similar problem with libFuzzer since it doesn't accept inputs over 1 MB).
Is this a problem worth worrying about?

**Comment by alex** [comment]
It's worth noting that if you fuzz a PNG parser where the first 3 bytes are configuration, with a corpus designed for a "normal" PNG parser's corpus, you probably won't get any value.

libFuzzer will discard almost all the inputs in the initialization stage, where it greedily searches for the smallest set of inputs to maximize coverage. Because most of the inputs will have the same limited coverage (e.g. they won't have the magic PNG header in the right places, so they'll almost all be rejected immediately), they won't be part of the running corpus, even if they might be a useful launching point for mutations.

AFL has a different strategy I believe, I don't have as strong an understanding of it.

**Comment by jonathanmetzman** [comment]
>It's worth noting that if you fuzz a PNG parser where the first 3 bytes are configuration, with a corpus designed for a "normal" PNG parser's corpus, you probably won't get any value.

Ah right. It would have to be some kind of fuzzing that was initially blind to coverage.

**Comment by alex** [comment]
In terms of opt-in cross-pollination, what do you imagine the configuration for that would look like?

**Comment by jonathanmetzman** [comment]
I haven't put much thought into it, but I think we could have a section like this in the `project.yaml`:
```
formats:
   foobar_png_fuzzer: png
   foobar_gif_fuzzer: gif
```

**Comment by kcc** [comment]
I would prefer to avoid complicated config options -- they are easy to get wrong. 
Anything more than a single boolean parameter is likely to be misused and/or underused.

**Comment by pauldreik** [comment]
There can be cross pollination between
 - projects
 - fuzzer targets within the same project
 - fuzzing engines

Which one(s) are we talking about here?

I assume cross pollination is the most beneficial for difficult targets (slow to execute, difficult to randomly find interesting input)

As an oss-fuzz "end user" I do not care of how oss-fuzz comes up with clever input. If it comes from randomization or some other project/fuzzer target/build should not be something I have to care about.
I do however appreciate that oss-fuzz is very good finding interesting input, and if this improves that capability, what's not to like?

One potential very minor security problem could be that projectA gets input from projectB and crashes. The authors of projectA then indirectly gets access to a fuzzer input from projectB. If that fuzzer input also crashes projectB, projectA has access to information that is not public.

If one is concerned about wasting resources on this - does one have to run it all the time? Perhaps start with libfuzzer only and run it once a day?

I am all for this being automatic and default to on.

**Comment by inferno-chromium** [comment]
All of this is automatically done already, see
https://github.com/google/clusterfuzz/blob/master/src/python/bot/tasks/corpus_pruning_task.py#L812
https://github.com/google/clusterfuzz/blob/master/src/python/bot/tasks/corpus_pruning_task.py#L842
https://github.com/google/clusterfuzz/blob/master/src/python/bot/tasks/corpus_pruning_task.py#L275
once a day with 3 random targets. We want to get more intelligent here, but over time this just works.

**Comment by inferno-chromium** [comment]
This bug just tracks the better cross-pollination selections.

**Comment by jvoisin** [comment]
Why wontfix? Having a simple label system would likely help tremendously to ramp up new fuzzers operating on *popular* formats like png, json, …

**Comment by jonathanmetzman** [comment]
Too many TODOs not enough resources. I think this should be done by an LLM now (ie LLM decides libpng_parse and imagemagick_png have same corpus).
