### ISSUE TITLE
The overall story for OSS project owners is not clear

### ISSUE THREAD

**Issue by dvyukov** [google/oss-fuzz#16]
I've read the main page and "New Library Guide", but I am still puzzled as to what is the overall workflow and why/when do I want to use it (as an owner of an OSS project).

I've got that I need to do lots of steps and then _somebody_ will run something on some ClusterFuzz.
Who will receive bug reports? Is it me? Or only that somebody? If it's me, then how will I receive them? Is there some kind of dashboard? Can I integrate it with my bug tracker (e.g. github issues or Mantis)? Can I subscribe the project mailing list? Should I subscribe the mailing list straight away? Or start with just me? What is ClusterFuzz? How do bug reports look like? Is it like "your project has a bug" (which would not be too useful)?

All these questions need to be answered on the main page.
I am not sure ClusterFuzz should be mentioned here at all. It is irrelevant for users. And can change in future.
On the other hand, the very first sentence of main page talks about "coverage-guided" and "in-process". That's not the most important piece of information for end users. They probably don't even know what it is. And that can change in future as well (i.e. implementation detail).

**Comment by mikea** [comment]
The root README page was significantly expanded. It should now answer all those questions, please take a look.
