### ISSUE TITLE
Progression tasks not running?

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#1608]
In the last few days I've seen several bugs that I'd expected to be marked fixed, not having been marked as such.

When I look at them in OSS-Fuzz, it seems the nightly progression task hasn't run.

**Comment by oliverchang** [comment]
Could you please point to an example?

**Comment by alex** [comment]
https://oss-fuzz.com/v2/testcase-detail/6326168570560512?noredirect=1 is an example.

The most recently tested version is a day behind what was built on https://oss-fuzz-build-logs.storage.googleapis.com/index.html

**Comment by inferno-chromium** [comment]
@oliverchang fixes this. Thanks for noticing.

**Comment by alex** [comment]
@oliverchang Are you sure this is fixed, https://oss-fuzz.com/v2/testcase-detail/5646197065777152?noredirect=1 is another example where the "last run on" doesn't line up with the last build.

**Comment by inferno-chromium** [comment]
[2018-07-13 07:07:36 UTC] oss-fuzz-linux-zone3-host-jwcd-7: Progression task started: r201807120510.
[2018-07-13 07:08:31 UTC] oss-fuzz-linux-zone3-host-jwcd-7: Progression task finished.

**Comment by inferno-chromium** [comment]
@alex - can you check timestamp on the last build, is it > 00:00 PST

**Comment by alex** [comment]
Last build where? https://oss-fuzz-build-logs.storage.googleapis.com/index.html shows  7/13/2018, 5:37:23 AM (EDT)

**Comment by inferno-chromium** [comment]
imagemagick
Last built 7/13/2018, 2:37:23 AM (Pacific Daylight Time)

yes that seems the issue, we ran progression task at 00:00, but builds came around 2 AM. so, it will be tested today.

@oliverchang - do you think we have enough projects/builds now that we need to move back from our 9 pm trigger to something like 6/7 pm and increase number of builders  ? from a dev perspective, waiting 2 days seems not justified. or we can even do something like run progression task 2 times a day.

**Comment by inferno-chromium** [comment]
Change base-images trigger from 9 pm to 6 pm. so now progression task trigger at 12 am should get new build even for slow jobs like imagemagick. Please reopen later if see you this still happening.

**Comment by oliverchang** [comment]
oops, missed this in my inbox. thanks for changing the trigger time!
