### ISSUE TITLE
Revision number in crash stacktrace is not copyable

### ISSUE THREAD

**Issue by wantehchang** [google/oss-fuzz#1616]
In the detailed reports, the git revision number in the crash stacktrace is not copyable. Here is an example:

https://oss-fuzz.com/testcase?key=5646284508626944

In the CRASH STACKTRACE section, the lines "LAST TESTED STACKTRACE ON REVISION 6EECFE92..." and "ORIGINAL STACKTRACE ON REVISION 89F54505..." are not copyable.

It seems that not all detailed reports have this problem. For example, in this detailed report:

https://oss-fuzz.com/testcase?key=5472823026909184

I can copy the line "ORIGINAL STACKTRACE ON REVISION 48073D93C20DD2D319C0D45291D43E0DFB76C9A5".

Perhaps it depends on whether there is an "xx lines omitted" line.

**Comment by inferno-chromium** [comment]
Now fixed!

**Comment by wantehchang** [comment]
Thank you, Abhishek!
