### ISSUE TITLE
Enable required reviews for pull requests

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1618]
... by following https://help.github.com/articles/enabling-required-reviews-for-pull-requests/

I think that would be a better workflow as we probably should not push code directly to master. If there is a local change that doesn't really need a review, we can always self-approve and land it as we do TBR in Chromium and other places.

Another benefit I see besides of reducing the rate of errors / bugs introduced is that we will have a better visibility as we have email notifications enabled for new issues / PRs, but not for commits pushed directly to master.

WDYT?

**Comment by inferno-chromium** [comment]
+1

**Comment by oliverchang** [comment]
+1

**Comment by Dor1s** [comment]
Yeah, seems to be working!

```bash
$ git commit -a -m '[docs] Link code_coverage.md page from the ideal_integration.md.'
[master 4c0637b1] [docs] Link code_coverage.md page from the ideal_integration.md.
 1 file changed, 4 insertions(+)

$ git push origin master
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 56 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 502 bytes | 502.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:google/oss-fuzz.git
 ! [remote rejected]   master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:google/oss-fuzz.git'

$ git checkout -b test_review
Switched to a new branch 'test_review'

$ git push origin test_review
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 56 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 502 bytes | 502.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:google/oss-fuzz.git
 * [new branch]        test_review -> test_review
```

**Comment by Dor1s** [comment]
Tested by #1621

**Comment by Dor1s** [comment]
Disabled enforcing for administrator still allows us to push manually to master :(

```bash
$ git commit -a -m '[docs] Dummy formating change just to test #1618 a bit more.'
[master bb78fa98] [docs] Dummy formating change just to test #1618 a bit more.
 1 file changed, 3 insertions(+), 2 deletions(-)

$ git push origin master
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 56 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 414 bytes | 414.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:google/oss-fuzz.git
   c720e404..bb78fa98  master -> master

```

**Comment by pdknsk** [comment]
> Delta compression using up to 56 threads.

Googler workstation spotted.

**Comment by Dor1s** [comment]
This message on the community forum claims that the issue with self-approval has been fixed for cases when PR author is a code owner: https://github.community/t5/How-to-use-Git-and-GitHub/Do-not-require-owner-approval-if-the-pull-request-is-from-an/m-p/4933/highlight/true#M1589

I can give a try to using CODEOWNERS file, just a top level directory one at least.

**Comment by Dor1s** [comment]
Ok, now I'm testing out owners thing and enforce approval requirement for administrators as well.

**Comment by Dor1s** [comment]
Doesn't work either. I've sent a message to GitHub support as suggested in https://github.community/t5/How-to-use-Git-and-GitHub/Do-not-require-owner-approval-if-the-pull-request-is-from-an/m-p/7203/highlight/true#M2416

Now reverting the CODEOWNERS file as well as enforcement for administrators.

**Comment by Dor1s** [comment]
So, in the current state every pull requests requires at least 1 approval, but we still can push commits manually to master. Not sure if current state makes sense at all, we may disable it and WontFix the issue for now, until GitHub support provides more info or fixes the problem.
