### ISSUE TITLE
Make /out be a link to the actual build directory on CF.

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#162]
For various reasons, the directory containing the fuzzer build on CF can't be hardcoded. However, we can link /out to this directory so fuzz targets can hardcode paths to data files etc.

**Comment by oliverchang** [comment]
Should work now.

**Comment by oliverchang** [comment]
Reopening this, since this won't work as expected since in:

https://github.com/google/oss-fuzz/blob/master/infra/libfuzzer-pipeline.groovy#L101 

We do zip -j ... (and without -r).

**Comment by inferno-chromium** [comment]
This can be closed now.
