### ISSUE TITLE
Testcase stuck in status: pending?

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#1626]
https://oss-fuzz.com/v2/testcase-detail/5942223190360064

the metadata section doesn't seem to show any ongoing tasks, but it still says: status: pending

**Comment by jonathanmetzman** [comment]
The Metadata section shows regression task has started but no progress was made. Looking into this.

**Comment by oliverchang** [comment]
Did we figure out what went wrong? The testcase is no longer in pending, and the metadata section did in fact have an ongoing task right?

**Comment by jonathanmetzman** [comment]
>Did we figure out what went wrong?

I'm not sure we figured out the root cause, I think the task had RPC errors. In any case, we figured out a way to prevent this from happening (retrying regressions that haven't completed a day later), I just didn't get a chance to implement it yet. 

>The testcase is no longer in pending, and the metadata section did in fact have an ongoing task right?

Yes it did.

**Comment by jonathanmetzman** [comment]
I don't think it got restarted though, and I'm having trouble getting the logs now.

**Comment by oliverchang** [comment]
It can take a few hours for the task to get picked up again. In any case let's close this for now since there's nothing actionable at this point. We can re-open if we encounter this again.
