### ISSUE TITLE
Button `TOTAL COVERAGE` seems to be broken

### ISSUE THREAD

**Issue by cherusker** [google/oss-fuzz#1638]
When clicking on `TOTAL COVERAGE` on the overview page of FreeType's project, I reach a page that tells me `Failed to get coverage report.`. Is that still supposed to work or did the the recent updates (https://github.com/google/oss-fuzz/issues/799#issuecomment-397484736) replace that?

**Comment by cherusker** [comment]
In addition, viewing the coverage of files online (on a per-fuzzer-basis) does no seem to work either:

- Clicking on `coverage` on the fuzzers' overview page.
- Clicking on any arbitrary file.
- The page states `404: Not Found`.

**Comment by Dor1s** [comment]
We haven't finished #799 yet, so the old coverage stuff is not supposed to be broken. However, there were some recent changes that could affect it. Either way, I think we won't be fixing it anyway, as #799 is close to be finished. In the meantime, let me encourage you to try out https://github.com/google/oss-fuzz/blob/master/docs/code_coverage.md 

Please share any feedback you have :)

**Comment by Dor1s** [comment]
Actually, I should leave the issue open just to make sure I won't forget to make that button work.

**Comment by cherusker** [comment]
Testing https://github.com/google/oss-fuzz/blob/master/docs/code_coverage.md is definitely on my list but it didn't work out of the box for me which is why I postponed that for a bit. On my Fedora machine I seem to have to run all docker commands in `--privileged` mode which creates files owned by `root`. The problem then is that I seem to be unable to run `gsutil` in `root` mode - hence I get permission errors. There will be a way around that (avoid `docker --privileged ...`, get `sudo gsutil ...` to run, have a script ready with `chown`, ...) but I yet have to look into that.

**Comment by cherusker** [comment]
For some reason I have to run all `docker run ...` commands in privileged mode (tried to debug that for a bit but couldn't come up with anything) anyways; I got `sudo gsutil ...` to work and just browsed through the coverage report - that works really well! 😃

**Comment by Dor1s** [comment]
The button now leads to the shiny new coverage report aggregated per project. If you don't get a report for your project, please check "Coverage build" tab on https://oss-fuzz-build-logs.storage.googleapis.com/index.html and then try reproducing it locally via https://github.com/google/oss-fuzz/blob/master/docs/code_coverage.md
