### ISSUE TITLE
Can testcases be shared with other projects that are part of OSS-Fuzz?

### ISSUE THREAD

**Issue by cherusker** [google/oss-fuzz#1649]
We (FreeType) use `libarchive` to send multiple input files to the fuzz targets. As it happens, OSS-Fuzz just discovered an issue within `libarchive`. Is there a way to share the details page of the test case (incl. the stacktrace etc) with the `libarchive` devs from within OSS-Fuzz?

**Comment by inferno-chromium** [comment]
We can add those folks to cc list if you tell us the bug links and their ccs. If this is needed frequently, we can give your account access to add ccs yourself.

**Comment by cherusker** [comment]
Thanks a lot! :) The bugs are:

- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9565
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9566

I will ask them about their individual CCs :)

Haha let's see how frequently this happens; but thanks for the offer, I will come back to that should something like this be needed again :)

**Comment by cherusker** [comment]
Oh that was a false alarm, sorry, already fixed in `libarchive`'s upstream. Thanks anyways for the extremely quick reply (as always); good to know that such a thing works, should we need it :)
