### ISSUE TITLE
Migrate to -fsanitize=fuzzer

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1652]
That should solve the problem with fuzzing engine being unnecessary instrumented: https://github.com/google/oss-fuzz/pull/1615

We probably would need to build libFuzzer with `-gline-tables-only`

**Comment by jonathanmetzman** [comment]
Another advantage this will have: improving development by speeding up build times since we no longer need to build libFuzzer every time `build_fuzzers` is run

**Comment by jonathanmetzman** [comment]
Marking this as duplicate since most of the discussion has happened elsewhere.
Duplicate of #2164
