### ISSUE TITLE
Definition of `flaky`?

### ISSUE THREAD

**Issue by cherusker** [google/oss-fuzz#1659]
Today, https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9501 got declared `flaky` after being reported as a proper issue four days ago. However, running the instance locally (with the regression suite as well as with OSS-Fuzz via docker) still triggers the report 100% of the time. I am a bit confused now about how to proceed 😛

**Comment by inferno-chromium** [comment]
in future, use "Re-upload testcase" button to see what new stack you get from trunk. I just uploaded it here - https://oss-fuzz.com/v2/testcase-detail/5893688231198720
lets see what we get there.

**Comment by cherusker** [comment]
Thanks a lot; `re-upload` seems like the golden bullet, I will keep that in mind! :)

**Comment by inferno-chromium** [comment]
Sorry for trouble, this started happening because we started ignoring frames with /glibc- to consider in crash state yesterday.

**Comment by cherusker** [comment]
Oh no worries, glad it was so easy to fix :)
