### ISSUE TITLE
NSS build failing

### ISSUE THREAD

**Issue by franziskuskiefer** [google/oss-fuzz#1673]
Similar to #470 I see 

    Step #4: /tmp/crypto_primitives-a52268.s:81: Fatal error: bad .section directive: want a,l,w,x,M,S,G,T in string
    Step #4: clang-7: error: assembler command failed with exit code 1 (use -v to see invocation)

in the build log again [1]. Maybe a bad clang version again?

[1] https://oss-fuzz-build-logs.storage.googleapis.com/log-76ad1102-ef32-4256-9f63-c44948de545a.txt

**Comment by franziskuskiefer** [comment]
@Dor1s Can we do something about this? I can reproduce the issue, but only with the specific clang version.

**Comment by Dor1s** [comment]
We can try using another LLVM revision, if you know which one would work.

Btw, why do we use assembly? I think that doesn't let us to use MemorySanitizer. Should we consider excluding asm code, if there is an option for that?

**Comment by franziskuskiefer** [comment]
Building locally with clang tip worked just fine.

The NSS build isn't really changed from the standard build and thus contains some assembly. But that's really not a lot and nothing we explicitly fuzz at this point. If you think it makes a difference, I could disable assembly code for the oss-fuzz builds

**Comment by Dor1s** [comment]
We can try bumping the revision if you give us a specific number. Alternatively, it will get updated automatically in a week or two.

>> f you think it makes a difference, I could disable assembly code for the oss-fuzz builds

That would make sense if you want to use MSan, for example:

https://github.com/google/oss-fuzz/blob/6b95c945ddb7262778d1bccc376e119aaa91a140/projects/tor/build.sh#L33

**Comment by franziskuskiefer** [comment]
Then let's wait for the next automatic version bump and see if that fixes the issue.
I'll see what I can do about the assembly.

**Comment by franziskuskiefer** [comment]
So this didn't go away...
I had another look at this and found out two things:
a) this is not coming from any assembly code, so disabling wouldn't help
b) `-fsanitize=fuzzer-no-link`is the culprit. Running without that (or with the old `-fsanitize-coverage=trace-pc-guard,trace-cmp`) works just fine. I have no idea why though. Any idea why that might be @Dor1s ?

**Comment by Dor1s** [comment]
I'm afraid we need either @morehouse or @kcc here (I could dig into this, but I'm OOO).

Kostya / Matt, please see the most recent log for NSS on https://oss-fuzz-build-logs.storage.googleapis.com/index.html

The build breaks even in our default ASan + libFuzzer configuration.

**Comment by morehouse** [comment]
LLVM emits assembly for the `__sancov_cntrs` section with the flags `aGwo`.  The integrated assembler understands the `o` flag as specifying a link order, but my system assembler (GNU) doesn't understand the `o` flag which causes the error described here.

If I remove the `-no-integrated-as` flag in `lib/freebl/freebl_base.gypi`, it fixes this issue for me locally, although then we hit issues with the `lib/freebl/intel-gcm.s` file using syntax that Clang's assembler doesn't understand.

I don't know much about `gyp`, but is there some way to build only `intel-gcm.s` with `-no-integrated-as` and everything else without it?

**Comment by franziskuskiefer** [comment]
I see. I can reproduce your findings. I'll try to change the build to add `-no-integrated-as` only to the assembly code.

**Comment by franziskuskiefer** [comment]
I landed changes to the NSS build [1] that solve the issue. The last build was successful [2]. Thanks all for the help!

[1] https://hg.mozilla.org/projects/nss/rev/77ae602f995a
[2] https://oss-fuzz-build-logs.storage.googleapis.com/log-00169ee0-f93b-4511-ba4e-a1daf665e9bb.txt
