### ISSUE TITLE
Bump libFuzzer to r338661+

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#1681]
Please bump libFuzzer to r338661. 
http://llvm.org/viewvc/llvm-project?view=revision&revision=338661 extends the signal produced by value profiling.

**Comment by oliverchang** [comment]
Is this crucial to have now? We can bump it manually in https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-clang/checkout_build_install_llvm.sh#L50, or we'll get it automatically when chromium rolls clang.

**Comment by kcc** [comment]
No rush at all. Just want to watch for new coverage/bugs when it happens

**Comment by Dor1s** [comment]
Wait, we're using the trunk libFuzzer: https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-clang/checkout_build_install_llvm.sh#L96

**Comment by Dor1s** [comment]
Closing as per my previous comment. The version rolled in Chromium is also ahead of the one requested by Kostya.
