### ISSUE TITLE
Timeout only with sanitizer

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#1692]
Hi,

This is about https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9756
On my laptop, the compiled fuzz target on the test case takes 3.5 seconds.
So, it timeouts only with the sanitizers.
3.5 seconds is already a lot, but then, this is because of crypto with big integers.

@kcc already advised in https://github.com/google/oss-fuzz/pull/1400
> Maybe you may want to limit the length of the input for such fuzzers to reduce the size of big integers.

Is this the good solution for this test case ?

Thanks

**Comment by Dor1s** [comment]
Unfortunately, yes. That's the most common workaround, if there is no way to make the target code faster.

**Comment by Dor1s** [comment]
Just for the one that has timeout problem.
