### ISSUE TITLE
reproducing documentation leads to non building

### ISSUE THREAD

**Issue by tsdgeos** [google/oss-fuzz#1699]
https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md says

Reproduce using local source checkout

$ python infra/helper.py build_fuzzers --sanitizer <address/memory/undefined> $PROJECT_NAME <source_path>

but if i do 

python infra/helper.py build_fuzzers --engine libfuzzer --sanitizer memory poppler  /home/tsdgeos/devel/poppler

I get 

Running: docker run --rm -i --privileged -v /home/tsdgeos/devel/oss-fuzz/build/work/poppler:/work gcr.io/oss-fuzz-base/msan-builder bash -c 'cp -r /msan /work'
Running: docker run --rm -i --cap-add SYS_PTRACE -e FUZZING_ENGINE=libfuzzer -e SANITIZER=memory -e MSAN_LIBS_PATH=/work/msan -v /home/tsdgeos/devel/poppler:/src -v /home/tsdgeos/devel/oss-fuzz/build/out/poppler:/out -v /home/tsdgeos/devel/oss-fuzz/build/work/poppler:/work -t gcr.io/oss-fuzz/poppler
---------------------------------------------------------------
Compiling libFuzzer to /usr/lib/libFuzzingEngine.a... clang-7: error: no such file or directory: '/src/libfuzzer/*.cpp'

It seems like it's trying to find libfuzzer in /home/tsdgeos/devel/poppler which it's not there, that folder only contains the poppler code, no idea where that libfuzzer code is.

So i guess the parameters i need to pass are not those?

**Comment by Dor1s** [comment]
I've landed the fix. Please update your checkout and try again. Sorry for the inconvenience.

@oliverchang, please take a look at the commit and close the issue if it LGTY.

**Comment by tsdgeos** [comment]
thanks :)
