### ISSUE TITLE
How to share corpus & coverage between fuzzers

### ISSUE THREAD

**Issue by eustas** [google/oss-fuzz#171]
I would like to add more fuzzer variants (with different compile options).
It would be nice it they would be able to share corpora (or, at least would pick each others corpora) for more effective fuzzing.

Also it would be nice to be able to view combined coverage for a group of fuzzers.

Is that possible?

**Comment by Dor1s** [comment]
We don't have such feature at the moment.

Regarding shared corpus, if you want to use different processing on the same files, why not to add those fuzzer variants into single fuzz target? How many variants are you planning to have? [An example](https://github.com/google/oss-fuzz/blob/master/projects/expat/parse_fuzzer.cc#L15) of multiple variants in single fuzz target.

This also will resolve the combined coverage request :)

**Comment by eustas** [comment]
The problem is that different variants are produced with different compilation flags...

**Comment by kcc** [comment]
btw, what exactly "different compilation flags" are you referring to?

**Comment by eustas** [comment]
In my case (brotli decoder) we have several options:
 * 32 / 64 bit
 * big- / little- / other- endian
 * aligned / unaligned memory access

(Sweet dreams: ideally, running on ARM CPU should also be tested)

**Comment by kcc** [comment]
ack. 
So, we will eventually implement some form of cross-pollination between the targets.
Meanwhile you can do this: 
  * use the same seed corpus for your different builds
  * periodically download all the [corpora](https://github.com/google/oss-fuzz/blob/master/docs/corpora.md) generated by ClusterFuzz, [merge](http://llvm.org/docs/LibFuzzer.html#corpus) them into one and update your seed corpus.

**Comment by inferno-chromium** [comment]
I just fixed this. For every fuzzer, once a day we will cross-pollinate with all the corpuses we have and merge them with the fuzzer corpus. This will be more effective after @kcc enables the experimental crash-resistant merge on trunk. Right now, merge can fail if crash happens on other corpuses.
