### ISSUE TITLE
Notification for failing builds

### ISSUE THREAD

**Issue by cherusker** [google/oss-fuzz#1710]
Hi guys, is there such a thing like email notifications for builds that fail?

I am kind of post mortem identifying what must've happened yesterday and while there was definitely a build fail (my bad), almost all fuzzers + corpora were built. Anyways, `build.sh` exited with `1` (I think) and I believe that no fuzzer got run.

The real issue though: I only detected that by accident when I tried to build the coverage stats locally and ran into corpora that could not been downloaded from ClusterFuzz (from new targets that should've been started yesterday).

**Comment by Dor1s** [comment]
Is your email added to project.yaml file? In that case you should be receiving email notifications from the bugtracker. If you don't receive them, please check your settings at https://bugs.chromium.org/hosting/settings

**Comment by cherusker** [comment]
I do receive emails from issues in the bug tracker but no one (including the `primary_contact` in `project.yaml`) got a notification that the build itself failed.

I can't say for sure that no fuzzers were run (a lot of things point to that conclusion though) but `build.sh` definitely exited early with an error code (and didn't build all fuzzers it was supposed to build).

**Comment by Dor1s** [comment]
> I do receive emails from issues in the bug tracker but no one (including the primary_contact in project.yaml) got a notification that the build itself failed.

In that case I don't understand what's wrong with notifications. Sorry.

> I can't say for sure that no fuzzers were run (a lot of things point to that conclusion though) but build.sh definitely exited early with an error code (and didn't build all fuzzers it was supposed to build).

Broken build doesn't affect the fuzzing process. We always run the most recent build we have. If today's build failed, we would use the yesterday's one, and so one.

**Comment by cherusker** [comment]
> In that case I don't understand what's wrong with notifications. Sorry.

No worries, just wanted to check if that was generally the case and I would generally get notifications for that.

> Broken build doesn't affect the fuzzing process. We always run the most recent build we have. If today's build failed, we would use the yesterday's one, and so one.

Ohhhh - that's clever, love it! ❤️

**Comment by cherusker** [comment]
I would like to reopen this: the build failed again (today it wasn't me tho :P) but no one got any notification about that. Could you please look into this and see if you can find something? Thaaaanks a lot :)

**Comment by Dor1s** [comment]
I think we report the breakage after two consequent failures, and there is only one so far.

**Comment by Dor1s** [comment]
And the most recent build succeeded. Nothing to worry about :)

**Comment by cherusker** [comment]
Oh cool, thanks for the update :)
