### ISSUE TITLE
envoy's ASSERT is reported as abrt

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#1728]
https://oss-fuzz.com/v2/testcase-detail/5736189054156800

oss-fuzz reports this as abort, even though the relevant source line in envoy has ASSERT. 
Strangely, there is no assertion failure message in the log... 
@htuch, any thoughts?

**Comment by htuch** [comment]
@kcc yeah, Envoy's ASSERT macro will ultimately call into `abort()`. I actually completely disabled logging when running on oss-fuzz to reduce spam and hopefully improve performance, this is why you don't see the ASSERT message. I could re-enable at critical log level, but I think this is fine for our purposes as is.

Is there anything we can do to make the fuzz issue categorization better for ClusterFuzz?

**Comment by htuch** [comment]
I've bumped log level to allow critical messages to be observed, see https://github.com/envoyproxy/envoy/pull/4204. Hope this doesn't slow things down too much.

**Comment by kcc** [comment]
Cool! Let's wait for some new ASSERT bugs to pop up. 
It should be useful to see the assert messages in bug titles instead of 'abrt'.

**Comment by kcc** [comment]
New ASSERT bugs are coming. 
(Hm.. They might be dups of the previously submitted abrt bugs). 
Anyway, this issue is resolved

**Comment by kcc** [comment]
@htuch I think there are some more places where you may want to improve ClusterFuzz reports. 
E.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10544 reports as Abrt, but the code looks like 
```
NOT_REACHED_GCOVR_EXCL_LINE;
```

If you don't care, feel free to close.

**Comment by htuch** [comment]
@kcc this is legitimate, let me put in on my TODO.

**Comment by htuch** [comment]
@kcc I had a look into this. The code in question is https://github.com/envoyproxy/envoy/blob/031501b1680d7544ab585b06ea459e94f9972f46/source/common/common/assert.h#L62 (and the `PANIC` macro above). 

This takes a different path to our `ASSERT` macro above, logging `panic:` rather than `assert failure:`. I'm guessing oss-fuzz is smart enough to pick up the latter but not the former today.

I agree that ideally our oss-fuzz reports don't show a plain abort here. Do you have any pointers to where I can make changes to oss-fuzz to do the regex match dance? Do you reckon that picking up on `panic:` is a generally useful thing?

**Comment by Dor1s** [comment]
@htuch, do you want us to rely on `panic: not reached` and `panic: not implemented` strings? I can add parsing for those.

**Comment by Dor1s** [comment]
To be more precise, from the following line:

```
[2018-09-20 01:00:45.516][1][critical][assert] source/common/upstream/cluster_manager_impl.cc:259] panic: not reached
```

We could also extract the filename + line number, and report it like "ASSERT in source/common/upstream/cluster_manager_impl.cc:259".


Another alternative token I see is `[critical][assert]`.

**Comment by Dor1s** [comment]
Ok, sounds good! I don't think we have a way for per-project signatures, but I can add it on ClusterFuzz side, unless @inferno-chromium would have any objections :)

**Comment by htuch** [comment]
Thanks @Dor1s, this is working as witnessed in https://oss-fuzz.com/v2/testcase-detail/5653068977274880?noredirect=1. Feel free to close this one out again.
