### ISSUE TITLE
show combined coverage for all targets in a project 

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#174]
Right now we show coverage data for every target individually. 
Sometimes it might be useful to also show the combined coverage, for all targets in the project. 
(see e.g. #171 )
@mikea , WDYT?

**Comment by inferno-chromium** [comment]
@tanin47 - Tanin has interests to dive deeper into code coverage results. ccing him so that he can work with @mikea and @oliverchang on this in Q1.

**Comment by oliverchang** [comment]
We should be able to implement this pretty easily on CF (I can probably prototype something by the end of the week).

**Comment by mikea** [comment]
You can use sancov tool to merge symbolized reports with `-merge`. (In fact `-merge` and `-symbolize` are synonyms.)

**Comment by oliverchang** [comment]
I implemented a task to periodically merge all the symcovs for a project, but it looks like for some projects (e.g. icu and ffmpeg), the oom-killer kicks in as the sancov tool consumes too much memory. 

@mikea is it possible to reduce the memory usage when merging many symcov files? Does the current implementation load all the symcovs passed to it into memory at once?

**Comment by mikea** [comment]
I've got couple ideas what could be done. I'll download several bug files and will try to merge those.

**Comment by oliverchang** [comment]
This is implemented experimentally on CF. Sample link: https://clusterfuzz-external.appspot.com/coverage_report/job/libfuzzer_asan_boringssl/latest 

This link isn't exposed yet though, since it looks like we're still having some issues on sancov merge for some projects (ffmpeg):

```bash
#!/bin/bash

symcovs=$(gsutil ls gs://clusterfuzz-external-coverage-reports/libFuzzer_ffmpeg_**/2016-12-19.symcov)

i=0
for symcov in $symcovs; do
  gsutil cp $symcov $i.symcov
  i=$(($i + 1))
done

sancov -merge *.symcov > merged.symcov
```

This works on my workstation, but results in a 32GB merged.symcov file. The sum of the individual symcov sizes is nowhere near this size.

**Comment by mikea** [comment]
With these:

https://reviews.llvm.org/rL290277
https://reviews.llvm.org/rL290278

merged.symcov file is reduced to 39M.

**Comment by oliverchang** [comment]
Confirming that with the latest sancov build, ffmpeg works: https://clusterfuzz-external.appspot.com/coverage_report/job/libfuzzer_asan_ffmpeg/latest

Will expose these project coverage links on the home page (and maybe the fuzzer stats page).

**Comment by oliverchang** [comment]
The home page now has a link to the total coverage for each project.
