### ISSUE TITLE
dealing with timeouts

### ISSUE THREAD

**Issue by sebpop** [google/oss-fuzz#1740]
After I added tests to get more coverage in zlib-ng, I end up with timeouts when I run the oss-fuzzer on my laptop.  Also see https://github.com/Dead2/zlib-ng/issues/195
```
ALARM: working on the last Unit for 26 seconds
       and the timeout value is 25 (use -timeout=N to change)
MS: 0 ; base unit: 0000000000000000000000000000000000000000
artifact_prefix='./'; Test unit written to ./timeout-f0e6ea0f11514c6833d70e881de5fdef8da03369
==13== ERROR: libFuzzer: timeout after 26 seconds
```
What is the recommended way to avoid the timeouts?
Should I split the fuzzer test function into several fuzzers that will run independently?

**Comment by kcc** [comment]
If you can split the target into several that'll be great. 
Otherwise, just look at the algorithm and see why it takes to much time. 
Also, do you limit the input size?
If you don't expect any bugs to be triggered by very large inputs, you may do something like this:
```
   if (size  > kMaxSize) return 0;
```

**Comment by sebpop** [comment]
Thanks @kcc for the hint.  I will do both.
