### ISSUE TITLE
Recent commit broke builds

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#175]
```
+ docker run --rm --user 0 -v /var/lib/jenkins/workspace/projects/gnutls/out/address:/out -v /var/lib/jenkins/workspace/projects/gnutls/junit_reports/address:/junit_reports -e TEST_SUITE=gnutls.address. -t ossfuzz/base-runner test_report
docker: Error response from daemon: oci runtime error: exec: "test_report": executable file not found in $PATH.
```

Seen in several of the failing builds from https://oss-fuzz-build-logs.storage.googleapis.com/status.html

**Comment by alex** [comment]
I think this has a really simple explanation, like `ossfuzz/base-runner` needs to be rebuilt.

**Comment by oliverchang** [comment]
Closing this now. Looks like builds are succeeding again.

**Comment by alex** [comment]
I guess `base-runner` is rebuilt on a different schedule than other builds.

**Comment by mikea** [comment]
@alex it is always a trouble when you make a change that depends on base-images. It usually takes an hour for it to rebuild and dependencies to catch up.
