### ISSUE TITLE
Deactivate leak detection when building with build_fuzzers

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#1752]
Is it possible to do such a thing ?
I experienced the problem with gnupg https://github.com/catenacyber/gnupg/commit/0928dae4305c37be7e56bfe7b828c38b2f99a909

And now I am getting with a new project
`python infra/helper.py build_fuzzers --sanitizer address project`
The undefined sanitizer seems to work though

**Comment by kcc** [comment]
You can set `ASAN_OPTIONS=detect_leaks=0` in `build.sh`. 
Some projects already do this.
This won't affect how the fuzzers are run, only how they are built.

**Comment by catenacyber** [comment]
Thank you @kcc
