### ISSUE TITLE
No space left on device errors

### ISSUE THREAD

**Issue by htuch** [google/oss-fuzz#1759]
From https://oss-fuzz.com/v2/testcase-detail/5644730562510848:

```
[2018-08-23 21:05:44.628][22433][critical][assert] test/test_common/environment.cc:54] assert failure: ::mkdtemp(test_tmpdir) != nullptr. Details: Failed to create tmpdir /tmp/envoy_test_tmp.LBSV5i No space left on device
```

Thoughts on how we can be hitting this in ClusterFuzz? We started to run into issues like this after recently switching to using `mkdtemp` to attempt to give each fuzz test its own area of the filesystem, to reduce the chance of interactions between independent test cases.

**Comment by Dor1s** [comment]
Do you remove those dirs afterwards?

**Comment by htuch** [comment]
Yep, I had thought the artifacts would be small enough, but I guess they add up. Should be fixed by https://github.com/envoyproxy/envoy/pull/4253.
