### ISSUE TITLE
Project bignum-fuzzer is creating confusion for upstream developers

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1761]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10063#c3

@kroeckx @guidovranken @kcc - lets try to discuss and resolve any confusion that this project creates. How can this comparison be improved ? What sort of testcase reduction are you looking for ?

Just fyi, that bug is not created as a security bug.

**Comment by kroeckx** [comment]
There is a bug, but it's only reproducible on certain cpu types. This result in it being found by oss-fuzz, and later closed by it while the bug didn't get fixed, because it tried to reproduce it on a different CPU type. This same bug has already been found and closed several times. The bug is still not fixed in OpenSSL.

**Comment by guidovranken** [comment]
I can make a workaround in in the base project ( https://github.com/guidovranken/bignum-fuzzer ).
Either that or OpenSSL must fix the bug. I already reported the bug "like 10 times" so I'm not going to make another GitHub issue for it. Devs have all the info they need.

**Comment by guidovranken** [comment]
Workaround implemented https://github.com/guidovranken/bignum-fuzzer/commit/9ccc3370fa728af9f5b06533a4149ddb678a1080
I expect that the outstanding bug(s) will be marked as resolved by the system in the next build.
Will remove the workaround once OpenSSL fixes the bug.

**Comment by guidovranken** [comment]
As expected, the system has now marked the issue as resolved. This particular bug will not reoccur. Feel free to close this issue if this solution is satisfactory.

**Comment by davidben** [comment]
Here, have a fix. It's pretty uninteresting. OpenSSL just got the order of two things wrong.
https://github.com/openssl/openssl/pull/7187
