### ISSUE TITLE
Regression in masn?

### ISSUE THREAD

**Issue by tsdgeos** [google/oss-fuzz#1783]
MemorySanitizer is reporting an error in this code
```
  char tok1[256];
  tok1[0] = 3;
  tok1[1] = 0;
  if (!strcmp(tok1, "endcidrange")) {
    return;
  }
```

```
Uninitialized bytes in __interceptor_memcmp at offset 2 inside [0x7ffd77d199e0, 12)
==9==WARNING: MemorySanitizer: use-of-uninitialized-value
```

To me that code is fine, sure tok1 has uninitalized byes at offset 2, but strcmp should never go there since at offset 1 there's the null character signaling the end of the string, no?

P.S: Probably this is not the correct place to report this? If so can someone point me to it?

**Comment by morehouse** [comment]
Please open an issue at https://github.com/google/sanitizers/.
