### ISSUE TITLE
Sharing OSS-Fuzz Issues with another Project

### ISSUE THREAD

**Issue by cherusker** [google/oss-fuzz#1787]
Follow-up on https://github.com/google/oss-fuzz/issues/1649; now two issues have really been found that belong another (included) project:

* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10183
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10192

I don't know yet who will want to get CCed on this but I remember that an option exists where we can manually add CCs ourselves -- if that is still possible, I would kindly ask you to activate that for `freetype2`.

Thanks + have a great Sunday!

**Comment by oliverchang** [comment]
I've given your email account the ability to edit CCs. Please let us know if anyone else in freetype would like the ability to do so.

**Comment by cherusker** [comment]
Thanks, works perfectly as expected :) I think no one else really needs that feature for now.
