### ISSUE TITLE
Rename CF sanitizer names

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#180]
Currently it says:

Fuzzing engine: libFuzzer
Sanitizer: ASAN (UBSAN)

Should be: "address", "undefined" or "memory" - the same string we specify in project.yaml

**Comment by kcc** [comment]
maybe... OTOH, ASAN is more recognizable than "address".

**Comment by oliverchang** [comment]
What about both? Ie 

Sanitizer: address (ASAN)

**Comment by kcc** [comment]
that SGTM

**Comment by oliverchang** [comment]
This is done.
