### ISSUE TITLE
Provide access to /dev/shm through minijail

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#1800]
This is needed to allow the firefox IPC fuzzer to work on CF.
@alex I think you mentioned it was just a small part of shm that is needed? Do you remember what this is?

I think I'll try to add it if it doesn't defeat the purpose of sandboxing.

CC: @pdknsk

**Comment by oliverchang** [comment]
I don't think it's worth adding support for this.

We should just wait for minijail to go away, hopefully in the next few months unless there's really an urgent need.

**Comment by jonathanmetzman** [comment]
OK. Given that we intend to remove minijail in a couple of months probably better to wait until then instead of adding features to it.

**Comment by pdknsk** [comment]
Is there some work going on here behind the scenes? I've been sporadically getting notifications over the past two weeks about flaky reports for target `ContentParentIPC`, such as for `ipc::SharedStringMap::SharedStringMap` today.
