### ISSUE TITLE
Compiler optimization issue with strcmp()...

### ISSUE THREAD

**Issue by sebras** [google/oss-fuzz#1801]
In https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10132 I'm seeing the strcmp() issues already reported to MemorySanitizer over at https://github.com/google/sanitizers/issues/993. They have forward this issue to https://reviews.llvm.org/D50233 where they appear to be fixing this issue.

Once this is fixed in the clang compiler, please update ASAP so the mupdf project (and others) won't be affected by this bug.

**Comment by inferno-chromium** [comment]
Fix is in https://reviews.llvm.org/rL342582, all bugs closed.

**Comment by sebras** [comment]
Thank you to the clang developers for the fix and to you for integrating this quickly. :)
