### ISSUE TITLE
Miscompiling(?) string functions to non-string functions

### ISSUE THREAD

**Issue by agl** [google/oss-fuzz#1802]
In [this BoringSSL report](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10140), disassembling the binary compiled by OSS-Fuzz appears to show a strncmp turning into a call to `__interceptor_memcmp`. The latter is (correctly) reporting a use of uninit memory because the length argument to `strncmp` is only a maximum length&mdash;arguments can be shorter.

[Here's](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10129) another report that seems to have the same cause.

I don't think this is a valid compilation? At the very least, it looks like OSS-Fuzz is stuck on this issue and I don't know how to address it.

**Comment by kcc** [comment]
@eugenis is this related to #1801 ?

**Comment by eugenis** [comment]
Yes, and both are https://github.com/google/sanitizers/issues/993

**Comment by inferno-chromium** [comment]
Fix is in https://reviews.llvm.org/rL342582, all bugs closed.
