### ISSUE TITLE
Consider publishing all coverage reports in a single place

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1809]
Like on a status page. Inspired by https://github.com/google/oss-fuzz/commit/4574ff8bdbc5bf6f1197fa828e59fc2a2b6db797#commitcomment-30459068

**Comment by pdknsk** [comment]
I'd like a way to directly link to current coverage. Using `/latest/` or so instead of `/YYYYMMDD/` in the link.

**Comment by pdknsk** [comment]
Ah, thanks.

**Comment by evverx** [comment]
@Dor1s The links above don't seem to work anymore and although the "/v2/" part can be removed to make them point to the coverage reports, it would be great if oss-fuzz could redirect people there automatically so that it wouldn't be necessary to edit all the links out there.

**Comment by inferno-chromium** [comment]
@evverx - we kept the /v2 prefix for a long time as redirect, today i removed those. please just use the links without those.

**Comment by evverx** [comment]
@inferno-chromium I will (now that I have no choice anyway :-)). I'm just worried that some links I've shared are dead now (though I'm probably too optimistic about how many people look at the coverage reports).

**Comment by Dor1s** [comment]
Thanks for catching, I've updated my comment above and removed `/v2` :)

**Comment by Dor1s** [comment]
A wild idea: we can publish coverage report links on the main page of CF even for unauthorized users. It should work for Chromium's ClusterFuzz well too, as the coverage reports for Chromium are public as well.
