### ISSUE TITLE
Info: Which pre-built MSan libraries are available?

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#1811]
Hello,

At the time of integrating Open vSwitch I was hesitant to add "MemorySanitizer" to `project.yaml` because I was not sure if the PR is responsible for MSan instrumentation of dependent libraries OR if the oss-fuzz base docker image contains these MSan libraries. I consulted the oss-fuzz docs but could not find this piece of information.

My question is: Could we have more concrete guidelines for MSan integration? Perhaps with examples and a list of MSan libs available "for free". For example, Open vSwitch depends on a handful of standard libs such as libssl, libz, libcrypto and you may already have stock MSan versions of these? In which case, adding MSan is a simple flick of the switch (i.e., adding MemorySanitizer in `project.yaml`).

Thank you!

**Comment by Dor1s** [comment]
Hello @bshastry,

From: https://github.com/google/oss-fuzz/blob/22f3a1481cbc8252fb340369cdb3d50f185017fa/docs/new_project_guide.md#sanitizers-optional:

> MemorySanitizer ("memory") is also supported, but is not enabled by default due to likelihood of false positives. For this to work, ensure that your project's runtime dependencies are listed in this file. You may opt-in by adding "memory" to this list.

**This list** points to https://github.com/google/oss-fuzz/blob/master/infra/base-images/msan-builder/Dockerfile#L20

I'd also highly recommend to test MSan build locally:

1) `python infra/helper.py build_fuzzers --sanitizer=memory %PROJECT%`
2) `python infra/helper.py shell %PROJECT%`
3) download corpus backup from the Fuzzer Stats page
4) in another terminal do `docker ps`, lookup the container name
5) `docker cp %CORPUS% %CONTAINER_NAME%:/out/`
6) switch back to the terminal from 2), unpack the corpus and run fuzzers built with MSan with the corpus
7) if you don't see any false positive crashes in a few minutes, that's a good sign :)

**Comment by bshastry** [comment]
Hello @Dor1s Thanks for your help.

> download corpus backup from the Fuzzer Stats page

Could you please link me to this page? Should I be listed on auto_ccs to access this?

**Comment by Dor1s** [comment]
@bshastry, https://oss-fuzz.com/v2/fuzzer-stats

Yes, you need to be listed on auto_ccs to access this.

In the worst case, you can test fuzzers using seed corpus or even no corpus at all.

> Edit: I am on "auto_ccs" for openvswitch as of a few minutes ago, but it seems I still don't have access to oss-fuzz.com

I think it takes up to 30 minutes for such changes to propagate.

**Comment by bshastry** [comment]
Hey @Dor1s 

I tried MSan testing and it flags a likely true positive right away. However, I get the following warnings during the build process:

> WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libc.so.6
> WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libdl.so.2
> WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libgcc_s.so.1
> WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libm.so.6
> WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libpthread.so.0
> WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/librt.so.1
> WARNING: Instrumented library not found for /usr/lib/x86_64-linux-gnu/libatomic.so.1

Now I know that the test harness depends indirectly on the following libs: librt, libatomic, libm and libpthread but I don't see how it depends on libdl, libc and libgcc_s.

Should I pay attention to these warnings?

**Comment by Dor1s** [comment]
No, I think these warnings are fine, see the discussion in #1725

**Comment by bshastry** [comment]
Thanks for clarifying. Closing the issue.
