### ISSUE TITLE
improve woff2 fuzzing

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#183]
@rsheeter
Here is what needs to be done: 

1. Add yourself to https://github.com/google/oss-fuzz/blob/master/projects/woff2/project.yaml
like this: 
primary_contact: "your-email"

2. Move the fuzz target (https://github.com/google/oss-fuzz/blob/master/projects/woff2/convert_woff2ttf_fuzzer.cc) to the woff repository. 
Also put any other targets you want there, e.g. those from google3
(https://cs.corp.google.com/piper///depot/google3/third_party/woff/woff2_dec_fuzzer_new_entry.cc, etc)

See more about our preferred integration here:
https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md

3. Modify Dockerfile and build.sh [here](https://github.com/google/oss-fuzz/tree/master/projects/woff2)
to get a seed corpus somewhere from internet or from the woff2 repo. 
More info: https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md#seed-corpus
For woff2 this is a critical step -- IIRC the file format is pretty hard to crack w/o proper seeds. 

4.  Once 1-3 are done, wait for a few days and look at clusterfuzz-external.appspot.com,
find woff2 and see if the fuzzer has good enough coverage.

**Comment by inferno-chromium** [comment]
This is mostly done.

@rsheeter - can you add a seed corpus for woff2 and then we can close this issue.

**Comment by inferno-chromium** [comment]
@rsheeter - do you have a woff2 corpus, we have few files in https://cs.chromium.org/chromium/src/testing/libfuzzer/fuzzers/woff2_corpus/?q=woff2+package:%5Echromium$+libfuzzer&dr. If nothing, we should just add that and then close this issue.

**Comment by rsheeter** [comment]
I think I have a few more but I haven't had time to check on their licensing. That looks like a reasonable start set.

**Comment by inferno-chromium** [comment]
Ok added for now, once you have licenses cleared, please move all these in woff2 repo.
