### ISSUE TITLE
[bignum-fuzzer] Build succeeds locally, but ClusterFuzz-External keeps reporting failure

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#1834]
Since https://github.com/google/oss-fuzz/pull/1810 I can build bignum-fuzzer locally.

But the build on your end is still failing: https://oss-fuzz-build-logs.storage.googleapis.com/log-c686f700-479b-4e35-8ad3-85dbe38a60d7.txt

As you can see here: https://raw.githubusercontent.com/guidovranken/bignum-fuzzer/master/modules/rust/Makefile

I use static instrumentation flags because I cannot use CFLAGS directly with the Rust compiler.

And possibly the problem lies in the discrepancy between ClusterFuzz' ```-fsanitize-coverage=``` flags and my static Rust flags.

Can you tell me how to simulate the build configuration as used in the build log above so I can test and resolve this locally before submitting a patch?

Other alternatives include disabling the Rust fuzzer for now, or running it without code coverage instrumentation..

**Comment by Dor1s** [comment]
For fuzzing builds, we're using `-fsanitize=fuzzer-no-link` instrumentation. The flag combination from the log (`-fsanitize-coverage=bb,no-prune,trace-pc-guard`) is used for the old code coverage pipeline, which will be removed later this week, as we're already serving new coverage reports (e.g. https://oss-fuzz.com/coverage_report/job/libfuzzer_asan_bignum-fuzzer/latest).

**Comment by Dor1s** [comment]
Assigning this to myself to verify that the build succeeds once I disable old coverage build (have a draft CL in https://github.com/google/oss-fuzz/commit/14ebc1e6bfc134f641ec6152cf318fb40226a59c).

**Comment by Dor1s** [comment]
Looks like now it's breaking when building AFL + ASan, in that config we're using `-fsanitize-coverage=trace-pc-guard`. Do you need to use AFL?

**Comment by inferno-chromium** [comment]
Please submit a pull request with just libfuzzer in list - https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md#sanitizers-optional
