### ISSUE TITLE
afl fuzzing engine not respecting fuzzer options

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#1846]
Hi oss-fuzz team,

I just noticed that oss-fuzz auto-filed a bug for openvswitch (ID:10714) that is triggered by an input that is 20 kB in size. However, the [options file for this target](https://github.com/openvswitch/ovs/blob/master/tests/oss-fuzz/config/expr_parse_target.options#L3) clearly stipulates a "max_len" of 100 bytes.

EDIT: Disregard this comment ~~Also, there is something weird in the naming of the fuzzer target. It is called "openvswitch_expr_parse_target" although the OvS build system clearly produces a target that is simply called "expr_parse_target." Any ideas why this may be happening?~~

On a related note:

- Is the [libfuzzer] header mandatory for oss-fuzz style fuzzer options file?
- Are the options propagated to all fuzzing engines? It seems the engine that produces the big input is afl , so I am wondering if I am missing a header like `[afl]` or so in my options?

**Comment by inferno-chromium** [comment]
options files is only applicable to libFuzzer, not AFL. if you want to restrict size across both libFuzzer, AFL, then just do it in fuzz target itself by adding a check on size argument.

Unrelated note: looks like you might have added expr_parse_target.options, that file is invalid options file, libFuzzer can't parse, can you fix it please.

**Comment by Dor1s** [comment]
Documentation about this: https://github.com/google/oss-fuzz/blob/22f3a1481cbc8252fb340369cdb3d50f185017fa/docs/new_project_guide.md#custom-libfuzzer-options-for-clusterfuzz

**Comment by bshastry** [comment]
Thank you @inferno-chromium @Dor1s for the clarification. I fixed the options formatting by adding the `[libfuzzer]` header that it was previously missing. Hope all is well now.

**Comment by Dor1s** [comment]
Just to clarify this once again: `max_len` specified in .options file would not work well, the length limit must be enforced in a fuzz target source code.
