### ISSUE TITLE
improve zlib fuzzing

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#186]
@madler, can you please help to improve zlib fuzzing. See our blog post at https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html

1. Add yourself to https://github.com/google/oss-fuzz/blob/master/projects/zlib/project.yaml
like this:
primary_contact: "your-email"

2. Move the fuzz target (https://github.com/google/oss-fuzz/blob/master/projects/zlib/zlib_uncompress_fuzzer.cc) to the zlib repository.
See more about our preferred integration here:
https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md
Please see if the fuzz target code can be improved.

3. Modify Dockerfile and build.sh [here](https://github.com/google/oss-fuzz/tree/master/projects/zlib)
to get a seed corpus somewhere from internet or from the zlib repo.
More info: https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md#seed-corpus
The file format can be hard to crack w/o proper seeds.

4. Once 1-3 are done, wait for a few days and look at clusterfuzz-external.appspot.com,
find zlib and see if the fuzzer has good enough coverage.

**Comment by inferno-chromium** [comment]
@madler - friendly ping!

**Comment by inferno-chromium** [comment]
@madler - friendly ping, it should be pretty easy to finish this ideal integration with oss-fuzz and finding many more bugs and vulnerabilities.

**Comment by inferno-chromium** [comment]
Closing due to lack of interest.

**Comment by ProgramMax** [comment]
Maybe I can help.
I wrote many of Chromium's zlib fuzzers as seen here:
https://cs.chromium.org/chromium/src/third_party/zlib/contrib/tests/fuzzers/

I would be happy to submit these upstream.

Chromium's copy of zlib is slightly different from standard so it would make sense to treat the two fuzz targets separately.

**Comment by Dor1s** [comment]
Re-opening as per the comment above :)

**Comment by ProgramMax** [comment]
I have created a pull request for zlib here:
https://github.com/madler/zlib/pull/403
Please go take a look and let me know if you think anything should be changed.

It takes a while for upstream zlib changes to be accepted.
Once they are, I can alter OSS-Fuzz.

**Comment by ProgramMax** [comment]
While we wait, I also created a pull request to add myself to the autocc list of OSS-Fuzz's zlib coverage:
https://github.com/google/oss-fuzz/pull/2152

**Comment by Dor1s** [comment]
Awesome! Left some feedback on https://github.com/madler/zlib/pull/403

**Comment by Dor1s** [comment]
This is done, there are multiple fuzz targets now and the coverage is relatively good: https://storage.googleapis.com/oss-fuzz-coverage/zlib/reports/20200117/linux/report.html

**Comment by alexhultman** [comment]
I have a fuzz target that triggers MemorySanitizer issues use-of-uninitialized value that is not accepted as a bug upstream. What should I do? Ignore it and say that zlib is not compatible with MemorySanitizer or what?

**Comment by Dor1s** [comment]
@alexhultman I'm not sure this is the right place to ask this :) You can contribute the fuzz target to oss-fuzz though.
