### ISSUE TITLE
Add seed corpus for pcre2 from repo

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#187]
src/testdata seems to contain a bunch of input files. Can these be directly feed into pcre2_fuzzsupport.c or as seed corpus or do we need to feed individual lines, etc. I don't know how test data is consumed, but it will be great to add seeds to improve fuzzing efficiency.

**Comment by kcc** [comment]
Theese inputs are not for the fuzz target, afiact. 
also, in experience with fuzzing regexp implementations, this kind of target does not really require seeds

**Comment by inferno-chromium** [comment]
Ok, closing issue.
