### ISSUE TITLE
I can't access oss-fuzz issues by using my Google account.

### ISSUE THREAD

**Issue by guyharris** [google/oss-fuzz#1876]
I just created a Google account so I can look at oss-fuzz issues file against libpcap and tcpdump.

I logged into the Google account, but when I went to look at an issue, I got

You (email=guy@alum.mit.edu) are not authorized to access this page!

Please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.

So here's the issue.

(Note: I'm using a private browser window to access that; I don't want my Google account tied to *any* Web accesses other than those needed to look at oss-fuzz issues and other bug reports that are, unfortunately, hidden behind Google accounts.)

**Comment by oliverchang** [comment]
You need to be listed on https://github.com/google/oss-fuzz/blob/master/projects/libpcap/project.yaml. Are you a libpcap developer?

**Comment by guyharris** [comment]
> Are you a libpcap developer?

Yes, I'm a core developer.

So are @fxlb, @infrastation, and @mcr - I've asked them in issue #1756 whether they want to be added as well.
