### ISSUE TITLE
How many memory (RAM) and CPU cores are available in builders?

### ISSUE THREAD

**Issue by Lekensteyn** [google/oss-fuzz#1885]
On a VM with 6 cores and 8GiB of memory, ninja creates 8 parallel link jobs. This caused an OOM which failed the `build_image` step. When reducing the number of jobs to 6 (`$(nproc)`), the build completes though.

Would this be a problem for the build environments used by oss-fuzz? The FAQ only mentions the per-process 2GB RAM limitation for runtime, it does not say anything about the build environment.

Based on https://oss-fuzz-build-logs.storage.googleapis.com/index.html, nproc = 32.

**Comment by inferno-chromium** [comment]
@oliverchang - can you please this to faq and here.

**Comment by inferno-chromium** [comment]
Can you please add this to faq and here.

**Comment by oliverchang** [comment]
We use 32CPU / 28.8 GB machines for building

**Comment by oliverchang** [comment]
We use 32CPU / 28.8GB machines for building. Adding this to the faq.

**Comment by Lekensteyn** [comment]
Thanks!

**Comment by Lekensteyn** [comment]
Thank you!
