### ISSUE TITLE
Adding --no-as-needed to coverage build broke Tor builds

### ISSUE THREAD

**Issue by nmathewson** [google/oss-fuzz#1886]
Hi!  It looks like this build failure is caused by the --no-as-needed linker flag added by 5c263869ae364dd6ea4331cf0cdfcd58639d286b: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10914#c5

I'm not sure whether this is something that should be fixed in the flags, or whether something I should try to resolve myself.  In the latter case, any tips would be welcome. :)

**Comment by Dor1s** [comment]
Removing `--no-as-needed` does not fix the build for me.

**Comment by Dor1s** [comment]
Just checked that the most recent coverage build has succeeded.
