### ISSUE TITLE
improve ots fuzzing

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#189]
@khaledhosny, can you please help to improve ots fuzzing. See our blog post at https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html

1. Add yourself to https://github.com/google/oss-fuzz/blob/master/projects/ots/project.yaml
like this:
primary_contact: "your-email"

2. Move the fuzz target (https://github.com/google/oss-fuzz/blob/master/projects/ots/ots_fuzzer.cc) to the upstream repository.
See more about our preferred integration here:
https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md
Please see if the fuzz target code can be improved.

3. Modify Dockerfile and build.sh in https://github.com/google/oss-fuzz/tree/master/projects/ots
 and move seed corpus to somewhere in your repo.
More info: https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md#seed-corpus

4. Once 1-3 are done, wait for a few days and look at clusterfuzz-external.appspot.com,
find ots and see if the fuzzer has good enough coverage.

**Comment by inferno-chromium** [comment]
@khaledhosny, friendly ping!

**Comment by khaledhosny** [comment]
Will work on this soonish.

**Comment by inferno-chromium** [comment]
Thanks @khaledhosny!
