### ISSUE TITLE
xz

### ISSUE THREAD

**Issue by pdknsk** [google/oss-fuzz#1892]
I did the inital work on that project some while ago, but didn't pursue it. I [uploaded](https://github.com/pdknsk/oss-fuzz/commit/6265894b4ca049895eaa522ca3964b78ff8a52ef) it in case someone else wants to take and complete it. They can claim full ownership.

What still needs to be done.
- Ask the author
- Add flag to `xz` to ignore `CRC32` checks

`xz` has `LZMA_IGNORE_CHECK` but it's not enough. From the relevant [commit](https://git.tukaani.org/?p=xz.git;a=blobdiff;f=src/liblzma/api/lzma/container.h;h=b9c5e71970d1597fc83233d6624c26d50d77a778;hp=891c6b7af6a15d1f9af795ae0dc18baae9fd09e9;hb=9adbc2ff373f979c917cdfd3679ce0ebd59f1040;hpb=0e0f34b8e4f1c60ecaec15c2105982381cc9c3e6).

> This flag only affects the checks of the compressed data itself; the CRC32
> values in the .xz headers will still be verified normally.

@bshastry @catenacyber

**Comment by catenacyber** [comment]
Thanks @pdknsk for tagging me as well
@bshastry I let you take a look first

**Comment by pdknsk** [comment]
When I ran this locally, I noticed the fuzzer didn't seem to make much progress. I think the CRC32 checks are holding it back. According to the [format specs](https://tukaani.org/xz/xz-file-format-1.0.4.txt), those checks are used in several places.

**Comment by alex** [comment]
Having a CRC check won't just slow it down, it'll make such a massive performance difference that with-crc checks is basically useless :-)

The odds of randomly passing a CRC check are like 1 in 4 billion or something, so as a rough estimate it'd be a 4 billion x perf difference. Probably worse, since it'd render the coverage guiding useless, and it'd basically just be a truly random fuzzer.

**Comment by bshastry** [comment]
Thank you @alex and @pdknsk for the discussion. Yes, that is problematic indeed. Tbh, I am a bit confused how the fuzzer is making significant progress locally, but then again I don't really know how to characterize significance. Here's what I see anyway:

```
Running: docker run --rm -i --privileged -e FUZZING_ENGINE=libfuzzer -v /home/bhargava/work/github/oss-fuzz-v2/build/out/xz:/out -t gcr.
io/oss-fuzz-base/base-runner run_fuzzer fuzz                                                                                            
Using seed corpus: fuzz_seed_corpus.zip                                                                                                 
/out/fuzz -rss_limit_mb=2048 -timeout=25 /tmp/fuzz_corpus -dict=fuzz.dict < /dev/null
Dictionary: 2 entries
INFO: Seed: 2877407825
INFO: Loaded 1 modules   (3021 inline 8-bit counters): 3021 [0x76b410, 0x76bfdd),
INFO: Loaded 1 PC tables (3021 PCs): 3021 [0x5166a0,0x522370),
...
...
#34311  REDUCE cov: 1844 ft: 10762 corp: 481/791Kb lim: 4 exec/s: 4901 rss: 26Mb L: 253/33514 MS: 1 EraseBytes-
#34532  NEW    cov: 1846 ft: 10764 corp: 482/791Kb lim: 4 exec/s: 4316 rss: 26Mb L: 46/33514 MS: 1 ChangeASCIIInt-
#34570  NEW    cov: 1846 ft: 10766 corp: 483/819Kb lim: 4 exec/s: 4321 rss: 26Mb L: 28865/33514 MS: 3 CopyPart-ChangeBinInt-ChangeByte-
#34591  REDUCE cov: 1846 ft: 10766 corp: 483/811Kb lim: 4 exec/s: 4323 rss: 26Mb L: 10049/33514 MS: 1 EraseBytes-
#34683  REDUCE cov: 1846 ft: 10766 corp: 483/810Kb lim: 4 exec/s: 4335 rss: 26Mb L: 5370/33514 MS: 2 ChangeByte-EraseBytes-
#34705  REDUCE cov: 1846 ft: 10766 corp: 483/810Kb lim: 4 exec/s: 4338 rss: 26Mb L: 174/33514 MS: 2 ChangeByte-EraseBytes-
#34736  NEW    cov: 1847 ft: 10767 corp: 484/810Kb lim: 4 exec/s: 4342 rss: 26Mb L: 38/33514 MS: 1 ChangeByte-
#34737  REDUCE cov: 1847 ft: 10767 corp: 484/810Kb lim: 4 exec/s: 4342 rss: 26Mb L: 235/33514 MS: 1 EraseBytes-
#34819  NEW    cov: 1847 ft: 10769 corp: 485/810Kb lim: 4 exec/s: 4352 rss: 26Mb L: 56/33514 MS: 2 CopyPart-CopyPart-
```

So if I understand libFuzzer output correctly, what this tells me is:
  - There are a total of `3021` instrumented CFG edges
  - Over `1847` of them (a little over 60%) have been covered by the fuzzer

This corresponds to code that disables CRC checks for the body of the compressed data, but not for its headers. In other words, it is my understanding that the headers in the compressed data (fuzz input) are still being checked for integrity.

My earlier intuition was that CRC checks for header fields will likely hinder fuzzing (pseudo code based on my understanding):

```
int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
    init_decoder();
    if (crc_check(data, HEADER_LEN))
       return 0;
    decompress(data, size);
    return 0;
}
```

All of this is arm chair analysis, so this likely is grossly inaccurate. I will dig into the code soon. In the meantime, I sent a patch to the xz devel mailing list after making some modifications to the test harness written by @pdknsk . I'm hoping to get some of these points clarified from the dev team as well. Thank you!
