### ISSUE TITLE
coverage oddity

### ISSUE THREAD

**Issue by pdknsk** [google/oss-fuzz#1893]
For project `glib`, targets [`fuzz_bookmark`](https://storage.googleapis.com/oss-fuzz-coverage/glib/reports/20181019/linux/src/glib/fuzzing/fuzz_bookmark.c.html) and [`fuzz_key`](https://storage.googleapis.com/oss-fuzz-coverage/glib/reports/20181019/linux/src/glib/fuzzing/fuzz_key.c.html) have the same run count today: `5.97k`.

What a coincidence, you might think. Except that it's also true yesterday, a week ago, and every other day.

It turns out the main functions of the targets, which are called on every run, have very different counts.

[`g_bookmark_file_load_from_data`](https://storage.googleapis.com/oss-fuzz-coverage/glib/reports/20181019/linux/src/glib/glib/gbookmarkfile.c.html#L1685) `4.14k`
[`g_key_file_load_from_data`](https://storage.googleapis.com/oss-fuzz-coverage/glib/reports/20181019/linux/src/glib/glib/gkeyfile.c.html#L951) `1.83k`

You may notice it sums up to the bogus count.

From what I can tell, this appears to be just a display bug, and doesn't affect coverage itself.

**Comment by Dor1s** [comment]
Good catch! Very interesting. I've been fixing pretty much the same issue upstream ~5 months ago: https://reviews.llvm.org/rL331801

WIll take a closer look later this week.

**Comment by Dor1s** [comment]
Sorry, didn't get to it this week. But it's in my queue. Let me know if this is blocking anything on your side.

**Comment by Dor1s** [comment]
This looks obsolete.
