### ISSUE TITLE
OSS-FUZZ doesn't handle errors in generated code very well

### ISSUE THREAD

**Issue by guyharris** [google/oss-fuzz#1899]
[This report on a memory leak in libpcap](https://oss-fuzz.com/v2/testcase-detail/5733944318754816?noredirect=1) reports that the allocated memory is allocated on line 1952 of grammar.c.

grammar.c is generated by Bison or Berkeley YACC from grammar.y; the fact that it's complaining about grammar.c, not grammar.y, suggests that the memory might have been allocated by Bison-generated code, not by code in grammar.y.

Unfortunately, the generated grammar.c does not seem to be made available for inspection in any obvious place; the error report page has a GitHub link for libpcap/build/grammar.c, but, not surprisingly, that link gets a 404 from GitHub.

The error report email for this issue says that

> This crash occurs very frequently on linux platform and is likely preventing the fuzzer fuzz_filter from making much progress. Fixing this will allow more bugs to be found.

Unfortunately, the reports of errors in grammar.c are *also* occurring frequently and are preventing the libpcap developers from making much progress.  Fixing this will allow *this* bug to be found.

(No, ASAN isn't reporting any leak on my Mac running High Sierra, so it's not as if it's an easy-to-find leak.)

**Comment by Dor1s** [comment]
Do you know whether valgrind detects this memory leak or not?

//cc @inferno-chromium as this week's sheriff

**Comment by guyharris** [comment]
Neither Asan nor valgrind report a leak on my Ubuntu 16.04 VM, either.

$ bison --version
bison (GNU Bison) 3.0.4
Written by Robert Corbett and Richard Stallman.

Line 1952 of the grammar.c that *it* generates is

        union yyalloc *yyptr =
          (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));

which actually allocates something.  If `YYSTACK_ALLOC` is defined, the grammar uses `alloca()` to allocate stuff on the stack; otherwise, it uses `YYMALLOC` and `YYFREE`, which are defined to `malloc` and `free` if they're not defined otherwise.  *We* (the libpcap developers) don't define them anywhere; hopefully *you* don't.

A quick look at grammar.c seems to suggest that the stack eventually *does* get freed.

Maybe it's not getting freed, for some reason, in *your* grammar.c.  (You're not defining `yyoverflow`, are you?)

**Comment by Dor1s** [comment]
AFAIK, Valgrind doesn't work with ASan. In UBSan config it detects the following leak:

```
# valgrind --leak-check=yes ./fuzz_filter clusterfuzz-testcase-minimized-fuzz_filter-5733944318754816 
==1339== Memcheck, a memory error detector
==1339== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==1339== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==1339== Command: ./fuzz_filter clusterfuzz-testcase-minimized-fuzz_filter-5733944318754816
==1339== 
INFO: Seed: 2882647851
INFO: Loaded 1 modules   (13336 inline 8-bit counters): 13336 [0x7e0bf0, 0x7e4008), 
INFO: Loaded 1 PC tables (13336 PCs): 13336 [0x5610e0,0x595260), 
./fuzz_filter: Running 1 inputs 1 time(s) each.
Running: clusterfuzz-testcase-minimized-fuzz_filter-5733944318754816
Executed clusterfuzz-testcase-minimized-fuzz_filter-5733944318754816 in 96 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
==1339== 
==1339== HEAP SUMMARY:
==1339==     in use at exit: 21,511,039 bytes in 25 blocks
==1339==   total heap usage: 39 allocs, 14 frees, 21,521,868 bytes allocated
==1339== 
==1339== 288 bytes in 1 blocks are possibly lost in loss record 19 of 25
==1339==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1339==    by 0x40138A4: allocate_dtv (dl-tls.c:322)
==1339==    by 0x40138A4: _dl_allocate_tls (dl-tls.c:539)
==1339==    by 0x514B26E: allocate_stack (allocatestack.c:588)
==1339==    by 0x514B26E: pthread_create@@GLIBC_2.2.5 (pthread_create.c:539)
==1339==    by 0x4740B1: __libcpp_thread_create (__threading_support:328)
==1339==    by 0x4740B1: std::__1::thread::thread<void (&)(fuzzer::Fuzzer*, unsigned long), fuzzer::Fuzzer*&, unsigned long&, void>(void (&)(fuzzer::Fuzzer*, unsigned long), fuzzer::Fuzzer*&, unsigned long&) (thread:368)
==1339==    by 0x46CD97: StartRssThread (FuzzerDriver.cpp:272)
==1339==    by 0x46CD97: fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (FuzzerDriver.cpp:651)
==1339==    by 0x465240: main (in /out/fuzz_filter)
==1339== 
==1339== 10,423 bytes in 1 blocks are definitely lost in loss record 23 of 25
==1339==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1339==    by 0x45DE41: pcap_parse (grammar.c:1952)
==1339==    by 0x432426: pcap_compile (gencode.c:776)
==1339==    by 0x431CEC: LLVMFuzzerTestOneInput (fuzz_filter.c:32)
==1339==    by 0x47FCB5: fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (FuzzerLoop.cpp:570)
==1339==    by 0x465A32: fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (FuzzerDriver.cpp:280)
==1339==    by 0x46D4CB: fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (FuzzerDriver.cpp:713)
==1339==    by 0x465240: main (in /out/fuzz_filter)
==1339== 
==1339== LEAK SUMMARY:
==1339==    definitely lost: 10,423 bytes in 1 blocks
==1339==    indirectly lost: 0 bytes in 0 blocks
==1339==      possibly lost: 288 bytes in 1 blocks
==1339==    still reachable: 21,500,328 bytes in 23 blocks
==1339==         suppressed: 0 bytes in 0 blocks
==1339== Reachable blocks (those to which a pointer was found) are not shown.
==1339== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==1339== 
==1339== For counts of detected and suppressed errors, rerun with: -v
==1339== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
```

**Comment by Dor1s** [comment]
Quickly reading the code, I don't see any free calls for the allocated buffer:

```
# grep -nr yyptr -C 1 /src/libpcap/build/grammar.c
853-        YYSIZE_T yynewbytes;                                            \
854:        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
855:        Stack = &yyptr->Stack_alloc;                                    \
856-        yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
857:        yyptr += yynewbytes / sizeof (*yyptr);                          \
858-      }                                                                 \
--
1950-        yytype_int16 *yyss1 = yyss;
1951:        union yyalloc *yyptr =
1952-          (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
1953:        if (! yyptr)
1954-          goto yyexhaustedlab;
```

**Comment by guyharris** [comment]
> Quickly reading the code, I don't see any free() calls for the allocated buffer

It's a twisty little maze of code.  I *think* it gets freed in the `YYSTACK_FREE (yyss);` call that should be made when the parser returns; the `YYSTACK_RELOCATE` calls end up setting `yyss` to point to the beginning of the allocated block and `yyvs` to point into the middle of the block - the block is allocated to contain both the state stack and the value stack, with `yyss` pointing to the state stack and `yyvs` pointing to the value stack.

The problem appears to be that longjmping out of the parser bypasses the freeing done when the parser returns, so the parser has to do the setjmp and do `YYABORT`, with `pcap_compile()` checking the parser's return value.  (Checked by using one of *my* favorite debugging tools, the "inserted fprintf", reporting allocations and frees in grammar.c, with not all allocations matched by frees.)

(But this would still have taken less time to discover had the generated code been available.)
