### ISSUE TITLE
dictionary and options are not picked up

### ISSUE THREAD

**Issue by dvyukov** [google/oss-fuzz#19]
Created a fuzzer following https://github.com/google/oss-fuzz/blob/master/docs/new_library.md
https://github.com/google/oss-fuzz/pull/18
Docs claim that options and dictionary will be picked up. This does not happen:

```
$ sudo python scripts/helper.py run_fuzzer $LIB_NAME curl_fuzzer
Running: docker run -i -v /usr/local/google/home/dvyukov/src/oss-fuzz/build/out:/out -t ossfuzz/libfuzzer-runner /out/curl/curl_fuzzer
INFO: Seed: 2376061953
INFO: Loaded 0 modules (0 guards): 
INFO: -max_len is not provided, using 64
```

**Comment by mikea** [comment]
@kcc it would be swell if fuzzers supported .options file natively. WDYT?
