### ISSUE TITLE
OSS-FUZZ is stuck retesting one issue before the commit that fixes it.

### ISSUE THREAD

**Issue by guyharris** [google/oss-fuzz#1902]
[Libpcap issue 10931](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10931) should be fixed by the-tcpdump-group/libpcap@71abe040fa49dfcb8ba3e08e5f21896b0c7cc6e8.

However, the oss-fuzz builder seems to keep testing it with revision the-tcpdump-group/libpcap@2954b59a01a2e5f5a3305e900659e9f2807cc875, which is *before* the fix.  I've repeatedly tried the "Check if bug still reproduces" option of "REDO TASK", but it still checks against that revision.

How do I get it to try with the *latest* commit to the-tcpdump-group/libpcap?

**Comment by inferno-chromium** [comment]
We build latest revision only once a day, so you need to wait for tonight and then it will be retried automatically.
