### ISSUE TITLE
Better dashboard

### ISSUE THREAD

**Issue by behdad** [google/oss-fuzz#1903]
I'm not sure if this is the right place to request this.

Currently, I check this URL, changing date every time:
https://oss-fuzz.com/v2/fuzzer-stats/by-day/date-start/2018-10-20/date-end/2018-10-24/fuzzer/afl_harfbuzz_hb-shape-fuzzer

Would be nice if there was a fixed URL that would default to current date and show past 7 days...

Also, better if I could have one URL for both libFuzzer and afl.

Thanks.

**Comment by inferno-chromium** [comment]
@Dor1s has a url with latest, he can give an example.

**Comment by jonathanmetzman** [comment]
@behdad 
If you get rid of the date-start and date-end parts of the link (ie: https://oss-fuzz.com/v2/fuzzer-stats/by-day/fuzzer/afl_harfbuzz_hb-shape-fuzzer) it will show stats from the last 6 days.

**Comment by Dor1s** [comment]
Thanks @jonathanmetzman! And to get the most recent code coverage report available, you can use https://oss-fuzz.com/v2/coverage-report/job/libfuzzer_asan_harfbuzz/latest
