### ISSUE TITLE
OSS-FUZZ appears to be tripping over a GNU libc issue when fuzzing libpcap

### ISSUE THREAD

**Issue by guyharris** [google/oss-fuzz#1910]
In [libpcap issue 11150](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=11150), it reports a use-of-uninitialized-value issue in `send_dg()` in GNU libc 2.23, according to [the stack trace detail](https://oss-fuzz.com/v2/testcase-detail/5754994205130752).

That's somewhat deep in the bowels of the resolver; the only *input* passed to `getnetbyname_r()` is the network name - all other arguments are pointers to areas into which return values are stored, or lengths of those areas, as per [the `getnetent_r()` man page](http://man7.org/linux/man-pages/man3/getnetbyname_r.3.html).

[Libpcap issue 10919](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10919) reports another `getnetbyname_r()` bug, in which it apparently fails to set \**result*, even though the man page explicitly says that it's always set:

> If the function call successfully obtains a network record, then \**result* is set pointing to *result_buf*; otherwise, \**result* is set to NULL.

so I wouldn't trust the GNU libc code path here.

**Comment by kcc** [comment]
It might as well be an msan bug, probably due to missing the `getnetbyname_r` interceptor.
If you can provide a minimized reproducer we may be able to fix the problem quicker.

**Comment by inferno-chromium** [comment]
please file this in sanitizers repo.
