### ISSUE TITLE
Google account requirement for project enrolment

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#1915]
Hello,

It is clear from the documentation that a Google account is needed to enrol a project into oss-fuzz.

> Our ClusterFuzz fuzzing infrastructure and issue tracker require a Google account for authentication. Note that an alternate email address associated with a Google acount does not work due to appengine api limitations.

The xz (#402 and #1892 #1287 ) project is almost ready to be added to oss-fuzz but its maintainer does not intend on creating a Google account. So, is Google's position in this situation wontfix i.e., no alternate arrangements possible?

P.S. It seems [xz is being ~~fuzzed~~ built as a dependency of the imagemagick fuzzer](https://github.com/ImageMagick/ImageMagick/blob/master/Magick%2B%2B/fuzz/build.sh#L11)

Thanks

**Comment by oliverchang** [comment]
If the maintainer does not have a Google account, they will not be able to access most of our dashboards, including access to crash reports and reproducers. If listed in our projet.yaml, they will be still be able to receive email updates on our bug tracker, but may not be able to comment in issues.

In this case I think the only solution is to find some acceptable intermediary who does have a Google account and can forward the testcases and whatever else is required to the maintainer.

**Comment by bshastry** [comment]
> If the maintainer does not have a Google account, they will not be able to access most of our dashboards, including access to crash reports and reproducers. If listed in our projet.yaml, they will be still be able to receive email updates on our bug tracker, but may not be able to comment in issues.
> 
> In this case I think the only solution is to find some acceptable intermediary who does have a Google account and can forward the testcases and whatever else is required to the maintainer.

Thank you @oliverchang . iiuc, inclusion of a non-Google account in project.yaml permits

- viewing bug reports

does not permit

- access to crash reports, test cases etc

I will discuss this with the maintainer.

**Comment by jonathanmetzman** [comment]
Duplicate: #2261
