### ISSUE TITLE
Firebase Authentication

### ISSUE THREAD

**Issue by pdknsk** [google/oss-fuzz#1916]
I don't know if this was already discussed internally at Google, but it seems possible to mostly remove the current Google Account requirement by switching to [Firebase Authentication](https://firebase.google.com/products/auth/).

> It provides an end-to-end identity solution, **supporting email and password accounts**, phone auth, and Google, Twitter, Facebook, and GitHub login, and more.

Supported by App Engine: [Authenticating Users on App Engine Using Firebase](https://cloud.google.com/appengine/docs/standard/python/authenticating-users-firebase-appengine).

And Cloud Storage.
> [Firebase Security Rules](https://firebase.google.com/docs/storage/security/user-security) for Cloud Storage integrates with Firebase Authentication to provide powerful user based authentication to Cloud Storage.

The only missing puzzle piece would then be signing into the bug tracker, I think.

**Comment by inferno-chromium** [comment]
Done!
