### ISSUE TITLE
Support archive formats beyond zip

### ISSUE THREAD

**Issue by htuch** [google/oss-fuzz#1918]
It would be ideal if run_fuzzer and ClusterFuzz can take `.tar` etc. In particular as Bazel projects can easily generate `.tar` directly from the build system.

CC @jonathanmetzman

**Comment by pdknsk** [comment]
I haven't yet tried but [it's supposed to work already](https://github.com/google/oss-fuzz/issues/1217).

**Comment by inferno-chromium** [comment]
yes it should just work, see https://github.com/google/clusterfuzz/blob/master/src/python/system/archive.py#L25
