### ISSUE TITLE
Split uploaded artifacts

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#192]
We are looking at build configuration explosion (#59, #60, #128, #191). I suggest that we split our uploaded artificats into code/non-code and upload non-code only once.

E.g. ffmpeg build will produce:

* `ffmpeg-libfuzzer-address-timestamp.zip`, `ffmpeg-afl-undefine-timestamp.zip` with only fuzzer binaries inside.
* `ffmpeg-data-timestamp.zip` - the rest of files from `/out` output that will be extracted during run
* (maybe) `ffmpeg-seeds-timestamp.zip` - seed copruses for fuzzers. There are not expected to be readable by fuzzer binary

**Comment by oliverchang** [comment]
this sgtm

**Comment by inferno-chromium** [comment]
Lets do the split once ClusterFuzz side things are ready to pick this up. Please sync with @oliverchang, he will be on vacation starting next week.

**Comment by inferno-chromium** [comment]
Not needed.
