### ISSUE TITLE
Add per-project HTML anchors to https://oss-fuzz.com/v2

### ISSUE THREAD

**Issue by behdad** [google/oss-fuzz#1944]
Such that one can bookmark https://oss-fuzz.com/v2#harfbuzz for example.

**Comment by jonathanmetzman** [comment]
Will take a look at this.

**Comment by jonathanmetzman** [comment]
Unfortunately, this doesn't "just work" in polymer like it does regular HTML. 
I don't really have the cycles to figure out how to do this right now.
