### ISSUE TITLE
openssl does not build with ubsan

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#195]
https://oss-fuzz-build-logs.storage.googleapis.com/build_logs/openssl/latest.txt

@mikea, @kroeckx - any idea why ?

coverage=edge,indirect-calls,8bit-counters -fno-sanitize=alignment -o fuzz/bndiv-test fuzz/bndiv.o fuzz/test-corpus.o -L. -lcrypto -ldl /usr/local/lib/libc++.a
../../usr/lib/libFuzzingEngine.a(FuzzerIO.o): In function `basic_ifstream':
/usr/local/bin/../include/c++/v1/fstream:1067: undefined reference to `__ubsan_vptr_type_cache'
/usr/local/bin/../include/c++/v1/fstream:1067: undefined reference to `__ubsan_handle_dynamic_type_cache_miss_abort'
../../usr/lib/libFuzzingEngine.a(FuzzerIO.o): In function `basic_istream':
/usr/local/bin/../include/c++/v1/istream:189: undefined reference to `__ubsan_vptr_type_cache'
/usr/local/bin/../include/c++/v1/istream:189: undefined reference to `__ubsan_handle_dynamic_type_cache_miss_abort'
/usr/local/bin/../include/c++/v1/istream:189: undefined reference to `__ubsan_vptr_type_cache'
/usr/local/bin/../include/c++/v1/istream:189: undefined reference to `__ubsan_handle_dynamic_type_cache_miss_abort'
../../usr/lib/libFuzzingEngine.a(FuzzerIO.o): In function `std::__1::basic_ios<char, std::__1::char_traits<char> >::init(std::__1::basic_streambuf<char, std::__1::char_traits<char> >*)':
/usr/local/bin/../include/c++/v1/ios:673: undefined reference to `__ubsan_vptr_type_cache'
/usr/local/bin/../include/c++/v1/ios:673: undefined reference to `__ubsan_handle_dynamic_type_cache_miss_abort'
/usr/local/bin/../include/c++/v1/ios:674: undefined reference to `__ubsan_vptr_type_cache'
/usr/local/bin/../include/c++/v1/ios:674: undefined reference to `__ubsan_handle_dynamic_type_cache_miss_abort'
/usr/local/bin/../include/c++/v1/ios:675: undefined reference to `__ubsan_vptr_type_cache'
/usr/local/bin/../include/c++/v1/ios:675: undefined reference to `__ubsan_handle_dynamic_type_cache_miss_abort'
../../usr/lib/libFuzzingEngine.a(FuzzerIO.o): In function `basic_ifstream':
/usr/local/bin/../include/c++/v1/fstream:1069: undefined reference to `__ubsan_vptr_type_cache'
/usr/local/bin/../include/c++/v1/fstream:1069: undefined reference to `__ubsan_handle_dynamic_type_cache_miss_abort'
/usr/local/bin/../include/c++/v1/fstream:1069: undefined reference to `__ubsan_vptr_type_cache'
/usr/local/bin/../include/c++/v1/fstream:1069: undefined reference to `__ubsan_handle_dynamic_type_cache_miss_abort'

**Comment by kcc** [comment]
The linker command should have the same -fsanitize=* as the compiler command. 
Does it?

**Comment by kroeckx** [comment]
I currently don't see what's wrong with the calling it, all arguments that should be there seem to be there.

**Comment by kroeckx** [comment]
So what I'm confused about is that it's all undefined references it's showing are for libFuzzingEngine.a, and I didn't expect that to get build with ubsan.

**Comment by mikea** [comment]
The root cause of this issue is openssl using `clang` (not `clang++`) to link the fuzzer. libFuzzingEngine.a is a C++ program and additional ubsan c++ runtime libraries have to be linked in. `clang++` usually takes care of this. We were able to overcome the issue by specifying `libc++` manually. (https://github.com/google/oss-fuzz/blob/master/projects/openssl/build.sh#L19) This list has to be expanded for undefined sanitizer. 

I'll try to fix it on our side, but the proper fix would be to make openssl use clang++ for linking.

**Comment by kroeckx** [comment]
Thanks for fixing that.

I'd like to get rid of that hack. I remember having issues when we actually tried to use clang++, but I don't remember what exactly.

**Comment by mikea** [comment]
Can you create a variable to override the linker? Would be easy to try `LD=clang++ make` then.

**Comment by kroeckx** [comment]
LDCMD does that

**Comment by kroeckx** [comment]
I've been thinking about moving that libc++.a thing to the EX_LIBS, or maybe $FUZZER_LDFLAGS should get added to it? But I didn't try to set up a working test environment yet.

**Comment by kroeckx** [comment]
Maybe it's easier to use PLIB_LDFLAGS instead of EX_LIBS, that should be default empty.

**Comment by mikea** [comment]
I want to remove FUZZER_LDFLAGS. They don't seem to be needed.

BTW #198 seems to work fine for both sanitizers.
