### ISSUE TITLE
Skip missing files when generating coverage for bazel projects.

### ISSUE THREAD

**Issue by htuch** [google/oss-fuzz#1955]
Envoy coverage still hits:

```
[2018-11-14 18:29:48,492 DEBUG] Finished generating per-file code coverage summary.
[2018-11-14 18:29:48,492 DEBUG] Generating file view html index file as: "/out/report/linux/file_view_index.html".
Traceback (most recent call last):
  File "/opt/code_coverage/coverage_utils.py", line 824, in <module>
    sys.exit(Main())
  File "/opt/code_coverage/coverage_utils.py", line 818, in Main
    return _CmdPostProcess(args)
  File "/opt/code_coverage/coverage_utils.py", line 775, in _CmdPostProcess
    processor.PrepareHtmlReport()
  File "/opt/code_coverage/coverage_utils.py", line 574, in PrepareHtmlReport
    self.file_view_path)
  File "/opt/code_coverage/coverage_utils.py", line 446, in GenerateFileViewHtmlIndexFile
    self.GetCoverageHtmlReportPathForFile(file_path),
  File "/opt/code_coverage/coverage_utils.py", line 426, in GetCoverageHtmlReportPathForFile
    self._MapToLocal(file_path)), '"%s" is not a file.' % file_path
AssertionError: "/root/.cache/bazel/_bazel_root/4e9824db8e7d11820cfa25090ed4ed10/external/envoy_deps_cache_b22e04bff96538ea37e715942da6315c/nghttp2.dep.build/nghttp2-1.34.0/lib/nghttp2_outbound_item.c" is not a file.
Failed to generate clang code coverage report.
[1]    199761 exit 1     python infra/helper.py coverage envoy
```

This is largely because of some changes to the way Bazel treats external repos. Can we have a softer fail during coverage generation, where we just skip these missing files?

@Dor1s

**Comment by Dor1s** [comment]
@htuch looks like the coverage job for Envoy has recovered on Nov 15th. But if I understand correctly, the issue occurs from time to time? If so, I think I can do the following:
* add a flag to the coverage scripts (like `--ignore-missing-file` or smth like this)
* add a way to opt-in for using that flag via project.yaml or smth similar

@oliverchang I remember you didn't like when I did https://github.com/google/oss-fuzz/blob/master/projects/envoy/project.yaml#L9

Do you think we should have one more .yaml file for runtime configuration? What else we can put in there besides coverage options? //cc @jonathanmetzman -- any AFL specific cases? env variables?

**Comment by htuch** [comment]
@Dor1s yeah, not sure why, maybe some in Bazel itself? I'm going to be poking at the coverage data shortly, so will let you know if it is not looking right.

I'd take any option to have it gracefully handle missing files TBH; the main issue for us is the external dependencies of Envoy. Some of these coverage does matter for, others it doesn't. We're willing to take best effort and manual shepherding of the former category over ongoing Bazel hacking :)

**Comment by oliverchang** [comment]
> add a flag to the coverage scripts (like --ignore-missing-file or smth like this)

Maybe we can just make this default? And add warnings when we encounter such cases? Possibly also some threshold to hard fail if too many files don't exist. 

The less configuration options we have, the better.

**Comment by Dor1s** [comment]
Yeah, make it a default would be better, but I don't want us to blindly miss any valid failures. A threshold could help here, but it can be anything depending on the project size, e.g. in one case it's ok to miss 100 files from a third party dependency, while in another case the whole project is just 50 files and we should fail hard here.

Need to think more. Adding yet another configuration option is not good at all, I agree.

**Comment by Dor1s** [comment]
Btw, @htuch, looks like the error in the initial issue description was from a local run, right?

I've just checked 9 last failures on the buildbot and 1 of them was compilation failure and 8 were `rsync` failures.

I believe that https://github.com/google/oss-fuzz/blob/master/projects/envoy/project.yaml#L9 should take care of those missing files and we should not see any issues with that. Maybe `coverage_extra_args` doesn't work well when running locally and that's what I should fix?

**Comment by oliverchang** [comment]
Let's avoid this dependency on having the project.yaml if we can. Having the bash script for now sgtm.
