### ISSUE TITLE
Fuzzing the JIT compiler of V8

### ISSUE THREAD

**Issue by pratikbhd** [google/oss-fuzz#1956]
Hello,
I am currently working on a project that involves fuzzing JIT compilers. I am looking into libFuzzer and was trying to figure out how I can use libFuzzer to fuzz the JIT compiler engines of V8. I found several tutorials online related to libFuzzers but none that talked about integrating it with V8 and JIT compilers in specific.

I was wondering if there are any resources I can look into to understand how I can use **libFuzzer** (or any other fuzzer such as **oss-fuzz** or **jfs**) to fuzz the JIT compilers of V8.

Thanks!

**Comment by jonathanmetzman** [comment]
oss-fuzz is not a fuzzer that you can use locally.

It uses AFL or libFuzzer which you can use locally to fuzz v8.
There are bunch of libFuzzer targets for v8 in the [chrome source](https://cs.chromium.org/search/?q=v8+fuzzer&sq=package:chromium&type=cs) and there is documentation on how to build them [here](https://chromium.googlesource.com/chromium/src/+/master/testing/libfuzzer/README.md)
