### ISSUE TITLE
Can't reproduce build failure for Git

### ISSUE THREAD

**Issue by steadmon** [google/oss-fuzz#1959]
I've been getting notifications about build failures for the Git fuzzers:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=11385

However, I haven't been able to reproduce the build issues. Part of the difficulty is that the build logs don't list the command that's being run, so I'm left to guess about which build options are being used. From the error messages, it appears that it's failing for the honggfuzz engine, so I've been using that to try to reproduce the failure. However, check_build tells me there are no issues:

$ python infra/helper.py build_image git
[output snipped]
$ python infra/helper.py build_fuzzers --sanitizer address --engine hongfuzz git
[output snipped]
$ python infra/helper.py check_build  --sanitizer address --engine honggfuzz git fuzz-pack-idx
Running: docker run --rm -i --privileged -e FUZZING_ENGINE=honggfuzz -e SANITIZER=address -v /usr/local/google/home/steadmon/src/oss-fuzz/build/out/git:/out -t gcr.io/oss-fuzz-base/base-runner bad_build_check /out/fuzz-pack-idx
Check build passed.

From the build logs, it looks like something is trying to unzip a seed corpus archive using an incorrect name:

Step #5: [/corpus/fuzz-pack-headers.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/fuzz-pack-headers.zip or
Step #5:         /corpus/fuzz-pack-headers.zip.zip, and cannot find /corpus/fuzz-pack-headers.zip.ZIP, period.

It seems that it's trying to unzip a file named fuzz-pack-headers.zip, but according to OSS-Fuzz documentation, the file should be named fuzz-pack-headers_seed_corpus.zip

**Comment by inferno-chromium** [comment]
ah, this is the coverage build.

@Dor1s - can you add the coverage build instructions on https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md#reproducing-build-failures. i think people need to know which type of build it is and use that for reproduction.

**Comment by Dor1s** [comment]
Sure. Line #3 in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=11385 says that it's a coverage build:

```
Build type: coverage
```

And I've just updated https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md in https://github.com/google/oss-fuzz/commit/76686d085bd59b5ba39de1940792c074caecef08

@steadmon thanks for reporting this and please let us know if you run into any other issues!

**Comment by steadmon** [comment]
I am afraid that I am still unable to reproduce this build failure locally. check_build reports no issues with --sanitizer=coverage, and I am able to generate a coverage report locally. Is there any way to get more details on exactly how the failed build was run?

**Comment by Dor1s** [comment]
That's weird. Thanks for checking. I'll take a closer look later.

**Comment by Dor1s** [comment]
Looks like the build has recovered, exactly two days ago when @steadmon could not reproduce the failure locally.
