### ISSUE TITLE
Analysis of fuzzer logs and updating dictionary, performance issues

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#196]
As discussed over chat,

we will run a midnight analysis job that analyzes fuzzers logs from previous day and then updates dictionary recommendations on a gcs file, also analyzes for performance issues like too much logging, etc and then updated dictionary is used during fuzzing, and performance issues are reported in the fuzzer stats page.

**Comment by inferno-chromium** [comment]
Before i forget, @Dor1s i had 2 more ideas for performance analyzer

1. Detect if a fuzzer crashed prematurely.
2. Detect if seed corpus has crashy input and crashes prematurely on that.

**Comment by Dor1s** [comment]
Recommended dictionary stuff has been deployed. Looking forward to see whether it affects coverage and other stats or not :)

**Comment by inferno-chromium** [comment]
Some dictionaries are 0 sizes, we should skip creating these.
https://pantheon.corp.google.com/storage/browser/libteken-logs.clusterfuzz-external.appspot.com/dictionaries/libFuzzer_libteken_fuzzer/?project=clusterfuzz-external
https://pantheon.corp.google.com/storage/browser/pcre2-logs.clusterfuzz-external.appspot.com/dictionaries/libFuzzer_pcre2_fuzzer/?project=clusterfuzz-external

**Comment by inferno-chromium** [comment]
More ideas for performance analyzer
- Detect if the fuzzer is behaving randomly [maybe uses random seed somewhere, either in target function or inside source] or if it is generating lots of unreproducible inputs (e.g. file fuzzer is doing this right now). [@kcc - any ideas for detecting this]

**Comment by Dor1s** [comment]
Regarding 0 size, I think these are leftovers from previous implementation and/or testing runs. Current version shouldn't create empty files. 

I'll go through all these leftovers and delete them. Thanks for catching!

**Comment by inferno-chromium** [comment]
Dont worry about deleting then, we will anyway move to its own dedicated bucket for dictionaries.

**Comment by inferno-chromium** [comment]
@Dor1s  - Startup crashes seems to be most important to detect for performance analyzer.
@oliverchang - just as fyi, see also #283

**Comment by Dor1s** [comment]
Looks like we may close this issue, as LogsAnalysis task has been landed.
- Recommended dictionary is being used for 50% runs at the moment
- Performance analysis now detects startup crashes among other issues, but doesn't use BigQuery. We'll have a major update later (I'll share the design doc, there are some points to brainstorm)
