### ISSUE TITLE
[open62541] Issues wrongly verified as fixed

### ISSUE THREAD

**Issue by Pro** [google/oss-fuzz#1968]
I implemented our own memory manager as mentioned in #1675 

Basically, we are taking the last 4 bytes of the fuzzer input, cast it to unsigned int `memoryLimit` bytes, and take that value as the available RAM. We have overrridden malloc and free so that we can keep track of the allocated memory and return NULL if we are allocating results in more than `memoryLimit` RAM usage.

This was merged into master on 2018-11-17 and the fuzzer found some new issues:

https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=label%3AProj-open62541+opened%3E2018%2F11%2F1&colspec=ID+Type+Component+Status+Proj+Reported+Owner+Summary&cells=ids

Unfortunately we now have the problem that the issues are verified as fixed and closed on the next day without really being fixed in our master branch. I can even reproduce "fixed" issues if I take the reproduce testcase as an input on the current master branch.

How is oss-fuzz verifying the issues? Is it taking different fuzzer inputs for opening the bug and then verifying it?

**Comment by inferno-chromium** [comment]
It verifies using the same exact testcase that was used to find the crash on older revision. I see the following commits in fixed range list - https://github.com/open62541/open62541/compare/762712d5377fc2f1236ea9056c2dcbd82f12864f...56bb742e2ba12c9f2453d27b158aaa5b6a97141a. could these cls have caused this to stop reproducing. Variants of those testcases are now coming back (as part of fuzzing), e.g. https://oss-fuzz.com/testcase-detail/5713564380168192 and those will get filed as new bugs are 2 days (we have a 2 day throttle on same exact crash signature).

**Comment by inferno-chromium** [comment]
Closing, my last comment should answer this.
