### ISSUE TITLE
GraphicsMagick  convert +dither does not work as expected

### ISSUE THREAD

**Issue by zirneklitis** [google/oss-fuzz#1979]
“+dither” option does not suspend dithering. The command:
`for attels in *.tif; do gm convert -depth 8 -fuzz 10%  +dither  $attels  -colors 63 +dither -map colours.png -quality 100  $attels.png ;  done
`
generates an image with dithered colours.

_The source image:_
[Source.zip](https://github.com/google/oss-fuzz/files/2617420/Source.zip)

_The palette (colour map) file:_
![colours](https://user-images.githubusercontent.com/3538610/49043906-f7f21b80-f1d4-11e8-8b1c-dfcbafe7e2fe.png)

_The expected result:_
![expected_result](https://user-images.githubusercontent.com/3538610/49043908-f7f21b80-f1d4-11e8-945e-f64823b109e4.png)

_The actual result:_
![result](https://user-images.githubusercontent.com/3538610/49043909-f7f21b80-f1d4-11e8-9887-18df76287b1d.png)

**Comment by Dor1s** [comment]
Are you sure you've reported the issue to the right project? @dlemstra @alex @reaperhulk

**Comment by alex** [comment]
Yeah, this is the wrong place for bugs in graphicsmagick. The bug tracker for GM is here: https://sourceforge.net/p/graphicsmagick/_list/tickets

**Comment by Dor1s** [comment]
Thanks @alex !
