### ISSUE TITLE
glib project assertion failures not parsed properly

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1981]
@pdknsk - why did we close_fd_mask=2 on glib project. this is causing asserts to be not discovered and everything getting clubbed into the general https://oss-fuzz.com/testcase-detail/5702619287781376 ?

**Comment by pdknsk** [comment]
I [removed the options file](https://github.com/google/oss-fuzz/pull/1866/commits/39f7460488088e2d64fc1f91dd0ad8049bf7a684) when I integrated into its build system. The targets disable non-asserts logging internally now. So this shouldn't be happening. If it does, that's probably an `oss-fuzz` bug. I'm thinking of stale options or the like.

**Comment by pdknsk** [comment]
I verified locally again that logging for the targets is working as expected.
```
GLib:ERROR:../../src/glib/glib/gvariant-parser.c:1560:unicode_unescape: assertion failed: (value <= G_MAXUINT32)
AddressSanitizer:DEADLYSIGNAL
```

**Comment by inferno-chromium** [comment]
This is a regex issue on our side, making it more generic. Sorry i was looking at a old testcase, where -close_fd_mask argument is stored. new upload https://oss-fuzz.com/testcase-detail/5744988441280512 shows that assertion is there but we are not parsing properly.

**Comment by pdknsk** [comment]
It appears from [this bug](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9804) being marked flaky, and also [this fix](https://gitlab.gnome.org/GNOME/glib/merge_requests/511), that the issue is resolved.
