### ISSUE TITLE
A fuzzer that has just landed passed all the checks and then failed anyway with fuzzer::Fuzzer::ExecuteCallback(const uint8_t *, size_t): Assertion `Res == 0' failed

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#1983]
ClusterFuzz has just opened https://oss-fuzz.com/testcase?key=5642013043589120 and I think there are actually two issues there.

The first one is that it isn't clear that LLVMFuzzerTestOneInput can return only 0. This was briefly discussed in https://github.com/google/oss-fuzz/issues/1327, where I found a link to http://llvm.org/docs/LibFuzzer.html#id22, but, "Non-zero return values are reserved for future use" doesn't seem to be the same as "your fuzzer will crash if a non-zero value is returned". I'll fix the fuzzer so that it'll always return 0 if `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` is defined, but it'd be great to update the documentation too.

The second issue is more interesting. The fuzzer returns 77 when [it can't setup a mount namespace](https://github.com/systemd/systemd/blob/de38f06f52fb172c60485376b8648d7208bb5a90/src/fuzz/fuzz-udev-rules.c#L30-L45):
```c
static int setup_mount_namespace(void) {
        static thread_local bool is_namespaced = false;


        if (is_namespaced)
                return 1;


        if (unshare(CLONE_NEWNS) < 0)
                return log_error_errno(errno, "Failed to call unshare(): %m");


        if (mount(NULL, "/", NULL, MS_SLAVE|MS_REC, NULL) < 0)
                return log_error_errno(errno, "Failed to mount / as private: %m");


        is_namespaced = true;


        return 1;
}
```
Why was this not detected during the build checks? Is there some kind of security policy (or seccomp filters) in place that prevents `unshare`/`remount`?

**Comment by evverx** [comment]
Would it be possible to run a slightly modified version of the fuzzer from https://github.com/systemd/systemd/pull/10952 on ClusterFuzz to see how it goes? If it hits the assertion at https://github.com/systemd/systemd/pull/10952/files#diff-85f1bd77e917aee1f469b63334535b9cR83 there, it means that the environment is too restricted and I should probably find another place to run it :-)

**Comment by inferno-chromium** [comment]
@oliverchang - any idea on these issues, esp the mount namespace issue. i think minijail should be restricted and might not allow this right ?

**Comment by evverx** [comment]
> i think minijail should be restricted and might not allow this right ?

If this is the case, I think it'd be useful to mention in https://github.com/google/oss-fuzz/blob/master/docs/fuzzer_environment.md what "some security restrictions" are. It'd be even better if `infra/helper.py` could somehow mimic the environment created by minijail so that it wouldn't be necessary to wait for one day for fuzzer to be run in "production" and, as in my case, for another day to just check whether `mount` is allowed there.

**Comment by oliverchang** [comment]
Yes, I believe minijail is the cause of the second issue.

There is a script which somewhat emulates the minijail environment: https://github.com/google/oss-fuzz/blob/3740c751fd9edea138c17783995d370d6b1b89bc/infra/base-images/base-runner/run_minijail

However, we are going to be getting rid of minijail in the next few months, so this issue should hopefully go away.

**Comment by evverx** [comment]
@oliverchang thank you for the pointer! I've just run the fuzzer with `run_minijail` and it's very obvious now that `unshare` and `mount` are not allowed. I also played with `bash` there and it seems that `/run`, `/etc` and `/sys` don't exist there. Is it safe to assume that the same happens on ClusterFuzz? Locally I can create the required layout manually, that is, it's possible for me to have `/etc/udev/rules.d` I can write to. Can I do the same on ClusterFuzz?

**Comment by evverx** [comment]
I've updated the fuzzers so now it should work on "normal" machines, in docker containers, on Travis CI and in the environment created by run_minijail. I hope it will be enough for ClusterFuzz.

**Comment by oliverchang** [comment]
> Is it safe to assume that the same happens on ClusterFuzz? Locally I can create the required layout manually, that is, it's possible for me to have /etc/udev/rules.d I can write to. Can I do the same on ClusterFuzz?

This will likely work. However, when minijail is removed in the near future, you may lose write access to / so that may break again in the future. On the other hand, it will be closer to a "normal" machine so I guess your solution in https://github.com/evverx/systemd/commit/fa6e5861f77d621b5a23fa9758b8ade47b0b3c0e will continue to work.

Sorry for the trouble with minijail, and thanks for addressing the issue! Let's confirm that it works on ClusterFuzz in a day or so.

**Comment by evverx** [comment]
The fuzzer will crash if `mkdir_p("/etc/udev/rules.d")` doesn't succeed due to a strategically placed `assert_se`, but it will only happen if `/tmp` isn't writable and `mount` isn't allowed, which, if I understand correctly, is unlikely to happen even after `minijail` is removed. The ancient craft of adding kludges is safe with me :-)

**Comment by evverx** [comment]
https://oss-fuzz.com/testcase?key=5642013043589120 has been closed. With 9aa11dbd251f393eee0e merged and https://github.com/google/oss-fuzz/pull/1986 pending I think there is nothing left to do here because, as far as I can tell, technically, the libfuzzer documentation isn't part of the OSS-Fuzz project.
