### ISSUE TITLE
Fuzz PHP

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1984]
PHP is getting many memory corruption reports found by people running AFL and (perhaps) other tools: https://hackerone.com/ibb-php/hacktivity?sort_type=latest_disclosable_activity_at&filter=type%3Aall%20to%3Aibb-php&text_query=&page=1

It would be a great benefit for PHP and its users if PHP could integrate with OSS-Fuzz. OSS-Fuzz is a free continuous fuzzing service which does not only find bugs, but also automatically reports them, verifies the fixes, and does bunch of other things.

The integration process is very easy, just follow https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md

@m6w6 @nikic @johannes @KalleZ would you be interested in that? Could you please @mention more developers here who might be interested?

We also issue monetary rewards for projects who integrate with OSS-Fuzz. Please see https://opensource.googleblog.com/2017/05/oss-fuzz-five-months-later-and.html for more info on that.

**Comment by johannes** [comment]
I am not very active in the PHP Community at the moment and suggest to involve security at php net. In general I think fuzzing is something interesting. A year ago I did some experiments with clang's libFuzzing, maybe it's useful to build upon. I pushed the code, which I haven't touched or tested for a year to https://github.com/johannes/php-fuzzing-sapi

**Comment by smalyshev** [comment]
Trying to build it, I get the build running almost to the end and then I get this:

```
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(FuzzerDriver.o): In function `append':
/usr/local/bin/../include/c++/v1/string:2547: undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*, unsigned long)'
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(FuzzerDriver.o): In function `__init':
/usr/local/bin/../include/c++/v1/string:1783: undefined reference to `std::__1::__basic_string_common<true>::__throw_length_error() const'
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(FuzzerDriver.o): In function `fuzzer::CleanseCrashInput(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, fuzzer::FuzzingOptions const&)':
/src/libfuzzer/FuzzerDriver.cpp:317: undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(FuzzerDriver.o): In function `operator==<char, std::__1::char_traits<char>, std::__1::allocator<char> >':
```
and about 9000 instances of the same. The build command looks like this:
```
/bin/bash /src/php-src/libtool --silent --preserve-dup-deps --mode=link clang++ -export-dynamic -std=c++11 -I/usr/include -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -fvisibility=hidden -fsanitize-coverage=edge -fsanitize=address -DZEND_SIGNALS      ext/date/php_date.lo ext/date/lib/astro.lo ext/date/lib/dow.lo ext/date/lib/parse_date.lo ext/date/lib/parse_tz.lo ext/date/lib/timelib.lo ext/date/lib/tm2unixtime.lo ext/date/lib/unixtime2tm.lo ext/date/lib/parse_iso_intervals.lo ext/date/lib/interval.lo ext/libxml/libxml.lo ext/pcre/pcrelib/pcre_chartables.lo ext/pcre/pcrelib/pcre_ucd.lo ext/pcre/pcrelib/pcre_compile.lo ext/pcre/pcrelib/pcre_config.lo ext/pcre/pcrelib/pcre_exec.lo ext/pcre/pcrelib/pcre_fullinfo.lo ext/pcre/pcrelib/pcre_get.lo ext/pcre/pcrelib/pcre_globals.lo ext/pcre/pcrelib/pcre_maketables.lo ext/pcre/pcrelib/pcre_newline.lo ext/pcre/pcrelib/pcre_ord2utf8.lo ext/pcre/pcrelib/pcre_refcount.lo ext/pcre/pcrelib/pcre_study.lo ext/pcre/pcrelib/pcre_tables.lo ext/pcre/pcrelib/pcre_valid_utf8.lo ext/pcre/pcrelib/pcre_version.lo ext/pcre/pcrelib/pcre_xclass.lo ext/pcre/pcrelib/pcre_jit_compile.lo ext/pcre/php_pcre.lo ext/sqlite3/sqlite3.lo ext/sqlite3/libsqlite/sqlite3.lo ext/ctype/ctype.lo ext/dom/php_dom.lo ext/dom/attr.lo ext/dom/document.lo ext/dom/domerrorhandler.lo ext/dom/domstringlist.lo ext/dom/domexception.lo ext/dom/namelist.lo ext/dom/processinginstruction.lo ext/dom/cdatasection.lo ext/dom/documentfragment.lo ext/dom/domimplementation.lo ext/dom/element.lo ext/dom/node.lo ext/dom/string_extend.lo ext/dom/characterdata.lo ext/dom/documenttype.lo ext/dom/domimplementationlist.lo ext/dom/entity.lo ext/dom/nodelist.lo ext/dom/text.lo ext/dom/comment.lo ext/dom/domconfiguration.lo ext/dom/domimplementationsource.lo ext/dom/entityreference.lo ext/dom/notation.lo ext/dom/xpath.lo ext/dom/dom_iterators.lo ext/dom/typeinfo.lo ext/dom/domerror.lo ext/dom/domlocator.lo ext/dom/namednodemap.lo ext/dom/userdatahandler.lo ext/fileinfo/fileinfo.lo ext/fileinfo/libmagic/apprentice.lo ext/fileinfo/libmagic/apptype.lo ext/fileinfo/libmagic/ascmagic.lo ext/fileinfo/libmagic/cdf.lo ext/fileinfo/libmagic/cdf_time.lo ext/fileinfo/libmagic/compress.lo ext/fileinfo/libmagic/encoding.lo ext/fileinfo/libmagic/fsmagic.lo ext/fileinfo/libmagic/funcs.lo ext/fileinfo/libmagic/is_tar.lo ext/fileinfo/libmagic/magic.lo ext/fileinfo/libmagic/print.lo ext/fileinfo/libmagic/readcdf.lo ext/fileinfo/libmagic/softmagic.lo ext/fileinfo/libmagic/strcasestr.lo ext/filter/filter.lo ext/filter/sanitizing_filters.lo ext/filter/logical_filters.lo ext/filter/callback_filter.lo ext/hash/hash.lo ext/hash/hash_md.lo ext/hash/hash_sha.lo ext/hash/hash_ripemd.lo ext/hash/hash_haval.lo ext/hash/hash_tiger.lo ext/hash/hash_gost.lo ext/hash/hash_snefru.lo ext/hash/hash_whirlpool.lo ext/hash/hash_adler32.lo ext/hash/hash_crc32.lo ext/hash/hash_fnv.lo ext/hash/hash_joaat.lo ext/hash/hash_sha3.lo ext/iconv/iconv.lo ext/json/json.lo ext/json/json_encoder.lo ext/json/json_parser.lo ext/json/json_scanner.lo ext/pdo/pdo.lo ext/pdo/pdo_dbh.lo ext/pdo/pdo_stmt.lo ext/pdo/pdo_sql_parser.lo ext/pdo/pdo_sqlstate.lo ext/pdo_sqlite/pdo_sqlite.lo ext/pdo_sqlite/sqlite_driver.lo ext/pdo_sqlite/sqlite_statement.lo ext/phar/util.lo ext/phar/tar.lo ext/phar/zip.lo ext/phar/stream.lo ext/phar/func_interceptors.lo ext/phar/dirstream.lo ext/phar/phar.lo ext/phar/phar_object.lo ext/phar/phar_path_check.lo ext/posix/posix.lo ext/reflection/php_reflection.lo ext/session/mod_user_class.lo ext/session/session.lo ext/session/mod_files.lo ext/session/mod_mm.lo ext/session/mod_user.lo ext/simplexml/simplexml.lo ext/simplexml/sxe.lo ext/spl/php_spl.lo ext/spl/spl_functions.lo ext/spl/spl_engine.lo ext/spl/spl_iterators.lo ext/spl/spl_array.lo ext/spl/spl_directory.lo ext/spl/spl_exceptions.lo ext/spl/spl_observer.lo ext/spl/spl_dllist.lo ext/spl/spl_heap.lo ext/spl/spl_fixedarray.lo ext/standard/crypt_freesec.lo ext/standard/crypt_blowfish.lo ext/standard/crypt_sha512.lo ext/standard/crypt_sha256.lo ext/standard/php_crypt_r.lo ext/standard/array.lo ext/standard/base64.lo ext/standard/basic_functions.lo ext/standard/browscap.lo ext/standard/crc32.lo ext/standard/crypt.lo ext/standard/cyr_convert.lo ext/standard/datetime.lo ext/standard/dir.lo ext/standard/dl.lo ext/standard/dns.lo ext/standard/exec.lo ext/standard/file.lo ext/standard/filestat.lo ext/standard/flock_compat.lo ext/standard/formatted_print.lo ext/standard/fsock.lo ext/standard/head.lo ext/standard/html.lo ext/standard/image.lo ext/standard/info.lo ext/standard/iptc.lo ext/standard/lcg.lo ext/standard/link.lo ext/standard/mail.lo ext/standard/math.lo ext/standard/md5.lo ext/standard/metaphone.lo ext/standard/microtime.lo ext/standard/pack.lo ext/standard/pageinfo.lo ext/standard/quot_print.lo ext/standard/rand.lo ext/standard/mt_rand.lo ext/standard/soundex.lo ext/standard/string.lo ext/standard/scanf.lo ext/standard/syslog.lo ext/standard/type.lo ext/standard/uniqid.lo ext/standard/url.lo ext/standard/var.lo ext/standard/versioning.lo ext/standard/assert.lo ext/standard/strnatcmp.lo ext/standard/levenshtein.lo ext/standard/incomplete_class.lo ext/standard/url_scanner_ex.lo ext/standard/ftp_fopen_wrapper.lo ext/standard/http_fopen_wrapper.lo ext/standard/php_fopen_wrapper.lo ext/standard/credits.lo ext/standard/css.lo ext/standard/var_unserializer.lo ext/standard/ftok.lo ext/standard/sha1.lo ext/standard/user_filters.lo ext/standard/uuencode.lo ext/standard/filters.lo ext/standard/proc_open.lo ext/standard/streamsfuncs.lo ext/standard/http.lo ext/standard/password.lo ext/standard/random.lo ext/tokenizer/tokenizer.lo ext/tokenizer/tokenizer_data.lo ext/xml/xml.lo ext/xml/compat.lo ext/xmlreader/php_xmlreader.lo ext/xmlwriter/php_xmlwriter.lo TSRM/TSRM.lo TSRM/tsrm_strtok_r.lo main/main.lo main/snprintf.lo main/spprintf.lo main/php_sprintf.lo main/fopen_wrappers.lo main/alloca.lo main/php_scandir.lo main/php_ini.lo main/SAPI.lo main/rfc1867.lo main/php_content_types.lo main/strlcpy.lo main/strlcat.lo main/mergesort.lo main/reentrancy.lo main/php_variables.lo main/php_ticks.lo main/network.lo main/php_open_temporary_file.lo main/output.lo main/getopt.lo main/streams/streams.lo main/streams/cast.lo main/streams/memory.lo main/streams/filter.lo main/streams/plain_wrapper.lo main/streams/userspace.lo main/streams/transports.lo main/streams/xp_socket.lo main/streams/mmap.lo main/streams/glob_wrapper.lo Zend/zend_language_parser.lo Zend/zend_language_scanner.lo Zend/zend_ini_parser.lo Zend/zend_ini_scanner.lo Zend/zend_alloc.lo Zend/zend_compile.lo Zend/zend_constants.lo Zend/zend_dtrace.lo Zend/zend_execute_API.lo Zend/zend_highlight.lo Zend/zend_llist.lo Zend/zend_vm_opcodes.lo Zend/zend_opcode.lo Zend/zend_operators.lo Zend/zend_ptr_stack.lo Zend/zend_stack.lo Zend/zend_variables.lo Zend/zend.lo Zend/zend_API.lo Zend/zend_extensions.lo Zend/zend_hash.lo Zend/zend_list.lo Zend/zend_builtin_functions.lo Zend/zend_sprintf.lo Zend/zend_ini.lo Zend/zend_sort.lo Zend/zend_multibyte.lo Zend/zend_ts_hash.lo Zend/zend_stream.lo Zend/zend_iterators.lo Zend/zend_interfaces.lo Zend/zend_exceptions.lo Zend/zend_strtod.lo Zend/zend_gc.lo Zend/zend_closures.lo Zend/zend_float.lo Zend/zend_string.lo Zend/zend_signal.lo Zend/zend_generators.lo Zend/zend_virtual_cwd.lo Zend/zend_ast.lo Zend/zend_objects.lo Zend/zend_object_handlers.lo Zend/zend_objects_API.lo Zend/zend_default_classes.lo Zend/zend_inheritance.lo Zend/zend_smart_str.lo Zend/zend_execute.lo main/internal_functions_cli.lo sapi/fuzzer/fuzzer-parser.lo sapi/fuzzer/fuzzer-sapi.lo -lcrypt -lresolv -lcrypt -lrt -lrt -lm -lnsl -lstdc++ -lxml2 -lxml2 -lxml2 -lcrypt -lxml2 -lxml2 -lxml2 -lcrypt  -lFuzzingEngine -o sapi/fuzzer/php-fuzz-parser
```

Not sure what is missing - it builds locally for me with -lFuzzer, but not here with -lFuzzingEngine. Any ideas?

**Comment by Dor1s** [comment]
@smalyshev thanks a lot for giving this a try!

The command looks good overall, except of these flags `-fsanitize-coverage=edge -fsanitize=address`, they aren't needed, because OSS-Fuzz has already provided the needed flags in `CFLAGS` and `CXXFLAGS`, in your command those are `-std=c++11 -I/usr/include -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -fvisibility=hidden`.

However, I don't think that explains the undefined reference errors you've got.

Can you try using `-stdlib=libc++` instead of `-lstdc++`? If that doesn't help, please upload a PR so that we could reproduce the failure. Otherwise it's kinda hard to fix such errors without being able to play with flags a little bit.

**Comment by smalyshev** [comment]
I've made https://github.com/google/oss-fuzz/pull/2202 with the config I'm using. Removing `-lstdc++` might be a bit tricky as it comes from standard flags, but I'll see if it's possible. Adding `-stdlib=libc++` should be easy.

**Comment by smalyshev** [comment]
Looks like `-stdlib=libc++` helped, the build finishes now. Will proceed to further testing. One thing not yet clear to me from the docs is how do I define the initial corpus?

**Comment by Dor1s** [comment]
> Looks like -stdlib=libc++ helped, the build finishes now. 

Woohoo!

> ... the initial corpus

For the very initial testing locally, corpus is not necessary, but it's really important even for the initial integration (i.e. when we merge a pull request and start running fuzzers on OSS-Fuzz). It's documented here: https://github.com/google/oss-fuzz/blob/6d1247c377f20a3c4282a5be0a75a09b5f3b751e/docs/new_project_guide.md#seed-corpus

Basically, you just need to copy interesting inputs into `/out/<fuzzer_name>.zip` archive.

> Looks like I need to add some libraries to runtime image? Is it possible?

It's highly recommended to use static linking, if possible. There should be some `./configure` flag for that, I suppose.

**Comment by smalyshev** [comment]
I think #2202 is working now, and EXIF fuzz looks nice too, will enable after some more testing. Please review and see if you see anything wrong there.

**Comment by Dor1s** [comment]
Thanks a lot for the first step! Also copying my comment about MSan here:

When building with MemorySanitizer (`python infra/helper.py build_fuzzers --sanitizer memory php`) I've got the following error:

```
Generating phar.php
/bin/bash: line 1: 54872 Segmentation fault      (core dumped) ` if test -x "/src/php-src/sapi/cli/php"; then /src/php-src/build/shtool echo -n -- "/src/php-src/sapi/cli/php -n"; if test "x" != "x"; then /src/php-src/build/shtool echo -n -- " -d extension_dir=/src/php-src/modules"; for i in bz2 zlib phar; do if test -f "/src/php-src/modules/$i.la"; then . /src/php-src/modules/$i.la; /src/php-src/build/shtool echo -n -- " -d extension=$dlname"; fi; done; fi; else /src/php-src/build/shtool echo -n -- "/src/php-src/sapi/cli/php"; fi;` -n -d 'open_basedir=' -d 'output_buffering=0' -d 'memory_limit=-1' -d phar.readonly=0 -d 'safe_mode=0' /src/php-src/ext/phar/build_precommand.php > ext/phar/phar.php
Makefile:356: recipe for target 'ext/phar/phar.php' failed
make: *** [ext/phar/phar.php] Error 139
Fuzzers build failed.
```

**Comment by smalyshev** [comment]
> When building with MemorySanitizer (python infra/helper.py build_fuzzers --sanitizer memory php) I've got the following error:

Very weird, since after fetching backtrace from that crash it segfaults on:

>  return __builtin_cpu_supports("avx2");

I wonder if it's some weird incompatibility between memory sanitizer and clang builtins. In any case, since PHP has own memory manager, memory sanitizer probably would not be that useful... 

Which reminds me, for sanitizers to work, it probably is much more useful to run PHP fuzzers with `USE_ZEND_ALLOC=0` environment variable. Is there any way to define this for oss-fuzz system?

**Comment by nikic** [comment]
Some sanitizers are incompatible with ifunc resolvers. We currently opt-out of address sanitizer for ifuncs via https://github.com/php/php-src/blob/master/Zend/zend_cpuinfo.h#L103. This probably needs to handle memory sanitizer as well. Is there an attribute that applies to all sanitizers?

**Comment by smalyshev** [comment]
CLang defines `__attribute__((no_sanitize("memory")))` for MemorySanitizer, and `__attribute__((no_sanitize("undefined")))` for UBSanitizer, and unsurprisingly also `__attribute__((no_sanitize("address")))` but no syntax to disable all of them. I guess we'd need to support CLang syntax too probably.

**Comment by Dor1s** [comment]
> Which reminds me, for sanitizers to work, it probably is much more useful to run PHP fuzzers with USE_ZEND_ALLOC=0 environment variable. Is there any way to define this for oss-fuzz system?

Would it work if you set this up in the fuzz target itself? Using 
http://llvm.org/docs/LibFuzzer.html#startup-initialization

**Comment by smalyshev** [comment]
Am I supposed to get a message on build failure? I see build fails in https://oss-fuzz-build-logs.storage.googleapis.com/log-0b58b5e9-d38b-4fc2-a7d1-f6dba8d6f1ed.txt (it's a legit bug btw, so I guess all the work is already paying off :) but I don't see any alerts in my mail...

**Comment by Dor1s** [comment]
Build failures are reported only after 2 consecutive failures, that's why a bug hasn't been reported yet.

**Comment by smalyshev** [comment]
I'm having a lot of trouble adding fuzzers that depend on external libraries - PHP build does not seem to have any option to use static libraries when shared libraries are around (I guess as it doesn't make sense in most real-life builds?) and I can't find any libtool magic options to make that happen. Moreover, some dependencies (like [libonig](https://packages.ubuntu.com/xenial/libs/libonig-dev) for example) don't even seem to ship static versions of the library. Is there any way to get a shared lib into the build environment? Maybe copy it to $OUT somehow and set rpath or something?

**Comment by jonathanmetzman** [comment]
>Maybe copy it to $OUT somehow and set rpath or something?

I've shipped shared objects in `$OUT` before, this should work fine.

**Comment by Dor1s** [comment]
@smalyshev looks like the existing fuzz target has found some interesting bugs in the past. What's your opinion of it? Was it useful? Would you be interested to have more fuzz targets for PHP?

**Comment by nikic** [comment]
php-src should now be clean under `-fsanitize=undefined`.

**Comment by smalyshev** [comment]
> looks like the existing fuzz target has found some interesting bugs in the past. What's your opinion of it? Was it useful? 

Yes, it was useful, found several bugs on EXIF.

> Would you be interested to have more fuzz targets for PHP?

Definitely.
