### ISSUE TITLE
maintain font corpora

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#199]
this is a spin-off of #194 primarily dedicated to fonts.
Let's keep here (an updated) list of fonts publicly available to download and use as seeds. 
for freetype, harfbuzz, ots, woff2, etc. 

Also let's make sure oss-fuzz actually uses these fonts. 

https://github.com/unicode-org/text-rendering-tests
https://github.com/google/fonts 
https://github.com/adobe-fonts/ (several repos)

@behdad

**Comment by MarkusTeufelberger** [comment]
https://www.freedesktop.org/wiki/Software/Fonts/ contains a large list of open source/free/libre fonts.

**Comment by inferno-chromium** [comment]
@kcc - i uploaded everything in comment#0 to gs://global-corpus.clusterfuzz-external.appspot.com/fonts
except
https://github.com/adobe-fonts/source-han-serif (too huge)
https://github.com/adobe-fonts/source-han-serif (too huge)

@MarkusTeufelberger - do you have an archive of all files, hard to navigate that page.
