### ISSUE TITLE
Regresion? Lots of issues resolved at once

### ISSUE THREAD

**Issue by tsdgeos** [google/oss-fuzz#1995]
In poppler lots of issues have been changed (3 hours ago aprox) from Reproducible to Unreproducible and then to wontfix

A sample (there's too many to list)
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8477
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8762
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8540

I guess that's a regression?

**Comment by inferno-chromium** [comment]
Really sorry about that. This is a regression from a large code refactoring. I know the fix, just need to migrate these testcases.

**Comment by tsdgeos** [comment]
No worries, great that it could be fixed :)
