### ISSUE TITLE
testing locally does not work for out-of-tree fuzzers

### ISSUE THREAD

**Issue by dvyukov** [google/oss-fuzz#20]
`build.sh` for an out-of-free fuzzer does:
```
$CXX $CXXFLAGS /src/oss-fuzz/mylib/my_fuzzer.cc -o ...
```

https://github.com/google/oss-fuzz/blob/master/docs/new_library.md#testing-locally suggests to test locally with:
```
$ python scripts/helper.py build_fuzzers $LIB_NAME
```

This fails because my fuzzer is not committed to oss-fuzz yet:
```
clang-4.0: error: no such file or directory: '/src/oss-fuzz/mylib/my_fuzzer.cc'
```

To test I need to commit. To commit I need to test.

**Comment by mikea** [comment]
This will be fixed by my PR. It removes "/src/oss-fuzz" folder and explicitly adds fuzzer using COPY (the same way you did in your PR).
