### ISSUE TITLE
Use Chromium as the upstream for libwebp fuzzers in oss-fuzz and libwebp

### ISSUE THREAD

**Issue by madeleine-b** [google/oss-fuzz#2002]
With the CL [here](https://chromium-review.googlesource.com/c/chromium/src/+/1361324), I have duplicated the fuzzers from this repository into Chromium, specifically under chromium/src/third_party/libwebp/fuzzing.

For consistency and cleaner project dependency structure, those should be considered upstream and automatically imported here. This may serve as a tracking issue for making that change.

**Comment by inferno-chromium** [comment]
@madeleine-b - please submit a PR to use these. See https://google.github.io/oss-fuzz/advanced-topics/ideal-integration/, we dont have cycles to do these changes.
