### ISSUE TITLE
Add gitlab support for VCS coverage reporting.

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#202]
Example URL: https://clusterfuzz-external.appspot.com/coverage_report/libFuzzer_gnutls_private_key_parser_fuzzer/2016-12-17/f/%2Fsrc%2Fgnutls%2Flib%2Fx509%2Fprivkey.c

Errors with: `Couldn't load file content {"vcs_url":"https://gitlab.com/gnutls/gnutls.git","path":"/lib/x509/privkey.c"}: 404`

**Comment by inferno-chromium** [comment]
Done, we supported a bunch of VCSes, but forgot gitlab. Now added.
