### ISSUE TITLE
Wrong permissions for local testing

### ISSUE THREAD

**Issue by bilboed** [google/oss-fuzz#203]
Hi,

I'm trying out oss-fuzz locally, but the resulting image ends up with unreadable permissions.

The simplest way to reproduce is the following:
> git clone git@github.com:google/oss-fuzz.git
> cd oss-fuzz

Generate a sample project (automatically creates the proper project directory with required files)
> python infra/helper.py generate test
Comment out this line from projects/test/Dockerfile : RUN git clone --depth 1 <git_url> test     # or use other version control

Finally start a shell for that project (will automatically create image if needed)
> python infra/helper.py shell test
> ls /work
ls: cannot open directory '/work': Permission denied
> ls /out
ls: cannot open directory '/out': Permission denied

**Comment by bilboed** [comment]
Host machine : fedora 25
Everything run as user (member of docker group)

**Comment by inferno-chromium** [comment]
Did you have a Dockerfile and build.sh created yet. You need those first and then run
python infra/helper.py build_image $PROJECT_NAME

**Comment by bilboed** [comment]
Updated description accordingly

**Comment by bilboed** [comment]
It seems as though the volumes being mounted are created with root permission
>ls -lah build/
>total 16K
>drwxrwxr-x. 4 bilboed bilboed 4.0K Dec 18 15:57 .
>drwxrwxr-x. 7 bilboed bilboed 4.0K Dec 18 15:56 ..
>drwxr-xr-x. 3 root    root    4.0K Dec 18 15:57 out
>drwxr-xr-x. 3 root    root    4.0K Dec 18 15:57 work

**Comment by MarkusTeufelberger** [comment]
Inside a container, you are root by default afaik.

**Comment by inferno-chromium** [comment]
@mikea i think we have a bug for root permission - https://github.com/google/oss-fuzz/issues/30. Is there anything else that needs to be done for this bug ?

**Comment by mikea** [comment]
Yes, this is the exact duplicate of #30. I'll try to write down my ideas there.
