### ISSUE TITLE
The work directory should be different per-configuration

### ISSUE THREAD

**Issue by stefanbucur** [google/oss-fuzz#2042]
Currently, the `$WORK` directory is reused across fuzzer builds, even if the builds use different santizier options. For instance, unless the developer remembers to run `python infra/helper.py build_fuzzers --clean`, building MSAN after a previous ASAN build may fail, due to missing MSAN symbols in the existing ASAN builds. Many of the existing integrations safeguard against this situation by invoking a clean command in their build script, but this hurts incremental builds during fuzzer development.

To facilitate incrementality within each build configuration, the infra scripts could designate a distinct `$WORK` directory for each build configuration.

**Comment by jonathanmetzman** [comment]
I know it's been a very long time @stefanbucur but do you have a patch file I could apply to a project to reproduce this problem?
I think fixing this requires handling this in the many places we do fuzzer builds:

- [ ] helper.py
- [ ] Production builds
- [ ] Bisection builds
- [ ] CIFuzz builds.

**Comment by stefanbucur** [comment]
Hmmmm, unfortunately I don't even remember how I ran into this. In my latest uses of `python infra/helper.py`, I haven't run into this issue. Maybe this is no longer a problem? If you haven't heard of others bringing this up, it might be safe to close.

**Comment by jonathanmetzman** [comment]
Ha, I suspect it still is an issue, but projects don't use work so it doesn't become an issue.
I guess we can close and reopen if someone complains about this.
Thanks @stefanbucur
