### ISSUE TITLE
Import new SQLite fuzz targets from Chromium

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2053]
Ideally, those should be ported to sqlite3 upstream, but having them in https://github.com/google/oss-fuzz/tree/master/projects/sqlite3 as a temporary solution would be fine as well.

This might depend on #864. If that's a blocker, we can repeat what's been done in https://github.com/google/oss-fuzz/tree/master/projects/libpng-proto

//cc @drhsqlite, @pwnall, I'll also ping Matt who's been working on new fuzz targets in Chromium.

**Comment by mdenton8** [comment]
Thanks for filing this, just set up my GitHub account.
