### ISSUE TITLE
ClusterFuzz can't find seed corpus

### ISSUE THREAD

**Issue by randy408** [google/oss-fuzz#2085]
```
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: [/corpus/spng_read_fuzzer.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/spng_read_fuzzer.zip or
Step #5:         /corpus/spng_read_fuzzer.zip.zip, and cannot find /corpus/spng_read_fuzzer.zip.ZIP, period.
```
Should I rename the .zip to be <fuzz_target>.zip? I used libpng's [build.sh](https://github.com/glennrp/libpng/blob/libpng16/contrib/oss-fuzz/build.sh) as a template for libspng which produces a similarly named .zip.

[Monorail issue](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=12496)

**Comment by jonathanmetzman** [comment]
It has to be named <fuzz_target>_seed_corpus.zip

**Comment by Dor1s** [comment]
The error is reported from the coverage build, see `Build type: coverage`. The root cause is that the target does not have corpus backup (this should be done by ClusterFuzz during the first 24hrs of running the project). Let me see whether it's CF fault or something is wrong with the project.

**Comment by Dor1s** [comment]
I think it's my fault. After merging the original PR, I've manually decreased the project's weight (because it doesn't seem to have a significant user base). I might've done that wrong, since the interface on our end has changed. Now I tried to fix that, let's wait for a day or two. Please ignore this issue for now.

**Comment by Dor1s** [comment]
The coverage build succeeded and here is a report: https://storage.googleapis.com/oss-fuzz-coverage/libspng/reports/20190116/linux/report.html
