### ISSUE TITLE
Provide Guidance on Timeout "Issues"

### ISSUE THREAD

**Issue by dwbuiten** [google/oss-fuzz#2095]
I realize this not a technical issue per se, but it's caused quite a few problems within our (FFmpeg's) community, so I feel it is worth bringing up.

I understand the concept of reporting timeouts: You don't want to loop infinitely, or use a really huge amount of resources on what is probably an uninteretsing non-issue (and CPU time costs money).

There are a [huge number](https://git.ffmpeg.org/gitweb/ffmpeg.git?a=search&h=HEAD&st=commit&s=timeout) of these reported by oss-fuzz against FFmpeg, given the nature of our code (ingesting arbitrary files with a large number of codecs), and some developers feel that we should fix every single time out. The rationalization is something along the lines of ["if we don't fix the timeouts, we risk losing out on detection of legitimate security issue by oss-fuzz"](http://ffmpeg.org/pipermail/ffmpeg-devel/2019-January/239050.html).

However, in the process of doing this, it has created a lot of tension, because it often creates [a lot](https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/6e23736aefa83859fdb6faae4fd14c169f1a41ab?hp=75ea329b78f40537864e2ca2833c087c20041181) of [terrible](http://ffmpeg.org/pipermail/ffmpeg-devel/2019-January/238995.html) and [unreadable](http://ffmpeg.org/pipermail/ffmpeg-devel/2018-December/238084.html) code in order to satisfy oss-fuzz's timeouts, causing a lot of argument and tension between developers. (Even some stuff that ends up being almost ["let's write an optimized memset" giant thread](http://ffmpeg.org/pipermail/ffmpeg-devel/2018-December/238150.html).)

Many see it as overcomplicating code and making it more complex in order to satisfy an arbitrary timeout from a particular fuzzer. Many of these timeouts are in obscure/rare/game codecs, some of which are meant to be simple references (and some are indeed used as the official reference at the Library of Congress).

It would be good, in my opinion, anyway, if the official oss-fuzz documention provided guidance on how to go about handling these en masse, and/or a way to go about addressing these that won't 'hurt the ability to detect security issues', even if that documentation amounts to "tough luck" or "please contact us in special cases".

Apologies if this is all noise, or out of scope.

**Comment by michaelni** [comment]
Timeouts represent security issues in some contexts. More precisely they can range from true infinite loops to cases where small and trivial input can trigger substantial computations both these allow denial of service attacks in some contexts.
These fixes are not just for the fuzzer.

About optimizations, making code faster in general is a good thing, that is especially true for code that has broader use and isnt just some odd corner case. For example the memset code you quote is code that should be optimized even in a world that has no fuzzer. Its true of course that some codepathes involved in the timeouts are alot more obscure. And there you certainly have a point that optimizing it is ugly. There is no question that i agree with you that some of these changes are ugly.

Ultimately IMHO alot of this boils down to a tradeoff of making code as robust as possible, that is in the context of timeouts minimizing cpu usage per byte of hostile input. Vs. having pretty and terse code.
My opinion is that if we can reduce the worst case CPU usage per input byte for a codec by a factor of 2 by adding a few lines that is a win.

about the topic, If oss-fuzz documentation could say something that reduces disagreements within projects, and iam not sure how to exactly achieve that but such a thing would certainly be good. 
I 100% agree about that.

**Comment by kierank** [comment]
You are "optimising" for files that are infinitesimally unlikely to happen in the real world, and if they do cause a DoS there should be external means to stop that.

You should start optimising for cosmic ray hits while you're at it, start adding ECC in software to every array of memory. 

Your fixes are quite clearly there for the fuzzer, you trade one arbitrary timeout for another arbitrary timeout. It's an amazing waste of your intelligent human resources.

**Comment by inferno-chromium** [comment]
OSS-Fuzz can't do anything here. Timeout would need to be analyzed and ignored on a case-by-case basis. You should always prioritize security vulnerabilities (Type=Bug-Security) and functional crashers first and if time remains, then fix timeouts, ooms.

**Comment by dwbuiten** [comment]
@inferno-chromium That kind of ignores the point of the bug report. The problem is not prioritization ('if time permits'). The problem is that many of these 'timeout' problems are not problems, and the 'fix' makes code worse - that is why I think guidance is important. Blindly fixing every timeout listed leats to terrible results.

**Comment by inferno-chromium** [comment]
@dwbuiten - you mean guidance on fixing timeout issues and ignoring ones that can lead to bad code ? There can be some text in every timeout issue filed, but can you expand more on what sort of guidance can be provided in such bugs (in a generic way).

**Comment by DavidKorczynski** [comment]
We added guidance here https://github.com/google/oss-fuzz/pull/6431 

Closing this as resolved.
