### ISSUE TITLE
support for multiple fuzzers for the same library 

### ISSUE THREAD

**Issue by dvyukov** [google/oss-fuzz#21]
See curl/fuzzer.cc in https://github.com/google/oss-fuzz/pull/18/files

I would like to create a bunch of fuzzers for curl: http, http2, ftp, imap, ftp, pop3, etc. They could share build.sh, Dockerfile, Jenkins, and most of the fuzzer code. Though, they may need different dictionaries. Currently I need to throw in a dozen of top level directories with lots of copy-pasted code. It would be nice if I could create a dozen of fuzzers in the same dir sharing most of the code.

**Comment by Dor1s** [comment]
I think you can do this. We have 13 fuzzers for NSS: https://github.com/google/oss-fuzz/tree/master/nss. They use the same .h file, for example.

**Comment by mikea** [comment]
Yes, you can add as many fuzzers as you want. As long as they end up in `/out/` we don't care how many you've got.

**Comment by dvyukov** [comment]
Wait, something is missing here. At least documentation on writing such fuzzers.

Do you mean that off-fuzz will discover all binaries in /out and use them as fuzzers? What if I have some non-fuzzer binaries there? Should I put them to a different dir?
How will it match fuzzers with options? I don't see where I specify the correspondence. Will it read my mind?

**Comment by mikea** [comment]
* yes it will consider everything runnable in /out as a fuzzer. We didn't have a case of non-fuzzier binary yet. At this point we don't even allow data files on CF (@oliverchang right?)
* yes, I think putting it into a sub dir is reasonable
* fuzzed options a matched by name. I have updated this documentation section.

**Comment by dvyukov** [comment]
The doc makes much more sense now. I did not realize that .options file must be prefixed with fuzzer name, doc said that any .options files will be picked up.

**Comment by kcwu** [comment]
> At this point we don't even allow data files on CF (@oliverchang right?)

Really? libchewing need data files :( https://github.com/google/oss-fuzz/issues/13
