### ISSUE TITLE
How do you check significant user base to accept project?

### ISSUE THREAD

**Issue by necros2k7** [google/oss-fuzz#2100]
subj

**Comment by inferno-chromium** [comment]
https://github.com/google/oss-fuzz/blob/master/docs/faq.md#what-kind-of-projects-are-you-accepting

not any quantitive numbers, but mostly how it is used. is it used by other popular projects and part of critical infrastructures ? we do this on a case-by-case-basis. so you can start with just submitted a project.yaml and we can provide an answer. any info on these is useful for panel to make decision.
