### ISSUE TITLE
Support custom build configurations

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2106]
There is an interest from e.g. dav1d project to have some additional build configs. The distinction will be in the different implementations used (e.g. no asm, only certain SIMD extensions, full production build). That would be also useful for crypto libraries as well as some other projects.

@inferno-chromium has mentioned that it could be achieved via specifying an additional `config` information in a project.yaml file and by branching on that `config` into passed to the `build.sh`.

Let's continue discussion and track some experiments in this issue.

**Comment by dalecurtis** [comment]
At some point I read or thought about using a VM to automate this process. E.g, start each fuzzer in a VM with the cpuid manually forced. The most interesting cpuflag subset could automatically be determined via a disassembly/opcode scan... or more easily just a manual configuration when operating on a targeted basis.

**Comment by Dor1s** [comment]
I don't recall anything like that :( That might be a nice idea though, if we could specify some CPU stuff. It should be also helpful with reproducibility, because right now we may get flaky testcases when GCE bots in different zones have different CPUs. Or we might have already addressed that issue after that openssl bug... @oliverchang might rebember
