### ISSUE TITLE
visualize coverage w/o dead code (need to add -fdata-sections -ffunction-sections -Wl,--gc-sections)

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#2110]
When we link a fuzz target against a library, not all functions are reachable from the target 
and in many cases the linker can eliminate such dead code if the following flags are used:
```
-fdata-sections -ffunction-sections # compile
 -Wl,--gc-sections # link
```

We don't currently use these flags and hence when we visualize coverage we show lots of statically dead code as uncovered. 

Example: libpng:
https://storage.googleapis.com/oss-fuzz-coverage/libpng/reports/20190123/linux/src/libpng/pngrtran.c.html

```
3200 |   | png_do_compose(png_row_infop row_info, png_bytep row, png_structrp png_ptr)
-- | -- | --
3201 | 0 | {
```
we show this function as uncovered while in fact it's just statically dead and linker can remove it.

Thus, I suggest to add the compiler/linker flags above to our base flags. 
(as usual, anything can break, so need to test carefully).

**Comment by kcc** [comment]
also, need to be careful with inlining -- probably want to disable it in the coverage build (if not already)

**Comment by Dor1s** [comment]
I _think_ clang coverage handles inlining well, but shouldn't harm to disable anyway. And thanks for the dead code stripping suggestion, will see how it works out!
