### ISSUE TITLE
improve libpng coverage on OSS-Fuzz

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#2111]
@glennrp

Did you have a chance to look at the code coverage achieved by OSS-Fuzz on libpng? 
At least the following functions are never executed: 
```
edges: 85 OSS_FUZZ_png_build_gamma_table png.c:4230
edges: 61 OSS_FUZZ_png_do_check_palette_indexes pngtrans.c:700
edges: 43 OSS_FUZZ_png_do_strip_channel pngtrans.c:496
edges: 36 OSS_FUZZ_png_colorspace_set_rgb_coefficients png.c:2503
edges: 31 OSS_FUZZ_png_do_bgr pngtrans.c:620
edges: 20 OSS_FUZZ_png_do_invert pngtrans.c:263
edges: 16 OSS_FUZZ_png_set_unknown_chunks pngset.c:1202
edges: 13 png_cache_unknown_chunk pngrutil.c:2864
edges: 13 png_build_16bit_table png.c:4007
edges: 9 OSS_FUZZ_png_do_swap pngtrans.c:320
edges: 9 OSS_FUZZ_png_do_packswap pngtrans.c:456
edges: 7 OSS_FUZZ_png_muldiv png.c:3384
edges: 7 OSS_FUZZ_png_gamma_correct png.c:3982
edges: 6 OSS_FUZZ_png_reciprocal2 png.c:3577
edges: 4 OSS_FUZZ_png_gamma_8bit_correct png.c:3898
edges: 2 OSS_FUZZ_png_app_warning pngerror.c:393
edges: 2 OSS_FUZZ_png_app_error pngerror.c:406
```

The coverage report ([here](https://storage.googleapis.com/oss-fuzz-coverage/libpng/reports/20190123/linux/src/libpng/pngrtran.c.html#L1574)) shows e.g. why `png_build_gamma_table` is not executed: there are no inputs that satisfy the complicated if statement inside `png_init_read_transformations`. 

```
1574 | 1.59k | if ((png_ptr->transformations & PNG_GAMMA) != 0 \|\|
-- | -- | --
1575 | 1.59k | ((png_ptr->transformations & PNG_RGB_TO_GRAY) != 0 &&
1576 | 1.59k | (png_gamma_significant(png_ptr->colorspace.gamma) != 0 \|\|
1577 | 0 | png_gamma_significant(png_ptr->screen_gamma) != 0)) \|\|
1578 | 1.59k | ((png_ptr->transformations & PNG_COMPOSE) != 0 &&
1579 | 1.59k | (png_gamma_significant(png_ptr->colorspace.gamma) != 0 \|\|
1580 | 0 | png_gamma_significant(png_ptr->screen_gamma) != 0
1581 | 0 | #  ifdef PNG_READ_BACKGROUND_SUPPORTED
1582 | 0 | \|\| (png_ptr->background_gamma_type == PNG_BACKGROUND_GAMMA_UNIQUE &&
1583 | 0 | png_gamma_significant(png_ptr->background_gamma) != 0)
1584 | 0 | #  endif
1585 | 1.59k | )) \|\| ((png_ptr->transformations & PNG_ENCODE_ALPHA) != 0 &&
1586 | 1.59k | png_gamma_significant(png_ptr->screen_gamma) != 0))
1587 | 0 | {
1588 | 0 | png_build_gamma_table(png_ptr, png_ptr->bit_depth);
```

Ideally, the fuzzer would find a way into these parts, but alas, it can't. 
There are 3 main things we could do here: 
* extend the seed corpus with inputs that trigger this code (then the fuzzer will explore further) 
* modify the fuzz target (`contrib/oss-fuzz/libpng_read_fuzzer.cc`) so that it can execute that code
* prove that the code can not possibly be executed and delete it. 

Please help with any of the above. 

And another request: there are quite a few libpng functions that are not involved in fuzzing at all, 
e.g. `png_do_compose` is removed from the fuzzer binary by linker (with `-Wl,--gc-sections`). 
Please check if it's possible to implement another fuzz target to cover these functions.

**Comment by kcc** [comment]
+ @ctruta

**Comment by alex** [comment]
@kcc Sadly Glenn passed away late last year, I'm not sure who is maintaining libpng now.

**Comment by kcc** [comment]
:(  ack... 
looks like @ctruta is the major contributor now

**Comment by randy408** [comment]
Gamma correction has to be explicitly requested in the fuzz target ([example](https://gitlab.com/randy408/libspng/blob/v0.4.2/tests/test_png.h#L113) of how that would work), libpng's seed corpus does have .png's with gAMA chunks so making that change should touch at least some of the gamma correction code, same goes for color correction. Calling `png_set_bgr()` should touch `png_do_bgr`  and some of the the transforms have to be set conditionally to reach all codepaths over multiple runs e.g. 16-bit PNG's should be scaled/stripped to 8-bit and vice versa.

**Comment by kcc** [comment]
Yea, figured this out too. 
I'm currently playing with as [a way](https://github.com/google/fuzzer-test-suite/blob/master/libpng-1.2.56/png_mutator.h) to do structure aware fuzzing for PNG (any API that consumes PNG). 
One of my thoughts is to encode the sequence of transforms as an extra PNG chunk, say `fUZz`, 
so that every input gets exactly one execution with exactly one set of transforms. 
Does this sound reasonable? (I'm still a PNG noob)

**Comment by randy408** [comment]
For libpng there is no 1:1 mapping from functions to transforms, some functions are aliases to multiple other functions (see [here](https://gitlab.com/randy408/libspng/blob/master/tests/test_png.h#L124) and [here](https://gitlab.com/randy408/libspng/blob/master/tests/test_png.h#L135)), `png_set_palette_to_rgb()` is actually just an alias to `png_set_expand()` etc so you'll have to deal with that, AFAIK you can't do some transforms without the "tRNS_to_alpha" transform.

**Comment by kcc** [comment]
The leak is auto-reported at https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=12716
Will need the libpng folks to take a look.

**Comment by bshastry** [comment]
Wondering if you still need help increasing coverage of libpng, is there anything specific one could help with?

**Comment by kcc** [comment]
Yes. 
One could help with extending https://github.com/google/oss-fuzz/blob/master/projects/libpng-proto/libpng_transforms_fuzzer.cc or https://github.com/glennrp/libpng/blob/libpng16/contrib/oss-fuzz/libpng_read_fuzzer.cc to cover more functionality of libpng. (Or creating yet another independent fuzz target and adding it alongside the two above).

**Comment by Dor1s** [comment]
Still valid issue. Is anyone working on it?

**Comment by randy408** [comment]
If a file is not listed in the [coverage report](https://storage.googleapis.com/oss-fuzz-coverage/libpng-proto/reports/20200227/linux/src/libpng/report.html) does it mean it has 0% coverage? I might be able to improve the libpng-proto fuzzer.

**Comment by Dor1s** [comment]
@randy408 if a file is not listed in the report, it means it is not even linked into the output binary/library.

0% coverage will be displayed if a file is linked it, but the code from it is never executed.
