### ISSUE TITLE
[Question] Does MD4C qualify for being added?

### ISSUE THREAD

**Issue by mity** [google/oss-fuzz#2134]
Hello, 

I'm interested in continuous fuzz testing of [MD4C](https://github.com/mity/md4c). It is very fast SAX-like markdown parser implementation written in C.

I am maintainer and main developer of it.

Some more info about the project can be found here:
 * https://github.com/mity/md4c
 * https://talk.commonmark.org/t/md4c-new-implementation-in-c/2302
 * https://talk.commonmark.org/t/why-is-md4c-so-fast-c/2520

There is currently work in progress to get it into some Linux distros, and Qt team is working on Markdown support in their `QTextDocument` class using this parser, which likely means MD4C is going to have much wider exposure in the foreseeable future.
 * https://github.com/mity/md4c/issues/48
 * https://github.com/mity/md4c/pull/49
 * https://codereview.qt-project.org/#/c/214842/

So, given the current state, does MD4C already qualify for being added into the oss-fuzz project?

**Comment by inferno-chromium** [comment]
Once the QT cl lands OR one of the distros start including your package, we would be happy to accept your project for continuous fuzzing in OSS-Fuzz. Please submit a pull request once either one of those things happen.
