### ISSUE TITLE
New bugs seen in daily fuzzing logs not automatically reported

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#2138]
Hello,

Just noticed that oss-fuzz maintains a directory for storing fuzzing logs and results on a daily basis. I observed that there is a discrepancy between the last field issue (on oss-fuzz.com) and the last bug found.

For example, in the Solidity logs, I found that there is a new memory leak that was discovered by the fuzzer today, but the last reported leak on the oss-fuzz.com dashboard is one week old.

Is there a reason behind this? Is it that the latest leak is a duplicate of the old one and hence unreported? To me, it is hard to say whether the leak is a duplicate because sometimes stack traces and the quantum of leak can be different for the same underlying issue.

Thank you!

**Comment by inferno-chromium** [comment]
yes a bug can be found earlier. we dont update the original stacktrace, but now there is a dedicated last tested stacktrace section that runs it once a day with new code.
