### ISSUE TITLE
Identify which build config is broken when we report a build failure

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2142]
Sometimes a project might have a broken build in a non obvious config such as UBSan. It is very hard to get this information from the build log that we surface to the users. If we could parse the log somehow and hint in which config the failure happened, that would be very helpful for the developers.

**Comment by inferno-chromium** [comment]
Done!

**Comment by Dor1s** [comment]
FTR, this was done in https://github.com/google/oss-fuzz/pull/3236
