### ISSUE TITLE
Data on all fuzzing faults found

### ISSUE THREAD

**Issue by Derek-Jones** [google/oss-fuzz#2144]
I'm after data on all the faults found during fuzzing.

Why?

A count of how many times each distinct fault was experienced (in a program) can be used to estimate the number of faults (of the kind being detected) that remain.  Details here:
http://shape-of-code.coding-guidelines.com/2018/03/18/estimating-the-number-of-distinct-faults-in-a-program/

I also have a wider interest in obtaining data for evidence-based software engineering:
http://www.knosof.co.uk/ESEUR

**Comment by oliverchang** [comment]
Our bug tracker is public: https://bugs.chromium.org/p/oss-fuzz/issues/list, which may have what you're after.

**Comment by Derek-Jones** [comment]
Thanks, I saw this data.

The bug tracker lists bugs (obviously).  But does not include information on the numbers of times a particular bug was encountered during the fuzzing process (no reason why it should).
