### ISSUE TITLE
More flexible public release of issues and ACLs on ClusterFuzz results

### ISSUE THREAD

**Issue by htuch** [google/oss-fuzz#2147]
One of the issues we're hitting in Envoy's use of ClusterFuzz is that we have permanent backlog of issues that the core maintainers don't have bandwidth to fix. Most of these are not security critical, and would benefit from early release to the community, rather than waiting for the 90 days (I think?) embargo to expire.

It would be great to have a way to tag an issue for immediate public release or for release to a specific set of users.

**Comment by inferno-chromium** [comment]
So, we have given you EditIssue permission for your own ACL bugs.
