### ISSUE TITLE
Documentation on what's a Fuzz Target

### ISSUE THREAD

**Issue by jsha** [google/oss-fuzz#2148]
In the [New Project Guide](https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md), it says:

> This file describes how to build **[fuzz targets](https://github.com/google/oss-fuzz/blob/master/docs/glossary.md#fuzz-target)** for your project. The script will be executed within the image built from Dockerfile.

This suggests that a "fuzz target" is a binary, but the linked glossary says it's:

> Fuzz Target
> A function to which we apply fuzzing. A specific signature is required for OSS-Fuzz. Examples: openssl, re2, SQLite.

I found this somewhat confusing; would you mind updating either the New Project Page or the Glossary?

Thanks!

**Comment by kcc** [comment]
Good catch. 
Maybe like this?

This file describes how to build binaries for **[fuzz targets](https://github.com/google/oss-fuzz/blob/master/docs/glossary.md#fuzz-target)** in your project.

**Comment by inferno-chromium** [comment]
Someone just need to sync old OSS-Docs with this - https://google.github.io/clusterfuzz/reference/glossary/

**Comment by jsha** [comment]
Ah, syncing the docs seems like a good idea.

To go deeper into the problem I was trying to solve: I had written a binary that worked for fuzzing under afl-fuzz, and was trying to port to OSS-Fuzz. It wasn't clear to me whether I should provide my own `main` or whether that would be provided by the OSS-Fuzz build chain. I tried to deduce that from the definition of "fuzz target" but it might also be clearer to just say "Don't define your own `main` function; a `main` will be provided at link time by linking with the fuzzer engine (with -lFuzzerEngine)"

**Comment by kcc** [comment]
Yes, do *not* define your own main.

**Comment by Dor1s** [comment]
This should be addressed with all the clarifications we've made to the docs. The last of them is https://github.com/google/oss-fuzz/pull/3220

**Comment by jsha** [comment]
I think there's still some improvement available here. If I go to the updated New Project Guide at https://google.github.io/oss-fuzz/getting-started/new-project-guide/#prerequisites, I see:

> Integrate one or more [fuzz targets](https://google.github.io/oss-fuzz/reference/glossary/#fuzz-target) with the project you want to fuzz.

That links to https://google.github.io/oss-fuzz/reference/glossary/#fuzz-target, which has a very OSS-Fuzz specific definition:

> Fuzz Target
> In addition to its general definition, in OSS-Fuzz a fuzz target can be used to reproduce bug reports. It is recommended to use it for regression testing as well (see ideal integration).

However, there's a more useful definition at https://github.com/google/fuzzing/blob/master/docs/glossary.md#fuzz-target:

> Fuzz Target
> Or Target Function, or Fuzzing Target Function, or Fuzzing Entry Point.
> A function to which we apply fuzzing. A specific signature is required for OSS-Fuzz. Examples: openssl, re2, SQLite.

I think it would be better for the New Project Guide to link to docs/glossary.md, and for docs/glossary.md to link to the "OSS Fuzz specific terms" for additional information. Alternately, maybe the "OSS Fuzz specific terms" should link out to docs/glossary.md for the general definition of fuzz target?

**Comment by Dor1s** [comment]
@jsha thanks again for the feedback. I've linked the "general definition" text to the google/fuzzing repo.
