### ISSUE TITLE
Timeout bugs should explicitly specify timeout value

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#216]
I think each timeout bug should specify its timeout value. Currently people often get confused.

**Comment by mikea** [comment]
The should probably apply to out-of-memory bugs.

**Comment by kcc** [comment]
It would also be interesting to run with a larger time (memory) limit and report whether the test passes with that larger limit.

**Comment by Dor1s** [comment]
Would it be fine to put those values into bug title? e.g. `Timeout (25+ secs) in....` or `Out-of-memory (2+ GB) in ...`?

**Comment by mikea** [comment]
That would be a good start.

**Comment by kcc** [comment]
We also need to point to the FAQ entry (docs/faq.md#how-timeouts-and-ooms-are-handled) in the description.

**Comment by inferno-chromium** [comment]
Better to put in issue comment than title. Also, should be in overview section of testcase report. Currently, it is in red in command line in stacktrace which might be not obvious.

**Comment by inferno-chromium** [comment]
A major problem is our reproducer scripts didn't pass the timeout values. So, fixing that in https://github.com/google/oss-fuzz/pull/236.

**Comment by inferno-chromium** [comment]
Should be now fixed for future bugs, we will show this in both UI and on filed bug.
https://chrome-internal.googlesource.com/chrome/tools/clusterfuzz/+/80ac6d046a8eaa29e6e3816971d88273c223c6c9
