### ISSUE TITLE
Testcase stuck in regression

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#2161]
This [testcase](https://oss-fuzz.com/testcase-detail/5408668986638336) has been stuck in regression task and seems to be trying "current range 201704251415:201902100254" too many times for it to be coincidental.
cc @mbarbella-chromium

**Comment by oliverchang** [comment]
succeeding now.

**Comment by jonathanmetzman** [comment]
Thanks Oliver!
