### ISSUE TITLE
start using libFuzzer's -fork=1 mode

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#2178]
Docs: http://llvm.org/docs/LibFuzzer.html#fork-mode

The biggest change now is that a libFuzzer run may produce more than one artifact
(e.g. multiple `oom-`, `timeout-`, `leak-`, or `crash-` outputs).
Quite likely some features that CF relies on are missing -- please tell me which. 

Please also give feedback on the feature and on the docs: both are very fresh and have rough edges. 

It would be interesting to use ClusterFuzz to evaluate if the fork mode is more efficient than the default mode.

**Comment by kcwu** [comment]
Doesn't ctrl-c work in fork mode?

**Comment by kcwu** [comment]
And in fork mode, no crash files are recorded for SIGABRT.
```
#381772: cov: 7642 ft: 36389 corp: 13647 exec/s 0 oom/timeout/crash: 0/1/0 time: 489s
==2112==ERROR: AddressSanitizer: ABRT on unknown address 0x000000000840 (pc 0x7f760320c428 bp 0x7fff101deda0 sp 0x7fff101deb48 T0)
#407368: cov: 7643 ft: 36392 corp: 13650 exec/s 568 oom/timeout/crash: 0/1/1 time: 500s
```
No matter -ignore_crashes or not.

I don't have time to investigate the detail yet.

BTW, I'm using oss-fuzz's scripts to build my fuzzers today and I say yes to "Pull latest base images (compiler/runtime)? (y/N):"

**Comment by kcwu** [comment]
Looks like fork-mode still only use only one process to load corpus. Would be better if loading are paralleled as well.

**Comment by kcwu** [comment]
What is exec/s in fork mode? per process or total?
I have a bad target (often timeout) and the number goes up and down dramatically. I am wondering maybe you should calculate average with longer time frame.

Example: (`-fork=15 -timeout=10`)
```
#1199927: cov: 7898 ft: 52947 corp: 17635 exec/s 40 oom/timeout/crash: 0/70/54 time: 3105s
#1200161: cov: 7898 ft: 52948 corp: 17636 exec/s 5 oom/timeout/crash: 0/70/54 time: 3115s
#1213664: cov: 7898 ft: 52950 corp: 17638 exec/s 150 oom/timeout/crash: 0/71/54 time: 3140s
#1218482: cov: 7898 ft: 52951 corp: 17639 exec/s 267 oom/timeout/crash: 0/72/54 time: 3146s
```

And minor issue: `exec/s` should be `exec/s:`.

**Comment by kcc** [comment]
>> Doesn't ctrl-c work in fork mode?

Not well enough... Patches are welcome :) 

>> And in fork mode, no crash files are recorded for SIGABRT.

Small repro, please, in a separate issue (in https://github.com/google/sanitizers/). Works for me. 

>> Would be better if loading are paralleled as well.

What's the point? Loading a corpus is a tiny portion of the overall fuzzing. 
(if not, you are already in trouble)

>> What is exec/s in fork mode? per process or total?

Per process, as reported by the exited child. 

>> And minor issue: `exec/s` should be `exec/s:`.

ACK, thanks!

**Comment by kcwu** [comment]
> > Would be better if loading are paralleled as well.
>
> What's the point? Loading a corpus is a tiny portion of the overall fuzzing.
> (if not, you are already in trouble)

I agree it is tiny portion compared to overall fuzzing. However,

 1. This is my current main usage:

I'm developing/debugging a new fuzzing target. Initially it works well. After few hours of fuzzing, it behave not so well. So I'm debugging and I want to see its behavior after loaded full corpus. And now it has already generated about 20k corpus and needs few minutes to load.

2. Maybe somebody use `-runs=0` to do regression testing. Parallel loading sounds good for them. I'm not sure.

BTW, I found loading in fork mode (1800s) is significant slower than non-fork mode (40s) in my case. I will report separate issues when I have more time to test/investigate (not soon).

**Comment by jonathanmetzman** [comment]
`-print_final_stats=1` isn't supported by fork mode right?

**Comment by kcc** [comment]
Nope. should be easy to add. Will do once I have the time (feel free to do it too)

**Comment by bshastry** [comment]
> And in fork mode, no crash files are recorded for SIGABRT.

Is this still a problem? I am considering enabling fork mode for one of my projects, but am not sure if I should due to potential false negative issues.

**Comment by kcc** [comment]
I have not seen a repro for the problem for SIGABRT. Works for me.

**Comment by kcwu** [comment]
I didn't do fuzzing recently, so I have no more information about the problem for SIGABRT.
