### ISSUE TITLE
Timeout but only with address sanitizer

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#2180]
This comes from https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13255
There is a timeout with more than 25 seconds execution.

Without sanitizers, I get
```
time ./test/fuzz/fuzz_htp /Users/catena/Downloads/clusterfuzz-testcase-minimized-fuzz_htp-5708681826533376.dms 

real	0m0.063s
user	0m0.056s
sys	0m0.006s
```

So it is more than 100x faster without sanitizer

I gather that this comes from many calls to `calloc` and `free` in `htp_process_response_header_generic`
The solution would be to use a temporary variable on the stack and alloc + memcpy only when parsing is successful.
But this means an overhead if we have to do that every time...

Any better idea ?
(Limit the number of failed parsing before returning global failing ?..)

**Comment by kcc** [comment]
All the time is spent in `realloc`:

```
#3  0x00000000004f0a2a in __interceptor_realloc (ptr=0x7fffe8897800, size=418928) at /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:165
#4  0x000000000053922b in bstr_expand () at bstr.c:273
#5  0x000000000055c80d in htp_process_response_header_generic () at htp_response_generic.c:286
#6  0x0000000000556f08 in htp_connp_RES_HEADERS () at htp_response.c:812
#7  0x000000000055ab3c in htp_connp_res_data () at htp_response.c:1127
#8  0x00000000005361f8 in LLVMFuzzerTestOneInput () at test/fuzz/fuzz_htp.c:198
```

there isn't much we can do here. realloc in asan always reallocates the memory
(so that it can finds bugs; so it's asan's feature, not bug). 

Maybe try to be less aggressive with realloc.

**Comment by catenacyber** [comment]
Thank you @kcc 
How did you do the profiling to find out that the time was spent in this `realloc` ?


The point of this code is to transform some input like
```
a:1
a:2
a:3
a:1
```
into a structure like
```
a:"1,2,3,1"
```
That means one `realloc` for each 4 bytes of input

I am afraid that it will take a less readable code to do less realloc
Another solution would be to limit the size of the inputs...

@victorjulien what do you think ?

**Comment by victorjulien** [comment]
I think we can do 2 things:

1. optimize a bit at the cost of some memory, so expand by a bit more than we need so we don't have to expand as often.

2. limit the number of duplicate headers we accept. I actually think this makes a lot of sense. Simply allow one duplicate and raise an event if there are more. If we allow just one duplicate it will be a trivial code change, as a flag is set on the ```htp_header_t::flags```:
```c
h_existing->flags |= HTP_FIELD_REPEATED;
```
So if the flag is already set we can refuse to add the header and raise the event.

**Comment by catenacyber** [comment]
The timeout just got fixed without any changes to libhtp code.
Did you change something in the sanitizer ?

**Comment by kcc** [comment]
The idiom in C++ is to use `std::vector` instead of `realloc` -- it will not have the described problem. 
In C, there is no good out of the box idiom. 

We didn't change anything, but timeouts bugs are, sadly, flaky this way.

**Comment by kcc** [comment]
> How did you do the profiling to find out that the time was spent in this `realloc` ?

I used 'perf record` which has shown me that we spend all the time inside the kernel and allocator, 
then I used `gdb`, interrupted the process several times and typed `bt` to get the stack trace. 
You can used `perf record -g` to get stack traces, but this is more involved than with `gdb `

**Comment by catenacyber** [comment]
Thank you @kcc 
Should this `perf record` tooling be somehow integrated into `infra/helper.py` ?

**Comment by catenacyber** [comment]
And how do you install perf in the docker container ?

**Comment by kcc** [comment]
I didn't run perf inside docker. I've used docker to build the target, then ran the binary on my machine. 

It would be interesting indeed to provide a flat function profile as part of the UI. 
There are some questions though, e.g. do we collect the profile with asan and coverage or using vanilla -O2 build?

**Comment by catenacyber** [comment]
> I've used docker to build the target, then ran the binary on my machine.

Ok (but I am running MacOS...)

> do we collect the profile with asan and coverage or using vanilla -O2 build?

Both make sense I guess.
Timeouts (such as the mentioned one) only happen with asan so it is interesting
Production builds are with O2 so they are interesting as well
