### ISSUE TITLE
Protocol for adding a new proto fuzzer

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#2191]
Hello,

Currently, there are separate directories for corpus and proto fuzzers e.g., `libpng` and `libpng-proto`. Is this something that is recommended?

We are thinking of adding a protofuzzer for solidity, so I was wondering if the PR should be under a new dir called `solidity-proto` or subsumed under the current `solidity` dir.

Thank you!

**Comment by jonathanmetzman** [comment]
>Currently, there are separate directories for corpus and proto fuzzers e.g., `libpng` and `libpng-proto`. Is this something that is recommended?

I'm pretty sure that is only because @kcc is writing the proto fuzzer but doesn't work on libpng.

>We are thinking of adding a protofuzzer for solidity,

Go for it!

>so I was wondering if the PR should be under a new dir called `solidity-proto` or subsumed under the current `solidity` dir.

I think current directory is fine (though ideally, it would be upstreamed :-)
