### ISSUE TITLE
Fuzz libxslt

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2192]
Moving the discussion here, //cc @nwellnhof @ngregoire

It's been a while since https://github.com/google/oss-fuzz/pull/574 got merged. It would be awesome to finally enable continuous fuzzing for libxslt.

Please let us know if you have any questions / concerns.

**Comment by nwellnhof** [comment]
The biggest blocker for me right now is that certain XSLT or XPath inputs can take arbitrarily long to process, so you'll always get timeouts. This wasn't a problem when I was fuzzing with AFL but I couldn't find a way to ignore timeouts with libFuzzer. It seems that the experimental fork mode should work but the fork option isn't available on my LLVM 7 setup.

**Comment by Dor1s** [comment]
Yep, the new fork mode should be helpful. You can play with the recent clang revision if you go through [New Project Guide](https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md) and then do `python infra/helper.py shell $project_name`.

**Comment by nwellnhof** [comment]
I worked around the timeout problem and started with OSS-Fuzz integration. Now I'm running into a strange problem with UBSan and unsigned integer overflows. With the latest Docker image and C code like

    static int global = -1;
    if (global != 0) ...

I get

~~~
/src/libfuzzer/FuzzerTracePC.cpp:391:62: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned int'
    #0 0x467246 in HandleCmp<unsigned int> /src/libfuzzer/FuzzerTracePC.cpp:391:62
    #1 0x467246 in __sanitizer_cov_trace_const_cmp4 /src/libfuzzer/FuzzerTracePC.cpp:512
    #2 0x5a1801 in xmlNewMutex /src/libxml2/threads.c:184:28
~~~

The problem persists if I compile with `-fno-sanitize=unsigned-integer-overflow`.

**Comment by nwellnhof** [comment]
The unsigned integer overflow is in the libFuzzer code. Adding `-fno-sanitize=unsigned-integer-overflow` in `base-builder/compile_libfuzzer` fixes the issue.

**Comment by inferno-chromium** [comment]
@kcc - can you help with an owner for this libfuzzer fix. Or can ask Max/Jonathan when they are back from OOO.

**Comment by kcc** [comment]
libFuzzer must not be built with ubsan.
If anything, it makes libFuzzer much slower. 
It absolutely must not be built with  `-fsanitize=unsigned-integer-overflow`. 

But we are not using it anywhere outside of two projects that enabled it for their good reasons. 
@nwellnhof, are you using any custom compiler flags anywhere? 
 
I think this is similar to other issues caused by OSS-Fuzz using it's own custom build of libFuzzer instead of the upstream build.

**Comment by nwellnhof** [comment]
> @nwellnhof, are you using any custom compiler flags anywhere?

I'm only using `-fnosanitize` to disable some UBSan sanitizers.

> I think this is similar to other issues caused by OSS-Fuzz using it's own custom build of libFuzzer instead of the upstream build.

Yes, OSS-Fuzz apparently builds a custom libFuzzer archive with `$SANITIZE_FLAGS`, see #2164. But this only seems to affect testing fuzz targets locally.

**Comment by nwellnhof** [comment]
Turns out that I was using an outdated `base-runner` image. After updating, everything runs as expected. Sorry for the noise.

**Comment by nwellnhof** [comment]
I'm almost done now. The new fuzz targets currently need an additional XML file that is copied to `$OUT`. I noticed that `bad_build_check` doesn't `cd $OUT` which causes the startup check to fail. Is this an oversight? Are the fuzz targets allowed to use other build artifacts in `$OUT`?

**Comment by Dor1s** [comment]
> Is this an oversight?

This is rather intentional, to catch issues like the one you've just observed :)

> Are the fuzz targets allowed to use other build artifacts in `$OUT`?

Yes, but the code should rely on `dirname(argv[0])` rather than the CWD.
