### ISSUE TITLE
Set security severity on historical bugs?

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#2196]
For statistical purposes, it'd be great if severity labels were added to historical bugs in monorail.

**Comment by jonathanmetzman** [comment]
Which bugs are you talking about? [These ones?](https://bugs.chromium.org/p/oss-fuzz/issues/list?can=2&q=Type%3DBug-Security+-label%3Asecurity_severity-medium+-label%3Asecurity_severity-low+-label%3Asecurity_severity-high&colspec=ID+Type+Component+Status+Proj+Reported+Owner+Summary&cells=ids)

**Comment by jonathanmetzman** [comment]
Or are there others?
One issue with severity in OSS-Fuzz (as opposed to Chrome) tracker is that most people can't edit them, so severity is only what ClusterFuzz decides and a human can't contradict this (maybe this is a good thing for what you are trying to do).

**Comment by alex** [comment]
@jonathanmetzman exactly those -- except all bugs, not just the open ones. Here's an example query I was looking at where move populated data would have been interesting:

https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=Type%3DBug-Security+label%3ADeadline-Exceeded+&colspec=ID+Type+Component+Status+Proj+Reported+Owner+Summary&x=security_severity&y=proj&mode=grid&cells=counts

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman exactly those -- except all bugs, not just the open ones.

D'oh!

Here's an example query I was looking at where move populated data would have been interesting:
> 
> https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=Type%3DBug-Security+label%3ADeadline-Exceeded+&colspec=ID+Type+Component+Status+Proj+Reported+Owner+Summary&x=security_severity&y=proj&mode=grid&cells=counts

I'll look into doing this (probably by sometime next week). Shouldn't be too hard to bulk edit each severity type using a query like [this](https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=Type%3DBug-Security+-label%3Asecurity_severity-medium+%22Recommended+Security+Severity%3A+Medium%22&colspec=ID+Type+Component+Status+Proj+Reported+Owner+Summary&cells=ids). But I want to avoid messing this up in a way that has such widespread consequences.

**Comment by alex** [comment]
Awesome, thanks!

**Comment by jonathanmetzman** [comment]
I've done it for the high and low severity cases. However, before I do the medium severity issues I want to investigate why some of them don't get a label when filed. Such as [this bug](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6402) for example.

**Comment by inferno-chromium** [comment]
not feasible, and more chance of incorrectness.
