### ISSUE TITLE
Various comments on oss-fuzz documentation and process

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#22]
Let me use this issue as a laundry list for small improvements. 

* Change the scripts and the docs to use `/work/libFuzzer.a` instead of `/work/libfuzzer/*.o`. Not that it will have any different result, but this is the way we document it in libFuzzer docs.

* Document what to do with non-git (svn, hg, etc)

* Can we use shorter (2-line) copyright headers? 

* Why do we have -
`LDFLAGS=-Wl,-whole-archive /usr/local/lib/libc++.a /usr/local/lib/libc++abi.a -Wl,-no-whole-archive`? 
It breaks the build for me on pcre2 because LDFLAGS are applied to the command that generates .a files. (maybe, a but in pcre2 build system?)

* [docs/new_library.md#checking-in-to-oss-fuzz-repository](../blob/master/docs/new_library.md#checking-in-to-oss-fuzz-repository) requires an example, of links to documentation or both. We shouldn't assume the the user is familiar with git workflow 

* `$ sudo python scripts/helper.py run_fuzzer $LIB_NAME name_of_a_fuzzer`  in new_library.md.
I don't think you need `sudo`

**Comment by mikea** [comment]
Created issues: #31 #32 #33 

Added link to gitHub forking guide & removed sudo documentation.

As for shorter header, I don't know. Our guidelines specifically ask for this header.
