### ISSUE TITLE
CI testing when adding a new project

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2206]
This was pointed out by @jonathanmetzman recently. Quite often when we merge a new integration and it appears to have a broken build (e.g. MSan or some other config that no one has tested), we're getting a bunch of errors from CF about missing builds. How hard would it be to add on-demand GCB / Travis check that would execute `infra/gcb/build_project.py` for a particular project?

**Comment by oliverchang** [comment]
This was already tracked in #1788 :)
