### ISSUE TITLE
Installed libraries don't persist

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#2209]
In the Dockerfile I install a library in using apt-get install.
When build.sh is executed, linking to the shared library works.
However, when I do ```python infra/helper.py run_fuzzer ...```, the libraries are gone.

Example:

in ```Dockerfile``` install ```libtiff5-dev```
in ```build.sh``` compile something with libtiff, eg.:

```
echo -en '#include "tiffio.h"\nint main(void) { TIFFClose(0); }' >x.cpp
$CXX $CXXFLAGS x.cpp -ltiff -o $OUT/fuzzer-x
```

Then run:

```
python infra/helper.py run_fuzzer <project> fuzzer-x
```

Result:

```
/out/fuzzer-x: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory
```

Is this expected, and should I always link against static libraries rather than shared libraries, am I doing something wrong, or is this a bug?

**Comment by jonathanmetzman** [comment]
This is expected. 
The packages get installed on the builder. But the fuzzers get run on the "runner".
It's easier for us this way.
I've worked around this by using patchelf to remove dependencies that aren't actually needed and by saving dynamic libraries to `$OUT`. Static linking is the preferred option though.
