### ISSUE TITLE
Enable build_fuzzers to not delete container on failed build

### ISSUE THREAD

**Issue by smalyshev** [google/oss-fuzz#2211]
It would be very useful if `infra/helper.py build_fuzzers` script had an option where it runs docker without `--rm` switch for the build.sh step. When the build is long and something goes wrong at the very end of it, it could be very helpful to preserve the environment so that the situation can be debugged within the same container. The container of course can be recreated step-by-step, but having the one that just failed and being able to debug it immediately saves time. I could do:
```
docker container ls -a
docker commit {ID} failed_container_image
docker run --entrypoint=bash -it failed_container_image
```
and explore all the files, logs and environment of the failed build immediately, reproduce the failure exactly as it happened, try some tweaks to fix it - all this without costly re-run of the whole build from scratch.

**Comment by Dor1s** [comment]
I feel like this was brought up previously and we had some reasons not to do it. @oliverchang do you remember? What's our position?

It seems to me that having a special flag for preserving container state might be helpful. In the meantime, you can follow [Debugging Build Scripts](https://github.com/google/oss-fuzz/blob/d69a8ea80da1611e55d1e9a441087568ecbd86f6/docs/debugging.md#debugging-build-scripts) doc:

```
python infra/helper.py build_image $project
python infra/helper.py shell $project
# inside the container
compile
# inspect the logs, change the scripts, etc
compile
```

But note, the changes made inside the container won't be visible outside and will get lost once you exit the container -- make sure to remember or copy them :)

**Comment by oliverchang** [comment]
Having a flag seems reasonable, but our recommended approach is the one that Max suggested. Would that work for you? We'd like to avoid having to add too many flags to our helper script.

**Comment by smalyshev** [comment]
Yes I think I can work with what Max suggested, thanks.
