### ISSUE TITLE
Skia build failing with "unable to push image"

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#2217]
The skia build failed twice now (once naturally, once after I manually started it) with this error:
```
denied: Access denied.
ERROR: failed to push because we ran out of retries.
ERROR
ERROR: error pushing image "gcr.io/oss-fuzz/skia": exit status 1
```
Logs [here](https://oss-fuzz-build-logs.storage.googleapis.com/index.html).
Assigning to current sheriff. cc @kjlubick

**Comment by Dor1s** [comment]
I checked the quotas and didn't find anything relevant. Googling and StackOverflowing also don't seem to help me so far.

**Comment by Dor1s** [comment]
Yeah, no clue so far. @oliverchang do you have any idea?

**Comment by Dor1s** [comment]
A wild guess: is the container too large? I see 2.2GB, while some others which I'd expect to be the biggest are smaller than that:
- ffmpeg: 1GB
- libreoffice: 2.1GB

Maybe there is an overflown signed 32-bit integer somewhere? :D

**Comment by Dor1s** [comment]
And now the latest build succeeded :)

**Comment by jonathanmetzman** [comment]
Failed again

**Comment by jonathanmetzman** [comment]
There are old tensorflow builds from 2018 that are 3.42 GB. I suspect size isn't a cause of this but your guess is as good as mine.

**Comment by jonathanmetzman** [comment]
Closing this as we are also tracking this issue [here](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13605)
