### ISSUE TITLE
How do I request an extension to the 90-day disclosure window?

### ISSUE THREAD

**Issue by micah-at-talos** [google/oss-fuzz#2223]
As stated [here](https://github.com/google/oss-fuzz#bug-disclosure-guidelines), there is a 14-day grace period. How do I request an extension to the 90-day disclosure window? Are the comments for the issues on bugs.chromium.org monitored, or do I need to request an extension through an issue here?

**Comment by jonathanmetzman** [comment]
>How do I request an extension to the 90-day disclosure window?

This is a good point. We should probably specify a particular channel.
I've filed #2225 to track this work.

>Are the comments for the issues on bugs.chromium.org monitored

Not really, I think some other means, like a GitHub issue is better.
