### ISSUE TITLE
Specify that GitHub should be used to request deadline extensions

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#2225]
As brought up in #2223 we should tell people to request extensions in a way that is unlikely to be accidentally missed. Therefore, I think we should recommend people open a GitHub issue to request an extension.

**Comment by Dor1s** [comment]
I'm leaning towards WontFix'ing this, as every issue filed by ClusterFuzz has the following sentence:

> If you need to contact the OSS-Fuzz team with a question, concern, or any other feedback, please file an issue at https://github.com/google/oss-fuzz/issues.

Do you think it's not enough?

**Comment by jonathanmetzman** [comment]
>Do you think it's not enough?

One would think it is enough.

But [many deadline extension requests](https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=deadline-grace&sort=&groupby=&colspec=ID+Type+Component+Status+Proj+Reported+Owner+Summary&x=&y=&mode=&cells=&num=100) were made on the oss-fuzz monorail.

I'm fine WontFixing this since I don't think it will be a priority in the near future.

**Comment by oliverchang** [comment]
Adding this explicitly might be good. Should be a simple change in sheriffbot if anyone wants to pick that up :)

**Comment by oliverchang** [comment]
@mbarbella-chromium

**Comment by jonathanmetzman** [comment]
Another [data point](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=16752)
If I get a chance I'll try to this when I'm sheriff if no one takes it up.
The current wording fails to make it understood by everyone that we will not respond to monorail comments.
