### ISSUE TITLE
Support for smaller fuzz targets

### ISSUE THREAD

**Issue by jfoote** [google/oss-fuzz#2231]
Hello,

Following up on https://github.com/google/oss-fuzz/pull/2229, is there a way to integrate small fuzz targets that are compiled with insufficient instrumentation to pass the `check_build` step? We have found bugs in our small fuzz targets after shorter/non-continuous fuzzing and think it would be worthwhile to run them regularly.

We are also [looking into](https://github.com/h2o/picotls/issues/221) creating [larger fuzz targets](https://github.com/h2o/picotls/pull/224) that would supersede smaller ones that fail `check_build`.

Thanks,
Jon

**Comment by Dor1s** [comment]
The problem with small fuzz targets is that they exhaust the search space fairly quickly and since then become regression tests essentially. We could probably allow running those, if we had a way to specify that a particular fuzz target should get a very small fraction of compute power allocated.

**Comment by jfoote** [comment]
We addressed our immediate need here by creating larger fuzz targets (merged into oss-fuzz via #2236). I am closing this issue accordingly; please feel free to re-open it at your discretion.
