### ISSUE TITLE
Disable unmaintained projects

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#2243]
Right now, it is

Firestore: broken builds since 6 mo 11 days
Chakra: broken builds since 4 mo 9 days

@minafarid @var-const - do you intend to maintain firestore build in OSS-Fuzz (see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10281). If this is not feasible, lets disable the OSS-Fuzz project.

@EdMaurer - do you intend to keep Chakra fuzzing in OSS-Fuzz, given Edge's recent plan to move to Chromium. If this is not feasible, lets disable the OSS-Fuzz project.

**Comment by var-const** [comment]
@inferno-chromium I will fix the Firestore build. I'm very sorry for neglecting the build breakage; thanks for the ping. I hope to have a fix tomorrow.

**Comment by inferno-chromium** [comment]
Thanks a lot @var-const.

**Comment by EdMaurer** [comment]
Not sure what's up with the ChakraCore build. We have a broken Linux build and will fix assuming it will address this build.

**Comment by inferno-chromium** [comment]
Sounds good, thanks @EdMaurer
