### ISSUE TITLE
LAME MP3 encoder/decoder fuzzer

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#2247]
I have a [LAME](http://lame.sourceforge.net/) fuzzer ready. Are you interested in integrating this into oss-fuzz?

It found one bug already in LAME master, not yet reported.
Still need to contact LAME team about interest in oss-fuzz integration.

Possibly some LAME code is already covered by the ffmpeg fuzzer. Reasons to nonetheless consider a separate fuzzer:

- No dependencies so easier to set up MemorySanitizer
- Fuzzes the encoder (I think ffmpeg only tests the decoder?)
- LAME decoder/encoder settings (VBR/CBR/ABR, mono/stereo, samplerate, quality etc) configured dynamically from the fuzzer input, to test all conceivable scenerio's and code paths.
- Directed fuzzing against LAME vs a plethora of decoders in ffmpeg is probably more effective

**Comment by kcc** [comment]
Hi Guido. Yes, ship it! 
As usual, please try to get the upstream interested.
