### ISSUE TITLE
Permission issue on Monorail

### ISSUE THREAD

**Issue by randy408** [google/oss-fuzz#2258]
I can't view any issues assigned to me on Monorail.
e.g.: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13810
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=12527

> **Restricted**
> Only users with Commit permission can see this issue.

**Comment by inferno-chromium** [comment]
What is the error message you are getting ? Are you logging with `randy440088@gmail.com`

**Comment by randy408** [comment]
@inferno-chromium "Only users with Commit permission can see this issue.", all the messages are hidden. I am logged in with `randy440088 [at] gmail.com`.

**Comment by inferno-chromium** [comment]
I see your comment 3 hours ago on the monorail issues, so it does seem like you have access - https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13810#c2
similarly - https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=12527#c4

Can you tell the link which link you are clicking ? are you not able to access the monorail issue at all ?

**Comment by randy408** [comment]
My issue is limited to seeing messages, posting new messages is still possible. Image attached below:
![Screenshot from 2019-03-22 17-23-33](https://user-images.githubusercontent.com/33860634/54837735-76fce980-4cc7-11e9-8fc0-9a86f90eef00.png)
This is how all issues look to me.

**Comment by inferno-chromium** [comment]
so weird, so no comments, just blank :(

btw, till we figure this out, you can checkout crashes on https://oss-fuzz.com/testcases?project=libspng&showall=1

**Comment by inferno-chromium** [comment]
Is your randy440088 account an alias for some other email ?
I asked some other folks from my side to reproduce, but they can't. So, trying to understand why this is happening for you. Can you try in incognito in a new login session ?

**Comment by randy408** [comment]
It's a regular account. This seems to be limited to Firefox ESR, I can reproduce this on both Linux and Windows. With Firefox 66 and Chromium the search bar and comments are visible.

**Comment by inferno-chromium** [comment]
ah this is a monorail UI issue then, probably coming from their recent polymer 2 migration. Not anything related to OSS-Fuzz. Please file a bug at https://bugs.chromium.org/p/monorail/issues/entry.
