### ISSUE TITLE
Builds not updated

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#2265]
For the solidity project, we added two new fuzzers that are seemingly not picked up. The only indication I have (since the build logs seem to be stale) is that the oss-fuzz.com dashboard does not display the new fuzzers.

**Comment by inferno-chromium** [comment]
That builds page is stale due to https://github.com/google/oss-fuzz/issues/2263, but builds itself are getting triggered. @oliverchang is working on it, should be fixed sometime today. Regarding your build, it is broken, here is the log output, did you try running with check_build on various sanitizers. One of it is broken.

```
 ERROR: build step 4 "gcr.io/oss-fuzz/solidity" failed: exit status 2 I 
 ERROR I 
 Finished Step #4 I 
 Step #4: Makefile:370: recipe for target 'ossfuzz' failed I 
 Step #4: make: *** [ossfuzz] Error 2 I 
 Step #4: make[1]: *** [test/tools/ossfuzz/CMakeFiles/ossfuzz.dir/rule] Error 2 I 
 Step #4: CMakeFiles/Makefile2:934: recipe for target 'test/tools/ossfuzz/CMakeFiles/ossfuzz.dir/rule' failed I 
 Step #4: [ 90%] Built target solidity I 
 Step #4: [ 90%] Linking CXX static library libsolidity.a I 
 Step #4: [ 88%] Building CXX object libsolidity/CMakeFiles/solidity.dir/parsing/Parser.cpp.o I 
 Step #4: [ 88%] Building CXX object libsolidity/CMakeFiles/solidity.dir/parsing/DocStringParser.cpp.o I 
 Step #4: [ 88%] Building CXX object libsolidity/CMakeFiles/solidity.dir/interface/Version.cpp.o I 
 Step #4: [ 86%] Building CXX object libsolidity/CMakeFiles/solidity.dir/interface/StandardCompiler.cpp.o I 
 Step #4: [ 86%] Building CXX object libsolidity/CMakeFiles/solidity.dir/interface/Natspec.cpp.o I 
```

**Comment by bshastry** [comment]
Thank you for the update @inferno-chromium 

Quick question: Does broken build stall fuzzing on all targets or only those whose build failed?

After I created this issue, I could reproduce this locally but was surprised clusterfuzz didn't warn me earlier :)

**Comment by oliverchang** [comment]
This issue should now be fixed by https://github.com/google/oss-fuzz/pull/2285. 

To answer your question, yes a broken build of any fuzz target will usually block and fail the entire project build.
