### ISSUE TITLE
Known crash count on fuzzer stats is incorrect (racy, does not account for duplicates).

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#228]
@tanin47 is already working on this and completely rewriting the crash stats page and will hook the correct numbers into fuzzer stats, but filing this as fyi for others.

**Comment by inferno-chromium** [comment]
atleast we have the new page - oss-fuzz.com/v2/crash-stats, but need fuzzer stats have the right numbers and link to crash stats page.

**Comment by tanin47** [comment]
I'll take care of this next week. Thanks.

**Comment by inferno-chromium** [comment]
This is done, @kcc - fyi, numbers on fuzzer stats are now accurate and unique crashes. only total_crashes is raw count.
