### ISSUE TITLE
What to do with LAME?

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#2297]
LAME devs seem not receptive to idea of using oss-fuzz, and bugs I submitted manually via their bug tracker have not been responded to so far.

If you know anyone who would be willing to maintain LAME and address the bugs found by oss-fuzz (maybe Youtube people? IDK), then that could be an alternative. Otherwise, you may delete the LAME project from oss-fuzz. I was hoping to get a $1000 initial integration reward for this work, but alas.

**Comment by kcc** [comment]
I'd rather keep it working. If possible, please give links to your conversation with the lame folks here.

**Comment by guidovranken** [comment]
Conversation: https://sourceforge.net/p/lame/mailman/lame-dev/?viewmonth=201903

If it stays running, do I retain my eligibility for the initial integration reward?

**Comment by inferno-chromium** [comment]
Yes you will be still eligible for all the hard work you did to get fuzzing running on LAME.
