### ISSUE TITLE
Use revision numbers in oss-fuzz regression/fixed ranges

### ISSUE THREAD

**Issue by eugenis** [google/oss-fuzz#230]
Example:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=229#c5

"ClusterFuzz has detected this issue as fixed in range 201612281120:201612281335"

OSS-fuzz prints fix range in PST(!) timestamps. It would be nice to change that at least to UTC, or, better, to actual revision numbers.

I've also filed this request on monorail, but it got weird:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=352

**Comment by inferno-chromium** [comment]
If you click on link in link https://clusterfuzz-external.appspot.com/revisions?job=libfuzzer_asan_libass&range=201612281120:201612281335, it does give revisions.

regarding utc for build archive name, @mikea can you make that change on builder side. on clusterfuzz, we now use utc everywhere as well. for showing in ui, we convert to user's local time.

**Comment by mikea** [comment]
Can this revision number be included in the issue comment?

**Comment by kcc** [comment]
Ultimately, it would be nice to bisect to the precise revision. 
Not sure if this is feasible.

**Comment by inferno-chromium** [comment]
Regarding last comment, we are working on FindIt to guess the precise revision and show that as list of culprit.

Regarding UTC change, Mike already did it.

Regarding showing revision number, it is still better to show the clickable url (with more readable date range) and then when you click it show the various components and their git revision range. It can be more than 1 and that was the reason of keeping it simple with clickable url. E.g. check 2 components with range in https://clusterfuzz-external.appspot.com/revisions?job=libfuzzer_asan_gnutls&range=201612280211:201612280636&view=plain. If you disagree, reopen the issue.
