### ISSUE TITLE
Fuzz osquery

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2305]
@mhlakhani, do you know who might be a good contact to reach out to?

**Comment by mhlakhani** [comment]
@Dor1s I'm asking around, will get back to you on this one

**Comment by Dor1s** [comment]
Thanks a lot, @mhlakhani

**Comment by mhlakhani** [comment]
While I do that - is there any specific expectations of what you are looking for from a contact? That might also help get the right people onboard here.

**Comment by Dor1s** [comment]
Not really. I'd say whoever is working on the project at the moment and might be interested in finding vulnerabilities and stability issues :)

**Comment by mhlakhani** [comment]
@Dor1s It looks like they might not have bandwidth to pick this up in the short term unfortunately - might be worth posting on the github there to see if any of the open source contributors want to pick this up?

**Comment by Dor1s** [comment]
@mhlakhani thanks for checking! Yeah, creating an issue in their repo sounds like a good idea. We may also have some potentially interested devs here //cc @guidovranken

**Comment by guidovranken** [comment]
Thanks for the notification @Dor1s . Yeah I will do it for the $1000 integration bounty.

**Comment by guidovranken** [comment]
I've written a few fuzzers so far, will do a PR for them probably tomorrow

**Comment by guidovranken** [comment]
Here's what I have so far: https://github.com/guidovranken/osquery/tree/fuzzing/osquery/fuzzers

I can't make the PR because I struggle to get the build working on the OSS-Fuzz image; the build seems to crash with the older Python version included in the OSS-Fuzz Ubuntu image, I've been trying with PPA's but no luck yet.

**Comment by tomrittervg** [comment]
@guidovranken Do you still have your fuzzers?  It would probably be easy to integrate them at this point.
