### ISSUE TITLE
nondeterministic `-merge` implementation spoils fuzzer stats

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#231]
It seems that issue #227 is caused by existing `-merge` implementation. When we fuzz with a corpus subset, we usually get a huge number of new testcases. Then, when we merge them into existing corpus, it usually adds some significant number of files. For example:
1) I took xml_read_memory_fuzzer
2) its corpus contained 4152 files
3) I took 2 random files from the corpus
4) run the fuzzer for 120 seconds
5) the fuzzer generated ~1K new inputs
6) then I `merge` those new inputs into existing corpus and it added 10 new units, i.e. 4152 -> 4162

10 new units in 2 minutes! It doesn't sounds fair for our existing saturated corpus.

If I try to `merge` those 4162 files, I'm getting 4160. Next merge gives me 4159, and so on.

Because of that, we cannot calculate `new_units_added` stats when a corpus subset has been used for fuzzing. As a temporary solution, we will ignore new units stats for fuzzer runs over corpus subset.

**Comment by Dor1s** [comment]
To have a better evidence, I've just launched the fuzzer with two different corpuses (the existing one and its random subset of 2 items) for 3000 seconds. Then, I'll compare how many new units each of them merges and will update the issue.

**Comment by kcc** [comment]
Note that with -trace-pc-guard (#84) the merge *should* be deterministic

**Comment by Dor1s** [comment]
I should admit that my statement above can be wrong. Results of a 3000 seconds run:

* Fuzzing on **a full corpus** of 39876 files generated 5 new files. Then, **3 new files** have been merged into original corpus.

* Fuzzing on **a subset of 2 files** (from 39876) generated 3603 files. Then, **0 new files** have been merged into original corpus.

May be it's a bad luck, may be a completely wrong hypothesis. Let's wait for today's stats...

**Comment by inferno-chromium** [comment]
See https://github.com/google/oss-fuzz/issues/227#issuecomment-269864412, this was wrong file. Closing.
