### ISSUE TITLE
tpm2-tss build has some potentially invalid fuzz targets

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2310]
https://oss-fuzz.com/fuzzer-stats/by-fuzzer/fuzzer/libFuzzer/job/libfuzzer_asan_tpm2-tss

Looks like there are ~223 fuzz targets, but about half of them have an empty corpus, as they aren't able to discover any interesting coverage.

@pdxjohnny is that expected?

**Comment by pdxjohnny** [comment]
Ya I put them up there to make sure everything is working, I've been
meaning to go through and refactor but haven't had time yet.

**Comment by pdxjohnny** [comment]
update: I'll work on this next week

**Comment by jonathanmetzman** [comment]
@pdxjohnny Did you get time to look at this? Looks like it's still happening.
