### ISSUE TITLE
Openssl build now fails in Tor build script.

### ISSUE THREAD

**Issue by nmathewson** [google/oss-fuzz#2314]
It looks like the way we're building OpenSSL for Tor broke again in the past week or so.  When the script tries to produce a shared library, it gives all kinds of linker errors about missing asan symbols, such as:
{{{
Step #4: crypto/fips-dso-cryptlib.o: In function `OPENSSL_die':
Step #4: /src/openssl/crypto/cryptlib.c:421: undefined reference to `__asan_handle_no_return'
}}}

Has anybody else run into this kind of thing? The OpenSSL makefile and the hacky options that we pass to it are sufficiently complicated that I am not quite sure how to approach this myself.

**Comment by Dor1s** [comment]
A standalone openssl build is broken for more than a week as well: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14075

@kroeckx do you know what could've changed?

**Comment by kroeckx** [comment]
I've just filed https://github.com/openssl/openssl/issues/8735, which I think is the problem.

**Comment by nmathewson** [comment]
Thanks! I'll keep an eye on it.

**Comment by jonathanmetzman** [comment]
openssl/openssl#8749 landed but openssl and tor builds still failing.

**Comment by jonathanmetzman** [comment]
Recent envoy and Tor builds have been succeeding. @Dor1s I think this can be closed right?

**Comment by Dor1s** [comment]
Yes, Sir! Thanks!

**Comment by jonathanmetzman** [comment]
Sorry I meant to post the previous comment on #2315 but this issue can be closed too as openssl and tor builds have been succeeding.
