### ISSUE TITLE
Linking errors in some builds (e.g. envoy, openssl)

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2315]
e.g. envoy and openssl build are failing for a week with some linking issues. There was clang roll in Chromium around that time, so I'm going to revert the roll here in OSS-Fuzz and see what happens.

**Comment by Dor1s** [comment]
So, envoy build got fixed, but not OpenSSL :/

**Comment by jonathanmetzman** [comment]
I think envoy builds have failed to link since this change was made

**Comment by Dor1s** [comment]
Which change?

It succeeded after "[infra] Revert the recent clang roll to fix some builds (#2315). (#2316)" two times, than failed ones, then recovered, and now is broken with the following regression range:


ChangesChange LIB_FUZZING_ENGINE to -fsanitize=fuzzer in libFuzzer builds (detail / githubweb)[libical] Make sure to do an apt update before apt install (#2319) (detail / githubweb)[libxslt] Start with integration (#2320) (detail / githubweb)[libxslt] Update project.yaml: replace Chromium owner in auto_cc. (detail / githubweb)
--


Change LIB_FUZZING_ENGINE to -fsanitize=fuzzer in libFuzzer builds (detail / githubweb)
[libical] Make sure to do an apt update before apt install (#2319) (detail / githubweb)
[libxslt] Start with integration (#2320) (detail / githubweb)
[libxslt] Update project.yaml: replace Chromium owner in auto_cc. (detail / githubweb)

**Comment by jonathanmetzman** [comment]
The revert. I meant to say that the revert hasn't solved all of envoy's build problems (though it may have solved one of them). The latest builds are failing because of what I think is a linker OOM
Here's an excerpt from the logs:
```
 Step #12: clang-9: error: unable to execute command: Killed
 Step #12: clang-9: error: linker command failed due to signal (use -v to see invocation)
```

**Comment by jonathanmetzman** [comment]
The last build succeeded but I think the build will fail again randomly if this issue isn't solved (sorry for taking over this issue, this should probably moved).

**Comment by Dor1s** [comment]
Ha, interesting. Let me see if we can bump the RAM on the builder (I'm afraid we can't).

**Comment by Dor1s** [comment]
Yeah, we're using the most powerful machine type available (`N1_HIGHCPU_32`) and the only customizeable thing is the disk size.

**Comment by Dor1s** [comment]
@oliverchang may know if there are any possibilities :)

**Comment by Dor1s** [comment]
@htuch this workaround has been reverted, looks like envoy is the only project (maybe file is the second one, that's it) that is having troubles with a newer clang version, so I'm afraid this has to be fixed on envoy side, sorry :(

**Comment by jonathanmetzman** [comment]
@Dor1s for the record "file" build succeeds now, I'm not sure any other project failed because of this other than envoy.

**Comment by Dor1s** [comment]
Nice, thanks for checking!

**Comment by htuch** [comment]
OK, I see the build failures happening since this morning. I'll dig into this as time allows, thanks for the heads up.

**Comment by jonathanmetzman** [comment]
I think this can be closed as recent Tor and envoy builds have been succeeding.

**Comment by rlohning** [comment]
> Here's an excerpt from the logs:
> 
> ```
>  Step #12: clang-9: error: unable to execute command: Killed
>  Step #12: clang-9: error: linker command failed due to signal (use -v to see invocation)
> ```

I now get the same error (just with clang-11) in coverage builds of Qt. Is this something I need to fix in Qt? The comments above look like it's a problem with the platform.

**Comment by Dor1s** [comment]
@rlohning is it still happening for you? On our builder the coverage build is doing fine since June 9th.

**Comment by rlohning** [comment]
That doesn't necessarily mean the linking would work now. I had to remove the affected Qt submodule from oss-fuzz for other reasons: https://github.com/google/oss-fuzz/pull/3949

I'll try locally whether linking it succeeds now.

**Comment by rlohning** [comment]
When I revert https://github.com/google/oss-fuzz/pull/3949 I still get the same linker error.
