### ISSUE TITLE
Some projects cannot build with -fsanitize=fuzzer

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#2317]
**NOTE: Project maintainers please reach out if you have questions. Once we are ready for you to migrate I will contact a maintainer from each project.**

We are migrating libFuzzer builds to use `-fsanitize=fuzzer` instead of linking the fuzz targets against `/usr/lib/libFuzzingEngine.a`. This will give us performance benefits (see #2164 for more discussion).

We are starting this migration by making `LIB_FUZZING_ENGINE` by `-fsanitize=fuzzer` during libFuzzer builds.
Some projects that use `LIB_FUZZING_ENGINE` will break if we do this, these projects are:
```
llvm
librawspeed
strongswan
irssi
```
To prevent these projects from breaking we substituted their uses of `LIB_FUZZING_ENGINE` with `LIB_FUZZING_ENGINE_DEPRECATED` which will continue pointing to /usr/lib/libFuzzingEngine.a for the time being.
I will try to look at each of these projects individually to see if they can be fixed from the OSS-Fuzz side. But if not, I'd like the maintainers to please do this migration.

As a reminder, you can use the instructions [here](https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md#reproducing-build-failures) to reproduce a build failure.

For those who are curious, the performance benefits will come from not needing to instrument sanitizers in libFuzzer. This is necessary now but is not necessary using the complex build used for libFuzzer when built as part of clang. See [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=930446#c3) for a discussion of an actual case where a fuzz target is spending most of its time in libFuzzer.

**Comment by kcc** [comment]
@morehouse for llvm

**Comment by josephbisch** [comment]
I'm the person to contact for irssi. Probably needs to be fixed on the irssi side.

**Comment by jonathanmetzman** [comment]
> I'm the person to contact for irssi. Probably needs to be fixed on the irssi side.

Thanks Joseph.

**Comment by jonathanmetzman** [comment]
@micah-at-talos, @caolanm It looks like clamav and libreoffice are using `$LIB_FUZZING_ENGINE` in their build files outside of OSS-Fuzz in a way that breaks if `$LIB_FUZZING_ENGINE` is `-fsanitize=fuzzer`. Their builds are broken now as a result, sorry for that.
Can you replace usages of `LIB_FUZZING_ENGINE` with `LIB_FUZZING_ENGINE_DEPRECATED` in your build system as a temporary fix. Then at some point in the near future can make your projects work with `LIB_FUZZING_ENGINE` when it is `-fsanitize=fuzzer`

**Comment by micah-at-talos** [comment]
@jonathanmetzman Thanks for the heads up.  I'm just testing the change from `LIB_FUZZING_ENGINE` to `LIB_FUZZING_ENGINE_DEPRECATED` now.  It's a bit disappointing that `LIB_FUZZING_ENGINE` was reused for the `-fsanitize=fuzzer` CXXFLAG, but whatever works.  I'll put some more time into switching it to use `LIB_FUZZING_ENGINE` the new way later.  How much time do you reckon until the deprecated version goes away?

**Comment by jonathanmetzman** [comment]
@micah-at-talos 

>It's a bit disappointing that LIB_FUZZING_ENGINE was reused for the -fsanitize=fuzzer CXXFLAG, but whatever works

Sorry, I don't think this is ideal, but it seems like the best option for keeping integration simple and migrating 150+ projects.

>How much time do you reckon until the deprecated version goes away?

I suppose we can keep around `LIB_FUZZING_ENGINE_DEPRECATED` for as long as it is needed, meaning that so long as you are using it, we won't break it.
But I recommend switching to `LIB_FUZZING_ENGINE` for performance (and thus bug finding improvements).

**Comment by pauldreik** [comment]
Thanks for the heads up. I fixed it and pushed, but I am on vacation so wont be able to verify it for now. Is there perhaps an example of ideal integration with a cmake based project?
I am also curious how -fsanitize=fuzzer would improve perfomance over linking with libFuzzer.a?
Thanks,
Paul

**Comment by jonathanmetzman** [comment]
> Thanks for the heads up. I fixed it and pushed, but I am on vacation so wont be able to verify it for now.

Thanks for the fix. Last build succeeded!

>Is there perhaps an example of ideal integration with a cmake based project?

I can't think of one off the top of my head but I will try to look. I think LLVM might have be an ideal integration and I know it uses cmake, however it doesn't work with -fsanitize=fuzzer right now, so the integration isn't actually "ideal".

>I am also curious how -fsanitize=fuzzer would improve perfomance over linking with libFuzzer.a?

I'll add an explanation of this to the issue description. But currently we compile libFuzzer with sanitizers since it is necessary for MSAN and we've seen that not doing so can be problematic for ASAN. This actually can cause quite a bit of slowdown for a fuzz target. See [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=930446#c3) for a discussion of an actual case where a fuzz target is spending most of its time in libFuzzer.

**Comment by jonathanmetzman** [comment]
This isn't a problem any longer. We use the precompiled libFuzzer everywhere now after the PR: #4682
