### ISSUE TITLE
Upstream fuzzer stats collection to reduce hacky parsing of the logs

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2321]
The following stats might be upstreamed:

-    "max_len": the argument value that was used or auto-selected, libFuzzer prints it at the beginning of the run, but having it at the end would be much easier to parse
-    "edges_total": that's also printed at the beginning, can be include in the final stats to simplify the parsing
-    "feature_coverage": the latest "ft: XXX" value printed
-    "actual_duration": libFuzzer prints it as "Done 12345 runs in 777 second(s).", I'd like to have it easy parsable in the stats
-    "initial_edge_coverage": number of edges covered after reading the initial corpus (i.e. "INITED" line)
-    "slowest_unit_time_sec": if slow units were reported, how long the slowest one took to process
-    "edge_coverage": the latest edge coverage (i.e. "cov: XXX" value)
-    "slow_unit_count": how many slow units were reported
-    "initial_feature_coverage": the initial "ft: XXX" value
-    "timeout_limit": the "-timeout=" option that was used. Might be not necessary, as we usually control it and can record it ourselves.
-    "dict_used": whether the dictionary was used or not
-    "seed_corpus_rss": how much memory was used when reading the given corpus (i.e. "rss: XXXMb" value from the "INITED" line)

**Comment by jonathanmetzman** [comment]
Is `seed_corpus_rss` a useful metric? Maybe we should stop reporting it at all?

**Comment by Dor1s** [comment]
I guess it's helpful to understand why a target is OOMing, though I'm not sure we're leveraging that information right now.
