### ISSUE TITLE
Tips on debugging oom violations

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#2323]
Hello,

When a fuzzer reports an out-of-memory failure it is because a newly synthesized test case requested memory that tipped the total memory consumption of the fuzzing process at the time beyond the threshold maximum resident set size memory (which defaults to 2048 Mb).

oom can be unreproducible if the newly synthesized test case alone is insufficient to tip the maximum rss threshold. Do you have any tips to find out the reason allocated memory has been accumulating?

On a sidenote, why doesn't the LeakSanitizer flag the first instance of accumulated memory? I am somewhat confused because LS is otherwise good at flagging direct as well as indirect leaks but leaks leading to OOMs go undetected.

**Comment by kcc** [comment]
Not all cases of accumulated memory are leaks (e.g. if the target has a global state that grows over time).
Also, remember that ASAN tends to use more memory over time (due to its quarantine). 

Does oss-fuzz report OOMs that are not reproducible by running the input alone? 
(It probably shouldn't)

**Comment by inferno-chromium** [comment]
It will keep trying until it finds a reproducible bug. if it does not find one in 14 days, then it files a bug with that bad repo.
