### ISSUE TITLE
Incorrect coverage report

### ISSUE THREAD

**Issue by terrelln** [google/oss-fuzz#2330]
The zstd coverage report is not correct. For example, in `src/zstd/lib/compress/zstd_fast.c`, `ZSTD_compressBlock_fast_generic()` is shown as never executed, I'm certain that it is executed in some of the fuzzers. To be extra sure I ran the `simple_round_trip` fuzzer locally with an `assert(0);` in the function and it crashed as expected.

**Comment by Dor1s** [comment]
Thanks for your report. There is definitely something wrong with the merging of the reports. If I check results for the individual fuzz targets, I see some coverage for all of them, e.g.

https://storage.googleapis.com/oss-fuzz-coverage/zstd/fuzzer_stats/20190417/simple_round_trip.json

shows that `simple_round_trip.c` has 100% coverage, which is totally reasonable for the target function.

However, this directory clearly lacks coverage for some fuzz targets: https://storage.googleapis.com/oss-fuzz-coverage/zstd/reports/20190417/linux/src/zstd/tests/fuzz/report.html

Sadly, I don't see any issues reported in the logs. Will have to reproduce it and dig deeper. Thanks again!

**Comment by Dor1s** [comment]
Looks like this has regressed between

https://storage.googleapis.com/oss-fuzz-coverage/zstd/reports/20190411/linux/src/zstd/tests/fuzz/report.html

and

https://storage.googleapis.com/oss-fuzz-coverage/zstd/reports/20190412/linux/src/zstd/tests/fuzz/report.html

i.e. Apr 11-12th. We had a couple changes on that day (#2311 and #2316), but I don't really suspect either of those is a culprit (though it might be).

**Comment by terrelln** [comment]
I think it might have also been broken on 2019-04-11, since the `src/zstd/tests/fuzz/dictionary_decompress.c` file isn't even present in the report, even though the fuzzer is run.

I didn't notice the problem before I added the new fuzzers on April 10th, but I hadn't checked the coverage in quite some time, and didn't look too closely then.

**Comment by terrelln** [comment]
I checked the report [2019-04-09](https://storage.googleapis.com/oss-fuzz-coverage/zstd/reports/20190409/linux/report.html) and [2019-04-10](https://storage.googleapis.com/oss-fuzz-coverage/zstd/reports/20190410/linux/src/zstd/lib/decompress/report.html) and they are both the same, and both look correct.

The report on 2019-04-11 doesn't include any coverage for `dictionary_round_trip` or `dictionary_decompress`, but otherwise looks correct, though since those were newly added fuzzers, its possible they weren't run yet.

**Comment by Dor1s** [comment]
The problem is that some function(s) seem to have different binary code in different fuzz targets. That confuses llvm-cov when merging the coverage across binaries (e.g. if the same function has different structure, how we can merge it). The tool prints the warning and aborts the merge process after observing a modified function. If I exclude such cases, everything works fine, e.g.:

```
warning: /out/dumps/simple_round_trip.profdata: Function basic block count change detected (counter mismatch)
```

and

```
warning: /out/dumps/simple_decompress.profdata: Function basic block count change detected (counter mismatch)
```


without these two targets, I'm getting a correct report.

Usually this happens when different binaries with the same dependencies are compiled with different flags / options.

The most obvious thing to blame in zstd case is `ZSTD_STATIC_LINKING_ONLY` define which is declared in some targets, but not in all of them. I've tried adding `#define ZSTD_STATIC_LINKING_ONLY` to the following targets as well:

```
zstd_frame_info.c 
dictionary_round_trip.c 
dictionary_decompress.c 
simple_decompress.c 

root@6342b7c19ccc:/src/zstd/tests/fuzz# egrep ZSTD_STATIC_LINKING_ONLY `egrep -r LLVMFuzzer -l`
zstd_frame_info.c:#define ZSTD_STATIC_LINKING_ONLY
block_round_trip.c:#define ZSTD_STATIC_LINKING_ONLY
stream_round_trip.c:#define ZSTD_STATIC_LINKING_ONLY
block_decompress.c:#define ZSTD_STATIC_LINKING_ONLY
dictionary_round_trip.c:#define ZSTD_STATIC_LINKING_ONLY
simple_round_trip.c:#define ZSTD_STATIC_LINKING_ONLY
dictionary_decompress.c:#define ZSTD_STATIC_LINKING_ONLY
stream_decompress.c:#define ZSTD_STATIC_LINKING_ONLY
simple_decompress.c:#define ZSTD_STATIC_LINKING_ONLY
```

But still got the error. Do you know if there are any other differences that may lead to the different binary code produced for the same function(s)?

**Comment by Dor1s** [comment]
Also filed https://bugs.llvm.org/show_bug.cgi?id=41533 to discuss with LLVM devs, as I think we've hit this issue several times already and it's always hard to notice as the tool doesn't fail hard.

**Comment by terrelln** [comment]
The fuzzers should all be compiled with the same flags, `ZSTD_STATIC_LINKING_ONLY` just exposes extra declarations, and doesn't change anything in the build process. They are all built using exactly the same object files for the shared dependencies too. You can see the relevant part of the [Makefile](https://github.com/facebook/zstd/blob/dev/tests/fuzz/Makefile#L77), which shows all the object files compiled in the same way, and all the fuzzers compiled with the same flags and dependencies.

Does `build.sh` always get run with a clean image? The `Makefile` won't detect if flags change, and we don't run `make clean`, so if there are already prebuilt object files, it would behave weirdly.

Is there a way to tell what functions are messing it up manually?

**Comment by Dor1s** [comment]
> The fuzzers should all be compiled with the same flags, ZSTD_STATIC_LINKING_ONLY just exposes extra declarations, and doesn't change anything in the build process

Sorry, I wasn't super clear in my explanation. Use of different macro definitions may also lead to the issue, e.g. if you have:

```c
int foo(int bar) {
#ifdef SOMETHING
  return bar + 1;
#else
  if (bar > 0)
    return bar + 1;
  else
    return bar - 1;
#endif
}
```

That would also generate different code for the function and would mess up the merge process.

> Does build.sh always get run with a clean image? The Makefile won't detect if flags change, and we don't run make clean, so if there are already prebuilt object files, it would behave weirdly.

For the coverage job I believe the image is clean, yes. Anyhow, I was able to reproduce it locally after doing `rm -rf /out/*`.

> Is there a way to tell what functions are messing it up manually?

Yes, it's just not super convenient, but looks I'll have to do that :)

**Comment by terrelln** [comment]
`ZSTD_STATIC_LINKING_ONLY` is never used like that, it just exposes function declarations. There are other macros, like `ZSTD_MULTITHREAD` or `ZSTD_LEGACY_SUPPORT` which affect the code used, but AFAIK they are the same across all the builds.

> Yes, it's just not super convenient, but looks I'll have to do that :)

Thanks! If it's easier for you, I'm happy to look into it as well, if you can show me how.

**Comment by Dor1s** [comment]
I see, thanks for clarifying!

> Thanks! If it's easier for you, I'm happy to look into it as well, if you can show me how.

Thanks for offering that :) Debugging an issue like this usually involves running llvm-profdata (https://llvm.org/docs/CommandGuide/llvm-profdata.html) with different flags. In the worst case I have to add some printf-debugging to llvm-profdata.

So, for this case I've got the following info so far:

```
$ llvm-profdata merge -sparse \
    dumps/dictionary_decompress.profdata \
    dumps/simple_decompress.profdata \
    -j=1 -o 1.profdata 
dumps/simple_decompress.profdata: LLVMFuzzerTestOneInput: Function basic block count change detected (counter mismatch)
Make sure that all profile data to be merged is generated from the same binary.
```

Which is pretty confusing... I believe we account for the filename + function name, otherwise we wouldn't have a single correct report.

**Comment by Dor1s** [comment]
Another piece of information:

```
root@03c1ff553970:/out# llvm-profdata show -function=LLVMFuzzerTestOneInput dumps/simple_decompress.profdata              
Counters:
  LLVMFuzzerTestOneInput:
    Hash: 0x733e2e175c5637f4
    Counters: 6
    Function count: 3604
Instrumentation level: Front-end
Functions shown: 1
Total functions: 176
Maximum function count: 7389956
Maximum internal block count: 7387780
root@03c1ff553970:/out# llvm-profdata show -function=LLVMFuzzerTestOneInput dumps/dictionary_decompress.profdata
Counters:
  LLVMFuzzerTestOneInput:
    Hash: 0x733e2e175c5637f4
    Counters: 8
    Function count: 5786
Instrumentation level: Front-end
Functions shown: 1
Total functions: 410
Maximum function count: 430485367
Maximum internal block count: 430485367
root@03c1ff553970:/out# llvm-profdata show -function=LLVMFuzzerTestOneInput dumps/block_decompress.profdata
Counters:
  LLVMFuzzerTestOneInput:
    Hash: 0x42f0adf974af6282
    Counters: 5
    Function count: 2184
Instrumentation level: Front-end
Functions shown: 1
Total functions: 135
Maximum function count: 2673211
Maximum internal block count: 2505318
```

Looks like there is a Hash collision for `LLVMFuzzerTestOneInput` in `dictionary_decompress` and `simple_decompress`. That's the only pair that has an issue for that function:

```bash
$ for f in dumps/*.profdata; do echo $f && llvm-profdata show -function=LLVMFuzzerTestOneInput $f | egrep Hash; done
dumps/block_decompress.profdata
    Hash: 0x42f0adf974af6282
dumps/block_round_trip.profdata
    Hash: 0xbe0dd7cc9db8d8d5
dumps/dictionary_decompress.profdata
    Hash: 0x733e2e175c5637f4
dumps/dictionary_round_trip.profdata
    Hash: 0x6012e823e983fa0f
dumps/simple_decompress.profdata
    Hash: 0x733e2e175c5637f4
dumps/simple_round_trip.profdata
    Hash: 0xc226f4e0bf5fab53
dumps/stream_decompress.profdata
    Hash: 0x877908c1cad7b82b
dumps/stream_round_trip.profdata
    Hash: 0x7c157288b6c80b24
dumps/zstd_frame_info.profdata
```

Let me find what else is colliding.

**Comment by terrelln** [comment]
Wow they must be using a pretty terrible hash function to get a collision on 64 bytes of hash with only 10 inputs :(

**Comment by terrelln** [comment]
I ended up changing the `dictionary_decompress` and `simple_decompress` fuzzers a little bit last week, and the coverage report looks correct now, so the changes must've changed the hashes.

**Comment by Dor1s** [comment]
Haha, nice, thanks for the fix @terrelln! Sorry I was out on Friday. I still want to refresh in my memory what exactly is being hashed, so I'll leave this issue open for a little while.

**Comment by Dor1s** [comment]
Sorry, I couldn't get to this in a while. Also, there was a relevant discussion on llvm-dev mailing list a month ago: https://groups.google.com/d/msg/llvm-dev/Wp0pVlJmhqQ/qT5X_ap7BQAJ

So, what actually collides is probably `function’s structural hash` mentioned in https://llvm.org/docs/CoverageMappingFormat.html#function-record

It's also referenced in https://github.com/llvm-mirror/llvm/blob/6b547686c5410b7528212e898fe30fc7ee7a70a3/include/llvm/ProfileData/Coverage/CoverageMapping.h#L714

Which I believe is lower 64 bits of a MD5 hash, but the hash input is the functions profile data rather than a function name.
