### ISSUE TITLE
Bounties for improving fuzzers?

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#2334]
Will you provide a bounty/funding for improving existing fuzzers?

I can do the following:

- Compile C++ projects with ```-D_GLIBCXX_DEBUG```. This requires re-compilation of all dependencies like Boost. This feature can detect some real bugs that any of the sanitizers may not detect. I can give some examples if you want.
- Better MSAN usage. Memory sanitizer is normally only triggered if uninitialized memory is used for branching, not if it is copied over directly. If the output of a library function comprises non-branching data, it will not be detected by MemorySanitizer. Data can be checked for uninitialized bytes by writing it to /dev/null. Possibly there is an MSAN utility function for this.. This trick is featured in my [LAME fuzzer](https://github.com/guidovranken/LAME-fuzzers/blob/master/fuzzer-encoder.cpp)
- More code coverage. In my LAME fuzzer you can see that I use a technique that allows me to branch everywhere in the harness to select or deselect certain features, see ```ds.Get<bool>()``` for example. I can use this to call any amount of methods with any set of options to maximize the fuzzer's search space and code coverage.
- Serialization testing. For any bidirectional lossless serialization scheme, from base64 to lossless image compression, I can check if the output can convert back into the same input. This can find bugs with potentially severe effects (imagine JSON sent to an RPC server that the server interprets differently than the client intended..).

Also can you name some libraries that you want to run in oss-fuzz that will get me the $1000 integration bounty (even if there is no interest from the library maintainers..) ?

Thanks

**Comment by inferno-chromium** [comment]
Yes you can get the $1K integration rewards for new projects, see https://github.com/google/oss-fuzz/issues/402. We do encourage to try with library maintainers first. If there is no interest from maintainers, but the library is still critical for the OSS world, we still encourage OSS-Fuzz integration.

Regarding bounty for improving fuzzers, we would definitely consider this on a case-by-case basis. Especially we would take into account, how overall coverage improves with the changes and number of new bugs found. For the four classes you mentioned, esp -D_GLIBCXX_DEBUG, can you provide more detailed examples. Still, i think there can be numerous improvements, so we would consider those.

**Comment by guidovranken** [comment]
I will post examples for each of the 4 classes.
Here's the MemorySanitizer thing, other 3 will be posted later.

```cpp
#include <vector>
#include <stdlib.h>
#include <stdint.h>

static void encrypt(uint8_t* data, size_t size) {
    /* Uninitialized variable here */
    uint8_t c;

    for (size_t i = 0; i < size; i++) {
        data[i] ^= c;
    }
}

extern "C" {
void __msan_check_mem_is_initialized(const volatile void *x, size_t size);
}

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, const size_t size)
{
    std::vector<uint8_t> v(data, data + size);
    encrypt(v.data(), v.size());
    //__msan_check_mem_is_initialized(v.data(), v.size());
    return 0;
}
```
Image ```encrypt``` is a function in a library. It uses uninitialized memory, but it does not use this uninitialized memory for branching. Hence, it is not detected by default.
Uncomment the call to ```__msan_check_mem_is_initialized``` to detect it.
What I usually do is call a utility function ```memory_test()``` on all data output by the library, that in turn calls ```__msan_check_mem_is_initialized``` (or writes the data to /dev/null, which works too).

**Comment by guidovranken** [comment]
Serialization testing:

Lossless compression algorithms should decompress into the original input.
Base64 should decode into the original input.
JSON should parse into the original input.
etc

The following should always be true: ```deserialize(serialize(input)) == input```. If not, abort().

Without this guarantee, a number of bad things can happen, even without a malicious actor.

Imagine a payment API that receives transaction commands over HTTP and JSON, where the transaction encoded in JSON is authenticated via HTTP cookies.

If the client sends ```{'dollars_to_send' : 1}``` and the API backend decodes it as ```{'dollars_to_send' : 4294967296}``` due to a bug in its JSON decoder, that would be a problem. The transaction is already authenticated with HTTP cookies, so the API backend has no reason to doubt that it should send 4294967296 dollars.

This can also bring to light certain types of "uninitialized" memory not detected by MemorySantizer and other spurious data (through values retained in global/static variables, PRNGs, file/network data, pointer values, ...), for example in this case:

```cpp
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

static void encode_decode(uint8_t* data, size_t size) {
    static uint8_t key;

    for (size_t i = 0; i < size; i++) {
        data[i] ^= key;
        key = data[i];
    }
}

int main(void)
{
    for (size_t i = 0; i < 2; i++) {
        uint8_t data[] = {0x12};
        printf("Input:\n");
        for (size_t i = 0; i < sizeof(data); i++) {
            printf("%02X ", data[i]);
        }
        printf("\n");
        encode_decode(data, sizeof(data));
        printf("Output:\n");
        for (size_t i = 0; i < sizeof(data); i++) {
            printf("%02X ", data[i]);
        }
        printf("\n");
    }
}
```

Prints:

```
Input:
12 
Output:
12 
Input:
12 
Output:
00 
```

Even in something more innocuous than payment API's like PNG encoding/decoding, a mismatch would indicate something is amiss (without the sanitizers ever indicating a bug).

**Comment by guidovranken** [comment]
Can you spot the bug in the program below? The sanitizers can't.

```cpp
#include <vector>
#include <stdio.h>

struct S
{
    S() : it(v.end()) {}

    std::vector<int> v;
    mutable std::vector<int>::iterator it;
    const int* get_next() const
    {
        if (it == v.end()) {
            return nullptr;
        }
        return &(*(it++));
    }
    const int* get_first()
    {
        it = v.begin();
        return get_next();
    }

    void insert(const int& i)
    {
        v.push_back(i);
    }
};

int main(void)
{
    auto s = new S();
    s->insert(123);
    s->insert(555);
    s->get_first();
    auto t = new S(*s);
    const auto next = t->get_next();
    if ( next != nullptr ) {
        printf("%d\n", *next);
    }
    delete s;
    delete t;
    return 0;
}
```

The variable ```t``` is copy-constructed from the existing ```s```.
The ```S``` struct does not implement a copy constructor, and because ```t``` is a copy-constructed from ```S```, the compiler inserts an ad-hoc copy-constructor for ```S``` that copies over its member variables. This is a problem because it also copies over the iterator, so the ```it``` variable in ```t``` points to the ```v``` in ```s```, not ```t```.

If you ```delete s``` before ```t->get_next()```, ASAN will report UAF. But even without UAF it is still a bug because you generally don't want the iterator pointing to a random memory location other than the struct's own vector, even if that memory is (still) valid.

If an UAF doesn't transpire during fuzzing, this can be due to:

- The target's state space/code coverage has not been fully explored yet, but an UAF is technically possible.
- An UAF is not yet possible, but may be implemented in the future by random changes to the code that change the allocation/free order.

Compile with ```-D_GLIBCXX_DEBUG``` to get an early warning sign that something is wrong:

/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/debug/safe_iterator.h:505:
Error: attempt to compare iterators from different sequences.

```
Objects involved in the operation:
    iterator "lhs" @ 0x0xf73f58 {
      type = __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<int*, std::__cxx1998::vector<int, std::allocator<int> > >, std::__debug::vector<int, std::allocator<int> > > (mutable iterator);
      state = dereferenceable;
      references sequence with type 'std::__debug::vector<int, std::allocator<int> >' @ 0x0xf73e70
    }
    iterator "rhs" @ 0x0x7ffdae3db088 {
      type = __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<int const*, std::__cxx1998::vector<int, std::allocator<int> > >, std::__debug::vector<int, std::allocator<int> > > (constant iterator);
      state = past-the-end;
      references sequence with type 'std::__debug::vector<int, std::allocator<int> >' @ 0x0xf73f20
    }
Aborted (core dumped)
```

(and the solution to the bug is to implement a copy constructor that resets the iterator).

**Comment by guidovranken** [comment]
```-D_GLIBCXX_DEBUG``` also detects things like ```back()``` and ```front()``` on an empty containers like ```std::vector``` which MAY not be detected by any sanitizer if the container's internal storage array was previously initialized and expanded by insert operations, and then ```clear()```ed (meaning its internal item size set to 0, but not necessarily deleted/shrunk its internal array). Whether the sanitizers can detect this kinda depends on the container's specific implementation, but ```-D_GLIBCXX_DEBUG``` always detects this, and it's always a bug worth fixing.

**Comment by guidovranken** [comment]
The LAME API allows you to optionally set all kinds of fields with various values.
Here's the LAME ID3 setter in my fuzzer:

```cpp
void setID3(void) {
            /* Optionally set various ID3 fields */

            if ( ds.Get<bool>() ) {
                id3tag_init(flags);

                if ( ds.Get<bool>() ) {
                    const std::string title = ds.Get<std::string>();

                    Debug ? printf("id3tag_set_title(flags, %s);\n", title.c_str()) : 0;

                    id3tag_set_title(flags, title.c_str());
                }

                if ( ds.Get<bool>() ) {
                    const std::string artist = ds.Get<std::string>();

                    Debug ? printf("id3tag_set_artist(flags, %s);\n", artist.c_str()) : 0;

                    id3tag_set_artist(flags, artist.c_str());
                }

                if ( ds.Get<bool>() ) {
                    const std::string album = ds.Get<std::string>();

                    Debug ? printf("id3tag_set_album(flags, %s);\n", album.c_str()) : 0;

                    id3tag_set_album(flags, album.c_str());
}
```

Here I optionally use LAME's ID3 at all, optionally set the title, optionally set the artist, optionally set the album, etc. After all, a particular combination could expose a bug that setting all the fields would not.

```cpp
            while ( ds.Get<bool>() ) {
                const auto data = ds.GetData(0);

                /* Round to a multiple of sizeof(T) */
                const size_t copySize = data.size() - (data.size() % sizeof(T));

                std::vector<T> toInsert;
                toInsert.resize( data.size() / sizeof(T) );

                memcpy(toInsert.data(), data.data(), copySize);

                /* Correct NAN values */
                for (size_t i = 0; i < toInsert.size(); i++) {
                    if ( isNAN(toInsert[i]) ) {
                        /* If NaN, set to default value (0.0) */
                        toInsert[i] = {};
                    }
                }

                inDataV.push_back(toInsert);
}
```

Here I get a buffer of a random size and repeat this process a random number of times.
These are the chunks that are fed to to the LAME encoder.
Why not just feed the encoder 1 big chunk at once like most fuzzers would do? Because there may be subtle bugs that only can transpire in chunked encoding.
This pattern is also heavily featured in my crypto fuzzers, because there have been bugs in ciphers that only manifested when cleartext was fed in specific chunks.

The ```ds``` variable is an interface for getting basic types like bools and strings from the fuzzer input. If it is out of data, it throws an exception that is caught in ```LLVMFuzzerTestOneInput```.

It's similar to using Protobufs for fuzzing I guess, but I like this method more.

Protobufs or this method allow for very versatile fuzzing of complex API's.

**Comment by guidovranken** [comment]
@inferno-chromium does this clear things up?

**Comment by guidovranken** [comment]
My general point is that there are many ways to improve fuzzing of targets that currently only have simple 5 line harnesses, apart from code coverage alone. If you have any project in mind that would benefit from an "extreme fuzzing" treatment, let me know, you can also contact me privately about this.

**Comment by oliverchang** [comment]
re `D_GLIBCXX_DEBUG`, we only support libc++. libc++ might have a different macro that turns on additional checks though.
