### ISSUE TITLE
Cryptofuzz cannot build with LIB_FUZZING_ENGINE

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#2336]
After I build Cryptofuzz locally and I run it against a seed corpus I get

```
Thread 1 "cryptofuzz-open" received signal SIGSEGV, Segmentation fault.
0x00007ffff72022d8 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) bt
#0  0x00007ffff72022d8 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00007ffff7203352 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#2  0x00007ffff720496b in _Unwind_RaiseException () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#3  0x00000000007d2807 in __cxa_throw ()
#4  0x000000000051478b in fuzzing::datasource::Datasource::get(unsigned long, unsigned long, unsigned long) () at fuzzing-headers/include/fuzzing/datasource/datasource.hpp:148
#5  0x00000000005133f5 in bool fuzzing::datasource::Base::Get<bool>(unsigned long) () at fuzzing-headers/include/fuzzing/datasource/datasource.hpp:52
#6  0x000000000052663e in cryptofuzz::module::CTX_Copier<evp_md_ctx_st>::copy() () at ./module_internal.h:19
#7  0x000000000051d826 in cryptofuzz::module::OpenSSL::OpDigest(cryptofuzz::operation::Digest&) () at module.cpp:932
#8  0x00000000004c99e2 in cryptofuzz::ExecutorBase<cryptofuzz::Buffer, cryptofuzz::operation::Digest>::callModule(std::__1::shared_ptr<cryptofuzz::Module>, cryptofuzz::operation::Digest&) const ()
    at executor.cpp:33
#9  0x00000000004c8f14 in cryptofuzz::ExecutorBase<cryptofuzz::Buffer, cryptofuzz::operation::Digest>::Run(fuzzing::datasource::Datasource&, unsigned char const*, unsigned long) const ()
    at executor.cpp:486
#10 0x00000000004c3e9d in cryptofuzz::Driver::Run(unsigned char const*, unsigned long) const () at driver.cpp:39
#11 0x000000000050a975 in LLVMFuzzerTestOneInput () at entry.cpp:32
#12 0x0000000000455245 in ExecuteCallback () at /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:529
#13 0x0000000000454c36 in RunOne () at /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:453
#14 0x0000000000456c3f in ReadAndExecuteSeedCorpora () at /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:755
#15 0x0000000000456fa6 in Loop () at /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:779
#16 0x000000000044854b in FuzzerDriver () at /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:776
#17 0x000000000046ea43 in main () at /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19
```

This happens with both ASAN and UBSAN and if I run the binary directly and when I run ```infra/helper.py run_fuzzer cryptofuzz cryptofuzz-openssl```, and for all fuzzer binaries.

Just half a day ago this still worked. As you can see in the backtrace it happens when an exception is thrown. It doesn't happen because the exception isn't caught, but even if that were the case, the output would be different.

I've pruned my Docker cache and tried building from scratch (build_image + build_fuzzers) several times.

When I build my fuzzers "manually", no error occurs.

Did you change anything? The error could be on my end due to local software updates but I'm not sure. Does it crash for you too?

**Comment by inferno-chromium** [comment]
@jonathanmetzman - could this be related to https://github.com/google/oss-fuzz/issues/2328#issuecomment-483882437

**Comment by jonathanmetzman** [comment]
Very possible. Can you compile with -lFuzzingEngine or $LIB_FUZZING_ENGINE_DEPRECATED instead of $LIB_FUZZING_ENGINE

**Comment by guidovranken** [comment]
> Very possible. Can you compile with -lFuzzingEngine or $LIB_FUZZING_ENGINE_DEPRECATED instead of $LIB_FUZZING_ENGINE

Replacing LIB_FUZZING_ENGINE with LIB_FUZZING_ENGINE_DEPRECATED solves the problem.

**Comment by guidovranken** [comment]
Just in case it's relevant, Cryptofuzz uses ```-std=c++17```, not sure about jsonnet.

**Comment by guidovranken** [comment]
I'm about to push an unrelated PR for Cryptofuzz -- should I also replace LIB_FUZZING_ENGINE with LIB_FUZZING_ENGINE_DEPRECATED ?

**Comment by jonathanmetzman** [comment]
Sure go ahead. Can you please add a comment containing this text: "TODO(metzman): Switch this to LIB_FUZZING_ENGINE when it works."

**Comment by morehouse** [comment]
Should be able to switch back to `LIB_FUZZING_ENGINE` after rolling past r359218.

**Comment by jonathanmetzman** [comment]
I moved cryptofuzz over to LIB_FUZZING_ENGINE in #2359. It passes check_build now.
