### ISSUE TITLE
Build logs seem to be unavailable

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#2349]
Looks like something happened to the page where build logs are shown. Below is what I see when I visit https://oss-fuzz-build-logs.storage.googleapis.com/index.html:
![Screenshot 2019-04-26 at 12 50 08](https://user-images.githubusercontent.com/10195800/56799637-ff6c2e00-6821-11e9-9e79-ce16d665a2d0.png)

**Comment by inferno-chromium** [comment]
My regression, just fixed it. Sorry!
