### ISSUE TITLE
How to access detailed reports of publicly-viewable fixed bugs?

### ISSUE THREAD

**Issue by z3str** [google/oss-fuzz#2350]
Hi, I was trying to see the crash location in the source code. I was hoping to find the source file name and line number in the detailed report. However, it seems I don't have the accesses to those reports. 

I was wondering if the detailed reports are viewable by the public. If not, would it be possible I could apply for the access to the detailed reports of fixed bugs somehow? (I checked the docs but didn't find the guidelines. Apologies if I missed something) 

For example, if I go to a bug report like [this one](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=165&can=1&q=-status%3AWontFix%2CDuplicate%20-Infra&colspec=ID%20Type%20Component%20Status%20Proj%20Reported%20Owner%20Summary) and click [the detailed report link](https://clusterfuzz-external.appspot.com/testcase?key=4890595495510016). I got the following error:

```
You (email=zyh1121@gmail.com) are not authorized to access this page!

Please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.

Switch account
Logout

OSS-Fuzz is an effort to provide continuous fuzzing infrastructure for open-source software. You can read more about it here: https://github.com/google/oss-fuzz.
```

**Comment by inferno-chromium** [comment]
Maybe regressed after https://github.com/google/clusterfuzz/commit/7a16ece8c2b388e518c9ffb97b5b97226f4bf7f2.  @oliverchang - can you please take a look.

**Comment by oliverchang** [comment]
Hi. Detailed reports are not publicly viewable even after being fixed. The reproducer however, is available so you should be able to run it locally yourself.

**Comment by inferno-chromium** [comment]
Just fyi, reproducer link is this one in comment#0 of bug.

Minimized Testcase (0.41 Kb): https://clusterfuzz-external.appspot.com/download/.......
