### ISSUE TITLE
"This browser is not supported or 3rd party cookies and data may be disabled."

### ISSUE THREAD

**Issue by LebedevRI** [google/oss-fuzz#2353]
It is no longer possible to log into oss-fuzz.com with "Block third-party cookies" setting enabled.
Can this please be fixed?

**Comment by inferno-chromium** [comment]
I think this might be coming after our recent move to Firebase for auth (https://github.com/google/clusterfuzz/commit/7a16ece8c2b388e518c9ffb97b5b97226f4bf7f2), which will soon allow things like logging with github, twitter, etc account and not just google account as a sign in.
https://github.com/firebase/firebaseui-web/issues/444

Given the benefits it provides, we might not be able to do this. Assigning to @oliverchang to make final call.

**Comment by LebedevRI** [comment]
Somehow this is the first time i have encountered this issue.
If i were to guess, i'd say there is some better way, that does not require
users to give up their privacy by disabling that setting for 3rd party cookies..

**Comment by oliverchang** [comment]
Unfortunately, according to https://github.com/firebase/firebaseui-web/issues/444 this is not possible :/

**Comment by LebedevRI** [comment]
This is a *serious* limitation, will be basically a show-stopper for many.

**Comment by inferno-chromium** [comment]
Well, being restricted to google as sign in provider was a stopshopper for many as well. This helps us support auth providers like Github, Facebook, Twitter, phones, etc.

**Comment by LebedevRI** [comment]
Sure.
But is this error limited to only the google auth,
or will the same happen for every other new auth provider?

**Comment by inferno-chromium** [comment]
only google auth if you are using google account, you can selectively enable oss-fuzz.com and clusterfuzz-external.firebaseapp.com

**Comment by aawc** [comment]
In fact, just `https://cluster-fuzz.firebaseapp.com` is sufficient.

**Comment by inferno-chromium** [comment]
for oss-fuzz, domain is different - it will be `clusterfuzz-external.firebaseapp.com`

**Comment by oliverchang** [comment]
Third party cookies should no longer be necessary here for oss-fuzz.com. Could you please try again? @LebedevRI

**Comment by LebedevRI** [comment]
Yep, it appears to work now, thanks!

**Comment by LebedevRI** [comment]
(i suppose i should have closed it, at least for the moment)
