### ISSUE TITLE
Fuzzers run with `helper.py run_fuzzer` seem to keep going even when MSan is complaining about "use-of-uninitialized-value"

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#2357]
A couple of weeks ago I ran the fuzzer being introduced in https://github.com/systemd/systemd/pull/12230 manually with `./infra/helper.py run_fuzzer --sanitizer=memory systemd fuzz-varlink` and it crashed with
```
==27==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f4a219d8c08 in varlink_write /work/build/../../src/systemd/src/shared/varlink.c:407:21
    #1 0x7f4a219d7f12 in varlink_process /work/build/../../src/systemd/src/shared/varlink.c:877:13
    #2 0x7f4a219eacb1 in defer_callback /work/build/../../src/systemd/src/shared/varlink.c:1723:16
    #3 0x7f4a21db046b in source_dispatch /work/build/../../src/systemd/src/libsystemd/sd-event/sd-event.c
    #4 0x7f4a21daf0f2 in sd_event_dispatch /work/build/../../src/systemd/src/libsystemd/sd-event/sd-event.c:3234:21
    #5 0x7f4a21db196d in sd_event_run /work/build/../../src/systemd/src/libsystemd/sd-event/sd-event.c:3291:21
    #6 0x7f4a21db249c in sd_event_loop /work/build/../../src/systemd/src/libsystemd/sd-event/sd-event.c:3313:21
    #7 0x49bf73 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-varlink.c:122:9
    #8 0x508e6d in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:529:15
    #9 0x49f0a0 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:286:6
    #10 0x4aff7c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:715:9
    #11 0x49e1a0 in main /src/libfuzzer/FuzzerMain.cpp:19:10
    #12 0x7f4a2079e82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #13 0x4201d8 in _start (/out/fuzz-varlink+0x4201d8)

  Uninitialized value was created by a heap allocation
    #0 0x44bc1d in __interceptor_malloc /src/llvm/projects/compiler-rt/lib/msan/msan_interceptors.cc:911:3
    #1 0x7f4a207fad06 in _IO_str_overflow (/lib/x86_64-linux-gnu/libc.so.6+0x7cd06)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /work/build/../../src/systemd/src/shared/varlink.c:407:21 in varlink_write
```
Today I downloaded the latest images using `sudo ./infra/helper.py pull_images` and ran the fuzzer again. The warning is still there but it keeps going as though nothing happened.

**Comment by Dor1s** [comment]
//cc @jonathanmetzman @morehouse

**Comment by evverx** [comment]
By the way, passing `MSAN_OPTIONS=halt_on_error=1` to the fuzzer manually seems to make it crash but I can't remember doing it explicitly ever before.

**Comment by jonathanmetzman** [comment]
Looking into this. I'm not convinced this is related to the changes i've made recently as there have been some msan bugs found recently https://oss-fuzz.com/testcase-detail/5717618784206848

**Comment by jonathanmetzman** [comment]
I wasn't able to reproduce this with that testcase. My best idea for what is going on here is that the problem is systemd specific.

**Comment by jonathanmetzman** [comment]
I can't reproduce this with https://oss-fuzz.com/testcase-detail/5717618784206848

**Comment by evverx** [comment]
It could be systemd-specific in the sense that that particular fuzzer somehow triggers something weird (which can't be triggered by a simple five-line fuzzer triggering "use-of-uninitialized-value" I've just written). But the fact that `MSAN_OPTIONS=halt_on_error=1` somehow gets MSan+libFuzzer to work as expected makes me think that it has something to do with clang/MSan/libFubfuzzer. I also just built the fuzzer with "clang version 7.0.1 (Fedora 7.0.1-6.fc29)" shipped on Fedora 29 and it crashes as soon as it starts:
```sh
$ ./out/fuzz-varlink test/fuzz/fuzz-varlink/
INFO: Seed: 1576677495
INFO: Loaded 2 modules   (41206 inline 8-bit counters): 41149 [0x7f0d6c631938, 0x7f0d6c63b9f5), 57 [0x510c80, 0x510cb9),
INFO: Loaded 2 PC tables (41206 PCs): 41149 [0x7f0d6c63b9f8,0x7f0d6c6dc5c8), 57 [0x4ee020,0x4ee3b0),
INFO:        7 files found in test/fuzz/fuzz-varlink/
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 10014 bytes
INFO: seed corpus: files: 7 min: 5b max: 10014b total: 20667b rss: 44Mb
Uninitialized bytes in __interceptor_send at offset 10073 inside [0x729000000000, 10074)
==7374==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f0d6c1d6815 in varlink_write /home/vagrant/systemd-test/build/../src/shared/varlink.c:407:21
    #1 0x7f0d6c1d5ee2 in varlink_process /home/vagrant/systemd-test/build/../src/shared/varlink.c:877:13
    #2 0x7f0d6c1e2d6d in defer_callback /home/vagrant/systemd-test/build/../src/shared/varlink.c:1723:16
    #3 0x7f0d6c47fbe2 in source_dispatch /home/vagrant/systemd-test/build/../src/libsystemd/sd-event/sd-event.c
    #4 0x7f0d6c47ed78 in sd_event_dispatch /home/vagrant/systemd-test/build/../src/libsystemd/sd-event/sd-event.c:3234:21
    #5 0x7f0d6c480a3c in sd_event_run /home/vagrant/systemd-test/build/../src/libsystemd/sd-event/sd-event.c:3291:21
    #6 0x7f0d6c481267 in sd_event_loop /home/vagrant/systemd-test/build/../src/libsystemd/sd-event/sd-event.c:3313:21
    #7 0x4d0a17 in LLVMFuzzerTestOneInput /home/vagrant/systemd-test/build/../src/fuzz/fuzz-varlink.c:122:9
    #8 0x435b9d in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/vagrant/systemd-test/out/fuzz-varlink+0x435b9d)
    #9 0x436b25 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) (/home/vagrant/systemd-test/out/fuzz-varlink+0x436b25)
    #10 0x4399be in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, fuzzer::fuzzer_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (/home/vagrant/systemd-test/out/fuzz-varlink+0x4399be)
    #11 0x43b1a6 in fuzzer::Fuzzer::Loop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, fuzzer::fuzzer_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (/home/vagrant/systemd-test/out/fuzz-varlink+0x43b1a6)
    #12 0x42ae97 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/vagrant/systemd-test/out/fuzz-varlink+0x42ae97)
    #13 0x41eaf6 in main (/home/vagrant/systemd-test/out/fuzz-varlink+0x41eaf6)
    #14 0x7f0d6bbca412 in __libc_start_main (/lib64/libc.so.6+0x24412)
    #15 0x41eb2d in _start (/home/vagrant/systemd-test/out/fuzz-varlink+0x41eb2d)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/vagrant/systemd-test/build/../src/shared/varlink.c:407:21 in varlink_write
Exiting
MS: 0 ; base unit: 0000000000000000000000000000000000000000
artifact_prefix='./'; Test unit written to ./crash-8298e7eafaa1977eb214120280b27110b63a613f
```

**Comment by evverx** [comment]
On the bright side, that MSan report looks like a false positive so in a sense it's kind of useful that the fuzzer keeps fuzzing :-)

**Comment by evverx** [comment]
Could it be that it's `-fsanitize-recover=memory` injected in [msan_build.py](https://github.com/google/oss-fuzz/blob/7d2884aaeaa04275b71ac5b9d035f0e13c4c82fb/infra/base-images/base-msan-builder/msan_build.py#L41) that kicks in and prevents the fuzzer from crashing?

**Comment by evverx** [comment]
It has just been reported by ClusterFuzz in https://oss-fuzz.com/testcase-detail/5730863070838784.

**Comment by evverx** [comment]
I've just downloaded the latest images (with clang version 9.0.0 (trunk 360094)). `./infra/helper.py reproduce` exits with 77 but `./infra/helper.py run_fuzzer` keeps fuzzing although there is a file in the corpus triggering the issue. I'm not sure what to do about it. I suppose I can live with that.

**Comment by inferno-chromium** [comment]
So, ClusterFuzz does not use infra/helper.py and we easily detect sanitizer signatures even if the binary does not exist. So, it does not impact ClusterFuzz. We can improve this in infra/helper.py, so reopening.

**Comment by evverx** [comment]
As much as I appreciate awesome bugs ClusterFuzz finds, I kind of hope some day it will stop discovering them after they all go away (though I realize it isn't going to happen) :-)

I closed the issue because I wasn't sure it can be fixed on the OSS-Fuzz side (apart from setting MSAN_OPTIONS=halt_on_error=1, which looks like a stopgap to me) but if it's OK to keep it open here anyway, then so be it. Thank you!

**Comment by inferno-chromium** [comment]
I think code reaches a point of stability in some time, after that it finds only minor regressions which are much simpler to fix (since you just wrote that code).

**Comment by evverx** [comment]
I think in general it depends on projects being fuzzed. While it's true that over time it's usually easier to fix bugs because they're relatively new (that is, the knowledge of why code is written that way isn't completely faded :-)), unfortunately it doesn't prevent some projects from introducing more bugs than before (as far as I know, `syzbot` (last time I checked) showed a very sad trend. Which is, of course, not to say that everyone is doomed :-) It's just the way it is for now and it's undoubtedly better to fuzz code and be aware of dynamics (however bad they may be).

**Comment by evverx** [comment]
If it's still reproducible, I'm pretty sure it should be fixed on the MSan side. I don't think it makes much sense to keep it open here.
