### ISSUE TITLE
-fsanitize=fuzzer resulting in "invalid origin" crashes in MSAN

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#2369]
For example in [this testcase](https://oss-fuzz.com/testcase-detail/5735452293726208), there is a crash because [this line](https://github.com/the-tcpdump-group/libpcap/blob/d00d99d143a3be2dc87e3cd142cb6f6bf7bb17e0/testprogs/fuzz/fuzz_filter.c#L22) supposedly uses uninitialized-memory.

More examples:
https://oss-fuzz.com/testcase?key=5674747897053184
https://oss-fuzz.com/testcase-detail/5681075289849856

These were the only 3 examples I could find. I may need to revert #2325

**Comment by jonathanmetzman** [comment]
cc @inferno-chromium @morehouse @kcc

**Comment by jonathanmetzman** [comment]
The testcase in https://oss-fuzz.com/testcase-detail/5735452293726208 is also definitely incorrect.
The stacktrace says https://github.com/the-tcpdump-group/libpcap/blob/d00d99d143a3be2dc87e3cd142cb6f6bf7bb17e0/testprogs/fuzz/fuzz_both.c#L62 uses uninitialized memory which seems impossible.

**Comment by jonathanmetzman** [comment]
https://oss-fuzz.com/testcase-detail/5674747897053184 and https://oss-fuzz.com/testcase-detail/5735452293726208 can't repro the issue after I moved them back to -lFuzzingEngine, so this crash was caused by -fsanitize=fuzzer.

**Comment by morehouse** [comment]
I made some changes to the build.sh so I could build locally and couldn't repro.  My guess is this has something to do with OSS-Fuzz flags.

My build.sh is:
```bash
export CC=clang
export CXX=clang++
export CFLAGS="-fsanitize=memory,fuzzer-no-link"
export CXXFLAGS="$CFLAGS"
#export LIB_FUZZING_ENGINE=$HOME/code/fuzzer/libFuzzer.a
export LIB_FUZZING_ENGINE=-fsanitize=fuzzer
export SRC=$PWD
export OUT=$PWD/out

cd libpcap
# build project
git apply ../patch.diff

rm -rf build
mkdir build
cd build
cmake ..
make


# build fuzz targets
for target in pcap filter both
do
    $CC $CFLAGS -I.. -c ../testprogs/fuzz/fuzz_$target.c -o fuzz_$target.o
    $CXX $CXXFLAGS -ldbus-1 fuzz_$target.o -o $OUT/fuzz_$target libpcap.a $LIB_FUZZING_ENGINE
done

# export other associated stuff
cd ..
cp testprogs/fuzz/fuzz_*.options $OUT/
# builds corpus
cd $SRC/tcpdump/
zip -r fuzz_pcap_seed_corpus.zip tests/
cp fuzz_pcap_seed_corpus.zip $OUT/
cd $SRC/libpcap/testprogs/BPF
mkdir corpus
ls *.txt | while read i; do tail -1 $i > corpus/$i; done
zip -r fuzz_filter_seed_corpus.zip corpus/
cp fuzz_filter_seed_corpus.zip $OUT/
```

**Comment by morehouse** [comment]
Interesting development...  I can reproduce with `-O1` added to `CFLAGS`, but not with `-O0`, `-O2`, or `-O3`.

**Comment by jonathanmetzman** [comment]
>Interesting development... I can reproduce with -O1 added to CFLAGS, but not with -O0, -O2, or -O3.

Super interesting find.

>I made some changes to the build.sh so I could build locally and couldn't repro. My guess is this has something to do with OSS-Fuzz flags.

Do you still think this? Do you mean compilation flags? Does this mean we are doing something wrong or that we are using some combo flags that isn't being handled properly?

**Comment by morehouse** [comment]
I hope to look more today.  I don't think the flags are wrong, just that the bug only repros with `-O1`, which OSS-Fuzz uses.

**Comment by morehouse** [comment]
We have run into an issue caused by not instrumenting libFuzzer with MSan.

When we instrument libfuzzer we get something like this:
```
Fuzzer::ExecuteCallback:
  ...
  # Store shadow for Data and Size to TLS
  call LLVMFuzzerTestOneInput

LLVMFuzzerTestOneInput:
  # Load shadow for Data and Size from TLS
```

But since `-fsanitize=memory,fuzzer` does not instrument libFuzzer with MSan, we end up with this:

```
Fuzzer::ExecuteCallback:
  ...
  call __msan_unpoison(Data, Size)  # Unpoisons the memory pointed to by Data, but not Data or Size themselves
  call LLVMFuzzerTestOneInput

LLVMFuzzerTestOneInput:
  # Load shadow for Data and Size from TLS
```

So instead of `LLVMFuzzerTestOneInput` loading the shadow for `Data` and `Size`, it ends up loading whatever happens to be left in TLS from previous calls.

@eugenis:  Is there a way we can manually unpoison the TLS shadow for these two parameters?

**Comment by eugenis** [comment]
On Tue, May 7, 2019 at 1:21 PM Matt Morehouse <notifications@github.com>
wrote:

> We have run into an issue caused by not instrumenting libFuzzer with MSan.
>
> When we instrument libfuzzer we get something like this:
>
> Fuzzer::ExecuteCallback:
>   ...
>   # Store shadow for Data and Size to TLS
>   call LLVMFuzzerTestOneInput
>
> LLVMFuzzerTestOneInput:
>   # Load shadow for Data and Size from TLS
>
> But since -fsanitize=memory,fuzzer does not instrument libFuzzer with
> MSan, we end up with this:
>
> Fuzzer::ExecuteCallback:
>   ...
>   call __msan_unpoison(Data, Size)  # Unpoisons the memory pointed to by Data, but not Data or Size themselves
>   call LLVMFuzzerTestOneInput
>
> LLVMFuzzerTestOneInput:
>   # Load shadow for Data and Size from TLS
>
> So instead of LLVMFuzzerTestOneInput loading the shadow for Data and Size,
> it ends up loading whatever happens to be left in TLS from previous calls.
>
> @eugenis <https://github.com/eugenis>: Is there a way we can manually
> unpoison the TLS shadow for these two parameters?
>
See COMMON_INTERCEPTOR_UNPOISON_PARAM in msan_interceptors.cc.
I thought we decided to build libfuzzer with msan some time ago?

**Comment by morehouse** [comment]
We did, but now that libFuzzer has its own private libc++, we're trying to avoid building it with MSan.  This simplifies `-fsanitize=memory,fuzzer` and has performance benefits.

**Comment by morehouse** [comment]
I've landed a fix in https://reviews.llvm.org/D61751 and https://reviews.llvm.org/D61753.

Once we're rolled past r360390, these false positives should go away.

**Comment by jonathanmetzman** [comment]
r360398 is the revision closest in to that revision that has [built successfully on Chrome's build bots](https://ci.chromium.org/p/chromium/builders/ci/ToTLinuxASanLibfuzzer/3431). Will roll to that on Monday.

**Comment by jonathanmetzman** [comment]
I had to revert the roll in #2408

**Comment by jonathanmetzman** [comment]
This is blocking #2164

**Comment by jonathanmetzman** [comment]
I think clang rolled [upstream](https://bugs.chromium.org/p/chromium/issues/detail?id=965768) to r362913, uptaking this fix, so this should be fixed in OSS-Fuzz.
