### ISSUE TITLE
BAD BUILD: fuzzer does not seem to be compiled with UBSan.

### ISSUE THREAD

**Issue by bblanchon** [google/oss-fuzz#2374]
Hi!

[ArduinoJson's build started to fail](https://oss-fuzz-build-logs.storage.googleapis.com/log-8c4a8be8-d300-4665-b9ac-59c5a8d9bf1d.txt) but I didn't change anything recently.

```
Starting Step #22
Step #22: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #22: INFO: performing bad build checks for /workspace/out/undefined/json_fuzzer.
Step #22: INFO: performing bad build checks for /workspace/out/undefined/msgpack_fuzzer.
Step #22: Broken fuzz targets (1):
Step #22: msgpack_fuzzer:
Step #22: BAD BUILD: /workspace/out/undefined/msgpack_fuzzer does not seem to be compiled with UBSan.
Step #22: ERROR: 50% of fuzz targets seem to be broken. See the list above for a detailed information.
Finished Step #22
```

It complains about only one of the two fuzzers (msgpack_fuzzer), but both are compiled the same way (same command line options).

Any clue what that might be?

Best Regards,
Benoit

**Comment by jonathanmetzman** [comment]
Maybe the clang roll caused this issue to manifest, but I suspect the real "problem" here is not the roll but that our bad build check is too sensitive and thinks a target wasn't instrumented when it was in fact.
Looking into this.

**Comment by jonathanmetzman** [comment]
Builds started failing at 9:07 AM on April 30th.

**Comment by jonathanmetzman** [comment]
The only change since the previous build was #2358 so looks like it was indeed the clang roll.

**Comment by jonathanmetzman** [comment]
Digging into why this was failing in particular, for it to fail msgpack_fuzzer must have less than 170 calls to UBSAN runtime. In the last successful UBSAN build it had 748 calls. Pretty big dropoff.

**Comment by jonathanmetzman** [comment]
Some possibilities for how we can fix this:
1. Roll forward to a new revision and hope it solves this issue.
2. Identify the problem, fix it and roll forward.
3. Roll back to a working revision. Unfortunately a bunch of projects depend on changes in the current clang so I'm inclined not to do this.

**Comment by bblanchon** [comment]
Thank you @jonathanmetzman for taking care of this.
Is there anything I can do to help you?

**Comment by jonathanmetzman** [comment]
@bblanchon I'll let you know if I think of something.
I looked at a few targets in skia and it also had a drop of about 500 ubsan calls per target, need to figure out what's causing this.
I had one theory that is wrong but worth mentioning since it has correct implications for our MSAN and ASAN checks (@Dor1s). In fsanitize=fuzzer builds, the libFuzzer runtime is not instrumented, so the number of instrumentation calls will be less for fuzz targets. For some reason in UBSAN builds there were 0 calls to the UBSAN runtime from the libFuzzer runtime. In MSAN builds there was about 50 calls. In ASAN builds there were about 200.

**Comment by bblanchon** [comment]
The build was fixed on May 7th.
Thank you @jonathanmetzman.

**Comment by jonathanmetzman** [comment]
Weird I don't think I did anything that could have fixed this.
O well it at least its fixed.
