### ISSUE TITLE
[Solidity] build failure cause unknown

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#2379]
Hello,

When I consult the build log, I see the following

```
Step #1: error pulling image configuration: Get https://storage.googleapis.com/artifacts.oss-fuzz-base.appspot.com/containers/images/sha256:ad499a28d661dcad45440d28ef96a0008e134cced40daf753c8cf3a41174aa6f?access_token=ya29.c.EmL_BnLGFnuFF0S91cPorIcwPhHa20UJXArLWP0iLycHop29oit2NjvPgbBsg3dx_BW9Y7LmjkfKHQsnHwe2jC3oPB96cdiE6EyBIr8Aa5AStL3m4xriJ5kvgLcIV3maJeGcoA: dial tcp 74.125.20.128:443: i/o timeout
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/cloud-builders/docker" failed: exit status 1
```

Any idea why build is failing?

**Comment by inferno-chromium** [comment]
Seeing the i/o timeouts on a bunch of projects. @oliverchang have you seen this before?, can you please help to take a look or have debugging pointers.

**Comment by bshastry** [comment]
Hello,

Any updates on this. I still keep getting failed build pings from clusterfuzz. Is solidity fuzzing being blocked due to this?

Thank you!

**Comment by Dor1s** [comment]
Looking.

> Is solidity fuzzing being blocked due to this?

Not completely. ClusterFuzz is still fuzzing using the most recent build it has. That's not good though, as (A) bug fixes are not recognized; (B) target might be out of date and report irrelevant bugs.

**Comment by Dor1s** [comment]
If I remove the output suppression from the following line https://github.com/google/oss-fuzz/blob/8f9a3fa22ba404a8a6e25ecb0315880a6cf52724/projects/solidity/build.sh#L69

I'm able to see the actual problem:

```
/src/build.sh: line 69: /usr/bin/zip: Argument list too long
```

I'd suggest removing `&>/dev/null` and either doing `zip -r` with an intermediate directory or minimizing the corpus (I'm a bit surprised that the list is too long just for the seed corpus).

**Comment by bshastry** [comment]
Thank you @Dor1s for triaging this! It was a stupid error on my part. As #2418 notes, the reason the argument list is so long is that (even the minimized seed corpus) contains too many files, beyond the maximum bash argument length.

**Comment by bshastry** [comment]
@Dor1s Another quick question to get this right. Is it okay to ignore directory structure while creating the seed corpus zip archive?

I'm wondering how unzip is handled in the fuzzer bot. Is it an `unzip <corpus.zip> -d corpus`? The reason I ask is if I ignore directory structure while zipping, unzip leads to a flat structure (i.e., all corpus files are placed in the directory where unzip is invoked OR in the output directory specified by the unzip command).

**Comment by Dor1s** [comment]
@bshastry, thanks for checking! It's fine to ignore the structure, CF will unpack the files into a dedicated directory anyway: https://github.com/google/clusterfuzz/blob/6738dd64ab88998f612311ec11c75a0b10c5d671/src/python/bot/fuzzers/engine_common.py#L384
