### ISSUE TITLE
Option to file issues in github issue tracker

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#240]
We have previously discussed that if we are going to support external issue trackers, it would probably be only github.

Several projects are hosted on github and want to have issues public (libass, json). By filing issues directly in their issue tracker we may save maintainers some effort.

**Comment by kcc** [comment]
If/when we implement github issue support, we may still want to duplicate issues in monorail, 
just for the sake of easier bookkeeping.

**Comment by inferno-chromium** [comment]
Monorail is working well, i dont think we are moving on github anytime.
