### ISSUE TITLE
How to avoid unexpect shared file modification from simultaneous testcase?

### ISSUE THREAD

**Issue by comicfans** [google/oss-fuzz#2400]
Hello, I have a idea to use libFuzzer to test [vim](https://github.com/neovim/neovim/issues/9998), basic idea is to map libFuzzer binary as deterministic user input. but it may have such problem:
libFuzzer runs my LLVMFuzzerTestOneInput, it will run vim instance and do some action, these action may modify any file (if possible) , but simultaneous testcase may operate same files , or corrupt the libfuzzer corpus/crash files, how can I avoid such problems ? I'm thinking to use chroot into a clean rootfs (maybe by base + overlayfs) for every fuzze input, but it seems too complicated and I'm not sure if libFuzzer can work in such environment (will corpus/crashed files got right place after chroot?) . any better solution for such case ?

**Comment by jonathanmetzman** [comment]
>I'm thinking to use chroot into a clean rootfs (maybe by base + overlayfs) for every fuzze input, but it seems too complicated and I'm not sure if libFuzzer can work in such environment (will corpus/crashed files got right place after chroot?) . any better solution for such case ?

This sounds too slow. You should probably avoid actually writing to disk and do things in memory instead (maybe writing to /dev/null works?).

Also, it looks like you are essentially testing if user input can crash a program. Although this might help find some stability bugs, it may find a lot of cases where crashing is expected and inevitable.
