### ISSUE TITLE
Convert infra scripts to Python 3

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#2407]
title.

**Comment by evverx** [comment]
Yesterday, in an absolutely different context that has nothing to do with the infra scripts I was reminded (by python complaining about f-strings) that Ubuntu Xenial still ships with Python 3.5 so I think it would be great if it would be possible to run them even there without updating Python manually.

**Comment by jonathanmetzman** [comment]
I was able to run `pull_images` with python3.5.
I think this issue is fixed.
