### ISSUE TITLE
The "Original Stacktrace" collapser is too confusing

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#241]
Consider this testcase:

https://clusterfuzz-external.appspot.com/v2/testcase-detail/6064680095186944?noredirect=1

It is not clear that you can click "Original Stacktrace" and see the memory error. I suggest we don't collapse output at all.

**Comment by inferno-chromium** [comment]
The collapser is wrong here (for timeout, ooms) and we will fix it. But just showing the entire stack in every case is not good. The purpose is to load page quickly and show the most relevant part of stacktrace. E.g. checkout https://clusterfuzz-external.appspot.com/v2/testcase-detail/6642615457939456 which works as expected. @tanin47

**Comment by tanin47** [comment]
We currently preview around the lines that match the crash state. We will make special conditions for oom and timeout.

In the future, we will further explore how we can parse stacktrace into a meaningful data structure. That would be better for previewing stacktrace (e.g. separating command and environment variables).

@inferno-chromium, can you assign the issue to me?

**Comment by inferno-chromium** [comment]
Now fixed!
