### ISSUE TITLE
helper.py fails when its input isn't connected to a tty

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#2417]
I kind of reported it in https://github.com/systemd/systemd/pull/12542#issuecomment-491563572 but I thought it'd make sense to duplicate it here just in case. I tried to run `./infra/helper.py` in a non-interactive environment and it failed with
```sh
Successfully built 6bcfc7f1786e
Successfully tagged gcr.io/oss-fuzz/systemd:latest
the input device is not a TTY
the input device is not a TTY
Fuzzers build failed.
Running: docker build -t gcr.io/oss-fuzz/systemd projects/systemd
Cleaning existing build artifacts.
Running: docker run --rm -i --privileged -v /tmp/oss-fuzz/build/out/systemd:/out -t gcr.io/oss-fuzz/systemd /bin/bash -c 'rm -rf /out/*'
Running: docker run --rm -i --privileged -v /tmp/oss-fuzz/build/work/systemd:/work gcr.io/oss-fuzz-base/msan-builder bash -c 'cp -r /msan /work'
Running: docker run --rm -i --cap-add SYS_PTRACE -e FUZZING_ENGINE=libfuzzer -e SANITIZER=memory -e MSAN_LIBS_PATH=/work/msan -v /tmp/oss-fuzz/build/out/systemd:/out -v /tmp/oss-fuzz/build/work/systemd:/work -t gcr.io/oss-fuzz/systemd
##[error]Bash exited with code '1'.
##[section]Finishing: This is where it gets darker
```
because it passed `-i` to docker, which, in turn, refused to start. Given that `pull_images`, `build_fuzzers` and `check_build` aren't interactive I think It'd be great if there was a way to pass something like `--non-interactive` to `helper.py` to make it work smoothly even without a tty.

In the end I wrapped `helper.py` in `script` to trick it into thinking that it has a tty:
```
# helper.py is wrapped in script to trick it into thinking it's "interactive"
# See https://github.com/systemd/systemd/pull/12542#issuecomment-491563572
sudo script -e -c "./infra/helper.py build_fuzzers --clean --sanitizer=memory systemd $REPO_ROOT"
sudo script -e -c "./infra/helper.py check_build --sanitizer=memory systemd"
```

**Comment by evverx** [comment]
Ideally, non-interactive commands like `pull_images`, `build_fuzzers` and `check_build` probably shouldn't require `--non-interactive` at all but to get it working properly in interactive environments as well it would be necessary to handle `CTRL-C` on the helper.py side to stop containers it starts, which I don't think is worth it so `--non-interactive` looks like a reasonable compromise :-)

**Comment by oliverchang** [comment]
Is there a big issue with using `script`?

We would like to avoid adding any more flags to `helper.py`, which was also never intended to be used in a non-terminal/testing environment :)

**Comment by evverx** [comment]
The only issue with `script` I had was that initially I forgot to pass `-e` to it and spent about 10 minutes wondering why it succeeded even after I intentionally broke our fuzzers :-) Other than that, I have no problem with it. Just to be clear, I opened the issue mainly because I wanted to keep it somewhere in case anyone else (or me in a year :-) will run into that.

> We would like to avoid adding any more flags to helper.py

How about undocumented environment variables? :-) Seriously though, on an absolutely unrelated note, would it be OK if I replaced `ALLOWED_BROKEN_TARGETS_PERCENTAGE=10` with `ALLOWED_BROKEN_TARGETS_PERCENTAGE=${ALLOWED_BROKEN_TARGETS_PERCENTAGE:-10}` in [`test_all`](https://github.com/google/oss-fuzz/blob/8f9a3fa22ba404a8a6e25ecb0315880a6cf52724/infra/base-images/base-runner/test_all#L19) to make it a little bit easier to prevent broken fuzzers from even making it to our repository. I'm sure nobody will notice :-)

**Comment by evverx** [comment]
Regarding ALLOWED_BROKEN_TARGETS_PERCENTAGE, 10 is an absolutely reasonable default in general but in our case we have 30 fuzzers covering code scattered all over the repository and it's surprisingly easy to bypass `build_check` (either by breaking a couple of fuzzers accidentally or introducing a new one that is totally broken).

Regarding CI, I totally get it (and if I recall correctly, we already discussed that when I opened a PR that was supposed to make it easier to download corpora, build fuzzers with all the engines and sanitizers and so on). But when something is useful it's hard to prevent people from using it however weird their use cases are :-) I do all sorts of crazy things with `helper.py` to be honest :-)

**Comment by evverx** [comment]
> would it be OK if I replaced ALLOWED_BROKEN_TARGETS_PERCENTAGE=10 with ALLOWED_BROKEN_TARGETS_PERCENTAGE=${ALLOWED_BROKEN_TARGETS_PERCENTAGE:-10}

Let's find out in https://github.com/google/oss-fuzz/pull/2419 :-)

**Comment by oliverchang** [comment]
#2419 was merged, so I'll close this issue, since I don't think there are any issues remaining here :) Please correct me if I'm wrong.

**Comment by evverx** [comment]
Yes, I have no problem with closing the issue. I've just noticed that `helper.py` is run in `https://github.com/google/oss-fuzz/blob/master/infra/travis/travis_build.py` so I think it's just a matter of time before it fails there :-) When that happens, it will probably make sense to reconsider how to handle non-interactive environments. In the meantime, I seem to have all the building blocks I need to build my weird fuzzing spaceship :-)
