### ISSUE TITLE
CI job is timing out

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2420]
e.g. for solidity project: https://github.com/google/oss-fuzz/pull/2418

https://travis-ci.org/google/oss-fuzz/builds/532791018?utm_source=github_status&utm_medium=notification

raw log: https://api.travis-ci.org/v3/job/532791019/log.txt

ends with

```
The job exceeded the maximum time limit for jobs, and has been terminated.
```

**Comment by jonathanmetzman** [comment]
Looking into splitting up builds into different jobs based on build config (engine, sanitizer, arch)

**Comment by jonathanmetzman** [comment]
#2423 seems like it will mitigate some of the problems here (see #2424 for it in action). But it won't solve the problem for builds that take longer than [50 minutes](https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts) for a single config, but I don't think I can do anything about that

**Comment by Dor1s** [comment]
SGTM, thanks for the quick fix!
