### ISSUE TITLE
Access denied to clusterfuzz page using linked account

### ISSUE THREAD

**Issue by neusdan** [google/oss-fuzz#243]
Login not possible for me on the CluserFuzz UI. My email is listed in the CCs section [here](https://github.com/google/oss-fuzz/blob/master/projects/botan/project.yaml) and this mail address is linked to my google account. 

```
You (email=Daniel.Neus@googlemail.com) are not authorized to access this page!
```

Using the incognito window as suggested in #157 doesn't help.

**Comment by inferno-chromium** [comment]
If you signout and then sign back in, did you sign in using d.neus@sirrix.com username and password for Daniel.Neus@googlemail.com ?

**Comment by neusdan** [comment]
Yes exactly.

**Comment by inferno-chromium** [comment]
Ok try now, i added you explicitly. I have still no clue why it is showing your googlemail email in the users.get_current_user(),email() call when you signed it with your other alternative email id.

**Comment by tanin47** [comment]
@neusdan I'd like to confirm a couple things.

* When you go to https://myaccount.google.com/email, what is your "Google Account email"? and what is your "Alternate emails"?

Thank you!

**Comment by neusdan** [comment]
@inferno-chromium works now thanks!

@tanin47 Google account mail is daniel.neus@googlemail.com. Alternative mail is d.neus@sirrix.com. To link the email i added d.neus@sirrix.com as the alternative mail address

**Comment by tanin47** [comment]
Thank you for confirming. Unfortunately, we don't support authentication with an alternative email address.

**Comment by inferno-chromium** [comment]
@mikea @kcc @tanin47 

We need to update our documentation for this or find a way to get list of alternative email address. I also worry when we find alternative email address, how can we make sure it is indeed verified, as our auth can't rely on an unvalidated alternative email adress.

**Comment by inferno-chromium** [comment]
So, currently that alternative email address work in issue tracker, but does not work when accessing clusterfuzz UI.

**Comment by tanin47** [comment]
> I also worry when we find alternative email address, how can we make sure it is indeed verified,

Alternative email address is verified with email confirmation, IIRC.

> So, currently that alternative email address work in issue tracker, but does not work when accessing clusterfuzz UI.

I didn't know that. I think we can follow what they do in monorail. I'll figure it out.

**Comment by inferno-chromium** [comment]
This is a WontFix, appengine folks confirmed that this is not doable in UI.

Fixed our language in https://github.com/google/oss-fuzz/commit/a51e5dda5136cfc86874c06bcea341df02566f0d
