### ISSUE TITLE
replace allocator_release_to_os=1 with allocator_release_to_os_interval_ms=500 

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#245]
the asan flag for releasing memory to os has changed. 
Now it spells as `allocator_release_to_os_interval_ms=500`, please update. 
(I hope to make it default this quarter)

**Comment by inferno-chromium** [comment]
Updated OSS-Fuzz and ClusterFuzz side ASAN flags.

Looks like allocator_release_to_os_interval_ms is supported in MSAN (allocator_release_to_os_interval_ms), so updated there as well. I don't know about UBSAN use, but added it there as well.
