### ISSUE TITLE
AFL exceptions caused by core dump misconfiguration

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#2450]
Happens to [gfwx](https://console.cloud.google.com/logs/viewer?resource=gce_instance%2Finstance_id%2F2676953448771991958&logName=projects%2Fclusterfuzz-external%2Flogs%2Fbot&expandAll=false&timestamp=2019-05-21T00:40:09.875000000Z&project=clusterfuzz-external&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&interval=JUMP_TO_TIME&scrollTimestamp=2019-05-21T00:38:37.800797054Z) and [wxwidgets](https://console.cloud.google.com/logs/viewer?resource=gce_instance%2Finstance_id%2F4706728565930275919&logName=projects%2Fclusterfuzz-external%2Flogs%2Fbot&expandAll=false&timestamp=2019-05-21T00:53:55.047000000Z&project=clusterfuzz-external&organizationId=433637338589&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2019-05-13T16:55:17.252Z&dateRangeEnd=2019-05-13T17:55:17.252Z&interval=CUSTOM&scrollTimestamp=2019-05-13T17:54:10.660221984Z)

**Comment by inferno-chromium** [comment]
root@oss-fuzz-linux-zone1-worker-tesseract-ocr-8s6q:/mnt/scratch0# cat /proc/sys/kernel/core_pattern
|/sbin/crash_reporter --user=%P:%s:%u:%g:%e

**Comment by oliverchang** [comment]
Something must be going wrong with [setting these](https://github.com/google/clusterfuzz/blob/master/configs/test/gce/linux-init.yaml#L32), or something is resetting these. Weird that it only happens with those 2 projects.

**Comment by jonathanmetzman** [comment]
[It's now happening on internal](https://console.cloud.google.com/errors/CK7XvcyctdDU1QE?time=P7D&project=google.com:clusterfuzz&organizationId=433637338589&src=ac)

**Comment by jonathanmetzman** [comment]
[Also happening here](https://console.cloud.google.com/errors/COOfqYGN_cnOXw?time=P1D&project=google.com:clusterfuzz&organizationId=433637338589&src=ac)

**Comment by inferno-chromium** [comment]
@oliverchang - can you please take a look at this.

**Comment by jonathanmetzman** [comment]
One mitigation we may want to consider is setting the correct value is set in the AFL launcher. So if some fuzz target unset it, it will only harm itself.

**Comment by inferno-chromium** [comment]
needs sudo :(

**Comment by jonathanmetzman** [comment]
Forgot to mention that, but doesn't CF have root on OSS-Fuzz? If it doesn't have root, then fuzz targets can't be changing this value, which means that this solution (changing it back) isn't that useful.

**Comment by inferno-chromium** [comment]
docker bots do have it, but wont want to generalize this as it might not work for folks using cf code.

**Comment by jonathanmetzman** [comment]
I guess the fix may not be generalizable but if it doesn't break on others (ie: if we check that we have root first) then I don't really see harm (if it is indeed targets changing the config). Another solution is running CF as nonroot so that targets can't mess with this stuff.

**Comment by inferno-chromium** [comment]
That seems good, will let @oliverchang respond as well. interesting to debug what caused the internal breakage, i remember seeing it happen sometimes, but now it seems more persistent.

**Comment by oliverchang** [comment]
I'm not sure if it's possible to set this from within the docker container, which is why we set it in the cloud-int rather than one of the startup scripts. This might have changed, but I think we should figure out why this started happening.

**Comment by jonathanmetzman** [comment]
In #2474 an (unrelated) [build failure](https://oss-fuzz-build-logs.storage.googleapis.com/log-56b0ea26-8963-43f4-9940-405655713ff7.txt) is mentioned, in that build failure I see these interesting lines:
```
Step #30: [1;91m[-] [0mHmm, your system is configured to send core dump notifications to an
Step #30:     external utility. This will cause issues: there will be an extended delay
Step #30:     between stumbling upon a crash and having this information relayed to the
Step #30:     fuzzer via the standard waitpid() API.
Step #30: 
Step #30:     To avoid having crashes misinterpreted as timeouts, please log in as root
Step #30:     and temporarily modify /proc/sys/kernel/core_pattern, like so:
Step #30: 
Step #30:     echo core >/proc/sys/kernel/core_pattern
```

AFL fails for this reason on CF because we don't set `AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1` there like we do in the OSS-Fuzz runner image. Maybe this issue can be caught in jenkins and travis by running `echo core >/proc/sys/kernel/core_pattern` on the host and then unsetting `AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES` in the runner.

**Comment by inferno-chromium** [comment]
On internal, i am guessing this is somehow that chromeos crash reporter is resetting this. see https://www.chromium.org/chromium-os/packages/crash-reporting/faq also mentioning /sbin/crash_reporter. on oss-fuzz project, i think some project / binary might reset it too. I am thinking on a fix to check this in launcher (since current check on fuzzer.py is wrong and dont work in oss-fuzz since that code runs on host).

**Comment by inferno-chromium** [comment]
These are now fixed with https://github.com/google/clusterfuzz/commit/70f9bbdc05ff62098313616e5122eb74e9e89121
