### ISSUE TITLE
Monero fuzzer integration

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#2451]
I have about 16 fuzzers for [Monero](https://github.com/monero-project/monero) that I (or Monero devs) could be making a PR for.

Would you accept this PR? Is there any reason why you would not accept a PR for Monero fuzzers?

Thank you.

**Comment by jonathanmetzman** [comment]
>Would you accept this PR?

Yes, assuming upstream devs OK it.

**Comment by evverx** [comment]
Their [licence](https://github.com/monero-project/monero/blob/master/LICENSE) isn't a "standard" open-source licence and just part of it distributed under the MIT licence, as far as I can tell. Just out of curiosity, does that mean that any project whose source code is available on GitHub regardless of the licence can be integrated into OSS-Fuzz?

**Comment by jonathanmetzman** [comment]
I think their license is 3-clause BSD which is a standard license.

After discussing this integration, monero doesn't seem to the kind of core infra we are looking for in OSS-Fuzz. Sorry Guido.

**Comment by evverx** [comment]
@jonathanmetzman indeed it looks like it. I'm not sure why GitHub doesn't recognize it. Though having just found https://github.com/monero-project/monero/issues/3913, I'd run it by the legal department anyway :-)

**Comment by anonimal** [comment]
Hi @jonathanmetzman. I think if @guidovranken factored out CN related code into a new, generic, `libcryptonote`, and fuzzed that, there would be a better chance of merging *that* work into oss-fuzz. With Schneier and Green on the CII committee, I would be interested to see their argument as to why a generic libcryptonote (with generic ring technology) should or shouldn't be a candidate for merging.

**Comment by evverx** [comment]
Before this issue was opened my understanding had always been that OSS-Fuzz accepted only core open-source infrastructure projects (whatever that is) that should be widely-used and I chimed in there just to find out whether that definition was applicable to Monero. (In my opinion it isn't). Though after https://github.com/google/oss-fuzz/issues/2516 was accepted I've been kind of puzzled about what exactly OSS-Fuzz is supposed to fuzz so I would be interested to hear the details about why Monero was rejected as well. And just to be clear, I have absolutely no problem with Monero and Etherium. Just trying to figure out the scope of OSS-Fuzz.

**Comment by sedddn** [comment]
Humbly requesting this issue be reopened. Imho, Monero and libcryptonote both stand as critical open-source infrastructure, as much as OpenSSL and libsodium. Monero and libcryptonote are fundamental pieces of both cryptography, and trustless online financial transactions. Many rely on Monero technology for financial privacy and security.

Again, kindly asking to please reconsider adding Monero code to OSSFuzz. If the answer is still a "no", can you please provide some steps Monero could take to be reconsidered for the project in the future?

**Comment by inferno-chromium** [comment]
Sure, we are fine with getting Monero added to OSS-Fuzz.

**Comment by sedddn** [comment]
Thank you very much @inferno-chromium and OSS Fuzz team!

**Comment by moneromooo-monero** [comment]
Thanks, I'll make a PR then :)
