### ISSUE TITLE
Progression task pending for > 17 h

### ISSUE THREAD

**Issue by nico** [google/oss-fuzz#2459]
https://oss-fuzz.com/testcase-detail/5646803271155712 has been in "Pending" for over 17 hours now.

Sounds a bit similar to #1626 , so @jonathanmetzman :)

**Comment by inferno-chromium** [comment]
Thanks for the report, something has broken our host images after yesterday image upgrade. looking.

**Comment by inferno-chromium** [comment]
The fix is in (https://github.com/google/clusterfuzz/pull/488), but we need a few hours to regenerate docker image again and recreate bots.

**Comment by inferno-chromium** [comment]
finished

```
[2019-05-24 16:02:55 UTC] oss-fuzz-linux-zone3-host-lzjh-2: Progression task started: r201905220318.
[2019-05-24 16:06:21 UTC] oss-fuzz-linux-zone3-host-lzjh-2: Progression task finished: still crashes on latest revision r201905220318.
```

**Comment by nico** [comment]
Thanks! But it looks like it's still testing r361347, which is from 2 days ago.

https://oss-fuzz-build-logs.storage.googleapis.com/index.html also says that llvm was last build 2 days ago (there are no build errors, just no attempts since then). Is that related to image changes as well?

**Comment by nico** [comment]
Actually, from what I can tell, _no_ project on https://oss-fuzz-build-logs.storage.googleapis.com/index.html has a build newer than 5/22.

**Comment by inferno-chromium** [comment]
more breakage :( @jonathanmetzman can you look at the jenkins new build generation issue

**Comment by nico** [comment]
Haha we broke this? Sorry! @zmodem , FYI. Thanks for the fix; looks it still needs merging.

(Later this year, llvm will move from the svn master to a git master; at this point CLANG_SVN_REVISION will disappear.)

**Comment by jonathanmetzman** [comment]
I figured this would happen but I did this as a temp fix. Long term I think OSS-Fuzz should use the monorepo for getting LLVM's source anyway

**Comment by inferno-chromium** [comment]
in a hour or so, we should have the build (after base-images with llvm build). i will comment back.

**Comment by nico** [comment]
llvm built correctly, and CF verified that bug as fixed. Thanks again!
