### ISSUE TITLE
misaligned access is reported as null pointer

### ISSUE THREAD

**Issue by michaelni** [google/oss-fuzz#2465]
at https://oss-fuzz.com/testcase-detail/5088609952071680 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14551
the issue is reported as "Null-dereference READ". But actually it seems to have been a misaligned access in AVX2 code. A more accurate error message could help debugging in cases where this is less obvious.
Thanks

**Comment by inferno-chromium** [comment]
@michaelni - Try reuploading the testcase using "Re-upload testcase" link and upload it to asan job type. ASan might give you the misaligned access stack. If that works, please close this.

**Comment by michaelni** [comment]
Iam not sure i understand how this would help a bug about suboptimal/incorrect error messages but. Doing this the issue is unreproducable as it was already fixed of course.
But assuming this would display more details and a better error message if it was not yet gone. The problem is still there. A developer sees "null pointer" and may or may not guess quickly that its something else. The tools should show the most precisse and most usefull error message

**Comment by inferno-chromium** [comment]
This would need a bug in sanitizers repo for ubsan.
