### ISSUE TITLE
is AFL_DRIVER_DONT_DEFER gone ?

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#2468]
Back in https://github.com/google/oss-fuzz/issues/1449 we added AFL_DRIVER_DONT_DEFER to various LibreOffice afl fuzzers because of some mysterious forking problem with some of the fuzzers.

In recent builds the afl fuzzers have begun failing again, with what seems like the same problem. Is AFL_DRIVER_DONT_DEFER still a thing, or has it been removed ?

**Comment by jonathanmetzman** [comment]
It should still be a thing. Will look into this.

**Comment by jonathanmetzman** [comment]
build should pass now feel free to reopen if it doesn't

**Comment by jonathanmetzman** [comment]
The problem was that we never use AFL_DRIVER_DONT_DEFER in the bad_build_check and our breakage heuristic never considered enough fuzzers broken to reject the entire build. I've changed things so that we always use AFL_DRIVER_DONT_DEFER=1 in bad_build_check.

**Comment by jonathanmetzman** [comment]
libreoffice build seems to be failing now for a different reason: https://oss-fuzz-build-logs.storage.googleapis.com/log-c5fe04cf-58be-4312-8d19-03bf96d0911e.txt

**Comment by caolanm** [comment]
https://cgit.freedesktop.org/libreoffice/core/commit/?id=460cf721da261e6c9d7388fd4cddf4b66fc7b1b7 should fix the newer problem
