### ISSUE TITLE
bad_build_check does not support .options files

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#2470]
bad_build_check does not support .options files.
This can cause bad builds to be falsely reported when fuzz targets depend on the .options file to run properly (as in #2468).
bad_build_check should probably be replaced by the actual ClusterFuzz launchers now that ClusterFuzz is open sourced.

**Comment by Dor1s** [comment]
> bad_build_check should probably be replaced by the actual ClusterFuzz launchers now that ClusterFuzz is open sourced.

That would be super cool, if we could make it easy to use without all CF dependencies.

**Comment by jonathanmetzman** [comment]
This should be possible now that we parse options: https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/parse_options.py
