### ISSUE TITLE
Error while trying to read coverage reports - x-browser issue

### ISSUE THREAD

**Issue by drhsqlite** [google/oss-fuzz#248]
The following URL works on chrome bug gives "Error loading coverage data: 0" on Firefox, Safari, and Edge.

https://clusterfuzz-external.appspot.com/coverage_report/fuzzer/libFuzzer_sqlite3_ossfuzz/latest

**Comment by inferno-chromium** [comment]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://clusterfuzz-external-coverage-reports.storage.googleapis.com/libFuzzer_sqlite3_ossfuzz/2017-01-05.symcov?Expires=1483638565&GoogleAccessId=clusterfuzz-external%40appspot.gserviceaccount.com&Signature=........ (Reason: missing token 'x-requested-with' in CORS header 'Access-Control-Allow-Headers' from CORS preflight channel).

**Comment by inferno-chromium** [comment]
I updated CORS as per https://cloud.google.com/storage/docs/cross-origin. And it now works on Firefox. Edge has some rendering issue, will file another bug.

[
    {
      "origin": ["https://clusterfuzz-external.appspot.com"],
      "responseHeader": ["Origin", "X-Requested-With", "Content-Type", "Accept", "X-PINGOTHER"],
      "method": ["GET", "POST", "OPTIONS"],
      "maxAgeSeconds": 3600
    }
]

**Comment by inferno-chromium** [comment]
@tanin47 confirmed that it works on Safari as well. Have opened #252 to track IE rendering issue.
