### ISSUE TITLE
Need help fixing issue 

### ISSUE THREAD

**Issue by DanBloomberg** [google/oss-fuzz#2485]
This relates to:
issue 13675 by sheriffbot@chromium.org: leptonica/pix_rotate_shear_fuzzer: Out-of-memory in leptonica_pix_rotate_shear_fuzzer
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13675#c4

I don't have permission to view the chromium bug.

I would also like to have a shell script that reproduces the bug in a new client, so that I can run that script and then fix the problem in that client.

It would be nice if the oss-fuzz bugs generate that script, rather than just refer one to a page of documentation.

**Comment by DanBloomberg** [comment]
Here's another one: same problem

 issue 13674 by sheriffbot@chromium.org: leptonica/pix_rotate_shear_fuzzer: Direct-leak in jinit_memory_mgr
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13674#c6

**Comment by DanBloomberg** [comment]
and two more:

 issue 13671 by sheriffbot@chromium.org: leptonica/pix_rotate_shear_fuzzer: Timeout in leptonica_pix_rotate_shear_fuzzer
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13671#c4


 issue 13672 by sheriffbot@chromium.org: leptonica/pix_rotate_shear_fuzzer: Out-of-memory in pix_rotate_shear_fuzzer
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13672#c3

So, in all, 4 bugs I need help with.

**Comment by DanBloomberg** [comment]
Here's another one:

 14773 by ClusterFuzz-External: leptonica/pix_rotate_shear_fuzzer: Heap-buffer-overflow in tiffReadCallback
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14773#c2

I looked into this and replied on the issue on May 17:

"I don't have permission to access the chromium bug.

Also, I cannot run the binary "reproducible test case"  (exec format error):
   clusterfuzz-testcase-minimized-pix_rotate_shear_fuzzer-5674137189613568 "

**Comment by jonathanmetzman** [comment]
Are you signed into the bug tracker using your @google.com account?

**Comment by DanBloomberg** [comment]
I wasn't.  Now I can see the bugs.

However, for these issues, I am unable to get to even the first step; e.g.,
   python infra/helper.py build_image leptonica
   python: can't open file 'infra/helper.py': [Errno 2] No such file or directory

So, the oss-fuzz doc page
   https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md
is useless for me.  Documentation should not assume that the reader understands in detail what is happening or how to use any part of the infrastructure that is not explicitly and clearly explained.  Furthermore, it should be as simple as possible to use.

For internal bugs, you did this the right way.  You provided a shell script that made a client and ran the fuzzer in it, demonstrating the problem.  It was that simple.  And it worked.  This allowed me to fix the bug in the client and that was it.

Why is this not provided for oss-fuzz issues??

**Comment by kcc** [comment]
`python: can't open file 'infra/helper.py': [Errno 2] No such file or directory`
Did you `git clone` this project? 

`Why is this not provided for oss-fuzz issues??`
It is provided, it's called `infra/helper.py`. 
See https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md
It is more hairy that the internal instructions because in oss-fuzz we
deal with an unknown user build system. 

If this fuzz target is the same as your internal one, you can download the reproducer file
and use it with the internal build system. Happy to help with that too, if needed.

**Comment by DanBloomberg** [comment]
No, I did not git clone oss-fuzz.

The good news is that the external leptonica code on github is very closely kept in sync with internal third_party/leptonica, so a failure on the external code should be reproducible in third_party.

I would very much appreciate your help in streamlining the process of fixing these oss-fuzz bugs using the internal build system.

**Comment by inferno-chromium** [comment]
Please check https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md if this helps. I think other issues/questions in this issue are addressed.
