### ISSUE TITLE
Linkify source links in stacktrace

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#249]
Marty, see if srcmap.json is good enough, otherwise @mikea can point/add what else needs to be done on builder side to support this.

**Comment by oliverchang** [comment]
@mbarbella , did we make any progress here? If not, I can own this and do this in Q2

**Comment by mbarbella** [comment]
I haven't started on this yet, no. Feel free to steal it.

**Comment by inferno-chromium** [comment]
This is now done, we support top 4 repos - FreeDesktopVCS, GitHubVCS, GitLabVCS, GoogleSourceVCS, will add others later as well.
