### ISSUE TITLE
Usage of run_fuzzer saving corpus

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#2490]
Hi oss-fuzz :-)

Is there already a way that I can get the generated corpus back after running `python infra/helper.py run_fuzzer` ?

That would be useful for local tests. For instance, after building with a new sanitizer, I will take advantage of my first run and all the new inputs it already found.

I think that it is not the same as in #340

**Comment by Dor1s** [comment]
I think there is `download_corpora` command https://github.com/google/oss-fuzz/blob/91a17744a0ec6e3330a8277d868d9df0cc55fd33/infra/helper.py#L135

Did you try it?

**Comment by catenacyber** [comment]
Thank you @Dor1s 
But this command is for a project already integrated into oss-fuzz.
For them, no problem.

I am asking for a local command for the projects that are work in progress (right now for me it is mysql)

**Comment by Dor1s** [comment]
Ah, sorry, I misread your question. I think there is no way as of now. One workaround I can think of, you can do `infra/helper.py shell $project`, run fuzzer yourself inside the docker, and then copy the corpus either from the host via `docker cp $container:$path $local_path` or get it in `oss-fuzz/build/out/$project`, if you create the corpus directory inside `$OUT`.

**Comment by catenacyber** [comment]
Thanks @Dor1s I got the same workaround.

Would this be a nice feature to add to `run_fuzzer` command ?

**Comment by Dor1s** [comment]
It might be a nice feature, but I'm afraid we're trying to avoid complicating the helper script interface by adding more options. 

Btw, I've just remembered https://github.com/google/oss-fuzz/pull/1922, which is kinda relevant.

**Comment by catenacyber** [comment]
Thanks @Dor1s closing in favor of #2491

**Comment by Pro** [comment]
I found a dirty-hack solution for this:

Just add the following docker option
```
      '-v', '/tmp/fuzzer_tmp:/tmp',
```

here:

https://github.com/google/oss-fuzz/blob/641de9e1ac3aa00701aa257e3f667835534d54d9/infra/helper.py#L723

and then use your run_fuzzer command as usual. This will then store the fuzzer corpus on your host system under `/tmp/fuzzer_tmp`.

**Comment by PetteriAimonen** [comment]
Currently the tutorial here https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally kind of suggests that coverage should work before the project is integrated to ossfuzz, but because of this issue it doesn't.

The workaround suggested by @Pro works great!

**Comment by Dor1s** [comment]
Re-opening this. I think we should choose either of the two:

1) Apply the patch mentioned above in this thread.
2) Remove point 4) from https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally

@oliverchang @inferno-chromium @jonathanmetzman

**Comment by catenacyber** [comment]
My comments about the solutions are :

1. the patch should make corpus directory sharing between host and container optional for performance reasons
2. the documentation can still mention the local coverage with some workaround on how to achieve this, such as https://github.com/google/oss-fuzz/pull/2491#issue-286076422

**Comment by Dor1s** [comment]
Thanks @catenacyber ! I'm against complicating the documentation, but ready to accept helper.py script complication. Let's see what others think on this.

**Comment by Pro** [comment]
To throw in my bits:
Maybe the script can just take an additional command line switch which adds the volume mapping as shown in my patch above.

**Comment by Dor1s** [comment]
@Pro yes, I'm personally fine with that, even though originally I've rejected this because our general strategy was not to expand `helper.py` interface. Seeing this mismatch with documentation and user confusion that happened more than once made me change my mind :)

**Comment by oliverchang** [comment]
We already have `corpus_dir` argument for `helper.py coverage`, so we may as well add it for `helper.py run_fuzzer`. Should be a few lines patch if anyone wants to put up a PR :)

**Comment by inferno-chromium** [comment]
This is a duplicate of https://github.com/google/oss-fuzz/issues/1517
