### ISSUE TITLE
Support shared libraries in the fuzzers

### ISSUE THREAD

**Issue by eugenis** [google/oss-fuzz#25]
Linking everything static is a huge pain in the ass.
Case in point.

My dependencies are fontconfig, harfbuzz, fribidi and freetype. In static link I have to list all indirect deps, too, so the list grows a bit: graphite, glib, pcre, z, png, expat. Note that this is internal detail of third party libraries, and may change when the base system is updated.

I also need to install all the -dev packages.

Also, fribidi and graphite packages don't include static libraries. I need to build them from source. More autocrap.

There goes my day, and I have not yet run my 5-line fuzzer once.

The solution is to include shared libraries with the fuzzer. Just put them in the same directory and use RPATH or LD_LIBRARY_PATH. The list of shared libraries can be generated automatically with recursive readelf/ldd walk. Can we support that?

**Comment by mikea** [comment]
We talked about this and the issue is more complicated than it sounds due to security considerations.

We might revisit this when ClusterFuzz receives an architecture change, but for now I'm going to close the issue: all fuzzers have to have all libraries statically linked in except for libc.
