### ISSUE TITLE
How to download all the corpora for a project via a browser

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#2500]
I needed to download all the corpora for the systemd project via a browser so that I could upload them to Fuzzit: https://github.com/systemd/systemd/pull/12771#issuecomment-500757658. I can't seem to find a way to do it so I ended up downloading them via `helper.py download_corpora` on a machine where I keep my key and copying them to another machine where I could run a browser. I'm wondering if there is a button or anything like that I can click.

**Comment by Dor1s** [comment]
I don't think there is a convenient way to download raw corpora files via browser, but you can definitely download corpus backups (which are daily minimized corpus). Please try opening https://pantheon.corp.google.com/storage/browser/systemd-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/

**Comment by Dor1s** [comment]
I don't think there is a convenient way to download raw corpora files via browser, but you can definitely download corpus backups (which are daily minimized corpus). Please try opening https://console.cloud.google.com/storage/browser/systemd-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/

**Comment by evverx** [comment]
I think I visited a page that looks like that one but there weren't zip archives there. I'm not sure why I couldn't find it.

**Comment by evverx** [comment]
Got it. The dashboards point to urls like https://console.cloud.google.com/storage/browser/systemd-corpus.clusterfuzz-external.appspot.com/libFuzzer/

**Comment by Dor1s** [comment]
Yeah, "-corpus" bucket has working corpus, which is a lot of files that are frequently updates. The "-backup" bucket should have only daily archives.

**Comment by evverx** [comment]
If the backup bucket is more useful, why do all the dashboards point to the working corpus?

**Comment by Dor1s** [comment]
It actually points to both, see the rightmost column "corpus_backup". However, I think we can improve the fuzzer stats page (https://github.com/google/oss-fuzz/issues/1720).

**Comment by evverx** [comment]
Oh, I totally missed it. The page didn't fit into the screen of my laptop and it was cut so carefully I didn't even think about scrolling :-)
