### ISSUE TITLE
/tmp in minijail is too small for new merge tool

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#251]
As @kcc said, the new merge tool can take ~100 mb space in TMPDIR or /tmp. So, we need to either

1) Recompile minijail with higher tmpfs limit like 512/1024/??
2) Not use tmpfs for /tmp and then mark this 777.

@oliverchang, which option do you think is better to do ?

**Comment by kcc** [comment]
you may also use TMPDIR=/some/other/place

**Comment by oliverchang** [comment]
We no longer use tmpfs for /tmp.
