### ISSUE TITLE
project status link in docs/new_project_guide.md doesn't work

### ISSUE THREAD

**Issue by jberkenbilt** [google/oss-fuzz#2511]
docs/new_project_guide.md includes this link to project status: https://oss-fuzz-build-logs.storage.googleapis.com/status.html

This link doesn't seem to work for me, even when I'm logged into oss-fuzz.com and can the details of my project. When I go to this link, I get the following content:

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: oss-fuzz-build-logs/status.html</Details>
</Error>
```

Just going to https://oss-fuzz-build-logs.storage.googleapis.com/ reveals that whatever this is is listing an s3 bucket, which doesn't seem to have a status.html key. Is the link wrong, or did something break?

**Comment by inferno-chromium** [comment]
Should be fixed now, it was wrong.
