### ISSUE TITLE
Ethereum 2.0 phase 0 beacon chain state transition function differential fuzzer

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#2516]
I've been building a differential fuzzer that tests for differences between implementations of the Ethereum 2.0 [phase 0 beacon chain state transition function](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md).

Currently, only the Go client ([zrnt](https://github.com/protolambda/zrnt)) is implemented. The Python client (PySpec) is expected to be integrated into the fuzzer soon. Later, we will probably be looking at adding [more clients](https://docs.ethhub.io/ethereum-roadmap/ethereum-2.0/eth2.0-teams/teams-building-eth2.0/), but zrnt vs PySpec is currently our priority.

The fuzzer is being developed [here](https://github.com/guidovranken/eth2.0-fuzzing). A Dockerfile to build the binaries already exists. While the existing Dockerfile builds several fuzzer binaries, we are currently primarily interested in running the ```block``` fuzzer continuously.

Interesting technical features:

-> Fast input splitting into Go structs using [zssz](https://github.com/protolambda/zssz)'s decoding made designed for fuzzing. SSZ decoding is or will also be implemented for other languages (Python, Rust, Javascript, ...)
-> libFuzzer-based Python code coverage guided fuzzing using a [modified CPython](https://github.com/guidovranken/cpython/tree/fuzzing), passed to libFuzzer using its "extra counters" feature (this is the first in-memory, libFuzzer-based Python fuzzer, as far as I know).
-> Go code coverage guided fuzzing based on work by dvyukov.
-> Uses a hybrid of "curated" corpus (for certain parts of the input, that must adhere to certain rules) and a dynamic corpus, mutated and updated by the fuzzing engine. Both parts are deterministically combined at runtime before passing it to the various clients.

Every component of this project is open source.

For this project we explicitly forgo any and all financial rewards from Google for which OSS-Fuzz integrations are otherwise eligible.

Will you accept this project into OSS-Fuzz?

CC @JustinDrake

**Comment by JustinDrake** [comment]
I can confirm a few things :)

* The fuzzing target is a small mission-critical consensus core (between 1024 and 2048 lines of code depending on implementation) for Ethereum 2.0 (the next version of Ethereum).
* We cannot afford consensus divergences across client implementations. This makes thorough differential fuzzing particularly valuable.
* Everything we do is 100% open source. We are also happy to forgo financial rewards from integration with OSS-Fuzz.
* @guidovranken is leading the Ethereum 2.0 fuzzing effort from within the Ethereum Foundation.

**Comment by guidovranken** [comment]
ping @Dor1s @inferno-chromium :)

**Comment by inferno-chromium** [comment]
Since @kcc reviewed most of your differential fuzzing, assigning to him for triage.

**Comment by kcc** [comment]
Sounds interesting, even though unusual. Please send a PR.
