### ISSUE TITLE
Why is nonnull-attribute disabled on OSS-Fuzz

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#2518]
When the fuzz targets from the systemd project were ported to Fuzzit, `-fsanitize=undefined` was initially passed to the compiler, which caused a few crashes there: https://github.com/systemd/systemd/pull/12771#issuecomment-502139157. To temporarily silence UBsan, in https://github.com/systemd/systemd/pull/12761 I turned on a subset of https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#available-checks I borrowed from https://github.com/google/oss-fuzz/blob/a3c935fe9ca7f82bafa520731525e1cc38acf650/infra/base-images/base-builder/Dockerfile#L33-L34

I'm going to turn `nonnull-attribute` on on Fuzzit in https://github.com/systemd/systemd/pull/12810, but I'm wondering why it's not used on ClusterFuzz. Is it not considered a bug or does it produce a lot of false positives?

**Comment by evverx** [comment]
Generally, I'd say it's not obvious to me why some of the checks are disabled. For example, I found https://github.com/google/oss-fuzz/issues/232#issuecomment-278660351 where `object-size` was turned on and then turned off again. If those checks aren't exactly reliable wouldn't it be better to turn them off by default on the clang side?

**Comment by evverx** [comment]
In a sense this issue is a duplicate of https://github.com/google/oss-fuzz/issues/232, which has been inactive for more than 2 years, so, in principle, it can probably be closed and the discussion can be moved there if it's more convenient.

**Comment by inferno-chromium** [comment]
Probably `nonnull-attribute` is new, dont remember seeing this. We can enable this, might also need a parsing change in https://github.com/google/clusterfuzz/blob/master/src/python/crash_analysis/stack_parsing/stack_symbolizer.py

**Comment by evverx** [comment]
At first glance, the issue reported by UBSan with `pointer-overflow` looks correct as well. The pointer seems to point to an address beyond "defined" limits. Luckily, it doesn't to be dereferenced anywhere afterwards. Everything is fine :-)

**Comment by evverx** [comment]
FWIW It turns out that the fuzz targets in the systemd project can [withstand all default UBSan checks except for "pointer-overflow","object-size" and "float-cast-overflow"](https://github.com/systemd/systemd/pull/12812). Not that these three checks produce false positive though. I'll turn them on later when the fuzz targets are ready.

**Comment by evverx** [comment]
Since I no longer use OSS-Fuzz as a primary source of bugs discovered by UBSan and I turned on the checks I need elsewhere, I think this issue can be closed. #232 refers to this issue so when someone gets round to it, it should be relatively easy to find it.
