### ISSUE TITLE
Coverage viewer does not work on IE Edge

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#252]
I don't see any list of files, but coverage data is in response. So, some rendering issue.

**Comment by mikea** [comment]
I can't seem to be able to reproduce this problem. Everything works fine with Microsoft's Edge test image (screenshots attached). What's your browser version?

![msedge - win10_preview-2](https://cloud.githubusercontent.com/assets/3236/21734210/ff7c7676-d416-11e6-8e1b-2284d47bdd83.png)
![msedge - win10_preview](https://cloud.githubusercontent.com/assets/3236/21734211/ff836eea-d416-11e6-85f5-16c645ceff8e.png)

**Comment by inferno-chromium** [comment]
Ok my bad. Edge works. It isn't working on IE11, do we care ?

**Comment by mikea** [comment]
I think we shouldn't. Live is hard enough as it is :)
