### ISSUE TITLE
Integrate Thunderbird project

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2520]
Inspired by Full Disclosure dated Jun 14th: https://seclists.org/fulldisclosure/2019/Jun/date.html

@pdknsk @alex do you guys know anyone who might be interested in setting this up?

**Comment by alex** [comment]
I couldn't tell you the name of the Thunderbird folks off hand -- Dan Veditz could get you their names easily.

FYI, Thunderbird is no longer maintained by the Mozilla Corporation, however it is still sponsored by the Mozilla Foundation. Mostly what that means is that the usual Firefox security team doesn't really work on Thunderbird, besides helping triage vulnerabilities (and insofar as security improvements in the mozilla codebase also help Thunderbird, e.g. fixing HTML rendering vulns).

**Comment by alex** [comment]
If you need Dan's contact info let me know and I can dig it up.
