### ISSUE TITLE
Travis doesn't handle edge cases very well

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#2554]
Such as [reverting a project](https://github.com/google/oss-fuzz/pull/2553).
[Or adding a project with only a project.yaml](https://github.com/google/oss-fuzz/pull/2536).

Frankly I'm not sure if this is worth fixing, but posting to a bug in case anyone disagrees.

**Comment by inferno-chromium** [comment]
Adding only a project yaml file is common usecase, can you please fix that. reverting seems complicated, can skip.

**Comment by jonathanmetzman** [comment]
This should be fixed now.
