### ISSUE TITLE
Reproduce with multiple sanatizers

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#2558]
I used the reproducing.md documentation to reproduce an issues of the ImageMagick project. At this moment we have a huge backlog of issues that need attention and I try to look at them in chronological order. But it looks like it is only possible to use one sanitizer at the same time. And rebuilding it for another sanitizers takes very long because our build includes a lot of third party projects. Would it be possible to add an extra option to `python infra/helper.py reproduce` where I can specify which sanitizer should be used? And can the result be cached per sanitizer instead so I don't need to do a rebuild when I need to switch to another sanitizer?

**Comment by Dor1s** [comment]
Hi @dlemstra,

Looks like something similar was discussed in #1521 and (in theory) may be addressed as #1529.

Did you try reproducing OSS-Fuzz crashes using your local build? Projects that follow [Ideal Integration](https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md) guide should be able to reproduce the vast majority of bugs outside of the docker container. That's part of the reason why upstream integration is so important and being rewarded for.

**Comment by dlemstra** [comment]
Under Windows we can compile our fuzzers into an executable where we can pass the test file as argument and examine the issue. But for some issues I cannot reproduce it locally so I tried to use the tooling to check why it fails. But maybe we should modify the build script to also make it possible to create those executable on Linux and check them there.
