### ISSUE TITLE
Reduced amount of cases per day according to stats.

### ISSUE THREAD

**Issue by kroeckx** [google/oss-fuzz#256]
According to the stats, the openssl client fuzzer changed from around 250M test cases per day to about 300 around january 4th. The same goes for almost all of them. Is something wrong with the stats, or is there really a lot less tested? Looking at the log files, I'm guess it's the first.

**Comment by Dor1s** [comment]
Looking into this now. I wonder if it's related to https://github.com/google/oss-fuzz/issues/227

**Comment by inferno-chromium** [comment]
Max, can you take a look, only things i see in that range are these changes. And testcases_executed seems broken for all fuzzers.

4070fe7 libFuzzer: use dict.update() to override stats, update tests for stats. by Max Moroz · 4 days ago
f85daf3 libFuzzer: remove old version of dumpStats() + update the tests. by Max Moroz · 5 days ago
8952f1a libFuzzer: apply overridden stats to parsed stats before dumping anywhere. by mmoroz@google.com · 5 days ago

**Comment by Dor1s** [comment]
BigQuery has the following data:

```
Row	testcases_executed	job	fuzzer	timestamp	 
1	12470953	libfuzzer_asan_openssl	libFuzzer_openssl_client	1.48188596E9	 
2	13230378	libfuzzer_asan_openssl	libFuzzer_openssl_client	1.481864539E9	 
3	12715717	libfuzzer_asan_openssl	libFuzzer_openssl_client	1.481861649E9	 
4	11536360	libfuzzer_asan_openssl	libFuzzer_openssl_client	1.481862644E9	 
5	15678195	libfuzzer_asan_openssl	libFuzzer_openssl_client	1.481887605E9	 
6	24846091	libfuzzer_asan_openssl	libFuzzer_openssl_client	1.481869102E9	 
7	4		libfuzzer_asan_openssl	libFuzzer_openssl_client	1.483808726E9	 
8	15381280	libfuzzer_asan_openssl	libFuzzer_openssl_client	1.48187722E9	 
9	4		libfuzzer_ubsan_openssl	libFuzzer_openssl_client	1.483828992E9	 
10	17663318	libfuzzer_asan_openssl	libFuzzer_openssl_client	1.481919634E9	 
```

That means we do dump stats data correctly. I suspect something is wrong with showing the data / aggregating for the stats page.

**Comment by oliverchang** [comment]
This should be fixed now.

**Comment by kcwu** [comment]
The number is still low.
https://clusterfuzz-external.appspot.com/fuzzerstats?fuzzer_name=libFuzzer_openssl_bndiv&job_type=libfuzzer_asan_openssl&last_n=15&last_n_type=days&group_by=last_n

**Comment by oliverchang** [comment]
I'm afraid you're looking at the deprecated soon to be removed dashboard. How did you find this link? It shouldn't be linked to anywhere from the home page... 

The proper one is:

https://clusterfuzz-external.appspot.com/v2/fuzzer-stats/by-day/2017-01-06/2017-01-12/fuzzer/libFuzzer_openssl_bndiv/job/libfuzzer_asan_openssl
