### ISSUE TITLE
[Open vSwitch] Problem reproducing build failure reported by oss-fuzz

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#2568]
Dear all,

The monorail issue number is: 15624

I could not reproduce the failure locally when I did the following

```
$ export P=openvswitch
$ infra/helper.py pull_images
$ infra/helper.py build_fuzzers --clean $P
$ infra/helper.py check_build $P
INFO: performing bad build checks for /out/expr_parse_target.
INFO: performing bad build checks for /out/odp_target.
INFO: performing bad build checks for /out/ofp_print_target.
INFO: performing bad build checks for /out/flow_extract_target.
INFO: performing bad build checks for /out/json_parser_target.
INFO: performing bad build checks for /out/miniflow_target.
INFO: performing bad build checks for /out/ofctl_parse_target.
7 fuzzers total, 0 seem to be broken (0%).
Check build passed.
```

Any hints how I could debug this further?

Thank you!

**Comment by jonathanmetzman** [comment]
[This](https://oss-fuzz-build-logs.storage.googleapis.com/log-bfa41486-24a3-440f-a765-e9345391012e.txt) looks like an AFL failure.
Try this instead please:
```
$ infra/helper.py build_fuzzers --clean --engine afl $P
$ infra/helper.py check_build --engine afl $P
```

**Comment by bshastry** [comment]
Thank you for the tip @jonathanmetzman . I am able to reproduce the issue now.

The problem is that afl has a hard-coded timeout of 1s (1000ms) when performing a dry-run of the fuzzed binary, if this timeout is exceeded, it simply aborts. `check_build` is essentially relaying this failure.

I'm not sure why the binary is so slow that it takes over a second to process one input. Need to dig deeper here.
