### ISSUE TITLE
Discussion : Help with Mandelbulber integration

### ISSUE THREAD

**Issue by mancoast** [google/oss-fuzz#2573]
Greetings oss-fuzz experts!

I have not spun up all the way on the requirements for a proper integration into the fuzz-system. I am looking for support or direction as to what exactly is required for integration.  I am unfamiliar with the fuzz ecosystem, but I want to learn more.

Thanks!
coast

**Comment by inferno-chromium** [comment]
Please see https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md

**Comment by mancoast** [comment]
Thanks!
