### ISSUE TITLE
Link between test case and issue is gone.

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#2574]
The link between the test case https://oss-fuzz.com/testcase-detail/6592348975792128 and the issue https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9883 is gone. But the issue still has a link to the test case. This issue should be closed because we have addressed this problem and the test case is now marked as fixed.

**Comment by inferno-chromium** [comment]
Fixed the link and redid task to check if fixed. It should close it now. This happens rarely and currently dont have cycles to debug this. If this happens again, will take a look.
