### ISSUE TITLE
Integrate libssh2 project

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2578]
Looks like there've been some nice findings recently: https://www.libssh2.org/security.html

//cc @bagder @cryptomilk @alex @guidovranken @bshastry is anyone interested?

I don't know the difference between libssh and libssh2, but would assume that libssh fuzz targets might be easily re-used as a starting point?

**Comment by cryptomilk** [comment]
[libssh2](https://libssh2.org) is a client only library under BSD license.
[libssh](https://libssh.org) is a client and server library providing state of the art cryptography under LGPL license.


The libssh client fuzzer could be used as a starting point to implement a fuzzer for libssh2. However someone form the libssh2 project would need to implement that :-)

**Comment by bagder** [comment]
Interested indeed, but I'm not personally up to doing the job... :disappointed:

**Comment by cryptomilk** [comment]
You can find the libssh client fuzzer at:

https://git.libssh.org/projects/libssh.git/tree/tests/fuzz/ssh_client_fuzzer.cpp

**Comment by bshastry** [comment]
I have a couple of projects to attend to at the moment. Will add it to my queue though. If no one else has picked it up by the time I'm done with my current tasks, I'll pick it up

**Comment by cmeister2** [comment]
Sounds interesting, might take a look if I have spare time this evening.

**Comment by tiennou** [comment]
We just got a report that some fuzzing would be helpful (https://github.com/libgit2/libgit2/issues/5169), so I'm pleased to see a 8-days-old issue about it here 😉. I'm currently converting example code to testcases (https://github.com/libssh2/libssh2/pull/243), and adding a PEM/hostkey fuzzer on top would be ❤️.

**Comment by cmeister2** [comment]
I've got a basic fuzzer working here. Will probably send a PR to libssh2 shortly. Interestingly, despite only testing libssh2_session_handshake, it hits a READ memory access error, so it's probably worth getting in!

**Comment by cmeister2** [comment]
Added PR at https://github.com/libssh2/libssh2/pull/392. Will submit an OSS-Fuzz PR when that one is accepted.

**Comment by jonathanmetzman** [comment]
Seems like this has been completed
