### ISSUE TITLE
How to make issues reported by OSS-Fuzz public

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#2582]
OSS-Fuzz frequently finds bugs that can be made public right away because they either have nothing to do with security or they are about code introduced recently that has never been released. Currently to refer to them in bug reports on GitHub for example I have to manually copy and paste backtraces and testcases from monorail and that annoys me to say the least. I'm wondering if there is a way to bypass the standard disclosure policy.

**Comment by evverx** [comment]
In principle if there was API of some kind provided by monorail/oss-fuzz.com I could use to replicate issues on GitHub using my gmail account it would be also great. This way I could create issues on GitHub and reference them instead of the corresponding issues on monorail.

**Comment by inferno-chromium** [comment]
I have added EditIssue access for evvers@ya.ru. To open a bug early, please remove "Restrict-View-Commit" label. Use this edit functionality with caution and it is preferable not to modify other labels like Status, etc (status to Verified auto-happens when bug is fixed)

**Comment by evverx** [comment]
Thank you. I have never been able to do anything apart from receiving notifications from monorail with evvers@ya.ru so I created evverx@gmail.com back in June 2018 just to view bug reports, downloading corpora and so on. Could you use it instead?

**Comment by inferno-chromium** [comment]
Done!

**Comment by evverx** [comment]
Thank you. I've just made https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=15678 public. It seems to be working except that https://oss-fuzz.com/testcase?key=5751041854799872 seems to ask me to sign up to view the detailed. Would it be possible to bypass that restriction as well?

**Comment by inferno-chromium** [comment]
@oliverchang would know. i think there was some label to allow anyone to view detailed report ?

**Comment by evverx** [comment]
Interestingly, it took ClusterFuzz more than a month to discover that particular memory leak while normally it takes a couple of days to find similar issues in `networkd` (mostly because we have a script to make sure that every time a new feature is introduced the corpus is updated to help the fuzzer to trigger the codepath: https://github.com/systemd/systemd/commit/e520ce64405dedfc1bdd3888f926a69f7d812ab9#diff-9d149976c3a61fb0d3c41eb9a158c75f). Probably we should make the script a bit smarter so that it would also make sure typical values are specified as well or switch to a dictionary.

**Comment by oliverchang** [comment]
Unfortunately we don't have a way to make the detailed report public at the moment. Reproducers can still be downloaded without needing to login if the issue is public.

**Comment by evverx** [comment]
Would it be possible to add ASAN/UBSAN/..._OPTIONS, command lines used to trigger bugs and full backtraces to public bug reports?

**Comment by evverx** [comment]
Just to make sure, should I open a new issue regarding including *_OPTIONS and command lines in bug reports or does the silence mean that it's not going to happen anyway?
