### ISSUE TITLE
container allways exit

### ISSUE THREAD

**Issue by butterflyhack** [google/oss-fuzz#2588]
I run the projects/clamav docker file. 
run cmd:
```
sudo docker container start  8e4ecc492567
```
start a container, but wait for a while, when build.sh run over, the container will exit itself.
if I start container 8e4ecc492567 again, the build.sh will run and compile once again. then exit itself again. 
thanks, what is wrong?

**Comment by inferno-chromium** [comment]
Can you use "python infra/helper.py shell" command to go to your container and use for debugging ?
