### ISSUE TITLE
Evaluate the need to document "view_restrictions" for issue restrictions (all open/security open/all closed(default))

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#2590]
In a couple of projects I found "view_restrictions" set to "none" (which as far as I can tell means that all issues are automatically publicly open). Could it be documented anywhere?

Plus, having looked at the clusterfuzz code, I noticed that it can be set to "none", "security" and "all". I think I more or less understand what "none" and "all" are about but "security" isn't so straightforward.

And, hypothetically, if I choose "none", https://github.com/google/oss-fuzz/blob/master/docs/faq.md#why-do-you-use-a-different-issue-tracker-for-reporting-bugs-in-oss-projects technically no longer applies so it should probably be possible to choose GitHub for example.

**Comment by inferno-chromium** [comment]
Where are you seeing this ?

**Comment by evverx** [comment]
```
$ git grep view_restric
projects/libchewing/project.yaml:view_restrictions: none
projects/llvm/project.yaml:view_restrictions: none
```

**Comment by inferno-chromium** [comment]
For extremely rare features, we intend to keep them undocumented to avoid confusion. Here it just means that project intends to keep all of its issues open. This is not the case 99% of the time. We can point to a project.yaml reference doc, may consider this in future.

**Comment by evverx** [comment]
> Here it just means that project intends to keep all of its issues open. This is not the case 99% of the time.

That's probably true if we are talking about "none" but it seems to me that it should be relatively safe to use "security" (my understanding is that it means that issues deemed "security"-related are closed and the rest are automatically open).

**Comment by inferno-chromium** [comment]
yes correct. feel free to propose a PR to add it in doc.

**Comment by evverx** [comment]
I'll see whether I can get around monoroail altogether without lifting the view restrictions and if not I'll send a PR. I generally agree it makes sense not to document it at this point.

**Comment by evverx** [comment]
Interestingly (and it's somewhat tangential to "view_restrictions"), TIL it's possible to use "experimental: true" to apparently hide bugs from monorail and the standard disclosure policy as in https://github.com/google/oss-fuzz/blob/master/projects/freeimage/project.yaml. Given that the point of monorail (among other things) is to enforce the policy, I'm wondering if OSS-Fuzz somehow flips the flag automatically if nothing happens or the fuzz targets aren't really unstable (which as far as I know can be detected automatically).

**Comment by inferno-chromium** [comment]
"experimental: true" is used when:
1. we just want to see the bug and see if there are false positives. usually done with msan.
2. we dont have a maintainer contact and dont want to start bug filing

**Comment by evverx** [comment]
> we just want to see the bug and see if there are false positives. usually done with msan

MSan almost always triggers false positives. If I recall correctly I opened a least three bugs on the sanitizers bug tracker, than gave up and simply started to add workarounds. I don't think it should prevent people from viewing all bugs found with MSan.

> we dont have a maintainer contact and dont want to start bug filing

I don't think it's much different from a more typical scenario where maintainers don't have time to deal with bugs reported by OSS-Fuzz and should prevent people from viewing bugs either.

**Comment by evverx** [comment]
I think I now can ignore monorail altogether without lifting the view restrictions so I'll go ahead and close the issue.

As for comments vanishing into thin air, there are other (less questionable) ways to manage disruptive comments:  https://help.github.com/en/articles/managing-disruptive-comments#hiding-a-comment.
