### ISSUE TITLE
python3-libraries crashes marked as unreproducible

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#2602]
https://oss-fuzz.com/testcase-detail/5697995384815616 and https://oss-fuzz.com/testcase-detail/5767728272506880 can easily be reproduced, but it keeps marking them as unreproducible. What could be the cause of this?

**Comment by guidovranken** [comment]
Can I see the log of the reproduction attempt somewhere? That would shed light on the cause.
I suspect it has something to do with the reproducer environment not having access to auxiliary files like the stdlib.

**Comment by guidovranken** [comment]
ping

**Comment by Dor1s** [comment]
I don't think we have logs for that. Also, the suggestion about environment mismatch sounds reasonable, but I doubt it's the case, as we should be calling the same build setup routine for both fuzzing and minimizing tasks.

How do you reproduce these locally? Do both testcases hit 25 seconds timeout for you? Can you try bumping it to e.g. 50? Is it still happening?

**Comment by guidovranken** [comment]
Hmm, you're right, all of these testcases complete faster than 25 seconds on my machine.
Closing this issue for now..
