### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#2608]
The @ImageMagick project has a failing coverage build and we don't understand why this is happening. We get the following error message:

```
Step #8: Operation completed over 242 objects/35.5 MiB.                                   
Step #8: CommandException: 1 files/objects could not be copied/removed.
Finished Step #8
ERROR
ERROR: build step 8 "gcr.io/cloud-builders/gsutil" failed: exit status 1
```

This looks like something that the OSS-Fuzz team should fix. It looks like we are not the only project with this issue. Both opencv and graphicsmagick also have a failing build with a similar error message. More info can be found here: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=15653

**Comment by Dor1s** [comment]
Thanks for the report, @dlemstra. This is being tracked in https://github.com/google/oss-fuzz/issues/2585

**Comment by dlemstra** [comment]
Sorry I missed that one.
