### ISSUE TITLE
Track if impacted commit range commits has a tag in it

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#2628]
For automated reporting/severity assessment of OSS-Fuzz found vulnerabilities, being able to know in an automated fashion if the range from oldest-impacted to newest-impacted contains a git tag (or hg tag) would be valuable.

This is a starting point for answering "was this vulnerability in a release" (one exception is for vulnerabilities where the oldest-impacted release is when fuzzing began).

(Maybe I should file this on the CF side?)

**Comment by Dor1s** [comment]
Nice idea, not sure though whether OSS-Fuzz / ClusterFuzz should do it :/

**Comment by inferno-chromium** [comment]
Related project is in progress.

**Comment by jonathanmetzman** [comment]
I think the "related project" is https://osv.dev/ which has been released.
We probably won't implement this in CF/OSS-Fuzz since it is done there.
The only thing left really to do is have OSS-Fuzz display data from OSV.
I think @oliverchang plans on doing this, but unclear when he will have cycles.
