### ISSUE TITLE
ensure we use -fno-omit-frame-pointers and -gline-tables-only

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#263]
@mikea do we use -fno-omit-frame-pointers for asan/ubsa/msan by default?
I can't find any trace of that...

**Comment by kcc** [comment]
same probably for debug info. I notice that some fuzz targets are built w/o debug info -- 
we should simply enforce `-gline-tables-only`

**Comment by oliverchang** [comment]
We enforce -g: https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-clang/Dockerfile#L35

Kostya mentioned that he saw libass binaries without debug info, possibly because their build system strips binaries.
