### ISSUE TITLE
aspell: runtime dependencies?

### ISSUE THREAD

**Issue by cmeister2** [google/oss-fuzz#2638]
Hi! The aspell fuzzer depends on having additional language libraries installed to disk as the aspell main library and the aspell language libraries exist in separate places.

As part of the build these get installed to /out/dict, but I have a feeling that these aren't being copied across to the runner. Would that be the case?

Is there any mechanism for having additional runtime dependencies alongside a fuzz target?

**Comment by inferno-chromium** [comment]
everything in /out should be available to runner and to clusterfuzz. so we archive the whole of /out and then clusterfuzz unpacks it all.

**Comment by Dor1s** [comment]
But please don't rely on the `$OUT` dir presence. The directory structure is different on the bots. You can rely on the relative path though, and use `argv[0]` to derive it as per https://github.com/google/oss-fuzz/blob/master/docs/fuzzer_environment.md, but still better to avoid such operations.

**Comment by cmeister2** [comment]
Yeah, if we could avoid it that'd be great, but unfortunately I don't think that's possible. Thanks for the steer on argv[0]; I'll see if that fixes things.
