### ISSUE TITLE
make it simpler to run build.sh outside of docker

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#264]
essentially, we need to have a fake docker environment (best effort) that will allow to run build.sh for
(most) projects simply on a local machine, w/o modifying the local machine too much. 

For example, this means that we should not have libFuzzingEngine.a in /usr/, but instead have it
in $WORK or $SRC (or some such).

**Comment by mikea** [comment]
We don't hardcode libFuzzingEngine.a path anywhere, but just use -lFuzzingEngine. I am not aware of any other changes that might be needed for this. Do you have any specifics?

**Comment by kcc** [comment]
I have not looked at it closely. But at the very least we need a way to define $SRC, $OUT, etc
Some build.sh actually hardcode the path to libFuzzingEngine.a.

**Comment by mikea** [comment]
We have discussed this at length at decided against it. It goes against our principles of ideal integration. Fully integrated project's build.sh is trivial "configure && make fuzzer" and doesn't need any special environment.
