### ISSUE TITLE
MSAN OOM reports should include backtrace

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#2654]
E.g. https://oss-fuzz.com/testcase-detail/5680972070125568 contains no stacktrace/backtrace.

Especially in this case, where I can't reproduce locally using the minimized testcase, a backtrace might be very useful for a first quick check.

**Comment by Dor1s** [comment]
OOM crashes are detected in a few different ways, and some of them may not have a stack trace, unfortunately. I've marked the linked issue as WontFix. This way, ClusterFuzz should report another timeout variant in a day or two. Hopefully the new one will be reliably reproducible and/or have a stacktrace.
