### ISSUE TITLE
allow user-specified build configurations

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#268]
Right now we build the same fuzz targets in different pre-set configuration (e.g. asan, ubsan, etc). 
Later will have debug vs non-debug, libFuzzer vs afl, etc.

Sometimes a user may need to have variations of their own. 
Here are two use cases resulting from recent discussions with @davidben and @ekasper 
* boringssl has a config with and w/o asm, (--with[out]-asm) and we want to test both
* openssl team is interested in testing several release branches, not just master 

I am not sure we can scale to this level of build type explosion, but at least need to look at it.

**Comment by inferno-chromium** [comment]
Different build configs can be handled in a way similar to https://github.com/google/oss-fuzz/pull/385/commits/2acf141045662ee018a6636d3a988b449eb1b168

Like a _build_config_suffix to fuzzer name ?

**Comment by kcc** [comment]
yes, true. I am not actually sure if providing extra flags in our configs is worth it. 
Doing multiple configs in the user build.sh is pretty simple too..

**Comment by inferno-chromium** [comment]
yes whatever configs we define in project.yaml will anyway have to be used specifically in build.sh, so better to keep that complexity inside build.sh. it can't be done in a generic way inside project.yaml or can it ?

**Comment by inferno-chromium** [comment]
@davidben @moshekaplan  - can you checkout https://github.com/google/oss-fuzz/pull/385/commits/2acf141045662ee018a6636d3a988b449eb1b168 and then create fuzzer_asm and fuzzer_no_asm as part of build.sh.

**Comment by moshekaplan** [comment]
@inferno-chromium : Erm, was I supposed to be tagged here?

**Comment by inferno-chromium** [comment]
Sorry @moshekaplan, i meant @ekasper. I fixed the comment above.
