### ISSUE TITLE
Feature request: Option to select the corpus for a fuzzer

### ISSUE THREAD

**Issue by nsajko** [google/oss-fuzz#2681]
Sometimes fuzzing targets in one project share corpora, so it would be good if that could be specified in the fuzzer.options file.

In case that option already exists, I could not find the info on https://google.github.io/oss-fuzz/getting-started/new-project-guide/ or https://google.github.io/oss-fuzz/advanced-topics/ideal-integration

Slightly related, but for inter-project corpus sharing: https://github.com/google/oss-fuzz/issues/1581

**Comment by nsajko** [comment]
Something like

```
$ cat fuzzer.options
[oss-fuzz]
secondaryCorpus = fuzzer2_seed_corpus.zip
```

**Comment by jonathanmetzman** [comment]
Does this solve the problem of
1. Needing to copy seed corpus to share it between fuzzers.
2. Using multiple seed corpora for a single fuzzer.

I think 1 isn't worth solving, it's easy/cheap enough to copy.
2. is more interesting, but I still would prefer if projects solved this issue themselves by incorporating what they want into the seed corpus for a fuzzer.

I'll close for now, but feel free to reopen if my understanding of this proposal is wrong.
