### ISSUE TITLE
run valgrind on the pre-fuzzed corpora

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#269]
Valgrind is too slow to do fuzzing with it, but the benefit is that valgrind instruments assembly. 
I suggest to have a separate valgrind-friendly build type (e.g. -O1, or maybe combine it with plain coverage build) and then run it on the existing corpora. 

Short term, it will give us functionality of msan on the projects where we don't have msan yet.
Longer terms it will still give us all sorts of bugs in assembly code (we seem to be getting some of it in the crypto libs)

**Comment by derekbruening** [comment]
How about Dr. Fuzz for fuzzing the assembly?

**Comment by kcc** [comment]
Eventually -- why not. We may get additional coverage signal this way.
(probably deserves a separate issue)
