### ISSUE TITLE
Make it possible to navigate directly to a project's build logs

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#2690]
Each button on https://oss-fuzz-build-logs.storage.googleapis.com/index.html should change the URL to something like `/#$PROJECT_NAME` and navigating to https://oss-fuzz-build-logs.storage.googleapis.com/index.html#$PROJECT_NAME should show the logs for $PROJECT_NAME.

This is needed so we can point the OSS-Fuzz badges to something useful.

@oliverchang @mbarbella-chromium Do you have any idea how this can be done? I've tried messing with app-route but my polymer knowledge makes it pretty hard for me to do this.

**Comment by jonathanmetzman** [comment]
Thanks @evverx and systemd for being the first to add our badge. We appreciate it!

**Comment by evverx** [comment]
`brotli` got there first and I just followed suit. Though it's not a competition :-)

Regarding the landing page, I think it would be great if it was also possible to switch to coverage builds without scrolling up, pressing the "coverage builds" button and scrolling down. One option would probably be to fix the selector at the top of the screen I think.

**Comment by ammaraskar** [comment]
For what its worth, libvips beat out even my "official" brotli PR: https://github.com/search?q=oss-fuzz-build-logs.storage.googleapis.com%2Fbadges%2F&type=Code
