### ISSUE TITLE
People with access to bugs

### ISSUE THREAD

**Issue by kroeckx** [google/oss-fuzz#272]
For openssl we had a few people set up with access to the bugs. But for new bugs only me and now openssl-security@ seem to have access. Is this now controlled by the project file?

**Comment by inferno-chromium** [comment]
Yes, please add them to project file. I removed a bunch of people after fixing that bug yesterday. Best to put these in project.yaml.

**Comment by kroeckx** [comment]
I guess you don't have that list anymore?

**Comment by inferno-chromium** [comment]
Nope!
