### ISSUE TITLE
Reproduce tool support for OSS-Fuzz

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#2723]
The ClusterFuzz reproduce tool can reproduce a bug by simply passing in the testcase id as an argument.
Developers [have asked](https://github.com/google/oss-fuzz/pull/2704#discussion_r315003926) for something like this for OSS-Fuzz.

CC @mbarbella-chromium

**Comment by inferno-chromium** [comment]
New reproduce tool does not do the build, it only helps in reproing once you have a build. So we need to think more.

**Comment by jonathanmetzman** [comment]
I don't think we plan on doing this any more.
