### ISSUE TITLE
Build status page has stopped updating

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#2755]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

All projects show 20 08 2019 as the last build date.

**Comment by inferno-chromium** [comment]
@oliverchang fyi.

I also added a "timeout 1800" in jenkins build step since in this case, it was stuck.

**Comment by inferno-chromium** [comment]
Thanks a lot @guidovranken for the report. Should be fixed now and hopefully it shouldnt happen again.

**Comment by guidovranken** [comment]
You're welcome!

**Comment by guidovranken** [comment]
BTW https://oss-fuzz-build-logs.storage.googleapis.com/ exposes all the files on the web server. Not sure if intentional?

**Comment by inferno-chromium** [comment]
that is gcs bucket, so listing is fine, nothing confidential stuff there.

**Comment by guidovranken** [comment]
My only concern was XSS in one of those html files. Though it probably wouldn't matter that much because it's on a special subdomain.

**Comment by inferno-chromium** [comment]
yes not an issue since each gcs bucket is its own subdomain.
