### ISSUE TITLE
zlib is too old and does not support ignoring checksums

### ISSUE THREAD

**Issue by randy408** [google/oss-fuzz#2758]
I recently added support for disabling zlib checksums in lib**s**png which involves calling zlib's `inflateValidate()`, Ubuntu 16.04 LTS ships an older version of zlib that does not provide this function.

The lib**png** fuzzer is also validating the zlib checksums because this function is  `#if` [guarded with zlib's verison](https://github.com/glennrp/libpng/blob/e19a576157911315c1e045fcd0e4dec3e80fba81/pngrutil.c#L425) and the [build script](https://github.com/glennrp/libpng/blob/libpng16/contrib/oss-fuzz/build.sh) doesn't build zlib from source anymore. This might affect other projects too.

**Comment by randy408** [comment]
https://github.com/randy408/libspng/commit/58b64ae6d2604c9a464c1d820c7356fa43bd177f should fix the build for now, the build.sh will be updated once https://github.com/google/oss-fuzz/pull/2702 can be merged.

**Comment by jonathanmetzman** [comment]
Similar to #2758.
I don't think this issue is blocking @randy408 so closing.
In any case, I don't think we want to update versions of packages in the image, it's too cumbersome.
Instead we should just update the docker images completely.
