### ISSUE TITLE
Update project examples in the New Project Guide

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2764]
As per offline discussion with @inferno-chromium and @jonathanmetzman 

https://google.github.io/oss-fuzz/getting-started/new-project-guide/#prerequisites

1) there are unnecessarily many examples, we can remove some of them

2) we should add project using libprotobuf-mutator and FuzzedDataProvider to the lis (e.g. one project using each of these) with a comment like `(note how this project uses LPM / FDP)`

I don't see any good examples of projects using FDP right now.

@jonathanmetzman do you know any nice LPM example in OSS-Fuzz?

**Comment by BlackAngel35** [comment]
> As per offline discussion with @inferno-chromium and @jonathanmetzman
> 
> https://google.github.io/oss-fuzz/getting-started/new-project-guide/#prerequisites
> 
> 1. there are unnecessarily many examples, we can remove some of them
> 2. we should add project using libprotobuf-mutator and FuzzedDataProvider to the lis (e.g. one project using each of these) with a comment like `(note how this project uses LPM / FDP)`
> 
> I don't see any good examples of projects using FDP right now.
> 
> @jonathanmetzman do you know any nice LPM example in OSS-Fuzz?

**Comment by BlackAngel35** [comment]
> > As per offline discussion with @inferno-chromium and @jonathanmetzman
> > https://google.github.io/oss-fuzz/getting-started/new-project-guide/#prerequisites
> > 
> > 1. there are unnecessarily many examples, we can remove some of them
> > 2. we should add project using libprotobuf-mutator and FuzzedDataProvider to the lis (e.g. one project using each of these) with a comment like `(note how this project uses LPM / FDP)`
> > 
> > I don't see any good examples of projects using FDP right now.
> > @jonathanmetzman do you know any nice LPM example in OSS-Fuzz?



> As per offline discussion with @inferno-chromium and @jonathanmetzman
> 
> https://google.github.io/oss-fuzz/getting-started/new-project-guide/#prerequisites
> 
> 1. there are unnecessarily many examples, we can remove some of them
> 2. we should add project using libprotobuf-mutator and FuzzedDataProvider to the lis (e.g. one project using each of these) with a comment like `(note how this project uses LPM / FDP)`
> 
> I don't see any good examples of projects using FDP right now.
> 
> @jonathanmetzman do you know any nice LPM example in OSS-Fuzz?
