### ISSUE TITLE
stats dashboard failed to show ("type mismatch")

### ISSUE THREAD

**Issue by kcwu** [google/oss-fuzz#277]
For example,
https://clusterfuzz-external.appspot.com/fuzzerstats?fuzzer_name=libFuzzer_openssl_asn1&job_type=libfuzzer_asan_openssl&last_n=30&last_n_type=days&group_by=last_n

It returns error ```Type mismatch. Value 3039 does not match type string```.
If reduced the day from 30 to 10, it works.
https://clusterfuzz-external.appspot.com/fuzzerstats?fuzzer_name=libFuzzer_openssl_asn1&job_type=libfuzzer_asan_openssl&last_n=10&last_n_type=days&group_by=last_n

More than one fuzzer has this issue.

**Comment by oliverchang** [comment]
As mentioned in the other bug, this dashboard is no longer supported and about to be removed.

**Comment by oliverchang** [comment]
(I don't see any similar issues with the new one at https://clusterfuzz-external.appspot.com/v2/fuzzer-stats)

**Comment by kcwu** [comment]
Ah, I bookmarked the old links. The new one looks good. Thanks.
