### ISSUE TITLE
How does one go about identifying fuzz targets in an open source project?

### ISSUE THREAD

**Issue by txtsd** [google/oss-fuzz#278]
There is information on how to fuzz targets, but no information on how to actually _find_ one, or to make it easier for beginners to understand what to look for.

**Comment by kcc** [comment]
some hints: 
* any code that consumes un-trusted data from users or from the network
* any code that consumes complex data inputs, event if it's 'trusted'. 
* any algorithm that has two or more implementations (to verify their equivalence)
* look at the existing fuzz targets here

**Comment by inferno-chromium** [comment]
Reopening since we need to add this somewhere in documentation.
