### ISSUE TITLE
Fuzzer CPU hours

### ISSUE THREAD

**Issue by randy408** [google/oss-fuzz#2792]
Is it possible to check how many hours a fuzzer is run?

**Comment by Dor1s** [comment]
A performance report (linked on the stats page, [example](https://oss-fuzz.com/performance-report/libFuzzer_libspng_spng_read_fuzzer/libfuzzer_asan_libspng/latest)) has this information.

But keep in mind that it's per target, per job, per day, and things might be changing from day to day, so it's a very rough approximation of the value you're looking for.

**Comment by jonathanmetzman** [comment]
@inferno-chromium added support for it in fuzzer-stats (see https://oss-fuzz.com/fuzzer-stats/by-fuzzer/date-start/2019-09-03/date-end/2019-09-09/fuzzer/libFuzzer/job/libfuzzer_asan_libspng for example)
