### ISSUE TITLE
Add jbig2dec to oss-fuzz

### ISSUE THREAD

**Issue by sebras** [google/oss-fuzz#2815]
I would like to add the open source jbig2dec project to oss-fuzz.

This is included in `project/mupdf` and `project/ghostscript`, but fuzzing jbig2dec on its own is better. A smaller code base along with a dedicated jbig2 test suite makes it more likely that a jbig2dec-related bugs will be found.

I will provide a proposed pull request.

**Comment by jonathanmetzman** [comment]
This is done right?
