### ISSUE TITLE
access request for Proj-golang

### ISSUE THREAD

**Issue by josharian** [google/oss-fuzz#2825]
https://oss-fuzz.com/testcase-detail/5686956473712640 told me to ask here for access/auth. Thanks. :)

**Comment by jonathanmetzman** [comment]
I think everyone who wants to access these testcases must add their email to golang's project.yaml.
Is this correct @inferno-chromium?

**Comment by inferno-chromium** [comment]
i see your email on https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=17110#c1, can you please submit your email to add as a PR here - https://github.com/google/oss-fuzz/blob/master/projects/golang/project.yaml#L4. Once you do that, you should have access. We also encourage you to own the fuzz targets, improve them and integrate it in golang repo as part of ideal integration here - https://google.github.io/oss-fuzz/advanced-topics/ideal-integration/

**Comment by josharian** [comment]
I still do not have access. E.g. https://oss-fuzz.com/testcase-detail/5748279228235776 says:

> You (email=josharian@gmail.com) are not authorized to access this page!

**Comment by inferno-chromium** [comment]
@josharian - fixed access. problem was it was an old afl testcase and we don't have afl fuzzing now - https://github.com/google/oss-fuzz/blob/master/projects/golang/project.yaml#L8
