### ISSUE TITLE
libc++ linkage errors

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#2826]
Hello,

I am trying to put together a custom docker image for solidity CI that currently comprises the following steps
  - base image -> ubuntu disco
  - clang++-8, libc++8-dev, libc++abi8-dev, llvm-8-dev installed from upstream disco
  - CC=clang CXX=clang++ CXXFLAGS="-stdlib=libc++"
  - Make and install solidity dependencies
  - CC=clang CXX=clang++ CXXFLAGS="-fsanitize=fuzzer-no-link -stdlib=libc++" and fuzzer binaries linked with "-fsanitize=fuzzer -stdlib=libc++"
  - When I try to build solidity, I get linking errors from `libclang_rt.fuzzer-x86_64.a` (which is presumably the ubuntu shipped clang rt library that bundles libfuzzer)
```
/usr/lib/llvm-8/lib/clang/8.0.0/lib/linux/libclang_rt.fuzzer-x86_64.a(FuzzerDataFlowTrace.cpp.o):function fuzzer::DataFlowTrace::Init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&): error: undefined reference to 'std::basic_ifstream<char, std::char_traits<char> >::basic_ifstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&,
std::_Ios_Openmode)'
/usr/lib/llvm-8/lib/clang/8.0.0/lib/linux/libclang_rt.fuzzer-x86_64.a(FuzzerDataFlowTrace.cpp.o):function fuzzer::DataFlowTrace::Init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&): error: undefined reference to 'std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_trait
...
and so on
```

I was wondering what you make of this?

**Comment by Dor1s** [comment]
> clang++-8, libc++8-dev, libc++abi8-dev, llvm-8-dev installed from upstream disco

I don't think there are any guarantees that things would work unless you use the LLVM toolchain installed in OSS-Fuzz docker images.

As a random guess though, I'd suggest you to make sure you're using `clang++` for linking, not `clang`.
