### ISSUE TITLE
Confusion of repos: google/oss-fuzz vs oss-fuzz/oss-fuzz

### ISSUE THREAD

**Issue by rouault** [google/oss-fuzz#2828]
I recently got trapped by pointing someone to https://github.com/Oss-fuzz/oss-fuzz which happens to be a dead fork of https://github.com/google/oss-fuzz. Could https://github.com/Oss-fuzz/oss-fuzz be deleted to avoid the confusion ?

**Comment by inferno-chromium** [comment]
Thanks a lot for notifying us. I just sent an email to GitHub support, https://github.com/Oss-fuzz/oss-fuzz  even closed issue filing, so cant even notify them directly.

**Comment by nsajko** [comment]
https://github.com/Google-Autofuzz/oss-fuzz is a similarly confusing fork.

**Comment by jonathanmetzman** [comment]
It's hard to remember what became of this, but it appears that we gave up on this rather than complete an annoying bureaucratic process.
