### ISSUE TITLE
New dictionary merge code can pass an empty dictionary causing startup crash

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#283]
E.g. https://pantheon.corp.google.com/storage/browser/irssi-logs.clusterfuzz-external.appspot.com/libFuzzer_irssi_irssi-fuzz/libfuzzer_asan_irssi/2017-01-16

If we pass an empty dict file, libFuzzer just crashes on startup with "ParseDictionaryFile: file does not exist or is empty". Can you please fix this so that we don't pass an empty file.

Command: /mnt/scratch0/clusterfuzz/slave-bot/builds/clusterfuzz-builds_irssi_1324be13f2f2cd0662b26f9511664a4ace2554ae/revisions/irssi-fuzz -max_len=2048 -dict=/mnt/scratch0/clusterfuzz/slave-bot/builds/clusterfuzz-builds_irssi_1324be13f2f2cd0662b26f9511664a4ace2554ae/revisions/irssi-fuzz.dict -rss_limit_mb=2048 -timeout=25 -artifact_prefix=/ -max_total_time=2950 -print_final_stats=1 /new /irssi_irssi-fuzz
Bot: ossfuzz-linux-3248
Time ran: 0.077961

(irssi-fuzz:1): GLib-WARNING **: getpwuid_r(): failed due to unknown user id (0)

(irssi-fuzz:1): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
ParseDictionaryFile: file does not exist or is empty
==1==SanitizerCoverage: failed to open /mnt/scratch0/tmp/irssi-fuzz.1.sancov for writing (reason: 2)
==1==SanitizerCoverage: failed to open /mnt/scratch0/tmp/caller-callee.1.sancov for writing (reason: 2)
Merging new testcases failed:

(irssi-fuzz:1): GLib-WARNING **: getpwuid_r(): failed due to unknown user id (0)

(irssi-fuzz:1): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
ParseDictionaryFile: file does not exist or is empty
==1==SanitizerCoverage: failed to open /mnt/scratch0/tmp/irssi-fuzz.1.sancov for writing (reason: 2)
==1==SanitizerCoverage: failed to open /mnt/scratch0/tmp/caller-callee.1.sancov for writing (reason: 2)

**Comment by inferno-chromium** [comment]
Ok i fixed this, lets see if fuzzer logs in irssi improve and then close this.

**Comment by Dor1s** [comment]
Thanks for fixing this, Abhishek (@inferno-chromium) !
Logs look good, I'm closing this.

**Comment by Dor1s** [comment]
Btw, `GLib-WARNING`, `GLib-CRITICAL` and `==1==SanitizerCoverage` messages are still there. Is it a known issue or should we file a new one?

**Comment by inferno-chromium** [comment]
filed https://github.com/google/oss-fuzz/issues/284 for sanitizer coverage issue (known). others glib ones don't look critical, i see new coverage hit with fuzzer. will let irssi dev check it out.
