### ISSUE TITLE
[Solidity] afl-fuzz: Binary uninstrumented error

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#2834]
Hello,

I was notified of a build issue which from the logs seems to be related to dry-run of afl compiled binaries not being instrumented.

```
Step #21: BAD BUILD: fuzzing /workspace/out/address/const_opt_ossfuzz with afl-fuzz failed.
Step #21: /workspace/out/address/afl-fuzz -m none -i /tmp/const_opt_ossfuzz_corpus -o /tmp/const_opt_ossfuzz_afl_address_out /workspace/out/address/const_opt_ossfuzz
Step #21: [0;36mafl-fuzz [1;97m2.54b[0m by <lcamtuf@google.com>
Step #21: [1;92m[+] [0mDisabling the UI because AFL_NO_UI is set.[0m
Step #21: [1;92m[+] [0mYou have 32 CPU cores and 3 runnable tasks (utilization: 9%).[0m
Step #21: [1;92m[+] [0mTry parallel jobs - see docs/parallel_fuzzing.txt.[0m
Step #21: [1;94m[*] [0mChecking CPU core loadout...[0m
Step #21: [1;92m[+] [0mFound a free CPU core, binding to #0.[0m
Step #21: [1;94m[*] [0mChecking core_pattern...[0m
Step #21: 
Step #21: [1;91m[-] [0mHmm, your system is configured to send core dump notifications to an
Step #21:     external utility. This will cause issues: there will be an extended delay
Step #21:     between stumbling upon a crash and having this information relayed to the
Step #21:     fuzzer via the standard waitpid() API.
Step #21: 
Step #21:     To avoid having crashes misinterpreted as timeouts, please log in as root
Step #21:     and temporarily modify /proc/sys/kernel/core_pattern, like so:
Step #21: 
Step #21:     echo core >/proc/sys/kernel/core_pattern
Step #21: [1;94m[*] [0mSetting up output directories...[0m
Step #21: [1;92m[+] [0mOutput directory exists but deemed OK to reuse.[0m
Step #21: [1;94m[*] [0mDeleting old session data...[0m
Step #21: [1;92m[+] [0mOutput dir cleanup successful.[0m
Step #21: [1;94m[*] [0mScanning '/tmp/const_opt_ossfuzz_corpus'...[0m
Step #21: [1;92m[+] [0mNo auto-generated dictionary tokens to reuse.[0m
Step #21: [1;94m[*] [0mCreating hard links for all input files...[0m
Step #21: [1;94m[*] [0mValidating target binary...[0m
Step #21: 
Step #21: [1;91m[-] [0mLooks like the target binary is not instrumented! The fuzzer depends on
Step #21:     compile-time instrumentation to isolate interesting test cases while
Step #21:     mutating the input data. For more information, and for tips on how to
Step #21:     instrument binaries, please see docs/README.
Step #21: 
Step #21:     When source code is not available, you may be able to leverage QEMU
Step #21:     mode support. Consult the README for tips on how to enable this.
Step #21:     (It is also possible to use afl-fuzz as a traditional, "dumb" fuzzer.
Step #21:     For that, you can use the -n option - but expect much worse results.)
Step #21: )B[?25h[0m[1;91m
Step #21: [-] PROGRAM ABORT : [1;97mNo instrumentation detected[1;91m
Step #21:          Location : [0mcheck_binary(), afl-fuzz.c:6930
```

We recently changed solidity link flags to use `-fsanitize=fuzzer` instead of linking to `libFuzzingEngine.a` (see https://github.com/ethereum/solidity/pull/7413). Could this build error be related to that?

Thank you!

**Comment by jonathanmetzman** [comment]
Yep, it is almost certainly caused by that. Could you please use $LIB_FUZZING_ENGINE at least for non-libFuzzer builds.
I don't think directly using `-fsanitize=fuzzer` is a good idea because not only will it prevent solidity from using AFL, it will prevent it from using honggfuzz and any other fuzzing engine we decide to support in the future.

**Comment by bshastry** [comment]
@jonathanmetzman iirc, the ossfuzz build scripts take care to set `$LIB_FUZZING_ENGINE` to as per the fuzzer used. So e.g., `-fsanitize=fuzzer` for libfuzzer and `/usr/lib/libFuzzingEngine.a` for others?

I'm trying to understand how to replicate the linking step in the solidity CI. One solution is I change the link flag from `-fsanitize=fuzzer` to $LIB_FUZZING_ENGINE in the solidity CMake file and in the solidity CI set this to `-fsanitize=fuzzer`.

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman iirc, the ossfuzz build scripts take care to set `$LIB_FUZZING_ENGINE` to as per the fuzzer used. So e.g., `-fsanitize=fuzzer` for libfuzzer and `/usr/lib/libFuzzingEngine.a` for others?

Yep.

> 
> I'm trying to understand how to replicate the linking step in the solidity CI. One solution is I change the link flag from `-fsanitize=fuzzer` to $LIB_FUZZING_ENGINE in the solidity CMake file and in the solidity CI set this to `-fsanitize=fuzzer`.

That seems reasonable.
