### ISSUE TITLE
Disable coverage during fuzzing

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#284]
Fuzzer logs can create failure confusion with messages like

==1==SanitizerCoverage: failed to open /mnt/scratch0/tmp/irssi-fuzz.1.sancov for writing (reason: 2)
==1==SanitizerCoverage: failed to open /mnt/scratch0/tmp/caller-callee.1.sancov for writing (reason: 2)

We should either disable sancov coverage during fuzzing or change coverage_dir to /tmp.

**Comment by kcc** [comment]
once we migrate to trace-pc-guard (soon, hopefully) this should get fixed automatically. right?

**Comment by inferno-chromium** [comment]
@kcc - is this because -dump_coverage=0 by default and our old ASAN_OPTIONS=coverage=1:coverage_dir= will be ignored ? Anyway, @oliverchang we should fix the flag clusterfuzz side to account for this.

**Comment by kcc** [comment]
yes

**Comment by oliverchang** [comment]
Should be fixed now.
