### ISSUE TITLE
Will an updated seed corpus be merged into the running corpus?

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#2845]
I'll be merging elliptic curve support into Cryptofuzz soon.
I've generated a seed corpus for this with specific values in the inputs (pub/priv keys, signatures) that the fuzzer might not find on its own. Hence, I'd like oss-fuzz to use this corpus instead of starting from a clean slate.
If I update the Cryptofuzz seed corpus zip, will this be merged into the OSS-Fuzz internal corpus?

The docs appear to say no, but I'm not sure if that's right?

To provide a corpus for my_fuzzer, put my_fuzzer_seed_corpus.zip file next to the fuzz target’s binary in $OUT during the build. Individual files in this archive **will be used as starting inputs for mutations**.

**Comment by inferno-chromium** [comment]
If the fuzzer has an existing corpus, then it is still retained. Seed corpus is just additionally added to fuzzer current corpus once a day.

**Comment by jonathanmetzman** [comment]
>The docs appear to say no, but I'm not sure if that's right?

Which part of the docs. I want to correct it if it is unclear.

**Comment by guidovranken** [comment]
I'm sorry, I was confused because https://google.github.io/oss-fuzz/getting-started/new-project-guide/#seed-corpus says

"Individual files in this archive will be used as starting inputs for mutations."

But I've now read https://google.github.io/oss-fuzz/advanced-topics/ideal-integration/#seed-corpus and it implies what @inferno-chromium says

"It should be regularly extended with the inputs that (used to) trigger bugs and/or touch new parts of the code."

**Comment by guidovranken** [comment]
I actually didn't know that previous crashers must be added to the seed corpus manually. I always thought that clusterfuzz would automatically do that once a bug has been fixed.

**Comment by Dor1s** [comment]
CF would do that, but it cannot update the seed corpus, which is useful for regression / CI testing.
