### ISSUE TITLE
Debug or release build?

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#2846]
Hello

As a general suggestion, would you recommend fuzzing a debug or a release build? I notice that debug builds usually contain more edges but this is most likely because of sub-optimal code.

Debug build pros:
  - Executes debug assertions
  - ??

Debug build cons:
  - Slower
  - ??

Thanks!

**Comment by inferno-chromium** [comment]
Prefer release build. Assertions can sometimes be very noisy, if it is not, then can enable assertions. Also, many projects provide ways to turn on assertions even in release mode.
