### ISSUE TITLE
'compile' failed on i386 build image (--architecture i386 --sanitizer address)

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#2865]
I invoked 'compile' several times to track down issues with my build.sh.

One of them failed with a segment violation
```
...
clang-10: error: unable to execute command: Segmentation fault (core dumped)
clang-10: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 10.0.0 (trunk 371856)
...
```

Files are in the attached tar file, `output.txt` contains the output of `compile`.

[report.tar.gz](https://github.com/google/oss-fuzz/files/3636376/report.tar.gz)

**Comment by jonathanmetzman** [comment]
What project is this?

**Comment by jonathanmetzman** [comment]
Note to self: I think this also reveals why i386 isn't working with -lFuzzingEngine (a pretty low priority issue, but an issue nonetheless). `compile_libfuzzer` is compiling libFuzzer for x86_64 instead.

**Comment by jonathanmetzman** [comment]
@rockdaboot I'm not really able to repro this with the command in the output.txt. Have you pulled the latest image recently?
(I'm still trying to repro by running compile several times).

**Comment by rockdaboot** [comment]
> What project is this?

wget2, but I don't think it matters.

> Have you pulled the latest image recently?

I am very sure I did. But over the weekend I have no access to that machine. Instead I will try to reproduce on a different machine / hardware (but both on latest Debian unstable).

**Comment by rockdaboot** [comment]
I let the `compile` run 260x here (Ryzen 7 1700, latest Debian unstable) without issues.

So let's close this and reopen only if needed. I'll test on Monday with the other machine again.

Thanks for looking into it.
