### ISSUE TITLE
garbage collect really old builds.

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#287]
We should set a lifecycle policy on our build buckets to automatically delete builds that are more than say 6 months old.

Some potential issues:
  - many testcase tasks may break if the testcase is old.
  - fixed testing (progression task) may have some remaining issues.
  - races when build list is first retrieved from GCS, and then the older builds are deleted.

**Comment by inferno-chromium** [comment]
We discussed this today and right now, it is a much lower in our priority queue. We will get back to it in next quarter or so.

**Comment by jonathanmetzman** [comment]
Do we still care about doing this at all?
