### ISSUE TITLE
libreoffice build failure

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#289]
https://oss-fuzz-build-logs.storage.googleapis.com/build_logs/libreoffice/latest.txt

Executable/wmffuzzer
/work/workdir/LinkTarget/StaticLibrary/libfuzzer.a(localedata_en_MY.o): In function `getAllCurrencies_en_MY':
/src/libreoffice/vcl/workben/localestub/localedata_en_MY.cxx:83: undefined reference to `getAllCurrencies_ms_MY'
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
/src/libreoffice/vcl/Executable_wmffuzzer.mk:13: recipe for target '/work/instdir/program/wmffuzzer' failed
make[1]: *** [/work/instdir/program/wmffuzzer] Error 1
Makefile:153: recipe for target 'Executable_wmffuzzer' failed
make: *** [Executable_wmffuzzer] Error 2
[Pipeline] }
[Pipeline] // stage

@caolanm - can you take a look.

**Comment by caolanm** [comment]
yeah, I saw that this morning, should be fixed earlier today.

**Comment by inferno-chromium** [comment]
Now fixed, thanks @caolanm .
