### ISSUE TITLE
Coverage report seems broken for proxygen

### ISSUE THREAD

**Issue by mhlakhani** [google/oss-fuzz#2892]
I would appreciate some guidance on how to debug this as the documentation is a bit sparse. 

When I go to see the coverage report at (https://storage.googleapis.com/oss-fuzz-coverage/proxygen/reports/20190925/linux/file_view_index.html) it's surprisingly low. More worryingly it shows that even the `LLVMFuzzerTestOneInput` isn't called (https://storage.googleapis.com/oss-fuzz-coverage/proxygen/reports/20190925/linux/src/proxygen/proxygen/fuzzers/ProxygenHTTP1xFuzzer.cpp.html) which leads me to believe something is broken in the coverage reporting.

How can I debug/fix this so we get meaningful data?

**Comment by jonathanmetzman** [comment]
Ugh the files that are covered look statically initialized I wonder if the coverage binary fails completely.
Did you see [these docs](https://google.github.io/oss-fuzz/advanced-topics/code-coverage/) on coverage?

**Comment by mhlakhani** [comment]
@jonathanmetzman when I ran it in the local run in https://github.com/google/oss-fuzz/commit/4b5a47fe3b84260c9e89989299178857d087afbd it threw some errors about the corpus not being found -- I hadn't seen these docs which point to the corpus dir. I'll test that out and report back, thank you!

Is there a quick way to generate the corpus dir from a local run?

**Comment by jonathanmetzman** [comment]
>Is there a quick way to generate the corpus dir from a local run?

You could run a fuzzer for ~30 minutes on your host (or on runner using a subdir of $OUT) and use that corpus.

You would need a non-cov build for this though.

 But a corpus with just one file containing "ABC" should be enough to repro this I think.

**Comment by mhlakhani** [comment]
@jonathanmetzman I'm able to repro, but I'm confused because at first sight it seems like the coverage binary is fine and there is an issue elsewhere.

Here's what I did:

    python infra/helper.py build_fuzzers --sanitizer coverage proxygen
    python infra/helper.py coverage proxygen

I looked at the output in `/out/proxygen/report` and verified that it matches what I see on the oss-fuzz ui. I'll pick out a couple of files from the summary JSON:

    {"filename":"/src/proxygen/proxygen/lib/http/codec/HTTPSettings.h","summary":{"lines":{"count":22,"covered":0,"percent":0},"functions":{"count":6,"covered":0,"percent":0},"instantiations":{"count":6,"covered":0,"percent":0},"regions":{"count":6,"covered":0,"notcovered":6,"percent":0}}}
    {"filename":"/src/proxygen/proxygen/fuzzers/ProxygenHTTP1xFuzzer.cpp","summary":{"lines":{"count":7,"covered":0,"percent":0},"functions":{"count":1,"covered":0,"percent":0},"instantiations":{"count":1,"covered":0,"percent":0},"regions":{"count":1,"covered":0,"notcovered":1,"percent":0}}}

I then tried to run the binary directly in the shell. I did the following:

    python infra/helper.py shell --sanitizer coverage proxygen
    echo "aaaa" > a.txt
    /out/ProxygenHTTP1xFuzzer a.txt
    llvm-profdata merge -sparse default.profraw -o merged.profraw
    llvm-cov report /out/ProxygenHTTP1xFuzzer -instr-profile=merged.profraw

This outputs a report with a bunch of numbers that are non-zero. This is the overall summary line:

    13635             13114     3.82%        3380              3201     5.30%       27077             25797     4.73%

And if I pick out the data for the two files above:

    50                48     4.00%          50                48     4.00%          92                90     2.17%
    1                 0   100.00%           1                 0   100.00%           7                 0   100.00%

Interestingly the line count doesn't match for HTTPSettings (the first file) -- maybe because oss-fuzz does some postprocessing in the report generation?

**Comment by Dor1s** [comment]
weird, I don't see anything suspicious in the logs, trying to reproduce locally now

**Comment by Dor1s** [comment]
Oh wait, corpus pruning doesn't seem to work for this target and therefore corpus backups are empty: https://console.cloud.google.com/storage/browser/proxygen-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/proxygen_ProxygenHTTP1xFuzzer

**Comment by Dor1s** [comment]
Yeah, coverage works totally fine, I've added one dummy input and got more stuff covered, including the fuzz target source.

**Comment by mhlakhani** [comment]
> Oh wait, corpus pruning doesn't seem to work for this target and therefore corpus backups are empty

Is there a way I can help debug this?

**Comment by Dor1s** [comment]
Good question, let me try to understand why it's failing. Typically it has something to do with the target itself. If that's the case, you help will be needed :) I'll report soon.

**Comment by mhlakhani** [comment]
I'd love to help debug as needed because I'm also curious -- the internal version of this seems to be running fine on the corpus pruning stage. The code is the same but it's compiled differently, so I imagine that has something to do with it.

**Comment by Dor1s** [comment]
It looks like the corpus bucket was full or some junk temporary files produced by gsutil (they all have `_.gstmp` prefix) and that was breaking gsutil command at some point: it would download pretty much all good files and then start to download all these temporary ones and eventually fail.

We've never seen a problem like this (and that's why it might be scary, what if other projects got these too), so I've manually pruned the corpus, kicked off the coverage job again, and right now am overwriting the "working" corpus so that fuzzing can work without issues and the corpus pruning task should also succeed later today.

Will check some other projects now, hopefully they don't have these files.

**Comment by Dor1s** [comment]
Ok, here we go: https://oss-fuzz.com/coverage-report/job/libfuzzer_asan_proxygen/latest

I've checked corpus buckets for 5 other projects, haven't found these `_.gstmp` files anywhere else. Let's see if it ever happens again. Thanks for keeping an eye on this and reporting the issue, @mhlakhani !

**Comment by mhlakhani** [comment]
thanks for fixing!
