### ISSUE TITLE
Question: uneven fuzz targets

### ISSUE THREAD

**Issue by pauldreik** [google/oss-fuzz#2915]
Hi!
I wonder how you handle fuzz targets of uneven size?

Say you have one big and slow target, which finds new paths even after weeks of fuzzing. And then another fast target, which reaches everything it can reach within hours.

What happens if these two targets exist in the same project, will you load balance them somehow, so fuzzing power is not wasted on the already covered target?

The reason I am asking is that I wrote new fuzzers for curl, and I do not want those to reduce the "air time" for the existing ones.

Thanks,
Paul

**Comment by jonathanmetzman** [comment]
@mbarbella-chromium might be able to say more but we do have an automatic weighting feature that should downweight fuzz targets that haven't discovered new coverage in a while.
iirc it's not aggressive enough that you can add tons of useless fuzzers and still be productive but I think it should probably help with your use case.
