### ISSUE TITLE
CF: replace bad unit processing step in corpus pruning

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#293]
With trace-pc-guard enabled, we should have failure resistant merge everywhere. We can remove/replace our bad unit processing step to save some cycles.

**Comment by inferno-chromium** [comment]
But what about the fuzzing step. Quaranting the bad units is useful, so that we don't crash on startup when fuzzer tries to read from corpus containing these bad units.

**Comment by oliverchang** [comment]
Yes, that is what I meant by "replace" :) The merge step should output bad units, which we can process/quarantine.

**Comment by inferno-chromium** [comment]
ah nice! Didn't know the new merge process can output bad units, that would speed up the things a ton!.

**Comment by oliverchang** [comment]
This is done.
