### ISSUE TITLE
Delete libunwind library from the base-runner image

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#2947]
This was added for honggfuzz some time ago. Honggfuzz isn't still being used, and either way we should statically link it with libunwind.

**Comment by Dor1s** [comment]
//cc @jonathanmetzman I've added this to my TODO, but feel free to steal if you want.

**Comment by jonathanmetzman** [comment]
Please do, I don't have any immediate plans to do this.

**Comment by jonathanmetzman** [comment]
libunwind is causing myanmar-tools to spuriously pass bad build check and exception all over the place on ClusterFuzz.

**Comment by jonathanmetzman** [comment]
So the counterargument to removing it that we discussed in person is as follows:
We are going to support honggfuzz on CF soon.
Removing libunwind from the runner and builder will break honggfuzz in OSS-Fuzz.
When we support honggfuzz on CF, we may install libunwind there.
Removing it now won't fix anything, it will just prevent future issues like with proxygen and myanmar-tools.

Max preferred linking honggfuzz with libunwind statically.

**Comment by oliverchang** [comment]
We plan on adding support for honggfuzz soon, so we can also just add this to our CF runner images, but I agree that ideally we should link it statically. 

@robertswiecki is there some way we can link honggfuzz with libunwind statically?

**Comment by robertswiecki** [comment]
Instead of linking with -lunwind* you can probably link it with some static libs

```cc -o honggfuzz cmdline.o display.o fuzz.o honggfuzz.o input.o mangle.o report.o sanitizers.o socketfuzzer.o subproc.o linux/arch.o linux/bfd.o linux/perf.o linux/pt.o linux/trace.o linux/unwind.o  -lm libhfcommon/libhfcommon.a -L/usr/local/include -pthread -lbfd -lopcodes -lrt -ldl -lm -lipt /usr/lib/x86_64-linux-gnu/libunwind-ptrace.a /usr/lib/x86_64-linux-gnu/libunwind-x86_64.a /usr/lib/x86_64-linux-gnu/libunwind.a -llzma -lpthread```

Or eveb better with `pkg-config --libs libunwind-ptrace`

Did it help?

If you want to compile honggfuzz totally statically, it'll require a bit more debugging, cause some libs linke libbfd contain some transient dependencies on llzma and friends

**Comment by oliverchang** [comment]
Thanks! That worked, but libbfd and libopcodes are also causing trouble because they include the version number:

```
	libbfd-2.31.1-system.so => /lib/x86_64-linux-gnu/libbfd-2.31.1-system.so (0x00007ff8d3325000)
	libopcodes-2.31.1-system.so => /lib/x86_64-linux-gnu/libopcodes-2.31.1-system.so (0x00007ff8d3182000);
```

Would it be possible to link these statically too? 

Ideally honggfuzz will support a static build upstream as part of the build system, as increasing portability helps us decouple the build and fuzzing environments (which might be quite different). @robertswiecki WDYT?

**Comment by oliverchang** [comment]
I was able to do it by doing:
```
clang -o honggfuzz cmdline.o display.o fuzz.o honggfuzz.o input.o mangle.o report.o sanitizers.o socketfuzzer.o subproc.o linux/arch.o linux/bfd.o linux/perf.o linux/pt.o linux/trace.o linux/unwind.o -lm libhfcommon/libhfcommon.a -L/usr/local/include -pthread /usr/lib/x86_64-linux-gnu/libbfd.a /usr/lib/x86_64-linux-gnu/libopcodes.a -lrt -ldl -lm /usr/lib/x86_64-linux-gnu/libunwind-ptrace.a /usr/lib/x86_64-linux-gnu/libunwind-x86_64.a /usr/lib/x86_64-linux-gnu/libunwind.a -llzma -lpthread /usr/lib/x86_64-linux-gnu/libiberty.a -lz
```

But it would be great it this was officially supported upstream :)

**Comment by robertswiecki** [comment]
I've added some code to the Makefile

Please try with

```shell
BUILD_OSSFUZZ_STATIC=true make clean all
```

Unfortunately there's no pkgconfig for libbfd and libopcodes, so this might be a little risky to use with different distros, but maybe maybe it will work with yours.

**Comment by robertswiecki** [comment]
With https://github.com/google/honggfuzz/commit/d530bb1395fe28195f18cc1b4f6ebd8199bef275 I made it semi-static, i.e. no other deps than libc and friends (pthreads, dl, rt etc.)

**Comment by oliverchang** [comment]
This is awesome, thanks a lot @robertswiecki !!

Would it also be possible to get libBlocksRuntime statically linked too?

**Comment by robertswiecki** [comment]
Hi, done at HEAD.

PS: Which release are you'd be using, the oss-fuzz one - https://github.com/google/honggfuzz/releases/tag/oss-fuzz - or sth different?

**Comment by robertswiecki** [comment]
One more thing, the Makefile uses ```-mtune=native```, which might be risky for cloud environment (different CPUs used). I wonder if you should compile it as

```CFLAGS="-O3 -mtune=<some_safe_default>"``` 

where the argument could be e.g. ```nehalem``` as per https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html - it supports SSE4.2 and POPCNT and is suffciently old. Or maybe just drop -mtune as the SSE/POPCNT parts is enforced anyway for relevant parts of code - https://github.com/google/honggfuzz/blob/master/libhfuzz/instrument.c#L30

**Comment by oliverchang** [comment]
Thanks @robertswiecki !! 

We're using the oss-fuzz release. And thanks for the tip re -mtune, we'll drop it to be safe.

**Comment by sffc** [comment]
Hi all! There is the following TODO in https://github.com/google/oss-fuzz/blob/master/projects/myanmar-tools/build.sh

```
# TODO(https://github.com/google/oss-fuzz/issues/2947): Link in libunwind
# statically or stop copying if ClusterFuzz bot images get libunwind.
# Copy libunwind since it isn't on the ClusterFuzz bot images.
cp /usr/lib/x86_64-linux-gnu/libunwind.so.8 $OUT/lib/
```

This has ben working fine except today I tried building the myanmar-tools image on aarch64 and it fails to build since there is a hard-coded `x86_64` in that line above.

Is there a more permanent solution to this issue these days?

**Comment by sffc** [comment]
Should be resolved by https://github.com/google/oss-fuzz/pull/10074

**Comment by jonathanmetzman** [comment]
Do you actually need aarch support? Why? I suppose we could maybe fix this by copying from $ARCH-linux-gnu/libunwind.so.8 to OUT/lib but we aren't fuzzing on aarch64 yet (though it may come by the end of this year.

**Comment by sffc** [comment]
I'm just trying to reproduce https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57922 and my workstations are almost all on aarch64 these days.
