### ISSUE TITLE
Use lld for linker

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#295]
According to @eugenis https://github.com/google/sanitizers/issues/260 will be fixed for lld first.

**Comment by oliverchang** [comment]
This was reverted. We were seeing tonnes of:

```
==19==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed
```

errors everywhere.

**Comment by chandlerc** [comment]
Just to close the loop, with Peter's help I think we've figured out that this is a bug in LLD: http://llvm.org/PR31939

Peter has a patch to fix it out for review: https://reviews.llvm.org/D29861

**Comment by pcc** [comment]
The patch landed in LLVM r294977, so it may be worth trying this again.

**Comment by pcc** [comment]
When we tried to enable lld by default in Chromium for Linux we started getting false positives from msan, e.g.
https://bugs.chromium.org/p/chromium/issues/detail?id=776355
so we had to switch back to using gold with msan for now.

It would probably be worth investigating that before trying to switch to lld again.

**Comment by inferno-chromium** [comment]
@pcc what is the plan here ?
