### ISSUE TITLE
Question: most fuzzable corpus formats?

### ISSUE THREAD

**Issue by cmeister2** [google/oss-fuzz#2951]
This is a general question about improving the speed of fuzzing.

I'm wondering what the most easily fuzzable corpus format is for fuzzers which have:

* multiple options
* options which might be specified multiple times
* byte string inputs

At the moment in curl we use a collection of Type-Length-Value structures, but I'm unsure of whether there's anything better. It's been pointed out that TLVs might be hard to fuzz quickly.

**Comment by MarcoFalke** [comment]
See https://github.com/google/fuzzing/blob/master/docs/split-inputs.md, which mentions FuzzedDataProvider and TLV

I think this can be closed
