### ISSUE TITLE
runner image has an /out directory even though the actual bot image does not

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#2963]
I think this (along with libunwind) allowed myanmar-tools to pass bad_build_check (rather than a breakage) since it was linked against a hard coded path (`/out/lib`) it passed on the runner even though it failed on CF.
The fix here could be to rename the directory in the runner to something like `build-out`

**Comment by inferno-chromium** [comment]
Another occurrence - https://github.com/google/oss-fuzz/commit/4035d0d62f995482ec33c6ed9cd9c368a50413fd

**Comment by jonathanmetzman** [comment]
This isn't quite the same issue but it's quite similar. In the first case the issue is the runner doesn't have an /out directory. In the second case, the builder used on travis has an out directory but does not on jenkins.

**Comment by jonathanmetzman** [comment]
@oliverchang Do you know why we wanted gcb not to use /out?
https://github.com/google/oss-fuzz/commit/6d8ecba42381d946658b6ea09936345b692d7d0d

**Comment by oliverchang** [comment]
> @oliverchang Do you know why we wanted gcb not to use /out?
> [6d8ecba](https://github.com/google/oss-fuzz/commit/6d8ecba42381d946658b6ea09936345b692d7d0d)

It was because $OUT is not /out on GCB. The only mount we get is /workspace so it's set to a subdir of that.

**Comment by jonathanmetzman** [comment]
Fixed by #3205
