### ISSUE TITLE
libFuzzer may recommend an empty dictionary string, but will exit if you use it

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#298]
Example: https://storage.cloud.google.com/arduinojson-logs.clusterfuzz-external.appspot.com/libFuzzer_arduinojson_json_fuzzer/libfuzzer_asan_arduinojson/2017-01-18/19%3A55%3A31%3A274723.txt?_ga=1.136568759.681981521.1481280983

```
...
###### Recommended dictionary. ######
"" # Uses: 102970
###### End of recommended dictionary. ######
...
```

But then, when we've put it into auto-generated recommended dict:

```
<...> clusterfuzz-builds_arduinojson_f56dedd068c67b694fca67e88b5358b8f47813e0/revisions/json_fuzzer <...> /new /arduinojson_json_fuzzer
Bot: <...>
Time ran: 0.130289

ParseDictionaryFile: error in line 4913
		""

Merging new testcases failed:
ParseDictionaryFile: error in line 4913
		""
```

**Comment by Dor1s** [comment]
I'll land a quick fix on CF side to exclude `""` strings.

**Comment by Dor1s** [comment]
Landed a quick fix ~30 minutes ago, looks fine.

**Comment by inferno-chromium** [comment]
Thanks @Dor1s for catching this. We should continue to monitor logs and make sure there are no more ParseDictionaryFile crashes, this can happen silently and be very problematic.

**Comment by kcc** [comment]
should be fixed in libFuzzer r292520.

BTW, I am not entirely sure that "Recommended dictionary." in its current form is of any use. 
Max, let us know if you experiment shows any results.

**Comment by Dor1s** [comment]
Thanks! Let's discuss it on Monday, we have some questions / ideas about it.
