### ISSUE TITLE
[lz4] Can't reproduce issue marked reproducible

### ISSUE THREAD

**Issue by terrelln** [google/oss-fuzz#2982]
I'm attempting to reproduce a failure in lz4's `decompress_fuzzer` with ASAN and i386, the issue is https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18519.

I've been unable to reproduce the issue, I've tried these steps:
1. Reproduce with a ASAN and `-m32` with a custom driver that runs each input.
2. The same but with libfuzzer driver that runs the input 1000 times.
3. Reproduce with Docker following the steps in the guide with address sanitizer and architecture i386.
4. The same as above but with a local version of the code that adds asserts that may help debug.

Would anyone be able to help us figure out how to reproduce this issue, and why it was marked reproducible?

**Comment by jonathanmetzman** [comment]
I was also unable to reproduce this as well. Even within minijail and on one of the production OSS-Fuzz bots (without minijail). 
I don't really have the cycles to figure out what's going on here right now. It isn't occurring very often. Do you think the bug is a big security concern?

**Comment by terrelln** [comment]
@jonathanmetzman I don't know if it is a security concern, but it could be. I don't quite see how it can be triggered. My only thought would be some sort of integer overflow/underflow based on the pointer addresses. But, the address isn't within 64KB of 0 or 2^32-1, so that shouldn't be possible. Another possibility would be a mis-compilation (potentially because of UB), but then I don't see how it isn't reproducible.

**Comment by terrelln** [comment]
@jonathanmetzman this is showing up again in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19011. Still `decompress_fuzzer` with ASAN on i386.

**Comment by jonathanmetzman** [comment]
Sorry, I'll try to take a look again.

**Comment by jonathanmetzman** [comment]
I think this issue with unreproducible crashes has been reported before for ASAN on i386. Since I was unable to resolve this and lz4 disabled that build, I'm going to close.
