### ISSUE TITLE
Help with artifacts on libfuzzer

### ISSUE THREAD

**Issue by miguellpcs** [google/oss-fuzz#2984]
Hello everyone, 
I'm relatively new with the oss-fuzz infrastructure, so some questions may look trivial to you.
I've been using the oss-fuzz infra-structure with libfuzzer to try to evaluate techs. of minimization 
of seed corpus and the results brought me questions about the artifacts generated by libfuzzer when the fuzzer finds a crash and also about the oss-fuzzer's seed corpus.

1) What exactly are the artifacts generated by libfuzzer? I read that the artifacts are the data, i.e. the input, that generated a crash in a executable. For example, if during a fuzzing campaign of "Libjpeg-turbo" a bug is found, than a "(bug-type)-(some-hash-key)" file may be generated. If I run this file in the "Libjpeg-turbo executable" so is supposed to find a (bug-type) bug during the execution of that input that was generated. But when I tried to do this ( ./(executable-name  ((bug-type)-input) ), I didn't find a bug/error at all. So if it isn't a bug, why the artifact was created? How can I recognize real bugs?

2) If I can reproduce the bug, how can I go from it to the format that I can report for the developers? And how can I report? 

3) About the oss-fuzzer's seed corpus. Is it optimized for fuzzing? Is it true for all projects that do have a seed corpus? Its worthless try to reduce the seed corpus before a fuzzing campaign?

Thank you very much.

**Comment by inferno-chromium** [comment]
> Hello everyone,
> I'm relatively new with the oss-fuzz infrastructure, so some questions may look trivial to you.
> I've been using the oss-fuzz infra-structure with libfuzzer to try to evaluate techs. of minimization
> of seed corpus and the results brought me questions about the artifacts generated by libfuzzer when the fuzzer finds a crash and also about the oss-fuzzer's seed corpus.
> 
> 1. What exactly are the artifacts generated by libfuzzer? I read that the artifacts are the data, i.e. the input, that generated a crash in a executable. For example, if during a fuzzing campaign of "Libjpeg-turbo" a bug is found, than a "(bug-type)-(some-hash-key)" file may be generated. If I run this file in the "Libjpeg-turbo executable" so is supposed to find a (bug-type) bug during the execution of that input that was generated. But when I tried to do this ( ./(executable-name  ((bug-type)-input) ), I didn't find a bug/error at all. So if it isn't a bug, why the artifact was created? How can I recognize real bugs?

inputs that result in crashes. read more on libfuzzer.info

> 2. If I can reproduce the bug, how can I go from it to the format that I can report for the developers? And how can I report?

pass them the input file, fuzz target and how it is written.

> 3. About the oss-fuzzer's seed corpus. Is it optimized for fuzzing? Is it true for all projects that do have a seed corpus? Its worthless try to reduce the seed corpus before a fuzzing campaign?

oss-fuzz maintains a current fuzzing corpora which is minimized from continuous fuzzing and provided seed corpus. For file formats, it is usually important to provide a set of seed files, otherwise fuzzing engine can't derive all the fields from just fuzzing.

> 
> Thank you very much.
