### ISSUE TITLE
Support for fuzzing more than one branch

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#2991]
Hello,

Would you be okay if a project wants to fuzz more than one branch (e.g., master and feature branches) via oss-fuzz?

The simple way to do it from a project maintainer perspective would be
  - build binaries and copy to $OUT
  - git checkout feature
  - build binaries and copy renamed binaries to $OUT

**Comment by evverx** [comment]
I'm wondering why it would be useful to continuously fuzz feature branches. It seems the regression testing discussed in https://github.com/google/oss-fuzz/issues/2937 should be enough (assuming that apart from running fuzzers against the corpora OSS-Fuzz will additionally run them for several minutes).

**Comment by bshastry** [comment]
@evverx For the lack of a better example that I can think of atm,

Master branch: Car model X
Feature branch: car model X + sunroof

Corpus from master does not contain "open sunroof" and "close sunroof" seeds

**Comment by evverx** [comment]
If two versions of software are maintained independently and feature branches never make it to the master branch, it looks like they are technically different projects that shouldn't be fuzzed together. If, on the other hand, features are expected to be merged sooner or later, it seems to be enough to fuzz a branch/a PR for several minutes to catch shallow bugs during review and unleash continuous fuzzing once the feature is merged.

**Comment by Dor1s** [comment]
I think the only right way to do it would to have essentially two project integrations, e.g. `projects/name_master` and `projects/name_feature` but obviously you would need to get an approval from OSS-Fuzz team on this, which highly depends on the project and on how diverse the branches are.

**Comment by bshastry** [comment]
@Dor1s Thank you! I will create a dummy PR for discussion with more details.

**Comment by evverx** [comment]
> I think the only right way to do it would to have essentially two project integrations

@Dor1s I'm wondering if it would be possible to share corpora between those projects. Or would it mean that two projects would just use double the resources?

> I will create a dummy PR for discussion with more details.

Judging by the PR, it's not exactly a feature branch. It's just another release as far as I can tell and in theory it should be covered by continuous fuzzing by the master branch.

**Comment by Dor1s** [comment]
> @Dor1s I'm wondering if it would be possible to share corpora between those projects. Or would it mean that two projects would just use double the resources?

Yes, no automated corpora sharing as of now.

**Comment by evverx** [comment]
@Dor1s got it. Thank you!

Anyway, I've subscribed to that PR to see where it's going but as far as I can tell the project has never fuzzed the "development" branch (where new features are added) so instead of keeping two projects it seems it would make sense to start fuzzing the "development" branch (as everybody else does as far as know).
