### ISSUE TITLE
matio_fuzzer is not stateless, explodes corpus

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#3010]
gsutil -m ls gs://matio-corpus.clusterfuzz-external.appspot.com/libFuzzer/matio_fuzzer | wc -l
339730

@tbeu - can you please take a look.

**Comment by tbeu** [comment]
Not sure what you want me to do here, but I already fail to install the gsutil tool.

![grafik](https://user-images.githubusercontent.com/5444067/68525677-490afa80-02d4-11ea-8b36-19ebb01eebf8.png)

**Comment by inferno-chromium** [comment]
actually, you dont need to look at corpus. the point is number of files (corpus) for matio_fuzzer is growing exponentially. this can only happen if there is some random state in api calls. could it be that matio code uses temp filename to make some decisions in processing data. or could matio code be picking some random numbers at runtime and using it along with *data.

Basically right now

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {

for any `data` passed, result should be same / deterministic.

**Comment by tbeu** [comment]
That is very strange as there is no random behaviour built in matio. It all should be deterministic.

You can browse/get the fuzzer code from https://github.com/tbeu/matio/tree/master/ossfuzz. I have no idea why the temporary file (created by FuzzerTemporaryFile) is not deleted after the fuzzing run.

**Comment by inferno-chromium** [comment]
We had some corpus pruning issues before, now it looks ok, 20k files.

**Comment by tbeu** [comment]
Thanks for confirmation. Keep up the good work.
