### ISSUE TITLE
OSS-Fuzz doesn't seem to fuzz continuously

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#3014]
The other day I wrote the following comment:
> at some point (I guess after a lot of new projects had been added and the 32-bit mode had been introduced) it started to look like OSS-Fuzz kind of reached some limit in terms of its capability to fuzz continuously. For example, it keeps missing issues like systemd/systemd#13938 (which was found by continuous fuzzing using only 1 CPU 24 hours a day as opposed to about 3.3 hours the statistics tab on oss-fuzz.com says). I'm wondering if maybe it would be possible to scale what is currently available first before trying to cover more configs.

in response to which the CPU weighting for systemd was upped. That particular fuzzer appears to have started to run continuously but according to https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2019-09-30&date_end=2019-11-05&fuzzer=libFuzzer_systemd_fuzz-netdev-parser&job=libfuzzer_asan_systemd&project=systemd, another fuzzer just stopped on October 27 and hasn't been active since then. There are also 2-6 day gaps in October.

I didn't go over all the fuzzers but it looks like OSS-Fuzz doesn't fuzz continuously and keeps missing bugs. 

Just to clarify, I have absolutely no problem with this kind of fuzzing happening occasionally. After all, it's better than nothing and I'm unlikely to burn down my laptop ever again :-). It's just that in the past OSS-Fuzz seems to have thrown much more CPUs at the fuzzers than I possibly could using other methods (which in my opinion was its distinctive feature) and it was possible to make some relatively safe assumptions about the code. With those unpredictable fuzzing bursts I can see on the statistics page I don't think OSS-Fuzz can be integrated into a release cycle, for example.

**Comment by inferno-chromium** [comment]
We will look at this sometime this week or next. We have some automatic weight adjustments for bad fuzzers (extremely crashy ones), we will investigate if that is causing issues here. There shouldn't be unpredictability here, and you should get fuzz cycles every day for all targets, we will investigate.

**Comment by evverx** [comment]
Thank you! In the meantime, I'll try to find a comment I left somewhere where I first noticed what seems to be the same issue. At that point as far as I can remember the systemd project didn't use anything else so it wasn't possible to compare the results. I assumed the script automatically updating corpora when new features are added was broken. Most likely it was :-) but even before that with that script a certain class of shallow issues OSS-Fuzz had been able to find in a few hours using libFuzzer and bruteforce became as elusive as any other non-trivial bug. That time it took OSS-Fuzz more than 2 weeks to discover that particular bug if I recall correctly.

**Comment by oliverchang** [comment]
I took a quick look but didn't see anything obviously wrong. Some targets are automatically downweighted but only to 0.75. Let's see what happens a few days later with the increased CPU allocation.

**Comment by evverx** [comment]
> Some targets are automatically downweighted but only to 0.75

@oliverchang is my understanding correct that those weights (which affect the distribution of CPUs within the project) are different from the global weight (which affects how many CPUs the project gets and which was increased as far as I can tell)? I'm also wondering how I can translate those weights (which aren't available through the UI) into the fuzzing time I'm looking at.

**Comment by oliverchang** [comment]
Yes, there are per-target weights which are set automatically based on stats, as well as per-project weights. Unfortunately they're not exposed in UI right now.

**Comment by evverx** [comment]
@oliverchang got it. Thank you.

> Unfortunately they're not exposed in UI right now

I think if only the number of CPUs every project gets on average was shown somewhere, it would probably be easier to manage fuzz targets by maybe turning off some of them on OSS-Fuzz temporarily so that more important fuzzers could get more CPUs. Currently I can just roughly estimate the maximum (assuming all the fuzzers/sanitizers/fuzzing engines are "equal") by dividing 1000 (`PROJECT_MAX_CPUS` (which I understand most projects (including `systemd`) are never going to get because they aren't that important)) by 32 (fuzz targets) by 3 (ASan, UBsan, MSan) by 2 (libFuzzer, AFL, (though it appears hongfuzz is on the way)). By reducing the number of fuzz targets I was able to get the number I like in terms of bruteforce I'm looking for :-)

**Comment by evverx** [comment]
I've just taken a look at the statistics and it appears the systemd projects was fuzzed (with libFuzzer) for 394.4h on November 5 and for 482.5h on November 6 (compared to 31.4h on November 4). The large fuzzers I checked kept fuzzing for from 5h to 23h. If this is as far as we can currently get, I think the issue can be closed. Thank you!

**Comment by evverx** [comment]
I've just realized that instead of turning off some fuzzers another option would be to kind of split `systemd` into several projects like `systemd`, `systemd-networkd`, `systemd-resolved`, `systemd-journald`, `systemd-udevd` and so on so that they could get their fair share competing with the other projects for CPUs.

**Comment by inferno-chromium** [comment]
> I've just realized that instead of turning off some fuzzers another option would be to kind of split `systemd` into several projects like `systemd`, `systemd-networkd`, `systemd-resolved`, `systemd-journald`, `systemd-udevd` and so on so that they could get their fair share competing with the other projects for CPUs.

This is more complicated and we instead just bump up project weight for such large projects (with many fuzz targets).

**Comment by inferno-chromium** [comment]
@evverx - i want to thank you again for your involvement with OSS-Fuzz and continuously providing us feedback to improve the platform.
