### ISSUE TITLE
How to ensure that infra/helper.py is running with latest clang

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#302]
We need to run ./infra/base-images/all.sh explicitly to update clang. OSS-Fuzz developers might continue to keep using old clang if they don't call this. E.g. i could n't reproduce that lld breakage since my clang locally was old.

**Comment by mikea** [comment]
That's what `docker build --pull` is for in helper.py - it checks for image version on every build. 
We also do a push right after base-images build. The image should be reasonable fresh. Do you remember what did you do exactly?

**Comment by inferno-chromium** [comment]
I remember seeing the lld flag unsupported on line 
"Compiling libFuzzer to /usr/lib/libFuzzingEngine.a"
with the build_fuzzers command, can't reproduce it anymore. Maybe the image wasn't up-to-date yesterday when i pulled, and now it is. Closing.
