### ISSUE TITLE
Ideal integration for FLAC

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#3023]
E.g. @erikd commented in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=16468#c9

**Comment by erikd** [comment]
Let me be more specific.

I can totally understand why Oss-fuzz uses Docker to make setup and running of the fuzzers uniform across all fuzzing targets and reproducable.

However, Docker is not always a great solution for maintainers of projects which are being fuzzed. Personally I have only used Docker less than 5 times and all of those times it was done using pre-canned instructions that I did not need to understand in any depth.

The [Reproducing Bugs](https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-bugs) link assumes a bunch of Docker knowledge I do not possess. Following the [Getting Started](https://google.github.io/oss-fuzz/getting-started/) link is not really useful either.

I should also mention that in the couple of instances someone sent me a Docker setup for which I was supposed to do investigation and debugging, the Docker environment itself was of a sufficient impediment that I needed to reproduce it outside Docker before I was actually able to start working on the investigation/debugging.

**Comment by oliverchang** [comment]
We recommend that all projects [integrate fuzz targets](https://google.github.io/oss-fuzz/advanced-topics/ideal-integration/#build-support) into the upstream build system with sanitizer support for reproduction purposes. Would this be possible for FLAC? 

The first section (https://google.github.io/oss-fuzz/advanced-topics/reproducing/#fuzz-target-bugs) mentions this but we probably need to stress it at bit more:

> If you have already integrated the fuzz target with your build and test system, all you have to do is run this command:
>
> $ ./fuzz_target_binary <testcase_path>

Indeed requiring Docker for reproduction is not ideal, and the only way to really address this is upstream fuzz target build support.

**Comment by erikd** [comment]
Someone other than me supplied the Oss-Fuzz integration and this is how they did it.

**Comment by inferno-chromium** [comment]
@guidovranken integrated this. Do you want to work with @erikd on ideal integration next.

@erikd - you might want to check this example if it helps you to do this ideal integration. This is a one time thing, that will make your debugging a breeze without docker - https://github.com/google/oss-fuzz/tree/master/projects/example/my-api-repo

**Comment by erikd** [comment]
Thanks @inferno-chromium . I will have a look at that on the weekend.

**Comment by erikd** [comment]
Ok, I have had a look at "my-api-repo". Unfortunately that just uses a relatively simple `Makefile` and hence is not immediately applicable to FLAC which builds using something more complicated than Make. I maintain the autotools build system for FLAC. Is there a real project that is set up for Oss-Fuzz that uses auto-tools?

**Comment by erikd** [comment]
The fuzzing targets setup by @guidovranken uses libraries that cannot easily be built within the FLAC project. They will need to be re-written.

**Comment by erikd** [comment]
The extra library seems to be mostly headers from this repo https://github.com/guidovranken/fuzzing-headers.git . However pulling these into FLAC will require a bunch of fixes because all C++ code in FLAC is compiled with warning flags like `-Wshadow` and `-Weffc++`. I have avoided C++ for over a decade and will need to refresh my memory.

**Comment by erikd** [comment]
I have pulled the Oss-Fuzz targets for FLAC into the repo in this PR: https://github.com/xiph/flac/pull/163

They seem to build and run correctly. All that is needed now is all the other stuff. Is there a check list for this other stuff?

**Comment by inferno-chromium** [comment]
> I have pulled the Oss-Fuzz targets for FLAC into the repo in this PR: [xiph/flac#163](https://github.com/xiph/flac/pull/163)
> 
> They seem to build and run correctly. All that is needed now is all the other stuff. Is there a check list for this other stuff?

https://google.github.io/oss-fuzz/advanced-topics/ideal-integration/ has a list of the things. For build flags for various sanitizers, etc, please check - https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/Dockerfile#L54
