### ISSUE TITLE
testcase upload UI doesn't present right target types

### ISSUE THREAD

**Issue by bpfoley** [google/oss-fuzz#3037]
I was trying to upload a testcase to run on the job type libfuzzer_asan_readstat, and with the target binary fuzz_format_sas7bdat (as was used for https://crbug.com/oss-fuzz/14590)

I can successfully select libfuzzer_asan_readstat from the job type, but many binaries unrelated to readstat appear in the target list

See ![Screen Shot 2019-11-15 at 3 22 09 PM](https://user-images.githubusercontent.com/3423010/68982480-fe99ea00-07bb-11ea-8346-13bc3e31d95a.png)

**Comment by jonathanmetzman** [comment]
Assigning to current sheriff.

**Comment by Dor1s** [comment]
I'm the sheriff this week (we swapped with Abhishek)

**Comment by Dor1s** [comment]
Thanks for your report. I'm not quite sure what's going on here. I was about to type that this is an intended behavior  as the vast majority of OSS-Fuzz users do not have access to multiple jobs and that many fuzz targets. For users who can access too many things, there is a convenient search box where users can type the beginning of the fuzz target they are looking for.

However, I am not sure that this is entirely true -- I'd rather verify that using an additional account.

Another issue I've noticed is that there is some issue with stats: https://oss-fuzz.com/fuzzer-stats?project=readstat&fuzzer=libFuzzer&job=libfuzzer_asan_readstat&group_by=by-fuzzer

and also I don't see readstat fuzz targets in Datastore.

I'll take a closer look sometime later.

**Comment by inferno-chromium** [comment]
This is a known limitation, since otherwise UI needs to dynamically get the list as soon as you click the job type and it will lead to slight delay. We can fix this sometime, right now it shows all targets. Same is true for fuzzer stats.

**Comment by Dor1s** [comment]
Thanks for clarifying, @inferno-chromium. I've filed https://github.com/google/clusterfuzz/issues/1205 and am closing this for now.
