### ISSUE TITLE
New dependencies in base-builder broke some builds

### ISSUE THREAD

**Issue by tsdgeos** [google/oss-fuzz#3040]
poppler, karchive, kimageformats, karchive now fail compiling.

Seems to be related to zlib.

Has something changed in the base image install regarding to zlib now being included while previously wasn't or similar?

**Comment by inferno-chromium** [comment]
I can think of https://github.com/google/oss-fuzz/commit/ce39aeb200a10080dd31918cec88c24faf425e52#diff-2d0059c6b6b34a757c93f800bcb3f37c
@oliverchang - could that have caused this ?

**Comment by oliverchang** [comment]
Yes, zlib is now included in the base image. @tsdgeos is it obvious to you why this would be causing failures?

**Comment by Dor1s** [comment]
In case of kimageformats project, the error comes from karchive sources:

```
+ clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -fPIC -DHANDLER=KraHandler -std=c++11 /src/kimgio_fuzzer.cc /src/kimageformats/src/imageformats/kra.cpp -o /out/kimgio_kra_fuzzer -I /src/qtbase/include/QtCore/ -I /src/qtbase/include/ -I /src/qtbase/include//QtGui -I /src/kimageformats/src/imageformats/ -I /src/karchive/src/ -I /src/qtbase/mkspecs/linux-clang-libc++/ -L /src/qtbase/lib -lQt5Gui -lQt5Core -lqtlibpng -lqtharfbuzz -lm -lqtpcre2 -ldl -lpthread -fsanitize=fuzzer /usr/local/lib/libzip.a /usr/local/lib/libz.a -lKF5Archive
/usr/local/bin/../lib/x86_64-linux-gnu/libKF5Archive.a(kxzfilter.cpp.o): In function `KXzFilter::init(int, KXzFilter::Flag, QVector<unsigned char> const&)':
/src/karchive/src/kxzfilter.cpp:96: undefined reference to `lzma_auto_decoder'
/src/karchive/src/kxzfilter.cpp:186: undefined reference to `lzma_lzma_preset'
/src/karchive/src/kxzfilter.cpp:132: undefined reference to `lzma_properties_decode'
/src/karchive/src/kxzfilter.cpp:148: undefined reference to `lzma_properties_decode'
/src/karchive/src/kxzfilter.cpp:181: undefined reference to `lzma_easy_encoder'
/src/karchive/src/kxzfilter.cpp:193: undefined reference to `lzma_raw_encoder'
/src/karchive/src/kxzfilter.cpp:114: undefined reference to `lzma_properties_decode'
/src/karchive/src/kxzfilter.cpp:170: undefined reference to `lzma_raw_decoder'
/usr/local/bin/../lib/x86_64-linux-gnu/libKF5Archive.a(kxzfilter.cpp.o): In function `KXzFilter::terminate()':
/src/karchive/src/kxzfilter.cpp:216: undefined reference to `lzma_end'
/usr/local/bin/../lib/x86_64-linux-gnu/libKF5Archive.a(kxzfilter.cpp.o): In function `KXzFilter::uncompress()':
/src/karchive/src/kxzfilter.cpp:259: undefined reference to `lzma_code'
/usr/local/bin/../lib/x86_64-linux-gnu/libKF5Archive.a(kxzfilter.cpp.o): In function `KXzFilter::compress(bool)':
/src/karchive/src/kxzfilter.cpp:279: undefined reference to `lzma_code'
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
```

There is liblzma installed:

```
# ls /usr/lib/x86_64-linux-gnu/ | egrep zma
liblzma.a
liblzma.so
```

and even recognized by CMake:

```
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Found LibLZMA: /usr/include (found version "5.1.0") 
```

but it doesn't seem to be explicitly used in the linker command. That makes me wonder how did it work previously?

Bzip2 is reportedly missing:

```
-- The following RECOMMENDED packages have not been found:

 * BZip2 , Support for BZip2 compressed files and data streams , <https://sourceware.org/bzip2/>
   Support for BZip2 compressed files and data streams
```

but I doubt it might be an issue.

So my best guess so far is the following:
- we didn't have liblzma installed previously, therefore karchive (as a dependency of the **kimageformats** project) did not even try to use it, everything worked well;
- now, karchive's CMake sees liblzma available and enables it in the karchive build, but does not link with lzma library files. Then, when we come to the final link step, the final fuzz target links with karchive which has unresolved lzma calls.

This rather feels like an issue in the karchive CMake rules: why does it enable liblzma dependent features but doesn't link the lzma library? There is `-DBUILD_SHARED_LIBS=OFF`, so I wouldn't expect any missing dependencies after the build, but I might be wrong.

I'll try to estimate how many more projects got affected by that change. I frankly was hoping that we'd remove libunwind from the base-builder image, but apparently we ended up adding even more dependencies instead :(

**Comment by Dor1s** [comment]
Let me rename the issue a little bit a track the whole issue here. Thanks a lot @tsdgeos for reporting this!

**Comment by Dor1s** [comment]
Looks like ~12 breakages in total: https://bugs.chromium.org/p/oss-fuzz/issues/list?sort=-id&colspec=ID%20Type%20Component%20Status%20Proj%20Reported%20Owner%20Summary&q=id%3A18921%2C18922%2C18923%2C18924%2C18925%2C18926%2C18927%2C18928%2C18929%2C18931%2C18933%2C18934&can=1

Mostly unresolved symbols.

Two MSan issues ([18922](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18922) and [18923](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18923)), both are happening in the allocations created by zlib, so I guess we might be installing a buggy version, or the caller expectations are different in that version?

One issue ([18926](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18926)) is not so clear, but based on the maintainer's comment it looks like it is also sudden and the timing perfectly matches the base-builder upgrade.

@oliverchang in which configurations are we planning to use hongfuzz? If it's only ASan, let's build it right inside the base-builder and then delete the dependencies it needs?

**Comment by tsdgeos** [comment]
> Yes, zlib is now included in the base image. @tsdgeos is it obvious to you why this would be causing failures?

For example for poppler now freetype finds zlib which means that freetype builds new code, but since it's all static libraries it means that the final binary now suddenly also has to link against zlib when before it had not, that's a bit unexpected

**Comment by tsdgeos** [comment]
> That makes me wonder how did it work previously?

It didn't work because simply that codepath wasn't exercised, the only karchive support needed for kimageformats is zip so the lzma codepath wasn't built (as you guessed below)

> This rather feels like an issue in the karchive CMake rules: why does it enable liblzma dependent features but doesn't link the lzma library? 

Because that's how static linking works, isn't it?

AFAIK the final binary has to link to all static libs, so if now suddenly karchive depends on liblzma, the final binary (i.e. the fuzzer) has not only to link to karchive but also to liblzma

**Comment by tsdgeos** [comment]
About https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18923 maybe it is because it gets confused by having two zlibs around, the one i build and the one in the base image?

Would you recommend dropping the one i'm bulding?

**Comment by inferno-chromium** [comment]
@tsdgeos - hold off on making changes from your side, we will see if we can revert the deps addition.

**Comment by oliverchang** [comment]
Thanks @Dor1s for investigating!

> I'll try to estimate how many more projects got affected by that change. I frankly was hoping that we'd remove libunwind from the base-builder image, but apparently we ended up adding even more dependencies instead :(

Any reason you wanted to see dependencies removed from base-builder rather than base-runner (libunwind was removed there). Apart from this issue which was quite unexpected to me :) 

>  in which configurations are we planning to use hongfuzz? If it's only ASan, let's build it right inside the base-builder and then delete the dependencies it needs?

Just ASan right now, but this is quite hacky. Let me think more to see if there is a better fix...

**Comment by Dor1s** [comment]
> Any reason you wanted to see dependencies removed from base-builder rather than base-runner (libunwind was removed there). Apart from this issue which was quite unexpected to me :)

Ah, right, that one was affecting base-runner -- so I mixed things up, my bad. Yeah, base-builder should be flexible then, but looks like it is not always easy to change the deps we install in it.

**Comment by Dor1s** [comment]
> Because that's how static linking works, isn't it?

Makes sense, you're right.

**Comment by oliverchang** [comment]
Couldn't come up with anything better, so I have a PR out to precompile honggfuzz and install the required dependencies temporarily.

**Comment by oliverchang** [comment]
This was done (forgot to close). Let us know if you notice any other issues.
