### ISSUE TITLE
Auto-update LLVM binaries in the base-runner image

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#3067]
We have llvm-cov, llvm-profdata, and llvm-symbolizer binaries in the base-runner image. These binaries are part of OSS-Fuzz repo checkout. This is weird and does cause problems sometimes (e.g. #3065 is the most recent one).

As we intend to separate the runner image from the builder, we do not inherit anything from the builder and do not have real up-to-date LLVM binaries in the runner.

Ideal solution would be to upload these binaries from the base-builder image and then download and install when building the base-runner.

An alternative solution would be to grep the Chromium's LLVM update script and download the latest Chromium bundle to grab the binaries. I don't think it's a sane idea, and the "ideal" solution seems quite doable.

**Comment by Dor1s** [comment]
My original intent is to upload only those three binaries into a location named e.g. `gs://clusterfuzz-builds/oss-fuzz-base-runner-binaries/<DATE>/binaries.zip` and also with the `latest` instead of `<DATE>`.

I think we can also publish the whole LLVM bundle in this fashion, in case any of the users want to download it and use on their machine. Do people think it's worth doing?

Any other benefit we can get if we add a functionality for uploading anything built in the base-images?

**Comment by jonathanmetzman** [comment]
I actually don't see the chromium+grep solution as such a bad one to be honest.

**Comment by oliverchang** [comment]
How about a docker multi stage build? Where we inherit from the base-builder in the first state of the base-runner build, just to copy these binaries? The resulting image won't be based on base-builder.

https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by Dor1s** [comment]
That is awesome, @oliverchang! I didn't know that feature, thanks for the suggestion. I'll give it a shot.
