### ISSUE TITLE
deadline notifications for public bugs

### ISSUE THREAD

**Issue by dvyukov** [google/oss-fuzz#3071]
For syzkaller project all reported bugs are CCed to a public mailing list right away. But we still getting several notifications per bug about approaching deadline and derestriction:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=16961#c1

It's not that it's too critical, and I don't know how many other projects experience the same (though, I would assume some OSS projects also open bugs right away?), but if it's not too hard to do, it would be nice to be able to opt out some projects from these notifications.

**Comment by inferno-chromium** [comment]
Can submit a patch like this - https://github.com/google/oss-fuzz/blob/master/projects/llvm/project.yaml#L26

**Comment by dvyukov** [comment]
Hmmm, but we already have this:
https://github.com/google/oss-fuzz/blob/master/projects/syzkaller/project.yaml#L11

**Comment by alex** [comment]
@inferno-chromium the problem is that sherrifbot still leaves comments on monorail about "disclosure" even for bugs that are public

**Comment by inferno-chromium** [comment]
@mbarbella-chromium - how can we fix sheriffbot to avoid updating public bugs, i think skipping if bug does not have restrict-view-commit should be enough ?

**Comment by oliverchang** [comment]
I submitted a patch to sheriffbot to fix this.
