### ISSUE TITLE
expat and libfido2 fuzz targets do not seem to be executed by OSS-Fuzz: no stats, no logs, no corpora

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#3078]
Hello,

After a recent libexpat PR was merged (see #3041 ), I was alerted of a coverage build failure. The interesting portion of the build log is as follows

```
Starting Step #5
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: [/corpus/xml_parse_fuzzer_ISO-8859-1.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/xml_parse_fuzzer_ISO-8859-1.zip or
Step #5:         /corpus/xml_parse_fuzzer_ISO-8859-1.zip.zip, and cannot find /corpus/xml_parse_fuzzer_ISO-8859-1.zip.ZIP, period.
```

and this happens for all the other expat fuzzer binaries as well. Any idea what may be going wrong? As far as I can tell, expat's build script is not doing anything to create a seed corpus.

**Comment by Dor1s** [comment]
Did you change names of the fuzz target binaries? Would it be possible to preserve the original names while switching to the upstream repo? Otherwise, we'll be losing open crashes, corpora that we've accumulated over the years, and coverage might be flaky for a day or two. It's highly recommended not to change names of the fuzz targets.

**Comment by bshastry** [comment]
@Dor1s Ah, indeed. I just noticed that the names are different in the upstream (expat) build.

I would need to CC @hartwork here because this would mean that the naming scheme of fuzzers need to be changed here in a non-trivial way

Old name
  - parse_`encoding`_fuzzer, where `encoding` contains underscore separated names e.g., `UTF_8`.
  - Example: `parse_UTF_8_fuzzer` is the name of the fuzzer binary in the old (oss-fuzz maintained) build

New name
  - xml_parse_fuzzer_`encoding`, where `encoding` contains hyphen separated names e.g., `UTF-8`
  - Example: `xml_parse_fuzzer_UFT-8` is the name of the fuzzer binary in the new (upstream) build

Note:
  - upstream build introduces new fuzzing binaries named `xml_parsebuffer_fuzzer_`encoding`` that were not present before.
  - The new targets are built from a newer fuzzing harness in upstream expat

@Dor1s Would it be possible to "transfer" the old corpus to the new fuzzers named "xml_parse_fuzzer_encoding" where encoding name is hyphen separated AND treat the new set of fuzzers whose name is `xml_parsebuffer_fuzzer_encoding` (encoding name hyphen separated)?

**Comment by Dor1s** [comment]
Transferring the corpora would be helpful, but there are still other issues with renaming fuzz targets. I could copy the old corpus (even though we don't do that in general as it requires manual labor and doesn't scale), but it seems to be that something is wrong (either with the fuzz targets or with OSS-Fuzz).

This is the list of fuzz targets we build:

```
$ gsutil cat gs://clusterfuzz-builds/expat/targets.list.address
xml_parsebuffer_fuzzer_US-ASCII
xml_parse_fuzzer_ISO-8859-1
xml_parse_fuzzer_UTF-8
xml_parse_fuzzer_UTF-16LE
xml_parsebuffer_fuzzer_UTF-16
xml_parse_fuzzer_UTF-16BE
xml_parse_fuzzer_US-ASCII
xml_parsebuffer_fuzzer_UTF-8
xml_parsebuffer_fuzzer_ISO-8859-1
xml_parsebuffer_fuzzer_UTF-16LE
xml_parse_fuzzer_UTF-16
xml_parsebuffer_fuzzer_UTF-16BE
```

And this is the list of corpus directories we have (i.e. the targets we run):

```
$ gsutil ls gs://expat-corpus.clusterfuzz-external.appspot.com/libFuzzer
gs://expat-corpus.clusterfuzz-external.appspot.com/libFuzzer/expat_parse_ISO_8859_1_fuzzer/
gs://expat-corpus.clusterfuzz-external.appspot.com/libFuzzer/expat_parse_US_ASCII_fuzzer/
gs://expat-corpus.clusterfuzz-external.appspot.com/libFuzzer/expat_parse_UTF_16BE_fuzzer/
gs://expat-corpus.clusterfuzz-external.appspot.com/libFuzzer/expat_parse_UTF_16LE_fuzzer/
gs://expat-corpus.clusterfuzz-external.appspot.com/libFuzzer/expat_parse_UTF_16_fuzzer/
gs://expat-corpus.clusterfuzz-external.appspot.com/libFuzzer/expat_parse_UTF_8_fuzzer/
gs://expat-corpus.clusterfuzz-external.appspot.com/libFuzzer/expat_parse_fuzzer/
gs://expat-corpus.clusterfuzz-external.appspot.com/libFuzzer/parse_ISO_8859_1_fuzzer/
gs://expat-corpus.clusterfuzz-external.appspot.com/libFuzzer/parse_US_ASCII_fuzzer/
gs://expat-corpus.clusterfuzz-external.appspot.com/libFuzzer/parse_UTF_16BE_fuzzer/
gs://expat-corpus.clusterfuzz-external.appspot.com/libFuzzer/parse_UTF_16LE_fuzzer/
gs://expat-corpus.clusterfuzz-external.appspot.com/libFuzzer/parse_UTF_16_fuzzer/
gs://expat-corpus.clusterfuzz-external.appspot.com/libFuzzer/parse_UTF_8_fuzzer/
gs://expat-corpus.clusterfuzz-external.appspot.com/libFuzzer/parse_fuzzer/
```

I don't see any matches. Do you know if fuzz targets are running fine? Should we get worried and look for an issue on our end?

**Comment by Dor1s** [comment]
I've tried running a couple fuzz targets and they seem to work fine. I'm afraid there is an issue on our end and these targets aren't being executed properly. The coverage build should've auto-recovered in a couple days one corpus backups for new fuzzers are produced, but that didn't happen. Let me rename the issue.

**Comment by Dor1s** [comment]
Looks like this affects multiple projects, but not all of them. I do not see any cron failures, so presumably CPU allocation and all that management stuff works fine. I've also verified that e.g. expat gets reasonable sized GCE clusters allocated.

**Comment by Dor1s** [comment]
//cc @inferno-chromium @oliverchang please see my previous comment when you get back to work :)

**Comment by Dor1s** [comment]
@oliverchang says it could be caused by minijail, need to test

**Comment by inferno-chromium** [comment]
https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2019-12-05&date_end=2019-12-11&fuzzer=libFuzzer&project=libfido2 seem normal
https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2019-12-05&date_end=2019-12-11&fuzzer=libFuzzer&project=expat seem normal 

but fuzzer stats by fuzzer is broken for everywhere
@oliverchang - might be a memcache regression with huge data.

**Comment by Dor1s** [comment]
@oliverchang recreated host bots yesterday and things seem to recover, but it's still interesting to find out what's happened.

@jonathanmetzman mentioned the following in https://github.com/google/clusterfuzz/pull/1256:

I was curious if something happened since AFL and LF are performing nearly the same this month (https://docs.google.com/spreadsheets/d/18q5JGzU2pGv4FJhRjeVkXGi3bZ2dRU7SxagC_aupzAo/edit#gid=1198170776) unlike nearly every other month. -- **the doc is not publicly accessible I believe**

I'm checking the logs and seeing some other projects not running too. Again, all should be fixed now (thanks @oliverchang), but that's weird.

**Comment by Dor1s** [comment]
Things seem to recover. We now have stats, logs, and coverage reports.

AFL vs LF distribution also seems to be recovering as per https://docs.google.com/spreadsheets/d/18q5JGzU2pGv4FJhRjeVkXGi3bZ2dRU7SxagC_aupzAo/edit#gid=1198170776

The question now is what long term solution we can have? Auto-recreation of the hosts, perhaps?

**Comment by inferno-chromium** [comment]
one big root cause fixed in https://github.com/google/clusterfuzz/pull/1799
