### ISSUE TITLE
Build logs on oss-fuzz

### ISSUE THREAD

**Issue by asraa** [google/oss-fuzz#3084]
Hey! Would it be possible to view the last passing build logs on oss-fuzz? Envoy's build's are failing, and I've found it really helpful to see other bazel projects build logs (some also failing with the same reason). I would also love to see a passing build log so I can easily diff the two (or at least pull dates so I can diff bazel and clang versions).

**Comment by Dor1s** [comment]
Hey @asraa, I don't think we have a great way to do that, but I can think of a couple options:

1) Do you have access to the "internal Builds dashboard" linked from this page: https://google.github.io/oss-fuzz/reference/useful-links/#build-status ?

If yes, then you could see all Envoy builds on this page https://builder.oss-fuzz.com/job/projects/job/envoy/

To access the logs, you'd need to click on the build number, then click on the "Console output", then you'll see the log id and link to the StackDriver viewer.

2) All build logs are uploaded to `gs://oss-fuzz-gcb-logs` bucket. It appears to be quite huge (I'm still running `du -hs` on it), but I think we can make it work by setting a lifecycle policy on it to remove old logs. Once we do that, you should be able to download all the logs and grep for those that relate to Envoy project.

3) (probably the best long term solution) We should update the build script (https://github.com/google/oss-fuzz/blob/master/infra/gcb/build_project.py) to distinguish logs somehow (maybe we can append a project suffix or use tags from https://cloud.google.com/cloud-build/docs/build-config#logsbucket)

In your case I'm really hopeful that we'll make option 1) work, but if there is any more demand we should work on option 3) then.

**Comment by jonathanmetzman** [comment]
I think this is possible. If you look at the [build logs page for envoy](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#envoy) (which is currently failing again), you can see "Last Successful build:"
