### ISSUE TITLE
Use CODEOWNERS for projects/ directories

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#3103]
GitHub supports the code owners concept for code reviews: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-file-location

@inferno-chromium suggested to do this for projects using OSS-Fuzz to speed up process of making project specific changes (+ have less burden for OSS-Fuzz team).

If any of our users is reading this and wants to try it, please let us know!

**Comment by oliverchang** [comment]
Only issue is the codeowners have to have blanket write access to the repository:

> The people you choose as code owners must have write permissions for the repository.

**Comment by Dor1s** [comment]
Hm, I was thinking that protected branch settings would take care of that. We should require at least one approval from a Code Owner and only administrators may push changes directly.

If there is demand, will definitely have to test whether the state we want is achievable at all, thanks @oliverchang !

**Comment by nevun** [comment]
@Dor1s I would be happy to try it out for the libfido2 project

**Comment by mhlakhani** [comment]
I'd be happy to test this out for Facebook owned projects.

**Comment by jonathanmetzman** [comment]
Since CODEOWNERS need to have write access (see [docs](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners)). I'm not sure it makes sense to use.
