### ISSUE TITLE
Tracking bug for improving user / maintainer experience, making OSS-Fuzz even more self service

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#3104]
Please add more comments / examples of issues that are common:
- **fuzzing build failures**: not very common (thanks CI and local script), but sometimes developers don't notice a particular sanitizer / fuzzing engine that if failing
 - [x] Action Item: in build failures, report a particular `--sanitizer` and `--engine` to reproduce the failure (done in #3208 and #3213)
- **coverage build failures**: relatively often, various reasons: missing corpus, something wrong with the build, etc
- [x] Action Item: report missing corpus issue explicitly (done in #3208 and #3213)
- **other build failures** (e.g. https://github.com/google/oss-fuzz/issues/3093): sometimes due to toolchain update, sometimes with no apparent reason
- **unreproducible bugs**: sometimes bugs are explicitly unreproducible, but it's not obvious to devs; other cases are more subtle usually (hardware differences or sanitizer options)

**Comment by inferno-chromium** [comment]
another optimization would be to save manual time for build fixes review. using something like OWNERS file will help devs merge these quicker. I think our latency is usually <1 hour, but this is engineering cycles we should save.

**Comment by Dor1s** [comment]
Thanks @inferno-chromium, tracking issue for that: https://github.com/google/oss-fuzz/issues/3103

**Comment by Dor1s** [comment]
Another case where corpus pruning is failing and we do not report it anyhow: https://github.com/google/oss-fuzz/issues/3224

**Comment by Dor1s** [comment]
CQ proposal: https://github.com/google/oss-fuzz/issues/3478
