### ISSUE TITLE
New UBSAN error : Invalid-enum-value

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#3105]
There seems to be a new UBSAN warning.
But I do not know how to fix the bugs (if it is any bug at all).

How should we deal with some code like this ?

```
typedef enum {
    myenum_value1 = 1,
    myenum_value2 = 2,
} myenum;

int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size) {
    if (Size < 1) {
        return 0;
    }
    myenum value = (myenum) Data[0];
    switch (value) {
        case myenum_value1:
            //do something
        case myenum_value2:
            //do something else
        default:
            //unknown value, do not process
            return 0;
    }
    return 0;
}
```

**Comment by inferno-chromium** [comment]
-fsanitize=enum: Load of a value of an enumerated type which is not in the range of representable values for that enumerated type.

https://wiki.sei.cmu.edu/confluence/display/cplusplus/INT50-CPP.+Do+not+cast+to+an+out-of-range+enumeration+value

**Comment by catenacyber** [comment]
Thanks for the pointer
