### ISSUE TITLE
Coverage report for golang projects

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#3106]
Coverage report is great but not yet available for golang projects.

Here is my trick to get one :
Write a golang test (like a file named fuzz_test.go) for the package you are fuzzing
```
package mypackagebeingfuzzed

import (
	"io/ioutil"
	"os"
	"testing"
)

func TestFuzzCorpus(t *testing.T) {
	dir := os.Getenv("FUZZ_CORPUS_DIR")
	if dir == "" {
		t.Logf("No fuzzing corpus directory set")
		return
	}
	infos, err := ioutil.ReadDir(dir)
	if err != nil {
		t.Logf("Not fuzzing corpus directory %s", err)
		return
	}
	filename := ""
	defer func() {
		if r := recover(); r != nil {
			t.Error("Fuzz panicked in "+filename, r)
		}
	}()
	for i := range infos {
		filename = dir + infos[i].Name()
		data, err := ioutil.ReadFile(filename)
		if err != nil {
			t.Error("Failed to read corpus file", err)
		}
		FuzzFunction(data)
	}
}
```

That should be pretty reusable except for the function naming `FuzzFunction` 

Then run bash commands 
```
export FUZZ_CORPUS_DIR=/path/to/directorywithcorpus/
cd $GOPATH/src/path/to/mypackagebeingfuzzed
go test -coverprofile fuzz.cov -run TestFuzzCorpus
go tool cover -html=fuzz.cov -o covreport.html
```

And then you can browse your covreport.html

Can it be integrated into oss-fuzz somehow ?

**Comment by Dor1s** [comment]
Thanks @catenacyber, let's continue discussing this in #2817.

**Comment by catenacyber** [comment]
Thanks @Dor1s : I was surprised to be the first one to request for this, but did not find the duplicate issue while searching for golang instead of gofuzz
