### ISSUE TITLE
Wrong startup_crash report

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#3107]
For gonds project, there are a lot of startup crash reports :
https://oss-fuzz.com/performance-report/libFuzzer_gonids_fuzz/libfuzzer_asan_gonids/latest

But when I click on one :
https://storage.cloud.google.com/gonids-logs.clusterfuzz-external.appspot.com/libFuzzer_gonids_fuzz/libfuzzer_asan_gonids/2019-12-11/10:40:22:815046.log

I get 
```
Component revisions (build r201912110358):
Afl: 8da80951dd7eeeb3e3b5a3bcd36c485045f40274

Return code: 1

Command: /mnt/scratch0/clusterfuzz/resources/platform/linux/minijail0 -f /tmp/tmpw3SdnR -U -m '0 1337 1' -T static -c 0 -n -v -p -l -I -k proc,/proc,proc,1 -P /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-403/tmpRM7R8D -b /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-403/tmp4tvOsq,/tmp,1 -b /lib,/lib,0 -b /lib32,/lib32,0 -b /lib64,/lib64,0 -b /usr/lib,/usr/lib,0 -b /usr/lib32,/usr/lib32,0 -b /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_gonids_4fd1d07459dc0e09cc34419f8d397495d6d91ed0/revisions,/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_gonids_4fd1d07459dc0e09cc34419f8d397495d6d91ed0/revisions,0 -b /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_gonids_4fd1d07459dc0e09cc34419f8d397495d6d91ed0/revisions,/out,0 -b /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-403/new,/new,1 -b /mnt/scratch0/clusterfuzz/bot/inputs/data-bundles/global/gonids_fuzz,/gonids_fuzz,1 -b /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases,/fuzzer-testcases,1 /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_gonids_4fd1d07459dc0e09cc34419f8d397495d6d91ed0/revisions/fuzz -timeout=25 -rss_limit_mb=2048 -fork=1 -artifact_prefix=/fuzzer-testcases/ -max_total_time=6150 -print_final_stats=1 /new /gonids_fuzz
Bot: oss-fuzz-linux-zone3-worker-gonids-3nmc
Time ran: 6231.82507396

INFO: Seed: 1559086869
INFO: 65536 Extra Counters
INFO: -fork=1: fuzzing in separate process(s)
INFO: -fork=1: 1203 seed inputs, starting to fuzz in /tmp/libFuzzerTemp.1.dir
#31137: cov: 0 ft: 5511 corp: 1203 exec/s 15568 oom/timeout/crash: 0/0/0 time: 4s job: 1 dft_time: 0
#48586: cov: 0 ft: 5511 corp: 1203 exec/s 5816 oom/timeout/crash: 0/0/0 time: 7s job: 2 dft_time: 0
#74263: cov: 0 ft: 5511 corp: 1203 exec/s 6419 oom/timeout/crash: 0/0/0 time: 11s job: 3 dft_time: 0
```
End it ends with
```
#52296584: cov: 0 ft: 5511 corp: 1203 exec/s 11081 oom/timeout/crash: 0/0/0 time: 5793s job: 106 dft_time: 0
#52807012: cov: 0 ft: 5511 corp: 1203 exec/s 4726 oom/timeout/crash: 0/0/0 time: 5901s job: 107 dft_time: 0
#53955324: cov: 0 ft: 5511 corp: 1203 exec/s 10534 oom/timeout/crash: 0/0/0 time: 6010s job: 108 dft_time: 0
#55097347: cov: 0 ft: 5511 corp: 1203 exec/s 10382 oom/timeout/crash: 0/0/0 time: 6120s job: 109 dft_time: 0
#56056437: cov: 0 ft: 5511 corp: 1203 exec/s 8640 oom/timeout/crash: 0/0/0 time: 6231s job: 110 dft_time: 0
INFO: fuzzed for 6231 seconds, wrapping up soon
INFO: exiting: 0 time: 6231s
cf::fuzzing_strategies: fork:1
```

So, it looks to me like a normal run without crash, is it not ?

**Comment by inferno-chromium** [comment]
Is the fuzz target returning 0 exit code ? Minijail transforms a non-zero exit code into 1.

**Comment by catenacyber** [comment]
Yes 
@jonathanmetzman and I talked about this : https://github.com/google/oss-fuzz/pull/2995#discussion_r341157582

My guess is that oss-fuzz go integration returns 0 from `LLVMFuzzerTestOneInput` even if the golang `Fuzz` returned otherwise

Do you know where I can check this ?

**Comment by inferno-chromium** [comment]
@Dor1s - what are your thoughts here ?

**Comment by Dor1s** [comment]
Somehow the `INITED` line is missing, probably due to the fork mode being used. Might be an issue for regular targets as well

**Comment by catenacyber** [comment]
Ping.
This is still the case : 
https://oss-fuzz.com/performance-report/libFuzzer_gonids_fuzz_parserule/libfuzzer_asan_gonids/2020-01-09
reports that startup_crash should be improved

But, the proposed logs do not show any startup crash :
https://00e9e64bac7c288674e0565d1fd67cf135f74d238b7c0a98fc-apidata.googleusercontent.com/download/storage/v1/b/gonids-logs.clusterfuzz-external.appspot.com/o/libFuzzer_gonids_fuzz_parserule%2Flibfuzzer_asan_gonids%2F2020-01-09%2F07:35:24:413717.log?qk=AD5uMEuA4fP3E6g1uwFMzbFZ8LTRVtRrkOFxoQa6pDOPpnnLcpmIuyWxNtW0FYgNyCLwKRWVrmoV5bWh8Mx65JSYB9waoX2IMD-_nAl7rIM1h0ynz0f9J0uil7KwVqJZ95mLosW-zpl3wB6q3Hm6PqOLob8bE1TS5HdPgzemqb2fbEOF8mWjzQhv0iwkKox3P3I0kho6V7kSbEAl1oNsfYvsBdn0mQ0FYGQASGpD7OrPwzWfcCDFr86iDpAM9z3eWacRvq5dDBxAhk-sn718jrncsX6__rKEB97ixqFDWjXYy0_ty3kZCgF5b-D9hd_oQnvVbBmoBtHO0BNh7WwKah12NqVgfRRMZZESj78YxZ0tdtix94WknuULkcOYFXb1aCyeD2oLyNbAs34xdqafaVx_LB8jOtpNU_W40rBG-O6qHStxwMf_C6nGopGB3qLbV4wuSm3aSxKPRFjX0ZLFuTlS7pach7F4Iu3wLV_72k-wSdcXfgMeR4RE9QFvxmFUGz7Xnomo2GJ5CjAOZyh-SuAWbNAjYpvViGv3lDI8vR0U64U0JZrEW69Nm-ihbjBs-yHtmhyA-g0RVKYyNqHS8eIrSOqTb_srqkgIeDAw3Y4HDq08yAICyJ3PMm63aJUd42O7gFG9EIx0SLqiQDQN01nbXomUNQQeYCRf5OPy67oD9tSC3YrwkL9HozhtIrNIR9RtXb4raNye43a3aUHrOy3TNurknlk5NND9Yb4UDSD9DJ5uv9RynusX3xLfvz0vzrs7-WdxiP63dtCahDsuh6wqZJccBOcKSMbzDPmvRFpFKWkeMlw4veRGozYKqzWmgpy0P0nVIFeReGYzzjRWAETepEstQq7PMwsGtKrACAkr1_nrwCXFYigB5Gc4qN8fKjY2QWkyMF-7FoCqHEsKyURi2yYtaCqSBWBPlBEdaKlgJ_zzeseMi3k

shows 
```
Return code: 1
...
INFO: fuzzed for 6211 seconds, wrapping up soon
INFO: exiting: 0 time: 6211s
cf::fuzzing_strategies: fork:1,value_profile:1
```

Can I do something about it ?

**Comment by Dor1s** [comment]
I'll try to fix this next week.

**Comment by Dor1s** [comment]
> Somehow the INITED line is missing, probably due to the fork mode being used. Might be an issue for regular targets as well

Yeah, logs in the fork mode do not have `INITED` line, but somehow C/C++ targets are not affected by this.

**Comment by catenacyber** [comment]
Thanks, let's wait to see if oss-fuzz still complains about it for gonids project

**Comment by Dor1s** [comment]
It will take a day or two to take an effect. Let me re-open the issue for now (GitHub auto-closed it based on my comment in CF repo).

**Comment by catenacyber** [comment]
Ok, I will check next week

**Comment by Dor1s** [comment]
Seems to be working! https://oss-fuzz.com/performance-report/libFuzzer_gonids_fuzz_parserule/libfuzzer_asan_gonids/2020-01-16

Only 0.66% of runs are reported as `startup_crashes` as of yesterday, and I believe it will be 0 for today.

**Comment by catenacyber** [comment]
Thanks @Dor1s it works indeed
