### ISSUE TITLE
Fuzzer logs link does not show when all job types is selected

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#312]
https://clusterfuzz-external.appspot.com/v2/fuzzer-stats/by-fuzzer/2017-01-17/2017-01-23/fuzzer/libFuzzer

**Comment by Dor1s** [comment]
I guess we could delete them when removing old stats pipeline. Looking now.

**Comment by Dor1s** [comment]
No, we still have those links on internal CF. Should be something else.

**Comment by inferno-chromium** [comment]
No, i dont see the fuzzer_logs links on internal CF either.

**Comment by Dor1s** [comment]
If you choose a job type, links are there. @oliverchang is it expected?

**Comment by inferno-chromium** [comment]
In this case, we should give link to the fuzzer directory root, and then person can choose whichever job type they want to see it for. thoughts ?

**Comment by Dor1s** [comment]
Makes sense. But we get bucket name using a job name via `getValueFromJobDefinition`, so we need a workaround for that...

**Comment by oliverchang** [comment]
> Makes sense. But we get bucket name using a job name via getValueFromJobDefinition, so we need a workaround for that...

Yeah, that's why it's not being shown in the group by job case, since each job could have a different log bucket. We can probably show the fuzzer link if every job for that child fuzzer has the same logs bucket (we'll need to pre-compute and cache this to make it fast).

**Comment by inferno-chromium** [comment]
More issues, it can sometimes forget about job type selected.
E.g. try
1. Go to https://clusterfuzz-external.appspot.com/v2/fuzzer-stats/by-fuzzer/2017-01-30/2017-02-05/fuzzer/libFuzzer_boringssl_pkcs8/job/libfuzzer_asan_boringssl?path=gs%3A%2F%2Fboringssl-logs.clusterfuzz-external.appspot.com%2FlibFuzzer_boringssl_client%2Flibfuzzer_asan_boringssl%2Fperformance_analysis.html
2. Select another boringssl fuzzer
3. Click submit.
4. See it forgets about job type from last link and instead shows it for All. Since the result is for All, it does not show performance and logs, very annoying to miss.

**Comment by oliverchang** [comment]
I can no longer reproduce the issue in https://github.com/google/oss-fuzz/issues/312#issuecomment-277770756 after a recent deployment. My guess is that somehow we made a bad deployment somewhere, as I could only reproduce on the main instance and never on staging.

**Comment by inferno-chromium** [comment]
Yes it does not reproduce now, so weird!!!!!!!!!!!!!

**Comment by oliverchang** [comment]
Should be fixed now.
