### ISSUE TITLE
ClusterFuzz has closed a reproducible issue

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#313]
The https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=182 is still reproducible, there were no source changes, but CF has decided to close it.

**Comment by inferno-chromium** [comment]
I took libtsm%2Flibtsm-address-201701240001.zip build and it reproduces every time on ClusterFuzz. When this happens, need to see on that particular log. right now i lost it.

**Comment by oliverchang** [comment]
happened again: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=449 

looks like CF got a different crash state that didn't match the original and therefore thought the crash doesn't repro anymore. still investigating...

**Comment by inferno-chromium** [comment]
So, so yes, crash states are too different for similarity algorithm (only first frame match). I don't want to make an exception here, need to think more.

https://clusterfuzz-external.appspot.com/v2/testcases?q=vte_write_debug

**Comment by oliverchang** [comment]
Let's continue discussion in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=466 to avoid leaking crash information.

**Comment by inferno-chromium** [comment]
This is now fixed.
