### ISSUE TITLE
"Progression task started", but never seems to end

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#3130]
https://oss-fuzz.com/testcase-detail/5675859411468288 seems to be stuck trying to determine if the bug is fixed or not. I'm fairly confident this report is the same underlying bug shown as fixed in https://oss-fuzz.com/testcase-detail/5638500712185856

But https://oss-fuzz.com/testcase-detail/5675859411468288 always seems to be in a "Progression task started" state over the last three or so days

**Comment by inferno-chromium** [comment]
`Failed to make space for build.`

Increasing disk size for libreoffice builds

**Comment by inferno-chromium** [comment]
fixed, and it finished.
