### ISSUE TITLE
JavaScript fuzzers

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#3155]
I've got libFuzzer-based JavaScript fuzzing working. If you're interested let me know which projects you'd like to see fuzzed and are eligible for an initial integration reward. Preferably something simple like file format (eg. images) parsers to start with; complex stuff like detecting XSS in JS frameworks and DOM emulation should be possible and could be a nice future exercise but I'd like to test how well simple stuff goes first.

**Comment by baptistapedro** [comment]
Share?

**Comment by inferno-chromium** [comment]
Sorry we didn't respond here. Structure aware fuzzing will be eligible for high rewards. I am curious if you can add javascript fuzzing with chromium d8 shell or any browser js shell, that would be a nice project to add in OSS-Fuzz. simple stuff, start with any popular image or video parsers (things that have low coverage).

**Comment by guidovranken** [comment]
> Structure aware fuzzing will be eligible for high rewards.

What is this? Structured fuzzing of Javascript projects is eligible for higher rewards than normal?

> I am curious if you can add javascript fuzzing with chromium d8 shell or any browser js shell, that would be a nice project to add in OSS-Fuzz.

I've previously spent a considerable amount of time to extract a coverage signal from V8 and Chakra but due to the underlying JIT magic I wasn't able to do it. I eventually settled on Fabrice Bellard's QuickJS which only is an interpreter, not a JIT. Source code is [here](https://github.com/guidovranken/libfuzzer-js) (needs a little work but generally works as expected).
My intention was to use this for fuzzing Javascript projects on OSS-Fuzz.

> simple stuff, start with any popular image or video parsers (things that have low coverage).

I'm gonna look for a project to fuzz.

**Comment by inferno-chromium** [comment]
> > Structure aware fuzzing will be eligible for high rewards.
> 
> What is this? Structured fuzzing of Javascript projects is eligible for higher rewards than normal?

I mean panel always takes into account the complexity of work and anything related to structure aware fuzzing will for sure qualify for higher rewards.

> 
> > I am curious if you can add javascript fuzzing with chromium d8 shell or any browser js shell, that would be a nice project to add in OSS-Fuzz.
> 
> I've previously spent a considerable amount of time to extract a coverage signal from V8 and Chakra but due to the underlying JIT magic I wasn't able to do it. I eventually settled on Fabrice Bellard's QuickJS which only is an interpreter, not a JIT. Source code is [here](https://github.com/guidovranken/libfuzzer-js) (needs a little work but generally works as expected).
> My intention was to use this for fuzzing Javascript projects on OSS-Fuzz.
> 
> > simple stuff, start with any popular image or video parsers (things that have low coverage).
> 
> I'm gonna look for a project to fuzz.
