### ISSUE TITLE
Revert clang workaround for gRPC

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#3157]
Filing this to make sure we won't forget. Related to #3093.

Either Bazel would fix the issue or maybe we'll delete the default asan_blacklist.txt in LLVM.

**Comment by asraa** [comment]
FYI bazel 3.0 released, and the fix is there. https://github.com/bazelbuild/bazel/releases/tag/3.0.0
I'm bumping Envoy upstream first.

**Comment by Dor1s** [comment]
Thanks @asraa !

@jonathanmetzman could you please give this a try later on when you get a chance? Since you've been working in the issue initially :)

**Comment by jonathanmetzman** [comment]
I don't know when this bump is going to happen. I think the individual projects should revert it themselves when they are ready.

**Comment by Dor1s** [comment]
@jonathanmetzman thanks for clarifying and sorry for the confusion, I though it was some sort of global switch you used for the workaround, my bad.

CCing people who added integrations for
- oak: @tiziano88 @ipetr0v 
- gRPC: @matt-kwong @yang-g 

You should be able to revert the clang workaround (see example in https://github.com/google/oss-fuzz/pull/3588) after Bazel upgrade.

**Comment by inferno-chromium** [comment]
@asraa: any update on this. Due to this old image used in Dockerfile [https://github.com/google/oss-fuzz/blob/master/projects/envoy/Dockerfile#L19], this will now break Honggfuzz [reason being Honggfuzz is too old in your config and we just enabled it and it breaks too due to signature chanes]. If you can update bazel version and remove that hack in Dockerfile, then you get latest fuzzing engines and honggfuzz build will get fixed too.

**Comment by asraa** [comment]
@inferno-chromium Sorry about that! We had an upstream release yesterday and were delaying our projects bazel bump (https://github.com/envoyproxy/envoy/pull/10670) until after that. I'll try to push the bump so I can revert the change.

**Comment by inferno-chromium** [comment]
Thanks @asraa !

**Comment by inferno-chromium** [comment]
ping grpc (@matt-kwong @yang-g), oak (@tiziano88 @ipetr0v) devs

please see Max's comment https://github.com/google/oss-fuzz/issues/3157#issuecomment-611192254
We need to remove this hack and also this will cause other problems, like using old inefficient version of fuzzers.

**Comment by inferno-chromium** [comment]
ping again grpc folks @matt-kwong @yang-g
