### ISSUE TITLE
Identical build and fuzz machine configs

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#3165]
Hello,

While investigating a build failure for openvswitch, I discovered the following issue

- Build machine contains libunwind making the openvswitch believe that it is supported
- Fuzz machine does not leading to a runtime failure

Openvswitch automatically detects libunwind linking against it if present i.e., there is no clean way, afaiu, to disable the detection altogether at build time.

I was wondering if it would be an option for oss-fuzz to keep build and fuzz docker environments identical so that such time-of-check-time-of-use issues don't happen?

Thank you and happy holidays!

**Comment by jonathanmetzman** [comment]
@oliverchang I thought we deleted libunwind from the runner?

**Comment by oliverchang** [comment]
Thanks! This should be fixed in about a day or so once the base images are rebuilt.
