### ISSUE TITLE
Fuzzer statistics are not generated since mid-November

### ISSUE THREAD

**Issue by lpereira** [google/oss-fuzz#3169]
I noticed that, if I log into `oss-fuzz.com`, the fuzzer statistics for Lwan generates a "Got error with status: 404 No stats." error popup, for both the libfuzzer and afl fuzzing engines.  This seems to be happening since mid-November.  I have received no new crash notifications, and builds seem to be successful according to the build logs.

Is this expected, as the fuzzers could no longer find new interesting paths, or is it something else I should be worried about?

Cheers

**Comment by inferno-chromium** [comment]
Thanks for bringing this up, looks like only fuzzing with one engine AFL is happening - https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2019-12-01&date_end=2019-12-27&fuzzer=afl&job=afl_asan_lwan&project=lwan. And libfuzzer didn't seem to get used.

Something's up with how fuzzer weights is picking fuzzing engines. @oliverchang - can you take a closer look. libfuzzer_asan_lwan has 0 multipler, weight 1 and afl_asan_lwan has 2 multipler, weight 1, any idea why only afl can keep getting picked. i dont see libfuzzer_asan_lwan ever picked up.

**Comment by oliverchang** [comment]
This should now be fixed now after https://github.com/google/clusterfuzz/commit/644f0aa69184fcb20a6327f03b423b34c5b98eb9, and the new stats should show up in a few days.

**Comment by lpereira** [comment]
Thanks, @oliverchang!

**Comment by inferno-chromium** [comment]
Stats are available
https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2019-12-30&date_end=2020-01-05&fuzzer=libFuzzer&job=libfuzzer_asan_lwan&project=lwan
