### ISSUE TITLE
[CRAS] Build pass but no recent results

### ISSUE THREAD

**Issue by b92paul** [google/oss-fuzz#3170]
cras build passes in [oss-fuzz-build](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#cras) last week but no any recent [rclient_message results](https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2019-12-09&date_end=2019-12-29&fuzzer=libFuzzer_cras_rclient_message) show in oss-fuzz after 12/20.

We don't have any error logs to debug this. Any thoughts?

Thanks!
Paul (paulhsia@chromium.org)

**Comment by inferno-chromium** [comment]
Probably similar to https://github.com/google/oss-fuzz/issues/3169. Putting this in Oliver's queue to investigate post holidays.

**Comment by oliverchang** [comment]
Looks unrelated to #3169. Taking another look here.

**Comment by oliverchang** [comment]
Results are back: https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2019-12-09&date_end=2020-01-07&fuzzer=libFuzzer_cras_rclient_message
