### ISSUE TITLE
[tesseract-ocr] Build broken after upstream code reorganisation

### ISSUE THREAD

**Issue by stweil** [google/oss-fuzz#3176]
Changes in https://github.com/tesseract-ocr/tesseract/ require small updates to get fuzzing work again. See pull request https://github.com/guidovranken/tesseract-ocr-fuzzers/pull/1 and my comments at https://github.com/google/oss-fuzz/commit/b3b4a5c3a32a0b9376a5e0fcf1ea813d43d074b4#diff-4f3038037ae4b301ee0cd2a14da14166R38.

**Comment by inferno-chromium** [comment]
No need to file an issue, PR should handle this. See my comments on timeout testcases in seed corpus. Once those are fixed, we can merge the PR.

**Comment by stweil** [comment]
See PR #3177.
