### ISSUE TITLE
[FLAC] Not able to reproduce two new ASAN failuers

### ISSUE THREAD

**Issue by erikd** [google/oss-fuzz#3184]
Two recently listed probelms:

* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19758
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19816

and I can reproduce neither of them.

**Comment by inferno-chromium** [comment]
@erikd - both of these are coming from a 32-bit build.

Did you try using
https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-build-failures
with the `--architecture i386`

**Comment by erikd** [comment]
AS noted in https://github.com/google/oss-fuzz/issues/3023 reproducing then within the Docker environment make working on a fix for the problem significantly more difficult than it needs to be. I should however be able to reproduce within a 32 bit chroot.

**Comment by erikd** [comment]
Unfortunately, 32 bit fuzzing is busted in Debian. 

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=945073
