### ISSUE TITLE
when running just built fuzzer binaries inside docker, use the full path

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#319]
.. to avoid collisions with other things in PATH, including bash builtins. 
Example from nss (https://github.com/google/oss-fuzz/pull/316#issuecomment-275352765):
```
testing hash
Using seed corpus: hash_seed_corpus.zip
hash -rss_limit_mb=2048 -timeout=25 -runs=32 /tmp/seed_corpus/
bash: line 0: hash: -s: invalid option
hash: usage: hash [-lr] [-p pathname] [-dt] [name ...]
ERROR: bad exit code: 2

```

**Comment by inferno-chromium** [comment]
Ok fixed it properly in https://github.com/google/oss-fuzz/commit/f52193a4b1e1915d47fcc80e46fb2add7cd18f3a and https://github.com/google/oss-fuzz/commit/b4f6676dcf6cb9613f610841472a9bc7e0960679

**Comment by inferno-chromium** [comment]
fix confirmed in https://oss-fuzz-build-logs.storage.googleapis.com/build_logs/nss/latest.txt
