### ISSUE TITLE
All AFL builds failing

### ISSUE THREAD

**Issue by randombit** [google/oss-fuzz#3194]
FYI it appears all projects with AFL enabled as a fuzzer are failing with AFL issue, ex

```
Step #29: /workspace/out/address/afl-fuzz -m none -i /tmp/fuzz_target_corpus -o /tmp/fuzz_target_afl_address_out /workspace/out/address/fuzz_target
Step #29: bash: /workspace/out/address/afl-fuzz: No such file or directory
Step #29: ERROR: 100% of fuzz targets seem to be broken. See the list above for a detailed information.
```

One interesting thing, zlib is not reported as a failed build but has the same error in the build log.

**Comment by inferno-chromium** [comment]
Sorry for breakage, we are looking to fix this soon.

**Comment by inferno-chromium** [comment]
Should be fixed, we reverted the CL. Will reland after a day or so till everything recovers.
