### ISSUE TITLE
Use libFuzzer's -use_value_profile=1 on a fraction of runs

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#320]
I'd like to try running libFuzzer with [`-use_value_profile=1`](http://llvm.org/docs/LibFuzzer.html#value-profile) on a fraction of runs (e.g. 30%), similarly to how we chose to run on the full corpus vs 2 inputs. 

value profiles may blow up corpus (in theory by up to 64x, in practice, by 3x-8x), 
so most likely we should continue doing the final merge as we do now (w/o value profile)

**Comment by Dor1s** [comment]
Added `-use_value_profile=1` with 33% probability. Also made recommended dictionary to be used with 50% probability.
