### ISSUE TITLE
Build started failing; change in container image?

### ISSUE THREAD

**Issue by sffc** [google/oss-fuzz#3202]
The OSS build for myanmar-tools started failing:

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19809#c1

The error is:

```
Step #4: + mkdir -p /workspace/out/address/lib
Step #4: + cp libmyanmartools.so /workspace/out/address/lib
Step #4: + cp /usr/lib/x86_64-linux-gnu/libunwind.so.8 /workspace/out/address/lib/
Step #4: cp: cannot stat '/usr/lib/x86_64-linux-gnu/libunwind.so.8': No such file or directory
```

This used to work fine.  Did something change in the base image used to build the fuzzer?

**Comment by sffc** [comment]
Our Dockerfile is: https://github.com/google/oss-fuzz/blob/master/projects/myanmar-tools/Dockerfile

**Comment by inferno-chromium** [comment]
libunwind is no longer part of base image. (https://github.com/google/oss-fuzz/commit/81c465662194fefeca2a80cc4426789f7683b7e3)
Please install libunwind-dev explicitly in your project Dockerfile

**Comment by inferno-chromium** [comment]
uploaded a PR, lets see if fixes.
