### ISSUE TITLE
Testcase size rounding can be misleading

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#323]
e.g. https://clusterfuzz-external.appspot.com/v2/testcase-detail/5416064150142976

Here the testcase size is 2 bytes, but is shown in UI (and bug tracker) as 0.00 Kb.

**Comment by inferno-chromium** [comment]
Tanin, can you make this use utils.getSizeString or fix getSizeString to include 2 decimal points. getSizeString understands bytes.

**Comment by inferno-chromium** [comment]
Fixed.
