### ISSUE TITLE
report indirect leaks

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#324]
[example](https://storage.cloud.google.com/libxml2-logs.clusterfuzz-external.appspot.com/libFuzzer_libxml2_xml_read_memory_fuzzer/libfuzzer_asan_libxml2/2017-01-27/00%3A02%3A10%3A522658.txt?_ga=1.85764509.504747071.1474920227)

Probably just need to add one more asan signature.

**Comment by inferno-chromium** [comment]
I see this comment in code.

    # Note that we only generate reports for direct leaks. It is possible for there
    # to be indirect leak cycles, but we intentionally do not handle this case
    # to avoid issues with suppressed direct leaks.

Kostya suggested to use first stack trace of indirect leak iff there is no direct leak.

We need to discuss this more.

**Comment by kcc** [comment]
btw, if there is a direct leak report, we should completely ignore the indirect ones.

**Comment by inferno-chromium** [comment]
https://pantheon.corp.google.com/storage/browser/gnutls-logs.clusterfuzz-external.appspot.com/libFuzzer_gnutls_private_key_parser_fuzzer/libfuzzer_asan_gnutls/2017-02-06/ is blocked on this as well. indirect leaks 70% of the time.

**Comment by inferno-chromium** [comment]
Thanks Marty for fixing this, we should start seeing reports today.
