### ISSUE TITLE
"/etc/udev/rules.d" can't be created when honggfuzz is used

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#3249]
It seems since honggfuzz was turned on by default one of systemd fuzzers has been failing with
```

Accepting input from '[STDIN]'
--
  | Usage for fuzzing: honggfuzz -P [flags] -- /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds-honggfuzz_systemd_de63b71f16a30e45dc2ea3edcd6a924885950338/revisions/fuzz-udev-rules
  | Failed to call unshare(): Operation not permitted
  | Failed to mount /sys: Operation not permitted
  | Assertion 'mkdir_p("/etc/udev/rules.d", 0755) >= 0' failed at src/fuzz/fuzz-udev-rules.c:95, function int LLVMFuzzerTestOneInput(const uint8_t *, size_t)(). Aborting.
  | AddressSanitizer:DEADLYSIGNAL
```

As far as I can remember, something like this happened (with AFL) when minijail wasn't used (which was discussed in https://github.com/google/clusterfuzz/pull/165#issuecomment-463195121).

**Comment by Dor1s** [comment]
We can disable honggfuzz for systemd for now (if you prefer). Otherwise passing this to @oliverchang who enabled honggfuzz.

**Comment by evverx** [comment]
I'd prefer to keep honggfuzz :-) I think it would be great if the environment where the fuzzers are run with honggfuzz was identical to the one created for libFuzzer (or AFL) (where the fuzzer doesn't fail).

**Comment by oliverchang** [comment]
This is because honggfuzz is run without minijail. The longer term goal has always been to get rid of it completely for all engines -- is there a way to make this target work without these offending calls?

**Comment by evverx** [comment]
Judging by https://github.com/google/oss-fuzz/issues/1983#issuecomment-442243360, that kludge makes the fuzzer work when it's run with `minjail` so at this point I'm not sure how to avoid calling `mkdir` there. It would probably be easier to figure that out if I somehow could reproduce the runtime environment.

**Comment by oliverchang** [comment]
> Judging by [#1983 (comment)](https://github.com/google/oss-fuzz/issues/1983#issuecomment-442243360), that kludge makes the fuzzer work when it's run with `minjail` so at this point I'm not sure how to avoid calling `mkdir` there. It would probably be easier to figure that out if I somehow could reproduce the runtime environment.

Sorry for the delayed reply here. Is there some way to modify the target such that it works in a non-sandboxed environment as well as a fallback? Unfortunately for the time being, we'll have targets running under both sandboxed environments (AFL, libfuzzer) and unsandboxed (honggfuzz).

**Comment by jonathanmetzman** [comment]
We no longer use minijail at all for fuzzing in OSS-Fuzz? Is this still a problem for you @evverx ?

**Comment by evverx** [comment]
As far as I know, the fuzz target was changed to get around this issue back in 2020 so I think it can be closed. Thanks!
