### ISSUE TITLE
Use a specific version of LLVM/LibFuzzer

### ISSUE THREAD

**Issue by jfoote** [google/oss-fuzz#325]
Hello,

The oss-fuzz project appears to be compiling LLVM from master/head: https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-clang/checkout_build_install_llvm.sh#L21-L26

The LibFuzzer project is still under active development, so sometimes bugs appear in this branch. For example, I presently cannot build the fuzzer for `zlib`:

```
pony:oss-fuzz jfoote$ python infra/helper.py build_fuzzers zlib
Running: docker build --pull -t ossfuzz/zlib projects/zlib
Sending build context to Docker daemon 6.144 kB
Step 1/6 : FROM ossfuzz/base-builder
latest: Pulling from ossfuzz/base-builder

[...]

Removing intermediate container f3457611283f
Step 6/6 : COPY build.sh zlib_uncompress_fuzzer.cc $SRC/
 ---> 01cf38bd949c
Removing intermediate container e2fa7fe618a4
Successfully built 01cf38bd949c
Running: docker run --rm -i --cap-add SYS_PTRACE -e BUILD_UID=502 -v /Users/jfoote/dev/oss-fuzz/build/out/zlib:/out -v /Users/jfoote/dev/oss-fuzz/build/work/zlib:/work -t ossfuzz/zlib
---------------------------------------------------------------
Compiling libFuzzer to /usr/lib/libFuzzingEngine.a .../src/libfuzzer/FuzzerShmemPosix.cpp:94:23: error: use of undeclared identifier 'errno'
             strerror(errno));
                      ^
1 error generated.
fuzzers build failed.
```

.. likely due to a bug introduced into LibFuzzer yesterday: https://github.com/llvm-mirror/llvm/commit/001f56735f831f836fb002a77097b509f0cdb7f7

We've solved this problem on our end by targeting a specific commit for fuzz builds. Doing something like that would prevent this behavior from breaking oss-fuzz fuzzer builds and help ease development of new fuzzers. 

Regardless, thanks for all the work on this project.

Jon

**Comment by kcc** [comment]
fair point.
We may need to pin the LLVM revision and have a way to test new revisions before moving to them. 
OTOH, this may actually slowdown our development and unless such situations appear frequently, 
we may not want to do this. 

The particular bug is fixed in r293389 (I hope, will check ASAP). 
Looks like the headers are different between Ubuntu 14.04 (which I use for development and which 
is used for LLVM's CI) and Ubuntu 16.04, which is used for OSS-Fuzz. 

> We've solved this problem on our end by targeting a specific commit for fuzz builds. 
As a temporary workaround -- sounds good, but don't do this permanently, it will break things on our end.

**Comment by kcc** [comment]
Just to explain my point: we are doing fixes in LLVM and libFuzzer that (usually, positively) affect OSS-Fuzz
every day. Pinning the revision on OSS-Fuzz will complicate and slow down the development. 
However, if the failures like this appear frequently we'll have to do it anyway.

**Comment by inferno-chromium** [comment]
Closing as WontFix, we can reopen this in future if this becomes a significant issue.
