### ISSUE TITLE
License of public corpora

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#3259]
For one of my clients I would like to know under which license you release the public corpora generated by OSS-Fuzz and whether any usage restrictions apply. Thanks.

**Comment by inferno-chromium** [comment]
Should be considered under same Apache OSS license https://github.com/google/oss-fuzz/blob/master/LICENSE, and there are no usage restrictions.

**Comment by guidovranken** [comment]
Thanks!
