### ISSUE TITLE
Please provide access to libreoffice test cases

### ISSUE THREAD

**Issue by DamjanJovanovic** [google/oss-fuzz#326]
Hi

I am an Apache Openoffice developer and member of its security team, and would like to be given access to the Libreoffice oss-fuzz test cases to be able to fix any security issues that it has in common with Apache OpenOffice. Please help?

**Comment by kcc** [comment]
and your e-mail needs to have a google account: 
https://github.com/google/oss-fuzz/blob/master/docs/faq.md#why-do-you-require-an-e-mail-associated-with-a-google-account

**Comment by inferno-chromium** [comment]
Closing this, since pull request is started in https://github.com/google/oss-fuzz/pull/327
