### ISSUE TITLE
[Coverage] Difference between fork and non-fork modes

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#3287]
Hi,

It has been bothering me that fuzzers run with `fork=N` argument outperform their non-fork i.e., `jobs=N workers=N` counterpart. The difference is substantial (3x higher coverage for fork mode)

Is there a difference in the way `fork` counts coverage? Is there something I could do to debug?

Thank you!

**Comment by inferno-chromium** [comment]
Probably email Kostya.
