### ISSUE TITLE
[Coverage] Fork mode corpus coverage differs from runtime coverage

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#3288]
Hi,

Here's a snapshot of runtime coverage achieved in fork mode

```
#61710978: cov: 66046 ft: 367332 corp: 23049 exec/s 103 oom/timeout/crash: 36/0/0 time: 739803s job: 2534 dft_time: 0
#61742716: cov: 66046 ft: 367345 corp: 23050 exec/s 105 oom/timeout/crash: 36/0/0 time: 740105s job: 2535 dft_time: 0
```

One would expect the same coverage `66046` PCs assuming that the corpora (`23050` test cases) are written to disk (I am assuming fork mode writes interesting coverage to disk if command line invocation includes a corpus dir i.e., `./fuzzer -fork=1 C`).

However, if I stop the forked run, and restart it with the earlier corpus, the coverage drops to a third (~`21000` PCs). Why does this happen?

The codebase under test contains a lot of template functions i.e., functions that accept a templated callable function. Could it be that `-fsanitize-coverage` arguments passed by `-fsanitize=fuzzer` do not track indirect calls.

**Comment by bshastry** [comment]
My hunch is that the merge algorithm used by fork mode at runtime is different from the one used by the command line option `-merge=1`

**Comment by Dor1s** [comment]
> My hunch is that the merge algorithm used by fork mode at runtime is different from the one used by the command line option `-merge=1`

I don't think that's the case. If you leave you fuzz target running without fork mode for a while (e.g. to reach the same number of executions, i.e. `61742716`), how many coverage edges does it report?

**Comment by bshastry** [comment]
> If you leave you fuzz target running without fork mode for a while (e.g. to reach the same number of executions, i.e. 61742716 ), how many coverage edges does it report?

I have not reached this point yet. Still, if I reuse the corpus generated by the fork mode fuzzer without fork mode, what doesn't it start at the same coverage count that fork mode showed?

My experiment is as follows

  - `./fork_mode_fuzzer forkC -fork=1`

Run this for some time

 - `cp -Rf forkC C`

 - `./fuzzer C`

Fork mode reports 60k PCs, non fork reports 20k PCs

**Comment by Dor1s** [comment]
Does fork mode report 60K PCs from the beginning, i.e. after reading the corpus? Or only after fuzzing for a while?

My previous comment was assuming that your fuzz target may have a lot of "unstable" or "non-determenistic" coverage edges, that's why over time it keeps discovering those edges and they appear unique, while actually they cannot be easily hit when reading the corpus.

I checked the code in libFuzzer that prints stats from the fork mode and didn't noticed anything obviously suspicious.

Is your fuzz target in OSS-Fuzz / open source? If we could reproduce the issue ourselves, it would definitely help.

If it's not public but you can share it privately, feel free to send me an email and I'll try to take a look next week (I'm OOO tomorrow).

**Comment by bshastry** [comment]
> Does fork mode report 60K PCs from the beginning, i.e. after reading the corpus? Or only after fuzzing for a while?

Only after fuzzing for a while.

> My previous comment was assuming that your fuzz target may have a lot of "unstable" or 
 "non-determenistic" coverage edges, that's why over time it keeps discovering those edges and they appear unique, while actually they cannot be easily hit when reading the corpus.

Ah I see. Could you please point me to resources (code/docs) that help me understand libfuzzer considers "unstable" or "non-deterministic" coverage edges? I'm quite interested to dig deeper here because coverage improvements (3x) is substantial.

> I checked the code in libFuzzer that prints stats from the fork mode and didn't noticed anything obviously suspicious.

Okay, thank you for spending time on this :-)

> Is your fuzz target in OSS-Fuzz / open source? If we could reproduce the issue ourselves, it would definitely help.

I'll mail you the details shortly. Thank you.

**Comment by Dor1s** [comment]
> Could you please point me to resources (code/docs) that help me understand what libfuzzer considers "unstable" or "non-deterministic" coverage edges?

I'm not sure if there is any documentation on it. AFL has a "stability" metric that tries to reflect approximately this issue.

We were trying to add a mode in libFuzzer to handle and ignore unstable edges, but didn't like how it worked back then.

I've received your email and will try to take a look some time later.
