### ISSUE TITLE
unique names for reproducer files

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#332]
Right now the repro files look like
   fuzz-N-target_name (where N is a small number)
which makes lots of non-unique names. 

Maybe have something like 
   oss-fuzz-target-name-bugtype-SHA1? 
(more or less any other way with a SHA1 in the name is ok too)

**Comment by oliverchang** [comment]
We'll probably use the unique testcase ID instead of a SHA1 to make things easier.

**Comment by kcc** [comment]
this should work well too

**Comment by oliverchang** [comment]
Done. Files downloaded should now look like:

clusterfuzz-testcase-UNIQUE_ID
