### ISSUE TITLE
Improve presubmit script - fixing lint issues in infra/, make sure lint not complain on unknown modules [explicitly run lint on all infra/*]

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#3320]
The presubmit script is really handy, but we seem to keep ignoring some of its findings, as well as keep adding more suppressions, which is a wrong trend.

Current issues (please feel free to edit and add more):

1) We have both py2 and py3 scripts, while presubmit supports py3 only
2) We have various dependencies (presubmit deps, gcb builder deps, cifuzz deps, etc), so presubmit complains about unknown modules

**Comment by Dor1s** [comment]
Potential solutions:

1) Disable linting for py2 scripts until we migrated those to py3
2) Install dependencies from all requirements and hope there are no conflicts, that should allow presubmit to lint everything

**Comment by inferno-chromium** [comment]
I think this should go away after the builder rewrite and we make sure everything in infra/ is python 3 and no dependencies issues are shown by lint. Keeping in @kabeer27 queue to work on this after finishing builder write and verifying everything in infra/ is py3 and presubmit does not complain on missing dependencies. [@oliverchang as fyi].

**Comment by kabeer27** [comment]
@inferno-chromium 
Yes i have been fixing all linting/dependency related lint issues while i work on each file.

**Comment by inferno-chromium** [comment]
There are some issues left, but not @kabeer27 responsibility.
