### ISSUE TITLE
kcodecs build fails in the server but succeeds locally

### ISSUE THREAD

**Issue by tsdgeos** [google/oss-fuzz#3329]
I can do

```
python infra/helper.py build_image kcodecs
python infra/helper.py build_fuzzers --sanitizer memory kcodecs
```

fine locally and it succeeds, but it seems the server is having trouble compiling according to https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20469 and https://oss-fuzz-build-logs.storage.googleapis.com/log-98fc31df-cff2-4b02-8bbc-d205ebd11e2f.txt 

It complains about 
```
Step #4: qfilesystemengine_unix.o: In function `freeDesktopTrashLocation(QString const&)':
Step #4: /src/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:1229: undefined reference to `QStorageInfo::QStorageInfo(QString const&)'
```
but that seems like the compiler is actually failing since if you look for the compilation line of qfilesystemengine_unix.cpp it says 

`clang++ -c -o qfilesystemengine_unix.o  -stdlib=libc++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -std=c++11 -ffunction-sections -fdata-sections -g -g  -I/src/qtbase/qmake -I/src/qtbase/qmake/library -I/src/qtbase/qmake/generators -I/src/qtbase/src/3rdparty/tinycbor/src -I/src/qtbase/qmake/generators/unix -I/src/qtbase/qmake/generators/win32 -I/src/qtbase/qmake/generators/mac -I../include -I../include/QtCore -I../include/QtCore/5.15.0 -I../include/QtCore/5.15.0/QtCore -I../src/corelib/global -I/src/qtbase/mkspecs/linux-clang-libc++ -DQT_VERSION_STR=\"5.15.0\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=15 -DQT_VERSION_PATCH=0 -DQT_BUILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL -DQT_NO_FOREACH /src/qtbase/src/corelib/io/qfilesystemengine_unix.cpp`

And then looking at https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/io/qfilesystemengine_unix.cpp?h=5.15 the `freeDesktopTrashLocation` function should not be compiled if `QT_BOOTSTRAPPED` is defined and by looking at the compilation line it is defined, so it should not be compiled, but the linking error says it was compiled.

So i've no idea what can be wrong :/

Any hint?

**Comment by Dor1s** [comment]
You mentioned memory sanitizer, but the log you've linked says the following:

```
Step #4: ********************************************************************************
Step #4: Failed to build.
Step #4: To reproduce, run:
Step #4: python infra/helper.py build_image kcodecs
Step #4: python infra/helper.py build_fuzzers --sanitizer address --engine libfuzzer --architecture x86_64 kcodecs
Step #4: ********************************************************************************
```

did you try reproducing this with `address` sanitizer?

**Comment by tsdgeos** [comment]
Yes, also works

**Comment by Dor1s** [comment]
Hm, than it's a problem :/

Did you pull new images when running `build_image` command (it should ask with `[y/N]` answer)?

//cc current sheriff @mbarbella-chromium

**Comment by tsdgeos** [comment]
Thanks to whoever fixed it, because it seems to be working on the server now :)
