### ISSUE TITLE
present regression and fixed range information in a better way

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#334]
It's very interesting to know which bugs are recent regressions and which were found 
by tireless bots after months of fuzzing. 
Is it possible to file bugs as regressions and give regression ranges, when we can be certain 
that a bug *is* a regression? (E.g. check if the previous build passes)

**Comment by oliverchang** [comment]
We already provide regression ranges for each issue that we file. Would you like this to be more explicit in the bug report?

**Comment by kcc** [comment]
Right.. I am still not sure we are doing great job here. Some ideas for improvement: 

* When we are certain this is a regression, add a prefix in the title and/or a tag. 
* Time stamps are not clear (e.g. now we have `201611012136`, but it better be  `2016-11-01-21-36`)
* it would indeed be very nice to list all revisions in the regression range (unless the number is too large)

**Comment by oliverchang** [comment]
Yeah I definitely agree what we have now isn't very good. Once we have commit messages alongside builds we should be able to present it in a better way.

Ideally the timestamps will go away from most user facing places -- they're used by CF internally but aren't really useful otherwise.
