### ISSUE TITLE
CIFuzz: artifact arguments

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#3346]
@catenacyber uncovered a potential UX issue: if CIFuzz user renames the artifacts e.g. in https://github.com/google/gonids/pull/130/commits/efe764933c16aebdbed0f1ced85632dd9718aa59, the action is failing to upload them (see https://github.com/google/gonids/pull/130/checks?check_run_id=429805515)

- if the action doesn't support custom artifact parameters, let's just remove those from the config and always use the default
- if it's necessary to be able to customize it, the action shouldn't fail I suppose?

maybe I misunderstand something, //cc @jonathanmetzman

**Comment by catenacyber** [comment]
And I did not even know what UX stood for

**Comment by jonathanmetzman** [comment]
I think we don't support it, @Leo-Neat WDYT? Removing it seems like the correct decision to me.
