### ISSUE TITLE
[FFmpeg] [Coverage] Very low coverage reported since jan 17th

### ISSUE THREAD

**Issue by michaelni** [google/oss-fuzz#3351]
Around 17th january 2020 the listed fuzzer coverage for FFmpeg droped substantially.
https://storage.googleapis.com/oss-fuzz-coverage/ffmpeg/reports/20200116/linux/src/ffmpeg/report.html
vs.
https://storage.googleapis.com/oss-fuzz-coverage/ffmpeg/reports/20200117/linux/src/ffmpeg/report.html
This low coverage persists till today. My attempt to reproduce this locally failed to reproduce this, with
python infra/helper.py coverage --fuzz-target=ffmpeg_DEMUXER_fuzzer ffmpeg
i got 
libavformat/ | 14.05% (12432/88493) | 24.63% (609/2473) | 14.78% (10466/70810)
even though its 0% on the web.
Also there were issues found by the fuzzer with the ffmpeg_DEMUXER_fuzzer during the time its code was claimed to be 0% covered.

Thanks!

**Comment by Dor1s** [comment]
Thanks for noticing this. I've just checked the logs from the coverage job and observed the following:

```
$ ls | wc -l
489  # this means there are 489 fuzz targets 
mmoroz@mmoroz3:~/Downloads/ffmpeg_logs/20200206$ cat * | egrep 'new files with' -c
100  # 100 of them seemed to successfully run
mmoroz@mmoroz3:~/Downloads/ffmpeg_logs/20200206$ cat * | egrep 'No such file or directory' -c
389  # the rest are failed due to the lack of corpora
```

That means, we don't have corpus backups for the affected targets. Let me check the corpus backup bucket.

**Comment by Dor1s** [comment]
The corpus backup bucket looks good. In that case there might be an issue with corpus downloading step.

**Comment by Dor1s** [comment]
The fix worked, here's a new report: https://storage.googleapis.com/oss-fuzz-coverage/ffmpeg/reports/20200206/report/linux/report.html

Sorry for the breakage and thanks again for reporting the issue, @michaelni :)
