### ISSUE TITLE
Updating seed corpora

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#3370]
Hello,

For solidity, we clone seed files for various fuzzers from a standalone github repo. This is done inside the oss-fuzz project specific docker file.

https://github.com/google/oss-fuzz/blob/6c2e01fb605e74c14b06043b7c9c818504416e67/projects/solidity/Dockerfile#L26

Are we doing this right? What if docker image is cached and updates to the seed corpus repo are not picked up?

Should we do a `git pull` inside the seed repo dir inside the oss-fuzz `build.sh` script? This will marginally increase build time but that should be fine, shouldn't it?

**Comment by oliverchang** [comment]
We build our docker files from scratch on our infra, without relying on any pre-existing caching so this shouldn't be an issue.
