### ISSUE TITLE
Python traceback on oss-fuzz.com

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#3372]
https://oss-fuzz.com/testcase-detail/5634736898965504

I suppose that I should not see this verbose error, and that the error itself would be fixed :
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xca in position 11818: ordinal not in range(128)`

**Comment by oliverchang** [comment]
@mbarbella-chromium could you please help take a look?

**Comment by mbarbella-chromium** [comment]
Should be fixed now. Thanks for the report!
