### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by randy408** [google/oss-fuzz#3373]
There was an issue with integrating stb_image, a non-gmail address was used intially and it was  replaced afterwards with a @gmail.com one for obvious reasons (https://github.com/google/oss-fuzz/pull/3362). When the PR was merged all addresses received another set of notifications of all bugs for that project, including the old address which was replaced, the old address still appears in the CC field for existing bugs: https://github.com/nothings/stb/pull/737#issuecomment-584727668.

Will the old address stop receiving email, or is the CC field only updated for new bugs?

**Comment by oliverchang** [comment]
Hi,

Emails removed from project.yaml are not removed from existing bugs. However, newly bugs won't include them.
