### ISSUE TITLE
Document Rust fuzzing

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#3383]
Similarly to https://google.github.io/oss-fuzz/getting-started/new-project-guide/go-lang/

**Comment by Dor1s** [comment]
Assigning to @jonathanmetzman who's probably the most familiar with it

**Comment by alexcrichton** [comment]
Sure! I'd be happy to help out. I'll try to make time to send a PR in the near future to this repo.

**Comment by inferno-chromium** [comment]
DONE, thanks to @alexcrichton !
