### ISSUE TITLE
Profiling fuzzers

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#339]
During lunch we brought up the idea of surfacing profiling information about fuzzers in addition to coverage.  This might be an interesting data point to see if a fuzzer is spending time in the right places.

@kcc @mikea What do you think of this idea? Would it be easy to set up profiling?

**Comment by inferno-chromium** [comment]
There are 3 places for this data::

1. When someone runs a fuzzer locally, they see a coverage report, they should be also able to see the profiling data to see where the fuzzer spends most time or is getting stuck. Also, good to have in combination with #340.
2. Showing this data on fuzzer statistics page on clusterfuzz and periodically archived.
3. Using this data as part of performance analyzer (that Max has) to give even more specific code points. like which part is fuzzer spending most time in, etc.

**Comment by kcc** [comment]
see also https://github.com/google/oss-fuzz/issues/336

**Comment by inferno-chromium** [comment]
Kostya suggested to use the linux perf tool.

**Comment by zhangysh1995** [comment]
I‘ve tried [`gprof`](https://sourceware.org/binutils/docs/gprof/Introduction.html#Introduction), but it seems it cannot track fuzzers with multithreading (e.g. fork). To be concise, it uses sampling to collect profiling data and the results must be interpreted with CPU frequency.
