### ISSUE TITLE
ossfuzz docker image

### ISSUE THREAD

**Issue by bshastry** [google/oss-fuzz#3400]
Hi,

We would like to replicate oss-fuzz builds in our CI so that build failures (currently flagged by ossfuzz builder bot) are picked up earlier.

Is the oss-fuzz clang docker image public? Can we reference it in our dockerfile?

Thanks!

**Comment by jonathanmetzman** [comment]
It is public, I think you should be able to use it.
For now, [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) can alert you to ASAN build failures. It doesn't support other sanitizers, but if we add other sanitizers it may be a cheap way to get what you are trying to do.
