### ISSUE TITLE
CIFuzz doesn't seem to run `check_build`

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#3401]
I think it would be great if CIFuzz ran `check_build` after building fuzz targets (ideally with ALLOWED_BROKEN_TARGETS_PERCENTAGE set to 0 (though it would probably be better if it was configurable)). This mostly should help to catch issues with the thresholds like ASAN_CALLS_THRESHOLD_FOR_ASAN_BUILD (that otherwise are likely to go unnoticed) and prevent "bad" fuzzers from getting merged.

**Comment by jonathanmetzman** [comment]
This should be pretty easy to do and would be nice. Maybe we should make it another action that can be run after build_fuzzers. I think we have some higher priority features though but we should get to this not too long from now.

**Comment by Leo-Neat** [comment]
Submitted a fix #3419
