### ISSUE TITLE
Coverage reports not appearing since a few days

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#3402]
Try

https://storage.googleapis.com/oss-fuzz-coverage/cryptofuzz/reports/20200217/linux/index.html
https://storage.googleapis.com/oss-fuzz-coverage/cryptofuzz/reports/20200216/linux/index.html
https://storage.googleapis.com/oss-fuzz-coverage/cryptofuzz/reports/20200215/linux/index.html

or

https://storage.googleapis.com/oss-fuzz-coverage/openssl/reports/20200217/linux/index.html
https://storage.googleapis.com/oss-fuzz-coverage/openssl/reports/20200216/linux/index.html
https://storage.googleapis.com/oss-fuzz-coverage/openssl/reports/20200215/linux/index.html

But these work:

https://storage.googleapis.com/oss-fuzz-coverage/cryptofuzz/reports/20200214/linux/index.html
https://storage.googleapis.com/oss-fuzz-coverage/openssl/reports/20200214/linux/index.html

**Comment by Dor1s** [comment]
Thanks @guidovranken, this regressed after https://github.com/google/oss-fuzz/pull/3396 and should be fixed now by https://github.com/google/oss-fuzz/pull/3404.

You can still see the reports (with a poor CSS) for those days if you remove "linux" subdir in the URL.

Sorry for the inconvenience and thanks again for noticing the issue!

**Comment by Dor1s** [comment]
> You can still see the reports (with a poor CSS) for those days if you remove "linux" subdir in the URL.


Actually, CSS should be fine for cryptofuzz and openssl projects. I can fix it for more projects, if needed :)
