### ISSUE TITLE
[CIFuzz]: CIFuzz can't be used to make sure bugs are really fixed

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#3413]
Now that https://github.com/google/oss-fuzz/pull/3385 is merged, CIFuzz ignores all the crashes reproducible with the latest fuzz targets downloaded from OSS-Fuzz (which should help to make CIFuzz less noisy). The only downside is that it's currently impossible to automatically make sure that PRs that are supposed to fix issues discovered by OSS-Fuzz really fix them.

We started to discuss this in https://github.com/google/oss-fuzz/pull/3385#discussion_r379387845. I'll just leave it here so that it won't get lost.

**Comment by Dor1s** [comment]
I have a pretty strong opinion on this, which is just an opinion, not necessarily our plan :) 

CIFuzz has a clear purpose: test pull requests and catch regressions that can be found in seconds / minutes of fuzzing. If we excel at this, CIFuzz should bring good value to its users. If we go after multiple purposes, we may not excel at any of them. I would rather stick to a single goal and focus on the main use case.

Now, if there is demand for some sort of "OSS-Fuzz assistant" thing, let's consider it a separate CI bot, which could have its own clear purpose and deliver the best experience on it. I think we can have a CI check that would be triggered by a comment like `/oss-fuzz 1337` and would talk to OSS-Fuzz infra to gather all the data needed to reproduce the issue number 1337. That data would include build config, sanitizer flags, input. In such a setup, the bot will become a real oracle for testing known issues. Of course, we'll need to figure out the permissions for it, and the users would have to get some key from us and put it in their repo settings, but I feel like it's worth it if one-time configuration that can be used for verifying fixes and stuff?

**Comment by evverx** [comment]
>  If we excel at this, CIFuzz should bring good value to its users. If we go after multiple purposes, we may not excel at any of them. I would rather stick to a single goal and focus on the main use case.

Can't argue with that but for CIFuzz to excel at this it would have to switch from GitHub Actions (where machines with 2 CPUs are currently being used to run fuzz targets one by one) to something else to make it possible for projects with more than 30 fuzz targets to run fuzz targets in parallel. But I digress :-)

> if there is demand for some sort of "OSS-Fuzz assistant" thing, let's consider it a separate CI bot, which could have its own clear purpose and deliver the best experience on it. I think we can have a CI check that would be triggered by a comment like /oss-fuzz 1337 and would talk to OSS-Fuzz infra to gather all the data needed to reproduce the issue number 1337.

I think it would be great to have a bot like this but it seems for the most part it's supposed to cover "security" issues (where it isn't desirable to make files triggering bugs public). I wouldn't say it isn't important but in my experience most bugs have nothing to do with security (often because the code hasn't even been released yet) so it's relatively safe to include testcases in PRs. As an example, in https://github.com/systemd/systemd/pull/14805, `test/fuzz/fuzz-network-parser/oss-fuzz-20548` was added (and kept there afterwards) to run the fuzzer against it to make sure the code no longer crashed.

I think it would be great if I could just somehow let CIFuzz know that some crashes shouldn't be ignored. Before #3385 was merged, in theory I was able to put all those files in the seed corpora and wait for CIFuzz to report any issues back.

**Comment by evverx** [comment]
Speaking of systemd/systemd#14805, in that particular case, a bot downloading testcases from OSS-Fuzz wouldn't have helped much because the code changed and the testcase had to be changed as well: https://github.com/systemd/systemd/pull/14805#issuecomment-583279290

**Comment by jonathanmetzman** [comment]
> > If we excel at this, CIFuzz should bring good value to its users. If we go after multiple purposes, we may not excel at any of them. I would rather stick to a single goal and focus on the main use case.
> 
> Can't argue with that but for CIFuzz to excel at this it would have to switch from GitHub Actions (where machines with 2 CPUs are currently being used to run fuzz targets one by one) to something else to make it possible for projects with more than 30 fuzz targets to run fuzz targets in parallel. But I digress :-)

We're hoping the we can use code coverage info to infer the correct fuzzer to run most of the time, so that running all 30 fuzzers isn't needed.

Thanks for sharing these points. That should help us decide which we should go if/when we make some kind of CI assistant.

**Comment by evverx** [comment]
> We're hoping the we can use code coverage info to infer the correct fuzzer to run most of the time, so that running all 30 fuzzers isn't needed.

I think it's a good idea. Though, I can imagine a few edge cases that seem to be relatively hard to get right (for example, when fuzz targets are added or renamed). Assuming it's going to be based on the data used to build coverage reports like https://storage.googleapis.com/oss-fuzz-coverage/systemd/reports/20200223/linux/report.html, I'm wondering if you're planning to keep  it in a machine-readable format that can be used outside of CIFuzz.

**Comment by jonathanmetzman** [comment]
>Though, I can imagine a few edge cases that seem to be relatively hard to get right (for example, when fuzz targets are added or renamed)

Oh, yeah, I fully expect there to be edge cases that we can't catch. But I imagine new fuzz target is probably we can catch using the coverage data, thanks for pointing this out! I expect modifying code that isn't executed is the source of other edge cases (macro changes, constant changes, config file changes etc).

> I'm wondering if you're planning to keep it in a machine-readable format that can be used outside of CIFuzz.

We already do.
You can get the coverage data on a per-target basis using URLs like this: https://storage.googleapis.com/oss-fuzz-coverage/systemd/fuzzer_stats/20200223/fuzz-udev-database.json (if you use gsutil you can search the directories, download everything at once, etc).

**Comment by jonathanmetzman** [comment]
@evverx I think our bad build checking might accidentally provide this feature. If you could test/verify it that would be great.
bad_build_check runs before fuzzing and will check that the fuzzer doesn't crash on the seed corpus. So I think if you add something to the seed corpus and it causes a crash, fuzzing won't happen and CIFuzz will fail during bad build check.

We're all a bit short on cycles because of performance review season, but I can also check this in a week or two if you want.

**Comment by evverx** [comment]
Last time I checked (a few months ago) it didn't work. Judging by https://github.com/google/oss-fuzz/blob/db8467bf302b0398feaf8317cbba0a2801775da5/infra/base-images/base-runner/bad_build_check#L413, this feature was commented out in a51ea6df922c648379
