### ISSUE TITLE
CIFuzz doesn't build fuzzers with UBsan/MSan

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#3421]
This was discussed about a week ago. I'll just leave a couple of comments from that thread here so as not to forget what it was about:

> UBSAN and MSAN would probably come later (on an opt-in basis) but we're focused on ASAN for now since those bugs are generally the most serious.

> I agree bugs found by MSan (and especially by UBsan) are usually considered minor but because of that nobody is fond of fixing them once they are merged, so in terms of preventing those minor issues from piling up I think CI is exactly the right place to whack them :-)

**Comment by jonathanmetzman** [comment]
I still need to test it, but this should be fixed with: https://github.com/google/oss-fuzz/pull/3516
