### ISSUE TITLE
[CIFuzz] Affected fuzzer with blaze build

### ISSUE THREAD

**Issue by Leo-Neat** [google/oss-fuzz#3433]
Issues arise when a project uses a different build system meaning files are placed in unexpected directories. This makes file diffs not match up with git diffs.

**Comment by jonathanmetzman** [comment]
CC @Dor1s our expert on handling weird build system interaction with coverage.
I think you must handle this in coverage reports, do you have ideas how we can do so in CIFuzz?

**Comment by Dor1s** [comment]
I don't think we had to solve exact same problem for coverage reports, but my best idea is to use the relative path of the modified files (i.e. `$SRC/project/relative/path/to/file.cpp`) and look for the files with paths ending with `relative/path/to/file.cpp` in the coverage data.

If source files are being moved even more weirdly during the compilation, I think our options are either to give up or to try some heuristic such as using only basename of the file. That might produce false positives (matching redundant files with the same basename), but shouldn't give false negatives (ignoring the corresponding files), assuming the basename doesn't ever change during the compilation.
