### ISSUE TITLE
Make sure that projects use all sanitizers by default and not need to override sanitizers:

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#344]
Following projects do the override, some of these might be accidently doing this.

projects/nss/project.yaml:sanitizers:
projects/boringssl/project.yaml:sanitizers:
projects/libyaml/project.yaml:sanitizers:
projects/sqlite3/project.yaml:sanitizers:
projects/llvm_libcxxabi/project.yaml:sanitizers:
projects/arduinojson/project.yaml:sanitizers:
projects/json/project.yaml:sanitizers:
projects/libjpeg-turbo/project.yaml:sanitizers:
projects/tpm2/project.yaml:sanitizers:
projects/tor/project.yaml:sanitizers:
projects/gnutls/project.yaml:sanitizers:
projects/openssl/project.yaml:sanitizers:
projects/expat/project.yaml:sanitizers:

**Comment by oliverchang** [comment]
Isn't the point of sanitizers: to override the default? e.g. if UBSan is particularly noisy that can be opted out. Do you mean cleaning up the existing project.yaml files?

**Comment by inferno-chromium** [comment]
Yes if it is explicitly done, then ok, but many of these might be doing by mistake and not benefiting from other sanitizers like ubsan.

**Comment by inferno-chromium** [comment]
@kcc, @mikea - just fyi, since ubsan is enabled by default, i removed from other places.

These are left and they are expected
projects/json/project.yaml:sanitizers:
projects/freetype2/project.yaml:sanitizers:
