### ISSUE TITLE
Travis: add a workaround for "The job exceeded the maximum log length, and has been terminated." error

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#3441]
Inspired by the conversation in https://github.com/google/oss-fuzz/pull/3408#pullrequestreview-365111085

It's possible to redirect output to a file and then print it (or just trailing lines of it) in case of a failure.

**Comment by jonathanmetzman** [comment]
I guess the only downside is you can't see realtime output, but I'm not sure anyone uses that. 
Maybe somewhere online there is a fancy solution for this?

**Comment by jonathanmetzman** [comment]
Btw, by better tooling I meant for travis buddy to explicitly tell me the cause. If it does already then I probably ignore it so it would have to look sufficiently different from normal failures for me to pay attention (sorry, but I have total logging fatigue from travis buddy).

**Comment by Dor1s** [comment]
When I searched for it, the best I found was a snippet on StackOverflow written in ~~your favorite language~~ bash :)

**Comment by inferno-chromium** [comment]
Not an issue anymore, switched to Github actions!
