### ISSUE TITLE
[ghostscript] Mysterious corpus related build error.

### ISSUE THREAD

**Issue by sebras** [google/oss-fuzz#3449]
I can see from [Ghostscript's build script for OSS-fuzz](https://github.com/google/oss-fuzz/blob/master/projects/ghostscript/build.sh#L66) that it tries to save the seed files into `$OUT/<project_name>_seed_corpus.zip` to allow for OSS-fuzz to mutate problematic files quicker.

In OSS-fuzz [issue 15591](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=15591) we have seen repeated build errors since July 2019. Looking at [the latest build log](https://oss-fuzz-build-logs.storage.googleapis.com/log-a26969e4-db55-4477-b596-dcf58dc838cf.txt) from [comment 49](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=15591#c49) I notice that a `/workspace/out/coverage/gstoraster_fuzzer_seed_corpus.zip` is created as expected.

`Step #3: + zip -j /workspace/out/coverage/gstoraster_fuzzer_seed_corpus.zip /work/seeds/053091fdd025de72a89f20064d638f8fab09bb07 /work/seeds/217aff142c96c7263afd7abab524c022c147bc2e /work/seeds/5eb368ec30c2952742fa67eaf26e36b0b75a7598 /work/seeds/7b7cbbc5d1434291e674a4a0bc8e0561fabb84bb /work/seeds/7c641c82276706758c2626ae26968506734b485d /work/seeds/82077a84f2402bee536c099ac7e519f6c918b278 /work/seeds/9ccd6a68c19456ee32c468ab213731414ab7e16b /work/seeds/d820feb326c38e2457cfb0e19a04f3f45bd98029 /work/seeds/d9953510f140b7da80c26a2000b0e9a0904201d4 /work/seeds/e0d883600058eaa99c5d76c91a56f2bd497990a8 /work/seeds/f3051516e7b7340fc27f2c9dd09f0e339b5fbd49 /work/seeds/f46d30cbdd073a4fb6ce9e778d1e6f1c2af9b9ff
Step #3:   adding: 053091fdd025de72a89f20064d638f8fab09bb07 (deflated 56%)
Step #3:   adding: 217aff142c96c7263afd7abab524c022c147bc2e (deflated 74%)
Step #3:   adding: 5eb368ec30c2952742fa67eaf26e36b0b75a7598 (deflated 9%)
Step #3:   adding: 7b7cbbc5d1434291e674a4a0bc8e0561fabb84bb (deflated 63%)
Step #3:   adding: 7c641c82276706758c2626ae26968506734b485d (deflated 75%)
Step #3:   adding: 82077a84f2402bee536c099ac7e519f6c918b278 (deflated 57%)
Step #3:   adding: 9ccd6a68c19456ee32c468ab213731414ab7e16b (deflated 6%)
Step #3:   adding: d820feb326c38e2457cfb0e19a04f3f45bd98029 (deflated 62%)
Step #3:   adding: d9953510f140b7da80c26a2000b0e9a0904201d4 (deflated 76%)
Step #3:   adding: e0d883600058eaa99c5d76c91a56f2bd497990a8 (deflated 3%)
Step #3:   adding: f3051516e7b7340fc27f2c9dd09f0e339b5fbd49 (deflated 52%)
Step #3:   adding: f46d30cbdd073a4fb6ce9e778d1e6f1c2af9b9ff (deflated 59%)
Finished Step #3`

But this is then followed by a step 5 that mysteriously fails:

`Starting Step #5
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: [/corpus/gstoraster_fuzzer.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/gstoraster_fuzzer.zip or
Step #5:         /corpus/gstoraster_fuzzer.zip.zip, and cannot find /corpus/gstoraster_fuzzer.zip.ZIP, period.
Step #5: Failed to unpack the corpus for gstoraster_fuzzer. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
Step #5: ********************************************************************************
Step #5: Code coverage report generation failed.
Step #5: To reproduce, run:
Step #5: python infra/helper.py build_image ghostscript
Step #5: python infra/helper.py build_fuzzers --sanitizer coverage ghostscript
Step #5: python infra/helper.py coverage ghostscript
Step #5: ********************************************************************************
Finished Step #5
ERROR
ERROR: build step 5 "gcr.io/oss-fuzz-base/base-runner" failed: step exited with non-zero status: 1`

We need help with resolving this because I can't see where there's a mistake in Ghostscript's build script.

**Comment by Dor1s** [comment]
This is the explanation: "Step #5: Failed to unpack the corpus for gstoraster_fuzzer. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully."

If I go to the corpus backup bucket for ghostscript, it's empty:

```
$ gsutil ls gs://ghostscript-backup.clusterfuzz-external.appspot.com
$
```

The performance report also shows that the fuzz target doesn't perform well and often times out (among other issues): https://oss-fuzz.com/performance-report/libFuzzer_ghostscript_gstoraster_fuzzer/libfuzzer_asan_ghostscript/latest

If you could fix those timeouts or speed up the fuzz target otherwise, the corpus pruning task should be able to succeed. That will successfully produce a corpus backup and fix the broken code coverage job.

Does it make any sense?

**Comment by sebras** [comment]
@Dor1s 
> Does it make any sense?

A little bit, but I need more assistance.

> If a fuzz target was added in the last 24 hours, please wait one more day.

A fuzz target has not been added recently. It still fails per comment #53 in issue 15591.
Moreover I looked [here](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#ghostscript) and it seems to build fine and additionally states towards the end:

```
Step #25:   adding: gstoraster_fuzzer_seed_corpus.zip (stored 0%)
```

> The performance report also shows that the fuzz target doesn't perform well and often times out 
> (among other issues): https://oss-fuzz.com/performance-report/libFuzzer_ghostscript_gstoraster_fuzzer/libfuzzer_asan_ghostscript/latest

How do I go about getting the testcases files that cause those timeouts (and other issues)? Why are these not reported as normal issue for oss-fuzz like 15591?

**Comment by sebras** [comment]
> `gsutil ls gs://ghostscript-backup.clusterfuzz-external.appspot.com`
> `$`

Having installed some tools I can confirm that this is still true.

**Comment by Dor1s** [comment]
> Having installed some tools I can confirm that this is still true.

I doubt it would get resolved by itself. If I were to debug it, I'd do the following:

1) get the most recent build using `--sanitizer address --engine libfuzzer`
2) download the most recent corpus 
```
mkdir corpus
gsutil -m -q cp -r gs://ghostscript-corpus.clusterfuzz-external.appspot.com/libFuzzer/ corpus
```

3) run corpus minimization (aka "corpus pruning") locally:

```
mkdir minimized_corpus
./fuzzer -merge=1 use_value_profile=1 minimized_corpus corpus
```

4) observe how long would it take and would there be any errors

5) if minimization runs relatively smoothly and finishes in a few hours, this likely an issue in OSS-Fuzz infra

I anticipate that you'd see many crashes from the fuzz target and the minimization would not finish in a reasonable amount of time. The crashes you'd see would be the reproducers helpful for fixing performance issues.

**Comment by Dor1s** [comment]
btw, corpus for that target is huge

```
$ gsutil du -hs gs://ghostscript-corpus.clusterfuzz-external.appspot.com/libFuzzer/
15.82 GiB    gs://ghostscript-corpus.clusterfuzz-external.appspot.com/libFuzzer
```

so don't even attempt to minimize it locally. We should just manually delete all files above some threshold, and ideally fuzz target should also enforce some input size limit (i.e. `if (size > 16 * 1024) return 0;` or any other limit you find reasonable).

**Comment by Dor1s** [comment]
@sebras please define a good limit, update the fuzz target and let us know so that we could shrink the existing corpora

**Comment by sebras** [comment]
> please define a good limit, update the fuzz target and let us know so that we could shrink the existing corpora

Ghostscript accepts PDF-files that can virtually be of any size, so defining a size is hard. But if Ghostscript has issues with files smaller than 1Kbyte, we should probably look at those issues before we try to fix the ones where the file is 100Kbyte and more complicated.

**Comment by sebras** [comment]
> mkdir minimized_corpus
> ./fuzzer -merge=1 use_value_profile=1 minimized_corpus corpus

I would like to run this command, but I don't know where I'd get `./fuzzer` from?

**Comment by Dor1s** [comment]
Let me try removing all files >100KB and seeing how much is left.

> I would like to run this command, but I don't know where I'd get ./fuzzer from?

Sorry for confusion, that's fuzz target binary, `gstoraster_fuzzer` in your case

> @Dor1s Oh, and I'm still puzzled as to why none of these issues pop up as issues in the bugtracker?

yeah, sorry about that :( We've been dreaming about some sort of notification for such issues for a while, but never prioritized implementing it. I've filed a bug for this particular case, maybe we can address it eventually: https://github.com/google/clusterfuzz/issues/1614

**Comment by Dor1s** [comment]
I've removed all files >100KB and there's still plenty of files left

```
# initial corpus was 15GB
$ ls | wc -l
673596

$ python shrink.py 
$ du -hs .
5.1G	.
$ ls ghostscript_gstoraster_fuzzer/ | wc -l
630870
```

99% of large files were generated by radamsa, filed https://github.com/google/clusterfuzz/issues/1616 to discuss / fix on CF side

**Comment by Dor1s** [comment]
@inferno-chromium pointed out that there was a fix deployed recently that should let fuzz targets with this issue automatically recover. @sebras I think we should wait another day or so and check the stats after that. If the issue is still present, I can fix it manually for ghostscript, but ideally we need the CF change to fix and prevent it for all fuzz targets.

**Comment by sebras** [comment]
@Dor1s I ran the minimization locally and it finally finished after almost two days on my machine.

```
[...]
INFO: Rendering completed
#2      pulse  cov: 9425 ft: 20111 exec/s: 2 rss: 236Mb
#2      DONE   cov: 9425 ft: 20111 exec/s: 2 rss: 237Mb
MERGE-OUTER: succesfull in 442 attempt(s)
MERGE-OUTER: the control file has 96865858 bytes
MERGE-OUTER: consumed 39Mb (227Mb rss) to parse the control file
MERGE-OUTER: 8716 new files with 109543 new features added; 17509 new coverage edges
$
```

The number of files are fewer in the minimized set:
```
$ find corpus -type f | wc -l; du -ms corpus
16468
378     corpus
$ find corpus.mini -type f | wc -l; du -ms corpus.mini
8655
184     corpus.mini
```

The top-level directory littered with ~400 files on the form `timeout-41335c9f34bb1a35bd815dfa36783663f15cbab2` that I think OSS-fuzz times out on when passing through the fuzzing target. I plan to take a look at a few of these and see what happens. Is that a good approach? How are these timeouts connected to the coverage build failing?

**Comment by Dor1s** [comment]
Btw, coverage is fixed now: https://storage.googleapis.com/oss-fuzz-coverage/ghostscript/reports/20200327/linux/report.html -- thanks @inferno-chromium for all the fixes on ClusterFuzz side.

> I plan to take a look at a few of these and see what happens. Is that a good approach?

Yes, definitely!

> How are these timeouts connected to the coverage build failing?

Coverage build (i.e. complication step) is going fine. The coverage job is failing, which includes the compilation and coverage report generation.

The latter is failing, because there are no corpus backups over the past 90 days. Coverage report generation doesn't work without corpus, as corpus is what essentially triggers different parts of the codebase.

Corpus backups are created by corpus pruning task, which has limit of ~22 hours. Because of those timeouts, it takes longer to minimize the full corpus, and corpus pruning task on ClusterFuzz is failing, without creating a backup.

Please note that corpus pruning issue seems to be fixed now, but please look into the timeouts anyway, as those are harmful for fuzzing and in many cases are valid software bugs.

**Comment by sebras** [comment]
> Please note that corpus pruning issue seems to be fixed now, but please look into the timeouts anyway, as those are harmful for fuzzing and in many cases are valid software bugs.

I found that the Ghostscript fuzzing target printed the PWG raster output to stdout, and that took a loooong time on my machine locally. I discovered that the same code will be tested even if I set the output file to `/dev/null`. Running that locally meant that minimization finished *significantly* quicker. Thus I sent pull request #3547 that was merged yesterday. Travis complained about that pull request but that doesn't seem to be an error on my part.

We have also submitted a [fix](http://git.ghostscript.com/?p=ghostpdl.git;a=commitdiff;h=1258814b0532f06217cbfaffc5254c9645f69b42) to the Ghostscript code base fixing removal of temporary source code files that @IslandCow mentioned in out of band conversation.

I'll let this run and see what it looks like next week. Hopefully order will be restored.

**Comment by sebras** [comment]
Alright, [issue 15951](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=15591) has finally been closed! :)

@Dor1s:
>[The performance report](https://oss-fuzz.com/performance-report/libFuzzer_ghostscript_gstoraster_fuzzer/libfuzzer_asan_ghostscript/latest) also shows that the fuzz target doesn't perform well and often times out (among other issues).

Two more questions:

1. Where do I find the testcase files that causes the fuzz target to perform badly in these cases?
2. Where am I supposed to ask questions like these? Surely Github issue can't be the preferred communication tool? Is there a community that I've missed?

**Comment by Dor1s** [comment]
> Where do I find the testcase files that causes the fuzz target to perform badly in these cases?

You can download corpus from the fuzzer stats page: https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2020-04-02&date_end=2020-04-08&fuzzer=libFuzzer_ghostscript_gstoraster_fuzzer&job=libfuzzer_asan_ghostscript&project=ghostscript

See the rightmost corpus_backup column. And then run fuzing locally starting from that corpus.

> Where am I supposed to ask questions like these? Surely Github issue can't be the preferred communication tool? Is there a community that I've missed?


Nope, GitHub is preferred in our case :)
