### ISSUE TITLE
enable ubsan on the rest of the projects

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#345]
* e.g. on ffmpeg ubsan was disabled in https://github.com/google/oss-fuzz/commit/eccbe4a50a6e0bad89a5a2e26e8fc67c303f9805
* on freetype the owners asked to wait for a bit, there are lots of known ubsan-ish bugs.

**Comment by inferno-chromium** [comment]
disabled on ffmpeg and harfbuzz due to rtti issue.
disabled on icu due to ubsan integer overflow crash in build process.

**Comment by inferno-chromium** [comment]
@caolanm - just fyi, libreoffice currently does not build with UBSan, disabled in https://github.com/google/oss-fuzz/commit/2afbb75670177d8f9f094d29f0ebfcd031306fd3. Once it does, please feel free to remove this. this is a new config we enabled last week.

**Comment by kcc** [comment]
can we enable ubsan on ffmpeg w/o vptr?

**Comment by inferno-chromium** [comment]
done in #404

**Comment by inferno-chromium** [comment]
enabled on harfbuzz as well, but without vptr, function.
https://github.com/google/oss-fuzz/commit/b4fb5be5897702860bfe502cfa94d1c2557b19b8
