### ISSUE TITLE
Add automation to land PR after travis passes

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#3478]
An annoying thing that happens to OSS-Fuzz maintainers is needing to revisit PRs to merge after travis is green. It would be very nice to have a bot that we could instruct to merge a PR if travis passes.

**Comment by jonathanmetzman** [comment]
Oh for security reasons, the bot should refuse to merge if there is another push to avoid the possiblity of us OKaying a PR and then someone changing the PR to touch another project. This would definitely be caught (very likely before the next build before it has any effect) but we definitely want to avoid this.

**Comment by jonathanmetzman** [comment]
This might be a good start https://github.com/pascalgn/automerge-action

**Comment by Dor1s** [comment]
> the bot should refuse to merge if there is another push

There is a setting in the protected branches settings for this:

> **Dismiss stale pull request approvals when new commits are pushed**
> New reviewable commits pushed to a matching branch will dismiss pull request review approvals.
>

**Comment by jonathanmetzman** [comment]
I like that setting because I'd rather the security here doesn't rely on the bot's implementation and depends on GH instead.

**Comment by jonathanmetzman** [comment]
This is another option https://github.com/apps/mergewhenready

**Comment by oliverchang** [comment]
We should also add some backup sanity checks to e.g. make sure nothing outside of projects/ is being modified.

**Comment by jonathanmetzman** [comment]
We now use github's automatic merge feature.
