### ISSUE TITLE
CRITICAL: Broken and unmaintained projects > 3 months

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#3479]
Developers, please confirm if you still plan to continue maintaining these projects. Your project build is broken for more than 3 months. Continuous fuzzing is critical to security and stability of your open source software, we would really appreciate if you take the time and effort to fix these builds (also eligible for our reward program [here](https://google.github.io/oss-fuzz/getting-started/integration-rewards/))

radare2: @zlowram 
Minizinc: @Dekker1 
gstreamer: @bilboed
tensorflow: @mihaimaruseac 
spidermonkey: @sylvestre @tysmith 
chakra: @EdMaurer [with move to Edgium, might be time to remove ?]
xmlsec: @bshastry 
firestore: @var-const

**Comment by mihaimaruseac** [comment]
I will be working toward getting TF back in shape in Q2

**Comment by var-const** [comment]
Sorry about this. Firestore fix will be merged tomorrow.

**Comment by bilboed** [comment]
Yes, it's on my todo list and have a WIP branch. Need to switch the scripts to the new `meson` build system.

**Comment by bshastry** [comment]
Sorry, will take a closer look this week end

**Comment by inferno-chromium** [comment]
Thanks for your responses.

Other projects like chakra, minizinc are now removed. We can bring them back if we get responses.

**Comment by Dekker1** [comment]
Hi @inferno-chromium,
Thank you for keeping us in the loop. We do still intend to maintain the MiniZinc fuzzer. However, with our small group of developers with limited knowledge of fuzzing, we haven't found the time to update the fuzzing target. Hopefully we'll be able to resubmit a fixed version soon.

**Comment by inferno-chromium** [comment]
Thanks @Dekker1 , that sounds good!

**Comment by inferno-chromium** [comment]
@danmar : can you please check cppcheck, broken for >2.5 months
@tysmith : can you please check qcms, broken for ~3 months

**Comment by danmar** [comment]
@inferno-chromium I will check it asap. Thanks.

**Comment by tysmith** [comment]
@choller would be the person to ask about spidermonkey if it still needs attention.
