### ISSUE TITLE
woff2 fuzzers suffer from logging issues

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#348]
See performance column on
https://clusterfuzz-external.appspot.com/v2/fuzzer-stats/by-fuzzer/2017-01-29/2017-02-04/fuzzer/libFuzzer_woff2_convert_woff2ttf_fuzzer_new_entry/job/libfuzzer_asan_woff2?path=gs%3A%2F%2Fexpat-logs.clusterfuzz-external.appspot.com%2FlibFuzzer_expat_parse_fuzzer%2Flibfuzzer_asan_expat%2Fperformance_analysis.html

@rsheeter - can you disable FONT_COMPRESSION_BIN so that it disables the printf logging.

Implausible compression ratio 117.8
Implausible compression ratio 117.8
Implausible compression ratio 15427.8
offset fail; src_offset 54263904 length 96 dst_offset 76
Implausible compression ratio 203.8
Implausible compression ratio 203.8
Implausible compression ratio 203.8
Implausible compression ratio 1022070.4
offset fail; src_offset 131124 length 116 dst_offset 44
offset fail; src_offset 151126068 length 116 dst_offset 44
offset fail; src_offset 512 length 508 dst_offset 188
offset fail; src_offset 1140 length 116 dst_offset 168
offset fail; src_offset 148 length 116 dst_offset 492
offset fail; src_offset 120 length 116 dst_offset 540
Implausible compression ratio 1942.8
offset fail; src_offset 1073741940 length 116 dst_offset 28
Implausible compression ratio 12611.4
Implausible compression ratio 799133.5
Implausible compression ratio 263.8

**Comment by inferno-chromium** [comment]
I am excited that @rsheeter has fixed this and is planning to move the fuzzers to woff2 repo - https://github.com/google/woff2/commit/b91b020ced3b0dc03a3d8c721ddbae811324f6fa. This is awesome!

**Comment by inferno-chromium** [comment]
Removing my wrong previous comment, there are no updates since Jan 3 in woff2.

**Comment by inferno-chromium** [comment]
@rsheeter - can you please checkout https://oss-fuzz.com/v2/performance-report/libFuzzer_woff2_convert_woff2ttf_fuzzer_new_entry/libfuzzer_asan_woff2/latest and check one of the logs next to the logging issue.

I am unsure if this is a logging issue or the fuzz target is running into errors. We don't have any single crash bug open, so there could a bug in fuzz target, help is very appreciated.

**Comment by rsheeter** [comment]
FONT_COMPRESSION_BIN is generally for CLI users who want to see a bit more of what happened. Definitely not desirable for the fuzzer. I don't see anything that looks like an error at a glance, looks like it's just noisily reporting the fuzzer is sending it horrific inputs.
