### ISSUE TITLE
libreoffice compile failure

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#349]
https://oss-fuzz-build-logs.storage.googleapis.com/build_logs/libreoffice/latest.txt

@caolanm - can you please take a look. Also, just a fyi, we have enabled ubsan as well.

[0m[37;40m[[0m[32;1;40mLNK[0m[37;40m][0m Executable/wmffuzzer
/work/workdir/UnpackedTarball/freetype/instdir/lib/libfreetype.a(sfnt.o): In function `Load_SBit_Png':
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfa1b): undefined reference to `png_create_read_struct'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfa48): undefined reference to `png_create_info_struct'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfa7a): undefined reference to `png_destroy_read_struct'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfa9c): undefined reference to `png_set_longjmp_fn'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfad9): undefined reference to `png_set_read_fn'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfaec): undefined reference to `png_read_info'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfb48): undefined reference to `png_get_IHDR'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfc47): undefined reference to `png_set_palette_to_rgb'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfc60): undefined reference to `png_set_expand_gray_1_2_4_to_8'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfc78): undefined reference to `png_get_valid'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfc8d): undefined reference to `png_set_tRNS_to_alpha'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfca6): undefined reference to `png_set_strip_16'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfcbf): undefined reference to `png_set_packing'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfce5): undefined reference to `png_set_gray_to_rgb'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfcfe): undefined reference to `png_set_interlace_handling'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfd1a): undefined reference to `png_set_filler'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfd2d): undefined reference to `png_read_update_info'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfd98): undefined reference to `png_get_IHDR'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfe37): undefined reference to `png_set_read_user_transform_fn'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xfe52): undefined reference to `png_set_read_user_transform_fn'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xff7d): undefined reference to `png_read_image'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xffae): undefined reference to `png_read_end'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0xffc5): undefined reference to `png_destroy_read_struct'
/work/workdir/UnpackedTarball/freetype/instdir/lib/libfreetype.a(sfnt.o): In function `error_callback':
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0x10005): undefined reference to `png_get_error_ptr'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0x10035): undefined reference to `png_set_longjmp_fn'
/work/workdir/UnpackedTarball/freetype/instdir/lib/libfreetype.a(sfnt.o): In function `read_data_from_FT_Stream':
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0x10089): undefined reference to `png_get_io_ptr'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0x100b7): undefined reference to `png_get_error_ptr'
/work/workdir/UnpackedTarball/freetype/src/sfnt/sfnt.c:(.text+0x100d2): undefined reference to `png_error'
/work/workdir/UnpackedTarball/freetype/instdir/lib/libfreetype.a(autofit.o): In function `af_face_globals_new':
/work/workdir/UnpackedTarball/freetype/src/autofit/autofit.c:(.text+0xff02): undefined reference to `hb_ft_font_create'
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
/src/libreoffice/vcl/Executable_wmffuzzer.mk:13: recipe for target '/work/instdir/program/wmffuzzer' failed
make[1]: *** [/work/instdir/program/wmffuzzer] Error 1
Makefile:153: recipe for target 'Executable_wmffuzzer' failed
make: *** [Executable_wmffuzzer] Error 2

**Comment by caolanm** [comment]
Yeah, we were seeing this on http://tinderbox.libreoffice.org/MASTER/status.html with the equivalent build config, should go green here too soon
