### ISSUE TITLE
Coverage builds stopped building

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#3492]
It looks like coverage builds were not built on March 11: https://oss-fuzz-build-logs.storage.googleapis.com/index.html

**Comment by Dor1s** [comment]
Ouch, I've changed `cpp` in project.yaml to `c++` as per @jonathanmetzman's suggestion, but didn't realize that it was also used in https://github.com/google/oss-fuzz/blob/fc05e61826caae0e84b2c64280a5adfa96e5dc73/infra/gcb/build_and_run_coverage.py#L39

Thanks @guidovranken for noticing!

**Comment by guidovranken** [comment]
You're welcome :)

**Comment by Dor1s** [comment]
Build status isn't updated it, but most of the coverage jobs are finished already.
