### ISSUE TITLE
libFuzzer_llvm_libcxxabi_cxa_demangle_fuzzer suffers from multiple perf issues.

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#350]
https://clusterfuzz-external.appspot.com/gcsviewer?path=gs%3A%2F%2Fllvm_libcxxabi-logs.clusterfuzz-external.appspot.com%2FlibFuzzer_llvm_libcxxabi_cxa_demangle_fuzzer%2Flibfuzzer_asan_llvm_libcxxabi%2Fperformance_analysis.html
https://clusterfuzz-external.appspot.com/v2/testcases?fuzzer=libfuzzer_llvm_libcxxabi_cxa_demangle_fuzzer&open=yes

timeout	68.30%
slow_unit	43.90%
crash	27.59%
startup crash	3.89%

@kcc - i see your name in project.yaml, are you planning to fix these ?

**Comment by kcc** [comment]
I am not planing with this target myself, but have just pinged the others in https://llvm.org/bugs/show_bug.cgi?id=31031 and will continue pinging until morale improves

**Comment by inferno-chromium** [comment]
No reason to keep this open here, closing.
