### ISSUE TITLE
Can't build samba project with current build script

### ISSUE THREAD

**Issue by daehee87** [google/oss-fuzz#3505]
Hi.
I am having trouble building samba image with current OSSFuzz setting.
AFAIK, gcr.io/oss-fuzz-base/base-builder is based on Ubuntu 16.04.
But Samba currently dropped Ubuntu 16.04 support due to python 3.6 support. So their build script tries to find non-existing path. 
( [see this page](https://gitlab.com/samba-team/samba/-/tree/master/bootstrap%2Fgenerated-dists) )

Because of that, when I try to build fuzzer, I can't build Samba with `helper.py`
can I use ubuntu 18.04 base image with OSSFuzz? or is there some other workaround for this?

Have a great day.

```
daehee@skyfire:~/oss-fuzz$ python infra/helper.py build_image samba
Pull latest base images (compiler/runtime)? (y/N): 
Using cached base images...
Running: docker build --no-cache -t gcr.io/oss-fuzz/samba projects/samba
Sending build context to Docker daemon   5.12kB
Step 1/5 : FROM gcr.io/oss-fuzz-base/base-builder
 ---> b762aa9afdc9
Step 2/5 : RUN git clone https://gitlab.com/samba-team/samba samba
 ---> Running in 8724a47ae1ea
Cloning into 'samba'...
Removing intermediate container 8724a47ae1ea
 ---> 64050b3b2e43
Step 3/5 : RUN samba/lib/fuzzing/oss-fuzz/build_image.sh
 ---> Running in cf81972276cb
samba/lib/fuzzing/oss-fuzz/build_image.sh: 6: samba/lib/fuzzing/oss-fuzz/build_image.sh: samba/lib/fuzzing/oss-fuzz/../../../bootstrap/generated-dists/ubuntu1604/bootstrap.sh: not found
The command '/bin/sh -c samba/lib/fuzzing/oss-fuzz/build_image.sh' returned a non-zero code: 127
docker build failed.
daehee@skyfire:~/oss-fuzz$ python infra/helper.py build_image samba
Pull latest base images (compiler/runtime)? (y/N): y
Pulling latest base images...
Running: docker build --pull --no-cache -t gcr.io/oss-fuzz/samba projects/samba
Sending build context to Docker daemon   5.12kB
Step 1/5 : FROM gcr.io/oss-fuzz-base/base-builder
latest: Pulling from oss-fuzz-base/base-builder
fe703b657a32: Pull complete 
f9df1fafd224: Pull complete 
a645a4b887f9: Pull complete 
57db7fe0b522: Pull complete 
a92dee5670c4: Pull complete 
2dbb9d2fb6a9: Pull complete 
69337abedda6: Pull complete 
431d3ee27017: Pull complete 
a82e9a81d043: Pull complete 
74ffe2496023: Pull complete 
a6cac759586d: Pull complete 
58d50358dd99: Pull complete 
bd724b9ef855: Pull complete 
61aaf2c5c9ce: Pull complete 
864ea03c70d8: Pull complete 
b4e15d7e2403: Pull complete 
67624374f573: Pull complete 
7b5904f71650: Pull complete 
7ecb539d4c66: Pull complete 
dfc408f23ddd: Pull complete 
509d2d6aa471: Pull complete 
Digest: sha256:540ed10c4bbbf8b9607afa86d642806221ec7389a24238f8a86baad1ab591fdc
Status: Downloaded newer image for gcr.io/oss-fuzz-base/base-builder:latest
 ---> c222d54805f9
Step 2/5 : RUN git clone https://gitlab.com/samba-team/samba samba
 ---> Running in 4c35d9cc9c1c
Cloning into 'samba'...
Removing intermediate container 4c35d9cc9c1c
 ---> 91b1de3a664d
Step 3/5 : RUN samba/lib/fuzzing/oss-fuzz/build_image.sh
 ---> Running in f66b297d90cc
samba/lib/fuzzing/oss-fuzz/build_image.sh: 6: samba/lib/fuzzing/oss-fuzz/build_image.sh: samba/lib/fuzzing/oss-fuzz/../../../bootstrap/generated-dists/ubuntu1604/bootstrap.sh: not found
The command '/bin/sh -c samba/lib/fuzzing/oss-fuzz/build_image.sh' returned a non-zero code: 127
docker build failed.
```

**Comment by abartlet** [comment]
Yeah, that is unfortunate.  We (Samba) CI the ./lib/fuzzing/oss-fuzz/build_samba.sh script but on our main image, which isn't the oss-fuzz image.

I didn't remember that oss-fuzz is stuck on ubuntu 16.04, and it looks like it would be a massive task to rebase to a new base image.

I would rather not roll back the Python 3.6 minimum, but I have got Samba to instead set a Python 3.5 minimum for fuzzing

We already skip most of the use of python for fuzzing builds so this seems to work...

https://gitlab.com/samba-team/samba/-/merge_requests/1220

**Comment by abartlet** [comment]
I should note that this moves the samba-fuzz task to Ubuntu 16.04, so we will notice if we drop that again.

**Comment by inferno-chromium** [comment]
Thank you very much @abartlet .

It will be a little while before we plan the upgrade from 16.04. Problem is MSan which requires all system instrumented libraries.

**Comment by abartlet** [comment]
Monorail informs me this is working again: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21189#c2

https://oss-fuzz-build-logs.storage.googleapis.com/index.html#samba

**Comment by inferno-chromium** [comment]
AMAZING, @abartlet - you are my hero, thank you very much for supporting this! We do plan to look at Ubuntu next LTS, 20 and will wait for it to be stable and do the major leap.

**Comment by abartlet** [comment]
Thanks.  We will want to move of Ubuntu 16.04 due to the old GnuTLS found there, but that isn't massively urgent and it would go when we drop 18.04 as well.
