### ISSUE TITLE
binutils:fuzz_bfd.c

### ISSUE THREAD

**Issue by amodra** [google/oss-fuzz#3506]
https://oss-fuzz.com/testcase-detail/5642099895828480 is an abort inside projects/binutils/fuzz_bfd.c due to not being able to remove, fopen, or fwrite to a file /tmp/fuzz.bfd.  It is a poor practice to abort here as there are many reasons why the file may not be able to be written, and use of a fixed file prevents multiple copies of fuzz_bfd being run.  Please change to use  mkstemp instead of a fixed name, and exit without an abort on /tmp errors.

**Comment by Dor1s** [comment]
//cc @catenacyber @DavidKorczynski who contributed binutils fuzz targets

Note that in general it's not recommended to interact with the file system during fuzzing -- prefer to keep everything in memory.

**Comment by catenacyber** [comment]
> Note that in general it's not recommended to interact with the file system during fuzzing -- prefer to keep everything in memory.

I know, but for this target, if I am not mistaken, there is no equivalent of `bfd_openr` with a buffer.
So we need a file
