### ISSUE TITLE
Crashes in radamsa in-process mutator

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#3525]
It's likely ClusterFuzz issue, but I'm filing it here so that other users could also see it and not file duplicates

//cc @mpherman2 @mbarbella-chromium 

https://oss-fuzz.com/testcase-detail/5116445232201728

https://oss-fuzz.com/testcase-detail/5176181516402688

https://oss-fuzz.com/testcase-detail/5661711026880512

**Comment by Dor1s** [comment]
Looks like these started to happen just yesterday, e.g. https://oss-fuzz.com/testcases?open=yes&q=CHUNK_QUARANTINE

**Comment by mpherman2** [comment]
Disabled Radamsa in process mutator to fix this for now. As is it should not have been active. Eventually we will re-enable with a fix that makes it compatible.
