### ISSUE TITLE
address sanitizer: incorrect ILL detected

### ISSUE THREAD

**Issue by boxerab** [google/oss-fuzz#3533]
[Bug Report]( https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21136)

[Code](https://github.com/GrokImageCompression/grok/blob/007a95cf4859acf17046cf3156f1a5292091795a/src/lib/jp2/t1/t1_ht/coding/ojph_block_decoder.cpp#L408)

Address sanitizer detects an illegal operation, but the only ILL I can see is if `tbl0[j].cwd_len`
were greater than 31. However, `tbl0[j].cwd_len` is always >=1 and <= 7 .

**Comment by inferno-chromium** [comment]
Assigning to current sheriff.

**Comment by inferno-chromium** [comment]
Did you try to run fuzzer and add some printf near the line to make sure that values passed to tbl0 are within range. That crash was on startup, so looks like it is happening pretty easily.

**Comment by boxerab** [comment]
@inferno-chromium thanks! this is a static init method, so it gets initialized the same way each time at start up. I added asserts to make sure that left shift is valid, and that the table index is always in bounds. In fact, the code enforces the bounds. But, I didn't run the fuzzer, I just ran the compressor on a sample file.

**Comment by boxerab** [comment]
Should it make a difference whether I run the fuzzer or just on a sample file, for this case ?

**Comment by boxerab** [comment]
By the way, I also see in the issue that:

`ClusterFuzz testcase 5759957036433408 appears to be flaky, updating reproducibility label.`

so it is currently set to un-reproducible.

**Comment by inferno-chromium** [comment]
For flaky cases, it is best to just try running fuzzer itself, this kind of issue should hit very quick.
Difference is when you run fuzzer, it tries random testcases, whereas with a testcase run, it only runs that testcase and exits. If bug is dependent on underlying program state that changes on each fuzzer run, then testcse run is not useful (as it will be unreproducible).

**Comment by boxerab** [comment]
@inferno-chromium thanks. In that case, I need a little help running the fuzzer. If you have time, can you tell me quickly how to run the fuzzer for this case ?

**Comment by boxerab** [comment]
I can build the fuzzers like so:

```
python infra/helper.py build_image grok
python infra/helper.py build_fuzzers grok
```

**Comment by boxerab** [comment]
ok, figured it out. And, no, there was no error reported when I ran the fuzzer on the test case.

**Comment by inferno-chromium** [comment]
Let fuzzer run without testcase argument for some time. It should crash with that error.
It is flaky, so testcase might not matter.
see crash stats, https://oss-fuzz.com/crash-stats?block=day&days=7&end=440248&group=platform&number=count&project=grok&sort=total_count
this seems like the top crash for grok.

**Comment by boxerab** [comment]
thanks, so, what command line to run fuzzer without test case ?

**Comment by inferno-chromium** [comment]
Point 3 at https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally
```
python infra/helper.py run_fuzzer $PROJECT_NAME <fuzz_target>
```

**Comment by boxerab** [comment]
@inferno-chromium thanks for your help !

**Comment by boxerab** [comment]
I ran the fuzzer for 10 minutes without any crashes. I did make a few fixes, so this may have fixed the problem. Closing.
