### ISSUE TITLE
No builds produced on Mar 23rd for many (if not all) projects

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#3537]
And no build failures reported -- our builder just didn't attempt to build, or maybe someone manually cancelled the builds?

This is not a big deal, but I'm filing this issue in case it ever happens again. Plus we can investigate more if anyone has an insight.

This incident sparked a bunch of exceptions on CF end: https://console.cloud.google.com/errors/CLP1laXxg9epag?time=P30D&project=clusterfuzz-external

I've marked the exceptions resolved for now.

which actually should not have happened, but I'll report it separately in CF repo.

**Comment by Dor1s** [comment]
Confirmed that all builds were skipped:

```
$ gsutil ls gs://clusterfuzz-builds/*/*-20200324*
```

returned none. Note Mar 24th timestamp -- that's because build names use UTC timezone.

**Comment by oliverchang** [comment]
There was a base-image build failure on Mar 23, which would explain this.

**Comment by Dor1s** [comment]
Ah, great catch! Filed https://github.com/google/oss-fuzz/issues/3538 to discuss build pipeline in a broader context, closing this. Thanks, Oliver!
