### ISSUE TITLE
Build pipeline improvements

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#3538]
Discussion / tracking issue

1. Migrate off Jenkins?
2. Report base image build failures?
3. Build status job is flaky: https://builder.oss-fuzz.com/job/infra/job/builds_status/
4. Think of on demand builds and/or more frequent builds for actively developed projects: https://github.com/google/oss-fuzz/issues/419

**Comment by kabeer27** [comment]
Progress completed on my end (offboarding today so just giving an update)
- Migrated off jenkins : Complete
- Historical logs now available (build_status job improved)
- Custom build frequency (upto 4 builds per day) now available as 'builds_per_day: value' in project.yaml

**Comment by jonathanmetzman** [comment]
I think this is essentially complete.
