### ISSUE TITLE
guidance on debugging failed build

### ISSUE THREAD

**Issue by mimoo** [google/oss-fuzz#3549]
Hey!

I'm trying to debug a failed build, but every time I run the command it just exits after it fails and doesn't let me investigate. 

```
python infra/helper.py build_fuzzers --sanitizer address libra
```

It would be nice to have some guidance on how to stay in the shell. I'm trying to ramp up on docker but so far my attempts have failed :)

**Comment by mimoo** [comment]
ok so this seems to do it:

```
docker container run --name investigate_build_failure -d gcr.io/oss-fuzz/libra
docker container exec -it investigate_build_failure /bin/bash
```

**Comment by jonathanmetzman** [comment]
I personally use `python infra/helper.py shell` for this purpose.
I wonder if adding `|| /bin/bash` to the build command we run in the docker image would be useful here? @Dor1s WDYT?

**Comment by Dor1s** [comment]
> I personally use `python infra/helper.py shell` for this purpose.

Same for me. Then inside the image I'd do `compile` command.

> I wonder if adding `|| /bin/bash` to the build command we run in the docker image would be useful here? @Dor1s WDYT?

Sounds like a nice idea to me, why didn't we do it earlier... :)

**Comment by mimoo** [comment]
wow nice! Didn't know I could do this :) thanks!

**Comment by mimoo** [comment]
I see that it is in the debugging section: https://google.github.io/oss-fuzz/advanced-topics/debugging/

So I'll close this
