### ISSUE TITLE
MySQL fuzz targets

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#355]
@vasild, @jdd-mysql - have you heard about OSS-Fuzz (https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html). It will be great to fuzz MySQL as part of OSS-Fuzz and find security and stability issues automatically.  It is easy to integrate with us - https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md.

**Comment by Dor1s** [comment]
Hey @morgo, we've been discussing this at FOSDEM last weekend, would you mind helping to set things up?

**Comment by morgo** [comment]
I've introduced you to the right person on our end via email :)

**Comment by vasild** [comment]
That looks really interesting, good luck!

**Comment by inferno-chromium** [comment]
We are just as excited as you are :) Closing this since you guys already communicated.

**Comment by catenacyber** [comment]
Hi all, for your information, we started working on mysql with @ChAlv @zjanati and Julien Zhan and we are working with Oracle Security Alerts on fixing the first found bugs.
