### ISSUE TITLE
Fix wpatund fuzzers, they connect to network/internet in some cases

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#3555]
See https://github.com/google/fuzzbench/issues/171

@darconeous - can you please help to mock that part. this will help us keep wpatund as a benchmark in our recently launched FuzzBench project.

**Comment by darconeous** [comment]
@abtink is the current maintainer.

**Comment by abtink** [comment]
@inferno-chromium `wpantund` is in maintenance mode (bug-fixing and small enhancements for CI tests of related projects). I would not recommend using it as benchmark for new features/projects.

**Comment by inferno-chromium** [comment]
Thanks, it is now removed in fuzzbench.
