### ISSUE TITLE
reproducible docker images

### ISSUE THREAD

**Issue by KihongHeo** [google/oss-fuzz#3559]
Hi,
It seems that reproducible docker images have not been updated since last year (https://console.cloud.google.com/gcr/images/oss-fuzz). Do you provide them somewhere else or only to private members?

**Comment by Dor1s** [comment]
That was intentionally disabled in https://github.com/google/oss-fuzz/pull/2232

We still provide all base images. As for particular project build images, you can use `infra/helper.py build_image <project_name>` command to create one locally.
