### ISSUE TITLE
Interested in enabling DFT on Grok project

### ISSUE THREAD

**Issue by boxerab** [google/oss-fuzz#3569]
cc @Dor1s 

Would like to learn more about adding data flow to the Grok fuzzers.

https://github.com/GrokImageCompression/grok

**Comment by Dor1s** [comment]
Let's just try and see: https://github.com/google/oss-fuzz/pull/3570

Dataflow config won't work right now if grok depends on other libraries. In such case this will be blocked on https://github.com/google/oss-fuzz/issues/3388

**Comment by boxerab** [comment]
Why was this closed? #3388 is still open, and my issue has not been resolved.
Thanks.

**Comment by inferno-chromium** [comment]
Sorry about that, reopening.
