### ISSUE TITLE
Monorail no longer sends detailed bug reports to non-gmail addresses

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#3576]
Here's what bug reports I have been receiving lately look like:
```
Subject: Issue 20548 in oss-fuzz

The following issue was created:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20548
-- 
You received this message because:
  1. You were specifically CC'd on the issue

You may adjust your notification preferences at:
https://bugs.chromium.org/hosting/settings

Reply to this email to add a comment.
```
The same bug report sent to my gmail address (which I almost never use) looks like:
```
Subject: Issue 20548 in oss-fuzz: systemd:fuzz-network-parser: Abrt in in_addr_from_string


New issue 20548 by ClusterFuzz-External: systemd:fuzz-network-parser: Abrt in in_addr_from_string
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20548

Detailed Report: https://oss-fuzz.com/testcase?key=5648923282898944

Project: systemd
Fuzzing Engine: libFuzzer
Fuzz Target: fuzz-network-parser
Job Type: libfuzzer_msan_systemd
Platform Id: linux

Crash Type: Abrt
Crash Address: 0x000000000001
Crash State:
  in_addr_from_string
  config_parse_address_generation_type
  next_assignment
  
Sanitizer: memory (MSAN)

Regressed: https://oss-fuzz.com/revisions?job=libfuzzer_msan_systemd&range=202002050334:202002052115

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=5648923282898944

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

If you need to contact the OSS-Fuzz team with a question, concern, or any other feedback, please file an issue at https://github.com/google/oss-fuzz/issues. Comments on individual Monorail issues are not monitored.

This bug is subject to a 90 day disclosure deadline. If 90 days elapse
without an upstream patch, then the bug report will automatically
become visible to the public.

-- 
You received this message because:
  1. You were specifically CC'd on the issue

You may adjust your notification preferences at:
https://bugs.chromium.org/hosting/settings

Reply to this email to add a comment.
```

It was relatively easy to figure out whether a bug report is important enough to go look at it closely by just skimming over emails sent to my main address. Now I mostly ignore anything ClusterFuzz has to say until I check out my gmail inbox once a month.

As an aside, given that it's not uncommon to use non-gmail addresses  I'm wondering if it could be one of the reasons OSS-Fuzz bug reports like https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20816 go unnoticed.

**Comment by evverx** [comment]
Interestingly, turns out we already discussed why issues can go unnoticed in https://github.com/google/oss-fuzz/issues/3006#issuecomment-549737611. It seems that the part reporting bugs (including sending notifications to non-gmail addresses) isn't ideal and probably can be made more useful in terms of delivering bug reports to developers who triage and fix bugs.

**Comment by Dor1s** [comment]
Wow, this is pretty bad. Thanks for noticing this, @evverx. Very likely it explains the ignorance on the OpenSSL bug indeed.

Filed https://bugs.chromium.org/p/monorail/issues/detail?id=7461 against the bug tracker.

**Comment by evverx** [comment]
I forgot to mention that as far as I can tell it stopped working in September 2019. I hope it helps to track down what could have caused it.

**Comment by evverx** [comment]
I commented there but to judge from https://bugs.chromium.org/p/monorail/issues/detail?id=7461, it's a losing battle. Closing.

**Comment by Dor1s** [comment]
We should find a solution for this, re-opening.

**Comment by evverx** [comment]
I'm just spitballing but now that all the corpora have been made public I'm wondering if it still makes sense to keep adding the "restrict-view-commit" label. Given that most bugs including https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20816 are usually a few minutes of fuzzing away from being discovered it seems to me that it just kind of gives everybody a false sense of security.

**Comment by inferno-chromium** [comment]
Current corpora is not public, it is 90 day old corpora that is made public. So, we are trying to prevent against harder to find bugs. However, for obvious security regressions, they can hit very easily, even without corpora. Making bugs public early on or at time of filing will not happen, we want to give projects time to respond to their bugs, this will reflect very bad practice on our part [even though truth for some bugs is they can be found with a few minutes of fuzzing].

**Comment by evverx** [comment]
> it is 90 day old corpora that is made public

Good to know. Though, unless I'm mistaken, it means that CIFuzz always lags behind OSS-Fuzz, which, in turn, means that it isn't as useful as it could be.

**Comment by inferno-chromium** [comment]
This is now fixed in monorail - https://bugs.chromium.org/p/monorail/issues/detail?id=7461. Please reopen if you still see this.
