### ISSUE TITLE
bisector doesn't work for gdal

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#3582]
The bisector does not work for gdal as-is, as gdal checks out dependencies in the the main repo. 

```
RUN git clone --depth 1 https://github.com/OSGeo/gdal gdal

RUN git clone --depth 1 https://github.com/OSGeo/proj.4 gdal/proj

RUN git clone --depth 1 https://github.com/curl/curl.git gdal/curl
```

Opening this issue to figure out the best way to address this.

**Comment by Dor1s** [comment]
One idea we had was to check the nearest (in time) srcmap file, but that won't be precise in many cases.

**Comment by oliverchang** [comment]
> One idea we had was to check the nearest (in time) srcmap file, but that won't be precise in many cases.

I also had something similar in mind. I suspect we'll need some form of this for reliable bisects but want to make sure we haven't ruled out any other possible solutions.

**Comment by jonathanmetzman** [comment]
I think the implementation might not be what we specified in design (go/specific-builds#heading=h.aarlwjfiuxo) I think in the design said to copy the $SRC to the host, checkout what is needed and then $SRC back.

**Comment by oliverchang** [comment]
I've implemented the $SRC copying, and it seems to work. The implementation is specific to bisection and does not affect CIFuzz.
