### ISSUE TITLE
Some projects might be missing to enable honggfuzz

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#3591]
E.g. these that mention afl explicitly, but not honggfuzz

/build/oss-fuzz/projects/brotli
/build/oss-fuzz/projects/xz
/build/oss-fuzz/projects/proxygen
/build/oss-fuzz/projects/fuzzing-puzzles
/build/oss-fuzz/projects/libyaml
/build/oss-fuzz/projects/pffft
/build/oss-fuzz/projects/libexif
/build/oss-fuzz/projects/nss
/build/oss-fuzz/projects/openjpeg
/build/oss-fuzz/projects/bzip2

**Comment by Dor1s** [comment]
good catch, looks like there are up to 43 of such projects:

```
$ egrep -r fuzzing_engines -l | wc -l
93
$ cat `egrep -r fuzzing_engines -l` | egrep honggfuzz -c
50
```

I can kick off builds for all of those and then enable the projects where build has succeeded.

**Comment by Dor1s** [comment]
I'm ready to do this, but waiting for the base-images re-build to finish first.

**Comment by inferno-chromium** [comment]
Thanks so much @Dor1s

**Comment by inferno-chromium** [comment]
travis should now do both build and check_build for honggfuzz projects.

**Comment by Dor1s** [comment]
thanks, GCB runs the build checks too (e.g. https://console.cloud.google.com/logs/viewer?resource=build%2Fbuild_id%2F0f633f71-0827-4af5-8a63-55579abc6098&project=oss-fuzz&minLogLevel=0&expandAll=false&timestamp=2020-04-08T23:17:21.179000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2020-04-08T22:17:21.431Z&dateRangeEnd=2020-04-08T23:17:21.431Z&interval=PT1H&scrollTimestamp=2020-04-08T23:02:51.208759765Z), so I'll bypass Travis to avoid spamming with ~40 pull requests

**Comment by Dor1s** [comment]
The failed projects are mostly Go, large projects, or some custom builds like jsc. However, Cloud Build failed for some of the projects for no apparent reason, e.g. proxygen https://console.developers.google.com/logs/viewer?resource=build%2Fbuild_id%2F35f21857-4275-4bb6-b32c-76cdeb7cf9ae&project=oss-fuzz, so I'm going to re-try them once again.
