### ISSUE TITLE
go-fuzz support

### ISSUE THREAD

**Issue by dvyukov** [google/oss-fuzz#36]
go-fuzz is a fuzzer for Go:
https://github.com/dvyukov/go-fuzz

Since oss-fuzz aimed at supporting multiple fuzzers, go-fuzz support should be possible and would be useful.

go-fuzz contains 70 fuzzers for Go std lib and other popular packages but there is no story for continous running:
https://github.com/dvyukov/go-fuzz/tree/master/examples

**Comment by mikea** [comment]
There are two areas:

* build system. This should be the easiest. As long as a docker image provides binaries in `/out/`, we are game. We don't care how the binary was produced. 

* ClusterFuzz. I am not sure how much need to be changed in CF to add a new type of fuzzer. @oliverchang

**Comment by dvyukov** [comment]
@Dor1s

**Comment by dvyukov** [comment]
FTR, issue about fuzzing support in Go:
https://github.com/golang/go/issues/19109

**Comment by dvyukov** [comment]
We need to ensure that Go fuzzing support will be integratable with OSS-Fuzz or it will be a bold fail if we later realize that it's poorly suitable for setups like OSS-Fuzz.

**Comment by Dor1s** [comment]
Yay! I'm sure it's all doable, we just need to plan some time for doing that. //cc @inferno-chromium 

> We should be able to support this, right? We can have the engine as the binary and target as data dependency of the binary, right?

Yes, AFL works in a similar way and we use it fine.

> What flags/features OSS-Fuzz needs from a fuzzing engine? Anything special?

We'll need crash stacktraces, distinct crash signatures for different crash types, crash minimization, performance stats (speed, coverage, corpus units, etc), something else I can't think off the top of my head.

The way it works now (and probably will keep working) is that we have a launcher script for every fuzzing engine. CF calls that launcher script (there is a fairly simple interface that needs to be implemented), and the script interacts with the fuzzing engine (e.g. provides proper CMD line, runs it, does some log parsing, etc). //cc @oliverchang

**Comment by dvyukov** [comment]
Thanks. Looks like we should not have any major problems then.
We could prototype OSS-Fuzz support later when Go fuzzing support takes shape... or maybe  now using @thepudds prototype https://github.com/golang/go/issues/19109#issuecomment-451871672

> We'll need crash stacktraces, distinct crash signatures for different crash types,

This should be extractable from raw crash in the wrapper script.

> crash minimization

The plan is that Go fuzzer will save already minimized crashes, so this can be no-op. And this should be optional anyway.

> performance stats (speed, coverage, corpus units, etc)

No concrete plan for this. But assuming this is optional.

**Comment by Dor1s** [comment]
This can be considered done. Further work is being tracked as https://github.com/google/oss-fuzz/issues/2714
