### ISSUE TITLE
Some project crash on startup with Honggfuzz due to failure to find LLVMFuzzerTestOneInput, breaks bad_build check

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#3607]
E.g. tor, pcre2, woff2

```
Persistent mode: Launched new persistent pid=6745
[2020-04-09T06:18:54+0000][F][6745] LLVMFuzzerTestOneInput():38 Define 'int LLVMFuzzerTestOneInput(uint8_t * buf, size_t len)' in your code to make it work
[2020-04-09T06:18:54+0000][W][118] arch_checkWait():234 Persistent mode: pid=6745 exited with status: EXITED, exit code: 1
```

This can be reproduced with
```
python infra/helper.py build_image tor
python infra/helper.py build_fuzzers --sanitizer address --engine honggfuzz --architecture x86_64 tor
python infra/helper.py check_build --sanitizer address --engine honggfuzz --architecture x86_64 tor
```
atleast tor does https://github.com/torproject/tor/blob/4f02812242d1fd90d859eb98ac3fb1ed182f18cf/src/test/fuzz/fuzzing_common.c#L125

woff2 is very weird, fuzzer seems striaghtforward with LLVMFuzzerTestOneInput - https://github.com/google/woff2/blob/master/src/convert_woff2ttf_fuzzer.cc

@robertswiecki - can you please check what is going on. Previously we were just building with honggfuzz and not checking for execution failures, now we do.

**Comment by robertswiecki** [comment]
> can you please check what is going on. Previously we were just building with honggfuzz and not checking for execution failures, now we do.

Sure, will check right after the holiday time, I gather that since you've disabled them for those targets, this is not urgent as in today-urgent :)

**Comment by inferno-chromium** [comment]
> > can you please check what is going on. Previously we were just building with honggfuzz and not checking for execution failures, now we do.
> 
> Sure, will check right after the holiday time, I gather that since you've disabled them for those targets, this is not urgent as in today-urgent :)

Yes right, disabled those to avoid confusion for OSS devs. Take your time, enjoy the holidays!

**Comment by nareddyt** [comment]
ESPv2 builds are still failing with a similar (?) error:

```
Step #32: Size:237 (i,b,hw,ed,ip,cmp): 0/0/0/2/0/0, Tot:0/0/0/403/17/2559
Step #32: Signal 2 (Interrupt) received, terminating
Step #32: Terminating thread no. #0, left: 0
Step #32: Summary iterations:217918 time:20 speed:10895 crashes_count:0 timeout_count:0 new_units_added:122 slowest_unit_ms:735 guard_nb:718115 branch_coverage_percent:0 peak_rss_mb:0
Step #32: backend_routing_filter_fuzz_test:
Step #32: BAD BUILD: fuzzing /tmp/not-out/backend_routing_filter_fuzz_test with honggfuzz failed.
Step #32: /tmp/not-out/honggfuzz -n 1 --exit_upon_crash -R /tmp/backend_routing_filter_fuzz_test_honggfuzz.report -W /tmp/backend_routing_filter_fuzz_test_honggfuzz_address_out -v -z -P -f "/tmp/backend_routing_filter_fuzz_test_corpus" -- "/tmp/not-out/backend_routing_filter_fuzz_test"
```

[Full log](https://oss-fuzz-build-logs.storage.googleapis.com/log-832329b5-3b5a-460d-9272-f9e6b4515619.txt)

Build just occured today, so I'm confused. I thought #3610 would disable this check and allow builds to pass after the PR is merged.

**Comment by nareddyt** [comment]
Oh, #3610 just disabled it for select projects, not `espv2`

**Comment by robertswiecki** [comment]
I think the projects compile and run fine (based on logs), it's just that he script parsing its output seems to be confused.

Recently I changed the output of honggfuzz, to print "Sz:<size> Time:<exectime> <coverage info>" instead of previous "Size:<size> <coverage info>" and one of oss-fuzz's PRs followed.

The current oss-fuzz tag from https://github.com/google/honggfuzz/releases/tag/oss-fuzz is using this convention and should be used in those lofs. I'm not sure why you see the old "Size:... " log entries, probably honggfuzz source code got cached somehow and is not downloaded from the repo for your build.

**Comment by inferno-chromium** [comment]
@nareddyt - see https://github.com/google/oss-fuzz/issues/3157#issuecomment-611706961, i am waiting on @asraa to fix this properly, so that this Dockerfile hack can be removed [it hardcodes old image, which uses an old version of Honggfuzz]. Upto you, you can either propose a PR to disable honggfuzz, but i prefer to wait a few more days and get this fixed properly.

**Comment by nareddyt** [comment]
Right, I forgot about that. Sounds good, I'll create a PR in GoogeCloudPlatform/esp-v2 to update the bazel version as well.

**Comment by jonathanmetzman** [comment]
I'm fairly sure I've run into this issue with tor+honggfuzz in the past. Don't really know that this is fixed.
