### ISSUE TITLE
Dataflow seems to break C++ linkage

### ISSUE THREAD

**Issue by PJK** [google/oss-fuzz#3613]
I have run into an issue where the dataflow sanitizer cannot link code that compiles correctly otherwise as soon as linking to the c++ stdlib is required: https://github.com/PJK/libcbor/issues/141, https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21411

Is it possible that this is a systematic issue, or is it a false flag?

**Comment by Dor1s** [comment]
lidstdc++ also has to be instrumented, this will be addressed as https://github.com/google/oss-fuzz/issues/3388

let me disable dataflow config for libcbor for now
