### ISSUE TITLE
bisector: find and use a project Dockerfile close to the provided commit ranges

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#3651]

**Comment by oliverchang** [comment]
Another issue: sometimes older revisions of projects don't build with newer base-images, due to more strict clang checks.

**Comment by jonathanmetzman** [comment]
> Another issue: sometimes older revisions of projects don't build with newer base-images, due to more strict clang checks.

Hacky solution: Find out the base-builder a nearby commit used, then pull that image tag it as base-builder:latest, build image from there.

**Comment by oliverchang** [comment]
This was done.
