### ISSUE TITLE
Fix broken CI build bot

### ISSUE THREAD

**Issue by sffc** [google/oss-fuzz#3656]
Context: https://github.com/google/myanmar-tools/pull/45

@inferno-chromium said:

> getcwd not exist might indicate
> build.sh should be WORKDIR $SRC/myanmar-tools instead of
> WORKDIR $SRC/myanmar-tools/clients/cpp
> this needs a change to OSS-Fuzz repo and then can try here again.
> @jonathanmetzman would know and can check in a day or two.

I merged the PR ignoring the failing CI, and am filing this issue to follow up, because the CI continues to fail on other PRs in our repo.

**Comment by inferno-chromium** [comment]
@sffc - can you please try again. try a new PR in your repo and see if is fixed.

**Comment by sffc** [comment]
Yep, looks like it's working now: https://github.com/google/myanmar-tools/pull/47

Thanks!
