### ISSUE TITLE
More convenient way to assign custom weights to projects

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#3663]
Sometimes we give a higher or lower than the default weight to projects integrated with OSS-Fuzz (based on the project importance and other factors). The existing way of doing that isn't super convenient, as it requires the project to be buildable and have a corresponding metadata created on ClusterFuzz side.

More convenient workflow would be when we accept a project and agree on assigning a custom weight for it, we should be able to assign that weight right away, at exactly that moment when the first integration PR gets accepted.

Possible solutions are to have some config file with key/value pairs, or maybe something in Datastore, so that we could add a record like `project ABC : weight 0.1` even when project `ABC` isn't integrated yet.

Don't have any good idea to be frank, but it seems we all agreed that we'd like to improve this.

**Comment by jonathanmetzman** [comment]
Why not use project.yaml for this? When a PR is integrated we can ask devs to add this.
Might become problematic if we were to make contributors OWNERS over their project directories and let them land PRs without asking.

**Comment by Dor1s** [comment]
yes, OWNERS would make it a problem and in general I don't think that config should be public.
