### ISSUE TITLE
syzkaller: broken with cryptic errors

### ISSUE THREAD

**Issue by dvyukov** [google/oss-fuzz#3670]
Our builds started failing recently with errors I can't understand.
Here is one example run:
https://github.com/google/syzkaller/pull/1681/checks?check_run_id=598000524

```
+ go-fuzz -func Fuzz -o compiler_fuzzer.a ./pkg/compiler
# _/src/syzkaller/pkg/compiler
pkg/compiler/attrs.go:56:26: undefined: prog.SyscallAttrs
pkg/compiler/attrs.go:67:13: undefined: prog.CppName
pkg/compiler/check.go:716:33: n.Attrs undefined (type *ast.Call has no field or method Attrs)
pkg/compiler/consts.go:80:26: n.Attrs undefined (type *ast.Call has no field or method Attrs)
pkg/compiler/consts.go:227:27: n.Attrs undefined (type *ast.Call has no field or method Attrs)
pkg/compiler/gen.go:115:12: undefined: prog.SyscallAttrs
pkg/compiler/gen.go:116:46: n.Attrs undefined (type *ast.Call has no field or method Attrs)
pkg/compiler/gen.go:132:3: unknown field 'Attrs' in struct literal of type prog.Syscall
2020/04/18 15:26:05 failed to build packages:exit status 2
2020-04-18 15:26:05,771 - root - ERROR - Building fuzzers failed.
```

This does not reproduce for me locally, both in normal builds and using go-fuzz-build.
And I am not sure what could cause such error mode, it seems that sources are in some very inconsistent state.

But also I can't understand why this is running go-fuzz and not go-fuzz-build. go-fuzz is not supposed to build anything and it does not even have such flags. Does oss-fuzz use some custom version? Can it be broken?

Also I noticed the script checks out `github.com/ianlancetaylor/demangle` separately:
```
Step 4/7 : RUN go get github.com/ianlancetaylor/demangle
```
We have it vendored and it should not be necessary:
https://github.com/google/syzkaller/tree/master/vendor/github.com/ianlancetaylor/demangle
go-fuzz-build works fine without that. Using a random version of the package may only cause build errors. But it does not seem to be the root cause of the above errors.

**Comment by inferno-chromium** [comment]
We switched syzkaller to using native go-fuzz from https://github.com/mdempsky/go114-fuzz-build (go-fuzz is basically go114-fuzz-build) in https://github.com/google/oss-fuzz/commit/896ed726e28f8b540f8331cdbe1fccf135796343. Will that not work (@mdempsky fyi) ? We can switch it back to your go-fuzz-build.

**Comment by inferno-chromium** [comment]
@mdempsky - did you get a chance to take a look ?

**Comment by jonathanmetzman** [comment]
@dvyukov syzkaller build seems to pass fine now.
Can you reenable CIFuzz?

**Comment by dvyukov** [comment]
Tried to re-enable it, the PR run failed:
https://github.com/google/syzkaller/runs/2154443033

**Comment by inferno-chromium** [comment]
@catenacyber - thoughts on this go failure ?

**Comment by catenacyber** [comment]
I just proposed https://github.com/google/oss-fuzz/pull/5463
It seems the error now is not the same one as initially.
The error seems to come from the fact that `git config --get remote.origin.url` returns `https://github.com/google/syzkaller/` when for other repos, they return `https://github.com/AFLplusplus/AFLplusplus.git`
I am not sure as I am not sure what arguments are passed to detect_repo.py

**Comment by dvyukov** [comment]
Re-triggered oss-fuzz run on https://github.com/google/syzkaller/pull/2513

**Comment by dvyukov** [comment]
OSS-Fuzz action succeeded now. Thanks.
