### ISSUE TITLE
Please add me so I can view the reports

### ISSUE THREAD

**Issue by kaleb-himes** [google/oss-fuzz#3676]
To whom it may concern you have my work email `kaleb [at] wolfssl [dot] com` on your mailing list but I can never view the reports because it only allows you to login with a gmail account. Can you add `kaleb [dot] himes [at] gmail [dot] com` to the mailing list also so I can view the reports? Thank you!

`https://oss-fuzz.com/download?testcase_id=5189949147316224`

```
You (email=kaleb.himes@gmail.com) are not authorized to access this page!

Please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.

Switch account
Logout

OSS-Fuzz is an effort to provide continuous fuzzing infrastructure for open-source software. You can read more about it here: https://github.com/google/oss-fuzz.
```

**Comment by kaleb-himes** [comment]
@guidovranken can you take a look?

**Comment by inferno-chromium** [comment]
You have two options,
1) either submit pr to add gmail address - https://github.com/google/oss-fuzz/blob/master/projects/wolfssl/project.yaml
2) create google account with your wolfssl email - https://support.google.com/accounts/answer/27441 "Use an existing email address "

**Comment by kaleb-himes** [comment]
NOTE: `kaleb [dot] himes [at] gmail [dot] com` is already in the project.yaml so opening a PR does no good. I need to have access to the reports, not have my email added to where it already is again...?

**Comment by inferno-chromium** [comment]
@kaleb-himes - i dont see your gmail id in project.yaml, see https://github.com/google/oss-fuzz/blob/master/projects/wolfssl/project.yaml#L4, where do you see it.

**Comment by kaleb-himes** [comment]
Oh I do apologize, i was looking at the wrong project.yaml. I'll open a PR, sorry about the confusion.
