### ISSUE TITLE
ClusterFuzz job management?

### ISSUE THREAD

**Issue by mykter** [google/oss-fuzz#3688]
I've pored through the oss-fuzz code but not been able to find anything that creates / updates / deletes jobs in ClusterFuzz.

The Cloud Build steps upload the necessary artefacts, but from my understand of ClusterFuzz, a job needs to be created for each project+fuzzer+sanitizer combo, right? Is this step performed elsewhere?

Sorry for the support request in Issue form, I couldn't find any better venues.

**Comment by jonathanmetzman** [comment]
I think that's done [here](https://github.com/google/clusterfuzz/blob/dc9538f83b52a3a484e58c3076c602e1765308e1/src/appengine/handlers/cron/project_setup.py).
Also, the issue tracker is our preferred place for questions anyway.

**Comment by mykter** [comment]
Ah terrific, thank you. I didn't realize ClusterFuzz had oss-fuzz specific functionality.
