### ISSUE TITLE
encourage users to mention oss-fuzz bug in their commit messages

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#369]
We want to have a way to map bug fixes in user repos to oss-fuzz bugs.
We tend to encourage users to mention oss-fuzz bugs in commit logs, but we don't specify the format. 

Right now: 
  * libreoffice uses `ofz#547` (https://github.com/google/oss-fuzz/pull/358#issuecomment-278457232)
  * libarchive uses `OSS-Fuzz issue 538` (see e.g. https://github.com/libarchive/libarchive/commit/b3bd0b81a1a06909f766dea8be4072ef81de62b8)
  * ffmpeg uses something else (see e.g. https://github.com/FFmpeg/FFmpeg/commit/8c2ea3030af7b40a3c4275696fb5c76cdb80950a)
  * and so on. 

Note that there is no way we can enforce the usage of a particular syntax, even if we document it on 
every page of our documentation, so we'll probably have to understand various styles. 

Thoughts?

**Comment by oliverchang** [comment]
CF should already give commit range that contains the fix for each issue (e.g. https://clusterfuzz-external.appspot.com/revisions?job=libfuzzer_asan_freetype2&range=201702012009:201702021736). This only gives commit hashes though, and not the contents of the commits.

If we change this page to include commit messages also, I think it would be sufficient without us having to automate the understanding of various styles?

**Comment by mikea** [comment]
It is trivial to attach output of "git log -n 10" to srcmap.json. Will you be able to use it?

**Comment by oliverchang** [comment]
yep, I was going to suggest something very similar :) maybe something like:

```
{
  "/src/blah": {
     "type": "git",
     "rev": "...",
     "url": "...",
      "commit_log": [{
         "timestamp": timestamp,
         "author": "...",
         "message": "..."
      }]
   }
}
```

and maybe instead of 10 it could be all commits since the last uploaded build?

**Comment by Lekensteyn** [comment]
So what is the desired format? For Wireshark I have started using tags like this (from https://code.wireshark.org/review/21188):

    Link: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1149

with bug reports (e.g. https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=13606) linking to same thing.
What is the trigger for closing issues and marking them as public?

**Comment by oliverchang** [comment]
Any format that you feel is clear is fine. We don't parse this.

We automatically re-run testcases once a day to check if they're fixed and close them if that's the case. 30 days after the fix (or if the 90 day deadline comes) first, the issue is made public.
