### ISSUE TITLE
Split library image in two

### ISSUE THREAD

**Issue by vitalybuka** [google/oss-fuzz#37]
It should be one image for building a library and another image for building a fuzzer.
When I change fuzzer, I don't want to rebuild the library itself.

**Comment by inferno-chromium** [comment]
I don't understand this request, so assigning to Mike.

**Comment by mikea** [comment]
I don't think this is feasible. The reason we don't prebuild libfuzzer is because a) we may need to build it with different flags, b) we will have other fuzzer engines. Will close this as not feasible.
