### ISSUE TITLE
performance analyzer visualisations

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#371]
It would be nice if performance analyzer had a way to visualize logs as time series data in a graph (coverage growth, corpus growth, speed, when crashes happened etc)

**Comment by inferno-chromium** [comment]
Added it now 
https://oss-fuzz.com/v2/fuzzer-stats/by-time/2018-02-01/2018-02-19/fuzzer/libFuzzer_skia_image_filter_deserialize
