### ISSUE TITLE
CIFuzz shouldn't try to upload artifacts if it fails to build fuzz targets

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#3711]
Having taken a look at https://github.com/systemd/systemd/actions/runs/87051305 (where the annotations are a little confusing), I think the steps mentioned in https://google.github.io/oss-fuzz/getting-started/continuous-integration/#integrating-into-your-repository should be rearranged to avoid running the "Upload Crash" step if the "Build Fuzzers" step fails.

**Comment by jonathanmetzman** [comment]
Thanks for reporting this. I have to go offline very shortly, but I will take a look at this early next week.

**Comment by jonathanmetzman** [comment]
Hmm...Do you know how we might rearrange things to avoid this?
Putting the build in a different job probably works, I wonder if this affects performance though.

**Comment by evverx** [comment]
Judging by https://github.com/evverx/systemd/pull/1/checks?check_run_id=628512261, something like https://github.com/evverx/systemd/pull/1/files should suffice. I haven't tested it thoroughly yet though.

**Comment by evverx** [comment]
It looks like `if: steps.build.outcome == 'success' && steps.run.outcome != 'success'` doesn't work even though "steps.*.outcome" was supposed to cover use cases like this judging by https://github.com/actions/runner/pull/274/files. I might have messed something up though.

**Comment by evverx** [comment]
>  I might have messed something up though.

It appears I shouldn't have removed `failure()`. Without it the last step was just skipped. I've just updated the workflow and it seems to be working as expected:
https://github.com/systemd/systemd/runs/629125153?check_suite_focus=true
https://github.com/systemd/systemd/runs/629166021?check_suite_focus=true

I've just opened https://github.com/google/oss-fuzz/pull/3733
