### ISSUE TITLE
[oss-fuzz.com] Is it possible to use Google Account alternative e-mail addresses for auth?

### ISSUE THREAD

**Issue by darrenkenny** [google/oss-fuzz#3722]
Hi,

I have a Gmail account that has a secondary or alternative e-mail address that is my corporate account. 

The project.yaml file contains my corporate e-mail address - but I don't appear to have any access
to browse coverage data, etc.  at oss-fuzz.com.

Instead I get a message telling me that my GMail account has no access, and logging in with my corporate account address just ends up reporting that my GMail account doesn't have access too, since the GMail account is the primary address.

Does the authorisation system not take into account the alternative addresses of that Google account?

Does that mean that I would have to use my GMail address in the project.yaml file? Which would mean e-mails would get sent to my personal account instead of my corporate account, which is not what is desired.

Is there any chance that it could be expanded to also take into account the alternative e-mail addresses of a Google account?

Thanks,

Darren.

**Comment by inferno-chromium** [comment]
You should create a new google account with your company email address. Appengine api limits us from getting secondary email from the an existing gmail account, see https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication

With this, you still get to use company email address and use that when logging in.
