### ISSUE TITLE
[CIFuzz]: CIFuzz seems to be incompatible with forks

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#3731]
I opened a PR against a fork and CIFuzz failed there with
```
2020-04-29 05:10:21,600 - root - DEBUG - Stderr of command 'git clone https://github.com/systemd/systemd systemd' is Cloning into 'systemd'...
.
2020-04-29 05:10:21,845 - root - DEBUG - Stderr of command 'git fetch origin refs/pull/1/merge' is fatal: Couldn't find remote ref refs/pull/1/merge
.
Running: docker build -t gcr.io/oss-fuzz/systemd projects/systemd
2020-04-29 05:10:21,846 - root - ERROR - Can not check out requested state.
2020-04-29 05:10:21,846 - root - ERROR - Error building fuzzers for project systemd with pull request refs/pull/1/merge.
```
I'm not sure what to do about it but given that GitHub Actions are turned on by default everywhere I'd say it should probably be skipped if the target repository is different from what CIFuzz expects. On Travis CI something like `[[ "$TRAVIS_REPO_SLUG" = "systemd/systemd" ]]` is used to protect the scripts from forks.

**Comment by jonathanmetzman** [comment]
I'll see what I can about this.
One reason why CIFuzz breaks on forks is we do some custom logic to check out the pull request from the GitHub repo. If we replaced this with using GitHub's checkout action I think the problem would go away.

**Comment by evverx** [comment]
As a stopgap I've just opened https://github.com/systemd/systemd/pull/15842 where CIFuzz is skipped when the target repository isn't "systemd/systemd". Among other things I hope this should help people [paying for GitHub actions](https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions#about-billing-for-github-actions) not to waste the free minutes they have.

**Comment by jonathanmetzman** [comment]
Thanks, I'll probably document this in the meantime until CIFuzz works with forks.

**Comment by jonathanmetzman** [comment]
@evverx just checking, do we want it to work with forks? 
I assumed not because I imagine the typical workflow is:
1. fork
2. make changes and push locally
3. Open PR where CI gets run.

So disabling it on forks should be OK right?

**Comment by evverx** [comment]
This issue was originally reported to me by a fellow systemd contributor who works at a company where all PRs are reviewed internally by opening PRs against their private fork. Once they're approved there and it makes sense to bring the changes upstream they go through the usual workflow.

> So disabling it on forks should be OK right?

It should be OK. Though I think ideally it would be great if CIFuzz could be used to test forks that can be different from upstream projects a bit because of patches maintained locally.

> Just confirming it works on PRs opened from forks right? 

That's correct.

> It just fails if CIFuzz runs on commits to master and you are using a fork or open a PR on a fork right?

It fails every time PRs are opened against forks regardless of whether CIFuzz runs on commits to master or not.

**Comment by jonathanmetzman** [comment]
>It fails every time PRs are opened against forks regardless of whether CIFuzz runs on commits to master or not.

Right I expect this. My question wasn't clear but I meant if you work on a fork of systemd/systemd and then open a PR on systemd/systemd from that fork, that your PR (which is in the systemd/systemd repo) still works.

**Comment by jonathanmetzman** [comment]
I need to retest this at some point. I think it should be compatible with forks now.

**Comment by evverx** [comment]
I've just opened a PR against my fork of systemd: https://github.com/evverx/systemd/pull/4. CIFuzz didn't fail there but I'm not sure what exactly it built there:
```
Successfully tagged gcr.io/oss-fuzz/systemd:latest
2021-03-19 17:53:39,880 - root - DEBUG - Stderr of command 'git clone https://github.com/systemd/systemd systemd' is Cloning into 'systemd'...
.
2021-03-19 17:53:40,880 - root - DEBUG - Stderr of command 'git fetch origin refs/pull/4/merge' is fatal: Couldn't find remote ref refs/pull/4/merge
.
2021-03-19 17:53:40,880 - root - ERROR - Can not check out requested state refs/pull/4/merge. Using current repo state
```

**Comment by evverx** [comment]
It couldn't trigger a memory leak introduced in that PR so it seems CIFuzz just fell back to the main branch of the systemd repository.

Below are some other logs that seem to be relevant:
```
2021-03-19 18:29:47,523 - root - DEBUG - Stderr of command 'git fetch origin main:main' is fatal: Refusing to fetch into current branch refs/heads/main of non-bare repository
.
2021-03-19 18:29:47,524 - root - DEBUG - Diffing against base_ref: main.
2021-03-19 18:29:47,527 - root - INFO - Diffing against main.
2021-03-19 18:29:47,741 - root - ERROR - No diff was found.
2021-03-19 18:29:47,741 - root - INFO - No files changed compared to HEAD.
```

**Comment by jonathanmetzman** [comment]
> It couldn't trigger a memory leak introduced in that PR so it seems CIFuzz just fell back to the main branch of the systemd repository.
> 
> Below are some other logs that seem to be relevant:
> 
> ```
> 2021-03-19 18:29:47,523 - root - DEBUG - Stderr of command 'git fetch origin main:main' is fatal: Refusing to fetch into current branch refs/heads/main of non-bare repository
> .
> 2021-03-19 18:29:47,524 - root - DEBUG - Diffing against base_ref: main.
> 2021-03-19 18:29:47,527 - root - INFO - Diffing against main.
> 2021-03-19 18:29:47,741 - root - ERROR - No diff was found.
> 2021-03-19 18:29:47,741 - root - INFO - No files changed compared to HEAD.
> ```

Lol. Thanks for testing this for me. I think I can fix this somewhat easily. I can try next week but it's not a super high priority.

**Comment by ailin-nemui** [comment]
hi, confusingly CI-Fuzz checks out the _wrong_ PR on forks, I guess this is related to this bug report?

If I open PR 1 on my fork, it instead builds PR 1 of the original repo.

**Comment by hartwork** [comment]
> hi, confusingly CI-Fuzz checks out the _wrong_ PR on forks, I guess this is related to this bug report?
> 
> If I open PR 1 on my fork, it instead builds PR 1 of the original repo.

I would like to second that as unfortunate and unexpected. Please re-open this issue as a feature request.

**Comment by evverx** [comment]
I'm not sure it was a feature request. I think it's a bug :-)

If it's really necessary ClusterFuzzLite can be used to fuzz forks. That's what systemd does to test its stable branches maintained in a separate repository.

**Comment by hartwork** [comment]
> I'm not sure it was a feature request. I think it's a bug :-)

I can see why you would say that. From a user's perspective I fully agree: it's a bug. Especially when it doesn't fail and just fuzzes the wrong code.

> If it's really necessary ClusterFuzzLite can be used to fuzz forks. That's what systemd does to test its stable branches maintained in a separate repository.

That's an interesting idea.

**Comment by evverx** [comment]
I'll just leave links to https://github.com/google/oss-fuzz/issues/7479 and https://github.com/libjpeg-turbo/libjpeg-turbo/commit/5c8cac97c0c130f287e67d9dafc3e4928110f478 here for future reference.
