### ISSUE TITLE
CIFuzz attempts to fetch a non-existent remote in some recent PRs

### ISSUE THREAD

**Issue by mrc0mmand** [google/oss-fuzz#3732]
After the fail reported in https://github.com/google/oss-fuzz/issues/3727 was resolved, all rescheduled CIFuzz jobs in systemd/systemd repository die because they try to fetch a non-existent remote:

```
Successfully built 65d05ead6f6a
Successfully tagged gcr.io/oss-fuzz/systemd:latest
2020-04-29 07:54:41,107 - root - DEBUG - Stderr of command 'git clone https://github.com/systemd/systemd systemd' is Cloning into 'systemd'...
.
2020-04-29 07:54:41,339 - root - DEBUG - Stderr of command 'git fetch origin refs/heads/more-specifiers' is fatal: Couldn't find remote ref refs/heads/more-specifiers
.
2020-04-29 07:54:41,339 - root - ERROR - Can not check out requested state.
2020-04-29 07:54:41,339 - root - ERROR - Error building fuzzers for project systemd with pull request refs/heads/more-specifiers.
```

See:
* https://pipelines.actions.githubusercontent.com/fW9YnoEKBASdi1Tl6Qk8OxwlrJgIZvKOJ6c0FMLt24imZ5L13v/_apis/pipelines/1/runs/92/signedlogcontent/3?urlExpires=2020-04-29T08%3A04%3A28.0892001Z&urlSigningMethod=HMACV1&urlSignature=Cy6Jcr2%2B5gslj1UmvktrVBtYwcDtvuRDgK1Ev%2F%2BKbqk%3D (https://github.com/systemd/systemd/pull/15626)
* https://pipelines.actions.githubusercontent.com/fW9YnoEKBASdi1Tl6Qk8OxwlrJgIZvKOJ6c0FMLt24imZ5L13v/_apis/pipelines/1/runs/93/signedlogcontent/3?urlExpires=2020-04-29T08%3A04%3A54.8552047Z&urlSigningMethod=HMACV1&urlSignature=L1JTkY2Z%2BbqW8xjfvMNmB1DUH74gAsku1oKcU9LWgJA%3D (https://github.com/systemd/systemd/pull/15627/)

On passing PRs the remote is (as expected): `refs/pull/xxx/merge`
```
Successfully built 0a607eaf0caf
Successfully tagged gcr.io/oss-fuzz/systemd:latest
2020-04-29 02:00:55,992 - root - DEBUG - Stderr of command 'git clone https://github.com/systemd/systemd systemd' is Cloning into 'systemd'...
.
2020-04-29 02:00:56,703 - root - DEBUG - Stderr of command 'git fetch origin refs/pull/15630/merge' is From https://github.com/systemd/systemd
 * branch            refs/pull/15630/merge -> FETCH_HEAD
.
2020-04-29 02:00:56,975 - root - DEBUG - Stderr of command 'git checkout -f FETCH_HEAD' is Note: checking out 'FETCH_HEAD'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d164be2... Merge 660e2ed25b6a8c86d953ed168575771cf7ed9d8c into 76410e9849cf5f7d1914734589a356b0b8ed5f7c
```

**Comment by evverx** [comment]
It seems https://github.community/t5/GitHub-Actions/GITHUB-REF-is-inconsistent/td-p/48129 might be relevant.

**Comment by jonathanmetzman** [comment]
https://pipelines.actions.githubusercontent.com/fW9YnoEKBASdi1Tl6Qk8OxwlrJgIZvKOJ6c0FMLt24imZ5L13v/_apis/pipelines/1/runs/92/signedlogcontent/3?urlExpires=2020-04-29T08%3A04%3A28.0892001Z&urlSigningMethod=HMACV1&urlSignature=Cy6Jcr2%2B5gslj1UmvktrVBtYwcDtvuRDgK1Ev%2F%2BKbqk%3D ([systemd/systemd#15626](https://github.com/systemd/systemd/pull/15626))
> * https://pipelines.actions.githubusercontent.com/fW9YnoEKBASdi1Tl6Qk8OxwlrJgIZvKOJ6c0FMLt24imZ5L13v/_apis/pipelines/1/runs/93/signedlogcontent/3?urlExpires=2020-04-29T08%3A04%3A54.8552047Z&urlSigningMethod=HMACV1&urlSignature=L1JTkY2Z%2BbqW8xjfvMNmB1DUH74gAsku1oKcU9LWgJA%3D ([systemd/systemd#15627](https://github.com/systemd/systemd/pull/15627))

Thanks for this report. I'll look into this.
Could you link to the PRs? These links expired unfortunately.
Is it just rerun actions that causes it to fail or does pushing do the same thing? What about opening new Pull Requests?

**Comment by mrc0mmand** [comment]
The PRs are https://github.com/systemd/systemd/pull/15626 and https://github.com/systemd/systemd/pull/15627, respectively, but the second PR was force-pushed since then, which seems to *fix* the issue. And it affects only rerun actions from what I've seen so far, so it seems to be consistent with the report @evverx mentioned.
