### ISSUE TITLE
Issue building project with Bazel

### ISSUE THREAD

**Issue by matt-kwong** [google/oss-fuzz#374]
For reference: #373

When I run `python infra/helper.py build_fuzzers grpc`, I get the following issue:

```
Compiling libFuzzer to /usr/lib/libFuzzingEngine.a ...ar: creating /usr/lib/libFuzzingEngine.a
 done.
CC=clang
CXX=clang++
CFLAGS=-fno-omit-frame-pointer -gline-tables-only -fsanitize=address -fsanitize-coverage=trace-pc-guard,trace-cmp
CXXFLAGS=-fno-omit-frame-pointer -gline-tables-only -fsanitize=address -fsanitize-coverage=trace-pc-guard,trace-cmp -stdlib=libc++
---------------------------------------------------------------
Adding user `builder' ...
Adding new group `builder' (1007) ...
Adding new user `builder' (1007) with group `builder' ...
Not creating home directory `/home/builder'.
+ FUZZER_FILES='test/core/end2end/fuzzers/api_fuzzer.c test/core/json/fuzzer.c test/core/client_channel/uri_fuzzer_test.c test/core/http/request_fuzzer.c test/core/http/response_fuzzer.c test/core/nanopb/fuzzer_response.c test/core/nanopb/fuzzer_serverlist.c test/core/slice/percent_decode_fuzzer.c test/core/slice/percent_encode_fuzzer.c test/core/transport/chttp2/hpack_parser_fuzzer_test.c test/core/end2end/fuzzers/client_fuzzer.c test/core/end2end/fuzzers/server_fuzzer.c test/core/security/ssl_server_fuzzer.c '
+ FUZZER_LIBRARIES='bazel-bin/test/core/util/*.a bazel-bin/test/core/end2end/*.a bazel-bin/external/submodule_boringssl/*.so bazel-bin/external/submodule_zlib/_objs/z/external/submodule_zlib/*.o bazel-bin/third_party/nanopb/*.so bazel-bin/*.a '
+ bazel
Error: mkdir('/home/builder/.cache/bazel/_bazel_builder'): Permission denied
fuzzers build failed.
```

When I run `python infra/helper.py shell grpc` and then `compile`, gRPC is built using Bazel and the binaries are sucessfully sent to `build/out/grpc`. It seems like a Docker issue with the permissions of the 'builder' user/group. Any suggestions for troubleshoooting this?

**Comment by kcc** [comment]
in https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile
we have  
adduser -u $BUILD_UID --disabled-password **--no-create-home** --gecos '' builder

bazel apparently needs to write stuff into $HOME, but $HOME does not exist. 
@mikea is OOO. Anyone else knows why we have **--no-create-home**?

**Comment by kcc** [comment]
And yes, removing --no-create-home from infra/base-images/base-builder/compile helps. 
@oliverchang @inferno-chromium any idea what may break if we remove --no-create-home?

**Comment by inferno-chromium** [comment]
Should be ok, i removed it. Lets see if the build fixes.

**Comment by inferno-chromium** [comment]
Current build failure here - https://oss-fuzz-build-logs.storage.googleapis.com/build_logs/grpc/latest.txt.

Need to fix linking of dependent libraries to happen statically.
https://github.com/google/oss-fuzz/blob/master/docs/fuzzer_environment.md

**Comment by kcc** [comment]
Fixed, righ?

**Comment by matt-kwong** [comment]
Yes for this specific issue
