### ISSUE TITLE
close_fd_mask=3 not working on h2o fuzzers

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#376]
https://storage.cloud.google.com/h2o-logs.clusterfuzz-external.appspot.com/libFuzzer_h2o_h2o-fuzzer-http1/libfuzzer_asan_h2o/2017-02-11/08%3A11%3A28%3A744767.txt?_ga=1.157022194.837344110.1463372149

Kostya, any clues ?

**Comment by kcc** [comment]
Can't reproduce. 
When running manually inside docker, I see that -close_fd_mask=3 removes the logging. 
Same wren running `python infra/helper.py --nopull run_fuzzer h2o h2o-fuzzer-http1`
Do we still see this?

**Comment by inferno-chromium** [comment]
Can't reproduce on local as well, but still showing on CF whose command has -close_fd_mask=3.
https://oss-fuzz.com/v2/performance-report/libFuzzer_h2o_h2o-fuzzer-http1/libfuzzer_asan_h2o/latest
https://oss-fuzz.com/gcsviewer?path=%2Fh2o-logs.clusterfuzz-external.appspot.com%2FlibFuzzer_h2o_h2o-fuzzer-http1%2Flibfuzzer_asan_h2o%2F2017-02-14%2F11%3A02%3A48%3A083930.txt

@oliverchang - any clues ?

**Comment by inferno-chromium** [comment]
No longer see it, maybe just needed to wait a day or two.
