### ISSUE TITLE
Getting 403s when selecting a recently added fuzzer

### ISSUE THREAD

**Issue by ttaubert** [google/oss-fuzz#377]
On Friday, we added the tls-client fuzzer. The fuzzer is working fine and it's showing up in the overview table, but if I click it to see statistics per day I always get a 403. IIRC we had the same happening with other fuzzers after we added them. I wonder if this is related to it being new?

**Comment by ttaubert** [comment]
Forgot to mention that I'm talking about the ClusterFuzz UI.

**Comment by oliverchang** [comment]
Could you please provide the exact link that's giving you the 403?

**Comment by ttaubert** [comment]
https://clusterfuzz-external.appspot.com/v2/fuzzer-stats/by-day/2017-02-06/2017-02-12/fuzzer/libFuzzer_nss_tls-client/job/

**Comment by oliverchang** [comment]
Does https://clusterfuzz-external.appspot.com/v2/fuzzer-stats/by-day/2017-02-06/2017-02-12/fuzzer/libFuzzer_nss_tls-client/job/libfuzzer_asan_nss work?

Selecting "all" jobs doesn't right now for external folks, but we should fix this soon.

**Comment by oliverchang** [comment]
Also, normally when someone clicks on per-day links for fuzzers it should keep the job association so most users shouldn't run the issue of 'All' jobs, but it looks like the issue we encountered in https://github.com/google/oss-fuzz/issues/312#issuecomment-277770756 may be happening again..

**Comment by ttaubert** [comment]
> Does https://clusterfuzz-external.appspot.com/v2/fuzzer-stats/by-day/2017-02-06/2017-02-12/fuzzer/libFuzzer_nss_tls-client/job/libfuzzer_asan_nss work?

Yes, that works for me.

**Comment by oliverchang** [comment]
Selecting 'All' jobs should work now.

**Comment by ttaubert** [comment]
Thanks!
