### ISSUE TITLE
Enabling experimental features

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#378]
We should have a way to experimentally turn on certain features for projects (e.g. MSan) but not file any bugs before we're sure we don't get flooded with false positives or noise.

**Comment by inferno-chromium** [comment]
We support EXPERIMENTAL=True in Job type, then we dont autofile bugs. But how do we remove the experimental flag since cron keeping overwriting the job definitions.

**Comment by oliverchang** [comment]
One idea:

- We keep a list of "features" that we consider experimental (e.g. sanitizers: msan)
- We keep some state on CF side that for each project maps whether if a particular feature is kept as experimental. This is set by default, and the autosetup cron can use this to determine whether or not to set EXPERIMENTAL=True
- Either manually, or automatically (e.g. crash count is below some threshold after some time) we can promote experimental features.

**Comment by oliverchang** [comment]
Alternatively we can make this completely manual and just specify:

```
sanitizers:
  - msan_experimental
```

instead of 

```
sanitizers:
  - msan
```

**Comment by inferno-chromium** [comment]
will this only be for sanitizers ? for sanitizers, msan_experimental sounds good. and we have afl in pipeline, so that will work too. for others, we can later implement same logic.

**Comment by oliverchang** [comment]
Yeah, thinking about this a bit more just manually specifying an _experimental suffix to options seems like the way to go for now.

We'll probably end up needing to do some manual work to decide whether to file bugs for a feature anyway and going with a potentially over-engineered solution probably won't give us that much value.

**Comment by mikea** [comment]
How about:

```yaml
sanitizers:
  - msan:
      experimental: true
```

This way we'll be able to specify other parameters as well.

**Comment by inferno-chromium** [comment]
+1, i like Mike's comment. String management is always annoying.

**Comment by oliverchang** [comment]
I considered doing this, but felt that it wasn't worth the complication of
dealing with different types (i.e. sanitizers could either be a list of
strings or a list of dictionaries). What other parameters were you thinking
of?

**Comment by mikea** [comment]
Custom set of undefined sanitizers is something that immediately comes to mind.
