### ISSUE TITLE
[FFmpeg] reduced coverage at may 1st

### ISSUE THREAD

**Issue by michaelni** [google/oss-fuzz#3788]
On the 1st may coverage of libavformat droped by alot
see:
https://storage.googleapis.com/oss-fuzz-coverage/ffmpeg/reports/20200430/linux/src/ffmpeg/report.html
vs.
https://storage.googleapis.com/oss-fuzz-coverage/ffmpeg/reports/20200501/linux/src/ffmpeg/report.html

i looked at the oss-fuzz gitlog and found at the time the commit below
(i do not know how to reproduce this kind of seed / cloud issues so i
 do not know if this is related but it smells a bit like it could be)
If its an issue on teh FFmpeg side, please explain what we are doing wrong
thanks!

commit 6b79797ed31e40c490f7c2ff92f110e84636178a
Author: Oliver Chang <oliverchang@users.noreply.github.com>
Date:   Thu Apr 30 15:32:17 2020 +1000

    helper: Clean /work as well if --clean is specified. (#3738)

**Comment by inferno-chromium** [comment]
That commit cannot be related to this as it is used for local reproduction and not used anywhere on ClusterFuzz. We dont have bandwidth to debug what is going wrong here but i can give you some ideas to start. first try to find which fuzzer hits that code, then go to https://oss-fuzz.com/fuzzer-stats?group_by=by-fuzzer&date_start=2020-05-06&date_end=2020-05-12&fuzzer=libFuzzer&job=libfuzzer_asan_ffmpeg&project=ffmpeg, find that fuzzer and look at day view, see if corpus changed, or maybe that fuzzer is hitting into some issues. if a fuzzer is crashing a lot, maybe we lose important corpus items. try closing new regression bugs and then usually it should improve.

**Comment by inferno-chromium** [comment]
Fixed, i think this was a issue with dead bots which we fixed recently, now it is ok,
