### ISSUE TITLE
Unusual timing around comments of bugs opened to public

### ISSUE THREAD

**Issue by alexcrichton** [google/oss-fuzz#3789]
We have an [issue on wasmtime](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20605) which has recently gone public. This is totally fine by us, it's something slow in our runtime that we haven't gotten around to fixing yet. I wanted to raise a point though that seemed a bit odd, however, in case y'all are intersted in the auto-process for opening bugs to the public.

[We were notified](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20605#c3) on 2020-05-09 that the bug would be made public in 7 days, but then [only two days later](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20605#c4) the bug was made public. Again this is totally fine by us, it's not something sensitive we need redacted. It did seem a bit odd though that 2 days after our 7 day warning action was taken!

**Comment by inferno-chromium** [comment]
@alexcrichton - i think you read the date wrong. the comment https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20605#c1 was made on Feb 9 (not May 9). And the bug was disclosed on the date mentioned - Disclosure-2020-05-11 is the label.

**Comment by alexcrichton** [comment]
Oh sorry I don't mean to say that the disclosure date was inaccurate, mostly just that the comment made on 2020-05-09 saying:

> This bug is approaching its deadline for being fixed, and will be automatically derestricted within 7 days. If a fix is planned within 2 weeks after the deadline has passed, a grace extension can be granted.

was misleading because the derestriction happened 2 days later, not 7 days later.

**Comment by inferno-chromium** [comment]
ah ok, gotcha, yes that is a bug.

**Comment by inferno-chromium** [comment]
@mbarbella-chromium - can you please fix this sheriffbot issue and deploy.

**Comment by jonathanmetzman** [comment]
@mbarbella-chromium this is fixed right?

**Comment by jonathanmetzman** [comment]
I think this was fixed. See [ this bug](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=28810&colspec=ID%20Type%20Component%20Status%20Proj%20Reported%20Owner%20Summary%20Modified&sort=-modified) for example.
