### ISSUE TITLE
[CIFuzz]: consider making reporting of bugs in a new target optional.

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#3815]
@evverx [wrote](https://github.com/google/oss-fuzz/issues/3813#issuecomment-628958552)

> As an aside, I wonder if it's safe to assume that contributors adding new fuzz targets are generally willing to fix bugs (or wait for someone else to fix them) before their PRs can be merged. It would probably make sense to somehow allow projects to choose whether to ignore bugs found by new fuzz targets or not (at least until all "shallow" bugs have been reported on Monorail).

**Comment by jonathanmetzman** [comment]
I think it's probably fine if the PR the fuzzer is introduced on is red even if it's not ideal. 
I think it is worse though that CIFuzz will continue reporting this bug until OSS-Fuzz produces a build of the fuzzer.

**Comment by evverx** [comment]
CIFuzz runs fuzz targets one by one so it appears one faulty fuzz target (depending on how it's called and how `os.walk` works) can in theory prevent the other fuzz targets from running making it possible for new bugs to sneak in even though they can be easily caught. As an alternative I think another option would be not to fail as soon as the first target fails.

**Comment by evverx** [comment]
More generally I think it would be great if there was a way to ignore known issues and at the same time keep discovering new bugs.

**Comment by jonathanmetzman** [comment]
> CIFuzz runs fuzz targets one by one so it appears one faulty fuzz target (depending on how it's called and how `os.walk` works) can in theory prevent the other fuzz targets from running making it possible for new bugs to sneak in even though they can be easily caught. As an alternative I think another option would be not to fail as soon as the first target fails.

Yep. I generally think tools should report as many errors as possible, but here I decided not to because I'd like there to be faster feedback in what I suspect is the more common case.
Otherwise CIFuzz will always take a fixed amount of time.

>More generally I think it would be great if there was a way to ignore known issues and at the same time keep discovering new bugs.

It might have to be on a per-fuzz target basis since CIFuzz isn't doing any parsing of errors, it just uses return codes. Maybe this can be changed if the bisection code has good support for identifying bugs.
