### ISSUE TITLE
support bazel -- pass all flags to bazel in a clean way

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#383]
@matt-kwong - See https://github.com/google/oss-fuzz/pull/380#issuecomment-279645886 and followup comments.

**Comment by kcc** [comment]
FTR, I was able to build reasonable binaries by adding this to the bazel command: 
```
--copt=-g  --strip=never  --copt=-fsanitize-coverage=trace-pc-guard  --copt=-fsanitize=address  --linkopt=-fsanitize=address
```

This is *not* the way we want this to be done, because we want to control what options are used via CXXFLAGS/etc. 

Also, by default bazel uses it's own compiler, which currently seems to be pretty good, 
but in OSS-Fuzz we use only our own toolchain, at least now... 
Still looking...

**Comment by inferno-chromium** [comment]
@kcc - why can't be use $COVERAGE_FLAGS and $SANITIZER_FLAGS in the command you cited. those env vars should be set.

**Comment by kcc** [comment]
It's not trivial, but possible (e.g. --copt= consumes only a single flag, can't have spaces there). 
What worries me more is the compiler (bazel uses it's own)

**Comment by kcc** [comment]
Wait a sec.... 
I am running 'bazel ... -s' and I can see that it invokes `/usr/local/bin/clang`, which is exactly what we need. 
Woohoo!

**Comment by kcc** [comment]
So, we wither need to parse CXXFLAGS and translate them into --copt and --linkopt bazel flags,
or provide OSS_FUZZ_BAZEL_FLAGS, or ask blaze to honor CXXFLAGS (unlikely, but let me check)

**Comment by kcc** [comment]
Ok... The above ugly hack seems to work, let's see how it goes on the bot. 
We will need to have a cleaner bazel support, but it will take time. 
Renaming this issue into 'support bazel'

**Comment by kcc** [comment]
The above change disables `sanitize=vptr` in an ugly way.
The problem is that bazel seems to be using clang (instead of clang++) to link code built
with `-sanitize=vptr` and so we were getting linker errors: 
```
src/compiler/objective_c_plugin.cc:0: error: undefined reference to '__ubsan_vptr_type_cache'
```

This also will need be be fixed cleaner.

**Comment by Dor1s** [comment]
Current version works fine with ASan:

```
<...>
Done 133121 runs in 2951 second(s)
stat::number_of_executed_units: 133121
stat::average_exec_per_sec:     45
stat::new_units_added:          25
stat::slowest_unit_time_sec:    0
stat::peak_rss_mb:              92
<...>
Done 169747 runs in 2951 second(s)
stat::number_of_executed_units: 169747
stat::average_exec_per_sec:     57
stat::new_units_added:          705
stat::slowest_unit_time_sec:    0
stat::peak_rss_mb:              87
cf::fuzzing_strategies: corpus_subset_2
```

UBSan always crashes on https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=589

**Comment by kcc** [comment]
>  UBSan always crashes ... 

This only affects  grpc_api_fuzzer, the other targets run fine.
grpc_ssl_server_fuzzer fails at startup for yet another reason. https://github.com/google/oss-fuzz/pull/373#issuecomment-279862430

**Comment by inferno-chromium** [comment]
Lets track this in https://github.com/google/oss-fuzz/issues/4069
