### ISSUE TITLE
CIFuzz seems to be failing with "FUZZING_LANGUAGE: unbound variable"

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#3838]
```sh
Finished Step #3
Starting Step #4
Step #4: Already have image: gcr.io/oss-fuzz/systemd
Step #4: ---------------------------------------------------------------
Step #4: ar: creating /usr/lib/libFuzzingEngine.a
Step #4: Compiling libFuzzer to /usr/lib/libFuzzingEngine.a...  done.
Step #4: /usr/local/bin/compile: line 66: FUZZING_LANGUAGE: unbound variable
```
Assuming https://github.com/google/oss-fuzz/pull/3837 was supposed to fix this, it would be great if the OSS-Fuzz images were updated because [CIFuzz has started failing as well](https://github.com/systemd/systemd/actions)

![Screenshot 2020-05-18 at 10 59 11](https://user-images.githubusercontent.com/10195800/82188495-a1136100-98f6-11ea-8d7b-51e544cb62ad.png)

**Comment by evverx** [comment]
It would also be great if it would be possible to just restart all those failed jobs once it's fixed without asking contributors to force-push their PRs once again: https://github.com/google/oss-fuzz/issues/3732.

**Comment by evverx** [comment]
Now that the OSS-Fuzz images are rebuilt, the latest build seems to have succeeded. CIFuzz keeps failing though because `build_fuzzers` doesn't pass `FUZZING_LANGUAGE` to `compile` in `infra/cifuzz/cifuzz.py`. @jonathanmetzman could you take a look?

**Comment by evverx** [comment]
In the meantime, I turned off GitHub actions for the systemd repository.

**Comment by guidovranken** [comment]
All coverage builds are failing too.

**Comment by inferno-chromium** [comment]
@guidovranken - really sorry about my mess, i thought FUZZING_LANGUAGE support was properly added, should never rely on things. coverage builds fixed in https://github.com/google/oss-fuzz/pull/3843. retriggering all builds now.

**Comment by guidovranken** [comment]
No worries, just wanted to let you know.

**Comment by inferno-chromium** [comment]
@evverx - can you check if you are unblocked on CIFuzz / it started working ?

**Comment by evverx** [comment]
To judge from https://github.com/google/oss-fuzz/issues/3842#issuecomment-630290041, the issue is gone.
