### ISSUE TITLE
oss-fuzz badge : coverage failing for Grok project

### ISSUE THREAD

**Issue by boxerab** [google/oss-fuzz#3841]
Hello!
I just noticed that my oss-fuzz badge is reporting coverage failing.

https://github.com/GrokImageCompression/grok

What does this mean, and how to fix ?

Btw, I recently added this badge to my project:

```
[badge-oss-fuzz]: https://oss-fuzz-build-logs.storage.googleapis.com/badges/grok.svg "Build Status"
[link-oss-fuzz]: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#grok "Build Status"
```

Thanks!

**Comment by inferno-chromium** [comment]
We have pushed a fix (https://github.com/google/oss-fuzz/pull/3843), and triggered rebuilds, things should be fixed soon (like an hour or so).

**Comment by inferno-chromium** [comment]
badge is updated, unsure why github is showing stale image for
https://oss-fuzz-build-logs.storage.googleapis.com/badges/grok.svg

Can you update your badge to:
[![Fuzzing Status](https://oss-fuzz-build-logs.storage.googleapis.com/badges/grok.svg)](https://bugs.chromium.org/p/oss-fuzz/issues/list?sort=-opened&can=1&q=proj:grok)

**Comment by inferno-chromium** [comment]
github has some caching on badges, i hope it updates in a few hours - https://github.com/sbts/github-badge-cache-buster

**Comment by boxerab** [comment]
Can you update your badge to:
> [image: Fuzzing Status]
> <https://bugs.chromium.org/p/oss-fuzz/issues/list?sort=-opened&can=1&q=proj:grok>
>
>
Thanks for the fuzz status link - I have updated it on Github.
