### ISSUE TITLE
Is running fuzz targets on aarch64 supported?

### ISSUE THREAD

**Issue by fitzgen** [google/oss-fuzz#3854]
I searched the docs and found no references to aarch64, but did see a couple commits/issues mentioning it, and I wasn't able to determine whether running fuzz targets on aarch64 is supported or not. And if it is supported, it isn't clear to me how to set it up.

We recently added aarch64 support to Wasmtime and its compiler, Cranelift, and would love to fuzz the new compiler backend and runtime.

Thanks for your time!

cc @bnjbvr

**Comment by jonathanmetzman** [comment]
Unfortunately it isn't supported right now.
Google Cloud doesn't have ARM machines and until that happens, it's unlikely we can get real support for ARM. There were some early plans to use QEMU for emulation but no one has any plans to implement this right now.

**Comment by fitzgen** [comment]
Ok, thanks for the info!

**Comment by jonathanmetzman** [comment]
There's been some progress on this issue. I've added some details on #1754.
