### ISSUE TITLE
False positives in Clang's MSAN since latest update

### ISSUE THREAD

**Issue by bluca** [google/oss-fuzz#3855]
Since the latest update of Clang, the following very simple snippet (and many, many more different and seemingly normal usage of std::string) triggers an uninitialised access error:

```
    const char foo[] = "foo";
    std::string bar (foo);
    if (bar.empty ())
        printf("wat\n");
```

```
artifact_prefix='./'; Test unit written to ./crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64: 
test_connect_fuzzer:
BAD BUILD: /tmp/not-out/test_connect_fuzzer seems to have either startup crash or exit:
INFO: Seed: 1337
INFO: Loaded 1 modules   (17935 inline 8-bit counters): 17935 [0xc2ba48, 0xc30057), 
INFO: Loaded 1 PC tables (17935 PCs): 17935 [0xc30058,0xc76148), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
==94==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x524083 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::size() const /usr/local/bin/../include/c++/v1/string:947:17
    #1 0x522ce9 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::empty() const /usr/local/bin/../include/c++/v1/string:967:42
    #2 0x5228dd in LLVMFuzzerTestOneInput /src/libzmq/tests/test_connect_fuzzer.cpp:45:13
    #3 0x45a141 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:556:15
    #4 0x45bc66 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:743:3
    #5 0x45c0d9 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:794:3
    #6 0x44b3ae in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:826:6
    #7 0x473b82 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
    #8 0x7f145d8ff82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #9 0x41fab8 in _start (/tmp/not-out/test_connect_fuzzer+0x41fab8)
DEDUP_TOKEN: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::size() const--std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::empty() const--LLVMFuzzerTestOneInput
  Uninitialized value was created by an allocation of 'bar' in the stack frame of function 'LLVMFuzzerTestOneInput'
    #0 0x5227f0 in LLVMFuzzerTestOneInput /src/libzmq/tests/test_connect_fuzzer.cpp:42
DEDUP_TOKEN: LLVMFuzzerTestOneInput
SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/local/bin/../include/c++/v1/string:947:17 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::size() const
Unique heap origins: 12
Stack depot allocated bytes: 712
Unique origin histories: 1
History depot allocated bytes: 24
Exiting
MS: 0 ; base unit: 0000000000000000000000000000000000000000
```

Is it possible to revert Clang to a previous, working version?

https://github.com/bluca/libzmq/blob/793617dc1770faa87f1e45434f3e686ebfc97aa6/tests/test_connect_fuzzer.cpp#L43
https://travis-ci.com/github/bluca/oss-fuzz/jobs/337522048

**Comment by inferno-chromium** [comment]
Can you please file a bug in https://github.com/google/sanitizers/issues
@eugenis @kcc fyi

**Comment by bluca** [comment]
https://github.com/google/sanitizers/issues/1252

**Comment by kcc** [comment]
Is the libc++ instrumented with msan in your reproducer?

**Comment by bluca** [comment]
it's from the oss-fuzz own CI build

**Comment by jonathanmetzman** [comment]
> it's from the oss-fuzz own CI build

Right, but I suspect you are doing something "wrong' in your build process that is failing now.
If I do bad_build_check on a new build of skcms and then do `helper.py bad_build_check skcms --sanitizer memory` there is no failure. So I don't think it is an msan wide issue.

**Comment by bluca** [comment]
Ok, what is the "right" thing then? The build script didn't change much. It's taking CXX/CC and relative flags from the env.

**Comment by bluca** [comment]
https://github.com/google/oss-fuzz/blob/master/projects/libzmq/build.sh

**Comment by bluca** [comment]
mmh does the CI define LDFLAGS only sometimes, perhaps? I remember getting an error from bash, complaining that LDFLAGS=$LDFLAGS ... referenced an uninitialized variable or something along those line

**Comment by jonathanmetzman** [comment]
I see the last successful build for this project was on April 27th. On the 28th: https://github.com/google/oss-fuzz/commit/4014d4d55a4024e32b27c7dc224a9c42a76a5e42#diff-e91420bb9cf1d4c1bc0554a8bee6f2a4 was landed. I would guess that if you are using `LDFLAGS` then you are not linking the fuzz targets using `$CXX` and `$CXXFLAGS` like you did previously which could mean you aren't linking against libc++.

**Comment by bluca** [comment]
The build log shows all linking happens with -std=libc++
Is there some undocumented magic flag to use? Some specific library path to add? Some other linker flag?

**Comment by bluca** [comment]
Verbose linking command from the ci log:

```
libtool: link: clang++ -std=c++11 -pedantic -Werror -Wall -Wno-long-long -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=memory -fsanitize-memory-track-origins -fsanitize=fuzzer-no-link -stdlib=libc++ -I/tmp/zmq_install_dir/usr/local/include -Wno-atomic-alignment -Wno-tautological-constant-compare -pthread -o tests/test_z85_decode_fuzzer tests/tests_test_z85_decode_fuzzer-test_z85_decode_fuzzer.o -fsanitize=fuzzer  -L/tmp/zmq_install_dir/usr/local/lib ./tests/libtestutil.a ./external/unity/libunity.a ./src/.libs/libzmq.a -L/usr/local/lib /tmp/zmq_install_dir/usr/local/lib/libsodium.a -lrt -lpthread -pthread
```

Anything obvious missing?

**Comment by jonathanmetzman** [comment]
>Is there some undocumented magic flag to use? Some specific library path to add? Some other linker flag?
Not that I know of. 
I would look at what's changed to debug this. In the working build we have:
```
clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=memory -fsanitize-memory-track-origins -fsanitize=fuzzer-no-link -stdlib=libc++ -std=c++11 -I. /src/decode_fuzzer.cc -fsanitize=fuzzer ./src/.libs/libzmq.a -o /workspace/out/memory/decode_fuzzer
```
In the failing build:
```
```

**Comment by jonathanmetzman** [comment]
One difference I notice is `-L/usr/local/lib`. That location contains libc++.a [but in msan builds we copy libc++.a to /usr/lib](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile#L43).

**Comment by jonathanmetzman** [comment]
In any case, if MSAN doesn't work you can just disable it.

**Comment by bluca** [comment]
-L/usr/local/lib was the culprit yes, and autoconf added it automatically (because /usr/local is the default install prefix). Overriding the prefix solves the issue.
Perhaps it would be good to avoid installing incompatible libraries in /usr/local, or at least add a warning somewhere in the documentation.

**Comment by bluca** [comment]
@jonathanmetzman is there any special sauce for glibc as well? Or is CC=clang enough?

**Comment by bluca** [comment]
WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libc.so.6

that doesn't look good...

**Comment by bluca** [comment]
Changed the offending "uninitialised" buffer to be allocated with calloc just to be sure, and yet:

```
Uninitialized bytes in __interceptor_send at offset 122 inside [0x724000002000, 202)
==404==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x75b572 in zmq::tcp_write(int, void const*, unsigned long) /src/libzmq/src/tcp.cpp:242:22
    #1 0x75947e in zmq::stream_engine_base_t::write(void const*, unsigned long) /src/libzmq/src/stream_engine_base.cpp:767:12
    #2 0x751321 in zmq::stream_engine_base_t::out_event() /src/libzmq/src/stream_engine_base.cpp:372:24
    #3 0x5b2ec1 in zmq::epoll_t::loop() /src/libzmq/src/epoll.cpp:202:29
    #4 0x5f8c5a in zmq::worker_poller_base_t::worker_routine(void*) /src/libzmq/src/poller_base.cpp:146:51
    #5 0x657558 in thread_routine(void*) /src/libzmq/src/thread.cpp:250:5
    #6 0x7fbdc9a8f6b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #7 0x7fbdc90a241c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x10741c)
DEDUP_TOKEN: zmq::tcp_write(int, void const*, unsigned long)--zmq::stream_engine_base_t::write(void const*, unsigned long)--zmq::stream_engine_base_t::out_event()
SUMMARY: MemorySanitizer: use-of-uninitialized-value /src/libzmq/src/tcp.cpp:242:22 in zmq::tcp_write(int, void const*, unsigned long)
  ORIGIN: invalid (0). Might be a bug in MemorySanitizer origin tracking.
    This could still be a bug in your code, too!
```

**Comment by jonathanmetzman** [comment]
> WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libc.so.6
> 
> that doesn't look good...

Where do you see this happen?
> 
> Note that linking step is using clang++ as instructed:
> 
> > libtool: link: clang++ -std=c++11 -pedantic -Werror -Wall -Wno-long-long -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=memory -fsanitize-memory-track-origins -fsanitize=fuzzer-no-link -stdlib=libc++ -I/tmp/zmq_install_dir/install_prefix/include -Wno-atomic-alignment -Wno-tautological-constant-compare -pthread -o tests/test_z85_decode_fuzzer tests/tests_test_z85_decode_fuzzer-test_z85_decode_fuzzer.o -fsanitize=fuzzer  -L/tmp/zmq_install_dir/install_prefix/lib ./tests/libtestutil.a ./external/unity/libunity.a ./src/.libs/libzmq.a -L/install_prefix/lib /tmp/zmq_install_dir/install_prefix/lib/libsodium.a -lrt -lpthread -pthread

right.

>@jonathanmetzman is there any special sauce for glibc as well? Or is CC=clang enough?

I would think so.

I'm out of ideas other than seeing what changed between the working build and the non-working one. Here's the full logs from the last successful build: https://oss-fuzz-build-logs.storage.googleapis.com/log-627f6292-73ba-4703-8a46-cc958d9225e5.txt

**Comment by bluca** [comment]
> > WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libc.so.6
> > that doesn't look good...
> 
> Where do you see this happen?

https://travis-ci.com/github/bluca/oss-fuzz/jobs/338436750

I found out that libsodium needs to be built without some assembly optimizations, for whatever reason - so testing the following changes, which include that and removing -L/usr/local/lib to avoid the "bad" libc++.so

https://github.com/bluca/oss-fuzz/commit/f2910472b04a

With those, most fuzzers are ok, apart from one.

> > Note that linking step is using clang++ as instructed:
> > > libtool: link: clang++ -std=c++11 -pedantic -Werror -Wall -Wno-long-long -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=memory -fsanitize-memory-track-origins -fsanitize=fuzzer-no-link -stdlib=libc++ -I/tmp/zmq_install_dir/install_prefix/include -Wno-atomic-alignment -Wno-tautological-constant-compare -pthread -o tests/test_z85_decode_fuzzer tests/tests_test_z85_decode_fuzzer-test_z85_decode_fuzzer.o -fsanitize=fuzzer  -L/tmp/zmq_install_dir/install_prefix/lib ./tests/libtestutil.a ./external/unity/libunity.a ./src/.libs/libzmq.a -L/install_prefix/lib /tmp/zmq_install_dir/install_prefix/lib/libsodium.a -lrt -lpthread -pthread
> 
> right.
> 
> > @jonathanmetzman is there any special sauce for glibc as well? Or is CC=clang enough?
> 
> I would think so. I've never seen this before and I would think CC=clang is enough.
> 
> I'm out of ideas other than seeing what changed between the working build and the non-working one. Here's the full logs from the last successful build: https://oss-fuzz-build-logs.storage.googleapis.com/log-627f6292-73ba-4703-8a46-cc958d9225e5.txt

The old build didn't have libsodium, which was causing the initial issues without the special configure flag, and also didn't have some new fuzzers, which are using libsodium.

**Comment by bluca** [comment]
Although given only one out of 4 fuzzers show this issue, and they are built in the exact same way, it might very well be a real issue - although the MSAN error is not super helpful, I'll keep digging
