### ISSUE TITLE
Inaccessible perf_report on oss-fuzz.com for unicorn project

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#3876]
For instance with 
https://oss-fuzz.com/performance-report/libFuzzer_unicorn_fuzz_emu_arm64_arm/libfuzzer_asan_unicorn/latest
I only get 
`Error: No stats. (my@mail.com)`

Is it due to the project somehow ?

**Comment by inferno-chromium** [comment]
https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2020-05-19&date_end=2020-05-25&fuzzer=libFuzzer_unicorn_fuzz_emu_arm64_arm&job=libfuzzer_asan_unicorn&project=unicorn

You can use this to go to https://oss-fuzz.com/performance-report/libFuzzer_unicorn_fuzz_emu_arm64_arm/libfuzzer_asan_unicorn/2020-05-24

There is something going on, looks like not all fuzzers are running everyday, see also https://github.com/google/oss-fuzz/issues/3864
unicorn project seems to be getting 48 cpus (/48 1-core vms), this shouldnt happen.

**Comment by inferno-chromium** [comment]
```
I 2020-05-26T18:15:45.888176503Z Shutting down host. 
W 2020-05-26T18:15:45.883525680Z Channel failed to become ready within reconnect timeout. 
W 2020-05-26T18:15:15.882623011Z Channel failed to become ready within reconnect timeout. 
I 2020-05-26T18:14:43.412667706Z Completed running platform initialization scripts. 
I 2020-05-26T18:14:43.412118523Z Running platform initialization scripts. 
I 2020-05-26T18:14:43.411741088Z Remote souce code <= local source code. No update. 
I 2020-05-26T18:14:43.411346056Z Remote source code version: 20200520171744-utc-15968ae-clusterfuzz. 
I 2020-05-26T18:14:43.410755989Z Local source code version: 20200520171744-utc-15968ae-clusterfuzz. 
I 2020-05-26T18:14:43.404767687Z Checking source code for updates. 
```

Somehow some host bots are hanging, @oliverchang @mbarbella-chromium . this is pretty serious and has happened in past, looks similar to #3864.

**Comment by inferno-chromium** [comment]
Looks fixed now with https://github.com/google/clusterfuzz/pull/1799. Thanks @oliverchang

**Comment by catenacyber** [comment]
Thanks, it works again :-)
