### ISSUE TITLE
Bisector seems to give up too soon

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#3887]
As far as I can remember OSS-Fuzz could bisect up to the point where fuzz targets were introduced. Now it seems it can no longer do that. In https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22547 there is no the "regressed" link and the "Crash Revision" seems to just point to the latest version of the code where the bug was present. I wonder if anything has changed there?

```
[2020-05-26 13:23:40 UTC] oss-fuzz-linux-zone1-host-v84z-8: Regression task in-progress: Testing r202005260340.
[2020-05-26 13:23:43 UTC] oss-fuzz-linux-zone1-host-v84z-8: Regression task in-progress: Testing r202005250335.
[2020-05-26 13:23:46 UTC] oss-fuzz-linux-zone1-host-v84z-8: Regression task in-progress: Testing r202005240340.
[2020-05-26 13:23:51 UTC] oss-fuzz-linux-zone1-host-v84z-8: Regression task finished: regressed in range 0:202001150132.
```

Just to make sure that the bug was there in 2019 I pulled systemd-v244, built the fuzz target and successfully reproduced the crash. The fuzz target was added to the repository in 2018.

**Comment by inferno-chromium** [comment]
This is honggfuzz job type whose builds are only introduced recently, so that is why it shows as 202001150132.

```
$ gsutil ls gs://clusterfuzz-builds-honggfuzz/systemd/systemd-address-*
gs://clusterfuzz-builds-honggfuzz/systemd/systemd-address-202001150132.srcmap.json
gs://clusterfuzz-builds-honggfuzz/systemd/systemd-address-202001150132.zip
gs://clusterfuzz-builds-honggfuzz/systemd/systemd-address-202001160318.srcmap.json
gs://clusterfuzz-builds-honggfuzz/systemd/systemd-address-202001160318.zip
....
```

**Comment by inferno-chromium** [comment]
To get better range (older builds), you can reupload that testcase to libfuzzer job type. Over time, we will have archived more honggfuzz builds.

**Comment by evverx** [comment]
It seems it would be easier to turn off honggfuzz then since bug reports aren't as useful as they can be. Though I'm not sure why OSS-Fuzz can't try switching to LibFuzzer automatically (given that according to the logs libFuzzer, AFL and honggfuzz found this bug)

**Comment by inferno-chromium** [comment]
> It seems it would be easier to turn off honggfuzz then since bug reports aren't as useful as they can be. Though I'm not sure why OSS-Fuzz can't try switching to LibFuzzer automatically (given that according to the logs libFuzzer, AFL and honggfuzz found this bug)

We do show if it reproduces on libFuzzer and AFL jobs. However, honggfuzz catches its own set of new bugs. We don't do regression testing across different job types, and implementing it is not a priority right now (as this become obsolete in a few months since we will have lot of honggfuzz builds archived).

**Comment by evverx** [comment]
> as this become obsolete in a few months since we will have lot of honggfuzz builds archived

I wonder if OSS-Fuzz goes back in time, so to speak, to accumulate old builds that are currently missing? If not, I'm not sure it will become obsolete because bugs introduced before 20200116 aren't going anywhere.

**Comment by inferno-chromium** [comment]
@evverx - we are looking into having both granular regression and fixed testing, and which is also not dependent on archived builds. we will keep you posted once that system comes through. @oliverchang fyi.

**Comment by evverx** [comment]
> @evverx - we are looking into having both granular regression and fixed testing

Is my understanding correct that until then the bisector will rely on those builds and by turning off honggfuzz I've just kind of reset this process for systemd? If so, I'd probably prefer to revert https://github.com/google/oss-fuzz/pull/3889

**Comment by inferno-chromium** [comment]
i will let @oliverchang confirm, but maybe that system will use regression range as input [in that case we cant go back furthur]. Still disabling honggfuzz is a bad thing to do since honggfuzz gives nice new bugs, i would prefer revert. for bugs that are really old, reuploading testcase to libfuzzer job type is a one click operation.
