### ISSUE TITLE
bzip2 added to images making builds fail?

### ISSUE THREAD

**Issue by tsdgeos** [google/oss-fuzz#3888]
I think bzip2 may have been added to the images and now my poppler and kimageformats builds fail.

Should i try to workaround that?

Or can we have it so that the devel package of bzip2 is not installed in the images?

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22612
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22617

**Comment by inferno-chromium** [comment]
Sorry about breakage.
