### ISSUE TITLE
Coverage build is failing because of a new fuzz target

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#3902]
According to https://oss-fuzz-build-logs.storage.googleapis.com/log-273c6142-8d8e-49ba-a888-6d9befb27e2b.txt,
> Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: [/corpus/fuzz-xdg-desktop.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/fuzz-xdg-desktop.zip or
Step #5:         /corpus/fuzz-xdg-desktop.zip.zip, and cannot find /corpus/fuzz-xdg-desktop.zip.ZIP, period.
Step #5: Failed to unpack the corpus for fuzz-xdg-desktop. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
Step #5: ********************************************************************************
Step #5: Code coverage report generation failed.

If failures like this are generally normal and expected, I wonder if it would be possible not report them as failures. I wouldn't have noticed this a year ago but we have a badge now and it's been yellow for two days.

**Comment by inferno-chromium** [comment]
This is a bad, we shouldn't break your badge because of these new fuzz targets.
