### ISSUE TITLE
List of UBSAN targets crashing >50% of time

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#391]
gnutls-logs.clusterfuzz-external.appspot.com-libFuzzer_gnutls_openpgp_cert_parser_fuzzer-libfuzzer_ubsan_gnutls-      "percent": 98.03, 
grpc-logs.clusterfuzz-external.appspot.com-libFuzzer_grpc_api_fuzzer-libfuzzer_ubsan_grpc-      "percent": 95.52, 
grpc-logs.clusterfuzz-external.appspot.com-libFuzzer_grpc_ssl_server_fuzzer-libfuzzer_ubsan_grpc-      "percent": 100.0, 
irssi-logs.clusterfuzz-external.appspot.com-libFuzzer_irssi_irssi-fuzz-libfuzzer_ubsan_irssi-      "percent": 99.63, 
lcms-logs.clusterfuzz-external.appspot.com-libFuzzer_lcms_cms_transform_fuzzer-libfuzzer_ubsan_lcms-      "percent": 87.45, 
libarchive-logs.clusterfuzz-external.appspot.com-libFuzzer_libarchive_fuzzer-libfuzzer_ubsan_libarchive-      "percent": 83.07, 
libass-logs.clusterfuzz-external.appspot.com-libFuzzer_libass_fuzzer-libfuzzer_ubsan_libass-      "percent": 94.43, 
libchewing-logs.clusterfuzz-external.appspot.com-libFuzzer_libchewing_chewing_default_fuzzer-libfuzzer_ubsan_libchewing-      "percent": 77.84, 
libchewing-logs.clusterfuzz-external.appspot.com-libFuzzer_libchewing_chewing_dynamic_config_fuzzer-libfuzzer_ubsan_libchewing-      "percent": 95.3, 
libchewing-logs.clusterfuzz-external.appspot.com-libFuzzer_libchewing_chewing_random_init_fuzzer-libfuzzer_ubsan_libchewing-      "percent": 83.53, 
libplist-logs.clusterfuzz-external.appspot.com-libFuzzer_libplist_xplist_fuzzer-libfuzzer_ubsan_libplist-      "percent": 84.36, 
libteken-logs.clusterfuzz-external.appspot.com-libFuzzer_libteken_fuzzer-libfuzzer_ubsan_libteken-      "percent": 99.51, 
libxml2-logs.clusterfuzz-external.appspot.com-libFuzzer_libxml2_xml_regexp_compile_fuzzer-libfuzzer_ubsan_libxml2-      "percent": 53.38, 
tpm2-logs.clusterfuzz-external.appspot.com-libFuzzer_tpm2_execute_command_fuzzer-libfuzzer_ubsan_tpm2-      "percent": 99.44,

**Comment by Dor1s** [comment]
There are mostly `shift` bugs, though `signed-integer-overflow` also presented. Many of crashes come from the corpus. IIRC, we don't have quarantine for jobs other than ASan? But even if we had, those seem to be low hanging fruits anyway.

Looks like the best solution would be actually fix bugs in target projects. But for now I believe that we can reduce number of bots running UBSan and move them to ASan. What do you think?

**Comment by inferno-chromium** [comment]
Yes we can't quarantine with UBSan, will just wipe the corpus a lot of the times. If we don't share corpus with ASan, that is disadvantageous as well. I want to see if some of these show up on https://oss-fuzz-build-logs.storage.googleapis.com/status.html, otherwise, might have to raise that fuzzer run to like 20-30 sec.

**Comment by inferno-chromium** [comment]
Builds now showing up as unstable on https://oss-fuzz-build-logs.storage.googleapis.com/status.html, will expect devs to fix these. atleast i see ffmpeg ones getting fixed.
