### ISSUE TITLE
It takes OSS-Fuzz more than 4 minutes to render the testcases tab sometimes

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#3919]
I noticed that from time to time it takes a lot of time for Chrome (Version 83.0.4103.61 (Official Build) (64-bit)) to render [the "testcases" tab](https://oss-fuzz.com/testcases)
![Screenshot 2020-06-02 at 05 48 43](https://user-images.githubusercontent.com/10195800/83475038-2752aa00-a496-11ea-876e-05552b50f5e0.png)

It appears in incognito mode after signing out and signing in again it happens much more often. The other tabs seem to be responsive.

Looks like it waits for https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2 most of the time:
![Screenshot 2020-06-02 at 06 49 34](https://user-images.githubusercontent.com/10195800/83478155-cdee7900-a49d-11ea-8196-874c6d9e01aa.png)

**Comment by evverx** [comment]
I'm sure that the browser gets stuck somewhere around those fonts. Though given that I can download them manually via the direct links with no lag whatsoever it seems some JS code initiates a connection and hangs afterfards making the whole page unresponsive.

**Comment by evverx** [comment]
FWIW I temporarily switched to "testcases" on oss-fuzz because of a glitch I mentioned in https://github.com/google/oss-fuzz/issues/3886#issuecomment-637559131. I had never used it and am planning to switch back to monorail once the list of issues on monorail is more or less sorted out. so I wouldn't say it's a priority.

**Comment by inferno-chromium** [comment]
Cannot reproduce it in regular mode (non-incognito). Tested hosting of fonts on site is actually way slower, since CDN are supposed to faster (since closer). Only optimization i can do is preconnect one on https://www.smashingmagazine.com/2019/06/optimizing-google-fonts-performance/, done in https://github.com/google/clusterfuzz/pull/1865
