### ISSUE TITLE
Please give me access to html5ever results

### ISSUE THREAD

**Issue by jdm** [google/oss-fuzz#3939]
I set the contact email to be the servo-ops@mozilla.com account so that it's not just tied to one person, but it appears I need to be able to access it with my own personal account instead (jmatthews@mozilla.com).

**Comment by alex** [comment]
You should be able to send a PR adding yourself to `auto_ccs` on https://github.com/google/oss-fuzz/blob/master/projects/html5ever/project.yaml

**Comment by jdm** [comment]
Great, thanks!
