### ISSUE TITLE
specifying keywords in project.yaml (for cross pollination)

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#394]
What do people think about the idea of specifying some keywords in project.yaml? For example, freetype might have "truetype", "font" etc as keywords.

This doesn't seem like a lot to ask of people, and can be used to improve the way we do cross pollination (right now we;re randomly picking testcases from all targets, which doesn't seem like it will scale).

**Comment by kcc** [comment]
I'm not very enthusiastic. People are unreliable source of information.

**Comment by oliverchang** [comment]
Sure, it definitely won't be perfect, but it's at least better than what we have?

**Comment by kcc** [comment]
In another system we have something like this and I have to ping users to add these keywords.
I.e. it does not work as a self service. 
Since it won't be perfect, we will still have to do full N*N cross pollination, which means that
such keywords will actually be useless and confusing.

**Comment by oliverchang** [comment]
Discussed offline, this was tried already and provides a very weak signal. I'll file another bug for improving cross pollination.
