### ISSUE TITLE
Rust project sees lots of noise about timeouts

### ISSUE THREAD

**Issue by alexcrichton** [google/oss-fuzz#3944]
I wanted to open an issue that we've seen in Wasmtime about how a ton of our fuzz bugs that we're getting are all related to timeouts. Unfortunately almost all of these reports have been "spurious" in that they're not really related to slow code or infinite loops. Instead it all seems related to sanitizing infrastructure and how sanitizers are run. I wanted to open this issue to see if others had thoughts on how to tackle this?

Rust code is built for fuzzing with `cargo-fuzz`, and this Cargo subcommand will automatically inject flags to the compiler to enable various fuzzing options in LLVM. This currently is hardcoded and ignores whatever is in the environment, so while the build images are likely specifying flags to sanitize with in the environment for C/C++, that's not being interpreted for Rust code. 

I [did some investigation awhile ago](https://github.com/rust-fuzz/cargo-fuzz/issues/216) and found that the `cargo fuzz` is quite aggressive about specifying coverage options and passes to LLVM. So much so that code often sees a 50x or greater slowdown compared to non-instrumented code. When we're dealing with a 60s timeout a 50x slowdown can cause relatively trivial cases to quickly hit the timeout.

Are there folks familiar with LLVM and its sanitization/coverage passes which could help us out? Are all of those options necessary for high quality fuzzing? Does oss-fuzz enable different subsets of those options and expect different timeout values? Could `cargo fuzz` respect the environment a different way to pass through fuzzing options?

Another thing I've seen is that our crash logs for timeouts often have `-runs=100`. I was wondering why this was the case, because if we're seeing a 50x slowdown with respect to normal code, and then we run it 100 times, that's a 5000x slowdown which means that if our test case doesn't finish in 12ms then we'll time out. (or is the timeout per-run instead of for each run?). I'm typically pretty perplexed though because many of our timeout issues, when reproduced locally, complete in under a second. Only with `-runs=100` do they take an appreciable amount of time.

In any case I'm hoping to cut down on the amount of noise we get for fuzz bugs related to timeouts. I'm not 100% sure what's the best way to do this, so if others have thoughts on things here that would be greatly appreciated!

**Comment by alexcrichton** [comment]
Sorry I hit the submit button a bit early on this issue, so if you got an email notification about this the contents have since been edited from when I opened the issue.

**Comment by inferno-chromium** [comment]
@alexcrichton - can you please start an email thread with kcc@ and dynamic-tools@ [google][dot][com]. I think underlying sanitizer instrumentation coverage slowness needs to be fixed (no need to lower -runs=100, also slowness impacts fuzzing efficiency). 50x is crazy slow.

**Comment by alexcrichton** [comment]
Sure thing, email sent!

**Comment by alexcrichton** [comment]
Ah unfortunately it looks like the dynamic-tools email bounced:

>  We're writing to let you know that the group you tried to contact (dynamic-tools) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
>
> * You might have spelled or formatted the group name incorrectly.
> * The owner of the group may have removed this group.
> * You may need to join the group before receiving permission to post.
> * This group may not be open to posting.

**Comment by inferno-chromium** [comment]
> Ah unfortunately it looks like the dynamic-tools email bounced:
> 
> > We're writing to let you know that the group you tried to contact (dynamic-tools) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
> > 
> > * You might have spelled or formatted the group name incorrectly.
> > * The owner of the group may have removed this group.
> > * You may need to join the group before receiving permission to post.
> > * This group may not be open to posting.

Sorry about that. @kcc will add folks!

**Comment by kcc** [comment]
I am completely ignorant about the use of sanitizers and santizer coverage in Rust.
I'd suspect something silly, like not using -O2, etc or using some redundant instrumentation. 
Happy to help here if you can create small reproducers and guide us though command lines and perf results. 

Let's start from some small reproducer, preferably a single rust file, that is sufficient to reproduce  50x slowdown.

**Comment by alexcrichton** [comment]
Hm so unfortunately I don't know of a great way to minimize this. I'm not sure if it's necessary, however, and I can try and ask a more direct question. (mentioned on https://github.com/rust-fuzz/cargo-fuzz/issues/216 in the details).

Currently Rust sanitizers are built with a number of flags that are sent directly to LLVM. These flags presumably control LLVM's behavior of instrumented code and how code works. These flags are the cause of the major slowdowns I've seen when fuzzers are run. Rust fuzzing right now always injects the "sancov" pass as well as the `-sanitizer-coverage-inline-8bit-counters` LLVM argument (without this 8-bit counter argument the runtime complains).

Further flags are [then added unconditionally](https://github.com/rust-fuzz/cargo-fuzz/blob/edc4345f2bfbde9fcfaf256ee651e369245cf174/src/project.rs#L155-L163) to all fuzz invocations. The purpose of https://github.com/rust-fuzz/cargo-fuzz/issues/216 was to see if anyone on the Rust side knew why these flags were passed, but it didn't really sound like there was great knowledge of this.

Running our fuzzer against a recent case that timed out, I get timings [similar to the original issue](https://github.com/rust-fuzz/cargo-fuzz/issues/216)

* Baseline fuzzer build (no extra flags) - 3.6s 
* `-sanitizer-coverage-level=1` - 3.6s
* `-sanitizer-coverage-level=4` - 3.8s
* `-sanitizer-coverage-level=4 -sanitizer-coverage-pc-table` - 3.8s
* `-sanitizer-coverage-level=4 -sanitizer-coverage-prune-blocks=0` - 3.9s
* `-sanitizer-coverage-level=4 -sanitizer-coverage-trace-geps` - 8.1s
* `-sanitizer-coverage-level=4 -sanitizer-coverage-trace-compares` - 12.9s
* `-sanitizer-coverage-level=4 -sanitizer-coverage-stack-depth` - 3.9s
* all flags - 21.2s

Honestly this isn't the degree of slowdown that I expected. My "gut" baseline for Wasmtime turns out to not include a number of other slowdowns specific to wasmtime itself including debug assertions, nan canonicalization, and a debug verifier.

This leads me a few questions:

* Is it expected that fuzzing is a 7x or more slowdown? 
* Is it expected that fuzzers on oss-fuzz have all possible checks enabled, even at the cost of runtime? Is there a way that we could only collect timeouts for builds that have few extra checks enabled but run normal fuzzers against builds with all checks enabled?
* Do these LLVM flags for sanitizers match what's expected of C/C++? Is `cargo fuzz` enabling too much? Too little?

Does that help with a more focused question at least? If it's still necessary to minimize I unfortunately don't have enough time to focus on this and try to create a single-file reproduction. I can share reproduction steps but if the bug here is in the sanitizers themselves or LLVM's codegen passes I probably won't be much help to debug that.

**Comment by kcc** [comment]
Some things to try: 

* remove `-sanitizer-coverage-prune-blocks=0` which disables useful optimization and is not expect to loose a useful signal. libFuzzer doesn't use this one. 

* remove `-sanitizer-coverage-trace-geps`. This feature is experimental and is not (currently) very useful. libFuzzer for C++ (-fsanitize=fuzzer) doesn't use it.

* If you remove `-sanitizer-coverage-trace-compares ` you will get the largest gain, but you will loose some functionality. How much -- very hard to tell. Fuzzing will certainly become faster, but in some cases it may become dumber. This feature slows things down substantially in the C++ land as well, but probably not by the degree you show. Maybe this is something rust-specific (like, maybe we instrument Rust's bounds checks?). 

> Is it expected that fuzzing is a 7x or more slowdown?

We typically see more like 4x (2x from asan, 2x from coverage) but 7x may happen too due to `-sanitizer-coverage-trace-compares `  in very branchy code. 

> Is it expected that fuzzers on oss-fuzz have all possible checks enabled, even at the cost of runtime? 

We don't enable all checks at once, but we do enable enough of them at once to make this a problem, like you describe. But the goal of these timeouts is to detect cases where fuzzing is slow, and so essentially these timeouts helped us uncover the problem we have here. 

>> Do these LLVM flags for sanitizers match what's expected of C/C++? Is cargo fuzz enabling too much? Too little?

Seems like we have too much for sancov. 

Also, please make sure that optimization (O2) is enabled.

**Comment by alexcrichton** [comment]
Does C/C++ code get built with `-sanitizer-coverage-trace-compares` on OSS-Fuzz? I figure that the Rust code should probably just match C/C++ in whatever it does.

> Also, please make sure that optimization (O2) is enabled.

Ah yes forgot to mention, but yes optimizations are always enabled in all these measurements.

**Comment by kcc** [comment]
> Does C/C++ code get built with -sanitizer-coverage-trace-compares on OSS-Fuzz?

Yes. And this is a large source of slowdown under libFuzzer. 
We still don't know how useful this is on the large scale (it *is* very useful on small puzzles)

**Comment by alexcrichton** [comment]
Ok thanks for the info and your help here! I've opened https://github.com/rust-fuzz/cargo-fuzz/pull/229 to remove some of the more aggressive options which should hopefully bring at least some of a speedup to these test cases.

To confirm a final point before closing, though, it sounds like there's not really a good guidance per se on how many project-specific internal checks should be enabled while fuzzing? It sounds like there's basically a balance where you enable enough to mostly not time out on CI but still have something checked. There's definitely not a standard for "this build has all the checks enabled and isn't checked for timeouts" or something like that. Does that sound right?

**Comment by kcc** [comment]
These are not internal checks.
These are instrumentation options that guide fuzzing. 
We need to strike a balance between the instrumentation costs and benefits. 

> There's definitely not a standard for "this build has all the checks enabled and isn't checked for timeouts" or something like that. Does that sound right?

Right

**Comment by alexcrichton** [comment]
Er sorry, yes, I'm asking a different question more about OSS-Fuzz than libfuzzer itself. We enable debug assertions and an internal "debug verifier" when we fuzz on OSS-Fuzz. These are pretty big slowdowns for us (wasmtime specifically, not related to libfuzzer), which when multiplied by libfuzzer instrumentation slowdowns yields an even slower execution (hence the timeouts).

In any case it sounds like it's up to us to figure out the right balance of what to turn on with oss-fuzz. If we time out too often burning through all our debug checks that's probably too many being turned on.

**Comment by alexcrichton** [comment]
Ok I'm going to go ahead and close this, thanks so much for your help here @kcc! We'll probably reduce some debug checks on our side in Wasmtime but this has been very useful for sync'ing `cargo fuzz` with C++'s default settings!

**Comment by inferno-chromium** [comment]
@alexcrichton - thanks a lot for disabling those unneeded checks. can you please update here later on how much speed was recovered and what final slowdown look like.
