### ISSUE TITLE
Would like to close non-reproducible issues for Grok project

### ISSUE THREAD

**Issue by boxerab** [google/oss-fuzz#3953]
This issue has not been reproducible since March, but the sherrif-bot just opened this "bug" to the public:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21137&sort=-opened&can=1&q=proj%3Agrok

Can this bug report please be closed ?

Also:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21136&sort=-opened&can=1&q=proj%3Agrok

**Comment by inferno-chromium** [comment]
I have restricted view and closed it. Lets wait for a more reproducible variant to get filed.
