### ISSUE TITLE
Bug not closed when testcase was marked as fixed

### ISSUE THREAD

**Issue by Jakuje** [google/oss-fuzz#3964]
There is a bug that was not closed although the attached test cases were marked as fixed months ago. I do not see a way to manually close them so I would like to ask here for suggested approach to these bugs:

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18590&sort=-opened&can=1&q=proj%3Aopensc

**Comment by inferno-chromium** [comment]
Some weird issue tracker flake, closed it now. if something like this happens again, can investigate more.
