### ISSUE TITLE
How to deal with divide by zero error reports?

### ISSUE THREAD

**Issue by beltoforion** [google/oss-fuzz#3968]
I'm getting a lot of divide by zero reports for the muparser math expression parser project. Divide by zero is a natural condition for a math arsing engine. It is expected to happen and i need to let it happen because returning NaN's or Inf is the behavior that clients expect from a math parser. 

Is there a way to deal with such a situation?

**Comment by inferno-chromium** [comment]
in your build.sh, try
CFLAGS="${CFLAGS} -fno-sanitize=integer-divide-by-zero,float-divide-by-zero"
CXXFLAGS="${CXXFLAGS} -fno-sanitize=integer-divide-by-zero,float-divide-by-zero"
should work, test and then close the issue.

**Comment by beltoforion** [comment]
Thanks. I'll try that.

**Comment by nwellnhof** [comment]
Another solution is to mark the offending function with `__attribute__((no_sanitize("float-divide-by-zero")))`.
