### ISSUE TITLE
provide function profile and uninstrumented run-time in timeout reports

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#397]
I think we need to have a plain optimized build (no instrumentation) so that we can 
automatically report uninstrumented run-time in timeout reports together with the profile.

Example: 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=595 (comment 1)

**Comment by inferno-chromium** [comment]
This is part of the planned profiler work, assigning owners.

**Comment by inferno-chromium** [comment]
Dupe of #339
