### ISSUE TITLE
Use GitHub actions for CI

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#3970]
Travis has been painful as ever
1. 4mb log limit
2. times out after 50 minutes.

We can't keep up with this, given the vast number of new PRs and failure to run/verify things with large projects. Need to save ourselves from manual work. 

Github runner allows
1. 6 hr run time.
2. No log limit issue

There is some disk space issue like 29 gb in github actions vs 50 gb allowed by travis, but benefits outweight this disk space issue.

**Comment by inferno-chromium** [comment]
or even just github runner,
Each job in a workflow can run for up to 6 hours of execution time.
and no log limit

**Comment by jonathanmetzman** [comment]
It has lower disk space limits. Not sure this is a good idea.

**Comment by inferno-chromium** [comment]
> It has lower disk space limits. Not sure this is a good idea. Hacking around the 30 minute log problem is probably better if that's the only problem left

29 gb is quite a lot for building. Also 6 hr is way better than 50 minutes, even projects like ffmpeg build and run now. also no 4mb log limit. this outweights the benefits.
