### ISSUE TITLE
libreoffice builds failing in docker setup phase

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#398]
LibreOffice build has been failing a lot, but in the pre-build setup phase, e.g. right now https://oss-fuzz-build-logs.storage.googleapis.com/build_logs/libreoffice/latest.txt ends in...

 ---> f52f419104fd
Removing intermediate container 74b4a7802fcd
Step 42 : ADD http://dev-www.libreoffice.org/src/libfreehand-0.1.1.tar.bz2 $SRC/

open /var/lib/docker/image/overlay/imagedb/content/sha256/f52f419104fdc4d481d5b00dd2fc9310eca28821e82fb6526043d749c8914227: no such file or directory
[Pipeline] }

**Comment by inferno-chromium** [comment]
It is fixed now, but we need to recheck when it happens again. We are planning to expand our builders, it could be the timeout issue we face at the moment.

**Comment by inferno-chromium** [comment]
So, it keeps failing some times a day and once a day it succeeds and pushes build. So, we should n't be blocked. Mike can debug this, but he is on vacation atm. might have to wait if we can't figure it out.

**Comment by mikea** [comment]
There seems to be lots of intermittent issues like that reported in the internet. It looks to be coming from some docker-fs interaction. We could try replacing all ADDs with a single `RUN wget ... && wget ...` to drastically reduce the number of layers created.

**Comment by inferno-chromium** [comment]
seems fixed now.
