### ISSUE TITLE
[CIFuzz]: Some projects using CIFuzz still try to upload artifacts on build failure.

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#3982]
This itself fails because there are no artifacts. see https://github.com/openssl/openssl/runs/764449019?check_suite_focus=true

I vaguely remember fixing this issue but I don't have time to investigate today.

**Comment by evverx** [comment]
It looks like a duplicate of https://github.com/google/oss-fuzz/issues/3711 (which was kind of fixed in https://github.com/google/oss-fuzz/issues/3711).

https://github.com/openssl/openssl/blob/master/.github/workflows/main.yml has to be updated  to make that work though.

**Comment by jonathanmetzman** [comment]
Ah thanks

**Comment by inferno-chromium** [comment]
I don't think there is any work remaining here, template is updated in documention, and existing projects can update this over time. @jonathanmetzman please reupload if anything else left.
