### ISSUE TITLE
Add more builders

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#400]
Discussed in https://github.com/google/oss-fuzz/commit/54c51d787bf990b293b50b7a54faf1a88e6a6492#commitcomment-20931217

**Comment by inferno-chromium** [comment]
We upgraded builder to 16core, 50 gb bot, and 4 executors, so that seems to work fast, dont see choking anymore. We can wait for @mikea to come back and maybe add one more builder.

**Comment by Dor1s** [comment]
I thought about this too, but [most of the projects](https://github.com/google/oss-fuzz/search?utf8=%E2%9C%93&q=nproc&type=Code) are using `-j$(nproc)`. Having 4 executors on a single machine could result in 4 simultaneous builds running with `-j16` each.

**Comment by inferno-chromium** [comment]
Mike has enabled multiple builders. @mikea - feel free to close once the builders are stable and moved to clusterfuzz-external project.

**Comment by mikea** [comment]
We are using new GCB-based build system that gives us almost infinite horizontal scalability.
