### ISSUE TITLE
access to libexif issues

### ISSUE THREAD

**Issue by msmeissn** [google/oss-fuzz#4016]
Hi,

As I am one of the libexif developers I would like to have access to libexif issues , account is either marcus@jet.franken.de  or marcusmeissner@googlemail.com

**Comment by inferno-chromium** [comment]
Done in https://github.com/google/oss-fuzz/commit/e8ffee4077b59e35824a2e97aa214ee95d39ed13, should get access in 15-30 min, one email was already there, added other. in future, can just submit a Pr :)
