### ISSUE TITLE
Is it possible to reduce grace period?

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#4020]
Is it possible to reduce the grace period and simply make all issues public from the beginning? This would be awesome to have in cases where the open source project looks to share bugs with its community (at scale rather than listing emails of all). (CR https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23653#c2)

**Comment by inferno-chromium** [comment]
This can be done using
https://github.com/google/oss-fuzz/blob/master/projects/llvm/project.yaml#L27
but please warn the developers that they will be exposing security vulnerabilities and harming their users. we do this only for project that have no attack surface.
