### ISSUE TITLE
Project failing to build, but works locally and submits reports

### ISSUE THREAD

**Issue by moneromooo-monero** [google/oss-fuzz#4037]
Monero is getting reports of failing to build ("Friendly reminder that the the build is still failing.")

It links to (latest): https://oss-fuzz-build-logs.storage.googleapis.com/log-b42f4dd8-defd-48d3-b5b1-a91eed34eb23.txt

However, I can build just fine locally (build_image, build_fuzzers, check_fuzzers).

Moreover, we've been getting a couple fuzzing reports after this bug was filed, so it's clearly running.

The log above also shows monero finished building (build.sh ends by creating the corpus, and that finished fine in the log).

Last, the error at the end of this log doesn't seem to be about our code, it's not finding files in /workspace/out/coverage/report/coverage.

Is it something we need to fix ? If it is, any clue what needs to change given the error seems unrelated to our code ?

**Comment by inferno-chromium** [comment]
ah, someone messed up code coverage utils in chromium ?

```
Step #5: [2020-06-24 16:14:01,571 ERROR] Default coverage report dir does not exist: /workspace/out/coverage/report/coverage.
Step #5: Traceback (most recent call last):
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 829, in <module>
Step #5:     sys.exit(Main())
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 823, in Main
Step #5:     return _CmdPostProcess(args)
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 780, in _CmdPostProcess
Step #5:     processor.PrepareHtmlReport()
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 572, in PrepareHtmlReport
Step #5:     self.RenameDefaultCoverageDirectory()
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 556, in RenameDefaultCoverageDirectory
Step #5:     MergeTwoDirectories(default_report_subdir_path, self.report_root_dir)
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 727, in MergeTwoDirectories
Step #5:     for filename in os.listdir(src_dir_path):
Step #5: FileNotFoundError: [Errno 2] No such file or directory: '/workspace/out/coverage/report/coverage'
Step #5: ********************************************************************************
```

**Comment by Dor1s** [comment]
@moneromooo-monero did you try running a coverage build locally? Please see the log you linked:

```
Step #5: ********************************************************************************
Step #5: Code coverage report generation failed.
Step #5: To reproduce, run:
Step #5: python infra/helper.py build_image monero
Step #5: python infra/helper.py build_fuzzers --sanitizer coverage monero
Step #5: python infra/helper.py coverage monero
Step #5: ********************************************************************************
Finished Step #5
```

I'm pretty sure you'll reproduce the issue locally with these commands.

The problem is that monero compiles using source files placed in temporary locations e.g.

```
Step #5: [0m[0;31merror: /workspace/out/coverage/builder/home/.ccache/tmp/Cryptonigh.stdout.c8a28f6c310a.2139.FhKtlB.i: No such file or directory
Step #5: [0m[0;31mwarning: The file '/builder/home/.ccache/tmp/Cryptonigh.stdout.c8a28f6c310a.2139.FhKtlB.i' isn't covered.
```

These files are not available in the `base-runner` image which does code coverage report generation. There are two solutions:

1) copy over these directories similarly to e.g. https://github.com/google/oss-fuzz/blob/c06528180b3893199212d17a640f0037f6f40088/projects/abseil-cpp/build.sh#L49

2) ignore those files via e.g. https://github.com/google/oss-fuzz/blob/71f4914c453d1cba4f13dc331830378939ee84d9/projects/grpc/project.yaml#L13

option 2) is probably sufficient here

**Comment by moneromooo-monero** [comment]
Thanks, I can repro it indeed.

coverage_extra_args in project.yml doesn't seem to work.
adding -- -ignore-filename-regex=.*\.cache.*  to the coverage command line gets rid of those (the error lines show ccache, and interestingly \*..ccache.* also gets rid of them) but this one still remains:
> [2020-06-27 11:27:35,058 ERROR] Default coverage report dir does not exist: /out/report/coverage.
Traceback (most recent call last):

In the end I worked out removing ccache detection in our build system makes all the errors go away, and I think it's fine since it likely gets built once anyway so I'll PR that.

Thank you for the help, closing.
