### ISSUE TITLE
Badges should be "failing" when two consequent builds are failed

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#4046]
Similarly to why we don't file bug after only one build failure -- some things are flaky despite all retries and mitigations in place.

This has caused some user confusion in #3902 and #4039

**Comment by evverx** [comment]
To be honest, when it comes to "fuzzing" builds I think it's actually good that badges turn red without the two-day lag. Thanks to https://github.com/google/oss-fuzz/pull/3585 they are pretty stable.

Regarding coverage builds, I wonder if something like https://github.com/google/oss-fuzz/issues/1517 could be used to make sure coverage builds are more or less fine. If `./infra/helper.py coverage` could handle this it could be added to the CI and issues like https://github.com/google/oss-fuzz/issues/4037 could probably be easily prevented. More importantly, nobody would have to wait for 2 days to just find out their coverage build is broken.

**Comment by evverx** [comment]
> This has caused some user confusion in #3902 and #4039

Just to clarify I wouldn't say I was confused. I was pretty sure the coverage build wasn't broken because before sending patches to OSS-Fuzz I usually manually make sure that `build_fuzzers --sanitizer=coverage` and my kludgy `coverage` generating ascii coverage reports don't fail. It's just that I think it's kind of cumbersome and I'm not sure why OSS-Fuzz can't do that.

**Comment by Dor1s** [comment]
> I wonder if something like #1517 could be used to make sure coverage builds are more or less fine

Yes, after we implement a new notification system and start filing bugs for fuzz targets that fail corpus pruning task and do not produce a backup: https://github.com/google/clusterfuzz/issues/1614

> I was pretty sure the coverage build wasn't broken because before sending patches to OSS-Fuzz I usually manually make sure that ...

Good point. Users who are really hands on understand what's going on very well and have their own testing / CI. For majority of the users a two day lag is not a big deal given that many features take up to a day as well to get their job done.

**Comment by Dor1s** [comment]
@jonathanmetzman is this badge change something you can quickly fix? Or it's not trivial and I should take a look myself?

**Comment by jonathanmetzman** [comment]
I don't know to be honest how difficult this change would be.
But I think the current behavior is fine and I don't think anyone has the cycles to change this now, so closing.
