### ISSUE TITLE
QEMU: Corpus and Coverage inaccessible after ~10 days of fuzzing

### ISSUE THREAD

**Issue by a1xndr** [google/oss-fuzz#4051]
Hello,
OSS-Fuzz has been fuzzing QEMU for ~10 days and has already found some bugs. From the web-console I can see that each libfuzzer target has executed inputs. Additionally, I looked through the logs and saw that libfuzzer is adding to the corpus.
The corpus does not seem to be accessible in gcs and the coverage jobs are failing. My local helper.py coverage jobs fail due to missing corpora on gcs. The OSS-Fuzz coverage jobs are failing at the "unzip corpus" stage, which seems to corroborate this:
`unzip:  cannot find or open /corpus/*.zip, /corpus/*.zip.zip or /corpus/*.zip.ZIP.`
I have used the run_fuzzer and coverage jobs locally to successfully generate a corpus, merge it, and llvm-cov the resulting coverage data. 
Is there some  other debugging I can do locally? At the moment I am simply using the trick mentioned here to save a corpus locally: https://github.com/google/oss-fuzz/issues/2490#issuecomment-539950426 
Thank you
-Alex

**Comment by Dor1s** [comment]
The problem is that none of the fuzz targets has corpus backup. Corpus backup is produced during corpus pruning (i.e. minimization) task that runs daily.

The actual corpus is not empty:

```
$ gsutil ls gs://qemu-corpus.clusterfuzz-external.appspot.com/libFuzzer
gs://qemu-corpus.clusterfuzz-external.appspot.com/libFuzzer/qemu_qemu-fuzz-i386-target-i440fx-qos-fork-fuzz/
gs://qemu-corpus.clusterfuzz-external.appspot.com/libFuzzer/qemu_qemu-fuzz-i386-target-i440fx-qos-noreset-fuzz/
gs://qemu-corpus.clusterfuzz-external.appspot.com/libFuzzer/qemu_qemu-fuzz-i386-target-i440fx-qtest-reboot-fuzz/
gs://qemu-corpus.clusterfuzz-external.appspot.com/libFuzzer/qemu_qemu-fuzz-i386-target-virtio-net-slirp/
gs://qemu-corpus.clusterfuzz-external.appspot.com/libFuzzer/qemu_qemu-fuzz-i386-target-virtio-net-socket-check-used/
gs://qemu-corpus.clusterfuzz-external.appspot.com/libFuzzer/qemu_qemu-fuzz-i386-target-virtio-net-socket/
gs://qemu-corpus.clusterfuzz-external.appspot.com/libFuzzer/qemu_qemu-fuzz-i386-target-virtio-scsi-flags-fuzz/
gs://qemu-corpus.clusterfuzz-external.appspot.com/libFuzzer/qemu_qemu-fuzz-i386-target-virtio-scsi-fuzz/
```

and it's quite large in fact:

```
$ gsutil du -hs gs://qemu-corpus.clusterfuzz-external.appspot.com/
1.87 GiB     gs://qemu-corpus.clusterfuzz-external.appspot.com
```

Based on the performance reports (e.g. https://oss-fuzz.com/performance-report/libFuzzer_qemu_qemu-fuzz-i386-target-i440fx-qos-fork-fuzz/libfuzzer_asan_qemu/latest), it seems that fuzz target have frequent crashes and memory leaks. Very likely this is why corpus minimization doesn't succeed in the given time (24hr per target). Can you please look into fixing memory leaks and other frequent crashes?

**Comment by a1xndr** [comment]
@Dor1s Thank you for the pointer. I'll work on addressing the memory leaks.

**Comment by a1xndr** [comment]
My patch addressing the memory leak with a large priority score has landed upstream ( https://git.qemu.org/?p=qemu.git;a=commit;h=0b33521ea16463d7f942ddb2b354fa029c96231f ). Hopefully that will speed up the merges.

**Comment by a1xndr** [comment]
Hello. We fixed some additional leaks, and it seems that the coverage reports are now generating. Thank you for the pointer.
