### ISSUE TITLE
Simplify bazel project integration

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#4069]
Looking at https://github.com/google/oss-fuzz/blob/master/projects/envoy/build.sh, there are several parts that can be moved to https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile and https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/Dockerfile

E.g.
- Install latest stable bazel in base-builder Dockerfile - https://github.com/google/oss-fuzz/blob/master/projects/envoy/Dockerfile#L34, remove from all projects's dockerfiles.
- All BAZEL_FLAGS in some env var already set in compile, e.g.
```
declare -r EXTRA_BAZEL_FLAGS="$(
for f in ${CFLAGS}; do
  echo "--conlyopt=${f}" "--linkopt=${f}"
done
for f in ${CXXFLAGS}; do
  echo "--cxxopt=${f}" "--linkopt=${f}"
done
if [ "$SANITIZER" = "undefined" ]
then
  # Bazel uses clang to link binary, which does not link clang_rt ubsan library for C++ automatically.
  # See issue: https://github.com/bazelbuild/bazel/issues/8777
  echo "--linkopt=\"$(find $(llvm-config --libdir) -name libclang_rt.ubsan_standalone_cxx-x86_64.a | head -1)\""
fi
)"
```
- UBSan issues like https://github.com/google/oss-fuzz/blob/master/projects/zetasql/build.sh#L52, https://github.com/google/oss-fuzz/blob/master/projects/zetasql/build.sh#L39
- Anything else ?

**Comment by inferno-chromium** [comment]
We should look at abseil-cpp, envoy, esp-v2, tensorflow, zetasql build.sh for ideas here.

**Comment by inferno-chromium** [comment]
@tengpengli fyi

**Comment by zd-project** [comment]
I would also like to point out the issue with coverage fuzzer, which is handled here. Generated files should be moved out of the sandbox and into runtime environment for coverage fuzzer to work properly. This behavior should at least be documented. 

https://github.com/google/oss-fuzz/blob/master/projects/zetasql/build.sh#L76

Btw, "${OUT}/proc/self/cwd" seemed to be a peculiar choice of src look up path. I'm not sure why Bazel chooses so during build.

**Comment by zd-project** [comment]
Documentation on recommended bazel options are also helpful.

https://github.com/google/oss-fuzz/blob/master/projects/zetasql/build.sh#L59

**Comment by mihaimaruseac** [comment]
A lot of the bazel options are implicit in `.bazelrc` in the repository itself. For example, tensorflow uses `--config=libc++` to handle all the bazel options

https://github.com/google/oss-fuzz/blob/82252c22efbea9215137912c53e0c8c0b442273b/projects/tensorflow/build.sh#L59-L66
