### ISSUE TITLE
ffmpeg build breakage

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#408]
https://oss-fuzz-build-logs.storage.googleapis.com/build_logs/ffmpeg/latest.txt

@michaelni - can you please take a look

**Comment by michaelni** [comment]
Hmm, i see a
<pre>
+ cd /src/libva
+ ./autogen.sh
/src/build.sh: line 73: ./autogen.sh: No such file or directory
</pre>
FFmpeg doesnt use any auto* stuff so i would guess that is something else than FFmpeg failing

**Comment by inferno-chromium** [comment]
ah, looks like libva moved - https://github.com/01org/libva, let me double check compile locally.
