### ISSUE TITLE
New issue is incorrectly opened for similar testcase, after existing one is just closed.

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#4083]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23964 has just been opened even though it's basically the same issue as https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23895 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23950 (both of which were closed). As far as I can remember, it doesn't seem to be the first time issues that have been fixed have been reported over and over again.

**Comment by inferno-chromium** [comment]
Unsure if https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23950 is the same, it looks like null stack.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23964 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23895 look related, but the reason a new bug is filed, is it is a different crash type across a different sanitizer (index out-of-bounds ubsan vs heap-buffer-overflow overwrite). our grouping logic only works on open bugs, and the problem here is the slow once a day builds. Once that is fixed, you wont have to worry about this.

**Comment by evverx** [comment]
>  the problem here is the slow once a day builds. Once that is fixed, you wont have to worry about this.

Given that the two issues were closed, it seems the commit where the bug was fixed was picked up this morning so it appears it got lost somewhere along the way (at least partially). Building more often would help in the sense that the issue would be closed today (instead of tomorrow) but it would have been opened anyway.

**Comment by inferno-chromium** [comment]
Ah i think i see the issue that testcase was manually done redo->progression. so, basically one testcase got closed and then another one didn't get chance to be re-tested till 7-8 am PST. I recommend not using the redo explicitly, let things get auto-closed at 7 am (although there can be race, but i expect that to not happen much).

**Comment by evverx** [comment]
> I recommend not using the redo explicitly

It seems it's the only way to figure out whether bugs reported by OSS-Fuzz still need fixing.

FWIW I've just found a similar issue I mentioned in https://github.com/google/oss-fuzz/issues/3886#issuecomment-637559131.

**Comment by Dor1s** [comment]
Whenever a reproducible bug is closed, there's always a "fixed range" of commits. That means some commit in the range made the original issue unreproducible and therefore CF has to treat it as fixed. If you observe a case where this is not true, then it's probably a bug on our end.

Most often, when a project has a lot of bugs and some of them get unintentionally fixed or hidden by other bugs, that this might be annoying no matter how frequently you build. The only solution is to fix the bugs one by one and reduce their overall density in the code.

**Comment by evverx** [comment]
> If you observe a case where this is not true, then it's probably a bug on our end.

That's exactly what this issue is about. It's still unclear to me why https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23964 was reported in the first place. https://github.com/systemd/systemd/commit/e26538dd04ef3a0fa1582ff3be4ec1ec5c9a4178 (where the bug was fixed) was included in the last OSS-Fuzz build, as far as I can tell.

> Most often, when a project has a lot of bugs and some of them get unintentionally fixed or hidden by other bugs

If we're talking about systemd, there were just 2 bugs that were fixed almost as soon as they were reported. They led to at least 8 different OSS-Fuzz bug reports though most of which were opened after the bugs were fixed.

**Comment by evverx** [comment]
Anyway, my understanding is that nobody should press the "redo" button and that most bugs reported by OSS-Fuzz have already been fixed so before looking at bug reports it makes sense to wait for a week to make sure they are still reproducible and need fixing. I'll go ahead and close it.

**Comment by inferno-chromium** [comment]
> Anyway, my understanding is that nobody should press the "redo" button and that most bugs reported by OSS-Fuzz have already been fixed so before looking at bug reports it makes sense to wait for a week to make sure they are still reproducible and need fixing. I'll go ahead and close it.

It shouldn't be a week, it should be just an additional day wait. We can think of someone around this, but until the new build pipeline comes, it is hard to do. @kabeer27 fyi, lets discuss this later.

**Comment by kabeer27** [comment]
Okay @inferno-chromium, currently in the new pipeline the feature i have added is to specify a custom build frequency for upto 4 builds per day, starting at 6:00, and then at regular intervals from 6:00. (for 4 it will be 6:00, 12:00, 18:00, 00:00/24:00).

**Comment by evverx** [comment]
As far as I understand, in this particular case the problem was that https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23964 wasn't based on the latest build even though it was already there according to the build logs. It seems it can't be addressed by more frequent builds only. I'd say more frequent build will most likely lead to more bug reports because if OSS-Fuzz can't switch between the two last builds consistently I'm not sure how it can handle four builds.

**Comment by inferno-chromium** [comment]
> As far as I understand, in this particular case the problem was that https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23964 wasn't based on the latest build even though it was already there according to the build logs. It seems it can't be addressed by more frequent builds only. I'd say more frequent builds will most likely lead to more bug reports because if OSS-Fuzz can't switch between the two last builds consistently I'm not sure how it can handle four builds.

It does not switch builds, it just has a task that runs at a particular time and picks whatever is latest available. i am still thinking of what would be the right way to address this.

**Comment by evverx** [comment]
> It does not switch builds

The switch is in my head mostly :-) I just think of it as a system switching from state A to state B in one fell swoop where all the tasks scheduled for state A are invalidated once it's switched to state B.

**Comment by evverx** [comment]
It seems 'builds_per_day' hasn't been fully integrated into OSS-Fuzz in the sense that the util-linux project has been built at least twice since I added 'builds_per_day' but all the bugs that have been fixed are still open and OSS-Fuzz reported https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24879 2 hours after the build with the fix was there (according to the build logs).

**Comment by oliverchang** [comment]
This is within expectations. builds_per_day is more for helping with build failures and decreasing the regression ranges.

Fixed checking is done once a day, and our fuzzing tasks can take up to 4 hours. This means that if a new build comes in while the task is running, there is a window where you may get a bug that's already fixed.

**Comment by evverx** [comment]
> builds_per_day is more for helping with build failures and reducing the regression ranges

I don't think it's particularly useful for projects where build failures and regression are caught by CI before PRs are merged

**Comment by evverx** [comment]
Given that OSV is based on OSS-Fuzz and the data seems to be used in papers like https://twitter.com/mboehme_/status/1374639017715634180 I think it would be great if this issue could be fixed. Right now it seems due to duplicates the number of issues OSS-Fuzz has found can be safely divided by 1.5 (at least in the projects I keep track of).

**Comment by evverx** [comment]
As far as I can tell a series of patches that fixed several issues at once didn't trigger new bug reports because all of them were put on hold because "a similar issue has just been fixed". Closing.

Though the crashes seem to have been grouped in a way that prevented ClusterFuzz from reporting serious issues.
