### ISSUE TITLE
AFL Configuration for larger timeouts - spanner_emulator

### ISSUE THREAD

**Issue by jonvolfson** [google/oss-fuzz#4087]
AFL fails due to timeout on trivial test cases despite running the fuzz target locally with ~.02-.05 seconds per iteration. Options to configure AFL to have a larger timeout to account for startup could be helpful.

**Comment by Dor1s** [comment]
@jonathanmetzman is an expert on this subject

**Comment by jonathanmetzman** [comment]
Spanner_emulator is no longer fuzzed in OSS-Fuzz so I think we can close this.
This problem though will be tracked in #5452.
