### ISSUE TITLE
GitHub Actions CI: failures on the projects that aren't modified by the PR

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#4088]
Noticed at least two incidents:

https://github.com/google/oss-fuzz/pull/4076#issuecomment-655102952

https://github.com/google/oss-fuzz/pull/4073#pullrequestreview-444221299

@inferno-chromium pointed out that `git diff` logic might be at fault: https://github.com/google/oss-fuzz/blob/master/infra/ci/build.py#L38

**Comment by jonathanmetzman** [comment]
I haven't seen this happen recently. Is it still an issue or can we close?

**Comment by Dor1s** [comment]
I don't know (haven't uploaded / reviewed stuff recently). Let's close for now based on your comment.
