### ISSUE TITLE
No logs for running fuzzers

### ISSUE THREAD

**Issue by rlohning** [google/oss-fuzz#4092]
Looking at the [Fuzzer Statistics](https://oss-fuzz.com/fuzzer-stats) for project qt, I don't get any logs anymore. The "logs" column shows only "--". Coverage and corpus are available and the values show that the fuzzers are running. Is this anything I could fix?

**Comment by Dor1s** [comment]
Can you share an exact link you were checking?

If I open https://oss-fuzz.com/fuzzer-stats?project=qt&fuzzer=libFuzzer&job=libfuzzer_asan_qt&group_by=by-fuzzer I see the log for every fuzz target, and they lead to valid GCS directories.

**Comment by rlohning** [comment]
> If I open https://oss-fuzz.com/fuzzer-stats?project=qt&fuzzer=libFuzzer&job=libfuzzer_asan_qt&group_by=by-fuzzer I see the log links for every fuzz target, and they lead to valid GCS directories.

Indeed. As soon as I select a Job type as you did, I see the logs, too. When I look at https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2020-07-01&date_end=2020-07-07&fuzzer=libFuzzer_qt_qtbase_corelib_serialization_qcborstreamreader_next&project=qt , I don't see any logs, though.

Now that you showed me, I guess that's the intended behavior, because there are separate logs for the differrent jobs, but it seems surprising to me. I never would have figure this out since "--" looks like there are no logs available at all. Would it make sense to show links to all jobs' logs there, instead?

**Comment by Dor1s** [comment]
Yeah, that's intended, and I agree that it's not perfect given that we can have a link to e.g. https://pantheon.corp.google.com/storage/browser/qt-logs.clusterfuzz-external.appspot.com/libFuzzer_qt_qtbase_corelib_serialization_qcborstreamreader_next that has all the jobs. It wouldn't respect the date though, i.e. all links will be the same, but it feels like a less confusing behavior.

**Comment by Dor1s** [comment]
I'll upload a PR for that and we'll see what other CF developers think. The existing behavior also makes sense but I'm on your side :)

**Comment by rlohning** [comment]
Thank you. Feels good to not be alone. ;-)
