### ISSUE TITLE
[zstd] CIFuzz failing to build

### ISSUE THREAD

**Issue by terrelln** [google/oss-fuzz#4093]
The script `build.sh` started failing a few days ago on this line.

https://github.com/google/oss-fuzz/blob/600c51495857ff9d20d6cf683df6504b69a0f2a2/projects/zstd/build.sh#L19

It looks like `build.sh` assumes it is being run in the root of the zstd repo. But, some time ago it stopped being run from the root of the zstd repo. Is that expected?

**Comment by terrelln** [comment]
E.g. this run https://github.com/facebook/zstd/pull/2231/checks?check_run_id=849291310

**Comment by Dor1s** [comment]
As I recall CIFuzz might've had some assumptions. @jonathanmetzman could you please take a look?

**Comment by rgacogne** [comment]
CIFuzz stopped working for PowerDNS as well. We could change our working directory in `build.sh` to `${SRC}/pdns/` but I assume quite a lot of projects will have the same issue so perhaps it would be better to ensure that build.sh is run from the same place it used to, and match the regular OSS-Fuzz behaviour?

**Comment by inferno-chromium** [comment]
Looks like all cifuzz projects are broken, mayday!
Failures seem around 2020-07-08 08:46:00 UTC

**Comment by inferno-chromium** [comment]
Failure run:
http://cifuzz.appspot.com/run/pdns/161705947
2020-07-08T08:49:48.4007782Z Running: docker run --rm --privileged --cap-add SYS_PTRACE -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -e FUZZING_LANGUAGE=c++ -e OUT=/out -v /github/workspace/storage/pdns:/src/pdns -v /github/workspace/out:/out gcr.io/oss-fuzz/powerdns /bin/bash -c compile

Success run:
http://cifuzz.appspot.com/run/pdns/160774634
docker run --rm --privileged --cap-add SYS_PTRACE -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -e FUZZING_LANGUAGE=c++ -e OUT=/github/workspace/out --volumes-from 16f1c38a2c11 gcr.io/oss-fuzz/powerdns /bin/bash -c 'rm -rf /src/pdns/* && cp -r /github/workspace/storage/pdns /src && compile'

Looks like utils.get_container_name() helper is broken, looking more.

Maybe something broke with how we are detecting containers
https://github.com/google/oss-fuzz/blob/master/infra/cifuzz/cifuzz.py#L156

**Comment by evverx** [comment]
> Looks like all cifuzz projects are broken, mayday!

FWIW `systemd` and `util-linux` are fine

> Maybe something broke with how we are detecting containers

It appears some GitHub actions are run with `docker.service` (where `docker` is in `/proc/self/cgroup`) while the zstd actions are run with `containerd.service` where `/proc/self/cgroup` looks like
```
12:rdma:/
11:hugetlb:/actions_job/406ac3d3609a64ae01b084272f02ca57f2a807d1db3f3bd32c0c3f478f515262
10:cpu,cpuacct:/actions_job/406ac3d3609a64ae01b084272f02ca57f2a807d1db3f3bd32c0c3f478f515262
9:freezer:/actions_job/406ac3d3609a64ae01b084272f02ca57f2a807d1db3f3bd32c0c3f478f515262
8:memory:/actions_job/406ac3d3609a64ae01b084272f02ca57f2a807d1db3f3bd32c0c3f478f515262
7:net_cls,net_prio:/actions_job/406ac3d3609a64ae01b084272f02ca57f2a807d1db3f3bd32c0c3f478f515262
6:perf_event:/actions_job/406ac3d3609a64ae01b084272f02ca57f2a807d1db3f3bd32c0c3f478f515262
5:cpuset:/actions_job/406ac3d3609a64ae01b084272f02ca57f2a807d1db3f3bd32c0c3f478f515262
4:devices:/actions_job/406ac3d3609a64ae01b084272f02ca57f2a807d1db3f3bd32c0c3f478f515262
3:blkio:/actions_job/406ac3d3609a64ae01b084272f02ca57f2a807d1db3f3bd32c0c3f478f515262
2:pids:/actions_job/406ac3d3609a64ae01b084272f02ca57f2a807d1db3f3bd32c0c3f478f515262
1:name=systemd:/actions_job/406ac3d3609a64ae01b084272f02ca57f2a807d1db3f3bd32c0c3f478f515262
0::/system.slice/containerd.service
```

I've prepared a patch where `systemd-detect-virt -c` is called to make sure CIFuzz is run in a docker container. It's being tested in https://github.com/facebook/zstd/pull/2239

**Comment by inferno-chromium** [comment]
Thanks a ton @evverx for your awesome debugging!
