### ISSUE TITLE
[coverage] Irreproducible coverage failure, no logs error

### ISSUE THREAD

**Issue by asraa** [google/oss-fuzz#4116]
Hi OSS-Fuzz team!

I have another question I was wondering if you could help point me to out coverage failure. The logs here (https://oss-fuzz-build-logs.storage.googleapis.com/index.html#envoy) end like this:
```
Step #38:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Step #38:                                  Dload  Upload   Total   Spent    Left  Speed
Step #38: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    30    0     0  100    30      0     58 --:--:-- --:--:-- --:--:--    58
Finished Step #38
Starting Step #39
Step #39: Already have image: gcr.io/oss-fuzz/envoy
Finished Step #39
PUSH
DONE
```

and our latest coverage report hasn't been uploaded in a while. The "Already have image" line looks a little suspicious to me looking at other coverage builds, is this a known issue?

**Comment by Dor1s** [comment]
ouch, all coverage builds are broken, let's see

**Comment by Dor1s** [comment]
```
++ basename coverage/envoy
+ project_dir=/var/jenkins_home/workspace/coverage/envoy/oss-fuzz/projects/envoy
++ python build_and_run_coverage.py /var/jenkins_home/workspace/coverage/envoy/oss-fuzz/projects/envoy
  File "build_and_run_coverage.py", line 147
    'name': f'gcr.io/{base_images_project}/base-runner',
                                                      ^
SyntaxError: invalid syntax
```

**Comment by Dor1s** [comment]
Looks like https://github.com/google/oss-fuzz/pull/4103 was landed without testing the coverage job and caused this. Luckily today is the first day when all jobs have failed, and we have time to fix this without spamming too much users.

Thanks a lot @asraa for bringing this to our attetion.

**Comment by Dor1s** [comment]
Apparently the actual builds are failing too (it's just timing worked out for them better so far):

```
++ python build_project.py /var/jenkins_home/workspace/projects/zlib/oss-fuzz/projects/zlib
  File "build_project.py", line 72
    project_yaml.setdefault('image', f'gcr.io/{image_project}/' + project_name)
                                                              ^
SyntaxError: invalid syntax
```


In such case I'll just revert https://github.com/google/oss-fuzz/pull/4103 for now and re-run all coverage builds. //cc @kabeer27 @oliverchang

**Comment by Dor1s** [comment]
The builds are recovering now, closing this. Thanks again @asraa !

**Comment by asraa** [comment]
Thank you so much for quickly diagnosing!
