### ISSUE TITLE
fix c-ares after introducing -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#413]
See https://github.com/google/oss-fuzz/pull/410#issuecomment-281568382
```
configure: CFLAGS error: CFLAGS may only be used to specify C compiler flags, not macro definitions. 
```

One solution is to remove -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION from global flags and use it only in those projects there needed. (would be sad). 

Another solution is to hack https://github.com/google/oss-fuzz/blob/master/projects/c-ares/build.sh to cut -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION from CFLAGS (ouch!). Let me try this first. 

Also, let me ask David why is the configure script that picky... 

OMG, I hate build systems.

**Comment by daviddrysdale** [comment]
AIUI you should use `CPPFLAGS` for preprocessor definitions, and `CFLAGS` for C-specific options.  That way, the preprocessor options (`-Iwherever -Dwhatever`) can also be used in a C++ rule, without needing duplication between `CFLAGS` and `CXXFLAGS`.

Cf. http://stackoverflow.com/questions/2754966/cflags-vs-cppflags

**Comment by kcc** [comment]
Not all build systems will understand CPPFLAGS (or will they?), and only c-ares complains this way. 
Do you know what is special about c-ares that it  forbids the use of -DFOO in CFLAGS?

**Comment by daviddrysdale** [comment]
Looks like the check only went in a [few years ago](https://github.com/c-ares/c-ares/commit/037656b2d89f7bb8fb697afff5b67c3a9b1c1d87), but I don't the reasons why.  c-ares does get used on a lot of obscure platforms though, so it may have been an attempt to reduce misconfigurations with odd toolsets.
