### ISSUE TITLE
Mercurial coverage build busted

### ISSUE THREAD

**Issue by durin42** [google/oss-fuzz#4140]
I don't think this is related to #4003, because I think things were working for a day or two? In any event, https://oss-fuzz-build-logs.storage.googleapis.com/log-e0e08dec-bfd2-493d-b29b-cf49ed5f15d8.txt shows a missing .h somehow, and I haven't changed anything on our side in a while: #3571 was the last change on our side.

Halp?

**Comment by inferno-chromium** [comment]
I think one thing i saw wrong in #4003, was do we need to build python inside /out directory. if we do it elsewhere, all these bugs get resolved. /out should only have binaries for the specific project and not anything else. For this one, i think you need a 
```coverage_extra_args: -ignore-filename-regex=.*/\sanpy/.*``` in projecy.yaml for that sanpy dir so that coverage don't look for things there ?

**Comment by durin42** [comment]
Basically everything is dynamically linked against the sanitizer-built Python, so I'm pretty sure it has to be that way.

I'll send a PR for the coverage_extra_args and see if that helps, we definitely don't care about coverage on Python itself.

**Comment by inferno-chromium** [comment]
> Basically everything is dynamically linked against the sanitizer-built Python, so I'm pretty sure it has to be that way.
> 
> I'll send a PR for the coverage_extra_args and see if that helps, we definitely don't care about coverage on Python itself.

Did you try reproducing locally using
```
python infra/helper.py build_image mercurial
python infra/helper.py build_fuzzers --sanitizer coverage mercurial
python infra/helper.py coverage mercurial
```
i am pretty sure that coverage_extra_args change in project.yaml will fix this, but good to verify locally too.

**Comment by durin42** [comment]
Trying that now...

**Comment by inferno-chromium** [comment]
fixed
