### ISSUE TITLE
Need help setting LDFLAGS for Expat (in context of chromium.org bug 23225)

### ISSUE THREAD

**Issue by hartwork** [google/oss-fuzz#4143]
Dear oss-fuzz team,

currently the oss-fuzz build for Expat is failing as reported at https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23225 . The page says `If you have any questions, please create an issue at https://github.com/google/oss-fuzz/issues/new` near the top so I have come to this place…

I have determined that lack of setting `LDFLAGS` seems to be the issue and that setting `LDFLAGS` to the same value that `CFLAGS` is set to may fix the ASan related link errors. The code that sets these `CFLAGS` does not seem to be in here. Where can it be found? Can you apply the suggested fix and give it a try? Thank you! :pray:

Best, Sebastian

**Comment by Dor1s** [comment]
Add a line in https://github.com/google/oss-fuzz/blob/master/projects/expat/build.sh to set `LDFLAGS` equal to `CFLAGS`. We have many projects doing similar things, e.g.:

https://github.com/google/oss-fuzz/blob/47484451d54b9912276ba1061552846190fea0a1/projects/zlib-ng/build.sh#L19

https://github.com/google/oss-fuzz/blob/32df3fef08ec8d8e105a960703ea296f29160241/projects/rdkit/build.sh#L22

https://github.com/google/oss-fuzz/blob/2c4e8ca8376ac1ec0c19e2683174e925702b2d9d/projects/ffmpeg/build.sh#L75

**Comment by hartwork** [comment]
Okay great, thank you! :+1:
