### ISSUE TITLE
honggfuzz and afl engines give an error '-fsanitize-coverage=trace-pc-guard is no longer supported by libFuzzer'

### ISSUE THREAD

**Issue by tomrittervg** [google/oss-fuzz#4172]
While trying to add these engines to rnp ( https://github.com/google/oss-fuzz/tree/master/projects/rnp ) I am getting an error:

```
$ python infra/helper.py check_build rnp                                                                      1 ↵
Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -v /home/tom/Documents/play/rnp/oss-fuzz/build/out/rnp:/out -t gcr.io/oss-fuzz-base/base-runner test_all
INFO: performing bad build checks for /tmp/not-out/fuzz_keyring.
INFO: performing bad build checks for /tmp/not-out/fuzz_dump.
Broken fuzz targets (2):
fuzz_dump:
BAD BUILD: /tmp/not-out/fuzz_dump seems to have either startup crash or exit:
-fsanitize-coverage=trace-pc-guard is no longer supported by libFuzzer.
Please either migrate to a compiler that supports -fsanitize=fuzzer
or use an older version of libFuzzer
fuzz_keyring:
BAD BUILD: /tmp/not-out/fuzz_keyring seems to have either startup crash or exit:
-fsanitize-coverage=trace-pc-guard is no longer supported by libFuzzer.
Please either migrate to a compiler that supports -fsanitize=fuzzer
or use an older version of libFuzzer
ERROR: 100% of fuzz targets seem to be broken. See the list above for a detailed information.
Check build failed.
```

AFAICT these flags come from the oss-fuzz config; not anything I am using.  I am building in the oss-fuzz containers:

``
$ python infra/helper.py build_image $PROJECT_NAME && python infra/helper.py build_fuzzers --sanitizer address --engine honggfuzz $PROJECT_NAME
``

Full log: https://ritter.vg/misc/transient/log2.txt

Sample compile command:

```
/usr/local/bin/clang++
-O1
-fno-omit-frame-pointer
-gline-tables-only
-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
-fsanitize=address
-fsanitize-address-use-after-scope
-fsanitize-coverage=trace-pc-guard,indirect-calls,trace-cmp
-stdlib=libc++
-O3
-DNDEBUG
CMakeFiles/rnpkeys.dir/rnpkeys.cpp.o
CMakeFiles/rnpkeys.dir/tui.cpp.o
CMakeFiles/rnpkeys.dir/main.cpp.o
CMakeFiles/rnpkeys.dir/__/rnp/rnpcfg.cpp.o
CMakeFiles/rnpkeys.dir/__/rnp/fficli.cpp.o
../common/CMakeFiles/rnp-common.dir/list.cpp.o
../common/CMakeFiles/rnp-common.dir/str-utils.cpp.o
../common/CMakeFiles/rnp-common.dir/file-utils.cpp.o
-o rnpkeys
-Wl,-rpath,/src/rnp-build/src/lib:
../lib/librnp-0.so.0.0.0
/usr/lib/x86_64-linux-gnu/libjson-c.so
/usr/lib/libbotan-2.so
/usr/lib/x86_64-linux-gnu/libjson-c.so
/usr/lib/x86_64-linux-gnu/libbz2.so
/usr/lib/x86_64-linux-gnu/libz.so
```

I know I must be doing something wrong; but I'm not sure what...

**Comment by jonathanmetzman** [comment]
How are you linking your fuzz targets. Are you using `LIB_FUZZING_ENGINE`? Or are you using `-fsanitize=fuzzer`? I'm guessing `-fsanitize=fuzzer` since that would cause this issue.

**Comment by Dor1s** [comment]
I think you need to pass `--engine honggfuzz` to the `check_build` command

**Comment by jonathanmetzman** [comment]
> I think you need to pass `--engine honggfuzz` to the `check_build` command

This is also true, but I think that's a separate problem. From the examples you posted you are building libFuzzer targets with trace-pc-guard which shouldn't happen in OSS-Fuzz. Since these are non-libfuzzer builds, you must be linking the targets against libFuzzer incorrectly.

**Comment by Dor1s** [comment]
I think those coverage instrumentation flags are coming from https://github.com/google/oss-fuzz/blob/78e191ed92953b09a041232d39005d3074bfc49b/infra/base-images/base-builder/compile_honggfuzz#L25 and `--engine honggfuzz` is passed to the `build_fuzzers`, but you're right that it seems like libFuzzer is also linked in, otherwise I doubt that message would be printed by anything else

**Comment by jonathanmetzman** [comment]
> I think those coverage instrumentation flags are coming from
> 
> https://github.com/google/oss-fuzz/blob/78e191ed92953b09a041232d39005d3074bfc49b/infra/base-images/base-builder/compile_honggfuzz#L25
> 
> and `--engine honggfuzz` is passed to the `build_fuzzers`, but you're right that it seems like libFuzzer is also linked in, otherwise I doubt that message would be printed by anything else

Yeah it's printed by this: https://github.com/llvm/llvm-project/blob/226866e115de652b6fbc8f8195881a529ccb4b01/compiler-rt/lib/fuzzer/FuzzerTracePC.cpp#L404

**Comment by Dor1s** [comment]
```
/usr/local/bin/clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-coverage=trace-pc-guard,indirect-calls,trace-cmp -O3 -DNDEBUG  -fsanitize=fuzzer CMakeFiles/fuzz_keyring.dir/keyring.c.o  -o fuzz_keyring  -Wl,-rpath,/src/rnp-build/src/lib ../lib/librnp-0.so.0.0.0 /usr/lib/libbotan-2.so /usr/lib/x86_64-linux-gnu/libjson-c.so /usr/lib/x86_64-linux-gnu/libbz2.so /usr/lib/x86_64-linux-gnu/libz.so 
```

`-fsanitize=fuzzer` shouldn't be there, @jonathanmetzman is right

**Comment by tomrittervg** [comment]
Thanks all, I wasn't properly using `LIB_FUZZING_ENGINE`
