### ISSUE TITLE
Please grant ftang@google.com or ftang@chromium.org access 

### ISSUE THREAD

**Issue by FrankYFTang** [google/oss-fuzz#4176]
I am the owner of third_part/icu in chromium and in the ICU team.
Please grant me access to https://oss-fuzz.com/testcase-detail/ for
the following bugs
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19497
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=15671
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=15613
so I can work on them.

**Comment by alex** [comment]
Send a PR to https://github.com/google/oss-fuzz/blob/master/projects/icu/project.yaml adding yourself to `auto_ccs`.

**Comment by Dor1s** [comment]
Thanks @alex !

@FrankYFTang done, but we may need to wait up to ~30 minutes for the change to propagate.

**Comment by FrankYFTang** [comment]
thanks
