### ISSUE TITLE
ensure all builds are optimized

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#421]
See e.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=678
It's not totally clear if we should enforce -O1 or -O2. 
Also, if the project already has O2, do we want to downgrade it to O1?

**Comment by kcc** [comment]
libxml is also built w/o optimizations

**Comment by inferno-chromium** [comment]
afl might be building with -O0 as well, no -O enforced in here - https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile_afl#L26.

We enforced -O1 everywhere in chromium and it worked better than -O2 (@oliverchang). We can just add it here - https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-clang/Dockerfile#L38
