### ISSUE TITLE
Run all.sh error: cmake error

### ISSUE THREAD

**Issue by RosenZhu** [google/oss-fuzz#4229]
I try to build all base images running `infra/base-images/all.sh`. It was successfully built, but currently not.

The error is about cmake version: 
`CMake 3.13.4 or higher is required.  You are running version 3.5.1`.

It seems the LLVM version is not right.
`OUR_LLVM_REVISION=e84b7a5fe230e42b8e6fe451369874a773bf1867`, but finally it uses the version:
`Using LLVM revision: 7e8d5a90f2c101388d3b0bbce8555e871c670232`.

**Comment by inferno-chromium** [comment]
https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-clang/checkout_build_install_llvm.sh#L70
FORCE_OUR_REVISION is not set, it is 0, so it is picking latest version of llvm as expected. We set it to 1 if we need to hardcode a particular one (when latest is broken).

**Comment by inferno-chromium** [comment]
Just install latest cmake before calling all.sh
https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/Dockerfile#L35

Unsure why this does not show up as failure on our logs, maybe you are using something older than 16.04

**Comment by RosenZhu** [comment]
> Just install latest cmake before calling all.sh
> https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/Dockerfile#L35
> 
> Unsure why this does not show up as failure on our logs, maybe you are using something older than 16.04

I'm using Linux 18.04

**Comment by RosenZhu** [comment]
> https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-clang/checkout_build_install_llvm.sh#L70
> FORCE_OUR_REVISION is not set, it is 0, so it is picking latest version of llvm as expected. We set it to 1 if we need to hardcode a particular one (when latest is broken).

As I don't want a latest version of LLVM, I set FORCE_OUR_REVISION=1, and it works. Thanks very much.
