### ISSUE TITLE
speex revision not updated for open issues

### ISSUE THREAD

**Issue by tmatth** [google/oss-fuzz#4231]
Given https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22460, it seems that oss-fuzz is not testing the latest speex upstream revision, as this leak has been fixed since:
https://gitlab.xiph.org/xiph/speex/-/commit/7a762519869e7d34ba1f5c2ff09519f1021f4f6a

This may be because the upstream repo URL has been changed since speex was added to oss-fuzz:
https://github.com/google/oss-fuzz/commit/c7fa329aebd3af3fec3ac1b8e4dd1950720b7732#diff-2422798d15337ecac57389dae0fe04ae

**Comment by inferno-chromium** [comment]
@tmatth - can you propose the right url fix in https://github.com/google/oss-fuzz/blob/master/projects/speex/Dockerfile. I dont think there is any action item from our side.

**Comment by tmatth** [comment]
@inferno-chromium that's what I'm confused about, the URL in the dockerfile is currently the correct one, and oss-fuzz is referring to it already. The problem is that it's not seeing new revisions in that repo (the latest it tested is from over a year ago).

**Comment by inferno-chromium** [comment]
I see it was tested with latest build (metadata at end of report). Only explanation here is either leak is still there, or somehow build does not use right revision. Did you compile the fuzz target and see if leak does not reproduce on latest revision from repo ?

```
[2020-07-30 17:36:18 UTC] oss-fuzz-linux-zone1-host-t4v7-15: Progression task started: r202007300613.
[2020-07-30 17:36:19 UTC] oss-fuzz-linux-zone1-host-t4v7-15: Progression task finished: still crashes on latest revision r202007300613.
```

**Comment by tmatth** [comment]
At the top of the detailed report, I'm seeing:
![lasttested](https://user-images.githubusercontent.com/66862/88956740-ca902780-d26b-11ea-8595-89152209d9e6.png)

whereas the actual latest revision is:
https://gitlab.xiph.org/xiph/speex/-/commit/870ff845b32f314aec0036641ffe18aba4916887

**Comment by tysmith** [comment]
@inferno-chromium It does seem that oss-fuzz is stuck using Speex revision b54005c. I just tried "Redo task -> Check if bug still reproduces" and it used Speex revision b54005c.

**Comment by inferno-chromium** [comment]
ah found the bug, you need to fix this - https://github.com/google/oss-fuzz/blob/master/projects/speex/Dockerfile#L22 youu care checking out fuzz target from a particular branch

**Comment by tysmith** [comment]
Good catch!

**Comment by tmatth** [comment]
Fixed in 4232
