### ISSUE TITLE
Unclear state of coverage build status for qt

### ISSUE THREAD

**Issue by rlohning** [google/oss-fuzz#4233]
I can't see qt in [Coverage Builds](https://oss-fuzz-build-logs.storage.googleapis.com/index.html) anymore. Fuzzing builds seem fine.

The last successful build seems to be from July 27th, but qt is not even listed as a failed build. The [only change](https://codereview.qt-project.org/c/qt/qtqa/+/308790) I made since then was to add three corpus files.

Any idea what might be wrong?

**Comment by inferno-chromium** [comment]
We switched to a new build system infrastructure in last few days. @kabeer27 @oliverchang - thoughts ? i dont see qt in coverage tab of https://oss-fuzz-build-logs.storage.googleapis.com/index.html either

**Comment by oliverchang** [comment]
Tthe latest qt logs should show on the coverage tab of https://oss-fuzz-build-logs.storage.googleapis.com/index.html now.

**Comment by rlohning** [comment]
Yes, they do. Thank you.
