### ISSUE TITLE
infra/gcb code cleanup and Symlinks migration/merging into the new build pipeline folder

### ISSUE THREAD

**Issue by kabeer27** [google/oss-fuzz#4238]
After the migration of the new build pipeline, a lot of code from the old infrastructure can be removed.
Files to remove:
-infra/gcb/sync.py
-infra/gcb/wait_for_build.py
-infra/gcb/requirements.txt
-infra/gcb/cancel.py
-Any jenkins related files/configs that are not required anymore

Code to remove:
-All the def main() from infra/gcb/*.py files
-Some function calls that are not being used anymore by the new cloud functions Example the old run_build from build_project.py
-Imports that are not being used example from oauth2client.client import GoogleCredentials in build_project.py
-Any other imports that were being used by def main() or other functions that are not required anymore

Code to replace:
-~Make skip build better, use something else rather than sys.exit()~
-Better to way to kill cloud datastore processes in test_utils.py

Files to move:
-All the infra/gcb/*.py files leftover

Some other improvements:
- Can restructure the directory a little bit example all the cloud functions / requirements / related files can be moved into a different folder and testing files can be moved to a /tests folder.
- Some more scripts can be written that trigger coverage builds since they also have individual schedulers now.

Please also have an additional look in case i might have missed something

@oliverchang @inferno-chromium

**Comment by jonathanmetzman** [comment]
The infra/gcb directory was removed. This is complete.
