### ISSUE TITLE
Please give me access to the LibreOffice project

### ISSUE THREAD

**Issue by stbergmann** [google/oss-fuzz#424]
I've just signed a CLA as sbergman@redhat.com, linking that address to this github account. caolanm will approve to give me access to LibreOffice.

**Comment by Dor1s** [comment]
Could you please upload a pull request with an update of https://github.com/google/oss-fuzz/blob/master/projects/libreoffice/project.yaml ? This would help to automatically verify CLA stuff + @caolanm can explicitly approve the PR.
