### ISSUE TITLE
High startup_crash_percent due to "--entropic" and "--focus_function" combination

### ISSUE THREAD

**Issue by PetteriAimonen** [google/oss-fuzz#4242]
Since 2020-06-17, nanopb project has had `startup_crash_percent` of about 25%, while previously this was zero.

Looking at the logs, the error is:

<pre>
Component revisions (build r202007292150):
Nanopb: 0e0a1895be41840b706f38d074fef0ac65424977
Afl: 82b5e359463238d790cadbe2dd494d6a4928bff3

Return code: 1

Command: /mnt/scratch0/clusterfuzz/resources/platform/linux/minijail0 -f /tmp/tmpucm_1jvq -U -m '0 1337 1' -T static -c 0 -n -v -p -l -I -k proc,/proc,proc,1 -P /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-368/tmpeed5v6ca -b /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-368/tmpi207eyq3,/tmp,1 -b /lib,/lib,0 -b /lib32,/lib32,0 -b /lib64,/lib64,0 -b /usr/lib,/usr/lib,0 -b /usr/lib32,/usr/lib32,0 -b /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_nanopb_0d13a56e603333720afa1efa2ce7941f12a57151/revisions,/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_nanopb_0d13a56e603333720afa1efa2ce7941f12a57151/revisions,0 -b /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds-dataflow_nanopb_65be4f46a6f96f926114c92f399e51931bb0505d/dataflow,/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds-dataflow_nanopb_65be4f46a6f96f926114c92f399e51931bb0505d/dataflow,0 -b /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_nanopb_0d13a56e603333720afa1efa2ce7941f12a57151/revisions,/out,0 -b /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-368/new,/new,1 -b /mnt/scratch0/clusterfuzz/bot/inputs/data-bundles/nanopb_fuzztest,/nanopb_fuzztest,1 -b /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases,/fuzzer-testcases,1 /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_nanopb_0d13a56e603333720afa1efa2ce7941f12a57151/revisions/fuzztest -timeout=25 -rss_limit_mb=2560 -data_flow_trace=/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds-dataflow_nanopb_65be4f46a6f96f926114c92f399e51931bb0505d/dataflow/fuzztest_dft -focus_function=auto -entropic=1 -artifact_prefix=/fuzzer-testcases/ -max_total_time=6250 -print_final_stats=1 /new /nanopb_fuzztest
Bot: oss-fuzz-linux-zone3-worker-nanopb-f1gh
Time ran: 0.0168917179107666

ERROR: The parameters `--entropic` and `--focus_function` cannot be used together.
cf::fuzzing_strategies: dataflow_tracing:1,entropic:1
</pre>

I haven't been able to find out where these options are coming from.

Is there something project-specific that could be changed or is this a bug in the infrastructure?

**Comment by inferno-chromium** [comment]
Thanks for catching this, this is a bug with how we pick fuzzing strategies in fuzzing runs. Looks like entropic and focus_function can't be used together. 

@Dor1s - can you please help to fix this next week when you are back.

**Comment by Dor1s** [comment]
Uploaded https://github.com/google/clusterfuzz/pull/1942

**Comment by inferno-chromium** [comment]
This is fixed, thanks @Dor1s for fixing this.
https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2020-07-31&date_end=2020-08-06&fuzzer=libFuzzer&job=libfuzzer_asan_nanopb&project=nanopb
