### ISSUE TITLE
`ASAN_OPTIONS=handle_segv=2` prevents application-level segfault handling

### ISSUE THREAD

**Issue by alexcrichton** [google/oss-fuzz#4264]
Last night on the Wasmtime project we got https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24695 as a fuzz bug connected to https://oss-fuzz.com/testcase-detail/6205251766714368. I can reproduce this locally if I set the `ASAN_OPTIONS=handle_segv=2` environment variable. I believe though that this may be a problem with fuzzing, since if I don't set `handle_segv` (or if I set it to 1) then the test case runs fine. In Wasmtime we're a wasm JIT compiler and we use segfaults for out-of-bounds memory accesses of the guest wasm code (which we catch and handle), and in this test case I've confirmed that an out of bounds trap is indeed supposed to happen.

Is the `handle_segv=2` option something new in oss-fuzz? (we haven't gotten an issue before this point) Should we update our `default.options` to `handle_segv=1` or something like that?

**Comment by inferno-chromium** [comment]
Yes sorry about that, we would need project that need their own handler to set handle_* flags=1 in their fuzz target options file. https://github.com/google/clusterfuzz/pull/1952

**Comment by alexcrichton** [comment]
Ah no worries, thanks for the tip! I've made that change in https://github.com/google/oss-fuzz/pull/4266
