### ISSUE TITLE
base-clang image seems to be broken

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#4270]
@jonathanmetzman reported this on chat

https://console.cloud.google.com/cloud-build/builds/1a03608a-e377-402f-aa01-48e8e66f0d42;step=2?project=oss-fuzz-base

click "View Raw" to see the full log, but sadly I don't see anything actionable in there...

probably after this roll: https://bugs.chromium.org/p/chromium/issues/detail?id=1112148

**Comment by inferno-chromium** [comment]
Looks like 3 breakages, but atleast the last one is due to
https://chromium.googlesource.com/chromium/src/tools/clang/+/e6863f878319bc31e7f454132b655251f9761fc2%5E%21/#F1

```
-CLANG_REVISION = '1bd7046e4ce0102adef6096a12a289d7f94b8c73'
-CLANG_SVN_REVISION = 'n362116'
-CLANG_SUB_REVISION = 2
+# This is the output of `git describe` and is usable as a commit-ish.
+CLANG_REVISION = 'llvmorg-12-init-1771-g1bd7046e'
+CLANG_SUB_REVISION = 3
```

**Comment by inferno-chromium** [comment]
Trying https://github.com/google/oss-fuzz/pull/4275

**Comment by inferno-chromium** [comment]
This is fixed.

**Comment by Dor1s** [comment]
yay, thanks a lot @inferno-chromium !

**Comment by inferno-chromium** [comment]
MOre random failures
https://pantheon.corp.google.com/cloud-build/builds/8f82d93f-be57-4d4e-afe3-f50d26c946e1;step=2?project=oss-fuzz-base

```
Step #2: [3835/4801] Building CXX object tools/clang/lib/CodeGen/CMakeFiles/obj.clangCodeGen.dir/VarBypassDetector.cpp.o
Step #2: FAILED: /usr/bin/c++ -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/clang/lib/ASTMatchers/Dynamic -I/src/llvm-project/clang/lib/ASTMatchers/Dynamic -I/src/llvm-project/clang/include -Itools/clang/include -Iinclude -I/src/llvm-project/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -O3 -DNDEBUG  -fno-exceptions -fno-rtti -std=c++14 -MD -MT tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o -MF tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o.d -o tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o -c /src/llvm-project/clang/lib/ASTMatchers/Dynamic/Registry.cpp
Step #2: c++: internal compiler error: Killed (program cc1plus)
Step #2: Please submit a full bug report,
Step #2: with preprocessed source if appropriate.
Step #2: See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Step #2: ninja: build stopped: subcommand failed.
Step #2: The command '/bin/sh -c /root/checkout_build_install_llvm.sh' returned a non-zero code: 1
Finished Step #2
ERROR
ERROR: build step 2 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
```

**Comment by Dor1s** [comment]
The build keeps failing, but I don't see the actual cause in the logs (it's truncated). Will run it locally now...

**Comment by Dor1s** [comment]
Hm, no problem locally. Here comes a traditional dumb guess: what if we run out of resources? @oliverchang are we still using the same machine type for these builds?

**Comment by oliverchang** [comment]
Yep, we're still running on n1-highcpu-32.

**Comment by Dor1s** [comment]
Thanks Oliver! Let's try https://github.com/google/oss-fuzz/pull/4311 then

**Comment by oliverchang** [comment]
Looks like this is succeeding now in about 46 mins. Previous runs without the thread limit ran in 40~ mins so not much of a regression. Should we close?

**Comment by Dor1s** [comment]
yay, yeah, ninja by default should've been using 32 threads previously, which isn't much more useful than 16 given that there are just 16 physical cores.
