### ISSUE TITLE
Build failure not being filed

### ISSUE THREAD

**Issue by tomrittervg** [google/oss-fuzz#4278]
rnp stopped building on Aug 4th and hasn't succeeded since. In the past, 2 successive failed build jobs caused a build failure bug to be logged; but not this time. Has the behavior changed; or is this a bug in oss-fuzz, or perhaps something else...

**Comment by Dor1s** [comment]
/cc @oliverchang to take a look next week

looks like we didn't have build failures bugs opened or closed in the past 10 days: https://bugs.chromium.org/p/oss-fuzz/issues/list?sort=-id&colspec=ID%20Type%20Component%20Status%20Proj%20Reported%20Owner%20Summary%20Opened%20Closed&q=Type%3DBuild-Failure&can=1

issue 24345 was closed manually 4 days ago

**Comment by inferno-chromium** [comment]
```
 'successes'
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/webapp2.py", line 604, in dispatch
    return method(*args, **kwargs)
  File "/srv/libs/handler.py", line 97, in wrapper
    return func(self)
  File "/srv/handlers/cron/oss_fuzz_build_status.py", line 281, in get
    self._check_last_get_build_time(build_status, build_type)
  File "/srv/handlers/cron/oss_fuzz_build_status.py", line 260, in _check_last_get_build_time
    for build in itertools.chain(build_status['successes'],
KeyError: 'successes'
```

**Comment by inferno-chromium** [comment]
Seems to work - https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24747
