### ISSUE TITLE
Oss-fuzz now thinks that sigaction() does not initialize its oact output parameter.

### ISSUE THREAD

**Issue by bobfriesenhahn** [google/oss-fuzz#4299]
oss-fuzz 24690 illustrates what I believe is a new problem in the oss-fuzz framework, or the C library it is using.  The problem is that this code:

sigaction(signo, &act, &oact)

should be initializing the memory in oact when sigaction returns 0 but oss-fuzz says that the access is to uninitialized memory.  The oss-fuzz complaint goes away by doing a memset of oact prior to invoking sigaction.

**Comment by inferno-chromium** [comment]
aha, we now let sanitizer use its own signal handler, see https://github.com/google/oss-fuzz/issues/4264. Does it impact all of your fuzzers, you can add handle_sigfpe=1 or 0 in impacted fuzz targets.

**Comment by bobfriesenhahn** [comment]
I can understand the harm if a program's own signal handlers interfere with what oss-fuzz needs.  What is interesting about this specific case is that the GraphicsMagick library has code which deduces if a signal handler has already been set (is no longer the default of SIG_DFL) and if so, it skips registering its own signal handler.  If I have written my code correctly, then the original signal handlers would have been restored.  The reason for this approach is that it was discovered that there were some usages where the signal handlers were set up in advance and there was no feasible way for the user to fix the signal handlers after the fact (e.g by the Java VM).

It appears that the method that oss-fuzz is using to force its own signal handler is not entirely sufficient.  It should either allow sigaction to report the existing actual signal handling which is registered or it should update oact with default values, even if the signal handling was not allowed to be changed.  In particular, it should not treat the oact data as uninitialized!

**Comment by bobfriesenhahn** [comment]
I can understand the harm if a program's own signal handlers interfere with what oss-fuzz needs.  What is interesting about this specific case is that the GraphicsMagick library has code which deduces if a signal handler has already been set (is no longer the default of SIG_DFL) and if so, it skips registering its own signal handler.  If I have written my code correctly, then the original signal handlers would have been restored.  The reason for this approach is that it was discovered that there were some usages where the signal handlers were set up in advance and there was no feasible way for the user to fix the signal handlers after the fact (e.g by the Java VM).

It appears that the method that oss-fuzz is using to force its own signal handler is not entirely sufficient.  It should either allow sigaction to report the existing actual signal handling which is registered or it should update oact with default values, even if the signal handling was not allowed to be changed.  In particular, it should not treat the oact data as uninitialized!

**Comment by bobfriesenhahn** [comment]
I can understand the harm if a program's own signal handlers interfere with what oss-fuzz needs.  What is interesting about this specific case is that the GraphicsMagick library has code which deduces if a signal handler has already been set (is no longer the default of SIG_DFL) and if so, it skips registering its own signal handler.  If I have written my code correctly, then the original signal handlers would have been restored.  The reason for this approach is that it was discovered that there were some usages where the signal handlers were set up in advance and there was no feasible way for the user to fix the signal handlers after the fact (e.g by the Java VM).

It appears that the method that oss-fuzz is using to force its own signal handler is not entirely sufficient.  It should either allow sigaction to report the existing actual signal handling which is registered or it should update oact with default values, even if the signal handling was not allowed to be changed.  In particular, it should not treat the oact data as uninitialized!

**Comment by bobfriesenhahn** [comment]
I can understand the harm if a program's own signal handlers interfere
with what oss-fuzz needs.  What is interesting about this specific
case is that the GraphicsMagick library has code which deduces if a
signal handler has already been set (is no longer the default of
SIG_DFL) and if so, it skips registering its own signal handler.  If I
have written my code correctly, then the original signal handlers
would have been restored.  The reason for this approach is that it was
discovered that there were some usages where the signal handlers were
set up in advance and there was no feasible way for the user to fix
the signal handlers after the fact (e.g by the Java VM).

It appears that the method that oss-fuzz is using to force its own
signal handler is not entirely sufficient.  It should either allow
sigaction to report the existing actual signal handling which is
registered or it should update oact with default values, even if the
signal handling was not allowed to be changed.  In particular, it
should not treat the oact data as uninitialized!

**Comment by inferno-chromium** [comment]
So, i talked with libFuzzer folks, it is a bug in libFuzzer, please don't do the options file change i was suggesting, best to just wait for proper libFuzzer fix.

**Comment by hctim** [comment]
Hi Bob, we've fixed the problem upstream: https://reviews.llvm.org/D85797. Thanks for the report!

**Comment by inferno-chromium** [comment]
Note that it can take upto 2 weeks for a new llvm revision to roll in OSS-Fuzz, we appreciate your patience here as this fixes the root cause.
