### ISSUE TITLE
Testcase details page has mis-rendered unicode

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#4326]
https://oss-fuzz.com/testcase-detail/5471030328688640:

![image](https://user-images.githubusercontent.com/772/90336710-9034c300-dfab-11ea-8790-6f5e1865b4c9.png)

This is on latest CrOS stable channel.

**Comment by inferno-chromium** [comment]
@iamarshsingh, can you take a look, i think probably coming from your flask migration.

**Comment by iamarshsingh** [comment]
> @iamarshsingh, can you take a look, i think probably coming from your flask migration.

Weird bug, thanks for tagging will have a look.

**Comment by oliverchang** [comment]
Thanks! This is now fixed.
