### ISSUE TITLE
Rename `sanitizers` key to `configurations` in project.yaml

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#433]
I suggest we rename `sanitizers` key to `configurations` in project.yaml. It will allow us specifying:

```yaml
configurations:
  - address
  - afl
```

Thoughts?

**Comment by oliverchang** [comment]
Hmm, I feel that conflating sanitizer and fuzzing engine might be confusing to some people. What's your motivation for this?

**Comment by inferno-chromium** [comment]
configurations is a pretty confusing word here. and also, i dont think we should mix sanitizers and fuzzing engines.
sanitizers:
    - address
    - memory
fuzzing_engines:
   - afl
   - libfuzzer
?

**Comment by inferno-chromium** [comment]
Also, that will match our blog post.

OSS-Fuzz combines various fuzzing engines (initially, libFuzzer) with Sanitizers (initially, AddressSanitizer)

**Comment by mikea** [comment]
Agreed, not a good idea.
