### ISSUE TITLE
Test case reproduction is broken

### ISSUE THREAD

**Issue by terrelln** [google/oss-fuzz#4338]
I'm attempting to reproduce a bug following https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-bugs and the workflow is broken.

```
> git clone https://github.com/google/oss-fuzz
> cd oss-fuzz
> python infra/helper.py pull_images
> python infra/helper.py build_fuzzers --sanitizer address --architecture i386 lz4
> python infra/helper.py reproduce lz4 decompress_fuzzer clusterfuzz-testcase-minimized-decompress_fuzzer-5720493764378624
Running: docker run --rm --privileged -i -v /Users/terrelln/repos/oss-fuzz/build/out/lz4:/out -v /Users/terrelln/repos/oss-fuzz/clusterfuzz-testcase-minimized-decompress_fuzzer-5720493764378624:/testcase -t gcr.io/oss-fuzz-base/base-runner reproduce decompress_fuzzer -runs=100
+ FUZZER=decompress_fuzzer
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ run_fuzzer decompress_fuzzer -runs=100 /testcase
/out/decompress_fuzzer -rss_limit_mb=2560 -timeout=25 -runs=100 /testcase /tmp/decompress_fuzzer_corpus < /dev/null
INFO: Seed: 993877077
INFO: Loaded 1 modules   (5591 inline 8-bit counters): 5591 [0x8269ed0, 0x826b4a7),
INFO: Loaded 1 PC tables (5591 PCs): 5591 [0x821caf0,0x82279a8),
Not a directory: /testcase; exiting
```

I tested locally and it isn't fuzzing. The problem is that it passes both `/testcase` and the directory `/tmp/decompress_fuzzer_corpus`. If the directory `/tmp/decompress_fuzzer_corpus` is removed from the command line it should work.

**Comment by oliverchang** [comment]
@Dor1s most likely due to https://github.com/google/oss-fuzz/pull/4324 ?

**Comment by Dor1s** [comment]
Yes, very likely. Although I was testing this functionality too before landing, weird. I’ll take a look, sorry for the trouble.

**Comment by Dor1s** [comment]
Looking now. Sorry for the delay, I'm OOO, but this seems important since it affects multiple users.

**Comment by inferno-chromium** [comment]
@Dor1s - should we revert your change, and you can look at it next week when you are back ?

**Comment by Dor1s** [comment]
No, that would break the other thing -- `reproduce` won't use custom options, and `firefox` project would not work as expected. I'm testing a patch locally already, should be uploading soon

**Comment by Dor1s** [comment]
I merged #4367 and kicked off base-images build. In 3 hours you can try running `python infra/helper.py pull_images` to pull an updated base-runner image. The `reproduce` command should work correctly after that. Sorry for the trouble and thanks a lot for reporting the issue!

**Comment by Dor1s** [comment]
@terrelln did you have a chance to verify that the issue is fixed?

**Comment by jwhui** [comment]
@Dor1s , I did verify the fix and it works as expected now. Thanks!

**Comment by Dor1s** [comment]
Thanks for confirming!

**Comment by Jakuje** [comment]
Sigh ... just spent half a day with this, figuring out what is wrong with this before I updated the images. Now, I can too confirm it works.

**Comment by Dor1s** [comment]
@jonathanmetzman this sounds like one more argument supporting your idea of pulling new images automatically :)

**Comment by terrelln** [comment]
Thanks for fixing this @Dor1s!
