### ISSUE TITLE
Unable to build fuzzers in leptonica/prog/fuzzers using a shell script

### ISSUE THREAD

**Issue by DanBloomberg** [google/oss-fuzz#4341]
As suggested, we have put ossfuzz fuzzers for leptonica in the project:
      github.com/danbloomberg/leptonica
They are in the prog/fuzzer directory, along with the script for building them:
     https://github.com/DanBloomberg/leptonica/blob/master/prog/fuzzing/oss-fuzz-build.sh

With help from the ossfuzz team, I attempted to write a shell script to build the leptonica fuzzers, that calls the oss-fuzz-build.sh script above.  The attempt has so far been unsuccessful.

leptonica has dependencies on several image I/O libraries (tiff, jpeg, png, jp2k, webp, gif).
The script I am using is makefuzz.sh:
    [makefuzz.sh.gz](https://github.com/google/oss-fuzz/files/5104870/makefuzz.sh.gz)

Clang-9 on my linux box is 'broken'.  When I tried using it, I was unable to build the tiff library.
So I used clang-11, taken from the script that the ossfuzz team uses to build the tools:
   https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-clang/checkout_build_install_llvm.sh
I modified it slightly to define variables like $SRC and $WORK:
    [install-llvm.sh.gz](https://github.com/google/oss-fuzz/files/5104878/install-llvm.sh.gz)

Using the clang-11 versions of clang and clang++, along with my makefuzz.sh script, the functions compiled but were unable to link.  Here is the log file:
      [fuzz.log](https://github.com/google/oss-fuzz/files/5104905/fuzz.log)

Abhishek (aarya@) suggested that the appropriate team for this is dynamic-tools@, and specifically mascasa@

I've put the effort into building fuzzers because it's much easier to debug problems if I can modify the source code and run the fuzzer.  This also would allow me to verify that the problem has been finished.  Without running the fuzzer, I can only look at the source code.  Any help you can give to fix the problem would be greatly appreciated.

The documentation on the ossfuzz site for doing this is not helpful to someone like me who doesn't already know the fuzzing system or the issues with clang.  If we can get this to work, it would be nice to use the working scripts as a template to show how this is done.

**Comment by morehouse** [comment]
The link errors don't appear related to fuzzing... 

I noticed the following warnings, that may be related to the undefined references:

```
*** Warning: Linking the shared library liblept.la against the
*** static library //tmp/fuzz/leptonica/lib/libjbig.a is not portable!

*** Warning: Linking the shared library liblept.la against the
*** static library //tmp/fuzz/leptonica/lib/libzstd.a is not portable!

*** Warning: Linking the shared library liblept.la against the
*** static library //tmp/fuzz/leptonica/lib/libwebp.a is not portable!

*** Warning: Linking the shared library liblept.la against the
*** static library //tmp/fuzz/leptonica/lib/libpng.a is not portable!
```

**Comment by oliverchang** [comment]
I don't think this is an issue anymore.
