### ISSUE TITLE
Coverage builds seem to be broken due to "Malformed coverage data"

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#4348]
I'm not sure what's going on but it seems since Aug 20 some coverage builds have been failing

https://oss-fuzz-build-logs.storage.googleapis.com/index.html#systemd
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#ffmpeg
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#curl

**Comment by inferno-chromium** [comment]
@Dor1s - post perf/ can you please help with this. i am suspecting https://reviews.llvm.org/D85116 but developer feels otherwise.

**Comment by Dor1s** [comment]
Looks like Chromium coverage bots have recovered, let me try doing a roll locally and generating coverage for some of the projects mentioned above.

**Comment by Dor1s** [comment]
Tried curl and systemd. Both produced good reports, but I forgot to re-built `base-runner`, which might be important (though not likely), re-trying.

**Comment by Dor1s** [comment]
Yep, looks good to. Seems like we're lucky today and can just revert Abhishek's revert and hope for the best :)

**Comment by Dor1s** [comment]
Closing this since https://github.com/google/oss-fuzz/pull/4426 is uploaded for review.
