### ISSUE TITLE
CI doing coverage builds on arbitrary projects

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#4371]
In https://github.com/google/oss-fuzz/pull/4369
"Project tests / build (libfuzzer, coverage, x86_64) (pull_request)" fails.
But I don't even know why it is doing this build for that PR since the PR is for spidermonkey, which I think shouldn't have coverage builds because it doesn't use coverage-guided fuzzing.
@inferno-chromium @Dor1s I don't remember adding coverage builds to CI, do you know if it was added recently?
I'm guessing we do coverage builds for everything on CI. To fix this we would need to exempt projects with "fuzzer: none"

**Comment by Dor1s** [comment]
I think it was added when we migrated off Travis. I was also confused at first and we disabled it for non `c/c++` language attribute, so "fuzzing_engine: none` seems to be another case we need to account for.

**Comment by inferno-chromium** [comment]
Maybe need to fix something here - https://github.com/google/oss-fuzz/blob/master/infra/ci/build.py#L137
