### ISSUE TITLE
Repeated false issues

### ISSUE THREAD

**Issue by PhilipHazel** [google/oss-fuzz#4375]
Hello. Several times now there has been a PCRE2 issue such as  25021 and 25209 which claims there is a build failure. Then the next day I get another message saying all is well. Nothing has changed in the PCRE2 code. Maybe this is some borderline timeout thing? (I think I once got a timeout error that likewise went away of its own accord.) This is not a problem for me, but I figured somebody ought to know.
Philip Hazel
Philip.Hazel@gmail.com

**Comment by jonathanmetzman** [comment]
Thank you for reporting this.
We recently changed the infra we used to build so we can support things like multiple builds per day.
I agree these "failures" don't look real so I suspect maybe the new infra might need some fixes.

@oliverchang neither of these failures (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25021&q=25021&can=2 https://oss-fuzz-build-logs.storage.googleapis.com/log-ec994186-c298-4a16-9fcc-8edddc5c07a1.txt https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25209&q=25209&can=2 https://oss-fuzz-build-logs.storage.googleapis.com/log-da7b6c06-6188-433d-b5e9-f0bcee428b0d.txt) look real to me. Could the new build system with functions be slightly broken?

**Comment by oliverchang** [comment]
Didn't look too closely into this (and unfortunately logs are truncated for some reason) but it seems like it's failing during the coverage report upload step. Not sure why yet though

**Comment by oliverchang** [comment]
Closing as stale.
