### ISSUE TITLE
Have single source of truth for determining builds supported by a project in infra code

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#4376]
Right now I know infra/ci/build.py has its own implementation.
I bet infra/build has its own implementation.
I'm not sure if there are any others.
We should only have one.

**Comment by Dor1s** [comment]
Do you mean the combination of the default configurations + the `project.yaml` parsing logic?

**Comment by jonathanmetzman** [comment]
Exactly.
