### ISSUE TITLE
[cifuzz] consider making bad build checking optional

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#4377]
I think bad build checking is mainly useful for OSS-Fuzz projects so that they can easily catch bad builds as they are committed instead of waiting for OSS-Fuzz to report it.
But I think it might be a waste of time to do bad build checking in CIFuzz since CIFuzz will run the fuzzers.
I'm going to look into how much time we spend on this and consider making it opt-in if I think it is wasting too much time.

**Comment by evverx** [comment]
> But I think it might be a waste of time to do bad build checking in CIFuzz since CIFuzz will run the fuzzers.

Unless I'm mistaken, it's possible for "small" fuzz targets (where the number of edges is less than 100) to run successfully and fail during the build check at the same time.

**Comment by jonathanmetzman** [comment]
This is a fair point. Maybe we should just do the static checks then. But it's probably wasteful to run all fuzzers for 30 seconds and then run them on their seed corpora (ignoring that usecase I think it helps with) if we will fuzz for real later.
