### ISSUE TITLE
[builds] Rebuild base-image and base-runner everytime a project image is built.

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#4378]
@Dor1s discussed this on chat and I wanted to be sure I didn't forget.
Basically, changing base-builder/runner can be error prone because you have to remember to rebuild it before building a project image to test your change. We don't do this in CI, so CI can't verify your changes either.
If instead we always rebuild these images, you won't make this mistake.
I don't think this will slowdown the typical usecase because as long as those images have been pulled and are up to date with the oss-fuzz repo, building base-builder/runner should all be cache hits.
I don't want to do this for base-clang because I don't want to rebuild it when there is a cache miss since it will take forever on most users machines.
If we want to avoid burdening users, then it would probably be a good idea to do this just on CI. We can tell CI to rebuild base-image/base-builder whenever those files are changed and then have it also do a build of some random project to verify these changes.

**Comment by Dor1s** [comment]
@jonathanmetzman would you mind being an owner for this, to increase the odds of not forgetting, plus this was fully your idea! :)

**Comment by jonathanmetzman** [comment]
We do this in CI. I don't think we should do it locally because there's a good chance users will have to spend a lot of time rebuilding if there is a cache miss. I consider this fixed.
