### ISSUE TITLE
[spidermonkey] Missing lib

### ISSUE THREAD

**Issue by tysmith** [google/oss-fuzz#4383]
I tried to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19014 in #4369 with the assumption that spidermonkey-ufi was working. I don't think it worked.

Is there a way for a project to add `libc++.so.1` (or any libs) to the fuzzing/execution environment?

**Comment by tysmith** [comment]
Uh hmm. I just built spidermonky locally using (no oss-fuzz scripts) and got:
```
$ ldd dist/bin/js
	linux-vdso.so.1 (0x00007ffd91bde000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fac2afea000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fac2ac4c000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fac2aa2f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fac2a82b000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fac2a4a2000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fac2a29a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fac2a082000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fac29c91000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fac32b58000)
```

With oss-fuzz project scripts I get:
```
$ ldd code/oss-fuzz/build/out/spidermonkey/js
	linux-vdso.so.1 (0x00007ffc4f6e6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcc5c28b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcc5beed000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fcc5bcd0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fcc5bacc000)
	libc++.so.1 => not found
	libc++abi.so.1 => not found
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fcc5b8c4000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fcc5b6ac000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcc5b2bb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcc6429e000)
```

So must be missing something to build with stdlibc++

**Comment by tysmith** [comment]
```
Step #4: CXXFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope  -stdlib=libc++
```

So `-stdlib=libc++` is set by the oss-fuzz build system and the execution environment is missing `libc++.so.1`? Is this because `engine` is `none`?

**Comment by inferno-chromium** [comment]
You can add any library to $OUT and then change rpath on binary to point to it. E.g. https://github.com/google/oss-fuzz/blob/6c77e8cd0e75e79dca73298bc6fac3f76a4babbc/projects/zeek/build.sh#L65

Regarding point about -stdlib=libc++, build_fuzzers command should be printing CFLAGS, CXXFLAGS, do you see it there - https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile#L87

**Comment by jonathanmetzman** [comment]
+1, check_build is pretty good at verifying this works. Unfortunately it doesn't do this for engineless since there isn't a clear way to run the target like there is with libfuzzer/afl/honggfuzz builds.

**Comment by DavidKorczynski** [comment]
Closing this as it was solved by https://github.com/google/oss-fuzz/pull/5646
