### ISSUE TITLE
Do bad build check in build_fuzzers unless opted-out

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#4394]
Currently to properly check a build on GCB will pass OSS-Fuzz users need to do:
1. build_image
2. build_fuzzers
3. check_build
I think it's probably a good idea to do check_build in step 2 so people don't forget.
This might slowdown some other usecases but we can have an extra flag (`no_check_build`) to accommodate this.

**Comment by Dor1s** [comment]
Sounds reasonable to me! Also both `build_fuzzers` and `check_build` require the same command line arguments (engine + sanitizer).

**Comment by oliverchang** [comment]
Closing as stale.
