### ISSUE TITLE
Requesting a review on PRs?

### ISSUE THREAD

**Issue by cmeister2** [google/oss-fuzz#4401]
Is there an automated way of requesting a review on PRs? 

https://github.com/google/oss-fuzz/pull/4388 has been ready to go for 4 days but hasn't been reviewed yet - I'm wondering if I'm missing something obvious like **`r?`** or something. It's been a while since my last PR!

**Comment by inferno-chromium** [comment]
Nope, just ping PR again. Sometimes it gets lost with too many new prs.
