### ISSUE TITLE
Segfault with dataflow sanitizer in php project

### ISSUE THREAD

**Issue by nikic** [google/oss-fuzz#4402]
I'm currently testing whether the dataflow sanitizer can be enabled for the php project. After fixing [the usual](https://github.com/php/php-src/commit/a8687804bb73deff52206f3dec88880fc22ad9b0) on the php-src side, I get a startup crash for all fuzzers. 

Running ``gdb --args /out/php/php-fuzz-json` I get the following stack trace:

```
#0  0x00005555563866c9 in __dfsw___sanitizer_cov_trace_const_cmp4 ()
    at /src/libfuzzer/dataflow/DataFlowCallbacks.cpp:79
#1  0x000055555606b0fb in dfs$zend_hash_check_size () at Zend/zend_hash.c:119
#2  0x0000555556066bce in dfs$_zend_hash_init_int () at Zend/zend_hash.c:261
#3  0x0000555556066a4d in dfs$_zend_hash_init () at Zend/zend_hash.c:266
#4  0x0000555555e86786 in dfs$sapi_globals_ctor () at main/SAPI.c:57
#5  0x0000555555e86712 in dfs$sapi_startup () at main/SAPI.c:81
#6  0x0000555556386e61 in dfs$fuzzer_init_php () at sapi/fuzzer/fuzzer-sapi.c:138
#7  0x0000555556386b75 in dfs$LLVMFuzzerInitialize () at sapi/fuzzer/fuzzer-json.c:58
#8  0x0000555556384220 in main () at /src/libfuzzer/dataflow/DataFlow.cpp:160
```
At the following location:
```
   │0x5555563866a1 <__dfsw___sanitizer_cov_trace_const_cmp4+1>      mov    %rsp,%rbp                          │
   │0x5555563866a4 <__dfsw___sanitizer_cov_trace_const_cmp4+4>      push   %r14                               │
   │0x5555563866a6 <__dfsw___sanitizer_cov_trace_const_cmp4+6>      push   %rbx                               │
   │0x5555563866a7 <__dfsw___sanitizer_cov_trace_const_cmp4+7>      mov    %edx,%ebx                          │
   │0x5555563866a9 <__dfsw___sanitizer_cov_trace_const_cmp4+9>      or     %ecx,%ebx                          │
   │0x5555563866ab <__dfsw___sanitizer_cov_trace_const_cmp4+11>     lea    0xb900de(%rip),%rax        # 0x5555│
   │0x5555563866b2 <__dfsw___sanitizer_cov_trace_const_cmp4+18>     mov    0x20(%rax),%r14                    │
   │0x5555563866b6 <__dfsw___sanitizer_cov_trace_const_cmp4+22>     data16 data16 data16 mov %fs:0x0,%rax     │
   │0x5555563866c2 <__dfsw___sanitizer_cov_trace_const_cmp4+34>     mov    -0x10(%rax),%rax                   │
  >│0x5555563866c9 <__dfsw___sanitizer_cov_trace_const_cmp4+41>     or     %bx,(%r14,%rax,2)                  │
   │0x5555563866ce <__dfsw___sanitizer_cov_trace_const_cmp4+46>     pop    %rbx                               │
   │0x5555563866cf <__dfsw___sanitizer_cov_trace_const_cmp4+47>     pop    %r14                               │
   │0x5555563866d1 <__dfsw___sanitizer_cov_trace_const_cmp4+49>     pop    %rbp                               │
   │0x5555563866d2 <__dfsw___sanitizer_cov_trace_const_cmp4+50>     retq                                      │
```
I checked that this is the very first call to __dfsw___sanitizer_cov_trace_const_cmp4(). The code also isn't doing anything interesting around there, so I suspect I'm just holding it wrong. Any pointers?

**Comment by Dor1s** [comment]
It may be blocked on https://github.com/google/oss-fuzz/issues/3388, which is in progress.

**Comment by Dor1s** [comment]
Another thought here is that `LLVMFuzzerInitialize` might be involved too. Does the same crash occur for all fuzz targets?

**Comment by nikic** [comment]
> It may be blocked on #3388, which is in progress.

I don't think this is related to dependencies, as these fuzzers only depend on libc (well, the other dependency is manually built, so also instrumented).

> Another thought here is that LLVMFuzzerInitialize might be involved too. Does the same crash occur for all fuzz targets?

Yeah, the crash is the same for all fuzz targets, in the same place. I haven't verified this precisely, but from a quick look it looks like this may be the first comparison done inside LLVMFuzzerInitialize.

**Comment by Dor1s** [comment]
Thanks @nikias. I'll definitely take a look. I'll be OOO for the next ~10 days, but I'm committed to make it work eventually.

**Comment by nikias** [comment]
Hehe, mention fail :)

**Comment by Dor1s** [comment]
Oops! Thanks @nikic !
