### ISSUE TITLE
make oss-fuzz.com a bit more friendly

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#442]
If I navigate to oss-fuzz.com w/o being logged in, all I see is 'access denied, please login'.
Please add a visible link to https://github.com/google/oss-fuzz so that if anyone comes to oss-fuzz.com
by mistake they know where to go next.

**Comment by inferno-chromium** [comment]
SG, Tanin can you add this please!

**Comment by tanin47** [comment]
I'll add it by tomorrow. Thank you.

**Comment by inferno-chromium** [comment]
Thanks Tanin!

**Comment by kcc** [comment]
Very nice!
