### ISSUE TITLE
base-image needs to roll past https://github.com/llvm/llvm-project/commit/8427885e27813c457dccb011f65e8ded74444e31

### ISSUE THREAD

**Issue by LebedevRI** [google/oss-fuzz#4438]
Current clang in base-image contains https://reviews.llvm.org/D84604,
which is broken and was reverted in https://github.com/llvm/llvm-project/commit/8427885e27813c457dccb011f65e8ded74444e31.

Refs. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25551&q=label%3AProj-librawspeed

**Comment by inferno-chromium** [comment]
We follow Chromium clang roll, which happens every 2 weeks. At this point with 340+ projects, it is hard to roll to latest without testing. Next chromium roll should be happening soonish.

**Comment by LebedevRI** [comment]
I know :) Just for documentation purposes.
Appears to be resolved, thanks.
