### ISSUE TITLE
How to get access to results for my own lib?

### ISSUE THREAD

**Issue by erikd** [google/oss-fuzz#4444]
I am the main dev of https://github.com/erikd/libsndfile . Someone forwarded me an oss-fuzz report for libsndfile, but I can't access it.

> You (email=erik.de.castro.lopo@gmail.com) are not authorized to access this page!
> Please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.

How do I get access?

**Comment by oliverchang** [comment]
Hi, I've added you to https://github.com/google/oss-fuzz/blob/master/projects/libsndfile/project.yaml. Within a few hours you will be granted access.

**Comment by erikd** [comment]
Confirmed. Thanks!
