### ISSUE TITLE
capstone: access to detailed reports

### ISSUE THREAD

**Issue by StalkR** [google/oss-fuzz#4451]
Hello,

I was just working on a couple reports for https://github.com/aquynh/capstone

- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14912 fixed by https://github.com/aquynh/capstone/pull/1684 & https://github.com/aquynh/capstone/pull/1685

- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22236 fixed by https://github.com/aquynh/capstone/pull/1687 & https://github.com/aquynh/capstone/pull/1688

Annoyingly, I couldn't view the detailed report, for example:

> Detailed Report: https://oss-fuzz.com/testcase?key=5666610666012672

brings me to https://oss-fuzz.com/testcase-detail/5666610666012672 which says:

> You (email=stalkr@stalkr.net) are not authorized to access this page!
> 
> Please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.
>
> [Switch account]
> [Logout]

so I'm contacting you as requested if there's anything you can do :)

Thanks!

**Comment by inferno-chromium** [comment]
You need to create a google account with your email address, see https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication. Our reports UI requires google auth, we will probably support github auth at some time in near future.

**Comment by StalkR** [comment]
Yes I used Google Accounts, tried both my GSuite (stalkr@stalkr.net) & Gmail (stalkr@gmail.com) accounts, same error.

> You (email=stalkr@gmail.com) are not authorized to access this page!
> 
> Please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.
> 
> [Switch account]
> [Logout]

**Comment by inferno-chromium** [comment]
You need to submit PR to get yourself added in this project.yaml for capstone - https://github.com/google/oss-fuzz/blob/master/projects/capstone/project.yaml#L5
