### ISSUE TITLE
[grok] 3 fixed and 3 unreproducible bugs

### ISSUE THREAD

**Issue by boxerab** [google/oss-fuzz#4462]
Hello! I have just fixed the following 3 bugs:

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25798&sort=-opened&can=1&q=proj%3Agrok
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25670&sort=-opened&can=1&q=proj%3Agrok
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25651&sort=-opened&can=1&q=proj%3Agrok

I also tried the following bugs with docker image, and I wasn't able to reproduce them:

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25602&sort=-opened&can=1&q=proj%3Agrok
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25556&sort=-opened&can=1&q=proj%3Agrok
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25322&sort=-opened&can=1&q=proj%3Agrok

Can the issue tracker please be updated ?  Thanks!

**Comment by inferno-chromium** [comment]
You should have edit issue privilege now, so you can close these as verified (fixed ones) and wontfix for unreproducible ones.

**Comment by boxerab** [comment]
Cool, thank you!
