### ISSUE TITLE
[astc-encoder] false positives

### ISSUE THREAD

**Issue by solidpixel** [google/oss-fuzz#4481]
This fuzz target:

- `./projects/astc-encoder/astc_encode_decode_ise_fuzzer.cc`

... is hooking in to `astcenc` using internal functions, and throwing unconstrained fuzz data at two entry points which couldn't get sent that data under normal circumstances. It's not trivial to constrain the inputs to these function without using quite a lot of functionality in the compressor, which isn't currently easily accessible as standalone code.

Please can this target be removed for the time being so we stop getting false positives. I'm seeing if we can sign up to the CLA and propose a replacement.

**Comment by Dor1s** [comment]
I've created https://github.com/google/oss-fuzz/pull/4484 to disable the fuzz target for now.

To conveniently change the behavior of the target library, you can patch the code using `#ifdef FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION`, see more in https://llvm.org/docs/LibFuzzer.html#fuzzer-friendly-build-mode

**Comment by alsophian** [comment]
@solidpixel, I'm sorry that the fuzzer we wrote wasn't useful.  I'd be happy to work together to write a better fuzzer; we can follow up on https://github.com/ARM-software/astc-encoder/issues/50.

**Comment by solidpixel** [comment]
No need to apologize - thanks for trying. Talk to you on the astc-encoder ticket =)
