### ISSUE TITLE
Caching tables for LLVMFuzzerTestOneInput

### ISSUE THREAD

**Issue by solidpixel** [google/oss-fuzz#4482]
Is there any way to set up a cache containing dynamically allocated objects which can be used across multiple invocations of `LLVMFuzzerTestOneInput`? If I try today the tests fail because it looks like a memory leak.

Testing the astc-encoder project and it would be useful to have a set of data tables generated once and cached (because that's quite slow compared to the actual function I want to fuzz).

**Comment by Dor1s** [comment]
This sounds like a bad practice in general, as it assumes some shared state between different executions. See more in https://github.com/google/fuzzing/blob/master/docs/good-fuzz-target.md#global-state

If you really need to do that, one idea that comes to mind is to use some static / global objects to cache the data you need.

**Comment by solidpixel** [comment]
Unfortunately, even if I make the root structure a static the data tables it contains that are built during init are stored in some dynamically allocated memory. As soon as the first fuzz pass ends leaksanitizer throws an error.

**Comment by Dor1s** [comment]
Are those tables being created on every execution, or it's fine to do that only once, before starting the actual fuzzing? In case of the latter, https://github.com/google/fuzzing/blob/master/docs/good-fuzz-target.md#one-time-initialization should work. Unless I'm misunderstanding your issue.

**Comment by solidpixel** [comment]
Sorry - user error. I confirm it works if the dynamic memory allocation is directly triggered by the static initializer. 4 orders of magnitude improvement in fuzzer exec/s - nice.
