### ISSUE TITLE
[astc-encoder] Remove project Makefile.patch

### ISSUE THREAD

**Issue by solidpixel** [google/oss-fuzz#4486]
I've now made the modification needed in the Makefile to support oss-fuzz builds upstream, so you no longer need to manually patch that one.  

* Makefile.patch can be removed
* build.sh can be remove the patch step
* Dockerfile can remove the copy of the patch into the Docker image

**Comment by inferno-chromium** [comment]
Can you please submit a PR to remove that file. OSS-Fuzz is a self-service project, also check https://google.github.io/oss-fuzz/advanced-topics/ideal-integration/. We expect most files to stay in your repo, so you dont need to submit any future PRs here.
