### ISSUE TITLE
[astc-encoder] Build should specify VEC=sse2

### ISSUE THREAD

**Issue by solidpixel** [google/oss-fuzz#4487]
The build step for astcenc defaults to AVX2, but the later fuzzer builds run with the settings for no SIMD. 

While not a problem with the current fuzzers it risks issue with alignment in future (as AVX2 aligned load/store needs VECALIGN=32). Propose changing the astcenc build step to use SSE2:

`make -j$(nproc) BUILD=debug VEC=sse2`

... which will be safe with the fuzzer build settings.

**Comment by inferno-chromium** [comment]
Can you please submit a PR to make that change. OSS-Fuzz is a self-service project, also check https://google.github.io/oss-fuzz/advanced-topics/ideal-integration/ [build.sh can live in your repo and then we just call into yours, e.g. https://github.com/google/oss-fuzz/blob/master/projects/gdal/Dockerfile#L23. We expect most files to stay in your repo, so you dont need to submit any future PRs here.
