### ISSUE TITLE
[grok] How to pass a runtime parameter to fuzzer ?

### ISSUE THREAD

**Issue by boxerab** [google/oss-fuzz#4492]
My codec has an option to run in single threaded mode. As the code path for single threaded differs from multi threaded, it turns out many of the fuzz errors were coming from single threaded mode. Is it possible to build two versions of the fuzzer, one for single threaded and one for multi threaded ? Or, what is the best way of passing a parameter into the fuzzer ?

**Comment by Dor1s** [comment]
I would recommend you to have two fuzz targets running in two different modes. If that's the only difference between two fuzz targets, you can use the same source code file and pass different preprocessor defines during compilation, e.g.:

```
$CXX ... -DSINGLE_THREADED ... fuzz_target.cc -o fuzz_target_single_threaded
$CXX ...  ... fuzz_target.cc -o fuzz_target  # or fuzz_target_multi_threaded, it's all up to you
```

and in the code you'd do something like:

```cpp
#if defined(SINGLE_THREADED)
// code to enable single threaded mode
#else
// code to use multi-threaded mode
#endif
```

**Comment by boxerab** [comment]
Thanks, I will try that.
