### ISSUE TITLE
Weird CI failures / potential differences with GCB builder

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#4495]
https://github.com/google/oss-fuzz/pull/4483 is raising some questions, as it seems to be passing all the checks locally. 

I've kicked off a new build after merging that PR. Need to follow up and see if it succeeds. If yes, we have a problem with CI.

//cc @lnicco

**Comment by jonathanmetzman** [comment]
@Dor1s sadly is not working on OSS-Fuzz anymore.
i don't think it we can figure out what build he is referring to and if there is still a problem.
If the problem is simply with AFL's bad build check, then that is tracked in many other places.
Closing.
