### ISSUE TITLE
[simdjson] can not reproduce crash in afl

### ISSUE THREAD

**Issue by pauldreik** [google/oss-fuzz#4497]
There have been two recent reports for simdjson:
 - https://oss-fuzz.com/testcase-detail/5079699967180800 (reliably reproduces=yes)
 - https://oss-fuzz.com/testcase-detail/5715631033548800  (autoclosed, reliably reproduces=No)

Both are for afl address sanitizer builds, but not for the same fuzzer.

Both get have this type of reported error:
```
 ERROR: AddressSanitizer: ILL on unknown address XXXX 
SCARINESS: 10 (signal)
```

# Problem 1 - difficult to use the python helper with afl
I try to reproduce with
```shell
export PROJECT_NAME=simdjson
python infra/helper.py build_fuzzers --engine afl --sanitizer address $PROJECT_NAME
python infra/helper.py reproduce  $PROJECT_NAME fuzz_minifyimpl  /tmp/clusterfuzz-testcase-minimized-fuzz_minifyimpl-5079699967180800
```
But reproduce does not seem to work with afl (I first read https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-bugs, then tried to pass --engine afl as well as reading the output of python infra/helper.py reproduce --help). It crashes with 
```
Reading 18446744073709551615 bytes from -rss_limit_mb=2560
libc++abi: terminating with uncaught exception of type std::length_error: vector
AddressSanitizer:DEADLYSIGNAL
=================================================================
==12==ERROR: AddressSanitizer: ABRT on unknown address 0x00000000000c (pc 0x7fd817feb438 bp 0x7ffc656ceec0 sp 0x7ffc656ce618 T0)
SCARINESS: 10 (signal)
    #0 0x7fd817feb438 in raise (/lib/x86_64-linux-gnu/libc.so.6+0x35438)
    #1 0x7fd817fed039 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x37039)
    #2 0x5659b5 in abort_message (/out/fuzz_minifyimpl+0x5659b5)
    #3 0x569b1e in demangling_terminate_handler() (/out/fuzz_minifyimpl+0x569b1e)
    #4 0x565422 in std::__terminate(void (*)()) (/out/fuzz_minifyimpl+0x565422)
    #5 0x567215 in __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) (/out/fuzz_minifyimpl+0x567215)
    #6 0x5671af in __cxa_throw (/out/fuzz_minifyimpl+0x5671af)
    #7 0x559724 in std::__1::__throw_length_error(char const*) (/out/fuzz_minifyimpl+0x559724)
    #8 0x56511c in std::__1::__vector_base_common<true>::__throw_length_error() const (/out/fuzz_minifyimpl+0x56511c)
    #9 0x51c1a4 in __vallocate /usr/local/bin/../include/c++/v1/vector:995:15
    #10 0x51c1a4 in vector /usr/local/bin/../include/c++/v1/vector:1129:9
    #11 0x51c1a4 in ExecuteFilesOnyByOne /src/libfuzzer/afl/afl_driver.cpp:214:23
    #12 0x51c1a4 in main /src/libfuzzer/afl/afl_driver.cpp:254:12
    #13 0x7fd817fd683f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #14 0x41f218 in _start (/out/fuzz_minifyimpl+0x41f218)
```
so I think this is just because it is invoked the wrong way (fails to read the test case file).
It would be great to be able to reproduce with afl using the helper scripts, not only libfuzzer. Am I doing this wrong? Otherwise it would be nice to have a line or two in the documentation how to reproduce with afl.

# Problem 2 - can't reproduce
I run the following instead:
```shell
python infra/helper.py shell base-runner
# then inside the container...
cd /out/simdjson
base64 -d >crash # paste the base64 encoded input from the crash
./fuzz_minifyimpl crash
Reading 129 bytes from crash
Execution successful
```
which executes without problems. I also tried to run afl-fuzz for a while inside the container, using the crash as the input corpus. No crash found.

What is special about simdjson is that it uses simd. Could this perhaps be something that is rarely used together with afl and adress sanitizer?

**Comment by Dor1s** [comment]
Sorry for the inconvenience. I also can't reproduce this either with libFuzzer or AFL build. @jonathanmetzman do you have any idea?

**Comment by jonathanmetzman** [comment]
AFL is passed libfuzzer arguments so it crashes.
I think it is passed libFuzzer arguments because [this change](https://github.com/google/oss-fuzz/commit/d250f4ffbbdd04554df9e497fc452df2d2cdbd43#diff-09424f338ba176102ce9fa3acabe935c) (I think) made the `reproduce` script invoke `run_fuzzers` with libFuzzer automatically.
I'm somewhat hesitant to change this code since I don't know it well and there aren't tests. Would you mind taking a look @Dor1s ? I can try if you don't have the time right now.

**Comment by jonathanmetzman** [comment]
>Problem 2 - can't reproduce

I can't reproduce this using the correct commandline options myself either.
I think that's because the stacktrace references Haswell but my CPU is skylake. So my guess is that this bug is CPU specific and neither you nor I have the right CPU to repro. Does this make sense based on what you know about the program?

**Comment by pauldreik** [comment]
I hope I can explain how this works, please @lemire verify/amend/correct this:

>  this bug is CPU specific

Short answer: not really.

Long answer:

Simdjson supports multiple "backends", called implementations. On x86 there is haswell/fallback/westmere. At compile time, it will detect which ones exist, and add that implementation. At runtime, the best one is selected as default. However, there is also a possibility of manually selecting an implementation. That is what [this particular fuzzer does](https://github.com/simdjson/simdjson/blob/8b5a89c1361eefb7919eb0233c9abd5c8f3f0544/fuzz/fuzz_minifyimpl.cpp#L35-L36), it is a differential fuzzer set to detect [differences between the implementations](https://github.com/simdjson/simdjson/blob/8b5a89c1361eefb7919eb0233c9abd5c8f3f0544/fuzz/fuzz_minifyimpl.cpp#L46-L48).

There is also another differential fuzzer that [does the same thing](https://github.com/simdjson/simdjson/blob/master/fuzz/fuzz_implementations.cpp), and that does not crash. 

One of these reports was autoclosed because it is flaky, may it be because of it happening on one cpu kind but not another?

To my knowledge, as long as one has a Haswell cpu or better (such as Skylake), it should run all three backends. What kind of cpu do the fuzzer runners use?

**Comment by pauldreik** [comment]
Hmm, I think something is wrong in either how I think this works, or how the fuzzer should loop over the implementations.
I just dug out a Intel(R) Core(TM) i5-2410M which is a Sandy Bridge CPU (later than Westmere, earlier than Haswell) and I got this when trying to run afl-fuzzer:
```
Reading 5 bytes from in/small
Illegal instruction
```
Is some of your fuzzer runners also running a cpu as old as this?

Will investigate this further on this particular Sandy Bridge machine.

**Comment by lemire** [comment]
@jonathanmetzman 

> I think that's because the stacktrace references Haswell but my CPU is skylake. So my guess is that this bug is CPU specific and neither you nor I have the right CPU to repro. Does this make sense based on what you know about the program?

As Paul correctly explain, the term "haswell" here is the name of the kernel/implementation and it is meant to be usable with any processor that is "at least as good as haswell" which includes a bunch of AMD processors, skylake processors... Almost anything that Intel has built in the last 7 years...  It is basically our default kernel/implementation on x64 processors since it is usable with all modern-day processors. We call it haswell because... we needed some name to describe the feature set and it was easy to just pick a microarchitecture.

@pauldreik 

It seems that there are two issues. Runtime dispatching and a potential memory issue. As you clearly explain, the simdjson library will (generally though this can be changed) build three  kernels/implementations on x64 processors: fallback (no SIMD), westmere (SSE), haswell (AVX). On a Sandy Bridge processor, selecting the kernel/implementation with detect_best_supported() (or just going by the default) should select westmere. If you deliberately select the haswell kernel/implementation on a system that does not support AVX, then you will get a crash... very likely... So don't do that. (You are going low-level in the library where there is no runtime check to guard you.) Is runtime dispatching the issue ? It seems unlikely. Here the problem appears to be with the haswell kernel/implementation *and* it has to do with the memory sanitizer.

> Is some of your fuzzer runners also running a cpu as old as this?

How would that be relevant ? It this were the issue, that if, if their hardware was old and you go "illegal instruction" errors because you mistakenly assumed that the haswell kernel/implementation could be safely used, then wouldn't you just get an "illegal instruction" error and not a memory sanitizer error?

**Comment by pauldreik** [comment]
When running on my i5-2410M:
Invoking the afl-built binary directly gives "illegal instruction". Running it through afl-fuzz won't even start, because it says the fuzzer crashes for one of the starting inputs.
Running it with libFuzzer immediately gives "deadly signal" but no more clue.

>  if their hardware was old and you go "illegal instruction" errors because you mistakenly assumed that the haswell kernel/implementation could be safely used, then wouldn't you just get an "illegal instruction" error and not a memory sanitizer error?

I agree. (Note to avoid confusion: address sanitizer and memory sanitizer are two different things, I think you meant address sanitizer here but it is not important.)

Regardless, I think I will have to rewrite the code that selects which implementations are used. It must check the availability at runtime. I can use my i5-2410M to try that out. Hopefully that solves the problem which manifests as a flaky crash.

**Comment by jonathanmetzman** [comment]
I was running this on skylake.
Thanks for the explanations, not sure why I can't repro this then. I could be holding it wrong as well.

**Comment by lemire** [comment]
> I could be holding it wrong as well.

The irony is that we have been fuzzing forever. This is a new fuzzer, which tests a very simple function in our code.

So it is not like we can't fuzz simdjson. It is that we can't fuzz this little new function in simdjson.

**Comment by pauldreik** [comment]
> What do you mean by this? It seems likely those aren't used. But I still think it's mysterious why we can't repro this but it can repro reliably on OSS-Fuzz.

Just to clarify: I meant avx simd. It's not enabled unless -mavx is passed to the compiler, since the default is to compile for a generic target able to run even on old 64 bit targets, right?

Don't forget one of the reports I linked to in the beginning reproduces, but the other one does not and was autoclosed.

**Comment by Dor1s** [comment]
> I think it is passed libFuzzer arguments because this change (I think) made the reproduce script invoke run_fuzzers with libFuzzer automatically. This should also mean that Honggfuzz is broken.

I don't think `infra/helper.py reproduce` was ever supposed to be used with non libFuzzer builds. After we made it rely on `run_fuzzer`, that made it easier to support multiple fuzzing engines, but that would still need some work and reasoning that it's really needed.

@pauldreik it seems like no one is able to reproduce even the first crash, which is claimed to be reproducible by CF. Is that right?

**Comment by Dor1s** [comment]
I tried reproducing that on one of the ClusterFuzz bots and didn't succeed either. Here's the CPU info from that bot:

```
# cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2300.000
cache size	: 46080 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 4600.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

Also, if I try to debug that crash (either locally or on a bot), I'm hitting the instruction where it's supposed to crash, but it doesn't crash for me:

```
(gdb) b *0x4ecf1d
Breakpoint 2 at 0x4ecf1d: file ../src/haswell/simd.h, line 67.
(gdb) r
Starting program: /mnt/scratch0/simdjson/fuzz_minifyimpl clusterfuzz-testcase-minimized-fuzz_minifyimpl-5079699967180800
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
======================= INFO =========================
This binary is built for AFL-fuzz.
To run the target function on individual input(s) execute this:
  /mnt/scratch0/simdjson/fuzz_minifyimpl < INPUT_FILE
or
  /mnt/scratch0/simdjson/fuzz_minifyimpl INPUT_FILE1 [INPUT_FILE2 ... ]
To fuzz with afl-fuzz execute this:
  afl-fuzz [afl-flags] /mnt/scratch0/simdjson/fuzz_minifyimpl [-N]
afl-fuzz will run N iterations before re-spawning the process (default: 1000)
======================================================
Reading 129 bytes from clusterfuzz-testcase-minimized-fuzz_minifyimpl-5079699967180800

Breakpoint 2, (anonymous namespace)::haswell::stage1::json_minifier::step<128ul> (this=0x7fffffffd9e0, 
    block_buf=<optimized out>, reader=...) at ../src/generic/stage1/json_minifier.h:44
44	../src/generic/stage1/json_minifier.h: No such file or directory.
(gdb) i r
rax            0x60d0000000bf	106446469464255
rbx            0x7fffffffdb60	140737488345952
rcx            0x0	0
rdx            0x7fffffffd9f0	140737488345584
rsi            0xffffffffb3e	17592186043198
rdi            0x60d0000000a0	106446469464224
rbp            0x7fffffffdd40	0x7fffffffdd40
rsp            0x7fffffffd9c0	0x7fffffffd9c0
r8             0x60d000000080	106446469464192
r9             0x7ea110	8298768
r10            0x50	80
r11            0x1	1
r12            0x5a21e0	5906912
r13            0x0	0
r14            0x5a16a0	5904032
r15            0x80	128
rip            0x4ecf1d	0x4ecf1d <(anonymous namespace)::haswell::stage1::json_minifier::minify<128ul>(unsigned char const*, unsigned long, unsigned char*, unsigned long&)+797>
eflags         0x246	[ PF ZF IF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) c
Continuing.
Execution successful
```

I also don't understand how is that possible to have ILL on a certain address, if that's address is present in the stacktrace and appears like an address pointing to a valid instruction...

**Comment by Dor1s** [comment]
After collective investigation in the team meeting we figured out that some on the VMs are using Ivy Bridge CPUs, which do not seem to have AVX2 support, and that's why `_mm256_movemask_epi8` is causing an error on those VMs but works just fine on the others.

**Comment by lemire** [comment]
@Dor1s Ok. Good. I think that there was an assumption that the hardware was uniform.  PR https://github.com/simdjson/simdjson/pull/1197 on our end should help to guard the tests.

**Comment by pauldreik** [comment]
Regarding problem 1, may I suggest the following change?
````diff
diff --git a/docs/advanced-topics/reproducing.md b/docs/advanced-topics/reproducing.md
index 9b5e2973..c645ad6b 100644
--- a/docs/advanced-topics/reproducing.md
+++ b/docs/advanced-topics/reproducing.md
@@ -92,6 +92,7 @@ After you build an image and a fuzzer, you can reproduce a bug by running the fo
  ```bash
 $ python infra/helper.py reproduce $PROJECT_NAME <fuzz_target_name> <testcase_path>
  ```
+**Note**: The reproduce command only supports libfuzzer.
 
 For example, to build the [libxml2](https://github.com/google/oss-fuzz/tree/master/projects/libxml2)
````

**Comment by pauldreik** [comment]
I wanted to clarify what happened with this in case someone reads it.

The fuzzer was executing cpu instructions which were not allowed on older cpus. Oss fuzz runs on a a mix of cpus, some of which are of the older type. Eventually, one of those machines would fuzz and an error occured which did not occur on the newer machines. Thus, oss-fuzz reports the test as flaky as the same test case gives different results on different machines.

This was not easy to diagnose because it was not obvious from the crash report what happened.

The remedies are
- let the fuzzer dynamically check for cpu feature so it runs also on older cpus, see https://github.com/simdjson/simdjson/pull/1201 and https://github.com/simdjson/simdjson/pull/1197 
- clarify the documentation for how to reproduce #4504 

The reports have been autoclosed now when the dynamic change is in place.

**Comment by Dor1s** [comment]
@pauldreik thanks for the summary. From our side, we'll store CPU info in ClusterFuzz testcases: https://github.com/google/clusterfuzz/issues/2056

Once that's done, it might make sense to have a quick note in the docs. But maybe not, as such issues seem to occur once every 5-10 thousands bugs, i.e. for the vast majority of the users that information in the docs would be just noise.
