### ISSUE TITLE
Access Request for detailed reports

### ISSUE THREAD

**Issue by tcullum-rh** [google/oss-fuzz#4511]
Hello,

I work for Red Hat Product Security and am analyzing some OpenSC issues because we ship OpenSC in our products. In order to better understand the issues, I am requesting access to view:

https://oss-fuzz.com/testcase?key=5088104168554496
https://oss-fuzz.com/testcase?key=5682366024777728
https://oss-fuzz.com/testcase?key=5226571123392512

Additionally, on a more generic level, is this the proper way to request access to these types of reports in the future? I work on the RHEL team and we ship thousands of packages, many of which have oss-fuzz coverage.

Thanks,
Todd (tcullum@redhat.com)

**Comment by jonathanmetzman** [comment]
Access is generally controlled by each project. So for access to a project's reports, I would go to the directory for that project in OSS-Fuzz (https://github.com/google/oss-fuzz/tree/master/projects) and find the maintainers and ask them permission.
In this case, @devtty1er and @frankmorgner are you OK with @tcullum-rh being given access to reports before they are public?

If project maintainers agree, submit a PR adding yourself to vendor_ccs ([like so](https://github.com/google/oss-fuzz/blob/71f4914c453d1cba4f13dc331830378939ee84d9/projects/libtheora/project.yaml)). You can also just put the PR up for review and tag the owners to ask for permission.

Adding yourself to vendor_ccs gives you access before bugs are public and access to detailed reports. It also signals to us that we shouldn't contact you if there is a problem with the project's OSS-Fuzz integration.

**Comment by frankmorgner** [comment]
@tcullum-rh please check out 

- https://github.com/OpenSC/OpenSC/commit/9d294de90d1cc66956389856e60b6944b27b4817
- https://github.com/OpenSC/OpenSC/commit/6903aebfddc466d966c7b865fae34572bf3ed23e

For full details, please contact your colleague @Jakuje

**Comment by frankmorgner** [comment]
thanks for letting us know about the vendor_ccs option
