### ISSUE TITLE
[grok] playing whack-a-mole with two address fuzzer issues

### ISSUE THREAD

**Issue by boxerab** [google/oss-fuzz#4519]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26142&sort=-opened&can=1&q=proj%3Agrok
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26144&sort=-opened&can=1&q=proj%3Agrok

I cannot repro with the attached test cases. But if I close them as `wontfix`, they
 re-appear a few days later. 

How can I resolve these bugs ?

**Comment by inferno-chromium** [comment]
you can add "ClusterFuzz-Ignore" label if you dont want them to be ever filed again, but this unreproducible aspect is very annoying, unsure what is causing this here.

**Comment by boxerab** [comment]
Thanks. I looked at the code,and there is no way for an illegal operation to happen.
So, sounds like a bug in the fuzzer

**Comment by boxerab** [comment]
@inferno-chromium I don't have permissions to add a label, it seems.

**Comment by inferno-chromium** [comment]
> @inferno-chromium I don't have permissions to add a label, it seems.

Try again, should work now.

**Comment by boxerab** [comment]
Yep, working now. Thanks a lot!
