### ISSUE TITLE
No new openssl builds

### ISSUE THREAD

**Issue by kroeckx** [google/oss-fuzz#453]
It seems the latest openssl build is from 3 days ago?

**Comment by alex** [comment]
I think this might be a pervasive problem, not specific to OpenSSL, it'd explain why oss-fuzz didn't pick up a fix for a crasher we pushed to gnutls 2 days ago.

**Comment by inferno-chromium** [comment]
Thanks for noticing, 6 projects where in hung state, so i killed those hung jenkins threads.

@mikea - just as fyi.

**Comment by kroeckx** [comment]
Since this isn't actually the first time this happens, would it be
possible to monitor for this?

**Comment by mikea** [comment]
We are migrating our build system to GCB (google cloud builder). It should be much faster and more reliable. 

As for openssl, a build by GCB was uploaded today at ~1pm.

**Comment by oliverchang** [comment]
We've completed the migration to GCB. No longer seeing any more problems here.
