### ISSUE TITLE
[chromeos] building oss-fuzz is broken in linux container

### ISSUE THREAD

**Issue by cujomalainey** [google/oss-fuzz#4535]
Building fuzzers in crostini fails with
```
Running: docker run --rm --privileged -i --cap-add SYS_PTRACE -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -e FUZZING_LANGUAGE=c -v /home/cujomalainey/Github/oss-fuzz/build/out/sound-open-firmware:/out -v /home/cujomalainey/Github/oss-fuzz/build/work/sound-open-firmware:/work -t gcr.io/oss-fuzz/sound-open-firmware
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:70: creating device nodes caused \\\"open /var/lib/docker/btrfs/subvolumes/d36f49ccb63b422533662c8a45c6c59466c7ba8b56b6708adb83509b1cf72c53/dev/tty: no such device or address\\\"\"": unknown. 
```

I doubt its oss-fuzz's fault but I figured I would put it here if you guys wanted to 
a. put in a workaround
b. push for a fix in chromeos

also just so others know.

**Comment by Dor1s** [comment]
Thanks @cujomalainey

There are some specifics for installing docker documented at go/installdocker (internal link), maybe any of those are important to be documented for Chrome OS as well.

**Comment by cujomalainey** [comment]
Thanks, doesn't appear to be related, i will try on non-corp device sometime to see if it is a policy issue but appears to be more of a feature missing in the platform.
