### ISSUE TITLE
Ctrl-C not working in libFuzzer's fork mode.

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#4547]
@kcc @morehouse 
hardik from the fuzzing discord told me about this problem and I have been able to repro.
If you compile [this program](https://github.com/hardik05/Damn_Vulnerable_C_Program/blob/master/imgRead_libfuzzer.c) with -fsanitize=fuzzer,address (using OSS-Fuzz's clang) and run it with 
`./a.out -fork=1 -ignore_crashes=1`
Ctrl-C does nothing and libFuzzer will run forever.

**Comment by kcc** [comment]
Yea, I don't know an easy fix. 
(When running locally, I just use `pkill` to kill the remaining processes)

**Comment by hardik05** [comment]
I am doing the same.. using pkill. Any idea why ctrl c don't work in this case?

**Comment by kcc** [comment]
no idea, but I didn't dig.

**Comment by hardik05** [comment]
@morehouse ?

**Comment by morehouse** [comment]
I tried reproducing with ToT clang:
```bash
$ wget https://raw.githubusercontent.com/hardik05/Damn_Vulnerable_C_Program/master/imgRead_libfuzzer.c
$ clang -fsanitize=fuzzer,address imgRead_libfuzzer.c
$ ./a.out -fork=1 -ignore_crashes=1
```
Ctrl+C worked fine for me.  Sometimes I had to press it twice though...

**Comment by mboehme** [comment]
This fixes it for me:
```
diff --git a/compiler-rt/lib/fuzzer/FuzzerUtilLinux.cpp b/compiler-rt/lib/fuzzer/FuzzerUtilLinux.cpp
index 981f9a8..18de684 100644
--- a/compiler-rt/lib/fuzzer/FuzzerUtilLinux.cpp
+++ b/compiler-rt/lib/fuzzer/FuzzerUtilLinux.cpp
@@ -23,6 +23,7 @@ namespace fuzzer {
 int ExecuteCommand(const Command &Cmd) {
   std::string CmdLine = Cmd.toString();
   int exit_code = system(CmdLine.c_str());
+  if (exit_code == 2) exit_code = 72;
   if (WIFEXITED(exit_code))
     return WEXITSTATUS(exit_code);
   return exit_code;
```
Not sure why, but this call to libfuzzer returns with exit code 2 when interrupted. Copying, running, and interrupting the exact same command in the bash terminal gives the proper exit code 72 (`Options.InterruptExitCode`). Even forced the interrupt handler of the child to return immediately with 72. It still ends up as 2.

**Comment by mboehme** [comment]
This is the simple patch:
```
commit fb10537766c6216c43efb29b931787a89ff5bfd3
Author: Marcel Boehme <marcel.boehme@acm.org>
Date:   Sun Nov 8 23:21:14 2020 +0000

    [LibFuzzer] Bug Fix for https://github.com/google/oss-fuzz/issues/4547

diff --git a/compiler-rt/lib/fuzzer/FuzzerUtilLinux.cpp b/compiler-rt/lib/fuzzer/FuzzerUtilLinux.cpp
index 981f9a8..2c25e46 100644
--- a/compiler-rt/lib/fuzzer/FuzzerUtilLinux.cpp
+++ b/compiler-rt/lib/fuzzer/FuzzerUtilLinux.cpp
@@ -1,41 +1,44 @@
 //===- FuzzerUtilLinux.cpp - Misc utils for Linux. ------------------------===//
 //
 // Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
 // See https://llvm.org/LICENSE.txt for license information.
 // SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 //
 //===----------------------------------------------------------------------===//
 // Misc utils for Linux.
 //===----------------------------------------------------------------------===//
 #include "FuzzerPlatform.h"
 #if LIBFUZZER_LINUX || LIBFUZZER_NETBSD || LIBFUZZER_FREEBSD ||                \
     LIBFUZZER_EMSCRIPTEN
 #include "FuzzerCommand.h"
 
 #include <stdlib.h>
 #include <sys/types.h>
 #include <sys/wait.h>
 #include <unistd.h>
 
 
 namespace fuzzer {
 
 int ExecuteCommand(const Command &Cmd) {
   std::string CmdLine = Cmd.toString();
   int exit_code = system(CmdLine.c_str());
-  if (WIFEXITED(exit_code))
-    return WEXITSTATUS(exit_code);
+  if (WIFEXITED(exit_code)) {
+     return WEXITSTATUS(exit_code);
+  } else if (WIFSIGNALED(exit_code) && WTERMSIG(exit_code) == SIGINT) {
+    return 72; // Options->InterruptExitCode
+  }
   return exit_code;
 }
 
 void DiscardOutput(int Fd) {
   FILE* Temp = fopen("/dev/null", "w");
   if (!Temp)
     return;
   dup2(fileno(Temp), Fd);
   fclose(Temp);
 }
 
 } // namespace fuzzer
 
 #endif
```
To properly patch this, though, you might need to route the FuzzingOptions object to ExecuteCommand, which requires extending the FuzzerUtil header and all instances of the ExecuteCommand API. Then, you can retrieve the return value as Options->InterruptExitCode.

**Comment by SyrasX** [comment]
So I currently have the same problem and the fix by @mboehme works fine. Is there a reason why the patch was not accepted for libfuzzer?

**Comment by jonathanmetzman** [comment]
Libfuzzer is unmaintained and is going to be replaced soon.

**Comment by mboehme** [comment]
Wow. What's the replacement?

**Comment by jonathanmetzman** [comment]
> Wow. What's the replacement?

Not sure how public I can be about it. @kcc ?

**Comment by kcc** [comment]
I am hoping to make some form of announcement any day now. 
The team has switched to working on https://github.com/google/centipede.
libFuzzer will remain maintained at some level though, for some time.

**Comment by SyrasX** [comment]
Fix was added to llvm. The issue probably can be closed.

**Comment by jonathanmetzman** [comment]
Thanks! I don't think we have that version of LLVM yet (or will for a while)
