### ISSUE TITLE
honggfuzz isn't running?

### ISSUE THREAD

**Issue by mkj** [google/oss-fuzz#4549]
For dropbear project it has libfuzzer and honggfuzz engines listed but the stats on oss-fuzz.com don't show anything for honggfuzz (404 on one page, a table all zeroes for others).

Is there something I need to set up? 
Running locally with `check_build --engine honggfuzz` works OK, and the built binaries run OK under honggfuzz.

**Comment by inferno-chromium** [comment]
We dont support stats on honggfuzz fuzzing engine atm [only libFuzzer, AFL], we do plan to add it later, but fuzzing is working fine there. filed https://github.com/google/clusterfuzz/issues/2102, closing the issue here.
