### ISSUE TITLE
[yhirose/cpp-httplib] The primary cc is not able to access the bug reports 

### ISSUE THREAD

**Issue by omjego** [google/oss-fuzz#4568]
@inferno-chromium  
@yhirose Who's the maintainer of the cpp-httplib is the [primary contact](https://github.com/google/oss-fuzz/blob/ee423bf3d6195b38fcac59a3b68336bab6dc7001/projects/cpp-httplib/project.yaml#L3) for the reported bugs but he's unable to get access to them.   Is this intended?  See https://github.com/yhirose/cpp-httplib/issues/718

**Comment by inferno-chromium** [comment]
@yhirose - did you try opening the report in chrome, unsure if you were trying in other browser and maybe something failed at rendering level ?

**Comment by yhirose** [comment]
@inferno-chromium, sorry for the late reply. I am now able to access the bug reports. Thanks for your help!
