### ISSUE TITLE
llvm_libcxx targets have invalid filenames

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#4586]
Target filenames appear to be of the form "*.cpp". ClusterFuzz does not allow this, but unfortunately the OSS-Fuzz build still passes (this will be addressed in https://github.com/google/oss-fuzz/issues/4585).

In the meantime, @ldionne would it be possible to remove these extensions from the built fuzz targets?

**Comment by ldionne** [comment]
I'm not sure I understand. What extensions are allowed? I'm building C++ files... so it's pretty common to use `.cpp` as an extension, no?

**Comment by ldionne** [comment]
Also, I tried the reproducing steps in the documentation and I didn't see any failure, which confuses me a bit.

**Comment by oliverchang** [comment]
The issue is that the resulting built binaries have a ".cpp" extension -- this should not be the case as it's not allowed on our fuzzing infrastructure (ClusterFuzz).

As for why you're not seeing any failure, that is an issue on our side to make this behaviour difference more apparent.

**Comment by oliverchang** [comment]
Thanks for fixing the names! However it looks like builds are still failing due to another reason: http://oss-fuzz-build-logs.storage.googleapis.com/index.html#llvm_libcxx
