### ISSUE TITLE
Need to trim output from out-of-memory crashes

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#459]
https://oss-fuzz.com/v2/testcase-detail/4668555062673408 becomes unmanageable for python subprocess to handle. Also, hard to read for devs, can we reduce to maybe just top 5 allocations by default ?

@kcc - thoughts?

**Comment by kcc** [comment]
The function that prints the heap profile looks like this: 
```
    void __sanitizer_print_memory_profile(int top_percent);
```

Perhaps we need to make it look like this:
```
    void __sanitizer_print_memory_profile(int top_percent, int max_number_of_stack_traces);

```

on it.

**Comment by kcc** [comment]
Should be fixed with http://llvm.org/viewvc/llvm-project?rev=297916&view=rev

**Comment by inferno-chromium** [comment]
Confirmed that this is not happening anymore, fix worked. Thanks!
