### ISSUE TITLE
How to stop oss-fuzz complaining about build failures in nonexistent project?

### ISSUE THREAD

**Issue by vitaut** [google/oss-fuzz#4596]
`libfmt` has been renamed to `fmt` in #4533 but I'm getting emails about build failures in the old project which no longer exists: "Issue 26361 in oss-fuzz: libfmt: Fuzzing build failure". Is it possible to stop these emails?

**Comment by inferno-chromium** [comment]
Closed the bug. I dont think anything new will open w.r.t libfmt now. if it does, ping this issue.

**Comment by vitaut** [comment]
Thank you!

**Comment by vitaut** [comment]
Unfortunately oss-fuzz still complains about the build failure even after the issue has been closed: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26361#c6

**Comment by inferno-chromium** [comment]
@vitaut - sorry about this.

@oliverchang - do we need to delete some entity somewhere to avoid these alerts ?

**Comment by oliverchang** [comment]
This should be addressed by https://github.com/google/oss-fuzz/pull/4623.
