### ISSUE TITLE
NSS fails AFL builds with undefined reference to `LLVMFuzzerMutate'

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#460]
See: https://oss-fuzz-gcb-logs.storage.googleapis.com/log-83056d64-9257-4cd8-9faf-332ce41c6383.txt

What should we do about fuzzers with custom mutators that call this? Provide an empty stub?

**Comment by oliverchang** [comment]
(disabling AFL for NSS for now)

**Comment by kcc** [comment]
Yea, I guess we need an empty stub. Please try now.

**Comment by oliverchang** [comment]
Looks like it works now. Thanks!
