### ISSUE TITLE
No issue filed for legitimate, reproducible bug

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#4609]
https://oss-fuzz.com/testcase-detail/5721325144113152

OSS-Fuzz found this bug on 31 Oct 2020 but no issue was filed.

When I try to manually file an issue for it (click the `CREATE ISSUE` button), it says: 

```
Unexpected error occurred. It might be a network failure. Please try again in a moment.
If the problem persists, please report to clusterfuzz-dev [at] chromium [dot] org.
```

**Comment by inferno-chromium** [comment]
filed it now, if you see similar thing again, we can investigate.

**Comment by guidovranken** [comment]
It happened again with https://oss-fuzz.com/testcase-detail/5759363123904512
I just filed an issue manually.
I've never seen this in other projects, only wolfssl.

**Comment by guidovranken** [comment]
This one too https://oss-fuzz.com/testcase-detail/5631799994744832

**Comment by guidovranken** [comment]
Ah it's probably because the `experimental` flag is set on msan in `project.yaml`. I'll remove that flag.

**Comment by inferno-chromium** [comment]
> Ah it's probably because the `experimental` flag is set on msan in `project.yaml`. I'll remove that flag.

Yes right
