### ISSUE TITLE
[mupdf] Coverage build fails becuase of no output directory

### ISSUE THREAD

**Issue by sebras** [google/oss-fuzz#4613]
We've received a notification that our mupdf coverage build failed.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27155

Looking at the detailed log it looks like the framework failed to create the output directory?
https://oss-fuzz-build-logs.storage.googleapis.com/log-3da2c385-bc68-478a-ba6c-5a681095d51f.txt
It that also why _every_ source code file is not covered?

I'm not so familiar with coverage builds so I need help with this.

**Comment by micahsnyder** [comment]
I'm seeing the same thing. From the log it looks as though there's a missing space somewhere between the `$OUT` variable and the `src`. Example line from our failed coverage builds:
```log
...
error: /workspace/out/coveragesrc/clamav-devel/libclamav/yara_lexer.h: No such file or directory
...
```

**Comment by micahsnyder** [comment]
BTW, this ticket is a dup of https://github.com/google/oss-fuzz/issues/4608

**Comment by inferno-chromium** [comment]
yes it is, should be fixed tonight.

**Comment by sebras** [comment]
Sorry for not spotting the duplicate. I tried to look for it, honest! :) Oh and thanks for a quick fix.
