### ISSUE TITLE
[CIFuzz] MSan not using its own pcre library

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#4614]
After merging #4606, it looks like CIFuzz is working for Suricata.
But it found a crash with MSAN
cf https://github.com/OISF/suricata/pull/5541

The crash seems a false positive.
It happens in a call to `pcre_get_substring`
It does not happen on oss-fuzz because pcre library is part of the base libraries built by msan-libs-builder

Am I understanding it correctly ?
If so, can it be fixed ? Or should I disable MSAN for Suricata/CIfuzz for now ?

**Comment by jonathanmetzman** [comment]
@catenacyber thanks for the report. I'll take a look at this after Thursday.
@oliverchang any ideas what could be causing this? Do we need to use special docker images to build and run MSAN fuzzers? I don't think CIFuzz is doing this.

**Comment by oliverchang** [comment]
Yes, we have a hack to do this in ClusterFuzz, where we patch the rpaths of the binaries to point to the pre-built libs in our image: https://github.com/google/clusterfuzz/blob/f43e52e612117a2979a7a120cdd17213811f776b/src/python/build_management/build_manager.py#L415

Another example of something that libClusterFuzz could help with :)

**Comment by jonathanmetzman** [comment]
So I think I know the cause of this issue.
CIFuzz is not doing all of the necessary build steps for MSAN builds.
I'll change it to do so shortly.

**Comment by catenacyber** [comment]
Thanks, let me know when it should be good and I can test it

**Comment by jonathanmetzman** [comment]
@catenacyber Can you try again?
I'm not actually sure this worked because when I tried reproing, there was an unrelated failure: https://github.com/jonathanmetzman/suricata/pull/1

**Comment by catenacyber** [comment]
Trying with https://github.com/OISF/suricata/pull/5650

**Comment by catenacyber** [comment]
Does not seem to work...
