### ISSUE TITLE
TestOneProtoInput in ​http_request_fuzzer.cc may be incorrect

### ISSUE THREAD

**Issue by yanglijin** [google/oss-fuzz#4632]
When I use oss-fuzz to check the latest nginx source code,I get some possible mem leak problem(The function stack see as https://trac.nginx.org/nginx/attachment/ticket/2080/sgs-nginx_latest.log ) ,but I still don't know what the problem is. Could this be a test case problem?
According to the reply from Maxim Dounin in the Nginx, the problem occurs in test case TestOneProtoInput of file 'http_request_fuzzer.cc'(https://trac.nginx.org/nginx/ticket/2080#no1).I wonder if this test case is really wrong? If that's the case, how do I change the test case? I look forward to your reply. Thank you.

**Comment by jonathanmetzman** [comment]
I don't know about this target. @yooyoo9 I think you authored it right?

**Comment by DavidKorczynski** [comment]
Closing this one following https://github.com/google/oss-fuzz/pull/5964
