### ISSUE TITLE
coverage : llvm-profdata not built with zlib support

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#4637]
I try to visualize suricata coverage locally 
So I ran
`python infra/helper.py build_fuzzers --sanitizer=coverage suricata`
Then
`python infra/helper.py coverage --no-corpus-download suricata` with some corpuses in place

This fails.
Investigating, I see 
```
Running fuzz_confyamlloadstring
/out/dummy_corpus_dir_for_fuzz_confyamlloadstring /corpus/fuzz_confyamlloadstring &> /out/logs/fuzz_confyamlloadstring.log
warning: /out/dumps/fuzz_confyamlloadstring.9070895403272444084_0.profraw: Profile uses zlib compression but the profile reader was built without zlib support
error: No profiles could be merged.
```

So, I guess this is the problem: that llvm-profdata in base-runner is not built with lib support

**Comment by catenacyber** [comment]
To be complete, I am trying to visualize code coverage with the Rust part, cf https://github.com/rust-lang/rust/issues/34701

So, I did a quick and dirty patch to oss-fuzz:
```
diff --git a/projects/suricata/build.sh b/projects/suricata/build.sh
index d0e152d8..2aa6b403 100755
--- a/projects/suricata/build.sh
+++ b/projects/suricata/build.sh
@@ -45,11 +45,18 @@ make install
 cd ..
 
 export CARGO_BUILD_TARGET="x86_64-unknown-linux-gnu"
+if [ "$SANITIZER" = "coverage" ]
+then
+#maybe this rather belongs in the runner
+    cargo install rustfilt
+    export RUSTFLAGS="$RUSTFLAGS -Zinstrument-coverage"
+fi
+echo "RUSTFLAGS=$RUSTFLAGS"
```

and one to suricata (as `build-std` and coverage do not seem compatible for rust compiler) :
```
diff --git a/configure.ac b/configure.ac
index 32c230209..f0371828b 100644
--- a/configure.ac
+++ b/configure.ac
@@ -2624,7 +2624,7 @@ fi
     AC_ARG_ENABLE(fuzztargets,
         AS_HELP_STRING([--enable-fuzztargets], [Enable fuzz targets]),[enable_fuzztargets=$enableval],[enable_fuzztargets=no])
     AM_CONDITIONAL([BUILD_FUZZTARGETS], [test "x$enable_fuzztargets" = "xyes"])
-    AM_CONDITIONAL([RUST_BUILD_STD], [test "x$enable_fuzztargets" = "xyes" && echo "$rust_compiler_version" | grep -q nightly])
+    AM_CONDITIONAL([RUST_BUILD_STD], [test "x$enable_fuzztargets" = "xyes" && echo "$rust_compiler_version" | grep -q nightly && echo "$RUSTFLAGS" | grep -v -q coverage])
     AC_PROG_CXX
     AS_IF([test "x$enable_fuzztargets" = "xyes"], [
         AS_IF([test "x$CARGO_BUILD_TARGET" = "x" && echo "$rust_compiler_version" | grep -q nightly], [
```

**Comment by inferno-chromium** [comment]
Just install rustfilt everywhere, add in https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/Dockerfile#L80

That -Zinstrument-coverage, You can make change here - https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile#L70

can you propose a patch

**Comment by catenacyber** [comment]
Before I propose a patch, I would like to check that it works ;-)
Not sure where rustfilt is needed (builder or runner...)

But it does not work because of llvm-profdata

How can I test this patch ?
```
diff --git a/infra/base-images/base-clang/checkout_build_install_llvm.sh b/infra/base-images/base-clang/checkout_build_install_llvm.sh
index 7b8721c8..71c5fcc5 100755
--- a/infra/base-images/base-clang/checkout_build_install_llvm.sh
+++ b/infra/base-images/base-clang/checkout_build_install_llvm.sh
@@ -50,6 +50,7 @@ function cmake_llvm {
       -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
       -DLIBCXXABI_ENABLE_SHARED=OFF \
       -DCMAKE_BUILD_TYPE=Release \
+      -DLLVM_ENABLE_ZLIB=ON
       -DLLVM_TARGETS_TO_BUILD="$TARGET_TO_BUILD" \
       -DLLVM_ENABLE_PROJECTS="$PROJECTS_TO_BUILD" \
       -DLLVM_BINUTILS_INCDIR="/usr/include/" \
```

**Comment by inferno-chromium** [comment]
> Before I propose a patch, I would like to check that it works ;-)
> Not sure where rustfilt is needed (builder or runner...)
> 
> But it does not work because of llvm-profdata
> 
> How can I test this patch ?
> 
> ```
> diff --git a/infra/base-images/base-clang/checkout_build_install_llvm.sh b/infra/base-images/base-clang/checkout_build_install_llvm.sh
> index 7b8721c8..71c5fcc5 100755
> --- a/infra/base-images/base-clang/checkout_build_install_llvm.sh
> +++ b/infra/base-images/base-clang/checkout_build_install_llvm.sh
> @@ -50,6 +50,7 @@ function cmake_llvm {
>        -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
>        -DLIBCXXABI_ENABLE_SHARED=OFF \
>        -DCMAKE_BUILD_TYPE=Release \
> +      -DLLVM_ENABLE_ZLIB=ON
>        -DLLVM_TARGETS_TO_BUILD="$TARGET_TO_BUILD" \
>        -DLLVM_ENABLE_PROJECTS="$PROJECTS_TO_BUILD" \
>        -DLLVM_BINUTILS_INCDIR="/usr/include/" \
> ```

you can run that script locally to test. but i think just adding it should be fine, worst case we will revert. @Dor1s thoughts ?

**Comment by Dor1s** [comment]
`python infra/helper.py build_image base-clang` will re-build `base-clang` image locally using this updated script.

if that succeeds, you can also do  `python infra/helper.py build_image base-builder` and then try to build a particular project.

Make sure to answer N or pass `--no-pull` to the helper script when it will want to pull new images, because you want to use your local image instead.

**Comment by catenacyber** [comment]
Looks like `llvm-cov` has zlib support but the profdata files has invalid zlib streams...

I did not manage to disable compression with `-mllvm -enable-name-compression=false` in suricata CFLAGS and in llvm-profdata args

I manage to get coverage information locally on my Mac, with an older version of LLVM (10.0.1) not using https://reviews.llvm.org/D69471

I suspect a bug in LLVM, and will try to get coverage information in the Linux container with the older version of LLVM.

**Comment by catenacyber** [comment]
So, it seems to depend on LLVM and especially https://reviews.llvm.org/D69471
Here is my `git bisect log` for LLVM
```
# bad: [f086e85eea94a51eb42115496ac5d24f07bc8791] [gcov] Assign names to some types and loaded values used in @__llvm_internal*
# good: [d334ce0b5acb945d6202d0ab6a17bdca530f50c1] Fix GSYM tests to run the yaml files and fix test failures on some machines.
git bisect start 'f086e85eea94a51eb42115496ac5d24f07bc8791' 'd334ce0b5acb945d6202d0ab6a17bdca530f50c1'
# bad: [80cd518b809ddb3caaf1dc59db3fbc6d1bcaf2e0] [Coverage] Collect all function records in an object (D69471 followup)
git bisect bad 80cd518b809ddb3caaf1dc59db3fbc6d1bcaf2e0
# bad: [dd1ea9de2e3e3ac80a620f71411a9a36449f2697] Reland: [Coverage] Revise format to reduce binary size
git bisect bad dd1ea9de2e3e3ac80a620f71411a9a36449f2697
# good: [e441a584f3f7d743ab77031a47d9ad60ee56b53d] Try to fix WindowsManifest CMake logic on Windows
git bisect good e441a584f3f7d743ab77031a47d9ad60ee56b53d
```

The process is :
recompile and install llvm and its tools
recompile suricata and its fuzz targets with this new LLVM with coverage
run one target to get default.profraw
`/out/fuzz_applayerparserparse -merge=1 -timeout=100 /tmp/corpus /out/corpus/fuzz_applayerparserparse`
run `llvm-profdata merge -j=1 -sparse default.profraw -o test.profdata`
Finally run 
`llvm-cov export -summary-only -instr-profile= test.profdata -object=/out/fuzz_applayerparserparse`

Last step may succeed and give some json or fail
Message is `Failed to decompress coverage data (zlib)` on latest version, or `Failed to load coverage: Malformed coverage data` on first failing version

**Comment by CAKimam121** [comment]
https://github.com/google/oss-fuzz/issues/4637#issue-741662225
