### ISSUE TITLE
Cryptofuzz i386 targets continue to run after disabling it in project.yaml

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#4641]
PR and reason for this: https://github.com/google/oss-fuzz/pull/4626

After the PR, new i386 target bugs continue to appear:

https://oss-fuzz.com/testcase-detail/5074513511055360 (14 November)
https://oss-fuzz.com/testcase-detail/5086067107299328 (12 November)
https://oss-fuzz.com/testcase-detail/4917178574569472 (11 November)

Can you please kill the i386 processes?

**Comment by inferno-chromium** [comment]
Lets wait the weekend to see if new bugs come up, there can be 1-2 days gap from check in time.

**Comment by inferno-chromium** [comment]
Deleted the i386 job, hopefully the fuzzing should stop in a day.

**Comment by jonathanmetzman** [comment]
CC @terrelln if you still see bugs from i386 after it was disabled, it's expected but I will fix it and you should stop seeing them soon.

**Comment by jonathanmetzman** [comment]
@terrelln Did the same for lz4

**Comment by oliverchang** [comment]
Filed https://github.com/google/clusterfuzz/issues/2154 for CF-side issue with project setup not deleting these jobs. I think this came up a few times before but we had some concerns around existing testcases breaking.

**Comment by jonathanmetzman** [comment]
Let's close this issue because the immediate problem was fixed and the ClusterFuzz-side issue is being tracked: https://github.com/google/clusterfuzz/issues/2154
