### ISSUE TITLE
[Suricata] AFL ignores seeds in input directory

### ISSUE THREAD

**Issue by adrianherrera** [google/oss-fuzz#4644]
Hi oss-fuzz/Suricata devs,

Just wondering if this is intended behavior or not.

I have been experimenting with fuzzing suricata locally with AFL. Per the `run_fuzzer` script [here](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/run_fuzzer#L71), if a seed corpus is provided, then it is unzipped and used as the AFL input directory ([here](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/run_fuzzer#L108)). To ensure that there is at least one seed (I guess in the case that a corpus is not provided) a "default" seed is generated [here](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/run_fuzzer#L107).

However, if `$FUZZER_seed_corpus.zip` contains nested directories (as is the case for Suricata's `fuzz_siginit_seed_corpus`, as it creates both `corpus` and `tests` directories within the seed_corpus zip file), then all of these seeds are ignored by AFL because AFL does not recursively descend into the input directory (in contrast, libFuzzer does recursively search the input directory). Is this ignoring of nested directories intended? Should the input directory be "flattened" so that it contains no nested directories if AFL is the chosen fuzzer? I'm also not sure if this issue is unique to Suricata, or occurs in other oss-fuzz targets.

**Comment by inferno-chromium** [comment]
This is not needed on ClusterFuzz, as we recurse through dirs. Probably just a local run_fuzzer limitation, we can fix it sometime.

**Comment by adrianherrera** [comment]
Ah ok cool, I didn't realize that. Thanks for the response!
