### ISSUE TITLE
report assert failures as such

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#465]
See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=878
and https://oss-fuzz.com/v2/testcase-detail/6339875685007360

It would be lovely if 
* the bug title was "assertion failure in ..." not "crash in ..."
* the bug report contained the actual text of assertion failure.

**Comment by oliverchang** [comment]
I forced an update of https://oss-fuzz.com/v2/testcase-detail/6339875685007360 (it displays ASSERT now).

There was a bug in our AFL driver script which was already fixed earlier today :)

Bug titles for assertion errors don't have the text "assert" in them, but we can add that.

**Comment by oliverchang** [comment]
Future bug reports should have "ASSERT" in the title in the future.
