### ISSUE TITLE
UBSAN crashes on deadly signals without stacks, hence gets ignored

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#466]
I think this is expected, but should we change this to get similar stacks like ASan. We don't want to ignore such bugs coming from ubsan. @kcc @mikea - thoughts

WARNING: Failed to find function "__sanitizer_print_stack_trace".
INFO: Seed: 2719763165
INFO: Loaded 1 modules (1209 guards): [0x73eb90, 0x73fe74),
Loading corpus dir: /new
Loading corpus dir: /json_parse_afl_fuzzer
Loaded 1024/1088 files from /json_parse_afl_fuzzer
#0	READ units: 1087
#1087	INITED cov: 675 ft: 3553 corp: 924/74Kb exec/s: 0 rss: 11Mb
terminating with uncaught exception of type nlohmann::detail::out_of_range: [json.exception.out_of_range.406] number overflow parsing '1E11111111'
==1== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 2 EraseBytes-CopyPart-; base unit: 9209f1127cc218147c2f8cb35f32ab06c1968541
0x5b,0x31,0x31,0x31,0x45,0x31,0x2c,0x31,0x31,0x31,0x31,0x31,0x31,0x45,0x31,0x31,0x2c,0x31,0x45,0x31,0x31,0x2c,0x31,0x45,0x31,0x31,0x31,0x2c,0x31,0x31,0x2c,0x31,0x45,0x31,0x31,0x31,0x2c,0x31,0x31,0x31,0x31,0x45,0x31,0x31,0x2c,0x31,0x45,0x36,0x33,0x2c,0x31,0x45,0x31,0x31,0x2c,0x31,0x45,0x31,0x31,0x31,0x2c,0x31,0x45,0x31,0x31,0x31,0x31,0x31,0x31,0x31,0x31,0x2c,0x31,0x21,
[111E1,111111E11,1E11,1E111,11,1E111,1111E11,1E63,1E11,1E111,1E11111111,1!
artifact_prefix='/'; Test unit written to /crash-e2ac8fbb362c06c0afe0fcb16cdc4bc942609fc2
Base64: WzExMUUxLDExMTExMUUxMSwxRTExLDFFMTExLDExLDFFMTExLDExMTFFMTEsMUU2MywxRTExLDFFMTExLDFFMTExMTExMTEsMSE=
stat::number_of_executed_units: 1569
stat::average_exec_per_sec:     0
stat::new_units_added:          0
stat::slowest_unit_time_sec:    0
stat::peak_rss_mb:              11

**Comment by inferno-chromium** [comment]
@Dor1s - you already fixed this, right, if yes, please close.

**Comment by Dor1s** [comment]
Yes, deadly signal handler calls `__sanitizer_print_stack_trace` if it exists: https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer.git/+/master/FuzzerLoop.cpp#192

so should be fixed after https://reviews.llvm.org/D32542
