### ISSUE TITLE
CIFuzz is failing because of '/usr/local/bin/test_all: line 50: FUZZING_LANGUAGE: unbound variable'

### ISSUE THREAD

**Issue by mrc0mmand** [google/oss-fuzz#4672]
Our recent CIFuzz runs in [systemd](https://github.com/systemd/systemd/actions?query=workflow%3ACIFuzz) started failing with following error:

```
Digest: sha256:5aeba6054f1fc806d3fd9a4934e4dfd9092615c8777ed6e5cff5993ff05f4008
Status: Downloaded newer image for gcr.io/oss-fuzz-base/base-runner:latest
/usr/local/bin/test_all: line 50: FUZZING_LANGUAGE: unbound variable
2020-11-20 09:36:24,331 - root - ERROR - Check fuzzer build failed.
Running: docker build -t gcr.io/oss-fuzz/systemd projects/systemd
```

I suspect the issue is in the latest commit - https://github.com/google/oss-fuzz/commit/5e3f47dba6323aef4a85796a188ddf4fc0e445e2#diff-30b802392cdb73c370f5edd2cb6e985f2a31f7ef13b7629b2f27b67dbd67f70c - where the used `FUZZING_LANGUAGE` variable is probably not defined in the environment in case of CIFuzz.

/cc @evverx, @inferno-chromium

**Comment by jonathanmetzman** [comment]
Thanks. Looking into this now.

**Comment by jonathanmetzman** [comment]
Can repro: https://github.com/jonathanmetzman/cifuzz-example/runs/1431523486

**Comment by jonathanmetzman** [comment]
It's surprising to me that not every build is failing: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#abseil-cpp

**Comment by jonathanmetzman** [comment]
I think this breaks CI. Testing that theory [here](https://github.com/google/oss-fuzz/pull/4674).
If true, we should probably do "project tests" on a random project every time infra/ directory is changed

**Comment by jonathanmetzman** [comment]
My test project no longer fails on that step: https://github.com/jonathanmetzman/cifuzz-example/runs/1431880795

Can you let me know if systemd is still experiencing this issue?

Sorry for the trouble, I'm taking steps right now to ensure something like this doesn't happen again.

**Comment by mrc0mmand** [comment]
> My test project no longer fails on that step: https://github.com/jonathanmetzman/cifuzz-example/runs/1431880795
> 
> Can you let me know if systemd is still experiencing this issue?
> 

I can confirm that systemd jobs are up and running once again!

> Sorry for the trouble, I'm taking steps right now to ensure something like this doesn't happen again.

No worries, thanks a lot for the quick fix.
