### ISSUE TITLE
CIFuzz broken with `FUZZING_LANGUAGE: unbound variable`

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#4686]
It seems that it comes from adding python
cf
https://github.com/OISF/suricata/pull/5585/checks?check_run_id=1431053064

**Comment by inferno-chromium** [comment]
Should be already fixed - https://github.com/OISF/suricata/pull/5587/checks?check_run_id=1432311485

**Comment by inferno-chromium** [comment]
If not, please reopen. Here was the fix - https://github.com/google/oss-fuzz/commit/640a9c2bcf3036742b769ef71ee89b0221b360b8
