### ISSUE TITLE
nss build failing

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#470]
See: https://oss-fuzz-gcb-logs.storage.googleapis.com/log-88f8599d-9eef-4917-b6bf-a6762efd8e16.txt

```
Step #2: /tmp/alg2268-5a2d6a.s: Assembler messages:
Step #2: /tmp/alg2268-5a2d6a.s:8167: Fatal error: bad .section directive: want a,l,w,x,M,S,G,T in string
Step #2: clang-5.0: error: assembler command failed with exit code 1 (use -v to see invocation)
Step #2: ninja: build stopped: subcommand failed.
```

@ttaubert , could you please take a look?

**Comment by ttaubert** [comment]
I can reproduce this locally, using `./helper.py build_fuzzers nss`. We haven't touched assembler implementations lately, this looks like something caused by a recent clang change?

(cc @franziskuskiefer)

**Comment by franziskuskiefer** [comment]
That's strange. I can reproduce it in the oss-fuzz docker image but not locally with clang trunk. Looks like oss-fuzz is maybe using a bad clang snapshot?

**Comment by Dor1s** [comment]
The revision used in docker now is https://reviews.llvm.org/D30830 (commit on the mirror: https://github.com/llvm-mirror/clang/commit/5ab5499a5cc2de2ef4fd813a66438d44ee88e425) that has been landed ~20 hours ago.

```bash
<...>
clang-5.0: error: assembler command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
fuzzers build failed.


$ python infra/helper.py shell nss
<...>
root@106f88cf8d2b:/src/nss# clang --version
clang version 5.0.0 (http://llvm.org/git/clang.git 5ab5499a5cc2de2ef4fd813a66438d44ee88e425) (http://llvm.org/git/llvm.git 1111ea1a18939df766e18439e84ac2c6155318a1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
<...>
```

**Comment by franziskuskiefer** [comment]
Interesting. I built with https://github.com/llvm-mirror/clang/commit/18021952cce94fde55068790887992c1c9e0e2e8, which works fine.

**Comment by Dor1s** [comment]
That's cool. I've kicked off re-build of base images (builder, etc). Looks like we just need to wait a bit to resolve this :)

**Comment by Dor1s** [comment]
Confirmed. Now it build successfully. Thanks for taking a look!
