### ISSUE TITLE
libsecp256k1 integration

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#4708]
I have a nice harness for [libsecp256k1](https://github.com/bitcoin-core/secp256k1/). The maintainers have been very clear that they don't want it integrated into OSS-Fuzz because according to them the 90 day public disclosure window is too limited. I don't agree with this reasoning but I have respected their decision by not running libsecp256k1 on OSS-Fuzz.

libsecp256k1 has many users who have critical dependence upon its security, and the consequence of this decision is that there could be a security bug that remains hidden because bona fide testing is artificially constrained (while malicious actors obviously don't face such impediments).

libsecp256k1 is primarily used for its ECDSA signing and verification functionality. I've recently found bugs in the ECDSA code of Botan, wolfCrypt, BearSSL, possibly Golang, and another library (cannot say, pending disclosure) using Cryptofuzz. If any bug exists in libsecp256k1, there's a good chance we can find it by continuous fuzzing on OSS-Fuzz.

Considering these points, can you green-light libsecp256k1 integration despite the lack of support by the maintainers? If not, go ahead and close this issue.

**Comment by jonathanmetzman** [comment]
Hi Guido,
I don't think we want to accept this project if upstream doesn't want the integration. 
Without upstream's cooperation we could end up in the worst of all worlds where bugs are getting disclosed and not not fixed.
