### ISSUE TITLE
make reproducers for fixed bugs public

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#471]
Once a bug reported by OSS-Fuzz is fixed and then (in 30 days) made public, 
we also want to make the reproducer public. 
We still want to publicize the minimized repro (depends on https://github.com/google/oss-fuzz/issues/452)
and also try to cleanse the repro of any non-essential bits.

**Comment by kcc** [comment]
I've just [added](http://llvm.org/viewvc/llvm-project?view=revision&revision=300498) an experimental  cleanse option.
Use it similar to merge: 
```
./fuzzer -cleanse_crash=1 IN -exact_artifact_path=OUT
```
It tries to replace all bytes in a crash reproducer with garbage, while still preserving the crash. 
I suggest to use it after the minimizer. 

cleanse may be slow on large inputs (does all runs out-of-process currently), 
so just do it with some timeout (e.g. 5 or 10 minutes). 
Even if killed due to timeout, the intermediate result may still be good (partially cleansed)

**Comment by oliverchang** [comment]
Thanks, I'll work on integrating this on CF side.

Just making sure --  is having cleanse/minimize succeed intended to be a hard requirement for making a reproducer public? or just best effort (and we make the reproducer public anyway)? I'm assuming the latter.

**Comment by kcc** [comment]
Best effort.

**Comment by oliverchang** [comment]
SGTM, thanks.

**Comment by oliverchang** [comment]
This is now done on CF. There's no an extra step at the end of each minimize to cleanse.

I'll address #537, and then make reproducers public for derestricted bugs.

Some example testcases where this succeeded:  https://oss-fuzz.com/v2/testcase-detail/5063709787422720 and https://oss-fuzz.com/v2/testcase-detail/4694120629010432

(inspection by hexdump shows that there are a lot more 0x20s and 0xffs in the minimized testcase)

**Comment by oliverchang** [comment]
Reproducers for bugs whose issue is public are now publicly downloadable.
