### ISSUE TITLE
view_restrictions does not give access to detailed reports

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#4714]
A recent integration of Serenity has the `view_restrictions: none` settings set in its `project.yaml`. However, the maintainers cannot observe the detailed reports, (CR https://github.com/SerenityOS/serenity/issues/4154#issuecomment-733711783). Are the detailed reports available for all when this setting is set? 

Am not entirely sure, but looking at `can_user_access_testcase` in Clusterfuzz it looks like there is some support for relaxed settings in the detailed reports, however, I did not go into the complete details https://github.com/google/clusterfuzz/blob/1d27ac053f2cefaa5f71722d83b264acbfb49f61/src/appengine/libs/access.py#L118

**Comment by oliverchang** [comment]
Unfortunately detailed reports are not available to the public, even if you set "view_restrictions: none". Anyone who wishes to access the detailed report must be CCed on the monorail bug and logged in to oss-fuzz.com with the same account.

**Comment by DavidKorczynski** [comment]
Thanks!
