### ISSUE TITLE
[QEMU] Monorail Permissions

### ISSUE THREAD

**Issue by a1xndr** [google/oss-fuzz#4716]
For some of the QEMU bugs discovered by OSS-Fuzz, I build reproducers and report them to our public bug-tracker immediately. Eg: https://bugs.launchpad.net/qemu/+bug/1905444
I reference the issue on monorail, but it is usually a private link that the devs have no access to. Is there a way to change the bug visibility?
Maybe something like EditIssueStatus/EditIssueCC referenced in #1402?
Thanks

**Comment by inferno-chromium** [comment]
Please add those emails here 
https://github.com/google/oss-fuzz/blob/master/projects/qemu/project.yaml#L5
You need to make sure your email is associated with a google account. your current email can be used that way, see https://support.google.com/accounts/answer/176347?co=GENIE.Platform%3DDesktop&hl=en

**Comment by a1xndr** [comment]
Should it be possible to manually change the bug visibility to public (before the 90 day deadline)? I don't see such an option.

**Comment by inferno-chromium** [comment]
@a1xndr - it gets public 30 days after a day is fixed. 90 day is for unfixed bugs disclosure timeline. do you want earlier than that, if yes, i can give you EditIssue permission to an email you specify.

**Comment by a1xndr** [comment]
@inferno-chromium That would be useful - thanks! Can you give it to alxndr@bu.edu

**Comment by inferno-chromium** [comment]
DONE @a1xndr

**Comment by oliverchang** [comment]
@a1xndr After some discussions we've decided that we can't give EditIssue permissions generally anymore as it's not really fine grained enough. 

We are working on a way in the future for project maintainers to be able to provide more input on individual bugs though (including making an issue public earlier), so stay tuned :)

**Comment by a1xndr** [comment]
@oliverchang 
Ok thanks for the heads-up
