### ISSUE TITLE
[libjpeg-turbo] Please add my account to "primary_contact" so I can see oss-fuzz bug reports

### ISSUE THREAD

**Issue by dcommander** [google/oss-fuzz#4720]
I was told that [my e-mail address](https://github.com/google/oss-fuzz/blob/master/projects/libjpeg-turbo/project.yaml#L7) in "vendor_ccs" needs to also be added to "primary_contact" so I can see bug reports.  That e-mail address is associated with the Google account I use for work.

**Comment by inferno-chromium** [comment]
i meant you need to have the exact google account in there. it cannot be the secondary email listed on your google account.
