### ISSUE TITLE
Feature request: batch download of reproducer test cases

### ISSUE THREAD

**Issue by boxerab** [google/oss-fuzz#4740]
I currently have around 90 fixed oss-fuzz issues in my project. It would be handy to be able
to batch download all (or a subset) of the reproducers so I can do some local testing, to make
sure I haven't broken some of the old reproducers.

Currently, I have to download one by one after opening each issue in my browser.

**Comment by inferno-chromium** [comment]
Fixed reproducer get stored along with corpus in corpus backups periodically.

Go to 
gs://{project_name}-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/{fuzz_target}/
download the zip, crashes should be in regressions directory.

**Comment by boxerab** [comment]
cool! thanks a lot.

**Comment by boxerab** [comment]
@inferno-chromium how do I access Google storage for my project? Do I need to use `gsutil` ?

**Comment by inferno-chromium** [comment]
either gsutil or
direct path via web e.g.
```https://storage.cloud.google.com/openssl-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/openssl_asn1/public.zip
```

**Comment by boxerab** [comment]
Thanks. So, in my case, project is `grok` and fuzzer target is  `grk_decompress_fuzzer`

But, the URL below does not work:

https://storage.cloud.google.com/grok-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/grk_decompress_fuzzer/public.zip

**Comment by inferno-chromium** [comment]
```
$ gsutil ls -R gs://grok-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/**/public.zip
gs://grok-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/grok_grk_decompress_fuzzer/public.zip
```

**Comment by boxerab** [comment]
thanks, that worked!
