### ISSUE TITLE
BAD BUILD: ASan build of <libreoffice-fuzzer> seems to be compiled with MSan.

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#4743]
Since the 25th Nov the libreoffice build fails with the above message on the libreoffice fuzzers
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libreoffice
e..g. Step #32: BAD BUILD: ASan build of /tmp/not-out/xpmfuzzer seems to be compiled with MSan.
that message appears to come from infra/base-images/base-runner/bad_build_check
which has...

CALL_INSN="callq\s+[0-9a-f]+\s+<"
MSAN_CALLS=$(objdump -dC $FUZZER | egrep "${CALL_INSN}__msan" -c)
check_asan_build $FUZZER ... $MSAN_CALLS ...
which errors out of MSAN_CALLS is > -

locally I do get...

objdump -dC rasfuzzer|egrep __msan
... mov 0x76f6354(%rip),%rcx ... <__msan_scoped_disable_interceptor_checks>
... mov 0x76f6337(%rip),%rcx ... <__msan_scoped_enable_interceptor_checks>
... mov 0x76f631a(%rip),%rax ... <__msan_unpoison>
... mov 0x76f6304(%rip),%rax ... <__msan_unpoison_param>

but no actual call of a __msan* function, though I will try again after a: python infra/helper.py pull_images

**Comment by inferno-chromium** [comment]
Looks like something happened with envoy as well
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#envoy

```
Step #32: Broken fuzz targets (39):
Step #32: buffer_fuzz_test:
Step #32: BAD BUILD: ASan build of /tmp/not-out/buffer_fuzz_test seems to be compiled with MSan.
Step #32: codec_fuzz_test:
Step #32: BAD BUILD: ASan build of /tmp/not-out/codec_fuzz_test seems to be compiled with MSan.
Step #32: codec_impl_fuzz_test:
Step #32: BAD BUILD: ASan build of /tmp/not-out/codec_impl_fuzz_test seems to be compiled with MSan.
Step #32: compressor_fuzz_test:
Step #32: BAD BUILD: ASan build of /tmp/not-out/compressor_fuzz_test seems to be compiled with MSan.
Step #32: config_fuzz_test:
Step #32: BAD BUILD: ASan build of /tmp/not-out/config_fuzz_test seems to be compiled with MSan.
Step #32: conn_manager_impl_fuzz_test:
Step #32: BAD BUILD: ASan build of /tmp/not-out/conn_manager_impl_fuzz_test seems to be compiled with MSan.
```

**Comment by inferno-chromium** [comment]
Some regression landed on 24th as builds broken starting 25th.

**Comment by oliverchang** [comment]
Looks honggfuzz specific. Possibly https://github.com/google/honggfuzz/commit/e0670137531242d66c9cf8a6dee677c055a8aacb ? @robertswiecki

**Comment by oliverchang** [comment]
We probably need to make this regex a bit more specific, (not just checking for __msan) or check that there are multiple calls above some threshold.

**Comment by robertswiecki** [comment]
FWIW those calls are weak, maybe this can be used 

```shell
$ nm libhfuzz/libhfuzz.a  | grep __msan
                 w __msan_poison
                 w __msan_unpoison
```

**Comment by mihaimaruseac** [comment]
TF has the same issue

**Comment by inferno-chromium** [comment]
@mihaimaruseac - tensorflow is now green, see https://oss-fuzz-build-logs.storage.googleapis.com/index.html#tensorflow
Others should get green by tmrw as well since @oliverchang fix is in.

**Comment by oliverchang** [comment]
libreoffice is now green, while envoy looks broken due to an unrelated AFL issue.

**Comment by asraa** [comment]
Yesterday I fixed unrelated build failures (a bad parse_dictionary error, and an early fail for a fuzz test)  on libfuzzer, but see the too many ASan calls on on libfuzzer/UBSan builds error: https://oss-fuzz-build-logs.storage.googleapis.com/log-3fe6bcd5-c846-481a-baac-311f239d9f36.txt

(The AFL build is stuck on testcases that it thinks are taking too long).

On a local build it passes:

```
$ python infra/helper.py build_image envoy && python infra/helper.py build_fuzzers --sanitizer undefined --engine libfuzzer --architecture x86_64 envoy && python infra/helper.py check_build --sanitizer undefined --engine libfuzzer --architecture x86_64 envoy
[...]
INFO: performing bad build checks for /tmp/not-out/h2_capture_direct_response_persistent_fuzz_test
INFO: performing bad build checks for /tmp/not-out/utility_fuzz_test
Check build passed.
```
