### ISSUE TITLE
Unclear documentation about directory layout

### ISSUE THREAD

**Issue by robryk** [google/oss-fuzz#475]
The [new project guide](https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md#dockerfile) isn't very clear about the directory where the checkout of the project's sources will be made. The Dockerfile uses a relative path in `git clone`. I assume it's relative to `$SRC` (`/src`), but it might be less confusing to use an absolute path there.

**Comment by oliverchang** [comment]
I added a line to clarify this. Thanks!
