### ISSUE TITLE
Provide documentation on how to create c++ projects

### ISSUE THREAD

**Issue by robryk** [google/oss-fuzz#477]
It seems that the default `Dockerfile` doesn't install some packages that are required to link C++:

```
$ python infra/helper.py build_image $PROJECT_NAME

...

/usr/bin/ld: cannot find -lstdc++
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
guetzli.make:103: recipe for target 'bin/Release/guetzli' failed
```

**Comment by oliverchang** [comment]
We provide libc++, you should be linking with that instead.

Please see: https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-clang/Dockerfile#L39

**Comment by robryk** [comment]
Shouldn't that be also included in `$LDFLAGS`? I would expect that Makefiles typically link c++ code using `$(CXX) $(LDFLAGS) object_files.o... -o output`.

**Comment by kcc** [comment]
Will it help if you use 
```
$(CXX) $(LDFLAGS) $(CXXFLAGS) object_files.o... -o output
```  

Build systems are **HARD**.
If we can get away w/o defining one more flag, I'd prefer to keep it the way it is.

**Comment by robryk** [comment]
OK, so this stops being a problem for me once I stop trying to build normal executables from my project along the way.

**Comment by robryk** [comment]
I guess everything is working correctly. It might be useful to suggest in the new project guide to avoid building unnecessary artifacts, because they might require different kinds of effort to build than what is required to build the actual fuzz target.
