### ISSUE TITLE
CIFuzz: repository can't be cloned as recursive

### ISSUE THREAD

**Issue by athre0z** [google/oss-fuzz#4780]
We're currently in the progress of implementing CIFuzz for Zydis and stumbled across the issue that it doesn't appear to be possible to tell CIFuzz to clone a repo recursively. Since we depend on that to pull in our `zycore` utility library, CIFuzz currently doesn't work for us.

I can't pretend to understand all the inner workings of CIFuzz, but it appears to me like the non-recursive clone originates here: https://github.com/google/oss-fuzz/blob/8bd567697d2f36589ca315971f6fff47af4e9e2b/infra/repo_manager.py#L247

Our workflow config can be viewed here: https://github.com/zyantific/zydis/blob/6b48854250013bad75f570d1b566e56f19770c4d/.github/workflows/main.yml#L43
A corresponding failed run: https://github.com/zyantific/zydis/runs/1498160477

Just cloning every repository recursively sounds risky, so that probably won't be the fix -- my suggestion would be to add a GH action config just like e.g. `oss-fuzz-project-name: 'zydis'` where users can specify `recursive-clone: true`.

It's also very much possible that we're just doing it wrong -- any help would be appreciated!

**Comment by jonathanmetzman** [comment]
Hmm....I'm working on a new API for projects to use CIFuzz where you simply provide the repo to CIFuzz rather than CIFuzz cloning the repo for you. Do you want to try using this?

**Comment by flobernd** [comment]
@jonathanmetzman Sure, that sounds great :-) Can you point us a site to get started?

**Comment by jonathanmetzman** [comment]
Sorry for the big delay in this. I ended up changing the API so I think we still may have a problem here.
I'm still thinking about a solution to this.

**Comment by jonathanmetzman** [comment]
Duplicate: https://github.com/google/oss-fuzz/issues/6755
