### ISSUE TITLE
Make it easier to remove images from docker cache

### ISSUE THREAD

**Issue by robryk** [google/oss-fuzz#479]
When I'm adding a fuzz target, I create a `Dockerfile` that pulls from a branch and I develop the fuzz target on that branch. When I change something in that branch, I would want to be able to do `python infra/helper.py build_image` and get an image with the new sources. Unfortunately, Docker's image caching stands in the way -- the `git clone` step is also cached. I can try to randomly do `docker rmi` on some of the images, but it'd be nice if there was a flag to `build_image` that causes it not to reuse images from Docker's cache.

**Comment by mikea** [comment]
There's a --nocache docker build option. We've already got --nopull in helper, so --nocache should be easy to add.
