### ISSUE TITLE
infra/helper.py broken in Python 2

### ISSUE THREAD

**Issue by cmeister2** [google/oss-fuzz#4792]
Hi,

Commit https://github.com/google/oss-fuzz/commit/f533434871c91baa9e3fcdde882dc9750a6d4b46 introduced a number of `os.makedirs(directory, exist_ok=True)` calls. As per https://docs.python.org/2.7/library/os.html and https://docs.python.org/3.5/library/os.html, exist_ok was added in 3.2.

This broke the CI checking here: https://github.com/libsndfile/libsndfile/pull/663 with the error:
```
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
```

Not sure if this was the intention or not - and I don't mind fixing up our code to use python 3 to execute the script instead of python 2. If the intention is that python 3 is the default now, perhaps the shebang of infra/helper.py should be updated from 
```
#!/usr/bin/env python
```
to 
```
#!/usr/bin/env python3
```?

**Comment by jonathanmetzman** [comment]
Thanks for letting know about this. I'm going to change this code to work with python2 again.
@oliverchang Do you think we should just switch to python3?
I wonder if there's something like caniuse.com for python versions that we can use to find out which distros/OSes have python3.
