### ISSUE TITLE
Fix for clang bug 28629?

### ISSUE THREAD

**Issue by rlohning** [google/oss-fuzz#4844]
Hi,

when trying to [build Qt from its dev branch](https://github.com/google/oss-fuzz/pull/4820/checks?check_run_id=1531781312), I run into [QTBUG-89382](https://bugreports.qt.io/browse/QTBUG-89382) which seems to be an incarnation of [clang's bug 28629](https://bugs.llvm.org/show_bug.cgi?id=28629).
Does it make sense to wait for a fix or a workaround in clang itself or in oss-fuzz?

Cheers,
Robert

**Comment by jonathanmetzman** [comment]
Hmmm...so I don't fully understand that bug but given that it's been around since 2016 and hasn't been fixed I personally would try to work around the issue in QT. Or you could bug someone in clang to fix it.

**Comment by jonathanmetzman** [comment]
Hey @rlohning since QT has been building since you've filed this, and we aren't going to personally fix it, I think we can close this issue. Feel free to reopen if you think otherwise.

**Comment by rlohning** [comment]
Hi @jonathanmetzman, while I would still appreciate a proper fix, I follow your reasoning. I worked around the issue in https://codereview.qt-project.org/c/qt/qtbase/+/331617 so this is not urgent to me anymore. Keep the issue closed.
