### ISSUE TITLE
infra/helper.py _get_latest_corpus using incorrect URL to download

### ISSUE THREAD

**Issue by Smjert** [google/oss-fuzz#4857]
In the osquery project we have two fuzz targets named `osqueryfuzz-config` and `osqueryfuzz-sqlquery`.
When trying to download their corpus during a local coverage run, using the infra/helper.py script, I get:
```
Downloading corpora for osquery project to /home/smjert/Development/oss-fuzz/build/corpus/osquery
WARNING: corpus for osqueryfuzz-config not found:
b'CommandException: One or more URLs matched no objects.\n'
WARNING: corpus for osqueryfuzz-sqlquery not found:
b'CommandException: One or more URLs matched no objects.\n'
WARNING: corpus for osquery_llvm-symbolizer not found:
b'CommandException: One or more URLs matched no objects.\n'
[...]
```
Checking with `strace` I see that it's trying to access the paths:
```
gs://osquery-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/osqueryfuzz-config/
gs://osquery-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/osqueryfuzz-sqlquery/
```

But listing the contents of the parent directory I actually get:
```
gsutil ls gs://osquery-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/
gs://osquery-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/osquery_osqueryfuzz-config/
gs://osquery-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/osquery_osqueryfuzz-sqlquery/
```

In the script I see that the `_get_latest_corpus` function does:
```
def _get_latest_corpus(project_name, fuzz_target, base_corpus_dir):
  """Download the latest corpus for the given fuzz target."""
  corpus_dir = os.path.join(base_corpus_dir, fuzz_target)
  if not os.path.exists(corpus_dir):
    os.makedirs(corpus_dir)

  if not fuzz_target.startswith(project_name):
    fuzz_target = '%s_%s' % (project_name, fuzz_target)
    [...]
```

So it seems that if the target name already starts with the project name (osquery in this case), then it won't prepend `osquery_`.
But then the remote corpus have that prefix. It seems the naming logic between the script and gcloud are not in sync?

**Comment by inferno-chromium** [comment]
You are right, this need a fix
We add the "+ '_'" before that in CF

```
  normalized_project_prefix = normalized_name(project) + '_'
  if binary.startswith(normalized_project_prefix):
    return binary
```

Care uploading a PR ?

**Comment by inferno-chromium** [comment]
I am fixing it, too simple.

**Comment by Smjert** [comment]
> I am fixing it, too simple.

Ah thank you! 
I wanted to have a look at this later to see if there was a way to share the logic between clusterfuzz and ossfuzz, because I see that clusterfuzz normalizes the project name, and in general if the logic gets changed on the clusterfuzz size, it can get out of sync.
But at the same time I must admit I'm not that well versed with Python.

**Comment by jonathanmetzman** [comment]
>I wanted to have a look at this later to see if there was a way to share the logic between clusterfuzz and ossfuzz

We are in the process of making making ClusterFuzz functionality usable outside of ClusterFuzz through libClusterFuzz. This is a good idea to add.
