### ISSUE TITLE
Make --nopull and --no-cache the default for the helper.

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#487]
I think the default of pulling images has caused a lot of confusion. #479 shows that there are similar issues with docker's caching. 

Although it will make the initial image build slower, I think we should just make --nopull and --no-cache the default for helper.py. What do people think?

**Comment by kcc** [comment]
strongly agree. this has confused me a few times already :)

**Comment by oliverchang** [comment]
Behaviour has changed to:

- No project images are ever pulled.
- base images are still pulled when we build fuzzers (because they can be very slow to build).
- `build_image` bypasses docker cache, and won't pull images even if it's a base image.
