### ISSUE TITLE
Downloading the latest build of a project from Google Cloud

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#4883]
I was wondering if there is an easy way to download the latest build (fuzzer binaries) for any OSS-Fuzz project. I'm pretty involved in open source security and sometimes I want to do some testing on a project that I'm not necessarily a member of (eg. OpenSSL TLS fuzzers). Of course I can build the project myself, but downloading the pre-built binaries would be more convenient. I know how to download (90 days old) corpora of projects, but I can't figure out how to do the same for binaries.

**Comment by inferno-chromium** [comment]
gsutil cp from
gs://clusterfuzz-builds/{project_name} [for libfuzzer]
gs://clusterfuzz-builds-afl/{project_name}
gs://clusterfuzz-builds-honggfuzz/{project_name}

e.g. 
gsutil ls -l gs://clusterfuzz-builds/gdal/gdal-address-*

then
gsutil cp gs://clusterfuzz-builds/gdal/gdal-address-202012220613.zip <whereever_local>

**Comment by guidovranken** [comment]
Thanks!
