### ISSUE TITLE
Make it easier to test using local checkout of the repo

### ISSUE THREAD

**Issue by robryk** [google/oss-fuzz#489]
I expect the following workflow to be typical:

1. Get a bug report from the fuzzer.
2. Make a change that likely fixes the bug.
3. Make sure the bug doesn't reproduce, before publishing that change.

It would be nice if step 3 was easier. Right now, in order to accomplish that, I need to:
a) push the change to my fork
b) hack the `Dockerfile` so that it pulls from a non-master branch, from my repository.

I would prefer to be able to point `infra/helper.py build_fuzzers` at a local clone of the repository.

I imagine it should be possible to just mount the local checkout inside the container using volumes. That would also (if the volume was read-write) help with #52. What do you think about this approach?

**Comment by kcc** [comment]
> Make sure the bug doesn't reproduce, before publishing that change.

Yes, but you should not need to use docker for that. 
In the [ideal integration](https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md) you should be able to reproduce the bug in your local build environment.

**Comment by oliverchang** [comment]
That said, you can pass an additional argument to build_fuzzers (see `python helper.py build_fuzzers -h`). But yes, the helper is intended to help people get started and not intended to be used as part of the development process.

**Comment by robryk** [comment]
@kcc 

Ah, true, I can just write a trivial driver and use it in place of `$LIB_FUZZING_ENGINE`.

@oliverchang 

I somehow missed that when looking at `build_fuzzers`. Thanks for pointing it out; it's exactly what I was asking for.

Getting started is precisely when this is needed the most, for a slightly different reason: the fuzzing target itself is not yet pushed to the real repository and you need to get it to work. It might be useful to mention that in the getting started guide.
