### ISSUE TITLE
Building Fuzzers reruns Build Images

### ISSUE THREAD

**Issue by wiredfool** [google/oss-fuzz#4901]
(tldr, code doesn't match docs)

I'm trying to get Pillow to fuzz the latest (uncommitted/private/security) code, not from the main repo. 

In the documentation: ( https://google.github.io/oss-fuzz/advanced-topics/reproducing/)
>Build the image and the fuzzers
Run the following commands:
```
$ python infra/helper.py build_image $PROJECT_NAME
$ python infra/helper.py build_fuzzers --sanitizer <address/memory/undefined> \
    --architecture <x86_64/i386> $PROJECT_NAME
```

So, what I'm doing is integrating the fuzzer locally by rewriting the code in the image. But I'm thwarted by build_fuzzers_impl, which just rebuilds the images. 

In infra/helper.py
```
def build_fuzzers_impl(  # pylint: disable=too-many-arguments,too-many-locals,too-many-branches                                                              
    project_name,
    clean,
    engine,
    sanitizer,
    architecture,
    env_to_add,
    source_path,
    no_cache=False,
    mount_location=None):
  """Build fuzzers."""
  if not build_image_impl(project_name, no_cache=no_cache):
    return 1
```

**Comment by inferno-chromium** [comment]
Yes there is an option to provide local source path, see

usage: helper.py build_fuzzers [-h] [--architecture {x86_64,i386}]
                               [--engine {libfuzzer,afl,honggfuzz,dataflow,none}]
                               [--sanitizer {address,memory,undefined,coverage,dataflow}]
                               [-e E] [--clean] [--no-clean]
                               project_name [source_path]

Add souce_path at end, then it will mount your local in docker.

**Comment by wiredfool** [comment]
I've tried that: https://github.com/google/oss-fuzz/issues/4853

**Comment by inferno-chromium** [comment]
after holidays, will try to get #4853 fixed.
