### ISSUE TITLE
Progression run does not pull latest commit

### ISSUE THREAD

**Issue by tbeu** [google/oss-fuzz#4938]
I noticed that when triggering new fuzzer runs of [matio](https://github.com/google/oss-fuzz/tree/master/projects/matio) it uses outdated revision of the repository (for example: https://sourceforge.net/p/matio/matio/ci/7a9958485036ef37b4e88df5cbe32bd7ec4c0d25/) where I would expect to pull the latest commit. How can I trigger progression checks to pull the latest commit of matio? Thank you for your support and valuable service!

**Comment by inferno-chromium** [comment]
It uses the last build available, which is done once every night. If you want more frequent builds, then you can add this attribute - https://google.github.io/oss-fuzz/getting-started/new-project-guide/#build_frequency to do upto 4 builds per day. 
I find it hard to udnerstand why we would use such an old revision, Dockerfile pulls in latest. even checked matio testcase e.g. https://oss-fuzz.com/testcase-detail/4798940472016896, which tests against latest builds
```
[2021-01-10 15:04:50 UTC] oss-fuzz-linux-zone5-host-lqd1-6: Progression task started: r202101090618.
[2021-01-10 15:04:51 UTC] oss-fuzz-linux-zone5-host-lqd1-6: Progression task finished: still crashes on latest revision r202101090618.
```

**Comment by tbeu** [comment]
Thanks for your reply. For example, I triggered https://oss-fuzz.com/testcase-detail/5752296985591808 yesterday, but it did not used the latest revision of matio.

**Comment by inferno-chromium** [comment]
@tbeu - that is i386 build [libfuzzer_asan_i386_matio], which is not built anymore since i386 is missing in https://github.com/google/oss-fuzz/blob/master/projects/matio/project.yaml#L9
is it feasible to bring i386 builds back, if yes, then new builds will be auto-available [since they will be built]. Otherwise, we need to just close those bugs as wontfix and wait for fuzzing to re-hit. you can also reupload those testcases by pressing "Re-upload testcase" link and then selected a regular x86_64 job type - libfuzzer_asan_matio to verify that it is fixed.

**Comment by tbeu** [comment]
Thanks. I should have asked earlier since I spent to many hours on trying to reproduce.

**Comment by inferno-chromium** [comment]
> Thanks. I should have asked earlier since I spent to many hours on trying to reproduce.

Sorry about this confusion.

**Comment by tbeu** [comment]
I already asked in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=16856#c2, but apparently these bug reports are not read by humans, but only edited by CI.

**Comment by inferno-chromium** [comment]
> I already asked in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=16856#c2, but apparently these bug reports are not read by humans, but only edited by bots.

Yes, now we add some text in bugs:
```
If you need to contact the OSS-Fuzz team with a question, concern, or any other feedback, please file an issue at https://github.com/google/oss-fuzz/issues. Comments on individual Monorail issues are not monitored.```

**Comment by tbeu** [comment]
Sorry to ask again. I uloaded the issues raised from `libfuzzer_asan_i386_matio` again by `libfuzzer_asan_matio` and I could see that the issue no longer can be reproduced. However, this reupload does not contribute to the overall state of the issue. What should I do? How can I resolve an issue as wontfix?

**Comment by inferno-chromium** [comment]
reupload does not impact other issue status, are you fixing the i386 build at all ? if not, we can just wontfix those bugs.

**Comment by tbeu** [comment]
Yes, I propose to wontfix these open bugs.

**Comment by inferno-chromium** [comment]
> Yes, I propose to wontfix these open bugs.

actually mark all of those as fixed. new ones should show in regular x86-64 config

**Comment by tbeu** [comment]
Thanks.

**Comment by tbeu** [comment]
I noticed that new issue 30298 is opened using libfuzzer_asan_i386_matio is opened on old revision. How can I avoid such issues?

**Comment by inferno-chromium** [comment]
> I noticed that new issue 30298 is opened using libfuzzer_asan_i386_matio is opened on old revision. How can I avoid such issues?

forgot to delete libfuzzer_asan_i386_matio job, just did it. shouldnt happen anymore.

**Comment by tbeu** [comment]
Thank you again.
