### ISSUE TITLE
Question: how can I run two identical fuzzers, for two different branches ?

### ISSUE THREAD

**Issue by boxerab** [google/oss-fuzz#4947]
https://github.com/google/oss-fuzz/tree/master/projects/grok

I would like to fuzz both my master branch, and a dev branch with some more experimental code.
The fuzzers would be exactly the same, just pulling from different branches.

**Comment by jonathanmetzman** [comment]
We generally recommend only fuzzing on the branch that will make it into production.
e.g. in Chrome we only fuzz the master branch even though users are on an earlier commit from master.
You could try checking out the other branch you want to fuzz, building those fuzzers, and then renaming them before putting them in $OUT. I don't recommend this though as it will mess up things like regression commit ranges and CIFuzz.

**Comment by boxerab** [comment]
@jonathanmetzman thanks, makes sense.
