### ISSUE TITLE
[CIFuzz] No testcase found in stacktrace

### ISSUE THREAD

**Issue by evanmiller** [google/oss-fuzz#4956]
I'm trying to integrate CIFuzz with mdbtools. Here's the output from the latest run:

https://github.com/mdbtools/mdbtools/runs/1691216801?check_suite_focus=true

The "Run Fuzzers" stage passes, but the log indicates:

```
2021-01-12 21:54:45,794 - root - INFO - Using address sanitizer.
2021-01-12 21:54:45,803 - root - INFO - Fuzzer fuzz_mdb, started.
2021-01-12 21:54:45,889 - root - ERROR - Unable to download from: https://storage.googleapis.com/mdbtools-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/mdbtools_fuzz_mdb/public.zip.
2021-01-12 21:54:45,889 - root - INFO - Running command: docker run --rm --privileged --volumes-from 7497496647a7 -e OUT=/github/workspace/out -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e CIFUZZ=True -e RUN_FUZZER_MODE=interactive gcr.io/oss-fuzz-base/base-runner bash -c run_fuzzer fuzz_mdb -seed=1337 -len_control=0 -max_total_time=600
2021-01-12 21:54:46,485 - root - INFO - Fuzzer fuzz_mdb, ended before timeout.
2021-01-12 21:54:46,486 - root - ERROR - b'No testcase found in stacktrace: b''.'
2021-01-12 21:54:46,486 - root - INFO - Fuzzer fuzz_mdb, finished running.
```

My first question is: Does this look like a temporary error, or is my fuzzer misconfigured?

My second question is: Shouldn't this phase be failing in the event of a failed download?

**Comment by jonathanmetzman** [comment]
> Does this look like a temporary error, or is my fuzzer misconfigured?

I don't think I've ever seen this issue before. Other projects don't seem to have this issue (see https://github.com/openssl/openssl/runs/1682963337 for example) I may try to reproduce this later this week.
Do you know if this fuzzer prints anything btw?

>My second question is: Shouldn't this phase be failing in the event of a failed download?

Nope. There can be a lot of reasons why the download of the corpus backup fails. Such as a new fuzzer (that hasn't run on ClusterFuzz yet) or a fuzzer that isn't producing backups see https://github.com/google/oss-fuzz/issues/4937 for example.

**Comment by evanmiller** [comment]
Thanks for the clarification - the fuzzer may print warnings on certain kinds of input. I was expecting it to run for more than 2/3 of a second, so I thought the failed download caused the fuzzing to terminate abruptly. But perhaps I have misread the log.

**Comment by jonathanmetzman** [comment]
I think I figured this issue out.
I'm pretty sure unzipping the corpus isn't returning zero.
That's because it is complaining about path components in your compressed files:
```
unzip -d /tmp/u y/corpus.zip 
Archive:  y/corpus.zip
warning:  skipped "../" path component(s) in ../mdbtestdata/data/nwind.mdb
  inflating: /tmp/u/mdbtestdata/data/nwind.mdb  
warning:  skipped "../" path component(s) in ../mdbtestdata/data/ASampleDatabase.accdb
  inflating: /tmp/u/mdbtestdata/data/ASampleDatabase.accdb 
```
[Here](https://github.com/google/oss-fuzz/blob/master/projects/mdbtools/build.sh#L25) you should use the option -j to exclude path components.

**Comment by jonathanmetzman** [comment]
Feel free to open if this doesn't solve your issue.

**Comment by evanmiller** [comment]
@jonathanmetzman Thanks. I opened a PR with the suggested change.

It would be great if CIFuzz returned an error when unzipping fails in cases like this.

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman Thanks. I opened a PR with the suggested change.
> 
> It would be great if CIFuzz returned an error when unzipping fails in cases like this.

Definitely. I need to rework some things in CIFuzz for it to do this though.
