### ISSUE TITLE
What to do if issue is raised in dependent library?

### ISSUE THREAD

**Issue by tbeu** [google/oss-fuzz#4999]
Most of the [open matio fuzzing issues](https://bugs.chromium.org/p/oss-fuzz/issues/list?q=matio&can=2&sort=-id&mode=grid&x=Engine&y=Type) seem to be related to the hdf5 v1.12.0 library dependency which is is not being fuzzed by oss-fuzz. What can I do to get these open issues properly addressed. Can I reassign them to the [HDF5 developers](https://github.com/orgs/HDFGroup/people)? Can we add secondary contact to the project.yaml?

**Comment by inferno-chromium** [comment]
> Most of the [open matio fuzzing issues](https://bugs.chromium.org/p/oss-fuzz/issues/list?q=matio&can=2&sort=-id&mode=grid&x=Engine&y=Type) seem to be related to the hdf5 v1.12.0 library dependency which is is not being fuzzed by oss-fuzz. What can I do to get these open issues properly addressed. Can I reassign them to the [HDF5 developers](https://github.com/orgs/HDFGroup/people)? Can we add secondary contact to the project.yaml?

Yes you can add them to any bugs, then they get auto-access to report. Also, you can add devs to project.yaml if that is easier. Unfortunately, we don't have a good solution, other than encouraging those devs to see these reports and then look at trunk integration as a new OSS-Fuzz project.
