### ISSUE TITLE
Don't group unknown crash type across different libraries

### ISSUE THREAD

**Issue by kcwu** [google/oss-fuzz#50]
Otherwise all abort() and assert() failures of different projects will be grouped into single one.

**Comment by oliverchang** [comment]
This shouldn't be happening. Could you provide more details?

**Comment by kcwu** [comment]
[This](https://clusterfuzz-external.appspot.com/crashstats?fuzzer_name=libFuzzer_chewing_default_fuzzer&job_type=All&date_start=2016-10-20&date_end=2016-10-20&security_flag=Both) is crash list of chewing_default_fuzzer. 
Following the crash report [link](https://clusterfuzz-external.appspot.com/testcase?key=5018119483424768), it is libFuzzer_tpm2_execute_command_fuzzer

**Comment by oliverchang** [comment]
Asserts should be properly detected and grouped now. [Example testcase](https://clusterfuzz-external.appspot.com/testcase?key=5039547310145536&noredirect=true)
