### ISSUE TITLE
Recurring ASAN ILL bug with no way of reproducing

### ISSUE THREAD

**Issue by boxerab** [google/oss-fuzz#5001]
Every 14 days I get this bug appearing in my issue list:

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=29696&sort=-opened&can=1&q=proj%3Agrok

This is coming from code that is only called a single time by the fuzzer, at startup.
I have checked the code itself and there is no way it could be mis-behaving. 

Any suggestions would be very much appreciated!

**Comment by jonathanmetzman** [comment]
Think this is a duplicate of #5220
