### ISSUE TITLE
Can't get access to bug #29720?

### ISSUE THREAD

**Issue by tytso** [google/oss-fuzz#5002]
I was informed of this bug [1] via e-mail sent to my tytso@mit.edu address.   I can't access the bug description using either my theodore.tso@gmail.com account, nor my tytso@google.com account.   

[1] https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=29720

I'm just need to find the sources for ext2fs_check_directory_fuzzer and alas, the documentation is not at all helpful.  The documentation tells me that "ideally" the fuzzer is supposed to be in the upstream repository.  Well, no one has asked me to put it in the upstream repo.   Also, I'm only able to download the test case via my tytso@google.com account (the theodore.tso@gmail.com account didn't work).    But there's absolutely no information about where to find the reproducer binary.

**Comment by tytso** [comment]
Also, from what I can tell, this isn't actually a security bug.  The fuzzer is dying because it couldn't allocate 16GB of memory.   That's hardly a UBSAN.    And I don't see how the reproducer would actually work, since any attempt to operate on it will result in ext2fs_open() returning an error due to a short read.   Maybe if the image was written to a device that was at least a bit over 16 GB?   But then nothing would actually break.   The image is clearly a nonsense file system, of the kind which is created by fuzzers, but I don't at all see how this is a valid report.   (Of course, I've wasted a lot of time because the documentation sucks and I don't have access to the whole report....)

**Comment by oliverchang** [comment]
Are you able to login with a google account with your tytso@mit.edu address? The google account email must match what's specified in the project.yaml. 

I've CC'ed your @google.com account on the bug for now so that should grant you all the necessary access. For future access to other bugs you may need to update the project.yaml file here: https://github.com/google/oss-fuzz/blob/master/projects/e2fsprogs/project.yaml

**Comment by oliverchang** [comment]
Regarding the OOM itself, even if you do not consider it a bug it would be very beneficial to modify the fuzz target or the library code itself to disallow such large allocations under fuzzing. 

If a fuzz target constantly finds OOMS because they're easy to reach, other, more important bugs can be missed.

**Comment by tytso** [comment]
My google account theodore.tso@gmail.com is associated with tytso@mit.edu.    And that didn't work.....    That is, if I look at https://myaccount.google.com/email, tytso@mit.edu is listed as one[1] of the "Other email addresses you can use to sign in to your account."   And theodore.tso@gmail.com doesn't work.   

As I understand things, even if it didn't violate the TOS for me to create a second gmail account, the fact that tytso@mit.edu is listed as an alternate email address would preclude creating another gmail account based on tytso@mit.edu.

Regarding the fuzz target, where can I find the sources for said fuzz target?   Someone created it without consulting me, and it's not in the upstream repo.

[1] Only in my case.

**Comment by tytso** [comment]
If you want me to modify the fuzz target, then please make oss-fuzz more upstream friendly.   Otherwise, if you want to make this fuzzing failure public in 90 days, feel free.   But my time is limited, and right now I don't have the time to engage.   

If you want to close issues such as #5005, that's your prerogative.  But it's my prerogative whether or not I want to spend my limited time engaging with oss-fuzz.

**Comment by inferno-chromium** [comment]
Project files can be found here - https://github.com/google/oss-fuzz/tree/master/projects/e2fsprogs
@Google-Autofuzz can you please work with @tytso here on doubts. [@tytso, please set up a meeting with mtjz at google who hosted Ravi this summer and integrated fuzzers]
Added your two accounts in auto_ccs, this should give you full access - https://github.com/google/oss-fuzz/blob/master/projects/e2fsprogs/project.yaml, can propose PR to later a particular one.
