### ISSUE TITLE
[CIFuzz] Come up with better way to diff

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#5010]
Currently diffing is done against origin/master. This falls over in two scenarios I've seen:
1. Fuzzing on commits to master. Here there is no difference with origin/master. systemd which also fuzzes on commit is an example of this.
2. Fuzzing on PRs to branches other than master. zstd is an example of this because most PRs are to dev. This will also become more of a problem as the use of the term "master" declines.

I don't know what's the generic solution here.
Getting changed files can be done through [github actions API](https://github.com/jitterbit/get-changed-files), but I'm concerned:
1. About needing to use another language
2. About the stability of these APIs
3. About using a github specific solution.

I guess the generic solution might be to define a base thing to diff against. In commits it would need to be HEAD^1 and others could define this as well.

**Comment by evverx** [comment]
`systemd` switched to the `main` branch in https://github.com/systemd/systemd/issues/16834. It would be great if CIFuzz could use it instead of `master`.

**Comment by evverx** [comment]
Without the `master` branch CIFuzz seems to always build and run all the fuzzers regardless of whether anything has changed or not:
```
2021-01-21T14:14:20.9990632Z 2021-01-21 14:14:20,995 - root - DEBUG - Stderr of command 'git diff --name-only origin...' is warning: ignoring dangling symref refs/remotes/origin/HEAD.
2021-01-21T14:14:20.9991715Z fatal: ambiguous argument 'origin...': unknown revision or path not in the working tree.
2021-01-21T14:14:20.9992325Z Use '--' to separate paths from revisions, like this:
2021-01-21T14:14:20.9992847Z 'git <command> [<revision>...] -- [<file>...]'
2021-01-21T14:14:20.9993346Z .
2021-01-21T14:14:20.9994077Z 2021-01-21 14:14:20,996 - root - ERROR - Git diff failed with error message warning: ignoring dangling symref refs/remotes/origin/HEAD.
2021-01-21T14:14:20.9994813Z fatal: ambiguous argument 'origin...': unknown revision or path not in the working tree.
2021-01-21T14:14:20.9995394Z Use '--' to separate paths from revisions, like this:
2021-01-21T14:14:20.9995910Z 'git <command> [<revision>...] -- [<file>...]'
2021-01-21T14:14:20.9996175Z .
2021-01-21T14:14:20.9996674Z 2021-01-21 14:14:20,996 - root - INFO - No files changed compared to HEAD.
```

**Comment by evverx** [comment]
@jonathanmetzman I wonder if as a stopgap it would make sense to diff against the default branch (which CIFuzz could get by running something like `git remote show origin | grep 'HEAD branch'`:
```
# zstd
$ git remote show origin | grep 'HEAD branch'
  HEAD branch: dev

# systemd
$ git remote show origin | grep 'HEAD branch'
  HEAD branch: main

# util-linux
$ git remote show origin | grep 'HEAD branch'
  HEAD branch: master
```

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman I wonder if as a stopgap it would make sense to diff against the default branch (which CIFuzz could get by running something like `git remote show origin | grep 'HEAD branch'`:
> 
> ```
> # zstd
> $ git remote show origin | grep 'HEAD branch'
>   HEAD branch: dev
> 
> # systemd
> $ git remote show origin | grep 'HEAD branch'
>   HEAD branch: main
> 
> # util-linux
> $ git remote show origin | grep 'HEAD branch'
>   HEAD branch: master
> ```

THanks for mentioning this @evverx. I assumed commit fuzzing was completely broken, but I guess it wasn't. It was only due to the `main` vs `master` issue. I'll look into the solution you suggested.

**Comment by evverx** [comment]
> I think I will probably try to find out the base branch through env vars github passes actions (BASE_REF in particular)

I think for projects hosted on GitHub it's much better than trying to get the default branch with `git remote show`.

> For commit fuzzing, I think we need to special case things though. We can't compare against master/main because the latest commit there is the same as the one we are testing. In that case I think we can use HEAD^1 as the diff.

As far as I can remember, `systemd` started running CIFuzz in that mode to kind of double check the filters listed in https://github.com/systemd/systemd/blob/9b25429cb4e9b71e25cd9094ff2bbe3351aa9329/.github/workflows/cifuzz.yml#L8-L14 in the sense that we wanted to make sure that they didn't prevent CIFuzz from discovering new issues in PRs by catching commits that haven't failed when PRs were opened. I think that in that particular case diffs aren't important and just building and running all the fuzzers would work.

**Comment by evverx** [comment]
Though I can imagine projects where all the commits go directly into `master` (or any other default branch) so it seems HEAD^1 as the diff base would be the best solution.

**Comment by jonathanmetzman** [comment]
> Though I can imagine projects where all the commits go directly into `master` (or any other default branch) so it seems HEAD^1 as the diff base would be the best solution.

Right. Even though youre the only project using this feature so far as I know, I think this behavior is more intuitive.

**Comment by evverx** [comment]
`util-linux` uses it as well (mostly because some commits go directly into master)

**Comment by evverx** [comment]
> it seems HEAD^1 as the diff base would be the best solution.

@jonathanmetzman on the other hand, it seems to be based on the assumption that commits are pushed one by one. I don't think it's safe to assume that a bunch of unrelated commits can't be sent in one fell swoop. It seems that when it's unclear how many commits trigger a push event (and in general I think it seems to be the case) I'd say it would be better to build and run all the fuzz targets to catch issues as early as possible (hopefully).

**Comment by jonathanmetzman** [comment]
> > it seems HEAD^1 as the diff base would be the best solution.
> 
> @jonathanmetzman on the other hand, it seems to be based on the assumption that commits are pushed one by one. I don't think it's safe to assume that a bunch of unrelated commits can't be sent in one fell swoop. It seems that when it's unclear how many commits trigger a push event (and in general I think it seems to be the case) I'd say it would be better to build and run all the fuzz targets to catch issues as early as possible (hopefully).

Fair point, need to think about this.

**Comment by jonathanmetzman** [comment]
I figured out how to get the changed files for push events (even those that push multiple files).
However, it may complicate things somewhat. Since Fuzzbench currently treats fuzzing outside of github actions as push events.

**Comment by evverx** [comment]
> I figured out how to get the changed files for push events (even those that push multiple files). However, it may complicate things somewhat.

I wonder if it relies on github.event.before? As far as I know, it isn't set when new branches are pushed so it's probably even more complicated. Though I'm not sure how important this use case is.

**Comment by jonathanmetzman** [comment]
> > I figured out how to get the changed files for push events (even those that push multiple files). However, it may complicate things somewhat.
> 
> I wonder if it relies on github.event.before? As far as I know, it isn't set when new branches are pushed so it's probably even more complicated. Though I'm not sure how important this use case is.

Sure does. Which means we will end up for one method for pushes, one for PRs and one for non-github users.
