### ISSUE TITLE
[CI] projects are building unnecessarily

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#5022]
See https://github.com/google/oss-fuzz/runs/1737287979 where serenity is built even though I didn't modify it.
My guess is that this has something to do with diffing against origin/master, maybe we should just diff against master.

**Comment by inferno-chromium** [comment]
Yes this is the pain with `git diff --name-only FETCH_HEAD` which includes new commits pushed to master. Seeing if there is some workaround.

**Comment by jonathanmetzman** [comment]
I'll look into it too.
I realize now there's no reason this should be assigned to you in particular. When I filed this I thought it was because of your change, but your change only made it clear that this is a problem, it didn't introduce the problem.

**Comment by inferno-chromium** [comment]
> I'll look into it too.
> I realize now there's no reason this should be assigned to you in particular. When I filed this I thought it was because of your change, but your change only made it clear that this is a problem, it didn't introduce the problem.

i have been noticing this problem for a while now. We have same code in ClusterFuzz, but there we land PRs quickly. In OSS-Fuzz old PRs stay and now commits are happening fast.

**Comment by jonathanmetzman** [comment]
> > I'll look into it too.
> > I realize now there's no reason this should be assigned to you in particular. When I filed this I thought it was because of your change, but your change only made it clear that this is a problem, it didn't introduce the problem.
> 
> i have been noticing this problem for a while now. We have same code in ClusterFuzz, but there we land PRs quickly. In OSS-Fuzz old PRs stay and now commits are happening fast.

There's a somewhat similar problem in CIFuzz btw: https://github.com/google/oss-fuzz/issues/5010

Maybe the solution is to diff against the parent branch instead of FETCH_HEAD.

**Comment by inferno-chromium** [comment]
git diff --name-only $(git merge-base HEAD $(git rev-parse --abbrev-ref origin/HEAD))..
