### ISSUE TITLE
Clusterfuzz UI: make "redo task" less confusing

### ISSUE THREAD

**Issue by robryk** [google/oss-fuzz#504]
The "redo task" button now allows one to specify a set of "tasks" that can be redone. Those tasks are called "minimize", "regressed" and "fixed". While it's obvious what will happen when I ask for "minimize" to be redone (the minimal example will be recomputed), it's unobvious what will happen when I ask for "regressed" or "fixed" to be redone.

**Comment by oliverchang** [comment]
Hmm, I think we can either rename these or add some kind of description to each (tooltip?). @tanin47, what do you think?

**Comment by inferno-chromium** [comment]
We now fixed to have better strings and tooltips which explain their purpose.
