### ISSUE TITLE
Fuzz targets not found for llvm_libcxx project

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#5047]
OSS-Fuzz/ClusterFuzz only allows .exe, .par extension or no extension (most targets). This is done to avoid parsing libs and other unrelated files. 

@ldionne - Need to remove this line - https://github.com/llvm/llvm-project/blob/main/libcxx/utils/ci/oss-fuzz.sh#L13. can you please fix this.

**Comment by inferno-chromium** [comment]
Disabling project as unmaintained as well, both fuzzing and coverage builds failing - https://github.com/google/oss-fuzz/blob/master/projects/llvm_libcxx/project.yaml#L10

**Comment by ldionne** [comment]
This *is* maintained, it's just that it's very difficult to troubleshoot issues with your system. I'm trying to reproduce the issues locally so I can fix them, but I get:

```
% python infra/helper.py check_build llvm_libcxx
Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -v <snip>/build/out/llvm_libcxx:/out -t gcr.io/oss-fuzz-base/base-runner test_all
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "test_all": executable file not found in $PATH: unknown.
Check build failed.
```

**Comment by jonathanmetzman** [comment]
> This _is_ maintained, it's just that it's very difficult to troubleshoot issues with your system. I'm trying to reproduce the issues locally so I can fix them, but I get:
> 
> ```
> % python infra/helper.py check_build llvm_libcxx
> Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -v <snip>/build/out/llvm_libcxx:/out -t gcr.io/oss-fuzz-base/base-runner test_all
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "test_all": executable file not found in $PATH: unknown.
> Check build failed.
> ```

Have you pulled recently from master? I think the error you see will be fixed by doing that.

**Comment by inferno-chromium** [comment]
> This _is_ maintained, it's just that it's very difficult to troubleshoot issues with your system. I'm trying to reproduce the issues locally so I can fix them, but I get:
> 
> ```
> % python infra/helper.py check_build llvm_libcxx
> Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -v <snip>/build/out/llvm_libcxx:/out -t gcr.io/oss-fuzz-base/base-runner test_all
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "test_all": executable file not found in $PATH: unknown.
> Check build failed.
> ```

Can you try with commands mentioned in logs - https://oss-fuzz-build-logs.storage.googleapis.com/index.html#llvm_libcxx
```
python infra/helper.py build_image llvm_libcxx
python infra/helper.py build_fuzzers --sanitizer address --engine libfuzzer --architecture x86_64 llvm_libcxx
```

**Comment by ldionne** [comment]
> Have you pulled recently from master? I think the error you see will be fixed by doing that.

Yes, I pulled today.

@inferno-chromium 
I think I figured it out. But in order to do that, I had to boot the docker image without running the default scripts:

```
$ docker run --rm --privileged -i --cap-add SYS_PTRACE -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -e FUZZING_LANGUAGE=c++ -v <snip>/oss-fuzz/build/out/llvm_libcxx:/out -v <snip>/oss-fuzz/build/work/llvm_libcxx:/work -t gcr.io/oss-fuzz/llvm_libcxx bash
```

And then, from the Docker image:

```
$ compile
$ ../build.sh
$ apt-get install vim
edit-build-test loop
```

That wasn't obvious at first. Would it be possible to provide an easier way to do that? It would greatly help with reproducing issues.

**Comment by ldionne** [comment]
The fix should be in https://github.com/llvm/llvm-project/commit/4210b87020b9e558f650993d6a274807083ac5f6

**Comment by inferno-chromium** [comment]
@ldionne - can you remove this line as well - https://github.com/llvm/llvm-project/blob/main/libcxx/utils/ci/oss-fuzz.sh#L13
otherwise fuzz targets are not detected. 
i have reenabled project in https://github.com/google/oss-fuzz/commit/6fb0ce93667bdef91a4829c8ca5f238db0fbea50

**Comment by ldionne** [comment]
That line takes a filename of the form `testfile.pass.cpp` and transforms it into `testfile`. We previously hit issues with `.pass.cpp` extensions not being supported executables, and made that change as a result to try and fix the build.

Do you really want me to remove that line? I'll do it if you want me to, but I want to double-check we're on the same page about what it does.

**Comment by inferno-chromium** [comment]
> That line takes a filename of the form `testfile.pass.cpp` and transforms it into `testfile`. We previously hit issues with `.pass.cpp` extensions not being supported executables, and made that change as a result to try and fix the build.
> 
> Do you really want me to remove that line? I'll do it if you want me to, but I want to double-check we're on the same page about what it does.

yes those .pass.cpp files are not detected as fuzzers by clusterfuzz, so we need to remove those. i dont think check_build will break on this, but you can easily verify with these

```python infra/helper.py build_image llvm_libcxx
python infra/helper.py build_fuzzers --sanitizer address --engine libfuzzer --architecture x86_64 llvm_libcxx
python infra/helper.py check_build --sanitizer address --engine libfuzzer --architecture x86_64 llvm_libcxx
```

**Comment by ldionne** [comment]
Let me just restate. The line you are asking me to remove is specifically the line that renames those `<filename>.pass.cpp` files into `<filename>`. It removes the extensions to make sure they are detected as fuzzers. If I remove that line, then the filenames will have the `.pass.cpp` extension and won't be detected as fuzzers, if I follow you correctly.

I am getting emails saying that fuzzing errors were discovered, so I guess this means the fuzzing is happening as expected. I think we should be OK to close this unless I didn't get something.

**Comment by inferno-chromium** [comment]
> Let me just restate. The line you are asking me to remove is specifically the line that renames those `<filename>.pass.cpp` files into `<filename>`. It removes the extensions to make sure they are detected as fuzzers. If I remove that line, then the filenames will have the `.pass.cpp` extension and won't be detected as fuzzers, if I follow you correctly.
> 
> I am getting emails saying that fuzzing errors were discovered, so I guess this means the fuzzing is happening as expected. I think we should be OK to close this unless I didn't get something.

Yes ignore my bash misunderstanding :( you are right, it is stripping correctly.
