### ISSUE TITLE
Create sudo fuzzers

### ISSUE THREAD

**Issue by blackgnezdo** [google/oss-fuzz#5050]
In light of the [recent bug in sudo](https://www.sudo.ws/alerts/unescape_overflow.html) it makes sense to add a fuzzer. Hopefully fuzzing the command line of a setuid binary is not too special for clusterfuzz to support? 

Bonus points for also fuzzing PAM configuration and sudoers file.

**Comment by inferno-chromium** [comment]
This has now started with few fuzzers already landed. and we are encouraging sudo developer to write even more.
