### ISSUE TITLE
LibreOffice build seems to be running out of space

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#506]
e.g. https://oss-fuzz-build-logs.storage.googleapis.com/log-1d7bd595-6568-4e6f-a8b5-213389da18f4.txt

Step #3: zip I/O error: No space left on device
Step #3: zip error: Output file write failure (write error on zip file)
Finished Step #3

**Comment by oliverchang** [comment]
Will file a request to increase the disk space on the builders.

**Comment by oliverchang** [comment]
In the meantime, I implemented an ugly workaround that should hopefully unblock the libreoffice build: https://github.com/google/oss-fuzz/commit/cb91f9957f56baee3d19a8dc1ed7c6ca5eba6368

**Comment by oliverchang** [comment]
Builds are succeeding again.
