### ISSUE TITLE
Linker errors with afl++ due to wrong CC/CXX, need to use env vars

### ISSUE THREAD

**Issue by rlohning** [google/oss-fuzz#5093]
Hi,

different projects ran into linker errors with afl today, see
https://oss-fuzz-build-logs.storage.googleapis.com/log-d9c44c8c-807c-4b40-b5bc-3e7d037ff36e.txt
https://oss-fuzz-build-logs.storage.googleapis.com/log-f199b794-0f4d-4de9-b308-c4536ad68cc9.txt
```
Step #22: /usr/lib/libFuzzingEngine.a(aflpp_driver.o): In function `main':
Step #22: /src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:236: undefined reference to `__afl_manual_init'
Step #22: /src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:244: undefined reference to `__afl_manual_init'
Step #22: /src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:251: undefined reference to `__afl_persistent_loop'
Step #22: /src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:251: undefined reference to `__afl_persistent_loop'
Step #22: /src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:262: undefined reference to `__afl_fuzz_len'
Step #22: /src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:265: undefined reference to `__afl_fuzz_ptr'
```
Did we make the same mistake in our projects or is there something wrong with your afl setup? I'd appreciate if you could have a look.

Cheers,
Robert

**Comment by inferno-chromium** [comment]
I think this
https://github.com/google/oss-fuzz/pull/5095 should fix them, giving a try.

**Comment by rlohning** [comment]
Today's second build failed, too: https://oss-fuzz-build-logs.storage.googleapis.com/log-e328e84e-c43f-4354-8392-987d8acb875a.txt

**Comment by inferno-chromium** [comment]
@rlohning - does this comment response in any way - https://github.com/google/oss-fuzz/issues/4280#issuecomment-771474395 [@vanhauser-thc fyi)
---
ibmswtpm2:
your paste already shows it is not using afl-clang-fast++ but clang++ - that is the issue.
---
Is it using CC, CXX correctly ?
Same issue looks to be in QT

**Comment by rlohning** [comment]
> Is it using CC, CXX correctly ?

Obviously not. Thanks for the pointer.
