### ISSUE TITLE
Autoconf update causes failure to build PCRE2

### ISSUE THREAD

**Issue by PhilipHazel** [google/oss-fuzz#5122]
My autoconf got updated to 2.70 and when run it required some updates to configure.ac. This has caused PCRE2 builds to fail on oss-fuzz because it seems to run ./autogen.sh before ./configure, and it has an older version of autoconf. Is is necessary to run ./autogen.sh? Can it not just run ./configure?

**Comment by PhilipHazel** [comment]
Oops, I have just realized that ./configure doesn't get saved in the repository, so oss-fuzz has to run  ./autogen.sh. What's the best way to solve this?

**Comment by inferno-chromium** [comment]
you can upgrade things in dockerfile or remove autoconf. no clue here.

**Comment by PhilipHazel** [comment]
I'm afraid I have completely forgotten how this fuzzing was set up (I know, I know, I should have taken notes). How do I get to dockerfile?

**Comment by inferno-chromium** [comment]
https://github.com/google/oss-fuzz/tree/master/projects/pcre2
and then to verify locally, try this
https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-build-failures

**Comment by PhilipHazel** [comment]
Thank you. In the end I didn't need to do anything because tests showed that the requirement for autoconf 2.70 was not actually necessary. Downgrading the requirement to 2.60 has fixed things. But I've noted the above URLs for the future.
