### ISSUE TITLE
Aflplusplus ASAN wrongly marked bugs as fixed

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#5133]
For instance https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=28399#c3 
(this is a failed assert)
It states ClusterFuzz testcase 5759205634080768 is verified as fixed and the regression revision range is
```
COMPONENT | REVISION RANGE
-- | --
Suricata | 62e665c8482c90b30f6edfa7b0f0eabf8a4fcc79
Aflplusplus | 068bef5eab942df0a133c92522f2ab81b28ac636:1f71b85426f837ebcae8381897d44a3a67c73a4f
```

In the same time https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=30400 got created with the same stack trace (it uses MSAN instead of ASAN for the previous report) :

```

COMPONENT | REVISION RANGE
-- | --
Suricata | 62e665c8482c90b30f6edfa7b0f0eabf8a4fcc79
Aflplusplus | 068bef5eab942df0a133c92522f2ab81b28ac636:1f71b85426f837ebcae8381897d44a3a67c73a4f

```

**Comment by inferno-chromium** [comment]
even though aflplusplus shows up in component list, this bug was found on libfuzzer asan and somehow that repro got flaky and marked fixed. if this pattern repeats, then we can investigate, otherwise can close.

**Comment by catenacyber** [comment]
Ok, closing for now
