### ISSUE TITLE
Issue incorrectly marked as fixed

### ISSUE THREAD

**Issue by micahsnyder** [google/oss-fuzz#5138]
My project received a notification that [issue 30469](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=30469#c2) was verified (fixed).  It hasn't been fixed, yet. 

The issue was reported 2021-02-07.  If I understand correctly, oss-fuzz discloses issues 30 days after they're Verified. This wouldn't fit our schedule and we need the disclosure date to remain as it was (2021-05-10).  Can someone please help correct the ticket?

**Comment by micahsnyder** [comment]
Additional context, it seems this issue is actually a duplicate of [issue 29504](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=29504) for which the disclosure date is 2021-04-12.  

If the disclosure date for issue 30469 could be edited to match issue 29504, that would also work for us.

**Comment by inferno-chromium** [comment]
Marked it duplicate, shouldn't open it early.

But also no need on worry on this one, since it looks like simple null deref (not a security bug).

**Comment by micahsnyder** [comment]
My team considers null derefs to be security bugs because they kill the application.  It's not a dangerous one, but it has a big impact.  Anyways, thank you for your help!

**Comment by inferno-chromium** [comment]
> My team considers null derefs to be security bugs because they kill the application. It's not a dangerous one, but it has a big impact. Anyways, thank you for your help!

Makes sense, thanks for explaining!
