### ISSUE TITLE
[cifuzz] recommendation for go, ci and pull requests

### ISSUE THREAD

**Issue by roidelapluie** [google/oss-fuzz#5141]
Hello 👋🏻 

[Prometheus](https://github.com/prometheus/prometheus) is instrumented with oss-fuzz. We are registered and we use the CIFuzz as well.

I did notice that our Docker file uses
https://github.com/google/oss-fuzz/blob/0e6b81c81b415bb584c8d7595264480fa5a7de84/projects/prometheus/Dockerfile#L18

That is fine for fuzzing master, but it also means that pull requests that change go.mod are always getting the dependencies from master, and not from the pull request branch.

What would be the way forward? Should we do a 'go get ./...'  or 'go mod vendor' in build.sh ?

**Comment by SuperQ** [comment]
I think it would be fine to disable fuzzing PRs for now. Fuzzing master is probably good of a feedback loop.

**Comment by roidelapluie** [comment]
> I think it would be fine to disable fuzzing PRs for now. Fuzzing master is probably good of a feedback loop.

Yes, let's use that workaround as a stop-gap but I'd like to see this resolved in the mid-term.

**Comment by inferno-chromium** [comment]
> Hello 👋🏻
> 
> [Prometheus](https://github.com/prometheus/prometheus) is instrumented with oss-fuzz. We are registered and we use the CIFuzz as well.
> 
> I did notice that our Docker file uses
> https://github.com/google/oss-fuzz/blob/0e6b81c81b415bb584c8d7595264480fa5a7de84/projects/prometheus/Dockerfile#L18
> 
> That is fine for fuzzing master, but it also means that pull requests that change go.mod are always getting the dependencies from master, and not from the pull request branch.
> 
> What would be the way forward? Should we do a 'go get ./...' or 'go mod vendor' in build.sh ?

Yes feel free to change it so that it uses from source and not from latest master. i think that was a mistake in integration.

**Comment by jonathanmetzman** [comment]
@roidelapluie how did you solve this? Did you decide not to use CIFuzz in the end?

**Comment by roidelapluie** [comment]
Thanks, we are now using ci fuzz again.
