### ISSUE TITLE
Access to oss-fuzz not authorized

### ISSUE THREAD

**Issue by jedisct1** [google/oss-fuzz#5158]
Hi!

I’m receiving all the emails sent but cannot access the website to see actual reports (“you’re not authorized to access this page”), even when connected with the Gmail account emails are sent to.

Would it be possible to get access?

Thank you!

**Comment by jedisct1** [comment]
Maybe this is due to the `+ossfuzzz` suffix in the email address?

**Comment by oliverchang** [comment]
Hi, yes we do an exact email match for access to oss-fuzz reports. Would you be able to remove this from the project.yaml ?
