### ISSUE TITLE
Reduce docker image sizes

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#5170]
Right now they take a long time to pull which slows down CIFuzz (currently it spends about 1.5 minutes downloading base-builder and about 20 seconds downloading base-runner) and is generally annoying.
We should fix this.

Some alternatives:
1. I tried squashing the image layers which doesn't seem to help.
2. Caching in CIFuzz. I suspect this won't help since I think the cache has to download the files from somewhere. Also, the output of docker save is 3.4 GB uncompressed. I bet we will soon hit the limit of github action's cache (5 GB).

Some ideas for how to do this:

Right now they take a long time to pull which slows down CIFuzz (currently it spends about 1.5 minutes downloading base-builder and about 20 seconds downloading base-runner) and is generally annoying.
We should fix this.

Some alternatives:
1. I tried squashing the image layers which doesn't seem to help.
2. Caching in CIFuzz. I suspect this won't help since I think the cache has to download the files from somewhere. Also, the output of docker save is 3.4 GB uncompressed. I bet we will soon hit the limit of github action's cache (5 GB).

Some ideas for how to do this:

- [x] Split up base-builder into multiple images for each programming language. It's not sustainable to install .5 GB of dependencies in the images everyone uses for each language we support.
- [x] Delete things from clang install. There are tons of llvm-* binaries that probably aren't needed. This is also the largest layer in our image. We can probably look at the chromium clang install for inspiration. I think there's about 900MB of savings here if I'm conservative about what I delete.
- [x] Delete things from cmake install (we don't need cmake-gui) (#5161) (70 MB of savings).
- [x] Delete things from python install. There's a 63.4 MB test directory that looks unneeded (see https://bugs.python.org/issue27640) (another 63.4MB directory in /usr/local/lib/python3.8) and 10 MB in __pycache__.
- [x] Delete things from go/go-fuzzer install. There's 85.6 MB in /root/go/src,, 13.6 MB in /root/.go/test and 4 MB in /root/.go/doc that I bet can be deleted.
- [x] Delete things from rust install. /rust/registry/index/github.com-1ecc6299db9ec823/.git is 78 MB.
- [x] Delete the cache directory (14 MB of pip and go package stuff there).

**Comment by inferno-chromium** [comment]
Yes Rust was like some 400 mb and llvm was like some 1.5 gb madness. Rust we can start with creating a base-rust, and can remove unneeded llvm stuff. Unsure if seperating others like python, go etc are worth it.

**Comment by oliverchang** [comment]
@jonathanmetzman what's the state here? Is it still worth splitting up the base images into ones for separate languages? 

@asraa  mentioned that she would be interested in learning some OSS-Fuzz infra and this seems like a good starter project to me to learn many pieces.

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman what's the state here? Is it still worth splitting up the base images into ones for separate languages?
> 
> @asraa mentioned that she would be interested in learning some OSS-Fuzz infra and this seems like a good starter project to me to learn many pieces.

I think it would probably be helpful (especially in the long term). But I'm worried it will complicate things for devs to do this.
Need to think a bit more.

**Comment by oliverchang** [comment]
I think we should go ahead with this. Re complicating things, this would be for people adding new projects right?

We can just add a new required language argument for `python infra/helper.py generate <PROJECT>` command. This can also populate the attribute in `project.yaml` and use the correct base image name.

This shouldn't complicate things too much, or are there other things I'm not thinking of?

**Comment by jonathanmetzman** [comment]
> I think we should go ahead with this. Re complicating things, this would be for people adding new projects right?
> 

Yes. This is 99% of what I'm worried about.

> We can just add a new required language argument for `python infra/helper.py generate <PROJECT>` command. This can also populate the attribute in `project.yaml` and use the correct base image name.

Sounds good to me.

> 
> This shouldn't complicate things too much, or are there other things I'm not thinking of?

You're basically right.
The only other case that's on my mind are multi language projects.

I think it's not a huge concern and that there's an easy way to solve this.
Basically, instead of putting the logic for, as an example, installing the JVM directly in the base-java-builder image, we can put it an a script install_java_deps.sh which base-java-builder execute.
This would allow someone using a multi-language project to (fairly) easily install dependencies for another language by running the script as well.

There's also the issue of base-runner.
However, I'm pretty sure the image size is much smaller so it doesn't really matter.

**Comment by oliverchang** [comment]
Discussed this more with @jonathanmetzman today.

Having `install_{java,rust,swift,etc}_deps.bash` in base-builder seems like the way to go. Then we can have pre-built `base-builer-{lang}` which calls those scripts. If a multi-language project requires more, they can call those scripts manually. 

The size of base-runner isn't a big deal right now so we probably don't need to worry about it. 

@asraa Would you like to give this a shot?

**Comment by jonathanmetzman** [comment]
Worth noting that pulling base-builder takes about 40 seconds now (see https://github.com/systemd/systemd/runs/2402303605?check_suite_focus=true) instead of 90 seconds.

**Comment by jonathanmetzman** [comment]
This is done
