### ISSUE TITLE
Support fuzzing Java

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#5178]
Metabug for Java fuzzing.

**Comment by jonathanmetzman** [comment]
PR for adding Jazzer to docker image: #5166
PR for handling jazzer in bad_build_check: #5176

**Comment by jonathanmetzman** [comment]
Sorry, #5182 was linked here by mistake.

**Comment by jonathanmetzman** [comment]
JVM install in ClusterFuzz: https://github.com/google/clusterfuzz/pull/2244#pullrequestreview-591690411

**Comment by fmeum** [comment]
Deprecate Java assertions and make fuzz targets void functions: https://github.com/google/oss-fuzz/pull/5251

**Comment by jonathanmetzman** [comment]
I think the last issue to solve here is with crashes in native code.

**Comment by fmeum** [comment]
I just noticed that the status badges are not yet available for the onboarded JVM projects (see e.g. https://oss-fuzz-build-logs.storage.googleapis.com/badges/json-sanitizer.svg). But maybe they are simply not refreshed that often?

**Comment by fmeum** [comment]
@inferno-chromium Sorry, I did not expect a comment reference to auto close this issue. Could you reopen it for the very last step (fixing fuzzing of native libraries)?

**Comment by fmeum** [comment]
I had to apply another fix on the Jazzer side, but got the first report of a (synthetic) bug in native code: http://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33246

This issue can be closed now. Thanks for the support!
