### ISSUE TITLE
[CIFuzz] Support for python?

### ISSUE THREAD

**Issue by wiredfool** [google/oss-fuzz#5195]
I've been working on improving oss-fuzz support for Pillow, with the near term goal of adding CIFuzz support so that we get some realtime feedback when people contribute c level changes. 

The CIFuzz integration hasn't been going well, and I've traced it to this:

https://github.com/google/oss-fuzz/blob/master/infra/cifuzz/build_fuzzers.py#L202
```
      '-e',
      'CIFUZZ=True',
      '-e',
      'FUZZING_LANGUAGE=c++',  # FIXME: Add proper support.                                                            
  ]
```

Is the fix for this as simple as just getting the language from the `project.yml` file, or is there something more complicated due to the lack of support of oss-fuzz for coverage of python projects?

As an aside, it would be nice if the documentation mentioned limitations like this before burning a bunch of developer time.

**Comment by inferno-chromium** [comment]
Sorry about this, CIFuzz is in active development, and we can fix this language hardcode sometime soon.

Fyi, code coverage is not supported yet for Python (only exists for C/C++, Golang, Rust (soon). @IanPudney @Google-Autofuzz for any ideas on supporting coverage here.

**Comment by IanPudney** [comment]
Hi,

I don't know much about CIFuzz, but collecting code coverage for native extensions to Python should work the same as collecting code coverage for wholly native binaries.

Reporting code coverage for Python code could be implemented. In fact, Atheris uses the same hooks to gather coverage information as coverage.py, the typical tool for measuring Python test code coverage.

**Comment by jonathanmetzman** [comment]
> Sorry about this, CIFuzz is in active development, and we can fix this language hardcode sometime soon.
> 
> Fyi, code coverage is not supported yet for Python (only exists for C/C++, Golang, Rust (soon). @IanPudney @Google-Autofuzz for any ideas on supporting coverage here.

Code coverage isn't a prerequisite but is good for CIFuzz to have (it lets us run just the affected fuzzers rather than all of them).
I'll try to remove this language hardcode, and I'll mention that C/C++ projects are the only ones supported currently in the docs.

**Comment by wiredfool** [comment]
Pillow does collect coverage for both Python and C-extansion code during our test runs (https://app.codecov.io/gh/python-pillow/Pillow) using a specific makefile rule: https://github.com/python-pillow/Pillow/blob/master/Makefile#L61 .

I would hope that it should be possible to connect this up with whatever oss-fuzz is using for coverage. 

In the current case though -- since there's only one fuzzer for pillow at the moment, it wouldn't help determine which fuzzer to run.

**Comment by jonathanmetzman** [comment]
@wiredfool I think I can add support very soon (see #5222)
Could you try again once I've added support?

**Comment by wiredfool** [comment]
Sure thing.

**Comment by wiredfool** [comment]
Looks like it ran with that PR. Thanks!
