### ISSUE TITLE
helper shell to support fuzzer developing and debugging

### ISSUE THREAD

**Issue by kcwu** [google/oss-fuzz#52]
I know I always can run docker command explicitly to build any fancy env I want. But I feel helper script should provide better support for common usage.
1. fuzzer developing.
   When developing fuzzer, I may need to modify build script, fuzzer code, and sometimes the library code. In the past, /src is shared, I can run editor outside the docker in one terminal while run build script in another terminal. The development cycle is fast.
   
   Now the /src is not shared. If I need to modify fuzzer code, I need to either install/setup my editor inside docker (inconvenient) or run full build_fuzzers script (slow).
   
   If I need to tweak the library code, although I can edit inside the docker, I need to think how to send the diff to outside of docker.
   
   I don't know what is the best solution. I feel it may be good idea to add `--mount DIR` option (which add `-v $DIR:/mnt` to docker command line) to the helper script. Then I can sync my work between inside and outside of docker. 
2. debugging support
   I know [this doc](https://github.com/google/oss-fuzz/blob/master/docs/debugging.md). It would be great that helper script supports it natively.

**Comment by mikea** [comment]
Did you see this: https://github.com/google/oss-fuzz/blob/master/scripts/helper.py ?
It is also used in new library doc.

**Comment by kcwu** [comment]
Yes, I am asking to improve the helper script.

**Comment by kcc** [comment]
Such improvements might be useful, but in general I don't think we should consider oss-fuzz as a replacement for development environment. You should fist develop the fuzz target in the regular setting and then port the working target to oss fuzz. No?

**Comment by kcwu** [comment]
Good point. In the past I develop the fuzzer directly inside the docker. It sounds reasonable to develop from outside first. I will try that later.

But I still feel it is good to improve debugging support because who develop the fuzzer is probably not who need to debug the library. And replicate the exact same env is sometimes necessary for debugging.

**Comment by MarcoFalke** [comment]
See also https://github.com/google/oss-fuzz/pull/5455
