### ISSUE TITLE
Incorrectly merged issue?

### ISSUE THREAD

**Issue by nikic** [google/oss-fuzz#5211]
For the php project, we have two memory leaks, one is https://oss-fuzz.com/testcase-detail/6195816295432192 and the other is https://oss-fuzz.com/testcase-detail/6029559193534464. However, both point to the same issue https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=30584.

This seems odd to me, because these are leaks for different fuzz targets (php-fuzz-execute and php-fuzz-unserialize), and the leak traces differ at the start (though there are some common functions in them). The root cause is different as well.

**Comment by inferno-chromium** [comment]
This happens with automation, we overgroup things that look similar. You can either fix the first one and next one will file in 2 days or can file it manually by clicking file issue button.
