### ISSUE TITLE
Go coverage build - "OLDPWD not set"

### ISSUE THREAD

**Issue by AdamKorcz** [google/oss-fuzz#5234]
Thank you to everyone who worked on the Go builds over the last couple of days.

I am opening this issue in regards to the Go coverage builds as well.

We currently get the error `/usr/local/bin/compile_go_fuzzer: line 46: cd: OLDPWD not set`

...which makes sense in case this path does not exist: https://github.com/google/oss-fuzz/blob/6fe9d7f01d04bb5ce282942a07d71a1114f5576c/infra/base-images/base-builder/compile_go_fuzzer#L26

Then when we `cd -`, `OLDPWD` is not defined: https://github.com/google/oss-fuzz/blob/6fe9d7f01d04bb5ce282942a07d71a1114f5576c/infra/base-images/base-builder/compile_go_fuzzer#L46

**Comment by inferno-chromium** [comment]
@catenacyber - can you please check.

**Comment by catenacyber** [comment]
I think we can remove this line `cd -` now...
For which project did you see the problem @AdamKorcz ?

**Comment by AdamKorcz** [comment]
@catenacyber 
I posted 3 links above which experienced this issue. 

It seems it is simply because the projects do not reside in $GOPATH, and the coverage build script expects projects to be there.

**Comment by jonathanmetzman** [comment]
@AdamKorcz @catenacyber Is this still an issue or can we close this?

**Comment by AdamKorcz** [comment]
Closing as this is solved.
