### ISSUE TITLE
Auto CC's making changes to isssues?

### ISSUE THREAD

**Issue by asraa** [google/oss-fuzz#5236]
Hi!

I have a very quick question. Are there different levels of OSS-Fuzz permissions? On an issue, I have options to change labels and owners, but my teammate only has the option to change owners. (This is non-security related 
![image](https://user-images.githubusercontent.com/5194569/108732020-29b0d480-74fb-11eb-80ed-20ffe27daafb.png)

My teammate only sees, but we are both on auto-ccs
![image](https://user-images.githubusercontent.com/5194569/108731959-1aca2200-74fb-11eb-9831-882c41d30f9d.png)

This is the issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=31007&sort=-opened&can=1&q=proj%3Aenvoy%20status%3DNew#makechanges

These are the team members
https://github.com/google/oss-fuzz/blob/6fe9d7f01d04bb5ce282942a07d71a1114f5576c/projects/envoy/project.yaml#L12-L13

**Comment by inferno-chromium** [comment]
Yes, monorail edit permissions to change issue params (e.g. status) is manual and those folks need to be manually added. In most OSS-Fuzz workflows, we shouldn't require changing status or assigning owners. Please email me if those folks would be needing that access and i can add them.
