### ISSUE TITLE
Run tests when building base-images

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#526]
We want to prevent things like https://github.com/google/oss-fuzz/commit/49baa72f5b1dc40e21f01988fc0055d4b1e28e93 from happening again.

**Comment by inferno-chromium** [comment]
We should still run tests even after we are using pinned chromium revision. The reason being we are running on tip-of-tree libFuzzer and that can still break. Assigning to Max.

**Comment by inferno-chromium** [comment]
I think @Dor1s bad build checks will catch this. @oliverchang - do you think we need to run all llvm test here or bad build check is a reasonable stopgap ? if yes, please close.

**Comment by oliverchang** [comment]
I think the bad build checks are a reasonable stopgap. Closing!
