### ISSUE TITLE
restart failed builds

### ISSUE THREAD

**Issue by dtardon** [google/oss-fuzz#529]
Could the builds of dlplibs and libreoffice be redone? They both failed for the same reason: "Unable to find a source package for ..." in apt-get build-dep, which I assume was a temporary glitch in Ubuntu repos as it works fine locally. (Please ignore this if the system retries failed builds automatically. I've been unable to find any info regarding this.)

**Comment by inferno-chromium** [comment]
forced rebuild, but it should retry in <1 day. please close bug after you verify builds are fine in a hour or so.

**Comment by dtardon** [comment]
Hm, so this is not a transient glitch after all. I tried to build on a different machine, where I had never used docker before, and I'm getting the same error... Apparently the source repos, needed for "apt-get build-dep" to work, used to be enabled, but are not anymore. Let's close this; a proper fix is on the way.
