### ISSUE TITLE
go-ethereum: access denied errors (configuration + coverage reports)

### ISSUE THREAD

**Issue by holiman** [google/oss-fuzz#5316]
We're having some problems with the go-ethereum integration. Trying to access https://oss-fuzz.com/configuration, I get
```
You (email=martin.swende@ethereum.org) are not authorized to access this page!
```
Even though I'm listed here:  https://github.com/google/oss-fuzz/blob/master/projects/go-ethereum/project.yaml#L5 
 
And when trying to access coverage reports (e.g. https://storage.googleapis.com/oss-fuzz-coverage/go-ethereum/reports/20210307/linux/index.html ) gives me an xml-version of access denied. 

The same happens to @karalabe, who is the "primary contact" in the project yaml (https://github.com/google/oss-fuzz/blob/master/projects/go-ethereum/project.yaml#L2).

**Comment by jonathanmetzman** [comment]
Sorry you are experiencing this and than you for this report.
Is your email provided by Google Apps? If not, I think that is the problem, I think it needs to be a google account to sign in.
We can try changing the email accounts to gmail ones if you want to provide them.

**Comment by holiman** [comment]
Yes, we're using google apps email addresses

**Comment by holiman** [comment]
Also, since it literally says `You (email=martin.swende@ethereum.org) are not authorized to access this page!` -- it obviously successfully authenticated me, by email address. 

So authentication works, but the authorization seems to be off.

**Comment by jonathanmetzman** [comment]
> Yes, we're using google apps email addresses

Oh sorry didn't notice you were accessing oss-fuzz.com/configuration.
This is a page for administrators (it's for oss-fuzz.com as a whole not just go-ethereum). So this works-as-intended. Why did you want to access that page?

As for https://storage.googleapis.com/oss-fuzz-coverage/go-ethereum/reports/20210307/linux/index.html
That page is not accessible to me either. It does not exist. I'm not sure why that is, but it seems like the last report with an index.html for your project was made on 2021-02-16. See

https://storage.googleapis.com/oss-fuzz-coverage/go-ethereum/reports/20210216/linux/index.html is still accessible.

Maybe there is an issue with go coverage reports.

**Comment by holiman** [comment]
Ah I see. 
> Why did you want to access that page?

Well, mainly because I wanted to look into any permission-problems with the coverage reports. But I guess this is not an access problem, but coverage report problem, so closing this. Thanks!

**Comment by holiman** [comment]
Ah, cool, I'll reopen this and let #5319 close it when merged
