### ISSUE TITLE
minimize AFL testcases with libFuzzer

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#537]
Right now AFL testcases aren't minimized. It should be easy to minimize the testcase using the corresponding libFuzzer target.

**Comment by oliverchang** [comment]
This is done

**Comment by kcc** [comment]
I see afl-reported bugs with not minimized repros. 
E.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1933
The input is 1Kb, libFuzzer quickly minimizes it down to 3 bytes.

**Comment by oliverchang** [comment]
Hmm, not sure what happened here in the initial run -- the logs say that we weren't able to reproduce this crash with libFuzzer target.

re-doing the minimize (with the same build revision) seems to work. the minimized repro is 3B now.

**Comment by oliverchang** [comment]
Not seeing this on our recent AFL testcases. This might've been fixed by the fix for #665
