### ISSUE TITLE
Coverage build spuriously failed for jbig2dec

### ISSUE THREAD

**Issue by sebras** [google/oss-fuzz#5371]
In issue 31971 OSS-fuzz informed me that the jbig2dec coverage build failed with:

```
Step #7: Operation completed over 25 objects/2.1 MiB.                                     
Finished Step #7
Starting Step #8
Step #8: Already have image (with digest): gcr.io/cloud-builders/gsutil
Step #8: CommandException: 1 files/objects could not be removed.
Finished Step #8
Starting Step #9
Step #9: Already have image (with digest): gcr.io/cloud-builders/gsutil
Step #9: Copying file:///workspace/out/coverage/fuzzer_stats/jbig2_fuzzer.json [Content-Type=application/json]...
Step #9: / [0/1 files][    0.0 B/  6.8 KiB]   0% Done                                    
/ [1/1 files][  6.8 KiB/  6.8 KiB] 100% Done                                    
Step #9: Operation completed over 1 objects/6.8 KiB.                                      
Finished Step #9
Starting Step #10
Step #10: Already have image (with digest): gcr.io/cloud-builders/gsutil
Step #10: CommandException: 1 files/objects could not be removed.
TIMEOUT
ERROR: context deadline exceeded
```

I believe that this is a service problem and not anything that I can affect from the fuzzer.
Can you please advice me? Thank you! :)

**Comment by sebras** [comment]
The jbig2dec issue was surprisingly closed by clusterfuzz today.

Despite this I leave this bug open because I want you guys to have a look at the error log to verify that you have fixed something related recently, or if there is something that can be done to improve the error messages.

**Comment by inferno-chromium** [comment]
No clue, but will keep this open in case it happens again.

**Comment by oliverchang** [comment]
Looks like some network flake in the service we're using to build. I'm not sure if there's anything we can do here.. but perhaps if this comes up again we can tweak some timeout value somewhere.
