### ISSUE TITLE
[QUESTION] Call LLVMFuzzerInitialize just once on fork mode

### ISSUE THREAD

**Issue by illera88** [google/oss-fuzz#5376]
Hi,

Is there any easy way to only call `LLVMFuzzerInitialize` once on `fork` mode? Initialization takes a long time and I don't want it to happen per every worker but just once (as I think it makes sense to be).

Thank you

**Comment by jonathanmetzman** [comment]
Fork mode is kind of incorrectly named.
It doesn't actually use fork, I think it uses `system` or some similar call.
I don't think theres a way to do this because the children don't start with the same memory as the parent process.
@morehouse Can you confirm this?

**Comment by morehouse** [comment]
That's correct.  libFuzzer doesn't have a fork server like AFL, though we have discussed implementing one in the past.  But it is unlikely we will have cycles to do that for the foreseeable future.

Maybe a nice intern project though...

**Comment by illera88** [comment]
It will definitely be a very useful project!
Closing the ticket. Thanks guys
