### ISSUE TITLE
[image-png] Test case has infinite loop

### ISSUE THREAD

**Issue by fintelia** [google/oss-fuzz#5378]
The image-png test case contains these lines which are an infinite loop:
https://github.com/google/oss-fuzz/blob/2f9dd0753fb1ca4c56bfb55c987eeb6d7a5422d2/projects/image-png/buf_independent.rs#L72-L75

Instead of trying to pull frames out of the decoders forever, the test should either limit itself to a single frame (PNGs usually aren't animated) or should stop pulling frames once one of the decoders indicates that there are none left. 

In either case, it also looks like the test is missing a final check to see whether the reference and small image versions match.

**Comment by jonathanmetzman** [comment]
Thanks for mentioning this.
@DavidKorczynski can you look into this?

**Comment by DavidKorczynski** [comment]
@fintelia will take a look at this tomorrow.
