### ISSUE TITLE
gnutls build failure

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#538]
+ clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-coverage=trace-pc-guard,trace-cmp -stdlib=libc++ -std=c++11 -Ilib/includes devel/fuzz/gnutls_openpgp_cert_parser_fuzzer.cc -o /out/gnutls_openpgp_cert_parser_fuzzer lib/.libs/libgnutls.a -lFuzzingEngine -lpthread -Wl,-Bstatic -lhogweed -lnettle -lgmp -Wl,-Bdynamic
devel/fuzz/gnutls_openpgp_cert_parser_fuzzer.cc:18:10: fatal error: 'config.h'
      file not found
#include <config.h>
         ^~~~~~~~~~
1 error generated.
fuzzers build failed.

@alex @nmav - can you please take a look

**Comment by nmav** [comment]
Done. Should be addressed.

**Comment by inferno-chromium** [comment]
Thanks it worked.
