### ISSUE TITLE
OSS-Fuzz seems to be failing to minimize a test case

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#5388]
Trying to figure out how to reproduce https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=28525, I noticed that the testcase there wasn't minimized so I ran the minimizer by pressing the "Redo" button. Below are the logs from https://oss-fuzz.com/testcase-detail/5077351297843200
```
[2021-03-15 11:35:05 UTC] oss-fuzz-linux-zone7-host-sj70-2: Minimize task started.
[2021-03-15 11:35:23 UTC] oss-fuzz-linux-zone7-host-sj70-2: Minimize task errored out: LibFuzzer minimization failed.
[2021-03-15 11:36:39 UTC] evverx@*.com: Redo task(s): minimize
[2021-03-15 11:37:52 UTC] oss-fuzz-linux-zone7-host-shvg-8: Minimize task started.
[2021-03-15 11:41:06 UTC] oss-fuzz-linux-zone7-host-shvg-8: Minimize task finished.
[2021-03-15 11:45:38 UTC] evverx@*.com: Redo task(s): minimize
[2021-03-15 11:47:04 UTC] oss-fuzz-linux-zone4-host-s1rz-13: Minimize task started.
[2021-03-15 11:47:23 UTC] oss-fuzz-linux-zone4-host-s1rz-13: Minimize task errored out: LibFuzzer minimization failed.
[2021-03-15 11:49:43 UTC] evverx@*.com: Redo task(s): minimize
[2021-03-15 11:50:54 UTC] oss-fuzz-linux-zone7-host-sj70-6: Minimize task started.
[2021-03-15 11:52:05 UTC] oss-fuzz-linux-zone7-host-sj70-6: Minimize task errored out: LibFuzzer minimization failed.
```

I'll try to minimize it manually but it would be great if was possible to figure out what is going on there.

cc @fishilico

**Comment by evverx** [comment]
@fishilico could you try running the following commands:
```
podman run  --rm -ti docker.io/library/archlinux
pacman -Syu git make clang llvm python flex bison xmlto docbook-xml docbook-xsl
git clone https://github.com/SELinuxProject/selinux
cd selinux
ln -s $(pwd)/libsepol/cil/include/cil libsepol/include/sepol/cil
make -C libsepol/src CC=clang CFLAGS='-O2 -g -ggdb3' LDFLAGS='-g -ggdb3' libsepol.a
make -C secilc CC=clang CFLAGS='-O2 -g -ggdb3 -I../libsepol/include' LDFLAGS='-g -ggdb3 -L../libsepol/src'
cat <<EOF >CRASH

(macro m5 ()
  (type t5b)
  (optional o5a
   (allow t5a sel (C (1)))   )
)

()


(in m5.(macro o5a ((type t))
)
)
EOF
./secilc/secilc CRASH
```
It should crash `secilc` with
```
(gdb) r
Starting program: /selinux/secilc/secilc CRASH

Program received signal SIGSEGV, Segmentation fault.
cil_copy_macro (db=<optimized out>, data=<optimized out>, copy=copy@entry=0x7fffffffe830, symtab=<optimized out>) at ../cil/src/cil_copy_ast.c:1544
1544					param_new = (struct cil_param*)curr_new->data;
(gdb) bt
#0  cil_copy_macro (db=<optimized out>, data=<optimized out>, copy=copy@entry=0x7fffffffe830, symtab=<optimized out>) at ../cil/src/cil_copy_ast.c:1544
#1  0x00005555555794c5 in __cil_copy_node_helper (orig=orig@entry=0x5555555ef9f0, finished=<optimized out>, extra_args=extra_args@entry=0x7fffffffe928) at ../cil/src/cil_copy_ast.c:2055
#2  0x000055555558c428 in cil_tree_walk_core (node=0x5555555ef9f0, process_node=process_node@entry=0x555555579000 <__cil_copy_node_helper>, first_child=first_child@entry=0x0,
    last_child=last_child@entry=0x5555555796e0 <__cil_copy_last_child_helper>, extra_args=extra_args@entry=0x7fffffffe928) at ../cil/src/cil_tree.c:272
#3  0x000055555558c54e in cil_tree_walk (node=node@entry=0x5555555ef910, process_node=0x555555579000 <__cil_copy_node_helper>, first_child=first_child@entry=0x0,
    last_child=0x5555555796e0 <__cil_copy_last_child_helper>, extra_args=extra_args@entry=0x7fffffffe928) at ../cil/src/cil_tree.c:316
#4  0x000055555557898d in cil_copy_ast (db=db@entry=0x5555555d82a0, orig=0x5555555ef6d0, orig@entry=0x5555555ef910, dest=<optimized out>) at ../cil/src/cil_copy_ast.c:2160
#5  0x0000555555588906 in cil_resolve_in (current=current@entry=0x5555555ef910, extra_args=<optimized out>, extra_args@entry=0x7fffffffea00) at ../cil/src/cil_resolve_ast.c:2499
#6  0x0000555555588a2f in cil_resolve_in_list (extra_args=extra_args@entry=0x7fffffffea00) at ../cil/src/cil_resolve_ast.c:2545
#7  0x000055555558abae in cil_resolve_ast (db=db@entry=0x5555555d82a0, current=0x5555555dc010) at ../cil/src/cil_resolve_ast.c:4025
#8  0x000055555555d827 in cil_compile (db=0x5555555d82a0) at ../cil/src/cil.c:550
#9  0x0000555555556a19 in main (argc=<optimized out>, argv=<optimized out>) at secilc.c:291
```

**Comment by evverx** [comment]
My guess would be that crash signatures changed somewhere along the way. I think I ran into something like that with MSan:  https://github.com/google/oss-fuzz/issues/3886#issuecomment-636198712

**Comment by inferno-chromium** [comment]
Can you try the "Re-upload testcase" functionality and see if you can get minimized testcase from there. this stack changing is a hard problem, we can do worse things if we keep minimizing with unrelated stacks.

**Comment by evverx** [comment]
> Can you try the "Re-upload testcase" functionality and see if you can get minimized testcase from there

@inferno-chromium I tried but it seems it got stuck. It's been in the "pending" state for more than an hour: https://oss-fuzz.com/testcase-detail/4522714925760512

**Comment by oliverchang** [comment]
> I tried but it seems it got stuck. It's been in the "pending" state for more than an hour: https://oss-fuzz.com/testcase-detail/4522714925760512

I think I broke uploads for OSS-Fuzz. Will have a fix for this shortly.

**Comment by oliverchang** [comment]
The upload has been unblocked, and it looks like both it and the original issue (https://oss-fuzz.com/testcase-detail/5077351297843200) now have a minimized testcase with a size of 18KB (compared to 22KB originally). 

Is this working as expected now?  As @inferno-chromium  mentioned most of the time minimisation failures are due to flaky stacks,

**Comment by evverx** [comment]
> The upload has been unblocked

Thanks!

> it looks like both it and the original issue (https://oss-fuzz.com/testcase-detail/5077351297843200) now have a minimized testcase with a size of 18KB (compared to 22KB originally).

To be honest, 18KB isn't helpful either. In https://github.com/google/oss-fuzz/issues/5388#issuecomment-799402426 I minimized it manually and it took 115 bytes to trigger the issue.

Anyway, [the fix](https://lore.kernel.org/selinux/CAJfZ7==dLpSiV04zRKJdSXMg-FS3uZVQcQkixdK9tJ4+4d8xvQ@mail.gmail.com/T/#m0d4a577a262f8045e4693a3ef3c07aaaa68472cd) is on its way to the selinux project so I think the issue can be closed.
