### ISSUE TITLE
ASAN_OPTIONS "strict_string_check=1" is misspelled?

### ISSUE THREAD

**Issue by Lekensteyn** [google/oss-fuzz#542]
The results in clusterfuzz show the following environment:
> `[Environment] ASAN_OPTIONS = redzone=32:handle_sigill=1:strict_string_check=1:allocator_release_to_os_interval_ms=500:strict_memcmp=1:detect_container_overflow=1:coverage=0:allocator_may_return_null=1:use_sigaltstack=1:detect_stack_use_after_return=1:alloc_dealloc_mismatch=0:detect_leaks=1:print_scariness=1:strip_path_prefix=/workspace/:max_uar_stack_size_log=16:handle_abort=1:check_malloc_usable_size=0:quarantine_size_mb=10:detect_odr_violation=0:symbolize=0:handle_segv=1:fast_unwind_on_fatal=0`

and a similar option can be found in infra/base-images/base-runner/Dockerfile

But when checking the upstream compiler-rt code (at LLVM) and the libsanitizer library of GCC, I find the plural option `strict_string_check`**s**`=1` instead:

        strict_string_checks
                - If set check that string arguments are properly null-terminated

Is this a typo?

Before enabling it, please do note that there is a bug with applications using `textdomain(NULL)`: https://github.com/google/sanitizers/issues/787

**Comment by kcc** [comment]
Yep, good catch. The correct spelling is "strict_string_checks". 
It might be somewhat scary to enable it for real, there are lots of bugs in various code bases that this flag uncovers (and those are not always the bugs that the developers want to fix)

**Comment by inferno-chromium** [comment]
Oh no!, i just enabled it and then disabled it. If earlier revisions are broken, that will break regression testing as well. Need to think more on when to enable this.

**Comment by evverx** [comment]
Would it be possible to turn it on? It's kind of a bummer that issues like https://github.com/systemd/systemd/pull/10918 are not reported by ClusterFuzz. Though, it would probably be useful if ASan could somehow signal that heap-buffer-overflows it finds due to "strict_string_checks" could be false positives so that if would be a little bit easier for people to decide whether they want to fix them or not. In my experience, pretty much everything found with the option on led to data loss. Even when it didn't it usually made sense to replace string functions with the corresponding "binary" alternatives.

**Comment by Dor1s** [comment]
From the discussion above this feels like a (potentially) controversial feature. I'm not sure what would be a good way to proceed. Ideas:

1. Make it opt-it? I think we might be already supporting it via `.options` file, it's just not documented yet :)
2. Make it the default on CF, but in a way that we won't break reproducibility for the old testcases?

I think we can try 1. @evverx can you upload a pull request that will copy `$fuzzer_name.options` file into `$OUT` with the following contents:

```
[asan]
strict_string_checks = 1
```

No promises, but I think it should work just fine :) //cc @inferno-chromium @kcc

**Comment by inferno-chromium** [comment]
yes lets do opt-in for now as part of fuzzer_name.options file. @kcc you said this can have several false positives, how to spot the real from the false positives ones.

**Comment by kcc** [comment]
I am not aware of `false positives` in the sense of C/C++ standard. 
There are just many cases when developers don't want to fix bugs reported with this aggressive setting.

**Comment by vitalybuka** [comment]
"strict_string_checks = 1" can significantly hit performance.
For some functions O(1) with "strict_string_checks = 0" gets to O(N) with "strict_string_checks = 1" with corresponding consequences for entire programs. E.g. parsers with use atoi on large files can be hit hard.

**Comment by inferno-chromium** [comment]
@kcc @vitalybuka given the performance and devs not wanting to fix this considerations, we should just keep the option disabled. i will remove the misspelled word from ADDITIONAL_ASAN_OPTIONS on clusterfuzz side to avoid confusing devs.

**Comment by evverx** [comment]
@Dor1s given that there're about 20 fuzzers in the `systemd` repository, I'd say it'd be great if I could add one "options" file to rule them all :-) Anyway, as far as I know, at least, [run_fuzzer](https://github.com/google/oss-fuzz/blob/3740c751fd9edea138c17783995d370d6b1b89bc/infra/base-images/base-runner/run_fuzzer#L91-L95) doesn't split "options" files into sections, which means that it'll most likely pass something like `-strict_string_checks=1` to fuzzers (only when `libFuzzer` is used as an engine) and I'm not sure how `libFuzzer` is going to react to it. I'll try to do it locally to see how it goes.

Regarding false positives, I think, for example, https://github.com/google/sanitizers/issues/907 can be considered a false positive. What I was trying to say is that it would be helpful if something like "found with string_strict_checks" appeared in the ASan report.

**Comment by Dor1s** [comment]
> I'd say it'd be great if I could add one "options" file to rule them all :-)

Yeah, but I'm afraid that for now you'll have to go with `for f in ...; do cp common.options $OUT/$f.options; done` :)

> as far as I know, at least, run_fuzzer doesn't split "options" files into sections

You're right, that's why I've mentioned that the features is not really documented, but on CF side `.options` parsing is a bit smarter than that :)

**Comment by evverx** [comment]
@Dor1s if I understand correctly, nobody will be able to reproduce issues found with `strict_string_checks=1` locally following https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md#reproducing-bugs. I will have to somehow manually pass whatever is hidden in "options" files. I personally have no problem with that but I'm not sure others will find this kind of UX particularly convenient :-)

**Comment by evverx** [comment]
@Dor1s I usually try to break one thing at a time (when I do it intentionally :-)) and currently I'm waiting for the next build to finish to make sure that a fuzzer that was merged yesterday compiles and passes all the checks. And then I'm going to wait for some statistics gathered by ClusterFuzz (that usually takes 2 days). After that, I think I'll be ready to break a fuzzer or two by adding `strict_string_checks=1`.

**Comment by evverx** [comment]
Interestingly, I always thought that ASan would complain about, for example, `strncpy` too, but after reading @kcc's comment I took a look at the standard and it turns out that `strncpy` doesn't exactly take string arguments and `strict_string_checks=1` doesn't help catching copying random blocks of memory via what I considered string functions. And now I'm wondering what exactly `strict_string_checks` is supposed to check.

**Comment by evverx** [comment]
Just out of curiosity, I replaced `strndup` with `malloc` followed by `strncpy` and ASan can no longer uncover https://github.com/systemd/systemd/pull/10918, which is a little bit surprising. Could it be that I'm missing something obvious?

**Comment by evverx** [comment]
I've been playing with `strict_string_checks=1` locally and in the end decided not to turn on.

It's still unclear to me what it's supposed to check and the documentation at https://github.com/google/sanitizers/wiki/AddressSanitizerFlags doesn't help much but maybe it's just me :-)

**Comment by Dor1s** [comment]
Closing an old issue.
