### ISSUE TITLE
Spam from accounts associating themselves with google

### ISSUE THREAD

**Issue by anuraaga** [google/oss-fuzz#5471]
The repo I work on recently got spammed with a code review presumably using this code

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2601#discussion_r598286774

I think so because visiting the profile has a fork of this repo.

https://github.com/lillieMaiBauer

This is actually the second time in a couple of months with the same pattern, it's been a while but if I find the link to the first time assuming the account still exists.

My friend at Google confirmed that this account is not actually google, and the profile text is free form and anyone can claim it. But I think it would be a good idea for you to check with your contacts at GitHub if there is a way to block this sort of activity as they are claiming affiliation with google. This sort of behavior is fairly distracting to maintainers who have tooling in place.

**Comment by inferno-chromium** [comment]
Sent an email internally to investigate.

**Comment by jonathanmetzman** [comment]
We've notified Github about this, that "[@]Google" field is a text field controlled by the user. Anyone can put anything there.
