### ISSUE TITLE
ffmpeg build failing.

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#548]
@michaelni, @Dor1s could you please take a look?

seeing (from https://oss-fuzz-build-logs.storage.googleapis.com/log-a5707363-b221-49e8-87dd-ddd5fe2bde3b.txt)

```
Step #3: + clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-coverage=trace-pc-guard,trace-cmp -fno-sanitize=vptr -I/src/ffmpeg_deps/include /src/ffmpeg/tools/target_dec_fuzzer.c -c -o /tmp/ffmpeg_AUDIO_AV_CODEC_ID_AAC_fuzzer.o -DFFMPEG_CODEC=AV_CODEC_ID_AAC -DFUZZ_FFMPEG_AUDIO=
Step #3: /src/ffmpeg/tools/target_dec_fuzzer.c:52:10: fatal error: 'libavcodec/bytestream.h' file not found
Step #3: #include "libavcodec/bytestream.h"
Step #3:          ^~~~~~~~~~~~~~~~~~~~~~~~~
Step #3: 1 error generated.
```

**Comment by michaelni** [comment]
On Mon, Apr 24, 2017 at 04:55:05PM -0700, Oliver Chang wrote:
> @michaelni, @Dor1s could you please take a look?
> 
> seeing (from https://oss-fuzz-build-logs.storage.googleapis.com/log-a5707363-b221-49e8-87dd-ddd5fe2bde3b.txt)
> 
> ```
> Step #3: + clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-coverage=trace-pc-guard,trace-cmp -fno-sanitize=vptr -I/src/ffmpeg_deps/include /src/ffmpeg/tools/target_dec_fuzzer.c -c -o /tmp/ffmpeg_AUDIO_AV_CODEC_ID_AAC_fuzzer.o -DFFMPEG_CODEC=AV_CODEC_ID_AAC -DFUZZ_FFMPEG_AUDIO=
> Step #3: /src/ffmpeg/tools/target_dec_fuzzer.c:52:10: fatal error: 'libavcodec/bytestream.h' file not found
> Step #3: #include "libavcodec/bytestream.h"
> Step #3:          ^~~~~~~~~~~~~~~~~~~~~~~~~
> Step #3: 1 error generated.
> ```

target dec fuzzer can now be built with

./configure  --disable-yasm --enable-debug --disable-stripping --enable-ossfuzz --libfuzzer=~/libfuzzer/libFuzzer.a    --cc='ccache clang' --cxx='ccache clang++'
make -j tools/target_dec_video_TIFF_fuzzer

for video and TIFF codec
for aac and audio it should be make -j tools/target_dec_audio_AAC_fuzzer

one open question is the correct path to the libfuzzer headers

I used
#include <FuzzerInterface.h>

because thats where i had installed it locally but that may not be
correct, i failed to quickly find out where/how they are installed

--
Michael     GnuPG fingerprint: 9FF2128B147EF6730BADF133611EC787040B0FAB

Awnsering whenever a program halts or runs forever is
On a turing machine, in general impossible (turings halting problem).
On any real computer, always possible as a real computer has a finite number
of states N, and will either halt in less than N cycles or never halt.

**Comment by kcc** [comment]
> one open question is the correct path to the libfuzzer headers
Do you need to include it at all?

**Comment by michaelni** [comment]
On Mon, Apr 24, 2017 at 05:31:47PM -0700, Kostya Serebryany wrote:
> > one open question is the correct path to the libfuzzer headers
> Do you need to include it at all? 

no but then we need some hack which i dont really like and iam not
sure others would.

being build via our build system the code gets the same flags
everything else gets and with them non static functions need prototypes
or build fails.


[...]
-- 
Michael     GnuPG fingerprint: 9FF2128B147EF6730BADF133611EC787040B0FAB

Dictatorship naturally arises out of democracy, and the most aggravated
form of tyranny and slavery out of the most extreme liberty. -- Plato

**Comment by kcc** [comment]
FuzzerInterface.h may not be available in our docker build environment (especially when e.g. linking against other fuzzing engines, such as AFL, that don't have FuzzerInterface.h). 

The fuzz target interface is intentionally made in a way that it doesn't require including any header (in most common case). 
If you build system requires prototypes, the simplest way is to just provide a prototype in ffmpeg's own header.

**Comment by michaelni** [comment]
On Mon, Apr 24, 2017 at 05:59:27PM -0700, Kostya Serebryany wrote:
> FuzzerInterface.h may not be available in our docker build environment (especially when e.g. linking against other fuzzing engines, such as AFL, that don't have FuzzerInterface.h). 
> 
> The fuzz target interface is intentionally made in a way that it doesn't require including any header (in most common case). 
> If you build system requires prototypes, the simplest way is to just provide a prototype in ffmpeg's own header. 

ive added the prototype to tools/target_dec_fuzzer.c

not really pretty but doesnt really matter,
I do think a public API should have an installed header

[...]

-- 
Michael     GnuPG fingerprint: 9FF2128B147EF6730BADF133611EC787040B0FAB

What does censorship reveal? It reveals fear. -- Julian Assange

**Comment by Dor1s** [comment]
Looks like now there is another issue:

```bash
+ fuzzer_name=ffmpeg_AUDIO_AV_CODEC_ID_AAC_fuzzer
+ clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-coverage=trace-pc-guard,trace-cmp -fno-sanitize=vptr -I/src/ffmpeg_deps/include /src/ffmpeg/tools/target_dec_fuzzer.c -c -o /tmp/ffmpeg_AUDIO_AV_CODEC_ID_AAC_fuzzer.o -DFFMPEG_CODEC=AV_CODEC_ID_AAC -DFUZZ_FFMPEG_AUDIO=
/src/ffmpeg/tools/target_dec_fuzzer.c:48:10: fatal error: 'config.h' file not found
#include "config.h"
         ^~~~~~~~~~
1 error generated.
fuzzers build failed.

```
