### ISSUE TITLE
Profile reader built without zlib support leading to failure to create coverage report

### ISSUE THREAD

**Issue by drott** [google/oss-fuzz#5480]
Following the steps in

https://google.github.io/oss-fuzz/advanced-topics/code-coverage/#full-project-report

for project `freetype2`, then running the coverage report generation
`$ python infra/helper.py coverage freetype2`

I get many failures such as the following:

```
[2021-03-23 10:22:43,511 INFO] Finding shared libraries for targets (if any).
[2021-03-23 10:22:43,525 INFO] Finished finding shared libraries for targets.
error: cff-render-ftengine: Failed to load coverage: No such file or directory
error: Could not load coverage information
warning: /out/dumps/type42-render.8068147597932959924_0.profraw: Profile uses zlib compression but the profile reader was built without zlib support
error: No profiles could be merged.
[2021-03-23 10:23:46,435 INFO] Finding shared libraries for targets (if any).
[2021-03-23 10:23:46,447 INFO] Finished finding shared libraries for targets.
error: type42-render: Failed to load coverage: No such file or directory
error: Could not load coverage information
warning: /out/dumps/truetype-render-i35.8072456854705739956_0.profraw: Profile uses zlib compression but the profile reader was built without zlib support
error: No profiles could be merged.
[2021-03-23 10:24:05,798 INFO] Finding shared libraries for targets (if any).
[2021-03-23 10:24:05,810 INFO] Finished finding shared libraries for targets.
error: truetype-render-i35: Failed to load coverage: No such file or directory
error: Could not load coverage information
warning: /out/dumps/truetype-render-i38.8072456854705739956_0.profraw: Profile uses zlib compression but the profile reader was built without zlib support
error: No profiles could be merged.
```

Is there something wrong with the `coverage` step of the helper script, or am I missing some command line arguments in the build steps for the project so that the profile reader would gain zlib support?

**Comment by drott** [comment]
CC @cherusker

**Comment by jonathanmetzman** [comment]
Can you try running `python infra/helper.py pull_images` first and then rebuild (`python infra/helper.py build_image freetype2 && python infra/helper.py build_fuzzers freetype2 --sanitizer coverage `). I think this is caused by a mismatch of images and binaries possibly, I don't think this happens in prod (see [this report](https://storage.googleapis.com/oss-fuzz-coverage/freetype2/reports/20210322/linux/report.html) for example), so I'm guessing you simply aren't using the most up to date images for your build and coverage run.

**Comment by drott** [comment]
Thank you very much @jonathanmetzman for the quick response. I was able to generate a report without these errors now. I did do the `build_image` and `build_fuzzers` steps, but I missed the `python infra/helper.py pull_images` step. Sorry for the noise.
