### ISSUE TITLE
Use stacktrace comparison for timeout crashes

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#552]
Right now we do not compare stacktraces for Timeout crashes.

libFuzzer uses `__sanitizer_print_stack_trace` function when reporting a timeout (https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer.git/+/master/FuzzerLoop.cpp#233)

This function is implemented in all sanitizers except of UBSan.

To enable stacktrace comparison for timeout crashes we need:
1) add `__sanitizer_print_stack_trace` to UBSan (WIP: https://reviews.llvm.org/D32542)
2) remove 'Timeout' from unique crash types on CF side

**Comment by kcc** [comment]
I afraid this may not solve the problem. 
Timeout does not necessary happen in the same place from run to run. 
So, the same root cause may produce tons of different stack traces.

**Comment by oliverchang** [comment]
I think we can be a little smarter here and compare frames that are closer to the bottom rather than using the top frames like we're doing now.

**Comment by Dor1s** [comment]
Agreed, it may require some extra logic. Compare bottom frames sounds good. For isntance, 5 timeouts in dlplibs have been closed simultaneously:
1) [1107](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1107)
2) [1250](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1250)
3) [1267](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1267)
4) [1266](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1266)
5) [1281](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1281)

First two are from ASan build. 5 bottom frames (I don't count `LLVMFuzzerTestOneInput` and libFuzzer frames) are the same. Then, there is 1 line difference in the next frame. Consequently, the top frames differ significantly.

**Comment by Dor1s** [comment]
Change on LLVM side has been landed (https://reviews.llvm.org/D32542). But we probably still cannot  enable stacktrace comparison for Timeouts on CF side until the next roll of clang in Chromium.

Anyway, it would be good for now to collect some real testcases with stacktraces from both ASan and UBSan to test existing de-duplication algorithm against them.

**Comment by Dor1s** [comment]
Bugs [1416](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1416) and [1418](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1418) are good examples of slightly different stacktraces for the same Timeout issue.

[1530](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1530) and [1601](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1601) is another group, though need to verify whether the root cause is the same. [1597](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1597) and [1599](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1599) likely are unique Timeouts in the same project, they have absolutely different stacktraces.

Looking forward to have a few more examples to test de-duplication.

**Comment by Dor1s** [comment]
Wow, this is 3+ years old! Does anyone think we need to move in this direction?

**Comment by inferno-chromium** [comment]
Can close.

**Comment by Dor1s** [comment]
Thanks for your input @inferno-chromium !
