### ISSUE TITLE
14 (out of 18) lxc bugs are "unreproducible"

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#5526]
OSS-Fuzz reported a bunch of bugs that were fixed and then instead of closing them it marked them as "flaky". As far as I can tell, the reason most of them are "flaky" is because some known revision didn't crash.

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32491
```
[2021-03-26 21:59:32 UTC] christian@*: Redo task(s): progression
[2021-03-28 14:20:06 UTC] evverx@*: Redo task(s): progression
[2021-03-28 14:26:42 UTC] oss-fuzz-linux-zone3-host-g7pw-10: Progression task started: r202103281200.
[2021-03-28 14:26:45 UTC] oss-fuzz-linux-zone3-host-g7pw-10: Progression task errored out: Known crash revision 202103261800 did not crash.
[2021-03-28 14:26:45 UTC] oss-fuzz-linux-zone3-host-g7pw-10: Progression task errored out: Testcase appears to be flaky.
```

What's interesting is that the "build" link at https://oss-fuzz.com/testcase-detail/4531441192009728 points to a build that can trigger the issue. Though judging by the link (https://storage.cloud.google.com/clusterfuzz-builds/lxc/lxc-undefined-202103251800.zip) it was produced on March 25.

cc @brauner

**Comment by evverx** [comment]
My guess would be that it has something to do with "builds_per_day: 4" (which causes ClusterFuzz to somehow mix old and new builds and report bugs that have been fixed over and over again). For example, https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32637 has just been opened and was "fixed" by pressing the "redo" button.

**Comment by brauner** [comment]
Ah yes, I observed that too.

**Comment by inferno-chromium** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32637 is a regular issue where you get a new build and it gets fixed. C#0 is known crash that does not reproduce anymore. This is target specific and nothing changed on our side that could have caused this. If you see this again, then worth reinvestigating, but flaky targets can happen, is there any state in fuzz target itself ?

**Comment by evverx** [comment]
> https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32637 is a regular issue where you get a new build and it gets fixed.

I don't think it is. At the time the bug was opened that issue had already been reported and closed. That's https://github.com/google/oss-fuzz/issues/4083 though.

> If you see this again, then worth reinvestigating

I opened this issue because I saw this 16 times. As far as I can see, all the 16 open issues are "flaky": https://bugs.chromium.org/p/oss-fuzz/issues/list?q=label%3AProj-lxc&can=2

>  is there any state in fuzz target itself ?

No, there isn't. All those issues were 100% reproducible they were fixed.

**Comment by evverx** [comment]
OSS-Fuzz seems to have gotten back to normal in the sense that new issues were opened and closed as usual. Probably it was a glitch caused by an unusually large number of bugs fixed in one fell swoop and heavy use of the "redo" button. Hopefully those 16 issues will be autoclosed on April 9-11. The "unreproducible" label is misleading though.
