### ISSUE TITLE
Deduplication for OOM crashes

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#553]
This needs some brainstorming.

I see 3 different types of OOM reports:

1) [Crash on a single malloc that exceeds the rss limit](https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer.git/+/master/FuzzerLoop.cpp#101). It relies on `__sanitizer_print_stack_trace`, so can be resolved right after #552 

2) [Crash from RssLimitCallback](https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer.git/+/master/FuzzerLoop.cpp#241) with memory profile (relies on `__sanitizer_print_memory_profile`, implemented only in ASan)

3) [Crash from RssLimitCallback](https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer.git/+/master/FuzzerLoop.cpp#241) without memory profile (for sanitizers other then ASan)

It's unclear what we can do with 2) and 3). We probably can compare memory profiles in a similar way to stacktrace comparison (since memory profile is a bunch of stacktraces), but it wouldn't cover non-ASan reports.

**Comment by kcc** [comment]
yes, 1. is easy to dedup and it's worth doing.
2. and 3 are much harder because the same OOM root cause may produce different profile

**Comment by Dor1s** [comment]
Real world proof that at least 1) would work: just noticed two OOMs in wireshark closed simultaneously:
1) [1212](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1212)
2) [1245](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1245)

Top 6 stack frames are exactly the same (I'm not counting `__interceptor_malloc` and stuff above that).
