### ISSUE TITLE
Please remove the Hugo fuzzer

### ISSUE THREAD

**Issue by bep** [google/oss-fuzz#5536]
I received a PR with a simple fuzz func on github.com/gohugoio/hugo many moons ago -- and have since been drowned with build failure mails that I have not had time to follow up on, and the original PR submitter seems to have vanished. What do I know.

I have now removed that single func from the repo above, and ask you to disable/remove the Hugo config.

I may follow up/add this myself on a later time, but that is not on my priority list right now.

Thanks.

**Comment by inferno-chromium** [comment]
@AdamKorcz - can you please remove this or see what fix is needed here.

**Comment by AdamKorcz** [comment]
@bep I will take a look at this. Would you be fine with having the build failures sorted for now to stay integrated?
