### ISSUE TITLE
Flaky timeouts when execution time is close to -timeout= threshold

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#555]
There is an example in https://github.com/google/oss-fuzz/issues/314#issuecomment-288512567

To avoid this flakiness, we can harden the threshold when doing regression/progression testing. For example, if we find timeout crash when fuzzing with `-timeout=25`, we should test it later with smaller value like `-timeout=20`.

However, parsing testcase arguments and replacing `-timeout=` value would be too hacky. We need a generic solution because similar issue may happen with other limits as well (e.g. OOM with memory usage near `-rss_limit_mb` threshold), though I haven't seen other cases so far.

**Comment by kcc** [comment]
> we should test it later with smaller value 

Yea... Probably, at least I can't see a better alternative. 
I'd say we should run with a 30 or 35 sec timeout and then reproduce with 25 (which is what we have documented). 

> However, parsing testcase arguments and replacing -timeout= value would be too hacky.

Perhaps we should simply ignore user-provided timeout and rss_limit_mb (and document it)

**Comment by Dor1s** [comment]
Another issue (sort of):

```
$ ./third_party_re2_fuzzer -timeout=25 ./clusterfuzz-testcase-XXX 
<...>./third_party_re2_fuzzer: Running 1 inputs 1 time(s) each.
Running: ./clusterfuzz-testcase-XXX
Executed ./clusterfuzz-testcase-XXX in 37955 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
```

We spent 38 seconds even though passed `-timeout-25`.

The output is slightly confusing, as there are actually 2 runs (w/o and with leak detection), even if you pass `-runs=1`. However, I don't see any way to how to make it better.
