### ISSUE TITLE
Email sender is broken

### ISSUE THREAD

**Issue by Jens-G** [google/oss-fuzz#5563]
When I try to reply to the sender mail, I get an error mail back. So I marked the sender mail as spam until fixed. If I am not allowed to send emails to you, you're not allowed to send emails to me.

**Comment by jonathanmetzman** [comment]
What emails are you talking about? The ones from monorail?
I can comment by replying to the email: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32810#c1

**Comment by Jens-G** [comment]
> Maybe you have to login once before it works?
Maybe. Nobody told me I need some account somewhere.

**Comment by Jens-G** [comment]
> We don't read those bugs (there are 1000s of them

Well ... 👍

**Comment by Jens-G** [comment]
Created another Google account (which I need like Aids) with my other mail address and am now able to login and get access. That was easy. It only cost me 30  minutes of my time and got me an unwanted Google account.

**Comment by Jens-G** [comment]
Can't beat this. Is this comedy?

Now I try to open the ticket linked in the osfuzz reports (in this case https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32797) and get asked again for login. Now I have two options. 

 * Using the existing account I get into an endless loop saying "permission denied" then reloading the page. 
 * Using the new google account it just tells me "permission denied" without the reload loop. 

What do you think: Should I create a third account? </irony>

**Comment by Jens-G** [comment]
Ah, we also need cookies. Good to know.

**Comment by inferno-chromium** [comment]
@Jens-G - sorry for your experience. let me try to explain the access controls. A project developer gets access via the email listed in project.yaml file, see line here - https://github.com/google/oss-fuzz/blob/master/projects/thrift/project.yaml#L3. We require email to be associated with the google account as of now (in near future, we will support github auth). What google account you created, can you give that email address and leave in a comment here. I will add it in project.yaml and then in 30 min you should get access. Sorry, access control are important as they prevent disclosure of security vulnerabilities until they are fixed.

**Comment by Jens-G** [comment]
Thanks for you reply. Was a funny, bumpy road but now all is working. So ticket  can be closed now I think.

Happy Easter!

**Comment by inferno-chromium** [comment]
@Jens-G - very glad all of this worked out. Happy Easter to you and your family!
