### ISSUE TITLE
qcms build errors caused by arbitrary failing to build

### ISSUE THREAD

**Issue by jrmuizel** [google/oss-fuzz#5572]
See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32816

```
Step #3: error: symbol `_RINvMNtNtCs4RZURTQcbNt_4core3ptr7mut_ptrOINtNtCslaFPCg94Pel_5alloc3vec3VecINtNtBI_5boxed3BoxDNtNtNtNtB7_4iter6traits8iterator8Iteratorp4ItemcEL_EE4castuECscjAPxvUxSWH_9arbitrary` is already defined
```

Did something change in the infrastructure that could have started causing this?

**Comment by tysmith** [comment]
Looks like other rust projects are seeing this as well: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32814

**Comment by jonathanmetzman** [comment]
CC @catenacyber 

It doesn't like our infra code had any changes lately that seem like they could be responsible: 
https://github.com/google/oss-fuzz/commits/master/infra
Maybe some rust toolchain stuff changed? (AFAIK, none of the rust projects use the normal clang toolchain, so ruling that out).

**Comment by catenacyber** [comment]
You should update libfuzzer dependency version
```
diff --git a/mp4parse_capi/fuzz/Cargo.toml b/mp4parse_capi/fuzz/Cargo.toml
index 4027f6b..a2936ac 100644
--- a/mp4parse_capi/fuzz/Cargo.toml
+++ b/mp4parse_capi/fuzz/Cargo.toml
@@ -9,7 +9,7 @@ edition = "2018"
 cargo-fuzz = true
 
 [dependencies]
-libfuzzer-sys = "=0.3.2"
+libfuzzer-sys = "=0.4.0"
```

This new version works with `RUSTFLAGS=-Zinstrument-coverage`

**Comment by jrmuizel** [comment]
Ok, I landed: https://bugzilla.mozilla.org/show_bug.cgi?id=1703101

**Comment by catenacyber** [comment]
Thanks, let me know if there is still a problem after that

**Comment by jrmuizel** [comment]
This is fixed.
