### ISSUE TITLE
Make important information more prominent in issues description

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#56]
(I'm looking at https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=72)

The fields there are too ClusterFuzz specific. They should be:

Target: libchewing
Fuzzer: chewing_fuzzer
Sanitizer: asan

**Comment by oliverchang** [comment]
Hmm, we can definitely do this, but I'm worried that this will create confusion when developers need to interact with ClusterFuzz (where they will need to specify the exact fuzzer, job names for things like stats, crashes).

**Comment by mikea** [comment]
Ideally those should be consistent as well.

**Comment by mikea** [comment]
Another option would be to use some creative terminology. E.g:

Fuzzer: libfuzzer_expat_parse_fuzzer
Binary: parse_fuzzer

Target shouldn't conflict with anything.

**Comment by oliverchang** [comment]
That should work.

**Comment by oliverchang** [comment]
Done. See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=136 for an example.

**Comment by oliverchang** [comment]
(Reopen this if you'd like the things displayed to be changed/reordered).
