### ISSUE TITLE
about timezone

### ISSUE THREAD

**Issue by asarubbo** [google/oss-fuzz#563]
On each ticket created by clusterfuzz, if there will be a fix, it prints the range when it was fixed. However I'm not sure which timezone Clusterfuzz considers. Thanks.

**Comment by inferno-chromium** [comment]
I think its UTC, but will let @oliverchang confirm

**Comment by oliverchang** [comment]
yeah, it should be UTC. 

Note that if you click on the link after the "Fixed: " in the comment it should take you to a page that displays the actual revision control hashes.
