### ISSUE TITLE
specifying fuzz-seconds in .github/workflows/main.yml has no effect

### ISSUE THREAD

**Issue by hughsie** [google/oss-fuzz#5650]
Some time in the two weeks or so specifying fuzz-seconds has stopped working and the fwupd fuzzers run for hours and hours until manually killed. We've had to add `timeout-minutes: 20` to avoid burning through all our allocated CI time for the month.

We've even tried

    -    fuzz-seconds: 300
    +    fuzz-time: 300

out of desperation but that doesn't seem to work either. See https://github.com/fwupd/fwupd/pull/3172 for an example.

**Comment by jonathanmetzman** [comment]
Sorry about this.
I have a fix: https://github.com/google/oss-fuzz/pull/5651/files

**Comment by hughsie** [comment]
Many thanks! Confirmed fixed for me.

**Comment by jonathanmetzman** [comment]
Related: https://github.com/google/oss-fuzz/issues/5623
