### ISSUE TITLE
www.oss-fuzz.com:443 closes connection

### ISSUE THREAD

**Issue by Lekensteyn** [google/oss-fuzz#566]
Expected result:
https://www.oss-fuzz.com/ should redirect to https://oss-fuzz.com/

Actual result:
https://www.oss-fuzz.com/ and http://www.oss-fuzz.com:443/ are closed (TCP FIN) without receiving any reply.

Additional info (main domain, www subdomain and an arbitrary non-existing domain):
```
$ host oss-fuzz.com
oss-fuzz.com has address 216.239.32.21
oss-fuzz.com has address 216.239.34.21
oss-fuzz.com has address 216.239.38.21
oss-fuzz.com has address 216.239.36.21
oss-fuzz.com has IPv6 address 2001:4860:4802:32::15
oss-fuzz.com has IPv6 address 2001:4860:4802:34::15
oss-fuzz.com has IPv6 address 2001:4860:4802:36::15
oss-fuzz.com has IPv6 address 2001:4860:4802:38::15
$ host www..oss-fuzz.com
www.oss-fuzz.com is an alias for ghs.googlehosted.com.
ghs.googlehosted.com has address 172.217.17.51
ghs.googlehosted.com has IPv6 address 2a00:1450:400e:804::2013
$ host xefe.oss-fuzz.com
Host xefe.oss-fuzz.com not found: 3(NXDOMAIN)
```

**Comment by oliverchang** [comment]
Unfortunately setting this up is probably more effort than it's worth.

Are we incorrectly linking to www.oss-fuzz.com somewhere?

**Comment by Lekensteyn** [comment]
I didn't find links to www., just noticed it because "oss-fuzz" + Ctrl-Enter in Firefox completes it to www.oss-fuzz.com

**Comment by oliverchang** [comment]
Closing as WAI.
