### ISSUE TITLE
make ffmpeg seed corpora smaller and re-enable them 

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#567]
Currently, the ffmpeg corpora are too big (>11Gb) which, combined with 9.6Gb of binaries 
does not fit into ClusterFuzz constraints. 

(more details coming)

**Comment by kcc** [comment]
@michaelni 
I had to temporary disable the seed corpora for ffmpeg. 
The total size of the binaries alone is now 9.6Gb, which is close the ClustFuzz's limit.
The corpora add 11Gb more, which simply doesn't fit :( 
(The build-time limit is 70Gb, so we are good here, but we can't ship 20Gb to the workers). 

Some ideas of what can be done (either on ffmpeg side, or oss-fuzz or both). Comment are welcome!

* [ffmpeg/oss-fuzz] split the ffmpeg project on oss-fuzz into several. I'd try to avoid this if at all possible.
* [ffmpeg] maintain much smaller corpora (smaller files, minimized for coverage).
* [oss-fuzz] when a project is built, don't zip it as a single package, but instead create N smaller packages, 1 per target. Oliver, WDYT? 
* [oss-fuzz/ffmpeg] ship the seed corpora to oss-fuzz somehow else. Michael, are these samples set in stone, or the set evolves over time? 
* anything else?

**Comment by oliverchang** [comment]
With the corpora we're looking at 14GB (zip) + 20GB (unzip) == 34GB disk used for ffmpeg alone. 

> [ffmpeg/oss-fuzz] split the ffmpeg project on oss-fuzz into several. I'd try to avoid this if at all possible.
Agreed.

> [oss-fuzz] when a project is built, don't zip it as a single package, but instead create N smaller packages, 1 per target. Oliver, WDYT?
Maybe, this will be a little complicated to implement on ClusterFuzz because of various assumptions that we've made. Figuring out the right dependencies for each target might be a little difficult too.

However, we could upload seed corpora themselves separately and only download them when we need to.

> [oss-fuzz/ffmpeg] ship the seed corpora to oss-fuzz somehow else. Michael, are these samples set in stone, or the set evolves over time?

Another option that works today is to use static GCS corpora (I don't think this is documented yet). Corpora can be manually uploaded to cloud storage with "_static" suffixes to the same corpus bucket (gs://ffmpeg-corpus.clusterfuzz-external.appspot.com). This has the advantage of not repeatedly uploading the same files if the samples don't change often and are large.

**Comment by oliverchang** [comment]
> Another option that works today is to use static GCS corpora (I don't think this is documented yet). Corpora can be manually uploaded to cloud storage with "_static" suffixes to the same corpus bucket (gs://ffmpeg-corpus.clusterfuzz-external.appspot.com). This has the advantage of not repeatedly uploading the same files if the samples don't change often and are large.

We could also potentially do this ourselves at build time -- look for _seed_corpus.zip files and upload them to the static bucket, and not include them in the final zip.

**Comment by michaelni** [comment]
> I had to temporary disable the seed corpora for ffmpeg.
The total size of the binaries alone is now 9.6Gb, which is close the ClustFuzz's limit.
The corpora add 11Gb more, which simply doesn't fit :(
(The build-time limit is 70Gb, so we are good here, but we can't ship 20Gb to the workers).
Some ideas of what can be done (either on ffmpeg side, or oss-fuzz or both). Comment are welcome!

>  [ffmpeg] maintain much smaller corpora (smaller files, minimized for coverage).
    [oss-fuzz/ffmpeg] ship the seed corpora to oss-fuzz somehow else. Michael, are these samples set in stone, or the set evolves over time?

We have the fate samples archive and the full samples archive. fate samples are 1gb the full one is over 110gb. Both are likely to grow slowly with time.
i think ossfuzz uses the 1gb set. I dont see why it would ever need more than 1gb of space or why it is re downloaded via rsync from scratch each time.
symlinks may be an option to avoid turning 1gb into 11gb

In the end i think the space limit, restrictions on build (many separate static fuzzer tools), time spend on making things fit and coverage of the fuzzer are together constraint.

**Comment by Dor1s** [comment]
Question from the email thread by @michaelni :

> Is there a list / table of what is duplicated to which targets ?
> 
> from an naive POV 10x duplication seems odd. A file may have 2 or 3
> streams with different codecs so a 3x duplication would be the worst
> i would expect.
> 

I think you can download the build from April 29th (https://storage.cloud.google.com/clusterfuzz-builds/ffmpeg/ffmpeg-address-201704291626.zip?_ga=2.106562883.-192946872.1496676137), it's one of the last successful builds we had before removing the corpus.

Another way is to revert https://github.com/google/oss-fuzz/commit/ed23c7a0c9722fc6bf4243b820baa6c6a700b16e and build fuzzers locally

**Comment by michaelni** [comment]
> I think you can download the build from April 29th (https://storage.cloud.google.com/clusterfuzz-builds/ffmpeg/ffmpeg-address-201704291626.zip?_ga=2.106562883.-192946872.1496676137), it's one of the last successful builds we had before removing the corpus.

All the  *seed_corpus.zip in this file still only add up to 1.2G

**Comment by michaelni** [comment]
rebuilding with the commit reverted leads to 13gb corpus, 5gb of this is duplicated *_PCM_* content.
If i look at for example ffmpeg_AV_CODEC_ID_H263I_fuzzer_seed_corpus.zip its full of h264 conformance files. why ? 360mb in CUVID specific corpus files, (CUVID is GPU stuff, do the systems this runs on even have the hw for this? ffmpeg_AV_CODEC_ID_DOLBY_E_fuzzer_seed_corpus.zip contains 1gb of samples, are these all samples? why ? ffmpeg_AV_CODEC_ID_ADPCM_SBPRO_4_fuzzer_seed_corpus.zip contains 500mb of seemingly random samples, ...

**Comment by Dor1s** [comment]
The script (relevant_corpus_files) is pretty dumb and certainly archives redundant stuff in some cases.

For example, instead of:

```python
    relevant_corpus_files = set()
    for filename in corpus_files:
      # Remove 'ffmpeg' substring to do not use everything for 'MPEG' codec.
      sanitized_filename = filename.replace('ffmpeg', '').lower()
      for tag in fuzzer_tags:
        if tag in sanitized_filename:
          relevant_corpus_files.add(filename)

      if not relevant_corpus_files:
        # Strip last symbol from tags if we haven't found relevant corpus.
        # It helps for such codecs as 'RV40' ('RV4' -> 'RV') or 'PCX' (-> 'PC').
        for tag in fuzzer_tags:
          if tag[:-1] in sanitized_filename:
            relevant_corpus_files.add(filename)
```

we should probably be doing something like:

```python
    relevant_corpus_files = set()
    for filename in corpus_files:
      # Remove 'ffmpeg' substring to do not use everything for 'MPEG' codec.
      sanitized_filename = filename.replace('ffmpeg', '').lower()
      for tag in fuzzer_tags:
        if tag in sanitized_filename:
          relevant_corpus_files.add(filename)

+   # Move the following code outside of the "for" loop above.
    if not relevant_corpus_files:
+      # Loop through all corpus_files once again.
+      for filename in corpus_files:
+      # Remove 'ffmpeg' substring to do not use everything for 'MPEG' codec.
        sanitized_filename = filename.replace('ffmpeg', '').lower()
        # Strip last symbol from tags if we haven't found relevant corpus.
        # It helps for such codecs as 'RV40' ('RV4' -> 'RV') or 'PCX' (-> 'PC').
        for tag in fuzzer_tags:
          if tag[:-1] in sanitized_filename:
            relevant_corpus_files.add(filename)
```

It would be awesome if we replace it with another solution providing more granular and more accurate grouping.

**Comment by michaelni** [comment]
You should be able to identify most codecs per sample using something like:
```
for i in fate-suite/*/* ; do ./ffprobe  -show_streams -v 0 $i | grep codec_name  ; done
```
