### ISSUE TITLE
ffmpeg ubsan builds shouldn't run ASAN

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#568]
see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1348,

How is ASAN getting linked in UBSAN builds, @michaelni - any idea what could have caused this.

**Comment by michaelni** [comment]
In configure there is
```
enabled ossfuzz && {
    add_cflags  -fsanitize=address,undefined -fsanitize-coverage=trace-pc-guard,trace-cmp -fno-omit-frame-pointer
    add_ldflags -fsanitize=address,undefined -fsanitize-coverage=trace-pc-guard,trace-cmp
}
```
This should probably be skiped if sanitizer flags are set by some other way, i didnt realize ubsan and asan builds were seperate

**Comment by inferno-chromium** [comment]
--libfuzzer=-lFuzzingEngine should be sufficient. you shouldn't be passing custom cflags or ldflags for coverage and sanitizer.

@kcc @oliverchang - fyi

**Comment by oliverchang** [comment]
we provide CFLAGS/CXXFLAGS that should be used when compiling and linking.

**Comment by inferno-chromium** [comment]
Verified that --enable-ossfuzz is not needed, configure script will directly use CFLAGS/CXXFLAGS.

**Comment by michaelni** [comment]
This causes new ubsan - crash bugs to be closed as fixed, i dont think this is ideal

**Comment by inferno-chromium** [comment]
It will only close those ones that ASAN has like heap-buffer-overflow. UBSAN bugs should still come through, e.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1395 was filed today. Can you confirm if some ubsan bugs are closed incorrectly ? Any idea why, configure script should be using CFLAGS from environment. I verified with running some ubsan reports after my change and they were crashing fine.

**Comment by michaelni** [comment]
> It will only close those ones that ASAN has like heap-buffer-overflow.

Yes, it will close these and IIUC then soon publish the testcases for everyone to see while for us it will disappear of our "radar" of open issues we need to fix. This does not seem to be the ideal combination. The issues should be opened to the public after they are really fixed or after the X month timeout, not because the system thinks they where fixed due to a config change.

**Comment by inferno-chromium** [comment]
So, we don't open the bugs until 30 days. Config changes are usually rare, so sorry for inconvenience caused here. I hope you can fix these in < 30 days, otherwise we will have to do manual work to keep these restricted. For an automated system, it is hard to know difference between config change or actual fix. Build system is detached from ClusterFuzz bots that do the fuzzing.
