### ISSUE TITLE
recognize div-by-zero as such, instead of Crash Type: UNKNOWN

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#569]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1374
Crash Type: UNKNOWN
Crash Address: 

But the error report is: 
...c:1245:49: runtime error: division by zero

**Comment by inferno-chromium** [comment]
Max, can you add some signatures for these generic UBSAN types to UBSAN_CRASH_TYPES_MAP ?

**Comment by inferno-chromium** [comment]
I think we added everything security related, but need to add for the functional ones.

**Comment by Dor1s** [comment]
Sure, will do.

**Comment by Dor1s** [comment]
Btw, how did we get that report? I don't see that we are using any of division-by-zero flags: https://github.com/google/oss-fuzz/blob/60835ac4207d5877f119129a2a1e8639ee4b92a3/infra/base-images/base-builder/Dockerfile#L23

**Comment by Dor1s** [comment]
If I understood correctly, `-fno-sanitize-recover=undefined` enables all [UBSan checks ](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#usage) (except of  `unsigned-integer-overflow` and `nullability-*`) and crashes the program when an error happens.

Not sure if this is intended, as `-fsanitize=` flag doesn't make sense right now. `-fno-sanitize-recover` has been added a while ago (https://github.com/google/oss-fuzz/pull/102). I think we should remove one of these two options. @inferno-chromium @kcc what do you think?

**Comment by Dor1s** [comment]
Aha, I understood it wrong. `-fno-sanitize-recover=` does not enable additional checks, it just controls which types of errors should terminate the program. So, `-fno-sanitize-recover=undefined` terminates the program for all errors declared in `-fsanitize=` flag.

My PR doesn't make sense. And the question "How could we get a `division by zero` report?" is opened again.

**Comment by Dor1s** [comment]
I've also added the following signatures:
* `bool`, e.g. https://oss-fuzz.com/v2/testcase-detail/6421901003980800
* `alignment`, e.g. https://oss-fuzz.com/v2/testcase-detail/5958052211589120
* `null`, e.g. https://bugs.chromium.org/p/chromium/issues/detail?id=616870

**Comment by oliverchang** [comment]
To answer "How could we get a division by zero report?" this is probably because of https://github.com/google/oss-fuzz/issues/568 (ffmpeg was overriding our flags).

**Comment by Dor1s** [comment]
You're right, Oliver! Thanks!
