### ISSUE TITLE
base-builder is based on Ubuntu Xenial, which is EOL

### ISSUE THREAD

**Issue by MarcoFalke** [google/oss-fuzz#5697]
It seems that the base-builder is based on an operating system that is EOL. The instructions say that the required packages may be installed from the base-builder package manager (see https://google.github.io/oss-fuzz/getting-started/new-project-guide/#dockerfile). However, as the operating system is EOL, the package versions are often no longer supported by the project. Also, they might contain unfixed bugs that will result in false positives. Finally, it looks like this results in hacky workarounds that might break other things. (Example: https://github.com/google/oss-fuzz/blob/30f3a8f1c0f5b072e77d5bea82709db04c53453d/projects/libreoffice/Dockerfile#L24)

Even if the base-runner is based on Xenial, it might be good to offer alternative base-builders on Focal or Bionic that can do the static builds.

**Comment by inferno-chromium** [comment]
Yes we do plan to move to 18.04 or 20.04 soonish, in next month or two. really sorry that this has taken so long.

**Comment by inferno-chromium** [comment]
@asraa - as you are thinking of breaking base-builder at some time in Q2, maybe we do this at same time as well ?

**Comment by MarcoFalke** [comment]
Presumed duplicate of #6180
