### ISSUE TITLE
grpc build broken again

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#571]
Please see https://oss-fuzz-build-logs.storage.googleapis.com/log-16ee6691-3822-4039-b80b-3829bb8e9cc4.txt

```
Step #3: ERROR: /src/grpc/BUILD:445:1: C++ compilation of rule '//:grpc_base' failed: clang failed: error executing command /usr/local/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/local/bin -B/usr/bin -fcolor-diagnostics -fno-omit-frame-pointer -O1 -fno-omit-frame-pointer -gline-tables-only ... (remaining 42 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Step #3: error: invalid argument '-std=c99' not allowed with 'C++'
```

@matt-kwong it seems that the gRPC build breaks very often. Is there something we can do here to make this happen less often? Thanks!

**Comment by matt-kwong** [comment]
Sorry for the late response. We actually have a test in place for Bazel building, but because we use a different Dockerimage, our tests were passing. I believe this was because our Dockerimage uses Clang 3.8 and that throws a warning, instead of an error, for 
```
Step #3: ERROR: /src/grpc/BUILD:445:1: C++ compilation of rule '//:grpc_base' failed: clang failed: error executing command /usr/local/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/local/bin -B/usr/bin -fcolor-diagnostics -fno-omit-frame-pointer -O1 -fno-omit-frame-pointer -gline-tables-only ... (remaining 42 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Step #3: error: invalid argument '-std=c99' not allowed with 'C++'
```
I am going to add oss-fuzz's base Dockerimage for gRPC testing, so hopefully the frequency of gRPC breakges decrease. There is an open PR to fix gRPC that should be merged soon.

**Comment by inferno-chromium** [comment]
Build is broken again. @matt-kwong - please help to fix.

https://oss-fuzz-build-logs.storage.googleapis.com/log-0a6caa99-d32b-4bf8-9bf5-c4e646f1c3c1.txt
@submodule_cares//:all
Step #3: Extracting Bazel installation...
Step #3: ........
Step #3: ERROR: no such package '@submodule_boringssl//': error loading package 'external': The repository named 'submodule_boringssl' could not be resolved.
Step #3: ERROR: no such package '@submodule_boringssl//': error loading package 'external': The repository named 'submodule_boringssl' could not be resolved.
Step #3: ____Elapsed time: 2.588s
Finished Step #3
ERROR
ERROR: build step "gcr.io/oss-fuzz/grpc" failed: exit status 1
