### ISSUE TITLE
oss-fuzz doesn't find known issues

### ISSUE THREAD

**Issue by MarcoFalke** [google/oss-fuzz#5713]
The recently added `bitcoin-core` integration didn't trigger an expected (intentionally unfixed) bug. We wanted to see if the infrastructure works by issuing a known true positive.

The bug exercises UB, which is "optimized away" by all modern compilers. The only known way to detect it is by code review or with the options `-D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC`. (See https://github.com/bitcoin/bitcoin/pull/21802)

The needed options are indeed passed through to our build system. See https://github.com/google/oss-fuzz/pull/5709/checks?check_run_id=2501143068#step:8:2034 (and https://oss-fuzz-build-logs.storage.googleapis.com/log-d87af0ae-391c-4fa5-8e03-38d15c2fa4b7.txt):

```
...
   CC              = clang
  CFLAGS          = -pthread -pipe -O1 -m32 -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link
  CPPFLAGS        =  -DABORT_ON_FAILED_ASSUME  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -I/src/bitcoin-core/depends/i686-pc-linux-gnu/include/  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64
  CXX             = clang++ -std=c++17
  CXXFLAGS        =   -Wstack-protector -fstack-protector-all -fcf-protection=full -fstack-clash-protection     -pipe -O1 -m32 -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++
  LDFLAGS         = -lpthread  -Wl,-z,relro -Wl,-z,now -pie  -L/src/bitcoin-core/depends/i686-pc-linux-gnu/lib 
  ARFLAGS         = cr
...
```

The issue can then be found with the existing fuzz inputs.zip or by running the fuzz engine for a few seconds. However, no issues are reported on https://oss-fuzz.com/testcases?project=bitcoin-core&open=yes

**Comment by asraa** [comment]
Thanks for the report! Would like to figure out why. It's strange because fuzzers are run a few iterations to check the build, and the issue is in the existing corpus already.

It would be good to know if there is some difference in the environment (e.g. maybe a UBSan option). Could you try reproducing in OSS-Fuzz's environment by running against the triggering testcase? https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-bugs

**Comment by guidovranken** [comment]
@MarcoFalke 

-D_GLIBCXX_DEBUG has no effect on OSS-Fuzz because OSS-Fuzz uses the LLVM libc, but the compile flag only has effect on GNU libc.

When using the LLVM libc (e.g. on OSS-Fuzz), set -D_LIBCPP_DEBUG to 0 or 1 (1 implies more checks than 0).

**Comment by MarcoFalke** [comment]
Looks like this is an upstream clang "bug". According to https://libcxx.llvm.org/docs/DesignDocs/DebugMode.html#iterator-debugging-checks:

> The following containers and STL classes support iterator debugging: ... `std::vector<T> (T != bool)` ...


However, the issue present here is with a `std::vector<bool>`.
