### ISSUE TITLE
Unable to obtain libfuzzer coverage report

### ISSUE THREAD

**Issue by clvang000** [google/oss-fuzz#576]
Hello,

I'm fuzzing some projects locally for a study project, and I have a question about how to track fuzzer coverage with libFuzzer. 
I found that in order to produce the coverage report via <oss-fuzz/infra/base-images/base-builder/coverage_report.sh>, there are .sancov files required. I can't seem to produce these .sancov files. 
What I am interested in is to obtain the coverage report associated with an existing corpus and fuzzer (to get the total percentage of code coverage).

I have tried the following:
For example, when in the /out/ folder inside the Docker container, of a fully compiled project for libFuzzer. I've tried running several commands to obtain the .sancov files:

$ ASAN_OPTIONS=coverage=1 ./fuzzer corpus_dir -runs=0
$ ASAN_OPTIONS=coverage=1 ./fuzzer corpus_dir
(http://llvm.org/docs/LibFuzzer.html#how-good-is-my-fuzzer)

(and without corpus parameter)
$ ASAN_OPTIONS=coverage=1 ./fuzzer

Neither of these commands seem to produce the .sancov files. 

When the -runs=0 parameter is also given, some error message about the LeakSanitizer occurs:
==26==LeakSanitizer has encountered a fatal error.
==26==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==26==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
MS: 0 ; base unit: 0000000000000000000000000000000000000000

Without the -runs=0 parameters, the fuzzer just seems to start running as it usually does, but without generating the .sancov file.

I hope you are able to help me with this issue.
Thank you.

**Comment by kcc** [comment]
a few months ago we switched libFuzzer to handling it's own coverage,
so ASAN_OPTIONS won't trigger .sancov generation any more. 
Try libFuzzer's flag `-dump_coverage=1` (and thanks for the reminder, I need to update the docs at libfuzzer.info). 

```
HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
```
Weird. Is this inside Docker? 
How do you run it? 
Typically, docker needs `--cap-add SYS_PTRACE` to work well with lsan 

(Closing this issue now, but feel free to post updates)

**Comment by oliverchang** [comment]
You can also try using our helper script:

See: `python infra/helper.py coverage -h`

**Comment by oliverchang** [comment]
(helper script also adds --cap-add SYS_PTRACE to prevent lsan issues)

**Comment by clvang000** [comment]
Thank you. Both issues are resolved!


I've got another question, about the libFuzzer coverage report. 
It shows the coverage for the individual files. However, I would like to obtain an overall metric which indicates the overall coverage that a certain corpus has achieved (I was hoping this would show in the coverage report). 

For example, when libFuzzer is running, you will see the 'cov: ' depicted, but I do not see how many basic blocks there are in total, and would like to calculate the overall percentage of coverage .

Is there a way to obtain this metric with libFuzzer? I believe this is similar to the map density metric in AFL; where the map density refers to: "how many branch tuples we have already hit, in proportion to how much the bitmap can hold, for the entire input corpus" (http://lcamtuf.coredump.cx/afl/status_screen.txt). 

I mean this question besides actually saving the generated corpus by libFuzzer, and then using this an input corpus to initialize AFL with, and checking the map density at that point. 

Best regards.

**Comment by kcc** [comment]
When you start a libFuzzer binary it prints something like 
```
INFO: Loaded 1 modules (13 guards):
```
The number of "guards" is the number of instrumented basic blocks, i.e. what you are looking for.
But remember that often it's a number you can't achieve by fuzzing (e.g. if there is unreachable code, etc). 
So, it's a theoretical maximum for `cov:`
