### ISSUE TITLE
How to debug afl++ "build issue" (timeout in check_build)

### ISSUE THREAD

**Issue by MarcoFalke** [google/oss-fuzz#5761]
There is a build failure reported in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34157 for `bitcoin-core`. Interestingly, afl with `undefined` sanitize `check_build`s just fine. Only `address` times out. Locally (with our own build system) we don't see the timeout. Though, with `python infra/helper.py check_build  --sanitizer address  --engine afl $PROJECT_NAME` I can reproduce. However, as soon as I try to reproduce the same command in the shell, it passes.

In `python infra/helper.py shell $PROJECT_NAME` this passes:

`AFL_DRIVER_DONT_DEFER=1 AFL_SKIP_CPUFREQ=1 AFL_NO_AFFINITY=1 AFL_FAST_CAL=1 AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1 AFL_FUZZER_ARGS="-m none -l 2 -c /tmp/not-out/process_message_pong -x /tmp/not-out/afl++.dict -t 5000+" AFL_NO_UI=1 AFL_ENABLE_DICTIONARY=1 AFL_QUIET=1 AFL_LLVM_MODE_WORKAROUND=0 AFL_LLVM_CMPLOG=1               afl-fuzz -m none -l 2 -c /out/process_message_pong  -t 5000+ -i /tmp/process_message_pong_corpus -o /tmp/process_message_pong_afl_address_out   -- /out/process_message_ping`

**Comment by inferno-chromium** [comment]
@vanhauser-thc - thoughts?

**Comment by MarcoFalke** [comment]
Meta issue: #5452

**Comment by vanhauser-thc** [comment]
It would help to know where it is hanging. before the forkserver or after the forkserver? what is the error message afl-fuzz displays?

Two ideas:
1. modify do Dockerfile to add gdb (which adds gcore), increase the timeout to 30000+, run the check_build command, docker exec -ti into the containter and gcore the target binary to see where it is hanging
2. find out what the difference between check_build env + command line parameters are and then see what env or cmdline parameter is the issue.

IMHO the culprit could be AFL_DRIVER_DONT_DEFER=1 - this will run LLVMInitialize() for every new fork. It should only be used for debugging issues in a fuzzing harness.

**Comment by MarcoFalke** [comment]
Thanks for the hints, this will be fixed by #5784 (if merged as-is). If not, I am going to try your suggestions.
