### ISSUE TITLE
Coverage build failure due to missing coverage for `library/std/src/thread/local.rs`

### ISSUE THREAD

**Issue by rbehjati** [google/oss-fuzz#5767]
Generating coverage report for project Oak fails with the following error: 
```
error: /out/rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/std/src/thread/local.rs: No such file or directory
warning: The file '/rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/std/src/thread/local.rs' isn't covered.
[2021-05-14 13:18:47,173 DEBUG] Finished generating per-file code coverage summary.
[2021-05-14 13:18:47,173 DEBUG] Generating file view html index file as: "/out/report/linux/file_view_index.html".
Traceback (most recent call last):
  File "/opt/code_coverage/coverage_utils.py", line 829, in <module>
    sys.exit(Main())
  File "/opt/code_coverage/coverage_utils.py", line 823, in Main
    return _CmdPostProcess(args)
  File "/opt/code_coverage/coverage_utils.py", line 780, in _CmdPostProcess
    processor.PrepareHtmlReport()
  File "/opt/code_coverage/coverage_utils.py", line 578, in PrepareHtmlReport
    self.file_view_path)
  File "/opt/code_coverage/coverage_utils.py", line 450, in GenerateFileViewHtmlIndexFile
    self.GetCoverageHtmlReportPathForFile(file_path),
  File "/opt/code_coverage/coverage_utils.py", line 423, in GetCoverageHtmlReportPathForFile
    self._MapToLocal(file_path)), '"%s" is not a file.' % file_path
AssertionError: "/rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/std/src/thread/local.rs" is not a file.
```
The failure report: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34292
The logs: https://oss-fuzz-build-logs.storage.googleapis.com/log-b5a8362e-201e-47a5-9e19-43b3aa2ab914.txt

I was able to reproduce this locally by running
```
python infra/helper.py build_image oak
python infra/helper.py build_fuzzers --sanitizer coverage oak
python infra/helper.py coverage oak
```

Is it possible to get more details about this error? Is it an error from `llvm-cov`? 
Also, is it possible to disable coverage report generation for project Oak?

**Comment by DavidKorczynski** [comment]
Could you try bumping the libfuzzer-sys version in your crate? 
See here for an example of a fix for, what I believe, to be a similar issue https://github.com/rust-lang/regex/commit/6cdb9040f55aba067e2b3eeb5ea3045051681780

**Comment by DavidKorczynski** [comment]
Note that I checked the fix of bumping the libfuzzer crate and it does not fix the issue.

**Comment by catenacyber** [comment]
Getting the same error on Suricata and ecc-diff-fuzzer

I bet this is due to some change in rustc 2021-05-12 or 2021-05-11 to somehow include the standard library in the coverage 

The file is in fact located in /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs

And 6d395a1c2946c79966490f5b1e6e619d3a713e6b is the commit-hash version of rustc cf `rustc --version --verbose`

I propose as a fix https://github.com/google/oss-fuzz/pull/5776

**Comment by rbehjati** [comment]
Thanks for the help, and the explanations. 
Even with the change in #5776, I am getting the same error when testing locally.

**Comment by catenacyber** [comment]
Did you rebuild the base-builder ?

**Comment by rbehjati** [comment]
I ran `python infra/helper.py build_image oak` that pulls the latest `base-builder` image . I also ran `python infra/helper.py pull_images`. Is rebuilding the base-builder something different?

**Comment by catenacyber** [comment]
Thank you @rbehjati 
This was indeed incomplete. #5791 should get it right

**Comment by rbehjati** [comment]
Yes. I can run coverage locally without a problem now. Thanks.
