### ISSUE TITLE
False positive case of "verified as fixed"

### ISSUE THREAD

**Issue by hartwork** [google/oss-fuzz#5774]
Hi!

There was one case where a bug [was closed "verified as fixed" before it was fixed in Git](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=29442#c4). It is fixed in Git master by now but it was not back then. I did ["document" it](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=29442#c6) but I should have reported here right away.

Let me take the occasion to thank you for making, maintaining, and operating the OSS-Fuzz — it uncovers real bugs and that's awesome in my book.

Best, Sebastian

**Comment by inferno-chromium** [comment]
Timeouts and OOM bugs can be inherently flaky, you can try clicking Redo task->Fixed (on testcase) to sometimes double-check if bug is actually fixed. There is nothing much we can do here, if another timeout bug appears, a new bug gets opened after 2 days.

**Comment by hartwork** [comment]
I'm not sure I understand how they can be flaky in terms of a false "fixed" positive. Could you elaborate?

**Comment by inferno-chromium** [comment]
> I'm not sure I understand how they can be flaky in terms of a false "fixed" positive. Could you elaborate?

timeout can be flaky, if it timeout happens near the limit, (25 sec_. so in some builds, if it finishes >25 sec, then timeout happens, if it happens in <25sec, then no crash/timeout stack is generated.

**Comment by hartwork** [comment]
Okay, thanks!
