### ISSUE TITLE
GnuTLS does not work with MSAN, crashes on startup

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#578]
https://oss-fuzz.com/v2/testcase-detail/6639532524961792

GnuTLS seems to crash on startup on some asm library. Since MSAN can't instrument ASM code, it is advisable to use non-ASM mode for MSAN fuzzing (if such mode is available).

@nmav @alex - thoughts.

**Comment by kcc** [comment]
Right... If you build the fuzz targets with msan (https://clang.llvm.org/docs/MemorySanitizer.html)
they would crash like this: 

```
% python infra/helper.py build_fuzzers --sanitizer memory  gnutls 
% python infra/helper.py shell gnutls 
$ /out/gnutls_x509_parser_fuzzer 
Uninitialized bytes in __interceptor_memcmp at offset 0 inside [0x7ffd35080e1c, 4)
==16==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x6a8312 in check_intel_or_amd /src/gnutls/lib/accelerated/x86/x86-common.c:467:7
    #1 0x6a29da in register_x86_intel_crypto /src/gnutls/lib/accelerated/x86/x86-common.c:484:6
    #2 0x6a2916 in register_x86_crypto /src/gnutls/lib/accelerated/x86/x86-common.c:741:2
    #3 0x589ed3 in _gnutls_global_init /src/gnutls/lib/global.c:367:2
```

I suspect that if you disable assembly code (if that's possible), msan will work.

**Comment by alex** [comment]
I think msan will still be a challenge, since we use one or two libraries which are installed from `apt`. However... a quick grep of the code didn't turn up an obvious way to disable it, hopefully @nmav can say for sure.

**Comment by nmav** [comment]
There is a flag ```--disable-hardware-acceleration``` which disables all assembly optimizations.
