### ISSUE TITLE
Can corpora ZIPs be made public?

### ISSUE THREAD

**Issue by MarcoFalke** [google/oss-fuzz#5780]
Our inputs are fully public at https://github.com/bitcoin-core/qa-assets. I presume that OSS-Fuzz removes crashing inputs from the ZIPs, so is there any reason they can't be public as well? Maybe on a per-project basis, if there are concerns?

Unrelated, I was wondering if the corpus for a fuzz target is shared between all fuzz engines? If yes, it should be sufficient to download the ZIP of a single fuzz engine?

Finally, is it possible to download the latest backup ZIP for *all* fuzz targets with a single click in the Browser or a bash one-liner?

**Comment by inferno-chromium** [comment]
> Our inputs are fully public at https://github.com/bitcoin-core/qa-assets. I presume that OSS-Fuzz removes crashing inputs from the ZIPs, so is there any reason they can't be public as well? Maybe on a per-project basis, if there are concerns?

30-day old corpus is already made public automatically - https://github.com/google/clusterfuzz/blob/master/src/appengine/handlers/cron/corpus_backup.py#L47
does that suffice, or you want explicit feature. we might not have cycles to do this in Q2, can try early q3.

> 
> Unrelated, I was wondering if the corpus for a fuzz target is shared between all fuzz engines? If yes, it should be sufficient to download the ZIP of a single fuzz engine?

Yes it is already done automatically. you will only see one corpus in libfuzzer fuzzing engine, but it is shared with honggfuzz, afl.

> 
> Finally, is it possible to download the latest backup ZIP for _all_ fuzz targets with a single click in the Browser or a bash one-liner?

use gsutil to download this all in one go, with gsutil cp -R gs://{project_name}-corpus.clusterfuzz-external.appspot.com/libFuzzer/ .
