### ISSUE TITLE
[znc] can't access the findings

### ISSUE THREAD

**Issue by DarthGandalf** [google/oss-fuzz#5792]
Hi, I got an email report that it found some issue. But it doesn't let me access it. "Permission denied"

@AdamKorcz

**Comment by DavidKorczynski** [comment]
Looking at the email of the project.yaml I think it's due to the "+" https://github.com/google/oss-fuzz/blob/7004ced0d3a94eb07a535d5738e6403dc73ab313/projects/znc/project.yaml#L3

I think we need to get rid of that and write the email verbatim

**Comment by AdamKorcz** [comment]
@DarthGandalf Do you have a gmail or a @google.com account we could use? If not, I suggest we try adding "alexey@asokolov.org" to see if that helps.

**Comment by DarthGandalf** [comment]
Why does this need a google account?

I think alexey+znc@asokolov.org should work too. How am I supposed to apply filters on my email otherwise?

**Comment by DavidKorczynski** [comment]
The problem is on the Clusterfuzz side of things in that it does a verbose email authentication check

**Comment by DavidKorczynski** [comment]
I think it's similar to this issue https://github.com/google/oss-fuzz/issues/4809

**Comment by DavidKorczynski** [comment]
> Why does this need a google account?
> 
It doesn't - however, the email should be affiliated with a Google account. The problem in this case is, however, due to what I wrote in my comments above.

**Comment by DarthGandalf** [comment]
Let's try ktonibud@gmail.com then

**Comment by AdamKorcz** [comment]
Do you want to keep `alexey+znc@asokolov.org` for notifications?

**Comment by DarthGandalf** [comment]
Yes please

**Comment by DarthGandalf** [comment]
Works now, thanks
