### ISSUE TITLE
Extend deadline for handful of bugs.chromium issues

### ISSUE THREAD

**Issue by micahsnyder** [google/oss-fuzz#5801]
Can you please extend the deadline for the following bug reports to 2021-06-21? 🙏 I realize it's a slight stretch for the first one but falls within the guidelines for the rest. 
Each of these would be disclosed at some point prior to that date. The issue may affect a subset of ClamAV users and we would like to mitigate the effects in a patch release on 2021-06-21 (a Monday). 

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=31781
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=31785
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=31786
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=31790
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=31831
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=31939
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32172

**Comment by inferno-chromium** [comment]
Done!
