### ISSUE TITLE
Skia repo builds locally but not on OSS-fuzz

### ISSUE THREAD

**Issue by kjlubick** [google/oss-fuzz#581]
https://oss-fuzz-build-logs.storage.googleapis.com/log-1b9485dd-da62-41cf-b7ca-fe51e60d0fe6.txt

I don't see that zero-as-null-pointer-constant error when I run the following locally:

python infra/helper.py build_image skia
python infra/helper.py build_fuzzers --sanitizer address skia

Any tips to fix this / repro locally?

**Comment by kcc** [comment]
The exact same commands pass for me. 
Maybe you should do a fresh git pull and ensure you don't have local changes?

**Comment by kjlubick** [comment]
They pass for me too locally, which is annoying because it's not what we see when OSS-fuzz tries to run it.

What's the difference?

**Comment by kcc** [comment]
@oliverchang

**Comment by oliverchang** [comment]
I can reproduce this locally. Can you please do a git pull and try

`python infra/helper.py build_image --pull skia`
`python infra/helper.py build_fuzzers skia`

**Comment by kjlubick** [comment]
Can now repro locally, thanks

Will start working on silencing that.

**Comment by oliverchang** [comment]
Great! Thanks for pointing out this issue.
