### ISSUE TITLE
h2o shouldn't set -fsanitize flag, both sanitizer and coverage flags

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#585]
it should just use CFLAGS to get sanitizer and coverage flags. This is causing experimentally enabled msan to not work.
https://oss-fuzz-build-logs.storage.googleapis.com/log-2acd4f93-75af-4072-963c-8b7e37c86562.txt

Step #8: [ 41%] Linking CXX executable h2o-fuzzer-http2
Step #8: clang-5.0: error: invalid argument '-fsanitize=address' not allowed with '-fsanitize=memory'
Step #8: CMakeFiles/h2o-fuzzer-http2.dir/build.make:98: recipe for target 'h2o-fuzzer-http2' failed
Step #8: make[2]: *** [h2o-fuzzer-http2] Error 1
Step #8: CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/h2o-fuzzer-http2.dir/all' failed
Step #8: make[1]: *** [CMakeFiles/h2o-fuzzer-http2.dir/all] Error 2
Step #8: Makefile:127: recipe for target 'all' failed
Step #8: make: *** [all] Error 2
Finished Step #8
ERROR
ERROR: build step "gcr.io/oss-fuzz/h2o" failed: exit status 2

@jfoote, can you please take a look. I think similarly ubsan would be not working at all.

**Comment by inferno-chromium** [comment]
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_C_FLAGS} -fsanitize=address")
    IF (OSS_FUZZ)
        # Use https://github.com/google/oss-fuzz compatible options
        SET(LIB_FUZZER FuzzingEngine)
        SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fno-omit-frame-pointer")
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-omit-frame-pointer")
    ELSE ()
        # Default non-oss-fuzz options
        SET(LIB_FUZZER "${CMAKE_CURRENT_BINARY_DIR}/libFuzzer.a")
        SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fno-omit-frame-pointer -fsanitize=address -fsanitize-coverage=edge,indirect-calls,8bit-counters")
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-omit-frame-pointer -fsanitize=address -fsanitize-coverage=edge,indirect-calls,8bit-counters")

**Comment by inferno-chromium** [comment]
need this fix to enable msan on h2o.

**Comment by jfoote** [comment]
@inferno-chromium I will take a look, it may be a day or two if that is OK. Thanks for the heads up.

Is there an easy way to repro outside of clusterfuzz? Off the cuff I'm thinking I could just modify the `compile` script in a local copy of oss-fuzz to match the culprit CFLAGS assignment but figured I would double-check.

**Comment by inferno-chromium** [comment]
i disabled it for now, so it can wait couple of days.
python infra/helper.py build_image h2o
python infra/helper.py build_fuzzers --sanitizer memory h2o (make sure it builds)
python infra/helper.py run_fuzzer h2o <fuzz_target_name> (make sure that those fuzz targets dont crash on startup).
to reproduce.

I think also, asan is bleeding into ubsan builds, which is wrong. ubsan should be built on its own, so just using CFLAGS, CXXFLAGS which are already set is the right way to go.

**Comment by jfoote** [comment]
PR submitted [here](https://github.com/h2o/h2o/pull/1296). I will update this thread when it gets merged.

**Comment by inferno-chromium** [comment]
Already merged.
