### ISSUE TITLE
LibreOffice build failures: ERROR: context deadline exceeded

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#5855]
The last 4 LibreOffice builds (e.g. https://oss-fuzz-build-logs.storage.googleapis.com/log-601e8efe-5431-4c32-87c1-b46462c58115.txt) are reported as failed with:

TIMEOUT
ERROR: context deadline exceeded

I've seen it before, but it used to be a much more rare occurrence and maybe our build has gotten a little slower so we are now hitting it much more frequently.

git grep "context deadline exceeded" in oss-fuzz doesn't show the string so presumably the timeout is set by something else?

**Comment by MarcoFalke** [comment]
Submitted an untested fix at https://gerrit.libreoffice.org/c/core/+/116642

**Comment by MarcoFalke** [comment]
For reference, the build just passed *before* my fix. :man_shrugging:

**Comment by MarcoFalke** [comment]
Passed twice: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libreoffice

This can be closed?

**Comment by DavidKorczynski** [comment]
> Passed twice: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libreoffice
> 
> This can be closed?

Let's close this one since the build is now passing.
