### ISSUE TITLE
boringssl fuzz target breakage

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#586]
https://oss-fuzz-build-logs.storage.googleapis.com/log-37191629-dc18-4dee-9092-8685eeb65368.txt

Step #3: + echo 'Building fuzzer server'
Step #3: + clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-coverage=trace-pc-guard,trace-cmp -stdlib=libc++ -DBORINGSSL_UNSAFE_FUZZER_MODE -std=c++11 -o /workspace/out/address/server -lFuzzingEngine /src/boringssl/fuzz/server.cc -I /src/boringssl/include ./ssl/libssl.a ./crypto/libcrypto.a
Step #3: /src/boringssl/fuzz/server.cc:274:3: error: use of undeclared identifier 'SSL_set_max_version'
Step #3:   SSL_set_max_version(server, TLS1_3_VERSION);
Step #3:   ^
Step #3: 1 error generated.
Finished Step #3
ERROR
ERROR: build step "gcr.io/oss-fuzz/boringssl" failed: exit status 1

@davidben - can you please take a look.

**Comment by davidben** [comment]
Gah, sorry about that. Should be fixed now. I'll work on adding this to our builders today so this doesn't happen again.

**Comment by inferno-chromium** [comment]
Confirmed that latest build passes.
