### ISSUE TITLE
Mercurial build failing with "ERROR: context deadline exceeded" and we didn't change anything

### ISSUE THREAD

**Issue by durin42** [google/oss-fuzz#5903]
I looked into [the current failure](https://oss-fuzz-build-logs.storage.googleapis.com/log-d2c412f2-1e84-476f-a1ea-e9f9a1e6ba08.txt) for Mercurial's build and AFAICT it's a deadline that we don't control, and a step we don't control. Is this an oss-fuzz-side problem, or a Mercurial-side problem?

**Comment by MarcoFalke** [comment]
See also:
*  https://github.com/google/oss-fuzz/issues/5855
* https://github.com/google/oss-fuzz/pull/5858

**Comment by DavidKorczynski** [comment]
I looked a bit at this so I not completely understand mercurials fuzzing infra yet. However, @during it seems like you are building Python from source? Are there perhaps some ways we can speed up the build process, for example a lot of tests are compiled which may not be needed? Also, are you building Python from source so you can have python code compiled with sanitizers? OSS-Fuzz now supports Atheris - a Python-focused fuzzer than can also fuzz native libraries. If you have Python fuzzers would it make sense to try and rely on Atheris? https://github.com/google/atheris

**Comment by durin42** [comment]
Yes, we're building Python from source because some of the hg stuff we're fuzzing is cpython extension code. AFAIK Atheris is actually a descendant of the work we did for these fuzzers. Are there any examples of using atheris on oss-fuzz I can copy from?

**Comment by DavidKorczynski** [comment]
I think Pillow is the most complete Python fuzzing that also targets extensions:
- https://github.com/google/oss-fuzz/tree/master/projects/pillow

Others:
- Ujson: https://github.com/google/oss-fuzz/tree/master/projects/ujson

**Comment by DavidKorczynski** [comment]
oddly enough the CI is happy https://github.com/google/oss-fuzz/pull/5904

Am not sure here as I would have thought the CI would have less time allocated for builds. @inferno-chromium @jonathanmetzman perhaps you have a thought here?

**Comment by jonathanmetzman** [comment]
I'll try to look into this today.

**Comment by durin42** [comment]
FWIW I took a quick look at Atheris today and it looks like we'd have to disable msan for that, which I'm hesitant to lose. We're not fuzzing pure-Python logic, but instead fuzzing CPython extensions in case that changes your expectations.

Note that the Mercurial build is currently working, so I'm not sure there's an action for you here, at least on Mercurial.

**Comment by jonathanmetzman** [comment]
Build no longer failing: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#mercurial
