### ISSUE TITLE
Access Denied Issue

### ISSUE THREAD

**Issue by yzhang71** [google/oss-fuzz#5923]
Hi Team,
When I tried to see the detail of crashed test-case, I got "Access Denied", error message is below.

You (email=yzhang0701@gmail.com) are not authorized to access this page!

Please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.

Can someone please help? Thank you so much.

**Comment by DavidKorczynski** [comment]
Which project is this about?

**Comment by yzhang71** [comment]
Hi David,

Thanks for replying. Here is the project info:
Project: binutils
Fuzzing Engine: afl
Fuzz Target: fuzz_disassemble
Job Type: afl_asan_binutils
Platform Id: linux

And here is the link I can't access: https://oss-fuzz.com/testcase?key=5713869317603328

**Comment by DavidKorczynski** [comment]
Your email should be added to the `project.yaml` file here: https://github.com/google/oss-fuzz/blob/master/projects/binutils/project.yaml

You can put it under the `auto_ccs` field.

Just to clarify, are you involved with the binutils project?

**Comment by yzhang71** [comment]
Hi David,

I am not sure if I am involved binutils project. Currently I am fuzzing binutils locally, and detect several bugs by using ASAN, so I want check if these bugs are been reported by OSS project.

**Comment by inferno-chromium** [comment]
> Hi David,
> 
> I am not sure if I am involved binutils project. Currently I am fuzzing binutils locally, and detect several bugs by using ASAN, so I want check if these bugs are been reported by OSS project.

@yzhang71 - you cannot get access to bug unless you are a project maintainer.
