### ISSUE TITLE
[CIFuzz] Figure out a better container to run fuzzers in

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#5926]
Currently CIFuzz has a run_fuzzers container that for each fuzzer spawns a new container from gcr.io/oss-fuzz-base/base-runner and runs the fuzzers in that container.
This is bad for a few reasons:
1. It makes it harder to kill the fuzzer processes.
2. It adds complexity, especially if we want to use libClusterFuzz to run the fuzzers.
An alternative is to run the fuzzers in the run_fuzzers container which can inherit from base-runner.

There's another alternative I'm considering. When CIFuzz supports non-OSS-Fuzz users, it's probably going to annoy people that they can't install runtime dependencies in the dockerfile they provide. Maybe we can run the fuzzers directly in that container for this usecase.

**Comment by oliverchang** [comment]
+1 to just using an image with libClusterFuzz installed.

Would prefer if we could push people to build mostly static targets (i.e. stay with a base-runner), similar to OSS-Fuzz where this has worked for most people. We should avoid diverging too much of our build/runtime systems to make maintenance of both easier.

**Comment by jonathanmetzman** [comment]
> Would prefer if we could push people to build mostly static targets (i.e. stay with a base-runner), similar to OSS-Fuzz where this has worked for most people. We should avoid diverging too much of our build/runtime systems to make maintenance of both easier.

I would prefer this too. And I agree allowing nonstatic will be at least as much maintenance complexity as having base-runner. But I think nonstatic puts a burden on users to deploy ClusterFuzzLite. It seems fine but we might be missing the cases where nonstatic doesn't work and we only see the cases where it does. Also, I suspect open source software may be less likely to have issues with a static requirement than other software since open source software needs to be run on diverse environments, other software may not need to.

**Comment by oliverchang** [comment]
Perhaps we can let users override the image used for running the fuzzers, provided that it inherits from our base-runner (with libCF installed). 

We should heavily encourage the default though. Another benefit would be seamless integration into OSS-Fuzz if a project that tries CIFuzz wants to integrate into OSS-Fuzz proper.

**Comment by jonathanmetzman** [comment]
>Perhaps we can let users override the image used for running the fuzzers, provided that it inherits from our base-runner (with libCF installed).

This would help, but I think one image for building and running makes things much simpler for devs.

> Another benefit would be seamless integration into OSS-Fuzz if a project that tries CIFuzz wants to integrate into OSS-Fuzz proper.

This doesn't seem like a big benefit to me. CFLite needs users much more at this point than OSS-Fuzz :-)

**Comment by oliverchang** [comment]
The whole point of reusing OSS-Fuzz's build toolchain is to have something consistent/standardized for open source. I agree with the point about making things easier though, but we shouldn't diverge too much here.

**Comment by oliverchang** [comment]
We should figure this out early, since it's an important piece that's hard to change later.

libClusterFuzz should be in better shape now after https://github.com/google/clusterfuzz/commit/4f8020c4c7ce73c1da0e68f04943af30bb5f0b32. The current available functions are in https://github.com/google/clusterfuzz/tree/master/src/clusterfuzz (anything that isn't `_internal`).

@jonathanmetzman anything big missing from this (I think a simple pruning routine is one thing), or any other blockers?

I'm thinking we can just install libClusterFuzz into base-runner, and then we can have CIFuzz run in the same image (or use it as a base). WDYT? Are there any other issues / blockers we need to resolve?

**Comment by jonathanmetzman** [comment]
> I'm thinking we can just install libClusterFuzz into base-runner, and then we can have CIFuzz run in the same image (or use it as a base). WDYT? Are there any other issues / blockers we need to resolve?

I think we don't agree about whether fuzzing should be done in the builder image in ClusterFuzzLite. I think this is a bit of a blocker.

**Comment by oliverchang** [comment]
If we run things in the builder, things like coverage also won't work. We'd have to maintain a separate builder base image with all the coverage tools installed.

Keeping the same model as OSS-Fuzz just has has large benefits in terms of maintenance and promoting uniformity. We can potentially also extend `helper.py` to let people more easily run their CIFuzz stuff locally on their own machines (#6125). 

Diverging here will be painful to support, and make future development harder. If we do see lots of requests for this, the right way to go about it would be to do things in a way that benefits both OSS-Fuzz and CIFuzz. Maybe we can even get away with something at the build level (like e.g. detecting all shared libraries dependencies and copying automatically into $OUT).

**Comment by jonathanmetzman** [comment]
> If we run things in the builder, things like coverage also won't work. We'd have to maintain a separate builder base image with all the coverage tools installed.
> 

We already have a cifuzz-base image. This can inherit from base-builder and include things that are needed from base-runner.

> Keeping the same model as OSS-Fuzz just has has large benefits in terms of maintenance and promoting uniformity. We can potentially also extend `helper.py` to let people more easily run their CIFuzz stuff locally on their own machines (#6125).
> 
> Diverging here will be painful to support, and make future development harder. If we do see lots of requests for this, the right way to go about it would be to do things in a way that benefits both OSS-Fuzz and CIFuzz. Maybe we can even get away with something at the build level (like e.g. detecting all shared libraries dependencies and copying automatically into $OUT).
