### ISSUE TITLE
Add noble-crypto projects to fuzzer

### ISSUE THREAD

**Issue by paulmillr** [google/oss-fuzz#5945]
Almost two years ago, i've decided to create no-dependency cryptographic libraries for JavaScript (actually Typescript). Infrastructure hacks are a huge problem in JS, when hacking one dep can bring down thousands of commercial projects. [1](https://medium.com/intrinsic/compromised-npm-package-event-stream-d47d08605502) [2](https://blog.npmjs.org/post/185397814280/plot-to-steal-cryptocurrency-foiled-by-the-npm)

The libraries increase ECC security, since all Noble releases are signed, don't contain dependencies and a user is able to verify the source code in a simpler way versus indutny/elliptic, which uses BigNum library with thousands of LOC. They are written in a very concise way. Check out a blog post about 'em: https://paulmillr.com/posts/noble-secp256k1-fast-ecc/

Right now we have three main libraries:

1. [secp256k1](https://github.com/paulmillr/noble-secp256k1)
2. [ed25519](https://github.com/paulmillr/noble-ed25519)
3. [bls12-381](https://github.com/paulmillr/noble-bls12-381)

secp256k1 has been audited by a third-party firm; the audit has been crowdfunded.

All three libraries have been fuzzed with [cryptofuzz](https://github.com/guidovranken/cryptofuzz/tree/master/modules) thanks to Guido Vranken.

I think we should make noble fuzzable on OSS-Fuzz! Would you be open for the idea?

**Comment by inferno-chromium** [comment]
Adding noble to cryptofuzz should be fine.

**Comment by paulmillr** [comment]
@inferno-chromium cryptofuzz already has it

**Comment by guidovranken** [comment]
@inferno-chromium Would it be OK to create a new project, in which noble-sec256k1, noble-ed25519 and noble-bls12-381 are fuzzed? The main `cryptofuzz` project is already quite heavy with many libraries, and adding more libraries to it does not help the effectiveness..

**Comment by inferno-chromium** [comment]
> @inferno-chromium Would it be OK to create a new project, in which noble-sec256k1, noble-ed25519 and noble-bls12-381 are fuzzed? The main `cryptofuzz` project is already quite heavy with many libraries, and adding more libraries to it does not help the effectiveness..

I can adjust a project weight to give more cpu cores, so effectiveness shouldnt be hampered. Since noble is not widely used, i wont prefer to add another project for this.

**Comment by guidovranken** [comment]
OK thank you.
