### ISSUE TITLE
All open crashes have disappeared from oss-fuzz.com

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#5967]
E.g.:

https://oss-fuzz.com/testcases?project=wolfssl&open=yes
https://oss-fuzz.com/testcases?project=cryptofuzz&open=yes

There should be a whole bunch of them. A few hours ago this was still working, now the pages are empty.

**Comment by rlohning** [comment]
Same for Qt, it seems, but the respective issues in the bugtracker are still open:

https://bugs.chromium.org/p/oss-fuzz/issues/list?q=proj%3Dwolfssl
https://bugs.chromium.org/p/oss-fuzz/issues/list?q=proj%3Dcryptofuzz
https://bugs.chromium.org/p/oss-fuzz/issues/list?q=proj%3Dqt

**Comment by inferno-chromium** [comment]
So, this is looking like UI breakage, so fuzzing and issue tracker are all fine. Worst part is no error in stackdriver logs, testcases/cache cron is fine too. 

Some testcases are showing up now - https://oss-fuzz.com/testcases?project=wolfssl&open=yes
https://oss-fuzz.com/testcases?project=cryptofuzz&open=yes
but list is looking like incomplete (e.g. https://bugs.chromium.org/p/oss-fuzz/issues/list?q=label:Proj-cryptofuzz has more bugs than UI). Could be some appengine query/indexes breakage, lets give it a day or two. nothing is showing up wrong in our logs. yikes. @oliverchang fyi to double check on monday.

**Comment by inferno-chromium** [comment]
it seems to be coming back, might be some appengine breakage. please close if things look ok tmrw.

**Comment by oliverchang** [comment]
This seems to be OK now? It's likely there was some Datastore issue/outage affecting this.

**Comment by inferno-chromium** [comment]
> This seems to be OK now? It's likely there was some Datastore issue/outage affecting this.

Yes closing.
