### ISSUE TITLE
Requesting monorail permissions to CC other people

### ISSUE THREAD

**Issue by kjlubick** [google/oss-fuzz#599]
OSS-fuzz has filed some bugs against me (yay) for the Skia Project ([example](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1498)).

I am not the best person to fix them and would like to re-assign it and/or CC some of the Skia devs who can better address it.  However, I do not seem to have permissions to do so.

I would like these permissions for me (kjlubick@chromium.org) and hcm@chromium.org

**Comment by inferno-chromium** [comment]
You should be able to cc other folks and they will automatically get access to bug. If not, best to add these folks to project.yaml and system will autocc them.

**Comment by kjlubick** [comment]
I can now CC - thanks :)
