### ISSUE TITLE
Coverage data does not represent reality

### ISSUE THREAD

**Issue by michaelni** [google/oss-fuzz#5994]
The FFmpeg hevc coverage shown for example at https://storage.googleapis.com/oss-fuzz-coverage/ffmpeg/reports/20210704/linux/src/ffmpeg/libavcodec/report.html
show many hevc files as 0%
```
hevc_cabac.c	 	  0.00% (0/898)	 	  0.00% (0/56)	  0.00% (0/787)
hevc_filter.c	 	  0.00% (0/709)	 	  0.00% (0/16)	  0.00% (0/691)
hevc_mvs.c	  	  0.00% (0/525)	 	  0.00% (0/14)	  0.00% (0/552)
hevc_refs.c	 	 21.07% (79/375)	 43.75% (7/16)	 23.54% (89/378)
hevcdec.c		 35.21% (1012/2874)	 38.30% (18/47)	 36.94% (939/2542)
hevcdsp_template.c	  0.00% (0/1115)	  0.00% (0/56)	  0.00% (0/1180)
hevcpred_template.c	  0.00% (0/433)	 	  0.00% (0/10)	  0.00% (0/651)
```

But if i run coverage fully manually without any google code building with -fprofile-instr-generate -fcoverage-mapping
```
i=0
allprofraw=
for f in fate-suite/hevc/* fate/fate-suite/hevc-conformance/* hevc_corpus/google_cloud/*; do
    export LLVM_PROFILE_FILE="foo-$i.profraw"
    tools/target_dec_hevc_fuzzer $f
    i=$[$i+1]
    allprofraw="$allprofraw $LLVM_PROFILE_FILE"
done

for f in fate-suite/hevc/* fate-suite/hevc-conformance/* ; do
    export LLVM_PROFILE_FILE="foo-$i.profraw"
    tools/target_dem_fuzzer $f
    i=$[$i+1]
    allprofraw="$allprofraw $LLVM_PROFILE_FILE"
done

llvm-profdata merge -sparse $allprofraw -o default.profdata

llvm-cov report ./tools/target_dec_hevc_fuzzer -instr-profile=default.profdata | grep hevc | egrep -v 'vdpau|vaapi|bsf'
```

These files have close to 100% coverage
```
libavcodec/hevc_cabac.c                        787                17    97.84%          56                 0   100.00%         999                15    98.50%
libavcodec/hevc_filter.c                       713                23    96.77%          16                 0   100.00%         788                 6    99.24%
libavcodec/hevc_mvs.c                          552                 6    98.91%          14                 0   100.00%         626                12    98.08%
libavcodec/hevc_parse.c                         65                 0   100.00%           2                 0   100.00%         115                 0   100.00%
libavcodec/hevc_parser.c                       188                 6    96.81%           5                 0   100.00%         269                 4    98.51%
libavcodec/hevc_ps.c                          1274                31    97.57%          21                 0   100.00%        1651                50    96.97%
libavcodec/hevc_refs.c                         378                36    90.48%          16                 0   100.00%         458                24    94.76%
libavcodec/hevc_sei.c                          255                 8    96.86%          19                 0   100.00%         425                 6    98.59%
libavcodec/hevcdec.c                          2542               435    82.89%          47                 6    87.23%        3321               596    82.05%
libavcodec/hevcdec.h                            11                11     0.00%           1                 1     0.00%          15                15     0.00%
libavcodec/hevcdsp.c                           796                 4    99.50%           1                 0   100.00%         144                 0   100.00%
libavcodec/hevcdsp_template.c                 1180                14    98.81%          56                 0   100.00%        1193                 6    99.50%
libavcodec/hevcpred.c                           64                 1    98.44%           1                 0   100.00%          37                 0   100.00%
libavcodec/hevcpred_template.c                 651                64    90.17%          10                 0   100.00%         460                18    96.09%
libavcodec/x86/hevcdsp_init.c                  503                 5    99.01%          17                 0   100.00%         577                 0   100.00%
libavcodec/hevcdsp.h                             0                 0         -           0                 0         -           0                 0         -
libavcodec/x86/hevcdsp.h                         0                 0         -           0                 0         -           0                 0         -

```

**Comment by DavidKorczynski** [comment]
There can be discrepancies between running coverage locally and by way of the OSS-Fuzz set up. For example, the flag `-close_fd_mask=3` is set when running the coverage fuzzers by way of OSS_Fuzz: https://github.com/google/oss-fuzz/blob/64370814b47e93addc215d8c1deaaccd544d4212/infra/base-images/base-runner/coverage#L82

What is the result you get from running coverage by way of oss-fuzz locally? You can do this using the commands
```
python3 infra/helper.py build_fuzzers --sanitizer=coverage PROJ_NAME
python3 infra/helper.py coverage --no-corpus-download PROJ_NAME
```
The above commands assume you have corpus directories named according to the fuzzers in `build/corpus/PROJ_NAME/FUZZER_NAME` (i.e. one corpus directory per fuzzer)

**Comment by michaelni** [comment]
If i run coverage by way of oss-fuzz locally (limited to the target in question) i get the same results as are shown on the web. lots of 0% entries. It is also noticeable that "infra/helper.py coverage --no-corpus-download ffmpeg --fuzz-target=ffmpeg_AV_CODEC_ID_HEVC_fuzzer" opens the web server within 18seconds while running coverage without ossfuzz on the same files takes around 9 minutes so i dont think it really considers all files. Sadly there is no warning and no error message. And the documentation doesnt really seem to document how to debug/investigate coverage issues. 
Also as you pointed to a line of base-runner/coverage, i dont think editing this in the local checkout would have an effect as the code seems to not use the local checkout of base-runner/coverage or maybe iam just really stupid

**Comment by DavidKorczynski** [comment]
Modifying the various builders locally can be tested with rebuilding the docker images using 
`infra/base-images/all.sh` See here: https://github.com/google/oss-fuzz/tree/master/infra/base-images

I think the reason there is no documentation on debugging coverage issues is really because it shouldn't be different. I think it would be nice to use this issue to solve some of the differences there may be. Could you try rebuilding the way I describe above and see if it works?

**Comment by DavidKorczynski** [comment]
I checked if removing `-close_fd_mask=3` would solve the issue but it did not.

**Comment by DavidKorczynski** [comment]
`-close_fd_mask=3` is now removed, perhaps we can wait a day or so (so the new base runner is used) and see if it changes things?

I also experienced what you describe about the execution time. However, in my case, the entry point of the fuzzer `LLVMFuzzerTestOneInput` was indeed hit in the coverage run the correct number of times (i.e. coverage showed it was hit 5.4K times for 5.4K inputs).That makes me think it's something in the execution itself that is different.

**Comment by michaelni** [comment]
I found a bug on the FFmpeg side of the fuzzer, that may be related, i will push a fix for it to ffmpeg-git probably soon. We will see if that resolves this. Patch is here for reference: https://lists.ffmpeg.org/pipermail/ffmpeg-devel/2021-July/282075.html

**Comment by michaelni** [comment]
Running coverage by way of oss-fuzz locally now gives much better numbers, so i assume this will resolve itself when ossfuzz runs the next time, and probably was the bug on the FFmpeg side.

**Comment by DavidKorczynski** [comment]
Wonderful, thanks for updating.
