### ISSUE TITLE
UBSan support

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#60]
build fuzzers with [Undefined Behavior Sanitizer](http://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html)

`signed-integer-overflow,shift,vptr` are good starting configuration.

Should be a different upload binary.

**Comment by kcc** [comment]
`bool` should be pretty easy and useful too

**Comment by alex** [comment]
Should https://github.com/google/oss-fuzz/blob/master/infra/libfuzzer-pipeline.groovy#L31 be updated so that `undefined` is enabled by default?

**Comment by mikea** [comment]
Alex, that's exactly the plan. We need to fix couple more things before though. Most notably we need to report precise sanitizer configuration in bug reports.

**Comment by mikea** [comment]
Supported in helper.py & documented: https://github.com/google/oss-fuzz/blob/master/docs/reference.md#sanitizers

Forked #232, #233, #234.
