### ISSUE TITLE
email issue

### ISSUE THREAD

**Issue by rouault** [google/oss-fuzz#600]
I get an access denied error when accessing https://oss-fuzz.com/v2/testcase-detail/6249814238953472 which is a bug for GDAL,  whose I'm project owner, and the list https://bugs.chromium.org/p/oss-fuzz/issues/list?q=gdal remains empty. I login with my even.rouault at gmail.com account , which is associated with even.rouault at spatialys.com declared in https://github.com/google/oss-fuzz/blob/master/projects/gdal/project.yaml . What should I do ?

**Comment by inferno-chromium** [comment]
I think you are hitting https://github.com/google/oss-fuzz/issues/243. I just replaced your email with the gmail one, give it half an hour, then you should be able to access.

**Comment by rouault** [comment]
Ok that works now. Thanks
