### ISSUE TITLE
About llvm-patch (libFuzzer)

### ISSUE THREAD

**Issue by gtt1995** [google/oss-fuzz#6005]
https://reviews.llvm.org/D105084

Hello, I don’t know why, my RR (request for comment) on llvm's phabricator has never received a response, so with the help of clusterfuzz, please help me to pay attention.
@Dor1s 
@oliverchang 
@jonathanmetzman 
@inferno-chromium 
@morehouse 
Thanks very much!

In this patch, I found that libFuzzer’s fork mode has certain flaws. I proposed some strategies to solve these problems. Because it is an improvement of parallel fuzzing, I cannot evaluate it on fuzzbench. Finally, I uploaded my own local experiment data, and test targets are real-world programs from the OSS-Fuzz project.

**Comment by DavidKorczynski** [comment]
Closing this as it's a duplicate of https://github.com/google/clusterfuzz/issues/2373 which is the repository addressed in the comment. I will let it be handled over there.
