### ISSUE TITLE
Fuzz Tantivy?

### ISSUE THREAD

**Issue by migadi** [google/oss-fuzz#6022]
(new github account as I really use Gitlab for code and forgot password to my old one)

Is it OK if I begin work on adding fuzzing support for the Tantivy search engine? It's a notable project, being the most popular Rust based search library. It has over 5k stars on Github, 110,000 pages written about it (at least that's what Google says), and various websites like http://archivesort.org/ have reported using the library.  Toshi is also another popular library based on Tantivy.

The maintainer says he would like to see fuzzing efforts, so the question is this, are you fine with the project being added to oss-fuzz? I wouldn't want to do the work for you to reject it.
Thanks

**Comment by inferno-chromium** [comment]
Yes, we would be happy to accept it in oss-fuzz.
