### ISSUE TITLE
Cannot reproduce issues reported by oss-fuzz

### ISSUE THREAD

**Issue by vitaut** [google/oss-fuzz#6034]
I recently got several similar issues opened by oss-fuzz, for example, https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36086. However, I hasn't been able to repro it following the steps in https://google.github.io/oss-fuzz/advanced-topics/reproducing/:

```
$ sudo python3 infra/helper.py build_image fmt
$ sudo python3 infra/helper.py build_fuzzers --sanitizer address --architecture x86_64 fmt
$ sudo python3 infra/helper.py reproduce fmt named-arg-fuzzer ../fmt/test/fuzzing/clusterfuzz-testcase-minimized-named-arg-fuzzer-4935542000189440
Running: docker run --rm --privileged -i -v /home/vagrant/oss-fuzz/build/out/fmt:/out -v /home/vagrant/fmt/test/fuzzing/clusterfuzz-testcase-minimized-named-arg-fuzzer-4935542000189440:/testcase -t gcr.io/oss-fuzz-base/base-runner reproduce named-arg-fuzzer -runs=100
+ FUZZER=named-arg-fuzzer
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ export SKIP_SEED_CORPUS=1
+ SKIP_SEED_CORPUS=1
+ run_fuzzer named-arg-fuzzer -runs=100 /testcase
/out/named-arg-fuzzer -rss_limit_mb=2560 -timeout=25 -runs=100 /testcase < /dev/null
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2897256350
INFO: Loaded 1 modules   (3416 inline 8-bit counters): 3416 [0x8aebd0, 0x8af928),
INFO: Loaded 1 PC tables (3416 PCs): 3416 [0x6345e0,0x641b60),
/out/named-arg-fuzzer: Running 1 inputs 100 time(s) each.
Running: /testcase
Executed /testcase in 4 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
```
This doesn't report any errors.

Moreover the regression revision range refers only to documentation and comment changes in {fmt}: https://github.com/fmtlib/fmt/commit/e41ac1f875b7a1c419beaf7ddf431a01fb530a92.

Similar issues:
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36105
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36110
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36115
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36119

**Comment by vitaut** [comment]
Update: the issues were marked as fixed/verified despite no meaningful changes in {fmt}.

**Comment by evverx** [comment]
If the bugs were found with AFL, I suspect they have something to do with https://github.com/google/oss-fuzz/issues/6037

**Comment by MarcoFalke** [comment]
Can this be closed?
