### ISSUE TITLE
cifuzz batch: upload corpus and coverage report to git branch/repo instead

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#6052]
Currently batch mode doesn't really handle parallelism. There is only 1 artifact which contains the entire corpus.

One possibly crazy idea is to store corpora in a git branch instead with individual files -- because filenames are sha hashes we get deduplication for free.

**Comment by oliverchang** [comment]
@jonathanmetzman thoughts?

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman thoughts? another benefit is that this is much more CI agnostic, and we can use this to store other artifacts in the future as well.

This sounds like a brilliant idea. My only concern is that maybe some projects have a workflow where people download all branches and this branch would get larger and larger over time. I don't know about git enough to know if this is an actual thing, but if someone who does know about git told me it isn't a real use of git I think this is a great idea.

**Comment by oliverchang** [comment]
> > @jonathanmetzman thoughts? another benefit is that this is much more CI agnostic, and we can use this to store other artifacts in the future as well.
> 
> This sounds like a brilliant idea. My only concern is that maybe some projects have a workflow where people download all branches and this branch would get larger and larger over time. I don't know about git enough to know if this is an actual thing, but if someone who does know about git told me it isn't a real use of git I think this is a great idea.

I think the default behaviour of `git clone` does download data for all remote branches, so this could be concern. We will have pruning though. 

We can address this by giving an option to set up another repo instead to store the corpora, if this is a concern for the repo owner.

**Comment by jonathanmetzman** [comment]
> > > @jonathanmetzman thoughts? another benefit is that this is much more CI agnostic, and we can use this to store other artifacts in the future as well.
> > 
> > 
> > This sounds like a brilliant idea. My only concern is that maybe some projects have a workflow where people download all branches and this branch would get larger and larger over time. I don't know about git enough to know if this is an actual thing, but if someone who does know about git told me it isn't a real use of git I think this is a great idea.
> 
> I think the default behaviour of `git clone` does download data for all remote branches, so this could be concern. We will have pruning though.

Pruning might not help depending on what data is downloaded. If the full history of each branch is downloaded it won't help because deleting binary files in a git repo does not remove them from the history nor decrease the repo size.

**Comment by oliverchang** [comment]
I started this in https://github.com/google/oss-fuzz/pull/6088. Corpus uploading works well, but I haven't been able to test coverage generation yet because it doesn't look like it works yet.

**Comment by oliverchang** [comment]
And coverage now works well and can be rendered by github pages: https://oliverchang.github.io/cifuzz-external-storage/coverage/latest/report/linux/report.html

**Comment by oliverchang** [comment]
Follow up: investigate if we can upload builds to Git as well (squashing to remove history if necessary).

**Comment by oliverchang** [comment]
There are some issues here for storing larger artifacts like builds. 

- Github has a hard limit of 100MB per file. Not an issue for most projects, but we have seen larger binaries in larger projects. It's also not clear if we're run into other abuse/performance issues here as it's not an intended use case for git.
- There's git LFS but GitHub's quota is a pretty small 1GB of bandwidth (actions bandwidth is counted).

As an aside, I also think we should also decouple the upload build action from the current action. i.e. an action dedicated to uploading builds for a commit. This will also make parallel batch fuzzing more easily supported, and get rid of the current hacky logic:

https://github.com/google/oss-fuzz/blob/290344bc6ab0097d12a1a62a9a920da82861110f/infra/cifuzz/run_fuzzers.py#L243

Perhaps we can also just not have this build requirement at all -- if a "latest" build doesn't exist for some reason, just build the commit prior to the current PR/commit and try it there?

**Comment by oliverchang** [comment]
I think we'll keep things as is. @jonathanmetzman Let me know if you disagree.
