### ISSUE TITLE
cifuzz batch: don't rely on a base commit.

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#6053]
Currently all CIFuzz batch runs seem to rely on diffing on a basic commit. This requirement should be removed.

**Comment by oliverchang** [comment]
#6055 address this, but I wonder why we need to care about `base_commit` at all for push events? 

Are the two cases we care about just:
- pull_request, for PR fuzzing. This is the only case we care about affected fuzzers?
- batch fuzzing, from either pushes to master, schedule or workflow_dispatch events. We should try to run all fuzzers in this case? 

@jonathanmetzman

**Comment by jonathanmetzman** [comment]
We care about diffing for commits too. systemd does fuzzing against PRs and master commits (so the same PR is fuzzed twice before it lands and after). I think this workflow is standard. If we want a badge, I think the way most badges work depend on the CI job being run on master.

**Comment by oliverchang** [comment]
> We care about diffing for commits too. systemd does fuzzing against PRs and master commits (so the same PR is fuzzed twice before it lands and after). I think this workflow is standard. If we want a badge, I think the way most badges work depend on the CI job being run on master.

OK, in that case #6055 doesn't drop support for that -- it just enables fuzzing at master/main with other mechanisms like schedules or workflow_dispatch. PTAL at that PR.
