### ISSUE TITLE
cifuzz: affected fuzzer detection for external

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#6054]
right now we always check for oss-fuzz coverage reports. we need to support external coverage reports too.

**Comment by jonathanmetzman** [comment]
Assuming coverage reports work properly in ClusterFuzzLite, this should work as well.

**Comment by jonathanmetzman** [comment]
Assuming coverage reports work properly in ClusterFuzzLite, this should work as well.

**Comment by oliverchang** [comment]
Is this working now?

**Comment by jonathanmetzman** [comment]
Yes it is.
