### ISSUE TITLE
Suppressing memory leaks coming from an external library

### ISSUE THREAD

**Issue by tonkosi** [google/oss-fuzz#6066]
Hi, the [lldb_vs_lldb_eval_libfuzzer_test](https://oss-fuzz.com/fuzzer-stats?group_by=by-day&fuzzer=libFuzzer_lldb-eval_lldb_vs_lldb_eval_libfuzzer_test&job=libfuzzer_asan_lldb-eval&project=lldb-eval) target of [lldb-eval](https://github.com/google/oss-fuzz/tree/master/projects/lldb-eval) project is consistently failing with a memory leak ([crash report](https://oss-fuzz.com/testcase-detail/4809097760342016)). The leak is coming from an external library and we'd like to suppress it, at least until it's fixed in the external source.

Last week I updated the fuzz test with the following functions:

```
extern "C" const char* __lsan_default_options() {
  return "print_suppressions=0";
}

extern "C" const char* __lsan_default_suppressions() {
  return "leak:printNode(llvm::itanium_demangle::Node const*\n"
         "leak:llvm::itanium_demangle::initializeOutputStream";
}
```

This suppresses unwanted leak reports for me locally (when running `python infra/helper.py run_fuzzer --sanitizer address lldb-eval lldb_vs_lldb_eval_libfuzzer_test`). However, it continues to fail with the same leak error in the real OSS-Fuzz environment.

Am I using suppression list in a wrong way? Here are the first few lines of the error message and I can see the `printNode(llvm::itanium_demangle::Node const*` rule appearing as a substring:

```
Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x51c48d in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x7f738037b9b8 in initializeOutputStream /src/llvm-project/llvm/include/llvm/Demangle/Utility.h:178:31
    #2 0x7f738037b9b8 in printNode(llvm::itanium_demangle::Node const*, char*, unsigned long*) /src/llvm-project/llvm/lib/Demangle/ItaniumDemangle.cpp:389:8
    #3 0x7f737620509e in DWARFASTParserClang::ParseSubroutine(DWARFDIE const&, ParsedDWARFTypeAttributes&) /src/llvm-project/lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp:1237:22
    #4 0x7f73761f680e in DWARFASTParserClang::ParseTypeFromDWARF(lldb_private::SymbolContext const&, DWARFDIE const&, bool*) /src/llvm-project/lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp:522:15
```

Another way of suppressing I know of is via environment variables, e.g. `LSAN_OPTIONS="suppressions=file.txt print_suppressions=0"`. Could that fix issues and how to set the environment variable correctly?

Any help would be very much appreciated :)

**Comment by DavidKorczynski** [comment]
Have you tried using the `.options` file of OSS-Fuzz? This is a file where you can specify settings for the fuzzers. See here for an example with Readelf where we disable leaks:
https://github.com/google/oss-fuzz/blob/master/projects/binutils/fuzz_readelf.options

Simply adding 
```
[libfuzzer]
detect_leaks=0
```

Will do the job.

The options file must have the same name as the fuzzer that is moved to `$OUT`, and the options file itself should also be moved to `$OUT`

**Comment by tonkosi** [comment]
I didn't know that, thank you for pointing the options file out!

I wondered if there's a way to suppress specific leaks, but `detect_leaks=0` is also fine in our case.

**Comment by DavidKorczynski** [comment]
Great! Closing as it has now been solved.
