### ISSUE TITLE
cifuzz: Figure out what to do with artifacts

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#6070]
Won't post full details here, but we should figure out if we want to use nodejs library for uploading/downloading artifacts and switch to it if we do want to.

**Comment by oliverchang** [comment]
I think there are pretty good reasons to switch to using the nodejs library here, given that the python port is a non-trivial amount of code. The maintenance cost isn't worth the benefits.

**Comment by jonathanmetzman** [comment]
I think there's another issue with uploading artifacts. Some artifacts like coverage reports need to have subdirectories. But github actions artifacts doesn't like this. So we will need to archive the coverage report before uploading it.

**Comment by oliverchang** [comment]
I think we'll keep this current code as is, given the limitation you described.
