### ISSUE TITLE
Need instrumented versions for system libs to make MSAN work

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#608]
This is needed for several projects that depend on system libraries. E.g see https://github.com/google/oss-fuzz/pull/607

**Comment by kcc** [comment]
I've looked at the existing warnings from libpng, freetype, libarchive, 
and they are clearly caused by linking in non-instrumented system libs like -lz, lzma, or -larchive 

So, I think any further msan roll up is blocked until we can provide msan-instrumented libs in the docker image for msan. 

I suggest this order of steps: 
* add `-lz` and `-larchive`
* observe at least png and freetype targets get clean, enable them
* add `-lbz2 -llzo2  -lxml2 -llzma  -lcrypto -llz4 -licuuc `

**Comment by oliverchang** [comment]
Progress update:

We now have a set of scripts in https://github.com/google/oss-fuzz/tree/master/infra/base-images/msan-builder that attempt to build MSan instrumented libraries by hooking into debian's package build system.

This should hopefully work for most packages in a debian-based distro with some [minor overrides](https://github.com/google/oss-fuzz/tree/master/infra/base-images/msan-builder/packages).

At at high level this:

- Install a compiler [wrapper](https://github.com/google/oss-fuzz/blob/master/infra/base-images/msan-builder/compiler_wrapper.py) and sets up [various other](https://github.com/google/oss-fuzz/blob/master/infra/base-images/msan-builder/msan_build.py#L48) wrappers and environment variables.

- Figure out package dependencies that are c/c++ libraries (and build those too)

- Use `apt-get source` to get the source archive for them.

- Do `dpkg-buildpackage` to do the build and create .deb files

-  Extract shared libraries from the .deb files, fixing symlinks and rpaths to be relative.

Our infra will build a set of libraries specified [here](https://github.com/google/oss-fuzz/blob/master/infra/base-images/msan-builder/Dockerfile#L32)

Some remaining work:
- [ ] Make sure `openssl` gets `--no-asm` during configure
- [ ] Some basic tests to make sure the .so files are actually msan instrumented
- [ ] Enable more libraries to be built by default.
- [ ] Include these libraries in MSan project builds.

**Comment by oliverchang** [comment]
Also have a question for @eugenis :

To keep our build process simple, we're building libraries with `-fsanitize-recover=memory`. Are there any downsides to this? And can we mix a binary compiled *without* `-fsanitize-recover=memory` with these libraries?

**Comment by eugenis** [comment]
Having just one module built with -fsanitize-recover=memory will flip the
default setting of halt_on_error in MSAN_OPTIONS to false, which will make
all reports in interceptors non-terminating. Even when the interceptor is
called from a module that is built w/o fsanitize-recover.

You can compensate for that by setting MSAN_OPTIONS=halt_on_error=true.

**Comment by oliverchang** [comment]
Progress update. MSan builds will now use static libraries available in [this list](https://github.com/google/oss-fuzz/blob/master/infra/base-images/msan-builder/Dockerfile#L32). Builds will also have their rpaths patched to use any instrumented dynamic libraries available too.

2 projects I looked at:

- libarchive. Many false positives closed, but [9](https://oss-fuzz.com/v2/testcases?job=libfuzzer_msan_libarchive&open=yes) reports remain open. These all seem related to lz4, so either it's not instrumented properly or these are legitimate reports.

- libpng had a libz dependency. https://oss-fuzz.com/v2/testcase-detail/5439055517974528 was closed after it started running with the instrumented libz.

**Comment by inferno-chromium** [comment]
Done!
