### ISSUE TITLE
cifuzz: make coverage reports work.

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#6089]
It seems like they don't work right now, because our coverage script is hardcoded to /corpus for corpora. 

Perhaps we should make this an env var (CORPUS_DIR), similar to OUT.

**Comment by oliverchang** [comment]
@jonathanmetzman assigning to you since I think you're working on getting coverage reports working. WDYT about adding a new env var for the corpus dir?

**Comment by jonathanmetzman** [comment]
sg. I'll fix this part now. It wasn't easy to figure out because I wasn't sure if corpus downloading failed because there was no corpus for my test projects or if it failed for this reason.
