### ISSUE TITLE
[apache-commons] Fuzzer runs locally, but crashes on ClusterFuzz

### ISSUE THREAD

**Issue by fmeum** [google/oss-fuzz#6097]
(https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33489)

The `ImagingJpegFuzzer` in `apache-commons` runs locally with `infra/helper.py run_fuzzer apache-commons ImagingJpegFuzzer`, but crashes on ClusterFuzz on startup due to not finding the `libXext.so.6` (see e.g. [this log](https://console.cloud.google.com/storage/browser/_details/apache-commons-logs.clusterfuzz-external.appspot.com/libFuzzer_apache-commons_ImagingJpegFuzzer/libfuzzer_asan_apache-commons/2021-08-02/04:50:07:098278.log), which despite the incorrect timestamp in the URL was created today). The library has been added to `base-runner` in https://github.com/google/oss-fuzz/pull/5644 and is installed in the standard location.

Does ClusterFuzz perhaps set the `LD_LIBRARY_PATH` differently?

**Comment by inferno-chromium** [comment]
> (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33489)
> 
> The `ImagingJpegFuzzer` in `apache-commons` runs locally with `infra/helper.py run_fuzzer apache-commons ImagingJpegFuzzer`, but crashes on ClusterFuzz on startup due to not finding the `libXext.so.6` (see e.g. [this log](https://console.cloud.google.com/storage/browser/_details/apache-commons-logs.clusterfuzz-external.appspot.com/libFuzzer_apache-commons_ImagingJpegFuzzer/libfuzzer_asan_apache-commons/2021-08-02/04:50:07:098278.log), which despite the incorrect timestamp in the URL was created today). The library has been added to `base-runner` in #5644 and is installed in the standard location.
> 
> Does ClusterFuzz perhaps set the `LD_LIBRARY_PATH` differently?

just putting the library in $OUT wont work, you need to patchelf it
see ex https://github.com/google/oss-fuzz/blob/30f3a8f1c0f5b072e77d5bea82709db04c53453d/projects/orbit/build.sh#L50

**Comment by fmeum** [comment]
> > (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33489)
> > The `ImagingJpegFuzzer` in `apache-commons` runs locally with `infra/helper.py run_fuzzer apache-commons ImagingJpegFuzzer`, but crashes on ClusterFuzz on startup due to not finding the `libXext.so.6` (see e.g. [this log](https://console.cloud.google.com/storage/browser/_details/apache-commons-logs.clusterfuzz-external.appspot.com/libFuzzer_apache-commons_ImagingJpegFuzzer/libfuzzer_asan_apache-commons/2021-08-02/04:50:07:098278.log), which despite the incorrect timestamp in the URL was created today). The library has been added to `base-runner` in #5644 and is installed in the standard location.
> > Does ClusterFuzz perhaps set the `LD_LIBRARY_PATH` differently?
> 
> just putting the library in $OUT wont work, you need to patchelf it
> see ex
> 
> https://github.com/google/oss-fuzz/blob/30f3a8f1c0f5b072e77d5bea82709db04c53453d/projects/orbit/build.sh#L50

In https://github.com/google/oss-fuzz/pull/5644/files#diff-7f64b2ea27491178c95700031d247407e97131de9f9f7851e9a2ed36a16cb0cfR95, the library isn't placed in `$OUT`, but installed as a system library via `apt`. Should that work in general or do I still have to copy it into out and patch it?

**Comment by inferno-chromium** [comment]
> > > (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33489)
> > > The `ImagingJpegFuzzer` in `apache-commons` runs locally with `infra/helper.py run_fuzzer apache-commons ImagingJpegFuzzer`, but crashes on ClusterFuzz on startup due to not finding the `libXext.so.6` (see e.g. [this log](https://console.cloud.google.com/storage/browser/_details/apache-commons-logs.clusterfuzz-external.appspot.com/libFuzzer_apache-commons_ImagingJpegFuzzer/libfuzzer_asan_apache-commons/2021-08-02/04:50:07:098278.log), which despite the incorrect timestamp in the URL was created today). The library has been added to `base-runner` in #5644 and is installed in the standard location.
> > > Does ClusterFuzz perhaps set the `LD_LIBRARY_PATH` differently?
> > 
> > 
> > just putting the library in $OUT wont work, you need to patchelf it
> > see ex
> > https://github.com/google/oss-fuzz/blob/30f3a8f1c0f5b072e77d5bea82709db04c53453d/projects/orbit/build.sh#L50
> 
> In https://github.com/google/oss-fuzz/pull/5644/files#diff-7f64b2ea27491178c95700031d247407e97131de9f9f7851e9a2ed36a16cb0cfR95, the library isn't placed in `$OUT`, but installed as a system library via `apt`. Should that work in general or do I still have to copy it into out and patch it?

copy and patch it, since https://google.github.io/oss-fuzz/further-reading/fuzzer-environment/

**Comment by fmeum** [comment]
I think that we may have arrived at a misunderstanding here, so let me summarize the situation in some more detail:

The docs at https://google.github.io/oss-fuzz/further-reading/fuzzer-environment/ end with the following remark:

> You should ensure that the fuzz target works correctly by using run_fuzzer command (see instructions here). This command uses a clean base-runner docker container and not the base-builder docker container created during build-time.

It is clear to me that fuzz targets cannot depend on any shared shared library installed either in `base-builder` or in the project-specific docker image based on `base-builder`. This is because fuzz targets are not executed in these images.

However, in this situation, the missing library is available in `base-runner` since https://github.com/google/oss-fuzz/pull/5644 and is also found when the fuzz target is run with `run_fuzzers`. The library is also not a direct dependency of the fuzz target itself, but rather a dynamic dependency of `/usr/lib/jvm/java-15-openjdk-amd64/lib/libawt_xawt.so`, which [is installed in `base-runner` as part of the OpenJDK](https://github.com/CodeIntelligenceTesting/oss-fuzz/blob/ddbe4a246582cccaf382c0ab339792be01fa38e7/infra/base-images/base-runner/Dockerfile#L87). The shared libraries in `/usr/lib/jvm/java-15-openjdk-amd64/lib/` also depend on other system libraries, such as `libc` and `libm`, which _are_ found.

@inferno-chromium Can you say whether OSS-Fuzz fuzz targets are actually executed by ClusterFuzz in the context of `gcr.io/oss-fuzz-base/base-runner` or, perhaps, on one of the `gcr.io/clusterfuzz-images/oss-fuzz/*` images defined in the ClusterFuzz repo? The latter would explain the issue we are seeing here as it does have the OpenJDK installed since https://github.com/google/clusterfuzz/commit/7493c075642aa204bdeb56e27d28bad5b033384e but lacks the equivalent of #5644.

**Comment by inferno-chromium** [comment]
> I think that we may have arrived at a misunderstanding here, so let me summarize the situation in some more detail:
> 
> The docs at https://google.github.io/oss-fuzz/further-reading/fuzzer-environment/ end with the following remark:
> 
> > You should ensure that the fuzz target works correctly by using run_fuzzer command (see instructions here). This command uses a clean base-runner docker container and not the base-builder docker container created during build-time.
> 
> It is clear to me that fuzz targets cannot depend on any shared shared library installed either in `base-builder` or in the project-specific docker image based on `base-builder`. This is because fuzz targets are not executed in these images.
> 
> However, in this situation, the missing library is available in `base-runner` since #5644 and is also found when the fuzz target is run with `run_fuzzers`. The library is also not a direct dependency of the fuzz target itself, but rather a dynamic dependency of `/usr/lib/jvm/java-15-openjdk-amd64/lib/libawt_xawt.so`, which [is installed in `base-runner` as part of the OpenJDK](https://github.com/CodeIntelligenceTesting/oss-fuzz/blob/ddbe4a246582cccaf382c0ab339792be01fa38e7/infra/base-images/base-runner/Dockerfile#L87). The shared libraries in `/usr/lib/jvm/java-15-openjdk-amd64/lib/` also depend on other system libraries, such as `libc` and `libm`, which _are_ found.
> 
> @inferno-chromium Can you say whether OSS-Fuzz fuzz targets are actually executed by ClusterFuzz in the context of `gcr.io/oss-fuzz-base/base-runner` or, perhaps, on one of the `gcr.io/clusterfuzz-images/oss-fuzz/*` images defined in the ClusterFuzz repo? The latter would explain the issue we are seeing here as it does have the OpenJDK installed since [google/clusterfuzz@7493c07](https://github.com/google/clusterfuzz/commit/7493c075642aa204bdeb56e27d28bad5b033384e) but lacks the equivalent of #5644.

Yes ClusterFuzz runs its own images and not gcr.io/oss-fuzz-base/base-runner
