### ISSUE TITLE
support honggfuzz

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#611]
@robertswiecki, when you have time, let's start from making the oss-fuzz builds support [honggfuzz](https://github.com/google/honggfuzz/) (in-process mode). Changes will need to go to this repo (see how libFuzzer/afl builds are done). 

Once this is done, we'll need to support running honggfuzz binaries on ClusterFuzz side. 
The more it looks like libFuzzer or afl, the simpler it will be. :)

**Comment by robertswiecki** [comment]
PR #636 has been tested with openssl and with sqlite3 and it seems to work nicely.

It should work closely to what afl does: i.e continuous running, with saving crashes to /tmp/honggfuzz_workdir

Tested with:

```
$ ./infra/helper.py build_fuzzers --engine honggfuzz openssl
...
$ ./infra/helper.py run_fuzzer --engine honggfuzz openssl x509
./infra/helper.py run_fuzzer --engine honggfuzz openssl x509
Running: docker run --rm -i --cap-add SYS_PTRACE -e FUZZING_ENGINE=honggfuzz -v /home/jagger/src/oss-fuzz/build/out/openssl:/out -t gcr.io/oss-fuzz-base/base-runner run_fuzzer x509
Using seed corpus: x509_seed_corpus.zip
/out/honggfuzz --linux_keep_aslr -W /tmp/honggfuzz_workdir -v -z -P -f "/tmp/input" -- "/out/x509"
PID: 12, inputDir '/tmp/input', nullifyStdio: true, fuzzStdin: false, saveUnique: true, flipRate: 0.001000, externalCommand: 'NULL', tmOut: 10, mutationsMax: 0, threadsMax: 4, fileExtn: 'fuzz', memoryLimit: 0x0(MiB), fuzzExe: '/out/x509', fuzzedPid: 0, monitorSIGABRT: 'true'
Entering phase 1/2: Dry Run
Launched new fuzzing thread, no. #0
Launched new fuzzing thread, no. #1
Launched new fuzzing thread, no. #2
Launched new fuzzing thread, no. #3
Persistent mode: Launched new persistent PID: 17
Persistent mode: Launched new persistent PID: 18
Persistent mode: Launched new persistent PID: 19
Persistent mode: Launched new persistent PID: 20
NEW, size:176 (i,b,sw,hw,cmp): 0/0/1976/0/25150, Tot:0/0/1976/0/25150
NEW, size:1936 (i,b,sw,hw,cmp): 0/0/1354/0/16079, Tot:0/0/3330/0/41229
NEW, size:97 (i,b,sw,hw,cmp): 0/0/118/0/859, Tot:0/0/3448/0/42088
NEW, size:148 (i,b,sw,hw,cmp): 0/0/37/0/315, Tot:0/0/3485/0/42403
NEW, size:1782 (i,b,sw,hw,cmp): 0/0/73/0/653, Tot:0/0/3558/0/43056
NEW, size:71 (i,b,sw,hw,cmp): 0/0/14/0/101, Tot:0/0/3572/0/43157
NEW, size:65 (i,b,sw,hw,cmp): 0/0/52/0/254, Tot:0/0/3624/0/43411
...
```

**Comment by Dor1s** [comment]
Friendly ping :) Are there any plans to finish the integration? Looks like we've caused some [confusion](https://twitter.com/AdamOfDc949/status/1093917136039395328) by saying [this](https://github.com/google/oss-fuzz/blob/b05d5d8b269b3152b35f2a3c0e8678d4831c748b/docs/faq.md#does-oss-fuzz-support-honggfuzz) and [this](http://honggfuzz.com/#projects-utilizing-honggfuzz).

**Comment by alex** [comment]
It was working, at least locally, as of #1370.

**Comment by Dor1s** [comment]
Yeah, but IIRC there is still some work that needs to be done on ClusterFuzz side to make sure honggfuzz gets leveraged as much as possible.

**Comment by jonathanmetzman** [comment]
Right. While technically OSS-Fuzz the project supports honggfuzz, the service does not.

**Comment by robertswiecki** [comment]
I've given it a try to add support of honggfuzz to the clusterfuzz, but dropped the idea after some initial testing. The reason is that clusterfuzz configuration of fuzzing enginees is, in my opinion, too complex, as in it requires writting and maintaining a non-trivial driver.

From a high-level perspective configuration for a fuzzing engine could be a simple config file, specifying the command-line and maybe one or two other options (like, where to find outut artifacts, dict files etc.) Because, in my opinion, that's all that differentiates all fuzzing engines, at least I know of projects which made it this way, and it works great for them.

Would refactoring the fuzzing-enging-config in the clusterfuzz be possible before we add support for other fuzzers?

**Comment by oliverchang** [comment]
> Would refactoring the fuzzing-enging-config in the clusterfuzz be possible before we add support for other fuzzers?

Yes, hopefully in the coming months :) It's definitely true that adding fuzzing engines is too difficult right now.

**Comment by robertswiecki** [comment]
Sounds good :). Feel free to ping me once it has been done, and I'll get back to it!

**Comment by Dor1s** [comment]
Thanks @oliverchang !
