### ISSUE TITLE
FUZZING_LANGUAGE: unbound variable error while starting a container 

### ISSUE THREAD

**Issue by SivaKesava1** [google/oss-fuzz#6115]
Hello,

I wanted to try the Bind project [locally](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally). 

I followed these steps on my host machine:
```
1. git clone https://github.com/google/oss-fuzz.git
2. cd oss-fuzz
3. python infra/helper.py build_image bind9
```

After the last command, the `gcr.io/oss-fuzz/bind9` Docker image is created locally. 
If I run `python infra/helper.py build_fuzzers --sanitizer={'address','memory','undefined'} bind9`, then binaries appear in the `oss-fuzz/build/out/bind9` directory on my host machine. But, I don't want to run the fuzzer on my host machine directly but inside the container. 

If I try to run [` sudo docker run --rm -ti gcr.io/oss-fuzz/bind9 compile`](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/README.md#supported-commands) to start a container with the fuzz targets built inside the container, I get the error:
```
---------------------------------------------------------------
/usr/local/bin/compile: line 25: FUZZING_LANGUAGE: unbound variable
``` 

How to use the built Bind9 Docker image and not run things directly on the host machine? 
I tried starting a container directly (entrypoint=bash) and run the `./build.sh` script available in the `$SRC,` but I guess that is not the right way to build the fuzz targets inside a container. (I hope I didn't misunderstand something from the README, and excuse me if it's a silly question). 

Thanks for the help.

**Comment by DavidKorczynski** [comment]
You should be able to use the following steps:
```
python infra/helper.py build_fuzzers bind9
python infra/helper.py run_fuzzer bind9 FUZZER_NAME
```
Substitute the FUZZER_NAME for the name of the fuzzer you want to run. You can find the names of these in `build/out/bind9`

**Comment by SivaKesava1** [comment]
Thanks, David. 

When I tried initially, I got the error `does not seem to be compiled with ASan`, but I was able to run successfully after passing `--sanitizer address.` Then `python infra/helper.py check_build  bind9` went through. The `build/out/bind9` directory has the fuzzer and seed corpus zip. 

If I run `python infra/helper.py run_fuzzer --corpus-dir=build/work/bind9/ bind9 dns_name_fromtext_target_fuzzer`  then I see the fuzzer working and populating the `build/work/bind9/` directory with raw inputs.  Does the fuzzer generate any report when it finishes? How to know if there was a crash? (I am trying to understand how to interpret a run, thank you for your quick replies.)

**Comment by DavidKorczynski** [comment]
> Does the fuzzer generate any report when it finishes? 

Not really. Fuzzing doesn't really "finish" as such, but you can generate a coverage report to visualise what parts of the code the corpus reaches, and other than that the report you get as an oss-fuzz maintainer is what clusterfuzz shows you.

> How to know if there was a crash? (I am trying to understand how to interpret a run, thank you for your quick replies.)

The crash will be shown similarly to how the fuzzer shows it.

**Comment by SivaKesava1** [comment]
Makes sense, thanks. 

From the documentation, I see that the coverage and visualization are limited to the bind9 developers. The coverage generation requires `gcloud` authentication, and I am not part of the bind9 developers' team.

As an outsider, if I run the `python infra/helper.py run_fuzzer --corpus-dir=build/work/bind9/ bind9 dns_name_fromtext_target_fuzzer` locally on my machine, I understand that I will not be using the [`Clusterfuzz`](https://github.com/google/oss-fuzz#overview) infrastructure, but I guess I will still be able to see if there is a crash locally, isn't it?  I am trying to add a new fuzz target but not send a pull request initially to the Bind9 repository to merge (takes time for them to review and merge), so I am curious about how things will be if run on my local machine.

**Comment by DavidKorczynski** [comment]
Yes @SivaKesava1 you will be able to run fuzzers locally and see crashes. If you are curious about these things then you could set up a project with an error and observe the outcome.

@SivaKesava1 we don't have cycles to go through basic usage like this. Local fuzzing is documented here https://google.github.io/oss-fuzz/getting-started/new-project-guide/#fuzzer-execution-environment
