### ISSUE TITLE
Add a commit fix link to the clusterfuzz report

### ISSUE THREAD

**Issue by asarubbo** [google/oss-fuzz#612]
Hello,

I tried to make some downstream report of the issues found.

However all maintainers have difficulty, because of lack of information. I'm wondering if clusterfuzz, after detect the range when the issue is fixed, can identify the commit fix.

Alternatively, would be great if the maintainer can clearly state which commit fixes the issue.

Thanks in advance.

**Comment by kcc** [comment]
Providing the exact revision of the fix would be nice indeed, but it's far from trivial.
See also https://github.com/google/oss-fuzz/issues/334 and https://github.com/google/oss-fuzz/issues/369

**Comment by asarubbo** [comment]
> Providing the exact revision of the fix would be nice indeed, but it's far from trivial.

I understand. I don't know how clusterfuzz operates, but could it, for example, make a bisect from the range it has already identified?

Alternatively, you should force the maintainer to mention oss-fuzz in the commit message (as you stated in #369), that would help too, but from some reports I saw, there was no mention about oss-fuzz in the range where CF detected the bug as fixed...

**Comment by kcc** [comment]
bisection is not trivial because in general case we don't know the revision control system, etc,
or there could be several revision systems involved.
We may probably have a special case for projects that have a single 'git clone' command in the dockerfile. 

> you should force the maintainer 
'force' doesn't work in open source. We can only 'encourage'

**Comment by oliverchang** [comment]
Closing in favour of existing bugs (#334, #369, and #616)
