### ISSUE TITLE
[CIFuzz] extend helper.py support for external users.

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#6125]
People trying out CIFuzz will need to be able to test things locally. Our `helper.py` script works well for OSS-Fuzz users, but we should see if we can easily extend this to work for external users too.

**Comment by jonathanmetzman** [comment]
I was sort of envisioning having a separate repo for CIFuzz.
In that case, it wouldn't be worth modifying helper.py. WDYT?

**Comment by oliverchang** [comment]
> I was sort of envisioning having a separate repo for CIFuzz.
> In that case, it wouldn't be worth modifying helper.py. WDYT?

I think it's still beneficial to share what we can and avoid duplication. We can still pull in helper.py or parts of it for the CIFuzz repo.

**Comment by jonathanmetzman** [comment]
This should be essentially done.
