### ISSUE TITLE
encourage users to mention their fixes in monorail reports

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#616]
(counterpart of https://github.com/google/oss-fuzz/issues/369)
I'd like to see more users mention their fixes in the monorail reports (see what the GDAL maintainer does, for example). 
Can we add something like this to the bottom of the (new) bug reports?

```
When you fix this bug, please 
  * mention the fix revision(s)
  * state whether the bug was a short-lived regression or an old bug
  * add any other worthy comment. 
```

**Comment by oliverchang** [comment]
This is done.
