### ISSUE TITLE
Upgrade Ubuntu version

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#6180]
We need to do this eventually. I don't want to do it after ClusterFuzzLite launches because I don't want to break people so soon after releasing a project. Delaying this only makes the problem worse.

So far, I've tested a few major projects/configurations. I tested each sanitizer, each engine, each architecture, and each language. It seems like only the swift projects are breaking.
We expect some MSAN users to break also.

**Comment by jonathanmetzman** [comment]
We'll also need to coordinate this with ClusterFuzz and FuzzBench.
ClusterFuzz has seperate docker images that OSS-Fuzz images must run on.
FuzzBench depends on OSS-Fuzz images.

**Comment by oliverchang** [comment]
+1. We can make migration a little easier if the downstream consumers (ClusterFuzz + FuzzBench) if we upload a 16.04 tag and have those depend on that first.

**Comment by oliverchang** [comment]
This is done
