### ISSUE TITLE
pass dictionary autumatically, w/o requering the .options file

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#619]
Right now we require that the .options file specifies how to pass the dictionary. 
I'd like to also have oss-fuzz automatically pass the dictionary (to both libFuzzer, and AFL)
if there is a file called e.g. `fuzz_target_name_dict.txt`. 
This may increase the dictionary usage somewhat due to simpler setup.

**Comment by Dor1s** [comment]
I think we should also look for `%fuzz_target_name%.dict` files

**Comment by inferno-chromium** [comment]
I actually like the %fuzz_target_name%.dict convention over fuzz_target_name_dict.txt, but overall, this should be simpler to implement and then docs should be updated as well.

**Comment by oliverchang** [comment]
yeah +1 to *.dict

**Comment by kcc** [comment]
No objections to `%fuzz_target_name%.dict`

**Comment by oliverchang** [comment]
This is done on the infrastructure side, will update the docs.

**Comment by kcc** [comment]
please also update the 'example' project (remove .options, add a line to README, etc)

**Comment by oliverchang** [comment]
OK, done (https://github.com/google/oss-fuzz/commit/803075bc3a87b2aaf238e97757b77b3cb26b02a4 and https://github.com/google/oss-fuzz/commit/7d454b344cff0888ea4c1b56c2080e2aebddd74c).

Also made this work with our helper run_fuzzer command.
