### ISSUE TITLE
libssl-dev version >= 1.1.0

### ISSUE THREAD

**Issue by tstruk** [google/oss-fuzz#6194]
Hi,
The TSS build is failing [1] as it requires openssl to be >=1.1.0
The default version from gcr.io/oss-fuzz-base/base-builder doesn't meet this requirement.
Is the any way to install new version via Docker file other than building it from source?

[1] https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36849#c1

**Comment by jonathanmetzman** [comment]
If you could find a binary like from a PPA that would also work.
Or you could wait for #6180 since we hope to upgrade the Ubuntu version to 20.04 this month.

**Comment by tstruk** [comment]
Ok, created a new PR for this. https://github.com/google/oss-fuzz/pull/6203
It can be reverted after the upgrade.

**Comment by DavidKorczynski** [comment]
@tstruk the base image is now Ubuntu 20.04:

https://github.com/google/oss-fuzz/blob/d88421483f251db9db31c7f495ab8175d811c094/infra/base-images/base-image/Dockerfile#L19

Will close this issue as https://github.com/google/oss-fuzz/pull/6203 was also closed. Let us know if there are any more libssl issues.
