### ISSUE TITLE
documentation is confusing regarding reproducibility of runtime environment

### ISSUE THREAD

**Issue by Pamplemousse** [google/oss-fuzz#6215]
Documentation seems contradictory:

["Runtime Dependencies"](https://github.com/google/oss-fuzz/blob/d0c9f6f4a7c8678c4a1b33c9df0c468cb434be5d/docs/further-reading/fuzzer_environment.md#L21-L26) section states:
> You should not make any assumptions on the availability of dependent packages in the execution environment. Packages that are installed via Dockerfile or built as part of build.sh are not available on the bot runtime environment (where the fuzz targets run).

["Why do you use Docker"](https://github.com/google/oss-fuzz/blob/d0c9f6f4a7c8678c4a1b33c9df0c468cb434be5d/docs/faq.md#L80-L86) in the FAQ states:
> This also simplifies our support for a variety of Linux distributions and provides a reproducible and secure environment for fuzzer building and execution.
[...]
All build artifacts needed during fuzz target execution should be inside the $OUT directory. Only those artifacts are archived and used on the bots. Everything else is ignored (e.g. artifacts in $WORK, $SRC, etc) and hence is not available in the execution environment.

It seems that the claim "provides a reproducible environment for fuzzer execution" is false...

**Comment by jonathanmetzman** [comment]
Why do you think it's false?
The only thing I see that can be interpreted as contradictory is "You should not make any assumptions on the availability of dependent packages in the execution environment". The only exception to this is the packages you put in $OUT.

**Comment by Pamplemousse** [comment]
Pretty often, Docker brings "reproducibility" as in "build once, run everywhere".

Here, it seems to only mean "we conveniently gathered the tools necessary for building in a single place (image)".

From the runtime perspective, Docker does not seem to bring anything more than any environment;
AFAICT, I by copying `$OUT` on any linux x64_86, it should have the fuzzer working.

**Comment by jonathanmetzman** [comment]
I'm still not sure what isn't reproducible here. Could you spell it out more explicitly please?

>From the runtime perspective, Docker does not seem to bring anything more than any environment;
>AFAICT, by copying $OUT on any linux x64_86, it should have the fuzzer working.

Do you mean that bugs should be reproducible on other linux environments?
I personally repro bugs on my host frequently, but sometimes there are differences that make things better to do in the runner image.
For example, one time I think there was a bug caused by the fuzzer's interactions with system fonts. This bug behaved differently on the runner image than on my host.

**Comment by MarcoFalke** [comment]
Is there still an issue to be fixed here?

**Comment by jonathanmetzman** [comment]
I don't think so.
I don't think I agree there is anything that isn't "reproducible".
