### ISSUE TITLE
serenity: Working around code generators

### ISSUE THREAD

**Issue by ADKaster** [google/oss-fuzz#6235]
The SerenityOS LibUnicode library optionally uses a large set of generated tables and maps to do transcoding and codepoint categorization. The tables have a bunch of helper functions associated with them as well, so the generated cpp file is not just a set of arrays/maps in the data segment.

The code generator for these tables lives in the same CMake project() as the build for all the libraries that end up getting fuzzed in the set of fuzzer binaries we create when -DOSS_FUZZ=ON (or -DENABLE_FUZZER_SANITIZER=ON) is set. So, we can't build the code generator when the fuzzing engine is passed in LDFLAGS because it will cause a link error.

Without the tables, the Unicode library just assumes everything is ASCII and goes on its merry way, which has negative impacts on fuzzers for other libraries, such as FuzzJS, which makes heavy use of Unicode categories in the JavaScript parser.

As I outlined in the [SerenityOS issue](https://github.com/SerenityOS/serenity/issues/9466) for this, one option would be build the project twice, once for the code generator and again for the actual fuzzers, making sure to pass the right CMake magic for the fuzzer build to find an imported target for the code generator binary.

Is there a better way to do this?  Are there examples of other projects that have in-source code generators in oss-fuzz?

**Comment by DavidKorczynski** [comment]
I think this is more of a Serenity issue than an OSS-Fuzz issue. 

There are other projects that use in-source code generators, e.g. protobuf is perhaps the most frequently used. Envoy does this. 

You can build the project twice as you have full control of the build procedure: https://github.com/google/oss-fuzz/blob/master/projects/serenity/build.sh but in my mind the right solution seems to be ensuring that wrong flags are not used during linking (remove `-fsanitize=fuzzer` but not `-fsanitize=fuzzer-no-link` from the link flags) of a fuzz build and then only building once.

**Comment by DavidKorczynski** [comment]
Will close this one as it is a serenity issue at the core as described above - please open again if you have more queries.
