### ISSUE TITLE
add suricata

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#624]
@chifflier and I were talking about adding suricata to oss-fuzz. 
Let's do it!

**Comment by chifflier** [comment]
@kcc : as discussed, I think it would be interesting to add suricata. Can you give me some pointers on how to set this up?

**Comment by inferno-chromium** [comment]
@chifflier - please see https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md

**Comment by kcc** [comment]
Also, take a look at the existing projects in https://github.com/google/oss-fuzz/blob/master/projects/
E.g. wireshark or botan.
There is also a synthetic example here: 
https://github.com/google/oss-fuzz/tree/master/projects/example
https://github.com/google/oss-fuzz/tree/master/projects/example/my-api-repo

**Comment by kcc** [comment]
@chifflier do you need any help here?

**Comment by Dor1s** [comment]
@chifflier ping :)

**Comment by inferno-chromium** [comment]
Closing due to lack of interest. @chifflier - it will be great if you can integrate into oss-fuzz.
