### ISSUE TITLE
Restricted access to the libcxxabi demangler bugs

### ISSUE THREAD

**Issue by epilk** [google/oss-fuzz#626]
Hi,
I just got added to the CC list for the libcxxabi demangler. Would it be possible for me to get access to the detailed information for these restricted bugs? Otherwise CCing me is pointless. For example, I can't get my hands on the testcase for this: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1715#c2
Thanks,
Erik

**Comment by kcc** [comment]
weird. if you are logged in into this gmail account you should be able to see everything. 
What do you see when you try to access oss-fuzz.com ?

**Comment by epilk** [comment]
No go! I get the following:
You (email=Erik.Pilkington@gmail.com) are not authorized to access this page!

It might be that cases-sensitivity is being handed incorrectly? In the project.yaml file my email is erik.pilkington@gmail.com.

**Comment by inferno-chromium** [comment]
@epilk - ok i updated your email in project.yaml, can you try logging in again.

**Comment by epilk** [comment]
That did the trick. Thanks!
