### ISSUE TITLE
`/usr/bin/ld` cannot find some installed libraries

### ISSUE THREAD

**Issue by Pamplemousse** [google/oss-fuzz#6264]
When trying to use the `Docker` image to build fuzzers for [`nix`](github.com/nixos/nix/), `python infra/helper.py build_fuzzers --sanitizer address nix` produces the following error:

```
/usr/bin/ld: cannot find -lgssapi_krb5
/usr/bin/ld: cannot find -lkrb5
/usr/bin/ld: cannot find -lk5crypto
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

Now, the problem is that I do not understand **WHY** this error is triggered:
1. `libkrb5-dev` is installed;
2. Libraries files are present on the filesystem;
```
docker run --rm -it gcr.io/oss-fuzz/nix:latest /bin/bash -c "find /usr/lib/ -name '*krb5*.so'"
/usr/lib/x86_64-linux-gnu/libkrb5.so
/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so
/usr/lib/x86_64-linux-gnu/mit-krb5/libkrb5.so
/usr/lib/x86_64-linux-gnu/mit-krb5/libgssapi_krb5.so
/usr/lib/x86_64-linux-gnu/mit-krb5/libkrb5support.so
/usr/lib/x86_64-linux-gnu/libkrb5support.so
```
3. The right path is added with `-L` in the `ld` executed command; See (copied from a compilation try with `-v`):

```
"/usr/bin/ld" -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -static -o fuzz/parse_store_path
/usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/crti.o
/usr/lib/gcc/x86_64-linux-gnu/10/crtbeginT.o -Lsrc/libstore -L/usr/lib/x86_64-linux-gnu/mit-krb5 
-Lsrc/libutil -L/usr/lib/x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/10
-L/usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu -L/lib/x86_64-linux-gnu
-L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/10/../../..
-L/usr/local/bin/../lib -L/lib -L/usr/lib --whole-archive
/usr/local/lib/clang/12.0.0/lib/linux/libclang_rt.fuzzer-x86_64.a --no-whole-archive
--whole-archive /usr/local/lib/clang/12.0.0/lib/linux/libclang_rt.fuzzer_interceptors-x86_64.a
--no-whole-archive -lstdc++ --whole-archive /usr/local/lib/clang/12.0.0/lib/linux
/libclang_rt.ubsan_standalone-x86_64.a --no-whole-archive --dynamic-list=/usr/local/lib/clang/12.0.0
/lib/linux/libclang_rt.ubsan_standalone-x86_64.a.syms --whole-archive /usr/local/lib/clang/12.0.0
/lib/linux/libclang_rt.ubsan_standalone_cxx-x86_64.a --no-whole-archive --dynamic-list=/usr/local
/lib/clang/12.0.0/lib/linux/libclang_rt.ubsan_standalone_cxx-x86_64.a.syms
/tmp/target_parse_store_path-417c43.o -lnixstore src/libstore/libnixstore.a -lsqlite3 -lm -ldl -lz 
-lpthread -lcurl -lnghttp2 -lidn2 -lrtmp -lssh -lpsl -lssl -lcrypto -lssl -lcrypto -Bsymbolic-functions 
-z relro -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -llber -lldap -llber -lbrotlidec -lz -lsodium -ldl 
-lseccomp -lnixutil src/libutil/libnixutil.a -lcrypto -ldl -lbrotlienc -lbrotlidec -lbrotlicommon 
-larchive -lnettle -lacl -llzma -lzstd -llz4 -lbz2 -lz -lxml2 -lz -lboost_context -lcpuid -lstdc++ -lm 
--start-group --no-as-needed -lpthread -lrt -lm -ldl -lgcc -lgcc_eh -lpthread -lc --end-group /usr/lib
/gcc/x86_64-linux-gnu/10/crtend.o /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/crtn.o
```

Any idea what I am missing?

**Comment by Pamplemousse** [comment]
And here is the current state of the integration:
https://github.com/Pamplemousse/oss-fuzz/blob/33bff5a4e47c77c1cf7fd5e686652da144be10dd/projects/nix/ .

**Comment by DavidKorczynski** [comment]
Your linker has `-static` set, but the libraries you show are `.so` files. Are the `.a` files present? 

It might be easier to debug this if you use the `shell` command.

`python3 infra/helper.py shell nix` will give you a shell in the Docker container. You can then either run `compile` to execute the compile script used by OSS-Fuzz (https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile) or set the environment variables (CC, CXX, CFLAGS, CXXFLAGS, LIB_FUZZING_ENGINE) yourself. This might make it easier.

**Comment by Pamplemousse** [comment]
Ah, I kinda believed that static linking would work with `.so` files too... :facepalm:
Indeed, no statically library in sight; I wonder why the package does not have them...

Also, thanks for the debugging tip!

**Comment by DavidKorczynski** [comment]
All good! 

Perhaps the best approach is to compile them from scratch in your setup. Alternatively it looks like you link to a lot of libraries - are all those libraries really needed? It might be that you could discard some of them if your fuzzer(s) target sub-sets of the code. 

In either case, let's close this issue as it seem resolved?
