### ISSUE TITLE
Support for LLVM 13 fuzzing

### ISSUE THREAD

**Issue by alexcrichton** [google/oss-fuzz#6268]
I got a notification that the flate2 project's coverage build [is failing](https://oss-fuzz-build-logs.storage.googleapis.com/log-1ef4e2ba-e147-44f4-978b-3245ec2c068e.txt) and has the error message:

```
Step #5: warning: /workspace/out/coverage/dumps/fuzz_gz_roundtrip.16218861006045500770_0.profraw: Unsupported instrumentation profile format version
Step #5: error: No profiles could be merged.
```

AFAIK nothing about flate2 itself has changed, but the most recent change I can think of is that the Rust compiler upgraded to LLVM 13 over the weekend. I suspect that the new LLVM version may have updated something about coverage instrumentation?

**Comment by alexcrichton** [comment]
Also we're seeing a [different failure in `wasmtime`'s normal fuzz builds](https://oss-fuzz-build-logs.storage.googleapis.com/log-28ab3b14-c8d1-4827-ab71-7f5d4c96bf0e.txt) which I believe is mixing C/Rust so I think that there's possibly another incompatibility with LLVM 13, which Rust is using, and the system C compiler perhaps?

**Comment by DavidKorczynski** [comment]
Can confirm Rust issues - I get build failures on many (all projects I am CCed on) Rust projects.

**Comment by alexcrichton** [comment]
I'm attempting to pin the Rust toolchain to a pre-LLVM-13 version in https://github.com/google/oss-fuzz/pull/6288 as a temporary fix for now.

**Comment by MarcoFalke** [comment]
Is this still an issue?

**Comment by catenacyber** [comment]
@jonathanmetzman this is still an issue after rolling out clang 14

Reverting to clang13 makes suricata and rustls coverage builds succeed :

Patch is
```
diff --git a/infra/base-images/base-clang/checkout_build_install_llvm.sh b/infra/base-images/base-clang/checkout_build_install_llvm.sh
index a62b27cf..b4c00ad9 100755
--- a/infra/base-images/base-clang/checkout_build_install_llvm.sh
+++ b/infra/base-images/base-clang/checkout_build_install_llvm.sh
@@ -70,11 +70,11 @@ cd clang
 LLVM_SRC=$SRC/llvm-project
 
 # For manual bumping.
-OUR_LLVM_REVISION=llvmorg-12-init-17251-g6de48655
+OUR_LLVM_REVISION=llvmorg-13.0.0-rc1-gd6974c010878
 
 # To allow for manual downgrades. Set to 0 to use Chrome's clang version (i.e.
 # *not* force a manual downgrade). Set to 1 to force a manual downgrade.
-FORCE_OUR_REVISION=0
+FORCE_OUR_REVISION=1
 LLVM_REVISION=$(grep -Po "CLANG_REVISION = '\K([^']+)" scripts/update.py)
 
 clone_with_retries https://github.com/llvm/llvm-project.git $LLVM_SRC
```

Test is
```
python3 infra/helper.py build_image --no-pull base-builder
python3 infra/helper.py build_image --no-pull base-builder-rust
python3 infra/helper.py build_image --no-pull base-runner
python3 infra/helper.py build_image --no-pull suricata
python infra/helper.py build_fuzzers --sanitizer coverage suricata
python infra/helper.py coverage --no-corpus-download suricata
```

Right now, without this patch, we get `malformed instrumentation profile data` errors
Before rolling clang-14 we had ` Unsupported instrumentation profile format version` (because rust compiler used clang13 profile format)

Before : https://oss-fuzz-build-logs.storage.googleapis.com/log-3022ca9e-fbae-44d7-ac43-1214b857004b.txt
After : https://oss-fuzz-build-logs.storage.googleapis.com/log-b7dd2a93-58b6-47d2-88ef-7e0c2ffb7bd9.txt

Should we revert to clang 13 ? Only for rust projects ?

**Comment by catenacyber** [comment]
`llvmorg-14-init`+ cherry-pick of `a6c14fba70e170a279f7e77f068368f09d8c5eaf` seems good to me

**Comment by catenacyber** [comment]
I found the culprit commit in llvm : https://reviews.llvm.org/D104556
