### ISSUE TITLE
base-builder-swift isn't building

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#6269]
If you look at https://console.cloud.google.com/gcr/images/oss-fuzz-base/GLOBAL/base-builder-swift you can see it was last built on June 30th (I think it was done manually and pushed).
@asraa @oliverchang maybe we forgot to deploy changes to infra/build/functions

**Comment by asraa** [comment]
Oh, I added it here https://github.com/google/oss-fuzz/blob/30d927e324f3909ce7a9a9823219fcd8cb185150/infra/build/functions/base_images.py#L29

But I think it has to be in here too https://github.com/google/oss-fuzz/blob/30d927e324f3909ce7a9a9823219fcd8cb185150/infra/ci/build.py#L215

**Comment by inferno-chromium** [comment]
> If you look at https://console.cloud.google.com/gcr/images/oss-fuzz-base/GLOBAL/base-builder-swift you can see it was last built on June 30th (I think it was done manually and pushed).
> @asraa @oliverchang maybe we forgot to deploy changes to infra/build/functions

i deployed now.

fyi.
cd infra/build/functions
./deploy oss-fuzz
for future
