### ISSUE TITLE
Add mercurial vcs coverage?

### ISSUE THREAD

**Issue by mkj** [google/oss-fuzz#628]
Would it be possible to add mercurial (hgweb) as a VCS for code coverage? Dropbear's using it.
I see NSS is using mercurial too, though appears to be using a port of gitweb not hgweb.

https://oss-fuzz.com/coverage_report/fuzzer/libFuzzer_dropbear_fuzzer-pubkey/2017-05-24/f/%2Fsrc%2Fdropbear%2Fdbrandom.c
`Couldn't load file content {"vcs_url":"https://secure.ucc.asn.au/hg/dropbear","path":"/dbrandom.c"}: 404`

**Comment by oliverchang** [comment]
This is working now. Please see e.g. https://oss-fuzz.com/coverage_report/job/libfuzzer_asan_dropbear/latest/f/%2Fsrc%2Fdropbear%2Fbuffer.c

Let us know if something is still broken here.

**Comment by mkj** [comment]
Thanks @oliverchang , works well.

**Comment by mkj** [comment]
Can you take another look at this, it seems to be picking up files from the default hg branch, not the relevant revision in the fuzz branch that's being fuzzed.

Compare https://oss-fuzz.com/coverage_report/fuzzer/libFuzzer_dropbear_fuzzer-preauth/2017-06-11/f/%2Fsrc%2Fdropbear%2Fsvr-session.c (head) versus https://secure.ucc.asn.au/hg/dropbear/file/f0990c284663/svr-session.c (fuzz branch), search for "fuzz" to see changes.

The coverage_report page is picking up the correct revision in the params json.
`"/src/dropbear": {"url": "https://secure.ucc.asn.au/hg/dropbear", "rev": "f0990c2846632d2d7dd018a0e53c736cca7db65e", "type": "hg"}`
