### ISSUE TITLE
Dead link in "Fuzzer environment" documentation

### ISSUE THREAD

**Issue by Pamplemousse** [google/oss-fuzz#6284]
> Your fuzz targets will be run on a Google Compute Engine VM (Linux) with some security restrictions.

The "security restrictions" link points to a file that is not in the repository anymore.
https://github.com/google/oss-fuzz/blob/master/docs/further-reading/fuzzer_environment.md?plain=1#L13

**Comment by DavidKorczynski** [comment]
The documentation is now removed since it was deprecated.
