### ISSUE TITLE
Need to move off clang 12, need AFL++ to work with clang 13

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#6297]

**Comment by inferno-chromium** [comment]
We downgraded to Clang 12 due to https://github.com/google/oss-fuzz/pull/5131

@vanhauser-thc - does afl++ work with clang 13 ? we want to ideally switch back to llvm trunk in the next 2-3 weeks.

**Comment by vanhauser-thc** [comment]
To my knowledge it does

**Comment by inferno-chromium** [comment]
> To my knowledge it does

Thanks.

@jonathanmetzman - will keep in your queue to roll forward in next couple of week after ubuntu 20.04 fires are out.

**Comment by MarcoFalke** [comment]
Anything left to do here?

**Comment by vanhauser-thc** [comment]
dont think so as it is now on clang-14 right?

**Comment by inferno-chromium** [comment]
yes we moved to clang 14 now.
