### ISSUE TITLE
[pidgin] deadline extension

### ISSUE THREAD

**Issue by grimmy** [google/oss-fuzz#6374]
Could we (Pidgin) please have an extension to our deadline of September 6th for the 12 issues listed below?  We are planning a release for September 16th that should address all of these. I had intended to get to them sooner, but the past 90 days just flew by.

As part of this we'll also be moving the fuzzers to our repository (some of that was already started) and updating the oss-fuzz project to reflect that. Is there anything we'll need to do about the existing corpus? I'm asking because the fuzzers will be changing a bit. Originally when this was setup the fuzzers were calling multiple functions in the same namespace and I was leaning towards a fuzzer per function. I haven't been able to find any documentation that says a fuzzer should test one function or many functions, so any guidance here would be appreciated.

The issues needing an extension are as follows:
 * 34988
 * 34993
 * 34994
 * 34996
 * 34997
 * 34999
 * 35009
 * 35015
 * 35029
 * 35031
 * 35816
 * 36270

**Comment by inferno-chromium** [comment]
Done!
