### ISSUE TITLE
Cannot assign issues for the spirv-tools project

### ISSUE THREAD

**Issue by afd** [google/oss-fuzz#6378]
The spirv-tools fuzz targets are finding various issues. As I'm on the CC list I can view and comment on these issues. However, I cannot assign them. Is there an extra step that I need to take to have permissions to reassign these issues?

**Comment by jonathanmetzman** [comment]
Usually OSS-Fuzz contributors don't have this ability.
I've given it to you. Please try again and let me know if it doesn't work. 
Also, please don't remove labels as this may mess up ClusterFuzz.
