### ISSUE TITLE
[syzkaller] Coverage build failure

### ISSUE THREAD

**Issue by a-nogikh** [google/oss-fuzz#6379]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37974

[Syzkaller](https://github.com/google/syzkaller) builds began to fail without changes from syzkaller's side that might've triggered that.

Could you please hint at where the problem might be?

**Comment by jonathanmetzman** [comment]
I think this was an issue in our infra that was fixed. The issue should close automatically now.

**Comment by jonathanmetzman** [comment]
Latest syzkaller build passes.
