### ISSUE TITLE
Outdated i386 builds

### ISSUE THREAD

**Issue by nikic** [google/oss-fuzz#6382]
I recently received a couple reports of libfuzzer_asan_i386_php failures that have already been fixed, https://oss-fuzz.com/testcase-detail/4777065514139648 being an example. The "Build" link indicates that the build is from 2021-08-26-06:03.

https://oss-fuzz-build-logs.storage.googleapis.com/index.html#php doesn't indicate any recent build failures, so I'm wondering whether i386 builds somehow got stuck? This doesn't seem to affect other fuzzers.

**Comment by jonathanmetzman** [comment]
Ouch it looks like I broke uploading of i386 builds. They've been overwriting the x86_64 builds since August 28th.

**Comment by oliverchang** [comment]
Reopening to track moving the builds that were incorrectly uploaded to the x86-64 bucket back to the i386 bucket.

**Comment by oliverchang** [comment]
I've moved all affected builds and fixed up all affected testcases.

**Comment by jonathanmetzman** [comment]
Thanks Oliver!
