### ISSUE TITLE
start using a pinned revision of LLVM instead of current trunk

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#639]
We have recently seen a number of false positives caused by a short lived miscompile in llvm. 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1933
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1940
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1952
likely a few others. 

Probably it's time to start pinning the LLVM revision instead of using the fresh trunk. 
We could probably piggyback on the Chrome's released LLVM.

**Comment by oliverchang** [comment]
Using Chrome's version SGTM.

Would #526 have caught this also?

**Comment by kcc** [comment]
> Would #526 have caught this also?

Depending on what do you mean by "run tests".
If that 'run llvm tests' -- probably no, apparently the LLVM tests were green (not 100% sure)
