### ISSUE TITLE
Can't access testcase-detail 

### ISSUE THREAD

**Issue by graygnuorg** [google/oss-fuzz#6393]
When trying to access the detailed report at https://oss-fuzz.com/testcase?key=5683615552372736 I get "You (email=sergey.poznyakoff@gmail.com) are not authorized to access this page!".
Accessing the bug tracker at https://bugs.chromium.org/p/oss-fuzz/issues/ results in "Permission denied"

**Comment by inferno-chromium** [comment]
> When trying to access the detailed report at https://oss-fuzz.com/testcase?key=5683615552372736 I get "You (email=[sergey.poznyakoff@gmail.com](mailto:sergey.poznyakoff@gmail.com)) are not authorized to access this page!".
> Accessing the bug tracker at https://bugs.chromium.org/p/oss-fuzz/issues/ results in "Permission denied"

email in project.yaml is https://github.com/google/oss-fuzz/blob/master/projects/gdbm/project.yaml#L3, it needs to match.

**Comment by graygnuorg** [comment]
I understand this. Then please, tell me how can I log in using my registered (non-google) address?

**Comment by inferno-chromium** [comment]
> I understand this. Then please, tell me how can I log in using my registered (non-google) address?

you need to use your gmail address (sergey.poznyakoff@gmail.com) in project.yaml. alternate email does not work, please see https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication
