### ISSUE TITLE
Swift linkage might be losing protocol conformances

### ISSUE THREAD

**Issue by thomasvl** [google/oss-fuzz#6399]
I'm not sure this is an issue, but reaching out to try and get some help from others to help get confirmation.

Looking at [swift-protobuf coverage](https://storage.googleapis.com/oss-fuzz-coverage/swift-protobuf/reports/20210903/linux/file_view_index.html), `CustomJSONCodable.swift` and all the `Google_Protobuf_*+Extensions.swift` files have zero coverage.

The test proto has [fields with the WKTs](https://github.com/apple/swift-protobuf/blob/b36ecd659967295950deb904323f1dd1ac9ded8f/Protos/fuzz_testing.proto#L296-L314) to try and get coverage for this types. In theory this could be just the fuzz testing of JSON might not have generated these fields, but I'm also wondering if we're seeing apple/swift-protobuf#1061 again.

google/oss-fuzz#6312 just updated some of this, but I don't think has majorly changed things. Of note in the flow is the `SWIFTFLAGS` coming from: [infra/base-images/base-builder-swift/precompile_swift](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder-swift/precompile_swift); they provide `-Xswiftc -use-ld=/usr/bin/ld`.  Since the files in question provide conformances and there are no other calls to code in the `.o` files, could the conformances not be making it into the fuzz binaries?

cc @catenacyber @tbkka @Lukasa

**Comment by thomasvl** [comment]
cc @allevato

**Comment by tbkka** [comment]
Is this on Linux or Darwin?

**Comment by thomasvl** [comment]
> Is this on Linux or Darwin?

Linux.

**Comment by tbkka** [comment]
@aschwaighofer just pointed out to me that on Darwin, Swift marks the mach-o sections with `no_dead_strip` attribute but not on ELF.  (I'm not sure if there is any equivalent.)

Might it be feasible to change how Bazel handles this type of library?  Alternatively, we may need to talk with the linker folks to figure out if there's a suitable analog in ELF that we should be using.

**Comment by thomasvl** [comment]
> Might it be feasible to change how Bazel handles this type of library? Alternatively, we may need to talk with the linker folks to figure out if there's a suitable analog in ELF that we should be using.

No bazel here.  [`swift build`](https://github.com/google/oss-fuzz/blob/master/projects/swift-protobuf/build.sh#L22) but with some a bunch of extra flags [`-Xswiftc -parse-as-library -Xswiftc -static-stdlib -Xswiftc -use-ld=/usr/bin/ld --static-swift-stdlib`](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder-swift/precompile_swift)

**Comment by catenacyber** [comment]
> The test proto has fields with the WKTs to try and get coverage for this types. In theory this could be just the fuzz testing of JSON might not have generated these fields, but I'm also wondering if we're seeing apple/swift-protobuf#1061 again.

The best is to have one input that you know should cover this code, and debug print to check the code gets covered, and then check if the coverage report gets it...
Could you generate such an input ?

**Comment by thomasvl** [comment]
> The best is to have one input that you know should cover this code, and debug print to check the code gets covered, and then check if the coverage report gets it...
> Could you generate such an input ?

I was wondering about that.  What's the best way to do this?  Define a seed corpus or a dictionary and I guess they need to get copied out along with the build results?

**Comment by catenacyber** [comment]
> Define a seed corpus

If you can build one, that is the best way to start

cf https://google.github.io/oss-fuzz/getting-started/new-project-guide/#seed-corpus

**Comment by thomasvl** [comment]
Looks like things are working correctly and the conformances are there.  With the new `dict` files in place, we're seeing coverage within the apis that require the protocol conformances.
