### ISSUE TITLE
Can't reproduce https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38393

### ISSUE THREAD

**Issue by zoulasc** [google/oss-fuzz#6422]
There was no c code change and the bug started to appear on an unrelated python change.

**Comment by inferno-chromium** [comment]
We migrated to ubuntu 20.04 images and switched to llvm 14, so regression range can be wrong.

Are you not able to reproduce using instructions from https://google.github.io/oss-fuzz/advanced-topics/reproducing

**Comment by zoulasc** [comment]
I am having trouble asan working with ubuntu-20.04 and llvm 14:

[10:25am] 560>./file -m ../magic/magic.mgc ~/clusterfuzz-testcase-minimized-magic_fuzzer-5677554623709184
==86969==Shadow memory range interleaves with an existing memory mapping. ASan cannot proceed correctly. ABORTING.
==86969==ASan shadow was supposed to be located in the [0x00007fff7000-0x10007fff7fff] range.
==86969==This might be related to ELF_ET_DYN_BASE change in Linux 4.12.
==86969==See https://github.com/google/sanitizers/issues/856 for possible workarounds.
==86969==Process memory map follows:

**Comment by zoulasc** [comment]
Finally found what's wrong. It was a pointer addition overflow (that gcc treats as undefined behavior and removes the wrap check). This only happens in 32 bit mode, so I could not reproduce it without -m32. Perhaps it would be useful to mention in the docs to try -m32 too... Feel free to close this.

**Comment by inferno-chromium** [comment]
> Finally found what's wrong. It was a pointer addition overflow (that gcc treats as undefined behavior and removes the wrap check). This only happens in 32 bit mode, so I could not reproduce it without -m32. Perhaps it would be useful to mention in the docs to try -m32 too... Feel free to close this.

feel free to suggest a doc addition, see docs/ dir. closing
