### ISSUE TITLE
Add link to fuzzer environment doc from build.sh in new project guide

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#6425]

**Comment by inferno-chromium** [comment]
This was brought up in https://github.com/google/oss-fuzz/pull/6423#issuecomment-917478069

@DavidKorczynski - would you be able to help with this doc addition. Thanks a lot!

**Comment by DavidKorczynski** [comment]
Closed with https://github.com/google/oss-fuzz/pull/6428
