### ISSUE TITLE
Add 32bit fuzzing support for FreeType

### ISSUE THREAD

**Issue by lemzwerg** [google/oss-fuzz#643]
This is a follow-up of http://savannah.nongnu.org/bugs/?46149 – what steps are necessary to build and fuzz FreeType with gcc's or clang's '-m32' option?  Due to the very nature of many font formats I expect that integer overflows are much easier to trigger in such a setup.

**Comment by kcc** [comment]
This might involve a bit more work on our than I originally [suggested](http://savannah.nongnu.org/bugs/?46149 ) to Werner, but I think it's worth doing. 

**One way** to go is to build both 32- and 64- bit binaries in the same docker environment. 

Werner, on your side you will need:

* modify https://github.com/google/oss-fuzz/blob/master/projects/freetype2/Dockerfile to apt-get the 32-bit libs require to build 32-bit freetype. Note this docker is inherited from Ubuntu 16.04, see https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-image/Dockerfile

* modify https://github.com/google/oss-fuzz/blob/master/projects/freetype2/build.sh to add the 32-build that will produce e.g. $OUT/ftfuzzer32

I'd highly appreciate if you actually test the changes in Docker (Docker might be tricky to install on some systems, but it's worth it -- it really provides a hermetic build environment where we can be sure that what works for you also works for us)

We will need to provide the 32-bit libFuzzingEngine, or something. 

**Another way** is to create a pure 32-bit build environment on our side that will hopefully not require any changes on the user side.

@oliverchang @inferno-chromium WDYT? 
This might be useful for other projects as well (at least, all the crypto folks would be happy)

**Comment by oliverchang** [comment]
Yeah, maintaining 32-bit images sounds the most reliable. However, I can't seem to find official i386 ubuntu images (there are a couple of unofficial ones that I'd rather we didn't rely on).

**Comment by inferno-chromium** [comment]
it is supported, and in docs.
