### ISSUE TITLE
No issue opened for reliably reproducible memory issue

### ISSUE THREAD

**Issue by MarcoFalke** [google/oss-fuzz#6439]
There is https://oss-fuzz.com/testcase-detail/5734826813030400 , found two weeks ago, reliable reproduces. Though, there is no issue opened for it yet.

Is this expected?

**Comment by oliverchang** [comment]
We temporarily turned off bug filing as we had recently migrated our images to Ubuntu 20.04 from 16.04. Bug filing has been turned back on and I see that's the case for this one too.
