### ISSUE TITLE
monorail: add fuzzer program name in summary + label column

### ISSUE THREAD

**Issue by rouault** [google/oss-fuzz#644]
In https://bugs.chromium.org/p/oss-fuzz/issues/list?q=gdal , it is not possible to filter by fuzzer program name. I have several fuzzers, with some dedicated to a single file format, and it would be convenient (particularly for the maintainer of a particular format, not interested in unrelated issues) to filter easily by fuzzer program name. Just putting the program name in summary + label could be enough I think.

Note: I found it was possible through https://oss-fuzz.com/v2/testcases with a request like
https://oss-fuzz.com/v2/testcases?open=yes&q=cad_fuzzer
Having it through bugs.chromium.org would be good too.

**Comment by Dor1s** [comment]
Hi @rouault, there is at least one hacky way to do what you want via `description:` filter of a monorail query, e.g.:

https://bugs.chromium.org/p/oss-fuzz/issues/list?can=2&q=label%3AProj-gdal+description%3Alibfuzzer_gdal_cad_fuzzer%2Cafl_gdal_cad_fuzzer&colspec=ID+Type+Component+Status+Proj+Reported+Owner+Summary&cells=ids

**Comment by oliverchang** [comment]
You should just be able to search for the fuzz  target name. e.g. https://bugs.chromium.org/p/oss-fuzz/issues/list?can=2&q=cad_fuzzer&colspec=ID+Type+Component+Status+Proj+Reported+Owner+Summary&cells=ids  will list all bugs for cad_fuzzer

**Comment by rouault** [comment]
> You should just be able to search for the fuzz target name. e.g. https://bugs.chromium.org/p/oss-fuzz/issues/list?can=2&q=cad_fuzzer&colspec=ID+Type+Component+Status+Proj+Reported+Owner+Summary&cells=ids will list all bugs for cad_fuzzer

Hum, I thought I tried it before, but apparently not. Sorry for the noise. Thanks
