### ISSUE TITLE
Initialization code seemingly reported as leaky

### ISSUE THREAD

**Issue by astiob** [google/oss-fuzz#6440]
libass is getting a [weird memory leak](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38557) reported. Our investigation points to the library initialization code in our fuzzer target as the culprit. This never happened before, and the fuzzer target hasn’t changed. What should we do now?

The fuzzer target has a static variable inside `LLVMFuzzerTestOneInput` as [suggested by libFuzzer docs](https://llvm.org/docs/LibFuzzer.html#startup-initialization):

https://github.com/google/oss-fuzz/blob/3b1124b6eab29f266d0169c77a9f9e3a80ef8555/projects/libass/libass_fuzzer.cc#L36-L37

where libass is initialized and allocates some memory:

https://github.com/google/oss-fuzz/blob/3b1124b6eab29f266d0169c77a9f9e3a80ef8555/projects/libass/libass_fuzzer.cc#L15-L34

Of course, this memory is never freed, because the fuzzer API provides no shutdown cleanup hook.

It seems that it is this memory that’s getting reported, specifically memory from Fontconfig. (Manual tests with the library freed at the end of the test report no leak. Manual inspection of Fontconfig source code from Ubuntu 20.04 also suggests the ClusterFuzz leak shouldn’t be possible.)

Weirdly enough, only a subset of the memory allocated in init is reported, indeed only a subset of the Fontconfig memory. Further, this subset is [different](https://0x0.st/-xEk.txt) in the ClusterFuzz report and in local reproduction testing (admittedly _not_ via the Docker environment, but on same/similar Linux distributions). And as mentioned before, OSS-Fuzz has never reported this before the recent migration to Ubuntu 20.04.

Should we fully init & free the library in each `LLVMFuzzerTestOneInput` call? In local tests, this seems to fix the leaks we’ve managed to observe, but maybe this just hides one particular symptom. Even if this works, is this actually desired/intended/required?

Or would using a C++ destructor for cleanup work?

Or is this a fuzzer bug? If not, any idea why this only started happening now and isn’t consistently reporting all of the init allocations?

**Comment by DavidKorczynski** [comment]
In general, I am not sure if some things in the underlying infrastructure independent of oss-fuzz has caused the code struct to suddenly being considered a leak. 
> 
> Should we fully init & free the library in each `LLVMFuzzerTestOneInput` call? In local tests, this seems to fix the leaks we’ve managed to observe, but maybe this just hides one particular symptom. Even if this works, is this actually desired/intended/required?
> 
Have you considered using `LLVMFuzzerInitialize`? I think that's probably the best solution. You can see more here: https://llvm.org/docs/LibFuzzer.html#startup-initialization
Otherwise, I would probably prefer the C++ destructor below and lastly the suggestion you have here. 

> Or would using a C++ destructor for cleanup work?
> 

I think this might work and would consider it the preferred solution. 

> Or is this a fuzzer bug? If not, any idea why this only started happening now and isn’t consistently reporting all of the init allocations?

I don't think this is a fuzzer bug.

**Comment by astiob** [comment]
We’ve now tried `LLVMFuzzerInitialize`: no difference; and a C++ destructor: the leaks reported in local tests disappear.

I’ve also now been able to confirm all of these results in a proper dockerized `python infra/helper.py` setup [per the manual](https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-bugs), on an Ubuntu 20.04 host for good measure. (The reported leaks are still different from those ClusterFuzz got reported, but oh well.)

I’ll shortly submit a PR to fix the libass fuzzer target by using a C++ destructor. Right now one of its dependencies is broken, but a fix is about to be merged.

**Comment by astiob** [comment]
(cc @DavidKorczynski)

ClusterFuzz still [reports](https://oss-fuzz.com/testcase-detail/4643342974058496) this leak as present, despite the use of a C++ destructor. The same allocation was also listed in a new report today alongside a different, legitimate leak (which I’ve fixed).

I’m unable to reproduce the leak report via `infra/helper.py reproduce`. The test runs, the fuzzer target’s own stdout is the same, but no sanitizer problems are reported. (As mentioned before, source code inspection also suggests this kind of leak is impossible.)

I can take a stab in the dark and modify the fuzzer to fully un-/reinitialize libass on every test case. But is anyone able to confirm that this really is how it’s supposed to work?

Is there a better way to try reproducing the leak locally?

**Comment by DavidKorczynski** [comment]
Have you tried the `Re-upload Testcase` feature on the report? If you click that link and just select `Create`, does it show the same results?
