### ISSUE TITLE
infra/helper.py reproduce still uses Ubuntu 16.04

### ISSUE THREAD

**Issue by astiob** [google/oss-fuzz#6452]
When I run `python infra/helper.py reproduce ...` as instructed by https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-bugs, it pulls the `ubuntu:16.04` Docker image. Shouldn’t this be upgraded to 20.04 or changed to `gcr.io/oss-fuzz-base/base-runner`?

**Comment by astiob** [comment]
It seems this image is only used to check whether a file exists (the fuzzer target binary), and `base-runner` is used to actually run it. So perhaps this isn’t an urgent bug, but inconvenient and confusing to users.

Then again, why is Docker used for a file existence check at all? Can it not be checked directly on the host via os.path.exists`?

**Comment by jonathanmetzman** [comment]
> It seems this image is only used to check whether a file exists (the fuzzer target binary), and `base-runner` is used to actually run it. So perhaps this isn’t an urgent bug, but inconvenient and confusing to users.
> 
> Then again, why is Docker used for a file existence check at all? Can it not be checked directly on the host via `os.path.exists`?

Thanks for this bug. Yes, it was extremely confusing to me why docker is used for this check. According to https://github.com/google/oss-fuzz/pull/306 it is for OS X and Windows users. I think this is a worthwhile goal but I can't really test either and I'm frankly unsure that we haven't broken this.

I'm going to patch this to use base-runner so that it never gets out of sync. Longer term we should consider if we want this complexity for OSX/Windows.

**Comment by jonathanmetzman** [comment]
@oliverchang WDYT?

**Comment by astiob** [comment]
Thanks!

Ah, remote Docker sounds interesting and explains it. I may actually try using that, now that I know it’s possible! As it happens, I’m currently running Docker on a machine separate from my main machine, and having the oss-fuzz repo on there is a little inconvenient.

FWIW, Docker nowadays runs on both Windows and macOS as far as I know, but an ability to run a remote Docker is potentially useful for users on all platforms, including Linux.

**Comment by jonathanmetzman** [comment]
> Thanks!
> 
> Ah, remote Docker sounds interesting and explains it. I may actually try using that, now that I know it’s possible! As it happens, I’m currently running Docker on a machine separate from my main machine, and having the oss-fuzz repo on there is a little inconvenient.
> 
> FWIW, Docker nowadays runs on both Windows and macOS as far as I know, but an ability to run a remote Docker is potentially useful for users on all platforms, including Linux.

Oh so you think this feature is unnecessary to support Windows/OSX?
Could you explain why it's useful?

**Comment by astiob** [comment]
> Oh so you think this feature is unnecessary to support Windows/OSX?

Sorry, no, after more research, it seems that this feature is precisely what makes Docker work on Windows and macOS.

As far as I understand #306, this is basically supported everywhere else in OSS-Fuzz anyway, and the `_check_fuzzer_exists` helper is the only place that has to go out of its way to support this workflow.

In addition to local Docker on Windows, and macOS, it can also be used to connect to a remote Docker:

> Could you explain why it's useful?

Well, it’s a bit of a niche use, but someone (like me) may want to have the oss-fuzz Git repository on one machine and the Docker images and runtime on another.

In my particular case, my main development machine doesn’t have the free disk space for the heavy Docker images; and my secondary machine has a CPU too old to run OSS-Fuzz’s current ASan binaries (it gets ILL on popcount, which is SSE 4.2 whereas this CPU has only SSE 2). So in the end I’ve set up a third machine to hold the Docker runtime. Without ability to use remote Docker, this means I also have to move the oss-fuzz source repository to the third machine and perform or replicate any experimental source code changes on that machine. With remote Docker, I will be able to keep the source repository on my main machine and run the builds on the dedicated runner I set up.
