### ISSUE TITLE
honggfuzz build failures.

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#646]
See https://github.com/google/oss-fuzz/pull/636#issuecomment-305680499

**Comment by josephbisch** [comment]
Please try re-enabling honggfuzz for irssi now.

**Comment by robertswiecki** [comment]
I've also fixed a bug in honggfuzz (in libhfuzz.a) which prevented libchewing and libass from building.

As for nss and lack of LLVMFuzzerMutate, I have an idea on how to fix it, but I need a few days to implement and test it.

**Comment by oliverchang** [comment]
I've re-enabled honggfuzz for issi, libchewing, and libass. Thanks!
