### ISSUE TITLE
False alarm from msan with << operator of std::stringstream

### ISSUE THREAD

**Issue by afd** [google/oss-fuzz#6471]
The msan fuzz target of [this build](https://github.com/google/oss-fuzz/pull/6466) is failing because the fuzzer appears to be broken: most runs lead to an msan error.

I have looked into this, and the msan error seems to happen when << from std::stringstream is invoked.

I have a feeling this might be a false positive, and that maybe something is going wrong with compiler/linker flags. I'm digging into it, but I wonder if anyone can alert me to any known gotchas about msan? I have tried hard to let OSS-Fuzz take care of passing compiler and linker arguments.

Thanks in advance for any advice.

**Comment by jonathanmetzman** [comment]
Maybe it's caused by https://github.com/google/oss-fuzz/issues/6427 I can try fixing that today.

**Comment by jonathanmetzman** [comment]
How can I reproduce this issue?

**Comment by afd** [comment]
I originally found the issue when a spirv-tools build failed when msan was enabled. I just tried re-adding msan and the build now succeeds - see #6500. So I guess what you did for #6427 must have done the trick. Thanks!
