### ISSUE TITLE
Floating point divide-by-zero false positive

### ISSUE THREAD

**Issue by kevinbackhouse** [google/oss-fuzz#6489]
I'm getting an error that I think is a false positive: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38862

It's complaining about [this code](https://github.com/Exiv2/exiv2/blob/774e6625e3ed4fb6d330d8ad40677fafecf125f7/src/tags_int.cpp#L2617):

```c
const double x = std::round(1/tmp);    // DIVIDE-BY-ZERO!!!
// Check that x is within the range of a uint32_t before casting.
if (0 <= x && x <= std::numeric_limits<uint32_t>::max()) {
    ur.first = static_cast<uint32_t>(x);
}
```

The type of [`tmp`](https://github.com/Exiv2/exiv2/blob/774e6625e3ed4fb6d330d8ad40677fafecf125f7/src/tags_int.cpp#L2608) is `double`, so that's a floating point divide-by-zero which is totally fine. The value of `x` is `inf`, so it fails the bounds check on the next line and nothing bad happens.

**Comment by MarcoFalke** [comment]
This is set by default. If you want to opt out, you'll have to append `-fno-sanitize=...`.

For reference see:

```
$ git grep float-divide-by-zero
infra/base-images/base-builder/Dockerfile:ENV SANITIZER_FLAGS_undefined "-fsanitize=array-bounds,bool,builtin,enum,float-divide-by-zero,function,integer-divide-by-zero,null,object-size,return,returns-nonnull-attribute,shift,signed-integer-overflow,unsigned-integer-overflow,unreachable,vla-bound,vptr -fno-sanitize-recover=array-bounds,bool,builtin,enum,float-divide-by-zero,function,integer-divide-by-zero,null,object-size,return,returns-nonnull-attribute,shift,signed-integer-overflow,unreachable,vla-bound,vptr"
projects/exprtk/build.sh:CXXFLAGS="${CXXFLAGS} -O2 -fno-sanitize=integer-divide-by-zero,float-divide-by-zero"
projects/muparser/build.sh:CFLAGS="${CFLAGS} -fno-sanitize=integer-divide-by-zero,float-divide-by-zero"
projects/muparser/build.sh:CXXFLAGS="${CXXFLAGS} -fno-sanitize=integer-divide-by-zero,float-divide-by-zero"

**Comment by kevinbackhouse** [comment]
@MarcoFalke: Thank you! I have created #6549 to fix this false positive.
