### ISSUE TITLE
Unicode-rs coverage build fails

### ISSUE THREAD

**Issue by Manishearth** [google/oss-fuzz#6496]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37516

```
Step #5: Running unicode-segmentation-fuzzer
Step #5: warning: /workspace/out/coverage/dumps/unicode-segmentation-fuzzer.3547862932440866716_0.profraw: Unsupported instrumentation profile format version
Step #5: error: No profiles could be merged.
```

I'm not quite sure what's going on here, is this perhaps an issue with how oss-fuzz uses rust? `cargo fuzz` works fine, and I'm not quite sure how the coverage stuff is being done here.

**Comment by DavidKorczynski** [comment]
I think it's related to this issue: https://github.com/google/oss-fuzz/issues/6268

**Comment by MarcoFalke** [comment]
Is this still an issue now that #6268 is closed?

**Comment by Manishearth** [comment]
I'll try to wait for [the autofiled bug](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37516) to get closed by the robot before closing this, imo.

**Comment by Manishearth** [comment]
Still broken:

```
Step #5: warning: /workspace/out/libfuzzer-coverage-x86_64/dumps/unicode-segmentation-fuzzer.13117700142267093511_0.profraw: invalid instrumentation profile data (file header is corrupt)
Step #5: error: no profile can be merged
```

**Comment by catenacyber** [comment]
Just fixed by https://github.com/google/oss-fuzz/pull/6551

**Comment by Manishearth** [comment]
Thanks! And the issue did self close
