### ISSUE TITLE
【libexif】Timout in mnote_olympus_entry_get_value

### ISSUE THREAD

**Issue by yangcheng1203** [google/oss-fuzz#6537]
Running: fusiontest-testcase-exif_from_data_fuzzer-202108190002  
==1723460== ERROR: libFuzzer: timeout after 90 seconds  
    #0 0x52ab01 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:86:3  
    #1 0x4755a8 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5  
    #2 0x459669 in fuzzer::Fuzzer::AlarmCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:301:5  
    #3 0x7fc511d924bf  (/lib64/libpthread.so.0+0x134bf)  
    #4 0x5369c4 in __sanitizer::internal_strlen(char const*) /src/llvm-project/compiler- rt/lib/sanitizer_common/sanitizer_libc.cpp:167:10  
    #5 0x4c46f5 in printf_common(void*, char const*, __va_list_tag*) /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors_format.inc:496:3  
    #6 0x4c5623 in vsprintf /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:1670:1  
    #7 0x4c6733 in sprintf /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:1713:1  
    #8 0x57ec46 in mnote_olympus_entry_get_value /src/libexif/libexif/olympus/mnote-olympus-entry.c:818:5  
    #9 0x57c226 in exif_mnote_data_olympus_get_value /src/libexif/libexif/olympus/exif-mnote-data-olympus.c:85:9  
    #10 0x56d1f0 in exif_mnote_data_get_value /src/libexif/libexif/exif-mnote-data.c:148:9  
    #11 0x556040 in mnote_dump(_ExifData*) /src/exif_from_data_fuzzer.cc:29:13  
    #12 0x555e09 in LLVMFuzzerTestOneInput /src/exif_from_data_fuzzer.cc:56:5  
    #13 0x45ae93 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15  
    #14 0x446602 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:323:6  
    #15 0x44c2ce in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:856:9  
    #16 0x475d82 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10  
    #17 0x7fc511bc3b26 in __libc_start_main (/lib64/libc.so.6+0x25b26)  
    #18 0x4220a9 in _start (/opt/oss-fuzz/build/out/libexif/exif_from_data_fuzzer+0x4220a9)  

DEDUP_TOKEN: __sanitizer_print_stack_trace--fuzzer::PrintStackTrace()--fuzzer::Fuzzer::AlarmCallback()  
SUMMARY: libFuzzer: timeout

**Comment by yangcheng1203** [comment]
libexif fuzz test execution timeout problem：  
Perform operation  
./exif_from_data_fuzzer fusiontest-testcase-exif_from_data_fuzzer-202108190002

Software version  
libexif：libexif-0_6_22-release

**Comment by yangcheng1203** [comment]
libexif fuzz test execution timeout problem：  
Perform operation  
./exif_from_data_fuzzer fusiontest-testcase-exif_from_data_fuzzer-202108190002

Software version  
libexif：libexif-0_6_22-release

**Comment by DavidKorczynski** [comment]
This is just a timeout issue found by the fuzzer that has not been solved upstream, not an issue in OSS-Fuzz
