### ISSUE TITLE
Can't reproduce build failure

### ISSUE THREAD

**Issue by tsdgeos** [google/oss-fuzz#6553]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=39443

I can't find the command that is being used for it, but my guess was

python infra/helper.py build_fuzzers --engine afl --sanitizer address poppler

but that seems to build fine here.

Did i guess the command right? If not, which one is it? If yes, any idea why it may be failing on the server and not for me?

**Comment by haberman** [comment]
You might need to run this first:

```
python infra/helper.py pull_images
```

(I'm here because fuzz builds have recently started failing for me too, but only with the newest images. I looked at your build logs and the error is different enough that I think I'll file my own bug for it.)

**Comment by tsdgeos** [comment]
yes, that doesn't make a difference

**Comment by MarcoFalke** [comment]
The steps to reproduce are listed at the end of the build log. In this case:

```
python infra/helper.py build_fuzzers --sanitizer undefined --engine libfuzzer --architecture x86_64 poppler
```

I can reproduce locally, but it might depend on the hardware you use. See also related https://github.com/google/oss-fuzz/issues/6506#issuecomment-928296751

**Comment by tsdgeos** [comment]
Ok, i am officially blind ^_^

https://github.com/google/oss-fuzz/pull/6566 seems like should fix it.
