### ISSUE TITLE
Fuzz builds through GitHub Actions fail with the latest Docker images

### ISSUE THREAD

**Issue by haberman** [google/oss-fuzz#6554]
I am suddenly getting build failures in my fuzzing presubmits. I was able to reproduce locally, but only after updating to the most recent Docker images.

```
ERROR: /src/upb/upbc/BUILD:44:10: Linking upbc/protoc-gen-upb [for host] failed: (Exit 1): clang failed: error executing command /usr/local/bin/clang @bazel-out/host/bin/upbc/protoc-gen-upb-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/host/bin/upbc/_objs/protoc-gen-upb/protoc-gen-upb.o:protoc-gen-upb.cc:function upbc::(anonymous namespace)::SizeLg2[abi:cxx11](google::protobuf::FieldDescriptor const*): error: undefined reference to 'vsnprintf.inline'
bazel-out/host/bin/upbc/_objs/protoc-gen-upb/protoc-gen-upb.o:protoc-gen-upb.cc:function upbc::(anonymous namespace)::SizeLg2[abi:cxx11](google::protobuf::FieldDescriptor const*): error: undefined reference to 'vsnprintf.inline'
bazel-out/host/bin/upbc/_objs/protoc-gen-upb/protoc-gen-upb.o:protoc-gen-upb.cc:function upbc::(anonymous namespace)::SizeLg2[abi:cxx11](google::protobuf::FieldDescriptor const*): error: undefined reference to 'vsnprintf.inline'
```
https://github.com/protocolbuffers/upb/pull/424/checks?check_run_id=3787788860

```
bazel-out/k8-opt-exec-2B5CBBC6-ST-ab5d94bbe0bc/bin/external/com_google_protobuf/_objs/protoc_lib/php_generator.o:php_generator.cc:function google::protobuf::compiler::php::Generator::GenerateAll(std::vector<google::protobuf::FileDescriptor const*, std::allocator<google::protobuf::FileDescriptor const*> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::compiler::GeneratorContext*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const: error: undefined reference to 'vsnprintf.inline'
```
https://github.com/protocolbuffers/upb/pull/424/checks?check_run_id=3787788891

The `undefined reference to 'vsnprintf.inline'` makes me think this could be related to libc++ in the Docker image.

**Comment by oliverchang** [comment]
@jonathanmetzman could this be related to https://github.com/google/oss-fuzz/pull/6493 ?

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman could this be related to #6493 ?

Doubtful. This seems to have started on 10/04 and didn't happen on 10/02.
#6493 landed on 09/20

**Comment by haberman** [comment]
I first observed this a day earlier, on 10/3: https://github.com/protocolbuffers/upb/runs/3783389968

**Comment by jonathanmetzman** [comment]
Did you see this happen around september 20?
If not I'm not sure my change is responsible.
Another reason I don't think it is responsible is because that change only affects i386 and MSAN builds.
This problem is in an x86_64 ASAN build.

**Comment by haberman** [comment]
No I did not observe this until 10/3.

I wasn't meaning to suggest your change is responsible, just trying to give a slightly tighter time bound in case it helps narrow down the root cause.

**Comment by jonathanmetzman** [comment]
ACK. Thanks!

I'm having a little trouble debugging this because I'm not familiar with bazel.

**Comment by haberman** [comment]
You may find it useful to build with `-s` (eg. `bazel build -s ...`). It will dump the commands it is executing, which should give you a bare command invocation you can use to reproduce.

**Comment by jonathanmetzman** [comment]
Looks like there was a clang roll on 10/02:
https://chromium-review.googlesource.com/c/chromium/src/+/3199571

You can work around this issue temporarily by changing [this line](https://github.com/google/oss-fuzz/blob/master/projects/upb/Dockerfile#L17) to: `FROM gcr.io/oss-fuzz-base/base-builder@sha256:e963d3ebefb9390ad31df2f9d6722cb8478d9a9116b965b03b3a34faea00d543`

**Comment by jonathanmetzman** [comment]
Upb is pinned to an older clang but for a different reason.
