### ISSUE TITLE
OpenSK build failures

### ISSUE THREAD

**Issue by kaczmarczyck** [google/oss-fuzz#6571]
Hi!

OpenSK has coverage build failures since some time (i.e. [see bug](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36535#c10)). I saw #6551 mentioned our the problem, but no issue was open to track it. Just wanted to check if you are working on a fix or if there is anything we could do in our own code?

From the pull request:
> So these are other problems, likely missing `remap-path-prefix`

**Comment by oliverchang** [comment]
@catenacyber FYI. Is this the same issue?

**Comment by catenacyber** [comment]
Yes, this is the same issue.
From the latest build log, we can see 
`error: fuzz_helper/src/lib.rs: No such file or directory`

We should have an absolute path instead of a relative one for this file to find it.
The right `remap-path-prefix` should fix this.
I will try to look more into it
