### ISSUE TITLE
afl builds fail with "Bad syntax used for -t"

### ISSUE THREAD

**Issue by nikic** [google/oss-fuzz#6585]
You're probably already aware of this, but reporting just in case: All AFL builds seem to fail with error `Bad syntax used for -t`.

I'm looking at https://oss-fuzz-build-logs.storage.googleapis.com/index.html#php, but other builds show the same issue.

**Comment by oliverchang** [comment]
Let's close this since the main issue itself (afl failing) is fixed. Thanks for the help everyone!
