### ISSUE TITLE
No php builds since Oct 12th

### ISSUE THREAD

**Issue by nikic** [google/oss-fuzz#6605]
After the failed build on Oct 12th, there have been no new builds for the `php` project in the last three days: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#php

I don't really get why, as most other projects do their daily build just fine. There's only a couple others that haven't been built since Oct 12th (e.g. libecc and vlc).

**Comment by nikic** [comment]
Looks like the build worked on Oct 16th. Still weird that 3 builds before that were skipped.

**Comment by oliverchang** [comment]
The quote has been bumped.
