### ISSUE TITLE
ask users to file issues in github if they have questions to oss-fuzz team

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#662]
We periodically get questions from users in the monorail tracker. 
But with our current report volume it's easy to miss those question. 

So, I suggest that the bugs filed automatically by oss-fuzz contain something like this:
"If you have questions to the OSS-Fuzz team, please file an issue at https://github.com/google/oss-fuzz/issues"

**Comment by inferno-chromium** [comment]
This is done, Thanks Oliver!
