### ISSUE TITLE
a nicely reproducible null deref is marked as non-reproducible 

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#663]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1916 (@tobiasbrunner)
I've just verified that the reproducer is stable, but CF marks the case as non-reproducible.

**Comment by oliverchang** [comment]
It looks like the issue is that the CF testcase was incorrectly marked as "Security: yes" somehow after the initial filing, which confuses CF.

@tobiasbrunner, do you remember if you manually marked this testcase as "Security: yes" ?

**Comment by oliverchang** [comment]
Looking at the access logs, it looks like that @tobiasbrunner has indeed been marking testcases manually as "Security". I'll remove the ability to do so, as it's really intended for admins.

Note that there's no real distinction between security and non-security bugs in terms of view restrictions etc.

**Comment by oliverchang** [comment]
I've fixed up these null derefs, and removed the ability to manually set the security flag.

**Comment by tobiasbrunner** [comment]
> Note that there's no real distinction between security and non-security bugs in terms of view restrictions etc.

I see. I misunderstood the purpose of that flag then (what is its purpose?).

**Comment by inferno-chromium** [comment]
Actually that flag is to mark any functional crash stacktrace as one having security implication. It is an admin only functionality that shouldn't be exposed. It also does not work well, so we are removing from default view. All functional bugs are restrict view by default, so it shouldnt be needed.
