### ISSUE TITLE
we are WontFix-ing perfectly nice ubsan reports

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#665]
E.g. this one: 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1463#c2
I've just verified that it works:
```
python infra/helper.py build_image harfbuzz
python infra/helper.py build_fuzzers --sanitizer undefined harfbuzz 
python infra/helper.py reproduce harfbuzz hb-fuzzer ~/Downloads/clusterfuzz-testcase-minimized-4523479581851648
```

```
... runtime error: index 2 out of bounds for type ...
```

**Comment by Dor1s** [comment]
This is strange! I'll take a look.

**Comment by Dor1s** [comment]
Frankly, I don't see a particular reason why this happened. I'm suspicious about "regression" or "minimize" tasks, since after kicking off "progression" task, the crash is being marked as reproducible.
Now I kicked off "minimize" task only. Will check the result and the logs.

**Comment by Dor1s** [comment]
Minimize task on Friday had the following log (twice):

```
I  Executing command 'minimize 4523479581851648 libfuzzer_ubsan_harfbuzz' 
I  Reading blob key <...>. 
I  Wrote 525 bytes to local file. 
I  Retrieving build r201706081621. 
I  Start downloading https://commondatastorage.googleapis.com/clusterfuzz-builds/harfbuzz/harfbuzz-undefined-201706081621.zip. 
I  Finish downloading https://commondatastorage.googleapis.com/clusterfuzz-builds/harfbuzz/harfbuzz-undefined-201706081621.zip. 
I  Downloading https://commondatastorage.googleapis.com/clusterfuzz-builds/harfbuzz/harfbuzz-undefined-201706081621.zip succeeded. The size of /mnt/scratch0/clusterfuzz/slave-bot/builds/clusterfuzz-builds_harfbuzz_aa880bb59a58d1839d173911f98ec1829e12dfda/revisions/harfbuzz-undefined-201706081621.zip is 2052410, which matches 2052410. 
I  Retrieved build r201706081621. 
I  Setup application path. 
W  Did not crash. Output:
[Environment] UBSAN_OPTIONS = external_symbolizer_path=/bin/llvm-symbolizer:allocator_release_to_os_interval_ms=500:halt_on_error=1:strip_path_prefix=/workspace/:print_stacktrace=1:symbolize=0:print_summary=1

 
I  Clearing defunct process 7691. 

```

However, a further Minimize task was successful:
```
I  Executing command 'minimize 4523479581851648 libfuzzer_ubsan_harfbuzz' 
I  Data bundle was recently synced, skip. 
I  Reading blob key <...>. 
I  Wrote 525 bytes to local file. 
I  Retrieving build r201706091627. 
I  Start downloading https://commondatastorage.googleapis.com/clusterfuzz-builds/harfbuzz/harfbuzz-undefined-201706091627.zip. 
I  Finish downloading https://commondatastorage.googleapis.com/clusterfuzz-builds/harfbuzz/harfbuzz-undefined-201706091627.zip. 
I  Downloading https://commondatastorage.googleapis.com/clusterfuzz-builds/harfbuzz/harfbuzz-undefined-201706091627.zip succeeded. The size of /mnt/scratch0/clusterfuzz/slave-bot/builds/clusterfuzz-builds_harfbuzz_aa880bb59a58d1839d173911f98ec1829e12dfda/revisions/harfbuzz-undefined-201706091627.zip is 2052410, which matches 2052410. 
I  Retrieved build r201706091627. 
I  Setup application path. 
I  Initial crash state: hb_ot_face_glyf_accelerator_t::get_extents
hb_ot_get_glyph_extents
_start

 
I  Minimizing round 1. 

```

Those Minimize attempts were using different revisions:
- unlucky task: `r201706081621`
- luck task: `r201706091627`

The original revision of the crash seems to be ` r201705091619`:
```
[2017-05-09 19:33:25 UTC] oss-fuzz-linux-zone1-pre-1064: Fuzz task : Fuzzer libFuzzer_harfbuzz_hb-fuzzer generated testcase crashed in 34 seconds (r201705091619).
```

I'll test all of the revisions and will post an update.

**Comment by Dor1s** [comment]
Well, all of the revisions are correct and the crash is reproducible with all of them.

Another things that looks strange is the output from failed Minimize task. Shouldn't it have a line like `INFO: Seed...` or `Running 1 inputs 100 time(s) each.`? Other than that, there can me `SIGTERMed` message, if single test run has timed out, but it also is not there.

**Comment by oliverchang** [comment]
@Dor1s would you please check to see if this is still happening after the latest fixes, and close this if it's no longer happening? thanks!

**Comment by Dor1s** [comment]
Sure, I'm looking into this right now!

**Comment by Dor1s** [comment]
Confirmed:
- process tree is incredibly clean
- logs do not have those messages anymore
- the testcase is always reproducible even during Minimize task

Huge thanks to Oliver for his help!

**Comment by Dor1s** [comment]
And of course thanks Kostya @kcc for noticing this misbehavior, it helped to reveal a serious issue on our side.
