### ISSUE TITLE
Off-by-2 days in fixed testing

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#666]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=735

Oliver, i think we have an off by two depending on when builds get triggered. Maybe we should change the builds to be triggered around 10-11 pm, so that our 12 am fixed testing picks latest builds in most cases. Thoughts ?

Success > Console Output#1​12 Jun 8, 2017 9:48 AM 
Success > Console Output#1​11 Jun 7, 2017 9:46 AM
Fix went in 2017-06-07 17:58:26 (GMT) => 2017-06-07 12:58:26 (PDT), i think Jun8 fixed testing didn't pick latest build since builds go in later around 9 AM.

**Comment by oliverchang** [comment]
Done, builds are now triggered at 9pm PT
