### ISSUE TITLE
helper.py doesn't always consume --external properly

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#6686]
Will provide more details later.

**Comment by oliverchang** [comment]
Could you provide some examples here for what should work but doesn't ?

**Comment by jonathanmetzman** [comment]
Something like this fails: `python ~/oss-fuzz/infra/helper.py run_fuzzer /tmp/systemd fuzz-json --external`

**Comment by jonathanmetzman** [comment]
Because --external is interpreted as arguments to fuzz-json rather than an argument to helper.py

I think the way most tools deal with this is having arguments passed to child processes passes after `--`
