### ISSUE TITLE
Same null pointer dereference bug reported by ASAN and UBSAN fuzzers

### ISSUE THREAD

**Issue by rouault** [google/oss-fuzz#669]
This is more in the improvements category, but access to a field of a null pointer structure is reported by both the ASAN and UBSAN fuzzers. See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2167 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2193 for such ann occurence

**Comment by oliverchang** [comment]
@Dor1s can you please take a look at this?

**Comment by inferno-chromium** [comment]
low priority, but this can be fixed by fixing crash type comparison.

**Comment by oliverchang** [comment]
OK, wanted to make sure that the potential-null-derefence really is a potential-null-dereference (and not just null-dereference).

**Comment by oliverchang** [comment]
We no longer file potential-null-dereference bugs.
