### ISSUE TITLE
Issue with automatic libFuzzer minimization

### ISSUE THREAD

**Issue by clvang000** [google/oss-fuzz#672]
Hello, 

I'm experiencing a problem with libFuzzer. I'm running OSSFuzz locally.

For example the OpenSSL project. When I start fuzzing any of the fuzz targets with libFuzzer, it seems to minimize the corpus you give it, when it starts fuzzing. The problem is, that it actually seem to decrease the coverage of the overall corpus, in this minimization step.

I've tracked the coverage and number of test cases for the 'client' fuzz target, using the client seed corpus to start fuzzing with. The coverage has been calculated by using the nr. of guards for the client fuzz target and the INITED coverage of the corpus, at each interval. This gives the following results:

[time of measurement in seconds]:[coverage ratio]:[nr. of test cases]
0:0.1421:1389
10:0.0681:15
20:0.0681:17
30:0.0764:18
40:0.0766:20
50:0.0787:22
60:0.0789:24

Thus it seems that the corpus at 10 seconds actually has less coverage than the initial seed corpus. 
Do you understand what is going on here, and is there a solution for this issue?

Some additional info:

I'm running like this:
./client outlf_client lfmin_client -jobs=4 -workers=4 -print_final_stats=1 -rss_limit_mb=2048

The seed corpus (lfmin_client) used is the minimized corpus of the corp_client.zip that comes with the OpenSSL image. (minimized by libFuzzer -merge=1)

Thank you.
Best regards.

**Comment by kcc** [comment]
May I ask you to provide the *exact* command lines, the libFuzzer logs, and point what's bothering you there? 

(also let's not throw -jobs=4 -workers=4 into the problem -- parallelism makes things more complicated)

Sometimes it's possible to see a small discrepancy between coverage stats e.g. if the target code is somewhat unstable (e.g. has a global hash table that is filled with stuff over time and thus generates new coverage periodically)

**Comment by clvang000** [comment]
Hello,

Thanks for your response.
Alright, I've run the same operation without the parallelism now.

The command I execute to do the fuzzing:
**./lf_client test_lf2 cmin_client -print_final_stats=1 -rss_limit_mb=0**

Then I ran the fuzzing for about 30 seconds. And after that I checked the coverage of the resulting synthesized corpus (test_lf2) with the following command.
**./lf_client test_lf2 -runs=0**

The command I executed to get the initial_coverage:
**./lf_client cmin_client -runs=0**

Please see the log file and the coverage results here: https://github.com/clvang000/libfuzz

The INITED coverage of the initial seed corpus is 5933, and the log shows that it is improving on this coverage. However, after aborting the fuzz process, the synthesized corpus does not seem to have all the test cases anymore. After 30 seconds it only has 20 test cases and an INITED coverage of 3598. Thus, it seems that the coverage has actually decreased in the output corpus.

Or is it the case that libFuzzer also keeps using the initial seed corpus that you give it, and we should check here for the final coverage results? 

I was under the impression that the output corpus that you give it, will contain all the interesting test cases, and that libFuzzer will only use this corpus to do the fuzzing. Because it would get all test cases of the initial seed corpus copied over to that output corpus (as is the case with AFL), and use that corpus as the synthesized corpus. However, this does not seem the case here. 

Thank you.
Best Regards.

**Comment by kcc** [comment]
Ok, here is the shorter version of what you do, please check.

C0 -- directory with the initial (seed) corpus
C1 -- empty directory

```
./fuzz C1 C0  # run for some time, then stop
```

At this moment C1 will contain elements that add some coverage on top of C0,
but C1 is not a super-set of C0.

If you want C1 to be a super-set of C0, use 
```
./fuzz C1 C0 -merge=1 
```

(If this did not answer your question, please reopen)

**Comment by clvang000** [comment]
This answered my question. Thank you!
