### ISSUE TITLE
Spurious "ClusterFuzz-Verified" for reproducible issue

### ISSUE THREAD

**Issue by MarcoFalke** [google/oss-fuzz#6726]
Yesterday a reproducible unfixed issue was closed: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34146#c3

It still reproduces both locally and on clusterfuzz for task "Check if bug still reproduces".

**Comment by oliverchang** [comment]
Unfortunately flakiness does happen from time to time depending on the crash / target despite our best attempts.  

I see that your redo has set the testcase back in the expected state on https://oss-fuzz.com/testcase-detail/6328915661553664. 

Closing as I don't think there's anything left actionable here
