### ISSUE TITLE
Improving OSS-Fuzz: short, medium and long run

### ISSUE THREAD

**Issue by paulm1024** [google/oss-fuzz#673]
Hi guys,

I am currently looking for improving the OSS-Fuzz tool in a consistent manner. For this reason, since I am not aware of all the open constructions sites of OSS-Fuzz, I want to ask. 

Could somebody of you be so kind and share/list all the main directions for improving OSS-Fuzz in the short, medium and long run.

Thanks in advance.

Cheers,
Paul

**Comment by kcc** [comment]
> I am currently looking for improving the OSS-Fuzz tool in a consistent manner. 

OSS-Fuzz is a service, not really a tool. 
Can you share some details on what exactly you want to improve? 

> list all the main directions for improving OSS-Fuzz

* Get more OSS projects to participate 
* Make sure the process is as friction-less as possible
* Improve the efficiency of bug detection (better fuzzing engines, more sanitizers) 
* Probably some UI improvements

The final goal is to have every OSS project to have good continuous automated fuzzing 
(not necessary using OSS-Fuzz)

**Comment by oliverchang** [comment]
Not sure if there's anything immediately actionable here, so I'm closing this bug. Feel free to re-open if that's not the case.
