### ISSUE TITLE
Handle targets that implement signal handlers

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#675]
Targets that install their own SIGALRM/SIGSEGV/SIGABRT etc handlers may prevent libFuzzer/sanitizers from reporting timeouts/crashes in a way that ClusterFuzz understands.

#671  is an example -- libreoffice targets fail quickly on a timeout, but because there's a SIGALRM handlers that exit silently our logs show that the target just exits after some time without any indication why.

We should explore if there is a good way to prevent this situation.

**Comment by kcc** [comment]
Ughhh... 
@vitalybuka has made a change recently where we stopped blocking users from redefining asan's sig handlers by default. 
```
        handle_segv
                - Controls custom tool's SIGSEGV handler (0 - do not registers the handler, 1 - register the handler and allow user to set own, 2 - registers the handler and block user from changing it). 
        handle_sigbus
                - Controls custom tool's SIGBUS handler (0 - do not registers the handler, 1 - register the handler and allow user to set own, 2 - registers the handler and block user from changing it). 
        handle_abort
                - Controls custom tool's SIGABRT handler (0 - do not registers the handler, 1 - register the handler and allow user to set own, 2 - registers the handler and block user from changing it). 
        handle_sigill
                - Controls custom tool's SIGILL handler (0 - do not registers the handler, 1 - register the handler and allow user to set own, 2 - registers the handler and block user from changing it). 
        handle_sigfpe
                - Controls custom tool's SIGFPE handler (0 - do not registers the handler, 1 - register the handler and allow user to set own, 2 - registers the handler and block user from changing it). 
```

so, for those signals the simplest is to set all these flags to 2

As for SIGALRM... Hmmm. asan has nothing to do with SIGALRM.
libFuzzer needs to have it's own SIGALRM but it has not way to block the user from redefining it.

**Comment by kcc** [comment]
we can also add a code to libFuzzer to report a timeout if a single input took more than X seconds
even if the ALRM did not fire. This will work against slow inputs (that take > X but eventuall finish), but won't work against infinite loops (i.e. it's a partial solution)

**Comment by kcc** [comment]
here is a proposal: 
  * support SIGALRM interception in sanitizers
  * by default, set handle_alrm to 0
  * on handle_alrm > 0, install a handler that calls a user-provided callback (via __sanitizer_set_sigalrm_callback)

@vitalybuka WDYT?

**Comment by vitalybuka** [comment]
Why not in libFuzzer? It looks very libFuzzer specific.

**Comment by kcc** [comment]
sanitizers have the interception machinery, which is too hairy to have it re-implemented in libFuzzer

**Comment by oliverchang** [comment]
Re handle_signal=2, which llvm revision introduced it?

For our current builds with ASAN_OPTIONS=help=1, I'm not seeing "2" in the documentation:
```
        handle_segv
                - Controls custom tool's SIGSEGV handler (0 - do not registers the handler, 1 - register the handler).
```

Will it break if we set handle_signal=2 before we pick up the llvm change?

**Comment by vitalybuka** [comment]
It was introduced in r303941

**Comment by vitalybuka** [comment]
before r303941 you can set allow_user_segv_handler=0

**Comment by kcc** [comment]
See also https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1916#c7
where our recent changes in asan are causing trouble (sorry!)

I wonder if we can bump the llvm revision manually. 
Since recently we started following the chrome's clang revision, 
but maybe we should simply ping a revision of our own and periodically bump it?

**Comment by kcc** [comment]
One alternative: bump the revisions manually, but only to the revisions tested by Chrome (unless there is a urgency like this one)

**Comment by vitalybuka** [comment]
Actually I don't see this as revision issues.
Here manual replacing handle_signal=1 to handle_signal=2 was required anyway.
So it's rather my fault to notify oss-fuzz and chromium. I am very sorry for that.

**Comment by oliverchang** [comment]
argh, unfortunately we cannot just set handle_signal=2 everywhere, since we still need to run older builds for regression and fixed testing, and setting handle_signal=2 isn't backwards compatible and break those things..... is there anything that can be done on the sanitizers side to make this backwards compatible?

For now we may need to roll back the clang revision.

**Comment by oliverchang** [comment]
Discussed offline with @vitalybuka 

We need sanitizer options to be backwards compatible across builds. with handle_signal=2 unfortunately if we pass it to an older build we get a hard failure:

```
ERROR: Invalid value for bool option: '2'
ERROR: Flag parsing failed.
```

Adding new flags should be fine, because if we pass it to an older build we don't get a hard failure.

@vitalybuka said he will make a compatibility fix soon

Tracking this issue chromium side in https://bugs.chromium.org/p/chromium/issues/detail?id=731130#c10. If we don't get a revert there I'll manually pin our revision to the previous one.

**Comment by inferno-chromium** [comment]
What is the plan here ?

**Comment by nsajko** [comment]
Is the solution for this not for libFuzzer to do either either of these things that require POSIX:

* use SIGEV_THREAD with timer_create and timer_settime

* look for available signals (after the fuzzer starts) in the range SIGRTMIN:SIGRTMAX using sigaction and use what you find

* use a couple signals on the edge of the SIGRTMIN:SIGRTMAX range and then adjust that range with an interceptor function (like AddressSanitizer uses for malloc, etc.)
