### ISSUE TITLE
Firefox build failed

### ISSUE THREAD

**Issue by bajinsheng** [google/oss-fuzz#6751]
[https://github.com/google/oss-fuzz/blob/master/projects/firefox/Dockerfile#L38](Dockerfile#38) This line call mach script, but I always get timeout connection when building it locally. The error like this:

> 0:04.63 Downloading artifact to local cache: /root/.mozbuild/toolchains/1fd43b6c1d686102-clang.tar.zst
0:04.82 Downloading... 0.0 %
0:04.95 Downloading... 5.0 %
0:05.06 Downloading... 10.0 %
0:05.15 Downloading... 15.0 %
0:05.26 Downloading... 20.0 %
0:05.33 Downloading... 25.0 %
0:05.64 Downloading... 30.0 %
0:05.80 Downloading... 35.0 %
0:05.86 Downloading... 40.0 %
0:05.95 Downloading... 45.0 %
0:06.02 Downloading... 50.0 %
0:06.09 Downloading... 55.0 %
0:06.18 Downloading... 60.0 %
0:06.26 Downloading... 65.0 %
0:06.34 Downloading... 70.0 %
0:06.43 Downloading... 75.0 %
0:06.51 Downloading... 80.0 %
0:06.60 Downloading... 85.0 %
0:06.70 Downloading... 90.0 %
0:06.79 Downloading... 95.0 %
0:06.85 Downloading... 100.0 %
0:07.97 untarring "/root/.mozbuild/clang.tar.zst"
Error running mach:
 ['artifact', 'toolchain', '--bootstrap', '--from-build', 'linux64-cbindgen']
The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.
You can invoke |./mach busted| to check if this issue is already on file. If it
isn't, please use |./mach busted file artifact| to report it. If |./mach busted| is
misbehaving, you can also inspect the dependencies of bug 1543241.
If filing a bug, please include the full output of mach, including this error
message.
The details of the failure are as follows:
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(110, 'Connection timed out'))
  File "/src/mozilla-central/python/mozbuild/mozbuild/artifact_commands.py", line 461, in artifact_toolchain
    record = ArtifactRecord(task_id, artifact_name)
  File "/src/mozilla-central/python/mozbuild/mozbuild/artifact_commands.py", line 315, in __init__
    cot = cache._download_manager.session.get(
  File "/src/mozilla-central/third_party/python/requests/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)

I use the latest version code and docker images and only run this command:
`python infra/helper.py build_image firefox`

**Comment by DavidKorczynski** [comment]
Thanks! Any updates or patches to fix the build are appreciated!

**Comment by DavidKorczynski** [comment]
Closing this one as we're aware that some builds may fail at times. Hopefully maintainers will get time to fix it and, naturally,  any assistance is appreciated.
