### ISSUE TITLE
Iterating on build.sh is slow because libFuzzerEngine must be built every change

### ISSUE THREAD

**Issue by zachriggle** [google/oss-fuzz#676]
When spinning up a new project, it may not play nicely with the flags introduced by oss-fuzz.

As a first-time project integrator, it seems that the workflow is sub-optimal for interacting with the build process.  "FROM gcr.io/oss-fuzz-base/base-builder" indicates that everything should be set-up and ready-to-go.

Unfortunately, this isn't the case.  First, libFuzzerEngine needs to be built, and there doesn't seem to be a way to get a Docker image which has it pre-built, as it's build with `CMD` instead of with a `Dockerfile` command.

Since `libFuzzerEngine.a` is missing, one can run into weird issues when using oss-fuzz the first time.  All of the documentation says `/usr/lib/libFuzzerEngine.a` should exist, but:

```
$ docker run -it gcr.io/oss-fuzz-base/base-builder find /usr/ | grep Fuzz
<nil>
```

This is counter-intuitive.  The "correct" way to build the fuzzer is not `RUN build.sh` but rather to invoke `compile` via the default `CMD ["compile"]` rule (which is reflected in the docs, but not expected).

When trying to get the build to *work* at all, one will make lots of edits to `build.sh`.  The way that oss-fuzz is currently set up, there's no way to e.g. `docker run -it foo/bar/baz bash` just before `build.sh` is invoked.  One *can* just put `bash` inside of `build.sh` to invoke a shell, but that means that e.g. `libFuzzer` must be re-built for every change, which is slow.

I'd recommend re-architecting the build process for `libFuzzerEngine.a` such that all of the fuzzers are pre-built, and the default (libFuzzer) is pre-selected.  The replacement `CMD` can then just select the correct one via symlink, rather than building it on-the-fly.

**Comment by oliverchang** [comment]
Thanks for bringing this up.

The intention of the oss-fuzz build scripts is to be a thin layer on top of the upstream build system. That is, the bulk of the build system logic should be implemented upstream and easily tested without needing Docker.

That said, we have a command:

```
python infra/helper.py shell PROJECT_NAME
```

which essentially runs `docker run -ti gcr.io/oss-fuzz/PROJECT_NAME /bin/bash`

That drops you a shell inside the project image. From there, you may do `. compile` and manually invoke `$SRC/build.sh` afterwards to avoid the fuzzing engine rebuild. Does that address your use case? (We probably need to improve our docs here).

We may explore the option of prebuilding fuzzing engines, but the intention was that fuzzing engine builds may need to be configurable by the project.

**Comment by kcc** [comment]
Docker file is per project and the particular  `libFuzzerEngine.a` is per build config. 
We could theoretically build all engines (libFuzzer, AFL, hoggfuzz) in base-builder and then symlink
one of them to libFuzzerEngine.a depending on the build config. 
But then we risk that the pre-built fuzzing engine(s) will be misused (and instead of 3 different engines we'll get e.g. 3 libFuzzer builds) 

Please try `infra/helper.py shell` -- it should address your concerns.

**Comment by zachriggle** [comment]
The issue with `shell` is that it still precedes the build of the `FuzzerEngine`.  Normally, I would just be able to add `compile-fuzzer-engine` as a `RUN` step in my Dockerfile, so that I can interact with that environment after it's built.

However, there is only `compile`, which attempts to build *both* `FuzzerEngine` **and** the fuzz target via `build.sh`.  If these could be separated into two separate commands, it should resolve the problem.

**Comment by oliverchang** [comment]
> However, there is only compile, which attempts to build both FuzzerEngine and the fuzz target via build.sh. If these could be separated into two separate commands, it should resolve the problem.

Please see my comment in https://github.com/google/oss-fuzz/issues/676#issuecomment-307990197 about `. compile` and running `$SRC/build.sh` on its own. Does that address your use case?

**Comment by zachriggle** [comment]
The suggestion in the cited comment effectively invokes `build.sh` twice:

https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile#L52-L59

My suggestion is to separate this portion from the `build` script, either by refactoring `build` into two separate commands (e.g. `build-fuzzengine` and `build-fuzztarget`) which can each be invoked by `build`.  I can then manually `RUN build-fuzzengine` in my Dockerfile, which will save the output.  The former will build `libFuzzerEngine`, and the latter will set environment variables and invoke `build.sh`.

**Comment by Dor1s** [comment]
WontFixing an old issue. We've had a couple hundreds new project integrated since then and the existing pipeline seemed to work fine.
