### ISSUE TITLE
Q regarding bug in underlying library

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#678]
Bug [2262](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2262) is due to an *ancient* libidn2 in the docker image. BTW, that version is full of bugs that already have been fixed upstream (I am one of the maintainers).

I don't see any chance to get the latest libidn2 into Trusty (or any of the bug fixes) and even if they do something it'll take a long time.

Q1. How can I 'disable' / ignore this bug in OSS-Fuzz ?
Q2. The Oss-Fuzz FAQ mentions 'CC'ing' someone (in this case Debian or Ubuntu). How to do that without changing the YAML file (the issue/report seems to be protected) ?

**Comment by kcc** [comment]
There is no easy way to suppress such bugs in OSS-Fuzz. (report suppression is a messy business)
The best you can do here is to extend the libpsl Dockerfile/build.sh to pull/build the fresher libidn2
(either top of tree, or the latest release)

> 'CC'ing' someone (in this case Debian or Ubuntu)

I'm afraid only we (the admins) can do that. ( @oliverchang right? Do we have plans to change this?). 
Just tell us who you want to be CC-ed to the particular bug. 

Also, please try to encourage the libidn2 maintainers to join OSS-Fuzz

**Comment by oliverchang** [comment]
> I'm afraid only we (the admins) can do that. ( @oliverchang right? Do we have plans to change this?).
Just tell us who you want to be CC-ed to the particular bug.

I'm afraid this is a limitation on the monorail side.

**Comment by rockdaboot** [comment]
Thanks for the info. Maybe the text in your FAQ should be amended then:
```
If this is a real bug in the dependent project, then you should CC the maintainers of that project on the bug.
```

In this special case, IMO the best option is to open a bug at Ubuntu with a small reproducer C code. The corpus is just 3 bytes long. Kind of a disclosure, but anyways it is easy to find bugs that have been fixed in recent versions if you look at the repo.
