### ISSUE TITLE
Option to opt-in for -fsanitize=undefined,unsigned-integer-overflow ?

### ISSUE THREAD

**Issue by rouault** [google/oss-fuzz#682]
unsigned-integer-overflow is disabled by default for understandable reasons (unsigned integer overflow is well defined by the C/C++ standards), but quite often this can still be unwanted behaviour. In case this is intended, functions can be marked with __attribute__((no_sanitize("unsigned-integer-overflow"))) .

I guess a dirty way would be to analyze CPPFLAGS in build.sh and if -fsanitize=undefined is found, hack into it ,unsigned-integer-overflow. But it would be good if there was a clean way to opt-in for such sanitizer.

**Comment by Dor1s** [comment]
We've discussed it recently and decided that it might be useful to make UBSan flags more configurable (i.e. some projects may want to disable some of our default flags while others may want more UBSan checks to be enabled). Stay tuned :)

**Comment by LebedevRI** [comment]
Can some progress *please* happen here?
Many of the reports i'm having (or worse, not even having) are actually an unsigned integer overflow, instead of OOM/etc.

**Comment by Dor1s** [comment]
@LebedevRI, could you please elaborate? I've just checked the issues available for librawspeed, and noticed the following:

A) a couple of timeouts / OOMs found with ASan

B) a few more OOMs with MSan -- quite expected, MSan has a larger memory overhead

C) several integer overflows with UBSan, all of them seem to be valid, e.g. `runtime error: signed integer overflow: -2147450776 + -65535 cannot be represented in type 'int'`

**Comment by LebedevRI** [comment]
E.g. the last one:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4440 was fixed by https://github.com/darktable-org/rawspeed/commit/ddd9d4bd666d492ed7f0a58da87caac58c69bbb7

The cast was converting huge unsigned x/y into negative signed, thus these checks did not fail.
And unsigned multiplications in `return &data[static_cast<size_t>(y) * pitch + x * bpp];`  overflowed, returning a pointer to some wrong memory, thus the crash.

**Comment by LebedevRI** [comment]
(i guess what i would also want is "value-changing cast" sanitizer https://github.com/google/sanitizers/issues/885#issuecomment-346899629, but it does not even exist yet in llvm :))

**Comment by Dor1s** [comment]
Ah, I see what you mean, thanks. I believe that you can do something like https://github.com/google/oss-fuzz/blob/master/projects/llvm_libcxx/build.sh#L19 for now:

```bash
if [[ $SANITIZER = *undefined* ]]; then
  CXXFLAGS="$CXXFLAGS -fsanitize=unsigned-integer-overflow -fsanitize-trap=unsigned-integer-overflow"
fi
```

**Comment by kcc** [comment]
Probably `fno-sanitize-recover` instead `fsanitize-trap`

**Comment by LebedevRI** [comment]
Ok, thanks @Dor1s and @kcc, ugly temporary hacks it is :) #1011

**Comment by inferno-chromium** [comment]
Adding it in CXXFLAGS is the recommended way.
