### ISSUE TITLE
How often is clang updated?

### ISSUE THREAD

**Issue by MarcoFalke** [google/oss-fuzz#6829]
We ran into some compiler bugs earlier this month and fixed them in clang. How long will it approx. take for the updates to hit oss fuzz?

**Comment by jonathanmetzman** [comment]
There's no fixed schedule.
We update whenever chrome updates their clang.
That seems to be every 2 weeks about.
Tracking bug for current roll is here: https://bugs.chromium.org/p/chromium/issues/detail?id=1269407&q=roll%20clang&can=1

**Comment by MarcoFalke** [comment]
Thanks, I'll watch the issue.
