### ISSUE TITLE
Fixed issue kept open forever

### ISSUE THREAD

**Issue by rouault** [google/oss-fuzz#683]
Issue https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1583 / testcase https://oss-fuzz.com/v2/testcase-detail/5709498763182080?noredirect=1 appears to be non-closable manually and without any automatic closing deadline. However the issue has been fixed for more than a month.

It seems related to the fact that the testcase belongs to a group and is linked to another issue https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1582 , which is now in closed state

**Comment by oliverchang** [comment]
I think there may have been a race condition here with the grouping and filing, leading to the testcase for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1583 losing its testcase association.

This is tracked at https://bugs.chromium.org/p/chromium/issues/detail?id=731257 internally. @inferno-chromium , mind taking a look when you get the chance?

**Comment by oliverchang** [comment]
This should be fixed now. Thanks @inferno-chromium !
