### ISSUE TITLE
Finding out CPU where bug was reproduced

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#6834]
@guidovranken suspects this one is CPU dependent: https://oss-fuzz.com/testcase-detail/5703397865553920

**Comment by jonathanmetzman** [comment]
I think the testcase was deleted. Can't track it down now.

**Comment by catenacyber** [comment]
Maybe also ?
https://github.com/golang/go/issues/49075
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37855&q=label%3AProj-gonids
https://oss-fuzz.com/testcase?key=5194651375108096
