### ISSUE TITLE
afl miscompiling fribidi?

### ISSUE THREAD

**Issue by tsdgeos** [google/oss-fuzz#6847]
I' ve been trying to figure out what's wrong in https://oss-fuzz-build-logs.storage.googleapis.com/log-61b89a67-51d0-4854-98e9-3f81038e1dc5.txt

And i think i may have found a problem in afl (or clang?)

When running gdb over the binary compiled with afl it segfaults at line 336 of https://github.com/fribidi/fribidi/blob/master/gen.tab/packtab.c#L336

But then i've added printf of j, i, jj and they are all in valid bounds and i've added printf of x[j],  x[i] x[jj] and it does not segfault there, just in the if in the next line after the printf.

Is it possible that it's a miscompilation?  How would I contact the authors to bring this up?

**Comment by DavidKorczynski** [comment]
Although the crash is a bit different, could this be related to https://github.com/google/oss-fuzz/issues/6839?

**Comment by tsdgeos** [comment]
In that issue you say the fix is merged, but i can still reproduce the crash now, so probably different?

**Comment by DavidKorczynski** [comment]
It depends on whether the base images have been updated with the recent AFL - could we check in on this again tomorrow or so?

**Comment by tsdgeos** [comment]
Sure :)  is there a way to know if the AFL that is being run has the fix (version number or something)?

**Comment by tsdgeos** [comment]
Seems it fixed itself https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40978

**Comment by DavidKorczynski** [comment]
Thanks @tsdgeos - there was a fix in AFL so it's probably this: https://github.com/google/oss-fuzz/pull/6866
