### ISSUE TITLE
istio - fuzzers do not seem to run and 404 on stats page

### ISSUE THREAD

**Issue by AdamKorcz** [google/oss-fuzz#6857]
The Istio project has 50+ fuzzers, but it seems like some issues are happening that I'm unable to address:
- Fuzzer statistics page gives "404 no stats": https://oss-fuzz.com/fuzzer-stats?project=istio&fuzzer=libFuzzer&job=libfuzzer_asan_istio&group_by=by-fuzzer
- No bug reports have been issued in the last ~2 months, but the fuzzers should be uncovering some issues.

The fuzzers build and run fine locally with the Docker images (minor exception today, but this is fixed).

**Comment by AdamKorcz** [comment]
@oliverchang this may be something in the clusterfuzz backend?

**Comment by oliverchang** [comment]
Thanks for flagging! It looks like these machines are running out of disk, so I'll bump that and see how this recovers.

**Comment by AdamKorcz** [comment]
Thanks. Closing as this is solved.
