### ISSUE TITLE
Accessing corpora

### ISSUE THREAD

**Issue by Mizari** [google/oss-fuzz#686]
Hello.

I've got a question: is it possible for a third party to access generated corpus for independent fuzzing?

Edit: is it also possible to access projects' components and installation scripts?

**Comment by oliverchang** [comment]
> I've got a question: is it possible for a third party to access generated corpus for independent fuzzing?

The corpora for projects are not publicly accessible right now. Only the project members in the project.yaml file may access them, but this may change in the near future.

> Edit: is it also possible to access projects' components and installation scripts?
Could you clarify what you mean by this question? All of our build configuration and scripts are public.

**Comment by Mizari** [comment]
I meant scripts to download, install and start fuzzing. By components I meant some parts of projects that are to be fuzzed.  
  
I now see them. Are build configuration and scripts located in oss-fuzz/projects/XXX ?
Is build.sh installing script? Some projects lack them.
Do docker images contain components? Again, some projects lack them. :(

**Comment by oliverchang** [comment]
> I meant scripts to download, install and start fuzzing. By components I meant some parts of projects that are to be fuzzed.

Our build scripts are public, but our fuzzing infrastructure is not. 

However, our build scripts do provide a basic way to run fuzzers. Please see our documentation, which should answer most of your questions about how projects are integrated with oss-fuzz: https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md

> I now see them. Are build configuration and scripts located in oss-fuzz/projects/XXX ?
Is build.sh installing script? Some projects lack them.
Do docker images contain components? Again, some projects lack them. :(

Some projects have these files as part of the upstream repository, not in the oss-fuzz repository.
