### ISSUE TITLE
Python packages installed with apt-get can't be found by Python

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#6868]
That's another issue brought by `scorecard` complaining about `pip install`: https://github.com/ossf/scorecard/issues/1306

`systemd` installs `meson`, `ninja` and `jinja2` with `pip` and `scorecard` complains about that. And while `pip` is used to install the latest versions of `meson` and `ninja` and can't be avoided there, `jinja2` is a bit different in the sense that it's installed that way simply because `apt-get install python3-jinja2` doesn't work
```
apt-get install -y python3-jinja2

python3 -c 'import jinja2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'jinja2'

PYTHONPATH=/usr/lib/python3/dist-packages/ python3 -c 'import jinja2' && echo jinja2 was found
jinja2 was found
```
I wonder if it's intentional or it was just missed accidentally when the base-builder image started building python itself to fuzz python projects

**Comment by jonathanmetzman** [comment]
>I wonder if it's intentional or it was just missed accidentally when the base-builder image started building python itself to fuzz python projects

It's probably related to that or to the fact that the python in the 16.04 image was ancient.
We can try to fix this.

**Comment by evverx** [comment]
I wonder how long you are planning to keep Ubuntu Focal as a base image? On second thought I'm kind of concerned that at some point the version of Python OSS-Fuzz builds will diverge from the version of Python all the packages installed with `apt-get` are supposed to work.

**Comment by evverx** [comment]
In the meantime, I got it around with
```
    ORIG_PYTHONPATH=$(python3 -c 'import sys;print(":".join(sys.path[1:]))')
    export PYTHONPATH="$ORIG_PYTHONPATH:/usr/lib/python3/dist-packages/"
```

**Comment by jonathanmetzman** [comment]
> I wonder how long you are planning to keep Ubuntu Focal as a base image? On second thought I'm kind of concerned that at some point the version of Python OSS-Fuzz builds will diverge from the version of Python all the packages installed with `apt-get` are supposed to work.

Probably for at least a few years.
Someone on my team suggested upgrading the ubuntu image on a "rolling" basis, but I don't think we are really considering this.

**Comment by evverx** [comment]
Looking at https://github.com/google/oss-fuzz/issues/7914 it seems this issue can't be fixed. It should be fine though as long as the workaround works.
