### ISSUE TITLE
How to (auto-)download the corpora

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#687]
I would like to script the download of the corpora for each fuzzer to automatically merge/update them.
The manual download is pretty tedious with more and more fuzzers...
Are there any links (without authentication !?) or what is the suggested procedure ?

**Comment by inferno-chromium** [comment]
Use gsutil with wildcards, see https://github.com/google/oss-fuzz/blob/master/docs/corpora.md

**Comment by inferno-chromium** [comment]
I can you can just download everything in gs://wget2-backup.clusterfuzz-external.appspot.com/corpus using gsutil

**Comment by rockdaboot** [comment]
Thanks for the pointer !

**Comment by rockdaboot** [comment]
I spent 2h hours now (without success) reading and doing all those docs., installed all the software, gcloud init/auto/login/whatever... but still `gsutil -m rsync gs://<bucket> .` shows me
```
ServiceException: 401 Anonymous users does not have storage.objects.list access to bucket libpsl-corpus.clusterfuzz-external.appspot.com.
```

I found several issues when searching with a lot of tips what to do... but none was helpful.
What I really miss is a simple (functional !) step-by-step instruction.

**Comment by rockdaboot** [comment]
Uninstalled and reinstalled everything, now it works. Not sure what was wrong.

**Comment by inferno-chromium** [comment]
Maybe gsutil config, that is required to setup creds.
