### ISSUE TITLE
CIFuzz does not upload crashes

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#6885]
On project Suricata, CIFuzz found a bug 
https://github.com/OISF/suricata/runs/4288032285?check_suite_focus=true
But we do not have the reproducer test case 

We see the log
> root - INFO - Not uploading crashes because on OSS-Fuzz.

But we are not on oss-fuzz there...

cc @jonathanmetzman

**Comment by evverx** [comment]
> Not uploading crashes because on OSS-Fuzz

I'm not sure where this kind of misleading message comes from but the artifacts were successfully uploaded and can be found at https://github.com/OISF/suricata/actions/runs/1490732347

I think it's related to https://github.com/google/oss-fuzz/issues/5381 as well

**Comment by catenacyber** [comment]
Thanks @evverx

**Comment by evverx** [comment]
FWIW I think it would make sense to keep this issue open because that misleading message shouldn't be there I think. If I hadn't run into #5381 I would have thought that the artifacts weren't uploaded as well
