### ISSUE TITLE
Java coverage looks suspicious. Only including fuzz target?

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#6926]
@fmeum 
Check out some of the coverage reports for java projects:
https://storage.googleapis.com/oss-fuzz-coverage/protobuf-java/reports/20211129/linux/index.html
https://storage.googleapis.com/oss-fuzz-coverage/gson/reports/20211128/linux/index.html
https://storage.googleapis.com/oss-fuzz-coverage/jsoup/reports/20211128/linux/index.html

**Comment by fmeum** [comment]
This looks very wrong, will investigate.

**Comment by fmeum** [comment]
It's a subtle escaping bug that's ultimately caused by libFuzzer using `system()` to launch processes without escaping the arguments. We had a workaround in Jazzer for that in the past and I will revive it now.

**Comment by fmeum** [comment]
@jonathanmetzman Should be fixed with Jazzer HEAD. FYI, if you ever run into issues with subprocesses invoked by libFuzzer in other settings (e.g. Atheris), the following patch is necessary to unbreak argument passing: https://github.com/CodeIntelligenceTesting/llvm-project-jazzer/commit/b19be4a4f32f7b5441c5e004f4a9034cd6679b3d. I will see whether I can get this submitted upstream.

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman Should be fixed with Jazzer HEAD. FYI, if you ever run into issues with subprocesses invoked by libFuzzer in other settings (e.g. Atheris), the following patch is necessary to unbreak argument passing on Linux and Windows: [CodeIntelligenceTesting/llvm-project-jazzer@b19be4a](https://github.com/CodeIntelligenceTesting/llvm-project-jazzer/commit/b19be4a4f32f7b5441c5e004f4a9034cd6679b3d). I will see whether I can get this submitted upstream.

Are we using Jazzer HEAD in OSS-Fuzz? Will this change be included in OSS-Fuzz without additional action?

**Comment by fmeum** [comment]
> > @jonathanmetzman Should be fixed with Jazzer HEAD. FYI, if you ever run into issues with subprocesses invoked by libFuzzer in other settings (e.g. Atheris), the following patch is necessary to unbreak argument passing on Linux and Windows: [CodeIntelligenceTesting/llvm-project-jazzer@b19be4a](https://github.com/CodeIntelligenceTesting/llvm-project-jazzer/commit/b19be4a4f32f7b5441c5e004f4a9034cd6679b3d). I will see whether I can get this submitted upstream.
> 
> Are we using Jazzer HEAD in OSS-Fuzz? Will this change be included in OSS-Fuzz without additional action?

Yes, you are living at HEAD :-) We should just have to wait until `base-builder-jvm` is rebuilt.

**Comment by fmeum** [comment]
Coverage looks sensible again, @jonathanmetzman.
https://storage.googleapis.com/oss-fuzz-coverage/protobuf-java/reports/20211201/linux/index.html
https://storage.googleapis.com/oss-fuzz-coverage/jsoup/reports/20211201/linux/index.html

**Comment by jonathanmetzman** [comment]
Indeed.
