### ISSUE TITLE
Fuzzing failures for Django

### ISSUE THREAD

**Issue by apollo13** [google/oss-fuzz#6937]
Hi there, we currently get those failures:
```
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: [/corpus/fuzzer-utils.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/fuzzer-utils.zip or
Step #5:         /corpus/fuzzer-utils.zip.zip, and cannot find /corpus/fuzzer-utils.zip.ZIP, period.
Step #5: Failed to unpack the corpus for fuzzer-utils. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
Step #5: ********************************************************************************
Step #5: Code coverage report generation failed.
Step #5: To reproduce, run:
Step #5: python infra/helper.py build_image django
Step #5: python infra/helper.py build_fuzzers --sanitizer coverage django
Step #5: python infra/helper.py coverage django
Step #5: ********************************************************************************
```
https://oss-fuzz-build-logs.storage.googleapis.com/log-d6cfb65a-2d0f-481d-a1ed-7d9b3b077a89.txt
and have no idea on how to address them. Any chance someone could lead us a hand?

**Comment by asraa** [comment]
Hi, looking at this https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2021-01-01&date_end=2021-11-30&fuzzer=libFuzzer_django_fuzzer-utils&project=django

it seems like corpus_size last had posted info in mid-march, and probably by now the last corpus backup was deleted and so you're seeing failures due to missing corpus backup. did something change to the target around mid-march?

**Comment by DavidKorczynski** [comment]
In addition to this, I'm not entirely sure about this but do you keep the corpus hardcoded in your setup? The folder `corp-utils` [here](https://github.com/django/django-fuzzers)  seems to hold the corpus? I think that might be related to what Jonathan describes here https://github.com/google/oss-fuzz/pull/6754#pullrequestreview-797042474

**Comment by apollo13** [comment]
> it seems like corpus_size last had posted info in mid-march 

No we didn't change anything since January

@DavidKorczynski thank you, I will try that. Are there any docs somewhere about how that whole thing is supposed to work? :) If I remove the hardcoded corpus, how long should I wait to see changes?

**Comment by DavidKorczynski** [comment]
> > it seems like corpus_size last had posted info in mid-march
> 
> No we didn't change anything since January
> 
> @DavidKorczynski thank you, I will try that. Are there any docs somewhere about how that whole thing is supposed to work? :) If I remove the hardcoded corpus, how long should I wait to see changes?

Docs: https://google.github.io/oss-fuzz

I am not sure if the corpus removal will fix it, because in a sense it's a valid operation in that the seed corpus folder seems to be okay and should not cause issues. However, I tried to build and run the fuzzer, and it looks like it fails instantly?
```
Traceback (most recent call last):
  File "<string>", line 331, in FuzzerRunOne
  File "<string>", line 116, in test_get_valid_filename
  File "/out/django/utils/functional.py", line 230, in wrapper
    return func(*args, **kwargs)
  File "/out/django/utils/text.py", line 237, in get_valid_filename
    raise SuspiciousFileOperation("Could not derive file name from '%s'" % name)
django.core.exceptions.SuspiciousFileOperation: Could not derive file name from ''
AddressSanitizer:DEADLYSIGNAL
=================================================================
==12==ERROR: AddressSanitizer: ABRT on unknown address 0x00000000000c (pc 0x7fc64248218b bp 0x7ffefe0e2920 sp 0x7ffefe0e25f0 T0)
SCARINESS: 10 (signal)
    #0 0x7fc64248218b in raise (/lib/x86_64-linux-gnu/libc.so.6+0x4618b)
    #1 0x7fc642461858 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x25858)
    #2 0x58a53e in LLVMFuzzerTestOneInput /src/django-fuzzers/fuzzer.cpp:145:9
    #3 0x47d603 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) cxa_noexception.cpp
    #4 0x47cdea in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) cxa_noexception.cpp
    #5 0x47ec44 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) cxa_noexception.cpp
    #6 0x47ee79 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) cxa_noexception.cpp
    #7 0x46e8bd in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) cxa_noexception.cpp
    #8 0x497902 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #9 0x7fc6424630b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #10 0x44619d in _start (/out/fuzzer-utils+0x44619d)

```

**Comment by apollo13** [comment]
Interesting I will have to digg into the docs and see if I can get this running then… But this begs another question: The docs list ujson as a "good" example for python; but Django seems to use a c++ based fuzzer. Is this still required or is that just the case because Django is this "old" when it got added? If it is the latter I will try to port it over to python, what do you think?

**Comment by DavidKorczynski** [comment]
> if it is the latter I will try to port it over to python, what do you think?

It is a case of the latter. Am not sure if this helps, but we did briefly discuss Django fuzzers here https://github.com/google/oss-fuzz/pull/4754#issuecomment-736086159

I think that's a good idea to migrate to Python set up and most likely this will improve stability. Python support also includes native code, and to see an example of a set up perhaps Pillow is a nice one https://github.com/google/oss-fuzz/tree/master/projects/pillow

**Comment by apollo13** [comment]
Thank you, I will work on that then. Shall I leave this ticket open in the meantime or open new ones as I go along?

**Comment by DavidKorczynski** [comment]
You can leave it open and ask questions here in case!

**Comment by apollo13** [comment]
Ok I was able to build a python fuzzer locally. I pushed them to https://github.com/django/django-fuzzers/tree/python-fuzzer since I have a few questions about them.

 * I am currently just fuzzing one function: https://github.com/django/django-fuzzers/blob/python-fuzzer/basic_fuzzer.py#L7 -- I am not exactly sure what the proper way for multiple functions is. Add `*_fuzzer.py` for all of them or are there more "intelligent" ways? The old cpp code tried to select one function based on the fuzzing input https://github.com/django/django-fuzzers/blob/35403d43e74a3be3afdfee629db49cf6480780c6/utils.py#L323 -- is this a good approach?

 * https://google.github.io/oss-fuzz/getting-started/new-project-guide/python-lang/#buildsh recommends "pip3 install .". This will download prebuilt wheels for dependencies and those will then not be built with the proper CFLAGS, is this expected/wanted?

 * I am currently instrumenting the whole kitchensink ( https://github.com/django/django-fuzzers/blob/python-fuzzer/basic_fuzzer.py#L3 ), what would be a good idea to instrument, solely the functions required for the run?

I hope those questions are not to naive, please let me know when I should go and RTFM instead.

**Comment by asraa** [comment]
> Add *_fuzzer.py for all of them or are there more "intelligent" ways? The old cpp code tried to select one function based on the fuzzing input https://github.com/django/django-fuzzers/blob/35403d43e74a3be3afdfee629db49cf6480780c6/utils.py#L323 -- is this a good approach?

Both approaches are OK. Generally people may bundle all functions of a module into a select based on fuzzed inputs as you linked second in the cpp code. It's probably best for simple functions who's coverage is easily analyzed so the engine can mutate inputs intelligently to cover and explore all functions.

> This will download prebuilt wheels for dependencies and those will then not be built with the proper CFLAGS, is this expected/wanted?

I may not understand, the CFLAGS are provided in the environment and should be picked up by the pip3 install

> what would be a good idea to instrument, solely the functions required for the run?

Probably anything you want to explore for the purposes of fuzzing. You can even instrument individual functions. If a module is uninteresting (lets say, only operates on trusted or fixed values and doesn't interact with the fuzzed inputs), then no need to instrument it.

**Comment by apollo13** [comment]
> I may not understand, the CFLAGS are provided in the environment and should be picked up by the pip3 install

Yes but pip downloads dependencies as pre-built wheel files which are then only extracted -- so the dependencies are not compiled at all usually.

> Probably anything you want to explore for the purposes of fuzzing.

Okay, I guess I'll leave it as is then :)

**Comment by apollo13** [comment]
I have added #6940 and updated our fuzzing repo to work with that. It would be great if someone could merge that and maybe trigger a run?

**Comment by apollo13** [comment]
I have investigated the failures from the testrun today and it seems it still runs the CPP based variant, when will the images update to the python variant?

**Comment by asraa** [comment]
Hey, it looks like the latest build is from the Python based fuzzers https://oss-fuzz-build-logs.storage.googleapis.com/log-1031f521-1540-4d6d-a623-112be257ed37.txt

How did you come by the CPP based variant? Or maybe that was uploaded after you commented?

**Comment by apollo13** [comment]
Oh yes, I still had your initial link which had the wrong fuzzer selected… I will look through the new results.

**Comment by apollo13** [comment]
Mhm where can I find a nice overview of the builds? https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2021-11-29&date_end=2021-12-02&fuzzer=libFuzzer_django_basic_fuzzer&project=django lists nothing yet (and selecting libFuzzer doesn't have any logs)

**Comment by apollo13** [comment]
Okay, looking at the last runs the new fuzzers are picked up properly and executing fine. I will work on improving them in the future.  Thank you for your help @asraa & @DavidKorczynski -- closing this for now :)
