### ISSUE TITLE
CIFuzz does not detect repo

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#6942]
In clamav this error condition gets triggered https://github.com/google/oss-fuzz/blob/1ece14aeb26967eb7d7cefb55e6ca4ad10dc6d33/infra/cifuzz/continuous_integration.py#L135

Error log https://pipelines.actions.githubusercontent.com/pnTmDXqcG0N03YoUZ5j61ay9a3Sslr6gCHihzJ7AzbOQtwBDde/_apis/pipelines/1/runs/952/signedlogcontent/2?urlExpires=2021-11-30T20%3A22%3A34.7727648Z&urlSigningMethod=HMACV1&urlSignature=IWdmcCqhV9N3FnmYoAW8MwXS5lkAE%2FRAExHSVq8QmlA%3D

PR https://github.com/Cisco-Talos/clamav/pull/391

@jonathanmetzman is this something you would want to fix or should I modify the clamav set up?

**Comment by jonathanmetzman** [comment]
> Error log https://pipelines.actions.githubusercontent.com/pnTmDXqcG0N03YoUZ5j61ay9a3Sslr6gCHihzJ7AzbOQtwBDde/_apis/pipelines/1/runs/952/signedlogcontent/2?urlExpires=2021-11-30T20%3A22%3A34.7727648Z&urlSigningMethod=HMACV1&urlSignature=IWdmcCqhV9N3FnmYoAW8MwXS5lkAE%2FRAExHSVq8QmlA%3D

This link is expired. Github actions has some areas that could use improvement.

**Comment by DavidKorczynski** [comment]
huh - interesting!

End or the log:
```
Removing intermediate container 52f28485b1b6
 ---> 7f68f17b4e66
Step 7/10 : RUN git clone --depth 1 https://github.com/Cisco-Talos/clamav-devel.git
 ---> Running in 82c596584163
Cloning into 'clamav-devel'...
Removing intermediate container 82c596584163
 ---> baffb64fc745
Step 8/10 : RUN git clone --depth 1 https://github.com/Cisco-Talos/clamav-fuzz-corpus.git
 ---> Running in ea41ac34cdd3
Cloning into 'clamav-fuzz-corpus'...
Removing intermediate container ea41ac34cdd3
 ---> 6ba5194495ec
Step 9/10 : WORKDIR clamav-devel
 ---> Running in 211ec98e4d33
Removing intermediate container 211ec98e4d33
 ---> 15037168dc60
Step 10/10 : COPY build.sh $SRC/
 ---> 8e0daa6a1c17
Successfully built 8e0daa6a1c17
Successfully tagged gcr.io/oss-fuzz/clamav:latest
2021-11-30 20:01:55,980 - root - ERROR - Failed to detect repo:
ERROR:root:No git repos with specific commit: None found in /src

2021-11-30 20:01:55,981 - root - ERROR - Could not detect repo.
2021-11-30 20:01:55,981 - root - ERROR - Error building fuzzers for (commit: e246d7128ed6e8024c06a73a81e56e2171912f47, pr_ref: refs/pull/391/merge).
```
CI (hopefully permanent) link: https://github.com/Cisco-Talos/clamav/runs/4372641750?check_suite_focus=true

**Comment by DavidKorczynski** [comment]
I would think the issue is in the Dockerfile, as it seems likely it's not trivial to detect which is the code repo:
https://github.com/google/oss-fuzz/blob/b96b60c7a8451d9e1ebe83e4143a91534e2bb277/projects/clamav/Dockerfile#L26-L38

(it's `clamav-devel`)

**Comment by jonathanmetzman** [comment]
> I would think the issue is in the Dockerfile, as it seems likely it's not trivial to detect which is the code repo:
> 
> https://github.com/google/oss-fuzz/blob/b96b60c7a8451d9e1ebe83e4143a91534e2bb277/projects/clamav/Dockerfile#L26-L38
> 
> (it's `clamav-devel`)

Right. This is the issue.
I was preparing a fix that allows users to specify the repo so we don't need to detect it.
But I think a simpler approach is to force users to use their oss-fuzz-project-name as their repo name. WDYT?
If we go with the latter, then the fix is to clone into /src/clamav

**Comment by DavidKorczynski** [comment]
> But I think a simpler approach is to force users to use their oss-fuzz-project-name as their repo name. WDYT?

I would probably go with this one for now, not least because most repositories will match this anyways (We have gone through ~60 and this is the first instance I have seen of the error). If, down the line, it becomes a bigger issue then we can add the ability to specify it explicitly?

**Comment by DavidKorczynski** [comment]
Closing this as the project with the issue has now been resolved. https://github.com/google/oss-fuzz/pull/6943
