### ISSUE TITLE
Question about exit codes

### ISSUE THREAD

**Issue by afd** [google/oss-fuzz#6960]
In one of my oss-fuzz projects I'm suffering from a kind of false alarm where the fuzzer manages to drive the library into a state from which it can't really recover.

For the purposes of fuzzing, I plan to use a `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION`-guarded code block to detect this and gracefully exit.

I'd prefer to use `exit(1)` over `exit(0)` to make it clear in the source code that this is not *really* OK.

My question is: will OSS-Fuzz regard `exit(1)` as a crash and auto-file a bug?

**Comment by jonathanmetzman** [comment]
I answered this in our chat:
I think `exit(1)` will be regarded as a crash, so better to do `exit(0)`
