### ISSUE TITLE
build failure: afl can't find <stdlib.h> -- NeoMutt

### ISSUE THREAD

**Issue by flatcap** [google/oss-fuzz#6965]
**Project**: NeoMutt
**Issue**: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=41879
**Build log**: https://oss-fuzz-build-logs.storage.googleapis.com/log-ce9947de-6023-4996-9b95-692c91586dc0.txt

My build's stopped working, but only for **afl**.  libfuzzer and honggfuzz still compile.

`configure` can't find `<stdlib.h>`
This check has been there forever.

Running locally, I see the same.

```sh
infra/helper.py build_image neomutt
infra/helper.py build_fuzzers --sanitizer address --engine afl neomutt
infra/helper.py check_build neomutt
```

**output**:
```
Step #3 - "compile-afl-address-x86_64": + ./configure --fuzzing --disable-doc --disable-nls --disable-idn
...
Step #3 - "compile-afl-address-x86_64": Checking for stdlib.h...not found
```

The only differences I see in the logs are the `CC` and `CXX` env vars:
**libfuzzer** (works)
```
CC=clang
CXX=clang++
CFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link
CXXFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++
```

**honggfuzz** (works)
```
CC=clang
CXX=clang++
CFLAGS=[same as above]
CXXFLAGS=[same as above]
```

**afl** (broken)
```
CC=/src/aflplusplus/afl-clang-fast
CXX=/src/aflplusplus/afl-clang-fast++
CFLAGS=[same as above]
CXXFLAGS=[same as above]
```

Has the afl build changed recently?

**Comment by evverx** [comment]
I think it's https://github.com/google/oss-fuzz/issues/6957

**Comment by jonathanmetzman** [comment]
Fixed this.

**Comment by flatcap** [comment]
Confirmed. Thanks!
