### ISSUE TITLE
Issue 41797: failure to build fuzzers

### ISSUE THREAD

**Issue by DanBloomberg** [google/oss-fuzz#6968]
Build failure began with no change in leptonica fuzzer code.
From the log it appears to be a oss-fuzz build configuration problem.
The fuzzers all build properly with address sanitizer, using clang-10 on a local machine.

**Comment by evverx** [comment]
Looking at https://oss-fuzz-build-logs.storage.googleapis.com/index.html#leptonica, I think that's https://github.com/google/oss-fuzz/issues/6957

**Comment by DanBloomberg** [comment]
Thanks.  You're on it.  Closing.
