### ISSUE TITLE
Builds not happening for some projects

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#6983]
Builds for these projects weren't done yesterday:
```
zlib-ng
w3m
resiprocate
libidn2
libssh2
libxml2
lihgthttpd
m4dc
netcdf
nss
perfetto
php
```
Is this another rate limiting issue?

**Comment by oliverchang** [comment]
Thanks for flagging! Yep running into Cloud Build quota issues once again. I'll ask for another bump.

**Comment by jonathanmetzman** [comment]
In fuzzbench we have a similar problem, but i've solved it.
In Fuzzbench, instead of asynchronously sending builds to GCB, we send them synchronously in parallel, so we can enforce a limit on the number of concurrent requests without sacrificing parallelism.
Do you think we should go with that approach?

**Comment by oliverchang** [comment]
That's an interesting idea! However given the much larger scale of OSS-Fuzz and the additional work/maintenance required, let's see how far we can go with quota increases first.

**Comment by oliverchang** [comment]
Quotas are increased.
