### ISSUE TITLE
cannot access details nor test cases.

### ISSUE THREAD

**Issue by HinTak** [google/oss-fuzz#699]
After https://github.com/google/oss-fuzz/pull/696 , I can now read a total of 4 reports ( 2110, 2122, 2363, 2455 ) of freetype2 . But I still cannot access any of the test details or test cases of these 4, nor supposedly about 40+ other reports of freetype2  . I am mainly looking for accessing the test files for these 26:

```
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2047
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2057
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2060
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2062
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2063
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2068
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2075
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2088
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2133
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2137
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2144
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2151
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2153
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2173
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2186
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2216
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2218
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2270
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2278
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2300
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2313
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2323
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2328
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2364
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2384
      https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2391
```

**Comment by inferno-chromium** [comment]
Try now, it should work. The issue is we only add cc to new bugs, not to closed bugs. You should see all bugs with this query https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=label%3AProj-freetype2

**Comment by HinTak** [comment]
Yes, I can list and read AFAIK all the issue reports now, but most of the "Detailed report:" and "Reproducer Testcase" still gives "not authorized". I found only one testcase I can download, after trying a few.

**Comment by HinTak** [comment]
It seems that I can only download test cases which have been verified as closed more than a month ago; and cannot read any "detailed reports". This seems to be the same level of access as anonymous (not logging in at all).

**Comment by inferno-chromium** [comment]
Oliver, any ideas?

**Comment by oliverchang** [comment]
@HinTak, Could you please give the exactly message that you see when trying to view a detailed report?

**Comment by HinTak** [comment]
okay, I just tried to access the detailed in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2057 , which is https://oss-fuzz.com/testcase?key=4719566426996736 . It re-directed me to https://oss-fuzz.com/v2/testcase-detail/4719566426996736?noredirect=1 , and show the below. I have already logged in before the whole process anyway:

```
Access Denied

Please login see this page.

OSS-Fuzz is an effort to provide continuous fuzzing infrastructure for open-source software. You can read more about it here: https://github.com/google/oss-fuzz.
```

So I clicked on the login link anyway, and it did not askme to log in again either, just immediately shows:

```
Access Denied

You (email=HinTak.Leung@gmail.com) are not authorized to access this page!

Please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.

Switch account
Logout

OSS-Fuzz is an effort to provide continuous fuzzing infrastructure for open-source software. You can read more about it here: https://github.com/google/oss-fuzz.
```

Does the capitalization of my e-mail makes any difference? I have initlially used mixed case to register, but have never had problems using all-lower-case in any situation.

**Comment by HinTak** [comment]
I could show you the actual screenshot (with firefox) if needed. issue 2057 is already over a months passed fixed, so I had already gotten the "Reproducer Testcase:" file. (and I think I did not need to log in to get it either)

**Comment by oliverchang** [comment]
Please try again. It looks like it may be an issue with case sensitivity (fixed casing in https://github.com/google/oss-fuzz/commit/8ddf0990048a1d63779d031d8a6500db87c575fd).

**Comment by HinTak** [comment]
Thanks a lot - it works okay now.

Yes, it is a issue with case sensitivity - the first time I have this problem with my gmail account AFAIK. Just got too used to typing it all lower-case these days. I can access more recent test cases as well as the detailed report section now. BTW, the detailed report section seems to use aync javascript (?) and takes a bit of waiting before it appears.
