### ISSUE TITLE
OSS-Fuzz Support for corporate company usage

### ISSUE THREAD

**Issue by BharathMeduri** [google/oss-fuzz#702]
Hi , 
I want to use the Oss Fuzz for fuzzing my protocol  for office purposes. can i use it ? or there is a some commercial licence to use it ?

**Comment by BharathMeduri** [comment]
If i can get a linux vm , what are all things i need to do set up the test environment,
I read some of the details , But regarding the folder structure and naming of files i have few doubts. 
Previously i tried lib fuzzer for C code but i was not successes in integrating it as i used to face 2 errors
1)giving message that it supports only C++ code and i used some compiler option to solve
2)The lib compiled using clang used to give error  about the Encoding type that it is not supported , will i face similar problems again if i use OSS Fuzz

**Comment by Dor1s** [comment]
As per documentation on https://github.com/google/oss-fuzz, OSS-Fuzz provides Continuous Fuzzing for Open Source Software. We do not work with commercial products as of now.

libFuzzer works well with C code as well, please check http://tutorial.libfuzzer.info.

**Comment by kcc** [comment]
As for the problems with libFuzzer, please ask questions at libfuzzer@googlegroups.com or https://github.com/google/sanitizers/issues/

**Comment by BharathMeduri** [comment]
ok thanks
