### ISSUE TITLE
Missing reproducer testcase in bug report issue 42238

### ISSUE THREAD

**Issue by RosenZhu** [google/oss-fuzz#7037]
The Reproducer Testcase in [issue 42238](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42238&sort=-reported&q=buffer%20overflow%20proj%3Dkamailio&can=1) is not right. The testcase seems to be a javascript file.

**Comment by jonathanmetzman** [comment]
When I click on the reproducer testcase link ("") the file clusterfuzz-testcase-minimized-fuzz_parse_msg-4516937147744256 is downloaded which isn't a JS file.

**Comment by RosenZhu** [comment]
> When I click on the reproducer testcase link ("") the file clusterfuzz-testcase-minimized-fuzz_parse_msg-4516937147744256 is downloaded which isn't a JS file.

When I click on the link, it says "You are not authorized to access this page!" (I only `wget` before.)
Ok. I got it. 
For non-googlers, it has to be 90 days (or more?) when the test case is avaliable to be downloaded?

**Comment by jonathanmetzman** [comment]
> > When I click on the reproducer testcase link ("") the file clusterfuzz-testcase-minimized-fuzz_parse_msg-4516937147744256 is downloaded which isn't a JS file.
> 
> When I click on the link, it says "You are not authorized to access this page!" (I only `wget` before.) Ok. I got it. For non-googlers, it has to be 90 days (or more?) when the test case is avaliable to be downloaded?

Ah I think that's right although @oliverchang knows for sure.
