### ISSUE TITLE
h2o build failure

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#704]
@jfoote - can you please take a look.

https://oss-fuzz-build-logs.storage.googleapis.com/index.html

Step #3: [ 39%] Built target libh2o-evloop
Step #3: Scanning dependencies of target h2o-fuzzer-http1
Step #3: [ 39%] Building CXX object CMakeFiles/h2o-fuzzer-http1.dir/fuzz/driver.cc.o
Step #3: /src/h2o/fuzz/driver.cc:353:14: error: conflicting types for 'h2o_proxy_register_reverse_proxy'
Step #3:         void h2o_proxy_register_reverse_proxy(h2o_pathconf_t * pathconf, h2o_url_t * upstream, h2o_proxy_config_vars_t * config);
Step #3:              ^
Step #3: /src/h2o/include/h2o.h:1831:6: note: previous declaration is here
Step #3: void h2o_proxy_register_reverse_proxy(h2o_pathconf_t *pathconf, h2o_url_t *upstreams, size_t count, h2o_proxy_config_vars_t *config);
Step #3:      ^
Step #3: 1 error generated.
Step #3: CMakeFiles/h2o-fuzzer-http1.dir/build.make:62: recipe for target 'CMakeFiles/h2o-fuzzer-http1.dir/fuzz/driver.cc.o' failed
Step #3: make[2]: *** [CMakeFiles/h2o-fuzzer-http1.dir/fuzz/driver.cc.o] Error 1
Step #3: CMakeFiles/Makefile2:163: recipe for target 'CMakeFiles/h2o-fuzzer-http1.dir/all' failed
Step #3: make[1]: *** [CMakeFiles/h2o-fuzzer-http1.dir/all] Error 2
Step #3: Makefile:127: recipe for target 'all' failed
Step #3: make: *** [all] Error 2
Finished Step #3
ERROR
ERROR: build step "gcr.io/oss-fuzz/h2o" failed: exit status 2

**Comment by jfoote** [comment]
Sure thing. I am AFK but will take a look as soon as I return.

**Comment by inferno-chromium** [comment]
build is now fixed - https://oss-fuzz-build-logs.storage.googleapis.com/log-28db305f-7646-4968-8129-a9dbb677e27a.txt
