### ISSUE TITLE
"Couldn't load file content" on coverage pages

### ISSUE THREAD

**Issue by davidben** [google/oss-fuzz#707]
If I go to, e.g., https://oss-fuzz.com/coverage_report/fuzzer/libFuzzer_boringssl_server/2017-07-05/f/%2Fsrc%2Fboringssl%2Fssl%2Ftls13_server.c

I often get an error:
> Couldn't load file content {"vcs_url":"https://boringssl.googlesource.com/boringssl","path":"/ssl/tls13_server.c"}: 404

Sometimes it goes away on reload. I'm guessing you're getting rate-limited?

**Comment by inferno-chromium** [comment]
Can't reproduce, and we will be moving to clang source based coverage soon.
