### ISSUE TITLE
libidn fuzz targets are broken

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#708]
`libidn_tounicode_fuzzer` seems to run, but `libidn_stringprep_fuzzer` and `libidn_toascii_fuzzer` seem broken.

i.e.

```
python infra/helper.py run_fuzzer libidn libidn_stringprep_fuzzer
Running: docker run --rm -i --cap-add SYS_PTRACE -e FUZZING_ENGINE=libfuzzer -v /usr/local/google/home/ochang/work/oss-fuzz/build/out/libidn:/out -t gcr.io/oss-fuzz-base/base-runner run_fuzzer libidn_stringprep_fuzzer
Using seed corpus: libidn_stringprep_fuzzer_seed_corpus.zip
/out/libidn_stringprep_fuzzer -rss_limit_mb=2048 -timeout=25 /tmp/input < /dev/null
/out/libidn_stringprep_fuzzer: error while loading shared libraries: libidn.so.11: cannot open shared object file: No such file or directory
```

`libidn_toascii_fuzzer`  and `libidn_error_fuzzer` prints a bunch of:

```
testing 121 bytes from '/src/libidn/fuzz/libidn_toascii_fuzzer.in/c6105ed9c5be79ca95ee620fd2b1aaee22fcfbdd'
testing 72 bytes from '/src/libidn/fuzz/libidn_toascii_fuzzer.in/c7082b1d9354bc8933e91390afd30dede3f38c85'
```

messages, and it looks like it's using libidn's own `main` function instead of using libFuzzer's main to drive the fuzzing.

@rockdaboot could you please take a look?

**Comment by rockdaboot** [comment]
Thanks for pointing out.

Fixed upstream (C++ build needed some explicit casts).

The output came from remnants of 'make check' where the fuzzers are built for regression testing (iterate over all corpora). The following C++ build failed for those two fuzzers, so fuzzing took place with the regression testers.

I also cleaned up a bit, see #710.

**Comment by oliverchang** [comment]
Thanks!

I see on https://oss-fuzz.com/v2/fuzzer-stats/by-fuzzer/2017-07-05/2017-07-11/fuzzer/libFuzzer/job/libfuzzer_asan_libidn that `libFuzzer_libidn_error_fuzzer` has 45 instrumented edges and 2 items in its corpus. Please take a look at this one too to make sure it is being built and instrumented properly.

**Comment by rockdaboot** [comment]
Hmmm, `libidn_error_fuzzer` calls the 'error code to message' functions with all existing and one non-existing code. That is a pretty static code, maybe not worth fuzzing and better put into regression testing / code coverage area. At least not worth burning CPU cycles, should I simply remove it then ?

**Comment by oliverchang** [comment]
Thanks for clarifying. Unfortunately we don't have the ability right now to distribute CPU cycles by weight at a fuzz target granularity, so it may be worth removing this for now.

**Comment by rockdaboot** [comment]
Removed in upstream.
Merging the oss-fuzz corpora (-merge=1) took ages (5-7 execs/s). I'll look at that slowness issue soon.

**Comment by rockdaboot** [comment]
Just fixed the slowness as well. I guess you can close this now.

**Comment by oliverchang** [comment]
Thanks for the fixes!
