### ISSUE TITLE
Swift doesn't seem to honor `coverage_extra_args`

### ISSUE THREAD

**Issue by thomasvl** [google/oss-fuzz#7089]
PR #7076 added `coverage_extra_args` to with swift-protobuf yaml, but looking at the [recent runs](https://storage.googleapis.com/oss-fuzz-coverage/swift-protobuf/reports/20220103/linux/src/swift-protobuf/Sources/SwiftProtobuf/report.html), files that should match still seem to be showing up.

**Comment by thomasvl** [comment]
@catenacyber fyi

**Comment by catenacyber** [comment]
Swift honors it
cf https://github.com/google/oss-fuzz/pull/7091
We just need a right regexp ;-)

**Comment by thomasvl** [comment]
Doh, thanks.
