### ISSUE TITLE
C fuzzers need explicit -lubsan when linking to a C++ library

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#713]
Project 'libpsl' (C code) uses libicu (C and C++ mixed library). When statically linking the fuzzers with both libraries (using clang, not clang++), I have to explicitly give -lubsan (with SANITIZER=undefined). I don't have to do that (resp. -lasan) with the address sanitizer. Not tested the memory sanitizer yet.

Do you have any standards / suggestions for that situation ? Feels like a fragile hack now.

**Comment by rockdaboot** [comment]
It's fragile indeed.
```
python infra/helper.py run_fuzzer libpsl libpsl_fuzzer
```
then results in
```
/out/libpsl_fuzzer: error while loading shared libraries: libubsan.so.0: cannot open shared object file: No such file or directory
```

**Comment by rockdaboot** [comment]
BTW, the memory sanitizer also works without that hack.

**Comment by kcc** [comment]
very strange. -lubsan is *never* the right answer. Do you have a minimized reproducer?

**Comment by rockdaboot** [comment]
Currently can't reproduce at home, but have an older docker image (can't update due to very limited bandwidth).
Will try tomorrow in the office.

**Comment by rockdaboot** [comment]
Made up a branch with projects/libpsl-ubsan.
https://github.com/rockdaboot/oss-fuzz, branch is called 'libpsl-ubsan'.
It builds fine with --sanitizer <address|memory> but not with 'undefined' (linker fails with missing ubsan externals).

**Comment by kcc** [comment]
@morehouse please take a look why ubsan linking fails.

**Comment by morehouse** [comment]
Was able to reproduce this with the supplied Dockerfile and build.sh by amending "-fsanitize=undefined" to the CFLAGS, CPPFLAGS, and LDFLAGS defined in build.sh.

I'm getting undefined references to the following ubsan functions:
```
__ubsan_vptr_type_cache
__ubsan_handle_dynamic_type_cache_miss
```
These functions are defined in libclang_rt.ubsan_standalone_cxx-x86_64.a, but we're only linking against libclang_rt.ubsan_standalone-x86_64.a.

**Comment by kcc** [comment]
ubsan's vpts is meaningless for C (it's C++-cpecific). 
what if you do `export CFLAGS="$CFLAGS -fno-sanitize=function,vptr"`
like `harfbuzz/build.sh` and several others do?

**Comment by morehouse** [comment]
With `-fno-sanitize=function,vptr`, the undefined references above go away.

**Comment by kcc** [comment]
Let's do that for now, although we need a more general solution (one possible: just don't use vptr -- we haven't seen any reports from it, have we? )

**Comment by morehouse** [comment]
@rockdaboot 
Note that I had to add `-fsanitize=undefined -fno-sanitize=function,vptr` to both CFLAGS and CPPFLAGS.  I also had to add `-fsanitize=address,undefined` to LDFLAGS since apparently some of the files that are linked use ASan.

**Comment by rockdaboot** [comment]
Thank you all for looking into it.

@morehouse These mentioned flags only apply if `$SANITIZER = "undefined"`, I guess. And for building libicu + libpsl or just for one of them ? Maybe you could post your build.sh or a diff !?

**Comment by rockdaboot** [comment]
Thank you all for looking into it.

@morehouse These mentioned flags only apply if `$SANITIZER = "undefined"`, I guess. And for building libicu + libpsl or just for one of them ? Maybe you could post your build.sh or a diff !?

**Comment by rockdaboot** [comment]
PS: #717 skips the libicu/UBSAN combination for libpsl. ICU seems to have serious problems, it even skips undefined sanitizer in projects/icu/project.yaml.

**Comment by Dor1s** [comment]
We've seen several bugs found by UBSan's `vptr` check. It's a small fraction compared to overall number of bugs found, but all of those are security issues, which is cool.

Also it seems that we don't need to disable `function` check. That should be working with C code, and might be useful. Am I wrong?

**Comment by kcc** [comment]
@morehouse we may need to improve the clang-driver logic here to not force `vptr` when the linking does not allow it. (e.g C programs, or C++ with fno-rtti)

**Comment by morehouse** [comment]
The UBSan documentation states `vptr` requires linking with clang++.  So it seems the fundamental problem here may be that libicu (containing C and C++) is getting compiled with clang++ and `vptr` while libpsl is trying to link with libicu using clang.  Not sure how changing the clang-driver logic will fix that.

**Comment by kcc** [comment]
fair enough. In this case, indeed, we need to change the linker from $CC to $CXX.
But in general, we should probably warn (in the clang driver) if vptr is used w/o linking in the proper run-time. Can/should we do this?

**Comment by morehouse** [comment]
> But in general, we should probably warn (in the clang driver) if vptr is used w/o linking in the proper run-time.

I'm not exactly sure what you're proposing here.  At compile time we wouldn't know how linking would occur later, so we couldn't warn then.  And at link time we are already failing if the proper library can't be linked (although the failure is a bit cryptic).

It also looks like we have the following checks in place already:
- If `vptr` explicitly enabled and RTTI implicitly disabled, then warn and disable `vptr`
- If `vptr` explicitly enabled and `-fno-rtti` present, then error
- If `vptr` enabled as part of a group (e.g., `-fsanitize=undefined`) and RTTI disabled explicitly or implicitly, then silently disable `vptr`

In addition, it appears that explicit `vptr` is being silently disabled when compiling with clang on C, though I'm not sure where that happens in the clang-driver.

**Comment by kcc** [comment]
Yes, at the very least we should provide a meaningful error message instead of  `undefined reference to `__ubsan_vptr_type_cache'`. 
Can you prepare a minimized test that mimics the situation here?

**Comment by morehouse** [comment]
Yes, just got one working.

**Comment by morehouse** [comment]
But again, I'm not sure how we can catch the undefined reference at link time before clang passes things off to ld.

**Comment by kcc** [comment]
Ok, I see... Let's ignore this for now. The immediate problem with  libpsl is solved. 
If this keeps coming again will think more. 
Thanks for looking!

**Comment by rockdaboot** [comment]
IMO, some sort of documentation / explanation about this (e.g. in FAQ 'problems/issues') would be good. Libicu (C and C++) library) is pretty common and other projects might have similar problems in the future.

**Comment by jbendes** [comment]
I am having this exact issue linking cpp and c files together right now. Was there a conclusion on what should be done in this case? Changing from clang to clang++ compiles. Is this the fix? Is there a way to know which linker you need to use before running into the failure?

**Comment by kcc** [comment]
Using `clang++` to link C++ code is the right way.
