### ISSUE TITLE
I get notified about curl issues but can't access them

### ISSUE THREAD

**Issue by bagder** [google/oss-fuzz#716]
Hey,

I'm the lead developer and maintainer of the curl project and thus I get notified by OSS-fuzz issues about curl. That's awesome. However, I can't access any details about those issues since it says my account isn't good enough for it. I have a google account which has my regular email address registered as "alternate address".

(since I assume this issue will be filed publicly, I will refrain from adding specific details or URLs)

**Comment by inferno-chromium** [comment]
See https://github.com/google/oss-fuzz/issues/243, can you provide us with a gmail email address that we can add as cc and that will be able to acccess the reports.

**Comment by bagder** [comment]
Yes I do. daniel dot haxx at the gmail domain. If you'll take my word for it just like this...
