### ISSUE TITLE
Enhancement request: Need to have releases

### ISSUE THREAD

**Issue by richsalz** [google/oss-fuzz#7172]
Right now, everything seems to be done by checking into master; there's no releases or tagging.I want to use `ossf/scorecard` but I'll get dinged for not pinning specific hashes.  I can pin a specific git commit, but things like `dependabot` don't see a release so that's no help. 

Please see https://github.com/ossf/scorecard/issues/1500 for some background.

**Comment by evverx** [comment]
I think it's probably the same issue as https://github.com/google/oss-fuzz/issues/6836

**Comment by richsalz** [comment]
Yes, I will close this as a dup of #6836, thanks!

**Comment by evverx** [comment]
Looks like neither CIFuzz nor CFLite can be pinned properly so I'll go ahead and close https://github.com/google/oss-fuzz/issues/6836. CFLite can't be unpinned either though: https://github.com/google/clusterfuzzlite/issues/95 so once it's resolved I'll unpin it and ignore scorecard.
