### ISSUE TITLE
Reproducing instructions missing critical step

### ISSUE THREAD

**Issue by alexec** [google/oss-fuzz#7185]
https://google.github.io/oss-fuzz/advanced-topics/reproducing/

This does not show how to checkout the code, so isn't helpful. Please add it!

**Comment by asraa** [comment]
Do you mean checking out the oss-fuzz repo to run commands like `python infra/helper.py` in?

**Comment by alexec** [comment]
Yes. Either some instruction for that, or a link to a more basic getting started guide.

**Comment by oliverchang** [comment]
Thanks for pointing this out! This is now fixed.
