### ISSUE TITLE
how to use linfuzzing parms

### ISSUE THREAD

**Issue by tongxintest** [google/oss-fuzz#7196]
hi, this version i run_fuzzer use libfuzzing parm -max_total_time=300 is failed
what can  I do it ?
![image](https://user-images.githubusercontent.com/89123114/151526845-67d44875-dce4-4cc6-afd0-feb8da0ae77b.png)

**Comment by DavidKorczynski** [comment]
This is related to https://github.com/google/oss-fuzz/issues/7111 

You need to add `--`, i.e. change your commandline to:
`python3 infra/helper.py run_fuzzer mysql-server fuzz_initfile -- -max_total_time=300`

**Comment by tongxintest** [comment]
thx , i got   @DavidKorczynski
