### ISSUE TITLE
fuzz grpc

### ISSUE THREAD

**Issue by mikea** [google/oss-fuzz#72]
http://www.grpc.io/

**Comment by inferno-chromium** [comment]
@ctiller - check out https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html. It will be great if you can help us integrate grpc fuzzing in OSS-Fuzz.

**Comment by ctiller** [comment]
+Jan Tattermusch <jtattermusch@google.com> +Matt Kwong
<mattkwong@google.com> +Nicolas Noble <nnoble@google.com> +David Garcia
Quintas <dgq@google.com> +Abhishek Kumar <abhikumar@google.com>

This is possibly interesting for us. I'm OOO for a few weeks, but happy to
chat when I'm back.

Infrastructure folks: this would let us leverage different fuzzing engines
with gRPC, hopefully increasing coverage some. It does conflict with some
of the Jenkins migration work we've been doing, but that's been more about
learning Kokoro than anything else, so I think that's ok (and we'd probably
want to be running our own thing for some period anyway).

**Comment by mikea** [comment]
I tried our usual approach: https://github.com/google/oss-fuzz/compare/master...grpc

This is how far I was able to go: https://gist.github.com/9fb9c5285e9b8120173bc120281ef8d4

**Comment by kcc** [comment]
@ctiller up :) 
If this is still interesting -- let's chat.

**Comment by ctiller** [comment]
There's a thing on your calendar.

**Comment by inferno-chromium** [comment]
This is done, closing.
