### ISSUE TITLE
Istio: coverage build failing with "ERROR: context deadline exceeded"

### ISSUE THREAD

**Issue by AdamKorcz** [google/oss-fuzz#7204]
Bug report: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=41547#c9

Other projects have had similar failures in the past:

- https://github.com/google/oss-fuzz/issues/5855
- https://github.com/google/oss-fuzz/issues/5371

In those previosu cases the build fixed itself after a few days, but this has not been the case for Istio.

For info, Istio has more than 60 fuzzers, and some of the fuzzers may take a long time to run during the coverage build with the corpus that OSS-fuzz has.

`build_fuzzers`, `build_fuzzers --sanitizer=coverage` and `check_build` run fine locally without any corpus.

**Comment by jonathanmetzman** [comment]
Even though there are 60 targets, something still seems off. It shouldn't take an avg of 12 minutes to run each fuzzer on their corpus.

Looking at the past 3 failed cov builds it looks like they are all failing on `fuzz_host_matcher` I bet this one is really slow. Maybe eliminating it from coverage builds would fix things?

**Comment by jonathanmetzman** [comment]
Is this still an issue?

**Comment by AdamKorcz** [comment]
This has been fixed.
