### ISSUE TITLE
scorecard seems to complain about unpinned docker images when CFLite is used

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#7206]
I think it's technically a scorecard issue but by analogy with https://github.com/google/oss-fuzz/issues/6836 I'll just leave it here
```
        "Warn: third-party action not pinned by hash: .github/workflows/cifuzz.yml:37",
        "Warn: third-party action not pinned by hash: .github/workflows/cifuzz.yml:44",
        "Info: GitHub-owned actions are pinned",
        "Warn: docker image not pinned by hash: .clusterfuzzlite/Dockerfile:1",
        "Info: no insecure (not pinned by hash) dependency downloads found in Dockerfiles",
        "Info: no insecure (not pinned by hash) dependency downloads found in shell scripts",
        "Info: no insecure (not pinned by hash) dependency downloads found in GitHub workflows"
```

As far as I understand scorecard will ignore that eventually but as I said in https://github.com/google/oss-fuzz/issues/6836 I'm more interested in preventing the systemd CI from failing due to pulling the latest images with unpredictable clang/CIFuzz changes so it would still be nice if the images/actions could be versioned properly.

**Comment by jonathanmetzman** [comment]
What repo is this?

**Comment by evverx** [comment]
It was systemd before I pinned the image in https://github.com/systemd/systemd/blob/main/.clusterfuzzlite/Dockerfile. Dependabot can't follow floating tags though so it has to be updated manually

**Comment by jonathanmetzman** [comment]
Just curious, does it complain that clusterfuzzlite action isnot pinned by hash?

**Comment by evverx** [comment]
I suspect it does but it's pinned in the systemd repository

**Comment by oliverchang** [comment]
I think both this and https://github.com/google/oss-fuzz/issues/6836 can be addressed with an auto-releaser that bumps the minor version every week or so: https://github.com/google/oss-fuzz/issues/7212

Then we can let dependabot do the pinning updates.

**Comment by evverx** [comment]
Looking at https://github.com/google/clusterfuzzlite/issues/91 it seems it doesn't make much sense to pin clusterfuzzlite so I'm going to unpin both dockerfile and the action. I think scorecard should fix its bogus checks.

**Comment by evverx** [comment]
Another option would be to fork the action and pin the images there by analogy with https://github.com/google/clusterfuzzlite/issues/91#issuecomment-1080010189 but I don't think it's worth it
