### ISSUE TITLE
Java coverage build steps are failing

### ISSUE THREAD

**Issue by fmeum** [google/oss-fuzz#7225]
Multiple Java projects report coverage build steps:
https://oss-fuzz-build-logs.storage.googleapis.com/log-e33ecdf6-c335-479e-a08f-c236ec03d140.txt
https://oss-fuzz-build-logs.storage.googleapis.com/log-718e2a92-c221-46bc-9098-05757ff7e701.txt

There haven't been any relevant changes to upstream Jazzer and the fuzzing builds for these projects succeed, so I find it more likely that this breakage results from infrastructure changes. 

@jonathanmetzman @Navidem Could this be related to the addition of the fuzz introspector steps?

**Comment by jonathanmetzman** [comment]
Yeah I'd guess this is related to the fuzz introspector changes.
From zxing:
```
Step #10: Already have image (with digest): gcr.io/cloud-builders/gsutil
Step #10: CommandException: 1 files/objects could not be removed.
Finished Step #10
Starting Step #11
Step #11: Already have image (with digest): gcr.io/cloud-builders/gsutil
Step #11: CommandException: No URLs matched. Do the files you're operating on exist?
Finished Step #11
ERROR
ERROR: build step 11 "gcr.io/cloud-builders/gsutil" failed: step exited with non-zero status: 1
```

**Comment by jonathanmetzman** [comment]
This seems to also break go: https://oss-fuzz-build-logs.storage.googleapis.com/log-d5973f45-9921-4ca5-99ec-8287607bf8cb.txt
