### ISSUE TITLE
Build status running way too often.

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#7227]
CC @Navidem @oliverchang
![build-status](https://user-images.githubusercontent.com/31354670/152190519-dab8226c-f3b7-4ec0-b666-6bebd9640d7c.png)

**Comment by oliverchang** [comment]
Good catch! This was because we had 4 schedulers running every 30 minutes to trigger this. I just deleted the extra 3.

This was a leftover from the previous cloud function model (where we had separate functions handling coverage vs fuzzing vs badges)

**Comment by jonathanmetzman** [comment]
Thanks!

**Comment by jonathanmetzman** [comment]
Is it supposed to be running every half hour? https://console.cloud.google.com/cloud-build/builds?project=oss-fuzz&pageState=(%22builds%22:(%22f%22:%22%255B%257B_22k_22_3A_22Source_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22google%252Foss-fuzz_5C_22_22_2C_22s_22_3Atrue_2C_22i_22_3A_22source_22%257D%255D%22))

**Comment by oliverchang** [comment]
Yep, every 30 minutes is the currently configured time.
