### ISSUE TITLE
Fuzz introspector builds taking very long.

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#7228]
![introspector](https://user-images.githubusercontent.com/31354670/152194449-cd83d907-d37f-4b26-9519-4d5caa3a762d.png)
I think these are clogging up the build pipeline. My build I want to use to investigate https://github.com/google/oss-fuzz/issues/7225 is queued and will probably run a long time from now.

**Comment by jonathanmetzman** [comment]
Compare the ~5 hour build of openssl under fuzz introspector vs the < 20 minute builds of openssl for coverage and fuzzing:
https://pantheon.corp.google.com/cloud-build/builds;region=global/87d2da18-1b0a-437c-954e-9d0dfd1e7ade;tab=detail?project=oss-fuzz
https://pantheon.corp.google.com/cloud-build/builds;region=global/87d2da18-1b0a-437c-954e-9d0dfd1e7ade?project=oss-fuzz

**Comment by jonathanmetzman** [comment]
On further inspection this doesn't seem to be a widespread problem. Seems like a few projects are really slow.
Most however are not: https://console.cloud.google.com/cloud-build/builds?project=oss-fuzz&pageState=(%22builds%22:(%22f%22:%22%255B%257B_22k_22_3A_22tags_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22introspector_5C_22_22_2C_22i_22_3A_22tags_22%257D_2C%257B_22k_22_3A_22status_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22Successful_5C_22_22_2C_22s_22_3Atrue_2C_22i_22_3A_22status_22%257D%255D%22))

**Comment by jonathanmetzman** [comment]
About 16 introspector builds take 12 hours and time out.
https://console.cloud.google.com/cloud-build/builds?project=oss-fuzz&pageState=(%22builds%22:(%22f%22:%22%255B%257B_22k_22_3A_22tags_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22introspector_5C_22_22_2C_22i_22_3A_22tags_22%257D_2C%257B_22k_22_3A_22status_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22Timed%2520out_5C_22_22_2C_22s_22_3Atrue_2C_22i_22_3A_22status_22%257D%255D%22))

**Comment by jonathanmetzman** [comment]
@Navidem @oliverchang What do we think of using a more aggressive timeout for introspector for now?

**Comment by Navidem** [comment]
It does not surprise me that introspector takes longer than coverage build. It is mainly because of LTO.
I am fine with setting shorter timeout for now.

**Comment by jonathanmetzman** [comment]
Thanks! I think disabling it for some of these projects is a good idea too.

**Comment by jonathanmetzman** [comment]
> It does not surprise me that introspector takes longer than coverage build. It is mainly because of LTO. I am fine with setting shorter timeout for now.

How can we disable the really slow ones btw?

**Comment by Navidem** [comment]
Is there any better way than maintaining a blacklist for slow ones and skipping introspector build on them?

**Comment by jonathanmetzman** [comment]
I don't think so.
Usually the blocklist is stored in project.yaml, but since fuzz introspector is not ready for users yet, I think maintaining a central blocklist is the right move.

**Comment by oliverchang** [comment]
To address scalability / concurrency issues, I opened https://github.com/google/oss-fuzz/issues/7244 to give us much more flexibility.

**Comment by jonathanmetzman** [comment]
I  think this is no longer a concern.
