### ISSUE TITLE
Many canceled introspector builds

### ISSUE THREAD

**Issue by Navidem** [google/oss-fuzz#7237]
I am seeing so many introspector builds canceled.

@jonathanmetzman @oliverchang any idea why this is happening?

<img width="832" alt="Screen Shot 2022-02-03 at 2 12 20 PM" src="https://user-images.githubusercontent.com/19780488/152421632-4441a115-9a78-471a-a7f6-a57b53eef46e.png">

**Comment by jonathanmetzman** [comment]
Sorry. I did this so I could test that my fix worked.
