### ISSUE TITLE
Dependency of open62541 eligible for oss-fuzz?

### ISSUE THREAD

**Issue by Pro** [google/oss-fuzz#724]
open62541 is now integrated into oss-fuzz. Thanks!

We are using a mDNS library as a submodule in open62541:
https://github.com/Pro/mdnsd

And I would also like to add this mdnsd library to OSS-Fuzz since it may also contain security issues.

OSS-Fuzz states:
```
To be accepted to OSS-Fuzz, an open-source project must have a significant user base and/or be critical to the global IT infrastructure.
```

Unfortunately the user base of mdnsd is very small, on the other hand the one from open62541 is growing fast.

Since mdnsd is an important part of open62541, is it still possible to integrate mdnsd into OSS-Fuzz? (I.e., create a PR)

**Comment by Dor1s** [comment]
Are there any existing fuzz targets?

**Comment by Pro** [comment]
Not yet (didn't want to invest time if it may not be accepted), but I already have a few ideas for targets.
It the PR will be accepted, I'm happy to invest time into it.

**Comment by Dor1s** [comment]
Makes sense. You are right that mDNS seems to be too small for OSS-Fuzz at the moment, but you may add mDNS targets into https://github.com/google/oss-fuzz/tree/master/projects/open62541. In that case, open62541 and mDNS fuzz targets would share the same CPU quota. It looks like you pull mDNS sources already, so it shouldn't be hard to compile mDNS targets in the same build script. How does it sound?

**Comment by kcc** [comment]
>> mDNS targets into ... open62541

Since you are already pulling mDNS source, you might as well hace the fuzz targets for mDNS in mDNS repo.

**Comment by Pro** [comment]
Thanks for the comments. I will try to set it up in a way that mDNS has its own independent fuzz targets, and open62541 includes those targets when fuzzing.
So maybe in a later stage mDNS can simpliy run as its on fuzzing instance.
