### ISSUE TITLE
Corpora inaccessible through oss-fuzz.com interface

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#7242]
For example

https://oss-fuzz.com/fuzzer-stats?project=cryptofuzz&fuzzer=libFuzzer&job=libfuzzer_asan_cryptofuzz&group_by=by-fuzzer

if you scroll to the right and click 'Download' in the 'corpus backup' column, it takes you to https://console.cloud.google.com/storage/cryptofuzz-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/cryptofuzz_cryptofuzz-boringssl which says "URL not found. We couldn't find what you were looking for. Try one of the links below."

**Comment by oliverchang** [comment]
This is fixed together with #7188 !
