### ISSUE TITLE
Deadline extension for Issue 40884

### ISSUE THREAD

**Issue by sdenton4** [google/oss-fuzz#7249]
Hello!
We have a fix for this issue and should be landing it in the next couple days. A two week extension will be very comfortable.

**Comment by jonathanmetzman** [comment]
Done.

**Comment by sdenton4** [comment]
It looks like this issue was disclosed anyway:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40884&sort=-id&colspec=ID%20Type%20Component%20Status%20Library%20Reported%20Owner%20Summary&q=type%3DBug-Security%2CBug%20opus&can=1

**Comment by jonathanmetzman** [comment]
Sorry for this, it seems like I gave the extension to the issue with the same id as this github issue #7249 instead of the one you reuqested (40884).
