### ISSUE TITLE
Skia build is broken

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#725]
@kjlubick, could you please take a look at https://oss-fuzz-build-logs.storage.googleapis.com/index.html

There are lots of compilation errors due to C-style type casts when calling intrinsic functions:

```
<...>
Step #3: ../../src/core/../opts/SkNx_sse.h:76:43: error: cast from 'const void *' to 'float *' drops const qualifier [-Werror,-Wcast-qual]
Step #3:         __m128 v0 = _mm_loadu_ps(((float*)ptr) +  0),
Step #3:                                           ^
<...>
```

**Comment by kjlubick** [comment]
I am OOO til next Monday - will look at it then.
