### ISSUE TITLE
afl++ is not compatible with llvm 15

### ISSUE THREAD

**Issue by vanhauser-thc** [google/oss-fuzz#7273]
A quick test showed that llvm 15 disabled the old pass manager. we have not ported to the new one because it is a lot, really a lot of work.
so heads up - dont upgrade to llvm 15. dunno when we will have time to update all our passes ... :(

**Comment by jonathanmetzman** [comment]
ACK. I think we are still pinned to llvmorg-14-init-7378-gaee49255

**Comment by jonathanmetzman** [comment]
I think this has been fixed right?

**Comment by vanhauser-thc** [comment]
yes, LTO is not possible anymore as they borked custom plugin loading in lld though, but this does not affect oss-fuzz.

**Comment by fanquake** [comment]
Can this be closed now? My understanding is that afl++ is now compatible with LLVM 18 since #11404.
