### ISSUE TITLE
Increasing code coverage: prefer changing existing fuzzer or writing a new one?

### ISSUE THREAD

**Issue by ktmf01** [google/oss-fuzz#7275]
Currently the fuzzers for FLAC have a rather poor code coverage of about 50%. I've looked at the fuzzer code and seen a few opportunities for improvement. However, doing so would probably invalidate the current seed corpus and regression tests. So I guess it would be preferable to add a fuzzer instead of modifying one (especially one that has been around a long time) but that would mean two fuzzers with a lot overlap.

Please comment on what is preferred here.

**Comment by jonathanmetzman** [comment]
>I've looked at the fuzzer code and seen a few opportunities for improvement. However, doing so would probably invalidate the current seed corpus and regression tests.

Seems like this is only a problem in the short term though, right?

I'd probably just modify the current fuzz target.
It probably depends on the fuzz target, but I suspect most of them plateau in finding new coverage before a month of execution, so I suspect in the long wrong there won't be a real impact to invalidating the current corpus.

**Comment by ktmf01** [comment]
Yes, this is probably a short term problem. However, would that mean that CIFuzz is less effective the first two weeks or so?

**Comment by jonathanmetzman** [comment]
> Yes, this is probably a short term problem. However, would that mean that CIFuzz is less effective the first two weeks or so?

Actually for much longer than that. CIFuzz uses the public corpus from OSS-Fuzz, i.e. corpus units that are more than 90 days old.
