### ISSUE TITLE
Advice linking to libxml2 statically

### ISSUE THREAD

**Issue by szhorvat** [google/oss-fuzz#7284]
I am trying to get the igraph project to build with libxml2 support, but I am having trouble linking to libxml2 due to the static linking requirement.  Can anyone with experience with linking to libxml2 offer some advice?

libxml2 depends on libicu, so I ended up with the following linking flags:

```
-Wl,-Bstatic -lxml2 -lz -llzma -licuuc -licui18n -licudata -Wl,-Bdynamic -ldl
```

I still get linking errors such as:

```
/usr/bin/ld: /lib/x86_64-linux-gnu/libicuuc.a(umutex.ao): in function `umtx_init':
(.text+0x3b): undefined reference to `std::condition_variable::condition_variable()'
```

I am not certain, but I suspect that this might have to do with libicu being compiled with GCC and thus depending on libstdc++. Is this incompatible with the Clang used to build the fuzzers? If yes, is there a workaround?

Additionally, will the `-ldl` (not static) cause any problems? It also appears to be required by libicu.

**Comment by DavidKorczynski** [comment]
You're not the first to run into this issue! See here for examples on how to overcome it:
https://github.com/google/oss-fuzz/blob/30f3a8f1c0f5b072e77d5bea82709db04c53453d/projects/jsc/build.sh#L20-L33

https://github.com/google/oss-fuzz/blob/b661058c8857747d77fb925f2ebf045af7610c4f/projects/libphonenumber/build.sh#L52-L69

**Comment by szhorvat** [comment]
Thank you. This worked. I am going to close this issue now.

**Comment by szhorvat** [comment]
@DavidKorczynski Is there any procedure for dealing with minor issues that are present in dependencies? We hit one in `libicu` very quickly: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44768 As far as I can tell, this might be a harmless "undefined behaviour" issue in libicu.

**Comment by DavidKorczynski** [comment]
One thing you could is build the libicu project without sanitizers. One way of doing this is doing the build operations inside of the Dockerfile https://github.com/google/oss-fuzz/blob/master/projects/igraph/Dockerfile

**Comment by szhorvat** [comment]
Doesn't it need to be built with the same compiler as the fuzzer, to make sure that the C++ standard library matches?
