### ISSUE TITLE
Can making a fuzz bug public after it's been fixed be delayed?

### ISSUE THREAD

**Issue by alexcrichton** [google/oss-fuzz#7287]
I've worked with the Wasmtime project on oss-fuzz and one thing that we've noticed is that once a fuzz bug is fixed it's pretty quickly opened to the public. This makes sense most of the time for us since if a fix is landed in the public repository then the bug is public anyway. There are some situations, however, where to oss-fuzz the bug looks like it's been "fixed" but in reality the bug hasn't been fixed.

Many of our fuzz targets interpret the fuzz input as a form of "dna" along the lines of "if the next bit is 0 we generate this input else we generate that input". For example Wasmtime uses the [`wasm-smith` project from `wasm-tools`](https://github.com/bytecodealliance/wasm-tools) which, given random input, generates a guaranteed-valid WebAssembly module. This means that if Wasmtime's interpretation of the fuzz input changes then oss-fuzz can be fooled into thinking that a fuzz bug is fixed because the literal test case no longer reproduces. For us, though, if the interpretation of the input changes then that doesn't necessarily imply that the fuzz bug is fixed.

In this situation, is it possible for us to opt-in to delaying making a fuzz bug public until after the fix is known to have landed? We haven't ever needed to extend a public disclosure past the default 90 day deadline imposed by oss-fuzz, but an example of a situation we're in is:

* A [fuzz bug](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44678#c2) was discovered in Wasmtime.
* We drafted a fix and have [prepared a security release](https://groups.google.com/a/bytecodealliance.org/g/sec-announce/c/fWoHuZ6WeqE/m/Y4vBHVFiBQAJ?utm_medium=email&utm_source=footer)
* Concurrently we're [enhancing an orthogonal aspect of our fuzzers](https://github.com/bytecodealliance/wasmtime/pull/3800), but this enhancement will cause us to reinterpret the fuzz input (as some bits are now used for the feature implemented in that PR)

If https://github.com/bytecodealliance/wasmtime/pull/3800 were to merge, which is orthogonal to the fuzz bug issue, then it would mean that the literal test case for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44678#c2 would now appear fixed. We have to proactively hold off on merging PRs to enhance fuzzing while there's an active security-related fuzz bug we don't want disclosed. Is it possible for us to avoid this?

**Comment by oliverchang** [comment]
Hi @alexcrichton, thanks for reaching out! (and sorry for the delay in response).

Note that when an OSS-Fuzz report becomes "public", the reproducer input remains private for 30 days. The detailed stacktrace will be private indefinitely at time of writing. 

We can also override this on a case by case basis, if there are certain bugs where you'd like to have more control over the exact disclosure time. Let us know if this is what you'd like for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44678

**Comment by alexcrichton** [comment]
Ah ok so to confirm there's nothing we can do on our end to prevent disclosure in this manner? Thanks for pointing out that the reproducer and stack trace remain private, I had forgotten about that! Unfortunately in this case even the snippet in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44678 was enough to probably figure out how to trigger the crash (props to the reporting there!)

In this specific case we've now filed https://github.com/bytecodealliance/wasmtime/security/advisories/GHSA-88xq-w8cq-xfg7 which is public at this point so nothing's urgent on this from our end, we're mostly curious if there's ways we can prevent this from happening in the future. But it sounds like our options are:

* Proactively don't change fuzzers to reinterpret the input in different ways when a security issue is found.
* Alternatively proactively reach out to y'all to keep the bug private while other changes land which might change the fuzz input interpretation.

If that's true, what's the best way to reach out to y'all about keeping a fuzz bug private for a short while?

**Comment by oliverchang** [comment]
> Proactively don't change fuzzers to reinterpret the input in different ways when a security issue is found.
It would be beneficial in many cases to keep input formats stable for the same fuzz target. This will help with things like bisections, regression testing.

> If that's true, what's the best way to reach out to y'all about keeping a fuzz bug private for a short while?
You can either file a bug here, or if you expect to do this very frequently, we could grant permissions for you to do the same.

**Comment by alexcrichton** [comment]
Ok, thanks for the clarification!
