### ISSUE TITLE
cluster-api: EditIssue permission to maintainers

### ISSUE THREAD

**Issue by AdamKorcz** [google/oss-fuzz#7312]
Some crashes found in the cluster-api project can be made public instantly.

Would it be possible to grant EditIssue permission to naadir [a.t.] randomvariable.co.uk?

@randomvariable Please confirm whether anyone else should have permission to make issues public. Also see here how to make issues public: https://github.com/google/oss-fuzz/issues/2582#issuecomment-509669466

@inferno-chromium @jonathanmetzman @oliverchang

**Comment by inferno-chromium** [comment]
Done, granted.
