### ISSUE TITLE
conflict of variable storage in uint64_t *byte_values between keywords byte_math and byte_extract!

### ISSUE THREAD

**Issue by ljqchina** [google/oss-fuzz#7319]
Hi, I'm researching  and studying suricata6.0 and 7.0 code, and found some confusion when i use keywords byte_math、byte_extract，
the both keywords need to compute with variable and store the comute to a variable to a array of uint64_t *byte_values by index i'ts named 'local_id'.
the local_id is set in functions XXXSetup(detect-bytemath.c:DetectByteMathSetup, detect-byte-extract.c:DetectByteExtractSetup) while loading rules from rule file.
example:
alert udp any any -> any any \
  (byte_extract: 1, 0, extracted_val, relative; \
  byte_math: bytes 1, offset 1, oper +, rvalue extracted_val, result var; \
  byte_test: 2, =, var, 13; \
  msg:"Byte extract and byte math with byte test verification";)

byte_extract local_id is 0,  variable 'extracted_val' will be stored into byte_values[local_id],
byte_math local_id is 0, variable 'var' will be stored into byte_values[local_id],
so, they are conflict, the variable 'extracted_val' will be overwriten by variable 'var' , is this so?

and another confusion on byte_math: function: detect-engine-content-inspection.c:DetectEngineContentInspection
        uint64_t rvalue;
        if (bmd->flags & DETECT_BYTEMATH_RVALUE_VAR) {
             rvalue = det_ctx->byte_values[bmd->local_id];
        } else {
             rvalue = bmd->rvalue;
        }
the rvalue(bmd->value) is assigned to index of variable 'extracted_val' by executing statement 'data->rvalue = index;' in function DetectByteMathSetup.
 so, the rvalue should be fetche using 'rvalue = det_ctx->byte_values[bmd->rvalue];'
 not 'rvalue = det_ctx->byte_values[bmd->local_id];'
 
sorry, My English is very poor，very poor,  hope what i said is clear, say sorry again!!!

**Comment by jonathanmetzman** [comment]
I don't think this has anything to do with OSS-Fuzz, so I'm closing this bug. Feel free to reopen this if I'm wrong.
Maybe you could try https://github.com/OISF/suricata
CC @catenacyber who actually knows something about suricata, unlike us at OSS-Fuzz :-)

**Comment by ljqchina** [comment]
ok, thank you!

**Comment by catenacyber** [comment]
You are welcome to post at forum.suricata.io
cc @jlucovsky who knows about byte* stuff I think
