### ISSUE TITLE
Memory Sanitizer runtime option to change exit/status code

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#732]
Just realized that the libidn2 test suite returns some tests with `SKIP`when run with clang's memory sanitizer.
Well, that means the test program exits with 77 - and that is exactly what the memory sanitizer does !
The logs show 'use-of-uninitialized-value', but automated testing survives without reporting an error.

Q: How can I change the sanitizer's exit code to not interfere with automake testing (AFAIK, 77 is hard-coded into automake) ?

[1] https://www.gnu.org/software/automake/manual/html_node/Scripts_002dbased-Testsuites.html#Scripts_002dbased-Testsuites

**Comment by kcc** [comment]
You can use 
```
MSAN_OPTIONS=exitcode=42 ./a.out ...
```

Hope this helps.

**Comment by rockdaboot** [comment]
Thanks, exactly what I was looking for !

Couldn't find it in the msan docs. Just as reference for finding:
[SanitizerCommonFlags](https://github.com/google/sanitizers/wiki/SanitizerCommonFlags)
(where exitcode is documented with a default value of 1 !)

**Comment by behdad** [comment]
We also hit this issue.  I think 77 is a bad default, given how autotools interprets that.
