### ISSUE TITLE
Question: Any plans for restoring previous corpora for unbound?

### ISSUE THREAD

**Issue by hyyi** [google/oss-fuzz#7348]
Hello, I was looking into recreating and analyzing the scenarios where OSS-Fuzz had found bugs in the past but recently the initial corpora for certain fuzz harnesses in unbound seems to have gone missing. So I was curious if there were any plans to restore the corpora?

From what I have gathered, it seems that around 2 weeks ago (around the 14th or 15th of February), most of the corpora (4 out of 5) for the unbound project had gone missing. And shortly afterwards, it seems the build script for the unbound project in OSS-fuzz requiring those corpora have been removed to fix the error they introduced into the building process. I had initially thought this was a temp. fix before restoring the missing corpora but as that may not be the case, I was curious if I could ask if there were any plans on it? If these were lost, it would be quite unfortunate as it seems that the fuzz harnesses utilizing these corpora were the ones that had previously found bugs for unbound.

Thank you in advance!

**Comment by jonathanmetzman** [comment]
CC @DavidKorczynski who made the change.
We keep corpora backups for 90 days.
If you have access to the buckets, the backups can be found in gs://unbound-corpus.clusterfuzz-external.appspot.com/libFuzzer/
If you don't or don't know what this is, give me your email address and I can send you the corpus from a specific date (Jan 30, let's say).

**Comment by hyyi** [comment]
Thank you for your prompt response.
If it would be alright, maybe I could try following both avenues that you have suggested?

@jonathanmetzman 
Unfortunately I do not have access to the buckets. If you could provide a previous backup, maybe the original seeds would be mixed in there and hopefully I could extract them if the corpus hasn't gone through reduction. My email is hayoon.yi(at)samsung[dot]com.  The one for Jan 30 sounds good :)

@DavidKorczynski
That is unfortunate but thank you for the clarification. I will also try to ask the Unbound maintainers. 

If I have any luck, would you be interested in restoring the initial seeds?

**Comment by MarcoFalke** [comment]
There are also public archives, though they are dated back 30 days IIRC.

For example, https://storage.googleapis.com/unbound-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/unbound_parse_packet_fuzzer/public.zip

**Comment by hyyi** [comment]
> There are also public archives, though they are dated back 30 days IIRC.
> 
> For example, https://storage.googleapis.com/unbound-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/unbound_parse_packet_fuzzer/public.zip

Thank you for the suggestion! Unfortunately it seems that the time frame for the fuzzers of interest (fuzz_1 ~ fuzz_4) being available might have passed (assuming if the generated corpus for fuzz_1 were available it would be accessible at https://storage.googleapis.com/unbound-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/unbound_fuzz_1/public.zip which ends up in an 'access denied').

As the maintainers of Unbound also did not keep the initial corpora, I guess if there are no other avenues to try, I will have to skip recreating cases for unbound.

**Comment by jonathanmetzman** [comment]
I don't think anything can be done about this issue anymore.
