### ISSUE TITLE
MSAN detects uninitialized value in FuzzerMain.cpp:20

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#735]
Currently I can't test/run the memory sanitizer locally due to the above error (details further down).

Tested with latest commit (621b2d41534bc69f21c88cb1f995c72ed43d380a).

Steps to reproduce (likely reproducable with any other project):
- python infra/helper.py build_image libidn2
- python infra/helper.py build_fuzzers --sanitizer memory libidn2
- python infra/helper.py run_fuzzer libidn2 idn2_to_ascii_8z_fuzzer

```
Running: docker run --rm -i --cap-add SYS_PTRACE -e FUZZING_ENGINE=libfuzzer -v /usr/oms/src/oss-fuzz/build/out/libidn2:/out -t gcr.io/oss-fuzz-base/base-runner run_fuzzer idn2_to_ascii_8z_fuzzer
Using seed corpus: idn2_to_ascii_8z_fuzzer_seed_corpus.zip
/out/idn2_to_ascii_8z_fuzzer -rss_limit_mb=2048 -timeout=25 /tmp/input < /dev/null
INFO: Seed: 1422644284
INFO: Loaded 1 modules (1456 guards): [0xa11df0, 0xa134b0), 
Loading corpus dir: /tmp/input
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
#0      READ units: 4
#5      INITED cov: 227 ft: 414 corp: 4/62b exec/s: 0 rss: 70Mb
==11:11==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x51033a in operator() /src/libfuzzer/FuzzerLoop.cpp:431:9
    #1 0x51033a in void fuzzer::TracePC::CollectFeatures<fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*)::$_1>(fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*)::$_1) const::{lambda(unsigned long, unsigned char)#1}::operator()(unsigned long, unsigned char) const /src/libfuzzer/FuzzerTracePC.h:200
    #2 0x50f433 in void fuzzer::ForEachNonZeroByte<void fuzzer::TracePC::CollectFeatures<fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*)::$_1>(fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*)::$_1) const::{lambda(unsigned long, unsigned char)#1}>(unsigned char const*, unsigned char const*, unsigned long, void fuzzer::TracePC::CollectFeatures<fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*)::$_1>(fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*)::$_1) const::{lambda(unsigned long, unsigned char)#1}) /src/libfuzzer/FuzzerTracePC.h:176:11
    #3 0x504357 in void fuzzer::TracePC::CollectFeatures<fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*)::$_1>(fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*)::$_1) const /src/libfuzzer/FuzzerTracePC.h:204:3
    #4 0x4ffd24 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*) /src/libfuzzer/FuzzerLoop.cpp:430:7
    #5 0x50603d in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:620:9
    #6 0x506c56 in fuzzer::Fuzzer::Loop() /src/libfuzzer/FuzzerLoop.cpp:663:5
    #7 0x4df62d in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:751:6
    #8 0x4cb811 in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #9 0x7ff978ed282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #10 0x41ee68 in _start (/out/idn2_to_ascii_8z_fuzzer+0x41ee68)

  Uninitialized value was created by an allocation of 'SS' in the stack frame of function '_ZN6fuzzer12Sha1ToStringEPKh'
    #0 0x567d70 in fuzzer::Sha1ToString(unsigned char const*) /src/libfuzzer/FuzzerSHA1.cpp:209

SUMMARY: MemorySanitizer: use-of-uninitialized-value /src/libfuzzer/FuzzerLoop.cpp:431:9 in operator()
Unique heap origins: 198
Stack depot allocated bytes: 17944
Unique origin histories: 77
History depot allocated bytes: 1848
Exiting
MS: 1 ChangeBinInt-; base unit: 0af1147ba7f739b3c4095df504a61f1ccbe9e563


artifact_prefix='./'; Test unit written to ./crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64:
```

**Comment by kcc** [comment]
This seems to happen with every msan build (tried boringssl)

**Comment by kcc** [comment]
+CC @oliverchang @inferno-chromium

**Comment by inferno-chromium** [comment]
We had a clang roll - https://chromium.googlesource.com/chromium/src/+/1c688af81fcfa4c072dcca79e698641839e8a42f
, so guessing something broke. @kcc - anything interesting in that range of llvm commits.

**Comment by kcc** [comment]
Nothing comes to mind. :(

**Comment by kcc** [comment]
also reproduces with the 'example' project.

**Comment by kcc** [comment]
Any idea why we did not notice these breakages?

**Comment by inferno-chromium** [comment]
Not all MSAN projects are impacted, i see valid reports for libarchive, libpng, etc.

**Comment by kcc** [comment]
This also might have been caused by my recent changes in libFuzzer. Looking.

**Comment by oliverchang** [comment]
> Any idea why we did not notice these breakages?

Unfortunately we don't have notifications for startup crashes yet. @Dor1s is working on something that will make this breakage more noticeable.

This doesn't seem to be happening in chromium land (but we haven't rolled libFuzzer for a while there).

**Comment by Dor1s** [comment]
There are 3 bugs (https://github.com/google/oss-fuzz/issues/333, https://github.com/google/oss-fuzz/issues/535, https://github.com/google/oss-fuzz/issues/695), and it looks like at least some post-build checks (https://github.com/google/oss-fuzz/issues/333) need to be implemented as soon as we can. I'll take a look later this week.

**Comment by kcc** [comment]
This should be fixed by http://llvm.org/viewvc/llvm-project?rev=309038&view=rev
I still don't have upstream tests for libFuzzer+msan, this is blocked by something else (migrating libFuzzer to compiler-rt). Once we have such tests upstream, regressions like this should become much less frequent. Sorry... :( 

@rockdaboot -- thanks for reporting, please try again.

**Comment by oliverchang** [comment]
Thanks for fixing!

I've kicked off a base-images build to pick up the fix, so it should start working shortly if you answer "y" to `Pull latest base images (compiler/runtime)? (y/N):` when you run `python infra/helper.py build_image ...`

**Comment by oliverchang** [comment]
This crash has dropped off on CF, so closing.
