### ISSUE TITLE
Badge/shield for OSS-Fuzz?

### ISSUE THREAD

**Issue by jwhui** [google/oss-fuzz#738]
Is there a badge/shield for OSS-Fuzz?  Would be great to include on a top-level README, for example, as a way to indicate that OSS-Fuzz is being used on a given project, possibly some status, and as a way to promote OSS-Fuzz more broadly.

**Comment by kcc** [comment]
We don't have one, but this sounds like a great idea. 
Do you have examples of such badges? Is this something widely used in github?

**Comment by alex** [comment]
Pretty widely used, yeah. Here's a few examples: https://github.com/pyca/cryptography/#pycacryptography

**Comment by ammaraskar** [comment]
Closed by #2513

**Comment by behdad** [comment]
Thanks for this!  We use badges heavily in HarfBuzz.  See:

  https://github.com/harfbuzz/harfbuzz

My wishlist / adjustment suggestions:

* Per-project landing page so we can link to it from the badge.

* If project is not building, that definitely needs to be highlighted in the badge.

* Beyond that, I like a green/yellow/red status to show, ideally with numbers, how many outstanding oss-fuzz issues are against the project.

See other badges we have there, eg. Coverity / CodeCov / Coveralls.  The badge should concisely show the health status of the project according to oss-fuzz.

Thank you again!

**Comment by inferno-chromium** [comment]
Is in documentation.
