### ISSUE TITLE
How to make the JVM font-system available as part of fuzzing

### ISSUE THREAD

**Issue by centic9** [google/oss-fuzz#7380]
I am working on building fuzzing via oss-fuzz for [Apache POI](poi.apache.org/).

I am using the JVM/Jazzer support in oss-fuzz and it mostly works locally.

However the JVM that is installed as part of fuzzing via oss-fuzz is not providing the necessary font-system, so Apache POI currently crashes because necessary system libraries (libfreetype6) and other parts of the font-system are missing.

Apache POI works a lot with fonts when producing Microsoft file formats, e.g. to compute font-sizes or rendering PowerPoint slides, so it would lower the quality of fuzzing a lot if we need to exclude this part of the code. 

Also fuzzing the Java font system might even show some hidden native issues in the JVM itself.

When reading https://google.github.io/oss-fuzz/further-reading/fuzzer-environment/ it does not take such a case into account. I.e. I cannot statically link here as the JVM is loading this dynamic library. Also more than just a few libraries are necessary, so providing a few .so-files as part of the fuzz target does not work as well as then font-configuration is not available.

So is there a way to install an operating-system package as part of fuzzing?

**Comment by centic9** [comment]
I found that I can install the minimum necessary packages as part of the execute-script that is created in build.sh.

So if this is an acceptable approach, I think this is solved.

**Comment by oliverchang** [comment]
Sorry for the delayed reply! 

Unfortunately there's no way to install packages in the fuzzer execution environment. If you can bundle it with the fuzzer as part of the `build.sh` script, that would be ideal.

Thanks!

**Comment by centic9** [comment]
I really need it when actually running the fuzzers as they need font-support, so the following in build.sh does work locally for me. I.e. I install these when the fuzzer actually runs via the created script.

Hopefully this will ok:

```
...
# Create an execution wrapper that executes Jazzer with the correct arguments.
echo "#!/bin/sh

apt-get install -y fontconfig libfreetype6 fonts-dejavu-core

LD_LIBRARY_PATH=\"$JVM_LD_LIBRARY_PATH\":\$this_dir \
...
```

**Comment by oliverchang** [comment]
> I really need it when actually running the fuzzers as they need font-support, so the following in build.sh does work locally for me. I.e. I install these when the fuzzer actually runs via the created script.
> 
> Hopefully this will ok:
> 
> ```
> ...
> # Create an execution wrapper that executes Jazzer with the correct arguments.
> echo "#!/bin/sh
> 
> apt-get install -y fontconfig libfreetype6 fonts-dejavu-core
> 
> LD_LIBRARY_PATH=\"$JVM_LD_LIBRARY_PATH\":\$this_dir \
> ...
> ```

Unfortunately we can't install packages on the fly like this in our fuzzer execution environment. Is there some way to bundle these fonts with the fuzzer binaries in the output directory?

**Comment by centic9** [comment]
I feared that would be the case.

I have to take a look, the font-system is more than just some so-libs and the fonts, it includes some config-files and other pieces, not sure if it can be packaged along the application.

**Comment by centic9** [comment]
I found that most of the issues are actually caused by loading other classes from java.awt, e.g. Color and others. For these it seems to suffice to provide some additional .so files from a few additional packages. 

This has been put in place with PR #11006, let's see if this works during the next few runs.

Apache POI actually tries to handle missing fonts gracefully, so we should be fine with this solution for now, thus closing this issue.
