### ISSUE TITLE
recommend to open a git hub issue instead of ClusterFuzz-Wrong

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#739]
Today monorail prints this: 
"If this is incorrect, please add ClusterFuzz-Wrong label and re-open the issue."
But AFIACT the users can't really append the ClusterFuzz-Wrong label.
So, instead, we should show something like this: 
"If this is incorrect, please add open an issue at https://github.com/google/oss-fuzz/issues"

**Comment by oliverchang** [comment]
This is done!
