### ISSUE TITLE
BoringSSL build breakage

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#741]
@davidben - can you please take a look.

https://oss-fuzz-build-logs.storage.googleapis.com/log-33b717ee-b39b-4290-8db0-16e895c58c32.txt

Step #8: FAILED: /usr/local/bin/clang++   -DBORINGSSL_IMPLEMENTATION -I/src/boringssl/third_party/googletest -I/src/boringssl/third_party/googletest/include -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=bool,array-bounds,float-divide-by-zero,function,integer-divide-by-zero,return,shift,signed-integer-overflow,vla-bound,vptr -fno-sanitize-recover=undefined -fsanitize-coverage=trace-pc-guard,trace-cmp -stdlib=libc++ -DBORINGSSL_UNSAFE_FUZZER_MODE -std=c++11 -Wall -Werror -Wformat=2 -Wsign-compare -Wmissing-field-initializers -Wwrite-strings -ggdb -fvisibility=hidden -fno-common -Wnewline-eof -Wmissing-declarations -fno-exceptions -fno-rtti -Wmissing-prototypes -Wimplicit-fallthrough -Wshadow -MMD -MT CMakeFiles/gtest.dir/third_party/googletest/src/gtest-all.cc.o -MF CMakeFiles/gtest.dir/third_party/googletest/src/gtest-all.cc.o.d -o CMakeFiles/gtest.dir/third_party/googletest/src/gtest-all.cc.o -c /src/boringssl/third_party/googletest/src/gtest-all.cc
Step #8: clang-6.0: error: invalid argument '-fsanitize=vptr' not allowed with '-fno-rtti'
Step #8: ninja: build stopped: subcommand failed.
Finished Step #8
ERROR
ERROR: build step "gcr.io/oss-fuzz/boringssl" failed: exit status 1

**Comment by oliverchang** [comment]
already fixed in https://github.com/google/oss-fuzz/commit/368da1df2460c12490d8b7f72d20b531e5825232 :)

**Comment by inferno-chromium** [comment]
@davidben - when you reenable rtti in future, please also remember to submit pull request here to enable vptr again. you are missing on all the bad-cast catching awesomeness now :(

**Comment by davidben** [comment]
Oh, if the fuzzers work better with RTTI, we can easily and would love to arrange for OSS-Fuzz to build with it. RTTI is disabled for the standalone build because one of our consumers have broken toolchains (they can't handle a C++ runtime dependency), but that's no reason to lose out on tooling from you all! :-)

I'll go add a CMake toggle to suppress the `-fno-rtti` bit...

**Comment by inferno-chromium** [comment]
Yes please, thanks @davidben.

**Comment by inferno-chromium** [comment]
reverted the disable in https://github.com/google/oss-fuzz/commit/005893a244e86ec54144e2dd46a6ea1b0f67047a, so that we don't forget about it. @davidben - please add cmake rule to build with rtti in oss-fuzz build.

**Comment by davidben** [comment]
https://boringssl-review.googlesource.com/c/18484/

**Comment by davidben** [comment]
Alright, that's in now. If you adjust `CMAKE_DEFINES` to include `-DBORINGSSL_ALLOW_CXX_RUNTIME`, that should be fixed.
