### ISSUE TITLE
Support Go 1.18

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#7410]
There are a few things we need to do as part of upgrading to Go 1.18:

- Fix base image build failure

```
projects/influxdb/Dockerfile+ echo 'Set "PATH=$PATH:/root/.go/bin:$GOPATH/bin"'
+ go get -u github.com/mdempsky/go114-fuzz-build
Set "PATH=$PATH:/root/.go/bin:$GOPATH/bin"
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```
- Remove dependency on gotip in various places.
- Many go projects use "go get" to get the sources ([example](https://github.com/google/oss-fuzz/blob/master/projects/influxdb/Dockerfile)), which will no longer work longer work for the same reason as the base image build failure. We need to fix these.

**Comment by jonathanmetzman** [comment]
How do you notice base image build failures? I seem to miss them, can I sign up for email notifications somewhere?

**Comment by oliverchang** [comment]
> How do you notice base image build failures? I seem to miss them, can I sign up for email notifications somewhere?

These were surfacing as CI failures for my reland: https://github.com/google/oss-fuzz/pull/7407

**Comment by DavidKorczynski** [comment]
> * Many go projects use "go get" to get the sources ([example](https://github.com/google/oss-fuzz/blob/master/projects/influxdb/Dockerfile)), which will no longer work longer work for the same reason as the base image build failure. We need to fix these.

@AdamKorcz this might be something you can assist with for many of the go projects?

**Comment by DavidKorczynski** [comment]
> So in terms of Influxdb, I think the Dockerfile should be modified

This also looks to a stale project: it hasn't been building since Nov 2020 so it would be great to get it updated.
