### ISSUE TITLE
Random crashes for zero-length input on i386

### ISSUE THREAD

**Issue by szhorvat** [google/oss-fuzz#7421]
I keep getting unreproducible crashes for igraph, supposedly for zero-length input.

Examples:

https://oss-fuzz.com/testcase-detail/5392579543302144
https://oss-fuzz.com/testcase-detail/5946752023265280
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45406

For the first one, I do not believe that the input can truly be zero-length. This code path should not be accessible for zero-length input. The latter appears to be in libfuzzer itself.

All of these happen on i386.

Are there known problems with zero-length input?

**Comment by jonathanmetzman** [comment]
This is a known problem with i386 builds. ASAN on i386 is not actively supported and there are no resources to fix this.
If it bothers you, the only solution is disabling i386 fuzzing.
Sorry there isn't a better solution here.

**Comment by szhorvat** [comment]
Could you please mention this in the documentation, preferably [here](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#architectures)? i386 fuzzing has been useful for us, so I won't disable it.

**Comment by szhorvat** [comment]
Thanks for adding it to the docs and pointing me to #2746! It's interesting that their suspicion was also that this is due to an OOM. I'm still not sure that's true.

**Comment by szhorvat** [comment]
@jonathanmetzman Is there any way I can get https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45596 closed as a "false positive"?

**Comment by szhorvat** [comment]
Another question: If I scroll to the end of this page, https://oss-fuzz.com/testcase-detail/5946752023265280, and use the "Click to see the stats" button, it looks like this crash happen 20-30 times every day. But if I look on the [Crash Stats page](https://oss-fuzz.com/crash-stats?project=igraph), it appears that it happened only twice in the past week. Which is correct?

**Comment by jonathanmetzman** [comment]
Sorry I missed the rest of this. I maked it wontfix but I suspect another one will be opened. Lemme look into blocking CF from reporting these.

**Comment by szhorvat** [comment]
It would be useful to be able to opt into ignoring any crash with a zero-length input on i386, but not on other platforms.

The fuzz driver could ignore any zero-length input but I would rather not do that on x86_64, where this problem does not exist.

For igraph, there is usually 1-2 crash of this nature open at any time: https://oss-fuzz.com/testcases?project=igraph&open=yes (there is one as of this writing).
