### ISSUE TITLE
postgis_wkt_import_fuzzer is crashing on startup

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#746]
https://oss-fuzz.com/v2/performance-report/libFuzzer_postgis_wkt_import_fuzzer/libfuzzer_asan_postgis/latest

from the log:
```
...
Time ran: 0.023100
ParseDictionaryFile: error in line 1
		(
...
```

The [dictionary](https://git.osgeo.org/gogs/postgis/postgis/src/svn-trunk/fuzzers/wkt_import_fuzzer.dict) needs to be update in accordance with documentation regarding dictionaries: https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md#dictionaries

**tl;dr** wrap all elements into double quotes

**Comment by Dor1s** [comment]
Not sure who is responsible for that, so cc'ing @robe2 @rouault

**Comment by rouault** [comment]
@robe2 Patch to apply in https://trac.osgeo.org/postgis/ticket/3797

**Comment by robe2** [comment]
Committed patch.

**Comment by Dor1s** [comment]
Thanks @rouault and @robe2 ! I've just checked recent logs, the fuzz target is working well.
