### ISSUE TITLE
builds: zlib 1.2.11 does not exist anymore

### ISSUE THREAD

**Issue by bagder** [google/oss-fuzz#7468]
We're running "CIfuzz" in curl to do 40 minutes of fuzzing as a CI job. The part that builds curl is a job managed by oss-fuzz and it tries to download and use a zlib 1.2.11 tarball.

Since just now, that tarball is removed and causes a HTTP 404 response code. The zlib project has released 1.2.12 

The URL for the download thus just needs the 11 replaced by a 12 and it works again. Until then, the curl CIfuzz job fails.

Note: there are of course more builds than just curl that need and use this zlib version.

We're running it as a github action, [like this](https://github.com/curl/curl/blob/master/.github/workflows/fuzz.yml) also shown below for easier reference.
~~~
name: Fuzzer

on:
  # Trigger the workflow on push or pull requests, but only for the
  # master branch
  push:
    branches:
      - master
      - '*/ci'
  pull_request:
    branches:
      - master

jobs:
  fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'curl'
        dry-run: false

    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'curl'
        fuzz-seconds: 2400
        dry-run: false

    - name: Upload Crash
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: artifacts
        path: ./out/artifacts

**Comment by evverx** [comment]
> The URL for the download thus just needs the 11 replaced by a 12 and it works again

It seems it should be replaced in https://github.com/curl/curl-fuzzer/blob/master/scripts/download_zlib.sh

**Comment by bagder** [comment]
Oops, look at that. Thanks! I'll do a PR there...

**Comment by bagder** [comment]
https://github.com/curl/curl-fuzzer/pull/55

**Comment by bagder** [comment]
That does indeed fix my issue. There's only one occurrence of this URL in the oss-fuzz repo that I can find:

https://github.com/google/oss-fuzz/blob/1abbd8bf089660da96367b0370855f99e3aa2df6/projects/libspng/Dockerfile#L26

**Comment by evverx** [comment]
FWIW I'm not sure why that tarball vanished into thin air (I think it has something to do with https://seclists.org/oss-sec/2022/q1/191) but it seems to make that a bit more reliable `zlib` should be downloaded either from https://github.com/madler/zlib/tags or http://zlib.net/fossils/)

**Comment by oliverchang** [comment]
Thanks a lot @evverx for helping with this, and @bagder for pointing out the other occurence (I uploaded a PR to fix it).

Before we close this, would it make sense to switch the URLs to https://github.com/madler/zlib/tags for better reliability as @evverx suggested?

**Comment by oliverchang** [comment]
Closing for now -- if this comes up again we should definitely look at changing all our URLs.
