### ISSUE TITLE
Excessive logging in dlplibs_superpaintfuzzer

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#747]
There is a lot of logging that happens in 100% of fuzzer runs:

https://oss-fuzz.com/v2/performance-report/libFuzzer_dlplibs_superpaintfuzzer/libfuzzer_asan_dlplibs/latest

**Comment by Dor1s** [comment]
The same applies to dlplibs_macpaintfuzzer: https://oss-fuzz.com/v2/performance-report/libFuzzer_dlplibs_macpaintfuzzer/libfuzzer_asan_dlplibs/latest

**Comment by Dor1s** [comment]
Well, it's probably common across all dlplibs targets, e.g. https://oss-fuzz.com/v2/performance-report/libFuzzer_dlplibs_abwfuzzer/libfuzzer_asan_dlplibs/latest

**Comment by dtardon** [comment]
"Excessive logging" sounds like each run printed thousands of lines, not a single number... Anyway, it should be gone now.

**Comment by inferno-chromium** [comment]
@dtardon - can look at the performance reports tomorrow and confirm that logging issue is gone after your changes. Then we can mark this as fixed.

**Comment by dtardon** [comment]
@inferno-chromium: I can get to the "Fuzzer Performance Report" page when I use chromium, but I don't see any log when I click on any of the "log examples" links...

**Comment by inferno-chromium** [comment]
@dtardon - reported the issue you seen in #871. For many of the fuzz targets this is now fixed, so closing this. I think i only see it in https://oss-fuzz.com/v2/performance-report/libFuzzer_dlplibs_abwfuzzer/libfuzzer_asan_dlplibs/latest
