### ISSUE TITLE
Docker usage

### ISSUE THREAD

**Issue by Karthigaasri** [google/oss-fuzz#748]
I am new to using Docker. I followed the steps in https://github.com/google/fuzzer-test-suite/blob/master/tutorial/libFuzzerTutorial.md to install docker and run basic test programs in it. But now I am not sure of how to copy our project workspace into the docker container and run libfuzzer on it. Can anyone help me with this?

**Comment by kcc** [comment]
It's rather hard to answer questions like "I am not sure of how to".
Please start from reading https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md

A more productive question would be "I've made X, Y, and Z and now get an error message 'foo'".
