### ISSUE TITLE
Fixed timeout issue; oss-fuzz thinks it persists?

### ISSUE THREAD

**Issue by behdad** [google/oss-fuzz#7489]
This is about https://oss-fuzz.com/testcase-detail/5446125635633152

I fixed this issue in https://github.com/harfbuzz/harfbuzz/commit/a665e29ed71602dc37fbb987f0de6806bcc7d710 six days ago. The oss-fuzz issue was uncertain of reproducibility. I asked it to redo task for reproducibility and now it believes timeout is reproducible with tip of harfbuzz tree, which I'm certain it's not. I locally built and tested and it certainly doesn't timeout.

**Comment by behdad** [comment]
FWIW that task used to take over a minute before the fix, and finishes in 12ms locally:
```
Executed clusterfuzz-testcase-hb-shape-fuzzer-5446125635633152 in 12 ms
```

**Comment by behdad** [comment]
Humm. Between last night and now it went from Reliably Reproduces: YES, to Reliably Reproduces: NO.

Why does it not recognize it as fixed?

**Comment by behdad** [comment]
Okay I see "Deletion: | Will be auto-deleted on Sun, Apr 3, 2022 if flaky crash no longer seen"

**Comment by jonathanmetzman** [comment]
Weird. I guess timeouts are hard to deterministically prove, but this seems odd despite that.
Was there an issue filed for this bug btw?

**Comment by behdad** [comment]
> Was there an issue filed for this bug btw?

I don't recall seeing one. I just stumbled across this one browsing oss-fuzz.
