### ISSUE TITLE
Exception from coverage reports

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#749]
Static builds of underlying libraries appear in the coverage reports and strongly influence the coverage value. Normally, the coverage of underlying libraries isn't of any interest for the coverage of the target code. I know the 'lcov' tool supports exceptions. Can we please have it for oss-fuzz as well (e.g. within the .options file) ?

Example from libidn2 which also includes the coverage from submodule 'gnulib': https://oss-fuzz.com/coverage_report/fuzzer/libFuzzer_libidn2_to_unicode_8z8z_fuzzer/2017-07-30

The only interesting files would be
```
/src/libidn2/lib/decode.c	075%
/src/libidn2/lib/free.c	100%
/src/libidn2/lib/puny_decode.c	096%
```

**Comment by Dor1s** [comment]
@rockdaboot, that's a good idea. We are currently working on a new coverage reporting, so we'll keep this in mind. I don't think that we should ignore coverage from libraries though, we might simply collapse it but keep available on the page in case if it might be interesting.

**Comment by rockdaboot** [comment]
@Dor1s I am looking forward to the new reporting ! Collapsing and keeping it available is nice as long as the total isn't influenced by it any more.

As an example, libpsl has two fuzzers fuzzing almost the same code in libpsl but calling different IDN libraries. One fuzzer shows 25%, the other 69% coverage - though the coverage in libpsl code nearly the same (libFuzzer_libpsl_icu_load_fuzzer and libFuzzer_libpsl_idn2_load_fuzzer, see https://oss-fuzz.com/v2/fuzzer-stats/by-fuzzer/2017-07-24/2017-07-30/fuzzer/libFuzzer/job/libfuzzer_asan_libpsl).

And a second issue is fuzzing one function out of many in a single source file. The only way to increase coverage is to convince upstream to split each function into a separate source file. For the reporting that means configuration down to the function level.

**Comment by rockdaboot** [comment]
@inferno-chromium Did you close the issue because of FIXED or WONTFIX ?

**Comment by inferno-chromium** [comment]
@rockdaboot - this should be doable like this in project.yaml, see examples
https://github.com/google/oss-fuzz/search?q=%22-ignore-filename-regex%22&unscoped_q=%22-ignore-filename-regex%22

**Comment by rockdaboot** [comment]
@inferno-chromium Great ! Thank you for the link.
