### ISSUE TITLE
Request grace period/extension 

### ISSUE THREAD

**Issue by micahsnyder** [google/oss-fuzz#7506]
Please provide the 14-day grace period/extension for these two issues:
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43870
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44040

We have prepared fixes for these issues, but need a little extra time to prepare security patch versions.

**Comment by jonathanmetzman** [comment]
Done.
