### ISSUE TITLE
bitcoin-core: Coverage build started failing on April 2nd

### ISSUE THREAD

**Issue by MarcoFalke** [google/oss-fuzz#7511]
See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46316

I wonder if there are any upstream changes that caused this? Maybe a stricter timeout?

**Comment by jonathanmetzman** [comment]
They started taking a lot longer on April 1st. See below.
![bitcoin](https://user-images.githubusercontent.com/31354670/161837854-13ef5249-3613-46e8-8753-4d0a570181f1.png)

And now they take so long they go over our timeout.
Did anything change on your end that could have caused this?

**Comment by DavidKorczynski** [comment]
https://github.com/google/oss-fuzz/pull/7411 ?

**Comment by MarcoFalke** [comment]
Looks like this fixed itself on Sunday. We didn't change anything, so this might have been caused by changes to the underlying google docker images that oss fuzz builds on?

**Comment by jonathanmetzman** [comment]
I don't think we changed anything
