### ISSUE TITLE
Update GDB in base-runner-debug

### ISSUE THREAD

**Issue by Navidem** [google/oss-fuzz#7513]
The current base-runner-debug has GDB 9.2 installed which fails to load debugging info with this message:
`Dwarf Error: DW_FORM_strx1 found in non-DWO CU`

As I checked the latest GDB version 11.2 does not have such problem.

**Comment by chris-liddell** [comment]
This is affecting the Ghostcript project, too, effectively blocking progress on an open bug.

**Comment by Navidem** [comment]
> This is affecting the Ghostcript project, too, effectively blocking progress on an open bug.

Hope this latest merge helps your case.
