### ISSUE TITLE
Backfill GitHub issues 

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#7564]
Backfill GitHub issues for already filed Monorail issues.

**Comment by oliverchang** [comment]
@Alan32Liu We should do this as part of our rollout process as well. Let's discuss this tomorrow :)

**Comment by evverx** [comment]
FWIW I've already reported almost all the libbpf bugs on GitHub so it would be great if the bot could avoid reporting them again.

**Comment by evverx** [comment]
Looking at the systemd bug reports I think I'd ignore the timeouts and report https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44881 only. I'm not sure how this kind of filter can be implemented though.

**Comment by evverx** [comment]
Also it appears the bot ignores coverage build failures like https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46826. At least that bug has never been copied to GitHub. Though considering that coverage is usually flaky it makes sense to ignore it probably
