### ISSUE TITLE
[libjpeg-turbo] It doesn't appear as if OSS-Fuzz is running the fuzzers for the 2.0.x branch

### ISSUE THREAD

**Issue by dcommander** [google/oss-fuzz#7575]
Because of https://github.com/google/oss-fuzz/commit/5cc77a3fde7edc0b6fbb88636811185214d2d963, which was integrated in #7528, OSS-Fuzz should now be building and testing separate fuzzers for three branches of libjpeg-turbo.  However, I only see OSS-Fuzz results from two of the branches.  The 2.0.x branch is missing.

**Comment by jonathanmetzman** [comment]
I think it's because the fuzzers from the other branch have periods in the name which makes clusterfuzz misidentify the file extension. Can you change the suffix on the 2.0.x branch to "2"

**Comment by dcommander** [comment]
Cool. I will submit a new PR when I am back in the office.

**Comment by dcommander** [comment]
I've patched the in-tree fuzzer build script in libjpeg-turbo so that it replaces periods with underscores in the fuzzer suffix.  I'll give it a couple of days to see whether that fixes the problem and close this issue if so.

**Comment by dcommander** [comment]
It appears to be running the 2.0.x fuzzers now.
