### ISSUE TITLE
how do I see why coverage is failing

### ISSUE THREAD

**Issue by boxerab** [google/oss-fuzz#7579]
My repo badge notifies that coverage is failing. How can I see what the error is ?

https://github.com/GrokImageCompression/grok
https://bugs.chromium.org/p/oss-fuzz/issues/list?sort=-opened&can=1&q=proj:grok

Thanks!

**Comment by jonathanmetzman** [comment]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#grok

**Comment by jonathanmetzman** [comment]
Not great that our badge doesn't link to the issue.

**Comment by jonathanmetzman** [comment]
Something goes wrong with the link i sent you, how about this: https://oss-fuzz-build-logs.storage.googleapis.com/log-12ddf43e-cf0a-46de-aebb-808f4f0c53e0.txt

**Comment by boxerab** [comment]
Thanks, I can see the logs on that one.
 Is this coverage failure warning new behaviour ? Previously, I would only get a badge warning if the fuzzer failed to build.

**Comment by jonathanmetzman** [comment]
I don't think it's new, I think this is the old behavior

**Comment by boxerab** [comment]
Thanks. So, what exactly does "coverage failure" mean ? Does it mean there is a new fuzzer test that failed ?

**Comment by jonathanmetzman** [comment]
It means the coverage build of your fuzzers is failing

**Comment by boxerab** [comment]
gotcha. When I looked at the log, it seemed to build fine.

Also, my github fuzz action is building fine

https://github.com/GrokImageCompression/grok/actions/runs/2185088685

**Comment by boxerab** [comment]
maybe I should just wait until the next build attempt ?

**Comment by jonathanmetzman** [comment]
>gotcha. When I looked at the log, it seemed to build fine.

https://oss-fuzz-build-logs.storage.googleapis.com/log-12ddf43e-cf0a-46de-aebb-808f4f0c53e0.txt is definitely failing

>Also, my github fuzz action is building fine

Because this is a coverage failure, but your actions only use ASAN/UBSAN/MSAN and not coverage.

>maybe I should just wait until the next build attempt ?

That won't work.
To reproduce this, follow the instructions here: https://google.github.io/oss-fuzz/advanced-topics/code-coverage/

**Comment by boxerab** [comment]
@jonathanmetzman thanks! I was able to build the coverage using 

```
$ python infra/helper.py build_image grok
$ python infra/helper.py build_fuzzers --sanitizer=coverage grok
```

Perhaps this was either an intermittent failure, or whatever was causing the build failure has been fixed.

**Comment by jonathanmetzman** [comment]
Sorry for being unclear, but the error is during the coverage report generation, not during building

**Comment by jonathanmetzman** [comment]
It's an OOM so it might be intermittent, but I don't know that we should rely on this

**Comment by boxerab** [comment]
@jonathanmetzman thanks! is it possible to get the test case causing the failure? Also, does it make sense to add coverage to my github workflow ?

**Comment by evverx** [comment]
> Because this is a coverage failure, but your actions only use ASAN/UBSAN/MSAN and not coverage.

@jonathanmetzman I didn't know CIFuzz supports coverage. Personally I'd add it to the CI if it ran something like `./infra/helper.py coverage` in addition to `build_fuzzers --sanitizer coverage`: https://github.com/google/oss-fuzz/issues/7232#issuecomment-1037390331

**Comment by jonathanmetzman** [comment]
> > Because this is a coverage failure, but your actions only use ASAN/UBSAN/MSAN and not coverage.
> 
> @jonathanmetzman I didn't know CIFuzz supports coverage. Personally I'd add it to the CI if it ran something like `./infra/helper.py coverage` in addition to `build_fuzzers --sanitizer coverage`: [#7232 (comment)](https://github.com/google/oss-fuzz/issues/7232#issuecomment-1037390331)

clusterfuzzlite does.

**Comment by evverx** [comment]
> clusterfuzzlite does

It uploads artifacts by default as far as I can remember and it doesn't seem to be possible to turn it off.

Anyway, my guess would be that `grok` is failing due to a "shallow" bug that can be triggered with the latest OSS-Fuzz corpus. `libbpf` has been failing on OSS-Fuzz for the last two days because of something like that too. I'm not sure why this happens though because the latest corpora shouldn't include crashes as far as I know.

**Comment by boxerab** [comment]
thanks for this interesting discussion, guys. In the end, my coverage build started working again ! So, going to close this.
