### ISSUE TITLE
Links to incomplete fuzz-introspector reports

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#7601]
https://oss-fuzz-introspector.storage.googleapis.com/index.html seems to point to incomplete reports and I think it's confusing: https://github.com/google/oss-fuzz/issues/7599

**Comment by evverx** [comment]
I think it should point to the latest complete reports instead

**Comment by Navidem** [comment]
Is this only for the systemd case, or you may have other instances? 
The index is to point to the latest successful fuzz introspector build, it does not have any sanity check on the generated reports. For that purpose something like https://github.com/google/oss-fuzz/issues/7593#issuecomment-1104385015 is being considered.

**Comment by evverx** [comment]
elfutils: https://storage.googleapis.com/oss-fuzz-introspector/elfutils/inspector-report/20220421/fuzz_report.html and https://storage.googleapis.com/oss-fuzz-introspector/elfutils/inspector-report/20220419/fuzz_report.html

libbpf: https://storage.googleapis.com/oss-fuzz-introspector/libbpf/inspector-report/20220421/fuzz_report.html and https://storage.googleapis.com/oss-fuzz-introspector/libbpf/inspector-report/20220419/fuzz_report.html

selinux: https://storage.googleapis.com/oss-fuzz-introspector/selinux/inspector-report/20220421/fuzz_report.html and https://storage.googleapis.com/oss-fuzz-introspector/selinux/inspector-report/20220419/fuzz_report.html

**Comment by evverx** [comment]
> The index is to point to the latest successful fuzz introspector build, it does not have any sanity check on the generated reports.

I think this issue can be closed then because the checks discussed in https://github.com/google/oss-fuzz/issues/7593#issuecomment-1104385015 should prevent issues like that.

**Comment by DavidKorczynski** [comment]
It looks like there also was a regression, e.g. this is the elfutils report a month earlier https://storage.googleapis.com/oss-fuzz-introspector/elfutils/inspector-report/20220321/fuzz_report.html and coverage looks more accurate. Am actually working on the coverage as I'm writing so will look at that too

**Comment by evverx** [comment]
I'm still puzzled as to why no functions were covered at runtime according to the latest reports. Looks like the fuzz targets weren't run at all.

**Comment by evverx** [comment]
> I'm still puzzled as to why no functions were covered at runtime according to the latest reports. Looks like the fuzz targets weren't run at all

For the record It was reported once again and fixed in https://github.com/google/oss-fuzz/issues/7635
