### ISSUE TITLE
use StandaloneFuzzTargetMain for the coverage-only build

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#761]
Please use [StandaloneFuzzTargetMain](https://github.com/llvm-mirror/llvm/blob/master/lib/Fuzzer/standalone/StandaloneFuzzTargetMain.c) or some such for the coverage-only build as I am going to (temporary?) break libFuzzer's coverage dumper (it will sill work, but won't be compatible with `sancov -symbolize`. 

I am changing (once again!) the instrumentation used by libFuzzer and sancov doesn't work with it (yet?)

**Comment by oliverchang** [comment]
Is there an existing version of standalone main that takes in directories and runs all the files in them? 

To make things easy it would be nice if the behaviour of this main is similar to libFuzzer's -dump_coverage=1 in terms of the arguments passed to it.

**Comment by kcc** [comment]
Errr. No. Will this work instead? 
```
  ./a.out $(find $CORPUS -type f)
```

(and then this would use `UBSAN_OPTIONS=coverage=1` to dump `.sancov`)
See instructions in https://github.com/google/fuzzer-test-suite/issues/21

**Comment by oliverchang** [comment]
That might work, but I'm worried about running into command line length limits for larger corpora.

Also, how should we handle this transition in chromium? We don't have coverage builds there currently.

**Comment by kcc** [comment]
Understood... Bummer. Need to think

**Comment by kcc** [comment]
Ok... This will be auto-resolved once we migrate to SourceBasedCodeCoverage #769
