### ISSUE TITLE
base images not being rebuild

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#7650]
Looking at https://console.cloud.google.com/gcr/images/oss-fuzz-base/global/base-clang and https://console.cloud.google.com/gcr/images/oss-fuzz-base/global/base-builder the last image for each of these was built 13 days ago. Since then, at least three changes has been made across those related to fuzz-introspector:
https://github.com/google/oss-fuzz/pull/7605
https://github.com/google/oss-fuzz/pull/7636
https://github.com/google/oss-fuzz/pull/7583

There has also been other changes, but didn't track those.

**Comment by oliverchang** [comment]
@jonathanmetzman I think this probably broke after we moved to private build pools.
