### ISSUE TITLE
How to fuzz without sanitizer

### ISSUE THREAD

**Issue by ktmf01** [google/oss-fuzz#7663]
FLAC is a lossless audio codec. It just occurred to me that 'not being lossless' is a valid 'sanitizer' in its own right.

libFLAC has had a build-in verify mode for a long time. It has been used the encoder fuzzer for a few years, but failing this verify mode does not currently 'trigger' a sanitizer. So my question is: how could I augment my fuzzer to trigger on problems that are not related to a sanitizer? Should I use a `__builtin_trap()`, an assertion, raise an exception, exit with a non-zero exit code, or something else entirely? I would think the 'none' sanitizer setting was made for this.

**Comment by jonathanmetzman** [comment]
I think an assertion (provided these are turned on in your builds) should work.
`abort()` definitely works. I wouldn't do `exit()` though i think it works.
I'm not sure which of these use `__builtin_trap()` under the hood, but I suspect it works too.

**Comment by ktmf01** [comment]
`abort()` apparently triggers `SIGABRT` and `__builtin_trap()` triggers `SIGILL`. I've tried different sanitizers and the output doesn't seem to differ much.
