### ISSUE TITLE
last successful build of openssl is 7/25, yet the status is green.

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#768]
From: https://oss-fuzz-build-logs.storage.googleapis.com/index.html
```
openssl
Last built 7/25/2017, 9:45:19 PM
```
yet it shows as working

**Comment by kcc** [comment]
The above change broke the build.

**Comment by oliverchang** [comment]
I believe this was showing up as red until today, where I broke the builds status page while trying to fix something else.

The bug has been fixed, but it seems like GCS is still serving the cached version of the builds status..

**Comment by oliverchang** [comment]
The build status page is now fixed. There should also be no issues with caching in the future.
