### ISSUE TITLE
[rust] Generate a wasm module at runtime to be used by the fuzz target

### ISSUE THREAD

**Issue by rbehjati** [google/oss-fuzz#7690]
In project [oak](https://github.com/google/oss-fuzz/tree/master/projects/oak), we have a fuzz target that uses a wasm module. Ideally, the wasm module should be built from the source code at runtime (as in [this draft PR](https://github.com/project-oak/oak/blob/77d0a05914b4c475a9d637aaac0b41c5bc5b234a/oak_functions/loader/fuzz/fuzz_targets/wasm_invoke.rs#L77-L91)), but we have not been able to make this work with oss-fuzz, and the cifuzz workflow fails too ([example](https://github.com/project-oak/oak/runs/6368072702?check_suite_focus=true)). The problem appears to be that at the time of running the fuzz targets, the sources to build the wasm module from cannot be found. 

Should we expect the compiled and built fuzz targets to have access to the source code at runtime, and if so where is the source code located in this case? ([this failed cifuzz action](https://github.com/project-oak/oak/runs/6368072702?check_suite_focus=true) seems to have failed to find the sources in "/src/oak")

Note: our workaround so far has been to build the wasm module binary, and check that in into the oak repo. But this is causing too much hassle, as we have to manually rebuild the binary and check that in for most changes that we make to the repo.

**Comment by jonathanmetzman** [comment]
Excuse me for the delayed reply on this.


>Ideally, the wasm module should be built from the source code at runtime 

For us this makes things more complicated. Why is it better to compile this at runtime rather than at build time?

> 
> Should we expect the compiled and built fuzz targets to have access to the source code at runtime, 

No. Builds and fuzzing happen in different docker containers. Note that in the fuzzing container, you wont have access to the toolchain used to build your project.

>and if so where is the source code located in this case? ([this failed cifuzz action](https://github.com/project-oak/oak/runs/6368072702?check_suite_focus=true) seems to have failed to find the sources in "/src/oak")

If you need to do this, you can copy the source code to `/out` and it will be available at runtime. Just make sure that you don't use any absolute paths since these will change between ClusterFuzz and CIFuzz.

> 
> Note: our workaround so far has been to build the wasm module binary, and check that in into the oak repo. But this is causing too much hassle, as we have to manually rebuild the binary and check that in for most changes that we make to the repo.

Makes sense. This sounds like a hassle and I'm happy to help come up with something better.

**Comment by rbehjati** [comment]
Thanks for the very helpful explanation. 

> No. Builds and fuzzing happen in different docker containers. 

This is the main piece of information I was missing. 

> If you need to do this, you can copy the source code to /out and it will be available at runtime.

I am experimenting with this and will let you know if I need more help :)

**Comment by rbehjati** [comment]
I was not able to fix the path, but closing this, as my question is answered.

**Comment by jonathanmetzman** [comment]
Sorry you couldn't fix this, I've given more instructions that might be helpful if you're still interested.
