### ISSUE TITLE
Helm issue extension

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#7707]
Helm team is currently dealing with the issues found by OSS-Fuzz but would appreciate a 2-week extension for the following issues:

- [44734](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44734)
- [44735](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44735)

CC @mattfarina @hickeyma @marckhouzam @scottrigby @AdamKorcz

**Comment by jonathanmetzman** [comment]
Done.
