### ISSUE TITLE
oss-fuzz-robot doesn't seem to close issues on GitHub

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#7712]
I'm not sure if it's expected or not but https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32461 was closed on May 1 but https://github.com/systemd/systemd/issues/23142 is still open.

**Comment by evverx** [comment]
Given that it closes some issues automatically my guess would be that the bot can't keep track of issues filed retrospectively.

**Comment by jonathanmetzman** [comment]
CC @Alan32Liu @oliverchang

**Comment by oliverchang** [comment]
Thanks for reaching out! I believe this is due to our robot account getting flagged temporarily during that period. Our account has been restored since, but any issues closed during those would have been missed.

@Alan32Liu would you be able to confirm this?

**Comment by Alan32Liu** [comment]
Sure, confirming it now.

**Comment by evverx** [comment]
As far as I can see https://github.com/systemd/systemd/issues/23143 and https://github.com/systemd/systemd/issues/23146 weren't closed automatically either. If it was a one-off glitch caused by the bot getting flagged I think I can close them manually.

**Comment by oliverchang** [comment]
It seems there are some other issues here since some of these are outside of the window of the bot getting flagged. We're looking into this now and will auto-close the ones that should've been autoclosed.

**Comment by oliverchang** [comment]
This should be resolved now! All issues we failed to close should now have been closed (thanks to @Alan32Liu!).

Please let us know if you notice any other discrepancies.
