### ISSUE TITLE
access for opendnp3

### ISSUE THREAD

**Issue by jadamcrain** [google/oss-fuzz#7714]
[Issue 47429 in oss-fuzz: opendnp3:fuzzmaster](https://oss-fuzz.com/download?testcase_id=5908512158384128)

Hi, I'm the primary author. Can you grant access to `jadamcrain@gmail.com`?

The `info@automatak.com` account is no longer active.

**Comment by jonathanmetzman** [comment]
Done.

**Comment by jonathanmetzman** [comment]
You should get added to the issue soon. Please reopen if you don't get added by tomorrow.
