### ISSUE TITLE
90-days disclosure clarification

### ISSUE THREAD

**Issue by Marsel-marsel** [google/oss-fuzz#7717]
Hi, 

As far as I understand, oss-fuzz security bugs adheres 90-day disclosure policy, but in tracker there are security bugs that opened less than 90 days ago and didn't fix. For example, [this](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47106&sort=-reported&q=Type%3DBug-Security&can=2) security bug opened 18 days ago (at the time I am asking)

Or oss-fuzz discovers a bug, wait for 90 days and then it pops up as new security related unfixed bug in your tracker?

**Comment by jonathanmetzman** [comment]
php opted to make all of their issues public: https://github.com/google/oss-fuzz/commit/3b501d3ac3fc1bf5d5ca120d475bfe7f5f20881e
