### ISSUE TITLE
trial_build.py doesn't support coverage + introspector builds?

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#7726]
e.g. on https://github.com/google/oss-fuzz/pull/7709,

I see 

```
Info
2022-05-20 03:14:00.130 GMTStep #1: INFO:root:Command: ['trial_build.py', 'libarchive', 'opencv', '--sanitizer', 'introspector', '--fuzzing-engine', 'libfuzzer'].
Info
2022-05-20 03:14:00.232 GMTStep #1: INFO:root:Getting steps for: "trial_build.py".
Info
2022-05-20 03:14:00.232 GMTStep #1: ERROR:root:Project "trial_build.py" does not have a dockerfile.
Info
2022-05-20 03:14:00.233 GMTStep #1: ERROR:root:Couldn't get project data. Skipping trial_build.py.
Info
2022-05-20 03:14:00.233 GMTStep #1: INFO:root:Getting steps for: "libarchive".
Info
2022-05-20 03:14:00.234 GMTStep #1: INFO:root:Nothing to build for this project: libarchive.
Info
2022-05-20 03:14:00.234 GMTStep #1: INFO:root:Getting steps for: "opencv".
Info
2022-05-20 03:14:00.237 GMTStep #1: INFO:root:Nothing to build for this project: opencv.
Info
2022-05-20 03:14:00.292 GMTStep #1: ['address', {'memory': {'experimental': True}}, 'undefined'] ['introspector']
Info
2022-05-20 03:14:00.292 GMTStep #1: ['address', 'undefined'] ['introspector']
```

I think this is because we take the intersection with the project.yaml's defined sanitizers and engines before determining whether to build or not:

https://github.com/google/oss-fuzz/blob/aab23a8fb8d1010ab78cb8dcd436020fa1fba15c/infra/build/functions/trial_build.py#L167

We should be making an exception for coverage and introspector builds.

**Comment by oliverchang** [comment]
Still failing with 
```
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/oss-fuzz-base@appspot.gserviceaccount.com:signBlob?alt=json returned "The caller does not have permission">
```

@jonathanmetzman could you please help with this?

**Comment by jonathanmetzman** [comment]
I'm pretty sure it does work for coverage builds.

**Comment by jonathanmetzman** [comment]
I seem to be no longer to run trial_build.py from my local machine. I'm now getting this error:
```

  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.DebugInfo",
        "detail": "[ORIGINAL ERROR] generic::permission_denied: IAM authority does not have the permission 'cloudbuild.builds.create' required for action CreateBuild on resource 'projects/oss-fuzz'. Explanation:  Security Context: RecordingSecurityContext{delegate=ValidatedSecurityContextWithSystemAuthorizationPolicy{delegate=ValidatedSecurityContextWithRegistryHandle{delegate=ValidatedSecurityContextWithObligations{delegate=ContextWithGaiaMintToken{delegate=ValidatedIamSecurityContext{user=gaiauser/0xff636bd0be, creds=EndUserCreds{loggable_credential { type: GAIA_MINT loggable_gaia_mint { } } loggable_credential { type: SERVICE_CONTROL_TOKEN }}, peer=protocol=loas;psp_version=0;level=strong_privacy_and_integrity;host=inci124.prod.google.com;is_authenticated_host=false;role=cloud-build-api;gaiaId=655284510247;security_realm=campus-sln;is_delegated=false;user_type=MDB_USER_NON_PERSON, InternalIAMIdentity{log=}}}}}}}\ncom.google.apps.framework.auth.IamPermissionDeniedException: IAM authority does not have the permission 'cloudbuild.builds.create' required for action CreateBuild on resource 'projects/oss-fuzz'. Explanation:  Security Context: RecordingSecurityContext{delegate=ValidatedSecurityContextWithSystemAuthorizationPolicy{delegate=ValidatedSecurityContextWithRegistryHandle{delegate=ValidatedSecurityContextWithObligations{delegate=ContextWithGaiaMintToken{delegate=ValidatedIamSecurityContext{user=gaiauser/0xff636bd0be, creds=EndUserCreds{loggable_credential { type: GAIA_MINT loggable_gaia_mint { } } loggable_credential { type: SERVICE_CONTROL_TOKEN }}, peer=protocol=loas;psp_version=0;level=strong_privacy_and_integrity;host=inci124.prod.google.com;is_authenticated_host=false;role=cloud-build-api;gaiaId=655284510247;security_realm=campus-sln;is_delegated=false;user_type=MDB_USER_NON_PERSON, InternalIAMIdentity{log=}}}}}}} [security.context.PolicyEnforcerErrorPayload] { }"
      }
    ]
  }
}
``` Even though I was definitely able to run this in the past locally

**Comment by oliverchang** [comment]
> I seem to be no longer to run trial_build.py from my local machine. I'm now getting this error:
> 
> ```
> 
>   "error": {
>     "code": 403,
>     "message": "The caller does not have permission",
>     "status": "PERMISSION_DENIED",
>     "details": [
>       {
>         "@type": "type.googleapis.com/google.rpc.DebugInfo",
>         "detail": "[ORIGINAL ERROR] generic::permission_denied: IAM authority does not have the permission 'cloudbuild.builds.create' required for action CreateBuild on resource 'projects/oss-fuzz'. Explanation:  Security Context: RecordingSecurityContext{delegate=ValidatedSecurityContextWithSystemAuthorizationPolicy{delegate=ValidatedSecurityContextWithRegistryHandle{delegate=ValidatedSecurityContextWithObligations{delegate=ContextWithGaiaMintToken{delegate=ValidatedIamSecurityContext{user=gaiauser/0xff636bd0be, creds=EndUserCreds{loggable_credential { type: GAIA_MINT loggable_gaia_mint { } } loggable_credential { type: SERVICE_CONTROL_TOKEN }}, peer=protocol=loas;psp_version=0;level=strong_privacy_and_integrity;host=inci124.prod.google.com;is_authenticated_host=false;role=cloud-build-api;gaiaId=655284510247;security_realm=campus-sln;is_delegated=false;user_type=MDB_USER_NON_PERSON, InternalIAMIdentity{log=}}}}}}}\ncom.google.apps.framework.auth.IamPermissionDeniedException: IAM authority does not have the permission 'cloudbuild.builds.create' required for action CreateBuild on resource 'projects/oss-fuzz'. Explanation:  Security Context: RecordingSecurityContext{delegate=ValidatedSecurityContextWithSystemAuthorizationPolicy{delegate=ValidatedSecurityContextWithRegistryHandle{delegate=ValidatedSecurityContextWithObligations{delegate=ContextWithGaiaMintToken{delegate=ValidatedIamSecurityContext{user=gaiauser/0xff636bd0be, creds=EndUserCreds{loggable_credential { type: GAIA_MINT loggable_gaia_mint { } } loggable_credential { type: SERVICE_CONTROL_TOKEN }}, peer=protocol=loas;psp_version=0;level=strong_privacy_and_integrity;host=inci124.prod.google.com;is_authenticated_host=false;role=cloud-build-api;gaiaId=655284510247;security_realm=campus-sln;is_delegated=false;user_type=MDB_USER_NON_PERSON, InternalIAMIdentity{log=}}}}}}} [security.context.PolicyEnforcerErrorPayload] { }"
>       }
>     ]
>   }
> }
> ```
> 
> Even though I was definitely able to run this in the past locally. If you know how I could fix this it would really help with debugging this problem. I haven't had much luck

Not sure about issue in particular. Did you re-run `gcloud auth application-default login`? 

This seems to be working now for both coverage builds. Not sure what changed.. introspector builds still need one more minor fix.

**Comment by jonathanmetzman** [comment]
> > I seem to be no longer to run trial_build.py from my local machine. I'm now getting this error:
> > ```
> > 
> >   "error": {
> >     "code": 403,
> >     "message": "The caller does not have permission",
> >     "status": "PERMISSION_DENIED",
> >     "details": [
> >       {
> >         "@type": "type.googleapis.com/google.rpc.DebugInfo",
> >         "detail": "[ORIGINAL ERROR] generic::permission_denied: IAM authority does not have the permission 'cloudbuild.builds.create' required for action CreateBuild on resource 'projects/oss-fuzz'. Explanation:  Security Context: RecordingSecurityContext{delegate=ValidatedSecurityContextWithSystemAuthorizationPolicy{delegate=ValidatedSecurityContextWithRegistryHandle{delegate=ValidatedSecurityContextWithObligations{delegate=ContextWithGaiaMintToken{delegate=ValidatedIamSecurityContext{user=gaiauser/0xff636bd0be, creds=EndUserCreds{loggable_credential { type: GAIA_MINT loggable_gaia_mint { } } loggable_credential { type: SERVICE_CONTROL_TOKEN }}, peer=protocol=loas;psp_version=0;level=strong_privacy_and_integrity;host=inci124.prod.google.com;is_authenticated_host=false;role=cloud-build-api;gaiaId=655284510247;security_realm=campus-sln;is_delegated=false;user_type=MDB_USER_NON_PERSON, InternalIAMIdentity{log=}}}}}}}\ncom.google.apps.framework.auth.IamPermissionDeniedException: IAM authority does not have the permission 'cloudbuild.builds.create' required for action CreateBuild on resource 'projects/oss-fuzz'. Explanation:  Security Context: RecordingSecurityContext{delegate=ValidatedSecurityContextWithSystemAuthorizationPolicy{delegate=ValidatedSecurityContextWithRegistryHandle{delegate=ValidatedSecurityContextWithObligations{delegate=ContextWithGaiaMintToken{delegate=ValidatedIamSecurityContext{user=gaiauser/0xff636bd0be, creds=EndUserCreds{loggable_credential { type: GAIA_MINT loggable_gaia_mint { } } loggable_credential { type: SERVICE_CONTROL_TOKEN }}, peer=protocol=loas;psp_version=0;level=strong_privacy_and_integrity;host=inci124.prod.google.com;is_authenticated_host=false;role=cloud-build-api;gaiaId=655284510247;security_realm=campus-sln;is_delegated=false;user_type=MDB_USER_NON_PERSON, InternalIAMIdentity{log=}}}}}}} [security.context.PolicyEnforcerErrorPayload] { }"
> >       }
> >     ]
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Even though I was definitely able to run this in the past locally. If you know how I could fix this it would really help with debugging this problem. I haven't had much luck
> 
> Not sure about issue in particular. Did you re-run `gcloud auth application-default login`?

I'm using service credentials I downloaded so I don't think this matters.

> 
> This seems to be working now for both coverage builds. Not sure what changed.. 

I gave the service account from oss-fuzz-base more permissions.

>introspector builds still need one more minor fix.

I thought it would take a lot more to get it working.

**Comment by jonathanmetzman** [comment]
Actually I don't think my permissions changes did anything.
Weirdly enough the last coverage build you did failed with the same error: https://pantheon.corp.google.com/cloud-build/builds;region=us-central1/4efc74b5-f574-466d-b6c7-c55e8413a273?project=oss-fuzz
But some earlier ones didn't?
https://pantheon.corp.google.com/cloud-build/builds;region=us-central1/4533b6af-e055-44cb-94a3-8d0446600d14?project=oss-fuzz

**Comment by jonathanmetzman** [comment]
@AdamKorcz @DavidKorczynski @Navidem What's a quick building project to test introspector with? skcms seems to break when I test it, not sure if the testing environment is wrong or this project is expected not to work

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer coverage --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
> > > introspector builds still need one more minor fix.
> > 
> > 
> > I thought it would take a lot more to get it working.
> 
> Maybe not "a lot more" but definitely more. Here are some things I can think of:
> 
> 1. Building base-builder:introspector in base-image build step.
> 2. Pull base-builder-testing:introspector
> 3. Make sure we only use testing buckets in any steps where GCS is written to.

After looking into this, I think it will in fact take "a lot more" to support introspector in trial builds and possibly double the amount of time it takes to do a trial from 45 minutes to 1.5 hours. I think before doing this we should refactor how the introspector image is built. Instead of hiding in base-clang behind a bunch of if statements controlled by a command line arg, it should be its own image (descending from base-image or base-clang) so that it can be built without tons of special casing.

**Comment by oliverchang** [comment]
One more issue from https://github.com/google/oss-fuzz/pull/7746.

```
Info
2022-05-26 02:58:22.846 GMTStep #1: Failed to get list of targets from "https://storage.googleapis.com/clusterfuzz-builds-testing/aiohttp/targets.list.address".
Info
2022-05-26 02:58:22.846 GMTStep #1: Status code: 404 Text:
```

Coverage builds seem to depend on an ASan build previously being built in the test environment.

**Comment by jonathanmetzman** [comment]
I got introspector working. I think this issue can be closed.
