### ISSUE TITLE
false OOM reports caused by large corpus

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#773]
Looking at https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2962 and a few similar reports
I can see libFuzzer consumes too much memory for the initial corpus  causes it to OOM when the actual target code is not guilty. 
Most likely, the fix should be inside libFuzzer.

**Comment by kcc** [comment]
This is what libFuzzer did: 
1. load all files from the initial corpus into memory
2. run all of them to collect the coverage, add interesting inputs to the working corpus
3. deallocate the initial corpus

In the reports we currently see the initial corpus is > 1Gb, and while processing it the working corpus gets to > 300Mb, and then actually running some of the items could take > 500Mb => OOOm. 

http://llvm.org/viewvc/llvm-project?rev=310881&view=rev implements a stop gap measure to reduce the RAM usage while loading the corpus. 

There is lots to improve here, but let's see how much the simple fix above improves the situation.
Potential next step is to load files one-by-one and process them, w/o having the entire corpus in memory at any point (although I'd like to avoid this)

**Comment by Dor1s** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2953 and some other issues do not occur anymore. Awesome!

**Comment by kcc** [comment]
There was yet another change after r310881. Cool. Let's close this and reopen if we see this again.
