### ISSUE TITLE
Can i opt-in into MSan sanitizer?

### ISSUE THREAD

**Issue by LebedevRI** [google/oss-fuzz#776]
Hi.
I would like to get msan sanitized fuzzer for [RawSpeed](https://github.com/google/oss-fuzz/tree/master/projects/librawspeed).
I have just worked on an issue which would be much better reported by msan...
There are no external dependencies, no extern librares used, so it should just work.
Also, refs. https://github.com/google/oss-fuzz/issues/775

**Comment by inferno-chromium** [comment]
Please submit a pull request.

See example https://github.com/google/oss-fuzz/blob/master/projects/boringssl/project.yaml#L9
