### ISSUE TITLE
Re-enable bad_build_check

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#777]
Disabled at: https://github.com/google/oss-fuzz/pull/765#issuecomment-322549161

It would help us catching issues like https://github.com/google/oss-fuzz/pull/765#issuecomment-322549161

**Comment by Dor1s** [comment]
Wow, got an issue number 777!

Before re-enabling the checks, need to address some of the issues: https://github.com/google/oss-fuzz/commit/e2e0c22845c09b9bbd3dc9244ad666d4a0f410d8

There was a suggestion from @oliverchang  to avoid using `test_all` for now and to use only `bad_build_check`, that would fix a significant number of the issues from the comment linked above.

**Comment by inferno-chromium** [comment]
This is done.
