### ISSUE TITLE
How to know the version of project?

### ISSUE THREAD

**Issue by linzc21** [google/oss-fuzz#7778]
In https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=xxxx, we can get the detailed info of a bug, and my question is that how can I get the version of the project? I want to reproduce the bug, but I don't know which version of the project.

**Comment by Alan32Liu** [comment]
In the webpage of the issue link you provided, there should be a link to "**Detailed Report**", which contains two tabs respectively named:
1. "LAST TESTED REVISION" (or "FIXED REVISION RANGE" if it has been fixed)
2. "REGRESSION REVISION RANGE"

They should contain the version info you need.

**Comment by Alan32Liu** [comment]
Hope that answers your question, otherwise feel free to reopen the issue : )

**Comment by linzc21** [comment]
> Hope that answers your question, otherwise feel free to reopen the issue : )
Thanks a lot! But it seems that I am not authorized to access the page 😭. Do you know how to obtain the authorization? And my email is acbuwa@foxmail.com. Thanks again!

**Comment by linzc21** [comment]
> Hope that answers your question, otherwise feel free to reopen the issue : )
Thanks a lot! But it seems that I am not authorized to access the page 😭. Do you know how to obtain the authorization? And my email is acbuwa@foxmail.com. Thanks again!

**Comment by linzc21** [comment]
> Hope that answers your question, otherwise feel free to reopen the issue : )

Thanks a lot! But it seems that I am not authorized to access the page 😭. Do you know how to obtain the authorization? And my email is acbuwa@foxmail.com. Thanks again!

**Comment by DavidKorczynski** [comment]
> Thanks a lot! But it seems that I am not authorized to access the page . Do you know how to obtain the authorization? And my email is [acbuwa@foxmail.com](mailto:acbuwa@foxmail.com). Thanks again!

You need to be a maintainer on the given project to get access to the detailed reports. I assume you're not in this case?  Looking at your Github repositories, is this perhaps related to doing fuzzing research?

**Comment by linzc21** [comment]
> > Thanks a lot! But it seems that I am not authorized to access the page . Do you know how to obtain the authorization? And my email is [acbuwa@foxmail.com](mailto:acbuwa@foxmail.com). Thanks again!
> 
> You need to be a maintainer on the given project to get access to the detailed reports. I assume you're not in this case? Looking at your Github repositories, is this perhaps related to doing fuzzing research?

Thanks! I got it. I am not the maintainer. Yeah, I want to do some fuzzing research, and I need some data.

**Comment by DavidKorczynski** [comment]
I think in that case your best option is reaching out to the maintainers for info about the issue. Another way might be to use the 30-day-old corpus published by OSS-Fuzz and try to reproduce the issue from that

**Comment by linzc21** [comment]
> I think in that case your best option is reaching out to the maintainers for info about the issue. Another way might be to use the 30 day old corpus published by OSS-Fuzz and try to reproduce the issue from that

Many thanks!!! 😂One more question, what is '30 day old corpus'?
