### ISSUE TITLE
How to get result when I run the fuzzer locally

### ISSUE THREAD

**Issue by jasonchio-cn** [google/oss-fuzz#7803]
I‘m new to OSS-Fuzz and I want to output the results to a file. Could someone kind can help me?
The tutorial I'm following [Testing locally](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally)

**Comment by jonathanmetzman** [comment]
What results are you talking about? Need more details.

**Comment by jonathanmetzman** [comment]
Ping
