### ISSUE TITLE
Ignoring OOMs

### ISSUE THREAD

**Issue by kevinGC** [google/oss-fuzz#7826]
We've got some failures for gVisor (e.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38891) that are OOMing, but this is expected behavior. The tl;dr on why this is happening: the fuzz test is parsing data as a header, and the fuzzed data says "give me a zillion-byte object". Go rightfully refuses and panics.

Is there a way to ignore OOMs for the project? I see references to a `REPORT_OOMS` variable in [the infra](https://github.com/google/oss-fuzz/pull/6711/files), but I'm not sure where this should be set.

**Comment by jonathanmetzman** [comment]
That flag is only for ClusterFuzzLite/CIFuzz.
I don't think we have a way to ignore this since our instances only have so much RAM.
I think to stop this you should use a macro that gets set during fuzzing, if this macro is set, bail if the object size is not sane.
