### ISSUE TITLE
Requesting more resources for Cryptofuzz

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#7866]
Recently there have been 2 bugs which OSS-Fuzz did not find, but I did on my private fuzzing server. One is a libgcrypt InvMod bug and the other a set of OpenSSL/BoringSSL modular exponentiation bugs. The latter required a _specific_ modexp function to be hit, with inputs of _specific_ bit sizes, and yielding a _specific_ result. I'm constantly trying to improve the mutator to nudge the fuzzer in the right direction and increase the odds of hitting bugs, but with such a large state space and specific internal constraints like the modexp bug, it remains a numbers game.

The project is unusual in that it packs a dozen or so (large) libraries, but it is (I think) only allotted the resources of a single project, and it's quite different from e.g. a JSON parser fuzzer which plateaus after a week or so. Given the fact that OSS-Fuzz is not finding all bugs in a timely manner, this implies that allotting more resources can be worthwhile in terms of bug quantity.

There are currently a number of active blocker bugs which might be impeding progress, which I think are mostly harness bugs and I will be resolving these this week.

**Comment by jonathanmetzman** [comment]
I gave cryptofuzz double CPU. I can probably go a higher if needed.

**Comment by guidovranken** [comment]
Awesome thanks!
