### ISSUE TITLE
python projects not generating any corpus on clusterfuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#7889]
Some Python projects are reported to have bad coverage builds with the failure of e.g.

```
Step #5: [/corpus/fuzz_iter.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/fuzz_iter.zip or
Step #5:         /corpus/fuzz_iter.zip.zip, and cannot find /corpus/fuzz_iter.zip.ZIP, period.
Step #5: Failed to unpack the corpus for fuzz_iter. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
```

and there are no stats on OSS-Fuzz. However, the fuzzers run fine locally and I can extract a corpus locally, e.g.:

```
python3 infra/helper.py build_fuzzers croniter
python3 infra/helper.py run_fuzzer croniter fuzz_iter --corpus-dir=./corpdir/
```
works just fine and collects a corpus. I can also generate a coverage report using the generated corpus.

This behaviour happens for several Python projects, including `croniter` and `ansible`. 

I wasn't able to locate what caused the issue and can't really debug as I'm missing data on how the running of the fuzzers went on Clusterfuzz.

**Comment by DavidKorczynski** [comment]
This is now solved. The solution to https://github.com/google/oss-fuzz/issues/7894 fixed this as well.

**Comment by jonathanmetzman** [comment]
I suspect this has something to do with execSan
