### ISSUE TITLE
projects not showing up on oss-fuzz.com

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#7894]
Some recent projects I helped integrate are not showing up on oss-fuzz.com:
- psqlparse: https://github.com/google/oss-fuzz/pull/7724
- google-py-crc32c: https://github.com/google/oss-fuzz/pull/7742

one thing these have in common and where they differ to previous integrations is that only `vendor_ccs` is filled out  and no `auto_ccs` or `primary_contact`.

**Comment by jonathanmetzman** [comment]
Related: https://github.com/google/oss-fuzz/issues/10266
