### ISSUE TITLE
Missing fuzzers / fuzzing statistics

### ISSUE THREAD

**Issue by nszetei** [google/oss-fuzz#7902]
I have these issues related to the fuzzer statistics:

- When I visit the [fuzzer-stats](https://oss-fuzz.com/fuzzer-stats?group_by=by-fuzzer&date_start=2022-06-20&date_end=2022-06-21&fuzzer=libFuzzer&job=libfuzzer_asan_teleport&project=teleport]) and click to search fuzzers, some of them are missing. For example `fuzz_new_matcher` was built successfully, but it's not included in the list. 

Also, clicking on some of them yield:

*Got error with status: 404
No stats.*

- Why are there only 7 fuzzers visible in the list from yesterday?

**Comment by oliverchang** [comment]
Thanks for filing the issue! 

I see stats now for fuzz_new_matcher now on https://oss-fuzz.com/fuzzer-stats?group_by=by-fuzzer&date_start=2022-06-20&date_end=2022-06-22&fuzzer=libFuzzer&job=libfuzzer_asan_teleport&project=teleport%5D. 

There was likely just a temporary issue with availability.

**Comment by nszetei** [comment]
@oliverchang thanks for your reply! I still see only 13 fuzzers, but when I check the [build logs](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#teleport), there should be around 25 added. Is it because it's running for two days only and I have to wait a few more days?
