### ISSUE TITLE
Testcase not being closed

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#7909]
I am not sure if this is the right place to report this but it looks like one of the testcases for @ImageMagick is not being closed. The testcase states the following `Will be auto-closed on Thu, Jan 2, 2020 if flaky crash no longer seen` message but it is still not closed: https://oss-fuzz.com/testcase-detail/4719563417714688. It also has a reference to a duplicate testcase but that shows this error message: `Invalid test case!`. And the group that is being referenced ([5197816155209728](https://oss-fuzz.com/testcases?q=group%3A5197816155209728)) only contains this testcase.

**Comment by oliverchang** [comment]
Thanks for reporting! This is quite old and unfortunately a bit hard to debug what happened here at this point.

I've marked the monorail issue as WontFix -- please let us know if you notice more instances of this.

**Comment by dlemstra** [comment]
Here are a couple other ones:
- https://oss-fuzz.com/testcase-detail/5854391533961216
- https://oss-fuzz.com/testcase-detail/6563839341625344
- https://oss-fuzz.com/testcase-detail/5776907855069184
- https://oss-fuzz.com/testcase-detail/6378043943288832
- https://oss-fuzz.com/testcase-detail/5120916129972224

And I also found this one:

Marked as fixed but linked with an empty group:
- https://oss-fuzz.com/testcase-detail/5854601889710080

**Comment by oliverchang** [comment]
I've manually marked several of these as wontfix. 

However some, while flaky, are still reproducing according to the "STATISTICS" section on the bottom (e.g. see https://oss-fuzz.com/testcase-detail/5120916129972224)
