### ISSUE TITLE
oss-fuzz-base: local python installation

### ISSUE THREAD

**Issue by ksztyber** [google/oss-fuzz#7914]
There's a local python installed under `/usr/local` on the oss-fuzz-base image:
```
$ which python3
/usr/local/bin/python3
$ which pip3
/usr/local/bin/pip3
```
Is there any reason for this? It causes build failures in SPDK [1], as we're using `pip` to install several dependencies, which fail because the local pip version is doesn't have up-to-date wheel platform tags, so it tries to them from source, which doesn't work for some reason. I haven't tracked down why the compilation fails, but I don't think it should even try to do that. It doesn't happen with pip packaged by the distro, but that doesn't help much, as `/usr/local/bin` is earlier in the `PATH`.

It can be worked around by upgrading the local pip version: `pip3 install --upgrade pip`, but I'm curious what's the reason behind the local python installation.

[1] https://oss-fuzz-build-logs.storage.googleapis.com/log-ff4e2de6-27ad-4fed-a9d3-67e00f676c5a.txt

**Comment by ksztyber** [comment]
Is that still necessary? It seems that the version from the distro is newer than the one installed manually:
```
root@218fe8d37ac5:/src/spdk# /usr/bin/python3 --version
Python 3.8.10
root@218fe8d37ac5:/src/spdk# /usr/local/bin/python3 --version
Python 3.8.3
```

**Comment by jonathanmetzman** [comment]
> Is that still necessary? It seems that the version from the distro is newer than the one installed manually:
> 
> ```
> root@218fe8d37ac5:/src/spdk# /usr/bin/python3 --version
> Python 3.8.10
> root@218fe8d37ac5:/src/spdk# /usr/local/bin/python3 --version
> Python 3.8.3
> ```

Youre probably right that we can stop doing this. I think it's basically a holdover from when we were on 16.04. I think I kept it because I wanted to minimize unnecessary changes when doing a big change. Now we could probably get rid of it.

**Comment by ksztyber** [comment]
Thanks for the info. I'd appreciate it if you pinged me once they're removed.

**Comment by jonathanmetzman** [comment]
I think we can't remove this.
