### ISSUE TITLE
Please grant access to fwang@igalia.com

### ISSUE THREAD

**Issue by fred-wang** [google/oss-fuzz#7919]
Hello,

Igalia sent an intent-to-ship for MathML in Chromium and there were questions about fuzzing support. @drott mentioned checking https://oss-fuzz.com/fuzzer-stats but I'm getting "Access Denied" message. Can you please grant me access to oss-fuzz.com? Thank you!

**Comment by drott** [comment]
Not sure to what extent it would help, but you may also try adding yourself to https://github.com/Oss-fuzz/oss-fuzz/blob/master/projects/harfbuzz/project.yaml#L3

**Comment by jonathanmetzman** [comment]
The link is wrong.  https://github.com/google/oss-fuzz/blob/master/projects/harfbuzz/project.yaml#L3
But it depends which project you are trying to access. Is it harfbuzz?

**Comment by jonathanmetzman** [comment]
Chromium/blink is in the chromium bug tracker. I think you need to see restrict-view-security bugs to access it.

**Comment by fred-wang** [comment]
cc @oliverchang 

PR opened at https://github.com/google/oss-fuzz/pull/7931
