### ISSUE TITLE
Permission to change Monorail status

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#7926]
In the Ghostscript project many of the fuzzers hit an interpreter where timeouts happen from time to time, and these are perfectly valid timeouts that aren't bugs. The Ghostscript maintainer adds comments explaning why this is a wontfix but does not have access to setting the status: would it be possible to get this in order to keep proper tracking of issues?

See: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48530#c1 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48437#c1

Ken is the one usually assessing the bugs: https://github.com/google/oss-fuzz/blob/a2eaeebecb37139041fcbb7a4e605567778634d5/projects/ghostscript/project.yaml#L10 but I would also happy if I could get edit access and help assing wontfix'es when needed.

There was a similar issue on OSS-Fuzz here in terms of setting WontFix: https://github.com/google/oss-fuzz/issues/1402

**Comment by oliverchang** [comment]
I just granted ken.sharp@artifex.com access to change the issue status. Let me know if this does not work.
