### ISSUE TITLE
Coverage buid failure

### ISSUE THREAD

**Issue by dlemstra** [google/oss-fuzz#7953]
With the @ImageMagick project we have a coverage build failure: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45679. The logs show that it fails because of a stackoverflow in code of one of our dependencies. This is a problem that has also been reported (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48117) but we are waiting for a fix upstream.

I do have the feeling that this is a bug in the oss-fuzz tooling. If this is not a bug in the oss-fuzz tooling then I would like to know how we can resolve this.

**Comment by jonathanmetzman** [comment]
Ah this is a fair point. Yeah ideally we wouldn't exit on an error when generating coverage. But it's pretty rare that a bug manifests in a coverage build and not in ASAN build. It will probably only be weird stuff like this.

**Comment by jonathanmetzman** [comment]
I don't think this is correct. These testcases are from OSS-Fuzz's minimized corpus. If any of those cause a crash on the ASAN build (which is used to minimize the corpus) they are not added to the corpus. So these testcases are all testcases that got run on an ASAN build without causing a crash.

**Comment by oliverchang** [comment]
The build is no longer failing, so closing.
