### ISSUE TITLE
wolfssl (and other projects?) have stopped building since June 15th

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#7955]
The wolfssl project has stopped building without raising an error. Glancing over the list at https://oss-fuzz-build-logs.storage.googleapis.com/index.html several other projects seemed to have stopped as well.

The wolfssl coverage build has stopped building for a few days because there is a compilation error (I'm working on resolving that) but that seems unrelated to the cessation of the main build.

**Comment by guidovranken** [comment]
These have stopped on 15-06:

- binutils
- brotli
- bzip2
- capstone
- cjson
- cmark
- google-py-crc32c
- harfbuzz
- hostap
- istio
- jbig2dec
- json-c
- lcms
- libexif
- libfdk-aac
- libidn2
- libldac
- libpcap
- libplist
- libwebp
- libyaml
- lz4
- miniz
- mupdf
- nanopb
- nghttp2
- ntp
- openjpeg
- pcre2
- pffft
- qubes-os
- speex
- stb
- tremor
- unicorn
- vorbis
- wolfssl
- wuffs
- xz
- zlib
- zstd

**Comment by jonathanmetzman** [comment]
Maybe something to do with this error i see in the logs: ```Scheduler creation for wolfssl failed with 429 Quota exceeded for quota metric 'Read requests per region' and limit 'Read requests per minute per region' of service 'cloudscheduler.googleapis.com' for consumer```

**Comment by jonathanmetzman** [comment]
I just triggered a binutils build and now it seems to work. I think I've fixed the issue.

**Comment by jonathanmetzman** [comment]
Thanks for the detailed report btw

**Comment by guidovranken** [comment]
Thanks Jonathan!
