### ISSUE TITLE
Reproducer testcases inaccessible

### ISSUE THREAD

**Issue by fcgorter** [google/oss-fuzz#7959]
I'm wondering whether there is a reason why some reproducer testcases are not accessible?
For example, for the recent issues: 48774, 48644, 48636, 48633, 48620, 48613 
the reproducer link leads to the Access Denied page (You (email=xyz) are not authorized to access this page)
Others do work however, e.g.: 48720 
Is there a way I can gain access to all the testcases?

**Comment by fcgorter** [comment]
Thanks for the reply, David.
However, https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47901#c3
is also marked as opened to the public, but the test case is not accessible.
How is that case different than e.g. 47673 as you pointed out?

**Comment by DavidKorczynski** [comment]
You're right @fcgorter there is a discrepancy here -- and I'm not sure what the difference is. @jonathanmetzman @oliverchang @Navidem  do you know?

**Comment by oliverchang** [comment]
We have a 30 day delay to the reproducer disclosure after initially making the report public. This is to prevent unintended disclosure if something goes wrong with the automation.
