### ISSUE TITLE
Can fuzzers be run without sanitizers?

### ISSUE THREAD

**Issue by alexcrichton** [google/oss-fuzz#7974]
Today I was looking at some fuzzing statistics for the Wasmtime project on oss-fuzz. We've got some slow-ish fuzzers that are clocking in at what appears to be ~10 executions per second. Locally though whenever I run fuzzers I see a significant performance boost when asan is disabled. For example locally I get ~20 executions per second with asan and ~300 per second without asan. For Rust projects that are built with `cargo fuzz build` the default is to always enable asan but the `-s none` flag will disable sanitizers at build-time. Currently Wasmtime's `build.sh` inherits the default of `cargo fuzz build` and enables asan by default. Additionally though Wasmtime is configured to have the `address` sanitizer enabled via its `project.yaml` which I presume hooks up somehow into configuration options and such for oss-fuzz.

Would it be possible to add a `none` configuration in the `sanitizers` configuration in `project.yaml`? For our case as a Rust project we're not really all that interested in the asan builds. While we do have `unsafe` code and we don't want to necessarily remove asan completely the main value we get from oss-fuzz is finding logic bugs or bugs when run against other engines (e.g. we execute a wasm module and so does v8 and we compare the results to make sure they're the same). Or otherwise is there something we can do for Wasmtime specifically where maybe one or two fuzzers have asan but the rest are built without asan?

Or somewhat orthogonally, is it expected that asan slows down code by ~15x? I know that the way fuzzing is configured is different in Rust than in C++ since we're not "just using clang" but rather there are specific LLVM flags hardcoded into `cargo fuzz` which likely historically corresponded to what Clang does for `-fsanitize=...` but may have diverged since then. If a 15x slowdown isn't expected then it may be a bug in how Rust code is built with sanitizers.

**Comment by catenacyber** [comment]
Hey @alexcrichton looking at this by chance, you can try to profile the as an runs cf #5995 

In Suricata case, (if I remember correctly), there are some functions whose instrumentation can be skipped to get some significant performance improvements...

**Comment by jonathanmetzman** [comment]
I don't know if this slowdown is normal. I would guess not. Maybe @hctim or @morehouse can speak to that.
We're going to be adding new fuzzer that I think will run targets without any sanitizer by default (right @Alan32Liu ?)
So I think we won't add that configuration and instead will rely on the new fuzzer.

**Comment by hctim** [comment]
> Or somewhat orthogonally, is it expected that asan slows down code by ~15x?

In normal code usage, ASan causes slowdown of ~2x. Certain (often synthetic) load patterns, like a malloc/free hot loop, can result in slowdowns greater than that (but 15x is certainly unexpected).

Have you tried playing around with some of ASan's options (runtime/compile time) and measuring the overhead? You could try `-mllvm -asan-stack=0` at compile time, or `-mllvm -asan-use-after-return=never`, or even `ASAN_OPTIONS=poison_heap=0` at runtime.

**Comment by Alan32Liu** [comment]
> I don't know if this slowdown is normal. I would guess not. Maybe @hctim or @morehouse can speak to that.
> We're going to be adding new fuzzer that I think will run targets without any sanitizer by default (right @Alan32Liu ?)
> So I think we won't add that configuration and instead will rely on the new fuzzer.

Yep, I am working on integrating that sanitizer.

**Comment by alexcrichton** [comment]
Having a no-sanitizer option as a new fuzzer would be great, and I think that would be definitely beneficial for Rust projects (and Wasmtime specifically here). Is there perhaps an issue I can follow to track that being done? If not no worries and I can just check back in awhile later.

Testing @hctim's suggestions for compile flags locally I get:

| configuration | iters/s |
|---------------|---------|
| no sanitizers | 320 |
| asan  | 140 |
| asan  + `ASAN_OPTIONS=poison_heap=0` | 130 |
| asan + `-asan-stack=0 -asan-use-after-return=never` | 140 | 

I'm not sure why the asan build sped up here vs when I tested it last week. The main difference is that there's no corpus to start from whereas prior I used whatever corpus I had lying around. So this seems to show that asan may not be performing as bad as I thought? Or maybe the seed on the asan fuzzer from last week got unlucky and took a very different path than the no-asan fuzzer.

In any case it appears that a no-sanitizer fuzzer would clearly improve speed here and that's already in the works, so I think it'd be best to integrate with that when it comes about.

**Comment by Alan32Liu** [comment]
> Is there perhaps an issue I can follow to track that being done? If not no worries and I can just check back in awhile later.

Unfortunately, there isn't at this moment.
We are evaluating the new fuzzer and will integrate it into OSS-Fuzz later.

**Comment by alexcrichton** [comment]
Ok sounds good, we'll try to keep our eyes peeled for this feature.
