### ISSUE TITLE
More useful "All current crashes"

### ISSUE THREAD

**Issue by LebedevRI** [google/oss-fuzz#798]
All of the fuzzing entities ({afl,libfuzzer}_{asan,ubsan,msan}_${project}) have a "crash stats" pages. They contain nice stats about frequency/count of the problems encountered. It is useful to gauge which issue is most impactful on the fuzzing, and should be fixed first. 

But. All these pages are unique/separate.
It would be awesome to have one page that would combine all these reports.

**Comment by inferno-chromium** [comment]
I think the reason for this is project filter for oss-fuzz is not there at all. We need to have that.

**Comment by oliverchang** [comment]
Does https://oss-fuzz.com/v2/crash-stats (without any job filters) give you what you're after?

**Comment by LebedevRI** [comment]
@oliverchang yes, that is **much** better :)

**Comment by inferno-chromium** [comment]
Also, i have a fix in mind, that will show project filter.

**Comment by inferno-chromium** [comment]
Ok, if you own one project, you can just go to crash-stats page and see crashes for that one project (project filter will be hidden). if you own multiple projects in oss-fuzz, project filter will now work and you will use it to select project name.
