### ISSUE TITLE
Permissions issue accessing issue

### ISSUE THREAD

**Issue by lws-team** [google/oss-fuzz#7985]
Hi -

I would like to look at issue 48959 on libwebsockets, but I don't have persmissions on my related Google account to see the issue on chromium.org or the details on oss-fuzz.com.

Thanks

**Comment by DavidKorczynski** [comment]
Is your email listed in `project.yaml` associated with a Google account and is it an "alternate email" on the account? The email listed in `project.yaml` should be the primary email of the Google account. (See here: https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication)

**Comment by lws-team** [comment]
> Is your email listed in project.yaml associated with a Google account and is it an "alternate email" on the account?

Yes... it's an alternate email on a google account.

> The email listed in project.yaml should be the primary email of the Google account.

I see, thanks.  I raised a PR for the change to the primary email on the google account.
