### ISSUE TITLE
Create a coverage build using clang source based code coverage

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#799]
https://clang.llvm.org/docs/SourceBasedCodeCoverage.html

Oliver has a hacky CL for that: https://github.com/oliverchang/oss-fuzz/commit/343ddfffebcf80533bd96b94892083650446327e

Basically, the following flags need to be added to CFLAGS / CXXFLAGS:

    -fprofile-instr-generate -fcoverage-mapping

Neither of sanitizers are needed for that build.

There are two goals here:

1) to see how many project would fail during the build 

2) to see how build sizes for different project would change

The second point may help us to debug issue 759795, as we need a smaller reproducer that has the same build size overhead.

**Comment by Dor1s** [comment]
//cc @cherusker @jadamcrain @catenacyber @evverx @reaperhulk @alex 

Please take a look at the [Code Coverage doc](https://github.com/google/oss-fuzz/blob/master/docs/code_coverage.md) and try out the new solution we've just landed. Looking forward to your feedback! And don't forget to pull the latest docker images (`python infra/helper.py pull_images`).

**Comment by evverx** [comment]
I'm having trouble making `gsutil` work, but I left a couple of comments in https://github.com/google/oss-fuzz/pull/1494.

Thank you for the reminder, by the way. I seem to have a tendency to forget to pull the latest images and changes in the repository :-)

**Comment by Dor1s** [comment]
@evverx, thanks a lot for the feedback! I'll address it later today!

**Comment by alex** [comment]
It doesn't appear to work with a macOS host do to a`find` compatibility issue:

```
~/p/oss-fuzz ❯❯❯ python3 infra/helper.py profile vorbis
find: -executable: unknown primary or operator
Traceback (most recent call last):
  File "infra/helper.py", line 755, in <module>
    sys.exit(main())
  File "infra/helper.py", line 165, in main
    return profile(args)
  File "infra/helper.py", line 550, in profile
    download_corpus(args.project_name)
  File "infra/helper.py", line 532, in download_corpus
    fuzz_targets = _get_fuzz_targets(project_name)
  File "infra/helper.py", line 476, in _get_fuzz_targets
    output = subprocess.check_output(command)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['find', '/Users/agaynor/projects/oss-fuzz/build/out/vorbis', '-maxdepth', '1', '-type', 'f', '-executable']' returned non-zero exit status 1.
```

**Comment by inferno-chromium** [comment]
Yes i think it is not good to rely on os-specific command line tools. lets change to python os.walk please.

**Comment by alex** [comment]
@inferno-chromium #1519 sent :-) I used `listdir` instead of `walk` since `find` already had `-maxdepth 1`

**Comment by alex** [comment]
Next error I'm encountering:

```
~/p/oss-fuzz ❯❯❯ python3 infra/helper.py profile --no-corpus-download vorbis
Running: docker run --rm -i --privileged -e FUZZING_ENGINE=libfuzzer -e PROJECT=vorbis -e SANITIZER=profile -v /Users/agaynor/projects/oss-fuzz/build/out/vorbis:/out -v /Users/agaynor/projects/oss-fuzz/build/corpus/vorbis:/corpus -p 8008:8008 -t gcr.io/oss-fuzz-base/base-runner coverage
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"coverage\": executable file not found in $PATH": unknown.
Failed to generate clang code coverage report.
```

**Comment by alex** [comment]
Nevermind, the `base-runner` image hadn't been updated, only `base-builder`.

**Comment by alex** [comment]
Substantive feedback:

- Looks pretty good!
  - I'd love it if covered code was highlighted green as in other coverage systems
- Can we exclude the libFuzzer source from showing up in the coverage UI?
- I assume we'll have this soon in the OSS-Fuzz UI?
- I found the corpus downloading stuff to be confusing (mostly because I couldn't figure out how to get `gcloud` installed using my normal package managers on macOS), and I ended up just going through the OSS-Fuzz UI to download the corpus backup and unzipping it to the right location.

**Comment by Dor1s** [comment]
> Looks pretty good!
Yay, thanks!

> I'd love it if covered code was highlighted green as in other coverage systems
I think it's doable, but not sure how useful it would be in cases when most of the code is covered, and you're actually looking for non-covered red spots only. Another detail here is that there are many lines which aren't executable, like comments, dead stripped functions, etc. I don't think that mixing white and green around those lines would be very convenient to look at (plus some comments inside a region still can be marked as covered), but that's all just a personal taste, I guess.

> Can we exclude the libFuzzer source from showing up in the coverage UI?
Absolutely, we should do that! I'll upload a fix.

> I assume we'll have this soon in the OSS-Fuzz UI?
Yes!

> I found the corpus downloading stuff to be confusing (mostly because I couldn't figure out how to get gcloud installed using my normal package managers on macOS), and I ended up just going through the OSS-Fuzz UI to download the corpus backup and unzipping it to the right location.
:( we can try using the web link provided on OSS-Fuzz stats page, but:

a) it might be even more complicated, as we have to handle authorization somehow
b) we cannot download the full corpus via web, only backup archive

**Comment by alex** [comment]
FWIW, I find Python's `coverage.py`'s UI to be very good, in terms of colors: https://screenshotscdn.firefoxusercontent.com/images/f62a0cbc-642c-43c1-8be4-8f9bde1ce2db.png

The other really nice thing is that the `j` and `k` keys can be used to move between uncovered hunks.

**Comment by evverx** [comment]
More of a feature request: I think it would be great if `profile` could generate a text report via `llvm-cov report -format=text` if something like `--cli` or `--text` was passed to `helper.py profile`. It should be enough to get the picture and, probably more importantly, could be used in scripts.

**Comment by catenacyber** [comment]
@Dor1s looks good to me (tried with opendnp3)

**Comment by Dor1s** [comment]
Thanks a lot everyone for the feedback! For new feature requests, let's create new issues, as it becomes hard to track all the suggestions posted in different places (e.g. this issue, closed PRs, merged commits).

**Comment by Dor1s** [comment]
I've also added support for running a specific fuzz target with an arbitrary corpus stored on the host machine: https://github.com/google/oss-fuzz/commit/9874e09f53596e2f5279bb0292b713882cfe8f1b

Documentation: https://github.com/google/oss-fuzz/blob/master/docs/code_coverage.md#single-fuzz-target

**Comment by Dor1s** [comment]
Done in the late 2018.
