### ISSUE TITLE
Update Code Intelligence build for Go1.18

### ISSUE THREAD

**Issue by reedloden** [google/oss-fuzz#8004]
https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/install_go_CodeIntelligenceTesting.sh hasn't been updated to support Go 1.18 yet, which means it can't be used by projects that utilize native Go fuzzing.

**Comment by oliverchang** [comment]
Thanks for filing this issue @reedloden!

The Code Intelligence patches will be be included in the Go 1.19 release, which should be out very soon. Given the short window here, I'm not sure it makes too much sense to update that particular image. 

What issues in particular did you encounter while using the Code Intelligence build?

**Comment by reedloden** [comment]
#7683 had moved `teleport` over to use the Code Intelligence build. However, when I was updating our fuzzing environment in #7895 for Go 1.18 native fuzzing, I had to swap back to the normal build, as it was causing build failures. I was just filing this to make sure that issue was known, but seems like you all are already on it if the changes were upstreamed into Go 1.19 proper.

**Comment by oliverchang** [comment]
Ack! I'll close this for now since there's nothing actionable here.
