### ISSUE TITLE
Use of -fork=2 in fuzzers?

### ISSUE THREAD

**Issue by ktmf01** [google/oss-fuzz#8006]
flac has a few fuzzers which write to a temp file named `/tmp/tmp.flac`: the fuzzing input is (partly) written to that file. This is obviously incompatible with fuzzer option `-fork`. I read somewhere in the docs that fuzzers run in a docker image with a single CPU core and 2GB of RAM, so I figured this option isn't used by oss-fuzz anyway.

For two fuzzers, I have had no problems, but now the third fuzzers that uses this tempfile runs into an enormous amount of unreproducible crashes. I've tried a few things (see #7997), but to no avail. Once more looking at the crash reports I see `-fork=2` is in use which makes this problem reproducible in my own environment as well.

Now my question is: why does this only happen with this fuzzer? Is there an option somewhere I should change? Should I randomize tempfile names? Should I do this only with this fuzzer or with all fuzzers using tempfiles?

**Comment by jonathanmetzman** [comment]
I think we might use fork mode sometimes.
I don't think we provide an option for disabling this. I don't know your answer to why it only happens for this fuzzer but I would randomize all of your tempfile names
