### ISSUE TITLE
openjpeg: should we have a fuzz target for opj_compress?

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#802]
It looks like we only have a fuzz target for [decompression](https://oss-fuzz.com/v2/fuzzer-stats/by-fuzzer/2017-08-22/2017-08-28/fuzzer/libFuzzer/job/libfuzzer_asan_openjpeg).

However there are also bugs in compression (see e.g. https://blogs.gentoo.org/ago/2017/08/28/openjpeg-invalid-memory-write-in-tgatoimage-convert-c/). Should we add a fuzz target for this also? @rouault

**Comment by rouault** [comment]
Yes compression side isn't tested. I created https://github.com/uclouvain/openjpeg/issues/1000 a few days ago to track this. That wouldn't be trivial to do as opj_compress and other depending code that isn't part of libopenjp2 would need to be librarified somehow to be compatible of libfuzzer entry point. I guess the situation is easier with AFL where you can run the actual opj_compress binary
Contributions welcome

**Comment by oliverchang** [comment]
Thanks for clarifying! Closing this in favour of the openjpeg issue.
