### ISSUE TITLE
[openthread] seed corpus not generating expected coverage

### ISSUE THREAD

**Issue by jwhui** [google/oss-fuzz#803]
As a test, I have a [seed corpus with a single item](https://github.com/openthread/openthread/tree/master/tests/fuzz/corpora/radio-receive-done) added to OpenThread.  This seed corpus should trigger [ot::Mle::Mle::HandleUdpReceive()](https://oss-fuzz.com/coverage_report/fuzzer/libFuzzer_openthread_radio-receive-done-fuzzer/2017-08-28/f/%2Fsrc%2Fopenthread%2Fsrc%2Fcore%2Fthread%2Fmle.cpp).  However, OSS-Fuzz does not show this coverage.  Thoughts/suggestions?

**Comment by oliverchang** [comment]
Could https://github.com/google/oss-fuzz/blob/master/docs/fuzzer_environment.md#network-access affect the coverage here? 

We don't have any network interfaces available in our fuzzer environment, but this restriction will be relaxed very soon.

**Comment by jwhui** [comment]
I don't think so.  OpenThread's fuzz targets do not depend on having network access.

**Comment by kcc** [comment]
I confirm that the sample input triggers calls to `Mle::HandleUdpReceive`, and that our coverage dashboard doesn't see that. @oliverchang could you please double-check that we use the seed corpus properly?

**Comment by kcc** [comment]
@jwhui there could also be some problem on your side, namely, the fuzz target seems to be non-deterministic to some extent. 
E.g. if I pass the same input file 100 times, only the first 20 actually cause `Mle::HandleUdpReceive` to be called. 

```
# 'z' is the input that triggers Mle::HandleUdpReceive
./tests/fuzz/radio-receive-done-fuzzer $(for((i=0;i<100;i++)); do echo z; done ) 2>&1 
```

**Comment by oliverchang** [comment]
Hmm the seed corpus is definitely merged into the main corpus:

```
$ gsutil -m rsync gs://openthread-corpus.clusterfuzz-external.appspot.com/libFuzzer/openthread_radio-receive-done-fuzzer corpus
$ sha1sum corpus/0000000000000001

70ba919ea29a8a390a5f918397954176f0f857fa  corpus/0000000000000001
```

This matches the sha1 of https://github.com/openthread/openthread/blob/master/tests/fuzz/corpora/radio-receive-done/mle-parent-request and the fuzzer logs (https://console.cloud.google.com/storage/browser/openthread-logs.clusterfuzz-external.appspot.com/libFuzzer_openthread_ip6-send-fuzzer/libfuzzer_asan_openthread/2017-08-31/) don't seem to indicate that the target is broken in any obvious way...

**Comment by jwhui** [comment]
@kcc thanks for pointing that out.  It appears that the fuzz targets were not clearing some state, which is why only the initial iterations trigger `Mle::HandleUdpReceive`.  I'll submit a fix to OpenThread soon.

**Comment by jwhui** [comment]
With my local updates, I used the docker image to validate the coverage reporting and it now shows `Mle::HandleUdpReceive` as covered.

**Comment by kcc** [comment]
Cool! Add more seeds then!
