### ISSUE TITLE
python coverage issues due to missing corpus

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#8030]
Some recent Python projects reported broken coverage builds due to missing corpus downloads. And there are no stats for these projects on oss-fuzz.com. 

Example: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49261

I am able to generate coverage locally.

This is similar behaviour as https://github.com/google/oss-fuzz/issues/7889 although I suspect it's not the same solution, i.e. the fix from here https://github.com/google/oss-fuzz/pull/7900 ?

**Comment by jonathanmetzman** [comment]
I suspect this has something to do with execSan

**Comment by DavidKorczynski** [comment]
okay -- let me know if there is something I can do.

**Comment by oliverchang** [comment]
It looks like we're hitting some quota limits -- I'll try to get us more.

**Comment by oliverchang** [comment]
We have the extra quota now and are fuzzing it. However we are seeing this:


```
"Traceback (most recent call last):
  File "fuzz_jwt.py", line 27, in <module>
Exception: Could not find public cert
[1298309] Failed to execute script 'fuzz_jwt' due to unhandled exception!
"
```

**Comment by DavidKorczynski** [comment]
hmm. This exception is thrown when a given cert is not available, which probably happens because the certs copied here https://github.com/google/oss-fuzz/blob/7970e727efcbe501abb4223aa6b2202caf30c6d8/projects/g-api-auth-library-python/build.sh#L19-L20 are not present in the given fuzzing instance on clusterfuzz. Let me change it up to embed the certicates in the fuzzers themselves or see if I can do something with the pyinstaller and embed the datafiles in the binary.
