### ISSUE TITLE
execSan possible false positive

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#8049]
I got this issue https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49312 which I believe is an execSan report. From what I can tell it flags this line https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/fuzzer/FuzzerUtilLinux.cpp#L25 which I assume is a false positive?

**Comment by oliverchang** [comment]
Yep, this one has a bad stacktrace from a bug in the detector, and the actual issue found is a false positive anyway. 

We're going to prevent any execSan bugs from getting filed by default.

**Comment by oliverchang** [comment]
(Closed this particular bug).
