### ISSUE TITLE
net-snmp coverage build fails

### ISSUE THREAD

**Issue by bvanassche** [google/oss-fuzz#8058]
The Net-SNMP coverage build fails but it is not clear to me why (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46588). Can anyone take a look at the latest build failure logs and tell us what we are doing wrong?

**Comment by DavidKorczynski** [comment]
I have been a bit puzzled by it for a while (see my comment in the bug here https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46588#c2) 

Will give it another go. I have a feeling it's something we should change in the fuzzer itself.

**Comment by DavidKorczynski** [comment]
This should be fixed by https://github.com/net-snmp/net-snmp/pull/439

Once https://oss-fuzz.com/testcase-detail/6008157151821824 is closed (the issue has not been tested through latest net-snmp revision yet) then I think the coverage failure should close as well.

**Comment by DavidKorczynski** [comment]
https://github.com/net-snmp/net-snmp/pull/439 seems to have done the job -- coverage succeeds now https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46588#c19 

Thanks for the patience on this one @bvanassche !
