### ISSUE TITLE
libexpat entropy false positive

### ISSUE THREAD

**Issue by hartwork** [google/oss-fuzz#806]
As requested at https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3233#c3 I'm opening this ticket here:

Makes perfect sense, the commits in range do include new sources of entropy.

We use this blacklist file for msan upstream through `-fsanitize-blacklist=$PWD/memory-sanitizer-blacklist.txt`: [memory-sanitizer-blacklist.txt](https://github.com/libexpat/libexpat/blob/master/expat/memory-sanitizer-blacklist.txt).

Could you adjust fuzzing code accordingly?

**Comment by kcc** [comment]
> Could you adjust fuzzing code accordingly?

We [encourage](https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md) the code owners to own their fuzzing code :)

**Comment by hannob** [comment]
Ultimately this is a limitation of msan. I've created a minimal example and opened a bug for msan:
https://github.com/google/sanitizers/issues/852

**Comment by kcc** [comment]
See https://github.com/google/sanitizers/issues/852#issuecomment-327305535

**Comment by inferno-chromium** [comment]
Tracked by sanitizer bug, closing it here.
