### ISSUE TITLE
Unable to see 47150 issue (I maintain the code being examined)

### ISSUE THREAD

**Issue by davea42** [google/oss-fuzz#8061]
Received a report https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47150
but completely unable (as the maintainer of the software being tested) to see any
details at all.    The May 1 original report was considered junk by gmail and
did not show up in my gmail inbox.

**Comment by DavidKorczynski** [comment]
Hi @davea42 ! We worked on this together before so can help here! What do you mean by "unable to see any details at all"? In the URL provided, if you click on the link "Detailed Report" do you not see the stacktrace?

**Comment by MarcoFalke** [comment]
The issue is now public, so this can be closed?
