### ISSUE TITLE
oss-fuzz missing stats

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#8067]
I was looking for dbus-broker reports and even though it has been on OSS-Fuzz for two days it seems it hasn't been fuzzed there judging by https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2022-06-30&date_end=2022-07-22&fuzzer=libFuzzer_dbus-broker_fuzz-message&job=libfuzzer_asan_dbus-broker&project=dbus-broker.
 
According to https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2022-06-30&date_end=2022-07-22&fuzzer=libFuzzer_systemd_fuzz-dns-packet&job=libfuzzer_asan_systemd&project=systemd that particular systemd fuzz target hasn't been run either since July 7.

**Comment by jonathanmetzman** [comment]
I'm guessing this is the same issue as https://github.com/google/oss-fuzz/issues/8030
CC @oliverchang

**Comment by oliverchang** [comment]
This is a different issue with our stats not loading (rather than things not getting fuzzed).

**Comment by oliverchang** [comment]
The latest stats are now available at:

https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2022-06-30&date_end=2022-07-25&fuzzer=libFuzzer_systemd_fuzz-dns-packet&job=libfuzzer_asan_systemd&project=systemd

and

https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2022-06-30&date_end=2022-07-25&fuzzer=libFuzzer_dbus-broker_fuzz-message&job=libfuzzer_asan_dbus-broker&project=dbus-broker

I'll keep this bug open to do a manual backfill to get the data for missing days added.

**Comment by oliverchang** [comment]
Unfortunately I never got around to backfilling, and given that no one else complained, I'm assuming it's not a priority at this point. Closing, unless there's any objections.
