### ISSUE TITLE
Project `ansible` failed to build

### ISSUE THREAD

**Issue by Alan32Liu** [google/oss-fuzz#8080]
Project `ansible` failed to build because 
```
package 'ansible-core' requires a different Python:  3.8.3 not in '>=3.9'
```

Here is [the link to the failure](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#ansible).

**Comment by DavidKorczynski** [comment]
Closing this as fixed by https://github.com/google/oss-fuzz/pull/8170

Python 3.9 was not strictly needed.
