### ISSUE TITLE
libpng coverage dropped by 5x, and corpus got reduced

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#809]
On Aug 29 the coverage (edge/func/corpus): `34.75% (2305/6634) | 43.28% (177/409) | Coverage | 2061 (2 MB)`
On Aug 30: `3.69% (43/1166) | 20.59% (21/102) | Coverage | 16 (2 KB)`

Sounds really bad. Something probably broke in the build system. Needs investigation. Looking. 

@glennrp

**Comment by kcc** [comment]
See also https://github.com/glennrp/libpng/issues/170#issuecomment-326639350

**Comment by kcc** [comment]
Or this may be caused by recent changes in `contrib/oss-fuzz/libpng_read_fuzzer.cc`

**Comment by kcc** [comment]
Yes, most likely contrib/oss-fuzz/libpng_read_fuzzer.cc
https://github.com/glennrp/libpng/commit/f6ca33d42c88b7be9ea4444cbef704ad6f815536 works fine.

**Comment by glennrp** [comment]
Something odd was happening yesterday.  The "Build Status" showed a red /!\ icon for libpng and a dozen or more other projects. The log did not appear to show a failure in libpng building but some failure to access one of the google/oss-fuzz hosts.  I thought I'd just wait it out for another day.

**Comment by kcc** [comment]
Nope, the contrib/oss-fuzz/libpng_read_fuzzer.cc seems to be completely broken.
f6ca33d42c88b7be9ea4444cbef704ad6f815536 is the last revision that worked. 
Several following revisions did not compiler, that a few crashed with a null deref on any input. 
Now they work, but don't do anything useful (have very low coverage).

**Comment by kcc** [comment]
> I did update libpng_read_fuzzer.cc but the "coverage" report is showing me some other version.

Can you elaborate?

**Comment by glennrp** [comment]
I looked at the "coverage" report and the fuzzer source shown was not the
current fuzzer source.

**Comment by kcc** [comment]
There is 1-2 day lag, so it was probably showing a version before your recent refactoring. 

Anyway, do you need help reproducing the current problem (libpng_read_fuzzer.cc not providing useful coverage)?

**Comment by oliverchang** [comment]
This (https://oss-fuzz.com/coverage_report/fuzzer/libFuzzer_libpng_read_fuzzer/2017-09-01) should be up to date (up to https://github.com/glennrp/libpng/commit/84a5bf83ff7968dca31e9b32bbe7e0ebab9b724c)

**Comment by kcc** [comment]
@glennrp I saw more changes in libpng_read_fuzzer.cc, but they don't seem to fix the problem yet. RIght?

**Comment by glennrp** [comment]
I don't know, just waiting to see the coverage report for today.

**Comment by glennrp** [comment]
Thanks for the fix to PNG_CLEANUP.

**Comment by kcc** [comment]
It's not merge yet, right? https://github.com/glennrp/libpng/pull/176

**Comment by glennrp** [comment]
It's merged now.

**Comment by kcc** [comment]
With the above PR merged I've rebuilt the docker image and see it working nicely: 

```
./infra/helper.py build_image libpng
./infra/helper.py build_fuzzers libpng
./infra/helper.py shell libpng
# inside the docker shell:
/out/libpng_read_fuzzer -runs=0 .
INFO: Seed: 3964609191
INFO: Loaded 1 modules   (3773 guards): 3773 [0x8ef150, 0x8f2c44), 
INFO:      442 files found in .
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 385849 bytes
INFO: seed corpus: files: 442 min: 28b max: 385849b total: 4504255b rss: 40Mb
#443	INITED cov: 600 ft: 915 corp: 43/47Kb exec/s: 0 rss: 69Mb
#443	DONE   cov: 600 ft: 915 corp: 43/47Kb exec/s: 0 rss: 69Mb
Done 443 runs in 0 second(s)
```

Note the `INITED` line which shows `cov: 600`. This means that running the fuzz target on all files in the libpng source tree produces 600 edges -- that's pretty good. 

Here is the output if I let it run for a bit:
```
mkdir C && /out/libpng_read_fuzzer C .
...
#74077	REDUCE cov: 745 ft: 1467 corp: 288/464Kb exec/s: 1511 rss: 376Mb L: 66/133060 MS: 4 InsertRepeatedBytes-ChangeASCIIInt-ChangeBit-EraseBytes-
#74370	NEW    cov: 745 ft: 1468 corp: 289/465Kb exec/s: 1487 rss: 376Mb L: 460/133060 MS: 2 CMP-EraseBytes- DE: "8\x00\x00\x00"-
#74679	REDUCE cov: 745 ft: 1468 corp: 289/465Kb exec/s: 1493 rss: 376Mb L: 201/133060 MS: 1 EraseBytes-
...
```

the coverage grows nicely, i.e. I think we have fixed it. 

Let's wait for the coverage dashboard to recover and close this issue.

**Comment by glennrp** [comment]
Thanks.  But "BUILDS" report says libpng gets rebuild sometime around 1:00AM but doesn't say what timezone.  Is it 1:00 UTC?

**Comment by kcc** [comment]
@oliverchang re the time zone

**Comment by kcc** [comment]
btw, I've kicked the build manually

**Comment by oliverchang** [comment]
> Thanks. But "BUILDS STATUS" report says libpng gets rebuilt sometime around 12:20 AM but doesn't say what timezone. Is it 00:20 UTC?

It should be your local timezone.

**Comment by kcc** [comment]
phew, the coverage has recovered: 
```
edge:                          func:
28.65% (1921/6704) | 40.34% (165/409)
```

```
/src/libpng/png.c | 048%
/src/libpng/pngerror.c | 048%
/src/libpng/pngget.c | 005%
/src/libpng/pngmem.c | 077%
/src/libpng/pngread.c | 009%
/src/libpng/pngrio.c | 086%
/src/libpng/pngrtran.c | 006%
/src/libpng/pngrutil.c | 059%
/src/libpng/pngset.c | 043%
/src/libpng/pngtrans.c | 003%


```

@glennrp please take a look at the dashboard now and decide if you can add more inputs to the seed corpus. 

I'm closing this bug.

**Comment by glennrp** [comment]
I think the seed corpus is OK.  The missing coverage is more due to the fact that the target doesn't exercise the progressive reader or the encoder.  I'll see about adding code to exercise the progressive reader.

**Comment by kcc** [comment]
>  adding code to exercise the progressive reader

That would be awesome!
