### ISSUE TITLE
document the corpus sharing process

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#81]
* explain that the corpus is stored in GCS
* explain that google-account should be added to the corpus owners
  * can we do it automatically? 
* explain how to install gsutil
* explain how to download files.

**Comment by MarkusTeufelberger** [comment]
Please also add an option to persist corpora across runs when running locally (not on Google infrastructure) using helper.py.

**Comment by kcc** [comment]
We don't want to beef up helper.py. 
Instead we want to encourage the projects to integrate the fuzzing into their build/test systems.
https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md
Then you won't need anything from oss-fuzz to run fuzzing locally and grow the test corpus.

**Comment by oliverchang** [comment]
Permissions are fixed. I think we can document this now.

**Comment by oliverchang** [comment]
Added some documentation to https://github.com/google/oss-fuzz/blob/master/docs/corpora.md. PTAL.

**Comment by kcc** [comment]
Looks great. Now need to put links to the page from various other places.

**Comment by oliverchang** [comment]
Added a link to the main README.
