### ISSUE TITLE
Performance tab reports 100% crashing fuzzers

### ISSUE THREAD

**Issue by randombit** [google/oss-fuzz#811]
Checking the performance report for the Botan fuzzers, such as

https://oss-fuzz.com/v2/performance-report/libFuzzer_botan_cert/libfuzzer_asan_botan/latest

I'm told that 100% of the runs are crashing ("The fuzz target does not work and crashes instantly on startup. [...]")

But the logs the performance report links to seem to show a normal libFuzzer run, I do not see anything amiss.

**Comment by Dor1s** [comment]
Thanks for the reporting, that is a common issue for all fuzz targets. libFuzzer output has changed since https://github.com/llvm-mirror/compiler-rt/commit/04d0769c4c9fe8e3204424cfc5368b4a78006d03, now there is no line matching the following regex:

```python
...
LIBFUZZER_LOG_START_READ_UNITS_REGEX = re.compile(
    r'#0\s+READ\s+units:\s+(\d+).*')
...
```

We probably have to rely on another line as a log start.

**Comment by Dor1s** [comment]
It looks like the following regex might be a good candidate:

```python
LIBFUZZER_LOG_START_INITED_REGEX = re.compile(
    r'#\d+\s+INITED\s+cov:\s+(\d+).*')

```
An example of how it works when corpus is empty:
```
INFO: A corpus is not provided, starting from an empty corpus
#2	INITED cov: 35 ft: 35 corp: 1/1b exec/s: 0 rss: 43Mb
#4	NEW    cov: 40 ft: 46 corp: 2/19b exec/s: 0 rss: 43Mb L: 18/18 MS: 2 ShuffleBytes-InsertRepeatedBytes-
```

and when corpus is not empty:
```
INFO:        0 files found in /new
INFO:       10 files found in /subset
INFO:     2000 files found in /mutations
INFO: seed corpus: files: 2010 min: 2b max: 165407b total: 2004138b rss: 33Mb
#2013	INITED cov: 1486 ft: 5217 corp: 348/88Kb exec/s: 0 rss: 64Mb
#2019	NEW    cov: 1486 ft: 5223 corp: 349/89Kb exec/s: 0 rss: 65Mb L: 92/888 MS: 1 ShuffleBytes-
```

I'll take another look tomorrow and upload the fix.

**Comment by kcc** [comment]
woops. sorry, I did not realize you are parsing that line. 
Yep, using `INITED` sgtm.

**Comment by Dor1s** [comment]
Some fuzz targets are crashing before line `INITED` gets printed. It feels like we shouldn't always treat it as a `startup crash`, but OTOH, if fuzz target even cannot load the corpus, it's almost equal to crashing on a startup...

**Comment by Dor1s** [comment]
Landed a fix on ClusterFuzz side, let's see how it goes...

@kcc, we actually parse quite a lot of libFuzzer output, so any changes in there may break our stats and other features built on top of that. May I ask you please to CC me and/or other folks when there is anything being removed from the output? :)

**Comment by kcc** [comment]
Sure, will try to!

**Comment by Dor1s** [comment]
Should be fixed now: https://oss-fuzz.com/v2/performance-report/libFuzzer_botan_cert/libfuzzer_asan_botan/2017-09-06
