### ISSUE TITLE
some crashes from OSS-fuzz project detected by local clusterfuzz

### ISSUE THREAD

**Issue by gtt1995** [google/oss-fuzz#8202]
Hello @jonathanmetzman 

I have found more than 100 crashes from the OSS-fuzz integration project. The reason I open an issue here is because of vulnerability sensitivity and vulnerability disclosure rules, so I think I should send you the email privately.

Best wishes for you.

**Comment by jonathanmetzman** [comment]
Thanks for the report.
Send an email to metzman@google.com and ochang@google.com please.

**Comment by gtt1995** [comment]
Thanks.
