### ISSUE TITLE
Question about CLA and public domain

### ISSUE THREAD

**Issue by TheOneric** [google/oss-fuzz#8236]
If I understand correctly, contributors are generally expected to sign a CLA *(mainly to give Google specifically the rights to distribute the code without restrictions)* — and signing the CLA requires a Google account *(as does viewing not yet public OSS-Fuzz reports of a project)*. I do not have and do not intended to create a Google account; therefore I was wondering if patches fully released to the public domain or completely licensed to a public-domain-equivalent license like 0BSD, MIT-0, or CC0 can be submitted without going through the CLA-signing process.
*(I realise this may not be possible, even if just due to e.g. bureaucratic reasons, but figured asking explicitly won't hurt and couldn't find any prior question about this in the issues)*

**Comment by jonathanmetzman** [comment]
> If I understand correctly, contributors are generally expected to sign a CLA _(mainly to give Google specifically the rights to distribute the code without restrictions)_ — and signing the CLA requires a Google account _(as does viewing not yet public OSS-Fuzz reports of a project)_.

I'm not sure about the latter. I think you may be able to view testcases on oss-fuzz.com using your

>I do not have and do not intended to create a Google account; therefore I was wondering if patches fully released to the public domain or completely licensed to a public-domain-equivalent license like 0BSD, MIT-0, or CC0 can be submitted without going through the CLA-signing process. _(I realise this may not be possible, even if just due to e.g. bureaucratic reasons, but figured asking explicitly won't hurt and couldn't find any prior question about this in the issues)_

I can try to ask about this. But the answer might be no

**Comment by TheOneric** [comment]
>  >  [...] (as does viewing not yet public OSS-Fuzz reports of a project).
>
> I'm not sure about the latter. I think you may be able to view testcases on oss-fuzz.com using your [?]

I'm going of [documentation stating](https://github.com/google/oss-fuzz/blob/34c7aa99a3d061f1b4f008d5a06d679fcf38ed34/docs/faq.md#why-do-you-require-a-google-account-for-authentication) the need for a Google account and several recent PRs and issues *(e.g. [#8090](https://github.com/google/oss-fuzz/pull/8090) or [#8097](https://github.com/google/oss-fuzz/pull/8097) )* switching the email to the primary mail of their Google accounts, because some logins didn't work. Though [#8096](https://github.com/google/oss-fuzz/issues/8096#issuecomment-1199851714) also mentions that some parts are accessible via GitHub authentication which is is news to me, but also notes that this doesn't expose everything and didn't allow to e.g. change notification settings. Did anything change since?

> I can try to ask about this. But the answer might be no

Thanks, if it doesn't cause you too much trouble this would be nice :)

**Comment by jonathanmetzman** [comment]
> > > [...] (as does viewing not yet public OSS-Fuzz reports of a project).
> > 
> > 
> > I'm not sure about the latter. I think you may be able to view testcases on oss-fuzz.com using your [?]
> 
> I'm going of [documentation stating](https://github.com/google/oss-fuzz/blob/34c7aa99a3d061f1b4f008d5a06d679fcf38ed34/docs/faq.md#why-do-you-require-a-google-account-for-authentication) the need for a Google account and several recent PRs and issues _(e.g. [#8090](https://github.com/google/oss-fuzz/pull/8090) or [#8097](https://github.com/google/oss-fuzz/pull/8097) )_ switching the email to the primary mail of their Google accounts, because some logins didn't work. Though [#8096](https://github.com/google/oss-fuzz/issues/8096#issuecomment-1199851714) also mentions that some parts are accessible via GitHub authentication which is is news to me, but also notes that this doesn't expose everything and didn't allow to e.g. change notification settings. Did anything change since?

Lol. Yeah logging onto oss-fuzz.com should work with a github account

> 
> > I can try to ask about this. But the answer might be no
> 
> Thanks, if it doesn't cause you too much trouble this would be nice :)

**Comment by jonathanmetzman** [comment]
Their answer was that we can't include the code unless it is in a third_party directory.
In other words, we can't really accept these patches.

**Comment by TheOneric** [comment]
Welp, that's unfortunate, but regardless thanks for looking into this.
