### ISSUE TITLE
Java coverage builds are failing

### ISSUE THREAD

**Issue by fmeum** [google/oss-fuzz#8241]
See https://oss-fuzz-build-logs.storage.googleapis.com/log-71bca0f6-29c8-448a-98b2-335054df3cb0.txt

@jonathanmetzman Could this be related to https://github.com/google/oss-fuzz/commit/ddd25e3c3f6990c3f2d32c7b7787092bbdcf7ea4? It looks like the report has been generated and uploaded at that point, which makes me think this is not a regression in Jazzer.

**Comment by jonathanmetzman** [comment]
I doubt this is due to the GCB change. The failure is due to fuzzer_stats not being generated. I don't think I touched that

**Comment by fmeum** [comment]
I will take a look at the Jazzer side of things.

**Comment by jonathanmetzman** [comment]
I change my mind, it's probably due to the commit you linked to. I can't repro locally.

**Comment by jonathanmetzman** [comment]
It is awfully weird that this only affects Java though

**Comment by jonathanmetzman** [comment]
These failures happen without my change: https://github.com/google/oss-fuzz/pull/8270 I think there's something else at fault here.

**Comment by jonathanmetzman** [comment]
I'm pretty sure the execfile isn't being created.
