### ISSUE TITLE
hsqldb project maintainer email

### ISSUE THREAD

**Issue by fredtoussi** [google/oss-fuzz#8251]
I am the maintainer of the hsqldb project. The current email address in project.yaml is my address at SourceForge which I use for OSS. 

My google account email is ft@cluedup.com. Please add this email address so I get access to the bug reports and fix them.

**Comment by oliverchang** [comment]
Done! Thanks for reaching out! 

I've updated the email address in https://github.com/google/oss-fuzz/pull/8253, and our system should automatically update all existing bug reports in a few hours. 

Please let us know if you encounter any issues with reproducing bug reports.

Thanks!

**Comment by fredtoussi** [comment]
Thank you!
