### ISSUE TITLE
OSS-Fuzz build for sqlite3 fails for aarch64

### ISSUE THREAD

**Issue by drhsqlite** [google/oss-fuzz#8257]
The SQLite developers received an email notification from OSS-Fuzz saying "The last 3 builds for sqlite3 have been failing".  The build log (<https://oss-fuzz-build-logs.storage.googleapis.com/log-cff98ad2-85b1-4ed1-a9ff-ee78a7f60caa.txt>) suggests that the problem might be with the fuzzer infrastructure and not anything to do with SQLite. Specifically, the build log says:

> cannot stat '/usr/local/lib/clang/*/lib/linux/libclang_rt.fuzzer-aarch64.a': No such file or directory

The [bug report](https://mail.google.com/mail/u/0/h/18hozcm873fq/?&th=1829c1e2bac76055&v=c) says that the bug is not monitored by the OSS-Fuzz team and suggests that I escalate the problem here.

**Comment by jonathanmetzman** [comment]
Sorry about that. I reconfigured your project not to use this experimental feature: https://github.com/google/oss-fuzz/commit/8515dad2ebf77d1a8e779563ed6e7e9ee750dd1f
