### ISSUE TITLE
ubuntu (clang, macos-11) fuzzer recently broken on protocolbuffers / upb

### ISSUE THREAD

**Issue by ericsalo** [google/oss-fuzz#8281]
This started failing last night, it was fine earlier in the day:

https://github.com/protocolbuffers/upb/runs/7872417448

**Comment by jonathanmetzman** [comment]
Thanks for the report. Sorry, but I can't tell from this issue what we (OSS-Fuzz) should do about this.

**Comment by ericsalo** [comment]
Well that makes two of us. I am reasonably certain that nothing has changed on our side for quite some time. Have there been any recent pushes on your side?

**Comment by jonathanmetzman** [comment]
I don't think so. We don't require mac support anyway.

**Comment by haberman** [comment]
Sounds like maybe we should disable fuzzing on Mac.

**Comment by jonathanmetzman** [comment]
At least as far as I'm concerned, yep!

**Comment by oliverchang** [comment]
Closing as there's nothing actionable here.
