### ISSUE TITLE
Broken wolfssl build

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#829]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

```
Step #40: ++ sancov -print-coverage-pcs /workspace/out/address/pem_cert
Step #40: ++ wc -l
Step #40: BAD BUILD: the code does not seem to have coverage instrumentation.
Step #40: + local NUMBER_OF_EDGES=1
Step #40: + ((  1 < 90  ))
Step #40: + echo 'BAD BUILD: the code does not seem to have coverage instrumentation.'
Step #40: + CHECK_FAILED=1
Step #40: + ((  1 > 0  ))
Step #40: + exit 1
```

**Comment by JacobBarthelmeh** [comment]
Hi Dor1s is there an action wolfSSL should take with this? What does the label buggy target mean?

**Comment by Dor1s** [comment]
Hi @JacobBarthelmeh, thanks for checking. I don't think that woflSSL should do anything right now, I need to manually verify this particular issue as well as some others.

`buggy target` label means that the root cause seems to be inside of the target / project, not on OSS-Fuzz side.

**Comment by Dor1s** [comment]
There is an issue when `pem_cert` fuzz target is being built with hongffuzz. When built with libFuzzer, it's absolutely fine.

**Comment by Dor1s** [comment]
As honggfuzz is not fully integrated at this point, we shouldn't mark a build as broken if only honggfuzz version has some issues. Will be skipping bad build checks for honggfuzz.

**Comment by JacobBarthelmeh** [comment]
Thanks for the update Dor1s.
