### ISSUE TITLE
Builds are listed as last built 17/08/2022 but its 21/08/2022 today

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#8307]
Issue open from this Tweet: https://twitter.com/MagickNET/status/1561271022090846208

Looking at the builds page all builds are listed as 17/08/21, are the builds currently stuck?

**Comment by Alan32Liu** [comment]
Thanks! I am looking/asking more into this.

**Comment by Navidem** [comment]
Thanks David for pointing this out!

> are the builds currently stuck?

As I checked, builds are going just fine: 

<img width="1008" alt="Screen Shot 2022-08-22 at 11 35 43 AM" src="https://user-images.githubusercontent.com/19780488/185994449-845b975a-beda-47b0-8fc9-791028114021.png">

Probably something broken in `build_status` cron job.

**Comment by Navidem** [comment]
looking into it I can see the docker run is failing with 
`Step #1: ModuleNotFoundError: No module named 'google.cloud.datastore_v1.gapic'`

**Comment by Navidem** [comment]
Looks fine now after #8316
