### ISSUE TITLE
Build_status is hitting timeout

### ISSUE THREAD

**Issue by Navidem** [google/oss-fuzz#8317]
Build status is taking longer than 1:30 time out threshold.

https://pantheon.corp.google.com/cloud-build/builds;region=global/51d15a9a-d475-4129-98d9-ec103ebf8efb?project=oss-fuzz

**Comment by Navidem** [comment]
@oliverchang should we increase timeout and also reduce the trigger frequency?

**Comment by pgrosu** [comment]
Hmm...unfortunately it's not visible from the outside:

![image](https://user-images.githubusercontent.com/6555937/186050935-dc14d5ad-88fd-44ae-ac42-dd771a88ba3c.png)

**Comment by oliverchang** [comment]
> @oliverchang should we increase timeout and also reduce the trigger frequency?

SG, let's do that.
