### ISSUE TITLE
migrate to -fsanitize=fuzzer

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#832]
libFuzzer now uses yet another flag for coverage instrumentation`-fsanitize=fuzzer`
(which is a macro for lots of things under the hood). 
We need to eventually migrate the libFuzzer builds to this flag. 
There is no rush, filing FTR.

**Comment by Dor1s** [comment]
Should we detach from [LLVM revision pinned in Chrome](https://cs.chromium.org/chromium/src/tools/clang/scripts/update.py?type=cs&q=+tools/clang/scripts/update.py&sq=package:chromium&l=30) then?

It seems to update [every two weeks](https://chromium.googlesource.com/chromium/src/+log/85421ca0a78779eb21a885167ac56c49055e1d52/tools/clang/scripts/update.py) (on average, but not too regularly).

As an alternative, I guess, we might consider checking out ToT of compiler-rt and building libraries out of it, but that sounds flaky to me, as the code might depend on other LLVM stuff.

**Comment by kcc** [comment]
> detach from LLVM revision pinned in Chrome t

No strong opinion here. 
If we stop using Chrome's version, then we should resume using libFuzzer and LLVM from the same revision. 
We may as well just bump the revisions manually every time we need it (giving preference to Chrome's pinned revisions)

> checking out ToT of compiler-rt 

This is too fragile.

**Comment by oliverchang** [comment]
Let's just keep using Chrome's LLVM revision and stop using trunk libFuzzer since the delay is only ~2 weeks.

If we need some feature/fix immediately, we can bump it ourselves as Kostya mentioned.

**Comment by kcc** [comment]
FTR: it should be llvm r312855 or later

**Comment by Dor1s** [comment]
r313222 has been rolled 4 days ago.

**Comment by Dor1s** [comment]
I think it's done via #975 and https://github.com/google/oss-fuzz/commit/62048995161677436b1e0326dd9d2c004f3f8124
