### ISSUE TITLE
Joda-Time failing

### ISSUE THREAD

**Issue by jodastephen** [google/oss-fuzz#8344]
Hi, Joda-Time has started failing but I have no idea why. All I did was update a few Maven dependencies. The [build log](https://oss-fuzz-build-logs.storage.googleapis.com/log-cb4a0aa4-5e9a-4918-8645-bd68adcb213d.txt) is unhelpful, and I don't  really have a clue as to what is going on:

```
Starting Step #9
Step #9: Already have image (with digest): gcr.io/cloud-builders/gsutil
Step #9: CommandException: No URLs matched. Do the files you're operating on exist?
Finished Step #9
```

FWIW, it looks like the Java build completed just fine.

**Comment by jonathanmetzman** [comment]
Assigning to sheriff. Oliver could you PTAL?

**Comment by oliverchang** [comment]
Build is no longer failing, so closing!

**Comment by jodastephen** [comment]
See here - https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50159#c3 - I'm still getting emails saying it is failing

**Comment by DavidKorczynski** [comment]
Yes, all java builds are still failing their coverage builds.

Joda-Time's coverage build is failing (non-coverage builds are succeeding).

Will keep this closed as the java coverage build failing is tracked in https://github.com/google/oss-fuzz/issues/8241
