### ISSUE TITLE
[Q] oss-fuzz/infra/base-images/ may need env variables?

### ISSUE THREAD

**Issue by LebedevRI** [google/oss-fuzz#839]
Hi.

Some time ago i have encountered this bug: https://bugs.llvm.org/show_bug.cgi?id=33548
Now, yesterday @hanatos encountered this same bug with standalone `opt-viewer`.
This did result in me providing a patch to fix the root cause upstream: https://reviews.llvm.org/D37661

But now i'm wondering, if the base dockerfile should specify proper default locales.
E.g.:
```
# see https://github.com/docker-library/python/issues/13
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV LC_MESSAGES C.UTF-8
ENV LANGUAGE C.UTF-8
```

Thoughts?

**Comment by kcc** [comment]
I'd prefer to not overcomplicate the docker environment. 
I've responded on  https://reviews.llvm.org/D37661

(please reopen if you still thing there is something to be fixed here)
