### ISSUE TITLE
OOMs issues reported from MSAN build are not so useful

### ISSUE THREAD

**Issue by LebedevRI** [google/oss-fuzz#840]
https://oss-fuzz.com/v2/testcase-detail/6122311713292288?noredirect=1
There is zero explanation, no stack trace

**Comment by LebedevRI** [comment]
Probably related to #774

**Comment by Dor1s** [comment]
Yes, it's the same thing. Closing as duplicate of https://github.com/google/oss-fuzz/issues/774
