### ISSUE TITLE
Cannot access documents under https://oss-fuzz.com via the "Sign in with Google" option

### ISSUE THREAD

**Issue by ulucinar** [google/oss-fuzz#8431]
Hello,
Although my gmail address (`alper.oss.fuzz@gmail.com`) has been added to the Crossplane's [project.yaml](https://github.com/google/oss-fuzz/blob/7b0f4f7d1ddb582ea9c09a038a2ac17ef4ecac8b/projects/crossplane/project.yaml#L7), I cannot still access documents under https://oss-fuzz.com (after 12 hours). The error message is:

```
You (email=alper.oss.fuzz@gmail.com) are not authorized to access this page!

Please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.

Switch account

OSS-Fuzz is an effort to provide continuous fuzzing infrastructure for open-source software. You can read more about it here: https://github.com/google/oss-fuzz.
```

Do I need to take any further steps to be able to access these resources? Am I allowed to access only documents/testcases for Crossplane (fine-grained access control) or can I access all resources under the site (although my email has been added to the `auto_ccs` for Crossplane).

Thank you very much in advance. cc @AdamKorcz 

P.S. FWIW, the document I'm trying to access is older than my registration.

**Comment by jonathanmetzman** [comment]
Assigning current sheriff @Navidem

**Comment by oliverchang** [comment]
Thanks, it looks like we're running into some quota issues on OSS-Fuzz. We'll resolve this.

**Comment by oliverchang** [comment]
@ulucinar this should work now. Could you please try again?

**Comment by ulucinar** [comment]
Thank you very much @oliverchang! I can access now, closing this issue.
