### ISSUE TITLE
Centipede is bloating our image sizes.

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#8468]
It reinstalls clang? and adds 1.7GB to our image size, which slows down every CFL/CIFuzz user.

**Comment by jonathanmetzman** [comment]
I think it reinstalls using apt and via tar.gz and does some stuff to /usr/bin/bazel that wastes 50 MB. Might be worth making a multistage build if this won't install cleanly.

**Comment by jonathanmetzman** [comment]
I'm not sure it has. It's worth looking at how much space the centipede layer is taking and if it should be reduced further.

**Comment by jonathanmetzman** [comment]
not sure this is done, let me remeasure now

**Comment by Alan32Liu** [comment]
> not sure this is done, let me remeasure now

Cool! Let me know if there is anything I can do to help : )

**Comment by jonathanmetzman** [comment]
> > not sure this is done, let me remeasure now
> 
> Cool! Let me know if there is anything I can do to help : )

If you want to learn how I do this btw you can use https://github.com/wagoodman/dive

**Comment by jonathanmetzman** [comment]
This is still adding a few hundred MB of into /usr increasing our image size by about 25%

**Comment by jonathanmetzman** [comment]
This was fixed by https://github.com/google/oss-fuzz/issues/8468
Now the centipede is a very svelte 11 MB :tada:

**Comment by jonathanmetzman** [comment]
This was fixed by https://github.com/google/oss-fuzz/issues/8468
Now the centipede is a more reasonable 11 MB :tada:
