### ISSUE TITLE
Coverage builds

### ISSUE THREAD

**Issue by cmeister2** [google/oss-fuzz#848]
Are coverage builds still working?

For libcurl we used to get a summary of how much coverage the fuzzers were providing, plus a link to download the test corpus. We haven't had these links in the dashboard for about 2 weeks.

**Comment by Dor1s** [comment]
Indeed: https://oss-fuzz.com/v2/fuzzer-stats/by-day/2017-08-23/2017-09-19/fuzzer/libFuzzer_curl_fuzzer/job/libfuzzer_asan_curl

@oliverchang, can it be related to recent changes on trusted / untrusted stuff?

**Comment by oliverchang** [comment]
It looks like this is working again (results will show up in a few hours).

We did notice a bunch of issues with curl fuzzers in the past week or so (they seemed to be creating a lot of junk files), but they seem to have stopped happening for now. I haven't had a chance to look into them yet, but were there any fixes done to the target?

**Comment by cmeister2** [comment]
I changed a few things recently:

- https://github.com/curl/curl/pull/1885 stopped the fuzzer from writing to stdout
- https://github.com/curl/curl/pull/1881 changed the behaviour of the fuzzer so that the generated corpora should be better (by changing some behaviour to be invalid).

Possibly one of those affected it?

**Comment by oliverchang** [comment]
It looks like we have proper stats for the past 2 days: https://oss-fuzz.com/v2/fuzzer-stats/by-day/2017-09-14/2017-09-21/fuzzer/libFuzzer_curl_fuzzer/job/libfuzzer_asan_curl

Closing this for now, it's that something broken in the target was recently fixed.
