### ISSUE TITLE
fuzzer stats report "b.split is not a function"

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#849]
If I try and expore the fuzzer stats I get an error "b.split is not a function", e.g. from

https://oss-fuzz.com/v2/fuzzer-stats/by-day/2017-09-14/2017-09-15/fuzzer/libFuzzer_libreoffice_xpmfuzzer/job/libfuzzer_asan_libreoffice

and press submit, I get "b.split is not a function"

**Comment by inferno-chromium** [comment]
It loads fine for me, can you retry once just to double check.

**Comment by oliverchang** [comment]
Which browser are you using?

**Comment by inferno-chromium** [comment]
@tanin47 - could this be a polymer v2 issue in firefox, can you check other CF pages as well.

**Comment by glennrp** [comment]
I'm seeing this with firefox "nightly" (58.0a1 (2017-09-26) (64-bit)), when looking at the libpng project reports.

**Comment by inferno-chromium** [comment]
@tanin47 - do you have any time today to look into this ?

I see another issue with loading oss-fuzz.com/any other page in firefox. the left panel sticks for some time before it vanishes after a click.

**Comment by tanin47** [comment]
I'm seeing: 

```
Loading failed for the <script> with source “https://www.gstatic.com/charts/45.2/loader.js”.  libfuzzer_asan_libreoffice:1
TypeError: google.visualization.Table is not a constructor
```

on Firefox. I'll find a way to fix it.

**Comment by tanin47** [comment]
For some reason, Firefox works with https://www.gstatic.com/charts/45/loader.js ... but not https://www.gstatic.com/charts/45.2/loader.js

As a quick fix, I'll freeze the version of Google's chart to 45.

Somehow, 45.2 is working on JSFiddle (https://jsfiddle.net/kLe5g15h/). I don't know why.

**Comment by tanin47** [comment]
It works on firefox now. Please re-open if it doesn't. Thank you for reporting this.
