### ISSUE TITLE
infra/ci/build.py doesn't respect `run_tests`

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#8508]
This lets projects opt out of bad build checks: https://github.com/google/oss-fuzz/blob/2fa71e3c7f87497dc31a9b236175c2173756fc99/infra/build/functions/build_project.py#L312

Our CI does not seem to respect this (https://github.com/google/oss-fuzz/pull/8488).

**Comment by oliverchang** [comment]
@jonathanmetzman is my understanding here correct?

**Comment by jonathanmetzman** [comment]
Yeah I think it's right
