### ISSUE TITLE
Fixed issue is still open

### ISSUE THREAD

**Issue by bvanassche** [google/oss-fuzz#8528]
Issue https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40640 is still open although it has been fixed. If I navigate to https://oss-fuzz.com/testcase-detail/6008157151821824 and ask to generate the stack trace for the trunk, `No crash occurred.` appears.

**Comment by bvanassche** [comment]
Same problem for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51529.

**Comment by oliverchang** [comment]
Looks like https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40640 has been autoclosed now. 

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51529 is something seen frequently, but not consistently reproducible. Please see the disclaimer text in the bug:

```
************************* UNREPRODUCIBLE *************************
Note: This crash might not be reproducible with the provided testcase. That said, for the past 14 days, we've been seeing this crash frequently.

It may be possible to reproduce by trying the following options:
- Run testcase multiple times for a longer duration.
- Run fuzzing without testcase argument to hit the same crash signature.

If it still does not reproduce, try a speculative fix based on the crash stacktrace and verify if it works by looking at the crash statistics in the report. We will auto-close the bug if the crash is not seen for 14 days.
******************************************************************
```

Are you able to try adding -runs=10000 or something to the reproduction command you're trying and see if it reproduces that way?

**Comment by oliverchang** [comment]
Closing as stale, please let us know if there's anything else we can help investigate.
