### ISSUE TITLE
Getting keyerror 'centipede' issues

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#8566]
https://pantheon.corp.google.com/errors/detail/COyAo6vihtnVGw;time=P7D?project=oss-fuzz
Maybe it's because we didn't deploy.

**Comment by jonathanmetzman** [comment]
CC @Alan32Liu

**Comment by jonathanmetzman** [comment]
Deployed. Let's see if this goes away

**Comment by oliverchang** [comment]
Looks gone.
