### ISSUE TITLE
libidn and libpsl build failing

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#857]
https://oss-fuzz-build-logs.storage.googleapis.com/log-dc1de3d6-1f7f-4af6-a337-a9cab7e73454.txt

```
Step #3: test-verify.c:42:10: error: 'struct (anonymous at test-verify.c:42:10)' cannot be defined in an enumeration
Step #3:   item = verify_true (1 == 1) * 0 + 17 /* should be ok */
Step #3:          ^
Step #3: ../gl/verify.h:240:24: note: expanded from macro 'verify_true'
Step #3: #define verify_true(R) _GL_VERIFY_TRUE (R, "verify_true (" #R ")")
Step #3:                        ^
Step #3: ../gl/verify.h:176:15: note: expanded from macro '_GL_VERIFY_TRUE'
Step #3:    (!!sizeof (_GL_VERIFY_TYPE (R, DIAGNOSTIC)))
Step #3:               ^
Step #3: ../gl/verify.h:196:5: note: expanded from macro '_GL_VERIFY_TYPE'
Step #3:     struct { unsigned int _gl_verify_error_if_negative: (R) ? 1 : -1; }
Step #3:     ^
Step #3:   CCLD     test-errno
Step #3:   CCLD     test-close
Step #3:   CCLD     test-binary-io
Step #3: 1 error generated.
Step #3:   CCLD     test-environ
Step #3: Makefile:2039: recipe for target 'test-verify.o' failed
```

@rockdaboot could you please take a look?

**Comment by oliverchang** [comment]
Also seeing a very similar failure for libpsl: https://oss-fuzz-build-logs.storage.googleapis.com/log-8e29de20-b393-4f32-a417-546aff9eee35.txt

**Comment by rockdaboot** [comment]
That's gnulib code suddenly not working any more !? The environment must have been changed... I have a closer look tomorrow with a better network bandwidth.

**Comment by rockdaboot** [comment]
Looks like a clang regression. Those files from libidn/gnulib check the compilers correct behavior / capabilities. And they didn't change at least since Jan 4th 2016. They work on all clang and gcc versions I know of (expect some very old ones - documented in those files).

**Comment by rockdaboot** [comment]
@oliverchang Anything new regarding the clang regression ?

**Comment by oliverchang** [comment]
Sorry for the delayed reply. 

I'm not 100% sure but searching around it may be fixed in https://reviews.llvm.org/D38109.

We depend on Chromium's clang revision (https://cs.chromium.org/chromium/src/tools/clang/scripts/update.py?q=clang+update.py&sq=package:chromium&dr=CSs&l=30), which should get a roll past the fix soon. Let's wait for that.

**Comment by oliverchang** [comment]
The chromium roll is taking longer than expected, so I'll try a manual roll later today.

**Comment by oliverchang** [comment]
Looks like this no longer happens after the roll.
