### ISSUE TITLE
MSAN false positives from zlib

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#8574]
I think this https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51600 is a MSAN false positive

Use-of-uninitialized-value : values have in fact been initialized by zlib `inflate`

Is there still the right zlib msan-compiled in the docker image ?

**Comment by jonathanmetzman** [comment]
Ah yeah we're not compiling zlib with msan.

**Comment by jonathanmetzman** [comment]
I think I fixed this: https://github.com/google/oss-fuzz/commit/08e3cd017586d6f3877204168cfcc54e0cc9f350 by getting rid of msan again

**Comment by catenacyber** [comment]
Could we compile zlib with MSAN again ?
Or is MSAN support getting dropped anyways ?

**Comment by jonathanmetzman** [comment]
Yeah you can compile zlib with msan, but we won't do this in the base-builder image anymore. MSAN support is not being dropped.

**Comment by catenacyber** [comment]
Ok, so I created https://github.com/google/oss-fuzz/pull/8614 to re-enable MSAN

Disabling it did not close the bugs.chromium.org issues ;-) like https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51600
