### ISSUE TITLE
Honggfuzz netdriver missing right kernel params on OSS-Fuzz runs

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#8601]
Honggfuzz netdriver is missing some permissions which is stopping it from running: https://oss-fuzz-build-logs.storage.googleapis.com/log-5ec7f249-8a59-4bea-857a-d4895dc7890e.txt

```
Step #13 - "build-check-honggfuzz-address-x86_64": Persistent mode: Launched new persistent pid=5140
Step #13 - "build-check-honggfuzz-address-x86_64": [2022-09-26T06:19:56+0000][E][5140] nsEnter():84 unshare(0x5c020000): Operation not permitted
Step #13 - "build-check-honggfuzz-address-x86_64": [2022-09-26T06:19:56+0000][W][5140] nsEnter():86 Executing 'sysctl -w kernel.unprivileged_userns_clone=1' might help with this
Step #13 - "build-check-honggfuzz-address-x86_64": [2022-09-26T06:19:56+0000][F][5140] netDriver_initNsIfNeeded():105 nsEnter(CLONE_NEWUSER|CLONE_NEWNET|CLONE_NEWNS|CLONE_NEWIPC|CLONE_NEWUTS) failed
Step #13 - "build-check-honggfuzz-address-x86_64": [2022-09-26T06:19:56+0000][W][2633] arch_checkWait():238 Persistent mode: pid=5140 exited with status: EXITED, exit code: 1
Step #13 - "build-check-honggfuzz-address-x86_64": Persistent mode: Launched new persistent pid=5141
Step #13 - "build-check-honggfuzz-address-x86_64": [2022-09-26T06:19:56+0000][E][5141] nsEnter():84 unshare(0x5c020000): Operation not permitted
Step #13 - "build-check-honggfuzz-address-x86_64": [2022-09-26T06:19:56+0000][W][5141] nsEnter():86 Executing 'sysctl -w kernel.unprivileged_userns_clone=1' might help with this
Step #13 - "build-check-honggfuzz-address-x86_64": [2022-09-26T06:19:56+0000][F][5141] netDriver_initNsIfNeeded():105 nsEnter(CLONE_NEWUSER|CLONE_NEWNET|CLONE_NEWNS|CLONE_NEWIPC|CLONE_NEWUTS) failed
Step #13 - "build-check-honggfuzz-address-x86_64": [2022-09-26T06:19:56+0000][W][2633] arch_checkWait():238 Persistent mode: pid=5141 exited with status: EXITED, exit code: 1
Step #13 - "build-check-honggfuzz-address-x86_64": Persistent mode: Launched new persistent pid=5142
Step #13 - "build-check-honggfuzz-address-x86_64": [2022-09-26T06:19:56+0000][E][5142] nsEnter():84 unshare(0x5c020000): Operation not permitted
Step #13 - "build-check-honggfuzz-address-x86_64": [2022-09-26T06:19:56+0000][W][5142] nsEnter():86 Executing 'sysctl -w kernel.unprivileged_userns_clone=1' might help with this
```

From https://github.com/google/honggfuzz/issues/242#issuecomment-456912399 a suggested solutions is: `sysctl -w kernel.unprivileged_userns_clone=1`

Am not entirely sure about the kernel parameters on the machines/environments but I assume `kernel.unprivileged_userns_clone` is set to 0?

**Comment by oliverchang** [comment]
This flag doesn't exist on our production ClusterFuzz instances:

```
$ sysctl kernel.unprivileged_userns_clone
$ sysctl: cannot stat /proc/sys/kernel/unprivileged_userns_clone: No such file or directory
```

But I think this is because this is a custom Debian flag for opting out rather than something we actually need according to https://serverfault.com/questions/939455/unprivileged-userns-clone-no-such, so this should hopefully not be an issue. 

This leaves our build environment (Cloud Build), I think we're just missing '--privileged' and maybe '--cap-add=all' in our run command here: https://github.com/google/oss-fuzz/blob/1ab5e408e5253db7058c5050a7ee15216c078698/infra/build/functions/build_lib.py#L106

**Comment by oliverchang** [comment]
@jonathanmetzman is that the right place to change the docker run command to fix https://pantheon.corp.google.com/cloud-build/builds;region=us-central1/5ec7f249-8a59-4bea-857a-d4895dc7890e;step=13;tab=detail?project=oss-fuzz ?

**Comment by jonathanmetzman** [comment]
@oliverchang I think actually https://github.com/google/oss-fuzz/blob/1ab5e408e5253db7058c5050a7ee15216c078698/infra/build/functions/build_project.py#L327 makes more sense but my weird wrapping hack may mess things up (i do this for ARM so maybe we need to kill it temporarily)

**Comment by oliverchang** [comment]
> @oliverchang I think actually
> 
> https://github.com/google/oss-fuzz/blob/1ab5e408e5253db7058c5050a7ee15216c078698/infra/build/functions/build_project.py#L327
> 
> makes more sense but my weird wrapping hack may mess things up (i do this for ARM so maybe we need to kill it temporarily)

Maybe we can make this a no-op (i.e. not wrap) for amd64 for now? would that work?

**Comment by cpq** [comment]
Thanks everybody for looking into this.
Is there an ETA ? Our project's fuzz build is broken and is reflected on the home page; if the ETA is too far in the future, we'd like to disable the fuzzer in the mean time.

**Comment by DavidKorczynski** [comment]
> if the ETA is too far in the future, we'd like to disable the fuzzer in the mean time.

I'll disable it for now until we have a fix!

Apologies for the inconvenience!

Fixed in: https://github.com/google/oss-fuzz/pull/8735

**Comment by cpq** [comment]
@DavidKorczynski thank you, appreciate your attention!

**Comment by cpq** [comment]
@DavidKorczynski thank you, appreciated!

**Comment by jonathanmetzman** [comment]
@DavidKorczynski Can you give me a toy project that has one of these fuzzers? It's fine if it fails, but I want to try building it.

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski Can you give me a toy project that has one of these fuzzers? It's fine if it fails, but I want to try building it.

This binary runs a netdriver fuzzer -- will this do the job? https://github.com/google/clusterfuzz/blob/master/src/clusterfuzz/_internal/tests/core/bot/fuzzers/honggfuzz/test_data/fuzz_netdriver_crash

**Comment by jonathanmetzman** [comment]
> > @DavidKorczynski Can you give me a toy project that has one of these fuzzers? It's fine if it fails, but I want to try building it.
> 
> This binary runs a netdriver fuzzer -- will this do the job? https://github.com/google/clusterfuzz/blob/master/src/clusterfuzz/_internal/tests/core/bot/fuzzers/honggfuzz/test_data/fuzz_netdriver_crash
> 
> Corresponding source: https://github.com/google/clusterfuzz/blob/master/src/clusterfuzz/_internal/tests/core/bot/fuzzers/honggfuzz/test_data/fuzz_netdriver_crash.c

Not really. Could you tell me how to reenable the fuzzer in the project that already has it? I'll just do a trial build of that project.

**Comment by DavidKorczynski** [comment]
> Could you tell me how to reenable the fuzzer in the project that already has it? I'll just do a trial build of that project.

uncomment the following lines:
https://github.com/google/oss-fuzz/blob/f83e9eea2632eec17fdefdcd6b4756b77052056b/projects/mongoose/build.sh#L20-L28
