### ISSUE TITLE
Is it possible to control ASAN_OPTIONS?

### ISSUE THREAD

**Issue by szhorvat** [google/oss-fuzz#8610]
I am wondering if it is possible to control `ASAN_OPTIONS` per project, and what options OSS-fuzz uses by default.

In particular, I would like to know if `detect_stack_use_after_return` is enabled. The igraph project has a real risk of introducing such a bug, so it would make sense to enable this sanitizer if it isn't already.

**Comment by oliverchang** [comment]
Very sorry for the late reply here. 

Yes, this is possible. Please see https://github.com/google/oss-fuzz/blob/bdfa1ef3d2335a5be03bda4ff88aff76c775050b/projects/ruby/fuzz_ruby_gems.options for an example. 

This just needs to be output next to the fuzz target binary in `$OUT`.

By default, `detect_stack_use_after_return` is enabled. The full list is here: https://github.com/google/oss-fuzz/blob/a4c1193050cc63155b6f3239bcf86b5e9480cf15/infra/base-images/base-runner/Dockerfile#L54
