### ISSUE TITLE
fuzz more of boost on oss-fuzz

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#862]
@meetingcpp: @vinniefalco told me about https://www.meetingcpp.com/blog/items/fuzzing-beast.html
Would you be interested in fuzzing beast (or any other part of boost) on [OSS-Fuzz](https://github.com/google/oss-fuzz)?

I've already set up [fuzzing for boost::regex](https://github.com/google/oss-fuzz/tree/master/projects/boost) and I am looking for someone to own and fix 8 bugs it found. If you know someone, please invite them here. I'm also going to e-mail to  boost@lists.boost.org shortly

**Comment by vinniefalco** [comment]
Beast tests have a "naive fuzz" implementation:
https://github.com/boostorg/beast/blob/0f5ea371c18a6797f4623a61f159326428c01400/test/extras/include/boost/beast/test/fuzz.hpp#L42

Usage:
https://github.com/boostorg/beast/blob/0f5ea371c18a6797f4623a61f159326428c01400/test/beast/http/basic_parser.cpp#L1130

**Comment by kcc** [comment]
@vinniefalco , if I read this right, you are doing generation-based fuzzing, w/o coverage feedback. 
In our experience coverage-guided fuzzing is many orders of magnitude more efficient.
The blog post above uses libFuzzer, which is coverage-guided.

**Comment by vinniefalco** [comment]
Yes and yes. However, this is not completely useless since it requires no external tooling and is implemented entirely in C++ with the existing test code. It is not meant to be exhaustive but merely to provide a possible early warning if a regression is introduced.

**Comment by kcc** [comment]
Sure. But we can use this on OSS-Fuzz.

**Comment by kcc** [comment]
@jzmaddock for boost::regex bugs

**Comment by tyler92** [comment]
Just for history: https://github.com/google/oss-fuzz/pull/12109
