### ISSUE TITLE
Introspector should use a different image name than gcr.io/oss-fuzz-base/base-builder:introspector

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#8625]
I think the current usage is deceptive and basically unlike normal usage of the tag part of a docker image name. It's also problematic for people looking at old images (i.e. me when I need to pin a project to an old image and this script from fuzzbench https://github.com/google/fuzzbench/blob/master/benchmarks/oss_fuzz_benchmark_integration.py) since once a new introspector image is tag, the old one loses the introspector tag and there's no way to tell what it contains.

**Comment by jonathanmetzman** [comment]
Can we just merge the introspector image with the main image? Can the patch we apply for introspector do nothing unless certain flags are passed so we can apply it to our normal build?

**Comment by Navidem** [comment]
> Can we just merge the introspector image with the main image? Can the patch we apply for introspector do nothing unless certain flags are passed so we can apply it to our normal build?

The main factor for having separate images for introspector is the customized clang to load LTO pass. That said, I believe we are guarding introspector pass load with an env variable. Testing with it in #8628.

**Comment by evverx** [comment]
Looks like it should address https://github.com/ossf/fuzz-introspector/issues/483 as well
