### ISSUE TITLE
libreoffice builds failure at link: ld.gold: internal error in read_header_prolog

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#8629]
recent libreoffice builds are failing with:

/usr/bin/ld.gold: internal error in read_header_prolog, at ../../gold/dwarf_reader.cc:1678

which isn't something I've seen happen before. Any recent toolchain changes?

https://oss-fuzz-build-logs.storage.googleapis.com/log-167cddd9-b6ab-42a3-bc59-b787c25f4f97.txt

**Comment by oliverchang** [comment]
Not sure we're familiar with this one unfortunately. @jonathanmetzman have you seen this before?

**Comment by jonathanmetzman** [comment]
Nope

**Comment by caolanm** [comment]
seem this might be due to duplicate symbols: https://cgit.freedesktop.org/libreoffice/core/commit/?id=658946e0353c2fad5e26bb75f851744da4b7751f
