### ISSUE TITLE
Add protobuf fuzzer support to OSS-Fuzz

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#864]

**Comment by kcc** [comment]
probably a matter of moving a couple of lines from https://github.com/google/oss-fuzz/blob/master/projects/libpng-proto/Dockerfile to one of the oss-fuzz base docker files.

May need to do some extra work on documenting and making things nicer. 
(@vitalybuka FYI)

**Comment by bshastry** [comment]
> probably a matter of moving a couple of lines from https://github.com/google/oss-fuzz/blob/master/projects/libpng-proto/Dockerfile to one of the oss-fuzz base docker files.

FWIW I tried this setup and ran into compilation errors due to unused variables inside protobuf header function definitions

```
/src/LPM/external.protobuf/include/google/protobuf/arenastring.h:177:57: error: unused parameter 'default_value'                        
      [-Werror,-Wunused-parameter]                                                                                                      
                                   const ::std::string* default_value,                                                                  
                                                        ^                                                                               
/src/LPM/external.protobuf/include/google/protobuf/arenastring.h:178:43: error: unused parameter 'arena' [-Werror,-Wunused-parameter]   
                                   Arena* arena) {                                                                                      
                                          ^                                                                                             
In file included from /src/solidity/test/tools/ossfuzz/proto_to_yul.cpp:19:                                                             
In file included from /src/solidity/test/tools/ossfuzz/yul_proto.pb.h:25:
```

and

```
/src/LPM/external.protobuf/include/google/protobuf/util/field_comparator.h:185:43: error: unused parameter 'field'
      [-Werror,-Wunused-parameter]          
  bool CompareBool(const FieldDescriptor& field, bool value_1, bool value_2) {
                                          ^     
/src/LPM/external.protobuf/include/google/protobuf/util/field_comparator.h:202:44: error: unused parameter 'field'
      [-Werror,-Wunused-parameter]    
  bool CompareInt32(const FieldDescriptor& field, int32 value_1,
                                           ^
/src/LPM/external.protobuf/include/google/protobuf/util/field_comparator.h:207:44: error: unused parameter 'field'
      [-Werror,-Wunused-parameter]                                   
  bool CompareInt64(const FieldDescriptor& field, int64 value_1,
                                           ^
/src/LPM/external.protobuf/include/google/protobuf/util/field_comparator.h:212:45: error: unused parameter 'field'
      [-Werror,-Wunused-parameter]
  bool CompareString(const FieldDescriptor& field, const std::string& value_1,
                                            ^
/src/LPM/external.protobuf/include/google/protobuf/util/field_comparator.h:217:45: error: unused parameter 'field'
      [-Werror,-Wunused-parameter]
  bool CompareUInt32(const FieldDescriptor& field, uint32 value_1,
                                            ^
/src/LPM/external.protobuf/include/google/protobuf/util/field_comparator.h:222:45: error: unused parameter 'field'
      [-Werror,-Wunused-parameter]
  bool CompareUInt64(const FieldDescriptor& field, uint64 value_1,
```

If need be, I can file a separate issue over at  google/libprotobuf-mutator.

**Comment by vitalybuka** [comment]
This is a warning in prototobuffs code, not LPM itself. You may try to work with https://github.com/protocolbuffers/protobuf, but this warning is quite benign.

Also I see "-w" which should disable all warning when compiling protocolbuffers https://github.com/google/libprotobuf-mutator/blob/master/CMakeLists.txt#L100

**Comment by bshastry** [comment]
> Also I see "-w" which should disable all warning when compiling protocolbuffers https://github.com/google/libprotobuf-mutator/blob/master/CMakeLists.txt#L100

Thanks, the problem is that CMake flags for a project that includes these header files does not have the `-w` flag and thus treats all warnings as errors.

**Comment by bshastry** [comment]
Since the upstream protobufs now contains a fix for the unused function parameters, would it be possible to include it inside LPM's `external.protobuf` directory?

**Comment by kcc** [comment]
@vitalybuka WDYT?

**Comment by vitalybuka** [comment]
@bshastry Done

**Comment by bshastry** [comment]
Thank you @vitalybuka

**Comment by bshastry** [comment]
Another generic LPM/libFuzzer/oss-fuzz question: Is support for both LPM and corpus based fuzzing planned? What I mean is that something like

```
$ ./proto-fuzzer-binary native_corpus_dir
```

I can't imagine how this will work because the `proto-fuzzer-binary` is expecting LPM input, where as the `native_corpus_dir` contains native input.

The main concern with LPM only fuzzing is that sometimes (when the proto spec is not good enough), coverage achieved via LPM fuzzing alone is sub-par compared to corpus-based fuzzing. In such cases, until a better proto spec comes along, such hybrid fuzzing may be useful. Wdyt?

**Comment by kcc** [comment]
>> planned? 

Not planned, but being investigated. 

Fully agree with your concern. 

https://github.com/google/fuzzer-test-suite/blob/master/tutorial/structure-aware-fuzzing.md#example-png
is an example of another approach, where the original corpus can be fully utilized with a structure-aware fuzzer.

**Comment by bshastry** [comment]
Thank you. The libpng example is really cool. If I understand correctly,
the libpng-proto fuzzer contains the vanilla LPM fuzzer and a fuzzer with a
custom PNG mutator. I couldn't locate the foo to fooproto code in there.
From the docs that you linked.

> Optionally implement a Foo => FooProtoconverter. This is more important
if there's already an extensive corpus of Foo inputs you'd like to use.

Is there a code example for this?

Sorry if I overlooked something in the docs.

**Comment by kcc** [comment]
> contains the vanilla LPM fuzzer and a fuzzer with a custom PNG mutator.

Yes. These are mostly unrelated.

 > Is there a code example for this?

No, not here. 
It's relatively easy to  extend png_mutator.h to produce a proto, 
but that would be a horrible example, because once you have a custom mutator, 
there is no point in having protos. 

Protos are good in the cases when implementing a custom mutator is a huge work,
but for PNG it turned out to be pretty simple. 

(Well, maybe not exactly true. We've put quite an effort into LPM and so it might still 
be a good off the shelf mutator)

**Comment by bshastry** [comment]
Okay, LPM definitely holds promise. I suppose, I'm trying to find a good
fallback until we have a good proto for our use case (fuzzing a code
optimizer)

I'm contemplating the following options

- separate LPM and corpus based fuzzer
- separate LPM and custom mutator
- others?

I will check out the other proto fuzzers to get a better idea.

Thanks!

**Comment by nedwill** [comment]
I'm working on making my XNU fuzzer compatible with OSS-Fuzz when I eventually open source it. Right now I have to build protobuf myself as part of the Dockerfile build, which means that it won't have the correct instrumentation for MSAN. That's also a lot of work. Ideally protobuf can be present in the build/run containers, and we can make an MSANified version available for MSAN builds (like we already do for libstdc++).

**Comment by vitalybuka** [comment]
Close by mistake in commit message

**Comment by Dor1s** [comment]
Does anyone know why we don't have MSan builds of LPM based fuzz targets? Does LPM library depend on many things which are hard to instrument?

**Comment by vitalybuka** [comment]
> Does anyone know why we don't have MSan builds of LPM based fuzz targets? Does LPM library depend on many things which are hard to instrument?

It has nothing special.

**Comment by evmaus** [comment]
Interesting.  There seems to be an MSAN issue hit by more than one project that seems to be related to something between how libfuzzer and LPM interact.

It seems like some folks have wound up disabling it as it wasn't working for them (https://github.com/google/oss-fuzz/blob/7b9a3a895c6aff4b372b9f5700f0f5e875891983/projects/jsoncpp/build.sh#L32) and one of the summer contributors also ran into an error with LPM and libfuzzer:  https://github.com/google/oss-fuzz/pull/4095/checks?check_run_id=851910517

**Comment by Dor1s** [comment]
@vitalybuka 

@morehouse pointed out on chat that we manually unpoison `data` in libFuzzer before calling `LLVMFuzzerTestOneInput`. That way MSan doesn't complain even if we use `-fsanitize=fuzzer` and don't really compile libFuzzer with MSan.

Would it be possible to add the same hooks for other methods that are being used by LPM (`LLVMFuzzerCustomCrossOver` seems to be one of them)?

**Comment by vitalybuka** [comment]
It should be possible at least for consistency with LLVMFuzzerTestOneInput
However, why OSS-fuzz does not compile libFuzzer with msan? Seems like a better solutions.
LPM and libprotobuf still need to be compiler with msan.

**Comment by morehouse** [comment]
> It should be possible at least for consistency with LLVMFuzzerTestOneInput
> However, why OSS-fuzz does not compile libFuzzer with msan? Seems like a better solutions.

A couple reasons I can think of:
- It requires a manual build of libfuzzer and its private libc++, rather than just `-fsanitize=fuzzer,memory`.
- performance

**Comment by morehouse** [comment]
Also, this might be fixable [here](https://github.com/llvm/llvm-project/blob/master/compiler-rt/lib/fuzzer/FuzzerMutate.cpp#L83) in libFuzzer where we already have the machinery to unpoison things.

**Comment by zd-project** [comment]
We experimented with instrumenting LPM w/o MSAN by specifying `-fno-sanitize=all` in LPM compilation but the issue still persists, passing through LPM to MSAN instrumented standard library calls that caught MSAN error. As @morehouse pointed out

> ...the issue is that LPM has common dependencies with the SUT (e.g., libc++).  Obviously we need to instrument those with MSan, so we need to instrument LPM as well.  I'm thinking the better solution is to unpoison in libfuzzer.

**Comment by vitalybuka** [comment]
> Also, this might be fixable [here](https://github.com/llvm/llvm-project/blob/master/compiler-rt/lib/fuzzer/FuzzerMutate.cpp#L83) in libFuzzer where we already have the machinery to unpoison things.

We need unpoison everything from here: LLVMFuzzerMutate, LLVMFuzzerCustomCrossOver, LLVMFuzzerCustomMutator
https://github.com/llvm/llvm-project/blob/master/compiler-rt/lib/fuzzer/FuzzerInterface.h,

**Comment by vitalybuka** [comment]
> We experimented with instrumenting LPM w/o MSAN by specifying `-fno-sanitize=all` in LPM compilation but the issue still persists, passing through LPM to MSAN instrumented standard library calls that caught MSAN error. As @morehouse pointed out
> 
> > ...the issue is that LPM has common dependencies with the SUT (e.g., libc++).  Obviously we need to instrument those with MSan, so we need to instrument LPM as well.  I'm thinking the better solution is to unpoison in libfuzzer.

LPM would be hard or impossible. LPM creates complex proto messages. Unpoisoning them is going to be inconvenient.
libFuzzer to LPM interfaces is much simpler so the only practical options are instrument "all" vs "all without libfuzzer".
