### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by garyemiller** [google/oss-fuzz#8658]
How do I mark a result as a false positive.  For example this one:

https://oss-fuzz.com/testcase-detail/5379656203501568

Calling an integer overflow a crash is just wrong.  And the whole point of generating a checksum is to use integer overflows!

**Comment by oliverchang** [comment]
Hi there, 

Thanks for raising this issue. Signed integer overflow is undefined behaviour (unlike unsigned integer overflow). Please see https://www.gnu.org/software/autoconf/manual/autoconf-2.63/html_node/Integer-Overflow-Basics.html 

If you still disagree with this, we are happy to disable this check completely. 

Thanks for filing an issue!

**Comment by garyemiller** [comment]
Signed integer overflow is most certainly NOT undefined behavior.  If it were then every checksum code in existence would be undefined.  40 years of experience says otherwise.

**Comment by oliverchang** [comment]
OK, we'll disable this check for gpsd. I opened https://github.com/google/oss-fuzz/pull/8668 for this.

**Comment by garyemiller** [comment]
From C99, page 34:

" A computation involving unsigned operands can never overflow,
because a result that cannot be represented by the resulting unsigned integer type is reduced modulo the number that is one greater than the largest value that can be represented by the resulting type."

**Comment by garyemiller** [comment]
> OK, we'll disable this check for gpsd. I opened https://github.com/google/oss-fuzz/pull/8668 for this.

There will a lot of code the uses this C99 (and higher) behavior.  You need a way for users to makr these false positives.

**Comment by oliverchang** [comment]
Thanks, but the text you quoted applies to **unsigned integers** only. This does not apply to **signed** integers. 

Please see https://www.gnu.org/software/autoconf/manual/autoconf-2.63/html_node/Integer-Overflow-Basics.html: 

"In contrast, the C standard says that signed integer overflow leads to undefined behavior where a program can do anything, including dumping core or overrunning a buffer. The misbehavior can even precede the overflow. Such an overflow can occur during addition, subtraction, multiplication, division, and left shift."

**Comment by garyemiller** [comment]
Note the false positive is for UNSIGNED, not signed, integers.

**Comment by garyemiller** [comment]
Here is the code:

```
            volatile uint16_t len, n, csum, xsum;
[...]
            csum = 0;
            for (n = 0; n < len; n++) {
                volatile uint16_t tmpw = getiw(7 + 2 * n);
                volatile uint32_t tmpdw  = (csum + 1) * (tmpw + n);
                csum ^= (tmpdw & 0xffff) ^ ((tmpdw >> 16) & 0xffff);
            }
```

**Comment by oliverchang** [comment]
I see this line here is the (alleged) offending line: 

https://gitlab.com/gpsd/gpsd/-/blob/1df61193e94b8d09537272a256ce19eefffa4257/gpsd/packet.c#L2650

I don't remember all my C integer promotion rules, but I think what's happening here is that because `csum` is `uint16_t`, and you're adding the constant `1` which is of type `int` to it, the result actually ends up being an `int` which is signed. 

Note this check is coming from a well established Clang sanitizer (https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html), so I would be very surprised if this was wrong.

**Comment by oliverchang** [comment]
https://wiki.sei.cmu.edu/confluence/display/c/INT02-C.+Understand+integer+conversion+rules has a summary of some of these weird C integer promotion rules that seem to apply here:

"Integer types smaller than int are promoted when an operation is performed on them. If all values of the original type can be represented as an int, the value of the smaller type is converted to an int; otherwise, it is converted to an unsigned int. Integer promotions are applied as part of the usual arithmetic conversions to certain argument expressions; operands of the unary +, -, and ~ operators; and operands of the shift operators. The following code fragment shows the application of integer promotions:"

**Comment by garyemiller** [comment]
Unsigned is never promoted to signed.

**Comment by garyemiller** [comment]
As your text clearly says: "If all values of the original type can be represented as an int, the value of the smaller type is converted to an int; otherwise, it is converted to an unsigned int. "

"othersiwe...unsigned int".  Thus overflow is defined.

**Comment by garyemiller** [comment]
"Note this check is coming from a well established Clang sanitizer (https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html), so I would be very surprised if this was wrong."

I find bugs inn 20 year old code all the time.  Note that gdb has known 20 year old, unfied, bugs.

**Comment by oliverchang** [comment]
> As your text clearly says: "If all values of the original type can be represented as an int, the value of the smaller type is converted to an int; otherwise, it is converted to an unsigned int. "
> "othersiwe...unsigned int". Thus overflow is defined.

But an uint16_t can be "represented as an int"... because the set of valid values for `uint16_t` (an unsigned 16-bit integer) can be completely covered by `int` (a signed 32-bit integer).

But i'll stop trying to convince you :) We'll just go ahead and disable this if you're not interested.

**Comment by garyemiller** [comment]
>      But an uint16_t can be "represented as an int".

If the uint16_t gets promoted to an in32, then there is no possible overflow.

But in this case, it is an uint32_t.

> But i'll stop trying to convince you :)

Nothing to do with "convincing", all to do with C99 compliant behavior.

>  We'll just go ahead and disable this

For everyone, please, not just for gpsd.  This sort of checksum code is all over.

The C99 standard is clear here.  Unsigned int math overflow is well defined, and unsigned ints are NEVER promoted to ints.  As your C99 quote makes clear.

> if you're not interested.

You mistake my arguing for disinterest?

**Comment by garyemiller** [comment]
Closed?  Did you give me the way to mark false positives?  Did you fix this for all unsigned integer overflows?  I really doubt it.

**Comment by garyemiller** [comment]
Note, this was the issue:

> How do I mark a result as a false positive. For example...

Did you in fact tell me how to mark things as false positives?

**Comment by oliverchang** [comment]
See https://stackoverflow.com/questions/56604299/why-do-unsigned-small-integers-promote-to-signed-int for an explanation of the rules re smaller unsigned types getting promoted to signed ints. Again, I won't try to change your mind again if this fails to convince you. 

Apologies for not answering your original question as that got lost in our discussion, but typically if you notice a false positive, this can be addresed by either disabling a check (as I have done for this issue), or fixing the fuzz target here as [0x34d](https://github.com/0x34d) has done in https://github.com/google/oss-fuzz/issues/8666.

**Comment by garyemiller** [comment]
> typically if you notice a false positive, this can be addresed by either disabling a check 

How do I disable a check?  How do I disable a check for a particular issue?

Every other validation tool I have used allows me to disable particular code lines for particular checks.  How do I do that?


> or fixing the fuzz target here as [0x34d](https://github.com/0x34d) has done in https://github.com/google/oss-fuzz/issues/8666.

Which is also something I can't do.

**Comment by DavidKorczynski** [comment]
> Every other validation tool I have used allows me to disable particular code lines for particular checks. How do I do that?

I think the best that can be done in terms of controlling things here is configure UBSAN how to handle errors, similar to how libxslt does:

https://github.com/google/oss-fuzz/blob/bfc44b8bc226af526160d9323aefab63700d85bb/projects/libxslt/build.sh#L19-L22

Thus, to do this you have to modify the `gspd` build script https://github.com/google/oss-fuzz/blob/master/projects/gpsd/build.sh to include essentially the same lines as libxslt, that would suppress the signed integer overflow check.

> Which is also something I can't do.

Can you elaborate, in terms of what's stopping you from doing this? You're more than welcome to modify the set up in https://github.com/google/oss-fuzz/tree/master/projects/gpsd

**Comment by garyemiller** [comment]
> Can you elaborate, in terms of what's stopping you from doing this? 

There seem to be a few misunderstandings here, and we are not converging.

> Thus, to do this you have to modify the gspd build script https://github.com/google/oss-fuzz/blob/master/projects/gpsd/build.sh to include essentially the same lines as libxslt, that would suppress the signed integer overflow check.

I have control of this projects code.

That would be a global change.

> that would suppress the signed integer overflow check.

I don't want to "suppress the signed integer overflow check".  I see that when it works, it is useful.  The problem is two fold:

1) it throws false positives.

2) it can not be disabled for particular lines of code.  Codacy allows me to disallow specific checks on specific locations.  Pycode style does, Coverity does.

For 1) fix the test!

For 2) allow marking of false positives.
