### ISSUE TITLE
Weird coverage report for libpng

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#866]
I've tried to use https://clang.llvm.org/docs/SourceBasedCodeCoverage.html for libpng, the result looks weird.

[libpng_coverage_report.zip](https://github.com/google/oss-fuzz/files/1338689/libpng_coverage_report.zip)
[build_log.txt](https://github.com/google/oss-fuzz/files/1338690/build_log.txt)

I believe that I've built everything properly (the build log attached), but there are some confusing pieces:

1) Coverage of the fuzz target code:
![image](https://user-images.githubusercontent.com/3372458/30937543-f79382b6-a38b-11e7-9240-4dd9bd590285.png)

Though I run the fuzzer over corpus of 1634 files. Other libpng files do not have any hits at all.

2) Coverage of libFuzzer files (e.g. `FuzzerClangCounters.cpp`):

![image](https://user-images.githubusercontent.com/3372458/30937374-64462a90-a38b-11e7-9186-5cbaa57d65e6.png)

?!?!?

Another confusion from `FuzzerDriver.cpp`:

![image](https://user-images.githubusercontent.com/3372458/30937474-c0227fd0-a38b-11e7-8cc9-cfc1247fea30.png)

I'll take another look sometime later, unless anybody else wants to.

**Comment by Dor1s** [comment]
I guess it might be caused by behavior described in #854

**Comment by glennrp** [comment]
See libpng commit 0512c63533d20634bad25f133f3094abbae7cda3
which reverts the fuzzer back to a version that did not exhibit the problem.

**Comment by glennrp** [comment]
As far as I can tell, this problem was due to the placement of a call to png_read_update_info() ahead of png_set_interlace_handling(), in libpng_read_fuzzer.cc

**Comment by glennrp** [comment]
Coverage reports for libpng have been OK for a week or more; I think this issue can be closed.

**Comment by oliverchang** [comment]
Sure, thanks!
