### ISSUE TITLE
Support FuzzTest + libFuzzer/centipede

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#8678]
FuzzTest interfaces with external engines through [LLVMFuzzerRunDriver](https://llvm.org/docs/LibFuzzer.html#using-libfuzzer-as-a-library). This is supported by all engines used in OSS-Fuzz ([libFuzzer](https://llvm.org/docs/LibFuzzer.html#using-libfuzzer-as-a-library), [Centipede](https://github.com/google/centipede/blob/c6ee177644c40f19a7175e44309a55cefae50d89/runner_interface.h#L58-L60), [AFL++](https://github.com/AFLplusplus/AFLplusplus/blob/stable/utils/aflpp_driver/aflpp_driver.c#L277-L278)), except [HonggFuzz](https://github.com/google/honggfuzz). (We skip running with HonggFuzz for now, but it’d be easy to add support for this in HonggFuzz too if there’s interest.)

This means that with fuzz tests we need to link the “no main” version of the engine’s library (e.g., lib/linux/libclang_rt.fuzzer_no_main-<architecture>.a for libFuzzer). This is not supported by OSS-Fuzz yet: $LIB_FUZZING_ENGINE contains the default library. One option is to introduce a $LIB_FUZZING_ENGINE_NO_MAIN. Alternatively, we can just “guess” from the $LIB_FUZZING_ENGINE value, which is the “no main” version. 

From @lszekeres

**Comment by Navidem** [comment]
Done by #8784
