### ISSUE TITLE
Performance reports links to log examples are not always correct

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#868]
Not sure when it started to happen, but e.g. 

`https://pantheon.corp.google.com/storage/browser/dlplibs-logs.clusterfuzz-external.appspot.com/libFuzzer_dlplibs_superpaintfuzzer/libfuzzer_asan_dlplibs/2017-09-28/07:31:38:006928.txt` 

doesn't exist, though there is `07:31:39:564132.txt` that looks related to the issue.

**Comment by Dor1s** [comment]
Surprisingly, I've never seen that issue on internal ClusterFuzz. Will investigate and fix later this week.

**Comment by cmeister2** [comment]
I was going to come and raise this bug too. I don't think the log examples have ever been right for curl.

**Comment by Dor1s** [comment]
Ok, I'm on it.

**Comment by Dor1s** [comment]
Oliver has uploaded a fix for that. It wouldn't fix the logs uploaded until now (anyway those logs get deleted in 2 weeks), but the new ones should be linked properly starting tomorrow. Sorry for the inconveniences.

**Comment by Dor1s** [comment]
Now it works properly (for recent reports, not for the old ones), thanks everyone.
