### ISSUE TITLE
atheris bug: unable to cast python instance to C++ type

### ISSUE THREAD

**Issue by ret2libc** [google/oss-fuzz#8682]
Some projects terminate after throwing a pybind11::cast_error:
```
terminate called after throwing an instance of 'pybind11::cast_error'
  what():  Unable to cast Python instance to C++ type (#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)
AddressSanitizer:DEADLYSIGNAL
=================================================================
==826==ERROR: AddressSanitizer: ABRT on unknown address 0x05390000033a (pc 0x7f551ad7b18b bp 0x60e0000017f8 sp 0x7ffe39312260 T0)
    #0 0x7f551ad7b18b in raise /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
    #1 0x7f551ad5a858 in abort /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:79:7
    #2 0x7f551abf1910  (/tmp/_MEIIvOWiz/libstdc++.so.6+0x9e910) (BuildId: c90e6603c7cdf84713cd445700a575d3ea446d9b)
    #3 0x7f551abfd38b  (/tmp/_MEIIvOWiz/libstdc++.so.6+0xaa38b) (BuildId: c90e6603c7cdf84713cd445700a575d3ea446d9b)
    #4 0x7f551abfd3f6 in std::terminate() (/tmp/_MEIIvOWiz/libstdc++.so.6+0xaa3f6) (BuildId: c90e6603c7cdf84713cd445700a575d3ea446d9b)
    #5 0x7f55184b492a in __clang_call_terminate (/tmp/_MEIIvOWiz/atheris/core_without_libfuzzer.cpython-38-x86_64-linux-gnu.so+0xb92a)
    #6 0x7f55184b4878 in pybind11::error_already_set::what() const /tmp/pip-install-7v6tezjq/atheris/.eggs/pybind11-2.10.0-py3.8.egg/pybind11/include/pybind11/pybind11.h:2636:24
    #7 0x7f55184c7189 in atheris::PrintPythonException(pybind11::error_already_set const&, std::ostream&) /tmp/pip-install-7v6tezjq/atheris/src/native/util.cc:45:25
    #8 0x7f55184b38f0 in atheris::TestOneInput(unsigned char const*, unsigned long) /tmp/pip-install-7v6tezjq/atheris/src/native/core.cc:159:5
    #9 0x7f551afa4263 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #10 0x7f551af8f9c2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #11 0x7f551af9526c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #12 0x7f551af95a18 in LLVMFuzzerRunDriver /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:925:10
[...]
```

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49764
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49884
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49929
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50074
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49188
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49597
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49598

**Comment by TheShiftedBit** [comment]
Did this just recently start happening?

**Comment by jonathanmetzman** [comment]
I think this has been going on since July.

**Comment by oliverchang** [comment]
@TheShiftedBit any ideas on what's going wrong here? 

@DavidKorczynski @AdamKorcz as well in case you have any ideas there.

**Comment by TheShiftedBit** [comment]
Hi, I'm sorry, I've been really busy. I'll investigate tomorrow

**Comment by TheShiftedBit** [comment]
Some updates.
I can reproduce inside of the oss-fuzz container, but not running the script normally. That means this might be related to PyInstaller.
I added the compile flag that pybind11 suggested; the error is: 
```
terminate called after throwing an instance of 'pybind11::cast_error'
  what():  Unable to cast Python instance of type <class 'str'> to C++ type 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
```
Which is just weird.

**Comment by TheShiftedBit** [comment]
I have found a bug pybind11.

In older versions, this presents as Pybind11 replacing the original exception with `RuntimeError: Unable to extract string contents! (encoding issue)`. This is at least descriptive, but it completely replaces the original exception with that message, making it impossible to determine the original exception. Furthermore, the replacement happened during the Python->C++ transition, so there's no way to get the original exception before it's replaced either. (Whether this behavior in the older version of pybind11 is "buggy" is ambiguous).

In new versions of pybind11, however, the `cast_error` is thrown from within the `.what()` function on `pybind11::error_already_set`. Unfortunately, `.what()` is marked as `noexcept`, meaning it promises never to throw an exception. This causes Python to crash without any opportunity to handle the error.

I'll soon update Atheris to (a) always build with the newer version of pybind11, and (b) never call `.what()` (instead generating the exception message itself). I'll also file a bug against pybind11.

**Comment by oliverchang** [comment]
thanks a ton @TheShiftedBit !!

**Comment by oliverchang** [comment]
@Navidem can you help make sure that we're installing the latest atheris version in our base images?
