### ISSUE TITLE
Issue 51020

### ISSUE THREAD

**Issue by jaymehta6** [google/oss-fuzz#8696]
I can not access the testcase crafted in this project of jackson-databind:ObjectReader2Fuzzer: Security exception in com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseBooleanPrimitive. Please do the needful so that the testcase can be downloaded and tested in a particular jar file.

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=4650513269915648

**Comment by jonathanmetzman** [comment]
Did you sign in with your google account? it should work. someone just reproduced this for me now.

**Comment by AdamKorcz** [comment]
Only emails here can access the issue: https://github.com/google/oss-fuzz/blob/master/projects/jackson-databind/project.yaml. It looks like your email is not on the list so I am closing. If it is, feel free to reopen the issue.
