### ISSUE TITLE
Ignore email case sensitivity.

### ISSUE THREAD

**Issue by terrelln** [google/oss-fuzz#870]
The message is "You (email=NickRTerrell@gmail.com) are not authorized to access this page!", even though I'm the primary contact.

**Comment by kcc** [comment]
@oliverchang can we do lower-casing automatically?

**Comment by kcc** [comment]
Ah, that's the other way around? the e-mail needed to be in CamelCase?

**Comment by oliverchang** [comment]
@terrelln please try again, i've fixe the casing of your email in project.yaml

@kcc I'll take a look next week, but I'm not sure if it's correct to assume emails are case insensitive.

**Comment by terrelln** [comment]
@oliverchang Thanks! AFAIK all gmail addresses are case insensitive, I didn't even know my email had uppercase letters.

**Comment by oliverchang** [comment]
OK, it looks like it's safe to do case insensitive matches on our side. I'll take this.

**Comment by oliverchang** [comment]
This should be done now.
