### ISSUE TITLE
Get rid of go install in base-runner

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#8701]
The go install is 500 MB and is the largest layer in base-runner. Can we get rid of it @catenacyber ? https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/Dockerfile#L68
I think the main thing we will need to fix is how we invoke certain binaries like this: `go tool cover -html=fuzz.cov -o $REPORT_ROOT_DIR/index.html` instead we will need to call the binaries directly.

**Comment by catenacyber** [comment]
We can install it, compile (`go build`) go's cover tool, and then remove it.
How would that sound ?

**Comment by jonathanmetzman** [comment]
That sounds excellent. If you could do this that would be great!
I think we need pprof too right?

**Comment by jonathanmetzman** [comment]
Alternatively we can delete these directories for 330 MB of uncompressed savings:
/root/.go/src
/root/.go/test
/root/.go/api
/root/.go/misc
/root/.go/pkg/linux_amd64_race
/root/.go/pkg/linux_amd64
/root/.go/pkg/tool/linux_amd64/compile
/root/.go/pkg/linux_amd64/trace
/root/.go/pkg/linux_amd64/vet
/root/.go/pkg/linux_amd64/link
/root/.go/pkg/linux_amd64/asm
And some more binaries in /root/.go/pkg/linux_amd64/ <30 MB of saving

**Comment by catenacyber** [comment]
Hot untested try : https://github.com/google/oss-fuzz/pull/8703

For pprof, we already have gocovmerge gocovsum and pprof-merge compiled and installed

If we need more in the future, this is just one line to add...

**Comment by jonathanmetzman** [comment]
Fixed.
