### ISSUE TITLE
Issue 52040 is a false positive, similar to resolved issue 52037

### ISSUE THREAD

**Issue by garyemiller** [google/oss-fuzz#8715]
Issue 52040 is a false positive, similar to resolved issue 52037.

And I still can't access Issue 

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52037#c3

**Comment by DavidKorczynski** [comment]
@0x34d Can you please assist here?

**Comment by 0x34d** [comment]
The issue was created by UBSAN, 
UBSAN is removed https://github.com/google/oss-fuzz/pull/8668

**Comment by 0x34d** [comment]
I believe this is a sanitizer bug. https://github.com/google/sanitizers/issues/1580

**Comment by DavidKorczynski** [comment]
> UBSAN is removed #8668

Thanks, closing because of this.
