### ISSUE TITLE
Leaks not raised as issues?

### ISSUE THREAD

**Issue by cmeister2** [google/oss-fuzz#872]
Over the last couple of days curl has had a few testcases generated which cause memory leaks, but oss-fuzz didn't raise an issue (they're present on the dashboard though)

For example, this log file shows the leak: https://storage.cloud.google.com/curl-logs.clusterfuzz-external.appspot.com/libFuzzer_curl_fuzzer/libfuzzer_asan_curl/2017-09-30/00%3A04%3A06%3A471676.txt

I noticed this separately and @bagder closed in https://github.com/curl/curl/pull/1933, so the problem is sorted; I'm just wondering if leaks will have issues raised for them or do we have to monitor the dashboard?

**Comment by inferno-chromium** [comment]
No bugs get autofiled, so dashboard does not need monitoring. I see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3513 issue filed, fixed and closed and i see daniel.haxx@gmail.com, daniel@haxx.se and cmeister2@gmail.com being cced. That bug matches the leak link you gave. Is there any other leak you want us to look.
--

**Comment by cmeister2** [comment]
There were two bugs in the same area of code - the first got fixed as 3513, the second was still open. The first was in a strdup of two strings, the second was a leak in sanitize_cookie_path.

**Comment by inferno-chromium** [comment]
So, looking at dashboard - https://oss-fuzz.com/v2/testcases?open=yes&project=curl, i don't see any other bugs open, so it means that fuzz target is not hitting the second bug. are you hitting that bug locally ? do you have log link that points to the second bug.

**Comment by cmeister2** [comment]
There's a link in the issue: https://storage.cloud.google.com/curl-logs.clusterfuzz-external.appspot.com/libFuzzer_curl_fuzzer/libfuzzer_asan_curl/2017-09-30/00%3A04%3A06%3A471676.txt

The log:

```
==1==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 18 byte(s) in 1 object(s) allocated from:
    #0 0x4dee08 in malloc _asan_rtl_
    #1 0x51fdad in curl_domalloc /tmp/curl/lib/memdebug.c:175:9
    #2 0x52043f in curl_dostrdup /tmp/curl/lib/memdebug.c:230:9
    #3 0x54e690 in sanitize_cookie_path /tmp/curl/lib/cookie.c:226:20
    #4 0x54c5ac in Curl_cookie_add /tmp/curl/lib/cookie.c:502:23
    #5 0x55ee37 in Curl_http_readwrite_headers /tmp/curl/lib/http.c:3720:7
    #6 0x5a1930 in readwrite_data /tmp/curl/lib/transfer.c:530:16
    #7 0x5a04da in Curl_readwrite /tmp/curl/lib/transfer.c:1139:14
    #8 0x52d1d3 in multi_runsingle /tmp/curl/lib/multi.c:1895:16
    #9 0x52ba53 in curl_multi_perform /tmp/curl/lib/multi.c:2160:14
    #10 0x51ecdc in easy_transfer /tmp/curl/lib/easy.c:708:15
    #11 0x51d1be in easy_perform /tmp/curl/lib/easy.c:794:42
    #12 0x51a87a in LLVMFuzzerTestOneInput /tmp/curl_fuzzer/curl_fuzzer.cc:84:3
    #13 0x624bd0 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:463:13
    #14 0x6232a6 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*) /src/libfuzzer/FuzzerLoop.cpp:392:3
    #15 0x6265c7 in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:589:9
    #16 0x628077 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:696:5
    #17 0x60fab6 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:736:6
    #18 0x602e88 in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #19 0x7f354742682f in __libc_start_main /build/glibc-9tT8Do/glibc-2.23/csu/libc-start.c:291

SUMMARY: AddressSanitizer: 18 byte(s) leaked in 1 allocation(s).
INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.
```

**Comment by Dor1s** [comment]
There are some leaks found on Crash Stats page: https://oss-fuzz.com/v2/crash-stats?block=day&days=7&end=418583&group=platform&number=count&q=curl&sort=total_count

All of them are marked as non reproducible, i.e. we cannot find a single testcase that would reliably reproduce it. We do file such issues as well, but first we need to see the same issue happening 14 days in a row. Those new leaks a fairly new (happening for last 3-5 days), this is why those are not auto-filed yet.

**Comment by inferno-chromium** [comment]
That stacktrace you pointed is a reproducible bug detected in https://oss-fuzz.com/v2/testcase-detail/5271812776656896. It was grouped with the other issue's testcase due to crash state similarity. It is now detected as fixed. It was not filed separately since it was part of testcase group. How we work in that case is we wait for one testcase in group to get fixed, then if the second one is still unfixed, we will autofile it as a seperate bug. Looks like in this case, you fixed both the bugs, so you will never see the second testcase as filed. Our grouping logic helps to keep spam from similar looking stacktraces,  and if we do it incorrectly, we autofile the second bug after first is fixed. Does it make sense ?

**Comment by cmeister2** [comment]
Ok, all sounds reasonable. I'll close this now.
