### ISSUE TITLE
Curl stacktrace sources are not hyperlinked and regression range does not curl range

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#874]
E.g. https://oss-fuzz.com/v2/testcase-detail/6635070158798848

I think this broke after https://github.com/google/oss-fuzz/commit/bf16050624e88ae1c2428a9a1cdfc13adf306b43#diff-8ffe952a5990a2786089b4096b8df01c

Sources should be in /src/curl and fuzzer can checked into /src/curl_fuzzer, so that source lines in stacktraces use that path. @cmeister2 - can you please fix that.

@oliverchang - is the above solution right ?

**Comment by inferno-chromium** [comment]
Even regression range is broken. It does not have the curl regression range.

Previously it worked fine, e.g. https://oss-fuzz.com/v2/testcase-detail/5578413563707392

**Comment by cmeister2** [comment]
I will fix up today. I may move more of the build logic to the curl-fuzzer project while I'm at it so that we can fix things without PRs here.
