### ISSUE TITLE
failed build logs seem out of date

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#877]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html lists LibreOffice build as "failed" and Last built 29/9/2017, 06:11:48 with git revision 25cd067a82742210793e39708cc1de9ff84692a7 of libreoffice.

But I've definitely fixed that with https://cgit.freedesktop.org/libreoffice/core/commit/?id=fc67b4476c9cdaa01c6ea008be592ff08731d1b1 and oss-fuzz has sent reports that various bugs have been found and fixed in various builds since then, so it looks to me like the build status page gets stuck at the first failure of a project to build

**Comment by oliverchang** [comment]
It looks like the build is timing out and our builds status page didn't correctly account for that. It should be fixed shortly. 

Even though the build timed out, some build configurations still succeeded and got uploaded.

I've also increased the build time limit from 4 hours to 6 hours to see if this resolves the libreoffice build.

**Comment by caolanm** [comment]
This all seems to work fine for me now
