### ISSUE TITLE
Make results from trial builds more prominent

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#8774]
1. It would be nice if trial builds reported on the comment what went wrong, rather than just complaining something went wrong.
2. If trial builds posted the logs to some publically accessible place, it would make the lives of maintainers easier when testing third party patches (we wouldn't need to do this for example: https://github.com/google/oss-fuzz/pull/8736)

**Comment by jonathanmetzman** [comment]
Nice @oliverchang I got the results to display on github. I had to make a new trigger using this command though `gcloud --project oss-fuzz-base beta builds triggers create github --region us-central1 --repo-name oss-fuzz --repo-owner google --branch-pattern ".*" --build-config=infra/build/functions/trial_build/cloudbuild.yaml --include-logs-with-status` simply checking the box on the web interface for my old trigger didn't work.

**Comment by jonathanmetzman** [comment]
To complete this, we need to make trial builds link to each build's logs and make those publicly accessible.

**Comment by jonathanmetzman** [comment]
The github display feature is truncated, so I'm gonna try using cloud buckets even though this is much less prominent.
We can probably combine the two, by printing instructions on getting to the full logs.
Related: https://github.com/google/oss-fuzz/pull/9303

**Comment by oliverchang** [comment]
+1 to this feature. So I think we need a few pieces here as @jonathanmetzman suggested:
1. Make the individual trial GCBs write logs to a publicly accessible bucket. We can leverage a Cloud Build feature for this. 
2. Add a step at the end of the trial build to write results as a GitHub comment summarising the results. If there are any failures, link to any failure logs.
