### ISSUE TITLE
Accessing testcases for bugs that exceeded the disclosure deadline

### ISSUE THREAD

**Issue by mechtaev** [google/oss-fuzz#879]
Hi,

I am doing research on software bugs and vulnerabilities and I would like to obtain data from OSS-Fuzz for experimentation. I noticed that some data (including bugs that exceeded the disclosure deadline) is not available. Is it possible to get access to this data?

More specifically, I tried this issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1424

This bug has the status `Deadline-Exceeded`:

`This bug has exceeded our disclosure deadline. It has been opened to the public.
`

However, when I tried to download the testcase, I got the following message:

```
You (mechtaev@gmail.com) are not authorized to access this page!

For access, please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.

If you see this error while trying to download a test case for a bug that you are the owner of, please download it from the test case details page.

Back
Switch account
Logout
```

**Comment by oliverchang** [comment]
Hi, that bug report should have been duped in to https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1426. You may download the testcase through that issue instead.

We don't treat bugs that exceeded the deadline any differently when it comes to making testcases public.

**Comment by thomasdullien** [comment]
Hey there,

I seem to be running into the same issue in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1434, which references https://oss-fuzz.com/testcase-detail/6314998085189632.

A search for the bug title of 1434 did not produce a dup, how would I go about finding the testcase?

**Comment by inferno-chromium** [comment]
@thomasdullien - for publicly open bugs, we only allow downloading of the testcase, but not the full crash report. if you try https://oss-fuzz.com/download?testcase_id=6314998085189632 link given in c#0, then the testcase should download. I forgot what was the reasoning for this access restriction, @oliverchang might remember (i think something related to not exposing infra metadata in report maybe).
