### ISSUE TITLE
run fuzzer failed and upload Crash error

### ISSUE THREAD

**Issue by vincentgoat** [google/oss-fuzz#8792]
When we run CI-Fuzz in KubeEdge project and we got the errors `Bug found. Stopping fuzzing` without call stack, more details here: https://github.com/kubeedge/kubeedge/actions/runs/3263101307/jobs/5361314140

This issue occurs frequently, but sometimes retries succeed, that's tricky. Can you help me to fix it?
cc @AdamKorcz @DavidKorczynski

**Comment by AdamKorcz** [comment]
@jonathanmetzman Is this something you have seen before in CIFuzz?

The CIFuzz `.yaml` is here: https://github.com/kubeedge/kubeedge/blob/master/.github/workflows/cifuzz.yml

**Comment by jonathanmetzman** [comment]
Actually this looks similar to #8768

**Comment by vincentgoat** [comment]
Fixd by https://github.com/google/oss-fuzz/pull/8901
