### ISSUE TITLE
How do we access oss-fuzz found bugs?

### ISSUE THREAD

**Issue by LibRaw** [google/oss-fuzz#8828]
This one, for example: https://github.com/LibRaw/LibRaw/issues/496

the https://oss-fuzz.com/testcase-detail/6381559087497216 refuses access (via github auth):

You (email=info@libraw.org) are not authorized to access this page!

Please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.

**Comment by DavidKorczynski** [comment]
This should be addressed in https://github.com/google/oss-fuzz/pull/8830

Note the caveat here https://github.com/google/oss-fuzz/pull/8830#issuecomment-1286692421

**Comment by DavidKorczynski** [comment]
Closing this as it seems resolved https://github.com/google/oss-fuzz/pull/8830#issuecomment-1286973116
