### ISSUE TITLE
add the target name to the bug subject line

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#883]
Right now subjects in our bug reports look like this:
```
project: <bug description>
```
E.g. the subject in [3137](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3137) looks like
```
llvm: ASSERT: CurPtr[-1]...
```

Can we add the target name to the subject? In this case, it could look like this:
```
llvm/clang-fuzzer: ASSERT: CurPtr[-1]...
```
I've been just asked about this on the LLVM dev mailing list. 
Sounds like an improvement. 

Reasons why we may not want to do this:
* this will break someone's e-mail filters
* some target names are long
* some projects have only one target 
* ??? 

WDYT?

**Comment by bogner** [comment]
+1. This makes the subjects more useful and makes good email filters trivial to set up. Long target names might be a problem, but I suspect they're unusual enough to not be too worrying.

**Comment by oliverchang** [comment]
This sounds reasonable to me.

**Comment by Dor1s** [comment]
Sounds good for OSS-Fuzz, but not sure about internal CF.

**Comment by oliverchang** [comment]
This is done. See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3636 for an example.
