### ISSUE TITLE
flag provided but not defined: -console

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#884]
First of all, the log size seems to be limited again (we had that before). That prevents me to see the actual error for gnutls which currently doesn't build.

So I tried to build/run locally without success:
```
Step 3/13 : RUN apt-get update && apt-get install -y  make  pkg-config  autoconf  automake  autogen  autopoint  libtool  gperf  bison  texinfo  curl  gettext  gengetopt  wget  python  mercurial
 ---> Running in f330ed5ef66a
Incorrect Usage: flag provided but not defined: -console
...
flag provided but not defined: -console
oci runtime error: flag provided but not defined: -console
docker build failed.
```

This is on up-to-date Debian unstable. I can't say if this a Debian issue or an incompatibility with newer docker/runc versions. Do you know any way to work-around this issue ?

**Comment by oliverchang** [comment]
I'm afraid I can't reproduce this issue.

That said, the gnutls build actually succeeded. The log truncation issue caused us to mark it as failed on https://oss-fuzz-build-logs.storage.googleapis.com/index.html (this is a Container Builder bug). I've added a hacky workaround to prevent such builds from being marked as failed in the future.

**Comment by rockdaboot** [comment]
Sounds good, thanks !
