### ISSUE TITLE
Regression "Invalid archive signature" in JDK fuzzing pipeline

### ISSUE THREAD

**Issue by johannes-riecken** [google/oss-fuzz#8860]
The fuzzing pipeline of a repo I haven't recently changed started to fail recently (see [run](https://github.com/johannes-riecken/pacman-java/actions/runs/3320628577/jobs/5493958565)). The error is

> E: Invalid archive signature
> E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}

Shouldn't there be commas like `control.tar.{...,gz,xz,bz2,...}`? If it helps, then feel free to fork my repo or to make changes to its pipeline.

**Comment by jonathanmetzman** [comment]
1. It's weird you are using coverage for batchfuzzing. I sorta consider this incorrect usage, I guess this sorta works with java but it will totally fall over with C++
2. I don't think this issue is on our end, I'm guessing apt or the deb file changed.
3. What are you using this repo for? Just curious

**Comment by johannes-riecken** [comment]
1. Interesting. How comes that wouldn't work with C++? Isn't it good to have an overview of what lines were covered during batch fuzzing?
2. I think you're right, as I get the same error when just running the `curl` command and the `apt install` command in a fresh Ubuntu container. I'll close this issue then.
3. It's a testing project I wrote for fuzzing with lots of assertions about my assumptions of how the code works. The fuzzer gets low coverage, so hopefully once the Github coverage reporting of the JDK fuzzer is fixed, I'll find out why.

**Comment by jonathanmetzman** [comment]
> 1. Interesting. How comes that wouldn't work with C++? Isn't it good to have an overview of what lines were covered during batch fuzzing?

Coverage is not meant for batch fuzzing. You should be using `address`
