### ISSUE TITLE
Unable to pull docker image

### ISSUE THREAD

**Issue by sai-sunder-s** [google/oss-fuzz#8879]
Hi,
I am following these [steps](https://google.github.io/oss-fuzz/advanced-topics/reproducing/#pull-the-latest-docker-images) to reproduce a bug that was reported by oss-fuzz.

When I run `python3 infra/helper.py pull_images`, I hit the below error:
```
INFO:root:Running: docker pull gcr.io/oss-fuzz-base/base-image
Using default tag: latest
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=gcr.io%2Foss-fuzz-base%2Fbase-image&tag=latest": dial unix /var/run/docker.sock: connect: permission denied
ERROR:root:Docker pull failed.
```

Should I be joining any group to get access? I did not find info on this in the steps.

**Comment by DavidKorczynski** [comment]
This is due to your Docker set up.

Either, use `sudo` for your commands or https://docs.docker.com/engine/install/linux-postinstall/
