### ISSUE TITLE
Issue 50217: Update fixed commit

### ISSUE THREAD

**Issue by radarhere** [google/oss-fuzz#8892]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50217#c2
> ClusterFuzz testcase 5368876619137024 is verified as fixed in https://oss-fuzz.com/revisions?job=libfuzzer_asan_pillow&range=202210190612:202210200610
>
> If this is incorrect, please file a bug on https://github.com/google/oss-fuzz/issues/new

Hi. I'm one of the core contributors to Pillow. From my testing, the test case wasn't fixed by the commits referenced. The issue was only occurring intermittently, and this later test just happened to pass. The issue was properly fixed in https://github.com/python-pillow/Pillow/pull/6678

**Comment by oliverchang** [comment]
Thanks for the report and pointing us to the actual fix! I've added a comment on this issue indicating the correct fix.
