### ISSUE TITLE
some bug reports don't have the project name in the title

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#890]
See e.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3629
The title is `ASSERT: Offset <= INT_MAX && "Offset too big to fit in int."`
while it should be `llvm: ASSERT: Offset <= INT_MAX && "Offset too big to fit in int."`

**Comment by oliverchang** [comment]
Thanks, I'll fix this together with #883.

**Comment by oliverchang** [comment]
Should be fixed now.
