### ISSUE TITLE
"Merging new testcases timed out:"

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#892]
I'm looking at the llvm run logs:
e.g. 
gs://llvm-logs.clusterfuzz-external.appspot.com/libFuzzer_llvm_clang-proto-fuzzer/libfuzzer_asan_llvm/2017-10-13/03:00:09:158440.txt

It's last line is a cryptic 
```
Merging new testcases timed out:
```

Should I worry about this?

**Comment by oliverchang** [comment]
That means that when we are merging new units back into the main corpus, it took more than our timeout (from memory 5 minutes). I can take a closer look next week.

**Comment by kcc** [comment]
I.e. I do need to worry. :( 
This target is particularly slow, so a timeout is not unexpected.

**Comment by oliverchang** [comment]
It looks like the majority of merges are failing for this target. Some are still succeeding, and the current corpus size is around 11k files. @Dor1s is this something that would've been caught with performance analyzer?

We can try to increase the timeout (it's actually 10 minutes right now), but does merge ever write partial results? or does it only write any files at the very end?

**Comment by kcc** [comment]
Can we start from exposing the merge logs so that I can see when exactly it fails?

**Comment by oliverchang** [comment]
Sure, we had some issues before with the merge logs being too large so we removed it, but now we have support for truncating logs so this should be doable.

**Comment by kcc** [comment]
Also, may I ask you to increase the timeout to 30 minutes, at least temporary.

**Comment by Dor1s** [comment]
>  is this something that would've been caught with performance analyzer?

Performance analyzer reports `coverage` issue since number of new units added appears to be 0, but it doesn't process `Merging new testcases timed out:` error in any special way. I think we might want catching stuff like that via notifications, as it seems to be an issue on our side rather than fuzz target problem?

Also, there are some other issues with our logging :(

e.g. the following log: https://storage.cloud.google.com/llvm-logs.clusterfuzz-external.appspot.com/libFuzzer_llvm_clang-proto-fuzzer/libfuzzer_asan_llvm/2017-10-15/04%3A05%3A10%3A827003.txt?_ga=2.60976492.-192946872.1496676137

```
<...>
#7192	NEW    cov: 76929 ft: 266707 corp: 2482/2203Kb exec/s: 18 rss: 333Mb L: 841/6493 MS: 1 Custom-
#7196	NEW    cov: 76929 ft: 266    main(sys.argv)
  File "/mnt/scratch0/clusterfuzz/src/tools/fuzzers/libFuzzer/launcher.py", line 1048, in main
    print '\n'.join(log_lines)
IOError: [Errno 11] Resource temporarily unavailable
```


or that one: https://storage.cloud.google.com/llvm-logs.clusterfuzz-external.appspot.com/libFuzzer_llvm_clang-proto-fuzzer/libfuzzer_asan_llvm/2017-10-15/04%3A06%3A36%3A347010.txt?_ga=2.63980143.-192946872.1496676137

```
<...>
#3271	NEW    cov: 75126 ft: 279215 corp: 1103/524Kb exec/s: 37 rss: 303Mb L: 585/2534 MS: 1 Custom-
#3272	NEW    cov: 75127 ft: 279219 corp: 1104/525Kb exec/s: 37 rss: 303Mb L: 1687/2534 MS: 2 Custom-CustomCrossOver-
#3274close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```

**Comment by oliverchang** [comment]
Timeout has been increased to 30 minutes, and any errors during merge should now be printed.

**Comment by oliverchang** [comment]
Still seeing timeouts even with 30 minute merge timeout :(

e.g. gs://llvm-logs.clusterfuzz-external.appspot.com/libFuzzer_llvm_clang-proto-fuzzer/libfuzzer_asan_llvm/2017-10-17/18:02:47:401433.txt

```
Merging new testcases timed out: INFO: Seed: 2196642225
INFO: Loaded 1 modules   (1605900 guards): 1605900 [0x118a9290, 0x11ec96c0),
MERGE-OUTER: 46212 files, 44212 in the initial corpus
MERGE-OUTER: attempt 1
INFO: Seed: 2196922257
INFO: Loaded 1 modules   (1605900 guards): 1605900 [0x118a9290, 0x11ec96c0),
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.1.txt'
MERGE-INNER: 46212 total files; 0 processed earlier; will process 46212 files now
#1      pulse  cov: 2348 exec/s: 0 rss: 181Mb
#2      pulse  cov: 2357 exec/s: 0 rss: 181Mb
#4      pulse  cov: 2383 exec/s: 0 rss: 181Mb
#8      pulse  cov: 23827 exec/s: 0 rss: 237Mb
#16     pulse  cov: 24454 exec/s: 0 rss: 247Mb
#32     pulse  cov: 24531 exec/s: 0 rss: 251Mb
#64     pulse  cov: 35383 exec/s: 64 rss: 263Mb
#128    pulse  cov: 36694 exec/s: 42 rss: 264Mb
#256    pulse  cov: 45190 exec/s: 36 rss: 271Mb
#512    pulse  cov: 55616 exec/s: 28 rss: 278Mb
#1024   pulse  cov: 65587 exec/s: 23 rss: 285Mb
#2048   pulse  cov: 71639 exec/s: 20 rss: 293Mb
#4096   pulse  cov: 76511 exec/s: 18 rss: 304Mb
#8192   pulse  cov: 82721 exec/s: 17 rss: 328Mb
#16384  pulse  cov: 87082 exec/s: 14 rss: 378Mb
```

**Comment by kcc** [comment]
Yep. This target is both very large and very slow -- we'll  hit all kinds of scalability troubles with it. 

But here, why do we have this? `46212 files, 44212 in the initial corpus`

Is it possible to include the merge command into the log?

**Comment by oliverchang** [comment]
If that helps, sure.

Does it make sense for merge to write partial results though, even if the process is killed before it finishes?

**Comment by kcc** [comment]
> Does it make sense for merge to write partial results though, even if the process is killed before it finishes?

In general -- maybe, but in this case it won't help. 
We have a large initial corpus (44212 files) and a small extra corpus (200 files). 
The merge first tries to read & execute the corpus and times out while doing that.

libFuzzer has two flags that are supposed to help here: 
```
FUZZER_FLAG_STRING(save_coverage_summary, "Experimental:"
                   " save coverage summary to a given file."
                   " Used with -merge=1")
FUZZER_FLAG_STRING(load_coverage_summary, "Experimental:"
                   " load coverage summary from a given file."
                   " Treat this coverage as belonging to the first corpus. "
                   " Used with -merge=1")

```

With these flags you can run the main corpus only once (with a much larger timeout) and then merge new elements w/o re-executing the main corpus. 
This works only when the binary didn't change. 
Do you think this workflow will work for CF? 

If not, I'll need to think more...

**Comment by oliverchang** [comment]
I've made the change to add the merge command to the output. Logs should start having this in a few hours.

{save,load}_coverage_summary should work with our workflow. I'll create a new bug for it, thanks!

**Comment by inferno-chromium** [comment]
Closing this here, since {save,load}_coverage_summary is tracked by other bug.
