### ISSUE TITLE
old "flaky" oom no longer seen for a week, but issue open

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#895]
So, https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3009 was reported in August, but now hasn't been seen for over a week according to the stats at https://oss-fuzz.com/v2/testcase-detail/5660564107821056

But text states, "If the fix resolved the issue, please close the bug by marking as Fixed." I assume I don't have the privileges to do this (?), so if there another mechanism to trigger that ?

**Comment by Dor1s** [comment]
Good point. @oliverchang, should we remove this part of the comment ("Please close the bug...") for OSS-Fuzz? or re-phrase it like "Please leave a comment ..."?

**Comment by oliverchang** [comment]
This will get autoclosed in 14 days after it stops happening.

I think we should just remove the "Please close the bug" part of the comment. It's easy for us to miss comments left by people on monorail bugs.

**Comment by Dor1s** [comment]
It looks like Abhishek has changed that comment 1.5 months ago, so this particular text appears on the old reports only.
