### ISSUE TITLE
Need access to oss-fuzz for trafficserver project

### ISSUE THREAD

**Issue by shukitchan** [google/oss-fuzz#8950]
I received a few emails regarding the following issues 

https://oss-fuzz.com/testcase?key=5979420909502464
https://oss-fuzz.com/testcase?key=4848849755963392
https://oss-fuzz.com/testcase?key=4953201724227584

And I would like to access these reports. I think that means adding my email to this - https://github.com/google/oss-fuzz/blob/master/projects/trafficserver/project.yaml#L6 ?

**Comment by DavidKorczynski** [comment]
Yes, please add your email there by way of PR. Maintainer approval is needed to be on the CC list to view details about issues. I see you're a contributor/maintainer https://github.com/apache/trafficserver/graphs/contributors but, can also see from the initial integration https://github.com/google/oss-fuzz/pull/8832 @bryancall determined which emails are authorised -- @bryancall do you approve to have @shukitchan's email there?

**Comment by shukitchan** [comment]
Submitted a PR and pinged @bryancall to leave a comment here when he is available.

**Comment by bryancall** [comment]
I approve @shukitchan to have access.

**Comment by DavidKorczynski** [comment]
Closed by https://github.com/google/oss-fuzz/pull/8961
