### ISSUE TITLE
[Question] Index for projects' public coverage reports?

### ISSUE THREAD

**Issue by QiuhaoLi** [google/oss-fuzz#8968]
In [FAQ](https://google.github.io/oss-fuzz/faq/#why-are-code-coverage-reports-public):

> Why are code coverage reports public?
> We work with open-source projects and try to keep as much information public as possible. **We believe that public code coverage reports** do not put users at risk, as they do not indicate the presence of bugs or lack thereof.

But I didn't find an entry for every project's coverage report, only get some direct links on storage.googleapis.com, for example [OpenSSL ](https://storage.googleapis.com/oss-fuzz-coverage/openssl/reports/20221031/linux/src/openssl/crypto/x509/x509_vfy.c.html).

Is there an index page for a  specific open-source project?

**Comment by oliverchang** [comment]
We do not have an index, but the links to the coverage reports should be pretty predictable if you are looking for a particular one. 

https://oss-fuzz-introspector.storage.googleapis.com/index.html may also be interesting to you. It has links to the Fuzz Introspector report, which also has links to coverage report.

**Comment by QiuhaoLi** [comment]
Thanks!🙌
