### ISSUE TITLE
Python coverage failing

### ISSUE THREAD

**Issue by nedbat** [google/oss-fuzz#8974]
This bug report is inscrutable to me: [Issue 53221: coveragepy: Coverage build failure](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53221).  

I've looked at the build log, and don't see what line indicates a failure. Can you help me decode it?

**Comment by DavidKorczynski** [comment]
It's a false positive and due to the infrastructure having an error. Many apologies!

@Navidem has this taken effect https://github.com/google/oss-fuzz/pull/8959 or is it because a new fix is needed?

**Comment by Navidem** [comment]
> This bug report is inscrutable to me: [Issue 53221: coveragepy: Coverage build failure](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53221).

Sorry for the false alarm.


> It's a false positive and due to the infrastructure having an error. Many apologies!
> 
> @Navidem has this taken effect #8959 or is it because a new fix is needed?

That's the fix, but looks like it is not in effect! Will check the deployment status.

**Comment by Navidem** [comment]
Update: it should be in effect now and the issue is resolved. It may take up to hour to reflect in oss-fuzz build logs.

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/19780488/201413510-755bcf14-d7f7-4321-b69d-0445b4fcaefd.png">
