### ISSUE TITLE
ffmpeg build is broken

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#899]
It appears that this bug is different from [issue 865](https://github.com/google/oss-fuzz/issues/865) that was causing the ffmpeg builds to fail.

This is the relevant part of the build output
```
Step #1: Step 15/21 : RUN svn co http://svn.xiph.org/trunk/ogg
Step #1:  ---> Running in 99a60560e88d
Step #1: Redirecting to URL 'https://svn.xiph.org/trunk/ogg':
Step #1: [91msvn: E170013: Unable to connect to a repository at URL 'https://svn.xiph.org/trunk/ogg'
Step #1: svn: E230001: Server SSL certificate verification failed: issuer is not trusted
Step #1: The command '/bin/sh -c svn co http://svn.xiph.org/trunk/ogg' returned a non-zero code: 1
Finished Step #1
ERROR
ERROR: build step "gcr.io/cloud-builders/docker@sha256:df0cfe8c883cd7757b61cbc9f29a63b99d85ff640b656b1235547f8bcb353c60" failed: exit status 1
```
The certificate for svn.xiph.org is issued by StartCom. 
Locally when I try the command svn co http://svn.xiph.org/trunk/ogg I get this error message:
```
Error validating server certificate for 'https://svn.xiph.org:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!
```
This seems related to Chrome's [recent removal of trust](https://groups.google.com/a/chromium.org/forum/#!topic/net-dev/FKXe-76GO8Y) from StartCom. 
The cert for https://xiph.org/ is issued by LetsEncrypt and appears trusted. Maybe the xiph folks need to be bugged into changing the cert used on svn.xiph.org?
I would check to see if there is a bug on the xiph.org bug tracker about this but I cannot reach https://trac.xiph.org/ because it also uses a StartCom cert :-(

**Comment by Dor1s** [comment]
//cc @michaelni Michael, do you know who can fix the cert issue for the svn repo? Can you ping them please?

**Comment by michaelni** [comment]
@Dor1s, i dont really know, but ive just sent monty a mail about this.

**Comment by Dor1s** [comment]
Thanks @michaelni !

**Comment by oliverchang** [comment]
I switched the ogg repo to use git instead, and now see this:

(https://oss-fuzz-build-logs.storage.googleapis.com/log-f695cc0f-54db-442f-b459-5b9131a84ed1.txt)

```
Step #3: + LD_LIBRARY_PATH=/src/ffmpeg_deps/lib/
Step #3: + ./autogen.sh --prefix=/src/ffmpeg_deps --enable-static --disable-examples
Step #3: Updating build configuration files, please wait....
Step #3: libtoolize: putting auxiliary files in '.'.
Step #3: libtoolize: linking file './ltmain.sh'
Step #3: libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
Step #3: libtoolize: linking file 'm4/libtool.m4'
Step #3: libtoolize: linking file 'm4/ltoptions.m4'
Step #3: libtoolize: linking file 'm4/ltsugar.m4'
Step #3: libtoolize: linking file 'm4/ltversion.m4'
Step #3: libtoolize: linking file 'm4/lt~obsolete.m4'
Step #3: configure.ac:56: installing './compile'
Step #3: configure.ac:9: installing './config.guess'
Step #3: configure.ac:9: installing './config.sub'
Step #3: configure.ac:12: installing './install-sh'
Step #3: configure.ac:12: installing './missing'
Step #3: doc/spec/Makefile.am: installing './depcomp'
Step #3: lib/Makefile.am:304: warning: '%'-style pattern rules are a GNU make extension
Step #3: parallel-tests: installing './test-driver'
Step #3: + make clean
Step #3: make: *** No rule to make target 'clean'.  Stop.
Finished Step #3
```

@michaelni could you please take a look?

**Comment by michaelni** [comment]
I first thought you talk about ogg but this failure is from theora. It seems there where changes in theoras build system. I can reproduce the issue locally and running configure before make clean fixes the make clean problem.
Also it may make sense if releases for dependancies would be used instead of tracking HEAD of every dep or that the build instructions for dependancies would be tracked outside projects. It seems to me that tracking how to build HEAD of every dep of every project in every project is not ideal, It inevitably duplicates the effort for each dep per project that uses the dep

**Comment by Dor1s** [comment]
Thanks @michaelni for taking a look. Let's see if https://github.com/google/oss-fuzz/commit/5d586c44da69fe36ae4b5868d6d74acaa96745b7 fixes that

**Comment by oliverchang** [comment]
--depth 1 doesn't seem to work with the ffmpeg repo... I'll remove that and try again.

```
Cloning into 'ffmpeg'...
fatal: The remote end hung up unexpectedly
fatal: protocol error: bad pack header
```

**Comment by Dor1s** [comment]
Yay, it works! Thanks!
