### ISSUE TITLE
real-time & dynamic coverage report

### ISSUE THREAD

**Issue by flyfish101** [google/oss-fuzz#9000]
Could we check the  coverage report of fuzz-introspector in real-time while the fuzzing is running?  So that we could identify the blockers and donot need to re-start fuzzing from scratch.

**Comment by DavidKorczynski** [comment]
I think this issue may fit better at https://github.com/ossf/fuzz-introspector/issues

In short, PRs on https://github.com/ossf/fuzz-introspector/issues are welcome to add real-time visualisations. It would be awesome to see this.

**Comment by flyfish101** [comment]
awesome!
