### ISSUE TITLE
Struggling to reproduce fuzzing failure in Teleport project

### ISSUE THREAD

**Issue by jentfoo** [google/oss-fuzz#9014]
Hello,

I am trying to reproduce a couple fuzzing failures for the `teleport` project.  However I am not having any luck reproducing them locally.  Looking at the first one only, I am trying to reproduce `testcase_id=5179131830075392`.  After building the fuzzers the `reproduce` output I get is:
```
mjensen@p16:~/code/oss/oss-fuzz$ python3 infra/helper.py reproduce teleport fuzz_mongo_read ~/clusterfuzz-testcase-minimized-fuzz_mongo_read-5179131830075392 
INFO:root:Running: docker run --rm --privileged --shm-size=2g --platform linux/amd64 -i -e HELPER=True -v /home/mjensen/code/oss/oss-fuzz/build/out/teleport:/out -v /home/mjensen/clusterfuzz-testcase-minimized-fuzz_mongo_read-5179131830075392:/testcase -t gcr.io/oss-fuzz-base/base-runner reproduce fuzz_mongo_read -runs=100.
+ FUZZER=fuzz_mongo_read
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ export SKIP_SEED_CORPUS=1
+ SKIP_SEED_CORPUS=1
+ run_fuzzer fuzz_mongo_read -runs=100 /testcase
/out/fuzz_mongo_read -rss_limit_mb=2560 -timeout=25 -runs=100 /testcase < /dev/null
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3123195053
INFO: Loaded 1 modules   (44873 inline 8-bit counters): 44873 [0x1996cd8, 0x19a1c21), 
INFO: Loaded 1 PC tables (44873 PCs): 44873 [0x10c000080000,0x10c00012f490), 
/out/fuzz_mongo_read: Running 1 inputs 100 time(s) each.
Running: /testcase
Executed /testcase in 16111 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
```

The failure is supposed to be a out of memory condition, however when I manually monitor the memory I don't see anything approaching the 2GB limit either.

Let me know what additional information I can provide.  I would appreciate any help you can give in trying to debug this issue.  Thank you!

**Comment by DavidKorczynski** [comment]
@AdamKorcz can you help here?

**Comment by AdamKorcz** [comment]
@jentfoo You are doing the right thing to reproduce. Is the issue marked as reproducible by OSS-Fuzz?

**Comment by jentfoo** [comment]
@AdamKorcz I don't see in the bug report anything indicating if it's reproducible or not.  I would expect that with a specific reproduction payload it would be.  The issue is not publicly disclosed yet, but if you have access, this is in reference to issue #50925.

Let me know how I can help, if you want to privately collaborate on this you can reach me at mike.jensen@goteleport.com.  Thank you!

**Comment by jentfoo** [comment]
Closing, it looks like the issue is now identified as fixed.   I will let you know if I run into future issues, thank you!
