### ISSUE TITLE
Priority of fuzzers

### ISSUE THREAD

**Issue by kroeckx** [google/oss-fuzz#9018]
In OpenSSL we've recently added a new fuzzer: punycode. The punycode parser was rewritten, and a fuzzer made for it. It's not a lot of code. So after 1 minute the fuzzer has actually found all coverage, and it seems like a waste of resources to run it as much as it does now. Is there a way to make it run less often?

**Comment by jonathanmetzman** [comment]
ClusterFuzz sort of does this on its own, fuzzers that don't find new coverage are given less runtime until they start finding new edges.

**Comment by jonathanmetzman** [comment]
Going to close this issue. Please reopen if further discussion is needed.
