### ISSUE TITLE
fuzzing with error unsafe.Slice requires go1.17 or later

### ISSUE THREAD

**Issue by vincentgoat** [google/oss-fuzz#9022]
We found errors that occurred recently.
vendor/golang.org/x/sys/unix/syscall.go:83:28: unsafe.Slice requires go1.17 or later (-lang was set to go1.16; check go.mod)

I wonder if there is an incompatibility problem.

More details:
https://github.com/kubeedge/kubeedge/actions/runs/3512265608/jobs/5883886196

cc @AdamKorcz

**Comment by AdamKorcz** [comment]
Few - if any - other OSS-Fuzz projects have 1.16 in their go.mod file. For projects that do, installing a newer Go version in the OSS-Fuzz build scripts is IMO the correct solution.

The fix to this issue should be in the documentation - That Go 1.16 is not fully supported.

**Comment by vincentgoat** [comment]
As for KubeEdge, we already have done as the documentation said. https://github.com/google/oss-fuzz/blob/master/projects/kubeedge/Dockerfile#L18

Do you mean other OSS-Fuzz projects will affect the Fuzz build of KubeEdge?

**Comment by vincentgoat** [comment]
I think upgrading the go version to v1.17 in Dockerfile but 1.16 still in `go.mod` can't solve this `unsafe.slice` issue.
FYI: https://github.com/golang/go/issues/46525#issuecomment-853319217

**Comment by AdamKorcz** [comment]
KubeEdges build will be fixed with https://github.com/google/oss-fuzz/pull/9067

**Comment by vincentgoat** [comment]
Thanks a ton!
