### ISSUE TITLE
fuzz-introspector warning says that LTO is not enabled

### ISSUE THREAD

**Issue by szhorvat** [google/oss-fuzz#9032]
I am looking at the fuzz-introspector reports for igraph, and I see this warning:

https://storage.googleapis.com/oss-fuzz-introspector/igraph/inspector-report/20220824/fuzz_report.html#functions_cov_hit_1

> Warning:
> The number of covered functions are larger than the number of reachable functions. This means that there are more functions covered at runtime than are extracted using static analysis. This is likely a result of the static analysis component failing to extract the right call graph or the coverage runtime being compiled with sanitizers in code that the static analysis has not analysed. This can happen if lto/gold is not used in all places that coverage instrumentation is used. 

Do we need to enable LTO explicitly (easy enough), or is this done automatically by OSS-fuzz?

**Comment by jonathanmetzman** [comment]
@DavidKorczynski @Navidem ?

**Comment by Navidem** [comment]
> Do we need to enable LTO explicitly (easy enough), or is this done automatically by OSS-fuzz?

Generally no, the lto flag is automatically added and I can see it is there for igraph: `-O0 -flto -fno-inline-functions -fuse-ld=gold`.

That warning can be result of multiple things, a common case is when the project has a lot of indirect calls then the call graph cannot track them statically. As a result, Introspector sees functions reported in coverage that has not a track for in the call graph.

**Comment by szhorvat** [comment]
@Navidem Is there anything we should try to do about this on the igraph side or just wait for the issue you linked to be resolved?

**Comment by Navidem** [comment]
> @Navidem Is there anything we should try to do about this on the igraph side or just wait for the issue you linked to be resolved?

Can you please confirm that igraph can be built with LTO and gold?

**Comment by szhorvat** [comment]
Looking carefully, the failure happens not when building igraph itself, but after building libxml2, a dependency. We build libxml2 to work around a crash in ICU, and to allow memory sanitizer to work.

I think now it works after this commit (going on a hunch):

https://github.com/igraph/igraph/commit/61e05160e042a1099fa8aec98ec07ad248455363

At least the following works when run locally:
```
python infra/helper.py build_fuzzers --sanitizer introspector --engine libfuzzer --architecture x86_64 igraph
```

**Comment by Navidem** [comment]
> At least the following works when run locally:

It is building successfully! Thanks for fixing it upstream!
https://storage.googleapis.com/oss-fuzz-introspector/igraph/inspector-report/20221130/fuzz_report.html

**Comment by szhorvat** [comment]
Frankly I don't even know what in that commit fixed it, but I'm happy it compiles ...

Regarding the warning I originally asked about, most instances of it are gone, but two still remains. From your comment above, @Navidem, it sounds like it's not something I need to be worried about, so I'll close this issue.

> That warning can be result of multiple things, a common case is when the project has a lot of indirect calls then the call graph cannot track them statically. As a result, Introspector sees functions reported in coverage that has not a track for in the call graph. Enhancing the call graph is on our todo list to cover such shortcomings.

However, if you can explain in a bit more detail what you mean by an "indirect call", that would be welcome. I am also wondering if we can retrieve the names of some of these functions which are covered, but can't be discovered using static analysis. 

igraph has a mechanism where it pushes some function pointers on a stack, then calls them from there. However, as far as I can see, all these are also called directly. It's just a way to ensure that destructors are called on error / early exit in a language like C that does not have built-in exceptions. So when an error does not occur, eventually a direct call will be made to the same destructor.

There are also a few instances of callback functions, i.e. a function pointer is passed to another function that calls it. But these are all used in a straightforward manner, so I assumed that static analysis should be able to discover them.

**Comment by Navidem** [comment]
Sorry for delay here :)

> However, if you can explain in a bit more detail what you mean by an "indirect call", that would be welcome.

From indirect call, I mean any call in the code that takes the callee's address from a variable (the call is resolved at runtime). So just by looking at the code one cannot say where this call is landing. Like this: `callq  *%rax`.

Fuzz Introspector call-graph collection cannot account for almost none of such cases, so if igraph is having such calls it is very probable that the call-graph is incomplete and reachability reports you get are inaccurate.

> igraph has a mechanism where it pushes some function pointers on a stack, then calls them from there. However, as far as I can see, all these are also called directly.

Do you mean you check the disassembly and see a direct call (like this: `callq  4061b0`)? Then it should be fine, as any function at say `4061b0` address will be identified as the callee in call-graph.

> There are also a few instances of callback functions, i.e. a function pointer is passed to another function that calls it. But these are all used in a straightforward manner, so I assumed that static analysis should be able to discover them.

Well, this needs data-flow to track propagation of that pointer assignment along with the function calls, which FuzzIntrospector does not do. So I assume those callbacks will be missed in call-graph.

> I am also wondering if we can retrieve the names of some of these functions which are covered, but can't be discovered using static analysis.

You can hack around on your local run of FuzzIntrospector, but we don't have an interface for using custom call-graph or something like that.
