### ISSUE TITLE
Put Google Analytics on Fuzz Introspector pages

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#9039]
David can you add an option for fuzz-introspector report generation to include an analytics code and JS snippet? This would help us track usage.

**Comment by DavidKorczynski** [comment]
Yep

**Comment by DavidKorczynski** [comment]
@AdamKorcz -- can you do this?

**Comment by AdamKorcz** [comment]
> @AdamKorcz -- can you do this?

Yes

**Comment by evverx** [comment]
> an option for fuzz-introspector report generation to include an analytics code and JS snippet?

I wonder if it would be possible to turn it off locally somehow (If it is supposed to be turned on by default when reports are generated)?

**Comment by DavidKorczynski** [comment]
> I wonder if it would be possible to turn it off locally somehow (If it is supposed to be turned on by default when reports are generated)?

Good point, @AdamKorcz let's do it so it's only on for oss-fuzz reports by controlling whether this feature is included with e.g. a command-line argument. In the OSS-Fuzz infra, we can then only pass this argument if a given environment variable is set, which will only be set for cloud builds. Basically, follow a similar pattern to how we do with code coverage urls: https://github.com/google/oss-fuzz/blob/4bcd9c97cc22d21272e2edc2c4109dbb0a52482b/infra/base-images/base-builder/compile#L241

**Comment by AdamKorcz** [comment]
GA needs a GA tracking ID anyways, and I thought we would assign that in OSS-Fuzz via an environment variable which would mean it would be off locally by default.

**Comment by Navidem** [comment]
> I wonder if it would be possible to turn it off locally somehow (If it is supposed to be turned on by default when reports are generated)?

+1

**Comment by Navidem** [comment]
> GA needs a GA tracking ID anyways, and I thought we would assign that in OSS-Fuzz via an environment variable which would mean it would be off locally by default.

Maybe do not even emit the script in the html if the env is not set?

**Comment by DavidKorczynski** [comment]
Support for this in fuzz introspector was added in https://github.com/ossf/fuzz-introspector/pull/671

Adding an environment variable `G_ANALYTICS_TAG` when running the introspector builds (in this condition https://github.com/google/oss-fuzz/blob/c0e4bb8d15a68b7f8cc731ea75523e48a2301bcf/infra/base-images/base-builder/compile#L209) with the relevant analytics tag, then it should work.
