### ISSUE TITLE
Jazzer sanitizers broken by latest update

### ISSUE THREAD

**Issue by fmeum** [google/oss-fuzz#9054]
The latest Jazzer update broke custom sanitizers shipped with Jazzer. Could someone revert https://github.com/google/oss-fuzz/commit/33c5ce4d6ff6595fbcab4b0a7a86a2f4c2925fb9?

_Originally posted by @fmeum in https://github.com/google/oss-fuzz/issues/9027#issuecomment-1325800998_

**Comment by Navidem** [comment]
https://github.com/google/oss-fuzz/pull/9055
