### ISSUE TITLE
Add branch coverage to the coverage summary

### ISSUE THREAD

**Issue by MarahGamdou** [google/oss-fuzz#9059]
Is it possible to add the branch coverage to the coverage summary (generated by oss-fuzz) since it is an important coverage metric ? I think this can be done by adding `$BRANCH_COV_ARGS` to [this line](https://github.com/google/oss-fuzz/blob/cfeba2ee8523971d30570dedf64df7e9d0ef3587/infra/base-images/base-runner/coverage#L235)  and gives valuable input to the developers.
@jonathanmetzman

**Comment by oliverchang** [comment]
@jonathanmetzman were you plannign on opening a PR with your referenced commit?

**Comment by jonathanmetzman** [comment]
I did. But since Marah was an intern and her internship ended, I think we can close this.
