### ISSUE TITLE
ubsan error in libcxx algorithm header (__independent_bits_engine)

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#906]
Trying to enable ubsan for the LibreOffice fuzzers I run into...

/usr/local/bin/../include/c++/v1/algorithm:2919:17: runtime error: shift exponent 32 is too large for 32-bit type 'std::__1::__independent_bits_engine<std::__1::mersenne_twister_engine<unsigned long, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>, unsigned int>::result_type' (aka 'unsigned int')

this has been fixed upstream in a more recent version of llvm's libcxx with...

https://reviews.llvm.org/rL313776

not sure when or how oss-fuzz would update to a version that includes that fix ?

**Comment by Dor1s** [comment]
I believe that we are using a newer revision. It should be at least r315377: https://github.com/google/oss-fuzz/blob/4862fdf384ebaf96e954e73b3eda16b382cf4cf9/infra/base-images/base-clang/checkout_build_install_llvm.sh#L29

**Comment by caolanm** [comment]
ubsan build enabled now
