### ISSUE TITLE
enable -fsanitize=unsigned-integer-overflow in non-faulting mode in ubsan build

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#910]
`-fsanitize=unsigned-integer-overflow` checks for unsigned overflow, which is *defined* behavior but often causes bugs. 
I'd like to try enabling `-fsanitize=unsigned-integer-overflow` in ubsan builds. 
By default, it will not cause the targets to crash on UIO, it will only print a message once, 
but will provide extra coverage signal that could be useful.

**Comment by Dor1s** [comment]
We are using `UBSAN_OPTIONS=halt_on_error=1` https://github.com/google/oss-fuzz/blob/fa41e6a94974a6f4607d8f8059c47a5f897590f5/infra/base-images/base-runner/Dockerfile#L29 UIO will not crash anyway?

**Comment by kcc** [comment]
Can you use `-fsanitize-trap=undefined` instead? 

This way we'll trap on regular ubsan errors and won't trap on UIO

**Comment by Dor1s** [comment]
Just tried doing that, got the following error:

```
clang-6.0: error: invalid argument '-fsanitize=vptr' not allowed with '-fsanitize-trap=undefined'
```

**Comment by kcc** [comment]
Ah. 
First, of course you need `-fno-sanitize-recover`, not `-fsanitize-trap=`.
Second, you need to match `-fsanitize=a,b,c` and `-fno-sanitize-recover=a,b,c`, and then add  `-fsanitize=unsigned-integer-overflow` w/o `-fno-sanitize-recover=`. 

Example: 
```
#include <limits.h>
#include <stdio.h>
int s  = INT_MIN;
unsigned u = 0;

int main() {
  u--;
  fprintf(stderr, "After UIO\n");
  s--;
  fprintf(stderr, "After SIO\n");
}
```

```
clang  two-overflows.cc -fsanitize=signed-integer-overflow,unsigned-integer-overflow -fno-sanitize-recover=signed-integer-overflow && UBSAN_OPTIONS=print_stacktrace=1 ./a.out ; echo $? 
two-overflows.cc:7:4: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned int'
    #0 0x41fd1d in main 
...

After UIO
two-overflows.cc:9:4: runtime error: signed integer overflow: -2147483648 - 1 cannot be represented in type 'int'
    #0 0x41fd84 in main ...
   
1

```

**Comment by Dor1s** [comment]
Thanks, that works:

```bash
$./zlib_uncompress_fuzzer 
<...>
#249843	REDUCE cov: 400 ft: 1434 corp: 229/8382b exec/s: 249843 rss: 31Mb L: 8/1835 MS: 1 EraseBytes-
/src/libfuzzer/FuzzerMutate.cpp:361:20: runtime error: unsigned integer overflow: 18446744073709551606 + 57 cannot be represented in type 'unsigned long'
/src/libfuzzer/FuzzerMutate.cpp:361:30: runtime error: unsigned integer overflow: 47 - 48 cannot be represented in type 'unsigned long'
#252224	REDUCE cov: 400 ft: 1434 corp: 229/8378b exec/s: 252224 rss: 31Mb L: 154/1835 MS: 2 CopyPart-EraseBytes-
<...>
```

**Comment by kcc** [comment]
BTW, will CF simply ignore all report signatures with `unsigned integer overflow`, or only those 
that lead to a crash? 

Asking because some project may want to enable UIO is crashing mode (like I did in llvm_libcxx)
where an un-annotated UIO is considered a bug.

**Comment by Dor1s** [comment]
It will simply ignore them as of now. Before that, it used to report them with `Integer-overflow` signature, not `Unsigned-integer-overflow`. I guess we'll have to change that. Do you want to have a separate crash type for UIO?

**Comment by kcc** [comment]
> Do you want to have a separate crash type for UIO?

Yes, would be lovely. It's generally not a bug, but some project may choose to treat them as bugs
(for good reasons)

**Comment by Dor1s** [comment]
Makes sense! Ok, we've added support for that, deploying new revision right now.

**Comment by Dor1s** [comment]
Should we consider doing the same trick in Chromium land?

**Comment by kcc** [comment]
I see bugs being open with Unsigned-integer-overflow where it is not enabled in failing mode.

**Comment by mkj** [comment]
This seems a bit noisy, eg https://oss-fuzz.com/v2/testcase-detail/5328094400348160 which is in a SHA1 routine (I assume perfectly valid)

Also https://oss-fuzz.com/v2/testcase-detail/5831846282657792 complaining about a negative array index in a debug allocator - that shouldn't be undefined behaviour? (Less certain about that though). It's referring to https://secure.ucc.asn.au/hg/dropbear/file/5b25d86b865b/dbmalloc.c#l70

**Comment by randombit** [comment]
Similarly https://oss-fuzz.com/v2/testcase-detail/5591424549519360 is for some modexp related code where unsigned overflow is intended.

**Comment by kcc** [comment]
Our apologies. This was not meant to report bugs. Looking.

**Comment by inferno-chromium** [comment]
ClusterFuzz does not make use of faulting mode, it just reads from stdout and if it finds "runtime error:", it will still report it. So, Max, you need to fix it differently, we can have some workaround when i am back, but till then feel free to revert to original behavior.

**Comment by inferno-chromium** [comment]
Reverted CL that enables unsigned integer overflow for now.

**Comment by Dor1s** [comment]
Thanks for noticing and for reverting.

> it just reads from stdout and if it finds "runtime error:"

We checked with Marty that we do not invoke stack_analyzer if the process finished with 0 return code, i.e. if there are UIO errors reported but we didn't crash, we don't report it.

It seems that the root issue is `halt_on_error=1` still present in `UBSAN_OPTIONS`. Most likely because we didn't rebuild base images until 14 hours ago, but I'll double-check.

**Comment by Dor1s** [comment]
Base images are not used for fuzzing on CF side, but there is one more piece of code that sets `halt_on_error=1`. Should be fixed now. I'll keep an eye on the logs to make sure we don't crash on UIO anymore (except of the project where we would like to). After that, we can re-land the CL reverted this morning.

**Comment by Dor1s** [comment]
Also kicked off progression task for all the incorrect reports, now they are marked as non-reproducible.

**Comment by kcc** [comment]
Let's hold this for now. My mistake -- we should have turned UIO into a proper no-output signal.
Let as make it on LLVM side first before another attempt.

**Comment by Dor1s** [comment]
I think we still need a way to suppress output from UIO, otherwise it just blows up our logs, even if we don't report such bugs.

**Comment by morehouse** [comment]
Added `UBSAN_OPTIONS=silence_unsigned_overflow=1` flag in https://reviews.llvm.org/D48660.

**Comment by Dor1s** [comment]
Noticed couple errors reported while testing locally, uploaded a followup change: https://reviews.llvm.org/D49324

```
../../third_party/libFuzzer/src/FuzzerMutate.cpp:403:13: runtime error: negation of 943208510 cannot be represented in type 'unsigned int'
    #0 0x292216 in unsigned long fuzzer::ChangeBinaryInteger<unsigned int>(unsigned char*, unsigned long, fuzzer::Random&) third_party/libFuzzer/src/FuzzerMutate.cpp:403:13
    #1 0x292f75 in fuzzer::MutationDispatcher::MutateImpl(unsigned char*, unsigned long, unsigned long, std::__1::vector<fuzzer::MutationDispatcher::Mutator, fuzzer::fuzzer_allocator<fuzzer::MutationDispatcher::Mutator> >&) third_party/libFuzzer/src/FuzzerMutate.cpp:518:22
    #2 0x2756cb in fuzzer::Fuzzer::MutateAndTestOne() third_party/libFuzzer/src/FuzzerLoop.cpp:650:18
    #3 0x2760f7 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) third_party/libFuzzer/src/FuzzerLoop.cpp:788:5
    #4 0x2625c3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) third_party/libFuzzer/src/FuzzerDriver.cpp:758:6
    #5 0x27e2aa in main third_party/libFuzzer/src/FuzzerMain.cpp:20:10
    #6 0x7f2091f352b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
....

../../third_party/libFuzzer/src/FuzzerMutate.cpp:403:13: runtime error: negation of 2893606913523066930 cannot be represented in type 'unsigned long'
    #0 0x292037 in unsigned long fuzzer::ChangeBinaryInteger<unsigned long>(unsigned char*, unsigned long, fuzzer::Random&) third_party/libFuzzer/src/FuzzerMutate.cpp:403:13
    #1 0x292f75 in fuzzer::MutationDispatcher::MutateImpl(unsigned char*, unsigned long, unsigned long, std::__1::vector<fuzzer::MutationDispatcher::Mutator, fuzzer::fuzzer_allocator<fuzzer::MutationDispatcher::Mutator> >&) third_party/libFuzzer/src/FuzzerMutate.cpp:518:22
    #2 0x2756cb in fuzzer::Fuzzer::MutateAndTestOne() third_party/libFuzzer/src/FuzzerLoop.cpp:650:18
    #3 0x2760f7 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) third_party/libFuzzer/src/FuzzerLoop.cpp:788:5
    #4 0x2625c3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) third_party/libFuzzer/src/FuzzerDriver.cpp:758:6
    #5 0x27e2aa in main third_party/libFuzzer/src/FuzzerMain.cpp:20:10
    #6 0x7f2091f352b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
...
```

**Comment by Dor1s** [comment]
I think this is done, though I'm not sure if we have any way to measure the effect. Any suggestions?
