### ISSUE TITLE
Fuzz-Introspector build of pcapplusplus

### ISSUE THREAD

**Issue by sashashura** [google/oss-fuzz#9112]
It looks like the pcapplusplus introspector build fails since April. However the fuzzing and coverage builds are green. Looking at https://oss-fuzz-build-logs.storage.googleapis.com/log-b1222686-3020-47d3-ab2d-99a8b4ef6486.txt It looks like a linking error:
```
Step #6 - "compile-libfuzzer-introspector-x86_64": pcap-linux.o: file not recognized: file format not recognized
Step #6 - "compile-libfuzzer-introspector-x86_64": clang-15: [0;1;31merror: [0m[1mlinker command failed with exit code 1 (use -v to see invocation)[0m
```
Any ideas what is wrong and how the build is different from the fuzzing build?

**Comment by DavidKorczynski** [comment]
If I remember correctly from trying to get this build working with fuzz-introspector in the past then the linker that's used is not actually the gold linker. Does pcapplusplus enforce use of specific linker?

**Comment by DavidKorczynski** [comment]
In the build, for this command:
```
clang  -shared -Wl,-soname,libpcap.so.$MAJOR_VER \

    -o libpcap.so.$VER pcap-linux.o fad-getad.o  pcap-usb-linux.o pcap-netfilter-linux.o  pcap.o gencode.o optimize.o nametoaddr.o etherent.o fmtutils.o pcap-util.o savefile.o sf-pcap.o sf-pcapng.o pcap-common.o pcap-options.o pcap-usb-linux-common.o bpf_image.o bpf_filter.o bpf_dump.o scanner.o grammar.o strlcat.o strlcpy.o
```

Can we get `-flto -fuse-ld=gold` in there? Otherwise, can we avoid building the shared .so library and just the static version?

**Comment by DavidKorczynski** [comment]
if I change this line:
https://github.com/google/oss-fuzz/blob/98e06456db89990b03e5bc1e1acb5d98be066037/projects/pcapplusplus/build.sh#L23

to 
`./configure --enable-shared=no`
Then fuzz-introspector works

**Comment by DavidKorczynski** [comment]
Fixed by https://github.com/google/oss-fuzz/pull/9115
