### ISSUE TITLE
minimization problem with clang-proto-fuzzer

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#916]
https://oss-fuzz.com/v2/testcase-detail/4629744193634304 has the original and minimized test cases.
The original test case works fine, the minimized one doesn't (it fails to parse as a proto). 

Do we have the minimization logs?
I'd like to try to understand why this happened... 
I'm running the minimizer locally, it seems to work fine.

**Comment by oliverchang** [comment]
Unfortunately we don't keep the minimization logs.

But this is strange, the testcase is still reproducible according to CF, and CF always tests with the minimized testcase if available..

**Comment by kcc** [comment]
Weird. I've rebuilt everything from scratch and the minimized reproducer works now as well. 
Sorry for false alarm.
