### ISSUE TITLE
Checkout Projects in build.sh

### ISSUE THREAD

**Issue by 0roman** [google/oss-fuzz#9198]
According to the documentation project sources should be checkout in the Dockerfile. Is this a requirement for anything? We would like to start checkout projects in the build.sh. That would give us the advantage to use the build.sh also locally in our development environment for fuzz targets.

**Comment by jonathanmetzman** [comment]
>According to the documentation project sources should be checkout in the Dockerfile. Is this a requirement for anything?

I think for CIFuzz/CFL it is a requirement.

>We would like to start checkout projects in the build.sh. That would give us the advantage to use the build.sh also locally in our development environment for fuzz targets.

build.sh will have access to a CIFUZZ env var that is set during CIFUZZ. You can check for the presence of this and overwrite the checkout if it is unset (or set some other env var locally to gate this).

**Comment by 0roman** [comment]
Thanks for the info, that would work for us.
