### ISSUE TITLE
Missing introspector reports

### ISSUE THREAD

**Issue by IvanNardi** [google/oss-fuzz#9209]
I noticed that in the `nDPI` project the introspector reports have not been available for a few days, even if the builds (as reported in https://oss-fuzz-build-logs.storage.googleapis.com/index.html) seems fine
Last report (11 December): https://storage.googleapis.com/oss-fuzz-introspector/ndpi/inspector-report/20221211/fuzz_report.html
Missing reports 12,13,14 December (example): https://storage.googleapis.com/oss-fuzz-introspector/ndpi/inspector-report/20221214/fuzz_report.html

Am I missing something obvious?

**Comment by DavidKorczynski** [comment]
Thanks a lot for reporting this!

I think all the introspector builds are failing, but they are being reported as passing:
```
Step #6 - "compile-libfuzzer-introspector-x86_64": ERROR:fuzz_introspector.analysis:branch-profiling: func name not in functions_profile LLVMFuzzerTestOneInput
Step #6 - "compile-libfuzzer-introspector-x86_64": Traceback (most recent call last):
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/main.py", line 142, in <module>
Step #6 - "compile-libfuzzer-introspector-x86_64":     main()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/main.py", line 123, in main
Step #6 - "compile-libfuzzer-introspector-x86_64":     return_code = commands.run_analysis_on_dir(
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/fuzz_introspector/commands.py", line 92, in run_analysis_on_dir
Step #6 - "compile-libfuzzer-introspector-x86_64":     analysis.overlay_calltree_with_coverage(
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/fuzz_introspector/analysis.py", line 408, in overlay_calltree_with_coverage
Step #6 - "compile-libfuzzer-introspector-x86_64":     profile.branch_blockers = detect_branch_level_blockers(proj_profile.all_functions, profile,
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/fuzz_introspector/analysis.py", line 529, in detect_branch_level_blockers
Step #6 - "compile-libfuzzer-introspector-x86_64":     llvm_branch.sides[blocked_idx].unique_not_covered_complexity)
Step #6 - "compile-libfuzzer-introspector-x86_64": IndexError: list index out of range
```
I'll dig into this now

**Comment by Navidem** [comment]
> I think all C/C++ projects for introspector builds are failing, but they are being reported as passing

Not all are failing, [bzip2](https://storage.googleapis.com/oss-fuzz-introspector/bzip2/inspector-report/20221214/fuzz_report.html) for example finishes and the report is current.

**Comment by DavidKorczynski** [comment]
> > I think all C/C++ projects for introspector builds are failing, but they are being reported as passing
> 
> Not all are failing, [bzip2](https://storage.googleapis.com/oss-fuzz-introspector/bzip2/inspector-report/20221214/fuzz_report.html) for example finishes and the report is current.

Yeah, I also found lz4 is working: https://storage.googleapis.com/oss-fuzz-introspector/lz4/inspector-report/20221214/fuzz_report.html

**Comment by oliverchang** [comment]
@Navidem please check if this is resolved tomorrow.

**Comment by Navidem** [comment]
> @Navidem please check if this is resolved tomorrow.

base-image builds were failing, as a result the updates were not picked up: https://github.com/google/oss-fuzz/pull/9208#issuecomment-1359856073

**Comment by Navidem** [comment]
The report is [here](https://storage.googleapis.com/oss-fuzz-introspector/ndpi/inspector-report/20221221/fuzz_report.html)! Thanks for filing the issue.

**Comment by IvanNardi** [comment]
> The report is [here](https://storage.googleapis.com/oss-fuzz-introspector/ndpi/inspector-report/20221221/fuzz_report.html)! Thanks for filing the issue.

Thanks to you guys for your work!
