### ISSUE TITLE
Unreproducible Golang crashes. Was Go updated to another version?

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#9228]
There are a few reports coming in where Golang gives the wrong result, but it's not reproducible:

https://oss-fuzz.com/testcase-detail/5922580295188480
https://oss-fuzz.com/testcase-detail/6329441657946112
https://oss-fuzz.com/testcase-detail/6099798866657280

This has never happened before. Cryptofuzz uses [install_go.sh](https://github.com/google/oss-fuzz/blob/3405bba3d8f1e805b290c40d2d1f491ccd145823/projects/cryptofuzz/Dockerfile#L21) to install Go. Was the Go version that the container uses recently updated? I'm trying to figure out what's causing this.

**Comment by DavidKorczynski** [comment]
@AdamKorcz Do you maybe have some ideas here?

**Comment by guidovranken** [comment]
No new Go crashes have come in. Must have been a bad server or something. Closing.
