### ISSUE TITLE
Integration of Zig targets

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#9229]
Will you accept projects written in the Zig programming language? I can arrange integration of some utility libraries (images, serialization etc) with full code coverage instrumentation. Zig usage is still kinda small but growing. Most of these libraries currently have 50-100 GH stars (questionable metric, I know).

**Comment by jonathanmetzman** [comment]
Will it require any changes on our end?

**Comment by guidovranken** [comment]
No. Under the hood Zig transpiles to C and uses its built-in clang binary to compile to binary, and all the instrumentation and sanitizer flags can be passed to it, including sanitizers. The built-in clang version might not be the same as the one provided by the OSS-Fuzz container, though. Coverage reports will not be as useful because they probably show the generated C code rather than the .zig files. MSAN might not work. But I suppose these are not deal breakers?

For starters I was thinking about libraries such as:

https://github.com/zigimg/zigimg
https://github.com/ducdetronquito/h11
https://github.com/chadwain/rem
https://github.com/travisstaloch/simdjzon
https://github.com/getty-zig/getty
https://github.com/getty-zig/json
https://github.com/ziglibs/s2s
https://github.com/zigtools/protobruh

Do these generally match your criteria wrt. popularity?

**Comment by guidovranken** [comment]
Actually MSAN seems to work.

**Comment by jonathanmetzman** [comment]
> Actually MSAN seems to work.

Wonder if it's going to find anything though.
In general, we haven't yet said we want zig projects even if unpopular so if you know that any of these are being used by a big/important user then well be happy to accept.

**Comment by guidovranken** [comment]
I think you can a lot of the same issues in Zig as you have in C, so MSAN might make sense.

> In general, we haven't yet said we want zig projects even if unpopular so if you know that any of these are being used by a big/important user then well be happy to accept.

I'm not sure I'm parsing this correctly. Do you say that if the Zig library I want to integrate is used by a big user then you'll accept, otherwise refuse?

**Comment by jonathanmetzman** [comment]
> I think you can a lot of the same issues in Zig as you have in C, so MSAN might make sense.
> 
> > In general, we haven't yet said we want zig projects even if unpopular so if you know that any of these are being used by a big/important user then well be happy to accept.
> 
> I'm not sure I'm parsing this correctly. Do you say that if the Zig library I want to integrate is used by a big user then you'll accept, otherwise refuse?

Basically.
I'm saying we'll definitely accept if it meets the same criteria, if not I don't think we will accept. @oliverchang WDYT?

**Comment by guidovranken** [comment]
Ok thanks.

Will you accept a project for Zig itself? It would comprise fuzzers for its standard library. https://github.com/ziglang/zig

There seems to be at least one big user: https://github.com/oven-sh/bun/

**Comment by jonathanmetzman** [comment]
It's a group decision but 37k stars seems like it would pass the committee.

**Comment by oliverchang** [comment]
Closing as I think there's nothing more actionable here for the OSS-Fuzz team.

**Comment by guidovranken** [comment]
Thank you.
