### ISSUE TITLE
Access to ntpsec

### ISSUE THREAD

**Issue by selsky** [google/oss-fuzz#9244]
I'm one of the maintainers of the NTPsec project. See https://www.ntpsec.org/core-team.html

With public access, I'm only able to review issues in the NTPsec project once they're public and I'm not able to view the underlying testcases. Eg, I'm able to view https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51558 now that it's public. However, I'm not able to view https://oss-fuzz.com/testcase?key=5652606961188864

Please add selsky@gmail.com to the vendor_ccs list in projects/ntpsec/project.yaml and also please add me as a CC on any existing NTPsec tickets.

@fallenpegasus @MarkAtwood @rlaager please confirm.

Thanks!

**Comment by rlaager** [comment]
Yes, please grant @selsky access.

**Comment by jonathanmetzman** [comment]
Done
