### ISSUE TITLE
[oss-fuzz-base] base-builder-go-codeintelligencetesting is failing to build

### ISSUE THREAD

**Issue by Navidem** [google/oss-fuzz#9251]
The failure started since Dec 18.

**Comment by Navidem** [comment]
It is preventing other images like base-clang to upgrade.

**Comment by DavidKorczynski** [comment]
Is it be because the base image is removed: https://github.com/google/oss-fuzz/pull/9230 ?

Can we just disable building this? It's not in use anymore

**Comment by Navidem** [comment]
The PR https://github.com/google/oss-fuzz/pull/9230 correctly is [removing image](https://github.com/google/oss-fuzz/commit/b7ee58b26c743f1e59e69e88dd1658e7450fda9b#diff-cf8eb7960e928beb9e206a5142d96ce07e2b2980b822dab4edf8ee466464e9fb) from the build, I believe the changes are not deployed correctly!

**Comment by Navidem** [comment]
deploying ... Will close this once the builds start to succeed.

cc @oliverchang

**Comment by jonathanmetzman** [comment]
Thanks Navid!

**Comment by Navidem** [comment]
This is resolved after deploy.
