### ISSUE TITLE
File names and directory names used by libfuzzer ?

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#926]
I wrote a new fuzzer that fuzzes application code which opens files depending on the input data (e.g. reading config files, writing logs etc). I 'overwrote' libc's fopen() and opendir() to just allow certain names. If I didn't do so, we'll see random files everywhere.

But it looks like running the fuzzers with `infra/helper.py run_fuzzer ...` fails due to files/dirs not being opened (e.g.: No such directory: /tmp/input; exiting).

Is there a certain naming scheme in libfuzzer that I could use to "fallback to normal behavior" instead of returning error ?

**Comment by oliverchang** [comment]
Could you please clarify the issue here and give a concrete example?

**Comment by rockdaboot** [comment]
I guess it is solved now.
FYI, the fuzzing input is taken as 'config file' where every command line option can be specified. There is also an option that takes a (wildcarded) filename to read more options from (recursive config files - what is pretty often seen in projects). We use the `glob()` function to resolve the wildcards, which in turn calls opendir/readdir/stat/closedir. To not let this function scan recursively (and uncontrolled) through the filesystem, I have to 'override' at least `opendir()` and return NULL on all 'unwanted' directories.
I think this is a standard problem for fuzzers (controlling network and filesystem access). So there must be some good examples or a documented way to handle it correctly. Maybe you even already have a framework/library to put such fuzzers into a controlled environment ?

**Comment by inferno-chromium** [comment]
Let us know if you need anything here, then can reopen
