### ISSUE TITLE
Automatic bug report spontaneously and wrongly closed

### ISSUE THREAD

**Issue by vadz** [google/oss-fuzz#928]
[This bug](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3828) was unexpectedly marked as fixed and then verified, so opening this bug report as requested in the message there because this bug was not fixed at all (I can still see it locally) and there were no commits touching this code in the indicated time frame.

**Comment by Dor1s** [comment]
Can be related to #910, I'll take a look.

**Comment by Dor1s** [comment]
Yes, the same input triggers `unsigned-integer-overflow` before triggering the original bug. If you run it with `UBSAN_OPTIONS=halt_on_error=1`, it will crash with UIO and will not reach the original error. Sorry about that, it should be fixed now, I'm double checking right now.

**Comment by Dor1s** [comment]
Looks good, ClusterFuzz now detected the real fix. Thanks for reporting the issue to us!
