### ISSUE TITLE
fuzz gstreamer

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#93]
https://twitter.com/scarybeasts/status/800838966878478336

https://twitter.com/hanno/status/801001207678599169

https://twitter.com/hanno/status/801020713788473344

**Comment by inferno-chromium** [comment]
@wtay @thomasvs - check out https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html. It will be great if you can help us integrate gstreamer fuzzing in OSS-Fuzz.

**Comment by Dor1s** [comment]
@bilboed ping from FOSDEM :)

**Comment by bilboed** [comment]
@Dor1s thanks for the chat this weekend !

My current plan is to build a static-only build of gst-discoverer (the gstreamer equivalent of mediainfo) which will enable testing of most of core gstreamer (core, filesrc, demuxers, parsers, decoders, convenience elements,...). I'll update this once I've got it built/running locally.

**Comment by kcc** [comment]
@bilboed, please remember that having many small fuzz targets is more efficient than having one huge.

**Comment by inferno-chromium** [comment]
tracked in https://github.com/google/oss-fuzz/issues/402

**Comment by Dor1s** [comment]
@bilboed, did you get a chance to work on the things we've previously discussed? :)

**Comment by bilboed** [comment]
I had spent some time back then trying to get the "small" static binary for ogg/vorbis/theora (as mentionned in comment from February 7th) which ended up being totally self-sufficient. I need to dig it back out again and make it run with oss-fuzz.... once I have more time :)
