### ISSUE TITLE
Worrying errors in cifuzz logs about non-reproducible crashes

### ISSUE THREAD

**Issue by randombit** [google/oss-fuzz#9318]
Hi OSS-Fuzz,

Not sure if this is a problem, but I'm not sure it's not either.

In CiFuzz log I see errors like so

```
2022-12-29 18:32:14,150 - root - INFO - Starting fuzzing
2022-12-29 18:33:14,164 - root - INFO - Fuzzer: ecc_p521. Detected bug.
/github/workspace/build-out/ecc_p521 -timeout=25 -rss_limit_mb=2560 -len_control=0 -seed=1337 -artifact_prefix=/tmp/tmp7smvirwf/ -max_total_time=50 -print_final_stats=1 /github/workspace/cifuzz-corpus/ecc_p521 >fuzz-0.log 2>&1
2022-12-29 18:33:14,165 - root - INFO - Trying to reproduce crash using: /tmp/tmp7smvirwf/tmpvl3636ki.
2022-12-29 18:34:58,339 - root - INFO - Reproduce command returned: 0. Not reproducible on /github/workspace/build-out/ecc_p521.
2022-12-29 18:34:58,339 - root - INFO - Crash is not reproducible.
```

Example job https://github.com/randombit/botan/actions/runs/3802299874/jobs/6467647584 from a PR change which should not affect the fuzzers in any way.

This is offputting because the way our fuzzers were written, if they ever fail it is almost certainly a bug, and if they are failing non-deterministically it means there is some memory corruption or use of unitialized data or other kind of UB :scream: 

These fuzzers are all fairly old, and I haven't see a new OSS-Fuzz report of any crashes in probably a year.

Is there some other reason (eg hardware flakes) that you would expect to see (several!) fuzzer runs fail in a non-reproducible way with every CiFuzz run? Is it somehow possible to get ahold of the artifacts that are triggering the failure and/or the fuzzer stdout? (typically before aborting we print useful information to stdout to aid debugging)

Thanks, and happy new year.

**Comment by evverx** [comment]
I think it's the same issue as https://github.com/google/oss-fuzz/issues/8768. Even though that issue was closed CIFuzz keeps failing there: https://github.com/SELinuxProject/selinux/actions/workflows/cifuzz.yml. My guess would be that CIFuzz can't stop fuzz targets properly for some reason.

**Comment by DavidKorczynski** [comment]
I think this might be the same as here https://github.com/google/oss-fuzz/pull/8985#issuecomment-1355740809 ? We're experiencing false positives in fuzz introspector and I think OSS-Fuzz too e.g. https://github.com/google/oss-fuzz/actions/runs/3796292178/jobs/6456248997

**Comment by evverx** [comment]
> I think this might be the same as here https://github.com/google/oss-fuzz/pull/8985#issuecomment-1355740809 ?

@DavidKorczynski  as far as I can see the fuzz targets timed out there with
```
2022-12-15 10:43:12,854 - root - ERROR - Reproducing timed out..
```
when CFLite tried to reproduce the issue it found. I think it was an actual timeout (unlike this issue where CIFuzz can't reproduce anything).

**Comment by evverx** [comment]
Having taken a closer look it isn't clear why CFLite tried to reproduce anything there since the exit code appears to have been 0 but I think `ERROR - Reproducing timed out..` probably indicates that that's a separate issue. It can be related to this issue though but I'm not sure.

**Comment by jonathanmetzman** [comment]
> Having taken a closer look it isn't clear why CFLite tried to reproduce anything there since the exit code appears to have been 0 but I think `ERROR - Reproducing timed out..` probably indicates that that's a separate issue. It can be related to this issue though but I'm not sure.

Side note, why is every CIFuzz run failing for SELinux?

**Comment by jonathanmetzman** [comment]
Trying to repro this: https://github.com/jonathanmetzman/botan/actions/runs/3831692410/jobs/6521116685

**Comment by jonathanmetzman** [comment]
Trying to repro here: https://github.com/jonathanmetzman/selinux/actions/runs/3832285868/jobs/6522418536

**Comment by jonathanmetzman** [comment]
> Trying to repro here: https://github.com/jonathanmetzman/selinux/actions/runs/3832285868/jobs/6522418536

Assuming this is correct, @oliverchang we need a way to tell if the process was terminated by clusterfuzz.
I think the right way to do this would be to plumb through timed_out into FuzzResult.

**Comment by evverx** [comment]
Looks like CIFuzz is flaky now in the sense that it seems from time to time it reports crashes reproducible with the latest builds: https://github.com/systemd/systemd/pull/25842#issuecomment-1383524668.

**Comment by oliverchang** [comment]
@jonathanmetzman please follow up on this when you are back.

**Comment by jonathanmetzman** [comment]
On it!

**Comment by jonathanmetzman** [comment]
I think this fixed landed. Can anyone say whether they still see the issue?

**Comment by cgzones** [comment]
Seems fixed (https://github.com/SELinuxProject/selinux/actions/runs/4027356294).

Thanks!

**Comment by jonathanmetzman** [comment]
I think it didn't happen again in David's test. Thanks david.

**Comment by DavidKorczynski** [comment]
> I think it didn't happen again in David's test. Thanks david.

That's true, also, the logging also shows
```
2023-01-27 18:45:26,885 - root - INFO - Not reporting crash in test_fuzz_report_generation because process timed out.
```
so it's due to the fix! Thanks for the fix.

**Comment by evverx** [comment]
Thanks! I think https://github.com/google/oss-fuzz/issues/8768 can probably be closed as well given that @cgzones confirmed that CIFuzz no longer fails there.

**Comment by randombit** [comment]
Just checked, everything looks good here as well. Thanks!

**Comment by sobomax** [comment]
Well this broke crash reporting when detect_leaks=0. In such case the result.timed_out is true.

**Comment by jonathanmetzman** [comment]
> Well this broke crash reporting when detect_leaks=0. In such case the result.timed_out is true, still there might be a crash to report.

Sorry can you share an example of this?
Is this consistently a problem or just a race? Also, do you know why detect_leaks affects this? It's not obvious to me.

**Comment by sobomax** [comment]
> > Well this broke crash reporting when detect_leaks=0. In such case the result.timed_out is true, still there might be a crash to report.
> 
> Sorry can you share an example of this? Is this consistently a problem or just a race? Also, do you know why detect_leaks affects this? It's not obvious to me.

Well, basically detect_leaks means that the leak detection will be performed when the fuzzing times out. As such after this change results of such analysis are ignored and the fuzzer behaves as if there is no leak. I have made a quick and dirty fix here:

https://github.com/sobomax/oss-fuzz/commit/94d68fd652305c74402b0eae887326ec94bbb7b9

Here is the example of affected run:

```
INFO:GLOBAL:ehandler:221: rtpproxy ended
==155==LeakSanitizer: checking for leaks
=================================================================
==155==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x55ff8ff1619e in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
    #1 0x55ff9046235b in rtpp_rzmalloc /src/rtpproxy/src/rtpp_mallocs.c:85:12
    #2 0x55ff9048a762 in rtpp_socket_ctor /src/rtpproxy/src/rtpp_socket.c:115:11
    #3 0x55ff904899c5 in create_twinlistener /src/rtpproxy/src/rtpp_command.c:122:17
    #4 0x55ff90511de4 in rtpp_ptbl_get_port /src/rtpproxy/src/rtpp_port_table.c:132:16
    #5 0x55ff90489078 in rtpp_create_listener /src/rtpproxy/src/rtpp_command.c:182:13
    #6 0x55ff9054aced in rtpp_command_ul_handle /src/rtpproxy/src/../src/commands/rpcpv1_ul.c:461:17
    #7 0x55ff90560a91 in handle_command /src/rtpproxy/src/rtpp_command.c:718:2
    #8 0x55ff905739df in ExecuteRTPPCommand /src/rtpproxy/scripts/fuzz/fuzz_rtpp_utils.h:135:16
    #9 0x55ff905739df in LLVMFuzzerInitialize /src/rtpproxy/scripts/fuzz/fuzz_rtp_session.c:51:13
    #10 0x55ff8fdf4fd3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:650:5
    #11 0x55ff8fe24032 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #12 0x7faeafaa6082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 0702430aef5fa3dda43986563e9ffcc47efbd75e)

DEDUP_TOKEN: __interceptor_malloc--rtpp_rzmalloc--rtpp_socket_ctor
SUMMARY: AddressSanitizer: 88 byte(s) leaked in 1 allocation(s).
MS: 1 EraseBytes-; base unit: a6777abb2434d048764080ae3fe6281aadc21116


artifact_prefix='/tmp/tmppbjfjjd6/'; Test unit written to /tmp/tmppbjfjjd6/crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64: 
stat::number_of_executed_units: 2523828
stat::average_exec_per_sec:     8384
stat::new_units_added:          3361
stat::slowest_unit_time_sec:    0
stat::peak_rss_mb:              94
/github/workspace/build-out/fuzz_rtp_session -detect_leaks=0 -max_len=8192 -print_final_stats=1 -use_value_profile=1 -timeout=25 -rss_limit_mb=2560 -dict=/github/workspace/build-out/fuzz_rtp_session.dict -len_control=0 -seed=1337 -artifact_prefix=/tmp/tmppbjfjjd6/ -max_total_time=300 -print_final_stats=1 /github/workspace/cifuzz-corpus/fuzz_rtp_session >fuzz-3.log 2>&1
2024-08-18 03:49:53,651 - urllib3.connectionpool - DEBUG - [https://storage.googleapis.com:443](https://storage.googleapis.com/) "GET /rtpproxy-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/rtpproxy_fuzz_rtcp_parser/public.zip HTTP/1.1" 200 701539
2024-08-18 03:49:53,778 - root - INFO - Starting fuzzing
2024-08-18 03:55:03,801 - root - INFO - Not reporting crash in fuzz_rtcp_parser because process timed out.
2024-08-18 03:55:03,801 - root - INFO - Deleting corpus and seed corpus of fuzz_rtcp_parser to save disk.
Fuzzing logs:
==224==Registered root region at 0x7f74107007a0 of size 32
2024-08-18 03:55:03,823 - root - INFO - Deleting fuzz target: fuzz_rtcp_parser.
2024-08-18 03:55:03,823 - root - INFO - Done deleting.
```

As you can see the leak is ignored with the message "Not reporting crash in fuzz_rtcp_parser because process timed out.". After applying my patch I see it try to reproduce the bug as expected:

```
==68==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 176 byte(s) in 2 object(s) allocated from:
    #0 0x5607fcb6919e in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
    #1 0x5607fd0b535b in rtpp_rzmalloc /src/rtpproxy/src/rtpp_mallocs.c:85:12
    #2 0x5607fd0dcf42 in rtpp_socket_ctor /src/rtpproxy/src/rtpp_socket.c:115:11
    #3 0x5607fd0dc1a5 in create_twinlistener /src/rtpproxy/src/rtpp_command.c:122:17
    #4 0x5607fd1645f4 in rtpp_ptbl_get_port /src/rtpproxy/src/rtpp_port_table.c:132:16
    #5 0x5607fd0db858 in rtpp_create_listener /src/rtpproxy/src/rtpp_command.c:182:13
    #6 0x5607fd19fc1e in rtpp_command_ul_handle /src/rtpproxy/src/../src/commands/rpcpv1_ul.c:534:13
    #7 0x5607fd1b32f1 in handle_command /src/rtpproxy/src/rtpp_command.c:718:2
    #8 0x5607fd1c4f7d in ExecuteRTPPCommand /src/rtpproxy/scripts/fuzz/fuzz_rtpp_utils.h:135:16
    #9 0x5607fd1c4f7d in LLVMFuzzerTestOneInput /src/rtpproxy/scripts/fuzz/fuzz_command_parser.c:15:5
    #10 0x5607fca5aa10 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:614:13
    #11 0x5607fca5a235 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:516:7
    #12 0x5607fca5ba05 in fuzzer::Fuzzer::MutateAndTestOne() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:760:19
    #13 0x5607fca5c7f5 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile>>&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:905:5
    #14 0x5607fca49eb6 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:914:6
    #15 0x5607fca77032 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #16 0x7fa708fa4082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 0702430aef5fa3dda43986563e9ffcc47efbd75e)

DEDUP_TOKEN: __interceptor_malloc--rtpp_rzmalloc--rtpp_socket_ctor
SUMMARY: AddressSanitizer: 176 byte(s) leaked in 2 allocation(s).
MS: 5 ChangeBit-ChangeByte-EraseBytes-InsertRepeatedBytes-EraseBytes-; base unit: c51fb7f4e5f1daa57755dc2334f35bea63941976


artifact_prefix='/tmp/tmp95a_oj4v/'; Test unit written to /tmp/tmp95a_oj4v/crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64: 
stat::number_of_executed_units: 193037
stat::average_exec_per_sec:     641
stat::new_units_added:          823
stat::slowest_unit_time_sec:    0
stat::peak_rss_mb:              113
/github/workspace/build-out/fuzz_command_parser -detect_leaks=0 -max_len=8192 -print_final_stats=1 -use_value_profile=1 -timeout=25 -rss_limit_mb=2560 -dict=/github/workspace/build-out/fuzz_command_parser.dict -len_control=0 -seed=1337 -artifact_prefix=/tmp/tmp95a_oj4v/ -max_total_time=300 -print_final_stats=1 /github/workspace/cifuzz-corpus/fuzz_command_parser >fuzz-3.log 2>&1
2024-08-21 03:06:11,646 - root - INFO - Fuzzer: fuzz_command_parser. Detected bug.
2024-08-21 03:06:11,653 - root - INFO - Trying to reproduce crash using: /tmp/tmp95a_oj4v/crash-da39a3ee5e6b4b0d3255bfef95601890afd80709.
2024-08-21 03:06:42,026 - root - INFO - Reproduce command returned: 0. Not reproducible on /github/workspace/build-out/fuzz_command_parser.
2024-08-21 03:06:42,026 - root - INFO - Crash is not reproducible.
2024-08-21 03:06:42,026 - root - INFO - SAVING CRASH
2024-08-21 03:06:42,027 - root - INFO - NOT MINIMIZED
```

Thanks for looking into it!
