### ISSUE TITLE
LTO/LLD?

### ISSUE THREAD

**Issue by LebedevRI** [google/oss-fuzz#933]
Hi.
I'd like to enable LTO for [RawSpeed](https://github.com/google/oss-fuzz/blob/master/projects/librawspeed/project.yaml#L2).

My unscientific non-bechmarking benchmarks show that
with LTO, decoding time of the [RPU sample set](https://raw.pixls.us/) is 30% less.
So it should at least not hurt the fuzzing.

However, there does not seem to be LLD in the base image, which is plausible looking at https://github.com/google/oss-fuzz/blob/5e8a4079238993dadabe2a15ee3ba12d19f25052/infra/base-images/base-clang/checkout_build_install_llvm.sh

Question:
1. Should i *NOT* use LTO for fuzzing?
2. If i should, should i *NOT* prefer to use LLD?
3. If i should, should i provide a patch to build&install LLD too?

**Comment by oliverchang** [comment]
As far as I can tell, lld/lto has no downsides when it comes to fuzzing. 

We experimented with lld in the past (#295) and it broke some things (IIUC which should now be fixed). 

If we want to revisit this, I think we can add a flag to project.yaml to enable this on a per-project basis for now. @kcc @Dor1s  what do you think?

**Comment by kcc** [comment]
Don't do this w/o extensive testing. We don't usually run asan+lto, and we've heard reports that those are not 100% compatible with each other.

**Comment by LebedevRI** [comment]
>If we want to revisit this, I think we can add a flag to project.yaml to enable this on a per-project basis for now.

In *my* case it is already handled by the project's cmakelists.txt, so the only thing missing is the LLD, thus the question is *mostly* about the missing(?) LLD in the base images.

> Don't do this w/o extensive testing.

Yeah, did not do that yet. It is obvious to me how to check that asan/ubsan will still be functional, but not obvious how to do extensive testing.

**Comment by Dor1s** [comment]
I think RawSpeed might be a good polygon for testing, since @LebedevRI is enthusiastic about that :)

**Comment by pcc** [comment]
When we tried to enable lld by default in Chromium for Linux we started getting false positives from msan, e.g.
https://bugs.chromium.org/p/chromium/issues/detail?id=776355
so we had to switch back to using gold with msan for now.

It would probably be worth investigating that before trying to switch to lld again.

**Comment by LebedevRI** [comment]
From `#llvm`:
```
[21:10:50] <eugenis> LebedevRI: look at test/asan/CMakeLists.txt, add a copy of
existing lit test configurations with -lto; also look at test/cfi/CMakeLists.txt for
inspiration (you'd need to check that lto is actually supported in the toolchain)
```
So *what* needs to be done is clear, until the bugs are hit anyway :)

**Comment by kcc** [comment]
This tracker is probably not the best place for llvm upstream discussion. 
BTW, I am still not certain what exactly do you want and why.

**Comment by LebedevRI** [comment]
As the previous comments in this issue explain, i would like to be able to use sanitizers/fuzzing with LTO/LLD, be it either during normal local development, or in oss-fuzz.
As you have pointed out, this requires enhancing compiler-rt test coverage with LTO/LLD, which is what i'm doing ([ubsan](https://reviews.llvm.org/D39508), [msan](https://reviews.llvm.org/D40768)).
So the current question is, what else other than asan/ubsan/msan sanitizers needs these LTO/LLD tests?

> This tracker is probably not the best place for llvm upstream discussion.

Any particular place where i should move this disscussion? cfe-dev? google/sanitizers?

**Comment by kcc** [comment]
> LTO/LLD, be it either during normal local development, or in oss-fuzz.

Local development -- fine, that may speed things up for you. 
oss-fuzz -- I am not convinced yet. 
Even if this speeds up fuzzing, we are unlikely to switch other projects to LTO any time soon, 
so the benefit will be localized. And we will have to pay the maintenance cost. 

Also, remember, there is a risk that LTO will bring more aggressive inlining and other optimizations,
and historically those were known to hide bugs from sanitizers. 

OTOH, aggressive inlining sometimes improves the coverage signal, which is good. 

> Any particular place where i should move this disscussion? 

llvm-dev, I think.

**Comment by inferno-chromium** [comment]
Closing based on last comment.
