### ISSUE TITLE
abort() not detected/handled ?

### ISSUE THREAD

**Issue by bilboed** [google/oss-fuzz#935]
In various places in GStreamer we have critical situation detection (i.e. detection of completely wrong usage/behaviour of the API). While they don't abort the program by default, they actually help in figuring out the root issues of wrong API usage (by both apps and plugins).

I have added code in the current fuzzer `g_setenv ("G_DEBUG", "fatal-criticals", TRUE);`to cause the underlying glib system to call `abort()` when such critical paths are reached ... but it doesn't seem to cause the fuzzers to stop.

Are those abort interrupted/handled by the sanitizers ?

Example output can be seen in https://oss-fuzz.com/v2/testcase-detail/4743394732539904 where these lines should have caused a call to abort:
  `** (gst-discoverer:3): CRITICAL **: gst_pad_set_caps: assertion 'caps != NULL && gst_caps_is_fixed (caps)' failed`

**Comment by kcc** [comment]
If `abort()` happens libFuzzer will treat it as any other bug.
The log clearly indicates the the abort didn't happen. 
You can check why using the crashy input locally.

**Comment by Dor1s** [comment]
Also note that we use Release build, if it matters.

**Comment by bilboed** [comment]
My bad. I just retried with a minimalist test-case and those env variable get read at library load. Will figure out another way to make it raise abort().

**Comment by inferno-chromium** [comment]
I am fixing the stack parsing, so it will account for assertion condition parsing as well.
Fixing this as part of https://github.com/google/oss-fuzz/issues/944
