### ISSUE TITLE
No access to testcase details

### ISSUE THREAD

**Issue by bilboed** [google/oss-fuzz#936]
For some testcases (mostly leaks), we don't have access to the testcase details.

One such example (for gstreamer) is https://oss-fuzz.com/v2/testcase-detail/4674256493346816

**Comment by kcc** [comment]
What does the web site tell you? 
Are you logged-in into your google account? (the one that is mentioned in `project.yaml`)

**Comment by Dor1s** [comment]
Hm, that link doesn't seem to be related to gstreamer... Where did you get it from?

**Comment by bilboed** [comment]
@Dor1s : I got it from https://oss-fuzz.com/v2/crash-stats

@kcc: It gives me : "You (email=bilboed@bilboed.com) are not authorized to access this page!". And yes I'm logged in (otherwise I wouldn't be able to see the other testcases)

**Comment by Dor1s** [comment]
The error looks correct to me, as the testcase being linked is not related to gstreamer, but why does it show up on crash-stats page for you... I'll take a closer look.

**Comment by bilboed** [comment]
I *think* I know why it's getting confused. It's a leak with a backtrace depth of 1. I figured out how to solve that : rebuild glib with same sanitizer flags.

**Comment by Dor1s** [comment]
Right, that's the reason!

@inferno-chromium, should we try not to show such testcases on the crash stats in order to avoid confusion?

**Comment by inferno-chromium** [comment]
Looks fixed, i see frames beyond g_malloc now.
