### ISSUE TITLE
u-root: Reported reproducible bugs by CIFuzz not reproducible locally

### ISSUE THREAD

**Issue by RiSKeD** [google/oss-fuzz#9381]
Multiple CIFuzz runs on u-root have been failing due to a reproducible bug found in the process (see [PR-1](https://github.com/u-root/u-root/actions/runs/3816068564/jobs/6491464476) or [PR-2](https://github.com/u-root/u-root/actions/runs/3859556655/jobs/6579199879)).
I have tried to reproduce these bugs locally using the provided artifacts but encountered no failures each time.
Furthermore, none of these crashes ever occurred in OSS-Fuzz itself even after multiple weeks. 
Is there any way to get a better understanding of these crashes and their cause?

I was also under the impression that CIFuzz only runs the fuzzing tests which have been affected by some code changes inside the specific PR. What are the necessary changes to get this enabled for u-root?

**Comment by DavidKorczynski** [comment]
I think this might be the same as described in the second half of this comment https://github.com/google/oss-fuzz/pull/8985#issuecomment-1355740809 -- I wonder if it's related to https://github.com/google/oss-fuzz/issues/9318

**Comment by jonathanmetzman** [comment]
Can you see if this is still happening?

**Comment by RiSKeD** [comment]
Seems to be more stable now, will close this issue.
