### ISSUE TITLE
False positive with msan and strlen()?

### ISSUE THREAD

**Issue by nmathewson** [google/oss-fuzz#940]
Hi!  I think this may be a false positive:
  https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3970#c2
As I read the code, it's failing when it takes the strlen() of a buffer.  But the buffer's contents are nul-terminated, as guaranteed by the tor_snprintf() call that constructed it.  Is it possible that msan's  strlen()-replacement code is not getting used here for some reason?

**Comment by Dor1s** [comment]
Valgrind doesn't complain... I'm starring at the code now.

**Comment by Dor1s** [comment]
Yes, the buffer does seem to be initialized, as it has the error message inside. Looks like we are missing instrumentation for `vsnprintf`.

**Comment by Dor1s** [comment]
I guess we either have to wait until https://github.com/google/oss-fuzz/issues/608 is resolved, or can try adding an interceptor for `vsnprintf` to https://github.com/llvm-mirror/compiler-rt/blob/master/lib/msan/msan_interceptors.cc

**Comment by Dor1s** [comment]
Wait, there is an interceptor for `vsnprintf`: https://github.com/llvm-mirror/compiler-rt/blob/master/lib/sanitizer_common/sanitizer_common_interceptors.inc#L1470

**Comment by Dor1s** [comment]
Existing build calls `vsnprintf_chk` isntead of `vsnprintf`. Thanks @kcc for the hint on disabling fortify source. Now it seems to work properly after https://github.com/google/oss-fuzz/commit/a66795291a6b25e810cafd3fdd67164676012674

**Comment by Dor1s** [comment]
@nmathewson, thanks for the report! I can imagine that some other reports can be false positives too. We can wait up to one day to see what gets "fixed" after disabling the fortify source.

**Comment by nmathewson** [comment]
Thanks for the amazingly fast response, @Dor1s !  If I understand you correctly, I should look again this time tomorrow to see which bugs have gone away in the meantime, and then focus my attention on whatever remains.  If so, that's my plan.

**Comment by nmathewson** [comment]
Okay. The following tickets all closed overnight.  We didn't change anything in Tor that would have fixed them, so they are probably false positives due to this msan/FORTIFY_SOURCE issue:

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3964
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3967
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3970
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3973

They are currently closed as "verified"; if that is incorrect, I can open another ticket if needed?

**Comment by Dor1s** [comment]
Yes! Thanks for checking!
