### ISSUE TITLE
Centipede support on a small project

### ISSUE THREAD

**Issue by IvanNardi** [google/oss-fuzz#9415]
According to the main page of centipede, on github
```
Early work-in-progress. We test centipede within a small team on a couple of targets. Unless you are part of the Centipede project, or want to help us, you probably don't want to read further just yet.
``` 
Does this advice still stand, even after libfuzzer has been declared EOL? Or should a project support this new fuzz engine, like the other ones?

Bottom line: do you recommend to support/configure centipede even on a "small/normal" project (already present in oss-fuzz)?

**Comment by jonathanmetzman** [comment]
CC @Alan32Liu 

> According to the main page of centipede, on github
> 
> ```
> Early work-in-progress. We test centipede within a small team on a couple of targets. Unless you are part of the Centipede project, or want to help us, you probably don't want to read further just yet.
> ```
> 
> Does this advice still stand, even after libfuzzer has been declared EOL? Or should a project support this new fuzz engine, like the other ones?

Not really. As far as OSS-Fuzz is concerned, centipede will eventually become our main fuzzer. So for a head start I recommend supporting centipede as soon as is convenient.

> 
> Bottom line: do you recommend to support/configure centipede even on a "small/normal" project (already present in oss-fuzz)?

**Comment by jonathanmetzman** [comment]
I'm gonna close this issue as I don't think there's more discussion required here, but please reopen if I'm wrong. thanks for the question, it is a good one.
