### ISSUE TITLE
"No space left on device" on bots running ffmpeg fuzzers

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#942]
Downside of having working ffmpeg build :)

**Comment by Dor1s** [comment]
@oliverchang, I guess we cannot do anything other than trying to reduce the build size?

**Comment by oliverchang** [comment]
I think this is happening on our hosts, so we will need to increase disk size there by a little.

**Comment by Dor1s** [comment]
As per offline discussion, that might be JS fuzzer, not ffmpeg. Doesn't seem to happen anymore, will re-open if it comes back. Thanks Oliver!
