### ISSUE TITLE
Projects using meson fail to compile with centipede

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#9431]
From https://github.com/google/oss-fuzz/pull/9427#issuecomment-1383709595

Before I forget other projects using meson like dbus-broker fail to build with centipede too. I think if by analogy with COVERAGE_FLAGS_coverage OSS-Fuzz prepended -Wl to linker options it would make centipede work with meson as well because https://github.com/mesonbuild/meson/issues/4542 was fixed by filtering out external linker flags passed via CFLAGS starting with -Wl. I'm not sure meson is going to start filtering out anything else.

**Comment by jonathanmetzman** [comment]
I think this works now as systemd is now using centipede.

**Comment by evverx** [comment]
Nice. Thanks! As far as I can see `dbus-broker` and `lxc` no longer fail to compile with `centipeded`. `lxc` seems to fail down the line though but to judge from https://github.com/google/oss-fuzz/pull/9300#issuecomment-1421370891 it's a known issue.
