### ISSUE TITLE
Specify depth for identical testcase detection

### ISSUE THREAD

**Issue by bilboed** [google/oss-fuzz#944]
With the various gstreamer targets, we have setup a custom message handler to raise abort() on critical messages (which are essentially codepaths that shouldn't be reached).

The problem is that we end up with stack traces like this:
#0 0x7f15a7835427 in gsignal /build/glibc-9tT8Do/glibc-2.23/sysdeps/unix/sysv/linux/raise.c:54
#1 0x7f15a7837029 in abort /build/glibc-9tT8Do/glibc-2.23/stdlib/abort.c:89
#2 0x42fa49 in custom_logger /src/gst-ci/fuzzing/gst-discoverer.c:79:5
#3 0x7264cc in g_logv /work/glib-2.54.2/glib/gmessages.c:1341:11
#4 0x726117 in g_log /work/glib-2.54.2/glib/gmessages.c:1403:3
#5 0x5a0a50 in **What actually triggered the critical**
...

It seems only the 3 functions before abort() are the ones being used to detect identical issues (which will always be the same), whereas we would want to add at least a function or two before that to detect similarities.

Is there a way to customize the depth for similar testcase detection ?

**Comment by inferno-chromium** [comment]
We need to ignore the glib stack frames, then it should work. we already ignore the glibc ones.

**Comment by inferno-chromium** [comment]
Fixed now, some old testcases like https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4024 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4021 might get closed, but will be reopened later with new signature.
