### ISSUE TITLE
Empty performance report ?

### ISSUE THREAD

**Issue by bilboed** [google/oss-fuzz#954]
When trying to view performance reports, I only get a page showing:

> Fuzzer Performance Report: libFuzzer on libfuzzer_asan_gstreamer
> 1118 runs (28 days, 20:33:32 of CPU time) on 2017-11-04
> b.split is not a function×

Is there anything we're missing on our side or is this an issue on the server side ?

ex: https://oss-fuzz.com/v2/performance-report/libFuzzer/libfuzzer_asan_gstreamer/2017-11-04

**Comment by inferno-chromium** [comment]
Might be a Polymer V2+firefox issue, can you try opening that link in Chrome.

**Comment by inferno-chromium** [comment]
Would probably need a similar fix as https://github.com/google/oss-fuzz/issues/849#event-1272476010 (that was on fuzzer-stats page).

**Comment by inferno-chromium** [comment]
Should be fixed now for Firefox, please give it a try.

**Comment by bilboed** [comment]
Confirmed, thanks !
