### ISSUE TITLE
Cannot login to oss-fuzz.com

### ISSUE THREAD

**Issue by Byron** [google/oss-fuzz#9540]
I am trying to download reproducers for [an issue it detected](https://github.com/Byron/gitoxide/issues/710), but cannot login with my google email address, nor with my GitHub connection.

After selecting my google account, it goes right back to the login page of the oss-fuzz.com. Interestingly, [this chrome-issue](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55557) I can access, which also requires a login.

https://user-images.githubusercontent.com/63622/215875118-bcbe1020-e904-4002-b650-abf6800abe40.mov

In the video above, when the screen turns blank, outside of the recording area I select my google account.

**Comment by jonathanmetzman** [comment]
Are you selecting byronimo@gmail.com ?
I assume you are firefox here? Or is it some other browser?

**Comment by jonathanmetzman** [comment]
This most definitely is a bug but it's already been reported: https://github.com/google/clusterfuzz/issues/2818
Unfortunately, I don't think anyone on the clusterfuzz team has a mac.
I'm going to close this since there's another bug tracking this problem.
