### ISSUE TITLE
tensorflow build issues: ASAN builds seems to not being build but no build issues are reported

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#9552]
The tensorflow is reported as being succesfully built on: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#tensorflow

However, when I go through the logs, I don't see any ASAN reports:
https://console.cloud.google.com/storage/browser/tensorflow-logs.clusterfuzz-external.appspot.com/libFuzzer_tensorflow_decode_bmp_fuzz?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

OSS-Fuzz.com also reports no stats on ASAN builds: https://oss-fuzz.com/fuzzer-stats?group_by=by-fuzzer&date_start=2023-01-25&date_end=2023-01-31&fuzzer=libFuzzer&job=libfuzzer_asan_tensorflow&project=tensorflow

UBSAN builds are fine though: https://oss-fuzz.com/fuzzer-stats?group_by=by-fuzzer&date_start=2023-01-25&date_end=2023-01-31&fuzzer=libFuzzer&job=libfuzzer_ubsan_tensorflow&project=tensorflow

I'm not sure how to debug this? Looking through the build logs the ASAN builds are fine.

Am not sure how to debug this? It seems something at runtime goes wrong?

**Comment by DavidKorczynski** [comment]
CC @fcoUnda @learning-to-play

**Comment by DavidKorczynski** [comment]
I recently pushed a coverage build fix https://github.com/google/oss-fuzz/pull/9568 and now the coverage failures are related to missing corpus:
```
Step #5:         /corpus/status_fuzz@CC_FUZZING.FuzzTest.zip.zip, and cannot find /corpus/status_fuzz@CC_FUZZING.FuzzTest.zip.ZIP, period.
Step #5: Failed to unpack the corpus for status_fuzz@CC_FUZZING.FuzzTest. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
Step #5: [/corpus/string_split_fuzz.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/string_split_fuzz.zip or
Step #5:         /corpus/string_split_fuzz.zip.zip, and cannot find /corpus/string_split_fuzz.zip.ZIP, period.
Step #5: Failed to unpack the corpus for string_split_fuzz. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
Step #5: [/corpus/string_split_v2_fuzz.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory 
```
@oliverchang @jonathanmetzman do you clues?

**Comment by oliverchang** [comment]
Thanks for flagging. Looks like our tensorflow bots are running out of disk again. I've bumped them so this should hopefully get resolved soon.

I also filed https://github.com/google/clusterfuzz/issues/2938 to better surface these errors as well.

**Comment by learning-to-play** [comment]
Thank you @oliverchang for resolving the issue.
Thank you @DavidKorczynski for flagging the issue.

**Comment by DavidKorczynski** [comment]
I can confirm we are now seeing ASAN stats uploaded -- thank you!

**Comment by learning-to-play** [comment]
Great, thanks!
