### ISSUE TITLE
Unable to access Reproducer Testcase

### ISSUE THREAD

**Issue by curtisman** [google/oss-fuzz#959]
I am trying to get the reproducer testcase of a restricted issue. (e.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3975)
I am logged in using the Google account that the issued is CC'ed on.
I can read the issue descriptions on bug.chromuum.org

But when I clicked the Detail report linke or the Reproducer Testcase link on oss-fuzz.com, I get the not authorized message.

How do I gain access?

**Comment by Dor1s** [comment]
Could you please copy the error message your are seeing?

**Comment by curtisman** [comment]
You (ChakraCore@microsoft.com) are not authorized to access this page!
For access, please contact the maintainers by filing a new issue on https://github.com/google/oss-fuzz.
If you see this error while trying to download a test case for a bug that you are the owner of, please download it from the test case details page.
Back
Switch account
Logout

**Comment by Dor1s** [comment]
Thanks! I think it's the same issue as #870. I've updated the email in project.yaml, it should start working soon.

**Comment by inferno-chromium** [comment]
Can you try now ? Does it work ?

**Comment by curtisman** [comment]
Yep.  Works now.  Thanks.
