### ISSUE TITLE
spidermonkey always gives "too much recursion" when ASAN_OPTIONS=detect_stack_use_after_return=1

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#961]
spidermonkey hasn't been running properly and always gives:

```
too much recursion
```

(e.g. gs://spidermonkey-logs.clusterfuzz-external.appspot.com/js_fuzzer/asan_spidermonkey/2017-11-06/12:16:16:476059.txt)

as the only output. This seems to only happen when `detect_stack_use_after_return=1` is set in `ASAN_OPTIONS`.

@alex any ideas why?

For now I'll disable this just for spidermonkey, but it would be nice to detect these bugs too.

**Comment by alex** [comment]
Can't say I recognize this one off hand, will dive in tomorrow.

**Comment by alex** [comment]
This appears to be a known issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1057551 :-(

**Comment by oliverchang** [comment]
Let's close this and continue to track this in the bugzilla.
