### ISSUE TITLE
Best practice question: initialize more ?

### ISSUE THREAD

**Issue by bilboed** [google/oss-fuzz#962]
While looking at the performance of our (GStreamer) fuzzing targets, I was wondering something.

Most of our targets work as such:

0. Initialize library once (GStreamer and plugins we want to use), protected by a static variable
1. Setup a pipeline containing the elements to be tested (the actual data-touching codepaths are within those elements).
2. Inject data into pipeline
3. Run pipeline
4. shutdown pipeline (i.e cleans up anything related to data parsing and resets all elements to the same state as when they were created in step 1).
5. unreference pipeline (and recursively unreferencing all elements contained within).

While this works great, we are actually doing again and again some operations which are unrelated to the data being tested (step 1 and 5). The steps that are related to data are steps 2/3/4. This results in wasted cpu time, and wasted analysis of codepaths which we know are data-unrelated.

I was thinking about maybe making something smaller than a pipeline, but:
* This would take more time to develop each target
* And most importantly it wouldn't guarantee reproducing exactly the same testing setup as within those pipelines (which is after all what we want to test, no ? :) )

My question is therefore two fold:
* Is it acceptable to do more than just "library initialization" in step 0 (i.e. only executed once per process) ? In this case creating the testing pipeline in addition to initializing the library.
* Is there a way to do a final "cleanup" (i.e. when libfuzzer exits, cleanup what was initialized/setup statically in step 0).

**Comment by Dor1s** [comment]
> Is it acceptable to do more than just "library initialization" in step 0 (i.e. only executed once per process) ? In this case creating the testing pipeline in addition to initializing the library.

It's preferable to initialize as much stuff as you can on a startup (i.e. only once per process), but that's crucial for all of those objects to be **stateless**. If there is anything stateful, we get at least 2 problems:

1) _parasitic coverage_: the same input can trigger different code paths due to different internal states
2) _non reproducible crashes_: same reason as the one above, but even more painful result, as we'll find bugs but won't be able to reproduce them with a single input

> Is there a way to do a final "cleanup" (i.e. when libfuzzer exits, cleanup what was initialized/setup statically in step 0).

Is it really needed? It's fine to intentionally leak global / static objects that were initialized in step 0. For the objects being created inside of `LLVMFuzzerTestOneInput`, we have to establish a proper deallocation as for any other production code.

**Comment by bilboed** [comment]
> It's preferable to initialize as much stuff as you can on a startup (i.e. only once per process), but that's crucial for all of those objects to be stateless. If there is anything stateful, we get at least 2 problems

Indeed, all that pipeline creation is unrelated to the input. It's essentially creating **a** program which will always be the same.

> Is it really needed? It's fine to intentionally leak global / static objects that were initialized in step 0. For the objects being created inside of LLVMFuzzerTestOneInput, we have to establish a proper deallocation as for any other production code.

Apart from creating the pipeline, anything else that was allocated due to using that pipeline (with or without data) wil be resetted before exiting LLVMFuzzerTestOneInput. GStreamer pipelines (and elements) **should** be re-usable once resetted. If they're not, it's a bug.

Thanks for the info, I'll look into applying this into our targets.

**Comment by Dor1s** [comment]
I believe the question has been answered. Closing this.
