### ISSUE TITLE
using old base-builder 

### ISSUE THREAD

**Issue by 0x34d** [google/oss-fuzz#9628]
Is it possible to use the old `base-builder`  with  `ubuntu:20.04` .

**Comment by jonathanmetzman** [comment]
This question is unclear. You can use an older base-builder but we won't provide any help if something goes wrong. We currently use Ubuntu 20.04. Do you mean Ubuntu 16.04? I don't think that would be a good idea at all.

**Comment by 0x34d** [comment]
> We currently use Ubuntu 20.04

- Oh, my bad I thought `oss-fuzz` usage  `Ubuntu 22.04`

- Well, I was thinking of adding https://github.com/magma/magma/pull/14966 

- It's unable to compile with `clang-15`, I'm thinking of using old `clang-10`, With clang-15 there will be patches all over the place.

 - magma also has a hardcoded dep from `Ubuntu 20.04`

**Comment by jonathanmetzman** [comment]
We do use ubuntu 20.04 so this should work.
This looks like a good project to add.
I think clang-10 is too old to use. We probably used that years ago.
It can't compile with 14 or 15?

**Comment by 0x34d** [comment]
>  It can't compile with 14 or 15?

Yes, there are multiple compiler errors.

Let's see what I can do.
