### ISSUE TITLE
Improvements to spidermonkey interegration

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#964]
Two things noticed in the first batch of bugs:

1) We hit spidermonkey's builtin `crash` function. The `js` binary should be run with `--fuzzing-safe`. Can this be done?

2) Our WASM code relies on having a segfault handler. Can we set `allow_user_segv_handler` to `1`?

**Comment by inferno-chromium** [comment]
Done, lets see how it works out. We can close this once we see things look ok.

**Comment by alex** [comment]
Great, thanks.

**Comment by oliverchang** [comment]
>Our WASM code relies on having a segfault handler. Can we set allow_user_segv_handler to 1?

Does this segfault handler save the original handler (i.e. ASan's) and defer to that in the case of segfaults that it can't handle?

**Comment by alex** [comment]
From skimming the code, I think yes.

On Nov 7, 2017 5:05 PM, "Oliver Chang" <notifications@github.com> wrote:

Our WASM code relies on having a segfault handler. Can we set
allow_user_segv_handler to 1?

Does this segfault handler save the original handler (i.e. ASan's) and
defer to that in the case of segfaults that it can't handle?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/oss-fuzz/issues/964#issuecomment-342638281>, or mute
the thread

**Comment by oliverchang** [comment]
> From skimming the code, I think yes.

Thanks for checking. 

It would be nice to make sure that this is always the case though (we have a unit test in v8 for this: https://cs.chromium.org/chromium/src/v8/test/unittests/wasm/trap-handler-unittest.cc)

**Comment by alex** [comment]
These seem to be working well. Declaring victory.
