### ISSUE TITLE
CIFuzz: allow building against latest OSS-Fuzz changes

### ISSUE THREAD

**Issue by kleisauke** [google/oss-fuzz#9660]
The [`gcr.io/oss-fuzz-base/cifuzz-build-fuzzers`](https://console.cloud.google.com/gcr/images/oss-fuzz-base/global/cifuzz-build-fuzzers) Docker image contains the `/opt/oss-fuzz` directory, which was last updated 8 days ago.

This is causing issues with libvips' CIFuzz integration, the OSS-Fuzz build was fixed with PR https://github.com/google/oss-fuzz/pull/9575, but CIFuzz still operates on the build script prior to that PR. See for example:
https://github.com/libvips/libvips/actions/runs/4106287622/jobs/7145477770#step:4:5693

Perhaps we should move the build script to https://github.com/libvips/libvips instead?

**Comment by jonathanmetzman** [comment]
Something must be broken. Let me investigate. Yeah moving it would prevent this in the future and is in general a good diea.

**Comment by jonathanmetzman** [comment]
https://github.com/google/oss-fuzz/pull/9466 broke us

**Comment by jonathanmetzman** [comment]
Need to land https://github.com/google/oss-fuzz/pull/9595

**Comment by jonathanmetzman** [comment]
Can you tell me if this is fixed please?

**Comment by kleisauke** [comment]
Seems to be fixed now. Thanks!

I'll try to move the build script upstream to prevent this in the future.

**Comment by jonathanmetzman** [comment]
> Seems to be fixed now. Thanks!
> 
> I'll try to move the build script upstream to prevent this in the future.

For the record,  this shouldn't happen, but as I said, upstreaming has some nice benefits (don't need our approval to make fixes)
