### ISSUE TITLE
nDPI: missing centipede and honggfuzz statistics

### ISSUE THREAD

**Issue by IvanNardi** [google/oss-fuzz#9667]
I am not able to see any statistics about centipede and honggfuzz in nDPI project. Everything is fine with afl and libfuzzer and the builds seems ok.

Examples:

Centipede: https://oss-fuzz.com/fuzzer-stats?group_by=by-fuzzer&date_start=2023-02-02&date_end=2023-02-08&fuzzer=centipede&job=centipede_asan_ndpi&project=ndpi
![Screenshot from 2023-02-09 20-05-23](https://user-images.githubusercontent.com/12729895/217912939-ad0cac15-6ec1-49c8-bc1d-f5d8ce5fe1f5.png)

Honggfuzz: https://oss-fuzz.com/fuzzer-stats?group_by=by-fuzzer&date_start=2023-02-02&date_end=2023-02-08&fuzzer=honggfuzz&job=honggfuzz_asan_ndpi&project=ndpi
![Screenshot from 2023-02-09 20-07-00](https://user-images.githubusercontent.com/12729895/217913142-722646f9-1e0e-4cd6-a883-dc2f27d7f257.png)

If you change the time interval, it seems nothing change...
Is that somehow expected?
Are there any issues with these two libraries or is it only a "visualization" problem?
Thanks in advance

**Comment by Alan32Liu** [comment]
Hi @IvanNardi, IIRC, `Centipede` does not have this feature yet.
It is in their TODO list and will be added later.

Not sure about `Honggfuzz`; maybe @oliverchang has more insights.

**Comment by oliverchang** [comment]
CLosing. Honggfuzz has a similar story here in that there are no custom metrics/stats.
