### ISSUE TITLE
Get rid of llvm-10 install that sneaks its way in with centipede

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#9668]
It wastes about 200 MB of space and is bad for cifuzz.

**Comment by jonathanmetzman** [comment]
Dongge can you try to figure out how its getting installed and prevent it? I'd rather do prevention then removing it after the fact.

**Comment by jonathanmetzman** [comment]
Since centipede :heart: bloating our images, I think we should consider using a multistage build where we copy over the resulting centipede binary into base-builder and let centipede go wild in the intermediate image that gets discarded.

**Comment by jonathanmetzman** [comment]
This is low priority work.

**Comment by Alan32Liu** [comment]
I see; let me think about how to insert that intermediate image to build Centipede.
I wonder if this will cause more of the `undefined function/package XXX` issues, but it should be alright.

**Comment by jonathanmetzman** [comment]
> I see; let me think about how to insert that intermediate image to build Centipede. I wonder if this will cause more of the `undefined function/package XXX` issues, but it should be alright.

I'm not entirely sure what the error your talking about is. Do you mean the libc++ issues how `new` is undefined? This should have no impact on that.

**Comment by jonathanmetzman** [comment]
It seems I'm mistaken and that my profiling tool, dive, must have been looking at an old image somehow.
