### ISSUE TITLE
libass build is broken

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#968]
https://oss-fuzz-build-logs.storage.googleapis.com/log-49e2afbd-08cc-42aa-adb2-a7efb4c94131.txt

@wm4, @astiob and @MrSmile - can you take a look

**Comment by behdad** [comment]
cc @dov

**Comment by behdad** [comment]
We should also setup oss-fuzz for fribidi; cc @khaledhosny @behnam

**Comment by dov** [comment]
Ok. Thanks. I think that I found the reason. I was reading the Decomposition field (field #5) into a variable of size 100, which isn't enough for the current Unicode.txt file. Fixed in master of fribidi.
