### ISSUE TITLE
Limit number of inputs in generated corpus

### ISSUE THREAD

**Issue by bstee615** [google/oss-fuzz#9717]
Hello, I want to use OSS-Fuzz to generate a corpus of varied inputs which I will use for dynamic program analysis. I limited the total running time using `-max_total_time`, but I also want to limit the number of generated inputs (the files dumped into the directory I gave to the `--corpus-dir` option) because I want the fuzzers to have roughly similar numbers of inputs. Is there an option I can use to do this?

For example, I'm fuzzing `apache-httpd` and after 1 hour, I generated 200 inputs for `fuzz_addr_parse` and 2000 inputs for `fuzz_url`. I want to stop fuzzing after 1 hour OR after 1000 inputs have been generated, so I end up with 200 inputs for `fuzz_addr_parse` and **1000** inputs for `fuzz_url`.

**Comment by oliverchang** [comment]
Hi, are you asking about our infrastructure in particular, or a way to do limit this locally on your own machine? (I don't know of an easy way to achieve what you want for either). 

One other way you can shrink your inputs (but keep coverage), is do a corpus distillation using `-merge=1` (https://llvm.org/docs/LibFuzzer.html#corpus).

**Comment by bstee615** [comment]
Sorry for the confusion -- I'm asking whether there's a way to do this on my local machine. I ended up implementing it as a bash script [here](https://gist.github.com/bstee615/6d4f09335bf4a572748d227f3bc6aef2).

Thank you for the reference. I am mostly concerned with stopping the process in a timely manner once a sufficient number of inputs has been generated. I'll close this for now since you answered, but please feel free to add any additional info.
