### ISSUE TITLE
fixed crash not updated as such in bugs.chromium.org

### ISSUE THREAD

**Issue by caolanm** [google/oss-fuzz#973]
Open Bug https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3839 points to fixed https://oss-fuzz.com/v2/testcase-detail/5465964796706816 but https://oss-fuzz.com/v2/testcase-detail/5465964796706816 doesn't point to https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3839 ("Issue: None" instead)

oss-fuzz.com reports it as fixed but bugs.chromium.org as open

**Comment by inferno-chromium** [comment]
Ok closed the bug now.

This is weird, we remember seeing this kind of issue very rarely, and deployed a fix some time back (@oliverchang), but looks like hitting it again. if you see this again, please let us know.
