### ISSUE TITLE
Oss-fuzz Reward Program: question about the form

### ISSUE THREAD

**Issue by IvanNardi** [google/oss-fuzz#9748]
While trying to fill in the form for the Oss-fuzz Reward Program (https://docs.google.com/forms/d/e/1FAIpQLSeWm2KhIYunS28v5J2BWnp-TKMhM8MTg7CzdaceIJoheGHipA/viewform) I noticed that in one of the question is stated that:
``` Please make sure that you're primary contact listed in the project.yaml file.```

Does it mean that only the "primay contact" can fill in the form? Not even the people in the "auto_ccs" list?
Thanks

[Not sure where to ask this question...]

**Comment by Alan32Liu** [comment]
Hi @IvanNardi, the form can be submitted by anybody who did the work: It does not have to be the primary contact.

Thanks for bringing this up. We have edited the form accordingly : )

**Comment by IvanNardi** [comment]
@Alan32Liu , thanks for the reply!
