### ISSUE TITLE
Missing stats in go coverage report 

### ISSUE THREAD

**Issue by manunio** [google/oss-fuzz#9766]
Hi, How can we get total coverage details for golang projects from oss-fuzz.com, for example in this report https://storage.googleapis.com/oss-fuzz-coverage/mxj/reports/20230210/linux/index.html#file0 as of now go coverage lists percentage for individual files but does not show details like total of covered or uncovered  for lines, functions or regions. As an alternative if you have access to corpora for the project you can build it locally which in turn generates summary.json file where we can get all needed data, but that makes it hard to verify data between local coverage build and oss-fuzz coverage build. 

```bash
cat build/out/mxj/report/linux/summary.json | jq ' .data | .[] | .totals'
{
  "functions": {
    "count": 151,
    "covered": 139,
    "notcovered": 12,
    "percent": 92.05298013245033
  },
  "lines": {
    "count": 2088,
    "covered": 1631,
    "notcovered": 457,
    "percent": 78.11302681992338
  },
  "regions": {
    "count": 1482,
    "covered": 1089,
    "notcovered": 393,
    "percent": 73.48178137651821
  },
  "instantiations": {
    "count": 0,
    "covered": 0,
    "notcovered": 0,
    "percent": 0
  },
  "branches": {
    "count": 0,
    "covered": 0,
    "notcovered": 0,
    "percent": 0
  }
}

```

**Comment by oliverchang** [comment]
Hi, a summary.json is available at https://storage.googleapis.com/oss-fuzz-coverage/mxj/reports/20230210/linux/summary.json. This should exist for all integrated projects. Does that work for you?
