### ISSUE TITLE
libreoffice build broken

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#978]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

Step #3: Patch FAILED: /src/libreoffice/external/harfbuzz/harfbuzz-rtti.patch
Step #3: make[1]: *** [/work/workdir/UnpackedTarball/harfbuzz.done] Error 1
Step #3: /src/libreoffice/solenv/gbuild/UnpackedTarball.mk:172: recipe for target '/work/workdir/UnpackedTarball/harfbuzz.done' failed
Step #3: make[1]: *** Waiting for unfinished jobs....
Step #3: 3 warnings generated.
Step #3: make: *** [Library_canvastools] Error 2
Step #3: Makefile:164: recipe for target 'Library_canvastools' failed
Finished Step #3
ERROR
ERROR: build step "gcr.io/oss-fuzz/libreoffice" failed: exit status 2

@caolanm - can you please take a look.

**Comment by caolanm** [comment]
I fixed the error shown in the logs with https://cgit.freedesktop.org/libreoffice/core/commit/?id=5ba0b8f98f874390aa839311b0164360733ec815 on Friday

The build log references https://cgit.freedesktop.org/libreoffice/core/commit/?id=e2eddd96bc1cd83da02c2d5a36c7a678a8544673 which precedes that

So I think the build log isn't up to date for some reason, the last time this happened was
https://github.com/google/oss-fuzz/issues/877 where the build was timing out, is that happening again in this case ?

**Comment by inferno-chromium** [comment]
Yes looks like that

+ python wait_for_build.py 2a914ffb-ac80-476d-a539-c9eda4f00714
2017-11-11 05:29:07.050239 QUEUED
2017-11-11 05:30:22.235186 WORKING
2017-11-11 11:31:19.874011 TIMEOUT

So, i just increased it to 10 hours, will see if this helps.

**Comment by inferno-chromium** [comment]
Build is fixed now.
