### ISSUE TITLE
wxwidgets build broken

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#980]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

Step #3: Configured wxWidgets 3.1.1 for `x86_64-unknown-linux-gnu'
Step #3: 
Step #3:   Which GUI toolkit should wxWidgets use?                 base only
Step #3:   Should wxWidgets be compiled into single library?       no
Step #3:   Should wxWidgets be linked as a shared library?         no
Step #3:   Should wxWidgets support Unicode?                       yes (using wchar_t)
Step #3:   What level of wxWidgets compatibility should be enabled?
Step #3:                                        wxWidgets 2.8      no
Step #3:                                        wxWidgets 3.0      yes
Step #3:   Which libraries should wxWidgets use?
Step #3:                                        STL                no
Step #3:                                        jpeg               none
Step #3:                                        png                none
Step #3:                                        regex              builtin
Step #3:                                        tiff               none
Step #3:                                        zlib               builtin
Step #3:                                        expat              builtin
Step #3:                                        libmspack          no
Step #3:                                        sdl                no
Step #3: 
Step #3: ++ nproc
Step #3: + make -j32
Step #3: /src/wxwidgets/bk-deps clang -c -o wxregex_regcomp.o -DNDEBUG -D__WX__   -D_FILE_OFFSET_BITS=64 -I/src/wxwidgets/lib/wx/include/base-unicode-static-3.1 -I./include -pthread -Wall -Wundef -D_GNU_SOURCE -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-coverage=trace-pc-guard,trace-cmp  ./src/regex/regcomp.c
Step #3: /src/wxwidgets/bk-deps clang -c -o wxregex_regexec.o -DNDEBUG -D__WX__   -D_FILE_OFFSET_BITS=64 -I/src/wxwidgets/lib/wx/include/base-unicode-static-3.1 -I./include -pthread -Wall -Wundef -D_GNU_SOURCE -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-coverage=trace-pc-guard,trace-cmp  ./src/regex/regexec.c
Step #3: /src/wxwidgets/bk-deps clang -c -o wxregex_regerror.o -DNDEBUG -D__WX__   -D_FILE_OFFSET_BITS=64 -I/src/wxwidgets/lib/wx/include/base-unicode-static-3.1 -I./include -pthread -Wall -Wundef -D_GNU_SOURCE -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-coverage=trace-pc-guard,trace-cmp  ./src/regex/regerror.c
Step #3: /src/wxwidgets/bk-deps clang -c -o wxregex_regfree.o -DNDEBUG -D__WX__   -D_FILE_OFFSET_BITS=64 -I/src/wxwidgets/lib/wx/include/base-unicode-static-3.1 -I./include -pthread -Wall -Wundef -D_GNU_SOURCE -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-coverage=trace-pc-guard,trace-cmp  ./src/regex/regfree.c
Step #3: make: *** No rule to make target 'src/zlib/adler32.c', needed by 'wxzlib_adler32.o'.  Stop.
Step #3: make: *** Waiting for unfinished jobs....
Finished Step #3
ERROR
ERROR: build step "gcr.io/oss-fuzz/wxwidgets" failed: exit status 2

@vadz - can you please take a look.

**Comment by vadz** [comment]
Oops, sorry, I should have thought about updating this myself -- but thanks for letting me know. The fix is in #982, but I wonder how could I have noticed the failures myself? Is there any way to receive notifications about this? TIA!

**Comment by inferno-chromium** [comment]
@vadz - We currently don't have a notification pipeline yet, right now it is manual. So, just looking at https://oss-fuzz-build-logs.storage.googleapis.com/index.html once a week should be good.

**Comment by vadz** [comment]
OK, thanks, will keep an eye on it.

**Comment by inferno-chromium** [comment]
build is fixed.
