### ISSUE TITLE
ffmpeg build broken

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#981]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

Step #3: + PKG_CONFIG_PATH=/src/ffmpeg_deps/lib/pkgconfig
Step #3: + ./configure --cc=clang --cxx=clang++ '--ld=clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-coverage=trace-pc-guard,trace-cmp -stdlib=libc++ -fno-sanitize=vptr -std=c++11' --extra-cflags=-I/src/ffmpeg_deps/include --extra-ldflags=-L/src/ffmpeg_deps/lib --prefix=/src/ffmpeg_deps --pkg-config-flags=--static --libfuzzer=-lFuzzingEngine --optflags=-O1 --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --disable-shared
Step #3: ERROR: x265 not found using pkg-config
Step #3: 
Step #3: If you think configure made a mistake, make sure you are using the latest
Step #3: version from Git.  If the latest version fails, report the problem to the
Step #3: ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Step #3: Include the log file "ffbuild/config.log" produced by configure as this will help
Step #3: solve the problem.
Finished Step #3
ERROR
ERROR: build step "gcr.io/oss-fuzz/ffmpeg" failed: exit status 1

@michaelni - Michael, can you please take a look.

**Comment by michaelni** [comment]
I suspect this is a bug in x265, i think https://patches.videolan.org/patch/18630/ would fix x265. Reference: https://trac.ffmpeg.org/ticket/6830

**Comment by oliverchang** [comment]
Latest build is green.
