### ISSUE TITLE
Fixed bugs not marked as fixed

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#9855]
These bugs:

https://oss-fuzz.com/testcase-detail/6543272207319040
https://oss-fuzz.com/testcase-detail/5173220321132544
https://oss-fuzz.com/testcase-detail/5139901307027456

don't reproduce anymore, and were probably fixed in https://github.com/wolfSSL/wolfssl/pull/6133, which was merged 4 days ago.

**Comment by nwellnhof** [comment]
I also see a few bugs which take unusually long to be marked as fixed.

**Comment by guidovranken** [comment]
Here is a bug where no issue is created for it, despite being 3 days old: https://oss-fuzz.com/testcase-detail/5272339217776640

Both the issues that don't resolve after being fixed and this one have `Pending, refreshes every 5 minutes.`, so it seems something is stuck in a loop.

**Comment by guidovranken** [comment]
> Here is a bug where no issue is created for it, despite being 3 days old: https://oss-fuzz.com/testcase-detail/5272339217776640

Don't know if this just happens for this project or for all of them, but maintainers not getting notified of bugs is rather unfortunate. Hopefully this can get fixed? @jonathanmetzman @oliverchang

**Comment by oliverchang** [comment]
Thanks for flagging. wolfssl has been stuck here because of disk space issues. We'll bump this to unblock it.

**Comment by oliverchang** [comment]
Looks like all of the mentioned bugs have become unstuck. Thanks again for flagging!

**Comment by guidovranken** [comment]
Thanks!
