### ISSUE TITLE
This is incredibly confusing

### ISSUE THREAD

**Issue by rminnich** [google/oss-fuzz#9876]
The usability of all this could use some improvement. I realize it's complex but a 'reproduce this failure' link that leads me to a page of near-incomprehensible instructions is not helping. I'm still not sure what to do. Further, I've taken what it seems to think is the case that causes the failure:
mapfile;  {{ 
and it does not cause a failure. I can't tell what's going on at all.

The instructions mention 3 fuzzers but the error message presents way more:
helper.py build_fuzzers: error: argument --sanitizer: invalid choice: 'undefine' (choose from 'address', 'none', 'memory', 'undefined', 'thread', 'coverage', 'introspector', 'hwaddress')

what's the answer here?

Could you maybe make a docker container with everything ready to run, and then when you ask me to reproduce a case, you send me the exact docker command to run so I can try it? I page of "lots of assembly required" instructions is not helpful to someone, like me, who has no idea how any of this works, or how it is put together.

thanks

**Comment by rminnich** [comment]
Yeah I'm trying to work through how to repro and none of it makes any sense, I could use some help.

I'm here:
18590  [2023-03-06 21:20:58 +0000] python infra/helper.py build_fuzzers --sanitizer address --architecture x86_64 u-root
18591  [2023-03-06 21:24:25 +0000] python infra/helper.py build_fuzzers --sanitizer memory --architecture x86_64 u-root
18594  [2023-03-06 21:28:27 +0000] python infra/helper.py build_fuzzers --sanitizer undefined --architecture x86_64 u-root

and that worked.

This issue:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54273

**Comment by jiridanek** [comment]
@rminnich I don't have permissions to see u-boot fuzzing results, so I'm going to try to do some hand waving.

I'd try to first identify which fuzzer failed. For example, there is https://github.com/u-root/u-root/blob/main/pkg/boot/netboot/ipxe/ipxe_test.go and IIUC 3 other fuzz tests in the project, so, which one of them is the failing one?

Then, I'd try to download the reproducing input. On my project (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=11794), there is link like this (last line)

> Detailed report: https://oss-fuzz.com/testcase?key=0123456789
> 
> Project: qpid-proton
> Fuzzer: libFuzzer_qpid-proton_fuzz-connection-driver
> Fuzz target binary: fuzz-connection-driver
> Job Type: libfuzzer_msan_qpid-proton
> Platform Id: linux
> 
> Crash Type: Timeout (exceeds 25 secs)
> Crash Address: 
> Crash State:
>   qpid-proton_fuzz-connection-driver
>   
> Sanitizer: memory (MSAN)
> 
> Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=0123456789

Also, consider going to the "Detailed report" link and downloading the Build

![image](https://user-images.githubusercontent.com/442720/223501756-0b01016d-082e-4434-9353-6c1ce03771da.png)

Now, in case of my project, qpid-proton, I am able to reproduce on a Linux machine by running the binary from the Build archive with the testcase input as a parameter. No docker required.

And, by looking at the source code of the fuzzer (seeing what it does with the input), you should be able to start figuring out what you need to reproduce this.

IMHO reproducing crash with docker is a blind alley. I need to reproduce crash in my IDE with current git tip I just compiled, not in some isolated Docker...

**Comment by oliverchang** [comment]
> Yeah I'm trying to work through how to repro and none of it makes any sense, I could use some help.
> 
> I'm here: 18590 [2023-03-06 21:20:58 +0000] python infra/helper.py build_fuzzers --sanitizer address --architecture x86_64 u-root 18591 [2023-03-06 21:24:25 +0000] python infra/helper.py build_fuzzers --sanitizer memory --architecture x86_64 u-root 18594 [2023-03-06 21:28:27 +0000] python infra/helper.py build_fuzzers --sanitizer undefined --architecture x86_64 u-root
> 
> and that worked.
> 
> This issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54273

Hey @rminnich, if I'm understanding you comment correctly -- did you end up getting this working?

**Comment by oliverchang** [comment]
Closing as there has been no response. Thanks!
