### ISSUE TITLE
Getting stacktraces of all threads

### ISSUE THREAD

**Issue by bilboed** [google/oss-fuzz#989]
When using the address sanitizer (didn't check the others), on failures it would be great to have the stacktraces of all threads (instead of just the thread that caused the failure).

**Comment by kcc** [comment]
That's not a question to oss-fuzz, but to AddressSanitizer, right?
Closing this bug here, but feel free to open another one at https://github.com/google/sanitizers/issues/ 
You are the first to ask for such feature in 6 years, so please explain why you need it.

**Comment by bilboed** [comment]
Opened a bug over there. https://github.com/google/sanitizers/issues/881

Slightly giggling at the fact that I'm the first one to ask this though :)

**Comment by bilboed** [comment]
Based on the reply from downstream bug, that means we won't be able to have automatic all-thread-stacktrace reporting in oss-fuzz ? It's a shame, because for race-related failures which are hard to reproduce but do get triggered on the google servers, we won't be able to have as much info as we can.

**Comment by kcc** [comment]
Could you give an example of such bug? 
Maybe we need to drag tsan into the game?
