### ISSUE TITLE
ClusterFuzzLite batch fuzzing does not upload corpus artifact

### ISSUE THREAD

**Issue by tatsuhiro-t** [google/oss-fuzz#9893]
I am using ClusterFuzzLite for a couple of my projects.  Since Feburary 10 (GMT +9), it stops uploading corpus as an artifact.

This is the last working run: https://github.com/ngtcp2/ngtcp2/actions/runs/4134300134
we can see the log message
```
/github/workspace/build-out/decode_frame -timeout=25 -rss_limit_mb=2560 -len_control=0 -artifact_prefix=/tmp/tmpjgabgqm8/ -max_total_time=1800 -print_final_stats=1 /github/workspace/cifuzz-corpus/decode_frame >fuzz-1.log 2>&1
2023-02-09 13:40:24,189 - root - INFO - Uploading corpus in /github/workspace/cifuzz-corpus/decode_frame for decode_frame.
2023-02-09 13:40:25,033 - root - INFO - Done uploading corpus.
```

And artifacts are created correctly.

The first non-working run is https://github.com/ngtcp2/ngtcp2/actions/runs/4137259021
"Uploading corpus in ..." is missing in the log:
```
/github/workspace/build-out/decode_frame -timeout=25 -rss_limit_mb=2560 -len_control=0 -artifact_prefix=/tmp/tmpp0fplmb0/ -max_total_time=1800 -print_final_stats=1 /github/workspace/cifuzz-corpus/decode_frame >fuzz-1.log 2>&1
2023-02-09 19:25:40,051 - root - INFO - Done uploading corpus.
```

And no artifacts are created.

**Comment by jonathanmetzman** [comment]
Ouch. Let me take a look

**Comment by jonathanmetzman** [comment]
Thanks for pointing out the date. I think it very likely has something to do with https://github.com/google/oss-fuzz/pull/9595

**Comment by jonathanmetzman** [comment]
I think I fixed this: https://github.com/jonathanmetzman/systemd/actions/runs/4438940963?pr=5

**Comment by jonathanmetzman** [comment]
Please reopen if I didn't and sorry for the delay in fixing this.
