### ISSUE TITLE
Spidermonkey Build is Broken

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#990]
https://oss-fuzz-build-logs.storage.googleapis.com/log-5e130e64-f73d-4990-a160-1190745913b3.txt

I believe these are the relevant lines:

Step #3: x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPSUTIL_VERSION=311 -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o
...
Step #3: Reexecuting in the virtualenv
Step #3: checking for the target C++ compiler... /usr/local/bin/clang++
Step #3: DEBUG: <truncated - see config.log for full output>
...
Step #3: DEBUG: Its error output was:
Step #3: DEBUG: | /tmp/conftest.wpOGzI.cpp:83:10: fatal error: 'cstddef' file not found
Step #3: DEBUG: | #include <cstddef>
Step #3: DEBUG: |          ^~~~~~~~~
Step #3: DEBUG: | 1 error generated.
Step #3: ERROR: Command `/usr/local/bin/clang++ -E /tmp/conftest.wpOGzI.cpp` failed with exit status 1

**Comment by oliverchang** [comment]
@alex can you please take a look?

**Comment by alex** [comment]
When was the build? This looks potentially the same as https://bugzilla.mozilla.org/show_bug.cgi?id=1417745, but that was reverted like 10 hours ago.

**Comment by jonathanmetzman** [comment]
11/15/2017, 9:19:19 PM, so before the revert.

**Comment by alex** [comment]
👍  I'd expect a rebuild to resolve it then.

**Comment by oliverchang** [comment]
Looks like it's no longer failing.
