### ISSUE TITLE
grpc build is broken

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#991]
https://oss-fuzz-build-logs.storage.googleapis.com/log-f3afc45e-5495-481c-94fa-50b636329716.txt

These appear to be the relevant lines:
Step #3: test/core/http/request_fuzzer.cc:36:59: error: use of undeclared identifier 'nullptr'
Step #3:   GRPC_ERROR_UNREF(grpc_http_parser_parse(&parser, slice, nullptr));
Step #3:                                                           ^
Step #3: 2 warnings and 1 error generated.
Finished Step #3
ERROR
ERROR: build step "gcr.io/oss-fuzz/grpc" failed: exit status 1

[request_fuzzer.cc](https://github.com/grpc/grpc/blob/master/test/core/http/request_fuzzer.cc) does not include `<cstddef>`, which is where `nullptr` is declared. Maybe this needs to be explicitly included.

**Comment by inferno-chromium** [comment]
@matt-kwong - can you please take a look.
