### ISSUE TITLE
ipykernel: Introspector build failure/timeout

### ISSUE THREAD

**Issue by jesslatimer** [google/oss-fuzz#9914]
The introspector build for ipykernel fails every [so often with `TIMEOUT ERROR: context deadline exceeded`](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#ipykernel)

**Comment by jonathanmetzman** [comment]
compilation is literally taking almost 20 hours(!!!) when this happens

**Comment by oliverchang** [comment]
@DavidKorczynski are there any fixes possible here? OR should we just disable this one?

**Comment by DavidKorczynski** [comment]
I think we can solve this -- am in the process of debugging this and will update here shortly.

**Comment by evverx** [comment]
@DavidKorczynski I noticed that `scapy` is built successfully with FI now. Could it be that https://github.com/google/oss-fuzz/commit/4f108126571416fb175b5a5933d0d87085500d01 fixed it too? According to https://github.com/AdaLogics/PyCG/commit/507c89d6afef9048f1c20c5b02a3cbe614659dc9#r106590415
> the converging will not happen in the usual manner

Could you expand on that a bit?

**Comment by evverx** [comment]
I played with it a bit and it seems it works in practice. Admittedly I use it to look for large uncovered chunks and maybe if I needed more granular results it would be a different story but I haven't reached that point yet :-)

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski I noticed that `scapy` is built successfully with FI now. Could it be that [4f10812](https://github.com/google/oss-fuzz/commit/4f108126571416fb175b5a5933d0d87085500d01) fixed it too? According to [AdaLogics/PyCG@507c89d#r106590415](https://github.com/AdaLogics/PyCG/commit/507c89d6afef9048f1c20c5b02a3cbe614659dc9#r106590415)
> 
> > the converging will not happen in the usual manner
> 
> Could you expand on that a bit?

Sorry for missing this @evverx -- I will expand shortly!

**Comment by evverx** [comment]
@DavidKorczynski no problem. I was just wondering whether that change could affect my local stuff and I haven't noticed any significant coverage drops. It's just that `scapy` stopped timing out and it drew my attention. Its report contains "The number of runtime covered functions are larger than the number of reachable functions" though and my guess would be that it has something to do with various meta-programming techniques used there but I have to admit I haven't taken a close look yet. I'll open a separate issue if I've gotten round to it.

**Comment by DavidKorczynski** [comment]
Closing as ipykernel has had no timeouts in a while
