### ISSUE TITLE
augeas build is broken

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#992]
https://oss-fuzz-build-logs.storage.googleapis.com/log-dc7cec28-0ea8-4884-9ad5-a51134975d91.txt

These appear to be the relevant lines: 
Step #18: lexer.l:21:10: fatal error: 'parser.h' file not found
Step #18: #include "parser.h"
...
Step #18: 1 error generated.
Step #18: Makefile:1558: recipe for target 'liblexer_la-lexer.lo' failed
Step #18: make[3]: *** [liblexer_la-lexer.lo] Error 1

**Comment by inferno-chromium** [comment]
@qiankehan - can you please take a look.
