### ISSUE TITLE
[flac] Why does my coverage decrease?

### ISSUE THREAD

**Issue by ktmf01** [google/oss-fuzz#9928]
Hi,

I've recently added a fuzzer (fuzzer_tool_flac) that seems to be blocked, but I am unable to diagnose why. One particular symptom is that coverage seems to randomly vanish for no reason.

I haven't changed anything recently, last change (to code that doesn't even compile with the fuzzer) was March 11th. The last relevant change was March 9th: https://github.com/xiph/flac/commits/master

Relevant line coverage for [March 12th](https://storage.googleapis.com/oss-fuzz-coverage/flac/reports/20230312/linux/src/flac/src/flac/report.html) was 20.18%
Relevant line coverage for [March 13th](https://storage.googleapis.com/oss-fuzz-coverage/flac/reports/20230313/linux/src/flac/src/flac/report.html) was 20.67%
Relevant line coverage for [March 14th](https://storage.googleapis.com/oss-fuzz-coverage/flac/reports/20230314/linux/src/flac/src/flac/report.html) was 20.67%
Relevant line coverage for [March 15th](https://storage.googleapis.com/oss-fuzz-coverage/flac/reports/20230315/linux/src/flac/src/flac/report.html) was 13.62%

Could it be that somehow corpus files are removed that shouldn't be removed on clean-up?

**Comment by DavidKorczynski** [comment]
Hmm. Indeed the `fuzzer_tool_flac` fuzzer has better coverage 12th March in comparison to 16th March (fewer reds --> better coverage).

On the 12th March, 2811 callsites are "red": https://storage.googleapis.com/oss-fuzz-introspector/flac/inspector-report/20230312/fuzz_report.html#Fuzzer:-fuzzer_tool_flac
![12th-march](https://user-images.githubusercontent.com/657617/225762387-283ac0ea-36d1-4825-bffe-1aa5e3d45186.png)

On the 16th March, 2924 callsites are "red": https://storage.googleapis.com/oss-fuzz-introspector/flac/inspector-report/20230316/fuzz_report.html#Fuzzer:-fuzzer_tool_flac
![16th-march](https://user-images.githubusercontent.com/657617/225762346-d8293fe1-5e22-4f2a-8d12-2861f49befe5.png)

Is there potentially something in the code that the fuzzer targets that is stateful or non-deterministic? When the code coverage is collected it runs the fuzzer on the corpus files at once and is the behaviour of the target code going to be identical independently of the ordering in which the seeds are run?

**Comment by ktmf01** [comment]
Thanks for your thorough search! I have been searching for a while but haven't checked statefulness. I will dive into this, many thanks for the pointer.

**Comment by ktmf01** [comment]
> The missing default setting of `optional_values.show_version` and the early return of the conditional `if (option_values.show_version)` is likely the cause of the code coverage difference, and will likely also cause disruption to the corpus minimisation process.

This definitely does the trick. Thanks!

**Comment by DavidKorczynski** [comment]
> This definitely does the trick. Thanks!

Awesome @ktmf01 !

For reference, I think this is something we could flag automatically -- that a certain seed has different coverage in different runs. I wonder if it would be nice to have some form of statefullness detector. Maybe I'll try to check if more projects have volatile coverage.
