### ISSUE TITLE
Upgrade install_go.sh to use Go 1.20

### ISSUE THREAD

**Issue by clfs** [google/oss-fuzz#9949]
`install_go.sh` says it downloads and installs the latest stable Go, but it uses Go 1.19 instead.

https://github.com/google/oss-fuzz/blob/c9e3a82e3dc1c7142bbff53cdf1eb6dce07d776d/infra/base-images/base-runner/install_go.sh#L22-L25

We should either use Go 1.20 (the latest stable Go at time of writing) or remove the misleading comment.

**Comment by DavidKorczynski** [comment]
> remove the misleading comment.

For now this is probably the easiest.

**Comment by joestringer** [comment]
Can we reopen this? Cilium now relies on Go 1.20, so oss-fuzz coverage is currently non-functional pending a Go version bump.
