### ISSUE TITLE
monorail deletes comments

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#998]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4272

The project maintainer tried to comment on issues, but the comments are deleted almost instantly.

**Comment by oliverchang** [comment]
This is probably overaggressive spam filtering. There's https://bugs.chromium.org/p/monorail/issues/detail?id=2727 to track it on monorail side but unfortunately hasn't been much progress there yet.

**Comment by inferno-chromium** [comment]
Fixed now.
