### ISSUE TITLE
New project cachetools not appearing in introspector reports

### ISSUE THREAD

**Issue by sg3-141-592** [google/oss-fuzz#9994]
A newly integrated project cachetools #9957 hasn't been appearing in the [introspector reports](https://oss-fuzz-introspector.storage.googleapis.com/index.html). I can see it building successfully in the [OSS-Fuzz build status](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#cachetools).

I also can't see any mention of it on [https://oss-fuzz.com/](https://oss-fuzz.com/).

**Comment by DavidKorczynski** [comment]
The coverage build is failing -- it looks like it has some issues getting the corpus. Is this a quota issue  @jonathanmetzman @oliverchang ?

**Comment by oliverchang** [comment]
Looks like this is all working now. Closing!
